### ISSUE TITLE
Adding the branch and coding convention to wiki

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#10]
The styling specially for branches are not specified in documentation.

**Comment by loumalouomega** [comment]
@pooyan-dadvand This issue is 15 days old, I don't want to look cranky, but maybe to avoid the accumulation of too many issues is a good idea to close this one.

**Comment by pooyan-dadvand** [comment]
I have added a [wiki page](https://github.com/KratosMultiphysics/Kratos/wiki/Style-Guide) (improvable) for coding style including the workflow
