### ISSUE TITLE
Broken mesh motion in trilinos_application

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#100]
The mesh motion solver is not working in trilinos_application.

**Comment by msandre** [comment]
The problem appears to be with using variables local to one application in another application. In this case it is the new MESH_* variables in the ALEapplication being used in trilinos_application. They are created twice, once in ALEapplication and once in trilinos_application. The ALEapplication registers its variables but accessing the variables in the trilinos_application retrieves the unregistered variable which causes lookup errors. I suggest removing all code from the ALEapplication that is compiled into trilinos_application and accessing the non-local variables and elements through the kratos components in the core.

For variables this looks like:

typedef Variable<array_1d<double, 3> > VariableWithComponentsType;
typedef VariableComponent<VectorComponentAdaptor<array_1d<double, 3> > > VariableComponentType;

const VariableWithComponentsType &rMESH_DISPLACEMENT = KratosComponents<VariableWithComponentsType>::Get("MESH_DISPLACEMENT");
const VariableComponentType &rMESH_DISPLACEMENT_X = KratosComponents<VariableComponentType>::Get("MESH_DISPLACEMENT");

For creating the mesh motion elements it is something like:

const Element * pStructuralMeshMovingElement;
    if (DomainSize == 2)
      pStructuralMeshMovingElement = &KratosComponents<Element>::Get("StructuralMeshMovingElement2D3N");
    else
      pStructuralMeshMovingElement = &KratosComponents<Element>::Get("StructuralMeshMovingElement3D4N");

for(ModelPart::ElementsContainerType::iterator it = BaseType::GetModelPart().ElementsBegin();
	it != BaseType::GetModelPart().ElementsEnd(); ++it)
    {
      MeshElems.push_back( pStructuralMeshMovingElement->Create(
          it->Id(),
          it->pGetGeometry(),
          it->pGetProperties()) );
    }

For this we would also need to add the Create() function in the mesh moving element since this create is not implemented yet.

**Comment by jcotela** [comment]
We have had similar problems with the FluidDynamicsApplication in the past and I believe that what @msandre is suggesting is the best possible solution. However, in the case you are mentioning, there was an additional complication because the MeshMoving elements could work with different underlying geometries (otherwise we would have suggested you to adopt this change already). I think you are already taking care of that.

In any case, I just wanted to say I back the suggestion making the ALE and trilinos applications independent.

**Comment by msandre** [comment]
@jcotela the additional complication could be solved by also checking the underlying geometry, only this results in a lot of if statements. If we want to allow for mixed element geometries in the model part we would also need to check each time in the for loop. Maybe we can generate a map in the initialization of the strategy which maps geometry types to mesh motion elements and call this to get the correct element?

**Comment by jcotela** [comment]
As an idea, Riccardo recently added Create() methods that take an actual geometry (not a list of nodes) to the Element and Condition base classes. I would suggest implementing these for the ALE elements and using them here. This would ensure that the ALE element has the same geometry type as the original, which may be enough in this case.

**Comment by msandre** [comment]
Great, tomorrow we're busy with exams but it should get done the next day.

**Comment by msandre** [comment]
The above changes have been added along with 2d tests in ALEapplication/tests in 6cdce50ed4b3601e65d295483c2aea43e769ff33. For verification of tests, I decided to compare results at 2 selected points generated by point_output_process.py instead of by node ids using from_json_check_result_process.py because of issues with node renumbering in mpi partitioning. This allows the same reference data to be used for verification of serial and parallel code.

To run all serial tests (so far there is just one):

python3 test_ALEApplication.py

To run tests individually, e.g.:

python3 test_structural_mesh_motion_2d.py

For mpi test:

mpiexec -n <np> python3 mpi_test_structural_mesh_motion_2d.py

To write post-processing results files uncomment lines with self.gid_output in test_MainKratos.py and run test.

There are also two new python wrappers for the trilinos/serial navier_stokes_solver_vmsmonolithic.py. These behave the same as the fluid solvers but also encapsulate a mesh motion solver.

@AndreasWinterstein can you checkout & test the above commit?

**Comment by AndreasWinterstein** [comment]
Hi Mike,

the tests are working and the implementation is also fine for me. I will add some more tests this evening and/or tomorrow in order to test the Laplacian version, too. Just one more question. Why are you adding the ale_trilinos_navier_stokes_solver_vmsmonolithic in the project parameter files?

**Comment by msandre** [comment]
Ok thanks, then let's do the pull request tomorrow so we can close this issue.

The ale_navier_stokes_solver_vmsmonolithic / ale_trilinos_navier_stokes_solver_vmsmonolithic were added to provide a single solver interface for ALE+CFD. It is a simple python wrapper to the regular navier_stokes_solver_vmsmonolithic. Some reasons for this are:

1. ALE solver type can be changed in the json parameters without changing MainKratos.py. This is the reason I introduced it now so that we can use a single test_MainKratos.py for all tests instead of a different one for each solver type.
2. ALE solver functions, which are closely related to the corresponding fluid solver functions, such as AddDofs() and Solve() are encapsulated with the fluid solver into a single solver instance. This reduces the differences between MainKratos.py for pure CFD and MainKratos.py for CFD+ALE. For prescribed boundary motion, they could actually be identical, only the json needs to be modified.

**Comment by RiccardoRossi** [comment]
Hi Mike,

is this issue solved? if so please close it

**Comment by msandre** [comment]
I just added PR #199 . We'll close this as soon as it is merged.

**Comment by AndreasWinterstein** [comment]
I am currently doing some more adjustments in the ALEapplication. I will open a new issue as soon as they are ready.
