### ISSUE TITLE
CoSim important FSI tests are disabled

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#10007]
@KratosMultiphysics/cosimulation the Mok-FSI tests are currently disabled (see [here](https://github.com/KratosMultiphysics/Kratos/commit/42b62c1ff7dd709777de2052ed221338190f46f7) and [here](https://github.com/KratosMultiphysics/Kratos/commit/0b853675c8e5e360f629c7511a4e923de19e6dca))
https://github.com/KratosMultiphysics/Kratos/blob/b9769b6578ba5cd9472e4834ad6cf4c193bc9501/applications/CoSimulationApplication/tests/test_CoSimulationApplication.py#L81-L83

@roigcarlo according to the history you made these changes? Those tests are probably the most important tests in the app, why did you disable them?

**Comment by roigcarlo** [comment]
Those were disabled when we set nightly as the default suit because they were faulty (they were failing 50% of times they were executed) , they can be re-enable as long as they are fixed.

**Comment by philbucher** [comment]
Ah I thought that was not merged because of failing tests 😅

In any case, out of all tests in Kratos those two were the ones I trusted most
If they are failing then I am a bit scared, as they test the entire workflow

@KratosMultiphysics/cosimulation would someone habe time to run them to see if they fail?

**Comment by mpentek** [comment]
@roigcarlo it is pretty concerning it these were turned off
@philbucher I will try to take a look asap @mtnzguillermo this might effect you as well

**Comment by mpentek** [comment]
Hopefully fixed with #10108.
