### ISSUE TITLE
[StructuralMechanicsApplication] Harmonic analysis compatibility with transient loads

### ISSUE THREAD

**Issue by danielandresarcones** [KratosMultiphysics/Kratos#10002]
**Description**
I am trying to use the `structural_mechanics_harmonic_analysis.py` in a CoSimulation framework to collect which eigenmodes are excited more prominently at every timestep. In this set-up, the harmonic analysis solver receives a different load configuration in every timestep, creating a transient load configuration. Can this case be computed using such a configuration in any way? I have modified the files to have access to the modal weights, but from my trials and the code of the strategy, it seems that the force vector is read only in the initialization of the simulation. 

**Scope**
- StructuralMechanicsApplication

**Comment by philbucher** [comment]
@qaumann as the author should know :)

**Comment by qaumann** [comment]
@danielandresarcones Sorry for the delayed response, I am currently a little bit out of the loop.

You are right, the RHS of the equation system is only initialized once and not updated during the simulation as a transient use case was not planned initially. However, I think it should be no problem to re-initialize the RHS in every solution step, but this must be done in the C++ layer.

If you have access to the mode shapes in Python, you could also perform the matrix vector products in Python, where I think you have access to the updated force vector, right? As the eigensolution does not change between time steps, this could be an efficient approach to solve your problem.

**Comment by danielandresarcones** [comment]
Thanks for the answer, that is what I thought, I will probably follow with the Python option. If I have time, I may update the C++ layer.
