### ISSUE TITLE
Import Material Parameter in .h file (CONSTITUTIVE LAW)

### ISSUE THREAD

**Issue by UmarSaeedMalik** [KratosMultiphysics/Kratos#10017]
Hello, 

I am trying to write a constitutive law. To make a computation, i want to read the size of a vector of material parameter that I input in my .JSON material file. To simply put it, i want to import the value of a material parameter, e.g like YOUNGS_MODULUS or a vector of values maybe, like the relaxation times of multiple branches of a generalized maxwell law. After importing this vector, i can find its size and use it. All this has to be done in the .h file.

To simplify, for example, can you tell me, in my .h file, how to read and store the double value of YOUNG_MODULUS?

I understand that this is done in the .cpp file by passing the Parameters structure in the function and then using rValues.GetMaterialProperties inside the function, but i can't understand how to read it without a function and in my .h file.

Your help would be much appreciated.

Best regards

**Comment by loumalouomega** [comment]
I don't know if i understand the question, but there are plenty of CL where you can see how the young modulus is imported:

https://github.com/KratosMultiphysics/Kratos/blob/8ab035aa0754eacbde98ed679c05d24385d5dcab/applications/StructuralMechanicsApplication/custom_constitutive/elastic_isotropic_3d.cpp#L353

FYI @AlejandroCornejo

**Comment by UmarSaeedMalik** [comment]
> I don't know if i understand the question, but there are plenty of CL where you can see how the young modulus is imported:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/8ab035aa0754eacbde98ed679c05d24385d5dcab/applications/StructuralMechanicsApplication/custom_constitutive/elastic_isotropic_3d.cpp#L353
> 
> FYI @AlejandroCornejo

Thank you for your reply.
This is exactly what i need, but see, this is inside the cpp file and inside the function, and just before this line, we have:     

const Properties& r_material_properties = rValues.GetMaterialProperties();

When I paste the same in my .h file, it says that rValues is undeclared. Thats because in the cpp file, we pass the 'Parameters' as rValues in the function. But here the code doesn't know what is rValues, so I don't know how to address this.

When I directly write:
const Properties& material_props = Parameters.GetMaterialProperties();
It tells me that 
"'Kratos::ConstitutiveLaw::Parameters': illegal use of this type as an expression"

I am sure its an easy thing, but since I am still learning, i can't do it.

**Comment by loumalouomega** [comment]
> > I don't know if i understand the question, but there are plenty of CL where you can see how the young modulus is imported:
> > https://github.com/KratosMultiphysics/Kratos/blob/8ab035aa0754eacbde98ed679c05d24385d5dcab/applications/StructuralMechanicsApplication/custom_constitutive/elastic_isotropic_3d.cpp#L353
> > 
> > FYI @AlejandroCornejo
> 
> Thank you for your reply. This is exactly what i need, but see, this is inside the cpp file and inside the function, and just before this line, we have:
> 
> const Properties& r_material_properties = rValues.GetMaterialProperties();
> 
> When I paste the same in my .h file, it says that rValues is undeclared. Thats because in the cpp file, we pass the 'Parameters' as rValues in the function. But here the code doesn't know what is rValues, so I don't know how to address this.
> 
> When I directly write: const Properties& material_props = Parameters.GetMaterialProperties(); It tells me that "'Kratos::ConstitutiveLaw::Parameters': illegal use of this type as an expression"
> 
> I am sure its an easy thing, but since I am still learning, i can't do it.

There is no difference between declare things in header or source file, except for compilation times (that's why usually the code is in source files except generic templated classes). I recommend to take a look a the whole implementation of the isotropic CL and try to understand how it works as a whole.
