### ISSUE TITLE
Compiling Kratos with pypy3

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#10019]
Compiling Kratos with `pypy3` yields an error in the Python exportation of the logger. The issue is located in `add_logger_to_python.cpp`. Specifically in https://github.com/KratosMultiphysics/Kratos/blob/96cc60fd5784600c5a6068e23b42aa9a9c8a3d5a/kratos/python/add_logger_to_python.cpp#L77

Seems to be something related to the pybind types.

To be studied together with @roigcarlo .

**Comment by rubenzorrilla** [comment]
@roigcarlo I can't remember whether we fixed this one or not.

**Comment by roigcarlo** [comment]
No that I remember
