### ISSUE TITLE
[CI] CentOS failing

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10023]
Core and FluidDynamics fail on CentOS in the CI. Some problem with the python version it says. Any ideas what's wrong?

**Comment by rubenzorrilla** [comment]
It's due to the fstrings. Current CI runs with Python 3.5. Kratos supports version 3.6 on. @roigcarlo will update the Docker to current standards soon. In the meantime, @KratosMultiphysics/technical-committee decided to disable CentOS CI as a requirement to prevent blocking current developments.

**Comment by roigcarlo** [comment]
Just to add that fix is ready, we are pending on approval and testing the new images (see #10003)

**Comment by matekelemen** [comment]
btw, how's C++17 gonna work on CentOS?

**Comment by roigcarlo** [comment]
We updated the compiler to gcc 8 so it will work the same, the title is misleading because I started to work in the branch before deciding to move to C++17, but the env will remain valid.
