### ISSUE TITLE
[GeoMechanicsApplication] create dynamic newmark scheme with rayleigh damping in GeoMechanicsApplication

### ISSUE THREAD

**Issue by anoordam** [KratosMultiphysics/Kratos#10020]
create dynamic newmark scheme with rayleigh damping in GeoMechanicsApplication

**Comment by Vahid-Galavi** [comment]
It is already available. For what element do you need that?

**Comment by anoordam** [comment]
Ah, I did see rayleigh damping for the structural elements. But i want to use it for the whole system, I did not see it in the newmark solver.

**Comment by Vahid-Galavi** [comment]
The Rayleigh damping is added in the elements. Check the base elements in GeoMechanicsApp.

**Comment by Vahid-Galavi** [comment]
I am not sure if it's a good idea to include Rayleigh damping in the Newmark scheme as the Rayleigh damping depends on the material parameters (stiffness and mass) which are different in elements.
