### ISSUE TITLE
Niche error in function_parser_utility

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/Kratos#10041]
**Description**
This is not really problematic, I'm reporting mostly so its documented. I don't believe anyone is afected by this.

In function `CheckThereIsNotx` in here:
https://github.com/KratosMultiphysics/Kratos/blob/fc2e6d1b32d98dbbedb06b244eb81deedd1ad30b/kratos/utilities/function_parser_utility.cpp#L28-L46

It ensures that functions such as `exp` are not confused with an `x` as a variable name. Tinyexpr also supports hexadecimal number so `f(t) = 0x13 + t` would still be misparsed as a function of x.

**Scope**
Parsing of functions in json

**To Reproduce**
With some process that allows functions, write something like `0x100 + t` and see how this function is labeled as depending on `x` by `CheckThereIsNotx`.

**Expected behavior**
Should not be parsed as depending on `x`.

**Environment**
I haven't reproduced this issue, I've reached this conclusion with static analysis. Note that I have confirmed that tinyexpr supports hex (With Ubuntu 22.04 and gcc, if that's relevant).

**Comment by matekelemen** [comment]
Oh god; good chance to replace this with a regex?

**Comment by EduardGomezEscandell** [comment]
Solved in https://github.com/KratosMultiphysics/Kratos/pull/10251
