### ISSUE TITLE
[Discussion] How to reduce size of MDPA files?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#10066]
**Description**

Right now MDPA are human readable, which is a huge advantage. But they have a main disavantage, these files are huge, specially with complex submodelparts structure. Due to this, among other things, the repository and specially Examples repository have become huge due to mdpa files from tests and examples. I think we should think about the following:

- Use zlib (which is included in Kratos) to create a format like * *.mdpaz* or * *.zmdpa* for example. Maybe just define a binary format, but if we just compress, then one uses who knows can still decompress and therefore keep it as human readable.
- Refactor submodelpart structure (keeping compatibility with current one), because is the main reason of the large sizes. 
	- Right now we define one by one the ids of the submodelparts, this can be a lot of lines of a file. Keeping the same format we can define ranges as many times the ids of the submodeparts are ordered. Like for example 1:96:1 meaning from 1 to 96 increasing 1 by 1, or simply 1:96. This is one example.
	- Another alternative is to use something similar to what we havce done in the MMGProcess. Were we define some references Ids for a subset of submodelparts and we can reconstruct the submodelpart structure from these Ids. This could be the most compressed of the two alternatives.

In addition to this it is also possible to instead of always define elements and conditions, which may imply redefine the same geometries several times for mutiphysics problems, try to use geometries and later assign the elements/conditions corresponding to the respective geometries. (I added the possibility of reading geometries from mdpa)

**Comment by matekelemen** [comment]
I don't think human-readability is that big of an advantage. A standard binary format (like HDF5 or VTK) can also be read using an appropriate tool instead of a simple text editor (not so different from the zlib compressed case).

Speaking of HDF5, I think it's the way to go for larger simulations. The only problem I see is that it doesn't work on windows yet (at least that's what @sunethwarna tells me), but I'm planning on addressing that. It's not just about size, but it can be safely read/written in MPI, which is a huge advantage in my opinion. MDPAs are still fine for small cases and debugging, but I don't think non-standard text-based files should be used for any meaningful analysis.

**Comment by mpentek** [comment]
I’d be in favor of HDF5 wherever possible. It seems to be an industry standard for many reasons, not least native MPI handling.

In the long run, could H5 field potentially replace REST restart files? In theory this could permit restarting from a different number of MPI cores.

**Comment by matekelemen** [comment]
I've talked with Suneth about adding HDF5 support for the restart system, and there are some caveats to that:
- HDF5 will probably never make it into Core, so HDF5 restarting will at most be a compile-time option beside the existing REST files.
- there are plans to recategorize fundamental applications (```LinearSolversApplication```, ```TrilinosApplication```, etc.) as "utilities": kinda like optional extensions of Core. We'll have to wait until this happens before we start thinking about how to implement HDF5 restarts.
- the ```HDF5Application``` is still flaky on Windows (I'm planning to look into it at some point).

**Comment by loumalouomega** [comment]
@KratosMultiphysics/implementation-committee

**Comment by loumalouomega** [comment]
I will close, if @KratosMultiphysics/technical-committee is interested can reopen it
