### ISSUE TITLE
Help with ReductionUtilities

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#10063]
**Description**
In #10029 I'm trying to define a custom reduction and I've faced the following problem:
> Local classes cannot access nonstatic "automatic" local variables of the enclosing function. But they can access the static variables.

See the following example from the related PR

header:
```c++
class CustomUtility
{
public:
double CalculateNearest(array_1d<double,3>& rCoordinates);
private:
array_1d<double,3> mDirection;
}
```

source:
```c++
double CustomUtility::CalculateNearest(array_1d<double,3>& rCoordinates)
{
struct CustomReducer {
    using return_type = double;
    double distance = 1e16;
    double wave_height = 0.0;

    return_type GetValue() {
        return wave_height;
    }
    void LocalReduce(NodeType& rNode) {
        // here I need access to mDirection and rCoordinates in order to compute the new distance
    }
    void ThreadSafeReduce(CustomReducer& rOther) {
        // do something
    }
};
return block_for_each<CustomReducer>(mrModelPart.Nodes(),[&](NodeType& rNode) -> NodeType& {return rNode;});
}
```

How can I make `rCoordinates` and member variables visible to my `CustomReducer` without declaring them static?

**Scope**
- KratosCore
- ReductionUtilities

**Comment by matekelemen** [comment]
Just to make sure I understand: when ```CustomUtility::CalculateNearest``` is called, it invokes a reduction on nodes using the ```CustomReducer```? Do you need to modify ```rCoordinates``` and ```mDirection```?

To access ```mDirection```, you need to explicitly capture ```this``` in the lambda:
```cpp
[&,this](NodeType& rNode) -> NodeType& {return rNode;}
```

**Comment by matekelemen** [comment]
2nd try:

A bit hackish, but you can just return pointers to the stuff you'll need in your reduction.
```cpp
using ReductionArguments = std::tuple<const Node<3>*,const array_1d<double,3>*,const array_1d<double,3>*>; // {pNode, pCoordinates, pDirection}

return block_for_each<CustomReducer>(mrModelPart.Nodes(),[&,this](NodeType& rNode) {
    return std::make_tuple(&rNode, &rCoordinates, &mDirection);
});
```

And your reducer would look like this:
```cpp
struct CustomReducer
{
    void LocalReduce(ReductionArguments);
    ...
}
```

**Comment by miguelmaso** [comment]
> 2nd try:
> 
> A bit hackish, but you can just return pointers to the stuff you'll need in your reduction.
> 
> ```c++
> using ReductionArguments = std::tuple<const Node<3>*,const array_1d<double,3>*,const array_1d<double,3>*>; // {pNode, pCoordinates, pDirection}
> 
> return block_for_each<CustomReducer>(mrModelPart.Nodes(),[&,this](NodeType& rNode) -> ReductionArguments {
>     return std::make_tuple(&rNode, &rCoordinates, &mDirection);
> });
> ```
> 
> And your reducer would look like this:
> 
> ```c++
> struct CustomReducer
> {
>     void LocalReduce(ReductionArguments node_coordinates_direction);
>     ...
> }
> ```

thanks! this is fine
