### ISSUE TITLE
How to write a restart file In Kratos simulations?

### ISSUE THREAD

**Issue by akhilkmat** [KratosMultiphysics/Kratos#10069]
Can anyone suggest how to write a restart file in Kratos? both for DEM and coupled DEM-FEM if possible. I am trying to simulate granular flow in a flat bottom silo. In order to fill the silo with a closed packing fraction, the opening must be kept closed for a duration till its completely filled and then the opening must be released. what is the best way to do this?

Any form of help is appreciated.

Thanks,
Akhil

**Comment by ceulogiof** [comment]
Hey Akhil,
Please check this link https://github.com/KratosMultiphysics/Kratos/issues/9958#issuecomment-1169053707, there was some discussion around this topic. Maybe by looking at the FluidDynamicsApp and StructuralMechanicsApp you can start somewhere. Unfortunately I can't help you any further. 

@KlausBSautter is restart enabled in DEM?
@AlejandroCornejo Is it in the FemToDemApp?

**Comment by akhilkmat** [comment]
Thanks for commenting,

It looks like there is nothing ready to go (atleast for DEM that i know of), I plan to use mesh_creator_sphere.py in DEMapplications at the end of the simulation to output the particle positions into a .mdpa file.

**Comment by loumalouomega** [comment]
@KratosMultiphysics/dem

**Comment by maceligueta** [comment]
Hi @akhilkmat ,
There are two different DEM users who developed utilities for this feature you are asking for. None of them recover velocities or angular velocities, so they do not create a true restart file, but the written files can be used as the input for new computations.
-	The first user ( @joaquinirazabal ) uploaded his utilities in the folder DEMApplication/python_scripts. They are in files named `mesh_creator_sphere.py` and mesh_creator_cluster.py. They contain the functions  `WriteSphereMdpaFromResults `and `WriteClusterMdpaFromResults`, which can be called from the main Kratos script with the desired frequency. This works while the computation is running, and saves files with the user-given periodicity. The saved files should work as inputs for a new computation.
-	The second user ( @salvalatorre ) decided to parse the Ascii GiD results and generate input files with them. This utility can be used once the run has finished, and you can choose which step you want to convert into input for the next run. It only requires to have written the GiD oputput in asci format (not binary as it is the default format). I can’t find this parser uploaded to the repository now, but we can obtain a copy of the parser or ask @salvalatorre to upload it if this is what you need currently.
- 
Let me know if this was helpful and sorry not to have something more production-ready.

**Comment by akhilkmat** [comment]
This was indeed helpful, I used WriteSphereMdpaFromResults() for getting the particle positions. Although this function needs to be called just before the Finalize() section, since the ModelPart -'SpheresPart' gets deleted after Finalize().

Thank you very much!
