### ISSUE TITLE
[GeoMechanicsApplication] make "rebuild_level" adjustable in a dynamic solver strategy in GeoMechanicsApplication

### ISSUE THREAD

**Issue by anoordam** [KratosMultiphysics/Kratos#10067]
currently dynamic calculations in GeoMechanicsApplication are very slow since the LHS is rebuild at each iteration.

In a linear elastic case, the LHS is constant thus has to be build only once, which greatly improves the speed in dynamic calculations

either make the "rebuild_level" property adjustable in a dynamic solver strategy in GeoMechanicsApplication. Or check if a strategy in another Application can be used for this purpose

**Comment by anoordam** [comment]
I think this issue is a bit different, as you are talking about solving time and I am talking about building time. In my case, I was solving a relatively small system dynamically in many time steps. Most of my computation time was at building the matrices. I think this can be optimized by only building the RHS in each iteration.

**Comment by Vahid-Galavi** [comment]
Then you just need to call "SetRebuildLevel(rebuild_level)" function

**Comment by anoordam** [comment]
yes I know, but i want to make it as an input variable. I think, currently that is not possible with the Geomechanics strategies. I think the geo  strategy factory has to be extended.

**Comment by aronnoordam** [comment]
#10109

**Comment by loumalouomega** [comment]
> #10109

Indeed
