### ISSUE TITLE
Reading out of bounds in function_parser_utility

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/Kratos#10077]
**Description**
Accessing element -1 of a string

**Scope**
If the expression string starts with 'x', then we reach line 38 with `i=0`.
https://github.com/KratosMultiphysics/Kratos/blob/fc2e6d1b32d98dbbedb06b244eb81deedd1ad30b/kratos/utilities/function_parser_utility.cpp#L28-L46
Then we access element `MAX_LONG -1`.
Testing it, I've seen that:
- With `libstdc++` (GNU's standard library implementation), this is understood as reading the `\0` sentinel, so no issue. [This reduced example](https://godbolt.org/z/scW1qTPW7) shows it reading `\0`.
- With `libc++` (LLVM's standard library), this is understood as a good old read outside limits, hence undefined behaviour. [This reduced example](https://godbolt.org/z/Ybvz58oaT) shows the sanitizer complaining and reading `\20`, some random ASCII character.

I haven't tested with Microsoft's implementation (Compiler explorer doesn't allow for running the minimal example either).

**To Reproduce**
This piece of code runs on Centos only, so it can be quite niche. Furthermore, it seems that with gcc it won't break. But it is still undefined behaviour.

**Expected behavior**
No illegal memory accessing.

**Comment by matekelemen** [comment]
I'm curious: shouldn't this have already caused segfaults? For example, [this test](https://github.com/KratosMultiphysics/Kratos/blob/55d962ddeff800edcc6ae4c9f3dd3cda5fb2be28/kratos/tests/test_function_parser_utility.py#L28) begins with an ```x``` but passed the CI on every compiler for years now.

**Comment by EduardGomezEscandell** [comment]
That's what I thought, but aparently on gcc's implementation (the one in CI) accessing `string::npos` returns `\0`. Note that `(std::size_t)(-1)` undeflows to `string::npos`.

With clang's implementation this breaks, but the Centos CI run doesn't test it.

**Comment by matekelemen** [comment]
> With clang's implementation this breaks

We also have a clang run in the CI, don't we? Does this only become an issue in release builds?

**Comment by EduardGomezEscandell** [comment]
We have a ubuntu clang CI, but this piece of code is only run on Centos (it is the fallback when regex is not available).

It is indeed possible that we're building with libstdc++, I don't know which one is the default and which one is used.
