### ISSUE TITLE
Runkratos Ignores Virtual Environment Paths

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10080]
## Description
```runkratos``` ignores paths set by a virtual environment and uses system libraries instead.

## To Reproduce
0) **Make sure ```KratosMultiphysics``` is not on your ```PYTHONPATH```**.
1) Create a virtual environment (eg.: in ```$HOME/python_venv/kratos```).
2) Activate the newly created virtual environment.
3) Compile (FullDebug) and install Kratos to the virtual environment's ```site-packages``` directory, which you can get by running ```python -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])'``` from the shell. (eg.: ```$HOME/python_venv/kratos/lib/python3.8/site-packages```).
4) Run ```python -m KratosMultiphysics.run_tests```. (It calls ```runkratos``` for all test suites by default), or just try running any Kratos script with ```runkratos```.

The loaded library path will be the system's ```site-packages``` path (eg.: ```/usr/lib/python3.8/site-packages```) instead of that of the virtual environment (eg.: ```$HOME/python_venv/kratos/lib/python3.8/site-packages```) where Kratos is installed, so **```KratosMultiphysics``` is not found**.

## Expected behavior
```runkratos``` should use the library paths that are set in the environment from which Kratos was compiled from. In this case, that means the virtual environment's paths (eg.: ```$HOME/python_venv/kratos/lib/python3.8/site-packages```).

## Environment
- OS: Up-to-date Manjaro on kernel 5.15.55-1.
- GCC: 12.1.0
- System Python: 3.10.5
- Venv Python: 3.8.13

**Comment by loumalouomega** [comment]
One option can be do static linking, but then the runkratos.exe will be huge

**Comment by rubenzorrilla** [comment]
Mentioning that at this point it might be better to finally get rid of the `runkratos`.

**Comment by loumalouomega** [comment]
> Mentioning that at this point it might be better to finally get rid of the `runkratos`.

We can put it as optional, and solve the issue with static linking. Win-win

**Comment by matekelemen** [comment]
I think it would be best to remove ```runkratos``` to make things unambiguous.

Being clear about how dependencies and libraries are loaded is quite important in my opinion. For example, aerospace companies are required to keep exact versions of their software stack they use for analysis (as far as I know) and we shouldn't make this unnecessarily difficult for them.

**Comment by loumalouomega** [comment]
> I think it would be best to remove `runkratos` to make things unambiguous.
> 
> Being clear about how dependencies and libraries are loaded is quite important in my opinion. For example, aerospace companies are required to keep exact versions of their software stack they use for analysis (as far as I know) and we shouldn't make this unnecessarily difficult for them.

I created the branch https://github.com/KratosMultiphysics/Kratos/tree/core/remove-runkratos

If @KratosMultiphysics/technical-committee  we can proceed and create a PR (I do not open right now because this an early discussion)

**Comment by roigcarlo** [comment]
@matekelemen runkratos acts as its own virtualenv and will only load libraries that exists in the scope of runkratos, if it does not find them it defaults to the system main python installation (if you are lucky), but that's something that we haven't support historically.

I confirm that it will not be fixed, as runkratos is schedules for removal #9733.
