### ISSUE TITLE
Migrate the new designed elements from GeoMechanics branch to Kratos application

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#10083]
**Description**
In issue #9990, New elements are added to the GeoMechanics branch, Triangle2D15N and Line2D5N

Based on @rubenzorrilla request:
Considering that we're adding a new geometry, which might be of interest to any other Kratos application, I'd add this to the Kratos core. Having said this, I'd create an auxiliary PR in which we only add the new geometry, together with its corresponding tests. Once we merge this, we can recover this one implementing the element that uses such geometry.

**TODO**
- Move the new designed elements (geometry), such as Triangle2D15N, Line2D5N, etc. to Kratos application.
- Add test cases for such elements.

**Comment by rubenzorrilla** [comment]
Very good!. Just ping me if you need any help to migrate the `Triangle2D15N` and `Line2D5N` geometries to the Kratos core. :rocket:
