### ISSUE TITLE
Why is BaseType::mStiffnessMatrixIsBuilt always false in Residualbased_newton_raphson_strategy.h?

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10109]
In the KratosCore,
Why is BaseType::mStiffnessMatrixIsBuilt always false in Residualbased_newton_raphson_strategy.h? 

In other words, how can only build and solve the RHS the first iteration.  BaseType::mRebuildLevel doesn't to anything now because in every call, a check for BaseType::mRebuilLevel  and BaseType::mStiffnessMatrixIsBuilt is done. While BaseType::mStiffnessMatrixIsBuild is always false. 

Is it required to copy SolveSolutionStep() in an inherited class, copy everything and add BaseType::mStiffnessMatrixIsBuild = True?

**Comment by loumalouomega** [comment]
If you want to solve in one iteration, you should use ResidualBasedLinearStrategy. In case you want to set manually that flag, indeed what you say it is correct. I will add an access method anyway, because it lacks consistency with other member variables.

**Comment by loumalouomega** [comment]
> If you want to solve in one iteration, you should use ResidualBasedLinearStrategy. In case you want to set manually that flag, indeed what you say it is correct. I will add an access method anyway, because it lacks consistency with other member variables.

I did https://github.com/KratosMultiphysics/Kratos/pull/10113

**Comment by aronnoordam** [comment]
Allright thanks. In my case I want to implement a non-linear force (dependent on displacement). Therefore I still need to solve the system in multiple iterations, however i can keep the LHS constant.
