### ISSUE TITLE
MPI - How to synchronize non historical data to max?

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#10129]
**Description**
I have the following code working in SMP (in the original this is cpp), but I think this cannot be synchronized right now in MPI because there is no SynchronizeNonHistoricalDataToMax (only ToMin). Maybe there is some reason for this as this can be done in a different way but I have not been able to find it yet. This is the pseudo-code.
```
for node in model_part.Nodes:
        node.SetValue(VARIABLE_1, 0.0)

for condition in model_part.Conditions:
    if condition1(condition):
         for node in condition:
                if condition2(node):
                     new_value = function(condition,node)
                     tmp = max(node.GetValue(VARIABLE_1), new_value)
                     node.SetValue(VARIABLE_1, tmp)

#Nodes are not synchronized in MPI at this point

```

Is there any solution to this apart from adding SynchronizeNonHistoricalDataToMax? Any reason why this was not added before?

@KratosMultiphysics/mpi @KratosMultiphysics/technical-committee @KratosMultiphysics/implementation-committee @roigcarlo 

**Scope**
- KratosMPI

**Comment by loumalouomega** [comment]
I think @jcotela just forgot: https://github.com/KratosMultiphysics/Kratos/commit/62b56b549ae796b38c3202aac9fa4a626aaad425 (there is a specific commit to add, but no commit for SynchronizeNonHistoricalDataToMax)

**Comment by loumalouomega** [comment]
In any case can be added relatively easy once you have the min. I understand that the problem is "the synchronization of projects" from our side and that's' why you are asking

**Comment by ddiezrod** [comment]
@loumalouomega That's not a major problem, my concern was rather if there was a reason why it was not there or if there was some workaround someone was using

**Comment by loumalouomega** [comment]
> @loumalouomega That's not a major problem, my concern was rather if there was a reason why it was not there or if there was some workaround someone was using

Doing a small research in the commit history looks like it's only because an error
