### ISSUE TITLE
Add Parameterize package to python 

### ISSUE THREAD

**Issue by mcgicjn2** [KratosMultiphysics/Kratos#10148]
Hi all,

We would like to request the inclusion of parameterized to the python packages to enable the parameterization of our python tests. This allows us to produce a lot of acceptance tests very quickly to test large ranges of values.

Can this be considered.

Regards

Jon (mcgicjn2)

**Comment by mcgicjn2** [comment]
![MicrosoftTeams-image](https://user-images.githubusercontent.com/9568573/185175814-44504ed9-7439-438d-b1e9-250e8b144199.png)

**Comment by roigcarlo** [comment]
Hi @mcgicjn2 

I see no problem, but let me discuss first with the @KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
Probably time to add a proper requirements.txt and setup.py

I think this package is a good addition (would be a testing dependency so that is does not get installed when distributing it)

**Comment by roigcarlo** [comment]
> Probably time to add a proper requirements.txt and setup.py

Agree. Btw, we have a [setup.py](https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/wheels/setup.py), but its only used through the wheelbuilders if we put some defaults we can move to the root.

**Comment by mcgicjn2** [comment]
Cheers, we have skipped the test for now, and will apply it again after the update

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee In principle is favorable to install it. I will do it during this week.

**Comment by carloslubbers** [comment]
Hi @roigcarlo did you have any time to work on this?

**Comment by roigcarlo** [comment]
Hi, yes we agreed on adding it. Let me make the PR.
