### ISSUE TITLE
body_force is not correctly interpolated

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1019]
@loumalouomega, the base solid element gets the VOLUMETRIC_ACCELERATION from the first node of the geometry instead of properly interpolating it to the gauss point

**Comment by RiccardoRossi** [comment]
was #1020 merged both in the master and in the release branch? if so please close this issue

**Comment by roigcarlo** [comment]
Is not. It needs to be merged in #1022  as well

**Comment by loumalouomega** [comment]
Can we close this?

**Comment by roigcarlo** [comment]
Yep
