### ISSUE TITLE
[Parallel memory shared] Lazy solution for parallelization when using `for_each([&]`

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#10192]
**Description**

Not technically a bug, but I have noticed that we have been doing a lazy parallelization (including from my side) in many loops.
 For example see:

https://github.com/KratosMultiphysics/Kratos/blob/9e06ba9e4e2e12b27469aaafcaa1803f9ccbd430/kratos/processes/reorder_and_optimize_modelpart_process.cpp#L44

In here, using the `for_each([&]` means that every variable that is existing will be passed to the lambda. This may imply a lot of memory operations, slowing down the code. So we must check each one of the loops and ensure only the essential variables are passed to the loop.

**Scope**

- KratosCore
- Every application

**Comment by rubenzorrilla** [comment]
Technically means capturing by reference all the variables in the scope where the lambda is defined, so it shouldn't be that bad. I agree that only the required ones must be passed (I tend to do this, specially when only a very few are required). However I'd be hesitant about refactoring current production ready code only because of this.

**Comment by rubenzorrilla** [comment]
> > Technically means capturing by reference all the variables in the scope where the lambda is defined, so it shouldn't be that bad. I agree that only the required ones must be passed (I tend to do this, specially when only a very few are required). However I'd be hesitant about refactoring current production ready code only because of this.
> 
> Yes, but in a class that means all the member variables, this could be quite inefficient

Well, of course it's worse, but if the class is properly implemented shouldn't be that worse... Again I don't think it's worth  changing current production ready code because of this. However, I completely agree with the observation, so I'd start promoting the correct usage of captures when doing code review.

**Comment by loumalouomega** [comment]
> > > Technically means capturing by reference all the variables in the scope where the lambda is defined, so it shouldn't be that bad. I agree that only the required ones must be passed (I tend to do this, specially when only a very few are required). However I'd be hesitant about refactoring current production ready code only because of this.
> > 
> > 
> > Yes, but in a class that means all the member variables, this could be quite inefficient
> 
> Well, of course it's worse, but if the class is properly implemented shouldn't be that worse... Again I don't think it's worth changing current production ready code because of this. However, I completely agree with the observation, so I'd start promoting the correct usage of captures when doing code review.

I think that if we do step by step, it will be OK. But it could have a significant penalty in performance, specially if in the future we give support to GPU in the parallel utilities (in GPU parallelization most of the time is consumed by copying memory, so it can be dramatically significant). And I am pointing a problem that have emerged from a lazy replacement, me included, but after thinking in potential memory bottlenecks I realize my error.

**Comment by matekelemen** [comment]
> Yes, but in a class that means all the member variables, this could be quite inefficient

Nope. Member variables are not part of the scope, only ```this``` (just a single pointer). Every member variable is accessed through dereferencing ```this```. (this is why I usually prepend member variable accesses and member function invocations with ```this->```, it reminds me that there's always an extra indirection)

https://en.cppreference.com/w/cpp/language/lambda

[godbolt](https://godbolt.org/z/WKf5Koe8a)

Additionally, from C++20 ```this``` has to be captured explicitly, ```[&]``` won't capture it (you'd have to do ```[this,&]```).

**Comment by matekelemen** [comment]
What I'm more worried about is converting lambdas to ```std::function```s. ```std::function``` is **MUCH** slower than an equivalent lambda or raw function call, and I see it getting used in a lot of places. Thankfully, ```parallel_utilities``` does it right and templates the function it executes so passed lambdas don't get converted to ```std::function```s.

That said I see ```std::function``` getting heavily used in core as well, I'm just hoping that they don't get passed to massive loops.

**Comment by loumalouomega** [comment]
> > Yes, but in a class that means all the member variables, this could be quite inefficient
> 
> Nope. Member variables are not part of the scope, only `this` (just a single pointer). Every member variable is accessed through dereferencing `this`. (this is why I usually prepend member variable accesses and member function invocations with `this->`, it reminds me that there's always an extra indirection)
> 
> [en.cppreference.com/w/cpp/language/lambda](https://en.cppreference.com/w/cpp/language/lambda)
> 
> [godbolt](https://godbolt.org/z/WKf5Koe8a)
> 
> Additionally, from C++20 `this` has to be captured explicitly, `[&]` won't capture it (you'd have to do `[&,this]`).

Okay, in that case this has less priority with respect to what I though

**Comment by loumalouomega** [comment]
> What I'm more worried about is converting lambdas to `std::function`s. `std::function` is **MUCH** slower than an equivalent lambda or raw function call, and I see it getting used in a lot of places. Thankfully, `parallel_utilities` does it right and templates the function it executes so passed lambdas don't get converted to `std::function`s.
> 
> That said I see `std::function` getting heavily used in core as well, I'm just hoping that they don't get passed to massive loops.

The only place I used std:::function was due to a compilation error from MSVSC...

**Comment by rubenzorrilla** [comment]
> What I'm more worried about is converting lambdas to `std::function`s. `std::function` is **MUCH** slower than an equivalent lambda or raw function call, and I see it getting used in a lot of places. Thankfully, `parallel_utilities` does it right and templates the function it executes so passed lambdas don't get converted to `std::function`s.
> 
> That said I see `std::function` getting heavily used in core as well, I'm just hoping that they don't get passed to massive loops.

@EduardGomezEscandell did some performance tests in this regard. I'm saying it by heart, but the problem was in the pointer assignation, not in the call itself.

**Comment by matekelemen** [comment]
> the problem was in the pointer assignation, not in the call itself.

Construction is an obvious overhead, but calls are extremely sluggish as well. Have a look at [this example](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahUAUgBMAIUtXyKxqiIEh1ZpgDC6egFc2TEABWC3J3ABkCJmwAOT8AI2xSEGkAZnIAB3QlYhcmL19/IJDM7OchCKjYtgSk1PtsRzKmESIWUiJ8vwDg%2BsbclraiCpj4xOS0pVb2zsKeycHhqprxgEp7dB9SVE4uSxTI1F8cAGozFI8XSdJsdjPcMy0AQT2Do%2BxT85ofJidciTuHs8LPsfm8Ph5fhwAU9AYcWEolMcACoEDikQFmADsNie6R8cXoBFQIEBxzJyNRiQgGCYk2Ok0wIBAV0iwEsADZjqQALLYBEsYDYFak8lYnGPcmS%2BlERloDZEcFnDxc3n8wVncVS8lsKzYYCRD4AEWlssO6FQAGsIMKUprRZjDRinpKAH4otHWkVksUMpkYHwKpVK04WCxmQIeGWbFhNEAhiyK87HCC%2BtD0c1WlbHAC0xx1esiWaDSdT7noGqxjphuNIBAAbjHOF6TX705aAPoK/P6pgVmEOvvPauPIjYNjpIyj8FwhHIgBi31%2BQmhjzr6AImGOACVvtShHTUyyTByuR54TF2NhyM2pYeCAAvbCd44ASVHpBjuS83yI1%2BdWrJJEFx%2BJoORPUhgKXJhhX7O1AMpUhjmcD1SDPFRokvG04OOQREJTGUmWyR9nwIM5DS0DVjlI8430ST8hG/YRKNsWwCBgiUAIgxcmggNjB0rJ0h0eSIuxYSJPVg5s72IhViDopp239YQjWOHhsAATkHSVvmyYAok3dMTGOQzgC5PkfHoIh%2BP/MkaTpFgA3QYz2DiTAWBU8MbAsdlriUCyrMCY18NlIin1kpgcHUItsV8/yQxsFJjUiSKKwHW1mzshVUy%2BEDchw7i8rI5zqjc6yOLJWLLJUij0ps7dd0sCwjBKlhGvIKj33ophFI2YR2ua1yWCwqSCLlANE2VSrA3OYNSwi8tbWOAB6JbjkwPw2AATyQpzBHoY50HSZCHy6wTJSm6qtPJHcmAgRrsoK5dQ3auSPwUpTf3y3KhGGurU39aaPGDC7i2VObMAWqxltW9a2C2nacPQbwDqO1ETtA/tDS4NZ6G4QJ%2BACLgdHIdBuCB6xbHpDYtnePY%2BHIIhtGxtYkBuHAkmtcgLSCHgADoUmkdkAA4tB4AXhdFlJ2UMbhpH4Nggi0chCeJ0muH4JQQCVxmiex8g4FgFBsHUbBUEcigqAgNpgCUVRjAaEQkHQAB3Qn6YwccGC6u2onoR2XZV/gPfSBgxht1h0iUJ3f2D0PSAAeQDf3XaZ0ITdQR5SBt7h%2BGN02WkIQn%2BEEYQxAkTgZDkYRlDUTRdfIfQ0iMEw0BY6xDAIOJNcgNZDqaTWuGzBkyPMCnrB4TEc3jlINep7YDAZSIfYdp2U94fgiGuHZ6edj90m4PgcbxgnU7V3B0/N451CF9ls3ZaRjmAVBUGTTfvgtLMIHJry7GOfBiDICGFIPAVgbyZisFmbMxic1xlwOW5AFaBCVoHEmOd7BawZuAtY3Ngi8x4IEYW7ILCYmkEg9SItAgyy4DPZWp80E6x0GsA2CB4AQCNhfEgFtqDW1tvbP2q83ZB3QJ7ScuRl78IDqnWOjAkhwhMDILQStpGJETqIARqc84ZyzgPXO6cC6RDQSXUQ4hJCVyMTXDQqd9A8EMMYUwbc7CEi7vAXuqN9zcCHjKEeDiJ5TxoUoOeFd7AyiXnw5OgiGZbwPvwXeLB97ryPlwfGtD65nw4YA6%2Bt977HDkaZGQvMtAFOTN/Ww7V/6cKASAsBusIHkFZiwdm1BEnwIVikTEvMhYpC6ZiEWQtpA8G8oEG%2BKTVZoM1trcB%2BtEBsJAJo82lBuHaPEeE6J5BpHezCeo%2Buyikh1lQOkdI7Y6w8HUu2ScfIiDtnUPfNZwiQ4yNUSs%2BumjM7Z3VmnfOISi5V2MeXKQshzEqEsfXfQIRm72LHo4zu3dOZ91yAPJavpR4/18UteOFhZ6bHnjYxeTBllbPppvbA28Yl72iYk5JKC0mm0vtch%2BbAlB7OOMc9SvNzl0i/g4sphAKl01AZgmpkCGnQOafLEARC8HsilRYE5%2BChaYgFiEKlYyMEMOZlzZI7S%2BnALaRYQI0h1Ki3UtLWBNDlXvLVbU2BGKRn8DVtUxhaw6yJGyK4aQQA%3D%3D%3D), it specifically times invocations (compile and run it locally for more reliable results).

The unoptimized program leads to a difference of 1-2 orders of magnitude in CPU time, but the real shocker is when optimization is turned on. The compiler cannot inline/properly optimize calls to ```std::function```.

**Comment by EduardGomezEscandell** [comment]
One consideration is that in the standard library, the function is usually templated:

```c++
template< class InputIt, class UnaryFunction >
UnaryFunction for_each( InputIt first, InputIt last, UnaryFunction f );
```

We should at least consider this approach, but I'm not familiar enough with the core's usage of std::functions to really take a position here. Anyways I ran a quick benchmark (btw highly recommended site): [Quickbench](https://quick-bench.com/q/d7Wo6wT-Sos17WHZfIlhHI_HwzM)

Here is the result for calling four implementations of a dummy function:

```c++
// Std function, constructed every time
float do_the_math_std(std::function<float(float)> func, float x)
{
  return func(x);
}

// Std function, pre-constructed
float do_the_math_std_ref(std::function<float(float)>& func, float x)
{
  return func(x);
}

// Function pointer (limited in which lambdas it can take)
float do_the_math_ptr(float(*func)(float), float x)
{
  return func(x);
}

// Templated
template<typename T>
float do_the_math_template(T&& func, float x)
{
  return func(x);
}
```

![d7Wo6wT-Sos17WHZfIlhHI_HwzM](https://user-images.githubusercontent.com/47142856/187304799-de730e0e-0f97-4b20-be9e-0462e2f779ea.png)


Y axis is CPU time (less is better)

**Comment by matekelemen** [comment]
> btw highly recommended site, it uses Google benchmark

Thanks for the heads-up.

I think it's important to see how much time the operation itself is taking up ([quickbench](https://quick-bench.com/q/K1NLxCoa091m3hmnYqRWW0dh-7g)):
![K1NLxCoa091m3hmnYqRWW0dh-7g](https://user-images.githubusercontent.com/44344022/187370115-ca6685d8-6901-4452-9db7-a8ce80fae5f2.png)



=> the overhead of invoking function pointers / deduced lambdas is either negligible or they're completely optimized out while calling an ```std::function``` is comparable to computing ```std::sqrt```.

**Comment by loumalouomega** [comment]
I will close this.
