### ISSUE TITLE
#pragma once - do we use it now?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#10229]
basically see title

I saw this popping up in a few places, I think this should be discussed and agreed on once

**Comment by rubenzorrilla** [comment]
The idea is to start promoting the use of `pragma once`. See [here](https://github.com/KratosMultiphysics/Kratos/pull/10016#discussion_r928602155). Closing as we already discussed this in the @KratosMultiphysics/technical-committee. @philbucher  feel free to reopen if you want to add something.

**Comment by philbucher** [comment]
awesome thx!

**Comment by sunethwarna** [comment]
The '#pragma once' is supported since 2013 ryt ?( as per Wikipedia) ...i also love the idea :)... But little bit curious about the cause for the sudden behavior change :)

**Comment by philbucher** [comment]
what behavior change?
