### ISSUE TITLE
GlobalCoordinates calculation

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/Kratos#10232]
**Description**
I have realized that when I use the method `GlobalCoordinates` in `geometry.h`, the calculation of the shape functions does not take into account the integration method, leading to inaccurate results when I get the global coordinates of the integration points. The code is below:

```
    /** This method provides the global coordinates to
    *   the corresponding integration point
    * @param rResult The global coordinates
    * @param IntegrationPointIndex The index of the integration point
    * @return the global coordinates
    */
    void GlobalCoordinates(
        CoordinatesArrayType& rResult,
        IndexType IntegrationPointIndex
    ) const
    {
        noalias(rResult) = ZeroVector(3);

        const Matrix& N = this->ShapeFunctionsValues();

        for (IndexType i = 0; i < this->size(); i++)
            noalias(rResult) += N(IntegrationPointIndex, i) * (*this)[i];
    }
```
Should the function `ShapeFunctionsValues()` have the integration method as an argument?

**Scope**
- KratosCore

**Comment by loumalouomega** [comment]
I would say there is a way...

**Comment by loumalouomega** [comment]
> I would say there is a way...

https://github.com/KratosMultiphysics/Kratos/blob/650b0c17cc931fac472f31481df4a2c49b2b02fe/kratos/geometries/geometry.h#L2391

just use the other method which uses the local coordinates as an input, therefore it will work with any integration method (you must get the local coordinates of your GP first, of course)

**Comment by loumalouomega** [comment]
> > I would say there is a way...
> 
> https://github.com/KratosMultiphysics/Kratos/blob/650b0c17cc931fac472f31481df4a2c49b2b02fe/kratos/geometries/geometry.h#L2391
> 
> just use the other method which uses the local coordinates as an input, therefore it will work with any integration method (you must get the local coordinates of your GP first, of course)

I would close this

**Comment by jgonzalezusua** [comment]
Ok, this is an alternative but the question is, should we generalize the method I mentioned above to make it more general?

**Comment by loumalouomega** [comment]
> Ok, this is an alternative but the question is, should we generalize the method I mentioned above to make it more general?

See https://github.com/KratosMultiphysics/Kratos/pull/10236

**Comment by jgonzalezusua** [comment]
Ok, thanks
