### ISSUE TITLE
[Performance] Did you know about FBVector?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#10269]
**Description**

I was reading the last post of my favourite C++ blog (the blog of PVS Studio)

https://pvs-studio.com/en/blog/posts/0989/

Where a discussion about different C++ containers is presented. And I know most of the content, but what I didn't know was about the existence of FBVector: https://medium.com/smucs/fbvector-a-possible-replacement-for-std-vector-e46bb31b8a56 and https://github.com/facebook/folly/blob/main/folly/docs/FBVector.md . An implementation of the std::vector by Facebook, which apparently is significative more efficient. The way it works is identical to the std::vector, so we may consider it in the future, as the replacement could be done in a relatively easy manner.

**Comment by RiccardoRossi** [comment]
just to tell that std vector cpuld also be used with an allocator as optional argument.

also the big problem i see for std vector (which we cpuld change) is that ot is zero initialized by default .
specifying an allocator one could at once remove the zero allocation and ise a better allocator

**Comment by RiccardoRossi** [comment]
following along the line of what i was telling

i would add the following to our define, and essentially use this "flexible_vector" anywhere we are currently using std::vector

~~~cpp
template<typename T>
using flexible_vector = std::vector<T,boost::noinit_adaptor<std::allocator<T>>>;
~~~

note that "Kratos::flexible_vector<int>" would then be perceived as a different object than "std::vector<int>" so we would need to change quite a lot of code (which would have to be done incrementally.

I should say that on my side i should say i am a bit resisting to the idea of adding a dependency to folly (or other large scale libraries), however the thing i am proposing would allow one to test your idea or simply the use of alternative allocators.

anyhow, this is a very preliminary idea, i am adding @KratosMultiphysics/technical-committee to the discussion as well as @philbucher with whom i toyed the idea some time back

**Comment by RiccardoRossi** [comment]
just to add that as can be seen at [link](https://www.boost.org/doc/libs/1_77_0/libs/core/doc/html/core/noinit_adaptor.html) the noinit_adaptor is a very shallow adaptor with code

~~~cpp
namespace boost {

template<class A>
struct noinit_adaptor
    : A {
    template<class U>
    struct rebind {
        typedef noinit_adaptor<allocator_rebind_t<A, U> > other;
    };

    noinit_adaptor() noexcept;

    template<class U>
    noinit_adaptor(U&& u) noexcept;

    template<class U>
    noinit_adaptor(const noinit_adaptor<U>& u) noexcept;

    template<class U>
    void construct(U* p);

    template<class U>
    void destroy(U* p);
};

template<class T, class U>
bool operator==(const noinit_adaptor<T>& lhs,
    const noinit_adaptor<U>& rhs) noexcept;

template<class T, class U>
bool operator!=(const noinit_adaptor<T>& lhs,
    const noinit_adaptor<U>& rhs) noexcept;

template<class A>
noinit_adaptor<A> noinit_adapt(const A& a) noexcept;

} /* boost */

so if we want we could make a kratos version of it not to add one more dependency on boost
~~~

**Comment by RiccardoRossi** [comment]
Well, the results are quite impressive:

here goes my test script, which does nothing else than assigning the entry of a vector (if you like to take the sqrt, just uncomment the code.

compilation on gcc is done by
"g++ main.cpp -Ofast -march=native -fopenmp -I/usr/include/boost -std=c++17 -DNDEBUG"

~~~cpp
#include <vector>
#include <iostream>
#include <chrono>
#include <cmath>
#include "core/noinit_adaptor.hpp"

//compilation line: g++ main.cpp -Ofast -march=native -fopenmp -I/usr/include/boost -std=c++17 -DNDEBUG

template<class Tvec>
double Test(){

    using unit_t = std::chrono::nanoseconds;

    auto start_cpp = std::chrono::steady_clock::now();

    unsigned int n = 1e8;
    Tvec a(n);

    //initialize
    for(int i=0; i<a.size(); ++i)
        a[i] = i;

    //take the square root of everything
    for(int i=0; i<a.size(); ++i)
        a[i] = std::sqrt(a[i]);

    auto end_cpp = std::chrono::steady_clock::now();
    auto duration_cpp = std::chrono::duration_cast<unit_t>(end_cpp- start_cpp).count();    
    std::cout << "duration     = " << duration_cpp << std::endl;

    //check result - not benchmarked
    double tot=0.0;
    for(int i=0; i<a.size(); ++i)
        tot += a[i];   

    return tot;
}

template<typename T>
using flexible_vector = std::vector<T,boost::noinit_adaptor<std::allocator<T>>>;

int main() {

    int nrepetitions = 10;
    std::cout << "std vector results:" << std::endl;    
    for(unsigned int i=0; i<nrepetitions; ++i)
    {
        Test<std::vector<double>>();    
    }

    std::cout << "flexible_vector results:" << std::endl;    
    for(unsigned int i=0; i<nrepetitions; ++i)    
    {
        Test<flexible_vector<double>>();    
    }

    return 0;
}
~~~

the output on my laptop are the following (admittedly my computer is partially busy, so the performance may not be optimal)

~~~txt
rrossi@LAPTOP-959TES5H:/mnt/c/Users/rross/Programming/scratch/test_noinit$ g++ main.cpp -Ofast -march=native -fopenmp -I/usr/include/boost -std=c++17
rrossi@LAPTOP-959TES5H:/mnt/c/Users/rross/Programming/scratch/test_noinit$ ./a.out
std vector results:
duration     = 241422202
duration     = 191408572
duration     = 186642094
duration     = 175217654
duration     = 170366916
duration     = 170711435
duration     = 184361935
duration     = 178092636
duration     = 180364622
duration     = 197534645
flexible_vector results:
duration     = 108762349
duration     = 108265949
duration     = 107631609
duration     = 106575921
duration     = 108704991
duration     = 120952285
duration     = 120456545
duration     = 131005303
duration     = 176222191
duration     = 113932587
~~~

**Comment by loumalouomega** [comment]
> Well, the results are quite impressive:
> 
> here goes my test script, which does nothing else than assigning the entry of a vector (if you like to take the sqrt, just uncomment the code.
> 
> compilation on gcc is done by "g++ main.cpp -Ofast -march=native -fopenmp -I/usr/include/boost -std=c++17 -DNDEBUG"
> 
> ```c++
> #include <vector>
> #include <iostream>
> #include <chrono>
> #include <cmath>
> #include "core/noinit_adaptor.hpp"
> 
> //compilation line: g++ main.cpp -Ofast -march=native -fopenmp -I/usr/include/boost -std=c++17 -DNDEBUG
> 
> template<class Tvec>
> double Test(){
> 
>     using unit_t = std::chrono::nanoseconds;
> 
>     auto start_cpp = std::chrono::steady_clock::now();
> 
>     unsigned int n = 1e8;
>     Tvec a(n);
> 
>     //initialize
>     for(int i=0; i<a.size(); ++i)
>         a[i] = i;
> 
>     //take the square root of everything
>     for(int i=0; i<a.size(); ++i)
>         a[i] = std::sqrt(a[i]);
> 
>     auto end_cpp = std::chrono::steady_clock::now();
>     auto duration_cpp = std::chrono::duration_cast<unit_t>(end_cpp- start_cpp).count();    
>     std::cout << "duration     = " << duration_cpp << std::endl;
> 
>     //check result - not benchmarked
>     double tot=0.0;
>     for(int i=0; i<a.size(); ++i)
>         tot += a[i];   
> 
>     return tot;
> }
> 
> template<typename T>
> using flexible_vector = std::vector<T,boost::noinit_adaptor<std::allocator<T>>>;
> 
> int main() {
> 
>     int nrepetitions = 10;
>     std::cout << "std vector results:" << std::endl;    
>     for(unsigned int i=0; i<nrepetitions; ++i)
>     {
>         Test<std::vector<double>>();    
>     }
> 
>     std::cout << "flexible_vector results:" << std::endl;    
>     for(unsigned int i=0; i<nrepetitions; ++i)    
>     {
>         Test<flexible_vector<double>>();    
>     }
> 
>     return 0;
> }
> ```
> 
> the output on my laptop are the following (admittedly my computer is partially busy, so the performance may not be optimal)
> 
> ```
> rrossi@LAPTOP-959TES5H:/mnt/c/Users/rross/Programming/scratch/test_noinit$ g++ main.cpp -Ofast -march=native -fopenmp -I/usr/include/boost -std=c++17
> rrossi@LAPTOP-959TES5H:/mnt/c/Users/rross/Programming/scratch/test_noinit$ ./a.out
> std vector results:
> duration     = 241422202
> duration     = 191408572
> duration     = 186642094
> duration     = 175217654
> duration     = 170366916
> duration     = 170711435
> duration     = 184361935
> duration     = 178092636
> duration     = 180364622
> duration     = 197534645
> flexible_vector results:
> duration     = 108762349
> duration     = 108265949
> duration     = 107631609
> duration     = 106575921
> duration     = 108704991
> duration     = 120952285
> duration     = 120456545
> duration     = 131005303
> duration     = 176222191
> duration     = 113932587
> ```

Between 65% and 15%, very nice

**Comment by RiccardoRossi** [comment]
ouch, i copied without commenting the sqrt... well never mind

**Comment by loumalouomega** [comment]
> ouch, i copied without commenting the sqrt... well never mind

Be careful with -Ofast, can be dangerous: https://stackoverflow.com/questions/27315941/gcc-ofast-complete-list-of-limitations

**Comment by loumalouomega** [comment]
> Well, the results are quite impressive:
> 
> here goes my test script, which does nothing else than assigning the entry of a vector (if you like to take the sqrt, just uncomment the code.
> 
> compilation on gcc is done by "g++ main.cpp -Ofast -march=native -fopenmp -I/usr/include/boost -std=c++17 -DNDEBUG"
> 
> ```c++
> #include <vector>
> #include <iostream>
> #include <chrono>
> #include <cmath>
> #include "core/noinit_adaptor.hpp"
> 
> //compilation line: g++ main.cpp -Ofast -march=native -fopenmp -I/usr/include/boost -std=c++17 -DNDEBUG
> 
> template<class Tvec>
> double Test(){
> 
>     using unit_t = std::chrono::nanoseconds;
> 
>     auto start_cpp = std::chrono::steady_clock::now();
> 
>     unsigned int n = 1e8;
>     Tvec a(n);
> 
>     //initialize
>     for(int i=0; i<a.size(); ++i)
>         a[i] = i;
> 
>     //take the square root of everything
>     for(int i=0; i<a.size(); ++i)
>         a[i] = std::sqrt(a[i]);
> 
>     auto end_cpp = std::chrono::steady_clock::now();
>     auto duration_cpp = std::chrono::duration_cast<unit_t>(end_cpp- start_cpp).count();    
>     std::cout << "duration     = " << duration_cpp << std::endl;
> 
>     //check result - not benchmarked
>     double tot=0.0;
>     for(int i=0; i<a.size(); ++i)
>         tot += a[i];   
> 
>     return tot;
> }
> 
> template<typename T>
> using flexible_vector = std::vector<T,boost::noinit_adaptor<std::allocator<T>>>;
> 
> int main() {
> 
>     int nrepetitions = 10;
>     std::cout << "std vector results:" << std::endl;    
>     for(unsigned int i=0; i<nrepetitions; ++i)
>     {
>         Test<std::vector<double>>();    
>     }
> 
>     std::cout << "flexible_vector results:" << std::endl;    
>     for(unsigned int i=0; i<nrepetitions; ++i)    
>     {
>         Test<flexible_vector<double>>();    
>     }
> 
>     return 0;
> }
> ```
> 
> the output on my laptop are the following (admittedly my computer is partially busy, so the performance may not be optimal)
> 
> ```
> rrossi@LAPTOP-959TES5H:/mnt/c/Users/rross/Programming/scratch/test_noinit$ g++ main.cpp -Ofast -march=native -fopenmp -I/usr/include/boost -std=c++17
> rrossi@LAPTOP-959TES5H:/mnt/c/Users/rross/Programming/scratch/test_noinit$ ./a.out
> std vector results:
> duration     = 241422202
> duration     = 191408572
> duration     = 186642094
> duration     = 175217654
> duration     = 170366916
> duration     = 170711435
> duration     = 184361935
> duration     = 178092636
> duration     = 180364622
> duration     = 197534645
> flexible_vector results:
> duration     = 108762349
> duration     = 108265949
> duration     = 107631609
> duration     = 106575921
> duration     = 108704991
> duration     = 120952285
> duration     = 120456545
> duration     = 131005303
> duration     = 176222191
> duration     = 113932587
> ```

Have you tried Google Benchmark? (https://github.com/google/benchmark), very nice

**Comment by RiccardoRossi** [comment]
@philbucher suggested to take away the initialization to see how is the differenence in the creation. Also, compiling with -O3 instead of -Ofast

here the results:

~~~txt
rossi@LAPTOP-959TES5H:/mnt/c/Users/rross/Programming/scratch/test_noinit$ ./a.out
std vector results:
duration     = 179592217
duration     = 104025070
duration     = 104944445
duration     = 105553201
duration     = 104510097
duration     = 105969380
duration     = 103519996
duration     = 103761265
duration     = 105757271
duration     = 105706968
flexible_vector results:
duration     = 19727
duration     = 2725
duration     = 2585
duration     = 4709
duration     = 3777
duration     = 3858
duration     = 4429
duration     = 4608
duration     = 6282
duration     = 4208
~~~

**Comment by matekelemen** [comment]
I like the idea of having more options in Kratos and also support having an uninitialized dynamic array class, but I think their applicability is very limited. Basically, it would only make sense to use it for arrays of built-in types (eg.: ```double```, ```int```, ...) and only when the items of the array must be evaluated in reverse / in a random access fashion, or when they must specifically be instantiated upfront.

If the items in the vector can be evaluated in order, a good old ```reserve``` + ```push_back``` loop on a standard vector does exactly the same thing. This covers most use cases.

As for custom types, the ```noinit_adaptor``` calls the default constructor, and since we initialize everything in default constructors in Kratos (which is a good thing in my opinion), it's identical to using ```std::allocator``` (== no performance benefit).

An amusing side effect of the above is that we can get the exact same performance benefit by using a wrapper around built-in classes that have a no-op default constructor. See the ```Wrapper``` class in the examples and the related benchmark results.

Here are the [benchmarks](https://github.com/matekelemen/benchmarks/blob/3e55a02d26f4a27b0bb5056b1473a79b60836bc6/src/noinit_vector.cpp) I am basing my opinion on:
```cpp
// --- External Includes ---
#include "boost/core/noinit_adaptor.hpp"
#include "benchmark/benchmark.h"

// --- STL Includes ---
#include <vector>
#include <cmath>


constexpr const std::size_t arraySize = 1e6;


template <class T>
class Wrapper
{
public:
    Wrapper() noexcept {};
    Wrapper(T value) noexcept : _value(value) {}
    Wrapper(Wrapper&& r_rhs) noexcept = default;
    Wrapper(const Wrapper& r_rhs) noexcept = default;
    Wrapper& operator=(T r_rhs) noexcept {_value = r_rhs; return *this;}
    Wrapper& operator=(Wrapper&& r_rhs) noexcept = default;
    Wrapper& operator=(const Wrapper& r_rhs) noexcept = default;

    operator T() const {return _value;}
    operator T&() {return _value;}

private:
    T _value;
}; // struct Wrapper


template <class T>
inline T process(T index)
{
    return std::sqrt(index);
}


template<class TArray>
void growAndInitialize(benchmark::State& r_state)
{
    for (auto dummy : r_state)
    {
        TArray array;
        for (std::size_t i=0; i<arraySize; ++i)
            array.push_back(process(i));
        benchmark::DoNotOptimize(array);
    }
} // void resizeAndInitialize


template<class TArray>
void resizeAndInitialize(benchmark::State& r_state)
{
    for (auto dummy : r_state)
    {
        TArray array(arraySize);
        for (std::size_t i=0; i<arraySize; ++i)
            array[i] = process(i);
        benchmark::DoNotOptimize(array);
    }
} // void resizeAndInitialize


template <class TArray>
void reserveAndInitialize(benchmark::State& r_state)
{
    for (auto dummy : r_state)
    {
        TArray array;
        array.reserve(arraySize);
        for (std::size_t i=0; i<arraySize; ++i)
            array.push_back(process(i));
        benchmark::DoNotOptimize(array);
    }
} // void reserveAndInitialize


template<typename T>
using NoInitVector = std::vector<T,boost::noinit_adaptor<std::allocator<T>>>;


// --- Standard vector of standard built-ins ---
BENCHMARK_TEMPLATE(growAndInitialize, std::vector<double>)->Name("Standard vector of built-ins: grow");
BENCHMARK_TEMPLATE(resizeAndInitialize, std::vector<double>)->Name("Standard vector of built-ins: resize");
BENCHMARK_TEMPLATE(reserveAndInitialize, std::vector<double>)->Name("Standard vector of built-ins: reserve");

// --- No-init vector of standard built-ins ---
BENCHMARK_TEMPLATE(growAndInitialize, NoInitVector<Wrapper<double>>)->Name("No-init vector of built-ins: grow");
BENCHMARK_TEMPLATE(resizeAndInitialize, NoInitVector<Wrapper<double>>)->Name("No-init vector of built-ins: resize");
BENCHMARK_TEMPLATE(reserveAndInitialize, NoInitVector<Wrapper<double>>)->Name("No-init vector of built-ins: reserve");

// --- Standard vector of wrapped built-ins ---
BENCHMARK_TEMPLATE(growAndInitialize, std::vector<Wrapper<double>>)->Name("Standard vector of wrapped built-ins: grow");
BENCHMARK_TEMPLATE(resizeAndInitialize, std::vector<Wrapper<double>>)->Name("Standard vector of wrapped built-ins: resize");
BENCHMARK_TEMPLATE(reserveAndInitialize, std::vector<Wrapper<double>>)->Name("Standard vector of wrapped built-ins: reserve");

// --- No-init vector of wrapped built-ins ---
BENCHMARK_TEMPLATE(growAndInitialize, NoInitVector<Wrapper<double>>)->Name("No-init vector of wrapped built-ins: grow");
BENCHMARK_TEMPLATE(resizeAndInitialize, NoInitVector<Wrapper<double>>)->Name("No-init vector of wrapped built-ins: resize");
BENCHMARK_TEMPLATE(reserveAndInitialize, NoInitVector<Wrapper<double>>)->Name("No-init vector of wrapped built-ins: reserve");

BENCHMARK_MAIN();
```

Output:
```
----------------------------------------------------------------------------------------
Benchmark                                              Time             CPU   Iterations
----------------------------------------------------------------------------------------
Standard vector of built-ins: grow               4902541 ns      4891313 ns          127
Standard vector of built-ins: resize             1447805 ns      1443818 ns          479
Standard vector of built-ins: reserve            1281006 ns      1280509 ns          543
No-init vector of built-ins: grow                4618039 ns      4614730 ns          135
No-init vector of built-ins: resize              1281131 ns      1280665 ns          538
No-init vector of built-ins: reserve             1282993 ns      1282483 ns          543
Standard vector of wrapped built-ins: grow       4634817 ns      4631665 ns          135
Standard vector of wrapped built-ins: resize     1280426 ns      1279965 ns          534
Standard vector of wrapped built-ins: reserve    1281042 ns      1280539 ns          543
No-init vector of wrapped built-ins: grow        4625464 ns      4622227 ns          137
No-init vector of wrapped built-ins: resize      1280939 ns      1280403 ns          545
No-init vector of wrapped built-ins: reserve     1297298 ns      1290643 ns          540
```

**Comment by RiccardoRossi** [comment]
well, i kind of agree... the point is that changing the allocator changes the type, so in essence my idea is to define a "flexible_vector" and to attempt replacing std::vector all over the  code by Kratos::flexible_vector. 

After that we should never assume vector is zeroed by default, which is a good thing for performance.

that is not panacea of course but at least it will be faster in many cases ...

**Comment by RiccardoRossi** [comment]
i correct myself, for "resize" there should be a difference (And there is actually, although not as dramatic as it was before ... point is that resize employes the copy constructor for all the iterms, so even the noinit vector will be obliged to do that.

note howevr that your benchmark does not call "resize" but rather it allocates a new vector.

try removing the code

~~~cpp
        for (std::size_t i=0; i<arraySize; ++i)
            array[i] = process(i);
~~~

and i expect the difference to be larger

**Comment by philbucher** [comment]
If it is decided if we use another vector type then it could be added as alias
Then maybe it could even be exchanged, e.g. to the folly one
if necessary multiple aliases could be added, e.g. `flexible_vector`, `fast_vector` 

and maybe even `fast_get_solution_step_vector` :rofl:  (I will see myself out :rofl: )

**Comment by loumalouomega** [comment]
As we use Trilinos, which uses Kokkos:

https://kokkos.github.io/kokkos-core-wiki/API/containers/vector.html

**Comment by philbucher** [comment]
Everyone: lets get rid of Trilinos 
Vicente: lets add it to the core 🤡😂

**Comment by loumalouomega** [comment]
> That's basically why @RiccardoRossi implements currently the Kratos Sparse Matrices

Yes, but I didn't though it was for total replacement, as Trilinos also provides other things apart from sparse matrices, like linear solvers.

**Comment by loumalouomega** [comment]
> Sure the linear solvers will still be usable, but we wont have the hard dependency on Trilinos for MPI any more
> 
> AMGCL doesn't need Trilinos, and I think most users use it in MPI, hence Trilinos will be fully optional in the future

Understood
