### ISSUE TITLE
[Workshop][Announcement] Kratos Workshop 2022

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#10272]
Dear @KratosMultiphysics/all, we are pleased to announce that, after the pandemic break, Kratos Workshop is back!

This year workshop will take place during November 9th and 10th and will be hosted by [Deltares](https://www.deltares.nl/en/) in the beautiful city of Delft, The Netherlands.

You can find the details and registration in https://softwaredays.deltares.nl/program?session-topic=dgeo&session-registrationType=userdays (Remember to register for both days!)

As always, Kratos Workshop is a good opportunity to get to know all member of the communities and the latest news about our framework, and this year we will also have the opportunity to see how Deltares has been able to integrate Kratos in some of their products. 

Hope to se you all there!

**Comment by loumalouomega** [comment]
We need more labels...

**Comment by mcgicjn2** [comment]
Hi @roigcarlo Has the agenda at your end been finalized ? Cheers Jon

**Comment by roigcarlo** [comment]
Hi @mcgicjn2 Yep, our session will consists in short presentations of ~20. We expect 6 sessions in total. I sent you a mail with the proposal and the list of speakers.

I will send it again in case it got lost or somethings.

**Comment by ChengshunShang1996** [comment]
It is very strange that there are two unpinning records about me. I even didn't check this issue before today. Sorry for that @roigcarlo

**Comment by ChengshunShang1996** [comment]
> It is very strange that there are two unpinning records about me. I even didn't check this issue before today. Sorry for that @roigcarlo

I guess I know the reason now. Sorry again.

**Comment by roigcarlo** [comment]
@ChengshunShang1996 no problem!

**Comment by rubenzorrilla** [comment]
Dear @KratosMultiphysics/all,

This is a reminder to the attendees to register. Note that event has a limited number of places and we are close to run out of them.

**Comment by loumalouomega** [comment]
I will close this issue, BTW, we should share in some manner our e-mails to keep contact.
