### ISSUE TITLE
[GeoMechanicsApplication] Phreatic error with discontinuous geometry

### ISSUE THREAD

**Issue by EleniSmyrniou** [KratosMultiphysics/Kratos#10290]
As a user, I would like to be able to apply a multiple-point phreatic line, such that I can model water pressure fields.

### Description 

When multiple phreatic lines are assigned to a surface it seems that the first point in the left is always extrapolated to the right. As it can be seen in the figures bellow.

![image](https://user-images.githubusercontent.com/51239334/191244261-cd39011b-bfb5-43f2-9090-32389366d332.png)

![image](https://user-images.githubusercontent.com/51239334/191244342-d36dc1d2-2428-4bef-820c-19ebf74a77d9.png)

**Comment by EleniSmyrniou** [comment]
The problem can be found in apply_scalar_constrain_table_process.py in function CalculatePressure.
In this case when the node is outside of the phreatic line the pressure gets extrapolated. This makes assigning different phreatic lines in the same surface order dependent

**Comment by mcgicjn2** [comment]
Fixed for constant pressure

![image](https://user-images.githubusercontent.com/9568573/193248160-cab5a334-8f90-4ce4-a809-d834072bcb79.png)

**Comment by mcgicjn2** [comment]
Also added phreatic multi line table process .... i.e. varies in time

**Comment by mcgicjn2** [comment]
The PR was closed so that @WPK4FEM and @avdg81 can complete there changes to the underlying functionalities before reimplementation.
