### ISSUE TITLE
[Wheels] Should we remove Python3.6 and add 3.11 for the next release?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#10331]
https://github.com/KratosMultiphysics/Kratos/blob/29d4910e1d69cd9618fef74c11bb9a8d7bb3a618/scripts/wheels/linux/build.sh#L2

Just asking

**Comment by roigcarlo** [comment]
I would remove 3.6 and 3.7, but I am not sure about adding 3.11 because we havn't tested it. In any case, lets wait until an official version comes for adding it to the release. RC are not included in the repos I use in the builders.

**Comment by loumalouomega** [comment]
Is still RC?, I thought it was final.

**Comment by roigcarlo** [comment]
Last version I am aware of is 3.11.0rc2 (from 12/9/22)

**Comment by loumalouomega** [comment]
> Last version I am aware of is 3.11.0rc2 (from 12/9/22)

You are right, well, as you are already aware I will close this
