### ISSUE TITLE
Update DAMApplication Status

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#10364]
Dear @KratosMultiphysics/dam

Currently DAMapplication is included in the release list, but is not compiling and not present in the CI, which is causing the pip installation to break.

We have been able to fix this but we would need you to either to add the app to the CI list or remove it from the release list.

**Comment by joaquinirazabal** [comment]
Hi @roigcarlo, we can add the Dam application to the CI list.

Thank you and sorry for the inconvenience.
