### ISSUE TITLE
[GeoMechanicsApplication] Add heat transfer calculation to geomechanics application

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#10372]
**Heat transfer**
Add calculation for heat transfer for soil. We here start for heat transfer equation for fully saturated soil.

**TODO**
- [1] Define thermal element with element classes (empty)
- [2] Add the input variables needed for heat
- [3] Defind solver
- [4] Define strategy
- [5] Add dispersion matrix/law.
- [6] Build matrices, stiffness, right hand side, mass ...
- [7] Add boundary conditions (Neumann)
- [8] Add boundary conditions (Robin)
- [9] Make the boundaries (Dirichlet and Robin) time dependent.
- [10] Give output for GID
- [11] Fix bugs.

**Comment by rubenzorrilla** [comment]
About the thermal element, which is your plan? To do a strongly coupled displacement-energy formulation or to weakly couple the temperature field to the displacement one? If you plan to do the second one, you don't need to implement the thermal element, as it is already in the `ConvectionDiffusionApplication`. You'll only need to implement your custom coupled solver, indeed, @AlejandroCornejo already did some developments in this regard.

**Comment by mnabideltares** [comment]
@rubenzorrilla thank you for your suggestion.
We would like to add heat transfer in combination with deformation and ground water flow. However, at this step we only add the first part, namely the heat transfer.
Our heat equation is not a standard diffusion, but it has extra coefficients accounts for porosity saturation and variable density, heat capacity and heat conductivity. Our final target will be a strong coupling between those as it will be more stable.
Can we still use ConvectionDiffusionApplication for our purpose?

**Comment by rubenzorrilla** [comment]
Hi @mnabideltares.

In that case, I think you'll need to implement your own custom displacement-temperature-pressure element. Besides, the heat elements in the `ConvectionDiffusionApplication` solve the standard transient convection-diffusion equations. About the variable material properties, this can be done with no problems provided that you save them in the nodal database. Then you can have a custom process implementing the state equation to update the nodal values at the end of the step, that is at the `ExecuteFinalizeSolutionStep` execution point.

In any case, I think that this is a nice topic to be discussed at the workshop :wink:
