### ISSUE TITLE
[Core] Triangle3D6N area is incorrect

### ISSUE THREAD

**Issue by pablobecker** [KratosMultiphysics/Kratos#10377]
**Description**
Chapuza area and lenght computation.
Interestingly, it was correct before this commit
https://github.com/KratosMultiphysics/Kratos/commit/9239d8d328196928536f949151b505a818adfac5

**Scope**
- KratosCore

ping @ipouplana do you recall why this chapuza was made? if not, I'll revert this commit.

**Comment by ipouplana** [comment]
Sorry @pablobecker, but I don't remember why Lorenzo committed this change...
