### ISSUE TITLE
[Discussion] Keeping Track of Performance

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10391]
Performance considerations often come up during PR reviews but right now, we don't have any kind of system in place that would provide concrete data on the implications of changes made to Kratos. So, we're left with rules of thumb, beliefs, and tiny benchmarks torn out of context (I'm especially guilty of this one) that may lead to incomplete - or even incorrect - conclusions.

\+ I'm often simply curious just how much of an impact @loumalouomega 's improvements have 😆

What I'd suggest is to set up a repo that provides a framework to quantify Kratos' performance and archive it from time to time, so we'd have some reference to compare the current state to, or make comparisons between different commits/branches or even platforms. I'd set up this repo outside Kratos to avoid polluting it and drawing in unnecessary third party dependencies, and rely on anyone who's interested to write some benchmarks/profiling scripts, run them, and update the archive from time to time. This would give everyone a good idea about how Kratos performs over its development, on different platforms and hardware.

My question is whether anyone is interested in this. I'm willing to start setting it up but only if I know that I won't be the only one actually giving a damn.

**Comment by loumalouomega** [comment]
There is some work (or will be) in this regard, but dont know details.

**Comment by RiccardoRossi** [comment]
8 like the idea of a benchmark repo...but i would still be sure not to include things with problenatic licenses...

even though if in this case we do not need to distribute it possibly it may also include gpl or lgpl, as it will never be mixed with production code

**Comment by loumalouomega** [comment]
Just to say that in my experience Google Benchmarks works very well and is Apache2 license: https://github.com/google/benchmark

**Comment by matekelemen** [comment]
> Google Benchmarks

Yep, that's what I had in mind too. We don't even need to distribute it though, we can just require it as a dependency (most people interested in running a benchmark will have it already anyway) and use the one installed on the system.

I don't have much experience in profiling python tho. Any ideas?

**Comment by RiccardoRossi** [comment]
line profiler works nicely, even though it requires commenting the code.

@roigcarlo is currently in holidays, but he may be able to comment meaningfully once back.

in a y case my point is that if we do not depend on strange libs (the one ypu me tion look ok) then we could add a performance repo directly to the KratosMultiphysics organization

**Comment by dcagritan** [comment]
What about using Intel's VTune? I guess there was an effort to use day back in the day. Is it still a viable option?
Regards

**Comment by roigcarlo** [comment]
Yes is still possible, but Vtune will only report performance at shared lib level, so no insight in python code (it might be an option now, but if its the case I ignore how to use it).

**Comment by dcagritan** [comment]
Thank you for the answer @roigcarlo. I'll also check out Google Benchmarks. 
Regards

**Comment by dcagritan** [comment]
> Just to say that in my experience Google Benchmarks works very well and is Apache2 license: https://github.com/google/benchmark

@loumalouomega Have you already used Google Benchmarks in any Kratos Application? If your answer is yes, could you please provide that test case?
Regards

**Comment by roigcarlo** [comment]
On this line, linking what @matekelemen has done in #10552 because I think it pretty much covers everything we are discussing here

**Comment by dcagritan** [comment]
> On this line, linking what @matekelemen has done in #10552 because I think it pretty much covers everything we are discussing here

Thank you @roigcarlo. I'll check that one out.
Regards

**Comment by loumalouomega** [comment]
> > Just to say that in my experience Google Benchmarks works very well and is Apache2 license: [google/benchmark](https://github.com/google/benchmark)
> 
> @loumalouomega Have you already used Google Benchmarks in any Kratos Application? If your answer is yes, could you please provide that test case? Regards

I used for pure C++ projects
