### ISSUE TITLE
Trim some branches

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1041]
Dear devs, I have detected that there is a unusual high number of open branches associated with PR that have been already merged or are inactive:

Let's begin with the already merged ones:
~~@adityaghantasala: https://github.com/KratosMultiphysics/Kratos/tree/multipoint_constraints~~
@GuillermoCasas: https://github.com/KratosMultiphysics/Kratos/tree/DEM-debug-search-radius-issue
~~@loumalouomega: https://github.com/KratosMultiphysics/Kratos/tree/hotfix-problem-type-retrocompabilty~~
~~@KlausBSautter: https://github.com/KratosMultiphysics/Kratos/tree/feature-add-work-equiv-lineload3D~~
~~@roigcarlo: https://github.com/KratosMultiphysics/Kratos/tree/hotfix-fix-testing-files (woops thats mine!)~~

Would you please tell me if we can delete those?

**Comment by loumalouomega** [comment]
Done, sorry

**Comment by KlausBSautter** [comment]
Hey @roigcarlo  I would like to keep https://github.com/KratosMultiphysics/Kratos/tree/feature-add-work-equiv-lineload3D as I will continue working on this after the release. thanks :)

**Comment by roigcarlo** [comment]
@KlausBSautter Ok thx!

**Comment by adityaghantasala** [comment]
Regarding the branch of multipoint_contraints : 
I would also keep this one as there are already performance enhancements and simplifications on the way.

**Comment by roigcarlo** [comment]
@adityaghantasala thx! :+1:
