### ISSUE TITLE
StructuralMechanics should use Kratos Model instead of a python dictionary

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1045]
the title says it all.

I am scheduling it for Release 5.3 since it may break the GUI

**Comment by loumalouomega** [comment]
Where are we using a dictionary instead of Model?

**Comment by RiccardoRossi** [comment]
in the MainKratos.py

**Comment by loumalouomega** [comment]
OK, I see:
![imagen](https://user-images.githubusercontent.com/19991680/32989447-66f86adc-cd16-11e7-90cc-8c0439801e33.png)
In the fluid main script too:
![imagen](https://user-images.githubusercontent.com/19991680/32989449-73ff6f78-cd16-11e7-9f87-c044b0151146.png)

**Comment by josep-m-carbonell** [comment]
@KratosMultiphysics/technical-committee, it concerns only to StructuralApp or to all applications? The use of this python list called Model  was forced to the constructors of all python processes. Is it going to change now?

**Comment by loumalouomega** [comment]
@josep-m-carbonell I was thinking the same, most of the processes use the Model as python dictionary, in order to avoid breaking the current implementation the behaviour of the Model class should be compatible with a python dictionary.

Besides, in which file is the model implemented?

The model.h of containers?

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/33013593-e4b31156-cde4-11e7-9ad7-869d49d98b28.png)
this is the current implementation, I propose to add the operators [] to be retrocompatible

**Comment by loumalouomega** [comment]
Ok, there is a operator [], sorry for the noise, the implementation can be seen in test_model.py in the tests folder:
![imagen](https://user-images.githubusercontent.com/19991680/33013974-0691e7d8-cde6-11e7-9682-6e11c23e243b.png)

**Comment by loumalouomega** [comment]
@josep-m-carbonell I did it in #1053, is easy, just 3 lines and 100% retrocompatible

**Comment by RiccardoRossi** [comment]
@josep-m-carbonell the change should be completely compatible with current implementation, since it exposes an identical interface. The only point is that the current interface (both the pure-python one and the one implemented in model **cannot be considered as definitive**...)

@loumalouomega you are right (and i was wrong, jeje). Current implementation still needs the lines in which the models are added manually. I will send you privately a fix so that you can send it and eventually commit it as a part of this branch, (i cannot change branch locally right now)

**Comment by loumalouomega** [comment]
OK
