### ISSUE TITLE
Nearest element mapper - non-consistent value n MPI

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#10464]
I was doing a test for the nearest element mapper. I took a case where the mesh was conformant and moved one node a little so the nearest neighbour mapper would detect it as non-conformant.

What I have found is that while running in mpi the value on the other side of the mesh (the side that was not modified) is changing depending on the number of cores (very significantly). Is this an "expected" behaviour? I tried to debug it a little but I could not completely follow the code, especially in MPI. @philbucher Could you give me any guidance on how to debug it or anything I could try?

I upload the test with the mdpa just for reference.

**Comment by ddiezrod** [comment]
[test_mapper.zip](https://github.com/KratosMultiphysics/Kratos/files/10032657/test_mapper.zip)

**Comment by philbucher** [comment]
so just to understand, the problem is that values in the origin modelpart are being modified during mapping?
In your example you use inversemap, so the values there should change

Can you also comment on how the values change and what can be done to reproduce the problem?

**Comment by ddiezrod** [comment]
Sorry for the poor explanation. I basically have two conforming meshes except for two nodes (id 313 on solid side and 122 on liquid side) which are in a slightly different position. I am using the nearest element mapper to map values from solid to liquid. After mapping, all values are exactly the same as the one on the mold side except for 122. This is normal as it does not coincide exactly with its correspondent node.

If I run the problem in serial the value on this node (122) is 0.00093982 which makes sense more or less as the value on 313 is 0.001. The problem is that when I run this in MPI the value of this node changes depending on the number of cores.
- With 8 cores, the value is 0.00093982 which is correct in principle as it is the same value that we got in serial.
- With 4 cores, the value I get is -4.754481e-05 so obviously the test fails there.

I guess that this means that in MPI it is reading its value from a different element so that looks like a possible error in the code. Maybe I am missing something in the test too... Is there a way to see which element is being used for each node? I dont mind  debugging a long print I do not even know where to put those prints :D

**Comment by mpentek** [comment]
I am interested in this issue. Throwing one more aspect into the discussion, could this be related also to small numbers?...

**Comment by philbucher** [comment]
It could be that the search is only finding an approximation 

Did you increase the echo level and check the search output?

Try increasing the search radius

**Comment by ddiezrod** [comment]
Ok, I think I got some information about what is going on. I ran again the cases with 4 and 8 cores. The status at the end seem to be fine for both cases.

With 8 cores:
```
Mapper search: search radius was increased, another search iteration is conducted
    search iteration: 5 / 6 | search radius: 0.0223562
Mapper search: An average of 2 objects was found while searching
Mapper search: current status:
    225 / 225 (100 %) local systems are done searching
    0 / 225 (0 %) local systems found only an approximation
    0 / 225 (0 %) local systems did not find a neighbor
Mapper search: Search iteration took 0.000270946 [s]
```

With 4 cores:
```
Mapper search: search radius was increased, another search iteration is conducted
    search iteration: 6 / 7 | search radius: 0.027661
Mapper search: An average of 7 objects was found while searching
[ad5cfc760c76:00315] Read -1, expected 6564, errno = 1
[ad5cfc760c76:00315] Read -1, expected 6900, errno = 1
[ad5cfc760c76:00315] Read -1, expected 5154, errno = 1
Mapper search: current status:
    225 / 225 (100 %) local systems are done searching
    0 / 225 (0 %) local systems found only an approximation
    0 / 225 (0 %) local systems did not find a neighbor
Mapper search: Search iteration took 0.000784994 [s]
```

But the initial radius in both cases is different, leading to different results. If I manually set the search radius to 0.00071831 (which is the value that I get by default with 8 cores) then the test is again consistent in serial and in mpi for any number of cores.

**Comment by philbucher** [comment]
The search radius is computed based on how the search bins partition the domain. 

Therefore it is different when using different number of cores

This is highly tuned towards it being fast, as previously it was more conservative but slow.

Maybe we could multiply the radius with a factor (e.g. 1.1) to improve the behavior 
I want to keep it as small as possible since this has a huge impact on the performance, especially for volume mapping.

Note that this happens because I am satisfied once an approximation is found (which is what happens in your case).
I am then excluding this entity from future search iterations.

**Comment by loumalouomega** [comment]
> The search radius is computed based on how the search bins partition the domain.
> 
> Therefore it is different when using different number of cores
> 
> This is highly tuned towards it being fast, as previously it was more conservative but slow.
> 
> Maybe we could multiply the radius with a factor (e.g. 1.1) to improve the behavior I want to keep it as small as possible since this has a huge impact on the performance, especially for volume mapping.
> 
> Note that this happens because I am satisfied once an approximation is found (which is what happens in your case). I am then excluding this entity from future search iterations.

Maybe instead of hardcoding I can just simply set it manually, I will try and see

**Comment by philbucher** [comment]
manually setting it is already possible

the issue is the automatic computation

**Comment by loumalouomega** [comment]
> manually setting it is already possible
> 
> the issue is the automatic computation

Yes, yes, it was like a comment to myself

**Comment by loumalouomega** [comment]
> manually setting it is already possible
> 
> the issue is the automatic computation

Doesn't solve the problem :P

**Comment by ddiezrod** [comment]
I have been thinking about this and even if I do not like it the result depends on the number of cores, at the end probably we can live with this from the more practical point of view. If you are ok with this we can close the issue @philbucher
