### ISSUE TITLE
creating higher order mesh

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10469]
During the recent workshop I remember that @pooyan-dadvand , was saying that a higher order mesh (including interface elements) can be generated from a lower order mesh. Did I understand this correctly, and if so, where can I find an example on how to do this?

**Comment by rubenzorrilla** [comment]
I think #10045 is the PR implementing the utility to generate a quadratic tetrahedral mesh from a simplex one. @pooyan-dadvand can you confirm?

**Comment by ddiezrod** [comment]
Adding also @pablobecker as he was working on this too.

**Comment by pablobecker** [comment]
please note that as @rubenzorrilla said, this only supports turning tet4 meshes into tet10

**Comment by rubenzorrilla** [comment]
Closing as it seems to be solved. @aronnoordam feel free to reopen if any issue pops up while using the utility.
