### ISSUE TITLE
Memory leak when computing

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#1046]
The last days I have been running some cases with my application (FemDem), which is derived from Solid and I have noticed that at each time step a memory leak occurs. I have checked everything and it seems that the problem appears when the code performs the Build() and the SystemSolveWithPhysics function.

Additionally, I have tried to calculate with the SmallDisplacementElement and everything is ok.

I have checked also with MA Celigueta this issue with linux (I use windows) and there is no memory leak in linux.

In conclusion, the only difference between the MA Celigueta case and mine is the OS and the fact that I have several compiling warnings that may be generating this problem. The warnings have the following text, in general:
*****************************
Severity	Code	Description	Project	File	Line
Warning	C4273	'round': inconsistent dll linkage (compiling source file D:\FemDem\applications\DEM_application\custom_python\add_custom_utilities_to_python.cpp)	KratosDEMApplication	c:\python34\include\pymath.h	22
************************

Anyone knows how to avoid these warnings?

Currently I'm using Python34 and boost_1_59_0.

Regards,

Alejandro

**Comment by maceligueta** [comment]
Referencing @roigcarlo ...

**Comment by RiccardoRossi** [comment]
hi Alejandro,

just to be sure, did u try to compile using "FullDebug"?

just to see if anything strange is detected....

also i would try to limit the use of openmp to ome thread to see if you get the same behaviour

**Comment by roigcarlo** [comment]
I can tell you about the linking warning: That tipically happens in windows if more than one system lib is implemeting the round function. 

This happens if you have more than one visual studio version at the same time, or if you have CUDA + Visual studio, or some other combinations. It is bad if you intend to build redistributable packages, but other than that and being anoing is "safe".

You can remove the warning compiling with 'HAVE_ROUND' defined (add -DHAVE_ROUND to the configure). That should help.

About the error, if fulldebug doesn't show anything strange, could you send us a small example and the branch you are using so we can debug?

**Comment by maceligueta** [comment]
I already ran a test case with the branch and memory does not increase in linux (OpenSuse).

**Comment by roigcarlo** [comment]
But problem is in win if I understood correctly? I can set it up in my machine or in the laptop we use for the releases... Or if it can wait we can look at it this Monday in Alejandro's computer

**Comment by maceligueta** [comment]
Yes, the problem was detected in Windows.

**Comment by RiccardoRossi** [comment]
@maceligueta if you run in linux, are u also adding manually the -GLIBCXX_DEBUG option?
it the valgrind output clean? (i know these are obvious things ... i just don't have any clue of what the problem could be)

**Comment by maceligueta** [comment]
GLIBCXX_DEBUG was activated and valgrind said nothing, as far as I could see. More thant than, with a regular run out of valgrind the memory was not increasing at all.

**Comment by AlejandroCornejo** [comment]
Good morning,

I haven't compiled the code in Full debug because you told me that it is
quite difficult to achieve in windows so I use the RelWithDebugInfo. I have
tried to run the case with 1 thread and the behaviour is the same.

If you want I can bring you my laptop to see what's happening @roigcarlo 

Regards

**Comment by roigcarlo** [comment]
Yep, bring me the laptop and we can debug there :+1:

**Comment by AlejandroCornejo** [comment]
Just in case another person has the same problem, the problem was solved merging my code to the newest version of kratos.

**Comment by rubenzorrilla** [comment]
@AlejandroCornejo  can we close the issue then?

**Comment by AlejandroCornejo** [comment]
Yes sure, thank you for your help.
