### ISSUE TITLE
How can nodal values be extrapolated or interpolated from one model part to another?

### ISSUE THREAD

**Issue by SADPR** [KratosMultiphysics/Kratos#10485]
**Description**
I have a Fluid Dynamics' velocity field solution with its corresponding model part, and want to interpolate the values to a coarser mesh to solve a convection-diffusion problem. I founded in MeshingApplication the process "[nodal_values_interpolation_process.cpp](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/custom_processes/nodal_values_interpolation_process.cpp)", but I have not being able to achieve the interpolation. 

To accomplish this, I am importing my fluid model part into the convection-diffusion analysis stage and setting the velocity state (imported as a numpy array). Then, my convection-diffusion model part is set to be my destination model part and my fluid model part is set to be my origin model part. The process does not appear to interpolate the values to my destination model part when executed.

Currently, I have my own Python interpolation that works fast and accurate for simple geometries, but it presents some errors at some nodes in complicated 3D cases. As a result, I was wondering if the aforementioned process should work, and also if the MappingApplication had something similar to this process. Here is a visual representation of what I intend to do:

**Fluid Mesh:**
![ezgif com-gif-maker (5)](https://user-images.githubusercontent.com/61457043/203606346-5a2286f6-ead4-4ebb-bab9-f3a6abfb3d05.gif)

**Convection-Diffusion Mesh:**
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/61457043/203605647-1df6e59b-e5ea-426e-89dc-8fe5f22cf5d0.gif)

**Comment by loumalouomega** [comment]
There is one process in the MeshingApp that may be moved to the Core:

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/custom_processes/nodal_values_interpolation_process.cpp

**Comment by loumalouomega** [comment]
> There is one process in the MeshingApp that may be moved to the Core:
> 
> [`master`/applications/MeshingApplication/custom_processes/nodal_values_interpolation_process.cpp](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/custom_processes/nodal_values_interpolation_process.cpp?rgh-link-date=2022-11-23T17%3A20%3A09Z)

What problem did you have? (it is used in remeshing and it works and it is tested)

**Comment by philbucher** [comment]
This is exactly what the nearest element mapper does

Works in 2D & 3D and also in MPI

**Comment by rubenzorrilla** [comment]
> This is exactly what the nearest element mapper does
> 
> Works in 2D & 3D and also in MPI

But does the nearest element mapper also work with volumetric meshes? i.e. to transfer values from tetrahedra to tetrahedra?

**Comment by philbucher** [comment]
It does :)

**Comment by loumalouomega** [comment]
> It does :)

I will try to replace my process with your mapper, problem is that it generates an additional dependency (MappingApp), maybe I can check if the app is imported and then use Mapping. What do you think @marcnunezc ?

**Comment by marcnunezc** [comment]
> > It does :)
> 
> I will try to replace my process with your mapper, problem is that it generates an additional dependency (MappingApp), maybe I can check if the app is imported and then use Mapping. What do you think @marcnunezc ?

Yes I think it is a good change to start using the MappingApp. In fact the [ParMmg examples ](https://github.com/KratosMultiphysics/Examples/blob/818767e383924020a9969e408eede6397e4afa01/parmmg_remeshing_examples/use_cases/body_fitted_hessian_cylinder3D/source/MainKratos.py#L94-L100) use the MappingApplication at python level as it works in MPI :).

**Comment by loumalouomega** [comment]
> > > It does :)
> > 
> > 
> > I will try to replace my process with your mapper, problem is that it generates an additional dependency (MappingApp), maybe I can check if the app is imported and then use Mapping. What do you think @marcnunezc ?
> 
> Yes I think it is a good change to start using the MappingApp. In fact the [ParMmg examples ](https://github.com/KratosMultiphysics/Examples/blob/818767e383924020a9969e408eede6397e4afa01/parmmg_remeshing_examples/use_cases/body_fitted_hessian_cylinder3D/source/MainKratos.py#L94-L100) use the MappingApplication at python level as it works in MPI :).

I assume it :)

**Comment by philbucher** [comment]
> Thanks to everyone, I discovered that I was making a mistake when setting the velocity values, I was setting the value with SetValue() on the original model part (fluid) and then expecting it to interpolate the value as if I had set it with SetSolutionStepValue() on the destination model part (convection-diffusion).

That can also be done with the MappingApp, I recommend to look at the readme, everything should be well described there

**Comment by philbucher** [comment]
@loumalouomega @marcnunezc I agree that this might be an unwanted dependency. 
FYI: In the long run the mapper should be integrated into the core. In fact, the interface is already there. The main issue I see with MPI is that it still depends on Trilinos, making it nasty to integrate in other Apps. Eventually I want to refactor it to use the new Kratos CSR matrix, then using it in other Apps will be easy

**Comment by sunethwarna** [comment]
Just an idea, what if we use the registry to register mappers as well, so it can be used in cpp and python levels and it does not matter where it is located.
