### ISSUE TITLE
Occacional test failure: test_interpolate_particles (test_particles_utilities.TestParticlesUtilities

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#10498]
**Description**
This test fails occasionally, maybe a tolerance problem?

~~~
 FAIL: test_interpolate_particles (test_particles_utilities.TestParticlesUtilities)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/Release/kratos/tests/test_particles_utilities.py", line 92, in test_interpolate_particles
    self.assertEqual(is_inside[1], True)
AssertionError: False != True
~~~

**Comment by pablobecker** [comment]
adding extra info from duplicated issue:

Description
The particles utilities is failing randomly. See https://github.com/KratosMultiphysics/Kratos/actions/runs/3681636447/jobs/6228524005
In that case it's failing in line 83, while on our side we had it failing also in line 92, so both the historical and non historical versions are affected. Not sure if it is restricted to the 2D version, but both fails happened in 2D.
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/test_particles_utilities.py#L83

Scope

Since it's failing when trying to find the point (before the interpolation itself) I'd say the bug is actually in the binbasedfastpointlocator, but it is strange

To Reproduce
Run the faling test, but it fails randomly

Expected behavior
Fails to find element containing the point

Environment
Ubuntu and Fedora

**Comment by pablobecker** [comment]
the points failing are well located, far away from the edges of the elems, so i don't think it's a tolerance issue

**Comment by RiccardoRossi** [comment]
my guess is that it is at the rim of a cell in the bin

**Comment by pablobecker** [comment]
just checked how the bins is configured, and it is not in the edge of a cell, These are the params that are being used by the bins:
mMaxPoint 1.01 1.01 0
mMinPoint -0.01 -0.01 0
mCellSize 0.51 0.51 1.96078
the z cell size is kinda magical, but it should not be used (i guess)

one more thing. it also fails randomly in fulldebug

**Comment by pablobecker** [comment]
live update : following @loumalouomega suggestion, i tried with 1 thread. it never fails. now checking where is the issue

**Comment by pablobecker** [comment]
I was able to locate the problem in this loop, if i turn it into serial code, it works
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/particles_utilities.h#L258
@RiccardoRossi can you take a look to see if there's something strange?

**Comment by loumalouomega** [comment]
> I was able to locate the problem in this loop, if i turn it into serial code, it works [`master`/kratos/utilities/particles_utilities.h#L258](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/particles_utilities.h?rgh-link-date=2022-12-15T15%3A21%3A26Z#L258) @RiccardoRossi can you take a look to see if there's something strange?

Taking a look at the code I would make some of those private to ensure that the threads are not modifying them. Particularly `rLocator`

**Comment by loumalouomega** [comment]
> > I was able to locate the problem in this loop, if i turn it into serial code, it works [`master`/kratos/utilities/particles_utilities.h#L258](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/particles_utilities.h?rgh-link-date=2022-12-15T15%3A41%3A35Z#L258) @RiccardoRossi can you take a look to see if there's something strange?
> 
> Taking a look at the code I would make some of those private to ensure that the threads are not modifying them. Particularly `rLocator`

Or `intersections`

**Comment by RiccardoRossi** [comment]
rLocator cannot be private...

**Comment by loumalouomega** [comment]
> rLocator cannot be private...

It was  the most obvious one. In any case if you can copy you can make it private

**Comment by philbucher** [comment]
It seems like the PointLocator is not threadsafe

Can you pass it as const to the fct? That might already give a hint where the problem is

**Comment by loumalouomega** [comment]
> It seems like the PointLocator is not threadsafe
> 
> Can you pass it as const to the fct? That might already give a hint where the problem is

Compilation fails, and it is not threadsafe, the cells are modified...

**Comment by pablobecker** [comment]
fixed!

https://github.com/KratosMultiphysics/Kratos/pull/10565

it was painful to find but resolved. learned about this the hard way

**Comment by philbucher** [comment]
closing since it is fixed
