### ISSUE TITLE
Error installing Kratos with pip

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#10505]
It's possible to install and import Kratos, but there is an error

![image](https://user-images.githubusercontent.com/25640870/204273986-fb35de52-1598-4c42-82d5-911e939c7582.png)

**Scope**
E.g.
- pip install
- Windows

**Comment by loumalouomega** [comment]
@roigcarlo

**Comment by loumalouomega** [comment]
(looks like you need to activate the long path in Windows 10): https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=powershell

**Comment by roigcarlo** [comment]
Yep, Its a known issue, but I am afraid no other solution aside from what @loumalouomega suggested :/
