### ISSUE TITLE
Line condition cannot be applied in a 3D space

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10519]
A line condition cannot be applied in a 3D space in the Geomechanics application. During the calculation, neighbour elements of the condition are searched. In this procedure, faces of the model elements are compared to the line condition elements. However, 3D elements do not contain line faces, thus neighbour elements cannot be found and the calculation does not continue

**Comment by Vahid-Galavi** [comment]
I will check this and let you know

**Comment by loumalouomega** [comment]
A 3D geometry contains faces, and the faces contain edges.

**Comment by Vahid-Galavi** [comment]
@aronnoordam do you have a test/example that I can use?

**Comment by aronnoordam** [comment]
I will create a simple test tomorrow. Thanks for looking at it

**Comment by loumalouomega** [comment]
I am seeing there is an inconsistent implementation, 3D geometries implement GenerateFaces, but not GenerateEdges. We need to do something about

**Comment by aronnoordam** [comment]
@loumalouomega are you refering to the Core or GeomechanicsApplication?

**Comment by loumalouomega** [comment]
Core, so that will help you too

**Comment by Vahid-Galavi** [comment]
This issue is solved in #10540 can be closed.
