### ISSUE TITLE
Error importing modelers

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#10514]
**Description**
The pip installation is missing the python modelers:
```sh
ModuleNotFoundError: No module named 'KratosMultiphysics.modelers'
```

because the folder `Python310\lib\site-packages\KratosMultiphysics` does not contain `modelers`

**Scope**
- pip distribution
- KratosCore

**To Reproduce**
```json
"modelers"         : [{
        "modeler_name"  : "import_mdpa_modeler",
        "kratos_module" : "KratosMultiphysics",
        "Parameters"    : {
            "echo_level"      : 0,
            "input_filename"  : "mastil",
            "model_part_name" : "FluidModelPart"
        }
    }
```

**Expected behavior**
The modeler should be imported

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Windows10
- Branch: pip distribution
- Python 3.10

**Comment by miguelmaso** [comment]
Ping @roigcarlo

**Comment by roigcarlo** [comment]
It will be solved in the next Release, the problem is that modelers didn't existed for 9.2.2

**Comment by miguelmaso** [comment]
Thanks @roigcarlo !
