### ISSUE TITLE
[Trilinos] Link Error on Import

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10536]
## Description
```py
import KratosMultiphysics.TrilinosApplication
```
```
 |  /           |                  
 ' /   __| _` | __|  _ \   __|    
 . \  |   (   | |   (   |\__ \  
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.2."2"-404cc90-RelWithDebInfo-x86_64
           Compiled for GNU/Linux and Python3.10 with Clang-14.0
Compiled with threading and MPI support.
Maximum number of threads: 16.
Running without MPI.
Process Id: 53506 
Importing    KratosMetisApplication 
    KRATOS  __  __      _   _
           |  \/  | ___| |_(_)___
           | |\/| |/ _ \ __| / __|
           | |  | |  __/ |_| \__ \
           |_|  |_|\___|\__|_|___/
Initializing KratosMetisApplication...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kelemen/python_venv/kratos_release/lib/python3.10/site-packages/KratosMultiphysics/TrilinosApplication/__init__.py", line 6, in <module>
    from KratosTrilinosApplication import *
ImportError: /usr/lib/libzadelus.so.13: undefined symbol: _ZN6Adelus10nprocs_colE
```

It's been like this for a couple of weeks now but I don't exactly now when it broke; maybe @sunethwarna knows better. No idea what the `Adelus` library is, and google doesn't help much either ([this](https://groups.google.com/g/dealii/c/uTkQoj7NYcM) is the most relevant link). Any ideas what's going on? Is this on our side (unlikely)?

The weird thing is that it compiles alright but fails to link this `libzadelus` library correctly when loading the python bindings.

## System
- OS: Manjaro with latest updates, Kernel 5.15.81-1
- Branch: master
- Python 3.10.8
- Trilinos: [latest from the AUR](https://aur.archlinux.org/packages/trilinos)

**Comment by sunethwarna** [comment]
Ok, I found a solution. We have to compile trilinos without the `Adelus`.

In manjaro, you can clean install the trilinos with modified `PKGBuild` file with following cmake flag.
```cmake
-DTrilinos_ENABLE_Adelus:BOOL=OFF
```

Then this can be rectified for the time being. But the original solution should come from the Trilinos side. Until then we can disable it and use Trilinos with `Kratos`.

**Comment by loumalouomega** [comment]
If you consider we can close, otherwise we can update the FindTrilinos

**Comment by matekelemen** [comment]
Technically, it solves the problem, but it's more of a hack than a permanent solution so I'd leave this open until Trilinos fixes their stuff.

**Comment by loumalouomega** [comment]
> Technically, it solves the problem, but it's more of a hack than a permanent solution so I'd leave this open until Trilinos fixes their stuff.

I think is more in our side, and we need to consider the possibility of supporting different Trilinos versions (painful, but probably necessary). This means a CMake file with a lot of checks and ifs

**Comment by philbucher** [comment]
Why do we need to modify FindTrilinos?

We are not using this library

**Comment by loumalouomega** [comment]
> Why do we need to modify FindTrilinos?
> 
> We are not using this library

We can notify to the user for example, or we can install it if we consider it is simpler than tell the user to compile without it, so the linking error doesn't appear

**Comment by philbucher** [comment]
how about adding a check in CMake saying that this version is not supported?

**Comment by matekelemen** [comment]
Well, it was unique to a version packaged for the AUR that moved on to Trilinos 14 already (which solves the issue), so I'm not sure whether it really is necessary.
