### ISSUE TITLE
Line3D3 ShapeFunctionsValues method is missing in line_3d_3.h 

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10530]
Line3D3 ShapeFunctionsValues method is missing in line_3d_3.h. Is this intended? Or is it actually missing?

**Comment by loumalouomega** [comment]
It is not intended. The geometries are implemented as needed. If unfortunately until now no one use it the line3D3 shape functions therefore the implementations is missing. Luckily, should be same as Line2D3

**Comment by aronnoordam** [comment]
> Fixed in #10532

Great!
