### ISSUE TITLE
Length() in line_3d_3.h is calculated with wrong node ordering

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10538]
Length() in line_3d_3.h is calculated with wrong node ordering

Currently the length of the element is calculated, using node 0 and node 2. While node numbering of the line3d3 element is:
0---2---1.

Correct length should be calculated with node 0 and node 1

**Comment by loumalouomega** [comment]
In fact that is not even correct, a quadratic line is a parabola, not a straight line

**Comment by aronnoordam** [comment]
In that case I would copy the function as written in line_2d_3.h

**Comment by loumalouomega** [comment]
> In that case I would copy the function as written in line_2d_3.h

I am on it, PR on the way

**Comment by aronnoordam** [comment]
great

**Comment by loumalouomega** [comment]
> In that case I would copy the function as written in line_2d_3.h

And if you just copy the method will not work as DeterminantOfJacobian is not defined
