### ISSUE TITLE
Discussion about migrate boost::python to pybind

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#1055]
Greetings, I have discover recently the library pybind, designed to not depend of boost::python

https://github.com/pybind/pybind11

I spoke with @RiccardoRossi and we agree to start a discussion if we are interested in the long term to migrate in order to not depend or depend the less possible of boost

In my opinion it is possible and not very painful if we first create an API just for using python in Kratos usign boost, and then change the API implementation to pybind. For example:

~~~c
#define KRATOS_USING_PYTHON using namespace boost::python;
~~~

And replace it in a future for re pybind

**Comment by oberbichler** [comment]
👍 
I am using pybind for a while in combination with the Eigen library and was very impressed by the simple handling. Specially the easy building and the automatic conversions for Eigen/Numpy/std-containers are very practical.

**Comment by roigcarlo** [comment]
:+1: For the idea of defining that macro, as a first step

**Comment by pooyan-dadvand** [comment]
I should take a look at this. Meanwhile adding it to the global plan

**Comment by maceligueta** [comment]
At the @KratosMultiphysics/technical-committee  we see this option very interesting. But boost is being used for other things as well. Pointers, matrices, and other boost objects. As soon as we finish this dependence, we will be able to switch from boost::python to pybind. 
We close this issue, but add the task in Projects (Global Plan).

**Comment by maceligueta** [comment]
The good part of not using boost is that we would not worry about versions and stability of boost. Pybind can be included in the Kratos repo so compatibility would be ensured from our side.
