### ISSUE TITLE
[Core] particles utilities failing randomly (uninit var??)

### ISSUE THREAD

**Issue by pablobecker** [KratosMultiphysics/Kratos#10553]
**Description**
The particles utilities is failing randomly.  See https://github.com/KratosMultiphysics/Kratos/actions/runs/3681636447/jobs/6228524005
In that case it's failing in line 83, while on our side we had it failing also in line 92, so both the historical and non historical versions are affected. Not sure if it is restricted to the 2D version, but both fails happened in 2D.
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/test_particles_utilities.py#L83

**Scope**

Since it's failing when trying to find the point (before the interpolation itself)  I'd say the bug is actually in the binbasedfastpointlocator, but it is strange

**To Reproduce**
Run the faling test, but it fails randomly

**Expected behavior**
Fails to find element containing the point

**Environment**
Ubuntu and Fedora

ping @RiccardoRossi @pooyan-dadvand @roigcarlo

**Comment by loumalouomega** [comment]
@pablobecker, have you tried to run with Valgrind? Sounds like a memory error

**Comment by pablobecker** [comment]
no, i dont have a linux virtual machine /docker  to give it a try

**Comment by loumalouomega** [comment]
> no, i dont have a linux virtual machine /docker to give it a try

Okay

**Comment by philbucher** [comment]
see also #10498

**Comment by pablobecker** [comment]
oh, sorry, i missed yours. I'll close this one and add the info there
