### ISSUE TITLE
[GeomechanicsApplication] Von Misis stress cannot be outputted on gauss points when UDSM interface elements are present

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10593]
Von Misis stress cannot be outputted on gauss points when UDSM interface elements are present. 

Is this expected behaviour?

**Comment by loumalouomega** [comment]
I would put this issue in the Gid interface instead. FYI @jginternational

**Comment by aronnoordam** [comment]
@loumalouomega. Sorry I gave a wrong definition, the issue is not the Gid interface, but output in general.  The issue lies in the Cpp code. When in the projectparameters, it is written that the VonMisisStress should be outputted on gauss_points, the code tries to access VonMisisStress  in the UDSM interface elements, while this is not present

**Comment by loumalouomega** [comment]
Huuum, should work, at least in my experience when using contact conditions (equivalent to your interface conditions) the stresses were outputed. The best way to check it would be to generate a minimal case that doesn't work, using if possible only conditions and elements of the StructuralMechanicsApplication

**Comment by aronnoordam** [comment]
`Vector& SmallStrainUDSM3DLaw::GetValue( const Variable<Vector> &rThisVariable, Vector &rValue )
{
   // KRATOS_INFO("0-SmallStrainUDSM3DLaw::GetValue()") << std::endl;

   if (rThisVariable == STATE_VARIABLES)
   {
      if (rValue.size() != mStateVariablesFinalized.size())
         rValue.resize(mStateVariablesFinalized.size());

      noalias(rValue) = mStateVariablesFinalized;
   }
   else if (rThisVariable == CAUCHY_STRESS_VECTOR)
   {
      if (rValue.size() != mStressVectorFinalized.size())
         rValue.resize(mStressVectorFinalized.size());

      noalias(rValue) = mStressVectorFinalized;
   }

   // KRATOS_INFO("1-SmallStrainUDSM3DLaw::GetValue()") << std::endl;

    return rValue;
}

//----------------------------------------------------------------------------------------
double& SmallStrainUDSM3DLaw::GetValue( const Variable<double>& rThisVariable, double& rValue )
{
   // KRATOS_INFO("01-SmallStrainUDSM3DLaw::GetValue()") << std::endl;

   const int index = GetStateVariableIndex(rThisVariable);

   KRATOS_DEBUG_ERROR_IF( index < 0 || index > (static_cast<int>(mStateVariablesFinalized.size()) - 1) )
                        << "GetValue: Variable: "
                        << rThisVariable
                        << " does not exist in UDSM. Requested index: " << index << std::endl;

   rValue = mStateVariablesFinalized[index];`

**Comment by aronnoordam** [comment]
i think the issue lies in the Geomechanics application, as calculating the VonMisisStress is not implemented for the small_strain_udsm_3D_law

**Comment by loumalouomega** [comment]
> i think the issue lies in the Geomechanics application, as calculating the VonMisisStress is not implemented for the small_strain_udsm_3D_law

Looks like, luckily it is relatively easy to implement

**Comment by Vahid-Galavi** [comment]
`VON_MISES_STRESS` is calculated inside all "volume" elements of GeomechanicsApp in function `void CalculateOnIntegrationPoints( const Variable<double>& rVariable, std::vector<double>& rOutput,  const ProcessInfo& rCurrentProcessInfo )`. 
For interface elements this is not done as we are usually interested in the normal and shear stresses along the interface (contact) and not the deviatoric stress. Of course this can simply be done but I do not really see its benefit.

**Comment by loumalouomega** [comment]
> `VON_MISES_STRESS` is calculated inside all "volume" elements of GeomechanicsApp in function `void CalculateOnIntegrationPoints( const Variable<double>& rVariable, std::vector<double>& rOutput, const ProcessInfo& rCurrentProcessInfo )`. For interface elements this is not done as we are usually interested in the normal and shear stresses along the interface (contact) and not the deviatoric stress. Of course this can simply be done but I do not really see its benefit.

A priori with the elements should be enough. As I said, in my experience with contact application should work.

**Comment by aronnoordam** [comment]
> `VON_MISES_STRESS` is calculated inside all "volume" elements of GeomechanicsApp in function `void CalculateOnIntegrationPoints( const Variable<double>& rVariable, std::vector<double>& rOutput, const ProcessInfo& rCurrentProcessInfo )`. For interface elements this is not done as we are usually interested in the normal and shear stresses along the interface (contact) and not the deviatoric stress. Of course this can simply be done but I do not really see its benefit.

ah okay got it, however, the calculation currently crashes when Interface elements are present within the model + von Misis stress is requested as an output, in the projectparameters.json. So either von misis stress should be calculated, or it should be set to zero. For completeness I can create a pull request with the implementation of the von misis stress
