### ISSUE TITLE
Duplicated variables in multiple apps

### ISSUE THREAD

**Issue by sunethwarna** [KratosMultiphysics/Kratos#10626]
**Description**
I have seen duplicated variable definitions for the same variable such as `CROSS_AREA` in multiple apps. Eventhough, all of them means the same variable (having the same key), do we keep on doing it or, should we think about moving the duplicated variables to core?

**Scope**
-All applications

**Comment by loumalouomega** [comment]
I will keep it as it is. After a redesign, this is intended. Before this, many variables were defined in Core just because it were used in multiple apps, and now the core is overpopulated of variables. In any case, I would clean up variables in Core
