### ISSUE TITLE
Someone can tell me how long it takes to compile

### ISSUE THREAD

**Issue by DEMSPHTrainer** [KratosMultiphysics/Kratos#10625]
Someone can tell me how long it takes to compile KratosMultiphysics+GID, I am always in the process of generating code.

**Comment by rubenzorrilla** [comment]
There is no need to compile GiD. You can download any version from [here](https://www.gidsimulation.com/gid-for-science/downloads/l).

About Kratos compilation time, this strongly depends on your machine features so it is impossible to establish an exact time. In my machine, admittedly rather new, a fresh compilation takes around 20 minutes.

**Comment by DEMSPHTrainer** [comment]
> There is no need to compile GiD. You can download any version from [here](https://www.gidsimulation.com/gid-for-science/downloads/l).
> 
> About Kratos compilation time, this strongly depends on your machine features so it is impossible to establish an exact time. In my machine, admittedly rather new, a fresh compilation takes around 20 minutes.
I could not open the link. Could you please provide another file?  For the compilation, It takes me 3 hours that the powerShell is still generating code.

**Comment by DEMSPHTrainer** [comment]
Is there any version of Kratos could be used? I do not finish the compilation process

**Comment by rubenzorrilla** [comment]
GiD offers the option to download an already compiled version. Depending on your needs this might be sufficient.

**Comment by DEMSPHTrainer** [comment]
Thanks. For the Kratos compilation, I have been blocked from generating code for more than 3 hours.  What is the reason, I have followed the video step by step.

**Comment by rubenzorrilla** [comment]
It is impossible to figure out without any further details... My suggestion would be to compile the core without any application to see if the compilation finishes.

**Comment by DEMSPHTrainer** [comment]
Which version of the GID can Kratos be used for at least

**Comment by rubenzorrilla** [comment]
As far as I remember last version of the GUI requires any 16.x.x version.
