### ISSUE TITLE
Is there any video about compilation

### ISSUE THREAD

**Issue by DEMSPHTrainer** [KratosMultiphysics/Kratos#10624]
**Description**
Description of the request.
The content is not clear enough for a new user, could you please send me a video for the compilation processing

**Comment by loumalouomega** [comment]
> **Description** Description of the request. The content is not clear enough for a new user, could you please send me a video for the compilation processing

Any particular system?

**Comment by loumalouomega** [comment]
> > **Description** Description of the request. The content is not clear enough for a new user, could you please send me a video for the compilation processing
> 
> Any particular system?

Because depends on the OS

**Comment by DEMSPHTrainer** [comment]
> just for the windows

**Comment by rubenzorrilla** [comment]
[Here](https://www.youtube.com/watch?v=zZq7ypDdudo) it is.

**Comment by loumalouomega** [comment]
> [Here](https://www.youtube.com/watch?v=zZq7ypDdudo) it is.

But here is installation, not compilation

**Comment by rubenzorrilla** [comment]
> 

No. This includes the compilation in Windows.
