### ISSUE TITLE
[GeoMechanicsApplication] C++ workflow for GeoFlow does not call KratosApplication::Register/RegisterVariables

### ISSUE THREAD

**Issue by carloslubbers** [KratosMultiphysics/Kratos#10644]
In PR https://github.com/KratosMultiphysics/Kratos/pull/10421 the Register() method of the core Kratos application was removed. This has caused pure C++ workflows to not have these variables registered properly.

Currently, tests ran through the python testing scripts will work because the test code implicitly imports the Kratos core code and registers all variables.

**Comment by philbucher** [comment]
Be careful, not correctly initializing the Core (aka importing it in Python) can cause problems, since quite a bit of stuff happens there

**Comment by mcgicjn2** [comment]
Unfortunately we don't use python in all our workflows, thus our problem. We think we have a work around

**Comment by mcgicjn2** [comment]
Now trying with kernel.import(geoApplication) route
