### ISSUE TITLE
[Core][Bug] Mutating Value in Parameter Iterators

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10649]
## Description
Iterating through a `Parameters` object mutates previous values of the iterator.

## Scope
- KratosCore

## To Reproduce
```py
params = KratosMultiphysics.Parameters("[0, 1]")
lst = []

for item in params:
    lst.append(item)
    print(item.GetInt())

for item in lst:
    print(item.GetInt())
```
Output:
```
0
1
1
1
```

## Expected Behaviour
```
0
1
0
1
```

## Details
`Parameters::iterator_adaptor` and `Parameters::const_iterator_adaptor` both hold an instance to `Parameters` for the sole purpose of providing references and pointers instead of instances when dereferenced. The stored instance gets overwritten each time the iterator is dereferenced, which means that that previous values of the iterator get updated too, and thus cannot be relied on. This isn't a huge issue on the C++ side because anyone who wants to store the value behind an iterator can just copy construct a `Parameters` from the returned reference, but this is not an option on the python side. As a result, python users have only 2 options:
- store a reference to the value behind the iterator (this is unreliable as the reference gets updated every time the iterator is dereferenced)
- clone the `Parameters` object that the iterator references in each iteration. This isn't a solution either since changes to the cloned instance don't propagate back to the parent object

On the flip side, `Parameters::operator[]` and `Parameters::GetArrayItem` does what you'd expect and returns a `Parameters` instance instead of a reference, so the following runs just fine:
```py
params = KratosMultiphysics.Parameters("[0, 1]")
lst = []

for i in range(params.size()):
    lst.append(params[i])
    print(params[i].GetInt())

for item in lst:
    print(item.GetInt())
```
Output:
```
0
1
0
1
```

By the way, storing an instance that always gets updated, and returning references to it is not even thread-safe.

**Comment by loumalouomega** [comment]
Umm, it was me (with the help of @RiccardoRossi ) who implemented this, so it is my fault... Any suggestion for change?

**Comment by loumalouomega** [comment]
@matekelemen in C++ the error persists?

**Comment by matekelemen** [comment]
> Any suggestion for change?

I'd get rid of the stored instance and change the dereference operator `Parameters& operator*` to return an instance instead `Parameters operator*`. Unfortunately, that means that `operator->` would no longer be viable. I've already made the changes and am compiling + running tests.

>  in C++ the error persists?

If you try hard enough, you'll run into this bug on the C++ side too, but I doubt anyone ever has (or will) because it would obviously be dangerous. You'd have to do something like this:
```cpp
Parameters params("[0, 1]");
std::vector<Parameters*> vector_of_raw_pointers;
for (auto& r_item : params) {
    vector_of_raw_pointers.push_back(&r_item);
}
```

**Comment by loumalouomega** [comment]
> > Any suggestion for change?
> 
> I'd get rid of the stored instance and change the dereference operator (`Parameters& operator*`) to return an instance instead (`Parameters operator*`). Unfortunately, that means that `operator->` would no longer be viable. I've already made the changes and am compiling + running tests.

Huuum, I don't like the idea, as we will lose features and it will add an overhead (copying)

> > in C++ the error persists?
> 
> If you try hard enough, you'll run into this bug on the C++ side too, but I doubt anyone ever has (or will) because it would obviously be dangerous. You'd have to do something like this:
> 
> ```c++
> Parameters params("[0, 1]");
> std::vector<Parameters*> vector_of_raw_pointers;
> for (auto& r_item : params) {
>     vector_of_raw_pointers.push_back(&r_item);
> }
> ```

![image](https://user-images.githubusercontent.com/19991680/213206370-93eca775-9677-438a-82e2-1dd3f37bc156.png)

**Comment by matekelemen** [comment]
> Huuum, I don't like the idea, as we will lose features and it will add an overhead (copying)

`Parameters` is just a wrapper around pointers to `nlohmann::json` so its footprint is rather small. When returning a copy of `Parameters`, the underlying JSON string is not copied. In fact, an extra heap allocation is eliminated by getting rid of the member `Parameters`.

**Comment by RiccardoRossi** [comment]
ok, after reading this i am more positive abou the change.

mentioning @KratosMultiphysics/technical-committee but i think i agree with the change

**Comment by RiccardoRossi** [comment]
one question: since the error is mostly in the py usage, wouldnt it make sense to fix it in the py interface?

**Comment by loumalouomega** [comment]
> one question: since the error is mostly in the py usage, wouldnt it make sense to fix it in the py interface?

I thought the same, but @matekelemen is right that this is not threadsafe anyway

**Comment by RiccardoRossi** [comment]
well the parameters object per se is not threadsafe...i would say that not even the underlyin lib is (unless i misunderstand your expectations)

@matekelemen would you have a better design for the Parameters? (constraint here is  that we isolate from the underlying lib)

**Comment by loumalouomega** [comment]
If the object per se is not designed to be threadsafe I would focus in python interface to not lost features in the class

**Comment by matekelemen** [comment]
> well the parameters object per se is not threadsafe...i would say that not even the underlyin lib is (unless i misunderstand your expectations)

By thread safety I mean the current is not even thread-safe for reading (the stored `Parameters` gets updated even when you aren't changing values of the original `Parameters` object). `nlohmann::json` doesn't have any problems with reading in parallel.

> one question: since the error is mostly in the py usage, wouldnt it make sense to fix it in the py interface?

the current PR also generates compilation errors for forbidden use cases of `Parameters` like this:
```cpp
Parameters params("[0, 1]");
for (auto& r_sub_params : params) {}
```
It caught a few cases and I prefer compilation errors to possible runtime bugs.

> would you have a better design for the Parameters?

Not one that I like. It would involve storing an array of subparameters, but I don't think it's worth it because we'd have to keep that array up-to-date whenever the root `Parameters` changes. If we were to make such huge changes to `Parameters`, we'd better solve all its issues at the same time (eg: const correctness) but I don't think anyone has the time to do it properly.

**Comment by RiccardoRossi** [comment]
i have one proposal:

what if we remove from the interface the Python iterators (without touching the interface)

and instado we export the methods keys(), values() and ítems()

we could then iterate as needed over the resulting lists, and that would solve our problem...
