### ISSUE TITLE
[GeomechanicsApplication] Make it possible to initialize a State parameter field in the Geomechanics application

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10651]
Make it possible to initialize a Material or State parameter field in the Geomechanics application. 

- Implement a method which makes it possible to initialize material state parameters per gauss point (not only per material). 
- Example applications are random fields and depth dependent Overconsolidation Ratio

**Comment by mcgicjn2** [comment]
Hey Aron, do you plan to do this or do you want us to facilitate ?

**Comment by aronnoordam** [comment]
I'm planning to do it

**Comment by mcgicjn2** [comment]
Hey Aron, Then maybe you should come in on our sprint when you do it, as I think it might be a multiman issue; and also impacts the things we do.
