### ISSUE TITLE
Eigen analysis. Some questions

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#10654]
For didactical purpose I want to solve an eigenvalue problem with Kratos.

- First of all, I'm having trouble running the analysis. I've defined a simple 2D structure with beams with BC, but no output is generated. However, the system has run succsesfully:
```
EigensystemSolver:: Completed in 0.0085399 seconds
                   Eigenvalues = [ 7569.62, 88736.4, 112805, 242473, 423136 ]
```
- Is it possible to convert loads to mass?
- Is it possible to define an analysis with shells and beams?

**Comment by miguelmaso** [comment]
Here is the json:

```json
{
    "problem_data"    : {
        "problem_name"  : "eigen",
        "parallel_type" : "OpenMP",
        "echo_level"    : 1,
        "start_time"    : 0.0,
        "end_time"      : 1.0
    },
    "solver_settings" : {
        "time_stepping"            : {
            "time_step" : 1.1
        },
        "solver_type"              : "eigen_value",
        "model_part_name"          : "Structure",
        "domain_size"              : 2,
        "echo_level"               : 1,
        "model_import_settings"    : {
            "input_type"     : "mdpa",
            "input_filename" : "eigen"
        },
        "material_import_settings" : {
            "materials_filename" : "StructuralMaterials.json"
        },
        "eigensolver_settings"     : {
            "solver_type"           : "eigen_eigensystem",
            "max_iteration"         : 1000,
            "tolerance"             : 1e-6,
            "number_of_eigenvalues" : 5,
            "echo_level"            : 1
        },
        "rotation_dofs"            : true,
        "volumetric_strain_dofs"   : false
    },
    "processes"       : {
        "constraints_process_list" : [{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "AssignVectorVariableProcess",
            "Parameters"    : {
                "model_part_name" : "Structure.DISPLACEMENT_Displacement_Auto1",
                "variable_name"   : "DISPLACEMENT",
                "interval"        : [0.0,"End"],
                "constrained"     : [true,true,true],
                "value"           : [0.0,0.0,0.0]
            }
        },{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "AssignVectorVariableProcess",
            "Parameters"    : {
                "model_part_name" : "Structure.ROTATION_Rotation_Auto1",
                "variable_name"   : "ROTATION",
                "interval"        : [0.0,"End"],
                "constrained"     : [true,true,true],
                "value"           : [0.0,0.0,0.0]
            }
        }],
        "loads_process_list"       : [],
        "list_other_processes"     : [{
            "python_module" : "postprocess_eigenvalues_process",
            "kratos_module" : "KratosMultiphysics.StructuralMechanicsApplication",
            "help"          : "This process postprocces the eigen values for GiD",
            "process_name"  : "PostProcessEigenvaluesProcess",
            "Parameters"    : {
                "result_file_name" : "eigen",
                "animation_steps"  : 20,
                "file_format"      : "gid",
                "label_type"       : "frequency"
            }
        }]
    },
    "analysis_stage"  : "KratosMultiphysics.StructuralMechanicsApplication.structural_mechanics_analysis"
}
```

**Comment by loumalouomega** [comment]
>     * Is it possible to convert loads to mass?

I am afraid that you should do manually. Remember that it only makes sense with dead masses that "belong" to the system
 
>     * Is it possible to define an analysis with shells and beams?

Should work.

**Comment by miguelmaso** [comment]
> I am afraid that you should do manually

Do you mean adding directly to a nodal variable? Which one, `NODAL_MASS` (double), `MASS` (array3) or another variable?
Or maybe modifying the element immplementation?

**Comment by loumalouomega** [comment]
> > I am afraid that you should do manually
> 
> Do you mean adding directly to a nodal variable? Which one, `NODAL_MASS` (double), `MASS` (array3) or another variable? Or maybe modifying the element immplementation?

You have NodalConcentratedElement, but I think there are also pure mass elements @philbucher ?

**Comment by philbucher** [comment]
The NodalMass can be used as pure nodal mass, I used it extensively 

Same for beams and shells

**Comment by philbucher** [comment]
Btw I recommend using the spectra eigensolver, its is like 10 times faster

**Comment by miguelmaso** [comment]
> The NodalMass can be used as pure nodal mass, I used it extensively

Thanks

**Comment by miguelmaso** [comment]
> Btw I recommend using the spectra eigensolver, its is like 10 times faster

Thanks for the hint. I was using the default options from the GiD interface.

Do you know if I need to modify some paramters in order to visualize the eigenmodes? The default options are not plotting the eigenmodes

**Comment by philbucher** [comment]
> Do you know if I need to modify some paramters in order to visualize the eigenmodes? The default options are not plotting the eigenmodes

looks good to me at first glance
What is not working?
Does it work with paraview?

**Comment by miguelmaso** [comment]
> Does it work with paraview?

It's working with paraview. Closing since this issue is very generic and all the questions have been answered.

I will open a more specific issue if I experience some difficulties with post processing
