### ISSUE TITLE
[Core] Passing the ProcessInfo to the InitializeMaterial() function for the Constitutive Laws

### ISSUE THREAD

**Issue by andinoboerst** [KratosMultiphysics/Kratos#10664]
**Description**
I want to suggest to the @KratosMultiphysics/technical-committee to pass the `ProcessInfo` as an additional parameter in the function call of the `InitializeMaterial()` function for the Constitutive Laws.

Currently, the `ProcessInfo` is not being passed to the `InitializeMaterial()` function for the Constitutive Laws. The `ProcessInfo` contains information, among other things, on whether the simulation was restarted or not.
This information is required in the `ParticleMechanicsApplication` for example, as only some parts of the `InitializeMaterial()` function need to be called on a restart.

For this reason, I would suggest adjusting the `InitializeMaterial()` function in the `consitutive_law.h` file to pass the `ProcessInfo` in the function call as well.
To not break the other applications, which are not passing the `ProcessInfo`, I think the best solution would be to overload this function.
The reason for requesting this change, as well as an implementation of the suggested changes, can be seen in this branch: #10542.

**Comment by andinoboerst** [comment]
I tried passing this information using the Properties, but that didn't work when multithreading.
If desired of course all the other applications could be adjusted to the new function call as well.

**Comment by RiccardoRossi** [comment]
I tend to agree with this change...however as Vicente tells, it will imply a lot of work to change everything to bring it to compilable status

**Comment by andinoboerst** [comment]
After further discussion in #10542 I decided to pursue a different solution, which does not require the restart flag inside the 'InitializeMaterial()' function.
Unless the 'ProcessInfo' could still be used in other instances inside the function, from my part the issue is resolved.
