### ISSUE TITLE
[Registry] Usage Guidelines

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10661]
I need some advice/examples on the specifics of how the `Registry` is meant to be used. I've looked around in master but haven't found anything that used it yet (apart from tests).

Looking at the class and its utilities, I have a basic understanding of how it works, but I'm not sure **when and where** items are supposed to be registered to it, since the entire interface is static. The following questions come to mind:
- when should `Registry::AddItem` be called for a base class?
- when should `RegistryItem::AddItem` be called for a derived class?
- how can I make sure that a base class is in `Registry` before trying to register a derived class?
- are there any separate standard file names/locations to do all the registry-related stuff in?

In particular I'm interested in how to handle the following scenarios:
- a base class `B` is registered in core and its derived class `D` is registered in an application `A`.
- both the base class `B` and its derived class `D` are registered in an application `A`.

The question is primarily meant for the C++ side but now that I think of it, it's also unclear to me in python. Code examples are welcome.

**Comment by loumalouomega** [comment]
@rubenzorrilla
