### ISSUE TITLE
Inverted normal in in planes

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1068]
Follow up @pooyan-dadvand comments on #1052 (it was already merged)

Old `UnitCrossProduct` function was returning the inverted normal instead of the normal. 
We have deprecated that function in #946, and replaced it in #1051 and #1052.

As the new `UnitCrossProduct` returns the correct normal, the components where inverted. So the behavior is the same but this is still a bug. Is that correct?

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee what is your opinion? 

My opinion is to keep the normal(edge1,edge2) as it was.

**Comment by RiccardoRossi** [comment]
sorry i accepted the PR without seeing this issue. @roigcarlo please keep the PR on hold until we find an agreement
