### ISSUE TITLE
Proposal to add a function "GetStageFinalData" to the analysis stage

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#10696]
**Description**
As of now there is no (non hacky) way to return data which are eventually computer within a stage. This makes cumbersome to have a stage to compute something (not to be written at disk!).

Two recent examples in which this capability would be useful are the following:
1 - computation of training data for ROM simulation (ping @Rbravo555 )
2 - i would like to change some constitutive parameters and compute the distribution of stresses that corresponds to this (i need it as a numpy array to use it later in an optimization loop 

in essence i would like to be able to do something of the type

~~~py
     ...within stage...
     def GetFinalData(self):
          results =  { "STRESSES" , self.stresses } by default results is an empty dictionary, but i could use it to return what i need
          return results
~~~

usage would be on the line of 

~~~py
   opt_params = {...}
   stage = MyCustomStage(Model, parameters, opt_params) # in here for example i apply opt_params and compute the stresses as a numpy array
   stage.Run()
   data = stage.GetFinalData() # here we return a python dictionary which contains the data that we will use for our optimization loop
~~~

**Comment by roigcarlo** [comment]
For me it makes sense :+1:

**Comment by rubenzorrilla** [comment]
Just saying that in the base class I'd return `None`.

**Comment by roigcarlo** [comment]
I am closing this as it is already Implemented in some branches and currently discussed in the context of the multistage.
