### ISSUE TITLE
[GeoMechanicsApplication] Pure Cpp testing application

### ISSUE THREAD

**Issue by huhaas** [KratosMultiphysics/Kratos#10692]
To speed up development it is nice to have a dedicated for Cpp unit testing and debugging. This avoids the need for a Python layer for these two use cases.
The flow will be more similar to existing testing applications (e.g. Google Test).

**Comment by roigcarlo** [comment]
This is something we are already have been considering for some time. I will unearth discussion in the @KratosMultiphysics/technical-committee .

Our idea would be to make each individual test a separate binary (GTest is one of the candidates)

**Comment by huhaas** [comment]
Does that mean if, for instance, Geo has 5 Cpp tests there will be 5 GTest executables?
If yes, GTest main can solve this with a single executable and arguments.

I have added a draft PR to show how it can be used with current testing framework.

**Comment by roigcarlo** [comment]
My idea is to have different suites, so no one executable per test, but "one per file". At least in the first version to make the transition automatic. 

I expect to have a draft with GTest (we still have not decided to use that one) in a couple of days or sooner so we can iterate over it to see how it looks and what are the needs of different users.

**Comment by huhaas** [comment]
Obsolete
