### ISSUE TITLE
[IO] ModelPartIO and Solution Step Variables

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10701]
## Description

The `mdpa` format allows storing nodal solution step variables, and `ModelPartIO` will happily write them for you, but it cannot read them unless the target `ModelPart` already knows what's in the file and is configured accordingly.

Here's an example:
```py
import KratosMultiphysics
import pathlib

model = KratosMultiphysics.Model()
source_model_part = model.CreateModelPart("source")
source_model_part.AddNodalSolutionStepVariable(KratosMultiphysics.PRESSURE)
KratosMultiphysics.ModelPartIO(pathlib.Path("tmp"),
                               KratosMultiphysics.IO.WRITE).WriteModelPart(source_model_part)

target_model_part = model.CreateModelPart("target")
KratosMultiphysics.ModelPartIO(pathlib.Path("tmp")).ReadModelPart(target_model_part) # <== Error: The nodal solution step container does not have this variable: PRESSURE.
```

## Details

In case it's not clear: nodal solution step variables are stored in the `ModelPart` instead of the `Node`s themselves, which has several consequences:
- all `Node`s within a `ModelPart` must have the same list of solution step variables
- newly added `Node`s also have the same list of solution step variables
- once a `ModelPart` is populated with `Node`s, the list of solution step variables *shouldn't* be changed

=> anything that wants to populate a `ModelPart` must know all required nodal solution step variables **before** it actually starts constructing `Node`s. However, the `mdpa` format doesn't convey any information beforehand, and defines variables on the fly.

## Discussion

As a user, I'd expect that `ModelPartIO` can read whatever it has written but that's not the case right now. Is this intended?I hope it's not, but on the off chance that it is, this behaviour should be clearly stated.

**Comment by loumalouomega** [comment]
I agree with you. But the only way to add the variables before reading is to do a first loop to see the variables to be added, as these variables must be added before adding the nodes

**Comment by philbucher** [comment]
you are aware that you can ignore the solution step vars while reading?

**Comment by matekelemen** [comment]
> But the only way to add the variables before reading is to do a first loop to see the variables to be added, as these variables must be added before adding the nodes

I understand, but that's an implementation detail. We can't expect users to be familiar with the `mdpa` format (which is a custom mesh file format, why aren't we using a standard one by default?) and somehow know that the core devs opted not to implement functionalities due to performance considerations stemming from the layout of that format.

> you are aware that you can ignore the solution step vars while reading?

I am, but that doesn't change the fact that `ModelPartIO`'s read and write are inconsistent with each other. It would make sense to me that a write operation with given options produces a file that can be read with the same options (in this case - default options). What's the point of writing data we can't access, anyway? Noone's going to open up an `mdpa` file and start manually reading the solution step data.

If writing variable data is not intended, the functions should be renamed to something like `WriteMesh` and `ReadMesh` to make it clear what they're supposed to do, though I'd prefer keeping the current names and implement solution step data loading.

So what's the general opinion?
1) do nothing; the current behaviour is intended
2) remove IO related to variable data, and rename the functions
3) implement historical variable data input at the expense of some performance, and keep the function names

I'd personally go with 3.

*P.S.: I've also noticed that nodal data (the non-historical kind) doesn't get written, even though element and condition data does.*

**Comment by rubenzorrilla** [comment]
I agree that current behaviour is inconsistent. Hence, this shouldn't be the intended one and we need to do something in this regard.

My personal view about this is that the `ModelPartIO` should take care of the geometry, that is coordinates, connectivities and groups. Everything else is IMO legacy from old Kratos days. Note that this is in line with the view of having a geometrical only mdpa.

Having said this, and considering that we now have enough capabilities to save the model part data (i.e.  `HDF5Application`), I'd promote these rather than adding an extra overhead to the `ModelPartIO`. Note that this might be non-negligible in large models.

@KratosMultiphysics/technical-committee

**Comment by rubenzorrilla** [comment]
@KratosMultiphysics/technical-committee has been discussing about this.

We consider @matekelemen 's as a good solution for this issue. However, it has the drawback of requiring parsing the mdpa twice.

Having said this, we suggest to create a new metadata section at the beginning of the mdpa (of course this needs to be optional to keep retrocompatibility). In this metadata section we can save
- the list of solution step variables: on top fixing the issue raised by @matekelemen 's  we can use it to add the variables required by the processes. Note that this is a temporary solution until we come up with the final design.
- the list of non-historical variables: then we can use this to allocate the memory (i.e. do a first `SetValue`) to avoid the race condition. Note that this will be specially helpful for newbies.
- the number of nodes, elements and conditions: that will potentially help to improve the reading performance.

@KratosMultiphysics/implementation-committee we would like to hear your opinion about it.
