### ISSUE TITLE
Mass in dynamic and modal calculations

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#10707]
**Description**
Hi, I'm trying to understand how to assign non-structural mass to a structure for dynamic and modal calculations. `mass_element` seems to be a good choice for that purpose, but I have a couple of questions regarding this element:

- Which are the units of the mass matrix? In `CalculateRightHandSide`:
```cpp
rRightHandSideVector[index] += temp * r_geom[i].FastGetSolutionStepValue(VOLUME_ACCELERATION)[j];
```
- It seems that `mass_element` is adding structural mass. Current implementation:
```cpp
double MassElement::GetElementMass() const
{
    ...

    if (local_dim == 1) { // line
        total_mass = GetProperties()[CROSS_AREA] * StructuralMechanicsElementUtilities::CalculateReferenceLength3D2N(*this);

    } else if (local_dim == 2) { // tri / quad
        total_mass = GetProperties()[THICKNESS]* r_geom.Area();
```
What I'm expecting (pseudocode, I don't know if some variables already exist):
```cpp
    double gravity2 = inner_prod(gravity, gravity);

    if (local_dim == 1) { // line
        total_mass = inner_prod(GetValue(LINE_LOAD),gravity) / gravity2 * r_geom.Length();

    } else if (local_dim == 2) { // tri / quad
        total_mass = inner_prod(GetValue(SURFACE_LOAD),gravity) / gravity2 * r_geom.Area();
```
- How to enable the `mass_element`? Should I use the `ConnectivityPreserveModeler` or this functionality is already present in all the structural elements?

**Scope**
- Documentation

**Comment by philbucher** [comment]
Short answer, this is a mass, applying loads can be done with the load-conditions

**Comment by philbucher** [comment]
Sorry I misunderstood 

Will get back after work with a more detailed explanation 

Do you want to apply point masses or distributed masses?

**Comment by philbucher** [comment]
Ok got it

So this element is basically a membrane element but without contributions to the LHS

I.e. you can gibe thickness (or cross section for lines) and density to set the mass

I used it to model paint

**Comment by philbucher** [comment]
And it is a regular element, i.e. it can come from the mdpa, or the ConnPresModeler (I had it in the mdpa)

**Comment by miguelmaso** [comment]
I see your point, makes sense.

Right now, it isn't un the interface. So, I will use the ConnPresModeler and modify the properties according to the non-structural elements.

If added to the interrace, it will come from the mdpa with the specified properties

**Comment by miguelmaso** [comment]
> * Which are the units of the mass matrix?

last question. It seems to be a volume...

**Comment by miguelmaso** [comment]
got it

https://github.com/KratosMultiphysics/Kratos/blob/e8e2cf68e8296c5bb3771fd5543ca7a7d9653929/applications/StructuralMechanicsApplication/custom_elements/mass_element.cpp#L256

**Comment by philbucher** [comment]
> I see your point, makes sense.
> 
> 
> 
> Right now, it isn't un the interface. So, I will use the ConnPresModeler and modify the properties according to the non-structural elements.
> 
> 
> 
> If added to the interrace, it will come from the mdpa with the specified properties

Sure, there are many ways you can use them

I usually wrote mdpas myself...
