### ISSUE TITLE
Errors when configuring

### ISSUE THREAD

**Issue by behzadtabari** [KratosMultiphysics/Kratos#10712]
**Description**
Hello,

I tried to clone and compile Kratos on my Ubuntu on Windows, and btw my default python is 3.8 version. but when running the bash script I get the following error and I don't know what to do and what is the issue. many thanks.

**Scope**
-- clipper : /home/.../Kratos/external_libraries/clipper
-- tinyexpr : /home/.../Kratos/external_libraries/tinyexpr/tinyexpr/
python libraries to be installed are: /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
CMake Error at scripts/post_install/CMakeLists.txt:5 (cmake_path):
  Unknown CMake command "cmake_path".

-- Configuring incomplete, errors occurred!
See also "/home/.../Kratos/build/Release/CMakeFiles/CMakeOutput.log".
make: *** No rule to make target 'install'.  Stop.

**Comment by kelofm** [comment]
Looks like our CMake minimum version requirement is out of sync. You have 2 options until we fix it:
1) update your CMake to at least version 3.20
2) or disable python stub generation by setting `KRATOS_GENERATE_PYTHON_STUBS` from `ON` to `OFF` in your build script. You'll lose some hints for python in your IDE but that only matters if you're planning to dig deep into kratos.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee would not change the minimum CMake version as at this moment this use case is optional. Nevertheless, in the future we may update when 3.20 is widely used.

**Comment by sunethwarna** [comment]
This is fixed in the #10727 . @behzadtabari, could you try the PR and let us know if it works for you without turning off the `KRATOS_GENERATE_PYTHON_STUBS`?

**Comment by behzadtabari** [comment]
@sunethwarna I tried updating the CMake version at first so then it complied. Since mine was 3.16 beforehand.
