### ISSUE TITLE
WINDOWS COMPILATION ERROR

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#10757]
**Description**
Today @atfard and me noticed that the master branch is not compiling in Windows (StructuralMEchApp):

C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(149,20): error C2065: 'PRESSURE': identificador no declarado [C:\Kr
atos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]
C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(150,50): error C2065: 'PRESSURE': identificador no declarado [C:\Kr
atos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]
C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(152,20): error C2065: 'NEGATIVE_FACE_PRESSURE': identificador no de
clarado [C:\Kratos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]
C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(153,50): error C2065: 'NEGATIVE_FACE_PRESSURE': identificador no de
clarado [C:\Kratos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]
C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(155,20): error C2065: 'POSITIVE_FACE_PRESSURE': identificador no de
clarado [C:\Kratos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]
C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(156,50): error C2065: 'POSITIVE_FACE_PRESSURE': identificador no de
clarado [C:\Kratos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]
C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(163,49): error C2065: 'NEGATIVE_FACE_PRESSURE': identificador no de
clarado [C:\Kratos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]
C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(164,77): error C2065: 'NEGATIVE_FACE_PRESSURE': identificador no de
clarado [C:\Kratos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]
C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(166,49): error C2065: 'POSITIVE_FACE_PRESSURE': identificador no de
clarado [C:\Kratos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]
C:\Kratos\applications\StructuralMechanicsApplication\custom_conditions\small_displacement_surface_load_condition_3d.cpp(167,77): error C2065: 'POSITIVE_FACE_PRESSURE': identificador no de
clarado [C:\Kratos\build\Release\applications\StructuralMechanicsApplication\KratosStructuralMechanicsCore.vcxproj]

Anyone knows somethign about the change of these variables?

@roigcarlo @loumalouomega

**Comment by loumalouomega** [comment]
Strange, can you include variables.h?

**Comment by AlejandroCornejo** [comment]
I'll do a PR with that change...
