### ISSUE TITLE
[Question] are iterators sorted?

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10756]
perhaps an obvious question, but when I iterate over parameters/elements/nodes/etc. does this happen in same order as the objects are present in the projectparameters.json /mpda file? or are the objects randomly accessed?

**Comment by loumalouomega** [comment]
Yes, it is sorted, see that `Sort()` is called each time that anything is added: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/containers/pointer_vector_set.h

**Comment by matekelemen** [comment]
`Parameters` is just a wrapper around [`nlohmann::json`](https://github.com/nlohmann/json) objects, which in turn probably uses something like an `std::map` under the hood, so the keys are sorted (although as `string`s in lexicographical order, mind you):

```py
import KratosMultiphysics
params = KratosMultiphysics.Parameters(R"""{
    "1" : 1,
    "2" : 2,
    "3" : 3,
    "10" : 10
}""")
for sub in params:
    print(sub.GetInt(), end=" ")
```
```
1 10 2 3
```

If you need to rely on the ordering within `Parameters`, use an array definiton:
```py
import KratosMultiphysics
params = KratosMultiphysics.Parameters('["1", "2", "3", "10"]')
for sub in params:
    print(sub.GetString(), end = " ")

```
```
1 2 3 10
```

Be careful when iterating over the components of `Parameters` though: there are some known bugs (#10649).

**Comment by aronnoordam** [comment]
okay clear, thanks!
