### ISSUE TITLE
[Question][LinearSolversApplication] Why is MKL not standard delivered with the LinearSolversApplication?

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#10786]
Why is the MKL library not standard delivered with the LinearSolversApplication?

**Comment by loumalouomega** [comment]
Licence issues I guess

**Comment by AlejandroCornejo** [comment]
@roigcarlo 
My guess, as @loumalouomega mentioned, that this is due to a mess regarding the licensing terms...Luckily it's quite easy to install. Let me know if you need any assistance.
Alejandro

**Comment by roigcarlo** [comment]
As Alejandro and Vicente have commented, while MKL licence (ISSL) allow for distribution, to our understanding is not compatible with Kratos' BSD4

The problems are about having to mention the original authors. If you want more details I can look for the specific clauses.

**Comment by aronnoordam** [comment]
ah, yes, license issues was what I expected, however I've read that ISSL allows for incorporation in software with a different license, so I was confused. @roigcarlo if you can look up the specific clause, that would be nice :)

**Comment by aronnoordam** [comment]
> @roigcarlo My guess, as @loumalouomega mentioned, that this is due to a mess regarding the licensing terms...Luckily it's quite easy to install. Let me know if you need any assistance. Alejandro

I have installed it already, I was mostly wondering because I was looking into distributing a Kratos application including MKL

**Comment by roigcarlo** [comment]
@aronnoordam This is the problem:

ISSL
```
Use and Redistribution. You may use and redistribute the software, which is provided in binary form only, (the "Software"), without modification, provided the following conditions are met:
```

BSD4
```
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: 
```

That would be the problem for us (ISSL does not allow modification or redistribution of sources)

As far of creating your own package with MKL, we tackled the topic in the past and albeit we didn't reach an agreement the most straight forward solution would be to distribute with a dual ISSL wich covers the MKL part and a BSD4 which covers the Kratos part.

If strictly necessary we may give you permission to change licence on our side, but I think its something that we really really want  to avoid.

**Comment by aronnoordam** [comment]
okay thanks, it's clear now. Regarding, changing license, for now I was mostly brainstorming what the possibilities are, possibly I don't even need mkl at all, so changing license is not needed (for now).

**Comment by rubenzorrilla** [comment]
Closing as it seems to be clarified. @aronnoordam feel free to reopen if required.
