### ISSUE TITLE
[Discussion] Offer Kratos PyPI wheels periodically (monthly)

### ISSUE THREAD

**Issue by DSchmoelz** [KratosMultiphysics/Kratos#10803]
**Description**

The PyPI wheels (https://pypi.org/project/KratosMultiphysics/#description) are a great way for project partners to install and use Kratos in their own python environments. 

However, the last build of the wheels has been **October 14th 2022**!!!

It would be great, if the wheels would be released on regular basis, e.g. monthly, so that project partners get access to new features quicker and no special wheels have to built manually for them.

This would streamline the submission for research projects and make Kratos more attractive.

**Comment by roigcarlo** [comment]
Hi  @DSchmoelz 

We try to keep a steady pace when it comes to public releases (The ones uploaded into PyPI), but our primary goal is to make them when there is something relevant added to Kratos. While our intention is to make them monthly, most of the time there are just no enough changes to justify the cost of making one.

For example from 9.2 to 9.3 we will:
- Add the new Kratos registry
- Support for HDF5 in windows
- The new LSPG rom solver
- Support for Python 3.11

As for private releases, we have no restrictions into how many we could generate, in fact internally we generate them weekly (often more). If it is useful we can study how to make those available to users.
