### ISSUE TITLE
[Question][MappingApplication] Nearest element mapping in Kratos

### ISSUE THREAD

**Issue by akhilkmat** [KratosMultiphysics/Kratos#10855]
Dear all,

I had some doubts in regards to the mapping procedure used in Kratos. I am trying to implement DEM-FEM volume coupling.

Here are a few doubts that came up after reading few papers associated with Kratos.

edit:

- In test cases, when I try to map DEM particles to a tetrahedral mesh using the nearest element (conservative) mapping approach, the particles outside the mesh receive negative weights and the ones inside are mapped correctly using linear shape functions. Although , I want to only the particles inside the element to get mapped to the nodes. Even adjusting the search radius doesn't seem to work, can you explain how the nearest element is found?

-Also how does the inverse mapping from DEM to FEM nodes work, if done 'conservatively'? It gives right results but I would like to know how it is done and what could be the computational cost?

Kind regards,
Akhil Mathews

**Scope**

- Documentation
- Mappingapllication

@philbucher

**Comment by akhilkmat** [comment]
Sorry I didn't see your reply, hence I edited my initial comment unknowingly, but the explanation helps.

Further questions:

- How do the mapping application 'find' the nearest element? is it a binning kind of approach?
- I intend to use the same mapping as implemented in Kratos but do not want to map the particles outside the element, is there any way to do this? like some settings that can be applied to mapper settings? or what do you suggest?
- I will be mapping coupling forces from FEM nodes back to DEM particles, the theory discuses direct non-conservative mapping ( something that can be improved) but I also tried conservative mapping in the inverse mode as well, the results are correct, but I would like to know how the application does this when mapping from 'particles to nodes'? what could be the computational cost?

Thanks a lot,
Akhil

**Comment by philbucher** [comment]
Hey, apologies for the late reply

- it uses a bin based search, implemented in the Core. For MPI, this happens on each partition. Do you want to know in more detail?
- if you do NOT want to map from outside you could try setting this parameter to zero: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MappingApplication/custom_mappers/nearest_element_mapper.h#L296
I think I misunderstood this initially.
- regarding conservative mapping, how does your mesh look like? And what about the field/distribution

**Comment by akhilkmat** [comment]
Hi Philipp,

Thank you very much for the inputs. I am attaching a test case ( please rename the extention to .py) that creates 'a' tetrahedral mesh (fem) and 2 dem particles and maps mass back and forth mass between them, results are printed before and after mapping. One particle is inside the tetrahedral mesh and the other one is outside.

-I tried the setting "local_coord_tolerance"   as 0. But it still gives shows influence of the second particle (the masses dont add up for just one particle). Can you please take a look? or suggest some alternatives?

- Regarding the conservative mapping, 'if' I use - "KM.Mapper.USE_TRANSPOSE"  for the inverse mapping, i get conserved mapping back to the dem particles as well '(if both particles were inside)' , can you explain how this mapping is done theoretically? 

[test_conserve_mass.txt](https://github.com/KratosMultiphysics/Kratos/files/11320446/test_conserve_mass.txt)

Best,
Akhil

@philbucher 
@maceligueta 
@chyalexcheng

**Comment by philbucher** [comment]
> -I tried the setting "local_coord_tolerance" as 0. But it still gives shows influence of the second particle (the masses dont add up for just one particle). Can you please take a look? or suggest some alternatives?

should be fixed with #11121
