### ISSUE TITLE
[Core] SolvingStrategy Return Value

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10856]
## Question

https://github.com/KratosMultiphysics/Kratos/blob/5f5e99281a114a3c331a158746d302e73c71d2df/kratos/solving_strategies/strategies/solving_strategy.h#L175-L193

What is `SolvingStrategy::Solve` supposed to return? It's a `double`, but there's no description anywhere on what that's supposed to represent, and by looking at some derived classes ([eg.: struct mesh moving strat](https://github.com/KratosMultiphysics/Kratos/blob/5f5e99281a114a3c331a158746d302e73c71d2df/applications/MeshMovingApplication/custom_strategies/strategies/structural_meshmoving_strategy.h#L154)), it's always set to `0.0`.

However, solvers assume it's a boolean indication of convergence ([example: `MeshSolverBase`](https://github.com/KratosMultiphysics/Kratos/blob/5f5e99281a114a3c331a158746d302e73c71d2df/applications/MeshMovingApplication/python_scripts/mesh_solver_base.py#L146)), which of course will always be `false`. This mistakenly perceived failure to converge then propagates through the analysis (example: [`AleFluidSolver`](https://github.com/KratosMultiphysics/Kratos/blob/5f5e99281a114a3c331a158746d302e73c71d2df/applications/MeshMovingApplication/python_scripts/ale_fluid_solver.py#L168) => [`AnalysisStage`](https://github.com/KratosMultiphysics/Kratos/blob/5f5e99281a114a3c331a158746d302e73c71d2df/kratos/python_scripts/analysis_stage.py#L65)) and renders checking for convergence utterly pointless.

## Suggestion

Either change the return type of `SolvingStrategy::Solve` to `void`, or clearly state what it's supposed to represent and update existing solving strategies accordingly.

**Comment by RiccardoRossi** [comment]
the idea was to return the ||dx||

the reason for this is that by doing it this way one can essentially write a newton raphson strategy by combining a sequence of linear solves

**Comment by loumalouomega** [comment]
> the idea was to return the ||dx||
> 
> the reason for this is that by doing it this way one can essentially write a newton raphson strategy by combining a sequence of linear solves

But we are not doing that, so I agree with the idea of @matekelemen
