### ISSUE TITLE
FemToDem Split

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#10860]
FemToDem Application is not split in core/interface, which is causing heavy performance issues in the release generation.

Someone should separate the interface....

I Assigned you @AlejandroCornejo and @rubenzorrilla because I have no Idea who maintain this and the last commits were yours.

if there is no maintainer I can do it myself...

**Comment by rubenzorrilla** [comment]
I think this is purely @AlejandroCornejo. My latest commits were most probably to keep it updated.

**Comment by AlejandroCornejo** [comment]
Already done and merged
