### ISSUE TITLE
Less response function for the supported StructuralMechanicsApplication when performing optimization from Python.

### ISSUE THREAD

**Issue by hrntsm** [KratosMultiphysics/Kratos#10879]
**Description**
I wrote the configuration in Json and tried to run the optimization using "adjoint_nodal_displacement" in the response function in Python, but I got the following error.

```
NameError: The response function 'objective' of type 'adjoint_nodal_displacement' is not available.
```

I read the this [README](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_response_functions/README.md) and it state that "adjoint_nodal_displacement" are supported.
I checked the [Python code](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/ShapeOptimizationApplication/python_scripts/analyzers/analyzer_internal.py#L153) that outputs the above "NameError" message, and it is not included in [the list of supported response functions](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/ShapeOptimizationApplication/python_scripts/analyzers/analyzer_internal.py#L128).

```py
csm_response_functions = ["strain_energy", "mass", "eigenfrequency", "adjoint_local_stress", "adjoint_max_stress"]
# No adjoint_nodal_displacement included.
```

So I modified the above list to include "adjoint_nodal_displacement" and it now works for "adjoint_nodal_displacement".
```py
csm_response_functions = ["adjoint_nodal_displacement", "strain_energy", "mass", "eigenfrequency", "adjoint_local_stress", "adjoint_max_stress"]
```

Based on the above, I think there may be a missing response function in the list.

**Scope**
- ShapeOptimizationApplication

**To Reproduce**
Run the python file in example.
[exaple.zip](https://github.com/KratosMultiphysics/Kratos/files/10977054/exaple.zip)

**Expected behavior**
All response functions in [structural_response_function_factory.py](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_response_function_factory.py#L4) such as "adjoint_nodal_displacement" work.

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Window11
- Branch: install kratos v9.3 via pip
- Python 3.9

**Comment by hrntsm** [comment]
Hi @sunethwarna 

If additional information is required, I'll describe it, what is it?

**Comment by sunethwarna** [comment]
Hi @hrntsm ,

Thanks for noticing and notifying. This is fixed in #10905  :+1: . could you also take a look? Sorry for the late reply.

**Comment by hrntsm** [comment]
Hi @sunethwarna 

Thank you for creating the PR
I think that adding you to the list as described in this PR will resolve this issue.

**Comment by matekelemen** [comment]
For future ref, `CreateResponseFunction` in `structural_response_function_factory.py ` should probably be encapsulated in a class that exposes a list of available response functions, and `KratosInternalAnalyzer.__CreateResponseFunctions` should use that instead of its own hardcoded list.

**Comment by sunethwarna** [comment]
@matekelemen, This mechanism will be removed in future with `OptimizationApplication` which is more generic and in there, no need to maintain any kind of lists.... :D
