### ISSUE TITLE
[Dam] Problem with non-active entities when initializing

### ISSUE THREAD

**Issue by joaquinirazabal** [KratosMultiphysics/Kratos#10877]
**Description**
When calculating the construction of a Dam with the DamApplication we have some non-active entities that become active during the simulation. The issue is that, after a long time without using it, now we have a segmentation fault once the entities are activated.

The problem is solved just removing the if (rEntity.IsActive()) in the function InitilizeEntities of [kratos](https://github.com/KratosMultiphysics/Kratos/tree/master/kratos)/[utilities](https://github.com/KratosMultiphysics/Kratos/tree/master/kratos/utilities)/entities_utilities.h

Would that be an appropriate change, or should I proceed another way?

**Scope**
- KratosCore

**Comment by rubenzorrilla** [comment]
From your explanation, it seems to me that the `ACTIVE` flag is no longer present in your entities, which is weird...

Did you try to run in `FullDebug` mode to see if we get a bit more information?

**Comment by philbucher** [comment]
This is a sensitive change, I think @KratosMultiphysics/geomechanics needs it the other way round 🤔

**Comment by joaquinirazabal** [comment]
Ok, thanks for the comments, I will try to figure out other solutions taking into account your suggestions.
