### ISSUE TITLE
Adding "ApplicationName" and keep a record of registered applications

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1088]
This is my latest try at this :-)

I would propose that KratosApplication is made to require a string for the name in the constructor.

This would allow that Kernel.AddApplication(), the function that registers the application in the kernel, also keeps track of the registered applications, thus allowing to define a function

kernel.ApplicationIsRegistered( application_name )

giving back a true or false.

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee 

this is working inthe branch, however we need to choose which string to respond to if we do

       kernel.HasApplication("KratosFluidDynamicsApplication")

which is equivalent to asking which name we should give to the applications.
The point is that right now we do

      import KratosMultiphysics.FluidDynamicsApplication

but the actual library is called "KratosFluidDynamicsApplication". We hence need to decide if we want the "KratosMultiphysics.*" or not. and wheter to add the "Kratos" in the name of the app to make it consistent with the name of the object.

**Comment by jcotela** [comment]
My vote is for
```
kernel.HasApplication("FluidDynamicsApplication")
```
That is, the same name we give to the module, in Python. I think consistency within Python makes it simple for "end users", while we developers can more easily "know" this trick.

**Comment by RiccardoRossi** [comment]
+1

**Comment by philbucher** [comment]
closing since solved in #1126
