### ISSUE TITLE
[Request] Status Board for Applications

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#10893]
## Motivation

I often find myself browsing through the applications to get a feel of what shape they're in, and it's quite a hassle to find out whether they're being actively developed, just maintained, or abandoned and not even compiled in the CI. It'd be very useful to both developers and prospective users, to have an overview of all applications on the github landing page: info about what the app is used for, who developed it, who's maintaining it, and whether it's supported and tested or not.

## Request

Insert a decent-looking tabular status board in the main *readme* with useful information about all applications within the repo. I'm thinking something along these lines, but of course with better visuals:
```
+--------------------+------------------------------+-----------------------+-----------------------------+
| Application        |  Description                 | Status                | Authors                     |
+--------------------+------------------------------+-----------------------+-----------------------------+
| {application name, | {short description about     | {Actively developed,  | {list of authors and their  |
|  logo, etc.}       |  what the application does,  |  maintained,          |  contacts, if available}    |
|                    |  eg.: copied from its own    |  abandoned,           |                             |
|                    |  readme.}                    |  deprecated,          |                             |
|                    |                              |  etc.}                |                             |
+--------------------+------------------------------+-----------------------+-----------------------------+
| ...                | ...                          | ...                   | ...                         |
+--------------------+------------------------------+-----------------------+-----------------------------+
```

**Comment by loumalouomega** [comment]
@KratosMultiphysics/all

**Comment by rubenzorrilla** [comment]
👍 I think we can consider having this table updated as a requirement to consider an application as core application.

**Comment by loumalouomega** [comment]
I already added mine :)

**Comment by AlejandroCornejo** [comment]
I agree, if there is consensus I will add it to the `ConstitutiveLawsApp`, `StructuralMechanicsApp` and `FemToDemApp`
