### ISSUE TITLE
Fluid element with bdf2 scheme

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#1090]
Hi @jcotela,

if I remember correctly there was a possibility to use the bdf2 time integration scheme for fluid elements. Is this correct? If yes, is this still possible? 
Reason for my question is, that @philbucher and me are currently doing some tests with different FSI problems and we found out that integrating the structure in time by the bdf2 is far more robust then with Newmark or Bossak scheme. Thus we would like to use bdf2 for the fluid if possible in order to be consistent.

**Comment by loumalouomega** [comment]
In fluids is called gear scheme

**Comment by philbucher** [comment]
is this still in the code?

**Comment by loumalouomega** [comment]
yes, here: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/custom_strategies/strategies/gear_scheme.h

**Comment by jcotela** [comment]
@loumalouomega is correct (and very fast). If you want to see an example of use (in the old python solver script format), look here: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/python_scripts/monolithic_solver_bdf2.py

**Comment by jcotela** [comment]
By the way, @KratosMultiphysics/fluid-dynamics: would you agree renaming this scheme to something more easily identifiable as BDF2?

**Comment by loumalouomega** [comment]
Related #1027

**Comment by philbucher** [comment]
thx @jcotela 
Are you planning to have this scheme in the new python solvers? From what I see it could be integrated with only a few lines in the `Initialize` Function of the `NavierStokesSolver_VMSMonolithic`

**Comment by jcotela** [comment]
@philbucher To be honest I had not considered it so far, but it is true that it should be an easy addition. We can do it. I just need to check that the trilinos version is still OK too.

**Comment by AndreasWinterstein** [comment]
@jcotela thx.

Again it would be very nice to have a consistent way of time integration in FSI for fluid and structure, which is not depending on any parameter choice. So far we are not sure what is exactly the problem with Newmark and Bossak in FSI, but I have some suspicion what it might be. I will try to use the bdf2/gears scheme and we will let you know what is the problem as soon as we find out.

**Comment by rubenzorrilla** [comment]
@AndreasWinterstein we are having problems as well... A few days ago I tried the BDF2 scheme implemented by @loumalouomega together with my element (the time integration is done inside the element using a BDF2 scheme as well) and your ALE mesh solver (BDF2). 

With this recipe, we couldn't get rid of our pressure oscillation problems. If we found something, I will let you know.
