### ISSUE TITLE
[MPM] Missing dependency pyevtk

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#10907]
**Description**
When running an MPM example, with vtk output, this error shows.
![image](https://user-images.githubusercontent.com/5918085/226880506-d0c19665-2d97-46b4-b096-b5ad696f77a9.png)

Seems to be missing this package -> pyevtk

**Scope**
I only found it in the MPM app, when VTK output is enabled

**To Reproduce**
Just execute any example for MPM

**Expected behavior**
MPM should have it as registered dependency

**Environment**
- Windows
- GID 16.1.4d > internet retrieve Kratos 9.3.2

@KratosMultiphysics/mpm

**Comment by jginternational** [comment]
Probably should be added here
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/ParticleMechanicsApplication/ParticleMechanicsApplication.json

**Comment by mpentek** [comment]
Recently come across this myself.

@antonialarese @VeronikaSinger

**Comment by philbucher** [comment]
afaik some special treatment is required to make MPM work with the core vtk output
I.e. some derived class (`MPMCtkOutput`) would need to be implemented with the required changes. I designed the `VtkOutput` with this in mind, similar to how the `EigenVtkOutput` in StructuralMechanics works

The current solution based on pyevtk was a rapid prototype iirc

**Comment by ncrescenzio** [comment]
I am writing a `ParticleVtkOutput` class for the `ParticleMechanicsApplication` derived from the `VtkOutput` class in the core. The dependency on `pyevtk` will be removed soon.

**Comment by ncrescenzio** [comment]
Issue fixed by #11140
