### ISSUE TITLE
amgcl test in core fails

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1091]
This is the issue for the discussion started in #1086

**Comment by ddemidov** [comment]
ddemidov/amgcl#53 should fix failing BiCGStab tests. The test with BiCGStab(L) has legitimate breakdown for the problem used in the test. ddemidov/amgcl#55 changes AMGCL implementation of BiCGStab(L) from [1] to [2], but the breakdown is still present.

There are a couple possible workarounds for this:
* Use non-zero initial approximation (set x to 1 [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/test_linear_solvers.py#L38)). This is made possible by ddemidov/amgcl#54.
* Choose different value for L. L=5 seems to work for the problem being tested.
* Use relaxation other that ILU(k).

[1] Sleijpen GL, Fokkema DR. BiCGstab (l) for linear equations involving unsymmetric matrices with complex spectrum. Electronic Transactions on Numerical Analysis, 1993.
[2] Fokkema, Diederik R. “Enhanced implementation of BiCGstab (l) for solving linear systems of equations.” Universiteit Utrecht. Mathematisch Instituut, 1996.

**Comment by RiccardoRossi** [comment]
@philbucher i think this is fixed in #1212

**Comment by philbucher** [comment]
Yep I will test it but it is not compiling

**Comment by philbucher** [comment]
Fixed in #1212
