### ISSUE TITLE
[Core] MetisDivideHeterogeneousInputProcess assigns conditions wrongly

### ISSUE THREAD

**Issue by sunethwarna** [KratosMultiphysics/Kratos#10938]
**Description**

The `MetisDivideHeterogeneousInputProcess` fails to assign conditions correctly in partitioning.

Following are the details of the mdpa:

MDPA (Quads 2D4N, Line2D2N):
Partitioning: grey: rank 0, green: rank 1, red: rank 2
Node ids: In bold underlined pink near nodes
Condition ids: Strike through numbers
Element ids: numbers in the middle of elements

![image](https://user-images.githubusercontent.com/7856520/228777720-8030d2ba-1ba3-4835-9f9d-fb8e9924d0ed.png)

I digged through the bug, and found the following:

After metis does partitioning based on element connectivities, we do the following call:

https://github.com/KratosMultiphysics/Kratos/blob/68f678be94b7bac4521dd709c7b5970e0cc3fbfc/applications/MetisApplication/custom_processes/metis_divide_heterogeneous_input_process.cpp#L405-L409
Metis partitioner input for the above line:
```c++
rNodePartition = [0, 0, 2, 0, 0, 0, 0, 0, 2, 2, 2, 0, 2, 2, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 2]
rElemPartition = [0, 0, 0, 0, 0, 2, 0, 2, 1, 2, 2, 2, 1, 1, 1, 2]
```

The issue is, if you check the element with id = 4 (index 3 in rElemPartition):
The connectivity node ids: [7, 9, 10, 8]
The connectivity sorted index ids in rNodePartition: [6, 7, 8, 9]
Ranks those node ids belongs to is: [0 ,0 ,2, 2]

Then we call `PartitionConditionsSynchronous`, in there after the following:
https://github.com/KratosMultiphysics/Kratos/blob/68f678be94b7bac4521dd709c7b5970e0cc3fbfc/applications/MetisApplication/custom_processes/metis_divide_heterogeneous_input_process.cpp#L424-L443

the cond_id = 10 (9th index in `rCondPartition`) is assigned to rank = 2 because, all the connectivity nodes in that condition are in rank 2 as shown below. [connectivity ids: [9, 10], connectivity node id indices in `rNodePartition` = [8, 9]]
```c++
rCondPartition = [0, 1, 0, 1, 0, 1, -1, -1, 0, 2, 0, 2, -1, -1, 1, -1]
```

then the following check will be skipped for cond_id = 10:
https://github.com/KratosMultiphysics/Kratos/blob/68f678be94b7bac4521dd709c7b5970e0cc3fbfc/applications/MetisApplication/custom_processes/metis_divide_heterogeneous_input_process.cpp#L450

hence this condition will not be assigned to the same rank where its parent element belongs to.

**Scope**
- Kratos Core

**To Reproduce**
[Archive.zip](https://github.com/KratosMultiphysics/Kratos/files/11109658/Archive.zip)
Extract the above archive zip and run the following command. It only happens with `-np 3`.
```bash
mpirun -np 3 python test_code.py  
```

**Expected behavior**
the cond_id=10 should be in rank 0. If I remove the `if *itPart == -1)` then it correctly assigns the condition to the partition.

**Environment**
- Linux (Manjaro) (I have only tested this in linux)
- Metis 5.1.0
- python 3.10.9
- gcc 12.2.1

**Comment by sunethwarna** [comment]
Hi @jcotela... Welcome back :) .... Could you have a look at this?

**Comment by jcotela** [comment]
In short: I think this is a bug.

The partitioner takes a shortcut when deciding where the conditions (and elements) are assigned to: if all nodes belong to the same partition, assign it to that partition and go ahead. This is wrong in this case: all nodes of your condition belong to the same partition, but it is not the same partition the element was assigned to. 

The fix, as you correctly point out, is to ignore the first guess and always partition the condition using the standard criteria.

Interestingly, this situation should be impossible on linear triangles with line conditions or linear tetras with triangle faces (if all nodes on one face belong to the same partition, it is the majority partition for the element too, so the element will be on the same partition), which is likely the reason why we never noticed.
