### ISSUE TITLE
Wrong distance in calculate distance to skin process

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#10957]
I am using the process to calculate distance to skin and I found that the distance is some nodes is not correct. The problem arises because I am in a limit case where there are corner elements in the volume model part that have all nodes exactly on the skin. When computing elemental distances here
https://github.com/KratosMultiphysics/Kratos/blob/e0d54c722003c1383e03923115d5e8503c1e8ae6/kratos/processes/calculate_distance_to_skin_process.cpp#L167
we get the follwing vector: elemental_distances : `(-2.22045e-16,-2.22045e-16,-2.22045e-16,-2.22045e-16)`.
As they are all negative , the element is set as SPLIT=false here
https://github.com/KratosMultiphysics/Kratos/blob/e0d54c722003c1383e03923115d5e8503c1e8ae6/kratos/processes/calculate_distance_to_skin_process.cpp#L180
And therefore it is not used later to compute nodal distances here https://github.com/KratosMultiphysics/Kratos/blob/e0d54c722003c1383e03923115d5e8503c1e8ae6/kratos/processes/calculate_distance_to_skin_process.cpp#L231

I might be missing something but I think that if there is any node whose distance is very close to zero when computing the elemental distances, we should then consider the element as SPLIT and use it for the nodal distance calculation.

**Comment by rubenzorrilla** [comment]
(I edited the comment because the vector values weren't shown before).

**Comment by ddiezrod** [comment]
I like your idea, that should work fine, thanks for the advice ;)
