### ISSUE TITLE
Write c++ tests running only with MPI

### ISSUE THREAD

**Issue by ncrescenzio** [KratosMultiphysics/Kratos#10974]
For the applications with  `trilinos_extension` (and thus supporting `MPI`), is it possible to write cpp tests that are executed only when Kratos is compiled with `MPI`? For example because these tests use an utility defined in `ApplicationName/trilinos_extension/custom_utilities`.

**Comment by philbucher** [comment]
Sure, there is a DISTRIBUTED_Test case around (don't remember the exact name, but you can check the tests in the MPICore)

**Comment by ncrescenzio** [comment]
ok, thanks @philbucher. But then do I have to create a `tests` folder inside the `trilinos_extension` and add these test files in the `CMakeLists.txt` in there, right?

**Comment by philbucher** [comment]
yes basically

Check how I [did it in the MappingApp](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MappingApplication/mpi_extension/cpp_tests/test_mapper_utilities_mpi.cpp). This is basically what you need
Corresponding CMake

Note that I called it mpi_extension bcs in the future I want to get rid of Trilinos. If you don't use Trilinos I recommend the same

**Comment by ncrescenzio** [comment]
Thanks, this is exactly what I need! I gave a look to all the applications with a `trilinos_extension` folder so I missed the `MappingApplication`... Thanks again @philbucher!
