### ISSUE TITLE
Removing 'if not defined KRATOS_BUILD_TYPE' from Windows configure

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#10986]
**Description**
If this line is coded like this
https://github.com/KratosMultiphysics/Kratos/blob/374f885eeb60f5a165669b4fac43708982d50fb2/scripts/standard_configure.bat#L23
It can happen that, after editing the value of KRATOS_BUILD_TYPE , the change is ignored until you open a new terminal. This happened to me last week and lost quite a lot of time. I guess it could happen also if you try to compile the Relase and the FullDebug version in the same terminal.
Is this part (`if not defined KRATOS_BUILD_TYPE`) really necessary? Why not just define the value?
@KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
You are right. This is known.

The reason behind this was to be able to give priority to variables set in the environment (for CI mainly).

To be honest we don't use this in the internal Kratos CI anymore, but I do not know if someone else does (@KratosMultiphysics/altair?)

**Comment by maceligueta** [comment]
@akhilkmat FYI

**Comment by ddiezrod** [comment]
We do not use this file directly in altair, however the current behaviour makes sense to me. You want to be able to change the KRATOS_BUILD_TYPE to FullDebug for example without modifying the file...

**Comment by roigcarlo** [comment]
It also makes sense to me. Initially I was against having this but it has proven to be useful in many places. The odd behavior here is how windows handles variable lifetimes in existing sessions

**Comment by roigcarlo** [comment]
I will leave the scripts as are as are needed in some CI as I commented, but feel free to create custom configure setting them directly.
