### ISSUE TITLE
"ImportError: DLL load failed while importing KratosLinearSolversApplication" when using MKL under Windows 11

### ISSUE THREAD

**Issue by clazaro** [KratosMultiphysics/Kratos#10998]
**Description**
I have compiled Kratos under Windows 11 with the MKL library following the Install instructions without problem. 

However, when running a simulation with the pardiso.lu solver, I get
`ImportError: DLL load failed while importing KratosLinearSolversApplication`
I checked that the file `\bin\Release\libs\KratosLinearSolversApplication.pyd` exists. I opened it with Dependencies and it turns out that `mkl_rt.2.dll` can´t be found. In fact, there is a `mkl_rt.lib` file, but not a file with that exact name.

I downloaded and installed openAPI from the Intel website, and I included the following lines in the config file:
```
call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat" intel64 lp64
if not defined MKL_ROOT set MKL_ROOT="C:\Program Files (x86)\Intel\oneAPI\mkl\2023.1.0"
CALL :add_app %KRATOS_APP_DIR%\LinearSolversApplication;
cmake -G"Visual Studio 16 2019" -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%" ^
-DUSE_EIGEN_MKL=ON
```
If -DUSE_EIGEN_MKL is turned OFF Kratos runs well, but I want to use pardiso.lu because the performance is one order of magnitude faster (at least this is my experience under Linux, and I wish to replicate it under Windows).

Any help will be welcome!

**Scope**
- Compilation/execution

**Comment by roigcarlo** [comment]
Hi, 

If it happens when running and you compiled with MKL it is likely that you are not executing the Intel setenv.bat script before running the problem.

You must use:
```
call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat" intel64 lp64
```

In your launch script or once you open the terminal if you are running it by hand.

**Comment by clazaro** [comment]
Hi,
The call was indeed missing in my launch script. I have added it, but it reports the same error. Also reports the error when running the call from the terminal before executing Kratos.

**Comment by roigcarlo** [comment]
Hi,

Are you seeing a message like:
```Bash
:: initializing oneAPI environment ...
   zsh: ZSH_VERSION = 5.9
   args: Using "$@" for setvars.sh arguments:
:: compiler -- latest
:: debugger -- latest
:: dev-utilities -- latest
:: dpl -- latest
:: mpi -- latest
:: tbb -- latest
:: mkl --latest
:: oneAPI environment initialized ::
``` 

Before running the case? If not, the env vars are not being set correctly. It should be handled by intel, but if it is the case you may try to add  `"C:\Program Files (x86)\Intel\oneAPI\mkl\2023.1.0\[path to the dll]"` directly to your `PATH` variable.

the [] is usually "latest/lib/intel64/...." but can change between version, you will have t osearch for the folder containing the dll and replace.

**Comment by clazaro** [comment]
I think I understand where the problem lies, but I don´t know how to solve it:
Using
```
call "C:\Program Files (x86)\Intel\oneAPI\mkl\latest\env\vars.bat" intel64 lp64
```
results in the following paths being added to the PATH variable:
```
C:\Program Files (x86)\Intel\oneAPI\mkl\latest\redist\intel64;
C:\Program Files (x86)\Intel\oneAPI\mkl\latest\bin\intel64;
```
However, the required library `mkl_rt.lib` is in `...\lib\intel64`
This other path has been added by`vars.bat` to a different environment variable as follows:
```
NLSPATH=C:\Program Files (x86)\Intel\oneAPI\mkl\latest\lib\intel64;
```
The problem is that the library is apparently not found or included during the compilation/building, apparently because vars.bat has the behaviour I described. 

Adding `C:\Program Files (x86)\Intel\oneAPI\mkl\latest\lib\intel64` to the PATH variable when running doesn´t fix the problem.

**Comment by clazaro** [comment]
An additional information: the message you mention is not displayed when running `...\vars.bat`. A similar message is shown though when running `C:\Program Files (x86)\Intel\oneAPI\setvars.bat`. However, the result is the same concerning mkl as described in my previous message.

**Comment by roigcarlo** [comment]
Mmm this is quite odd.

In general what you want is not the `.lib` file. This only includes information about symbol names, and is used during the compilation (to be precise, during the linking stage)

>  results in the following paths being added to the PATH variable:
C:\Program Files (x86)\Intel\oneAPI\mkl\latest\redist\intel64;
C:\Program Files (x86)\Intel\oneAPI\mkl\latest\bin\intel64;

This is precisely what needs to happen. If those locations are available through the path, you should be able to run. The only problem I can see here is that `latest`, which is a symlink to the last version folder is somehow broken.

A very bold solution would be to copy the dll's in `C:\Program Files (x86)\Intel\oneAPI\mkl\latest\redist\intel64` to `kratos\libs` folder (where the .lib is)

If this does not work maybe is easier to arrange a meeting and look directly into your computer (if you are ok with it)

**Comment by clazaro** [comment]
The "bold" solution works fine. Many thanks @roigcarlo!

The reason why it couldn´t find the missing dll is misterious though. I checked that the rigth path was set prior to running Kratos (`C:\Program Files (x86)\Intel\oneAPI\mkl\2023.1.0\redist\intel64`) even without the `latest` symlink, and also executed it with admin privileges, but to no avail.

I would be interested to know if someone else has experienced the same problem, because this solution is effective, but not very nice :)

I am closing this as solved.
