### ISSUE TITLE
The nightly build is still downloading the code from SVN

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#11]
@roigcarlo would you please reconfigure it to get the code from GitHub?

**Comment by roigcarlo** [comment]
Update on this: The script was changed in #47 but it appears that part of the changes need to be in the amazon user script.

If everything goes well, the next build should use the script from the repo instead of the hardcoded intructions on launch.

I will let this open until it works.

**Comment by roigcarlo** [comment]
Solved, I'm creating another issue relating problems when downloading kratos as a zip.

**Comment by RiccardoRossi** [comment]
just one thing: you might want to use the 

git checkout --depth=1 as an alternative (but i am fine with using zip)

**Comment by roigcarlo** [comment]
Mainly the problem is that, there is not git in the AMI in the first place

**Comment by pooyan-dadvand** [comment]
It is very rare that git is not there by default....

**Comment by roigcarlo** [comment]
Well, it does... but its a little bit old, I was trying to avoid it
