### ISSUE TITLE
Cross product calculation

### ISSUE THREAD

**Issue by GuillermoCasas** [KratosMultiphysics/Kratos#1100]
If I am not mistaken, the implementation of the CrossProduct from math_utils.h fails if the same vector is fed to the function as the output and as one of the factors, bacause its components are modified during the calculation. I tried it in the following simplified implementation, which shows the erroneous behaviour:

`#include <iostream>
using namespace std;

static inline void CrossProduct(
    double c[2], 
    const double a[2], 
    const double b[2]
    )
{
    c[0] = a[1]*b[2] - a[2]*b[1];
    c[1] = a[2]*b[0] - a[0]*b[2];
    c[2] = a[0]*b[1] - a[1]*b[0];
}

int main()
{   
    double a[3] = {1,0,0};
    double b[3] = {0,1.0};
    double c[3] = {3,3,3};
    CrossProduct(b, a, b);
    cout << b[0] << b[1] << b[2];

    return 0;
}`

And the result is 000 instead of 001.

**Comment by loumalouomega** [comment]
You can use a copy of the first one instead

**Comment by loumalouomega** [comment]
That way you will avoid the problem

**Comment by maceligueta** [comment]
Using a copy makes it slower, though.

**Comment by loumalouomega** [comment]
Yes, but the other option is to change the way it works

**Comment by GuillermoCasas** [comment]
Of course, but I think this behaviour is very easy to overlook, making the function unsafe in practice.

**Comment by RiccardoRossi** [comment]
I am afraid here is no way to avoid a copy here. What we could do is to
implement a aliasing check in debug mode.

Having said this please DO NOT use c arrays in kratos code

Cheers
Riccardo

**Comment by GuillermoCasas** [comment]
I am not advocating for the use of C arrays, it was only an example outside of Kratos.

**Comment by GuillermoCasas** [comment]
Maybe something like: 
```
{
auto c0 = a[1]*b[2] - a[2]*b[1];
auto c1 = a[2]*b[0] - a[0]*b[2];
c[2] = a[0]*b[1] - a[1]*b[0];
c[0] = c0;
c[1] = c1;
}
```

wouldn't be that bad, despite the allocations. What do you think?

**Comment by RiccardoRossi** [comment]
hi @GuillermoCasas, this is completely equivalent to making a copy as Vicente suggested.

my suggestion would be to do something of the type

     #ifdef KRATOS_DEBUG
          if(&c == &a) //if the direction is the same we have aliasing
               KRATOS_ERROR << "aliasing between the output parameter and the first input parameter";
          if(&c == &b) //if the direction is the same we have aliasing
               KRATOS_ERROR << "aliasing between the output parameter and the second input parameter";
     #endif

**Comment by GuillermoCasas** [comment]
Well, I think Vicente meant for me to copy the vector before calling the function. On the other hand, making a copy of two entries might be less work than copying the object itself, which could be large. Having said that, I think your suggestion is also reasonable.

**Comment by RiccardoRossi** [comment]
@GuillermoCasas we have been discussing this in the Technical committee. We reached the conclusion that although your solution is viable, and most probably would not be very expensive, we shall always assume that there is no aliasing between the parameters of a function. This is a general guideline, and we shall also use this rationale in this case rather than considering it as an exception.For this reason we will add the aliasing check in debug mode to warn if one is making a mistake

**Comment by loumalouomega** [comment]
What I am supposed to do with my PR?, I implemented an aliasing check

**Comment by RiccardoRossi** [comment]
we shall use yours to fix this. so reference this issue in your PR

**Comment by GuillermoCasas** [comment]
Fair enough!
