### ISSUE TITLE
Store and pass coupling term to FEM and DEM

### ISSUE THREAD

**Issue by chyalexcheng** [KratosMultiphysics/Kratos#11006]
Compute the coupling body force density and pass it to the FEM and the DEM solver using `before_data_transfer_operations` or `after_data_transfer_operations`

**Comment by chyalexcheng** [comment]
During the meeting with Miguel, we were checking this settings file:

[https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/tests/pfem_fem_waterslide2d/cosim_pfem_fem_waterslide2d_parameters.json](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKratosMultiphysics%2FKratos%2Fblob%2Fmaster%2Fapplications%2FCoSimulationApplication%2Ftests%2Fpfem_fem_waterslide2d%2Fcosim_pfem_fem_waterslide2d_parameters.json&data=05%7C01%7Ch.cheng%40utwente.nl%7C537626542d7d44cf849308db3cd40c86%7C723246a1c3f543c5acdc43adb404ac4d%7C0%7C0%7C638170653692723039%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hfn8fqJOEL%2FoUtJCAj660O2Sevy5Ms9H7ETHhzm%2BN8A%3D&reserved=0)

Where we can see:

        "coupling_operations" : {

            "compute_boundary_force_process": {

                "type"       : "compute_boundary_force",

                "echo_level" : 0,

                "solver"            : "pfem",

                "model_part_name"   : "PfemFluidModelPart.InterfaceWall",

                "write_output_file" : false,

                "width"             : 1,

                "interval"               : [0.0,"End"],

                "output_file_settings": {

                    "output_path": "force_output"

                    }

            },

            "reset_pfem_kinematics_fluid": {

                "type"       : "reset_pfem_kinematics",

                "echo_level" : 0,

                "solver"            : "pfem",

                "model_part_name"   : "PfemFluidModelPart.Fluid",

                "interval"               : [0.0,"End"]

            }

        },

 

"compute_boundary_force_process"  is just an alias invented when writing the settings file.

"type”    : “compute_boundary_force” actually refers to a python script, located here:

[https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/coupling_operations/compute_boundary_force.py](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FKratosMultiphysics%2FKratos%2Fblob%2Fmaster%2Fapplications%2FCoSimulationApplication%2Fpython_scripts%2Fcoupling_operations%2Fcompute_boundary_force.py&data=05%7C01%7Ch.cheng%40utwente.nl%7C537626542d7d44cf849308db3cd40c86%7C723246a1c3f543c5acdc43adb404ac4d%7C0%7C0%7C638170653692723039%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=W6lXBzcHSg9sStOsnTWnFSFKywrrJSIu7f%2BVBrVCON8%3D&reserved=0)

**Comment by akhilkmat** [comment]
Please check the latest commit, i have uploaded all the files related to volume coupling in its current form.
