### ISSUE TITLE
type casting when using pybind11

### ISSUE THREAD

**Issue by behzadtabari** [KratosMultiphysics/Kratos#11012]
Hi, I want to pass a function arg to the object then I want to cast the function to the std function and then save it as the private member of my class, but the compiler complains and I do not know what to do. I know it may not seem relevant but if answered makes my job way easier to work on Kratos. tnx

I have a class defined and declared as below:

#declaration

      class KRATOS_API(OPTIMIZATION_APPLICATION) NLOptOptimizer 
    {
     public:
        KRATOS_CLASS_POINTER_DEFINITION(NLOptOptimizer);

      
      void SetFunction(std::function<double(const std::vector<double>&, std::vector<double>&, void*)> objective_function) ;
      
      void Optimize();

    private:
     std::function<double(const std::vector<double>&, std::vector<double>&, void*)> objective_function_; 
    };

#definition

```
   void NLOptOptimizer::Optimize(){ 

   nlopt::opt opt_("LD_MMA", 2);
    opt_.set_min_objective(objective_function_, NULL);
    }

   void NLOptOptimizer::SetFunction(std::function<double(const std::vector<double>& x, std::vector<double>& y, void* z)> 
   objective_function) {
        objective_function_ = std::move(objective_function);
      }


   py::class_<NLOptOptimizer>( m, "NLOptOptimizer")
        .def(py::init<>())
       .def("set_function", [](NLOptOptimizer &opt, py::function func) {
            opt.SetFunction([func](const std::vector<double> &x, std::vector<double> &grad, void *data) -> double {
                return func(x, grad, data).cast<double>();
            });
        })
        .def("optimize", &NLOptOptimizer::Optimize);
     }       
 
```

python test

```
def myfunc(x, grad,data):
    if grad.size > 0:
        grad[0] = 0.0
        grad[1] = 0.5 / np.sqrt(x[1])
    return np.sqrt(x[1])


opt = KratosOA.NLOptOptimizer()
opt.set_function(myfunc)
opt.optimize()
```

error :
_opt.set_function(myfunc)
AttributeError: 'KratosOptimizationApplication.NLOptOptimizer' object has no attribute 'set_function'_

**Comment by rubenzorrilla** [comment]
You're trying to pass a Python object to c++, something that we intentionally avoid. I'd define `myfunc` in c++ instead.

**Comment by behzadtabari** [comment]
> You're trying to pass a Python object to c++, something that we intentionally avoid. I'd define `myfunc` in c++ instead.

Yes I see and already get that in future it'll probably get tougher with more complex data types, but the point is if I don't pass the function arg from python, the user probably needs to recompile the whole program to solve and this is probably more gruelling, even though I'd be happy to hear what's your stance on this?

**Comment by loumalouomega** [comment]
> > You're trying to pass a Python object to c++, something that we intentionally avoid. I'd define `myfunc` in c++ instead.
> 
> Yes I see and already get that in future it'll probably get tougher with more complex data types, but the point is if I don't pass the function arg from python, the user probably needs to recompile the whole program to solve and this is probably more gruelling, even though I'd be happy to hear what's your stance on this?

You can check https://github.com/loumalouomega/KratosPythonWrapperApplication, which dows what you want. It is not up to date. As @rubenzorrilla we doen't support offically to pass python -> C++, but I already did the work I did the repo for the app.

**Comment by rubenzorrilla** [comment]
> > You're trying to pass a Python object to c++, something that we intentionally avoid. I'd define `myfunc` in c++ instead.
> 
> Yes I see and already get that in future it'll probably get tougher with more complex data types, but the point is if I don't pass the function arg from python, the user probably needs to recompile the whole program to solve and this is probably more gruelling, even though I'd be happy to hear what's your stance on this?

You can implement these in c++ and export them to Python so the user doesn't need to recompile anything. However, from your comment I think that you want to give the possibility of using custom objective functions... If so the situation is much more complicated.

**Comment by sunethwarna** [comment]
As @rubenzorrilla said, it is a complicated and we understand that it is required for OptimizationApplication to support with third party libs.   So we will update this thread when we are finished with the WIP.

**Comment by matekelemen** [comment]
there are a couple of cases when passing a function from python to C++ is viable, but there are some important caveats to it and spoiler: your case won't work.

1) all python objects (including your function object) are protected by the global interpreter lock (GIL) which will block any thread other than python's thread that tries to access a python object, meaning that these threads will hang until python terminates. This effectively means that performance-intensive functions that should run in parallel mustn't be passed from python.
2) any object accessible from python must have bindings. This includes function arguments such as that gradient that's supposed to be a mutable reference to a vector. The automatically generated STL container bindings provided by pybind11 will always **convert** vectors from C++ to python lists and vice versa, so mutable references won't work. You'll need to define your own bindings if you really want to stick to mutable references; check out the [pybind docs](https://pybind11.readthedocs.io/en/stable/advanced/cast/stl.html) on STL containers.
3) I'm not quite familiar with `pybind11::function`, but pybind can automatically bind python function objects to C++ lambdas if you `#include "pybind11/functional.h"`, so give that a try.

I´ll stress again that performance-intensive functions shouldn´t be passed from python, and your program will hang if you try invoking them on other threads. As the others suggested, you should define these functions in C++. Don´t worry about build times that much, you´ll only need to recompile translation units that you modified (+ relink downstream binaries but that ain´t so bad).
