### ISSUE TITLE
[GeoMechanicsApplication] Element GeoCrBeamElementLinear3D2N with pointload leads to crash

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#11053]
**Description**
GeoCrBeamElementLinear3D2N with PointMomentCondition3D1N leads to crash.
This is also valid when this element is used with PointLoad.

**Scope**
Where in Kratos is this bug happening. 
- GeoMechanicsApplication

**To Reproduce**
Example case is attached.
[test703a.zip](https://github.com/KratosMultiphysics/Kratos/files/11326574/test703a.zip)

**Expected behavior**
crash of the code.

**Environment**
- OS: Windows 10
- Branch: master
- Python 3.9

**Comment by mnabideltares** [comment]
@loumalouomega , 
It has big similarities with the beam CrBeamElementLinear3D2N of structural mechanics. However, it was introduced years ago in order to add multistage functionality into it (restart for the new stage). We are still looking into it as it is not finalized yet. We are also investigating the further differences of those two elements.

**Comment by mcgicjn2** [comment]
This should not be fixed in geo application, as the reason for its existence is no longer justified. We should use the initializition functionality at the start of a stage.

**Comment by indigocoral** [comment]
Will fix
#11465
