### ISSUE TITLE
[GeoMechanicsApplication] GeoCurvedBeamElement2D3N does not lead to expected results.

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#11054]
**Description**
Applying GeoCurvedBeamElement2D3N with PointMomentCondition3D1N.
It is expected the element to be curved to a complete circle. However this element underestimated the deformation.

**Scope**
- GeoMechanicsApplication

**To Reproduce**
Test case is added:
[test704a.zip](https://github.com/KratosMultiphysics/Kratos/files/11326712/test704a.zip)

**Expected behavior**
The beam is curved, but the deformation is underestimated.

**Environment**
- OS: Windows 10
- Branch: master
- Python 3.9

**Comment by mcgicjn2** [comment]
This should not be fixed in geo application, as the reason for its existence is no longer justified. We should use the initializition functionality at the start of a stage.

**Comment by indigocoral** [comment]
Will fix
#11466
