### ISSUE TITLE
⚠️ Node Template Change ⚠️

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#11080]
**Description**
@KratosMultiphysics/all We are going to proceed with an important change in the node, which is going to lose all template arguments (see #11056). Among other things, this will allow us to noticeably reduce the compilation times.

In short, you will now use `Node` instead of `Node<3>`.

This can be potentially disruptive in currently open branches. We inted to accept and merge the PR by the 12/05/2023 **This is in ONE WEEK TIME** so please be aware of that.

**Comment by rubenzorrilla** [comment]
Pinging @KratosMultiphysics/all.

**Comment by loumalouomega** [comment]
> Pinging @KratosMultiphysics/all.

![image](https://user-images.githubusercontent.com/19991680/236572239-0628cd3c-f94d-4d6c-99e4-8d1ef0e11515.png)

**Comment by rubenzorrilla** [comment]
Pinging @KratosMultiphysics/all again to put it in the top of the notification list. We recall that we'll merge this in two days.

**Comment by dcagritan** [comment]
Thanks for the notification. I guess I have to modify the PFEM2Application according to this PR, right?
Regards

**Comment by loumalouomega** [comment]
> > Thanks for the notification. I guess I have to modify the PFEM2Application according to this PR, right? Regards
> 
> @loumalouomega did all the changes. This will mainly affect forked repositories.

And branches

**Comment by dcagritan** [comment]
I see. Thanks!
Regards

**Comment by roigcarlo** [comment]
Closing as the merge has been done.

**Comment by loumalouomega** [comment]
Source/header separated in #11119
