### ISSUE TITLE
Can Travis detect if the changes of a PR were only in Python files? (so compilation is not needed)

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#1109]
A reminder of something commented in meeting.

**Comment by salvalatorre** [comment]
+1

**Comment by ipouplana** [comment]
:+1:

**Comment by loumalouomega** [comment]
yes, it would be very practical

**Comment by loumalouomega** [comment]
@roigcarlo will kill me, but there is an option for the commit https://coderwall.com/p/f7fusq/how-to-skip-making-a-build-in-travis-ci, please use it with responsabilty or erase this comment

**Comment by ipouplana** [comment]
Thanks! @loumalouomega, as your link stated, for commits unrelated to the compilation of Kratos that option was perfect

**Comment by loumalouomega** [comment]
To avoid the rage of @roigcarlo my commentary will disappear like tears in the rain...

**Comment by ipouplana** [comment]
Well, I already saved the order to add to avoid Travis ;)

**Comment by roigcarlo** [comment]
@loumalouomega Gmail always remembers...

I agree that is quite annoying, but is not as straighforward as it might seem:

**The (in)Famous comment**
1 - Feel free to use the comment, but bear in mind that if the build does not happen, the pass check will not trigger. 

2 - Moreover, it will have no effect on a PR, it is only for commits, but if you manage to skip the build please tell me how.

There is a open discussion here: https://github.com/travis-ci/travis-ci/issues/5374 about that topic

**The solutions**
1 - Stablish a naming convetion & desactivate the force check to merge. That will allow you to "mark" the branches so I can tell travis not to build the tests. For example "documentation/whatever" or "dem/python/fix-variable-foo". 

2 - Check in the travis machine all the files in a commit and determine whether something prone to fail has been touched or not. While this is easy for simple PR, it gets VERY complex if there are cherry-picks or merges among the commits.

I personaly would like to go for solution 1. In fact I proposed it more than once, but the @KratosMultiphysics/technical-committee has to agree...

**Comment by RiccardoRossi** [comment]
We discussed in the Technical Committee. 
Our decision is that we will maintain the current system, that is, passing though the travis will still be mandatory for the PRs. 

we will on the other hand try to avoid a full recompilation when only py files are changed, however this has some technical difficulties, particularly if we want python tests to be run.

Also as a guideline we remark that PRs should remain visible sufficient time for people to take a look at them. Say around a **working** day for the non trivial changes.
