### ISSUE TITLE
Mesh size changes the value of distributed load.

### ISSUE THREAD

**Issue by hrntsm** [KratosMultiphysics/Kratos#11109]
**Description**

When distributed loading is applied to a surface using "distribute_load_on_surface_process" as shown below, the analysis results will vary depending on the mesh size.

```json
"loads_process_list": [
      {
        "python_module": "distribute_load_on_surface_process",
        "kratos_module": "KratosMultiphysics.StructuralMechanicsApplication",
        "process_name": "DistributeLoadOnSurfaceProcess",
        "help": "This process distributes a load on surface load conditions belonging to a modelpart. The load is distributed according to the surface area.",
        "Parameters": {
          "load": [
            0.0,
            0.0,
            100000.0
          ],
          "model_part_name": "plate.distribute_load_nodes_conditions"
        }
```

The deformation contours are visualized in Paraview. Both analyses are performed with the above settings, but the finer mesh results in smaller displacements.

![image](https://github.com/KratosMultiphysics/Kratos/assets/23289252/d49576f2-672c-4a28-8605-adccb6b0fe4a)

Checking the reaction force, the one on the left is 634 and the one on the right is 107, and the reaction force values are different.
Since the reaction forces are different, it is not likely that the mesh size makes a difference in the accuracy of the analysis.

**Scope**
Where in Kratos is this bug happening. 

- StructuralMechanicsApplication

**To Reproduce**

Run "run_analysis.py" in the attached file
[model.zip](https://github.com/KratosMultiphysics/Kratos/files/11450402/model.zip)

**Expected behavior**

Both will have the same displacement and the same reaction force.

**Environment**

- OS: windows11
- Branch: use Release 9.3 via PYPI
- Python 3.9

**Comment by loumalouomega** [comment]
Strange, I wil take a look

**Comment by loumalouomega** [comment]
The reactions sums is also different?

**Comment by loumalouomega** [comment]
Okay, I found the error:

https://github.com/KratosMultiphysics/Kratos/blob/501e8204cc0cc926d71bc126e50ae85994aa12af/applications/StructuralMechanicsApplication/custom_processes/distribute_load_on_surface_process.cpp#L62

They are dividing by total area and then multiplying by area again (wrong!). The fix is easy, but may break things, wait a second and I fix it, but if you are using PiP packages you will need to compile it or to wait for next release.

**Comment by loumalouomega** [comment]
See https://github.com/KratosMultiphysics/Kratos/pull/11111, nice number
