### ISSUE TITLE
[Core] Can Properties print be improved?

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#11117]
When executing this piece of code:
```
for properties in model_part.GetProperties():
    print(properties)
```
I get a print like this one:
```
Properties
    YOUNG_MODULUS : 1                                                                                                   
This properties contains 0 tables                                                                                       
This properties contains the following subproperties 1 subproperties
    YOUNG_MODULUS : 3                                                                                                   
This properties contains 0 tables
Properties
    YOUNG_MODULUS : 2
This properties contains 0 tables
This properties contains the following subproperties 1 subproperties
    YOUNG_MODULUS : 4
This properties contains 0 tables 
``` 
In my opinion, this print is not as clear as it could be. The Ids of the properties do not appear anywhere, neither the ids of the subproperties. On top of that: the message `This properties contains the following subproperties 1 subproperties` actually means that there is one subproperty. And the last word could probably be in the next line as a header like 'SubProperties 2' (containing id)

@pooyan-dadvand

**Comment by maceligueta** [comment]
Also, we could add a function to the ModelPart like `PrintAllProperties()`. Does it make sense?

**Comment by RiccardoRossi** [comment]
I would be favorable to these additions

**Comment by loumalouomega** [comment]
I did #11118

**Comment by loumalouomega** [comment]
@maceligueta it is done
