### ISSUE TITLE
Segfault when destructor is inovked.

### ISSUE THREAD

**Issue by jrubiogonzalez** [KratosMultiphysics/Kratos#1112]
Very random, aprox. 10% of the runs. Using CentOS7 with included gcc.
![segfault](https://user-images.githubusercontent.com/25137726/33480590-74fd2698-d691-11e7-9e93-f77f3c58d2e7.png)

 @pooyan-dadvand

**Comment by pooyan-dadvand** [comment]
We should take out the thread id check of Modelpart which is destroyed before. I put it for the next release.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee can we remove this log at this moment until make a better solution for such cases?

**Comment by pooyan-dadvand** [comment]
So I will take it out until we add the logger.

**Comment by philbucher** [comment]
I think I have the same error
[Segfault_NR_Strategy.zip](https://github.com/KratosMultiphysics/Kratos/files/1560103/Segfault_NR_Strategy.zip)
