### ISSUE TITLE
Coupled Thermal & Structural Analysis

### ISSUE THREAD

**Issue by alexbrownsoft** [KratosMultiphysics/Kratos#11144]
Hi,

I would like to carry out a coupled thermal & structural analysis using Kratos. The analysis case is to first anlaysis the temperature distribution in a space & then analysis the deformation for a structure in the space.

I assume this should be quite straightforward, is that correct?

**Comment by miguelmaso** [comment]
Hi, I'm also interested in this topic, keep me updated on this

**Comment by rubenzorrilla** [comment]
Adding to @AlejandroCornejo 's comment that the super simple case of having an initial strain from a previous thermal analysis should be straightforward to be done with the `InitialState` object.

**Comment by alexbrownsoft** [comment]
Thank you both for the guidance! This is exactly I need.

In addition to above, If I would like to carry out thermal analysis & structural analysis separately, which applications should I refer to?

**Comment by AlejandroCornejo** [comment]
> Thank you both for the guidance! This is exactly I need.
> 
> 
> 
> In addition to above, If I would like to carry out thermal analysis & structural analysis separately, which applications should I refer to?

In that case, you should use ConvectionDiffusionApp for the thermal case and the StructuralMechanicsApp for the mechanical part. If non linear constitutive models are used, also the ConstitutiveLawsApp must be compiled.

**Comment by AlejandroCornejo** [comment]
Is this issue solved? :)
