### ISSUE TITLE
electromagnetic simulation in Kratos

### ISSUE THREAD

**Issue by alexbrownsoft** [KratosMultiphysics/Kratos#11145]
Can Kratos be used for electromagnetic simulation? If not currently suppoted, is is straightforward to add this in Kratos?

**Comment by rubenzorrilla** [comment]
Current version doesn't support so (at least not in the master branch). Nonetheless, and as far as I know, there is a fork from an old version of Kratos that is being used for such a purpose. I'm not aware of the technicalities of the problem, but I'm afraid that adding such capability wouldn't be an straightforward task...

**Comment by alexbrownsoft** [comment]
> Current version doesn't support so (at least not in the master branch). Nonetheless, and as far as I know, there is a fork from an old version of Kratos that is being used for such a purpose. I'm not aware of the technicalities of the problem, but I'm afraid that adding such capability wouldn't be an straightforward task...

Could you please kindly help to advise which fork or branch can I find the electromagnetic function?

**Comment by rubenzorrilla** [comment]
I think it's being used by a project partner of @soudah (not sure if it is whether open source or not).

**Comment by alexbrownsoft** [comment]
@soudah 

Dear Sir,
 
 Could you please kindly help to advise where can I find kratos applications for electricmag simulations?

**Comment by rubenzorrilla** [comment]
Also pinging @cpnarvaezmunoz.

**Comment by cpnarvaezmunoz** [comment]
Hi @alexbrownsoft, I have added the equations for electrostatics (electric force and electric field). It will be ready for the master, specifically DropletDynamics branch, in the next few weeks.

**Comment by alexbrownsoft** [comment]
> Hi @alexbrownsoft, I have added the equations for electrostatics (electric force and electric field). It will be ready for the master, specifically DropletDynamics branch, in the next few weeks.
Many thanks! how about the magnetic parts, is there any available functions to use? I searched on the web, it seems kratos used to have a specific app for electromagnetic simulations, is that app still available?

**Comment by AlejandroCornejo** [comment]
can we close this issue?

**Comment by rubenzorrilla** [comment]
I think we can. @alexbrownsoft feel free to reopen if needed.
