### ISSUE TITLE
StructuralMechanics ComputingModelPart Construction

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1115]
Dear @KratosMultiphysics/structural-mechanics 
Now that we have the `Kratos::Model`(see #1053 ) available the question is if we want to update the construction of the `ComputingModelPart`, see [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/check_and_prepare_model_process_structural.py#L26)
Continuing the discussion from #1113 

Right now we specify in the `ProjectParameters` the `problem_domain_sub_model_part_list` and the `processes_sub_model_part_list`, with which the `ComputingModelPart` is being constructed. 
An alternative would be to skip these settings and use all `SubModelPart`s for the `ComputingModelPart`. @loumalouomega is this what you meant?

I think what we have right now should be kept, since adding every submodelpart to the computingmodelpart leads to overhead and might also interfer with postprocessing. Furthermore I assume that there could be convergence issues with the elements that don't get any load or bcs

**Comment by RiccardoRossi** [comment]
i think that we don't need any longer the list of names in the ProjectParameters.

one disclaimer though: DO NOT use Model estensively, since the interface WILL change

**Comment by RiccardoRossi** [comment]
this is done i believe. @philbucher i am closing. reopen if i got it wrong
