### ISSUE TITLE
When there are multiple constraints, the analysis behaves as if all configuration files are one.

### ISSUE THREAD

**Issue by hrntsm** [KratosMultiphysics/Kratos#11165]
**Description**

I am trying to optimize the hooks  like the [example](https://github.com/KratosMultiphysics/Examples/tree/master/shape_optimization/use_cases/10_Multi_Constraint_Optimization_3D_Hook).

Objective function is weight minimization
The constraint is that no more strain energy than the initial is produced in the two load cases.

The json file is set up with the following loads, so the actual analysis results are the rightmost load in both cases.
Why are the conditions different from the json?

![Screenshot 2023-05-22 at 11 12 27](https://github.com/KratosMultiphysics/Kratos/assets/23289252/fba2ee34-9744-4919-87ab-721ff5076111)

**Scope**

- ShapeOptimization

**To Reproduce**

Run attached file.
[example.zip](https://github.com/KratosMultiphysics/Kratos/files/11526187/example.zip)

**Expected behavior**

Each analysis works as per the configuration file.
In the above file, the tip load and the base load are each analyzed without overlap.

**Environment**

- OS: windows11
- Branch: v9.3 via PYPI
- Python 3.9

**Comment by sunethwarna** [comment]
Hi,

One of the problems with the approach given in the example is, you are applying two load cases to the same domain without removing the other. That means, when constrain 1 is applied, it also has the tip load from the constraint 2 from the previous design iteration, hence the result as you explained. I have changed the input files ("analysis_parameters_base.json", "analysis_parameters_tip.json") to remove the load of the other case when it is running. Could you try it out and let us know?

[Archive.zip](https://github.com/KratosMultiphysics/Kratos/files/11540339/Archive.zip)

**Comment by hrntsm** [comment]
Hi @sunethwarna 

It worked fine with the files I received. Thnak you!
What is the approach to not same domain?
