### ISSUE TITLE
Functionally material properties

### ISSUE THREAD

**Issue by Mammad1992** [KratosMultiphysics/Kratos#11183]
How can I assign functionally material properties in Kratos Multiphysics? For example, Young's modulus be a function of x, y, z, t (E = E(x,y,z,t))

**Comment by loumalouomega** [comment]
Right now you can't, but it is something I have always thought about.

**Comment by loumalouomega** [comment]
Any practical use or just curiosity?

**Comment by rubenzorrilla** [comment]
I think this will be possible with the accessors once #11069 is merged.

**Comment by Mammad1992** [comment]
Now is a curiosity but in the future maybe I want to use that.

**Comment by loumalouomega** [comment]
> I think this will be possible with the accessors once #11069 is merged.

True, I don't know if for space, but for time for sure. @AlejandroCornejo

**Comment by AlejandroCornejo** [comment]
Well, in the custom `GetValue` added to the properties soon, the available data is `GetValue(const TVariableType& rVariable, const GeometryType& rGeometry, const Vector& rShapeFunctionVector, const ProcessInfo& rProcessInfo)`

so you will have access to time trhough the `ProcessInfo `and position with the `rGeometry`.
