### ISSUE TITLE
Point output process - error trying to write after ExecuteFinalize 

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#11208]
We are not able to use the point output process after https://github.com/KratosMultiphysics/Kratos/pull/9908 in our altair stage. This stage changes the Finalize function from analysis stage to add a final print, so the function looks like this (pseudocode)

AltairAnalysis
```
def Finalize(self):

   processes.ExecuteFinalize() #Here we compute some final post-processes results

   solver.Finalize()

   OutputLastStep()


def OutputLastStep(self):
    processes.ExecuteBeforeOutputStep()
    output_processes.PrintOutput() #here we print the results computed in the ExecuteFinalize()
    processes.ExecuteAfterOutputStep()

```

The reason for this structure is that there are some post-process results that can be only computed at the very end of the stage, so that is why we added the OuputLastStep function.

The problem with the point output process is that this process closes its output file in ExecuteFinalize() so when we call PrintOutput the process throws an error becuse the file is close.
https://github.com/KratosMultiphysics/Kratos/blob/e36816eb641329d2da9462ae8b829a9f8c72b70a/kratos/python_scripts/point_output_process.py#L141

The first solution I thought was to move the last print inside the ExecuteFinalize of the processes that need it, the problem with this is that then we are not calling ExecuteBefore/AfterOutputStep for the rest of the processes in the list, so I do not think this is valid solution.

Other possible solutions are:
- Add a Free method to the processes that frees the resources at the very end of the stage. (This could also maybe be done calling the Clear method which is not being called now in the analysis stage)
- Close the file in the process destructor (we are not completely sure this works well in python)
- Somehow modify the process so after the file is closed , calling PrintOutput just passes (or throws a warning)

Any other ideas are very welcome!!
Pinging to hear your thoughts: @KratosMultiphysics/technical-committee @KratosMultiphysics/implementation-committee @philbucher @jcotela @KratosMultiphysics/altair

**Comment by matekelemen** [comment]
I've heard other complaints about the point output process keeping files open (problems hitting the max number of open files supported by the OS) before. Seems to me that if you change the process to open file/write to file/close file, your (and others') problems will be solved.

**Comment by ddiezrod** [comment]
> I've heard other complaints about the point output process keeping files open (problems hitting the max number of open files supported by the OS) before. Seems to me that if you change the process to open file/write to file/close file, your (and others') problems will be solved.

that'd be fine with me 👍

**Comment by philbucher** [comment]
Seems like a good solution 

I thought it would be more efficient to keep it open rather than reopening it, but this is only a guess :)

I don't object changing it

**Comment by ddiezrod** [comment]
We found a solution in our side, closing.
