### ISSUE TITLE
Slow Automigrate / Initialize

### ISSUE THREAD

**Issue by c-thiel** [KratosMultiphysics/Kratos#11257]
**Description**
Currently Automigration of Kratos can be quite slow. In my experience this stronly depends on the underlying Database.
For the initial automigration / schema setup, I measured the following times:

- SQLite: ~2 Seconds
- Postgres: 20 Seconds
- CockroachDB: 2 Minutes (Using the managed service from Cockroach)

As most production setups probably use CockroachDB, my issue mainly is with CockroachDB.

While CockroachDB isn't known to be very quick creating new tables, I was wondering if there maybe is an option to improve on this performance - maybe by creating some tables in parallel wherever applicable.

**Comment by matekelemen** [comment]
You're probably have the wrong repo. This is **KratosMultiphysics/Kratos**, a framework for multiphysics solvers.

Did you mean [ory/Kratos](https://github.com/ory/kratos) perhaps?

**Comment by c-thiel** [comment]
Oh, sorry
