### ISSUE TITLE
WallCondition2D2N/ 3D3N vs. MonolithicWallCondtion2D/ 3D

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#1128]
The reason why the FSI is so unstable and is always crashing is the WallCondition2D2N or 3D3N, when solving the fluid with the monolithic solver. If I am using the WallCondition2D2N or 3D3N the simulation is very unstable. Using the MonolithciWallCondition2D or 3D at the interface all my simulations run and also the number of interface iterations needed reduces drastically. I tested different cases and all of them worked. Also reducing the time step size does not have a bad effect anymore. 

This is especially a problem, since the problem type in GID adds the WallCondition2D2N or 3D3N as a default in the *.mdpa file. 

@rubenzorrilla and @jcotela: @msandre and me had a short look at the conditions (wall_condition and monolithic_wall_condition), but be could not see any major difference in what they are doing. Probably you can have a closer look at those conditions, since you are more familiar with this code.

**Comment by jcotela** [comment]
@AndreasWinterstein you are right that the WallCondition2D/3D is intended for fractional step elements. The interface should assign it for monolithic problems. Still, I'm not sure what about the wall condition may be causing your issues... We'll llook into it.

**Comment by rubenzorrilla** [comment]
@AndreasWinterstein @msandre  In principle, the fluid solver (in this case the navier_stokes_solver_vmsmonolithic.py) substitutes the WallCondition2D2N and WallCondition3D3N written in the *mdpa by the correspondent MonolithicWallCondition2D and MonolithicWallCondition3D. This is done for the elements as well.

We can be sure that the element substitution mechanism is working well (otherwise no fluid solution would be found). We should check if the same is happening for the conditions or not. I will give you some feedback ASAP.

**Comment by AndreasWinterstein** [comment]
After updating the master branch yesterday my FSI examples are also working with the WallCondition2D2N. I did tests with different time step sizes, accuracies on the interface and also with Newmark and Bossak time integration for the structure. Can you please try your tests.

 When comparing the code to the version it was not working with I cannot find any difference, which might be responsible for solving the problems.

**Comment by rubenzorrilla** [comment]
Hi @AndreasWinterstein, which benchmark did you solve? the one you sent me? As I told you, our problem were related with oscillations in the fluid pressure field. Reading between your lines, I guess that you get rid of such pressure problems. Isn't it?

**Comment by AndreasWinterstein** [comment]
I solved the one I sent you and also the Mok example. I am currently having a look at the pressure. I will give you some feedback.

**Comment by AndreasWinterstein** [comment]
Hi @rubenzorrilla. I think we can close this issue since the problem is solved. Great job.
