### ISSUE TITLE
Change repo link

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#113]
In the Cimne website (http://www.cimne.com/kratos/) the link to the repository is the old one. We should change it to the Git one.

**Comment by loumalouomega** [comment]
![](https://media.giphy.com/media/l3vRb9mmxRREEHtvy/giphy.gif)

**Comment by pooyan-dadvand** [comment]
Thanks @rubenzorrilla
@antonialarese Would you please inform the maintainer of the webpage?

**Comment by antonialarese** [comment]
@rubenzorrilla I guess you meant the link in the wiki, right? Since no link in the repository is present in the web page.

I changed it in the wiki.

**Comment by loumalouomega** [comment]
I think that the links available here:

http://www.cimne.com/kratos/download.asp should be changed, now we are trying to migrate the Wiki to the GitHub one: https://github.com/KratosMultiphysics/Kratos/wiki

**Comment by rubenzorrilla** [comment]
@antonialarese yes, I was referring to the wiki link. Thanks!!

**Comment by roigcarlo** [comment]
Is this already done? Can we close the issue?

**Comment by loumalouomega** [comment]
@antonialarese @roigcarlo Not done yet

**Comment by antonialarese** [comment]
The links are the correct one to the wiki page.
The question is: which is the download/installation page that will be mantained? The wiki ne or the Github or both?

**Comment by loumalouomega** [comment]
We are migrating the wiki to GitHub, many information of the wiki is outdated, and the official wiki is now supposed to be the one in GitHub https://github.com/KratosMultiphysics/Kratos/wiki.

The installation and everything (important) is described there

**Comment by loumalouomega** [comment]
![](https://i.imgur.com/ToVEXc6.jpg)

**Comment by pooyan-dadvand** [comment]
I agree that the wiki should point to the new one and we keep the reference to the old one from the new wiki until the migration finished.

**Comment by antonialarese** [comment]
ok, links on the web page have been updated. 
I'll close the issue.
