### ISSUE TITLE
How to retrieve PK stress in structural applications ?

### ISSUE THREAD

**Issue by azzeddinetiba** [KratosMultiphysics/Kratos#11300]
**Description**
In StructuralMechanicsApplication, what is the notation for the Piola Kirchoff stress ?
On the json file I used : 

```
    "output_processes" : {
        "vtk_output" : [{
            "python_module" : "vtk_output_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "VtkOutputProcess",
            "help"          : "This process writes postprocessing files for Paraview",
            "Parameters"    : {
                "model_part_name"                    : "Structure",
                "output_control_type"                : "step",
                "output_interval"                    : 1,
                "file_format"                        : "binary",
                "output_precision"                   : 7,
                "output_sub_model_parts"             : false,
                "output_path"                        : "vtk_output_csm",
                "save_output_files_in_folder"        : true,
                "nodal_solution_step_data_variables" : ["DISPLACEMENT", "POINT_LOAD"],
                "gauss_point_variables_in_elements" : ["PK2_STRESS_VECTOR", "GREEN_LAGRANGE_STRAIN_VECTOR"]
            }
        }]
     }
```
On the output using Paraview I only get the `GREEN_LAGRANGE_STRAIN_VECTOR` and nothing else on the elements.
Is there smth wrong with the parameters file.

The material file has 
```
{
    "properties" : [{
        "model_part_name" : "Structure.Parts_Solid_Structure",
        "properties_id"   : 2,
        "Material"        : {
            "constitutive_law" : {
                "name" : "HyperElasticPlaneStrain2DLaw"
            },
            "Variables"        : {
                "DENSITY"       : 1.225,
                "YOUNG_MODULUS" : 3500000.0,
                "POISSON_RATIO" : 0.3
            },
            "Tables"           : null
        }
    }]
}
```

PS : Is the notation used for the 2D tensors (xx, yy, xy) ? Since I get 3 components.

**Scope**
- StructuralMechanicsApplication

Thank you in advance.

**Comment by loumalouomega** [comment]
Yes, the Voight notation in 2D is XX, YY and XY

voigt notation:

- 3D case:

 STRAIN Voigt Notation:  e00 e11 e22 2*e01 2*e12 2*e02
 STRESS Voigt Notation:  s00 s11 s22   s01   s12   s02
        

- 2D plane strain/axisymmetric case (4 stress components)

 STRAIN Voigt Notation:  e00 e11 e22 2*e01 
 STRESS Voigt Notation:  s00 s11 s22   s01   

- 2D plane stress/strain

 STRAIN Voigt Notation:  e00 e11 2*e01 
 STRESS Voigt Notation:  s00 s11   s01

**Comment by loumalouomega** [comment]
What element are you using, some implementations may lack for some variables

**Comment by azzeddinetiba** [comment]
I'm using the `TotalLagrangianElement2D4N`

**Comment by loumalouomega** [comment]
> I'm using the `TotalLagrangianElement2D4N`

Should work..., maybe the VTK setting is not correct...

**Comment by loumalouomega** [comment]
> > I'm using the `TotalLagrangianElement2D4N`
> 
> Should work..., maybe the VTK setting is not correct...

Use `gauss_point_variables_extrapolated_to_nodes` instead of `gauss_point_variables_in_elements`

**Comment by azzeddinetiba** [comment]
Yes, Sorry, my bad, I was using `PK2_STRESS_TENSOR` instead of `PK2_STRESS_VECTOR` . It works even with `gauss_point_variables_in_elements`
Thank you.
Is there a variable for the first Piola Kirchoff stress as well ?

**Comment by loumalouomega** [comment]
> `PK2_STRESS_VECTOR`

I am not sure if PK1 is the same as KIRCHHOFF_STRESS_VECTOR

**Comment by AlejandroCornejo** [comment]
> > `PK2_STRESS_VECTOR`
> 
> I am not sure if PK1 is the same as KIRCHHOFF_STRESS_VECTOR

Nope, they are not the same. PK1 is not symmetrical (half based on the ref and curr conf) and Kirchhoff (full curr config) yes AFAIK

see https://en.wikipedia.org/wiki/Alternative_stress_measures

**Comment by azzeddinetiba** [comment]
And it can't be retrieved since it's a tensor and not a vector (like `PK2_STRESS_TENSOR` ?)

**Comment by AlejandroCornejo** [comment]
Thatit is true. However when retrieving the vector is doing the conversion as it was symm.
