### ISSUE TITLE
Are there any structural analysis elements for quadratic shells?

### ISSUE THREAD

**Issue by hrntsm** [KratosMultiphysics/Kratos#11302]
**Description**

For Solid I found that there are quadratic elements like "SmallDisplacementElement3D10N", but I could not find any shells. ( e.g. elements like "ShellThickElement3D6N").
Is there any implementation for shells?

**Scope**

- StructuralMechanicsApplication

**Comment by loumalouomega** [comment]
No, sorry, only lineal triangles and bilinear quadrilaterals.

**Comment by hrntsm** [comment]
Okay, thanks!
I use bead optimization a lot and it would be helpful to improve the accuracy of the shell.
