### ISSUE TITLE
Room Acoustics

### ISSUE THREAD

**Issue by eman-mag** [KratosMultiphysics/Kratos#11344]
Hello,

I would like to carry out room acoustic simulations for a room with detailed geometries.

I am currently using another software but it has very long delays, therefore, I was wondering if I could use Kratos for this instead.

I tried looking for examples of this using Kratos online, however, I wasn’t able to find any. If anyone has had experience would this I would appreciate any tips!

**Comment by rubenzorrilla** [comment]
Dear @eman-mag,

There is no application implementing acoustics in the master branch of Kratos and, up to my knowledge, the same happens with the forks.

Nonetheless, if you give us more details, we could be able to provide you with some hints about the stuff that would be required to be implemented.
