### ISSUE TITLE
Order of the dofs in the Vector variables extracted through GetSolutionStepValuesVector ?

### ISSUE THREAD

**Issue by azzeddinetiba** [KratosMultiphysics/Kratos#11379]
**Description**
What is the order retrieved when using [GetSolutionStepValuesVector](https://github.com/KratosMultiphysics/Kratos/blob/27b19811283f8687edeafa52da89689331c06c63/kratos/utilities/variable_utils.cpp#L461)
If we use, say, `KM.VariableUtils().GetSolutionStepValuesVector(modelpart.Nodes, KM.DISPLACEMENT, 0, 2)`
is it `[displ_node_0_x, displ_node_1_x, ... displ_node_N_x, displ_node_0_y, displ_node_1_y ....]` or `[displ_node_0_x, displ_node_0_y, displ_node_1_x, displ_node_1_y, ...displ_node_N_y]`

**Scope**
- KratosMultiphysics
- Python

Thank you in advance !

**Comment by matekelemen** [comment]
It's the latter (`[displ_node_0_x, displ_node_0_y, displ_node_1_x, displ_node_1_y, ...displ_node_N_y]`).
https://github.com/KratosMultiphysics/Kratos/blob/8ea2cde5d6f6ca56f4e17b7a525492d34c0026d1/kratos/utilities/variable_utils.cpp#L468-L476

**Comment by azzeddinetiba** [comment]
Yes, Should've looken closer at the code. Thank you !
