### ISSUE TITLE
Is `ShellThinElement3D4N` supported?

### ISSUE THREAD

**Issue by hrntsm** [KratosMultiphysics/Kratos#11375]
**Description**
I tried to use ShellThinElement3D4N and got an error with the chanting. Is it not supported?
> RuntimeError: Error: Element ShellThinElement3D4N is not registered in Kratos. Please check the spelling of the element name and see if the application which containing it, is registered correctly.

sample model 
[model.zip](https://github.com/KratosMultiphysics/Kratos/files/12011444/model.zip)

**Scope**

- StructuralMechanicsApplication

**Comment by loumalouomega** [comment]
I will check ASAP

**Comment by philbucher** [comment]
It is not, but I dont remember the reasons (they are valid though)
you need to use the corotational one

**Comment by loumalouomega** [comment]
> It is not, but I dont remember the reasons (they are valid though) you need to use the corotational one

(I remember something something about locking, but maybe is not that)

In that case I don't check anything.

**Comment by hrntsm** [comment]
I checked and ShellThickElement3D4N worked. But ShellThickElement3D3N did not work.
Is there also some reason for this?

**Comment by hrntsm** [comment]
I have also checked the working of corotational's 3D4N. Thank you.

**Comment by philbucher** [comment]
> Is there also some reason for this?

yes, but this was many years ago so I dont remember
@peterjwilson worked during his MT on this, and he tried to make it work, but it was not possible back then

Feel free to investigate, but I am pretty sure this will be quite some effort

**Comment by hrntsm** [comment]
Thanks for the answer.
I'll investigate it when I actually need it.
