### ISSUE TITLE
How to Access to IS_ACTIVE and elemental flags in general from python

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#1143]
Good afternoon,

Currently I'm trying to access to the IS_ACTIVE elemental flag from python but I don't know the way it's meant to be accessed.

Additionally, I've noticed that we can access/modify nodal flags with the SetValue/GetValue procedure but in the case of elemental flags we are forced to use the GetValuesOnIntegrationPoints (always from python)? If it is the case, how do we impose a certain value of that flag from python?

Thank you,

Alejandro

@maceligueta @RiccardoRossi @josep-m-carbonell

**Comment by loumalouomega** [comment]
`IS_ACTIVE` is not a flag, it is a boolean variable, `ACTIVE` is the flag. For the flag (recommended):

~~~py
node.Set(KratosMultiphysics.ACTIVE, False)
active = node.Is(KratosMultiphysics.ACTIVE)
~~~

With variable, assuming is non historical:

~~~py
node.SetValue(KratosMultiphysics.ACTIVE, False)
active = node.GetValue(KratosMultiphysics.ACTIVE)
~~~

**Comment by AlejandroCornejo** [comment]
Thanks!! I close the issue now
