### ISSUE TITLE
When to use dvms vs vms ?

### ISSUE THREAD

**Issue by azzeddinetiba** [KratosMultiphysics/Kratos#11434]
Hello again,

Is there a rule of thumb to when to use the `dvms`element Vs when to use the `vms`element ?
I can't find any documentation on that.

For  a cylinder flow in Re = ~300 with a mildly fine mesh (like the one below), which one do you recommend, since I noticed there's a big difference in the computation time.
<img width="734" alt="image" src="https://github.com/KratosMultiphysics/Kratos/assets/61483012/a7efc3b9-93db-4f2d-a235-70fc335848cc">

**Scope**
- FluidDynamicsApplication

Thank you in advance !

**Comment by rubenzorrilla** [comment]
If you want to consider the dynamic component of the subscales you must select the  `dvms` element. The default `qvms` follows the quasi-static approach, which neglects these terms.

**Comment by azzeddinetiba** [comment]
Thank you
