### ISSUE TITLE
Setting the change in stress after yield

### ISSUE THREAD

**Issue by hrntsm** [KratosMultiphysics/Kratos#11445]
**Description**

I would like to take into account the increase in stress after yielding, how should I set this up?
I was able to get it to yield at the target VonMises stress with "SmalStrainIsotropicPlasticity3DVonMisesVonMises" in the [page](https://kratosmultiphysics.github.io/Kratos/pages/Applications/Structural_Mechanics_Application/General/KratosStructuralMechanicsAPI-Constitutive-laws-in-Structural-Mechanics-Application.html#how-to-use-it), but could not figure out how to set the stress change after that.
For example, is it possible to include a table of post-yield stresses and plastic strains to set up a polyline?

I am attaching the file used in the analysis for your reference, I am using v9.3.0 installed with pip.
[model.zip](https://github.com/KratosMultiphysics/Kratos/files/12227399/model.zip)

**Scope**

- ConstitutiveLawsApplication

**Comment by AlejandroCornejo** [comment]
Hi, yes you can actually set a list of points in terms of strain/stress to be followed by the plasticity CL.

see in here:

~~~json
{
    "properties" : [{
        "model_part_name" : "Structure.Parts_Solid_Solid_Auto1",
        "properties_id"   : 1,
        "Material"        : {
            "constitutive_law" : {
                    "name" : "SmallStrainIsotropicPlasticity3DVonMisesTresca"
                },
                    "Variables"        : {
                    "DENSITY"       : 7850.0,
                    "YOUNG_MODULUS" : 201.0e9,
                    "POISSON_RATIO" : 0.263,
                    "FRACTURE_ENERGY" : 120e5,
                    "YIELD_STRESS"   : 885.0e6,
                    "HARDENING_CURVE" : 6,
                    "PLASTIC_STRAIN_VECTOR_PLASTICITY_POINT_CURVE" : [0.00E+00, 5.00E-04, 1.00E-03, 1.50E-03, 2.00E-03, 2.50E-03, 3.00E-03, 3.50E-03, 4.00E-03, 4.50E-03, 5.00E-03],
                    "EQUIVALENT_STRESS_VECTOR_PLASTICITY_POINT_CURVE" : [8.85E+08, 9.55E+08, 9.75E+08, 9.85E+08, 9.90E+08, 9.85E+08, 9.80E+08, 9.60E+08, 9.40E+08, 9.20E+08, 8.90E+08],
                    "HIGH_CYCLE_FATIGUE_COEFFICIENTS"    :  [0.418079096, 1.575, 0.6, 0.000226800, 5.58800, -0.00031840, 0.002]
                },
            "Tables"           : {}
        }
    }]
}
~~~

**Comment by AlejandroCornejo** [comment]
or use `TOTAL_STRAIN_VECTOR_PLASTICITY_POINT_CURVE` to input the total strain

**Comment by hrntsm** [comment]
Thanks @AlejandroCornejo for your answer along with the sample.
I did not understand how "FRACTURE_ENERGY" affects the yield load (or after yielding).
Could you please tell me this as well?

**Comment by AlejandroCornejo** [comment]
During the plastic region defined by points the fracture energy it does not affect. However, when the defined by points region ends, an exponential softening is automatically assumed according to the remaining energy available

**Comment by hrntsm** [comment]
I understand. Thank you very much for your quick response!
