### ISSUE TITLE
[GeoMechanicsApplication] Support CIMNE in creating CurvedBeamElement2D3N

### ISSUE THREAD

**Issue by indigocoral** [KratosMultiphysics/Kratos#11466]
#11054

**Comment by aronnoordam** [comment]
I think the CurvedBeamElement2D3N element is already there. However I think it is meant for small strain analysis. For large strain analysis like in #11054 , I think the corotational formulation is to be used ( like in GeoCrBeamElement2D2N)

**Comment by mcgicjn2** [comment]
Thanks Aron, so it could be a bit of a naming issue. We will look into it. But in essence we want all structural elements to be where possible in structural mechanics. I will leave open so it can be dealt with early next year in our soil structural interaction. @aronnoordam which do you need for moving forward with STEM ?

**Comment by rfaasse** [comment]
Closing this, as #12412 is merged to master
