### ISSUE TITLE
Issue with 3D CFD Benchmark (Turek)

### ISSUE THREAD

**Issue by fdifrison** [KratosMultiphysics/Kratos#1148]
Dear All,

I'm trying to replicate the Turek Benchmark on the 3d cylinder (the same available on the Gid For Kratos Problemtype). 
I always get the same error when i try to solve it (even with an empty box without cylinder inside).
What am I doing wrong?

Thanks for your help

![image](https://user-images.githubusercontent.com/33176611/33890694-421c6c9a-df54-11e7-9179-d8784c31c83f.png)

**Comment by rubenzorrilla** [comment]
Dear @fdifrison ,

I think that we solved this error in the past, I think it was related to a bug in the ProjectParameters.json writting (@jginternational correct me if I'm wrong).
- Which version of the interface and Kratos are you using? 
- Have you tried to update your master branches?
- Which GiD version are you using?
- Is the 2D version working?

**Comment by fdifrison** [comment]
Dear @rubenzorrilla 

The Kratos version is 5.1.0-8e739e6
The Gid version is 13.1.9d
I'm trying right now to update the master beanches

**Comment by fdifrison** [comment]
The Test-case works, also I modify it. But if I try to built a new one from scratch , I get the error shown in the screen above.

p.s. I have Re-downloaded Gid-For-Kratos (is it this what you mean by update master branches right? @rubenzorrilla ) and nothing changed.

**Comment by jginternational** [comment]
Hi @fdifrison Could you attach a zip containing your example?

**Comment by fdifrison** [comment]
Hi @jginternational , here we go

[Turek_prova.gid.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/1552136/Turek_prova.gid.tar.gz)

**Comment by jginternational** [comment]
![image](https://user-images.githubusercontent.com/5918085/33893418-a4cd1a04-df5b-11e7-90de-c6b2d28efc09.png)

@fdifrison  I've seen this little error. Inlet//Total and Outlet have the same surface.
try to set the inlet inbounds in a face, and the outlet in the opposite

**Comment by fdifrison** [comment]
@jginternational yep sorry, the last try I did I inverted inlet and outlet.. but forgot the total. Btw  I fixed it and it doesn't seems to be the problem. The same error remain.

**Comment by jginternational** [comment]
I've fixed it by deleting the Inlet group, and assigning again the surface 3 to the Inlet condition
[Turek_prova.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/1555387/Turek_prova.gid.zip)

**Comment by fdifrison** [comment]
@jginternational thanks , it works for me too. Do you have any idea what is the source of the error? Something I made or just a little bug in GiD for Kratos?

Thanks again for your help

**Comment by jginternational** [comment]
GiD team is improving things in the groups management. I hope it to be the problem :pray:

**Comment by mpentek** [comment]
@fdifrison Just a note: I think you have either the Kratos 5.2.0 (in case it is the one from the GiD website) or even a newer one if you are using the problem type from the developer version. The numbering "The Kratos version is 5.1.0-8e739e6" I think is displayed erroneously in the console/output window. Correct me if I am wrong.

**Comment by jginternational** [comment]
thanks @mpentek  -> @roigcarlo is informed

**Comment by roigcarlo** [comment]
I think all problems here are solved. Closing ( reopen if i missed something)
