### ISSUE TITLE
[Wiki] Kratos for Dummies: Stationary Heat Transfer

### ISSUE THREAD

**Issue by jeyci94** [KratosMultiphysics/Kratos#11520]
**Description**
After the initial steps of creating the application with its basic components I proceed to the [_Editing the main files of the application and creating elements and conditions_](https://github.com/KratosMultiphysics/Kratos/wiki/Kratos-For-Dummies:-Stationary-heat-transfer#editing-the-main-files-of-the-application-and-creating-elements-and-conditions) section (1 to 3) but I come across errors during the compilation after editing the files as per tutorials.
Inside the _Check_ function for both element and condition I get the following messages:
1. _"<.cpp file>: In member function 'virtual int Kratos::MyLaplacianElement::Check(const Kratos::ProcessInfo&) const':
**error**: '**KRATOS_CHECK_VARIABLE_KEY**' was not declared in this scope; did you mean '**KRATOS_CREATE_VARIABLE**'?
|     **KRATOS_CHECK_VARIABLE_KEY**(TEMPERATURE)
|     ^~~~~~~~~~~~~~~~~~~~~~~~~
|     **KRATOS_CREATE_VARIABLE**"_
2. _"<.cpp file>: **error**: '**number_of_points**' was not declared in this scope
|     for (unsigned int i = 0; i < **number_of_points**; i++)"_

(1) makes sense since when looking into _includes/checks.h_ there is no `#define KRATOS_CHECK_VARIABLE_KEY `
(2) can be avoided if the KRATOS_CHECK_VARIABLE_KEY lines are removed.
For `my_laplacian_application.cpp` I get the following error:

3. _"/my_laplacian_application.cpp: In constructor 'Kratos::KratosMyLaplacianApplication::KratosMyLaplacianApplication()':
/my_laplacian_application.cpp:33:77: **error: 'Kratos::Node'** is not a template
mMyLaplacianElement(0,Element::GeometryType::Pointer(new Triangle2D3<**Node**<3>>(Element::GeometryType::PointsArrayType(3)))),
/my_laplacian_application.cpp:34:77: **error: 'Kratos::Node'** is not a template
mPointSourceCondition(0,Element::GeometryType::Pointer(new Point2D<**Node**<3>>(Element::GeometryType::PointsArrayType (1))))"_

For (3) I suppose there's a template definition missing possibly in _geometries/point_2d.h_ since the error appears for both Triangle2D3 and Point2D and I suppose the triangle geometry needs the point geometry.

How could I fix these errors? Was `KRATOS_CHECK_VARIABLE_KEY` substituted by another CHECK definition or is there another directive that should be used?
As for the template error, is it an error in the tutorial script, was the template changed or is there an include/template missing?

Thank you very much!

**Scope**
- Wiki
- MyLaplacianApplication

**Comment by loumalouomega** [comment]
> KRATOS_CHECK_VARIABLE_KEY doesn't exist anymore because now variables are unique and therefore is not required, I will update wiki

Also now node is templateless

**Comment by loumalouomega** [comment]
Should be Okay now

**Comment by jeyci94** [comment]
Yes it works now, I was able to compile the application.
A small comment, the KRATOS_CHECK_VARIABLE_KEY lines are still present in the Check function of the [Conditions Tutorial](https://github.com/KratosMultiphysics/Kratos/wiki/Tutorial:-Creating-the-Conditions).
I see also that In the wiki for the `my_laplacian_application.h` file you updated the previous #define directive with the current `#pragma once`.
If I see notice any other line or comment that differs from the actual files should I also comment it here under this issue or somewhere else?

Other than that everything seems to be working now. Many thanks!

**Comment by loumalouomega** [comment]
> Yes it works now, I was able to compile the application. A small comment, the KRATOS_CHECK_VARIABLE_KEY lines are still present in the Check function of the [Conditions Tutorial](https://github.com/KratosMultiphysics/Kratos/wiki/Tutorial:-Creating-the-Conditions). I see also that In the wiki for the `my_laplacian_application.h` file you updated the previous #define directive with the current `#pragma once`. If I see notice any other line or comment that differs from the actual files should I also comment it here under this issue or somewhere else?
> 
> Other than that everything seems to be working now. Many thanks!

Fixed, fell free to close this issue
