### ISSUE TITLE
[GeoMechanicsApplication] Extend Kratos tables with the names of X and Y

### ISSUE THREAD

**Issue by avdg81** [KratosMultiphysics/Kratos#11531]
To support non-uniform line loads, we intend to add the ability to attach a table to a line load. The table then describes the relationship between a coordinate (e.g. X) and the magnitude of the line load. So far, tables have been used to describe time-dependent behavior and the implementation of the table component process implicitly assumes that. To support different kinds of dependencies, we need to know what relationship is described by a table. Although this information is present in the `mdpa` file, it is discarded by the reader. The goal of this task is to store the names of X and Y with the table.

**Comment by rubenzorrilla** [comment]
Just adding that we should consider X,Y and Z.
