### ISSUE TITLE
Problems compiling Kratos

### ISSUE THREAD

**Issue by ghost** [KratosMultiphysics/Kratos#11563]
**Description**
Compiling kratos by running the .\configure.bat . Getting errors:
I've also attached my configure.bat file as a txt file

Windows 11 (64 bit)
Python 3.10.0
VS code 17 2022
Boost 1.83.0
CMake 3.27.4

**Scope**
Which areas of Kratos are involved
E.g.
- Compilation

Here is the terminal when I try to run the compilation:

`PS D:\kratos\Kratos\scripts> .\configure.bat
Could Not Find D:\kratos\Kratos\build\Release\cmake_install.cmake
Could Not Find D:\kratos\Kratos\build\Release\CMakeCache.txt

D:\kratos\Kratos\scripts>cmake -G"Visual Studio 17 2022" -H"D:\kratos\Kratos\scripts\.." -B"D:\kratos\Kratos\scripts\../build\Release"          -DUSE_EIGEN_MKL=OFF                                                                                 -DCMAKE_CXX_FLAGS="  "                                                  -DKRATOS_GENERATE_PYTHON_STUBS=ON
CMake Warning (dev) at CMakeLists.txt:1 (project):
  cmake_minimum_required() should be called prior to this top-level project()
  call.  Please see the cmake-commands(7) manual for usage documentation of
  both commands.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- The C compiler identification is MSVC 19.37.32824.0
-- The CXX compiler identification is MSVC 19.37.32824.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- No KRATOS_SOURCE_DIR is defined, using: D:/kratos/Kratos
-- No KRATOS_BINARY_DIR is defined, using: D:/kratos/Kratos/build/Release
-- No INSTALL_RUNKRATOS is defined, setting to ON
-- No KRATOS_INSTALL_PYTHON_USING_LINKS is defined, setting to OFF
-- No CMAKE_INSTALL_MESSAGE is defined. Setting to NEVER
-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.37.1.windows.1")
-- CMAKE_SYSTEM_NAME = Windows
-- CMAKE_CXX_COMPILER_ID = MSVC
-- CMAKE_CXX_FLAGS =
-- CMAKE_C_FLAGS = /DWIN32 /D_WINDOWS /W3
Detected compiler as MSVC
CMake Deprecation Warning at cmake_modules/pybind11Tools.cmake:8 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  CMakeLists.txt:296 (include)

CMake Warning (dev) at cmake_modules/FindPythonLibsNew.cmake:60 (find_package):
  Policy CMP0148 is not set: The FindPythonInterp and FindPythonLibs modules
  are removed.  Run "cmake --help-policy CMP0148" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.

Call Stack (most recent call first):
  cmake_modules/pybind11Tools.cmake:16 (find_package)
  CMakeLists.txt:296 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found PythonInterp: C:\Users\ajmal\AppData\Local\Programs\Python\Python310\py.exe
CMake Error at cmake_modules/FindPythonLibsNew.cmake:110 (message):
  Python config failure:

Call Stack (most recent call first):
  cmake_modules/pybind11Tools.cmake:16 (find_package)
  CMakeLists.txt:296 (include)

-- Configuring incomplete, errors occurred!

D:\kratos\Kratos\scripts>rem Build

D:\kratos\Kratos\scripts>cmake --build "D:\kratos\Kratos\scripts\../build/Release" --target install -- /property:configuration=Release /p:Platform=x64
MSBuild version 17.7.2+d6990bcfa for .NET Framework
MSBUILD : error MSB1009: Project file does not exist.
Switch: install.vcxproj

D:\kratos\Kratos\scripts>goto:eof`

[configure.txt](https://github.com/KratosMultiphysics/Kratos/files/12608023/configure.txt)

**Comment by roigcarlo** [comment]
Hi @develpGit 

The problem is with the python executable, as cmake is not able to find it. Could you double check that the route is correct?. The executable is usally called "python.exe" in windows, not "py.exe".

You can always find the correct rout by running this:

```python
import sys
sys.executable
```

**Comment by develpGit** [comment]
Hi @roigcarlo 

It worked, I mistakenly kept py.exe instead of python.exe (Such a major oversight)

Thanks a lot.
