### ISSUE TITLE
[GeoMechanicsApplication] SonarQube/SonarCloud is investigated as a method for getting the code coverage

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#11589]
As a developer, I want to investigate using SonarQube as a code coverage measure, so I can get a quick overview of which parts of the code are covered.

#### Acceptance Criteria
* The possibility of using SonarQube code coverage functionality in our code base is investigated.
* The outcome is shared with the team
* Depending on the outcome and necessity, follow-up items are created for implementing code coverage for GeoMechanics. 

**Note:** This issue depends on implementing at least one GTest unit test in the GeoMechanics suite, see #11590

**Comment by joelvdberg** [comment]
Pull request with report document can be found here: https://github.com/Deltares/FEA-Tools/pull/79
