### ISSUE TITLE
[GeoMechanicsApplication] Investigate the use of GTest in GeoMechanics

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#11590]
As a developer, I want to be able to use GTest in my code base, such that I can use all GTest functionality for unit testing

#### Acceptance criteria
* The process of adding a Unit Test using GTest in the GeoMechanics suite is understood
* Knowledge is shared to the team
* The 'GeoMechanics' specific steps are documented and put on the wiki page.

**Note:** There should be communication with the CIMNE team, who are looking into implementing GTest for the KratosMultiPhysics suite in general

**Comment by roigcarlo** [comment]
Hi, we are still having an ongoing effort to makes this done:

- The main PR accepting GTest as our testing solution is: #11506 

Several issues were detected which were covered in:

- #11553 Removing dependencies between testing and core code.
- #11526 Split of `CHECK` vs `ASSERT` macros
- #11511 Fixing kernel destructor (currently not merged as splinting this change into a separate PR will break some tests, will be merged in the final PR)

Currently we are implementing the changes necessary so the MPI tests run. specifically there are two leftover task:
- [ ] Remove the message logging in processes that are not the master.
- [ ] Create a fixture / macro to capture and propagate errors from individual processes to the whole comm, and react only in the master.

**Comment by rfaasse** [comment]
Hi Carlos,

Thanks a lot for reaching out and thanks for the info! We are not planning to pick this issue up on the short term (we added it as a reminder that we need to look into it when GTest will become available), but it's very helpful for us to know what is the current status, so feel free to keep us updated on the progress!

FYI @avdg81 @WPK4FEM @indigocoral

**Comment by rfaasse** [comment]
Closing this issue, as gtest is already added for Kratos as a whole (no separate issue needed)

FYI @mcgicjn2 @avdg81
