### ISSUE TITLE
[GeoMechanicsApplication] Add an abstract interface for incrementing time and a concrete adaptive time incrementor

### ISSUE THREAD

**Issue by avdg81** [KratosMultiphysics/Kratos#11619]
As a developer, I would like to have an abstract interface for incrementing time that can be used by other components. Furthermore, I would like to have a concrete implementation of the currently used adaptive time incrementing scheme.

#### Background

This issue aims to provide a general interface for incrementing time, that will be used by a time loop executor. This interface shall be abstract. In addition, we aim to provide a concrete implementation that mimics the current implementation of adaptive time incrementing.

#### Acceptance Criteria

**Given** a time reduction factor that is not in the range <0, 1]
**When** the developer attempts to construct an adaptive time incrementor
**Then** its constructor must throw an exception.

**Given** a time increase factor that is not greater than or equal to 1.0
**When** the developer attempts to construct an adaptive time incrementor
**Then** its constructor must throw an exception.

**Given** a maximum number of iterations that equals 0
**When** the developer attempts to construct an adaptive time incrementor
**Then** its constructor must throw an exception.

**Given** a minimum number of iterations that is not in the range [0, maximum_num_of_iterations>
**When** the developer attempts to construct an adaptive time incrementor
**Then** its constructor must throw an exception.

**Given** a maximum number of cycles that equals 0
**When** the developer attempts to construct an adaptive time incrementor
**Then** its constructor must throw an exception.

**Given** a start increment size that is non-positive (i.e. in the range <,0])
**When** the developer attempts to construct an adaptive time incrementor
**Then** its constructor must throw an exception.

**Given** an adaptive time incrementor
**When** the developer queries whether a next step should be carried out (by calling member function `WantNextStep(...)` and the end time has not been attained yet
**Then** the query must return true.

**Given** an adaptive time incrementor
**When** the developer queries whether a next step should be carried out (by calling member function `WantNextStep(...)` and the end time has been exceeded
**Then** the query must return false.

**Given** an adaptive time incrementor
**When** the developer queries whether a next step should be carried out (by calling member function `WantNextStep(...)` and we are exactly at the end time
**Then** the query must return false.

**Given** an adaptive time incrementor
**When** the developer queries whether the step should be retried (by calling member function `WantRetryStep(...)` and the cycle number equals zero (i.e. no attempt has been made yet)
**Then** the query must return true.

**Given** an adaptive time incrementor and a previous step state that indicates convergence has not been achieved yet
**When** the developer queries whether the step should be retried (by calling member function `WantRetryStep(...)` and there is room for at least one more cycle
**Then** the query must return true.

**Given** an adaptive time incrementor and a previous step state that indicates convergence has not been achieved yet
**When** the developer queries whether the step should be retried (by calling member function `WantRetryStep(...)` and there are no more cycles left
**Then** the query must return false.

**Given** an adaptive time incrementor and a previous step state that indicates convergence has been achieved
**When** the developer queries whether the step should be retried (by calling member function `WantRetryStep(...)`
**Then** the query must return false.

**Given** an adaptive time incrementor with a start increment that does not result in exceeding the end time
**When** the developer queries the time increment to be adopted (by calling member function `GetIncrement(...)`
**Then** the query must return the start increment.

**Given** an adaptive time incrementor with a start increment that does result in exceeding the end time
**When** the developer queries the time increment to be adopted (by calling member function `GetIncrement(...)`
**Then** the query must return the increment such that we exactly attain the end time.

**Given** an adaptive time incrementor with a start increment and a previous step state that indicates that it did not converge
**When** the developer queries the time increment to be adopted (by calling member function `GetIncrement(...)`
**Then** the query must return a reduced increment corresponding to the given reduction factor.

**Given** an adaptive time incrementor with a start increment and N failed cycles (i.e. no convergence was found)
**When** the developer queries the time increment to be adopted (by calling member function `GetIncrement(...)`
**Then** the query must return an increment that has been reduced N times by the given reduction factor.

**Given** an adaptive time incrementor with a start increment and a converged step state that required the maximum number of iterations
**When** the developer queries the time increment to be adopted (by calling member function `GetIncrement(...)`
**Then** the query must return an increment that has been reduced by the given reduction factor.

**Given** an adaptive time incrementor and a converged step state that required less than the minimum number of iterations
**When** the developer queries the time increment to be adopted (by calling member function `GetIncrement(...)` and the "distance" to the end time is larger than last increment size multiplied by the increase factor
**Then** the query must return an increment that has been increased by the given increase factor.

**Given** an adaptive time incrementor and a converged step state that required less than the minimum number of iterations
**When** the developer queries the time increment to be adopted (by calling member function `GetIncrement(...)` and the "distance" to the end time is less than the last increment size multiplied by the increase factor
**Then** the query must return an increment that results in attaining the end time.

**Comment by rfaasse** [comment]
@avdg81 @WPK4FEM This issue feels very complete, I just had two questions, which depending on the implementation might/might not be relevant:
1. Is it possible to set the max number of cycles after the min? In that case we should check that range as well (I don't know if it's needed to add this to the AC thought)
2. Could the AC with the 'two failed cycles' be generalized to 'N failed cycles'?
