### ISSUE TITLE
[GeoMechanicsApplication] Initialize the solving strategy for the Settlement Workflow based on project parameters

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#11626]
As a user, I would like to be able to specify a solving strategy in the Settlement workflow, such that it is used to solve the equations during settlement computations.

#### Background
The following solving strategy is supported in the settlement workflow:
1. GeoMechanicsNewtonRaphsonStrategy

The following convergence criteria are supported in the settlement workflow:
1. DisplacementCriteria

The following linear solvers are supported in the settlement workflow:

1. amgcl
2. amgcl_ns
3. bicgstab
4. cg
5. deflated_cg
6. monotonicity_preserving
7. scaling
8. skyline_lu_factorization
9. sparse_cg
10. sparse_lu
11. sparse_qr
12. tfqmr

The following schemes are supported in the settlement workflow:
1. Backward_Euler with a Quasi-Static solution type.

The following 'BuilderAndSolvers' are supported in the settlement workflow:
1. ResidualBasedBlockBuilderAndSolver
2. ResidualBasedEliminationBuilderAndSolver

#### Acceptance Criteria
**Given** The user specifies a supported (see Background) solving strategy in the ProjectParameters.json
**When** The user runs the settlement workflow
**Then** The specified solving strategy and its parameters are available for use

**Given** The user specifies a non-supported (see Background) solving strategy in the ProjectParameters.json
**When** The user runs the settlement workflow
**Then** The workflow aborts with the error message: "The solving strategy <name> is not supported for the settlement workflow."

**Given** The user does not specify a solving strategy in the ProjectParameters.json
**When** The user runs the settlement workflow
**Then** The workflow aborts with the error message: "Please specify a solving strategy as it is mandatory to run the settlement workflow."

**Comment by rfaasse** [comment]
@avdg81 @WPK4FEM I elaborated this issue a bit. To me it is clear enough to start with, but we'll need to know which solving strategies we support at some point.

Feel free to add/change things here if I missed anything

**Comment by philbucher** [comment]
hey @KratosMultiphysics/geomechanics , the first page of issues is filled with TODO-tasks for Geomechanics. Perhaps a better workflow would be to create a correspnding [project](https://github.com/KratosMultiphysics/Kratos/projects?query=is%3Aopen) for TODOs, otherwise the issues page seems to be overflowing :sweat_smile:

**Comment by mcgicjn2** [comment]
@philbucher: To be fair there [project board](https://github.com/KratosMultiphysics/Kratos/projects/36) ..... we don't manually put them on the main board. I think it is automatic @roigcarlo is this by design ?
