### ISSUE TITLE
[GeoMechanicsApplication] Add a class for running a time loop

### ISSUE THREAD

**Issue by avdg81** [KratosMultiphysics/Kratos#11620]
As a developer, I would like to be able to run a full time loop given a solver strategy and a time incrementor.

#### Background

The Kratos team at Deltares would like to be able to carry out a time loop in custom workflows. Being able to execute a time loop is one of those components. The time loop itself must be independent of the selected solver strategy and time incrementor. In that way, we can create various compositions that satisfy our requirements of the workflow.

#### Acceptance criteria

**Given** a time loop executor, a time incrementor that generates four constant time increments, a solver strategy that always converges, and no start state
**When** the developer requests to run the time loop (by calling member function `TimeLoopExecutor::Run(...)`)
**Then** it must return a list of five step states (start state + four increments in time), each one indicating that it converged.

**Given** a time loop executor, a time incrementor that generates four constant time increments, a solver strategy that always converges, and a start state
**When** the developer requests to run the time loop (by calling member function `TimeLoopExecutor::Run(...)`)
**Then** it must return a list of four step states (one for each increment in time), each one indicating that it converged.

**Comment by rfaasse** [comment]
@avdg81 @WPK4FEM It's very clear what this issue should result in, thanks for taking the time to split it all out. Similarly to the other issue #11617, I think the acceptance criteria should be generalized. 

Next to that I think it would be nice to define here what would happen if the solver strategy doesn't converge (either immediately or after some steps).
