### ISSUE TITLE
json "parameter" = null

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#1162]
When custom and default settings have a parameter that is null, the validation fails. 

custom_settings =  KratosMultiphysics.Parameters("""
        {            
              "parameter" = null
        }
        """)

default_settings = KratosMultiphysics.Parameters("""
        {            
             "parameter" = null
        }
        """)

custom_settings.ValidateAndAssignDefaults(default_settings)  -> says parameter does not have the same type.

I think something is missing in the treatment of null parameters.

**Comment by loumalouomega** [comment]
I think you can use null just for doubles, let me check

**Comment by josep-m-carbonell** [comment]
The purpose of null is to say that the parameter is not supplied. If you supply a double

custom_settings = KratosMultiphysics.Parameters("""
{
"parameter" = 1.0
}
""")

custom_settings.ValidateAndAssignDefaults(default_settings) -> says parameter does not have the same type.

It also fails. Which is not a desired behavior.

**Comment by loumalouomega** [comment]
OK, so it is for a default value, maybe some improvements are necessary in the Parameters

**Comment by jcotela** [comment]
Is this the same issue as in #911?

**Comment by RiccardoRossi** [comment]
can u add the failing test in the test_parameters.py ? (marking it as skip, i'll remove the skip when i look into it)

Riccardo

**Comment by josep-m-carbonell** [comment]
Thank you @RiccardoRossi  I have added two tests in test_kratos_parameters.  See **feature-null-parameter** branch

Like @jcotela  mentioned the problem is the one previously commented also in #911

**Comment by RiccardoRossi** [comment]
solved
