### ISSUE TITLE
Can we install KratosMultiphysics with pip but with no parallelism ?

### ISSUE THREAD

**Issue by azzeddinetiba** [KratosMultiphysics/Kratos#11638]
**Description**
If we build from source, we can choose  `-DKRATOS_SHARED_MEMORY_PARALLELIZATION="None" `
But if we install using pip, it seems that we can't do serial computation.  Is there a workaround ?

Thank you in advance !

**Scope**
- Pip Installation

**Comment by AlejandroCornejo** [comment]
you can write this in your CMD prior to calculation:

`set OMP_NUM_THREADS=1` in Windows and

`export OMP_NUM_THREADS=1` in linux and it should work

**Comment by azzeddinetiba** [comment]
Thank you !
