### ISSUE TITLE
json assign defaults in sub_settings

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#1163]
When custom and default settings have sub_settings they are not updated: 

custom_settings =  KratosMultiphysics.Parameters("""
        {            
              "sub_settings" : {
                    "parameter_a" : 1.0
               }
        }
        """)

default_settings = KratosMultiphysics.Parameters("""
        {            
              "sub_settings" : {
                    "parameter_a" : 2.0,
                    "parameter_b" : 2.0
               }             
        }
        """)

custom_settings.ValidateAndAssignDefaults(default_settings)  

The sub_settings are not validated and defaults are not assigned, custom_settings remain the same
        {            
              "sub_settings" : {
                    "parameter_a" : 1.0
               }
        }

Is it the desired behaviour?

**Comment by loumalouomega** [comment]
Try to use the `RecursivelyValidateAndAssignDefaults`

**Comment by josep-m-carbonell** [comment]
Thank you @loumalouomega , it works
