### ISSUE TITLE
[GeoMechanicsApplication] Create simple utility to copy only a subset of entries from one 'Parameters' to another

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#11631]
As a developer, I want to be able to extract certain parameter entries and copy them to a new parameter, such that I can use constructors that only expect certain entries for their parameters.

**Background**
When creating the solving strategy factory, passing on all the 'solver strategy' entries from a parameter does not work, since the constructor of the GeoMechanicsNewtonRaphsonStrategy only expects a subset and crashes if there are more entries than there are default values for these parameters, therefore it crashes with the following error message:
Error: The item with name "block_builder" is present in this Parameters but NOT in the default values

Therefore, a new parameter object should be created which only contains the entries in the defaults for this constructor. The best way (since this is used in multiple other places) is to write a small utility for this.

#### Acceptance Criteria
**Given** A developer passes a 'Parameters' object and a list of entries that should be copied 
**When** the copy function is called
**Then** a new 'Parameters' object is returned that only contains entries that are in the specified list

**Given** A developer passes a 'Parameters' object and a list of entries that should be copied 
**When** the copy function is called and one of the entries in the specified list is not available in the original 'Parameters' object
**Then** this entry is ignored and not added to the new 'Parameters' object

**Comment by rfaasse** [comment]
@avdg81 This is the parameter copy utility issue we discussed. Feel free to add.

**Comment by loumalouomega** [comment]
You can use this: https://github.com/KratosMultiphysics/Kratos/blob/63cbe348a0e4819cd8d457ff662185e4ef5cac9f/kratos/sources/kratos_parameters.cpp#L1159

In any case it only fails if you use a Validate method, you may want only to assign defaults

**Comment by rfaasse** [comment]
Thanks for pointing at this function, @loumalouomega ! The only issue is that we need the function not to throw an error when an entry is not defined in the 'OriginParameters'. However, upon checking for other existing possibilities within the parameters class, we found that we can just use the RemoveValue function for the values we want to remove. 

So indeed this issue is redundant, thanks for pointing this out and saving us some time!
