### ISSUE TITLE
[GeoMechanicsApplication] Validate "updated_mesh" parameter

### ISSUE THREAD

**Issue by indigocoral** [KratosMultiphysics/Kratos#11642]
Related issue: [#11643](https://github.com/KratosMultiphysics/Kratos/issues/11643)

Validate "updated_mesh" parameter for NEN-Bjerrum soil model and investigate the effect of it on strains.
Possibly the term is "move_mesh_flag" in the project parameters.

After getting more information from Raymond van der Meij:
The Plaxis jargon updated_mesh refers to geometrical nonlinear implementation of elements. In Kratos GeoMechanics the UpdatedLagrangian elements are available for that. 
The move_mesh_flag in ProjectParameters.jsonhas something to do with what we need here, According to a communication from Vahid to Jonathan and Carlos it should be used together with USE_HENCKY_STRAIN in MaterialParameters.json. Both should be false or both should be true.

**Comment by WPK4FEM** [comment]
[Updated_mesh_objective_vs_non-objective_Plaxis.docx](https://github.com/KratosMultiphysics/Kratos/files/12925214/Updated_mesh_objective_vs_non-objective_Plaxis.docx)
[1D Formulation soils 2.docx](https://github.com/KratosMultiphysics/Kratos/files/12925213/1D.Formulation.soils.2.docx)
