### ISSUE TITLE
Interpolation Issue: Zero Norm Normal Error at Interface Nodes

### ISSUE THREAD

**Issue by SADPR** [KratosMultiphysics/Kratos#11663]
@loumalouomega I'm encountering an issue during the interpolation of the velocity field from one model part to another with a slightly different mesh size. Here's a snapshot of the error I'm getting:

vbnet
Copy code
RuntimeError: Error: The following errors occurred in a parallel region!
```bash
Thread #4 caught exception: Error: ERROR:: ZERO NORM NORMAL IN NODE: 164801

in applications/MeshingApplication/custom_processes/nodal_values_interpolation_process.cpp:365: auto NodalValuesInterpolationProcess<3>::ComputeNormalSkin(ModelPart &)::(anonymous class)::operator()(NodalValuesInterpolationProcess::NodeType &) const [TDim = 3]
(Note: I'm getting this error in all threads.)
```

The interpolation is being done using the following code:

```cpp
NodalValuesInterpolationProcess<3> interpolation(rOriginModelPart, rDestinationModelPart);
interpolation.Execute();
```

Could you provide some insights or hints on where the problem might be originating from? The error seems to suggest an issue with computing the normal at certain nodes. For additional context, the nodes involved lay on a surface that divides two volumes. Any guidance would be greatly appreciated. Thank you!

**Comment by SADPR** [comment]
Duplicated surface.

**Comment by loumalouomega** [comment]
Faster than my e-mail check speed.
