### ISSUE TITLE
An error occurred when compiling Configuration scripts under Windows

### ISSUE THREAD

**Issue by shifangmingliangjun** [KratosMultiphysics/Kratos#11681]
I encountered an error while compiling configure.bat on Windows. I am using Visual Studio 2019 and have installed Cmake 3.26 and Boost 1_ 83_ My goal is to use the PFEM module. May I know how to solve this problem? Thank you. The attachment contains the errors that I encountered while compiling with Cmd.                                                                                           

kratos_version.cpp
F:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(351,51): er
ror C2065: “uintptr_t”: 未声明的标识符 [F:\Kratos\Kratos\build\Release\kratos\KratosVersion.vcxproj]
F:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(351,61): er
ror C2146: 语法错误: 缺少“)”(在标识符“_StackCookie”的前面) [F:\Kratos\Kratos\build\Release\kratos\KratosVersion.vcxproj]
F:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(352,67): er
ror C2065: “uintptr_t”: 未声明的标识符 [F:\Kratos\Kratos\build\Release\kratos\KratosVersion.vcxproj]
F:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(352,77): er
ror C2146: 语法错误: 缺少“)”(在标识符“_StackCookie”的前面) [F:\Kratos\Kratos\build\Release\kratos\KratosVersion.vcxproj]
F:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(356,18): er
ror C2146: 语法错误: 缺少“;”(在标识符“__security_cookie”的前面) [F:\Kratos\Kratos\build\Release\kratos\KratosVersion.vcxproj]
F:\msys64\mingw64\include\corecrt.h(75,53): error C2378: “uintptr_t”: 重定义；符号不能由 typedef 重载 [F:\Kratos\Kratos\build\Rele
ase\kratos\KratosVersion.vcxproj]
F:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\vcruntime.h(356): messa
ge : 参见“uintptr_t”的声明 [F:\Kratos\Kratos\build\Release\kratos\KratosVersion.vcxproj]
F:\msys64\mingw64\include\stdio.h(184,64): error C2144: 语法错误:“int”的前面应有“;” [F:\Kratos\Kratos\build\Release\kratos\Krato
sVersion.vcxproj]
F:\msys64\mingw64\include\stdio.h(187,69): error C2144: 语法错误:“int”的前面应有“;” [F:\Kratos\Kratos\build\Release\kratos\Krato
sVersion.vcxproj]
F:\msys64\mingw64\include\stdio.h(190,87): error C2144: 语法错误:“int”的前面应有“;” [F:\Kratos\Kratos\build\Release\kratos\Krato
sVersion.vcxproj]
F:\msys64\mingw64\include\stdio.h(193,92): error C2144: 语法错误:“int”的前面应有“;” [F:\Kratos\Kratos\build\Release\kratos\Krato
sVersion.vcxproj]
F:\msys64\mingw64\include\stdio.h(196,87): error C2144: 语法错误:“int”的前面应有“;” [F:\Kratos\Kratos\build\Release\kratos\Krato
sVersion.vcxproj]
F:\msys64\mingw64\include\stdio.h(199,92): error C2144: 语法错误:“int”的前面应有“;” [F:\Kratos\Kratos\build\Release\kratos\Krato
sVersion.vcxproj]
F:\msys64\mingw64\include\stdio.h(202,88): error C2144: 语法错误:“int”的前面应有“;” [F:\Kratos\Kratos\build\Release\kratos\Krato
sVersion.vcxproj]
F:\msys64\mingw64\include\stdio.h(205,93): error C2144: 语法错误:“int”的前面应有“;” [F:\Kratos\Kratos\build\Release\kratos\Krato
sVersion.vcxproj]
F:\msys64\mingw64\include\stdio.h(219,61): error C2144: 语法错误:“int”的前面应有“;” [F:\Kratos\Kratos\build\Release\kratos\Krato
[erro.txt](https://github.com/KratosMultiphysics/Kratos/files/12894438/erro.txt)

**Comment by roigcarlo** [comment]
Hi @shifangmingliangjun,

There seems to be something wrong in the generator, can you attach your configure.bat file?

**Comment by shifangmingliangjun** [comment]
Of course, thank you for your assistance.

[configure.zip](https://github.com/KratosMultiphysics/Kratos/files/12922598/configure.zip)

**Comment by roigcarlo** [comment]
Hi, i see nothing wrong, so it must be caused by something else. 

Could you try to add `-DFORCE_LOCAL_ZLIB_COMPILATION=ON ^` to the cmake command? like this:

```
rem Configure
@echo on
cmake -G"Visual Studio 16 2019"  -A x64 -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%"          ^
-DUSE_EIGEN_MKL=OFF                                                                                 ^
-DCMAKE_CXX_FLAGS=" %KRATOS_PARALLEL_BUILD_FLAG% "                                                  ^
-DFORCE_LOCAL_ZLIB_COMPILATION=ON ^
-DKRATOS_GENERATE_PYTHON_STUBS=ON
```

Remove the build folder and try again.
Also, if you have the chance, please remove mingw from the system, it does not interact well with Kratos in windows

**Comment by shifangmingliangjun** [comment]
hello, roigcarlo

Following your tips, I have successfully compiled Kratos, thank you for your assistance. MinGW does have issues interacting with Katos.

**Comment by roigcarlo** [comment]
Glad to help, don't hesitate to contact us for any other issue.
