### ISSUE TITLE
Please test thin shell element 3D4N

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#117]
Hi Vicente,

as announced on Thursday I added a new branch called add-new-thin-shell-element-3D4N with this new element. Could you please test this element and tell me if there are any problems with it. From my opinion the bending formulation should be correct, but there might be some problems with the membrane part.

If necessary I can send you an example.

Thank you in advance.

Ciao

Andreas

**Comment by msandre** [comment]
@AndreasWinterstein if you have a test case in mind with reference/analytical data, I can help set up the test.

**Comment by loumalouomega** [comment]
@AndreasWinterstein  I wiil take a look after I finish what I am doing right now

**Comment by loumalouomega** [comment]
@msandre here some typical benchmarks for shells: https://hub.hku.hk/bitstream/10722/54269/2/92945.pdf?accept=1

**Comment by msandre** [comment]
I don't see the branch.

**Comment by loumalouomega** [comment]
Indeed, yo need to push after commit, otherwise will be just a local repository

**Comment by AndreasWinterstein** [comment]
Sorry. My mistake. Now it is there.

**Comment by loumalouomega** [comment]
Ok, thanks, I will test the element, but just one thing, you mixed in this branch things from the ALE application and the new shell element, can you split the branch in two?, the corresponding to the ALE and the corresponding to the new shell element

**Comment by AndreasWinterstein** [comment]
I can do that. Please especially check unstructured meshes. As far as I see there is a problem.

**Comment by loumalouomega** [comment]
I already did a small commit, I am doing the tests right now

**Comment by loumalouomega** [comment]
I added some tests, I will after our meeting a patch test for the membrane effect

**Comment by loumalouomega** [comment]
@AndreasWinterstein Remember to do a pull to download my commits before create a new branch

**Comment by loumalouomega** [comment]
I added a tension test, anyway I will check with a non regular mesh as you ask me

**Comment by loumalouomega** [comment]
@AndreasWinterstein Effectively the membrane is not working properly for non regular meshes:

What I get:
![](https://i.imgur.com/fYjbwZn.png) 

What I am supposed to get:
![](https://i.imgur.com/ZlmDDW0.png)

I attach you the problem that I am trying to solve:
https://www.dropbox.com/sh/qfceg472x2u8th3/AAB7W1hgkkBlyNGZ7VNH-T-ya?dl=0

**Comment by AndreasWinterstein** [comment]
I will close this issue and I will open a new one as soon I have tested the element myself. @loumalouomega thank you for your help.
