### ISSUE TITLE
Wiki sidebar

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#1177]
The wiki sidebar is only working from the wiki home page.
@loumalouomega  It seems that the short path is not working correclty

**Comment by loumalouomega** [comment]
One sec then

**Comment by loumalouomega** [comment]
Try now

**Comment by miguelmaso** [comment]
It is still not working
I added before the full path to the kratos-for-dummies page to make a test
Actually, the links fails when jumping from a page from another, when the origin or destination is not the home page
The full path solves this problem

**Comment by loumalouomega** [comment]
Full path restored
