### ISSUE TITLE
2D axisymmetric FEA / longitudinal cross section of a pipe

### ISSUE THREAD

**Issue by megaprimatus** [KratosMultiphysics/Kratos#11770]
Hi
I didn't find any example of the 2D axisymmetric analysis in Kratos docs. Is there a capability to do this simulation described below on the image? The pipe cross section is under internal pressure simultaneously under tension force.

![2d_axisymmetric](https://github.com/KratosMultiphysics/Kratos/assets/48415379/1cdc37c2-589a-48aa-b42f-d7d614cb8516)

**Comment by AlejandroCornejo** [comment]
Hi,

We do have axysimmetric elements in Kratos. Tha main condition is that the x coordinate of the solid must be >= 0.0.

Element: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_elements/axisym_small_displacement.cpp

**Comment by rubenzorrilla** [comment]
Adding to @AlejandroCornejo 's comment that the corresponding axisymmetric loads are also implemented. Maybe we should add an example to the examples repo.

**Comment by megaprimatus** [comment]
@AlejandroCornejo thanks for quick reply, do you have a python version as well?

**Comment by AlejandroCornejo** [comment]
Here you have a using case:
[axy.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/13297245/axy.gid.zip)

**Comment by megaprimatus** [comment]
Thank you very much for input file, I will definitely test it out

**Comment by megaprimatus** [comment]
Hi @AlejandroCornejo, I tried to run your archive you shared above and got this error message:

> `The item with name "use_old_stiffness_in_first_iteration" is present in this Parameters but NOT in the default values`

here is a complete output from running command: **kratos MainKratos.py**
[err.txt](https://github.com/KratosMultiphysics/Kratos/files/13307467/err.txt)

**Comment by AlejandroCornejo** [comment]
As far as I can see in the error message, seems that your Kratos version is really old (Kratos 7.0 and now we are 9.4). Can you upgrade it?
