### ISSUE TITLE
[StructuralMechanicsApplication] Question regarding cr_beam_element_linear_2D2N

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#11817]
In which way is the cr_beam_element_linear_2D2N linear? As I see that displacements are still incorporated for the calculation of the stiffness matrix?

**Comment by AlejandroCornejo** [comment]
Hi, Can you elaborate a bit your question? Can you also point to us which file are you checking? Thank you

**Comment by aronnoordam** [comment]
In the structural mechanics application, there is an element "CrBeamElementLinear2D2N" in cr_beam_element_linear_2D2N.cpp. 
As linear is in the name, I expected a linear set of equations and convergence after 1 iteration. However, this quick convergence didnt happen. So after inspecting, I saw that the stifnness matrix of the CrBeamElementLinear2D2N element is not linear, as it depends on the deformations in the current iteration. 

So my question is: since the stiffness matrix is not linear, what is meant by "linear" from the name:  "cr_beam_element_linear_2D2N "

**Comment by clazaro** [comment]
Hi,
cr_beam_element_linear_2D2N is a co-rotational element with linear behavior at the element level. The fact that it is co-rotational explains the dependence you mention. If I am not wrong, it was formulated according to Chapter 5 in this reference:
Krenk S. Non-linear Modeling and Analysis of Solids and Structures. Cambridge Univ. Press, 2009

**Comment by aronnoordam** [comment]
okay thank you
