### ISSUE TITLE
Does slip conditions work for quadratic elements?

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/Kratos#11859]
**Description**
I am running a 3D cylinder with an inlet at the bottom, an outlet at the top and slip conditions at the walls. My mesh consists of 27-noded hexahedra with 9-noded quadrilateral elements in the boundaries. The error comes when the slip process computes the unit normal of the conditions, throwing the following error:

```
Giving precedence to elements and writing only elements!
terminate called after throwing an instance of 'Kratos::Exception'
terminate called recursively
  what():  Error: ERROR: The normal norm is zero or almost zero. Norm. normal: 0

in kratos/geometries/geometry.h:1645: array_1d<double, 3> Geometry<TPointType>::UnitNormal(const CoordinatesArrayType&) const [with TPointType = Node; CoordinatesArrayType = array_1d<double, 3>]

Abortado (`core' generado)
```

Do you know if the `UnitNormal` of the `geometry.h` is general enough or it has only been tested for linear elements?

**Scope**
- KratosCore

**Comment by rubenzorrilla** [comment]
Frankly speaking, I've never tried...

**Comment by loumalouomega** [comment]
A priori the algorithm is general, but maybe it depends on things not defined, let me check.

**Comment by loumalouomega** [comment]
I just chekced and a priori there is a test for the normal of the Quad3D9, so it should work

**Comment by loumalouomega** [comment]
Can you provide the geometry failing?

**Comment by loumalouomega** [comment]
> Can you provide the geometry failing?

In fact can you provide the whole thing, because unitNormal is computed ina  set of local coordinates, maybe your input is on global coordinates.

**Comment by jgonzalezusua** [comment]
> Can you provide the geometry failing?

Do you mean the .mdpa? The problem is that quadratic conditions are not defined in `master` branch for the `FluidDynamicsApplication`, so I do not think you are not able to run it.

**Comment by loumalouomega** [comment]
> > Can you provide the geometry failing?
> 
> Do you mean the .mdpa? The problem is that quadratic conditions are not defined in `master` branch for the `FluidDynamicsApplication`, so I do not think you are not able to run it.

The error is in geometry.h, meaning that fails in a specific geometry. Can you provide the geometry points and input to check that it is a bug or something?

**Comment by jgonzalezusua** [comment]
> As @loumalouomega is saying, from the code it looks like UnitNormal should be working for Quadrilateral3D9. I would suggest trying to find out which is the condition that is generating this error in your problem to see if there is something strange going on (is the geometry degenerate? Is it aligned in a particular way?)

Ok, I will provide the output. Referring to the geometry, it is not degenerate as I am using a structured mesh in the wall.

**Comment by loumalouomega** [comment]
> > As @loumalouomega is saying, from the code it looks like UnitNormal should be working for Quadrilateral3D9. I would suggest trying to find out which is the condition that is generating this error in your problem to see if there is something strange going on (is the geometry degenerate? Is it aligned in a particular way?)
> 
> Ok, I will provide the output. Referring to the geometry, it is not degenerate as I am using a structured mesh in the wall.
> 

Maybe not well defined (order of nodes in Kratos may be the issue)

**Comment by rubenzorrilla** [comment]
It could also be the utility we are using for the calculation of the normal (`NormalCalculationUtils`). We should confirm that we are passing through the correct function (and not the simplified ones for the simplex).

**Comment by loumalouomega** [comment]
> It could also be the utility we are using for the calculation of the normal (`NormalCalculationUtils`). We should confirm that we are passing through the correct function (and not the simplified ones for the simplex).

The error shown is from geometry.h itself, not the normal utilities. The normal compute the simplex only for triangles a priori.

**Comment by jgonzalezusua** [comment]
Ok, I have found the error and there is nothing to do with the geometry. I registered the condition as it was 2 dimensional quadrilateral instead of 3d. Sorry for the inconvenience.

**Comment by rubenzorrilla** [comment]
OK. Closing then.
