### ISSUE TITLE
Potential problem with not storing "Pointers" to submodelparts

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1185]
This is a comment for @pooyan-dadvand and @jcotela  

I am thinking on how to add automatic registration of ModelParts into the model, (we'll speak together, since this is a more complicated issue). For now, my point is that I think we have a potential problem with the use of submodelparts and existing functions from the python interface.

The thing is as follows: to my understanding the model_part python interface assumes using Pointer has handler from the python side.

this allows exporting to python functions that accept either references or Pointers to the modelpart, say something of the type

      f(ModelPart& rModelPart) { ... }
      g(ModelPart::Pointer pModelPart) { ... }

now let's imagine that we do something like the following

     mp = ModelPart("main")
     sub = mp.CreateNewSubmodelPart("sub") //here sub is a reference
     g(sub) // ----> in order for this to work the python interface creates a smart_ptr to sub...

My problem is that in order to have "g(sub)" to work, the python interface silently creates a Pointer, which is obviously bad at the moment of destruction.

Having said this i just checked and ModelPart::Pointer is used very seldom through the python interface, mostly by @jcotela. I believe that we should avoid that OR use ModelPart::Pointer anywhere.

**Comment by pooyan-dadvand** [comment]
This is a serious problem and thank @RiccardoRossi for pointing it out! I should use shared pointer to store sub modelparts instead of raw pointers.

**Comment by pooyan-dadvand** [comment]
Now I have checked the interface and it `GetSubModelPart` returns an internal reference to python so python would bind it's existence to parent modelpart. So I think is not really a bug. Meanwhile I have discovered that AddSubModelPart method accepts a reference so if someone passes a submodelpart of other parent to this one both of them would delete it. 

Now the question is Do we need this feature? 

@KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
If we need it we have two options:
1. given an error if the other is a submodelpart
2. remove the submodelpart from its old parent.

**Comment by maceligueta** [comment]
I would say option 1 is better. The error would be clear and reasonable, while option 2 would modify old parent silently o with just a warning (not so clear).

**Comment by RiccardoRossi** [comment]
+1 for option 1.

however i still think that if you have a function

     f(ModelPart::Pointer pmp)

and you call it from python with a submodelpart, it will create a new pointer with bad consequences

**Comment by pooyan-dadvand** [comment]
OK, So I would go for option 1.

About the bug, I'm not sure about @RiccardoRossi comment but I would change the shared_ptr one to leave no doubt. Are you agree?

**Comment by maceligueta** [comment]
OK to me.

**Comment by pooyan-dadvand** [comment]
Checking more the `AddSubModelPart` method I see that it make a copy of the original one. So now I'm not sure if I should send any error. At the moment I leave it as is until we agree that we have to change this behaviour
