### ISSUE TITLE
How can we use the Mooney Rivlin law in 3D ?

### ISSUE THREAD

**Issue by azzeddinetiba** [KratosMultiphysics/Kratos#11888]
**Description**
How can we use the Mooney Rivlin law (or other laws in ConstitutiveModelsApplication) in 3D ?

If I use 
`"name"   : "KratosMultiphysics.ConstitutiveModelsApplication.LargeStrain3DLaw.IsochoricOgdenModel" ` like [here](https://github.com/KratosMultiphysics/Kratos/blob/16159ee87196bcefc5ca05b24a285e46b271ebcd/applications/ConstitutiveModelsApplication/tests/validation/isochoric_ogden_materials.json#L12) I get an error `RuntimeError: Error: Kratos components missing "IsochoricOgdenModel"`

PS : `ConstitutiveModelsApplication` and `ConstitutiveLawsApplication` are compiled.

**Scope**
- ConstitutiveModelsApplication

**Comment by AlejandroCornejo** [comment]
hi @azzeddinetiba , I am the main developer of the ConstitutiveLawsApp and currently we do not have the Ogden CL. We have the Kirchhoff, NeoHookean laws. It's in my TODO list.

The ConstitutiveModelsApp is not currently maintained in the master branch.

I hope this clarifies you a bit. What is the use case that are you interested in?

**Comment by azzeddinetiba** [comment]
Hi @AlejandroCornejo , thank your for replying.
I'm trying to model a flexible tube with an incompressible material law from [this paper](https://doi.org/10.1016/S0021-9290(99)00201-8).
$W = \alpha (I_B -3) + \beta (I_B - 3)²$ where $I_B = tr (F F^T) $
Are there incompressible NeoHookean models available ?

**Comment by AlejandroCornejo** [comment]
Yes I implemented a quasi incompressible Neo Hookean CL. It has to be used together with a U/P mixed element. Here you have a use case:
[calculos.zip](https://github.com/KratosMultiphysics/Kratos/files/13661344/calculos.zip)

**Comment by rubenzorrilla** [comment]
Just adding that in case you need to use another specific CL there is the option of using the strain-driven elements rather than the U/P one.

**Comment by azzeddinetiba** [comment]
@rubenzorrilla I'm not sure I understand your point, do you mean INSTEAD of the `MixedElement` for the `HyperElasticIsotropicQuasiIncompressibleIshochoricNeoHookean3D`, or it's to be used only for other CLs ?

**Comment by rubenzorrilla** [comment]
More or less. My point is that the `MixedElement` @AlejandroCornejo is pointing to only works with the `HyperElasticIsotropicQuasiIncompressibleIshochoricNeoHookean3D` so if you need to use any other CL it won't be compatible with the `MixedElement` so you'd need to switch to any of the mixed strain-driven elements, which are compatible with any CL.

**Comment by AlejandroCornejo** [comment]
Can we close this?

**Comment by azzeddinetiba** [comment]
Hi again @rubenzorrilla , I had a question about the volumetric strain elements. If I understood correctly, the volumetric part of the constitutive law is handled the same way whatever the constitutive law is (e.g `HyperElastic3D` or `KirchhoffSaintVenant3DLaw`) and that part depends on the bulk modulus $\kappa$. Why isn't this modulus computed from the material parameters ($E$ and $\mu$) ? which should go to infinity in the incompressible limit. 
[Here it's computed from the constitutive matrix](https://github.com/KratosMultiphysics/Kratos/blob/81dc1d4cac43dabf4fdd624b5225b0e5c0a4c7f4/applications/StructuralMechanicsApplication/custom_elements/total_lagrangian_mixed_volumetric_strain_element.cpp#L54), is there a reference/paper with more explanations for this part ? 
Thank you in advance !

**Comment by rubenzorrilla** [comment]
> Hi again @rubenzorrilla , I had a question about the volumetric strain elements. If I understood correctly, the volumetric part of the constitutive law is handled the same way whatever the constitutive law is (e.g `HyperElastic3D` or `KirchhoffSaintVenant3DLaw`) and that part depends on the bulk modulus κ. Why isn't this modulus computed from the material parameters (E and μ) ? which should go to infinity in the incompressible limit. [Here it's computed from the constitutive matrix](https://github.com/KratosMultiphysics/Kratos/blob/81dc1d4cac43dabf4fdd624b5225b0e5c0a4c7f4/applications/StructuralMechanicsApplication/custom_elements/total_lagrangian_mixed_volumetric_strain_element.cpp#L54), is there a reference/paper with more explanations for this part ? Thank you in advance !

Hi! The (equivalent) bulk modulus you are pointing to is only used for the stabilization. The volumetric part of the constitutive response is handled through the "enriched" strain ("enriched" because the volumetric part is computed node-by-node to avoid volumetric locking). You can find more details in [here](https://www.sciencedirect.com/science/article/abs/pii/S0045782523002001).

**Comment by azzeddinetiba** [comment]
> > Hi again @rubenzorrilla , I had a question about the volumetric strain elements. If I understood correctly, the volumetric part of the constitutive law is handled the same way whatever the constitutive law is (e.g `HyperElastic3D` or `KirchhoffSaintVenant3DLaw`) and that part depends on the bulk modulus κ. Why isn't this modulus computed from the material parameters (E and μ) ? which should go to infinity in the incompressible limit. [Here it's computed from the constitutive matrix](https://github.com/KratosMultiphysics/Kratos/blob/81dc1d4cac43dabf4fdd624b5225b0e5c0a4c7f4/applications/StructuralMechanicsApplication/custom_elements/total_lagrangian_mixed_volumetric_strain_element.cpp#L54), is there a reference/paper with more explanations for this part ? Thank you in advance !
> 
> Hi! The (equivalent) bulk modulus you are pointing to is only used for the stabilization. The volumetric part of the constitutive response is handled through the "enriched" strain ("enriched" because the volumetric part is computed node-by-node to avoid volumetric locking). You can find more details in [here](https://www.sciencedirect.com/science/article/abs/pii/S0045782523002001).

Thank you @rubenzorrilla !
