### ISSUE TITLE
[GeoMechanicsApplication] Compare, and adapt, the Kratos K₀ Procedure with Plaxis

### ISSUE THREAD

**Issue by mcgicjn2** [KratosMultiphysics/Kratos#11903]
It will be expected from typical users that the K<sub>0</sub> procedure will be comparable with that developed in Plaxis. From our initial investigations it appears that the K<sub>0</sub> procedure is straight forward and correctly implemented. However the development of the initial stresses differ. 

In our version the initial vertical stress field is developed using any material model that the user wishes to apply, while the procedure in Plaxis appears to use self-weight. 

Initial tests show that the use of the linear-elastic model in Kratos is not comparable. This issue will investigate and conclude

**Acceptance Criteria**
**Given** the developed K<sub>0</sub> procedure
**When** used in all circumstances
**Then** all results of the stage should be comparable to those in Plaxis

**Comment by mcgicjn2** [comment]
Having tested through comparison with our K<sub>0</sub> procedure we have found that in :
`GeoLinearElasticPlaneStrain2DLaw::CalculateElasticMatrix`

**Setting:**
```
c2 = 0;
c3 = 0;
```

Provides the best comparison with Plaxis results. See attached presentation.

To facilitate this we must create \ replace the `LinearPlaneStrainK0Law` which has the same functionality as `GeoLinearElasticPlaneStrain2DLaw` but with the above settings.

**Comment by mcgicjn2** [comment]
This is the results found using the adaptation described above.
[K0 Procedure.pptx](https://github.com/KratosMultiphysics/Kratos/files/13726199/K0.Procedure.pptx)

**Comment by rfaasse** [comment]
A class diagram of the fix:
![Image](https://github.com/KratosMultiphysics/Kratos/assets/56549273/c69279d5-8f9f-4b60-a2ff-ba4bafcf604c)

This reduces duplication and implements the proposed fix (with c2 = 0 and c3 = 0) in the CalculateElasticMatrix implementation of the classes.
