### ISSUE TITLE
[Core] Problems with LinearMasterSlaveConstraint

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#11916]
I have several grievances with the implementation of `LinearMasterSlaveConstraint`, but the most pressing ones are with how it handles setting the `SLAVE` flag.

## `SLAVE` on `Node` instead of `Dof`

As it stands right now, `LinearMasterSlaveConstraint` sets the `SLAVE` flag on the `Node` that contains the `Dof` to be constrained in one of its constructors.

https://github.com/KratosMultiphysics/Kratos/blob/81dc1d4cac43dabf4fdd624b5225b0e5c0a4c7f4/kratos/constraints/linear_master_slave_constraint.cpp#L47

This implies that **all** `Dof`s within that `Node` should be slaves, which we cannot be sure of at all since `MasterSlaveConstraint`s can operate on individual `Dof`s.

## Inconsistent `SLAVE`

Furthermore, there's only **one** constructor that sets `SLAVE`. The other one doesn't do it because it doesn't have access to the containing `Node`s at construction time.

https://github.com/KratosMultiphysics/Kratos/blob/81dc1d4cac43dabf4fdd624b5225b0e5c0a4c7f4/kratos/constraints/linear_master_slave_constraint.h#L118-L130

## Setting `SLAVE` in the constructor

Since `SLAVE` is set in the constructor, the `Node` is flagged as a slave for the rest of the analysis (unless some other process explicitly unsets it), but what if the constraint is destroyed or deactivated? The node would remain flagged a `SLAVE` even though no such constraint is imposed on it.

## Slaves with multiple masters

Even though the `SLAVE` flag is set, it is completely ignored in the rest of the constraint, even though it would provide the perfect opportunity to catch incorrect constraint definitions, in which a single slave node is assigned to multiple masters.

## Proposal

The main problem is clear: `Dof` doesn't derive from `Flags`. @KratosMultiphysics/technical-committee is this on purpose?

I strongly recommend:
1) deriving `Dof` from `FLAGS`
2) setting `SLAVE` on `Dof` instead of `Node`
3) setting `MASTER` on master `Dof`s, so that relationships are clear. This would also help us detect unsupported constraint definitions that our current approach doesn't allow (treating a `Dof` both as master and slave)
4) setting the flags on `Dof`s in `LinearMasterSlaveConstraint::Apply` instead of the constructor
5) checking for incorrect/unsupported constraint definitions using the `MASTER` and `SLAVE` flags

**Comment by loumalouomega** [comment]
Thanks @matekelemen I also didn't like this inconsistency, but I didn't have the bravery to ask for a change that may  break a lot of code. Let's see what @KratosMultiphysics/technical-committee  thinks

**Comment by sunethwarna** [comment]
I agree with @matekelemen . The next question is since the use of `Flags` is kinda exploding. Do the flags which we have will be meaningful or enough?

**Comment by ddiezrod** [comment]
We're not using any of the flags in Altair side. I think this could go in without much pain 👍

**Comment by matekelemen** [comment]
> use of Flags is kinda exploding

we already have flags defined for `MASTER` and `SLAVE` so it shouldn't be a problem.

https://github.com/KratosMultiphysics/Kratos/blob/e85ea35835a6073de4535d449e191ce225a64f1d/kratos/includes/kratos_flags.h#L70-L71

**Comment by pooyan-dadvand** [comment]
I fully agree that having the flag on the node is not good and can easily result in a problem.

Nevertheless, Dof is designed to be very lightweight, deriving it from the flag can easily making it 3x heavier. 

I would add a bit like (static constexpr int msIsMasterPosition = 62;) and reducing other fields (like the dof traits)

**Comment by matekelemen** [comment]
> Nevertheless, Dof is designed to be very lightweight, deriving it from the flag can easily making it 3x heavier.

Fine, though I don't agree with the idea that `Dof` has to be more lightweight than `Flags`.

## Compact Flags

How about this then: define a more compact version of `Flags` that is unique to `Dof`. `Dof` wouldn't derive from `Flags`, but it have a similar interface that internally translates the arguments to the more compact representation. Here's some example psudocode:

```py
class Dof:
private:
    class CompactFlags:
        FIXED = 0
        MASTER = 1
        SLAVE = 2
        ...

    def Set(self, flags: Flags) -> None:
        # Translate incoming Flags to CompactFlags and compare
        # Throw an exception if translation fails (incoming Flags defines flags that CompactFlags doesn't support)
        # Set the translated flags in the internal representation

    def Is(self, flags: Flags) -> bool:
        # Translate incoming Flags to CompactFlags and compare
        # Throw an exception if translation fails (incoming Flags defines flags that CompactFlags doesn't support)
        # Compare the translated flags with the internal representation
```

## Where to store it?

Believe it or not, we have 4 bits of free real estate in `Dof`. 

https://github.com/KratosMultiphysics/Kratos/blob/7bf35edc43614e310b5365b8254b6eb3e7761d0c/kratos/includes/dof.h#L439-L452

1 bit comes from the restricted integers. The restricted bitfields amount to a total 63 bits (1 + 4 + 4 + 6 + 48) so there's 1 extra bit we can get away with using. 1 extra bit won't solve our issues though.

However, we also have 3 unused bits in the 3 least significant bits of `mpNodalData`, because it's a pointer pointing to a `NodalData`, which has an alignment of 8 bytes (at least on every piece of hardware I own). This means that a `NodalData` pointer can only ever have a value that is a multiple of 8, which in turn means that the 3 least significat bits are never used in the pointer. So in summary, we can hide a total of 4 extra flags in `Dof` without any increase to its size.

This may seem overly complicated, but it's the only way to store extra info in `Dof` without any increase to its size. Btw this method is used all over LLVM, so its well tested and safe (though it definitely needs proper documentation). [Here](https://www.youtube.com/watch?v=vElZc6zSIXM)'s a video about it in more detail if you're interested. 

##

> I would add a bit like (static constexpr int msIsMasterPosition = 62;) and reducing other fields (like the dof traits)

I don't understand, can you please elaborate?

**Comment by RiccardoRossi** [comment]
From my point of view and after thinking into this for a while,  this change does not go in the right direction.
My biggest concern is that the same dof can be a master or a slave when considering a different set of constraints, so i don't think we can rely on storying this info on the nodes. 

If we were to design a strategy from the groun up, that would look something on the line of 

~~~cpp
    mpDofSet= ConstructDofSet(model_part) //includes calculation of constraints
    SetupSystemIds(mpDofSet) //assigns ids to be used in FEM assembly

    mpEffectiveDofSet = mpScheme->ConstructConstraintDofSet(model_part,mpDofSet) //only includes master nodes
    IndexPermutation = ConstructConstraintDofSet(mpEffectiveDofSet,mpDofSet) //this is the permutation list between the ids used in the assembly and the ones assigned to master

    Build(pA,pB)
    BuildConstraints(pT,pQ)
    pAeff,pBeff = ApplyConstraints(pA,pB,pT,pQ,mpEffectiveDofSet,mpDofSet)
    PrepareSystemSolution(pAeff, mpEffectiveDofSet) //for example we may factorize the system in here)
    while(is_converged == false){
        pDxeff = SolveSystem(pAeff,pBeff)
        pDx = T@pDxeff + pQ //reconstruct dof set
        mpScheme->Update(model_part,pDx)

        is_converged = pre_criteria...

        Build(pA,pB)
        BuildConstraints(pT,pQ)
        pAeff,pBeff = ApplyConstraints(pA,pB,pT,pQ,mpEffectiveDofSet,mpDofSet)

        is_converged = post_criteria...
    }
~~~

the critical points for this PR are the "ConstructConstraintDofSet" and the "ConstructConstraintDofSet" which are critical to the construction of the matrix "T".
This involves additional data structures (a permutation vector relating the ids used in the assembly and the ones in the reduced system)

to my understnading the Current PR attempts to avoid the construction of this permutation vector, but in doing so it loses generality

**Comment by matekelemen** [comment]
Master-slave elimination cannot deal with DoFs that are both master **and** slave at the same time.

That said, I do agree with eliminating the `MASTER` and `SLAVE` flags from nodes. In fact, I think we shouldn't assume that MFCs are imposed by the master-slave method at all.

Still, we need a place to store data related to MFCs (which DoFs are constrained, what's their coefficient, possibly in multiple constraints).
