### ISSUE TITLE
Installing Problems On Windows 10

### ISSUE THREAD

**Issue by muhammedfurkanyilmaz** [KratosMultiphysics/Kratos#11922]
I'm trying to install Kratos on Windows 10 but even configuration was done successfully runkratos.exe, python39.lib and bin folder do not appear in the C:\Users\firat\OneDrive\Desktop\KRATOS\Kratos\bin\Release folder. How can I fix it? 

Here is my configuration file.

[configure - Copy.txt](https://github.com/KratosMultiphysics/Kratos/files/13817892/configure.-.Copy.txt)

I have added the system architecture name(x64) to the configuration file and reruned it again then got the following output:
![image](https://github.com/KratosMultiphysics/Kratos/assets/80275498/7c256f1b-60e8-4174-9a5c-92b22b038b38)

Thanks

**Comment by matekelemen** [comment]
The messages you highlighted are normal; they just let you know that you didn't set some custom environment variables, so Kratos applied some defaults for you.

I'm no expert for windows builds, but I definitely know that runkratos is legacy and you shouldn't look for it. I think python39.lib (or any other python binary) in the kratos directory is also related to runkratos, so don't worry if you don't see them.

What you **should** see is a KratosMultiphysics directory (containing the python module scripts) and a libs directory (containing the python module binaries and kratos binaries). Can you plz send us what you see in the install directory?

##

The way you'd usually use Kratos these days, is as a python module. Make sure that the install directory is on your PYTHONPATH, and you should be able to import KratosMultiphysics and get started.

**Comment by muhammedfurkanyilmaz** [comment]
Thanks @matekelemen for your response. I followed an installation video on Youtube, in the above-mentioned directory those three guys showed up. 

Here is my install directory views:

![image](https://github.com/KratosMultiphysics/Kratos/assets/80275498/c93e4ada-7798-4d6f-b5a9-6bc6734190e4)

![image](https://github.com/KratosMultiphysics/Kratos/assets/80275498/ab954bac-cf1c-4948-9941-14087f6fd7ea)

**Comment by AlejandroCornejo** [comment]
Hi, those directories look fine. Which is the problem now?

**Comment by muhammedfurkanyilmaz** [comment]
Hi @AlejandroCornejo. I added the installation directory to the PYTHONPATH. Then I tried to run an example file, and at the terminal, this message was shown:
![image](https://github.com/KratosMultiphysics/Kratos/assets/80275498/3e1c1d61-5af5-458b-8f06-1e6a89741c28)

**Comment by AlejandroCornejo** [comment]
This error occurs when the environment variables are not correctly defined. Please checl that you added these 2:

set PYTHONPATH=%PYTHONPATH%;C:/Kratos/bin/Release
set PATH=%PATH%;C:/Kratos/bin/Release/libs

**Comment by muhammedfurkanyilmaz** [comment]
![image](https://github.com/KratosMultiphysics/Kratos/assets/80275498/58311278-eae8-4f1a-81b2-247099388bd1)
But still having same problem
![image](https://github.com/KratosMultiphysics/Kratos/assets/80275498/bbf74fd7-451a-4a3c-8a8b-d7c8f9f5dce0)

**Comment by AlejandroCornejo** [comment]
have you reset the CMD window?

**Comment by muhammedfurkanyilmaz** [comment]
After resetting the problem was solved. Now, everything looks normal. Thanks @AlejandroCornejo. I appreciate it.

Regards.

**Comment by matekelemen** [comment]
@muhammedfurkanyilmaz can you please copy the link to the video you mentioned? We should let viewers know that it's an old one and things have changed in the meantime.

**Comment by muhammedfurkanyilmaz** [comment]
Here

https://www.youtube.com/watch?v=zZq7ypDdudo&t=335s

**Comment by matekelemen** [comment]
Thanks!

@jginternational can you please update the description of the video or pin a comment explaining that it's legacy (because of runkratos)? Maybe you could also add a link to the relevant docs, or an up-to-date video (if there is one).
