### ISSUE TITLE
Recalculating elements of Initial Configuration

### ISSUE THREAD

**Issue by jeyci94** [KratosMultiphysics/Kratos#11952]
**Description**
I am working on an inverse problem where I need to update the coordinates of the _InitialConfiguration_ during the solution based on the displacements obtained. Then solve the system based on this updated _InitialConfiguration_.
To my understanding due to the update of the _InitialConfiguration_ instead of _CurrentConfiguration_ it would be necessary to call again calculation of element properties as i.e. area, Jacobian, etc. so that the rest of the calculations are coherent.
I assume this happens during some initialization step, however from looking into the `AnalysisStage`, `Solver`, or `Strategy` I haven't been able to find where.

If I were to recalculate the elements inside the solution loop in what layer can I find this function call? 

Some more details to my use case:
Application: _StructuralMechanicsApplication_
Elements: _MembraneElement3D3N_
Strategy: _ResidualBasedNewtonRaphsonStrategy_

**Scope**
- KratosCore
- StructuralMechanicsApplication

I hope I was able to explain myself. Thank you very much!

**Comment by loumalouomega** [comment]
Hi, this is quite standard issue in our analysis, and in fact for example @AlejandroCornejo while developing constitive laws which are formulated in reference configuration also had this very same issue. I don know if he found a solution or if he just moved the nodes, calculated, and then moved the nodes back again.

**Comment by jeyci94** [comment]
@loumalouomega regardless if there is another solution already implemented or not, if we take the approach you mention of moving nodes, calculating then moving nodes again, **which function would I need to call to recalculate the element?** 
Is this at Strategy, Builder & Solver, ModelPart or some other deeper level?

As I mentioned, my guess is this happens in some _Initialize...()_ step but since I wasn't able to find it I my next assumption is that this happens during the `GetSolver().ImportModelPart()` or` GetSolver().PrepareModelPart()` of the `AnalysisStage` in which case I don't know if it would be possible to recalculate the element's Initial Configuration later on inside the SolutionLoop once the Geometry has been imported from the mdpa.

**Comment by philbucher** [comment]
I would also be interested in the solution of @AlejandroCornejo 

Be careful with moving nodes, this needs proper locking in shared memory to avoid race conditions, i.e. generally not sth I recommend.

How does your global solution procedure look like? You dont seem to be using the standard workflow for your inverse problem. 
Potentially you could move the nodes every time before you do some call to the solver

**Comment by loumalouomega** [comment]
> I would also be interested in the solution of @AlejandroCornejo
> 
> Be careful with moving nodes, this needs proper locking in shared memory to avoid race conditions, i.e. generally not sth I recommend.
> 
> How does your global solution procedure look like? You dont seem to be using the standard workflow for your inverse problem. Potentially you could move the nodes every time before you do some call to the solver

Yes I know, that's why I think @AlejandroCornejo could help us, as i guess he already thought on this.

**Comment by loumalouomega** [comment]
> @loumalouomega regardless if there is another solution already implemented or not, if we take the approach you mention of moving nodes, calculating then moving nodes again, **which function would I need to call to recalculate the element?** Is this at Strategy, Builder & Solver, ModelPart or some other deeper level?
> 
> As I mentioned, my guess is this happens in some _Initialize...()_ step but since I wasn't able to find it I my next assumption is that this happens during the `GetSolver().ImportModelPart()` or` GetSolver().PrepareModelPart()` of the `AnalysisStage` in which case I don't know if it would be possible to recalculate the element's Initial Configuration later on inside the SolutionLoop once the Geometry has been imported from the mdpa.

That depends when do you need it. In which step?

**Comment by jeyci94** [comment]
> I would also be interested in the solution of @AlejandroCornejo
> 
> Be careful with moving nodes, this needs proper locking in shared memory to avoid race conditions, i.e. generally not sth I recommend.
> 
> How does your global solution procedure look like? You dont seem to be using the standard workflow for your inverse problem. Potentially you could move the nodes every time before you do some call to the solver

In a general sense the procedure is as follows:
- Import Geometry in 3D space from an mdpa (membrane elements)
- Set InitialConfiguration as a planar projection (i.e., flatten geometry)
- At InitializeSolutionStep set DISPLACEMENT from projection as an inital guess
- Solve system with a modified LHS & RHS to obtain a planar update as a solution
- Update InitialConfiguration with planar solution
- Solve system CurrentConfiguration until equilibrium is reached

_NOTE:_ CurrentConfiguration remains unchanged throughout whole solution

Here is a comparison from the base commit of the master branch and where I've implemented the changes for an overview.
https://github.com/KratosMultiphysics/Kratos/compare/19962ab...6051250. Changes are mainly located in the `StructuralMechanicsAnalysis` file and inverseforming solver/strategy

Implementation is located in the [inverseforming solver branch](https://github.com/KratosMultiphysics/Kratos/tree/test-inverseforming-solver) if you'd like to take a look.

**Comment by jeyci94** [comment]
> > @loumalouomega regardless if there is another solution already implemented or not, if we take the approach you mention of moving nodes, calculating then moving nodes again, **which function would I need to call to recalculate the element?** Is this at Strategy, Builder & Solver, ModelPart or some other deeper level?
> > As I mentioned, my guess is this happens in some _Initialize...()_ step but since I wasn't able to find it I my next assumption is that this happens during the `GetSolver().ImportModelPart()` or` GetSolver().PrepareModelPart()` of the `AnalysisStage` in which case I don't know if it would be possible to recalculate the element's Initial Configuration later on inside the SolutionLoop once the Geometry has been imported from the mdpa.
> 
> That depends when do you need it. In which step?

@loumalouomega I would need this during the `SolveSolutionStep()` of the `RunSolutionLoop` as I would need to update the geometry within the step while it iterates until equilibrium is found. So I think this could be either at solver or strategy level.

**Comment by rubenzorrilla** [comment]
Closing as seems to be solved. @jeyci94 feel free to reeopen if required.
