### ISSUE TITLE
Complex linear algebra in Python

### ISSUE THREAD

**Issue by oberbichler** [KratosMultiphysics/Kratos#1197]
Hi!
For the unit tests of the direct solvers I write some basic solving code:

```python
space = KratosMultiphysics.UblasSparseSpace()

settings = KratosMultiphysics.Parameters('{ "solver_type" : "' + solver_type + '" }')

solver = ConstructSolver(settings)

a = KratosMultiphysics.CompressedMatrix()
KratosMultiphysics.ReadMatrixMarketMatrix(matrix_path, a)

b_exp = KratosMultiphysics.Vector()
KratosMultiphysics.ReadMatrixMarketVector(vector_path, b_exp)

dimension = a.Size1()

x = KratosMultiphysics.Vector(dimension)

solver.Solve(a, x, b_exp)
```

Than I check the result with:

```python
b_act = KratosMultiphysics.Vector(dimension)
space.Mult(a, x, b_act)

for i in range(dimension):
    self.assertAlmostEqual(b_act[i], b_exp[i], 7)
```

Now I want to extend the test for the complex solvers. The problem is that I can not find the complex equivalents of `UblasSparseSpace`, `CompressedMatrix` and `Vector`.

Where are they defined?

**Comment by pooyan-dadvand** [comment]
I'm not sure if they are exported. Actually I realized that the sparse space is added in the strategy which is not easy to find even. A solution would be to put all of them in `add_spaces_to_python` files

**Comment by oberbichler** [comment]
👍 That would make the interface cleaner.

From a user point of view it would be perfect to expose dense/sparse matrices/vectors as numpy/scipy arrays.

**Comment by pooyan-dadvand** [comment]
I agree! and I think that current boost pythons have this support for ublas matrices.

**Comment by RiccardoRossi** [comment]
Hi Guys,

the big problem with numpy scipy interfaces is that then we would have to distribute them together with kratos. and such distribution is NOT trivial

**Comment by oberbichler** [comment]
@RiccardoRossi that would be my next question. I always designed my python modules to work together with the rest of the python ecosystem (advantage: a lot of functionality provided by other packages). But I think the design of Kratos is different. Python should only be a scripting language for Kratos (advantage: no dependencies).

So the solution would be to extend the existing interface for complex numbers.

**Comment by RiccardoRossi** [comment]
Hi @oberbichler we also need to package kratos together with all of its dependencies, for example to distribute it together with GiD.

having more dependencies on python libraries makes this very difficult

**Comment by pooyan-dadvand** [comment]
I was not aware of making this dependency in packaging. Agreed with @RiccardoRossi which complicates a lot the release!

**Comment by oberbichler** [comment]
I completely understand your point. Let's keep in mind this problem. Maybe we find some elegant solution. Meanwhile the manual exposing should do the job.
