### ISSUE TITLE
Existing Restart Processes

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1200]
Hi @KratosMultiphysics/fluid-dynamics and @KratosMultiphysics/structural-mechanics 

I will soon need restart capabilities and was looking through the code. Unfortunately the implementation is not complete in neither the in the `NavierStokesBaseSolver` nor the `MechanicalSolver`
I have some examples so I can also complete it myself, but I thought I'd ask first if there are existing, complete solutions.

Also in MPI, I have to use the `ParallelFillCommunicator` to rebuild the communication graph right?

**Comment by pooyan-dadvand** [comment]
I know that @jcotela used to make it work in fluid and @josep-m-carbonell had it working in solid mechanic. But I'm not sure about their current status.

**Comment by jcotela** [comment]
@philbucher the python solver is not typically serialized. In fluid dynamics we just serialize the model part, everything else is rebuilt (including the communication graph, as you noted), so it is just a mater of constructing a Serializer instance and using it to save/load the model part.

In some cases where I wanted to store some extra python data, it was enough for me to store it in an auxiliary variable in the model_part's ProcessInfo (which is serialized automatically).

As far as I know, there is no process to do any of this automatically (at least on the fluid side).

**Comment by pooyan-dadvand** [comment]
@philbucher do you need more info about restart? can we close this?

**Comment by RiccardoRossi** [comment]
closing for now. we'll reopen if needed
