### ISSUE TITLE
[GeomechanicsApplication] Move derivative update from quasi-static to dynamic solver

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#12005]
In the Newmark quasi static scheme within the Geomechanics application, the velocity and accelerations are updated after each time step. However, after the first time step they stay constant at a non-zero value. 

I expect no update of velocity and acceleration within quasi-static calculations (with a constand F and K), as the equation to be solved is `K.dot(u) = F` 

The wrongly updated velocities and accelerations cause problems when transfering from a quasi-static to a dynamic calculation in a multistage analysis

Note, in the backward euler scheme, the velocities and accelerations are also updated, but appear to be correct. I.e. a velocity and acceleration of 0 with constant K and F

**Comment by aronnoordam** [comment]
[inputs_kratos.zip](https://github.com/KratosMultiphysics/Kratos/files/14236878/inputs_kratos.zip)
hereby input files where I encountered the problem (2 stages), but already in the first stage it is seen that the velocity stays constant at a non-zero value

**Comment by WPK4FEM** [comment]
The current state of the time integration schemes in GeoMechanicsApplication is depicted here: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/GeoMechanicsApplication/custom_strategies/schemes/README.md
The NewmarkQuasistaticUPwScheme should not update velocity and acceleration for the displacement D.O.F., but does that using the UpdateVariablesDerivatives from GeneralizedNewmarkScheme. A possibility to correct this is to create UpdateVariablesDerivaties with specific functionality for the existing variants of the GeneralizedNewmarkScheme:
NewmarkQuasistaticPwScheme  --> only update p^dot
GeneralizedNewmarkTScheme --> only update T^dot
NewmarkQuasistaticUPwScheme --> only update p^dot
NewmarkDynamicUPwScheme --> update p^dot, v and a
NewmarkQuasistaticDampedUPsScheme --> update p^dot and v

Wijtze Pieter and Richard intend to pick this up together.
