### ISSUE TITLE
[Core] Please do not assign negative values to unsigned integers, otherwise you will have very strange memory errors

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#12017]
https://github.com/KratosMultiphysics/Kratos/blob/78f1c44e34e1fafb07e147e4465e0eb321823bce/kratos/containers/edge_based_data_structure.h#L659

@rubenzorrilla please replace with int or https://en.cppreference.com/w/cpp/types/ptrdiff_t, the equivalent signed to std::size_t.

**Comment by rubenzorrilla** [comment]
Well, I'm not sure if it turns into an error or into a cast to integer type. In any case, after checking the code I think we don't even need to initialize it to a negative value.

**Comment by philbucher** [comment]
This is also a compiler error with the intel compiler

**Comment by philbucher** [comment]
ping @rubenzorrilla
