### ISSUE TITLE
[GeoMechanicsApplication] Remove swapping edges and faces from "FindNeighbourElementsOfConditionsProcess"

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#12026]
**Description**

We have identified that certain 3D conditions in GeoMechanicsApp are not functioning correctly due to the presence of edge and face swapping. These lines were originally introduced as a workaround for a bug that has since been fixed. See issues #9818  #9422.

 However, it has come to our attention that these workarounds are now causing issues with our 3D boundary conditions.

To resolve this issue, we need to remove the edge and face swapping lines from the code. It was done for 2D conditions but as 3D conditions are never used/tested, they are left untouched. This removal should be carefully executed to ensure that the 3D boundary conditions are functioning as intended after the lines have been removed. It is crucial to thoroughly test the affected boundary conditions to confirm that they work properly.

The mesh which comes from GID, includes anticlockwise ordering of, for example, triangular face conditions. Hence, after swapping they are changed to clockwise. Therefore the GID conditions may not work and the code gives errors based on " corresponding elements to conditions are missing". 

There are 3 test cases of 3D in the integration tests in the Geomechanics application. The conditions there are ordered to be clockwise, in order to pass. After removing the swapping from the code, the conditions in the mdpa need to be modified (swap them back).
However, one of the test cases fails because it gives negative stresses (same value as before but with negative sign). The results of this test case has to be investigated, whether the change in sign is physical?

existing test cases:
test_tetra_4n.gid
test_tetra_10n.gid
test_normal_load_tetra_10n.gid

Test case "test_tetra_4n" is failing after this "code modification + swapping in its mdpa"

**Acceptance Criteria**

- The lines of code responsible for edge and face swapping have been identified and safely removed from the codebase.
- The 3D boundary conditions have been tested and confirmed to work correctly after the removal of the workaround.
- The codebase compiles and runs successfully after the removal of the edge and face swapping lines.
- Any relevant test cases related to 3D boundary conditions have been updated to reflect the code changes.

**Comment by aronnoordam** [comment]
note that its important to test adding a boundary condition on all faces of the 3D element. E.g. for a tetra3d4n => test face 2-3-1; 0-3-2; 0-1-3; 0-2-1

**Comment by aronnoordam** [comment]
> note that its important to test adding a boundary condition on all faces of the 3D element. E.g. for a tetra3d4n => test face 2-3-1; 0-3-2; 0-1-3; 0-2-1

also maybe instead of face 2-3-1, also check if the face is identified correctly when the ordering is 1-2-3 or 3-1-2
