### ISSUE TITLE
GeoMechanicsApplication Compilation issue 

### ISSUE THREAD

**Issue by Rbravo555** [KratosMultiphysics/Kratos#12063]
**Description**

After updating my local master branch, I encountered a compilation issue within the **GeoMechanicsApplication** that was not present at least two months ago.

Specifically, the compilation process reports that **VOIGT_SIZE_3D** and **VOIGT_SIZE_2D_PLANE_STRESS** are not defined.

The error message during compilation is as follows:

```shell
[ 81%] Building CXX object applications/GeoMechanicsApplication/CMakeFiles/KratosGeoMechanicsCore.dir/custom_elements/small_strain_U_Pw_diff_order_element.cpp.o
In file included from /home/jrbravo/Kratos_Master/Kratos/applications/GeoMechanicsApplication/custom_elements/geo_structural_base_element.cpp:14:
/home/jrbravo/Kratos_Master/Kratos/applications/GeoMechanicsApplication/custom_elements/geo_structural_base_element.hpp:111:56: error: ‘VOIGT_SIZE_3D’ was not declared in this scope
  111 |     static constexpr SizeType VoigtSize = (TDim == 3 ? VOIGT_SIZE_3D : VOIGT_SIZE_2D_PLANE_STRESS);
      |                                                        ^~~~~~~~~~~~~
/home/jrbravo/Kratos_Master/Kratos/applications/GeoMechanicsApplication/custom_elements/geo_structural_base_element.hpp:111:72: error: ‘VOIGT_SIZE_2D_PLANE_STRESS’ was not declared in this scope
  111 |     static constexpr SizeType VoigtSize = (TDim == 3 ? VOIGT_SIZE_3D : VOIGT_SIZE_2D_PLANE_STRESS);
      |                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/jrbravo/Kratos_Master/Kratos/applications/GeoMechanicsApplication/custom_elements/geo_curved_beam_element.hpp:19,
                 from /home/jrbravo/Kratos_Master/Kratos/applications/GeoMechanicsApplication/custom_elements/geo_curved_beam_element.cpp:14:
/home/jrbravo/Kratos_Master/Kratos/applications/GeoMechanicsApplication/custom_elements/geo_structural_base_element.hpp:111:56: error: ‘VOIGT_SIZE_3D’ was not declared in this scope
  111 |     static constexpr SizeType VoigtSize = (TDim == 3 ? VOIGT_SIZE_3D : VOIGT_SIZE_2D_PLANE_STRESS);
      |                                                        ^~~~~~~~~~~~~
/home/jrbravo/Kratos_Master/Kratos/applications/GeoMechanicsApplication/custom_elements/geo_structural_base_element.hpp:111:72: error: ‘VOIGT_SIZE_2D_PLANE_STRESS’ was not declared in this scope
  111 |     static constexpr SizeType VoigtSize = (TDim == 3 ? VOIGT_SIZE_3D : VOIGT_SIZE_2D_PLANE_STRESS);
      |                                                                        ^~~~~~~~~~~~~~~~~~~~~~~~~~
gmake[2]: *** [applications/GeoMechanicsApplication/CMakeFiles/KratosGeoMechanicsCore.dir/build.make:930: applications/GeoMechanicsApplication/CMakeFiles/KratosGeoMechanicsCore.dir/custom_elements/geo_structural_base_element.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
gmake[2]: *** [applications/GeoMechanicsApplication/CMakeFiles/KratosGeoMechanicsCore.dir/build.make:888: applications/GeoMechanicsApplication/CMakeFiles/KratosGeoMechanicsCore.dir/custom_elements/geo_curved_beam_element.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:527: applications/GeoMechanicsApplication/CMakeFiles/KratosGeoMechanicsCore.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Scope**
- Compilation

**Environment**
- OS: Ubuntu 22.04.3 LTS
- Compiler: gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- Branch: master
- Python 3.10.12

**Comment by rubenzorrilla** [comment]
Adding to @Rbravo555 's comment that we also tried to compile it in my machine with clang-17.

**Comment by roigcarlo** [comment]
Looks like a unity build related issue, an include may be missing in the `geo_structural_base_element.hpp`  @KratosMultiphysics/geomechanics.

**Comment by rfaasse** [comment]
Thank you for flagging this, I'll have a look. Does one of the pipeline builds represent the described environment (e.g. one of the unity builds)? I don't have this environment set up locally, so it would be difficult for me to test otherwise.

**Comment by rfaasse** [comment]
@rubenzorrilla @roigcarlo @Rbravo555 It seems indeed an include was missing in the header. Somehow it was included indirectly such that all the other builds are still compiling. 

It could be that our recent effort to format the elements using clang-format (which also puts includes in alphabetic order) brought this issue to light. If necessary headers are not included directly, the order of includes in different locations could have an influence on whether or not a variable is known at compile-time. 

I made a PR to include geomechanics_application_variables.h directly in the .hpp file of the file the compiler complains about, which I expect should fix the issue (feel free to already test this branch on your local machine).

**Comment by rfaasse** [comment]
Thanks all testing of the fix (see PR discussion for all confirmations), apologies for the inconvenience and of course always feel free to let us know if there happen to be any other issues related to GeoMechanicsApplication!
