### ISSUE TITLE
[GeoMechanicsApplication] Investigate extracting the equation of motion functionality from the elements

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#12068]
As a developer, I want to investigate how to separate the equation of motion functionality from the elements, such that the elements become more maintainable and configurable.

In discussions we discussed the following proposal for the equation of motion policy structure:
![Image](https://github.com/KratosMultiphysics/Kratos/assets/56549273/b7888cdc-a4df-4ec5-976c-e52f57298190)

In this investigation, the feasibility and (if possible) concrete steps to implement this structure are documented

### Acceptance criteria
- A follow-up issue is created and refined for the implementation or further investigations
- Investigation is documented

**Comment by rfaasse** [comment]
# Work in progress

The equation of motion policy should handle the top line of the following matrix equations, i.e. the displacements. There are three possible scenarios (as also described in the policy structure in the description of this issue): transient, steady state and dynamic, where different terms are taken into account:
- For steady state, only the stiffness matrix (K) is taken into account in the equations, while the other matrices (M and D) are not considered
- For transient, additional to the stiffness matrix, also the damping matrix (D) is considered
- For dynamic, also the inertia term, or the mass matrix (M) is taken into account.

![Image](https://github.com/orgs/Deltares/projects/55/assets/56549273/296486b0-9e5e-408f-9839-aef8d8c7e720)

This investigation has the goal of finding out how to implement the different possibilities (steady state, transient and dynamic) into a policy structure for the element. In summary, this investigation concludes that these different scenarios are currently **not** handled by the elements themselves, but by the different flavors of time integration schemes. Therefore, at this moment, there is no need for extraction of these policies for the elements, but we can keep this functionality in the schemes.

**Comment by WPK4FEM** [comment]
I completely support the above analysis by Richard.

**Comment by avdg81** [comment]
Very clear and well-written analysis. Thank you Richard!

**Comment by mnabideltares** [comment]
It is very nicely written, Thank you Richard.
