### ISSUE TITLE
[StructuralMechanicsApplication] Are C++ tests supposed to be deactivated?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#12083]
https://github.com/KratosMultiphysics/Kratos/blob/8fa8e65ef65a737e19652c1d7db2933f1f6efb69/applications/StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py#L514

@KratosMultiphysics/structural-mechanics

**Comment by philbucher** [comment]
Yes, bcs otherwise they are run twice in the CI

This seems to be a leftover, probably also needs to be cleaned in other apps

**Comment by loumalouomega** [comment]
In that case we should clean up in all apps, okay, noted
