### ISSUE TITLE
[GeoMechanicsApplication] Add documentation for the newly added stress state policies

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#12095]
As a developer, I want to have conceptual documentation of the stress state policies, such that I know how to use them and what their aim is.

**Acceptance Criteria**
- Markdown file is available describing the goal and usage of the newly created stress state policies

**Comment by indigocoral** [comment]
Link to the documentation:
[Policies.md](https://github.com/KratosMultiphysics/Kratos/blob/geo/12095-add-documentation-stress-state-policies/applications/GeoMechanicsApplication/custom_elements/Policies.md)

**Comment by rfaasse** [comment]
> Link to the documentation: [Policies.md](https://github.com/KratosMultiphysics/Kratos/blob/geo/12095-add-documentation-stress-state-policies/applications/GeoMechanicsApplication/custom_elements/Policies.md)

Indeed I forgot to link the branch, thanks for adding the link. I now also linked the PR to this issue 👍
