### ISSUE TITLE
FEM surface loading (time intervals are not followed)

### ISSUE THREAD

**Issue by akhilkmat** [KratosMultiphysics/Kratos#12099]
**Description**

I am trying to apply a linearly increasing load on column containing 64 3D8N nodes in the structural mechanics application, the side nodes are constrained to move only in the vertical direction ( y axis) and the bottom nodes are fixed.  The load_process_list contains a linearly increasing load that goes from a value of 0 to 250 N/m2 in 0.025 seconds, after which the load is completely released. For some reason, even after releasing the load, the last value of the load (at t = 0.025 seconds) = 250 N/m2 still remains and is reflected in the reaction from the bottom nodes. 

I saw this problem initially while trying out surface loads with DEM-FEM cosimulations, The behavior of surface loading processes is completely random such that sometimes it overrides another load - process and sometimes it doesn't. I didn't want to share the cosimulation example here and make the problem more complex hence posting a simple FEM example. 

**Scope**
-Structure Mechanics application
-Surface loading

**To Reproduce**
The example file is attached, simply run the problem, you can also use a REACTION post processor in the Analysis folder, it just needs .post and .msh file to be contained in the same folder.

**Expected behavior**
The force should increase till 0.025 seconds and then go back to zero.

**Environment**

- Branch: Volume_coupling
[FEMmesh.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/14348858/FEMmesh.gid.zip)
![base reaction](https://github.com/KratosMultiphysics/Kratos/assets/69186170/801e0327-cb31-4a8d-b07b-c0278092f635)

**Comment by rubenzorrilla** [comment]
As pointed by @philbucher, this is on purpose and detailed in #6291. As commented by @philbucher himself (see [here](https://github.com/KratosMultiphysics/Kratos/issues/6291#issuecomment-780493895)), you need to specify two processes.

Closing as it is repeated.

**Comment by akhilkmat** [comment]
> hey, in short, this is intended, since these procedures are also used for other analysis types Long explanation here: #6291

Thank you! 

Although I was trying to do the same conditions in a Cosimulation (DEM-FEM volume coupling), but it seems that the behavior is different such that the force keeps on increasing even after the time interval. I am not sure what causes this, I didn't get time properly debug this. Also, I am not sure if this is problem with the project codes that we are using or something else. I will do a proper study and update again.

Best,
Akhil


[with_surface_loading_ProjectParametersFEM.json](https://github.com/KratosMultiphysics/Kratos/files/14423030/with_surface_loading_ProjectParametersFEM.json)
![10000xt 0-0 0025](https://github.com/KratosMultiphysics/Kratos/assets/69186170/965d49f4-664f-4c1c-aaec-353cbe8c46b0)

**Comment by philbucher** [comment]
did you run only the structural problem in this case? Seems strange, the load should ramp up linearly btw 0 and 0.025. The curve is not at all what I would expect, are you maybe applying other loads too?
