### ISSUE TITLE
Volume and determinant sign error for tetrahedra_3d_4 

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#121]
I have a tetrahedron with following connectivity which seems to have correct order but the volume calculated by Kratos is negative:
```
        Point 1  : (1 , 1 , -10)
        Point 2  : (0 , 0 , 0)
        Point 3  : (0 , 10 , 0)
        Point 4  : (4 , 6 , 0)
        Center   : (1.25 , 4.25 , -2.5)

        Length   : -nan(ind)
        Area     : -66.6667
```
I have checked it in GiD and says that is positive! And also debugging I'm sure that it enters the correct method. 

Meanwhile calculating the length by volume cause another wrong information!

**Comment by pooyan-dadvand** [comment]
I should add that I could not find the error (of the tetrahedron or Volume() ) by myself so I'm asking for another eye!

**Comment by loumalouomega** [comment]
https://en.wikipedia.org/wiki/Niccol%C3%B2_Fontana_Tartaglia#Volume_of_a_tetrahedron

We can use Tartaglia formula (the equivalent to the Heron's formula for tetrahedron)

**Comment by pooyan-dadvand** [comment]
@loumalouomega your solution seems to be less efficient than the actual due to many power 2 and a square root.

Meanwhile I need to know were is the error.

**Comment by loumalouomega** [comment]
@pooyan-dadvand  Using http://www.colorado.edu/engineering/CAS/courses.d/AFEM.d/AFEM.Ch09.d/AFEM.Ch09.pdf

I get the correct volume:

![](https://i.imgur.com/wOQ5iX2.png)

**Comment by roigcarlo** [comment]
@loumalouomega You are using the absolute value of the determinant, we are not. Maybe the problem is that we assume that the sign of the determinant is the sign of the volume which is not true.

**Comment by pooyan-dadvand** [comment]
For us the sign of volume comes from the sign of determinant.

**Comment by RiccardoRossi** [comment]
What does the function in "GeometryUtils" return?

Riccardo

**Comment by roigcarlo** [comment]
Think I got the problem....

Seems to me that the matrix is transposed and shifted from the code in C++. The terms of the matrix are:

```C++
double x10 = rP1[0] - rP0[0];
double y10 = rP1[1] - rP0[1];
double z10 = rP1[2] - rP0[2];

double x20 = rP2[0] - rP0[0];
double y20 = rP2[1] - rP0[1];
double z20 = rP2[2] - rP0[2];

double x30 = rP3[0] - rP0[0];
double y30 = rP3[1] - rP0[1];
double z30 = rP3[2] - rP0[2];
```

By the calculation of the determinant `detJ = x10 * y20 * z30 ...` it means that internally the matrix is represented as:

|  |  |  |  |
| --- | --- | --- | --- |
| P1 x | P2 x | P3 x | P0 x |
| P1 y | P2 y | P3 y | P0 y |
| P1 z | P2 z | P3 z | P0 z |
| 1 | 1 | 1 | 1 |

If we use this as the template for the calculation with your example the results is: -400

If instead we: (Or we move P0 to the first row in the matrix above) 

```C++
double x10 = rP0[0] - rP3[0];
double y10 = rP1[0] - rP3[0];
double z10 = rP2[0] - rP3[0];

double x20 = rP0[1] - rP3[1];
double y20 = rP1[1] - rP3[1];
double z20 = rP2[1] - rP3[1];

double x30 = rP0[2] - rP3[2];
double y30 = rP1[2] - rP3[2];
double z30 = rP2[2] - rP3[2];
```

which is:

|  |  |  |  |
| --- | --- | --- | --- |
| P0 x | P0 y | P0 z | 1 |
| P1 x | P1 y | P1 z | 1 |
| P2 x | P2 y | P2 z | 1 |
| P3 x | P3 y | P3 z | 1 |

Then the order is correct and the det gives the correct sign for the example ( and it cause to fail to some of the current tests as they were assuming that code correct). Can someone else confirm this?

**Comment by roigcarlo** [comment]
Just corrected a mistake in the previous entry if someone was copying the code sorry

**Comment by pooyan-dadvand** [comment]
It seems that the `GeometryUtils::CalculateGeometryData` also gives a negative volume. So the error must be in Tetrahedron but I can not see it

**Comment by pooyan-dadvand** [comment]
It was closed by mistake!

**Comment by roigcarlo** [comment]
@pooyan-dadvand I've look at theGeometry::utilities and it has the exactly same code as the volume function in the tet. So whatever is the geometry or the method the problem is still the same.

**Comment by loumalouomega** [comment]
@pooyan-dadvand I created #125

**Comment by roigcarlo** [comment]
@pooyan-dadvand After speaking with @josep-m-carbonell I have to say that the issue was not exactly what I described above but by chance it solved the problem.

The problem is that we are mixing two ways of calculating things in the same function:

* If we take the determinant method, the problem is indeed that the vectors of the tetrahedron calculated do not correspond with the actual order, and the result is inverted.

* If we use the (AxB)*C formula then the error is that we are multiplying BxA instead of AxB, hance the solution in this case would be:

```C++
double detJ = x30 * y20 * z10 - x30 * y10 * z20 + y30 * z20 * x10 - y30 * z10 * x20 + z30 * x20 * y10 - z30 * x10 * y20; 
```

Which is basically what @loumalouomega has done in #125.

:+1:

**Comment by pooyan-dadvand** [comment]
Finally the problem was a nan value as quality which prevents the change of the tetrahedron and what we saw in GiD was the original correct one and not mentioned by Kratos. I have opened the issue #126 for this problem.
