### ISSUE TITLE
AreaNormal is still not consistent

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1210]
We still have an inconsistent definition of the AreaNormal function.

@loumalouomega last week correctly changed the AreaNormal function so that it gives back the area of the triangle. The problem is that if one calls the AreaNormal function on all the gauss points of a given surface geometry the sum of the norms of the AreaNormal is NOT equal to the area of the element.

I don't have a fix, we need to think on this. I am opening this issue as a reminder

**Comment by pooyan-dadvand** [comment]
But does it need to give sum as area? I mean it should not result in Ngp*Area?

**Comment by pooyan-dadvand** [comment]
One option is to do what was promised in #940. Changing back the `AreaNormal` method name to `Normal`

**Comment by jcotela** [comment]
👍 for `Normal`

**Comment by RiccardoRossi** [comment]
ok, the proposal we agreed in the @KratosMultiphysics/technical-committee  is as follows:

we define on each gauss point the result of the function "__Normal()__" as "n=CrossProduct(gxi, geta)"

where gxi and geta are the transformation of the vectors 1,0,0 and 0,1,0 from the parent space to the real space. (note that this is the same as telling that F = (gxi, geta), with gxi and geta coinciding with the first ans second column of F )
The case of 1d lines in the 2D space, is defined similarly, but F=(gxi)


this implies that the total area of the element can be obtained by doing

     area = 0.0
     loop on gauss
          area += gauss_point_weight * norm(n)

which also corresponds to telling that 
 
    norm(n) = generalized_det(F) 

if there is no counterexample to this we will push this change even if it may break some code

**Comment by RiccardoRossi** [comment]
note that if someone is still using the deprecated function Normal() this change will affect him

**Comment by loumalouomega** [comment]
UnitNormal() will still working after that, right?

**Comment by pooyan-dadvand** [comment]
It should!

**Comment by loumalouomega** [comment]
Did we solved this?, I am confused now

**Comment by pooyan-dadvand** [comment]
@loumalouomega I thought you were doing the changes!

**Comment by loumalouomega** [comment]
I don't remember, I think I fixed it long time ago

**Comment by philbucher** [comment]
@loumalouomega is this solved now?

**Comment by loumalouomega** [comment]
According to me yes

**Comment by roigcarlo** [comment]
Please Reopen if needed
