### ISSUE TITLE
[Core] Matrix Product Performance

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#12138]
## Symptoms

I noticed that moderately increasing the number of MPCs in a given system (while not changing anything else) significantly increased assembly duration, to the point that it became an order of magnitude more expensive than solving the resulting linear system.

## Traceback

1) `ResidualBasedBlockBuilderAndSolver::ApplyConstraints`
2) `SparseMatrixMultiplicationUtility::MatrixMultiplication`
3) `SparseMatrixMultiplicationUtility::MatrixMultiplicationSaad`
4) `SparseMatrixMultiplicationUtility::SortRows`

Surprisingly, `SortRows` is to blame.

## Issue

This is an issue of complexity and bad parallelization. `SortRows` loops over the rows of the sparse matrix and **naively** sorts the entries (values and column indices) within it, meaning that each row has quadratic complexity.

```cpp
template <typename TSize, typename Col, typename TIndexType, typename ValueType>
    static inline void SortRows(
        const TIndexType* CPtr,
        const TSize NRows,
        const TSize NCols,
        Col* Columns,
        ValueType* Values
        )
    {
        #pragma omp parallel
        {
            #pragma omp for
            for (int i_row=0; i_row<static_cast<int>(NRows); i_row++) {
                const TIndexType row_begin = CPtr[i_row];
                const TIndexType row_end = CPtr[i_row + 1];

                for(IndexType j = 1; j < row_end - row_begin; ++j) {
                    const IndexType i_column = Columns[j + row_begin];
                    const double value = Values[j + row_begin];

                    SignedIndexType i = j - 1;

                    while(i >= 0 && Columns[i + row_begin] > i_column) {
                        Columns[i + 1 + row_begin] = Columns[i + row_begin];
                        Values[i + 1 + row_begin] = Values[i + row_begin];
                        i--;
                    }

                    Columns[i + 1 + row_begin] = i_column;
                    Values[i + 1 + row_begin] = value;
                }
            }
        }
    }
```

As a result, the whole function has `O(number_of_rows * number_of_nonzero_columns²)` complexity that will be somewhere between quadratic and cubic complexity.  This is especially bad for MPCs that relate many masters to a single slave, as this results in a few dense rows. Since parallelization is done trivially on rows (each core gets some rows to sort) instead of parallelizing the sorting algorithm, this leads to serialization on dense rows and terrible performance.

## Discussion

As I see it, there are three possible ways of going about solving this issue:
- keep the current parallelization (rows assigned to cores) and change the sorting from naive to `std::sort`. This somewhat addresses complexity issues but will still lead to serialization if there's at least one dense row in the matrix.
- serially loop through rows and parallelize the sorting algorithm. I imagine we'd take a performance hit for usual cases (every row is sparse) but at least we'd never get serialized on dense rows.
- keep looping through rows in parallel, but also parallelize sorting dense rows. This would be the ideal solution, but it'll be tricky to implement because there are several things we need to ensure:
   - instead of directly assigning rows to cores, make sorting a row a task
   - decide whether parallelizing a row makes sense (requires some heuristics similar to what we're already doing in matrix multiplication)
   - if parallelizing a row is necessary, break up the sorting algorithm into tasks and assign them to cores. We need a parallel sorting algorithm for this

Any comments or other ideas?

**Comment by loumalouomega** [comment]
Well, initial implementation is mine, inspired in AMGCL implementation, sorry if this implementation is not as fast as it could. I will think about it.

**Comment by loumalouomega** [comment]
> Well, initial implementation is mine, inspired in AMGCL implementation, sorry if this implementation is not as fast as it could. I will think about it.

As you say we can consider `std::sort` (STL does not use naive sort, but quicksort algoritjhm which is n log n  complexity), and as we use C++17, we can use the execution parallel policies, the code should be something like this (I cannot debug right now but a priori something like this should work):

~~~c++
#include <algorithm> // For std::sort, I think already included
#include <execution> // For execution policies, I think this is not included as this code is previous to C++17

template <typename TSize, typename Col, typename TIndexType, typename ValueType>
static void SortRows(
    const TIndexType* CPtr,
    const TSize NRows,
    const TSize NCols,
    Col* Columns,
    ValueType* Values
    )
{
    #pragma omp parallel for
    for (TSize i_row = 0; i_row < NRows; i_row++) {
        const TIndexType row_begin = CPtr[i_row];
        const TIndexType row_end = CPtr[i_row + 1];
        TSize length = row_end - row_begin;

        // Use vectors to facilitate sorting
        std::vector<std::pair<Col, ValueType>> row_data(length);
        for (TSize j = 0; j < length; ++j) {
            row_data[j] = {Columns[j + row_begin], Values[j + row_begin]};
        }

        // Sort using a more efficient parallel algorithm
        std::sort(std::execution::par, row_data.begin(), row_data.end(), [](const auto& a, const auto& b) {
            return a.first < b.first;
        });

        // Write back sorted data
        for (TSize j = 0; j < length; ++j) {
            Columns[j + row_begin] = row_data[j].first;
            Values[j + row_begin] = row_data[j].second;
        }
    }
}
~~~

**Comment by loumalouomega** [comment]
> > Well, initial implementation is mine, inspired in AMGCL implementation, sorry if this implementation is not as fast as it could. I will think about it.
> 
> As you say we can consider `std::sort` (STL does not use naive sort, but quicksort algoritjhm which is n log n complexity), and as we use C++17, we can use the execution parallel policies, the code should be something like this (I cannot debug right now but a priori something like this should work):
> 
> ```c++
> #include <algorithm> // For std::sort, I think already included
> #include <execution> // For execution policies, I think this is not included as this code is previous to C++17
> 
> template <typename TSize, typename Col, typename TIndexType, typename ValueType>
> static void SortRows(
>     const TIndexType* CPtr,
>     const TSize NRows,
>     const TSize NCols,
>     Col* Columns,
>     ValueType* Values
>     )
> {
>     #pragma omp parallel for
>     for (TSize i_row = 0; i_row < NRows; i_row++) {
>         const TIndexType row_begin = CPtr[i_row];
>         const TIndexType row_end = CPtr[i_row + 1];
>         TSize length = row_end - row_begin;
> 
>         // Use vectors to facilitate sorting
>         std::vector<std::pair<Col, ValueType>> row_data(length);
>         for (TSize j = 0; j < length; ++j) {
>             row_data[j] = {Columns[j + row_begin], Values[j + row_begin]};
>         }
> 
>         // Sort using a more efficient parallel algorithm
>         std::sort(std::execution::par, row_data.begin(), row_data.end(), [](const auto& a, const auto& b) {
>             return a.first < b.first;
>         });
> 
>         // Write back sorted data
>         for (TSize j = 0; j < length; ++j) {
>             Columns[j + row_begin] = row_data[j].first;
>             Values[j + row_begin] = row_data[j].second;
>         }
>     }
> }
> ```

Also I avoided the static casts as with the new implementation should not be needed and the code is more compact.

**Comment by matekelemen** [comment]
using the parallel version for `std::sort` would be neat, but STL parallelism won't play nice with OpenMP, especially within an `omp` loop. We must **either** do the entire thing in OpenMP **or**  with STL parallelism, but we can't mix them.

**Comment by loumalouomega** [comment]
> using the parallel version for `std::sort` would be neat, but STL parallelism won't play nice with OpenMP, especially within an `omp` loop. We must **either** do the entire thing in OpenMP **or** with STL parallelism, but we can't mix them.

True

**Comment by RiccardoRossi** [comment]
these are short loops (rows) so the parallel implementation is not
efficient.

It is better to do many quick sorts in parallel

**Comment by loumalouomega** [comment]
@matekelemen I have done some tests and my suggestion (wthout std::execution::par) is 10% faster, if you want to do a test I will do a PR soon.
