### ISSUE TITLE
Container expressions - Test failing with 8 cores

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#12159]
While integrating master branch into our repositorty in @KratosMultiphysics/altair , I've found a test that gets stuck in MPI when running with 8 cores, and another one that is failing:
![image](https://github.com/KratosMultiphysics/Kratos/assets/25667299/d48ac30c-46dd-4a75-b678-414a6e272b29)

Could you please take a look? @sunethwarna @matekelemen 

BTW, I've found several times that a test fails only when running with 8 cores, maybe we could add this to our CI? @roigcarlo

**Comment by roigcarlo** [comment]
Ok, I will try to create a suit for 8 cores, but I would advise to only add those that we know that give problems, we are oversubscriving too much cores for the github machines.

**Comment by ddiezrod** [comment]
> Ok, I will try to create a suit for 8 cores, but I would advise to only add those that we know that give problems, we are oversubscriving too much cores for the github machines.

Maybe other option is instead of testing with 2,3 and 4 cores, is to run with 2,4 and 8. In my experience, errors in MPI usually appear when you have a higher number of cores...

**Comment by matekelemen** [comment]
I'd rather go with 3, 4 and 8 just to have an odd number (and not only powers of 2) as well.

**Comment by philbucher** [comment]
thats something to try
The linux machine have only 2 cores, the execution gets already quite slow with 4 procs
Maybe Altair could provide some machines? Seems that you regularly test with larger core numbers :thinking: 

Reminder: we get thousands of CPU-hours for free from github :D
