### ISSUE TITLE
[StructuralMechanics] Tests Requiring ConstitutiveLawsApp

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#12160]
The [TotalLagrangianMixedVolumetricStrainElementBonetPatch](https://github.com/KratosMultiphysics/Kratos/blob/5c47d94ef271aad3ce998a8ed5f6f6accf1c2d92/applications/StructuralMechanicsApplication/tests/cpp_tests/test_total_lagrangian_mixed_volumetric_strain_element.cpp#L178) test segfaults if `ConstitutiveLawsApplication` is not available. @rubenzorrilla can you please fix it and check the rest of the tests in `StructuralMechanicsApplication` as well?

**Comment by loumalouomega** [comment]
With the proper decorator the test can be skipped

**Comment by matekelemen** [comment]
> With the proper decorator the test can be skipped

It's a C++ test. Besides, as far as I remember there have been a couple of similar bugs recently, which is why I'm asking Ruben to take a look at his tests.

**Comment by loumalouomega** [comment]
> > With the proper decorator the test can be skipped
> 
> It's a C++ test. Besides, as far as I remember there have been a couple of similar bugs recently, which is why I'm asking Ruben to take a look at his tests.

In that case can be skipped iwth a return void if the law is not existing

**Comment by rubenzorrilla** [comment]
I'll do it right away following @loumalouomega 's suggestion.

**Comment by philbucher** [comment]
C++ tests should not have application dependencies, this was decided long time ago
I recommend to use a python test instead
