### ISSUE TITLE
Incompressible Fluid Application not compiling

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#1216]
Hi @jrubiogonzalez and @roigcarlo ,
apparently, the Incompressible Fluid Application is no longer compiling due to some missing variables: TEMPERATURES, VELOCITIES and MATERIAL.
It is probably due to PR#1198 that was merged recently. But I see that #1215 is also doing something with these variables. Can we use #1215 to make sure that this app is compiling?

**Comment by roigcarlo** [comment]
Ok, let me try to compile it

**Comment by jrubiogonzalez** [comment]
They are used in this process. copy_to_vulcan_post_variables_process.h, It is no longer being used, in fact we removed dependency of this application long time ago. So I'd suggest to simply remove the process (It was just a post process to match Vulcan results)

**Comment by roigcarlo** [comment]
Fixed in b0dfcf5(#1215)
