### ISSUE TITLE
Kratos currently not compiling under Windows

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#1219]
Dear all,

we noticed that the current master branch is not compiling under Windows giving the following error:

![image](https://user-images.githubusercontent.com/25897162/34257552-9bed77c0-e65a-11e7-8266-a68f4cd65d5d.png)

Can anybody confirm this, or suggest a solution? Thanks in advance.

Best regards,
Daniel

**Comment by roigcarlo** [comment]
I'll take a look

**Comment by roigcarlo** [comment]
Fixed in #1224
