### ISSUE TITLE
[GeoMechanicsApplication] Implement line thermal element for borehole pipe

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#12200]

**Comment by rfaasse** [comment]
This is the overarching issue for the element, so moving this back to the product backlog, since we're working on the 'sub-issues' now. We might be able to remove it as well, if all functionality is captured in the smaller issues

**Comment by rfaasse** [comment]
Closing this issue, as the sub issues are done, FYI @mcgicjn2
