### ISSUE TITLE
[MPM] CI Fails Regularly

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#12256]
The `MPMApplication` regularly fails at the (single-rank) python test phase with no message whatsoever.

```
 Running MPMApplication tests
...................................................................................ss......D:\a\Kratos\Kratos\bin\Custom\applications//MPMApplication/tests/test_MPMApplication.py
Completed MPMApplication tests with exit code 1!
```

##

I haven't checked but I assume it's some sort of memory corruption because `unittest` can't even generate an error report. If you have trouble finding the issue, I recommend taking the time to compile with ASAN enabled (`-fsanitize=address`) and sift through the report it generates for each test case separately.

##

Here's a complete report of a recent Windows CI failure from #12254: [ci_log.txt](https://github.com/KratosMultiphysics/Kratos/files/14897378/ci_log.txt)

**Comment by VeronikaSinger** [comment]
Hi @matekelemen 

I somehow missed this issue - is this problem still present?

**Comment by matekelemen** [comment]
I haven't seen it recently, but I haven't been active lately either. If I run into it again I'll repoen the issue.

Thanks for the fix again!
