### ISSUE TITLE
[Structural][ConstitutiveLaws] CL dependency from Structural in tests

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#12272]
**Description**
@KratosMultiphysics/structural-mechanics  Currently some Consitutive law application tests:

```console
[  FAILED  ] KratosConstitutiveLawsFastSuite.RuleOfMixturesConstitutiveLawHexahedronTwoLayers
[  FAILED  ] KratosConstitutiveLawsFastSuite.RuleOfMixturesConstitutiveLawHexahedronThreeLayers
[  FAILED  ] KratosConstitutiveLawsFastSuite.RuleOfMixturesConstitutiveLawTetrahedronTwoLayers
[  FAILED  ] KratosConstitutiveLawsFastSuite.RuleOfMixturesConstitutiveLawTetrahedronThreeLayers
[  FAILED  ] KratosConstitutiveLawsFastSuite.LinearElasticCasePertubationTensorUtility
[  FAILED  ] KratosConstitutiveLawsFastSuite.QuadraticLinearElasticCasePertubationTensorUtility
[  FAILED  ] KratosConstitutiveLawsFastSuite.QuadraticSmallStrainIsotropicPlasticity3DVonMisesVonMisesFirstOrderCasePertubationTensorUtility
[  FAILED  ] KratosConstitutiveLawsFastSuite.QuadraticSmallStrainIsotropicPlasticity3DVonMisesVonMisesCaseSecondOrderPertubationTensorUtility
[  FAILED  ] KratosConstitutiveLawsFastSuite.QuadraticSmallStrainIsotropicDamage3DsVonMisesCaseAutomaticDiffTensorUtility
[  FAILED  ] KratosConstitutiveLawsFastSuite.SmallDisplacementElement2D3NThermalLinearPlaneStrain
[  FAILED  ] KratosConstitutiveLawsFastSuite.SmallDisplacementElement2D3NThermalLinearPlaneStress
[  FAILED  ] KratosConstitutiveLawsFastSuite.SmallDisplacementElement2D3NThermalLinearPlaneStrainWithTable
[  FAILED  ] KratosConstitutiveLawsFastSuite.SmallDisplacementElement3D4NThermalLinearIsotropic3DWithTable
```

Have a dependency on elements registered and defined in the Structural mechanichs application. While this has been working until now (because the kratos kernel was badly handled during the cpp tests executions), it is causing the new tests to fail as they run now in an isolated kernel with no application dependencies (in most of the cases).

In particular `ConstitutiveLawsApplication` should not have a runtime dependency from the `StrcutrualMechanicsApplication` kernel.

My proposal is to move those tests to the StructuralMechanicsApplication and, if necessary, make a kernel delendency from the ConstitutiveLawsApplication in the Structural Test binary ( basically the oposite as what is happening right now)

Also ping @avdg81 & @rfaasse to keep track

**Comment by roigcarlo** [comment]
Ps,

The incorrect elements/laws are:

`SmallDisplacementElement3D8N`
`SmallDisplacementElement2D3N`
`SmallDisplacementElement3D4N`
`LinearElastic3DLaw`

**Comment by loumalouomega** [comment]
Feel free to move by approval by @AlejandroCornejo

**Comment by philbucher** [comment]
Not sure I fully understand the issue, but the structural app should not have the claw app as dependency 

We initially separated the to avoid this

**Comment by philbucher** [comment]
Can you post the error?

This problem also exists for other applications

**Comment by rubenzorrilla** [comment]
If there is such dependency, those tests should most probably be Python tests (which can be eventually skipped).

**Comment by AlejandroCornejo** [comment]
It is exactly as @philbucher says, the SMApp should not have any dependency on the CLApp. If there is one, we can move those CLApp related tests to the proper app

**Comment by roigcarlo** [comment]
Failures are like this:

```
[ RUN      ] KratosConstitutiveLawsFastSuite.SmallDisplacementElement3D4NThermalLinearIsotropic3DWithTable
Initializing KratosConstitutiveLawsApplication...
unknown file: Failure
C++ exception with description "Error: The component "SmallDisplacementElement3D4N" is not registered!
Maybe you need to import the application where it is defined?
The following components of this type are registered:
    DistanceCalculationElementSimplex2D3N
    DistanceCalculationElementSimplex3D4N
    EdgeBasedGradientRecoveryElement2D2N
    EdgeBasedGradientRecoveryElement3D2N
    Element2D1N
    Element2D2N
    Element2D3N
    Element2D4N
    Element2D6N
    Element2D8N
    Element2D9N
    Element3D10N
    Element3D13N
    Element3D15N
    Element3D1N
    Element3D20N
    Element3D27N
    Element3D2N
    Element3D3N
    Element3D4N
    Element3D5N
    Element3D6N
    Element3D8N
    GenericElement
    LevelSetConvectionElementSimplex2D3N
    LevelSetConvectionElementSimplex3D4N
    LevelSetConvectionElementSimplexAlgebraicStabilization2D3N
    LevelSetConvectionElementSimplexAlgebraicStabilization3D4N
```

From the `KRATOS_REGISTER_ELEMENT("SmallDisplacementElement3D4N", mSmallDisplacement3D4N)` which is added by the structural mechanics application

Agree that they should be moved to the structural

**Comment by roigcarlo** [comment]
So, the problem is not the structural depending on the CL, is the other way around

**Comment by philbucher** [comment]
Ok thx

I have some thoughts and possible solutions, will post them after work

**Comment by philbucher** [comment]
So the CLaws app depends currently on the Structural App. Therefore, it uses some of its elements for C++ tests. Usually we say that we do not allow dependencies for C++ tests between apps, but since they are dependent I think it is a fair/valid usecase (any opinion @rubenzorrilla ?)

Now, the elements are not available because the `StructuralApp` is never imported, the `Register` function is never called which would prevent the error above. 
I.e. nothing from the parent App can be used through the Registry/KratosComponents etc.

I see several solutions for this problem (and I think we should solve it because using things from the parent app is a valid usecase IMO):

- Directly use the things from the parent app, rather than through registry/KratsoComponents
    `model_part.CreateNewElement("SmallDisplacementElement3D4N", ...)` => `model_part.AddElement(make_shared<SmallDisplacementElement3D4N>())`
    This is the least intrusive version / least changes required
- Import the parent application one way or another:
    - Using python from C++ when launching the tests. Probably not the way to go, but pybind can technically do this
    - Deriving the Application (the c++ class) from the parent. This would also trigger the `Register` call. TBH I would try this, the changes would be very small (I think), but this would solve the problem well

**Comment by roigcarlo** [comment]
If the CL is dependent on the structural at compile time then there is no problem (I just assumed the dependency did not exist at app level), but its odd that this dependency exists :S

sorry for the noise

**Comment by philbucher** [comment]
> If the CL is dependent on the structural at compile time then there is no problem (I just assumed the dependency did not exist at app level), but its odd that this dependency exists :S

https://github.com/KratosMultiphysics/Kratos/blob/2937f5c541fe496be3c9ba75f84b73bfea1a27ac/applications/ConstitutiveLawsApplication/ConstitutiveLawsApplication.py#L3

:)

> sorry for the noise

All good
