### ISSUE TITLE
[GeoMechanicsApplication] Add integration point to extrapolation process to geomechanics application

### ISSUE THREAD

**Issue by mcgicjn2** [KratosMultiphysics/Kratos#12293]
Through the use of element shape functions, the extrapolation matrix for an element can be calculated. Through this extrapolation matrix the gauss values on a single element can be extrapolated to the nodes. These values should then be averaged for the number of connecting elements.

**Acceptance Criteria:**

- A **user** would like to calculate gauss\integration point values on the nodes of the mesh. (Typically for visualization)
- The process should be able to make this calculation for all available element types
- The process should be efficient
- The process should be fully tested
- For unsupported combinations of elements/components, a warning should be displayed to the user.
- Add documentation for the process

**Comment by indigocoral** [comment]
The process works for 3, 4, 6, and 8 node plane strain elements. And it can be made working for 2 and 3 node line elements, 4 and 10 tetrahydra, 8 and 20 node hexahydra, and 6 and 15 node wedges.
Code smells and duplication should be taken out by native C++ programmer, together with creating unit tests. Integration tests should be created for additional elements. Readme.md files should also be written for the tests and documentation of the process.
