### ISSUE TITLE
Kratos Parameters should GetVector & GetMatrix return bounded objects?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1229]
Hi @RiccardoRossi and @pooyan-dadvand 
I was looking through Kratos::Parameters and thought if the Methods `GetMatrix` and `GetVector` should return bounded objects or not. Right now the returned objects are standard `Vector` and `Matrix`, but after @pooyan-dadvand comments in #757 I thouht this should maybe be different

The returned objects should not be modified afterwards from how I understood, is that correct?

**Comment by philbucher** [comment]
I just noticed that they return `const`
Therefore I think it would be ok if they are bounded.

The only concern I have is if bounded_matrix is a subclass of the regular matrix.
I.e. if I could still do 
```
Matrix my_matrix = params.GetMatrix("test);
```
with 
```
bounded_matrix GetMatrix() {...}
```

**Comment by RiccardoRossi** [comment]
Hi @philbucher 

you don't know the size at compile time, so they cannot be bounded objects.

the point of pooyan (to my understanding) was that within the element you did know the size, so you'd better use it

**Comment by philbucher** [comment]
hm ok understood, thx
