### ISSUE TITLE
Element size for quadratic elements

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/Kratos#12300]
**Description**
I saw that the way of calculating the `AverageSizeCalculator` has been changed in line 866 of `element_size_calculator.cpp`. I remember that I modified it in past because Kratos assigned for biquadratic elements half of the size that bilinear ones (you can try with a regular structured mesh). Have you checked that the method `rGeometry.Length()` still corrects the underestimation of element size?

**Scope**
KratosCore

**Comment by loumalouomega** [comment]
The author of the code, https://github.com/KratosMultiphysics/Kratos/blob/51f3e625ac2a8d3fee51072ad2fc4780d2c73b80/kratos/utilities/element_size_calculator.cpp#L866, is @jcotela , not me

**Comment by jgonzalezusua** [comment]
Sorry, bu the last ones who changed that were you and @sunethwarna

**Comment by loumalouomega** [comment]
Maybe I just refactored, but I don't even recognise that code

**Comment by jgonzalezusua** [comment]
> Maybe I just refactored, but I don't even recognise that code

Ok
