### ISSUE TITLE
test_harmonic_analysis.py failing in the structural_mechanics application (in FullDebug)

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1230]
the test: test_harmonic_analysis.py fails in FullDebug.

the error message is

terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: attempting to do a GetValue for: NODAL_STIFFNESS variable #711 unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)

in kratos/containers/data_value_container.h:199:TDataType& DataValueContainer::GetValue(const Variable<TDataType>&) [with TDataType = array_1d<double, 3ul>]
   /home/rrossi/kratos_git/applications/StructuralMechanicsApplication/custom_elements/nodal_concentrated_element.cpp:292:virtual void NodalConcentratedElement::CalculateLocalSystem(Element::MatrixType&, Element::VectorType&, ProcessInfo&)
   /home/rrossi/kratos_git/applications/StructuralMechanicsApplication/custom_strategies/custom_schemes/eigensolver_dynamic_scheme.hpp:122:void EigensolverDynamicScheme<TSparseSpace, TDenseSpace>::CalculateSystemContributions(Element::Pointer, EigensolverDynamicScheme<TSparseSpace, TDenseSpace>::LocalSystemMatrixType&, EigensolverDynamicScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType&, Element::EquationIdVectorType&, ProcessInfo&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; Element::Pointer = boost::shared_ptr<Element>; EigensolverDynamicScheme<TSparseSpace, TDenseSpace>::LocalSystemMatrixType = boost::numeric::ublas::matrix<double>; EigensolverDynamicScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType = boost::numeric::ublas::vector<double>; Element::EquationIdVectorType = __debug::vector<long unsigned int>]

**Comment by loumalouomega** [comment]
I will add the corresponding checks to the element

**Comment by RiccardoRossi** [comment]
thx @loumalouomega
