### ISSUE TITLE
[GeoMechanicsApplication] Implement drainage policy

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#12318]
As a developer, I want the drainage functionality to be separated from the elements, such that the elements become more maintainable and extendible and easier to understand.

**Acceptance criteria**
- All functionality related to drainage, which could have different implementations (i.e. transient, drained and undrained) is moved to a separate class using the strategy design pattern see e.g. [wikipedia](https://en.wikipedia.org/wiki/Strategy_pattern) for a bit more info.
- Three strategies/policies are created, all deriving from an abstract interface, to provide the drainage functionality.

As discussed as apart of #12067 the interface for this policy will provide the following two functions to add the coupling, permeability and compressibility contributions to the left and right hand side:
- AddToLHS(Matrix& rLeftHandSideMatrix, …, const callBack) and
- AddtoRHS(Vector& rRightHandSideVector, …, const callBack).

where the callBack will hold references on required functions and it will be populated by an element (this implementation detail might still change).

We estimated this to be 13 SP, but removing it for now, since it's not ready to be picked up, and still needs to be split up

**Comment by rfaasse** [comment]
@markelov208 @WPK4FEM @avdg81 I added some details to this issue, feel free to add to/correct it.

**Comment by avdg81** [comment]
We will no longer attempt to create a drainage policy. Instead, we'll use the calculator-based approach, where we can inject the relevant contributions for the left hand side and the right hand side.
