### ISSUE TITLE
improving usefullness of python test output

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1232]
@roigcarlo a big improvement in usability would be to print the exact name of the test faling.

right now for example there is no way to see which test is causing the following output
(i already found out for this specific case, however i post here the output so that you can see my point)

Running tests for StructuralMechanicsApplication
.........................terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: attempting to do a GetValue for: YOUNG_MODULUS_X variable #1139 unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)

**Comment by philbucher** [comment]
I think it is printed if you increase the verbosity of the tests
-> python3 test_XY -v 2

**Comment by pooyan-dadvand** [comment]
I agree, I think unittesting should handle Kratos Exception separately giving the info of code location

**Comment by RiccardoRossi** [comment]
It is not possible to capture segfaults that happen in tests so the solution for now is to increase verbosity as @philbucher suggests. Closing for now. We'll reopen if we find a good solution
