### ISSUE TITLE
test_patch_test_shells_orthotropic.py takes very long

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1235]
@KratosMultiphysics/structural-mechanics the title says it all.

**Comment by philbucher** [comment]
currently fixing it in [my branch](https://github.com/KratosMultiphysics/Kratos/tree/StructMech/shells-new-testing-and-cleanup)

**Comment by roigcarlo** [comment]
@RiccardoRossi @philbucher Is this test being run in the nightly suit? I am having problems to debug why lately fails to send the mail and everything looks fine, so I am starting to track long tests.

**Comment by philbucher** [comment]
Yes it is
Shall make a PR to disable it temporarily?
You can disable it by commenting [this line](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py#L158)

Good thing I am not the onlyone not receiving the mails

**Comment by roigcarlo** [comment]
If you are fixing it already its ok, just to know :+1:

**Comment by roigcarlo** [comment]
@philbucher Finally the problem with the builds had nothing to do with the test. Just commenting it since I was asking around here.

**Comment by roigcarlo** [comment]
@philbucher Can we close this already?
