### ISSUE TITLE
[Core][IO] wrong output in vtk files when Point3D elements are present in model

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#12415]
In case Point3D elements are present in my model, all values on all integration points are inf or Nan. 

My guess is that it happens because Point3D has zero integration points and in vtk_output.cpp in WriteIntegrationScalarContainerVariable(, there is a division by the number of integration points.

**Comment by loumalouomega** [comment]
Well, the extrapolation to nodes from GP is my implementation, I never thought about possibility of 0D elements. I can do a fix.

**Comment by aronnoordam** [comment]
nice thanks!

**Comment by aronnoordam** [comment]
I think on line 920:
 `aux_value /= static_cast<double>(integration_points_number);`
, there is a division by 0 for point3D elements
