### ISSUE TITLE
[GeoMechanicsApplication] Change the base class of `SmallStrainUPwDiffOrderElement` to `UPwBaseElement`

### ISSUE THREAD

**Issue by markelov208** [KratosMultiphysics/Kratos#12450]
**Acceptance Criteria**

The direct base class of `SmallStrainUPwDiffOrderElement` is no longer `Element`, but it has become `UPwBaseElement`.

**Dependencies**

This issue requires [class `UPwBaseElement` to be a non-template class](https://github.com/orgs/Deltares/projects/55/views/8?pane=issue&itemId=65735666) first.

**Implementation Details**

In order to achieve what has been described above, the following action points have to be carried out:
- [ ] Make sure that the new base class is reflected by member functions `load` and `save` of class `SmallStrainUPwDiffOrderElement`.
- [ ] Remove the following data members (since they are also defined in `UPwBaseElement`): `mConstitutiveLawVector`, `mRetentionLawVector`, `mStressVector`, `mStateVariablesFinalized`, and `mIsInitialised`.
- [ ] In class `SmallStrainUPwDiffOrderElement`, replace the `virtual` keyword by the `override` keyword for the following member functions: `CalculateMaterialStiffnessMatrix`, `CalculateAll`, and `GetNumberOfDOF`.
- [ ] Remove the following member functions from class `SmallStrainUPwDiffOrderElement` (since they are identical to the ones implemented by `UPwBaseElement` _and_ they are non-`virtual`): `CalculateDerivativesOnInitialConfiguration`, `CalculateJacobianOnCurrentConfiguration`, and `GetStressStatePolicy`.

**Comment by avdg81** [comment]
Closed by https://github.com/KratosMultiphysics/Kratos/pull/12457
