### ISSUE TITLE
Question about import-checks

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1246]
Hi @KratosMultiphysics/technical-committee and @rubenzorrilla , I have some small questions:
With the recent introduciton of `CheckRegisteredApplications`, should we still be using the function `CheckForPreviousImport` in python-scripts such as a solver? Or is this deprecated? 

Also I have a question abt the `KratosMultiphysics.mpi` module: should we always import it in the mpi-solver scripts or only when we need the functionalities (It is just the MPI-Python interface, right?)
And can we use `CheckForPreviousImport`also on this module?

**Comment by RiccardoRossi** [comment]
Hi Philip,

i would say that we only have a half baked solution right now. the Check Registered does some of the work of the CheckForPreviousImport (which is broken anyway), however it is not a definitive answer. Hold on a little longer. Hopefully we will have a nicer solution not too long from now.
