### ISSUE TITLE
[GeoMechanicsApplication] Document the relation between the UPwSmallStrainInterfaceElement and UPwBaseElement

### ISSUE THREAD

**Issue by rfaasse** [KratosMultiphysics/Kratos#12497]
As a developer, I'd like to know the relation between the UPwSmallStrainInterfaceElement and UPwBaseElement, such that I know the steps needed to isolate the interface elements from the continuum elements.

**Predecessor** #12493 

**Acceptance Criteria**
- The functions used in the interface elements, but not overridden (i.e. only available in UPwBaseElement) are documented
- The variable JOINT_WIDTH is understood and documented

**Comment by markelov208** [comment]
UPwSmallStrainInterfaceElement calls the following UPwBaseElement functions explicitely
1.	Check
2.	Initialize
3.	GetNumberOfDOF 
4.	CalculateIntegrationCoefficients l
Based on test_interface.py, it also uses the following UPsSmallStrainElement functions:
5.	GetDofList
6.	CalculateLocalSystem
7.	CalculateRightHandSide
8.	EquationIdVector
9.	GetIntegrationMethod
10.	GetDofs
11.	CalculateDerivativesOnInitialConfiguration
12.	CalculateJacobianOnCurrentConfiguration

The following UPwSmallStrainElement functions are not covered by the tests: 
1.	CalculateLeftHandSide
2.	CalculateDampingMatrix
3.	GetValuesVector
4.	GetFirstDerivativesVector
5.	GetSecondDerivativesVector
6.	CalculateOnIntegrationPoints 
7.	SetValuesOnIntegrationPoints 
8.	ResetConstitutiveLaw
9.	GetStressStatePolicy

However, these interface tests are not complete. For example, they do not cover all UPwSmallStrainInterfaceElement functions, namely, the following 6 functions out of 42 functions are not covered:
1.	Create(IndexType NewId, GeometryType::Pointer pGeom, PropertiesType::Pointer pProperties) 
2.	CalculateMassMatrix
3.	CalculateOnLobattoIntegrationPoints
4.	CalculateOnLobattoIntegrationPoints
5.	ExtrapolateGPValues
6.	CalculateMaterialStiffnessMatrix

**Comment by avdg81** [comment]
Since the relationships have been documented (see above) we can now close this issue.
