### ISSUE TITLE
[GeoMechanicsApplication] Investigate and document the geo interface elements

### ISSUE THREAD

**Issue by WPK4FEM** [KratosMultiphysics/Kratos#12493]
As a developer I would like to have documentation on interface elements, such that I can more easily maintain and extend these elements.

**Successor** #12497

**Acceptance Criteria**
- The README.md file is extended with information on the interface elements (e.g. the order of DoF, stress/strain matrices)
- This is scoped to the following elements: UPwSmallStrainInterfaceElement, TransientPwInterfaceElement, SteadyStatePwInterfaceElement
- The gaps of functionality in the interface elements are documented (known already: diff order elements, quadratic variants)

**Comment by WPK4FEM** [comment]
For the tunnel model I have been trying interface elements in combination with UDSM material. Here I try to list my findings:

U_Pw Interface elements in GeoMechanics are basically copied from the PorousMechanics of Pouplana. 

The choosen geometry for the line interface element is a quadrilateral plane. Desirable would have been a line. This has several consequences:
- the node numbering is line the plane i.s.o. the 2nd side also numbering in the direction of the axis along the interface.
- interpolation has ksi and eta, intergration points are placed at eta = 0. Hence the polynomial gives values of +- 0.5 i.s.o 1 in the nodes.
- What is the B matrix in regular elements is here called Nu. It contains the correct subtraction of variables on the opposite sides. For clarity, I would rename it to b_matrix 
- the quadratic line interface ( 3+3 nodes ) is missing, probably because it has no generatable equivalent in GiD for pre and postprocessing. We need it for compatibility with quadratic triangular and quadrilateral elements.
- The chosen local coordinate system is X along and Z across the line interface. The strain and stress vector start with shear XZ, followed by the normal component ZZ. That is different from the choice XX, YY, ZZ, XY, YZ, ZX for the plane strain and solid continua and created quite some rearranging and specialized code.
- The relative displacement ( with unit of length ) seems to be passed to constitutive laws as a strain ( dimensionless ). 
- Output items local_strain_vector and local_stress_vector give relative displacement and traction vectors respectively.

**Comment by WPK4FEM** [comment]
geo/interface_elements is the GitHub branch on which I have tried to understand behaviour of the line interface element 
Anne has worked with me on understanding the behaviour, he will recognize some of the printing.
the example64.dll was not put in the repository. I place it on my postbox, Gennady also has it.

**Comment by mnabideltares** [comment]
A word document forinterface element.

[Interface elements.docx](https://github.com/user-attachments/files/16238168/Interface.elements.docx)

**Comment by rfaasse** [comment]
Added my (2) comments to [Interface_elements_comments_RF.docx](https://github.com/user-attachments/files/16313095/Interface_elements_comments_RF.docx)

@avdg81 @markelov208 feel free to close this issue when you have added your comments!

**Comment by avdg81** [comment]
I have added my comments, too.

[Interface_elements_comments_RF_AvdG.docx](https://github.com/user-attachments/files/16333003/Interface_elements_comments_RF_AvdG.docx)

**Comment by markelov208** [comment]
Here are my comments. 

[Interface_elements_comments_RF_AvdG_GM.docx](https://github.com/user-attachments/files/16347244/Interface_elements_comments_RF_AvdG_GM.docx)
