### ISSUE TITLE
Kratos New Testing

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#12503]
@KratosMultiphysics/all  As you my have notice we have recently merged #11506. This mean that, already open PR may have problems merging directly with the master.

If this is your case please merge the new master into your branch and the CI will not complain:

```console
git checkout master
git pull origin master
git checkout [your_branch_name]
git merge master
```

Also, please notice that, since Kratos test now live in their own executable interfacing them with python is no longer possible (you can still launch them by calling a subprocess if you wish to do so). For that matter, `KratosMultiphysics.Tester` is no longer available.

We apologize for the trouble.

**Comment by loumalouomega** [comment]
I think this can be closed and upinned already
