### ISSUE TITLE
windows compilation error in pointer_hash_map_set.h

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#1252]
![kratos_windows_compilation_error](https://user-images.githubusercontent.com/23210788/34670993-e25e9f00-f478-11e7-9596-3f004a0e571c.png)

**Comment by philbucher** [comment]
@oberbichler I think this is the same error you have

**Comment by pooyan-dadvand** [comment]
hmmm, my recent correction may cause it. let me check it!

**Comment by jginternational** [comment]
Same for me. Only in Windows
