### ISSUE TITLE
Testing a static analysis tool

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#1254]
@KratosMultiphysics/team-maintainers 

As you may observed in PRs there is a new check by codacy and I have added to our GitHub. This check perform static analysis on the code and try to do some standard review on it. At this moment it is experimental and I think we should tune it to be practical in Kratos. Nevertheless I think take a look at its reports is useful and my give you some hints in the implementation.

Meanwhile it would be great to have your comments about checks to be disabled here in this issue.

**Comment by philbucher** [comment]
Checking the types of objects in python scripts with `isinstance` (suggested by the tool) or with `type` (currently done, see [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/python_solvers_wrapper_structural.py#L11))

**Comment by pooyan-dadvand** [comment]
I understand that you want to disable this check. Isn't it?

I'm not a pythonic guy and leave your suggestion to the more python friendly guys!

**Comment by philbucher** [comment]
I don't have a strong opinion. Just saying that the way it is currently done is being marked by the codacy.

**Comment by pooyan-dadvand** [comment]
We will keep it as it is and gradually will take out the annoying ones
