### ISSUE TITLE
[GeoMechanicsApplication] Check integrity of densityMatrix

### ISSUE THREAD

**Issue by mnabideltares** [KratosMultiphysics/Kratos#12584]
As a software developer I would like to check the integrity of density matrix. Currently it is created with AssembleDensityMatrix and all elements are equal to density value. 

Using an unity matrix with the density value does not change our unit and integration tests.

Porous Mechanics application uses only the density value. No any density matrices. A similar way is used in [geo/correct_mass_matrix_upw](https://github.com/KratosMultiphysics/Kratos/pull/12521)

**Comment by mnabideltares** [comment]
In "element_utilities.hpp"

    template <unsigned int TDim>
    static inline void AssembleDensityMatrix(BoundedMatrix<double, TDim + 1, TDim + 1>& DensityMatrix, double Density)
    {
        for (unsigned int idim = 0; idim < TDim; ++idim) {
            for (unsigned int jdim = 0; jdim < TDim; ++jdim) {
                DensityMatrix(idim, jdim) = Density;
            }
        }
    }

This is worng as the matric componets are all filled by "Density". It has to be:

    template <unsigned int TDim>
    static inline void AssembleDensityMatrix(BoundedMatrix<double, TDim + 1, TDim + 1>& DensityMatrix, double Density)
    {
        for (unsigned int idim = 0; idim < TDim; ++idim) {
            DensityMatrix(idim, idim) = Density;
        }
    }

To have only the diagonal to be filled by "Density". In the case the density is constant (which is the case), we can ignore defining matrix for density, and use scalar value.

**Comment by indigocoral** [comment]
Some changes are proposed to be done by @aronnoordam in this [pull request](https://github.com/KratosMultiphysics/Kratos/pull/12521).

Closed by:

- https://github.com/KratosMultiphysics/Kratos/pull/12521
- https://github.com/orgs/Deltares/projects/55/views/1?pane=issue&itemId=72850954

**Comment by aronnoordam** [comment]
In the UPw interface, element, the same Density matrix is used. This is not fixed in #12521, as it has to be looked into if its correct or not
