### ISSUE TITLE
[GeoMechanicsApplication] "auto" variable declaration instead of array_1d<double, 3> messes with results on WSL on my machine

### ISSUE THREAD

**Issue by aronnoordam** [KratosMultiphysics/Kratos#12591]
"auto" variable declaration instead of array_1d<double, 3> messes with results on WSL on my machine

on my machine i was getting Nan values from "UpdateVectorSecondTimeDerivative" in  applications/GeoMechanicsApplication/custom_strategies/schemes/generalized_newmark_scheme.hpp

when I changed "const auto updated_second_time_derivative"

to: "const array_1d<double, 3> updated_second_time_derivative"

and same in "UpdateVectorFirstTimeDerivative"

my problems were solved.

**Comment by philbucher** [comment]
FYI: #7414

in a nutshell: dont use `auto` for `array_1d`

**Comment by aronnoordam** [comment]
Clear, thanks!
