### ISSUE TITLE
Length gives nan for inverted elements which leads to wrong quality measure

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#126]
The length in tetrahedra_3d_4 is calculated using the volume and gives `-nan` for inverted elements. This leads to a same result for quality measures which use the length.

@KratosMultiphysics/technical-committee can we change the definition of the length or make the qualities work in a separate way?

My option would be to "correct" the length but there is no best interpretation of what is the length and how to calculate it.

**Comment by roigcarlo** [comment]
@pooyan-dadvand I will fix this in #101 since it is related.

**Comment by RiccardoRossi** [comment]
Hi,

in my opinion we can have an open discussion on how to compute the lenght and then do it consistently for all the elements. However we shall first do a grep to see where this is currently being used, to minimize the impact on currently existing code.

Riccardo

**Comment by roigcarlo** [comment]
@pooyan-dadvand The problem with the length should have been fixed on #101 ( along with some other problems in the quality functions).

I did not automatically close this as I am not sure that was the source of the problem. Can you test if it works now?

**Comment by roigcarlo** [comment]
Closing this since it seems it works and the associated PR is merged. If it keeps returning wrong values we can make another issue.
