### ISSUE TITLE
WIndow CI fails with unexpected error

### ISSUE THREAD

**Issue by Igarizza** [KratosMultiphysics/Kratos#12627]
**Description**
The Windows CI has failed with following Error:
```
Run set PYTHONPATH=%PYTHONPATH%;%GITHUB_WORKSPACE%/bin/%KRATOS_BUILD_TYPE%
Process Id: 5964 

Running KratosCore tests
Error: .s...........................x........x........................................................FFFFFFFFFFFFFFs[Error]: Tests for KratosCore took too long. Process Killed.
Traceback (most recent call last):
  File "kratos/python_scripts/testing/run_python_tests.py", line 73, in <module>
    main()
  File "kratos/python_scripts/testing/run_python_tests.py", line 57, in main
    commander.RunPythonTests(applications, args.level, args.verbosity, cmd, signalTime)
  File "D:\a\Kratos\Kratos\bin\Custom\KratosMultiphysics\testing\utilities.py", line 212, in RunPythonTests
    self._RunTest(
  File "D:\a\Kratos\Kratos\bin\Custom\KratosMultiphysics\testing\utilities.py", line 164, in _RunTest
    if process_stdout:
UnboundLocalError: local variable 'process_stdout' referenced before assignment
Deregistering KratosMultiphysics
Error: Process completed with exit code 1.
```
Here is the log from CI run from PR: https://github.com/KratosMultiphysics/Kratos/actions/runs/10370528308/job/28708651708?pr=12373

**Scope**
The bug happened in the Windows CI.

**To Reproduce**
Steps to reproduce the bug (if applicable): Add any custom example files here if relevant.

**Expected behavior**
It is expected that the CI passes the test in a similar way to Linux Environment.  

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- Windows CI
- Branch: siapp/p_norm_damage_resp (with the latest master merged)

**Comment by roigcarlo** [comment]
Hi @Igarizza we are aware of the problem, unfortunately I am having no luck finding the issue. For the time being we have just marked the windows CI as options, if you have a pending PR feel free to ignore it and merge.

**Comment by rubenzorrilla** [comment]
Closing as it is already reported and ongoing.
