### ISSUE TITLE
[GeoMechanicsApplication] Investigate stresses and negative settlements below line load in stage 2

### ISSUE THREAD

**Issue by WPK4FEM** [KratosMultiphysics/Kratos#12623]
To check first to see whether this is on our end:

- Replace the soil model with linear elastic instead of abc (in stage 2)
- Check the input files

For the negative tension on the surface, the example can be found here:
n:\Projects\11209000\11209269\C. Report - advise\006-Software\testen D-Settlement\Alfa\Uniform load\

**Comment by WPK4FEM** [comment]
Sent to Raymond after investigation:
Hoi Raymond,
Heb gepoogd mijn sommetje zodanig aan te passen dat ik het gedrag van Settlement ( verticale spanning maaiveld ongelijk aan bovenbelasting ) uit Kratos zou komen. Dat is helaas mislukt. 
 
Toen heb ik in het sommetje wat je op mijn postbox zette het materiaal in alle stages op lineair elastisch gezet. Dan is de verticale spanning maaiveld gelijk aan bovenbelasting. Dat maakt helaas de UDSM.dll verdacht. Als ik stage 2 weer op UDSM materiaal zet, krijg ik voor stage 2 direct weer onbalans te zien. Stage 2 is de hele kleine tijdstap waarin er in de UDSM iets speciaals gebeurt om de instantane vervorming te laten zien ( dacht ik ). Spelen met convergentiecriteria lijkt hoegenaamd niets uit te halen. 
 
Ik meen me te herinneren dat er nabij maaiveld ook nog iets speciaals gedaan werd voor zeer lage spanningen. Hier zou de bovenbelasting dat moeten afvangen. Is er iets wat ik daarin over het hoofd zie? Het zou wel consistent zijn met jouw bevindingen dat het voor fijnere elementgrids minder duidelijk wordt.
 
Kortom, ik heb de puzzel nog niet opgelost, maar de gedragingen wijzen helaas naar de UDSM.
Heb jij nog suggesties en kan ik in de broncode van de UDSM.dll kijken?
 
Mvg Wijtze Pieter

**Comment by aronnoordam** [comment]
Is this a dynamic problem? If so, the problem might be solved by https://github.com/KratosMultiphysics/Kratos/pull/12521

**Comment by WPK4FEM** [comment]
This is a quasistatic problem, not a dynamic one.

**Comment by WPK4FEM** [comment]
Using a linear elastic model in a UDSM ( actually a MohrCoulomb model with a failure surface so far away that the response is elastic and the failure surface cannot be reached ), the problem does not reproduce. That rules out the connection of the UDSM to Kratos and indicates that the abc model itself plays a role.

Specific for stage 2 here is:
- switch to abc model
- abc model has stiffness that is proportional to the vertical compressive stress. ( see usrmod.f90 line 371    Eoed = sigv/a )
- small timestep, leading to the dt < eps_t behavior in the UDSM.dll

### Stiffness and displacement
The triangular elements near the surface are typically ordered alternating with a side on the surface or only 1 node on the surface. The position of the integration points is such that the integration point of the elements with a side on the surface are positioned at higher y position than those of the element with 1 node on the surface. A direct consequence of this is that the stiffness contribution to the nodes on the surface connecting the elements will have a higher stiffness than the midside nodes of the elements with an edge on the surface. In the displacement results the vertical movement of the midside nodes will be bigger than those of the corner nodes.

### Equilibrium
The load on top from the weight of water above the surface acts in the nodes. Uniform distributed load gives a 1/6 4/6 1/6 distribution on the nodes of an element edge. Hence the distribution of external vertical force to the surface nodes looks like 1 4 2 4 2 _____ 2 4 2 4 1.
Stresses in the element integration points integrate to an internal force that balance the external forces when equilibrium is reached.

**Comment by WPK4FEM** [comment]
Communicated the above on 16-8-2024 by demonstration on screen and by mail.
