### ISSUE TITLE
[GeoMechanicsApplication] Experiment with linear constraints to account for sheet pile walls not being present yet

### ISSUE THREAD

**Issue by WPK4FEM** [KratosMultiphysics/Kratos#12632]
There is a requirement to have nodal connectivities \ constraints when the interface \ sheetpile is not in place.

**Refinement 13/08/2024**

This will be an investigation to first understand how the existing mechanism works, second if it works with multi stage and boundary conditions and third how do we want to implement it.

The existing mechanism that we may want to use here is called multi-point constraint (MPC) and it has been documented [here](https://github.com/KratosMultiphysics/Kratos/wiki/%5BKratosAPI%5D-MultiPoint-Constraint-(MPC)-interface).

- Creating the small mesh with the split 
- Create a test in our test suite (check whether any exist)
- Get back with results of the investigation to the team in a refinement

Likely candidates to provide the desired functionality:
AssignMasterSlaveConstraintsToNeighboursProcess
AssignMasterSlaveConstraintsToNeighboursUtility

**Comment by WPK4FEM** [comment]
[linear_constraint.zip](https://github.com/user-attachments/files/16637209/linear_constraint.zip)

**Comment by WPK4FEM** [comment]
When converted to GeoMechanicsApplication the process AssignMasterSlaveConstraintsToNeighboursUtility seems to run correctly, but the linear equation solver does not find MasterSlaveConstraints on the model part that is given to the linear equation solver.

**Comment by avdg81** [comment]
The master-slave constraints have been added to the quay wall model by Wijtze Pieter. This issue can now be closed.
