### ISSUE TITLE
[GeoMechanicsApplication] Preparation for applying the POP in the K0 procedure process

### ISSUE THREAD

**Issue by indigocoral** [KratosMultiphysics/Kratos#12646]
Investigate how to implement POP in the k0 procedure process.
- See definition in powerpoint presentation on Kratos teams channel https://deltares.sharepoint.com/:p:/r/teams/d730-KratosTeamChannel/Shared%20Documents/Kratos%20Team%20Channel/K0%20verification/K0%20Procedure.pptx?d=w5f58e19bd5db4240b5e79198eeaeea1d&csf=1&web=1&e=GkJd5n
- Find suitable place in coding for the K0 procedure process
- First setup of documentation
- First attempt for an integration test with uniform saturated soil and POP as 0.4 * sig'_yy on the bottom.

**Comment by WPK4FEM** [comment]
Published branch with preparations for review.

**Comment by WPK4FEM** [comment]
Jonathan has added tests comparing the POP implementation to Plaxis.

Beste Anne en Richard,
Om gedachten op een rij te krijgen en te zien hoe we het K0 POP item naar de done kolom kunenn krijgen ...
Nog op te pakken dingen uit de reviews:
1: formatting .json files, meer op 1 regel i.v.m. leesbaarheid en overzicht. Vraag: specifiek hier met de hand doen of generiek oplossen voor alle projectparameter files.
2: unit testen van de nog niet met unit testen behandelde delen van het K0 proces
3: Alternatief voor de Plaxis res files en Plaxis verwijzingen.
 
Doordravend om het generieke K0 issue te kunnen sluiten:
1: 3D incremental linear elastisch materiaal via de nieuwe policy waarin plane strain al gevat is
2: dat 3D materiaal ook gebruiken met use_standard_procedure en de z richting blokkade voor K0 opheffen
3: 3D integration test toevoegen.
4: bestaande K0 materiaal testen omzetten of weggooien en de oude K0 material laws verwijderen.
 
Ondanks dat er graag aan wil werken lijkt het mij ineffectief om het me alleen te laten doen. Samen of verdeeld doen lijkt me veel effectiever.
 
Groet, WIjtze Pieter

Yesterday Richard has already taken up the formatting and shrinking the comparison with the Plaxis results. Today, we are attempting to unit test the K0 procedure process and the various paths through it.
