### ISSUE TITLE
Error in windows compilation when including the FluidDynamicsApplication 

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#1264]
Error in FluidDynamicsApplication:

10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(38): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(38): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition2D3N> const Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition2D3N::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(38): error C2491: 'Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition2D3N::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(38): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(38): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition2D3N::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(38): error C2491: 'Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition2D3N::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(39): warning C4273: 'Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition2D3N::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(38): note: vea la definición anterior de 'TestFunction'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(146): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(146): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition3D4N> const Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition3D4N::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(146): error C2491: 'Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition3D4N::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(146): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(146): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition3D4N::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(146): error C2491: 'Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition3D4N::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(147): warning C4273: 'Kratos::Testing::TestEmbeddedAusasNavierStokesWallCondition3D4N::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_ausas_navier_stokes_wall_condition.cpp(146): note: vea la definición anterior de 'TestFunction'
10>  test_embedded_navier_stokes_element.cpp
11>  nodal_values_interpolation_process.cpp
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(36): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(36): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestElementEmbeddedNavierStokes2D3N> const Kratos::Testing::TestElementEmbeddedNavierStokes2D3N::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(36): error C2491: 'Kratos::Testing::TestElementEmbeddedNavierStokes2D3N::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(36): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(36): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestElementEmbeddedNavierStokes2D3N::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(36): error C2491: 'Kratos::Testing::TestElementEmbeddedNavierStokes2D3N::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(37): warning C4273: 'Kratos::Testing::TestElementEmbeddedNavierStokes2D3N::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(36): note: vea la definición anterior de 'TestFunction'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(136): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(136): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestElementEmbeddedNavierStokes3D4N> const Kratos::Testing::TestElementEmbeddedNavierStokes3D4N::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(136): error C2491: 'Kratos::Testing::TestElementEmbeddedNavierStokes3D4N::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(136): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(136): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestElementEmbeddedNavierStokes3D4N::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(136): error C2491: 'Kratos::Testing::TestElementEmbeddedNavierStokes3D4N::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(137): warning C4273: 'Kratos::Testing::TestElementEmbeddedNavierStokes3D4N::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_embedded_navier_stokes_element.cpp(136): note: vea la definición anterior de 'TestFunction'
10>  test_fluid_dynamics_constitutive_laws.cpp
11>  Generando código...
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(86): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(86): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestNewtonian2DConstitutiveLaw> const Kratos::Testing::TestNewtonian2DConstitutiveLaw::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(86): error C2491: 'Kratos::Testing::TestNewtonian2DConstitutiveLaw::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(86): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(86): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestNewtonian2DConstitutiveLaw::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(86): error C2491: 'Kratos::Testing::TestNewtonian2DConstitutiveLaw::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(87): warning C4273: 'Kratos::Testing::TestNewtonian2DConstitutiveLaw::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(86): note: vea la definición anterior de 'TestFunction'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(142): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(142): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestNewtonian3DConstitutiveLaw> const Kratos::Testing::TestNewtonian3DConstitutiveLaw::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(142): error C2491: 'Kratos::Testing::TestNewtonian3DConstitutiveLaw::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(142): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(142): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestNewtonian3DConstitutiveLaw::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(142): error C2491: 'Kratos::Testing::TestNewtonian3DConstitutiveLaw::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(143): warning C4273: 'Kratos::Testing::TestNewtonian3DConstitutiveLaw::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(142): note: vea la definición anterior de 'TestFunction'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(207): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(207): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestEuler2DConstitutiveLaw> const Kratos::Testing::TestEuler2DConstitutiveLaw::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(207): error C2491: 'Kratos::Testing::TestEuler2DConstitutiveLaw::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(207): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(207): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestEuler2DConstitutiveLaw::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(207): error C2491: 'Kratos::Testing::TestEuler2DConstitutiveLaw::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(208): warning C4273: 'Kratos::Testing::TestEuler2DConstitutiveLaw::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(207): note: vea la definición anterior de 'TestFunction'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(259): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(259): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestEuler3DConstitutiveLaw> const Kratos::Testing::TestEuler3DConstitutiveLaw::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(259): error C2491: 'Kratos::Testing::TestEuler3DConstitutiveLaw::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(259): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(259): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestEuler3DConstitutiveLaw::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(259): error C2491: 'Kratos::Testing::TestEuler3DConstitutiveLaw::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(260): warning C4273: 'Kratos::Testing::TestEuler3DConstitutiveLaw::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_fluid_dynamics_constitutive_laws.cpp(259): note: vea la definición anterior de 'TestFunction'
10>  test_navier_stokes_symbolic_element.cpp
9>     Creando biblioteca C:/Kratos/cmake_build/applications/FSIapplication/Release/KratosFSIApplication.lib y objeto C:/Kratos/cmake_build/applications/FSIapplication/Release/KratosFSIApplication.exp
9>  KratosFSIApplication.vcxproj -> C:\Kratos\cmake_build\applications\FSIapplication\Release\KratosFSIApplication.pyd
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(37): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(37): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestElementNavierStokes2D3N> const Kratos::Testing::TestElementNavierStokes2D3N::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(37): error C2491: 'Kratos::Testing::TestElementNavierStokes2D3N::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(37): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(37): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestElementNavierStokes2D3N::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(37): error C2491: 'Kratos::Testing::TestElementNavierStokes2D3N::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(38): warning C4273: 'Kratos::Testing::TestElementNavierStokes2D3N::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(37): note: vea la definición anterior de 'TestFunction'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(168): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(168): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestElementNavierStokes2D3NStationary> const Kratos::Testing::TestElementNavierStokes2D3NStationary::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(168): error C2491: 'Kratos::Testing::TestElementNavierStokes2D3NStationary::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(168): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(168): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestElementNavierStokes2D3NStationary::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(168): error C2491: 'Kratos::Testing::TestElementNavierStokes2D3NStationary::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(169): warning C4273: 'Kratos::Testing::TestElementNavierStokes2D3NStationary::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(168): note: vea la definición anterior de 'TestFunction'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(270): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(270): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestElementNavierStokes3D4N> const Kratos::Testing::TestElementNavierStokes3D4N::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(270): error C2491: 'Kratos::Testing::TestElementNavierStokes3D4N::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(270): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(270): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestElementNavierStokes3D4N::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(270): error C2491: 'Kratos::Testing::TestElementNavierStokes3D4N::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(271): warning C4273: 'Kratos::Testing::TestElementNavierStokes3D4N::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(270): note: vea la definición anterior de 'TestFunction'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(401): warning C4273: 'mDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(401): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::RegisterThisTest<Kratos::Testing::TestElementNavierStokes3D4NStationary> const Kratos::Testing::TestElementNavierStokes3D4NStationary::mDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(401): error C2491: 'Kratos::Testing::TestElementNavierStokes3D4NStationary::mDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(401): warning C4273: 'mAnotherDummy': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(401): note: vea la definición anterior de 'private: static Kratos::Testing::Internals::AddThisTestToTestSuite const Kratos::Testing::TestElementNavierStokes3D4NStationary::mAnotherDummy'
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(401): error C2491: 'Kratos::Testing::TestElementNavierStokes3D4NStationary::mAnotherDummy': definición de miembro de datos estático dllimport no permitida
10>C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(402): warning C4273: 'Kratos::Testing::TestElementNavierStokes3D4NStationary::TestFunction': vinculación de DLL incoherente
10>  C:\Kratos\applications\FluidDynamicsApplication\tests\cpp_tests\test_navier_stokes_symbolic_element.cpp(401): note: vea la definición anterior de 'TestFunction'

**Comment by josep-m-carbonell** [comment]
![error_fluiddynamicsapp](https://user-images.githubusercontent.com/23210788/34713853-ced9c9a0-f527-11e7-8328-f23841e34d04.png)

**Comment by jginternational** [comment]
@KratosMultiphysics/fluid-dynamics

**Comment by roigcarlo** [comment]
Solved in #1272
