### ISSUE TITLE
[Structural] Strain energy of shell -like elements is not defined?

### ISSUE THREAD

**Issue by takeshimg92** [KratosMultiphysics/Kratos#12692]
**Description**
For an application which involves calculation of compliance, I am trying to output the strain energy of a shell-like element. For usual solid elements, it is enough to add "STRAIN_ENERGY" to the VTK outputs in the gaussian point variables; for shells, I have tried 

- STRAIN_ENERGY
- SHELL_ELEMENT_SHEAR_ENERGY
- SHELL_ELEMENT_BENDING_ENERGY
- SHELL_ELEMENT_MEMBRANE_ENERGY

All of these come out as fields with all entries equal to zero. I would like to understand if I am missing something.

As an example, I did this for a mesh with 4000 elements. Elements are ShellThinElement3D3N, and I apply a point load to a single node set as a PointLoadCondition3D1N. The resulting displacement field matches theoretical results, so I am confident in the physics.

**Scope**
- StructuralMechanicsApplication

**Comment by rubenzorrilla** [comment]
I had a quick look and it seems that it is not implemented. The corresponding calculation should be implemented in the `Calculate` function. A reference implementation can be found in here https://github.com/KratosMultiphysics/Kratos/blob/0e6dd1bb1ecd1fc322ebf7a8eca8d02df8e521f5/applications/StructuralMechanicsApplication/custom_elements/membrane_element.cpp#L1052

**Comment by takeshimg92** [comment]
Thank you! Would it be enough to add this to the ShellElement and rebuilld the StructuralMechanicsApplication?

**Comment by RiccardoRossi** [comment]
Yes, it should be enough
