### ISSUE TITLE
Update the GidPost Library due to Licensing issues

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#127]
Talking with @RiccardoRossi , we realized that there's no license file in the GidPost library. This might be problematic.
Actually, whenever we want we can download the new version from http://www.gidhome.com/category/gid-plus/tools  and replace the old GidPost. The new version contains a license file that allows everything we need.

**Comment by loumalouomega** [comment]
I was updating some says ago the license of GiD because of a bug, that after that was corrected removing the assert, there are some modifications that are needed in the new GidPost, because it exists the cluster element.

Additionally some problem I had with the new version, having a `core` error.

**Comment by loumalouomega** [comment]
I pushed my branch ( the one related with the new GiD IO), if you want to take a look, it is called `feature-solving-gid-io-debug-poblem`

**Comment by loumalouomega** [comment]
Maybe now is outdated, but at least you need less things to modify

**Comment by RiccardoRossi** [comment]
@loumalouomega does it still fail with the latest fix by @jcotela ?

**Comment by loumalouomega** [comment]
@RiccardoRossi No, it is fixed

**Comment by RiccardoRossi** [comment]
i am a bit lost :-(

@jcotela, your test is now in the master branch? did u merge it with mine?

if so, @loumalouomega could u try if the tests pass with the new library?

cheers
Riccardo

**Comment by loumalouomega** [comment]
The test passes in my computer

**Comment by jcotela** [comment]
@RiccardoRossi My test is in your branch, as you requested (but I committed it as skipped by default, so please remove the skip decorator from tests_gid_io.py in your branch).
The fix (which was in #133 ) has already been merged into the master branch.

**Comment by pooyan-dadvand** [comment]
I don't see how the assert discussion is related to the License?

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand i asked to Vicente to see if updating to the new gidpost library it works correctly. in another issue @maceligueta raised the point that the gidpost did not have the license file in place.

@jcotela fine, I think that Vicente ported the changes from my branch to this one.

**Comment by maceligueta** [comment]
@RiccardoRossi : this is the issue. Not another one.

**Comment by loumalouomega** [comment]
@RiccardoRossi The new library is not working yet, maybe is a good idea to focus in the License

**Comment by RiccardoRossi** [comment]
@Vicente,
i am lost. Didn't you say that it was working?

**Comment by loumalouomega** [comment]
@RiccardoRossi No, is not working, more modifications are needed

**Comment by pooyan-dadvand** [comment]
I would suggest to return to the license problem and continue the assert discussion in the corresponding issue. (BTW I can not find the other issue. Is it closed?)

**Comment by maceligueta** [comment]
For those of us who did not work with different versions of the GidPost library, can you explain what are the problems of just overwriting the old GidPost with the new GidPost? I mean, doing this would solve the license problem, but I am not aware of the problems that would appear.

**Comment by RiccardoRossi** [comment]
the point is that the current version of GiDPost is not containing a license file. We asked to Abel Coll (the GiD project leader) and he said that it was by mistake and that they would put the explicit license file in the next version of gidpost.

unfortunately @loumalouomega  tried out the latest version of the library and it appeared not to be working. This is the status as of today...

**Comment by maceligueta** [comment]
It is clear that we have to work on this. Now, what is the priority of this issue?

**Comment by pooyan-dadvand** [comment]
Maybe another solution is to ask them add their license to the current version in repo until they fix the problem with the new GiDpost library.

**Comment by RiccardoRossi** [comment]
@loumalouomega was this done finally?

on a side note, i think we should get a statement by the GiD team telling officially that we can use the library

**Comment by loumalouomega** [comment]
I don't remember...
