### ISSUE TITLE
Element-wise physical attributes requires element-wise Properties?

### ISSUE THREAD

**Issue by takeshimg92** [KratosMultiphysics/Kratos#12729]
**Description**
I have an application where my physical parameters (Young's modulus, density, etc) are specified as fields. I have a VTU to MDPA converter that allows me to map each Element/Condition to a field value.

I want to write a `ModifyInitialProperties` so that I can change the properties element-wise. However, the code below won't work unless I define a different `Property` object for each and every element:
```
model_part = self._GetSolver().GetComputingModelPart()
for i, element in enumerate(model_part.Elements):
     element.Properties.SetValue(KM.YOUNG_MODULUS, new_modulus[i])
```
Since, originally, all elements point to the same `Properties`, each pass alters the global Young modulus.

Also, using `element.SetValue`/`element.GetValue` doesn't work since the properties are not changed, although it achieves to store different values for each element.

Is the only option to first define each element with its own Property object, or is there something closer to `SetSolutionStepValue` which I can use Element-wise?

**Comment by loumalouomega** [comment]
Hello, that depends of which elemet are you using. But yes, generally properties are shared, so if you want to have element independent properties you should define as many properties as elements. An alternative is to implement your own element that retrieves properties from the DataValueContainer

**Comment by takeshimg92** [comment]
I see, are there examples of elements which have independent properties?

**Comment by philbucher** [comment]
I had the same problem some time ago and solved it via specifying a different property per element, but this has quite some overhead

In the meantime `Accessor` was added by @AlejandroCornejo which should help you to customize to the behavior you need. This does require some C++ implementation though, depending on how the input looks
AFAIK only table inputs are currently available

**Comment by AlejandroCornejo** [comment]
hi! @philbucher is right, we added the `Accessor` class to be able to modify material properties according to any table or input that you'd like. (e.g. according to Temperature)

Another option is to make use of the `element.HasValue(--)` and `element.GetValue(YOUNG_MODULUS_FACTOR)` to modify a predifined set of unique material properties. Since the `Properties` is a heavy class, it is advised to create a unique set of them.

**Comment by takeshimg92** [comment]
Thank you all for the responses.
I would like to stay within the Python interface. I essentially have a table with element id's as inputs, and Young's modulus as outputs.

Do you have a minimum working reference for using the `Accessor` for specifying element-wise attributions? I saw on [this issue](https://github.com/KratosMultiphysics/Kratos/issues/11214) about how Accessors work mapping values from a table to another, but I am confused about the syntax to make it element-wise.

**Comment by takeshimg92** [comment]
>Another option is to make use of the element.HasValue(--) and element.GetValue(YOUNG_MODULUS_FACTOR) to modify a predifined set of unique material properties. Since the Properties is a heavy class, it is advised to create a unique set of them.
@AlejandroCornejo could you perhaps clarify this a bit further?

**Comment by AlejandroCornejo** [comment]
> > Another option is to make use of the element.HasValue(--) and element.GetValue(YOUNG_MODULUS_FACTOR) to modify a predifined set of unique material properties. Since the Properties is a heavy class, it is advised to create a unique set of them.
> 
> @AlejandroCornejo could you perhaps clarify this a bit further?

Hi! yes, let me develop a bit.

Let's say that you define a unique set of materials properties `r_props`. In those `r_props` you have defined a global `YOUNG_MODULUS`.

Then, element-wise you want to modify that global value by a customized one. Let's also say that you know _a priori_ the factor that relates the custom and the global value and we call it `YOUNG_MODULUS_CUSTOM_FACTOR`.

Then, within each element/constitutive law you could retrieve modified custom element-wise `YOUNG_MODULUS` as:

~~~c++
double custom_variable;
if elem.HasValue(YOUNG_MODULUS_CUSTOM_FACTOR) {
    custom_variable = r_props[YOUNG_MODULUS] * elem.GetValue(YOUNG_MODULUS_CUSTOM_FACTOR) // someone is setting this in advance...
} else {
    custom_variable = r_props[YOUNG_MODULUS]
}
~~~

**Comment by AlejandroCornejo** [comment]
The other option, depending on the custom way of retrieving info, we can take advantage of the `Accessor`. Any `constitutive_law` has a null pointer by default to an `Accessor`. If you fill this pointer by your own `Accessor`, you could seeamlessly integrate any method to modify material properties at constitutive level.

**Comment by takeshimg92** [comment]
Thank you @AlejandroCornejo!
I am considering the first option, I just want to make sure I understand the `Accessor` one as well. As I mention in my answer above, I:
* Add an `TEMPERATURE_vs_YOUNG_MODULUS` table and a `"accessor_type"  : "table_accessor"` to my material JSON, which is of constitutive law `LinearElastic3DLaw`
* During the analysis execution, in `ModifyInitialProperties`, I try to set by hand a temperature using `SetSolutionStepValue`. My expectation was that it would naturally change the Young's modulus.
Does it not work because of some misunderstanding of mine on how this works, or is it because I have not filled the pointer in the `LinearElastic3DLaw` law?

**Comment by sunethwarna** [comment]
Hi, I am coming little bit late, but we also have the same problem in the OptimizationApplication, there, we made the following utility to create element wise properties. You can find the utility in the following link.

https://github.com/KratosMultiphysics/Kratos/blob/279f0a6c5c42552f36d29ca0172e329d946301ed/applications/OptimizationApplication/custom_utilities/optimization_utils.cpp#L90-L116

Python use case:
https://github.com/KratosMultiphysics/Kratos/blob/279f0a6c5c42552f36d29ca0172e329d946301ed/applications/OptimizationApplication/python_scripts/controls/material/material_properties_control.py#L55-L58

**Comment by AlejandroCornejo** [comment]
> Thank you @AlejandroCornejo! I am considering the first option, I just want to make sure I understand the `Accessor` one as well. As I mention in my answer above, I:
> 
> * Add an `TEMPERATURE_vs_YOUNG_MODULUS` table and a `"accessor_type"  : "table_accessor"` to my material JSON, which is of constitutive law `LinearElastic3DLaw`
> * During the analysis execution, in `ModifyInitialProperties`, I try to set by hand a temperature using `SetSolutionStepValue`. My expectation was that it would naturally change the Young's modulus.
> 
> Does it not work because of some misunderstanding of mine on how this works, or is it because I have not filled the pointer in the `LinearElastic3DLaw` law?

Hi! You did the right procedure. It is not working because the `LinearElastic3DLaw` is not adapted to do that. See `applications\ConstitutiveLawsApplication\custom_constitutive\thermal\small_strains\elastic\thermal_elastic_isotropic_3d.cpp` to check how we access to properties through the `Accessors` I did not adapted the elastic one since it adds an overhead.

I use: `const double E  = r_material_properties.GetValue(YOUNG_MODULUS, r_geom, r_N, r_process_info);` which passes through th accessor.

**Comment by AlejandroCornejo** [comment]
@takeshimg92  feel free to close the issue once it is solved :)

**Comment by takeshimg92** [comment]
I confirm that adapting the elastic isotropic 3d law [here](https://github.com/KratosMultiphysics/Kratos/blob/279f0a6c5c42552f36d29ca0172e329d946301ed/applications/StructuralMechanicsApplication/custom_constitutive/elastic_isotropic_3d.cpp#L362-L389) to be equal to that of the [thermoelastic constitutive law](https://github.com/KratosMultiphysics/Kratos/blob/279f0a6c5c42552f36d29ca0172e329d946301ed/applications/ConstitutiveLawsApplication/custom_constitutive/thermal/small_strains/elastic/thermal_elastic_isotropic_3d.cpp#L131-L162), together with setting a temperature by hand inside the `ModifyInitialProperties` method indeed solves the problem. 

Thank you all for the help, I am closing the issue.
