### ISSUE TITLE
Parameters RemoveValue does not throw if Value is not existing

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1274]
Hi @KratosMultiphysics/technical-committee 
I noticed that the `Parameters` object does not throw if one wants to remove a value that does not exist. I am not sure if this is the desired behavior, just wanted to point it out.
I checked the implementation, it could be easily fixed.
~~~py
import KratosMultiphysics
params = KratosMultiphysics.Parameters("{}")
params.RemoveValue("not_existing_value") # this does NOT throw an error
~~~

**Comment by RiccardoRossi** [comment]
are u suggesting to issue a warning?
We (@KratosMultiphysics/technical-committee) are not convinced that it is a good idea to throw. Would you have a good reason for actually doing it?

**Comment by philbucher** [comment]
My thought was to first check if the value I want to remove exists (`xxx.Has("Value")`) and remove it only then. In this case the `RemoveValue()` could throw if it is called without the check.

I am fine leaving it as is, just wanted to point it out / know if this is intended. Now I can design my code accordingly.

Thx for your reply
