### ISSUE TITLE
[FSI] Missing modelers compatibility

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#12747]
**Description**
Working on the GiD Problemtype, migrating the FSI app to use geometries. I've noticed that the modelers are not being loaded in FSI application

**To Reproduce**
In this case wich may not be definitive.
[fsi.gid.zip](https://github.com/user-attachments/files/17345928/fsi.gid.zip)

when running with the master branch, I can see in the log that the model parts are empty: 

🖼️ 
![image](https://github.com/user-attachments/assets/dc092384-cbbd-474b-836e-4bca31f712e2)

🖼️ 

Just by adding this lines to fsi_analysis.py it started working:

🖼️ 
![image](https://github.com/user-attachments/assets/7e279b35-8a20-4277-9af4-4a0da0372c66)
🖼️ 

Notice that I don't know if this should be the solution since I dont know about this app, just copied from [analysis_stage.py](https://github.com/KratosMultiphysics/Kratos/blob/bcfe53d8304090ea0458561b06ac309af01a0b7b/kratos/python_scripts/analysis_stage.py#L77)
I don't know if the code must be replicated here, or just call, or derive from... this is just a patch in my code so I can run now, not a PR.

Just to let you know @rubenzorrilla

**Comment by rubenzorrilla** [comment]
Hi @jginternational. You're right. Actually I came across this some weeks ago (but remember to push the changes). At first glance, I agree with the solution. Nevertheless, let me have a look to it (maybe we can take the base class implementation, note that the `FSIAnalysis` implementation is a bit "old fashioned").
