### ISSUE TITLE
KRATOS WORKSHOP - November 6,7,8 2024 - REGISTRATION IS OPEN!

### ISSUE THREAD

**Issue by ncrescenzio** [KratosMultiphysics/Kratos#12757]
Dear all,

We are glad to announce that the information and detailed program of the  <b>VII KRATOS WORKSHOP</b> that will be held in <b>Padova (Italy)</b>, on <b>November 6,7 and 8, 2024</b> are now online.

Please, visit the following web page for information and registration:
https://kratosmultiphysics.github.io/Kratos/pages/Kratos/Workshops/2024_UNIPD/Event/index.html

<b>The attendance is free but registration is required</b> (deadline for registration October 29, 2024).

Important info:
* <ins>KRATOS WORKSHOP</ins> on November 6 and 7, 2024
* <ins>KRATOS COURSE</ins> on November 8, 2024

<b>VENUE:</b> <a href="https://www.google.com/maps/place/Dipartimento+di+Matematica+%22Tullio+Levi-Civita%22+-+DM/@45.4111797,11.8849949,17z/data=!3m1!4b1!4m6!3m5!1s0x477eda58b5bcbb81:0xfe272ff292c152dd!8m2!3d45.4111797!4d11.8875698!16s%2Fg%2F1ptxtd80v?entry=ttu&g_ep=EgoyMDI0MTAxMy4wIKXMDSoASAFQAw%3D%3D">Department of Mathematics "Tullio Levi Civita", University of Padova, Via Trieste, 63, 35131 Padova (PD), Italy.</a>

<b>ROOM:</b> <a href="https://raw.githubusercontent.com/ncrescenzio/km2024/refs/heads/main/tex/info.pdf#page=4">Yellow Room, Library floor -1 (entrance from stair B).</a>

---

@KratosMultiphysics/all @KratosMultiphysics/altair @KratosMultiphysics/cosimulation @KratosMultiphysics/dem @KratosMultiphysics/fluid-dynamics @KratosMultiphysics/geomechanics @KratosMultiphysics/meshmoving @KratosMultiphysics/mpm @KratosMultiphysics/optimization @KratosMultiphysics/pfem @KratosMultiphysics/poromechanics @KratosMultiphysics/rom @KratosMultiphysics/structural-mechanics @KratosMultiphysics/students

**Comment by loumalouomega** [comment]
This is still pinned, we can unpin
