### ISSUE TITLE
[GeoMechanicsApplication] Create a constitutive law with the identified erosion mechanism

### ISSUE THREAD

**Issue by indigocoral** [KratosMultiphysics/Kratos#12774]
This is a sub-issue of https://github.com/orgs/Deltares/projects/55/views/1?pane=issue&itemId=66823242&issue=KratosMultiphysics%7CKratos%7C12441

the permeability for a pipe is defined as (pipe_height^3)/12 
as the pipe_height is written by the erosion mechanism, permeability needs to be evaluated every time before setup of LHS and RHS.

Create pipe constitutive law ....

**Comment by avdg81** [comment]
This functionality is currently part of both piping element implementations (i.e. including the new line element). Therefore, there is no need to develop this.
