### ISSUE TITLE
[GeoMechanicsApplication] Convert 3D test case from DGFlow format to Kratos

### ISSUE THREAD

**Issue by mcgicjn2** [KratosMultiphysics/Kratos#12797]
This is a sub-issue of https://github.com/KratosMultiphysics/Kratos/issues/12441

Convert the 3D test case provided by Lisa, to a Kratos test case.

**Comment by mcgicjn2** [comment]
[3DPipeCase.zip](https://github.com/user-attachments/files/17748776/3DPipeCase.zip)

Added this is the current test case.

The expected result 
[results.txt](https://github.com/user-attachments/files/17748811/results.txt)

Note that this calculation runs as a transient case so some extraction of data at the time is required. The time stepping might need adjusting

**Comment by WPK4FEM** [comment]
Test has been ran successfully on the branch for the 3D piping element by Richard. Is now added to the validation testsuite on that branch.

**Comment by rfaasse** [comment]
Closing this as we have the test case in our suite
