### ISSUE TITLE
model_part.GetElement(Id) silently creates new elements

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#128]
If I call `model_part.GetElement(Id)` with non-existing Id, it inserts a new element in the model part and returns it without throwing an error. This is most certainly not what the programmer intended since for creating elements one should use `model_part.CreateNewElement("SomeElement",` NewId, ...)`.

I would suggest changing 

ElementType& Mesh::GetElement(IndexType ElementId)
 {
        return (*mpElements)[ElementId];
 }

to something like

ElementType& Mesh::GetElement(IndexType ElementId)
 {
        auto i = mpElements->find(ElementId);
        assert(i != mpElements->end());
        return *i;
 }

with similar changes to pGetElement, pGetNode, GetNode, pGetCondition, GetCondition.

@pooyan is this possible?

**Comment by loumalouomega** [comment]
Yes, because when the Id doesn't exist it calls the parent class, and then the constructor

**Comment by RiccardoRossi** [comment]
just to say that i personally agree.

however i would suggest throwing a KratosError instead of using an assert.

@msandre why don't you make a pull request with this change? This way we could see if the tests pass ...

**Comment by pooyan-dadvand** [comment]
I have added my comments to PR #142

**Comment by msandre** [comment]
Thanks everyone for the comments. I will close this thread since the discussion has moved to #142 .
