### ISSUE TITLE
[GeoMechanicsApplication] Calculate backwards erosion piping in 3D

### ISSUE THREAD

**Issue by indigocoral** [KratosMultiphysics/Kratos#12803]
A user would like to calculate backwards erosion piping in 3D

Background
The current implementation of backwards erosion piping inherits from 2D interface elements, this element type therefore limits the calculation to 2D. If this element is moved to be based on 1D line elements, then the calculation is more easily facilitates in 2D and 3D.

A branch currently exists ([geo/pipe](https://github.com/KratosMultiphysics/Kratos/tree/geo/pipe)) to investigate this change, however it is recommended that we start again once to neccessary changes are required.

**Comment by WPK4FEM** [comment]
PIPE_WIDTH_FACTOR * PIPE_HEIGHT^4 /12

**Comment by mcgicjn2** [comment]
![Image](https://github.com/user-attachments/assets/d2c457b8-05ee-411b-a746-b893d06486be)

pipe width factor = w/a

**Comment by indigocoral** [comment]
This issue is a duplicate of https://github.com/KratosMultiphysics/Kratos/issues/12824, therefore we close it.
