### ISSUE TITLE
[GeoMechanicsApplication] Create 3D line piping element 3D2N

### ISSUE THREAD

**Issue by WPK4FEM** [KratosMultiphysics/Kratos#12824]
Slight variation on GeoSteadyStatePwPipingElement2D2N towards GeoSteadyStatePwPipingElement3D2N

with introduction
- pipe_width_factor ( 1 for 2D, otherwise for 3D )
- power 4 in longitudinal permeability of open pipe.
- publish the new element 
- unit test
- To be able to run [the converted test](https://github.com/KratosMultiphysics/Kratos/issues/12797)

**Comment by indigocoral** [comment]
Refers to: https://github.com/KratosMultiphysics/Kratos/issues/12803
