### ISSUE TITLE
how can i transform triangle meshes to nurbs surface/volume?

### ISSUE THREAD

**Issue by Yihao-Shi** [KratosMultiphysics/Kratos#12838]
Can I use kratos to transform complex triangle meshes to nurbs surface/volume? Or is there any open-sourced software for me to model the nurbs volume by triangle meshes?

**Comment by rubenzorrilla** [comment]
Up to my knowledge, you cannot do this natively in Kratos. Note that this requires CAD capabilities, which we of course do not provide. Maybe @KratosMultiphysics/nurbs-breps can give you some hints in this regard.

**Comment by Yihao-Shi** [comment]
sorry, the link @KratosMultiphysics/nurbs-breps is 404 and GitHub can not find any repository. Is it located in Kratos/applications/igaApplications. Thank you so much.

**Comment by rickyaristio** [comment]
Hi, I am part of @KratosMultiphysics/nurbs-breps team. I just want to verify the answer. Unfortunately, we cannot this at this moment. 

> Up to my knowledge, you cannot do this natively in Kratos. Note that this requires CAD capabilities, which we of course do not provide. Maybe [@KratosMultiphysics/nurbs-breps](https://github.com/orgs/KratosMultiphysics/teams/nurbs-breps) can give you some hints in this regard.

**Comment by Yihao-Shi** [comment]
thank you
