### ISSUE TITLE
import KratosMultiphysics error

### ISSUE THREAD

**Issue by luaignmeaugoera** [KratosMultiphysics/Kratos#12873]
**Description**
What is happening?

    from KratosMultiphysics import *
  File "D:\Kratos-10.1\kratos-10.1\bin\Release\KratosMultiphysics\__init__.py", line 36, in <module>
    from Kratos import *
ModuleNotFoundError: No module named 'Kratos'

**Scope**
Which areas of Kratos are involved
E.g.
- Compilation
- KratosCore
- FooApplication
- Documentation

**Comment by luaignmeaugoeax** [comment]
on Windows System ;

**Comment by luaignmeaugoeax** [comment]
using Anaconda3 python3.11

**Comment by luaignmeaugoeax** [comment]
i has solve it ;
The Python interpreter used to run the Python files must be consistent with the one used during installation.
