### ISSUE TITLE
Windows build before merge into master

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#1301]
Dear all,

In the last months, the master branch was often not compiling under windows: 
Would it be possible to include a mandatory windows build before a pull request can be merged into master?

**Comment by loumalouomega** [comment]
@roigcarlo Can confirm you that is not a trivial issue, because you can create a VM with GNU/Linux with no cost, but Windows requires to pay a license...

**Comment by roigcarlo** [comment]
Actually we are setting it up through appveyor, but as @loumalouomega says is not as trivial as linux so I cannot give you an ETA

**Comment by armingeiser** [comment]
I see, licensing of windows is something I did not think about. 
But its good to hear that there are plans on solving this somehow.
