### ISSUE TITLE
Error: Zero aggregates found

### ISSUE THREAD

**Issue by sarti-luca** [KratosMultiphysics/Kratos#1304]
Dear All,

I'm trying to solve a simple 3D fluid dynamics problem as I've already done. 
This time I get this error and I don't know why.
What am I doing wrong?

Thanks for your help.

![image](https://user-images.githubusercontent.com/35461057/34950921-d8f57cb2-fa14-11e7-95d7-58511d42c5c7.png)

**Comment by rubenzorrilla** [comment]
Hi @sarti-luca ,

Can you attach a .zip file containing the case source file? By the way, have you fixed the pressure in the outlet? (this is a common error when using the fractional step formulation).

**Comment by sarti-luca** [comment]
Hi @rubenzorrilla, yes I fixed the pressure. I tried several times to delete and create the boundary conditions and the last time it worked, even if I didn't change anything.

Thanks.

**Comment by rubenzorrilla** [comment]
This means that we can close the issue?

**Comment by sarti-luca** [comment]
I get the same error again. After having correctly solved the problem, I changed the velocity value and the time step, I recreate the mesh and saved. After 121 steps I get the error.

I attach the zip file.
Thanks
[building_2.gid.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/1633086/building_2.gid.tar.gz)

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/fluid-dynamics is anyone following the issue?

**Comment by jcotela** [comment]
@sarti-luca Sorry for the delay in answering, this issue fell through our to-do list...
Anyway, from looking into the solution, there seems to be something wrong with the boundary conditions in your model:

![screenshot from 2018-01-22 13-03-41](https://user-images.githubusercontent.com/5071546/35219999-fad3ba82-ff74-11e7-920c-b0c8d210c645.png)

You need to fix the Y and Z velocities on the top lines to avoid the non-physical growth of the velocity on the corners of your domain. I suspect this comes from using two different slip condition groups in GiD, you can try either fixing them manually on those lines or creating a single slip group comprising all "sides" of the domain.

**Comment by rubenzorrilla** [comment]
Can you try to use a unique group for all the slip walls?

**Comment by sarti-luca** [comment]
@rubenzorrilla, @jcotela thanks, I'll use an unique group and I'll pay attention on this. 
I'll let you know if it still does not work.

**Comment by RiccardoRossi** [comment]
closing as it seems solved. please reponen as needed
