### ISSUE TITLE
Kratos error in windows at the end of the script

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#1310]
In Windows (7 and 10) Kratus currently throws an error after the script has finished.

![image](https://user-images.githubusercontent.com/25903585/34988062-a5dff178-fabd-11e7-819f-5ab86aceca48.png)

Unfortunately I have only a german windwos: The message says: "runkratos.exe is not working anymore"

The results and everything look fine, it seems that the programm is just not exiting properly.

**Comment by jcotela** [comment]
Hi @armingeiser we are aware of this issue (it happens in linux too, but apparently not on all systems). We are working on this. If you can get a detailed report on this error (the call stack when this falls or anything else that visual studio can tell you), we would be grateful if you could send it, since it will help us debug the issue.

**Comment by armingeiser** [comment]
Maybe this already helps? I have no experience with such things...

Unhandled exception at 0x000000005DE41AC6 (python34.dll) in runkratos.exe: 0xC0000005: Access violation writing location 0x000000000000009C.

If there is a handler for this exception, the program may be safely continued.

**Comment by pooyan-dadvand** [comment]
This will be addressed in fix-issue-1199 branch. Would you please confirm me if it works for you?

**Comment by maceligueta** [comment]
In linux, the problem looks solved thanks to PR #1337 ! Thanks guys. @armingeiser , could you try it in Windows for a final confirmation?

**Comment by armingeiser** [comment]
Also in Windows it solves the issue. Thanks!
PR #1322 is needed in order to make it compile, but that one is already merged into master.
