### ISSUE TITLE
MKLSolversApplication

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#1316]
I wanted to open a discussion about the MKLSolverApplication. As far as I know, it is currently not working. Since the MKLPardiso solvers are included in the EigenSolversApplication now, I think we might discuss what should be done with the MKLSolversApplication.

**Comment by loumalouomega** [comment]
I tried to use the last version of the MKL libraries, but it was not
possible to me to compile it. We can think about update it, but I know is a
lot of work.

**Comment by AndreasWinterstein** [comment]
The question is, if this is necessary/worth to do it, if we can do it by the EigenSolversApplication.

**Comment by loumalouomega** [comment]
Well, in that case I think @pooyan-dadvand  and @RiccardoRossi can contribute more to the discussion than me

**Comment by RiccardoRossi** [comment]
Hi Andreas, Philip,
       the only thing is that this way we NEED eigen if we want to use MKL. Anyway we already clarified that the Eigen license allows it, so it is not a strong reason, also i don't use Pardiso since years.

Having said this, @pablobecker, i know that some of you guys are using the Pardiso. Could u find out if it would affect the team if we take out the MKLApplication?

cheers
Riccardo

**Comment by pooyan-dadvand** [comment]
ping @pablobecker

**Comment by AndreasWinterstein** [comment]
ping @pablobecker

**Comment by RiccardoRossi** [comment]
@pablobecker, i know you contacted your colleagues. Since as i understand they are not getting feedback, we'll proceed from this if we get no feedback until the 9th of february

**Comment by pablobecker** [comment]
Ok

**Comment by philbucher** [comment]
@RiccardoRossi do we go ahead and remove it?

I can make the PR

**Comment by pablobecker** [comment]
please go ahead
