### ISSUE TITLE
Side effect evaluation warning

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1321]
For quite some time we had to live with the 
warning: expression with side effects will be evaluated despite being used as an operand to 'typeid' in various places of model_part_io.cpp.

Some proposals have been made but none of them has made it up to the master. Last suggestion is to use `std::is_same instead` of using `std::type_index(typeid())`

@pooyan-dadvand You suggested that the first time so I assume you thumbs up. I also like it.
@loumalouomega The blame points to you as the author of the code. Is this a viable alternative or you need the current implementation by some reason? I don't quite understand the code so I cannot Judge.

If you both agree I will make the corrections once again. Hope this time we can merge them.

**Comment by loumalouomega** [comment]
It was me, I admit it, no one complained until now

**Comment by roigcarlo** [comment]
Yep I am the only one compiling with clang :D. But can we change it? is `std::is_same` ok?

**Comment by loumalouomega** [comment]
@roigcarlo I did a commit, is this what you mean?

**Comment by roigcarlo** [comment]
yep, basically that. Let me check if it compiles with clang

**Comment by roigcarlo** [comment]
(i can't today)

**Comment by roigcarlo** [comment]
Closed via #1327
