### ISSUE TITLE
please change boost::shared_ptr --> Kratos::shared_ptr 

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1328]
Hi All,

we recently introduced a 

Kratos::shared_ptr 
Kratos::make_shared

as alias to boost::shared_ptr and boost::make_shared

the rationale is to be able to switch to the c++11 counterparts at some point  (rather sooner than later) so to reduce our dependency on boost.

Doing this simply requires searching for boost::shared_ptr and replacing it by Kratos::shared_ptr
(same for boost::make_shared -> Kratos::make_shared)

We (@KratosMultiphysics/technical-committee) thought that this is best done by everyone in his own application, so to avoid multiple conflicts with the open branches. For this reason i would be asking to everyone to take care of making the relevant changes. Please note that at some point, not using the Kratos version WILL introduce a breakage in the code, so please take care of doing it in the near future

**Comment by jcotela** [comment]
Done for the FluidDynamicsApplication in PR #1330

**Comment by loumalouomega** [comment]
Done

**Comment by maceligueta** [comment]
Just referencing everyone to make them aware of this: @KratosMultiphysics

**Comment by rubenzorrilla** [comment]
Done in the FSI application.

**Comment by philbucher** [comment]
Done in StructuralMechanicsApplication: #1395

**Comment by loumalouomega** [comment]
Done centuries ago in #1331

**Comment by maceligueta** [comment]
Done in DEM and SwimmingDEM in #1342 .

**Comment by pooyan-dadvand** [comment]
Also done in the core in #1375

**Comment by maceligueta** [comment]
I just noted that we need to replace other operations, like, 'boost::move' in case that someone has it (I do). We need another PR for this, I guess, @roigcarlo 
Also, in case you have pointer casting, change from boost:: to Kratos:: as well!

**Comment by loumalouomega** [comment]
Can anyone approve me my PR?, I am quite sure this will provoke trillions of conflicts

**Comment by RiccardoRossi** [comment]
@maceligueta can u use std::move instead? that should be guaranteed to work

**Comment by RiccardoRossi** [comment]
@ipouplana can you port the PoroMechanicsApplication?

**Comment by ipouplana** [comment]
I'll do it ASAP

**Comment by ipouplana** [comment]
I just replaced it for the PoromechanicsApplication and the DamApplication in #1516

**Comment by RiccardoRossi** [comment]
closing as i think this was largely done
