### ISSUE TITLE
Some problems adding Tetgen

### ISSUE THREAD

**Issue by juliobarna** [KratosMultiphysics/Kratos#1338]
Dear all, 
I am witring in relation to the compilation Kratos + Tegten in acuario. Having compilated Tetgen(make tetgen) and later added some lines in configure.sh such as

_**-DUSE_TETGEN_NONFREE_TPL=ON 			                                          \
-DTETGEN_INCLUDE_DIR="/home/julio.marti/TETGEN/tetgen1.4.3"          \
-DTETGEN_LIBRARY_DIR="/home/julio.marti/TETGEN/tetgen1.4.3"		          \**_

sh configure.sh gives the following message

**** configuring KratosExternalSolversApplication ****
**** configuring KratosConvectionDiffusionApplication ****
**** configuring KratosMeshingApplication ****
**** configuring KratosFluidDynamicsApplication ****
**** configuring KratosPFEM2Application ****
**** configuring KratosIncompressibleFluidApplication ****
**** configuring KratosRadiationApplication ****
*****************************************************************************-------------******** /home/julio.marti/Kratos/external_libraries/triangle
python libraries to be installed are: /data0/globalfs/opt/python/3.5.1/lib/libpython3.5m.so.1.0
--------------------------------  standard install dir /home/julio.marti/Kratos
installed blas = /usr/lib64/libblas.so.3.4.2
installed lapack = /usr/lib64/liblapack.so.3.4.2/usr/lib64/libblas.so.3.4.2
**_CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
TETGEN_LIBRARIES (ADVANCED)_**
    linked by target "KratosMeshingApplication" in directory /home/julio.marti/Kratos/applications/MeshingApplication

-- Configuring incomplete, errors occurred!
See also "/home/julio.marti/Kratos/cmake_build/CMakeFiles/CMakeOutput.log".
make: *** [cmake_check_build_system] Error 1
[julio.marti@acuario cmake_build]$ 

Does anybody know how to fix this error?
Julio

**Comment by josep-m-carbonell** [comment]
If you include next lines in the configure.sh it must be enough:

-DINCLUDE_TETGEN=ON                                
-DTETGEN_INSTALL_DIR="home/julio.marti/TETGEN/tetgen1.4.3"

**Comment by juliobarna** [comment]
Adding only lines mentioned by josep-m-carbonell, Kratos has compiled.
However when I try to run an example Kratos don't know what TetGenPfemModeler is.

  File "restart.py", line 516, in <module>
    fluid_solverq = frac_step_solverQ.FracStepSolver(Qcomp_model_part,particle_model_part,domain_size)
  File "/home/julio.marti/Kratos/applications/pfem_2_application/python_scripts/frac_step_solverQ.py", line 234, in __init__
    self.Mesher = TetGenPfemModeler()
_**NameError: name 'TetGenPfemModeler' is not defined**_

**Comment by josep-m-carbonell** [comment]
I'm sorry, the previous configuration was for the PfemAplication, I don't know how it works in the pfem_2_application. I guess you need to include the meshing application, where tetgen maybe is configured in another way.

**Comment by josep-m-carbonell** [comment]
Hi @juliobarna  this must be also added, if not the TetGenPfemModeler() of the Meshing application is not exported to python
-DUSE_TETGEN_NONFREE_TPL=ON

**Comment by roigcarlo** [comment]
Tetlib was not compiled. Solved.
