### ISSUE TITLE
Boundary condition versus time with smooth transition

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#1346]
I cannot find in the new version the python file: `impose_vector_value_by_components_over_time_process`
to impose a boundary condition versus the time with specific step behaviour (`"step_type": "smooth"`)
What is the new name of the file or the new way to impose this load?

**Comment by pooyan-dadvand** [comment]
Ping @KratosMultiphysics/structural-mechanics

**Comment by RiccardoRossi** [comment]
Hi @PhilippeBussetta all of the impose_*  processes are gone.

i think that you can do what you need by the function
assign_scalar_variable_process

you can see an example of syntax etc here:
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/test_processes.py

does it do ?

**Comment by RiccardoRossi** [comment]
closing as inactive. Reopen if you need

**Comment by PhilippeBussetta** [comment]
Hi @RiccardoRossi , 
Yes, I saw the assign_vector* assign_scalar* python functions but I don’t understand how I can impose a complex loading (e.g. piecewise linear).
In the assign function the loading depends of the time and the space position but we lost the capacity of piecewise linear loading with smooth transition.
The problem with the intervals of different process is the transition phase.
We can reused the old loading function or add integration of more complex function (e.g. python functions)?

**Comment by RiccardoRossi** [comment]
Hi @PhilippeBussetta,
     maybe i simply don't understand what is the behaviour that you are missing. Could you say how was the old input so that maybe i can help you in determining the new one?

the point is that you can assign a function of time. That definitely allows you to ramp it up smoothly by prescribing a smooth function. 
An alternative would be to use table input (which i think is not implemented through the current interface). We could definitely push that too...

**Comment by PhilippeBussetta** [comment]
I would like:
linear loading t: 0-> t1
constant loading t: t1->t2
With the previous version it was posible to add smooth transition between the linear part and the constant one.

**Comment by PhilippeBussetta** [comment]
The loading could be enhanced with the possibility to add a python function as well as “PythonOneParameterFunction”
or adding some feature of the old version as well as the possibility to add smooth function on loading driven by vector of value and vector of time

**Comment by RiccardoRossi** [comment]
Hi @PhilippeBussetta, the point is that i would say this is already possible as of today.

let's suppose for example that you want to prescribe the pressure on the nodes, in a very general way.

you could define a process as

            {
                        "python_module"   : "assign_scalar_variable_process",
                        "kratos_module" : "KratosMultiphysics",
                        "process_name"          : "AssignScalarVariableProcess",
                        "Parameters"            : {
                            "model_part_name" : "Main",
                            "variable_name"   : "PRESSURE",
                            "interval"        : [0.0, 10.0],
                            "constrained"     : false,
                            "value"      : "x+100.0*y*t**2",
                            "local_axes"               :{
                                "origin" : [10.0, 0.0, 0.0],
                                "axes"  : [[1.0, 0.0, 0.0], [0.0, 0.0, 1.0], [0.0, 1.0, 0.0] ]
                            }
                        }
                    }

this would imply assigning a PRESSURE with value "x+100.0*y*t**2" where x and y are calculated in a arbitrary system of cordinates with origin in  [10.0, 0.0, 0.0], and with the axes described by the axes field. this condition acts in the interval  [0, 10].

now if you want two different conditions, one valid in the interval [0,10] and another one [10.0, "End"] you just add another process.

The alternative would be providing a table input. It is easy to do but was not done yet...

**Comment by RiccardoRossi** [comment]
closing since the processes should allow this, and also as it has been long inactive.

@PhilippeBussetta please reopen if you consider the solution i proposed you is not ok
