### ISSUE TITLE
Inconsistent GiD output with inactive Elements

### ISSUE THREAD

**Issue by lluis-mv** [KratosMultiphysics/Kratos#1347]
Hi

In the Contact Mechanics Application, we are creating some elements for postprocess purposes. As such, these elements are labeled as inactive [Element.Set(ACTIVE,false)].
I noticed that during the writing of the GiD files, the geometry of non-active elements is not written. (gid_mesh_container.h line 190).
However, when Gauss point variables are written, it is not checked if the element is active [gid_gauss_point_container.h], and the information at Gauss Points of inactive elements is then written to the output file.
As a consequence, “corrupted” postprocess files are generated (the number of integration points is different to the size of gauss point information).

In my computer I just commented lines 192-193 of gid_mesh_container.h

**Comment by loumalouomega** [comment]
I was thinking exactly the same today, particularly the conditions give a lot of problems because of this

**Comment by jcotela** [comment]
I am looking into this. For now, I can tell you I could only reproduce this error when generating binary GiD output. While we work on a fix, you can use Ascii mode to write your results and GiD should display it correctly.

**Comment by lluis-mv** [comment]
[Hi @jcotela , in my computer it fails using both, binary and ascii, maybe it is the version of GiD....]

**Comment by jcotela** [comment]
Hi @lluis-mv I tried to solve this in #1365 but, given that we find different behaviors, I'm unsure if this will work for both of us. Can you try the branch core/fix-gid-print-only-active-gauss-points and tell me if it solves your problem?

**Comment by lluis-mv** [comment]
Hi @jcotela , I merged the branch of #1365   into my branch an it fixes my problem.
(We were relying on writting inactive elements, but I will try to do it differently :sweat_smile: )

**Comment by jcotela** [comment]
@lluis-mv the changes on the PR should only modify the writing of the gauss point results, not of the elements themselves. Are you getting less elements in your output now?

**Comment by lluis-mv** [comment]
With this PR only the information of the Gauss point elements that are active is written (that is, the Gauss points whose geometry is written in the postprocess file).
Before this PR the Gauss Point information of all elements was written but only the geometry of active elements was written.

In ContactMechanicsApplication, we are creating some elements (for postprocess purposes only) that are tagged as ACTIVE = false. 

As such, the inactive elements we were creating just to be present in the Postprocess are not written. But I am sure this can be done differently.

All that said, the PR DOES fix problems when inactive elements or conditions were present.

**Comment by jcotela** [comment]
Ok thanks for the clarification 👍

**Comment by josep-m-carbonell** [comment]
@lluis-mv , the thing is that the ACTIVE flag, is used internally for the solvers with a certain objective, to not consider that elements/conditions in the computation. But, at the same time it is rehused in the output to determine which entities are written. Maybe the correct thing would be to have two different flags to set two different options...

**Comment by josep-m-carbonell** [comment]
@KratosMultiphysics/technical-committee ,  I would like to add that, I think that usage of global FLAGS in the objects of the core must be documented and known widely in order to avoid conflicts. Also in applications.

**Comment by loumalouomega** [comment]
Something like "TO_POSTPROCESS"?

**Comment by josep-m-carbonell** [comment]
Well, the question is that maybe a flag is not needed. Output must write all the entities of the model part you supply to it. Therefore one must pass the correct output model part to the gid_io.
