### ISSUE TITLE
FSI error

### ISSUE THREAD

**Issue by sarti-luca** [KratosMultiphysics/Kratos#1367]
Dear All,

I'm trying to solve an FSI problem type; first of all I would solve the MOK implemented in GiD (channel with flexible wall) but I get this error. Since I've generate only the mesh I don't know where could be the error.

What can I do?
Thanks for your help. 

![image](https://user-images.githubusercontent.com/35461057/35324267-87427ff4-00f0-11e8-88ee-d46c7403bcde.png)

**Comment by rubenzorrilla** [comment]
Dear @sarti-luca,

This was a simple bug related to the ALE mesh solver time scheme we fixed some time ago. Maybe this was fixed after the release date. In any case let me have a look to the Mok benchmark current state. 

Sorry for the inconveniences.

**Comment by RiccardoRossi** [comment]
closing as inactive. reopen if needed
