### ISSUE TITLE
Modelpart_io cannot identify the element type

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1368]
We recently suppressed a warning #number which has caused modelpart_io not being able to compare types.

The problem is the following:
when we execute:

```C++
std::is_same<decltype(*(rThisElements.begin())), decltype(*(it_comp->second))>::value
```

The types are not essentially the same, as the first is evaluated to `Kratos::Element &` and the later to `Kratos::Element const&`. This is a problem because is_same do take into account `const` and `volatile`.

A first solution would be to use `std::remove_cv` which strips those qualifiers from the type, but `const` is not a top-level qualifier (it is applied to the referenced type, not the reference itself).

So what we need to do is strip first the reference from both the element and the component and then strip the const qualifier from the component (Below code works and does not repeat the warning, [source](https://stackoverflow.com/questions/15887144/stdremove-const-with-const-references) ):
```C++
std::is_same<std::remove_reference<decltype(*(rThisElements.begin()))>::type, std::remove_cv<std::remove_reference<decltype(*(it_comp->second))>::type>::type>::value
```

Or we can change the component to work with `Element&` instead of `Element const&`.

Also having take a look to this makes me wonder if the warning was about that `Element const&` to begin with...

**Comment by loumalouomega** [comment]
I will check it later

**Comment by roigcarlo** [comment]
No need, I have the branch already done, just want to be sure that it is ok to make the fix like that.

**Comment by loumalouomega** [comment]
Ok, merci

**Comment by roigcarlo** [comment]
Btw I would propose to solve this by using:

```C++
template<typename FirstElementType, typename SecondElementType>
struct IsSameElement
{ 
    static const bool value = 
        std::is_same<typename std::remove_reference<FirstElementType>::type,typename std::remove_cv<typename std::remove_reference<SecondElementType>::type>::type>::value ||
        std::is_same<typename std::remove_cv<typename std::remove_reference<FirstElementType>::type>::type,typename std::remove_reference<SecondElementType>::type>::value; 
};
```
Which uses the same implementation technique as `std::is_same` itself.
@pooyan-dadvand ?
