### ISSUE TITLE
People should Watch and Star the GitHub project in order to increase relevance of the project

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#137]
In order to increase relevance of the project in GitHub people should Star and Watch the project. The button in the header:

![](https://i.imgur.com/sB4UEuT.png)

Thank you very much in advance

**Comment by maceligueta** [comment]
Maybe we should send this to the mailing list (@KratosMultiphysics/technical-committee ).
We should also recommend everyone to activate the e-mail notifications when they are referenced here. I see several pings that have no answer.

**Comment by loumalouomega** [comment]
I am going to close this
