### ISSUE TITLE
How to create face element list in .mdpa for face pressure condition on a 3D object

### ISSUE THREAD

**Issue by donggiang** [KratosMultiphysics/Kratos#1380]
Hi everyone, 

I've been comparing numerical results between solid and shell elements by a simple problem called "simply supported beam" subjected to uniform pressure on its upper face. The issue I'm facing is that  by using Gid, I can't not get face elements (connectivity) in .mdpa for face pressure condition though for nodes and elements of the problem and nodes of Dirichlet condition I can do that.

I hope I can get help and find a solution for my issues. Thanks in advance.

Regards,
Giang

**Comment by jginternational** [comment]
Hi @donggiang 

If you are trying to apply a pressure on a line in a shell, we still have not this implemented (at least in the GUI)

I know that someone in the @KratosMultiphysics/structural-mechanics team is working on that.

Anyway, it would be fine if you send me the example to check what's going on.

Regards

**Comment by donggiang** [comment]
Hi there,
I addressed my issue. Thanks for your comment.

Regards
