### ISSUE TITLE
Missing test files

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1381]
`ref_*` files are missing for the tests in `test_gid_io_gauss_points.py`

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/35459869-35b549de-02e2-11e8-9fe3-25f788441dcd.png)
In fact the test is not even running

**Comment by roigcarlo** [comment]
It runs on my computer :S, it just can't check the results

**Comment by roigcarlo** [comment]
Well not missing at all, they were just not copied. Fixed in https://github.com/KratosMultiphysics/Kratos/tree/core/fix-test-aux-files but i think @jcotela wanted to add another fix
