### ISSUE TITLE
"Enhanced Kratos for Advanced Tunneling Engineering"

### ISSUE THREAD

**Issue by xuhenry** [KratosMultiphysics/Kratos#1390]
Hi, all,
    Is there anyone using the "Enhanced Kratos for Advanced Tunneling Engineering" [1] code? And where can I download it? Thanks!
[1]Abdullah Alsahly, Janosch Stascheit, Günther Meschke. Advanced finite element modeling of excavation and advancement processes in mechanized tunneling.Advances in Engineering Software
Volume 100, October 2016, Pages 198-214.
Thanks a lot!
Best regards,
Henry

**Comment by RiccardoRossi** [comment]
@vryy this is mantained by your team...

**Comment by xuhenry** [comment]
Thanks. Is it open sources?
@vryy

**Comment by vryy** [comment]
@xuhenry It is supposed to be open source but we did not yet make a license for it. It actually comprises of a set of Kratos applications that do different thing, i.e. soil constitutive model and multiphase elements, mortar contact, parallel builders and solvers, finite cell and iga (in dev), etc, and a modeller to generate a complete tunnel with components (in python). Which part are you interested in?

**Comment by xuhenry** [comment]
@vryy Many thanks for your reply.
I want to used Kratos to simulate the construction process of a tunnel in 3D, including the pile, anchor, liner and seepage. 
Is there any suggestion about the simulation? or how can I get the code, so that I can try it or develop based on you code?
Thanks a lot!
Best regards,
Henry

**Comment by vryy** [comment]
@xuhenry we are open for any collaborations, contact me via my institute email at giang.bui@rub.de

**Comment by RiccardoRossi** [comment]
guys don't forget to close this when done

**Comment by xuhenry** [comment]
Thanks a lot!
@vryy
