### ISSUE TITLE
some errors during the compile

### ISSUE THREAD

**Issue by Dongxueyang** [KratosMultiphysics/Kratos#1391]
some errors occurred at the step compile,(sh configure.sh),can any one give advices?

the result:
CMakeFiles/Kratos.dir/python/kratos_python.cpp.o: In function `PyInit_Kratos':
kratos_python.cpp:(.text+0x730): undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
collect2: error: ld returned 1 exit status
kratos/CMakeFiles/Kratos.dir/build.make:2439: recipe for target 'kratos/Kratos.so' failed
make[2]: *** [kratos/Kratos.so] Error 1
CMakeFiles/Makefile2:143: recipe for target 'kratos/CMakeFiles/Kratos.dir/all' failed
make[1]: *** [kratos/CMakeFiles/Kratos.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[  1%] Built target gidpost
[ 11%] Built target KratosCore
[ 11%] Linking CXX shared library Kratos.so
CMakeFiles/Kratos.dir/python/kratos_python.cpp.o: In function `PyInit_Kratos':
kratos_python.cpp:(.text+0x730): undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
collect2: error: ld returned 1 exit status
kratos/CMakeFiles/Kratos.dir/build.make:2439: recipe for target 'kratos/Kratos.so' failed
make[2]: *** [kratos/Kratos.so] Error 1
CMakeFiles/Makefile2:143: recipe for target 'kratos/CMakeFiles/Kratos.dir/all' failed
make[1]: *** [kratos/CMakeFiles/Kratos.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by roigcarlo** [comment]
Hi @Dongxueyang 
This error means that the Python library used in kratos is different to the one used to compile boost.

You have to make sure that the python library used in this steps:
1 - https://github.com/KratosMultiphysics/Kratos/wiki/Linux-Build#boost
2 - https://github.com/KratosMultiphysics/Kratos/wiki/Linux-Build#configure

Are the same. I can help you check that if you can post here the output of the configure.sh (until "Configuration Done!" the rest is not needed) and the contents of your `project-config.jam`

**Comment by Dongxueyang** [comment]
Thanks for your answer ,I have tried another time .
The configure.sh file is as followed:

cmake ..  									                                                    \
-DCMAKE_C_COMPILER=/usr/bin/gcc							                                    \
-DCMAKE_INSTALL_RPATH="/home/youruser/kratos/libs"                              \
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE                                        \
-DCMAKE_CXX_COMPILER=/usr/bin/g++						                                    \
-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 -std=c++11 " 					                        \
-DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -msse3 " 					                            \
-DBOOST_ROOT="~/compiled_libraries/boost_1_65_0"                              \
-DPYTHON_LIBRARY="/usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so" \
-DPYTHON_INCLUDE_DIR="/usr/include/python3.5"                                 \		                                    
-DMKL_SOLVERS_APPLICATION=OFF							                                      \
......
-DMKLSOLVER_INCLUDE_DIR="/opt/intel/Compiler/11.1/072/mkl/include"	            \
-DMKLSOLVER_LIB_DIR="/opt/intel/Compiler/11.1/072/mkl/lib/em64t"	              \
-DMETIS_APPLICATION=OFF								                                          \
-DPARMETIS_ROOT_DIR="/home/youruser/compiled_libraries/ParMetis-3.1.1"          \
-DTRILINOS_APPLICATION=OFF							                                        \
-DTRILINOS_ROOT="/home/youruser/compiled_libraries/trilinos-10.2.0"		          \

and the project-config.jam is:

# Boost.Build Configuration
# Automatically generated by bootstrap.sh

import option ;
import feature ;

# Compiler configuration. This definition will be used unless
# you already have defined some toolsets in your user-config.jam
# file.
if ! gcc in [ feature.values <toolset> ]
{
    using gcc ; 
}

project : default-build <toolset>gcc ;

# Python configuration
import python ;
if ! [ python.configured ]
{
    using python : 3.5 : /usr ;
}

# List of --with-<library> and --without-<library>
# options. If left empty, all libraries will be built.
# Options specified on the command line completely
# override this variable.
libraries =  ;

# These settings are equivivalent to corresponding command-line
# options.
option.set prefix : /usr/local ;
option.set exec-prefix : /usr/local ;
option.set libdir : /usr/local/lib ;
option.set includedir : /usr/local/include ;

# Stop on first error
option.set keep-going : false ;

then I compiled again ,and got the result:

[ 24%] Linking CXX shared library KratosExternalSolversApplication.so
CMakeFiles/KratosExternalSolversApplication.dir/custom_python/externalsolvers_python_application.cpp.o: In function `PyInit_KratosExternalSolversApplication':
externalsolvers_python_application.cpp:(.text+0x1140): undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
collect2: error: ld returned 1 exit status
applications/ExternalSolversApplication/CMakeFiles/KratosExternalSolversApplication.dir/build.make:154: recipe for target 'applications/ExternalSolversApplication/KratosExternalSolversApplication.so' failed
make[2]: *** [applications/ExternalSolversApplication/KratosExternalSolversApplication.so] Error 1
CMakeFiles/Makefile2:296: recipe for target 'applications/ExternalSolversApplication/CMakeFiles/KratosExternalSolversApplication.dir/all' failed
make[1]: *** [applications/ExternalSolversApplication/CMakeFiles/KratosExternalSolversApplication.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

[ 30%] Linking CXX shared library KratosMeshingApplication.so
CMakeFiles/KratosMeshingApplication.dir/custom_python/kratos_meshing_python_application.cpp.o: In function `PyInit_KratosMeshingApplication':
kratos_meshing_python_application.cpp:(.text+0xd70): undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
collect2: error: ld returned 1 exit status
applications/MeshingApplication/CMakeFiles/KratosMeshingApplication.dir/build.make:465: recipe for target 'applications/MeshingApplication/KratosMeshingApplication.so' failed
make[2]: *** [applications/MeshingApplication/KratosMeshingApplication.so] Error 1
CMakeFiles/Makefile2:411: recipe for target 'applications/MeshingApplication/CMakeFiles/KratosMeshingApplication.dir/all' failed
make[1]: *** [applications/MeshingApplication/CMakeFiles/KratosMeshingApplication.dir/all] Error 2

[ 32%] Building CXX object kratos/CMakeFiles/Kratos.dir/python/add_sparse_matrix_to_python.cpp.o
In file included from /home/yuguoxin/Kratos/applications/structural_application/custom_python/add_custom_strategies_to_python.cpp:82:0:
/home/yuguoxin/Kratos/applications/structural_application/custom_strategies/strategies/residualbased_newton_raphson_line_search_strategy.h: In instantiation of ‘double Kratos::ResidualBasedNewtonRaphsonLineSearchesStrategy<TSparseSpace, TDenseSpace, TLinearSolver>::Solve() [with TSparseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >; TDenseSpace = Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; TLinearSolver = Kratos::LinearSolver<Kratos::UblasSpace<double, boost::numeric::ublas::compressed_matrix<double>, boost::numeric::ublas::vector<double> >, Kratos::UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >]’:
/home/yuguoxin/Kratos/applications/structural_application/custom_python/add_custom_strategies_to_python.cpp:331:1:   required from here
/home/yuguoxin/Kratos/applications/structural_application/custom_strategies/strategies/residualbased_newton_raphson_line_search_strategy.h:198:14: warning: variable ‘Satisfactory_Line_Search’ set but not used [-Wunused-but-set-variable]
         bool Satisfactory_Line_Search = false;

[ 54%] Linking CXX shared library Kratos.so
CMakeFiles/Kratos.dir/python/kratos_python.cpp.o: In function `PyInit_Kratos':
kratos_python.cpp:(.text+0x730): undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
collect2: error: ld returned 1 exit status
kratos/CMakeFiles/Kratos.dir/build.make:2439: recipe for target 'kratos/Kratos.so' failed
make[2]: *** [kratos/Kratos.so] Error 1
CMakeFiles/Makefile2:143: recipe for target 'kratos/CMakeFiles/Kratos.dir/all' failed
make[1]: *** [kratos/CMakeFiles/Kratos.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
[  1%] Built target gidpost
[ 11%] Built target KratosCore
[ 11%] Linking CXX shared library Kratos.so
CMakeFiles/Kratos.dir/python/kratos_python.cpp.o: In function `PyInit_Kratos':
kratos_python.cpp:(.text+0x730): undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
collect2: error: ld returned 1 exit status
kratos/CMakeFiles/Kratos.dir/build.make:2439: recipe for target 'kratos/Kratos.so' failed
make[2]: *** [kratos/Kratos.so] Error 1
CMakeFiles/Makefile2:143: recipe for target 'kratos/CMakeFiles/Kratos.dir/all' failed
make[1]: *** [kratos/CMakeFiles/Kratos.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
yuguoxin@yuguoxin-To-be-filled-by-O-E-M:~/Kratos/cmake_build$ 


but there are the similar errors.
I put the configure.sh and the project-config.jam in the attach files.
Thank you so much!/

**Comment by Dongxueyang** [comment]
sorry,the font in some part has changed,so it is not neat,

**Comment by roigcarlo** [comment]
Hi @Dongxueyang,
Don't worry about the font it's ok!

For what I can see the problem seems to be with boost. Could yo try replacing 

```
import python ;
if ! [ python.configured ]
{
using python : 3.5 : /usr ;
}
```

for 

```
using python : 3.5 : /usr ;
```

And recompile boost?

Seems that the first `import python` is selecting 2.7

**Comment by Dongxueyang** [comment]
Thank you for your patience,I appreciate it.
I have modified the code just as what you say, and compiled the configure.sh again.
but every time I got the same error like this:


[ 14%] Linking CXX shared library Kratos.so
CMakeFiles/Kratos.dir/python/kratos_python.cpp.o: In function `PyInit_Kratos':
kratos_python.cpp:(.text+0x730): undefined reference to `boost::python::detail::init_module(PyModuleDef&, void (*)())'
collect2: error: ld returned 1 exit status
kratos/CMakeFiles/Kratos.dir/build.make:2439: recipe for target 'kratos/Kratos.so' failed
make[2]: *** [kratos/Kratos.so] Error 1
CMakeFiles/Makefile2:143: recipe for target 'kratos/CMakeFiles/Kratos.dir/all' failed
make[1]: *** [kratos/CMakeFiles/Kratos.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2


I don't know if the original error was corrected.

**Comment by roigcarlo** [comment]
Hi @Dongxueyang, 

Did you also recompile boost? This is quite odd. Could you comment the `make install` line in the configure and send me the output? It should look like this:

```
./configure.sh: line 14: cd: build: No such file or directory
-- The C compiler identification is Clang 5.0.1
-- The CXX compiler identification is Clang 5.0.1
-- Check for working C compiler: /bin/clang
-- Check for working C compiler: /bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /bin/clang++
-- Check for working CXX compiler: /bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /bin/git (found version "2.15.1") 
additional default options were set for clang compiler
CMAKE_CXX_FLAGS =  -mavx2 -std=c++11 -fopenmp -fPIC  -funroll-loops -Wall -Wno-unused-local-typedef -Wno-unknown-pragmas  
CMAKE_C_FLAGS =  -mavx2 -fopenmp -fPIC -funroll-loops -Wall -Wno-unknown-pragmas  
KRATOS_EXCLUDE_OPENMP
OpenMP included
-- Found OpenMP_C: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP_CXX: -fopenmp=libomp (found version "3.1") 
-- Found OpenMP: TRUE (found version "3.1")  
Using component: python3
CMake Warning at /usr/share/cmake-3.10/Modules/FindBoost.cmake:1641 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:205 (FIND_PACKAGE)
...
```

**Comment by Dongxueyang** [comment]
yuguoxin@yuguoxin-To-be-filled-by-O-E-M:~/Kratos/cmake_build$ sh configure.sh 

-- The C compiler identification is GNU 4.9.3
-- The CXX compiler identification is GNU 4.9.3
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "2.7.4") 
additional default options were set for gcc
CMAKE_CXX_FLAGS =  -msse3 -std=c++11 -funroll-loops -Wall -std=c++11
CMAKE_C_FLAGS =  -msse3 -funroll-loops -Wall
KRATOS_BUILD_TESTING not defined. Setting to ON
KRATOS_EXCLUDE_OPENMP
OpenMP included
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
Using component: python
-- Boost version: 1.63.0
-- Found the following Boost libraries:
--   python
Boost Include: /usr/local/include
Boost Linkdir: /usr/local/lib
Boostlib used: /usr/local/lib/libboost_python.so.1.65.0
-- Found PythonLibs: /usr/lib/python3.5/config-3.5m-x86_64-linux-gnu/libpython3.5m.so (found version "3.5.2") 
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.2.11") 
 
CMAKE_BUILD_TYPE ........ Release
 
WARNING: YOUR GIDPOST IS BEING COMPILED  WITHOUT DEBUG (ALL ASSERTS WILL BE AVOIDED)
-- Looking for include file pthread.h
-- Looking for include file pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE

**Comment by roigcarlo** [comment]
Ok, The problem is here:

```
-- Boost version: 1.63.0
```

and 

```
Boost Include: /usr/local/include
Boost Linkdir: /usr/local/lib
Boostlib used: /usr/local/lib/libboost_python.so.1.65.0
```

CMake is just using your system libs instead of the ones you have compiled.
According to the configure you sent boost should be here:
```
-DBOOST_ROOT="~/compiled_libraries/boost_1_65_0" 
```
Could yo check that this is correct and you can do:
```
ls -DBOOST_ROOT="~/compiled_libraries/boost_1_65_0/stage/
```

If `no such file or directory` error appears it means that boost must be somewhere esle

**Comment by Dongxueyang** [comment]
Thank you so much .Today I have compiled the configure successfully.Thanks for your advices.

**Comment by Dongxueyang** [comment]
What should it be like after these command:

echo $LD_LIBRARY_PATH
echo $PYTHONPATH
echo $PATH
 I think my environment variables are wrong.

**Comment by roigcarlo** [comment]
Hi @Dongxueyang,
It depends on where you have kratos. I will asume `~/kratos`. Then:
```
LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/kratos/libs
PYTHONPATH=$PYTHONPATH:~/kratos
PATH=$PATH:~/kratos
```

**Comment by Dongxueyang** [comment]
Have tried so many times,I can test it successfully.
The result likes this:

dongxueyang@dongxueyang:~/Kratos/kratos/tests$ runkratos test_processes.py 
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.3.0-1e75958

Thank you for your help these days, thank you so much!
