### ISSUE TITLE
Windows compilation error - reference variable in reduction clause

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#1393]
Hi @rubenzorrilla , I think this goes to you

Visual studio shows an error in drag_utilities from FluidDynamicsApplication as it does not accept reference variables in the reduction clause:

![image](https://user-images.githubusercontent.com/25667299/35508064-4a8d6ff8-04ef-11e8-91c9-07ad90ae6eab.png)

**Comment by rubenzorrilla** [comment]
@ddiezrod, this seems to be another Windows - OpenMP problem... Honestly, I didn't compile in Windows before merging that. Let me have a look to it. Thanks for reporting that!

**Comment by roigcarlo** [comment]
Hi, these variables are references and indeed they should not be as they are used in a reduction. From the OopenMP manual:

> A type name in a declare reduction directive cannot be a function type, an array type, a reference type, or a type qualified with const, volatile or restrict.

**Comment by rubenzorrilla** [comment]
@RiccardoRossi just for your information. It seems that we cannot do that in this way...

**Comment by jginternational** [comment]
Bravo
