### ISSUE TITLE
New repository for GiD GUI

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#14]
If @pooyan-dadvand  agrees, I'm going to create a project for the GiD interface.

For the creation of the new repository, I can follow this steps:
https://help.github.com/articles/splitting-a-subfolder-out-into-a-new-repository/

**Comment by pooyan-dadvand** [comment]
yes, I found the same one yesterday. let me create the repo first!

**Comment by roigcarlo** [comment]
Also, maybe its worth to look at submodules https://git-scm.com/book/en/v2/Git-Tools-Submodules

**Comment by pooyan-dadvand** [comment]
I have just created the [GiDInterface](https://github.com/KratosMultiphysics/GiDInterface) repository.

**Comment by jginternational** [comment]
@pooyan-dadvand  please delete the following folders:

- interfaces
-gid_interfaces
