### ISSUE TITLE
Appveyor support

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1404]
@KratosMultiphysics/technical-committee I am going to activate appveyor support. If I break something or you see things that should not be there please use this issue to report

**Comment by pooyan-dadvand** [comment]
Great!!!!!

Thanks @roigcarlo !!!

**Comment by roigcarlo** [comment]
@pooyan-dadvand  I disabled it temporally since it was building some thing it should not. Fix already up in #1407

**Comment by roigcarlo** [comment]
It now only builds merges with master so this is fixed. Closing this.
