### ISSUE TITLE
Which process can calculate mass?

### ISSUE THREAD

**Issue by e-dub** [KratosMultiphysics/Kratos#1422]
I am looking for a way to calculate the mass of a structure in Kratos and see that following code does not throw an error, but gives zeros, i.e. (0,0,0),
``
main_model_part.ProcessInfo.GetValue(MASS)
``
This leads me to believe that it is indeed possible. I have seen that there is a process within the ULF and Shape Optimization applications.  
Can anyone give me a hint on calculating mass in concert with structural-mechanical analysis?

Thanks in advance!

**Comment by maceligueta** [comment]
Hi, I can't tell you what is the process you are looking for, but I can tell you why `main_model_part.ProcessInfo.GetValue(MASS)` did not work: 
By doing `main_model_part.ProcessInfo` you are accessing a container of heterogeneous Variables. When you do `main_model_part.ProcessInfo.GetValue(MASS)` you are accessing the Variable MASS. If you stored something there (inside MASS), with this sentence you would recover it. If not, it returns 0.

**Comment by loumalouomega** [comment]
Indeed, you need to implement a dummy strategy/scheme (in my opinion) for that. You assemble the system (lumped) with a zero stiffness and then sum all the diagonal terms of the resulting LHS matrix, that way you will get the total mass of the system (be careful, because if your problem add terms to the mass matrix not related with the mass of the system it will be added too)

**Comment by maceligueta** [comment]
Another option is to loop over the elements, ask the volume to each one and multiply times the density. It woud be great if a process was coded already for this.

**Comment by RiccardoRossi** [comment]
to resume, you can do something like(pseudo code)

     volume = 0
     for elem in model_part.Elements:
          volume += elem.Volume()

i am closing for now.

**Comment by loumalouomega** [comment]
Yes, this is definitively easier, for shell and beams is not so straight forward, that is why I suggested the other more complex approach

**Comment by e-dub** [comment]
My preliminary solution is the following:

Volumes:
```
mass = 0
from scipy.spatial import ConvexHull
for Element in main_model_part.Elements:
    points = np.array([[Element.GetNode(0).X0, Element.GetNode(0).Y0, Element.GetNode(0).Z0],
                       [Element.GetNode(1).X0, Element.GetNode(1).Y0, Element.GetNode(1).Z0],
                       [Element.GetNode(2).X0, Element.GetNode(2).Y0, Element.GetNode(2).Z0],
                       [Element.GetNode(3).X0, Element.GetNode(3).Y0, Element.GetNode(3).Z0],
                       [Element.GetNode(4).X0, Element.GetNode(4).Y0, Element.GetNode(4).Z0],
                       [Element.GetNode(5).X0, Element.GetNode(5).Y0, Element.GetNode(5).Z0],
                       [Element.GetNode(6).X0, Element.GetNode(6).Y0, Element.GetNode(6).Z0],
                       [Element.GetNode(7).X0, Element.GetNode(7).Y0, Element.GetNode(7).Z0]])
    V = ConvexHull(points).volume
    mass += main_model_part.GetProperties()[1].GetValue(DENSITY)*V
```

Beams and trusses:
```
mass = 0
for Element in main_model_part.Elements:
    el = ((Element.GetNode(1).X0-Element.GetNode(0).X0)**2 + \
          (Element.GetNode(1).Y0-Element.GetNode(0).Y0)**2 + \
          (Element.GetNode(1).Z0-Element.GetNode(0).Z0)**2)**0.5
    V = el*Element.GetArea()
    mass += main_model_part.GetProperties()[1].GetValue(DENSITY)*V
```
I still need to test to verify. 


For the suggestion 
```
volume = 0
 for elem in model_part.Elements:
      volume += elem.Volume()
```
Does elem have Volume()?

**Comment by loumalouomega** [comment]
I think it can be don in a simpler way, specially because the geometries of the beams have Lenght() and the the shells Area()

**Comment by e-dub** [comment]
Are Volume(), Area(), Length() readily available or would I have to implement this in each of the element description files?

**Comment by loumalouomega** [comment]
It is in the geometry, let me one sec

**Comment by loumalouomega** [comment]
I am implementing it, I will need some minutes

**Comment by loumalouomega** [comment]
~~~cpp
void TotalStructuralMassProcess::Execute()
{
    KRATOS_TRY
    
    // We initialize the total mass
    double total_mass  = 0.0;
    
    const std::size_t dimension = mrThisModelPart.GetProcessInfo()[DOMAIN_SIZE];
    
    // Now we iterate over the elements to calculate the total mass
    ElementsArrayType& elements_array = mrThisModelPart.Elements();
    
    #pragma omp parallel for reduction(+:total_mass)
    for(int i = 0; i < static_cast<int>(elements_array.size()); ++i) 
    {
        auto it_elem = elements_array.begin() + i;
        
        // We get the condition geometry
        GeometryType& r_this_geometry = it_elem->GetGeometry();
        const std::size_t local_space_dimension = r_this_geometry.LocalSpaceDimension();
        
        // We get the values from the condition
        Kratos::Properties& this_properties = it_elem->GetProperties();
        const double density = this_properties[DENSITY];
        
        if (local_space_dimension == 1) { // BEAM CASE
            const double area = this_properties[CROSS_AREA];
            total_mass += density * area * r_this_geometry.Lenght();
        } else if (local_space_dimension == 2 && dimension == 3) { // SHELL-MEMBRANE
            const double thickness = this_properties[THICKNESS];
            total_mass += density * thickness * r_this_geometry.Area();
        } else { // SOLID
            const double thickness = (dimension == 2) ? this_properties[THICKNESS] : 1.0;
            total_mass += density * thickness * r_this_geometry.Volume();
        }
    }
    
    std::cout << "The total mass of the system is :" << total_mass/1000.0 << " Tn\n" << "Check variable NODAL_MASS in the process info in order to acces to it in any moment" << std::endl;
    
    mrThisModelPart.GetProcessInfo()[NODAL_MASS] = total_mass;
    
    KRATOS_CATCH("")
} // class TotalStructuralMassProcess
~~~

**Comment by loumalouomega** [comment]
I will add to a branch

**Comment by loumalouomega** [comment]
Done

**Comment by e-dub** [comment]
@loumalouomega: Many thanks! Tested it this morning and gives consistent results!
Cheers from Bozen!
