### ISSUE TITLE
External forces/Internal forces discussion

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#1425]
@ipouplana and I have been working (very WIP) in a arc length strategy, and I realized that with the current implementation the RHS assembling incorporates simultaneously the internal and external forces, and in our particular case we are interested in only use the external forces, possible alternatives are:

- ProcessInfo variables: @RiccardoRossi suggestion. Adding a new variable to the `variables.h` called `COMPUTE_EXTERNAL_FORCES` or equivalent. This one requires the modification of conditions and elements but will be the best compromise between dirtiness and respecting the current API implementation. In any case in the same way that the Builder and Solver have the ComputeDirichlet maybe would a good idea a method called ComputeNeumman.
- Adding a new method to `condition.h` and `element.h` or modify the current ones like `CalculateRightHandSide()`. This one requires deeper modifications than the previous one and I assume that not @KratosMultiphysics/technical-committee will be no happy with that.
- Compute the assembling in a submodelpart containing just the conditions/elments of interest. This one is the dirtiest and easiest, but it lacks of generality

I think that all folks

**Comment by RiccardoRossi** [comment]
just to say that i do not consider as "dirty" the last option. We don't need a special method or builder and solver for that. Only need to catalogue the conditions to be considered in the arc lenght.

I would also say that Option2 brings nothing on the top of Option1, apart for making the interface larger (which is undesirable). The bad thing of options 1 and 2 is that they do not really solve completely the problem: imagine that you have both a PRESSURE and a BODY_WEIGHT.
you need arc lenght to be applied only on the pressure load. what then?

**Comment by loumalouomega** [comment]
@ipouplana knows more about the algorithm, he can tell if the relevant is the total external forces or just the related with the arc-length

**Comment by ipouplana** [comment]
If I remember correctly, we just need to consider the external forces that need to be modified with the arc-length...

**Comment by RiccardoRossi** [comment]
@ipouplana the point is how the user should select which of the external forces need to be multiplied by the load factor. 
My first suggestion would be to do that through Option 3, that is by prescribing a submodelpart which contains the loading conditions to be considered in the arclenght

**Comment by ipouplana** [comment]
What I have been doing is:
- Each external load applied is related to a submodelpart (standard behaviour)
- The names of the submodelparts corresponding to loads that need to be modified through the arc-length are listed in the projectparameters.json
- This list of arc-length loads is read by the arc-length strategy to modify them when needed

**Comment by RiccardoRossi** [comment]
I like this approach...what's wrong with this?

**Comment by ipouplana** [comment]
The problem is that the arc-length algorithm needs to work with a system vector of the external forces related to the arc-length (excluding self weight and other terms that could be included in the RHS system vector...)

**Comment by RiccardoRossi** [comment]
yes i understand. However you can obtain the overall residual vector by doing

     BuildRHS( computing_model_part ... ) 

and the external forces vector by doing

    BuildRHS(  submodel_part_with_loading_conditions .... )

the trick would be to define internally one submodelpart grouping all of the subparts you want to be considered in the arclenght

**Comment by ipouplana** [comment]
That could work nicely...

**Comment by loumalouomega** [comment]
Ok, maybe this could work...

**Comment by maceligueta** [comment]
So you guys decided option 3?

**Comment by ipouplana** [comment]
I think so...

**Comment by loumalouomega** [comment]
Probably, closing, opening again in case of further discussion
