### ISSUE TITLE
Inconsistent printing of Vector type variables in GiDIO

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#1428]
@soudah and me have encountered some inconsistent behavior of GiDIO when trying to print `Vector` type variables. Our setting is a 3D simulation (tetrahedra_3d_4 elements and triangle_2d_3 conditions), and we are trying to visualize in GiD a variable of type `Vector` and size 3.

- If we write it on the conditions (triangles) using `GiDIO::PrintOnGaussPoints`, it produces a vector type GiD variable (with var_x, var_y, var_z components and norm). This is what we want.
- If we write it on the nodes using `GiDIO::WriteNodalResults` and we use Binary output mode, the resulting file is unreadable.
- If we write it on the nodes, but now using Ascii mode, it produces a 3D symmetric matrix type GiD variable (with var_xx, var_xy, var_xz, var_yy,... components and principal directions).

Besides the Binary thing (which I think is obviously a bug), is there a good reason to have this differing behavior?

**Comment by RiccardoRossi** [comment]
I think that the problem is outputting matrices which are given in voigt format. (say strain or stress)

how do we distinguish such case?

**Comment by jcotela** [comment]
Well, I'd say a 3D Voigt matrix is of size 6 (not 3). I don't know if GiDIO knows if it is in 2D or 3D from within whatever function calls this, though...

**Comment by RiccardoRossi** [comment]
in 2D it is of size 3 Txx Tyy Txy

**Comment by RiccardoRossi** [comment]
expanding:

gid allows a voigt vector to have either 3 or 6 components. 

Of course however if you have a 2d element living in the 3d space you will need to provide the full 6 components

**Comment by jcotela** [comment]
Yes. The point is that now one output interprets the Vector(3) as a "mathematical" 3D vector, the other interprets the same vector as a 2D Voigt tensor. Both can be correct, but not at the same time...

**Comment by RiccardoRossi** [comment]
Yes i got you. I don't know how to fix this though. What we could do is that in order to be interpreted as voigt, a matrix should have one single row

i think this was what i was doing in the original structural_application

**Comment by pooyan-dadvand** [comment]
After discussion in TC the rule is: considering `array_1d<double,3>` as vectorial field and `Vector` as voigt notation.
