### ISSUE TITLE
Quadrilateral missing in point_output_process

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#1430]
Hi @pablobecker and @pooyan-dadvand.

While writing some tests and using this process I found that this is only implemented for triangular, tetrahedron and hexahedron elements. The process is currently not applicable for quadrilateral elements. Are there plans for implementing it for quadrilaterals?

**Comment by pooyan-dadvand** [comment]
Not from our side at this moment. Let see if @pablobecker has any plan on this. (It is long time that he is not working in this part)

**Comment by pablobecker** [comment]
No, sorry,
but it would be straighforward to implement it for other geometries.  Loot at https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/pointlocation.h

**Comment by AndreasWinterstein** [comment]
Thank you. I will discuss with @philbucher tomorrow since he just told me there might be a better solution for my problem. Otherwise I will implement it.
