### ISSUE TITLE
Installing mmg library

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#1436]
Hello, I am trying to install mmg following the steps in the Kratos Wiki.
When I recompile Kratos I get the next error:
~~~
make[2]: *** No hay ninguna regla para construir el objetivo «/home/mmaso/libraries/mmg/lib/libmmg2d.a», necesario para «applications/MeshingApplication/KratosMeshingApplication.so».  Alto.
~~~

**Comment by loumalouomega** [comment]
Have you compiled the mmg?

**Comment by loumalouomega** [comment]
[build.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/1691976/build.tar.gz)

This is my latest compilation.

Besides, I have been looking and looks like the support to quads in 2D is half implemented (they added variables, and methods for quads, but it is not supported in the API). I tried to manually set it, but is not working. Sorry

I will ask them in the forum

**Comment by loumalouomega** [comment]
Besides, I will add the support for triangles and quadrilaterals as elements in 3D

**Comment by loumalouomega** [comment]
I have asked in the forum, I will keep you informed

**Comment by miguelmaso** [comment]
I tried to compile the library following the steps from https://github.com/KratosMultiphysics/Kratos/wiki/MMG-Process#how-can-i-install-this-library and also from https://github.com/MmgTools/mmg#get-and-compile-the-mmg-project.
i will try with your latest compilation.
Thank you

**Comment by loumalouomega** [comment]
@miguelmaso Unfortunely looks like the support for quadrilaterals in 3D is just to keep the track of the prisms layer

https://forum.mmgtools.org/t/quadrilaterals-in-2d/177/2

They will keep us informed, sorry for the noise

**Comment by loumalouomega** [comment]
@miguelmaso Maybe we can build a temporal fix in order to remesh quads using an auxiliar triangular mesh and rebuilding quads from that mesh. We can add a warning telling that is not an official feature of MMG, as you wish

**Comment by loumalouomega** [comment]
Somethig like this https://stackoverflow.com/questions/10931626/how-do-i-convert-a-2d-mesh-of-triangles-into-quadrilaterals

**Comment by miguelmaso** [comment]
@loumalouomega thank you for your support. Some things about the compilation:
The configure.sh from the MeshingApplication generates the `libmmg.a` files to `usr/local/bin`.
Anyway I am still getting other compilation errors if I place the `.a` files in the lib of mmg:
~~~
/usr/bin/ld: /home/mmaso/libraries/mmg/build/lib/libmmg.a(API_functions_2d.c.o): no se puede usar la reubicación R_X86_64_32S contra `.rodata' cuando se hace un objeto compartido; recompile con -fPIC
/home/mmaso/libraries/mmg/build/lib/libmmg.a: error adding symbols: Valor erróneo
collect2: error: ld returned 1 exit status
make[2]: *** [applications/MeshingApplication/KratosMeshingApplication.so] Error 1
make[1]: *** [applications/MeshingApplication/CMakeFiles/KratosMeshingApplication.dir/all] Error 2
~~~
I am compiling with -fPIC option

**Comment by loumalouomega** [comment]
Try with this sh

(if your computer is old use -mavx)

~~~sh
cmake .. \
-DCMAKE_BUILD_TYPE=Release                                  \
-DCMAKE_CXX_FLAGS="-O3 -mavx -fPIC -fopenmp"               \
-DCMAKE_C_FLAGS="-O3 -mavx -fPIC -fopenmp"                 \
-DUSE_SCOTCH=OFF                                            \
-DSCOTCH_INCLUDE_DIR="/usr/include/scotch/"	            \
-DSCOTCH_LIBRARY="libscotchmetis-5.1.so"	            \
-DSCOTCHERR_LIBRARY="libscotcherr-5.1.so"	            \
-DLIBMMG_SHARED=ON                                       \
-DLIBMMG_STATIC=OFF                                       \
-DLIBMMGS_SHARED=ON                                      \
-DLIBMMGS_STATIC=OFF                                      \
-DLIBMMG2D_SHARED=ON                                     \
-DLIBMMG2D_STATIC=OFF                                     \
-DLIBMMG3D_SHARED=ON                                     \
-DLIBMMG3D_STATIC=OFF                                     \
#decomment this to have it verbose
# make VERBOSE=1 -j4
make -j4
# sudo make install

~~~

**Comment by loumalouomega** [comment]
If the installation is in the usr/local/bin will be due to sudo make install, but it is not necessary

**Comment by miguelmaso** [comment]
mmm, this is almost the same sh I have always used. After I compile mmg library with this sh, I am getting the same error when recompiling Kratos

**Comment by loumalouomega** [comment]
Try using the dynamic libraries instead of the static:ç

~~~sh
-DMMG_LIBRARY="~src/mmg/lib/libmmg.so"     \
-DMMG2D_LIBRARY="~src/mmg/lib/libmmg2d.so" \
-DMMG3D_LIBRARY="~src/mmg/lib/libmmg3d.so" \
-DMMGS_LIBRARY="~src/mmg/lib/libmmgs.so"   \
~~~

**Comment by miguelmaso** [comment]
Yesterday I used the dynamic libraries, but the tests didn't run. i will try again

**Comment by loumalouomega** [comment]
Okay

**Comment by miguelmaso** [comment]
Actually mmg is working
Thank you

**Comment by loumalouomega** [comment]
Hurray
