### ISSUE TITLE
Eigensolveranalysis in Problemtype of StructuralMechanics

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1458]
Hi @KratosMultiphysics/technical-committee , @jginternational and @KratosMultiphysics/structural-mechanics 

We now have the possibility to do Eigenvalue analysis in GiD since there is an eigenvalue solver available in the EigenSolversApplication , see #1359 
This works both in Windows and in Linux

From the GiD-side one only needs to copy the static analysis and remove the loads and adjust the settings a bit, so its no too much effort
Also the visualizing is available already

Now the main question is if the EigenSolversApplication can be included in the release. I think the licensing issues were discussed some time ago and it seemed to be ok

Compiling and packing it was already done by @armingeiser

**Comment by RiccardoRossi** [comment]
@roigcarlo this means that we would need to compile the EigenSolversApplication (which requires Eigen) and include it in the release

**Comment by philbucher** [comment]
maybe @oberbichler and @armingeiser can assist with the compilation
@roigcarlo there is a readme in the `EigenSolversApplication`

**Comment by roigcarlo** [comment]
No problem as long as it does not require a FORTRAN compiler. We can even activate the pardiso solvers if you want to add mkl to the package.

Just remember to add it here https://github.com/KratosMultiphysics/Kratos/projects/5 please, under the Linux or Windows (or both) so I don't miss it the day I make the package.

I'll try to compile it now (without MKL this time) to check if there gives any problem and let you know.

__Status__:
- [x] Linux: Seems ok!, just remark that for some reason EIGEN_ROOT must point to the include dir and not the root dir.
- [x] Windows: Seems ok as well. Pending to test...

**Comment by oberbichler** [comment]
A Fortran compiler is not required.

The SparseLU solver (no MKL) should be fast enough.

EIGEN_ROOT should point to the "eigen[versionnumber]/" path which contains the folders "Eigen", "Unsupported", ...

**Comment by roigcarlo** [comment]
@oberbichler Seems to compile in win but it has create like 778 projects and compiled under 2 sec. Are those tests or something?

**Comment by oberbichler** [comment]
What do you mean with "projects"?

**Comment by roigcarlo** [comment]
![image](https://user-images.githubusercontent.com/1935791/35913167-1f5dd310-0bff-11e8-80d0-21330cee6eab.png)
This

**Comment by oberbichler** [comment]
Interesting... I am using `ninja` instead of `msbuild` so I don't have VS projects at all. Maybe @armingeiser has an idea

**Comment by oberbichler** [comment]
You don't need to build Eigen. Does this happen if you just set the EIGEN_ROOT?

**Comment by roigcarlo** [comment]
A ok, I thought I needed to build them. Then everything ok 👍

**Comment by roigcarlo** [comment]
Well seems to work just fine as will in win. I cannot test it right now as there are compilation issues in the code but it shouldn't be an issue to add it to the release

**Comment by pooyan-dadvand** [comment]
If the license is not a matter I have no objection to include it in release :+1:

**Comment by armingeiser** [comment]
Important is the ```EIGEN_MPL2_ONLY``` compiler flag in the CMakeLists, then only the MPL2 features are available and those are compatible with BSD.

**Comment by roigcarlo** [comment]
Gonna add a reminder for that in the project thx @armingeiser

**Comment by RiccardoRossi** [comment]
can this issue be closed?

**Comment by philbucher** [comment]
I think so, here is the [issue in the GiD repo](https://github.com/KratosMultiphysics/GiDInterface/issues/243) for it
