### ISSUE TITLE
Serializer problem in win

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1463]
Serializer crashes with:

```Bash
C:\KratosSource\kratos\includes/serializer.h(207): error C2039: 'load': is not a member of 'std::_Array_iterator<_Ty,1>

with
          [
              _Ty=Kratos::Table<double,double,1>::result_type
          ]
```

Seems to be related with Kratos::Tables. @pooyan-dadvand any idea?

**Comment by roigcarlo** [comment]
Duplicated

**Comment by roigcarlo** [comment]
Follow up of #1335

**Comment by roigcarlo** [comment]
@philbucher I added `save` and `load` for std::array, but the problem seems to be that you are trying to save the iterator. Is that correct? Not sure how to serialize iterators, maybe @pooyan-dadvand can suggest something.

Only thng that comes to my mind is to save the iterator as a index and then resotre it in the load function...

**Comment by philbucher** [comment]
I don't know why it wants to save the iterator, I didn't use this anywhere and I also couldn't find anything.

Maybe its related to the `TableIterator` in `model_part.h`?

**Comment by roigcarlo** [comment]
Sorry I thought you coded that part. If it was @pooyan-dadvand let's wait for him. Seems to me that it is used in the load function, but I don't know if it needs to be that way because the memory is not consecutive or there is another reason

**Comment by philbucher** [comment]
I think pooyan did this bcs I didn't know how to do it.
Seems like e.g. [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/table.h#L803) an iterator is being saved/loaded

**Comment by philbucher** [comment]
from what I see, `mData` is of Type `TableContainerType`, which is an `std::vector`. Could you try looping without iterators? I think it should works then (even though then you might still need the methods to save/load the `std::array`)

**Comment by roigcarlo** [comment]
But the std::vector save/load code will call the save load methods o the DataType of the array, so at the end the problem will be the same.

It seems to work by just saving the whole array instead of the pointer to it like:

```C++
    void save(Serializer& rSerializer) const
    {
        std::size_t  local_size = mData.size();

        rSerializer.save("size", local_size);

        for(auto i_row = mData.begin() ; i_row != mData.end() ; i_row++){
            rSerializer.save("Argument", i_row->first);
            for(auto j = i_row->second.begin() ; j != i_row->second.end(); j++)
                rSerializer.save("Column", *j);
        }
    }

    void load(Serializer& rSerializer)
    {
        std::size_t local_size;

        rSerializer.load("size", local_size);

        mData.resize(local_size);

        for(auto i_row = mData.begin() ; i_row != mData.end() ; i_row++){
            rSerializer.load("Argument", i_row->first);
            for(auto j = i_row->second.begin() ; j != i_row->second.end() ; j++)
                rSerializer.load("Column", *j);
        }
   }
```

But not sure of this is the aim of the older code.

**Comment by philbucher** [comment]
what you did was kind of what I meant.

Do the tests run?

**Comment by roigcarlo** [comment]
Still compiling

**Comment by roigcarlo** [comment]
All tests seem ok (both cpp and python). I will make the PR
