### ISSUE TITLE
DBOOST_ROOT option ignored

### ISSUE THREAD

**Issue by oleburghardt** [KratosMultiphysics/Kratos#1474]
Dear Kratos developers,

as you already mention it yourselves in the Getting Started-section, Kratos apparently cannot be linked against some specific boost libraries, e.g. version 1.60 and 1.64 which I tried myself.

But I'm also in trouble using a local (second) build of the boost library (I'm trying 1.67) since although I specify the correct path to the second library with DBOOST_ROOT, cmake still uses the one installed in /usr/lib...

As I'm not familiar with cmake, could you provide a fix or a workaround?

Thanks in advance!
Ole

**Comment by jcotela** [comment]
Dear Ole,
You can try to set `Boost_LIBRARY_DIRS` and `Boost_INCLUDE_DIR` instead. For example, I use this:
```
-DBoost_LIBRARY_DIRS=/home/jcotela/Libraries/lib \
-DBoost_INCLUDE_DIR=/home/jcotela/Libraries/include/ \
```
Where the first path points to the folder containing all .so files and the second path points to a `boost` folder (for example, one of my headers is `/home/jcotela/Libraries/include/boost/python.hpp`).

If this does not work, I'd suggest sending us your configure script and the cmake output, so that we can give you more specific suggestions.

**Comment by RiccardoRossi** [comment]
As  a hint, i think it would also make step to make the first configure from an empty directory. Cmake stores a cache which is sometimes on the way to automatic detection

**Comment by oleburghardt** [comment]
Hi,

thanks for your help!! :-)
Worked immediately with the options above. 

Maybe you could add it to the Wiki page since the incompatible versions are currently the standard ones and people might run into a similar problem?

And by the way, if using Python 3, the indicated line in project-config.jam
`using python : 3.5 : /usr ;`  
might not be sufficient, I had to specify the precise version that Kratos attempted to use, i.e.
`using python : 3.6 : /usr/bin/python3.6m : /usr/include/python3.6m ;`
Even though it seems system-specific, this little note might also help others :-).

Thanks again and best regards,
Ole

**Comment by oleburghardt** [comment]
@RiccardoRossi We commented just in time :-).

Thanks very much for your hint though @jcotela already solved the issue.

Best regards, 
Ole
