### ISSUE TITLE
Looking for Help: Benchmark in FluidDynamic

### ISSUE THREAD

**Issue by fdifrison** [KratosMultiphysics/Kratos#1491]
# Hello KratosTeam! 

I’m seeking for your expertise in order to better understand if I’m way off base with my simulations  or if I’m in the good direction.

Since I’ll use Kratos FluidDynamic application for a part of my PhD  path, I started to test dome of its capabilities doing some benchmarks. In particular, I’m dealing with the Turek Benchmark on a 3d Cylinder. (You can find here the specification of the benchmark http://www.featflow.de/en/benchmarks/cfdbenchmarking/flow/dfg_flow3d/dfg_flow3d_configuration.html ). I’m running my analysis both on a Desktop Pc and a Cluster. On Desktop I’m using the 5.2.0 GiD-for-Kratos version while on the Cluser (Thanks to the help of @roigcarlo ) I’m using Kratos 5.1.0 .

## Benchmark Configuration

The domain is subdivided in three sub-volumes. At the inlet  and at the outlet a coarser mesh is employed. Around the cylinder and in the near wake a finer mesh is employed. In the following Fig. you can see the domain subdivision. In order to have a very regular mesh on the face of the cylinder I employed a 3D Boundary layer mesh. It’s  size is defined according to the calculation of y+. For the quantities involving the benchmark, the “a posteriori” y+ = 1 is equal to 0.0052 m. Therefore, the boundary layer is created with two layer of 0.0026 m (grow factor = 1) while the line-size and the surface size on the cylinder are set to 0.0052 m. The oder mesh dimension are a little coarser in order to limit the number of elements in the final mesh. The mesh on the cylinder and the boundary layer remain constant in the various simulations while the edge of the inner volume are progressively refined.

![image](https://user-images.githubusercontent.com/33176611/36124900-2d1341d2-1052-11e8-9eb6-2ed6cac72883.png)
![image](https://user-images.githubusercontent.com/33176611/36124906-30f62968-1052-11e8-8fad-81a81e77fe68.png)

Two different, even if very similar, refinement approach are employed (the difference lies in the mesh size of the two surfaces that are above and below the cylinder). 
The following tables show the specification of the different runs.

![ciao jnp](https://user-images.githubusercontent.com/33176611/36125139-25aa8300-1053-11e8-85bd-9fd37a567b35.png)

## Results

The results are presented in terms of drag and lift comparison.
I was naively expecting a progressive improvement of the results trough the different runs with progressively refined mesh. However, while the first runs shown an improvement in both drag and lift detection, the lasts (and therefore, more refined meshes) give quite bad results, especially for the lift. 
In particular, the results of run2 and run5 left me puzzled. They slight differ only in the mesh size of the  the two surfaces that are above and below the cylinder but give a totally different result. Moreover, the result given by run5 is even worst than the one get with run4 (same mesh but coarser). Since the “ refinement type 1” showed better results, I hoped that run3 would have given better results.. but “unfortunately” run2 is still the best try even with nearly 1 million element less. 
And finally, run6 seems to go literally crazy.

From my pour judgment (I am a newbie in this field) the meshes looks all relatively regular, in particular near the cylinder. Also, the post-processed results doesn’t seems to differ, at least not enough to explain such differences.

### run1
![image](https://user-images.githubusercontent.com/33176611/36125165-42da7ae8-1053-11e8-9678-2017fbabb163.png)

### run2
 ![image](https://user-images.githubusercontent.com/33176611/36125171-458255ea-1053-11e8-900d-3cbcb2629ae2.png)

### run3
![image](https://user-images.githubusercontent.com/33176611/36125176-488ce9f8-1053-11e8-9ef7-0d1573458a24.png)
 
### run4
 ![image](https://user-images.githubusercontent.com/33176611/36125180-4c37d8ba-1053-11e8-8b7b-374267f8abee.png)

### run5
![image](https://user-images.githubusercontent.com/33176611/36125187-4ec73684-1053-11e8-963d-c8651da85366.png)

### run6
 ![image](https://user-images.githubusercontent.com/33176611/36125190-519ece62-1053-11e8-9bbc-113dcced8498.png)

The following Figs. Shows one of the meshes in the case of run5 and the setup of the simulations

![image](https://user-images.githubusercontent.com/33176611/36125208-5d336ddc-1053-11e8-8410-c43b3af8030c.png)
![image](https://user-images.githubusercontent.com/33176611/36125214-615dbb6a-1053-11e8-81b5-d38a6e02d333.png)

Do you think there is something wrong in the approach or am I misreading something for example?
Any suggestion/ help will be appreciated.

Thank you very much in advance for your patience and help.

P.s. following the Project-parameter of the simulations.

Off-Topic:
In addition, comparing the results obtained on cluster and on Desktop with exactly the same simulation (remember: different version of Kratos, 5.1 on Cluster, 5.2 on Desktop) I causally found out that the drag file generated on Desktop made by nearly the triple of the steps than the one generated on Cluster (OpenMP run with 72 Cores). Is it normal? Or is somethin related to the Kratos version?

**Comment by maceligueta** [comment]
@KratosMultiphysics/fluid-dynamics ?

**Comment by RiccardoRossi** [comment]
@fdifrison the only thing i can think of is that even though you globally have more elements, your element distribution is not nice in the vicinity of the cylinder, which is the area which matters.

can u show a detail of the mesh if you cut your domain through the center of the cylinder? this would allow assessing if my impression may be correct or not

regarding the number of steps being different... if you run exactly the same settings everywhere do you get the same number of steps?

**Comment by fdifrison** [comment]
@RiccardoRossi Thanks for your reply.

Here some pictures from run2 (that seems to have a good trend) and run5 (more refined but with very bad lift values)
The first 2 pictures are vertical cut in the mid of the cylinder and are needed to understand the position of the horizontal cuts (that are at 1/2H , 1/4H , 1/8H, where H is the height of the cylinder)

### Vertical cut of run2
![cut_run2](https://user-images.githubusercontent.com/33176611/36493352-af467730-172f-11e8-8d46-c9d713624471.png)

### Vertical cut of run5
![cut_run5](https://user-images.githubusercontent.com/33176611/36493346-aa53fca2-172f-11e8-9d1d-c26ee1189506.png)

Following the horizontal cut:

### 1st Horizontal Cut run2
![cut_1_2_run2](https://user-images.githubusercontent.com/33176611/36493489-07907eea-1730-11e8-83a3-afb2dd8ff703.png)

### 1st Horizontal Cut run5
![cut_1_2_run5](https://user-images.githubusercontent.com/33176611/36493503-0f4dbee0-1730-11e8-9f17-2466d3af9798.png)

### 2st Horizontal Cut run2
![cut_1_4_run2](https://user-images.githubusercontent.com/33176611/36493511-1650cf70-1730-11e8-9068-da098b0c6723.png)


### 2st Horizontal Cut run5
![cut_1_4_run5](https://user-images.githubusercontent.com/33176611/36493523-1bff38ee-1730-11e8-9f9e-599ddd585f4d.png)

### 3st Horizontal Cut run2
![cut_1_8_run2](https://user-images.githubusercontent.com/33176611/36493535-225e306e-1730-11e8-9706-323f616a0372.png)

### 3st Horizontal Cut run5
![cut_1_8_run5](https://user-images.githubusercontent.com/33176611/36493539-26c6742c-1730-11e8-95bc-7d6a1c41782b.png)


Regarding the different number of step: If I run the exactly same simulation on cluster and on Desktop I have a totally different number of step

**Comment by RiccardoRossi** [comment]
@fdifrison none of those examples actually employ a Boundary Layer mesh... in this conditions since your mesh is very large i simply think you can take no conclusion whatsoever on which result should be best, **since your mesh is simply quite bad in the vicinity of the cylinder**.
If you want to have reproducibly good results, please do mesh the boundary layers with some - at least 2-3 layers of "structured" elements in the vicinity of the surface. This implies that you should see a "structured" patter without any interruption in the surrounding of the cylinder. If you do not see this, the boundary layer mesh generation was not correct...

regarding the number of steps, are u prescribing the time step to be used or are you selecting an automatic time stepping? In principle the drag should be plotted once per time step... so if you have more timesteps it means it is using a different dt.
Other than that we most probably did change something about the dt estimator, so this may result in the difference you see.

**Comment by RiccardoRossi** [comment]
closing as inactive for quite a while. let's reopen if there are changes on this
