### ISSUE TITLE
Problem in TotalStructuralMassProcess

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1492]
I use the new process to calculate the mass of my case
The problem I had was that I get different results before and after the calculation. This is because the Geometry functions (e.g. `Length`, `Area` etc) always refer to the current configuration, which in a problem for this process.
I am not sure how to solve this but I think we should be aware of this problem.

@KratosMultiphysics/technical-committee  maybe it would be good to have for these functions also the Initial-Configuration Counterpart. I think this would also be useful for other applications.

**Comment by loumalouomega** [comment]
Maybe the easiest way, and the one that requires the less quantity of modifications in the API is to create an auxiliary geometry with the original configuration

**Comment by maceligueta** [comment]
@loumalouomega , can you clarify a bit more your idea? Would you add new methods or not? Where would this auxiliary geometry go?

**Comment by loumalouomega** [comment]
@pooyan-dadvand Suggested to move coordinates and restore them later

@maceligueta I was suggesting create new methods

**Comment by pooyan-dadvand** [comment]
Just to clarify that I was suggesting a workaround and not a solution. 

The problem is that geometry does not have a clone method and a solution would be to add one.
