### ISSUE TITLE
Repeated defines in shell elements

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1509]
```C++
#define OPT_NUM_NODES
#define OPT_STRAIN_SIZE
#define OPT_NUM_DOFS
```

These defines are multiple times defined across different shell elements in StructuralMechanics application.

A possible solution for this would be to use a `static constexpr` inside the header of the element to store the values and then using it from its class:

Header file:
```C++
class ShellThickElement3D3N : public Element {
    static constexpr int OPT_NUM_NODES = 3
    static constexpr int OPT_STRAIN_SIZE = 6
    static constexpr int OPT_NUM_DOFS = 18
    ... // rest of the class
}
```

Source file:
```C++
// This:
if (geom.PointsNumber() != OPT_NUM_NODES)

// Turns into this:
if (geom.PointsNumber() != ShellThickElement3D3N::OPT_NUM_NODES)
```

**Comment by philbucher** [comment]
Known, working on it. Thx for the reminder :)

**Comment by RiccardoRossi** [comment]
maybe it would be good to have the shell to be a template of those parameters

**Comment by philbucher** [comment]
I am working on a baseclass for the shells
Using the template then is a good idea, I will consider it
