### ISSUE TITLE
Adding debug check to ConstitutiveLaws when returning quantities

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1547]
@KratosMultiphysics/technical-committee @loumalouomega 
While debugging in #1545 I found out that the constitutive law does not check if its internal quantities are initialized when it returns them (see [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/constitutive_law.h#L408-L420))
This can lead to segfaults that are not nice to debug.
The methods for checking if the quantity has been initialized [are there](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/constitutive_law.h#L436-L448), but one would have to manually check every time.
Therefore I propose to add checks in debugging compilation, i.e. from:
~~~c
const Matrix& GetDeformationGradientF      () {return *mpDeformationGradientF;};
~~~

to 
~~~c
const Matrix& GetDeformationGradientF      () {
KRATOS_DEBUG_ERROR_IF_NOT(IsSetDeformationGradientF()) << "DeformationGradientF is not set!" << std::endl
return *mpDeformationGradientF;};
~~~

**Comment by loumalouomega** [comment]
Ok, I will added once I finish what I am doing

**Comment by philbucher** [comment]
I can do it too just wanted another opinion

**Comment by loumalouomega** [comment]
For me is correct (if the check is done just in debug)
