### ISSUE TITLE
Overwriting properties in the read_materials_process

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#1556]
I encountered some problems with the read_materials_process, because i still had some properties (non-empty) defined in my old .mdpa file.

I was overwriting property 1 (that was also defined in the mdpa), and forgot to define a necessary value (```THICKNESS```). Now as the ```THICKNESS``` was defined in the old mdpa, it was just copied, without me noticing it.

I was wondering if it would make sense that the read_materials_process throws a warning if it tries to overwrite a property that already has values defined.

A function at the property.h would be needed to do so:
```c++
    bool IsEmpty()
    {
        return (mData.IsEmpty() or mTable.IsEmpty());
    }
```

This one could be called in the read_materials_process.

Whats your opinion?

**Comment by philbucher** [comment]
To add: Armin refers [to this](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/read_materials_process.py#L124), here either an empty property is returned OR if a property with this ID is defined in the mdpa, then this property is returned.
After retrieving the (new or old) property one would throw a warning if it is not empty:
~~~py
if not prop.IsEmpty():
    KratosMultiphysics.Logger.PrintWarning("::[Reading materials process]:: ", "Property with ID", prop_id, "exists already and is not empty!")
~~~

This way the user could check if things are going as expected

**Comment by pooyan-dadvand** [comment]
For me `Isempty` should check by and not by or: 
```c++
    bool IsEmpty()
    {
        return (mData.IsEmpty() && mTable.IsEmpty());
    }
```
But about the procedure I would go for getting the existing one or new one and adding the new parameters to them in coherent way. (I know that right now is not technically possible but won't be difficult to achieved.) I'm saying this because then someone could put its tables in data file (in any format even hdf5) and just add few parameters in configuration file.

**Comment by armingeiser** [comment]
I agree for the check with AND instead of OR.

This warning would actually not affect that, and if someone wants to use the process to overwrite just a few, but not all settings, then he is aware of that.
It would just add some information, so in case one does not intend to extend/overwrite existing properties, he is able to tell what happens from the output.
Beeing able to define the same thing several times in the input seems risky to me, especially because here the order of operations needs to be known by the user, in order to properly create the input files.

```python
prop = model_part.GetProperties(property_id, mesh_id)
if not prop.IsEmpty():
    KratosMultiphysics.Logger.PrintWarning("::[Reading materials process]:: ", "Property with ID", prop_id, "exists already and is not empty!")
```

**Comment by RiccardoRossi** [comment]
@armingeiser  i see the merit in what you are telling.

What should happen in the case in which the property is not empty but the oeverweirint only affects variables that are not there?

**Comment by philbucher** [comment]
@pooyan-dadvand what you describe is what is currently being done.
The problem that @armingeiser had was that there were some old/wrong data in the mdpa (created some time ago, before the readmaterialprocess was there). He used this in combination with this process and forgot to specify one variable, for which it used the value defined in mdpa.
This went unnoticed and was nasty to figure out

**Comment by armingeiser** [comment]
I would not distinguish between adding/overwriting. As soon as a property is not empty and variables are added/modified, this simple warning would already help to know whats happening.

**Comment by pooyan-dadvand** [comment]
I understand the problem and I see that it is a source of suffering. But I'm not sure if we should leave it legal or not. Again I understand that @armingeiser is in favor of notification but considering my use case it would complain a legal thing which may confuse the end users. 

Just to clarify that I'm not saying a NO and it is not the first time that we avoid such things (for example in reading nodes with the same ID) but we should consider a larger set of use cases. @KratosMultiphysics/technical-committee do you have any opinion on this?

**Comment by RiccardoRossi** [comment]
on my side i don't have a strong opinion on this and i see your point, however i tend to back @armingeiser suggestion, since we are in the corner case in which the application of materials overwrites the properties

**Comment by philbucher** [comment]
Two more thoughts on this:
1. I would vote for at least some notification, it can also be an `Info` that just says that a non-empty property is being used. Having this going unnoticed can be dangerous also in other cases I guess (some "leftover" stuff in older mdpa files is not too uncommon I'd say)
2. for the usecase @pooyan-dadvand describes one could also add methods `Properties::HasVariables` or `Properties::HasTables` to specify a bit more

**Comment by jcotela** [comment]
Just a thought (maybe stupid): now that we have a constitutive law register, would we be able to generate the constitutive law from the mpda? I think it is kind of strange that most model part data can be passed through the mdpa but the constitutive law can not...

**Comment by pooyan-dadvand** [comment]
I completely agree with sending an `info` as suggested by @philbucher and having the additional methods would also be useful 

Also I like the idea of @jcotela about the reading directly the constitutive law.

**Comment by armingeiser** [comment]
So i will create a PR with the necessary changes to send this INFO.
