### ISSUE TITLE
We should throw an error if density is not provided

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1560]
Hi  @KratosMultiphysics/structural-mechanics 

here we default to density=1 in the case in which the density is not provided:

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_elements/base_solid_element.cpp#L354

i think we should throw an error instead...what do you think?

**Comment by loumalouomega** [comment]
I think that instead of an error a warning (now that we have the logger it is possible)

**Comment by RiccardoRossi** [comment]
@loumalouomega the logger should never be used within the element since it has a pretty heavy overhead. (i mean other than debugging).

Aside for the technicality, I do think that not providing the density and computing the mass matrix should trigger an error not just a warning

**Comment by loumalouomega** [comment]
Ok, good point

**Comment by loumalouomega** [comment]
Ping @KratosMultiphysics/structural-mechanics

**Comment by RiccardoRossi** [comment]
@loumalouomega the logger should never be used within the element since it has a pretty heavy overhead. (i mean other than debugging).

Aside for the technicality, I do think that not providing the density and computing the mass matrix should trigger an error not just a warning

**Comment by philbucher** [comment]
+1 for @RiccardoRossi suggestion

**Comment by PhilippeBussetta** [comment]
+1 for @RiccardoRossi  suggestion and we can do the same with the thickness -- by default thickness = 1.0

**Comment by loumalouomega** [comment]
I think that the case for the thickness is not the same, usually when plane strain is used you want to solve a problem for unitary deep (even when the hypothesis assumes infinite thickness)

**Comment by PhilippeBussetta** [comment]
Of course, but maybe we have to define the default value in the shell element -- closer that it is needed?

**Comment by philbucher** [comment]
The shells throw if thickness is not provided 

Also I agree with vicente

**Comment by loumalouomega** [comment]
Yes, but in this case we were speaking about solids, for shells I agree in adding a check

**Comment by philbucher** [comment]
The shells have the check already 

Also agree with you abt NOT adding the check to the solids for the reason you mentioned
