### ISSUE TITLE
AddSubModelPart makes no guarantees

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1568]
I believe we have an inconsistency with the AddSubModelPart function

Consider we create a submodelpart "sub" of say A, and we later add it to B. There is no guarantee that the nodes, elements etc of the sumodelpart added also belong to B. 
Furthermore, since the AddModelPart changes the parent of "sub" it will no longer correctly hold a pointer to its original father. 

I think we shall clarify this...

**Comment by RiccardoRossi** [comment]
just to say that the more i think about, the more i think we need to clarify owneship, particularly in view of adding everything automatically to the "Model"

**Comment by loumalouomega** [comment]
What do you suggest?

**Comment by RiccardoRossi** [comment]
Mmm, difficult question. The only way i see is to remove the function in question. I think we COULD define a function MigrateSubModelPart, but it would have to do something quite different

**Comment by loumalouomega** [comment]
Maybe we can do somethign similar to the parameters, where the functions RecursivelyValidateAndAssignDefaults() ensures the consistency in the tree

**Comment by philbucher** [comment]
@RiccardoRossi I believe you removed the `AddSubModelPartFunction` in the model-branch right?
Should I make a separate PR?

**Comment by philbucher** [comment]
is this solved?

**Comment by RiccardoRossi** [comment]
AddSubModelPart is deprecated from a while now. Also by grepping i get:

applications/HDF5Application/tests/test_utils.cpp:void TestModelPartFactory::AddSubModelParts()
Binary file clang_build/kratos/libKratosCore.so matches
Binary file clang_build/kratos/CMakeFiles/KratosCore.dir/sources/model_part.cpp.o matches
Binary file cmake_build/kratos/libKratosCore.so matches
Binary file cmake_build/kratos/CMakeFiles/KratosCore_unity.dir/cotire/KratosCore_CXX_unity_0_73.cxx.o matches
Binary file cotire_debug_build/kratos/libKratosCore.so matches
Binary file cotire_debug_build/kratos/CMakeFiles/KratosCore.dir/sources/model_part.cpp.o matches
Binary file debug_build/kratos/libKratosCore.so matches
Binary file debug_build/kratos/CMakeFiles/KratosCore_unity.dir/cotire/KratosCore_CXX_unity_0_82.cxx.o matches
Binary file debug_build/kratos/CMakeFiles/KratosCore_unity.dir/cotire/KratosCore_CXX_unity_0_64.cxx.o matches
Binary file debug_build/kratos/CMakeFiles/KratosCore.dir/sources/model_part.cpp.o matches
Binary file debug_build_old/kratos/libKratosCore.so matches
Binary file debug_build_old/kratos/CMakeFiles/KratosCore_unity.dir/cotire/KratosCore_CXX_unity_0_30.cxx.o matches
kratos/sources/model_part.cpp:KRATOS_DEPRECATED void ModelPart::AddSubModelPart(ModelPart& rThisSubModelPart)
kratos/sources/model_part.cpp://         mpParentModelPart->AddSubModelPart(pThisSubModelPart);
kratos/includes/model_part.h:    void AddSubModelPart(ModelPart& rThisSubModelPart);

so it looks like it is not included anywhere and we could remove it for good...BUT...i haven't done it, so this is not really closed
