### ISSUE TITLE
error in tests for StructuralMechanics

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1579]
Hi Guys,
     with today's tests we have:

Running tests for StructuralMechanicsApplication
....F..F...............................terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: DeformationGradientF is not set!

in kratos/includes/constitutive_law.h:425:const Matrix& ConstitutiveLaw::Parameters::GetDeformationGradientF()
   /home/rrossi/kratos_git/applications/StructuralMechanicsApplication/custom_elements/prestress_membrane_element.cpp:809:void PrestressMembraneElement::CalculateAll(Element::MatrixType&, Element::VectorType&, const ProcessInfo&, bool, bool)
   kratos/solving_strategies/schemes/residualbased_incrementalupdate_static_scheme.h:291:void ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::CalculateSystemContributions(Element::Pointer, ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemMatrixType&, ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType&, Element::EquationIdVectorType&, ProcessInfo&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; Element::Pointer = boost::shared_ptr<Element>; ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemMatrixType = boost::numeric::ublas::matrix<double>; ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType = boost::numeric::ublas::vector<double>; Element::EquationIdVectorType = __debug::vector<long unsigned int>]

**Comment by philbucher** [comment]
Is that from your machine?
Test are running on my machine and also the nughtly report was clean

**Comment by loumalouomega** [comment]
Which test in particular?

**Comment by RiccardoRossi** [comment]
hi @philbucher yes, i just checked out the master branch and compiled in "superdebug".

with the -v 2 option i get:

test_thick_shell_quadrilateral (test_patch_test_shells_orthotropic.TestPatchTestShellsOrthotropic) ... FAIL
[...]
test_thin_shell_triangle (test_patch_test_shells_orthotropic.TestPatchTestShellsOrthotropic) ... FAIL
[...]
test_execution (NightlyTests.Fofi4PointTentnoCableTests) ... terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: DeformationGradientF is not set!

**Comment by philbucher** [comment]
What is „superdebug“?

**Comment by RiccardoRossi** [comment]
FullDebug + -D_GLIBCXX_DEBUG

**Comment by philbucher** [comment]
@RiccardoRossi are you sure this is the latest version of Master? It looks to me like you have the version before I merged #1545 (i.e. before yesterday) Before this merge these tests were failing with the error messages you posted

I tried this with the current version of the master and I didn't get any error

(BTW am I adding `-D_GLIBCXX_DEBUG` at the right position, I added it to the `DCMAKE_CXX_FLAGS` ?:
`-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -D_GLIBCXX_DEBUG -std=c++11 -march=native -ftree-vectorize -funroll-loops -ffast-math -Wall -Wno-unused-local-typedefs" \`
Also do I have to set sth else or recompile also boost with this?)

**Comment by philbucher** [comment]
ping @RiccardoRossi

**Comment by RiccardoRossi** [comment]
@philbucher yes, it is to be added in he cmake_cxx_flags 

i do believe i have it merged. However if i am the only one with the problem it definitely looks like i have something wrong on my machine

**Comment by philbucher** [comment]
ok

I will close this, please reopen if the error persists
