### ISSUE TITLE
GaussPointContainer might write wrong results

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1590]
Hi @KratosMultiphysics/technical-committee 
In the `GidGaussPointsContainer` the elements/conditions are looped and the results are written to the file.
The problem with this is that in case an element does not implement the `GetValueOnIntegrationPoints` method the results from the previous element/condition is being used!

For a better explanation here is what I mean
~~~
result container is being initialized
element #1 writes the results from GetValueOnIntegrationPoints to the result container
Results are being written (with result container)

now element #2 calls the method but it is not implemented, so it doesn't overwrite the results (i.e. results container is not overwritten)!
Results are being written (with result container still containing the results form element #1)
~~~

One way of avoiding this would be to reset the result container after each element/condition, but ofc this would be very expensive

Other than that I don't have any suggestion, just wanted to make you aware of this

**Comment by loumalouomega** [comment]
The methods of the base clase are empty 

![imagen](https://user-images.githubusercontent.com/19991680/36892591-855f104e-1e05-11e8-9dcf-b3670ca5db33.png)

Maybe we can define it as zero returning for each type, and let the derived elements to override the methods

**Comment by loumalouomega** [comment]
Besides the Doxygen Cleaning of the base classes is pending

**Comment by philbucher** [comment]
but this also does not work if your element overrides but it does not provide output for the requested variable
=> then again the old results are being used

**Comment by loumalouomega** [comment]
Well, but in that case the fault is the derived element implementation, you should at least return an zero solution (yes I know that I have some bad implementations respecting that, I would correct that eventually)

**Comment by pooyan-dadvand** [comment]
I think the solution would be to write only the element provides a non empty vector (or even better a vector with correct size) as results. And if not don't write neither the element id nor the vector. There wasn't a similar issue sometime ago?

**Comment by philbucher** [comment]
@loumalouomega this is also error prone for the reasons you are pointing out but would be a compromise btw performance and error probability

@pooyan-dadvand this would only work for vectors and matrices and yes there was an issue for this, but now I realized that is was just a hacky fix #727

**Comment by pooyan-dadvand** [comment]
A correct solution would be to have a `HasVariableOnIntegrationPoint` method for element but introducing it would be a huge work. So I'm not sure what would be the optimum solution

**Comment by msandre** [comment]
I think a more general solution would be required to exterminate this bug (not strictly related to gauss point container). I've made essentially the same bug in a subclass of scheme, which was hidden for some months until someone changed the way a matrix was initialized in an omp thread in the builder and solver. The problem is with the way we pass out parameters uninitialized to our functions.  `clear()` or `std::fill(v.begin(), v.end(), zero)` before each call or some sort of static analysis for functions that have unused non-const ref params might help.

**Comment by philbucher** [comment]
Closing and adding the `wontfix` label, I don't think this can be fixed without a major refactor
In VTK this is handled by writting EITHER elements or conditions, I don't think it is possible/a good idea to do both at the same time, esp if they overlap
