### ISSUE TITLE
Error when porting to pybind11

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1598]
@KratosMultiphysics/structural-mechanics guys, when porting to pybind i get a number of errors which i believe are actually mistakes of the current implementation which are correctly detected by pybind but not by the current boost python interface. I'll attach here the error list (i actually think it is always the same error repeated many times)

could you take a look?

test_execution (NightlyTests.SDTwoDShearQuaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/small_disp/patch_test_2D_shear_qua_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.SDTwoDShearTriPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/small_disp/patch_test_2D_shear_tri_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.SDTwoDTensionQuaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/small_disp/patch_test_2D_tension_qua_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.SDTwoDTensionTriPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/small_disp/patch_test_2D_tension_tri_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.SDThreeDShearHexaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/small_disp/patch_test_3D_shear_hexa_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.SDThreeDShearTetraPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/small_disp/patch_test_3D_shear_tetra_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.SDThreeDTensionHexaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/small_disp/patch_test_3D_tension_hexa_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.SDThreeDTensionTetraPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/small_disp/patch_test_3D_tension_tetra_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.TLTwoDShearQuaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/total_lagrangian/patch_test_2D_shear_qua_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.TLTwoDShearTriPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/total_lagrangian/patch_test_2D_shear_tri_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.TLTwoDTensionQuaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/total_lagrangian/patch_test_2D_tension_qua_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.TLTwoDTensionTriPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/total_lagrangian/patch_test_2D_tension_tri_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.TLThreeDShearHexaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/total_lagrangian/patch_test_3D_shear_hexa_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.TLThreeDShearTetraPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/total_lagrangian/patch_test_3D_shear_tetra_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.TLThreeDTensionHexaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/total_lagrangian/patch_test_3D_tension_hexa_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.TLThreeDTensionTetraPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/total_lagrangian/patch_test_3D_tension_tetra_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ULTwoDShearQuaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/updated_lagrangian/patch_test_2D_shear_qua_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ULTwoDShearTriPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/updated_lagrangian/patch_test_2D_shear_tri_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ULTwoDTensionQuaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/updated_lagrangian/patch_test_2D_tension_qua_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ULTwoDTensionTriPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/updated_lagrangian/patch_test_2D_tension_tri_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ULThreeDShearHexaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/updated_lagrangian/patch_test_3D_shear_hexa_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ULThreeDShearTetraPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/updated_lagrangian/patch_test_3D_shear_tetra_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ULThreeDTensionHexaPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/updated_lagrangian/patch_test_3D_tension_hexa_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ULThreeDTensionTetraPatchTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='patch_test/updated_lagrangian/patch_test_3D_tension_tetra_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.SprismMembranePatchTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='sprism_test/patch_membrane_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.SprismBendingPatchTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='sprism_test/patch_bending_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.Fofi4PointTentnoCableTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='formfinding_test/Fofi_4Point_Tent_noCable_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.Fofi4PointTentCableTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='formfinding_test/Fofi_4Point_Tent_Cable_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.MembraneQ4PointLoadTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='membrane_test/Membrane_Q4_PointLoad_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.MembraneQ4TrussPointLoadTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='membrane_test/Membrane_Q4_Truss_PointLoad_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.Simple3D2NTrussDynamicTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='truss_test/dynamic_3D2NTruss_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.Simple3D2NTrussLinearTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='truss_test/linear_3D2NTruss_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.Simple3D2NTrussTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='truss_test/nonlinear_3D2NTruss_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.Simple3D2NBeamCrTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='beam_test/nonlinear_3D2NBeamCr_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.Simple3D2NBeamCrLinearTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='beam_test/linear_3D2NBeamCr_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.Simple3D2NBeamCrDynamicTest) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='beam_test/dynamic_3D2NBeamCr_test_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ShellT3IsotropicLinearStaticStructScordelisLoRoofTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='shell_test/Shell_T3_isotropic_linear_static_struct_scordelis_lo_roof_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ShellT3AndQ4LinearStaticStructScordelisLoRoofTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='shell_test/Shell_T3andQ4_linear_static_struct_scordelis_lo_roof_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ShellT3AndQ4LinearStaticStructPinchedCylinderTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='shell_test/Shell_T3andQ4_linear_static_struct_pinched_cylinder_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ShellT3AndQ4LinearStaticStructPinchedHemisphereTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='shell_test/Shell_T3andQ4_linear_static_struct_pinched_hemisphere_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()
test_execution (NightlyTests.ShellT3AndQ4NonLinearStaticStructHingedCylRoofSnapthroughTests) ... ERROR

Stdout:
 ::[MechanicalSolver]::  Construction finished
/home/rrossi/compiled_libraries/PythonDebug/lib/python3.6/unittest/case.py:633: ResourceWarning: unclosed file <_io.TextIOWrapper name='shell_test/Shell_T3andQ4_nonlinear_static_struct_hinged_cyl_roof_snapthrough_parameters.json' mode='r' encoding='UTF-8'>
  outcome.errors.clear()

**Comment by philbucher** [comment]
I think I know what this is, I will push to your branch so that you can try it

**Comment by philbucher** [comment]
I pushed, can you please try?

**Comment by RiccardoRossi** [comment]
are u sure you pushed? i get nothing...

btw, the branch is "origin/switching_to_std_pointer"

**Comment by RiccardoRossi** [comment]
to my understanding the optimizer will remove this, since if(false) can be evaluated at compile time

**Comment by philbucher** [comment]
I pushed, it even shows up in your PR

**Comment by RiccardoRossi** [comment]
ok, you are right, i get a different error, related to the logger now. 

this is something on my side. thx!

**Comment by philbucher** [comment]
You are welcome
(And lucky I had a very similar error yesterday)
