### ISSUE TITLE
StructuralMechanics - WorkingSpaceDimension - CLs

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#1609]
Hi @KratosMultiphysics/structural-mechanics 

a function `WorkingSpaceDimension()` is implemented into the CLs
> hyper_elastic_isotropic_kirchhoff_3d
> hyper_elastic_isotropic_kirchhoff_plane_strain_2d
> hyper_elastic_isotropic_kirchhoff_plane_stress_2d
> hyper_elastic_isotropic_neo_hookean_3d
> hyper_elastic_isotropic_neo_hookean_plane_strain_2d

but not into the other CLs (e.g. linear_plane_stress)

Would we check the dimension using this function, we have to add into all the CLs or it remove from HyperElastic CLs?
This function is really necessary?

**Comment by loumalouomega** [comment]
We are right discussing about this, because the information is already defined and then duplicated, but some processes and tests require right now this method in order to work. So as I said we are in process of discussion right now.

**Comment by PhilippeBussetta** [comment]
Great.
For example, the tests of `constitutive_law_test.py` used this function to check the dimension of the CLs.
First, I am extending these test to linear elastic CLs without testing it. I don't think that it is necessary in this particular case but I can add the function.

**Comment by jcotela** [comment]
From the point of view of the FluidDynamics, the `WorkingSpaceDimension()` function is pretty much mandatory for us. We use it in the `Element::Check()` method to ensure that the dimension of the element and of the provided CL match. Otherwise, in the past it was common for us to get weird memory errors due to mismatched matrix sizes when a 2D law was wrongly used to initialize a 3D element or vice-versa.

**Comment by RiccardoRossi** [comment]
+1 for @jcotela 's comment. Also we should use it more extensively in the checks of the StructuralMechanics

**Comment by RiccardoRossi** [comment]
one last comment before closing: plane strain is a 2D test case, however it can be implemented with 3 or 4 strain components. this is actually something to be discussed, isn't it @marandra ?
