### ISSUE TITLE
Undefined Symbol in FluidDynamiApplication

### ISSUE THREAD

**Issue by fdifrison** [KratosMultiphysics/Kratos#1613]
Hi @rubenzorrilla,

seems we've found another error. Hope it can help.
Same conditions as the other error:
-pulled kratos (on another machine)
-recompiled
-pulled gidForKratos
-Opened the 2dCylinder test, meshed and lunched

Traceback (most recent call last):
  File "MainKratos.py", line 4, in <module>
    from KratosMultiphysics.FluidDynamicsApplication import *
  File "/home/bestofdicea/GiD/gid13.1.9d-x64/./problemtypes/kratos.gid/exec/Kratos/KratosMultiphysics/FluidDynamicsApplication.py", line 2, in <module>
    from KratosFluidDynamicsApplication import *
ImportError: /home/bestofdicea/Kratos/libs/KratosFluidDynamicsApplication.so: cccccc _ZN6Kratos16KratosComponentsINS_8VariableIjEEE12msComponentsE

**Comment by jcotela** [comment]
Hi @fdifrison I cannot reproduce your error using the current kratos master. Are you sure everything compiled correctly?

@rubenzorrilla: for our reference, the linking error in human-readable format points to
`Kratos::KratosComponents<Kratos::Variable<unsigned int> >::msComponents`

**Comment by fdifrison** [comment]
Hi @jcotela, the only thing I did that was new for me was to update the compiler from 5.4 to 7 (updating the link in /urs/bin/gcc ...). I did this because, before that, I had another error at the beginning of the simulation:
terminated called recursively
Aborted (core dumped)

Therefore, I pulled Kratos to see if there were any changes, updated gcc and recompiled.. but no error showed up during the compilation. At this point it is probably something wrong I made the update?

Thanks for your help

**Comment by jcotela** [comment]
If you changed compiler versions, it might be that there are some old files (compiled with the older gcc) remaining somewhere. To be safe, I'd recommend deleting the libs folder inside kratos (don't worry, everything will be re-created when you do make install next) and then re-compile kratos from scratch: first `make clean` then run the configure script.

**Comment by fdifrison** [comment]
Solved! Thanks
