### ISSUE TITLE
Periodic boundary conditions in fluids

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#1618]
Good morning @jcotela, I have heard that there is a way of imposing periodic boundary conditions in the fluid problems. Could you please let me know how this can be done?

Thank you!

**Comment by jcotela** [comment]
Hi @playpaolo currently we have some basic support for periodic boundary conditions,  but the tricky part is that you need to have matching meshes on the two periodic faces. When generating your mesh, you need to add line conditions (of type PeriodicCondition) between each node pair, and those can be used by the solver to impose periodic values for your variables.

In GiD, this can be achieved by generating a 'separated contact volume' (geometry-> create-> contact-> separated volume) between the two periodic faces and meshing that volume with lines. If you want more detalied help in generating the model, just write me an email or maybe we can arrange a skype call.
