### ISSUE TITLE
link to Kratos distribution lists

### ISSUE THREAD

**Issue by antonialarese** [KratosMultiphysics/Kratos#1619]
I am unable to find the link to join the Kratos community and receive the notifications of the nightly build, etc....
Is there also the Kratos Github list? I don0t remember.
The only link I find on the front page of the wiki is the slack one (which could also be more hidden.....)

**Comment by roigcarlo** [comment]
Should be the same as always, we haven't changed that. I will put it a more
visible place.

About the slack, that should not be public at all...

**Comment by roigcarlo** [comment]
It was here:
http://listas.cimne.upc.edu/cgi-bin/mailman/listinfo/kratos

But it no longer works. I am afraid I cannot fix this. @pooyan-dadvand I think we have to ask to IT guys...

**Comment by josep-m-carbonell** [comment]
https://listas.cimne.upc.edu/mailman/listinfo/kratos
https://listas.cimne.upc.edu/pipermail/kratos/

**Comment by roigcarlo** [comment]
@josep-m-carbonell thx!

**Comment by antonialarese** [comment]
@josep-m-carbonell and @roigcarlo Thanks!
