### ISSUE TITLE
failing test (it looks like it is about tolerance)

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1623]
@KratosMultiphysics/structural-mechanics 

we still have one failing test to address. 

======================================================================
FAIL: test_execution (NightlyTests.ShellQ4ThickDrillingRollUpTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/rrossi/kratos_git/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 42, in test_execution
    self.test.Solve()
  File "/home/rrossi/kratos_git/applications/StructuralMechanicsApplication/tests/Kratos_Execute_Structural_Test.py", line 114, in Solve
    process.ExecuteFinalizeSolutionStep()
  File "/home/rrossi/kratos_git/kratos/python_scripts/from_json_check_result_process.py", line 140, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking node " + str(node.Id) + " " + variable_name + " results."))
AssertionError: False is not true : 45524.884702802636 != 45525.59393114783, rel_tol = 1e-06, abs_tol = 0.001 : Error checking node 2 REACTION_X results.

Stdout:
Computing model part:
-computing_domain- model part
    Number of tables : 0
    Number of sub model parts : 0

    Mesh 0 : 
        Number of Nodes      : 243
        Number of Properties : 5
        Number of Elements   : 160
        Number of Conditions : 1

**Comment by philbucher** [comment]
I know abt this, this tests is deprecated and I will remove it soon (I refactored the entire shell testing bcs it is slow)

There are several other issues with the shells anyway that I will address in a PR soon

**Comment by RiccardoRossi** [comment]
ok thx. Maybe we could just remove it for the release. Your choice... for now i close this comment

**Comment by philbucher** [comment]
I removed it in #1624, you could also approve, it is a very minor cleanup

**Comment by philbucher** [comment]
btw when do you plan to make the release?

**Comment by RiccardoRossi** [comment]
asap ...
