### ISSUE TITLE
How set velocity

### ISSUE THREAD

**Issue by sarti-luca** [KratosMultiphysics/Kratos#1625]
Hi @rubenzorrilla 

How can I fix the velocity to some lines?
Since in GiD there isn't this function I added to the Projectparameters the following lines to the group "perimeter" previously created by GiD.

        "python_module" : "assign_vector_variable_process",
        "kratos_module" : "KratosMultiphysics",
        "help"          : "This process fixes the selected components of a given vector variable",
        "process_name"  : "AssignVectorVariableProcess",
        "Parameters"    : {
            "mesh_id"         : 0,
            "model_part_name" : "VelocityConstraints3D_perimeter",
            "variable_name"   : "VELOCITY",
            "constrained"     : [true,true,true],
            "value"           : [0.0,0.0,0.0],
            "interval"        : [0.0,"End"]

I also added the "VelocityConstraints3D_perimeter" to the "no_skin_parts"
However, running the MainKratos I got this error:

     RuntimeError: Error: There is no sub model part with name : VelocityConstraints3D_perimeter

What I'm doing wrong?
Thanks for your help

Luca

**Comment by RiccardoRossi** [comment]
Dear Luca, the error message is telling it  ... you don't have a submodelpart with name 

VelocityConstraints3D_permiter

to see the list of submodelparts you can do

      print(Model)

**Comment by sarti-luca** [comment]
@RiccardoRossi I switched to the developer mode on GiD and the velocity constraints option appeared among the conditions. So the problem is solved. 
Thanks

**Comment by RiccardoRossi** [comment]
good. @jginternational can u take a look if we have an error when the developer mode is off?
