### ISSUE TITLE
FRACTIONAL_STEP index: 0

### ISSUE THREAD

**Issue by sarti-luca** [KratosMultiphysics/Kratos#1628]
Hi @rubenzorrilla, @jcotela,

I've updated Kratos in order to fix the drag for fractional step but it seems to have a similar problem.
The version I used is 5.3.0-da43f58

I got this error only when I compute the drag file with fractional step scheme.

> *** Error in `/home/bestofdicea/GiD/gid13.1.9d-x64/./problemtypes/kratos.gid/exec/Kratos/runkratos': double free or corruption (!prev): 0x00000000013f46b0 ***
> *** Error in `/home/bestofdicea/GiD/gid13.1.9d-x64/./problemtypes/kratos.gid/exec/Kratos/runkratos': double free or corruption (!prev): 0x00000000013f46b0 ***
> ======= Backtrace: =========
> ======= Backtrace: =========
> /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f73fb3be7e5]
> terminate called after throwing an instance of 'Kratos::Exception'
> /lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7f73fb3be7e5]
>   what():  Error: Unexpected value for FRACTIONAL_STEP index: 0
> 
> 
> in /home/bestofdicea/Kratos/applications/FluidDynamicsApplication/custom_elements/fractional_step.cpp:53:void FractionalStep<TDim>::CalculateLocalSystem(FractionalStep<TDim>::MatrixType&, FractionalStep<TDim>::VectorType&, ProcessInfo&) [with unsigned int TDim = 2; FractionalStep<TDim>::MatrixType = boost::numeric::ublas::matrix<double>; FractionalStep<TDim>::VectorType = boost::numeric::ublas::vector<double>]
>    /home/bestofdicea/Kratos/applications/FluidDynamicsApplication/custom_elements/fractional_step.cpp:57:void FractionalStep<TDim>::CalculateLocalSystem(FractionalStep<TDim>::MatrixType&, FractionalStep<TDim>::VectorType&, ProcessInfo&) [with unsigned int TDim = 2; FractionalStep<TDim>::MatrixType = boost::numeric::ublas::matrix<double>; FractionalStep<TDim>::VectorType = boost::numeric::ublas::vector<double>]
> terminate called recursively
> /lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7f73fb3c737a]

What could be the problem?
Thanks for your help

Luca

**Comment by jcotela** [comment]
@sarti-luca we have just fixed some issues related to this in #1631. Please update your kratos and try again.

**Comment by sarti-luca** [comment]
@jcotela I'm updating. Thanks.

**Comment by RiccardoRossi** [comment]
this should be resolved as of now. reopen if i got it wrong
