### ISSUE TITLE
Compile error with CLANG

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#1634]
I am getting the following error when compiling:

```
[ 31%] Building CXX object kratos/CMakeFiles/Kratos.dir/python/add_amgcl_solver_to_python.cpp.o
In file included from /Users/marcelo/Projects/Kratos/kratos/python/add_amgcl_solver_to_python.cpp:31:
In file included from /Users/marcelo/Projects/Kratos/kratos/linear_solvers/amgcl_solver.h:43:
In file included from /Users/marcelo/Projects/Kratos/external_libraries/amgcl/runtime.hpp:53:
/Users/marcelo/Projects/Kratos/external_libraries/amgcl/solver/bicgstabl.hpp:345:56: error: call to 'real' is ambiguous
                    scalar_type kappa0 = sqrt(std::abs(std::real(dot0)));
                                                       ^~~~~~~~~
```
macOS 10.13.3
CMake 3.8.2.
Apple LLVM version 9.0.0 (clang-900.0.39.2)

and the flags set:
-DCMAKE_C_COMPILER="/usr/local/bin/clang-omp"
-DCMAKE_CXX_COMPILER="/usr/local/bin/clang-omp++"
-DCMAKE_C_FLAGS=" -msse3 "
-DCMAKE_CXX_FLAGS=" -msse3 -std=c++11 "
-DCMAKE_MACOSX_RPATH="~/Projects/kratos/libs"
-DCMAKE_INSTALL_RPATH="~/Projects/kratos/libs"
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE
-DBOOST_ROOT="~/Apps/boost"
-DPYTHON_LIBRARY="/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/Python"
-DPYTHON_INCLUDE_DIR="/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/include/python3.6m"
-DLAPACK_LIBRARIES="/usr/lib/liblapack.dylib"
-DBLAS_LIBRARIES="/usr/lib/libblas.dylib"
-DSTRUCTURAL_MECHANICS_APPLICATION=ON
-DEXTERNAL_SOLVERS_APPLICATION=OFF
-DINSTALL_EMBEDDED_PYTHON=OFF

**Comment by roigcarlo** [comment]
@marandra could you try to comment these lines:

https://github.com/KratosMultiphysics/Kratos/blob/master/external_libraries/amgcl/solver/bicgstabl.hpp#L78-L81

**Comment by marandra** [comment]
@roigcarlo commenting that block out fixed the issue. I compiled External Solvers Application and the Structural Mechanics Application tests pass.

**Comment by roigcarlo** [comment]
:+1: Sorry not to answer you before, I forgot about it. I will speak with the dev of amgcl as well to let him know. That part should probably be behind a ward for C++11

**Comment by marandra** [comment]
@roigcarlo no worries! thanks for your help
