### ISSUE TITLE
KRATOS INSTALL ERROR

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#164]
Hello everyone, I already have a KRATOS developers version on my computer which I am currently using to work on. It is the version of KRATOS before you moved to GitHub. So I am trying to install the current master version. After cloning the Code I used the configure.bat file I already used to install the previous verion: 

del CMakeCache.txt
:: this is an example file...please DO NOT MODIFY if you don't want to do it for everyone
:: to use it, copy it to another file and run it

cls

:: you may want to decomment this the first time you compile
del CMakeCache.txt

cmake -G "Visual Studio 14 2015 Win64"                                              ^
-DCMAKE_BUILD_TYPE=Release                                                          ^
-DCMAKE_CXX_FLAGS=" -D_SCL_SECURE_NO_WARNINGS "                                     ^
-DBOOST_ROOT="C:\boost_1_59_0"                                                      ^
-DPYTHON_LIBRARY="C:\Python33\libs\python33.lib"                                    ^
-DPYTHON_INCLUDE_PATH="C:\Python33\include"                                         ^
-DLAPACK_LIBRARIES="C:\external_libraries\liblapack.lib"                            ^
-DBLAS_LIBRARIES="C:\external_libraries\libblas.lib"                                ^
-DMESHING_APPLICATION=ON                                                            ^
-DEXTERNAL_SOLVERS_APPLICATION=ON                                                   ^
-DPFEM_APPLICATION=ON                                                               ^
-DSTRUCTURAL_MECHANICS_APPLICATION=ON                                                         ^
-DCONVECTION_DIFFUSION_APPLICATION=ON                                               ^
-DFLUID_DYNAMICS_APPLICATION=ON                                                     ^
-DALE_APPLICATION=ON                                                                ^
-DFSI_APPLICATION=ON                                                                ^
-DDEM_APPLICATION=OFF                                                               ^
-DSWIMMING_DEM_APPLICATION=OFF                                                      ^
-DINSTALL_PYTHON_FILES=ON                                                           ^
-DINSTALL_EMBEDDED_PYTHON=ON                                                        ^
-DEXCLUDE_ITSOL=ON                                                                  ^
-DSOLID_MECHANICS_APPLICATION=ON                                                    ^
-DKRATOS_INSTALL_PREFIX="C:\KRATOS_CLONE\KratosInstallNew"                                          ^
..

this file runs smoothly without any errors. But when I try to install it within VS2015 I get the following errors:
1.)  
Syntax error in cmake code at
24>
24>      C:/KRATOS_CLONE/Kratos/cmake_build/cmake_install.cmake:5
24>
24>    when parsing string
24>
24>      C:\KRATOS_CLONE\KratosInstallNew
24>
24>    Invalid escape sequence \K
24>
24>    Policy CMP0010 is not set: Bad variable reference syntax is an error.  Run
24>    "cmake --help-policy CMP0010" for policy details.  Use the cmake_policy
24>    command to set the policy and suppress this warning.
24>  This warning is for project developers.  Use -Wno-dev to suppress it.

2.) 
 CMake Error at applications/PFEMapplication/cmake_install.cmake:46 (file):
24>    file INSTALL cannot find
24>    "C:/KRATOS_CLONE/Kratos/cmake_build/applications/PFEMapplication/Release/KratosPFEMApplication.pyd".
24>  Call Stack (most recent call first):
24>    applications/cmake_install.cmake:38 (include)
24>    cmake_install.cmake:79 (include)

3.) 
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: The command "setlocal
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmEnd
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmErrorLevel
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: exit /b %1
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :cmDone
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
24>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Microsoft.CppCommon.targets(133,5): error MSB3073: :VCEnd" exited with code 1.

Sry for that long post, I hope anyone of you can help me.
Klaus

**Comment by pooyan-dadvand** [comment]
You are assigning a path to your install configure with windows back slash "\" path:
`-DKRATOS_INSTALL_PREFIX="C:\KRATOS_CLONE\KratosInstallNew" `
which gives the problem. Would you please change it to slash "/":
`-DKRATOS_INSTALL_PREFIX="C:/KRATOS_CLONE/KratosInstallNew" `

Please let us know if this works for you.

**Comment by KlausBSautter** [comment]
Thanks alot @pooyan-dadvand  this made error 1.) vanish. I still get error 2.) and 3.)

**Comment by pooyan-dadvand** [comment]
Would you please turn off the PFEM application:
`-DPFEM_APPLICATION=OFF`

in your configure?

The 3rd error basically seems to say that it cannot do all the installs and should be removed with that.

@roigcarlo You made some change related to this issue. Isn't it?

**Comment by roigcarlo** [comment]
@pooyan-dadvand Yep, PFEM sould be dissabled by default now. See #149.
If you cloned the code before this PR or used an old configure probably was enabled by default.

**Comment by KlausBSautter** [comment]
perfect! thanks @pooyan-dadvand  and @roigcarlo  it works nicely now .
cheers
