### ISSUE TITLE
problem in GetConstitutiveLaw

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1642]
Hi @philbucher @jcotela we have a problem with the new usage of GetConstitutiveLaw

the point is that the signature of the function is currently

         const ConstitutiveLaw& GetConstitutiveLaw(

this means that when you do

        constitutive_law = self._GetConstitutiveLaw( mat["constitutive_law"]["name"].GetString() )
        prop.SetValue(KratosMultiphysics.CONSTITUTIVE_LAW, constitutive_law)

you first get a reference and then you try to assign that reference to the SetValue.

This is not correct, since a CONSTITUTIVE_LAW is ConstitutiveLaw::Pointer
I think that boost::python is (in my opinion incorrectly) creating a new Pointer. Pybind throws an error.

**Comment by RiccardoRossi** [comment]
just to tell that a simple fix is to do:

       prop.SetValue(KratosMultiphysics.CONSTITUTIVE_LAW, constitutive_law.Clone())

however i am not sure if that's what we want

**Comment by philbucher** [comment]
I can fix it by Sunday, I am making another PR involving this anyway
