### ISSUE TITLE
[PFEM-MPM-etc] Simulation of sloshing water in a (rectangular) tank

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#1658]
Dear PFEM developers (@KratosMultiphysics/pfem @KratosMultiphysics/pfem2),

I would like to request your help as I am looking for possible models/ways to simulate sloshing water in a rectangular tank. I have come across the animation [here (sloshing)](http://www.cimne.com/kratos/galeriaPM.asp) which seems to go in the direction I am interested in. For my usage, I would like to be able to prescribe some excitation motion of the tank, simulate the sloshing and retrieve the (re)action forces of the sloshing liquid onto the tank.

Is this possible? Could you please help me or point me towards an example setup/publication?

I am quite familiar with some other parts and applications of Kratos, but have no insight into PFEM.

Information is highly appreciated!

**Comment by maceligueta** [comment]
Hi @mpentek . Right now, the researcher who takes care of the Fluid part of the PFEM is @AFranci (falessandro@cimne.upc.edu).
The Kratos GUI includes an interface for PFEM that you can try. It allows the introduction of functions when fixing the displacements or velocities, so you should be able to introduce the sloshing.
Regarding publications, here is a paper I co-authored about PFEM and sloshing (not with Kratos): http://oa.upm.es/2327/1/INVE_MEM_2008_54976.pdf
Here you can find a paper about one of the first formulations of PFEM fluid: http://www.cimne.com/pfem/docs/pfem.pdf
The current fluid formulation is described in Alessandro's PhD Thesis: http://www.springer.com/us/book/9783319456614 
Count on me for any help, though I am in PFEM just tangentially nowadays.

**Comment by AFranci** [comment]
Hi @mpentek, as Miguel Angel wrote, we have an interface for the PFEM-fluid application ready to use. You can find the reference formulation also in this paper http://onlinelibrary.wiley.com/doi/10.1002/fld.3870/abstract
Feel free to write me privately at falessandro@cimne.upc.edu if you need more information or if you have some troubles for running the problems. 
Regards,
Alessandro

**Comment by pooyan-dadvand** [comment]
can we close this?

**Comment by dcagritan** [comment]
Hello @mpentek,

Do you have any specific reason for using PFEM? Would PFEM2 would also work for you?

Regards,
Deniz

**Comment by mpentek** [comment]
@dcagri no specific reason for PFEM or PFEM2. Either would be good as long as I can setup and simulate sloshing.

Maybe we can continue this discussion via email in case it is of lesser general interest.

@pooyan-dadvand I will shortly close it, we just need to manage some other communication channel :-).

**Comment by pooyan-dadvand** [comment]
No problem!

**Comment by dcagritan** [comment]
@mpentek, feel free to contact me through dcagri@cimne.upc.edu .

Regards,
Deniz

**Comment by mpentek** [comment]
I am re-opening this discussion as I might finally get to the point to evaluate the possibilities for a tuned-liquid damper. Since the original post there has been quite some new development. I would appreciate some feedback from the various application owners either here or [mate.pentek@tum.de](mailto:mate.pentek@tum.de).

@KratosMultiphysics/pfem (pfem fluid probably, perhaps pfem2)
@KratosMultiphysics/shallow-water 
perhaps even free surface flow?

**Comment by dcagri** [comment]
Dear @mpentek,
I could provide help regarding PFEM-2 if you need. One part of my research is related with capturing the discontinuities on the interfaces in multi-fluid flows, so perhaps that could be useful for you as well. What exactly do you want to simulate? What kind of fluids? What about the geometry?
Regards,
Deniz

**Comment by miguelmaso** [comment]
Hi @mpentek the shallow water equations are the depth integrated Navier-Stokes equations with some assumptions:
- The vertical domain is smaller than the horizontal domain
- The vertical accelerations are small
- There is only hydrostatic pressure
- other assumptions...

Even though you can run a simulation of sloshing water in a tank with the shallow water equations (the walls are always vertical) it won't be as accurate as a cfd.

**Comment by mpentek** [comment]
> Hi @mpentek the shallow water equations are the depth integrated Navier-Stokes equations with some assumptions:
> 
> * The vertical domain is smaller than the horizontal domain
> * The vertical accelerations are small
> * There is only hydrostatic pressure
> * other assumptions...
> 
> Even though you can run a simulation of sloshing water in a tank with the shallow water equations (the walls are always vertical) it won't be as accurate as a cfd.

Thanks you for clarifying! I am aware of some of the main assumptions and limitations. I was wondering what the current status of the application is (works in Kratos master, a prototypical simulation can be setup using GiD etc). I plan to proceed with setting up an examplary case with Tuned-Liquid-Damper in mind and evaluate some applications in Kratos Multiphysics to see which could/would best fit my goals.

**Comment by miguelmaso** [comment]
It is a prototypical app, and there is a small Gid problemtype in the repo of the app (I will update it soon). I can help you to set up the problem.
The simulation of sloshing water will need to implement a moving topography (it is trivial)

**Comment by mpentek** [comment]
Thanks for the help. I now close this old thread and after our initial evaluations address the specific applications and people more directly.
