### ISSUE TITLE
The `TestMathUtilsInvMatTest` fails. 

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#169]
The `TestMathUtilsInvMatTest` fails. 

```
TestMathUtilsInvMatTest Failed with message:
        Error:  Determinant of the matrix is zero or almost zero!!!, InputMatrixDet = 0

in kratos/utilities/math_utils.h:236:MathUtils<double>::InvertMatrix
```

**Comment by pooyan-dadvand** [comment]
@loumalouomega  Since I could not find anybody to blame I assigned it to you. Would you please check if at least it passes in your machine?

**Comment by loumalouomega** [comment]
It passes, but the matrix is generated randomly, so sometimes there is not inverse, @RiccardoRossi  said to use a fixed seed instead of time

**Comment by loumalouomega** [comment]
We can just modify #168, now there is not a finished pull request

**Comment by loumalouomega** [comment]
@pooyan-dadvand You can accept #168, the modifications are done
