### ISSUE TITLE
run_tests.py - error

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#1691]
I have a problem to run the tests

-first, the command `python.exe kratos\python_scripts\run_tests.py` does not work (ModuleNotFoundError: No module named 'KratosMultiphysics')
I added Kratos as well as Kratos\libs into the windows path. 

-using `runkratos.exe kratos\python_scripts\run_tests.py` I have the error 

>  |  /           |
>  ' /   __| _` | __|  _ \   __|
>  . \  |   (   | |   (   |\__ \
> _|\_\_|  \__,_|\__|\___/ ____/
>            Multi-Physics 5.3.0-da61790ec0
> Running tests for KratosCore
> Traceback (most recent call last):
>   File "kratos\python_scripts\run_tests.py", line 326, in <module>
>     main()
>   File "kratos\python_scripts\run_tests.py", line 287, in main
>     signalTime
>   File "kratos\python_scripts\run_tests.py", line 95, in RunTestSuitInTime
>     self.RunTestSuit(application, applicationPath, path, level, verbose, command)
>   File "kratos\python_scripts\run_tests.py", line 146, in RunTestSuit
>     print(script)
> OSError: [WinError 1] Incorrect function
> Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
> OSError: [WinError 1] Incorrect function

I think it is because of `CaptureStdout()` -- line 265 of run_tests.py

**Comment by roigcarlo** [comment]
I am currently changing this. Let me take a look

**Comment by PhilippeBussetta** [comment]
@roigcarlo  thanks
