### ISSUE TITLE
Does SubSubModelparts make sense?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#1696]
Regarding #1692 we saw that the ParentModelpart doesn't know about the subsubmodelparts. My question is if a subsubmodelpart makes sense or it is better to stay focus in work with just one sublevel of submodelparts?

**Comment by RiccardoRossi** [comment]
it definitely makes sense. and for example we are using it right now in the fluid application for the slip BCs. In that case we have

     Main
           SlipBCs
                  Slip1
                  Slip2
                  ....

**Comment by loumalouomega** [comment]
In that case I we found a bug, I will create a test

**Comment by miguelmaso** [comment]
Actually I am not using subsubmodelparts, but soon I will need them

**Comment by loumalouomega** [comment]
The issue is more related with the way ModelPart works than #1692 . If the current behavior is not the expected we should solve it, if it is we can just modify our implementation in order to work

**Comment by loumalouomega** [comment]
Solved in #1692
