### ISSUE TITLE
The "moment reactions" are called TORQUE

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1719]
@KratosMultiphysics/structural-mechanics we shall find a better name for this...

**Comment by philbucher** [comment]
Maybe `ANGULAR_REACTION`?
following `ANGULAR_VELOCITY` / `ANGULAR_ACCELERATION`

**Comment by loumalouomega** [comment]
Yes, but I would declare a new variable, I have checked, and the TORQUE  variable is used across several applications

**Comment by loumalouomega** [comment]
Alternative name MOMENT_REACTION

**Comment by RiccardoRossi** [comment]
REACTION_MOMENT?

**Comment by philbucher** [comment]
Why don't we solve this globally?
Reaction Name = Variable name + `REACTION`

=> `ROTATION_REACTION`

Then one does not always have to know what belongs to what ...

**Comment by RiccardoRossi** [comment]
@philbucher i see merit in your propoal, however i tend to hate "string manipulation". i'll be thinking on this

**Comment by loumalouomega** [comment]
The problem is that there is a lack of consistency with the reaction name definition, see the following:

![imagen](https://user-images.githubusercontent.com/19991680/37664599-eb0b4dea-2c5b-11e8-9588-01d48d9725ad.png)

**Comment by loumalouomega** [comment]
[![](https://api.gh-polls.com/poll/01C920WJBWEGDP0GMCJVCRH23F/ANGULAR_REACTION)](https://api.gh-polls.com/poll/01C920WJBWEGDP0GMCJVCRH23F/ANGULAR_REACTION/vote)
[![](https://api.gh-polls.com/poll/01C920WJBWEGDP0GMCJVCRH23F/MOMENT_REACTION)](https://api.gh-polls.com/poll/01C920WJBWEGDP0GMCJVCRH23F/MOMENT_REACTION/vote)
[![](https://api.gh-polls.com/poll/01C920WJBWEGDP0GMCJVCRH23F/REACTION_MOMENT)](https://api.gh-polls.com/poll/01C920WJBWEGDP0GMCJVCRH23F/REACTION_MOMENT/vote)

**Comment by loumalouomega** [comment]
I created a poll using https://app.gh-polls.com/

**Comment by jginternational** [comment]
So, if MOMENT_REACTION wins the poll, shall we rename the REACTION -> FORCE_REACTION ?

**Comment by RiccardoRossi** [comment]
@philbucher i would go for a simple solution for the moment. Long term, my suggestion would be to assign the reaction at construction time of the variable, since this could help making the dofs more lightweight. however i think that @pooyan-dadvand has been thinking about this

@jginternational i suggest that any change we do for this **is not for the current release**

**Comment by philbucher** [comment]
In general I don't think it is a good idea renaming variables, esp such basic ones bcs it wiill break a lot of things!
@jginternational I think that FOCE_REACTION doesn't make sense, e.g. REACTION is associated with DISPLACEMENT in Structural

**Comment by loumalouomega** [comment]
Do we change the name or we wait?

**Comment by RiccardoRossi** [comment]
@loumalouomega i would wait for pybind to be merged and the waves to settle before making this name change

**Comment by RiccardoRossi** [comment]
just to say that we could now move forward with this.

Note however that we shall make an attempt from now on (let's say from release 6 onwards) to mantain backward compatibility. This WILL require an effort but we @KratosMultiphysics/technical-committee think it is time to go for it for the "core applications" as the structural or the fluid. (this is admittedly off-topic, we'll discuss this)

**Comment by loumalouomega** [comment]
So the division between core application and sandbox will be with the release 6.0?

**Comment by RiccardoRossi** [comment]
Guys, i think we could move forward with this. I guess it would be nice to have this in prior to release 6.0. 

@loumalouomega we are discussing it...
