### ISSUE TITLE
Some tests are failing in Windows

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1720]
In #1712 @PhilippeBussetta has detected that several tests are failing on windows:

**Python CoreTests**:
* `test_model_part_io_write_model_part`: test_model_part_io_write.mpda being used by another process. **FIXED**

**Python StructuralMechancisApplication**
* `test_PostprocessEigenvaluesProcess`: Missing ref file. **FIXED**

**Cpp CoreTests**
* `TestLoggerMessageStream`: Error in `test_logger.cpp:46` check
* `TestModelPartIOWriteModelPart`: Error deleting "main_model_part_output.mpda

Seems to me that both `test_model_part_io_write_model_part` and `TestModelPartIOWriteModelPart` are the same systematic error in something we are doing.

`TestLoggerMessageStream` no idea about that one. I assing this to myself but feel free to help

**Comment by roigcarlo** [comment]
I've fixed most of them already. Still, the modelpart CPP tests is failing.

The problem:
Model_part_io itself opens a file and stores it in a stream. This stream is freed when the model_part_io object is destroyed. As the deletion of the file is done before the destruction of the object, windows (correctly in this case) informs that the file is locked.

The problem is that the stream is stored internally as a `std::shared_ptr<std::iostream>` and hence, it does not have any `close()` function to call, so the only way to close it is to destroy the object.

Ideas to fix the test under this scenario?

Notice that a similar problem is happening with the `*.time` file, but this one can easily be solved added an explicit close mechanism.

My idea so far is to make a new "layer" in the tests which contextualize the use of the model_part_io in a deeper level which would cause the object to be destroyed when we call the delete function for the file.

@KratosMultiphysics/technical-committee  agree?

**Comment by maceligueta** [comment]
Definitely it seems like the ModelPartIO should be destroyed as soon as it is no longer useful. Would be enough if you put a function like 'ReadModelParts' and the ModelPartIO instance is used inside as a local variable?

**Comment by roigcarlo** [comment]
Exactly, that will solve the problem

**Comment by maceligueta** [comment]
Then I understood you correctly and I agree with this solution.

**Comment by pooyan-dadvand** [comment]
I agree with the sloution proposed by @maceligueta

Also we may add a close method to modelpartio in which deletes de streams

**Comment by roigcarlo** [comment]
@pooyan-dadvand Already fixed in #1741, I am pending on merge this once we figure out a problem @PhilippeBussetta is still having with a print function
