### ISSUE TITLE
Concerning backward compatibility with respect to the input json files

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#1723]
Hi everyone!
Suppose you run a case with the GUI today, json input files are generated.
Tomorrow you modify the GUI, now, instead of writing 
`"old_a" : 3.0`
you want to write
`"new_a" : 3.0`
In order to read this correctly, you modify the Default Parameters in Kratos in the same fashion.
This inevitably leads to an error when you try to run the case you generated with the GUI some time ago.
The same happens if you remove a pair key-value from the input json file and from the defaults, the old case does not run.
I am exposing this because I don't know of any valid solution to this problem and I would like to know how people deal with this. It is IMO a source of time loss for everyone.
At the DEM Application, the current policy is to keep `"old_a" : 3.0` in the defaults for some time (at the bottom), keeping track of the date when it was deprecated. But it has the problem of having useless stuff in the Parameters when Kratos is running.
Another solution would be to allow input files to have useless information, not present in the Default Parameters.
I would love to hear other possible solutions and reach a consensus, so we can run cases generated 3 months ago or 6, or one year, even if they are not from our own application.
@KratosMultiphysics/technical-committee

**Comment by RiccardoRossi** [comment]
@maceligueta if you don't want to check the Parameters, you can simply avoid calling the validation function. HOWEVER i would suggest **AGAINST** doing this, since it will also be silent for mistypings. say for example "olda" instead of "old_a".

my suggestion is to avoid writing to the input Parameters all the values for which default values are prescribed. Even though this is not a 100% solution (it will still break if you do prescribe it), in the practice it will save you a lot of headaches.

Finally you could throw a warning before the validate. This would mean that you could check if "old_a" (to be removed) is in the input settings,  throw a warning, and then remove it from the input settings BEFORE calling the validate

**Comment by philbucher** [comment]
Update Riccardo was faster

@maceligueta this is what we do in StructuralMechanics: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L93

If parameters are not needed any more we throw a warning saying that a certain setting is not needed any more and remove it before the validation

Also afaik no parameter was renamed yet

**Comment by maceligueta** [comment]
Definitely, the solution at 
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L93 is better than keeping that value in the Parameters.
If you don't mind I will leave this open a couple of days and if no one else brings alternative ideas I will adopt this one.

**Comment by josep-m-carbonell** [comment]
Something similar to ValidateAndAssignResults can be implemented in order to remove not existing values and give a report of them. A report telling which parameters have been removed, which default parameters have been updated with the current parameters, and which defaults are going to be used.

**Comment by maceligueta** [comment]
It would be nice. However, each change in the Json is done in a different moment in time, so the warning should be converted into error in different moments as well. I am assuming that those warnings do not have to appear forever, and we should keep track of the date when they were introduced, to convert them into errors.

**Comment by josep-m-carbonell** [comment]
The thing is that with ValidateAndAssignResults, first error that is detected is reported and the execution stops. A useful thing would be to create a "log" to give the complete details of what mismatches in a  json set of parameters, and then stop.

**Comment by maceligueta** [comment]
No objection. I also would love to see the error (or the compilation of warnings/errors) right at the bottom. Now, you have to scroll up to see the actual error, because a full json is printed after printing the error.

**Comment by maceligueta** [comment]
Anyways, my main concern was about _ensuring_ backward compatibility. Warnings are fair enough, as long as the code does not crash and you have time to fix it. We can open a different issue or PR for 'Improving the behavior of ValidateAndAssignDefaults'. Closing.

**Comment by pooyan-dadvand** [comment]
Just to leave my opinion here:

IMO the parameter error is too much and a warning would be ok if someone just make a tipo in parameters. (Like cmake and compilers  with their arguments)

For better visibility of warnings I would go for a separate log output with warnings as severity
