### ISSUE TITLE
Tester failing in Nightly compilation

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#1734]
![imagen](https://user-images.githubusercontent.com/19991680/37740083-b8f24d20-2d5c-11e8-8997-a27a2b8066b4.png)

**Comment by roigcarlo** [comment]
It has not compiled due to an error in the ThermoMechanicalApplication, so no tests.
Caused by #1725. I will fix it tomorrow...

For the record, is ThermoMechanicalApplication dependent on c2c by design? Just to know this for the next time we touch that file...

**Comment by roigcarlo** [comment]
Also ping @ddiezrod and @jrubiogonzalez, are you guys developing the thermomechanical one as well? (I honestly don't know)

**Comment by ddiezrod** [comment]
@roigcarlo Nope, we do not have any dependency on it.

**Comment by roigcarlo** [comment]
:+1:

**Comment by jrubiogonzalez** [comment]
We are not using Thermomechanical application anymore, but maybe there are some objects using the variables that we removed. Let us check that. Sorry!

**Comment by roigcarlo** [comment]
Already fixed by @jcotela in #1735

**Comment by jcotela** [comment]
Closing, since #1735 should have fixed it.
