### ISSUE TITLE
Thin Shell Stresses in Str. Mech. App.

### ISSUE THREAD

**Issue by f-zarate** [KratosMultiphysics/Kratos#1738]
Dear Friends.
I been trying to run with the Structural Mech. App. problemtype a simple square plate.
using the ShellThinCorotationalElement and a LinerarElasticPlaneStesss_Hybrid_3D material model.
The displacements looks nice, but I can not see any stresses on it.

What I am doing wrong??

thanks in advance

**Comment by KlausBSautter** [comment]
Did you specify stresses as GP-output?
"gauss_point_results" : ["VON_MISES_STRESS"]

**Comment by f-zarate** [comment]
In GiD Problemtype I select:
Results -> On Element -> Cauchy Stress Tensor = Yes

**Comment by KlausBSautter** [comment]
as far as I know, neither
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_elements/shell_thin_element_3D4N.cpp
nor 
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_elements/shell_thin_element_3D3N.cpp

has cauchy stress. try "VON_MISES_STRESS"

**Comment by f-zarate** [comment]
Ok Thanks , but that's an option that do not appears on GiD's problemtype.  I will try to do it manually.

Tx again.

**Comment by KlausBSautter** [comment]
yes just change your Projectparameters.json
