### ISSUE TITLE
tests of FSI and of meshing application 

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#174]
@rubenzorrilla the tests of FSI application are taking way too long (i had to stop them). Remember that the full set of tests should run in less than 10s. Note that this is a blocker in running the tests

@loumalouomega this is also valid for the tests of the meshign application, which right now are taking >50s on my computer. This is not a blocker right now, however it still takes too long...

**Comment by rubenzorrilla** [comment]
@RiccardoRossi this is because you are running the full FSI App suite, which includes the Mok validation test. To run the nightly tests only takes a few seconds (around 7").

**Comment by RiccardoRossi** [comment]
@rubenzorrilla if i run it as usually with

python_script/run_tests.py

that should last max 10s per app...

**Comment by rubenzorrilla** [comment]
FSI test suites amended in #182.
