### ISSUE TITLE
StructuralMechanics dynamic solver should default to bossak instead of Newmark

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#1743]
@KratosMultiphysics/structural-mechanics as the title suggests, we should default to bossak instead of newmark. This is important since in the nonlinear range it is way more robust. User can simply select newmark if so it wishes.

**Comment by loumalouomega** [comment]
Well, this is very simple to solve

**Comment by loumalouomega** [comment]
I create I branch for that, if everyone agrees I will correct the tests too

**Comment by RiccardoRossi** [comment]
ping @KratosMultiphysics/structural-mechanics . Anyone against this? if no one tells anything we go ahead...

**Comment by AndreasWinterstein** [comment]
This is Ok for us...

**Comment by RiccardoRossi** [comment]
ok, @loumalouomega  are u still willing to change that?

**Comment by loumalouomega** [comment]
Do I change it then?

**Comment by loumalouomega** [comment]
On it
