### ISSUE TITLE
Modifying analysis to run using MPI on a cluster

### ISSUE THREAD

**Issue by jaabell** [KratosMultiphysics/Kratos#1771]
Dear Kratos devs,

I could use some help here. I have a kratos model using PFEM FSI, developed in GiD, which I can run on my laptop using OpenMP. I wish to run this same example, and a finer version of it, on a cluster using MPI and MPI/OpenMP parallelism. I have already compiled Kratos and all dependencies using intel compilers on the cluster and the test runs fine. 

How do I go about modifying the ProjectParameters.json and MainKratos.py files to use MPI? I've attached the files I have right now....
[PFEM_MalladoGrueso.zip](https://github.com/KratosMultiphysics/Kratos/files/1857504/PFEM_MalladoGrueso.zip)

Also related: How can I find out what options are available on the ProjectParameters.json file? Is there any documentation specifying everything available?

Thanks!
Regards from Chile

Jose Abell

**Comment by pooyan-dadvand** [comment]
As far as I know the PFEM application is not mpi compatible and it’s actual remeshing step makes it difficult to be ported

Meanwhile I would refer you to @KratosMultiphysics/pfem which maintain this app

**Comment by maceligueta** [comment]
Some months back we discovered a library that could do the job in MPI. Tess2 by Diatomic, in GitHub. However, no more efforts were dedicated in this direction so far.

**Comment by jaabell** [comment]
Hi Pooyan and Miguel Angel. Thanks for your replies! 
I recently saw a presentation/paper on PFEM2... how is that coming along?

**Comment by maceligueta** [comment]
Let me reference @pablobecker for this.

**Comment by pablobecker** [comment]
I am no longer working on it, but I know @miguelmaso and @dcagri are using it, altough for their specific research and certainly not in MPI. The problem is that i never ported the movement of particles to MPI. Juan Marcelo Gimenez did the porting, but the current implementation uses OpenFoam instead of Kratos FEM.

**Comment by pablobecker** [comment]
If you are interested in geomechanics applications, why don't you take a look at the MPM application ? ping @iiaconeta

**Comment by philbucher** [comment]
Closing since inactive
Please reopen otherwise
