### ISSUE TITLE
Printing debug info in amgcl schur pressure correction

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#1774]
I am getting a lot of verbosity output in tests which use the amgcl solver. @RiccardoRossi can we remove the NDEBUG check at https://github.com/KratosMultiphysics/Kratos/blob/master/external_libraries/amgcl/preconditioner/schur_pressure_correction.hpp#L473 ?

This would also make it consistent with the mpi version.

**Comment by RiccardoRossi** [comment]
ok, just leave
#if defined(AMGCL_DEBUG) 

instead of

#if defined(AMGCL_DEBUG) || !defined(NDEBUG)

**Comment by RiccardoRossi** [comment]
@msandre i think this can be closed, do you agree?

**Comment by msandre** [comment]
Yes, I forgot to close it.
