### ISSUE TITLE
Error installing KRATOS on Windows

### ISSUE THREAD

**Issue by MatthiasWiller** [KratosMultiphysics/Kratos#179]
Hello everyone, I am trying to install KRATOS on Windows and I followed the instructions in the wiki step by step. As I try to Build the INSTALL-projekt in VS2015 I always get the same error messages:

![error_message_vs2015](https://cloud.githubusercontent.com/assets/26324328/24006778/f54d99fa-0a6c-11e7-9ade-ed8f19261384.jpg)

I tried reinstalling VS2015 (without update 3) and boost ( `b2 --toolset=msvc-14.0 --build-type=complete architecture=x86 address-model=64 stage --with-python --with-serialization link=shared,static` ) several times. Boost finished, but gave me some error messages which look like this: 

![error_message_boost](https://cloud.githubusercontent.com/assets/26324328/24006922/5ebd82ba-0a6d-11e7-818f-a1041d41e1ed.jpg)

(BTW I am using Anaconda3, if that could cause any issues.)

Can anyone help me with this problem?

Matthias

**Comment by roigcarlo** [comment]
Dear @MatthiasWiller 

We do not recommend to compile using anaconda. That said, this error means that the libboost_python library is not correctly compiled. You should recheck that no errors were produced while compiling boost.

Also please take into account that if you use anaconda you must manually set both boost `project-conf.jam` and kratos `configure.bat` files to point the same version of python. Most likely the path is not correctly set in `project-conf.jam` and that why the libs were not compiled in the first place.

**Comment by MatthiasWiller** [comment]
Thanks @roigcarlo 

So I removed anaconda and got python 3.6, which did not change anything significantly. Also I double-checked the paths in the mentioned files. 

But I solved the boost-problem by deactivating my anti-virus program. Now there is only one old link to anaconda, which prevents KRATOS from compiling.

**Comment by roigcarlo** [comment]
Hi @MatthiasWiller,
Could you show me exactly which path is giving you problems?

**Comment by MatthiasWiller** [comment]
Hi @roigcarlo 

![error_anacondapath](https://cloud.githubusercontent.com/assets/26324328/24094775/5c6742cc-0d5a-11e7-8aea-7ff206bc6f8c.jpg)

**Comment by roigcarlo** [comment]
That probably is caused because the paths to anaconda are still in the project. If you changed them in the `configure.bat`, just remove everything in the `cmake_build` folder except for the configure and rerun it again. 
That should fix it

**Comment by MatthiasWiller** [comment]
Thanks @roigcarlo , that solved the anaconda-link. But now it gives me this error:

![error_unresolvedexternalsymbol](https://cloud.githubusercontent.com/assets/26324328/24098212/b8bc26c8-0d69-11e7-8bbf-d50c0fff055b.jpg)

**Comment by roigcarlo** [comment]
That looks like a problem in boost, but last time I check 1.62 was just fine. @loumalouomega do you have any idea of what may cause this error?

**Comment by roigcarlo** [comment]
@MatthiasWiller, Are all 12 errors from he SolidMechanics? Could yo compile another application to check if it also fails? ( FluidDynamics for example)

**Comment by MatthiasWiller** [comment]
@roigcarlo, I tried to compile INSTALL. There are in total 170 errors. 12 in SolidMechanics, 75 in Kratos, 1 in ExternalSolvers, 5 in IGAStructuralMechanics, 4 in NurbsBrep.

And some of those:

![error_commandsetlocal](https://cloud.githubusercontent.com/assets/26324328/24112984/8e9f05ea-0d9b-11e7-9f75-ca596a012f58.jpg)

**Comment by roigcarlo** [comment]
Those are not important it just tells you that has not been able to copy the files because was not compiled.
Could you somehow send me the list of errors?

If you are in a hurry I would tell you to compile with boost 1.54 which is the safe version. Meanwhile I would keep looking at this.

**Comment by MatthiasWiller** [comment]
@roigcarlo, I copied all the errors in a .csv:
[kratos_errorlist_170320.zip](https://github.com/KratosMultiphysics/Kratos/files/856003/kratos_errorlist_170320.zip)

**Comment by roigcarlo** [comment]
Oh, are you trying to compile in debug mode? If that's the case then you also need boost libs in debug mode, you can obtain them by compiling it with this:

`b2 --toolset=msvc-14.0 --build-type=complete architecture=x86 address-model=64 stage --with-python --with-serialization link=shared,static`

Notice that the `variant=release` flag is not set.
You will also need to have `python3x_d.lib`

If not just change the debug to release in the top bar:
![image](https://cloud.githubusercontent.com/assets/1935791/24116168/29ddbc86-0da6-11e7-885e-8431cd295cf3.png)

**Comment by MatthiasWiller** [comment]
Yes, I try to compile in debug mode (sorry for not mentioning this earlier). And I used this command to compile boost. 

And VS is not complaining for any missing `python3x_d.lib`. Could it still be the reason for the errors?

**Comment by roigcarlo** [comment]
No, that will come later when you try to compile runkratos. You have to put that lib as ignored by
project name -> right click -> properties -> linker -> input -> ingore. Add that lib to the list.

Still seems strange, can you canfirm that you have the `_gd` variants of the boost libs in boost/stage/libs?

**Comment by MatthiasWiller** [comment]
Yes, I have every lib also as a `_gd` variant in that folder.

**Comment by roigcarlo** [comment]
Well after testing all morning, I can not find anything wrong, so my recommendation would be, try to use boost 1.59 or 1.54. Let's see what happens

**Comment by MatthiasWiller** [comment]
Thank you for your time and patience. I will try it tomorrow and let you know what happens.

**Comment by MatthiasWiller** [comment]
@roigcarlo, unfortunately the same errors with boost 1.59

I can try with Python 3.5?

**Comment by roigcarlo** [comment]
Yes sure, shouldn't be a problem, but I still wander why this is giving you problems...

**Comment by MatthiasWiller** [comment]
@roigcarlo, I have tried several different things:
- deactivating my anti-virus program (which caused some problems at the beginning with boost)
- recompiling boost (1.59, 1.62)
- installing python 3.5 and 3.6
- deleting the Kratos folder and cloning it again
- compiling in Debug, Release and "Release with Debug Info"

But I still get the same errors with unresolved symbols.

Do you have any ideas what I can try next?

**Comment by roigcarlo** [comment]
Honestly no, can you pm (roigcarlo@gmail.com) with the configure file? maybe the problem is there

**Comment by MatthiasWiller** [comment]
`add_model_to_python.obj : error LNK2001: unresolved external symbol "class Kratos::ModelPart const volatile * __cdecl boost::get_pointer<class Kratos::ModelPart const volatile >(class Kratos::ModelPart const volatile *)" (??$get_pointer@$$CDVModelPart@Kratos@@@boost@@YAPEDVModelPart@Kratos@@PEDV12@@Z)`
Maybe this is an issue with Visual Studio. I will try to remove Visual Studio and all its components and reinstall it again.

**Comment by roigcarlo** [comment]
This last particular error its known to happen with Boost 1.61. This points pretty clearly to boost as the source of the problem, but I fail to see why this is happening to you. Can you also recheck that using 1.59 gives you this very same link error?

**Comment by RiccardoRossi** [comment]
@MatthiasWiller can u make absolutely sure that you don't have a old msvc installed in the system?

**Comment by RiccardoRossi** [comment]
@roigcarlo is this solved? close it if that's the case

**Comment by roigcarlo** [comment]
@RiccardoRossi Last time we spoke with @MatthiasWiller he was trying to re-install visual studio, but I don't know if it worked.

**Comment by MatthiasWiller** [comment]
@RiccardoRossi @roigcarlo Now that I have re-installed visual studio it cannot find `io.h` and `corecrt.h`, when compiling boost. 

EDIT: Ok. I think I solved this one by deleting old `b2_*.cmd` files from `%TEMP%`

**Comment by RiccardoRossi** [comment]
that means that it does compile?

as a comment, if you change compiler/python/boost it is typically convenient to create a new compile directory, say build2 and configure and compile clean into that directory. this is so because Cmake cache may become a mess if you change the compiler

**Comment by MatthiasWiller** [comment]
Yes, now it compiles without any errors. 

The problem was that I had already installed the msvc compiler (probably already containing the Update 3), which I didn't remove before installing VS 2015. Therefore boost and Kratos were compiled with two different versions of msvc.

@RiccardoRossi @roigcarlo , thank you for your time and patience.
