### ISSUE TITLE
Structural mechanics test harmonic mdpa input test fails

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#1793]
There is a test in @KratosMultiphysics/structural-mechanics that depends on hdf5 for adjoint (I think). It fails now that I removed hdf5 from @KratosMultiphysics/adjointfluid because it doesn't find the output primal process. @MFusseder can you take a look at it? I think it is probably just a matter of changing the json to use the new hdf5 app, but you know it much better.

**Comment by philbucher** [comment]
I think this test was created by @qaumann , can you take a look?

**Comment by qaumann** [comment]
I will try to make it work again, thanks for the heads up

**Comment by qaumann** [comment]
Fixed in #1862
