### ISSUE TITLE
Compilation Error in windows of the master

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#1800]
Good afternoon,

I've just downloaded the master branch and the VisualStudio returns theses error messages:

********************************************************
Severity	Code	Description	Project	File	Line
Error	LNK2001	unresolved external symbol "public: static double const Kratos::ExactMortarIntegrationUtility<2,2,0>::ZeroTolerance" (?ZeroTolerance@?$ExactMortarIntegrationUtility@$01$01$0A@@Kratos@@2NB)	Kratos	D:\FemDemV4\cmake_build\kratos\add_utilities_to_python.obj	1
********************************************************
Severity	Code	Description	Project	File	Line
Error	LNK2001	unresolved external symbol "public: static double const Kratos::ExactMortarIntegrationUtility<3,3,0>::ZeroTolerance" (?ZeroTolerance@?$ExactMortarIntegrationUtility@$02$02$0A@@Kratos@@2NB)	Kratos	D:\FemDemV4\cmake_build\kratos\add_utilities_to_python.obj	1
********************************************************
Severity	Code	Description	Project	File	Line
Error	LNK2001	unresolved external symbol "public: static double const Kratos::ExactMortarIntegrationUtility<3,4,0>::ZeroTolerance" (?ZeroTolerance@?$ExactMortarIntegrationUtility@$02$03$0A@@Kratos@@2NB)	Kratos	D:\FemDemV4\cmake_build\kratos\add_utilities_to_python.obj	1

What should I do to solve these errors?

Thank you,

Alejandro

@roigcarlo @loumalouomega

**Comment by loumalouomega** [comment]
huuum, #1788 passed the three checks
![imagen](https://user-images.githubusercontent.com/19991680/38373197-f045e454-38f0-11e8-8050-6eda57c0a622.png)

**Comment by loumalouomega** [comment]
@roigcarlo Any idea?

**Comment by roigcarlo** [comment]
Well that was 2 days ago. Anyway, the problem is that those classes are not being exported and that application is not being checked in appveyor anyway. To solve this you have to add the KRATOS_API(APPLICATION) to the class that is not public.

**Comment by AlejandroCornejo** [comment]
I've rebuilded the solution and the same error appears @roigcarlo, tell me something when you have time.

Thank you

**Comment by roigcarlo** [comment]
:+1: As soon as I finish setting up the pybind in win I'll take a look

**Comment by loumalouomega** [comment]
@roigcarlo The utility is on the core and the KRATOS_API is added https://github.com/KratosMultiphysics/Kratos/blob/9888e7bddc92034a3ad65b61be15d836b2fde77e/kratos/utilities/exact_mortar_segmentation_utility.h#L81

**Comment by AlejandroCornejo** [comment]
I've been talking with @roigcarlo  and it seems that the problem is a bit complicated...

**Comment by roigcarlo** [comment]
Yup, @AlejandroCornejo was were and we took a look at it, seems to be a problem with the ZeroTolerance being a static constexp inside a template. Not sure how to handle this. I have to read a bit about that.

**Comment by loumalouomega** [comment]
One option is to define the ZeroTolerance like the PI number....

**Comment by loumalouomega** [comment]
Accesible to everyone

**Comment by roigcarlo** [comment]
Just a quick update. I may have found a way to solve this, but I will keep it on hold until we have merged pybind

**Comment by roigcarlo** [comment]
@loumalouomega This was fixed by you at some point if I am not mistaken right? can we close it?

**Comment by loumalouomega** [comment]
I think so

**Comment by loumalouomega** [comment]
yep, I defined locally the zero_tolerance, closing
