### ISSUE TITLE
eigen_eigensystem solver should output the tolerance

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#1806]
For echo level 2 the tolerance in each iteration should be printed.

**Comment by philbucher** [comment]
@armingeiser seems like it does not work automatically :/

**Comment by philbucher** [comment]
Sorry I just realized I closed the wrong issue

ping @armingeiser @oberbichler it would be nice to have this feature :)

**Comment by philbucher** [comment]
ping

**Comment by armingeiser** [comment]
Is already there, forgot to close the issue
