### ISSUE TITLE
[Tests] Travis tests are failing

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#1810]
For some reason Travis tests are failing (return 1). But apparently everything is OK, so I cannot identify the reason and which test is failing.

Any idea why?

**Comment by roigcarlo** [comment]
No idea, i will take a look

**Comment by loumalouomega** [comment]
If I run 

   echo $?

After running `test_KratosCore.py` I get 0, if I run `run_cpp_tests.py` I get 0 too. If I run `python3 run_tests.py -l small -a KratosCore ` I got 0

**Comment by loumalouomega** [comment]
With python3 run_tests.py -l small -a StructuralMechanicsApplication   I got 1 and the error is the following 

~~~

Running tests for StructuralMechanicsApplication
/home/vicente/src/Kratos/applications//StructuralMechanicsApplication/tests/test_StructuralMechanicsApplication.py
............................Check failed in file /home/vicente/src/boost_1_66_0/boost/numeric/ublas/functional.hpp at line 1373:
i < size_i
terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: bad index

in /home/vicente/src/Kratos/applications/StructuralMechanicsApplication/custom_elements/prestress_membrane_element.cpp:811:void PrestressMembraneElement::CalculateAll(Element::MatrixType&, Element::VectorType&, const ProcessInfo&, bool, bool)
   kratos/solving_strategies/schemes/residualbased_incrementalupdate_static_scheme.h:291:void ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::CalculateSystemContributions(Element::Pointer, ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemMatrixType&, ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType&, Element::EquationIdVectorType&, ProcessInfo&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; Element::Pointer = boost::shared_ptr<Element>; ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemMatrixType = boost::numeric::ublas::matrix<double>; ResidualBasedIncrementalUpdateStaticScheme<TSparseSpace, TDenseSpace>::LocalSystemVectorType = boost::numeric::ublas::vector<double>; Element::EquationIdVectorType = vector<long unsigned int>]


~~~

**Comment by loumalouomega** [comment]
In the Travis output this doesn't appear

**Comment by loumalouomega** [comment]
The test failing is `test_patch_test_formfinding`

**Comment by roigcarlo** [comment]
Yup I can confrim this. No idea why the log does not appear in travis. Maybe we should increase the verbosity level

**Comment by loumalouomega** [comment]
Solving the problem, this is related with @KratosMultiphysics/structural-mechanics

**Comment by philbucher** [comment]
Since when does this happen?

Afaik nothing has been modified related to this in the past weeks

**Comment by loumalouomega** [comment]
Well, yesterday the variables were changed, most of my tests are failing

**Comment by loumalouomega** [comment]
It is related with the Get/SetValue

**Comment by jcotela** [comment]
Regarding why this error does/does not appear, I think that that particular error message is only thrown in debug (it most likely indicates a memory error in release though). I don't know which compilation mode is used in travis, but that might explain the differences.

**Comment by loumalouomega** [comment]
I could solve the formfinding test, but still having problems with test_multipoint_contstraints.py

**Comment by loumalouomega** [comment]
test_postprocess_eigenvalues_process is giving problems too

**Comment by philbucher** [comment]
What are the problems?

**Comment by loumalouomega** [comment]
test_multipoint_contstraints.py: 

~~~
python3: /home/vicente/src/boost_1_66_0/boost/smart_ptr/shared_ptr.hpp:728: typename boost::detail::sp_dereference<T>::type boost::shared_ptr<T>::operator*() const [with T = Kratos::Dof<double>; typename boost::detail::sp_dereference<T>::type = Kratos::Dof<double>&]: Assertion `px != 0' failed.
[1]    17633 abort (core dumped)  python3 test_multipoint_contstraints.py

~~~

**Comment by loumalouomega** [comment]
The post process:

![imagen](https://user-images.githubusercontent.com/19991680/38455327-dfdb4186-3a76-11e8-9b4a-883b561a1642.png)

All

**Comment by loumalouomega** [comment]
Well I will comment these two tests, and we can try to find the origin later, but this is blocking everything

**Comment by roigcarlo** [comment]
+1 to that, we are in a very delicate schedule right now. Just mark them as expected failure or something so we can merge the pybind this monday.

**Comment by loumalouomega** [comment]
I will close this
