### ISSUE TITLE
[Core][StructuralMechanicsApplication] Deactivated tests->data_value_container.h

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#1812]
The following tests are deactivated due to Travis errors:

-`test_postprocess_eigenvalues_process`
-`test_multipoint_contstraints.py`

**Comment by loumalouomega** [comment]
@pooyan-dadvand The `test_multipoint_contstraints.py` shows the error we were looking yesterday at https://github.com/KratosMultiphysics/Kratos/blob/7f9294aee4e2be24c6b1aab32b080a0c8818884d/kratos/containers/data_value_container.h#L267

**Comment by loumalouomega** [comment]
I attach my Valgring output 
[out.out.zip](https://github.com/KratosMultiphysics/Kratos/files/1886436/out.out.zip)

**Comment by loumalouomega** [comment]
@pooyan-dadvand I solved the problem for the MPC with #1813. The problem is not in your new hash function. But now the keys must be necessarily a std::size_t or std::unint_64, or will provoke problems during the assign. The MPC B&S was using indistintly the int and unsigned int provoking this problem.

I will debug my tests now that I know where to focus

Besides I debugged first the MPC because the case to debug was simpler 

@philbucher can you debug test_postprocess_eigenvalues_process with this hint?

**Comment by loumalouomega** [comment]
@pooyan-dadvand  Additionally I created some new tests and a 64 bit hash trying to find the origin of the problem I will create a PR to be there for ever

**Comment by philbucher** [comment]
I will take a look at the test in the next days

**Comment by pooyan-dadvand** [comment]
It should be `std::uint_64_t` and **NOT** `std::size_t` which would crash in 32 bit!! Actually I found out that I have not changed the key type in the variable base class and I will do it ASAP. Then you may use it. Anyway,  I would suggest to avoid the use of key explicitly and better to rely on methods taking variables.

**Comment by pooyan-dadvand** [comment]
Thanks @loumalouomega for resolving this.

**Comment by loumalouomega** [comment]
If we don't give support for 32 bit std::size_t it is supposed do the same than std::uint_64_t, doesn't?

**Comment by pooyan-dadvand** [comment]
yes but I'm not sure if we can drop it now.... @KratosMultiphysics/technical-committee ?

**Comment by maceligueta** [comment]
Well, here my office mate is just entering the Kratos universe and he is complaining quite a lot about the limitations imposed by Kratos: a certain version of this, a certain version of that, ... If we add one more limitation it gets even worse. We are working in the opposite direction, right? I mean removing boost dependency, keeping compatibility with Python 2.7, ...

**Comment by RiccardoRossi** [comment]
about the python2.7 ... i would vote for removing support...

**Comment by maceligueta** [comment]
We discussed about python 2.7 several times at the Committee, and we always decided to keep python 2.7 due to the usual presence of it in hpc clusters and some linux distributions. If clusters and linuxes have moved to Python3, we can discuss it again. Any news on that?

**Comment by RiccardoRossi** [comment]
true, and this is not very urgent, however future releases (for example ubuntu 18.04) will ship without python2.6.

the without means it will not be install by default

**Comment by roigcarlo** [comment]
My experience lately is that every cluster has python3 already....

**Comment by loumalouomega** [comment]
Even Numpy is dropping support https://news.ycombinator.com/item?id=15707956

**Comment by pooyan-dadvand** [comment]
I imagine that there are still windows 32 bit around. (we have dropped the 32bit linux releases long ago) 

My concern is the use of size_t anywhere the variable key is used and I should see if I can see them as a visual studio warning in 32 bit to be sure someone is not narrowing the key without knowing it.

**Comment by pooyan-dadvand** [comment]
another possibility is to reduce the key size to 32bit but I don't like it so much.....

**Comment by pooyan-dadvand** [comment]
In @KratosMultiphysics/technical-committee we have decided to change the key type to be more clear and test if tests are running in win32. If not dropping the support.

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by pooyan-dadvand** [comment]
IMO yes

**Comment by loumalouomega** [comment]
Ok, I will close and reopen in case is necessary
