### ISSUE TITLE
Naming clash between Core and Applications

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#1820]
This issue is to open a discussion about the possibilities to solve the names clash between Core and Applications, first noticed with the Solid Mechanics Application (#1805), but can happen again in the future.
I open it now as a reminder, however, this discussion should take place after the merge or the Pybind PR (#1513), which is more urgent.

**Comment by loumalouomega** [comment]
One option is to add new namespaces for each application (but this will break all the current work)

**Comment by josep-m-carbonell** [comment]
Adding a namespace for the application scope can be a good solution. Are there any known cons that give preference to avoid doing this?

**Comment by jcotela** [comment]
It is not really a con, but there is the limitation that the namespace thing will not prevent clashes for things that have to be registered in the core. Right now it is only variables, elements/conditions and constitutive laws, but the @KratosMultiphysics/technical-committee dicusssed extending this to other types of objects in the future.

**Comment by pooyan-dadvand** [comment]
I also like the idea of having namespace for each app but the cons would be how to define clearly which parts goes into namespace and if the decision is all the classes in the applications goes to the namespace I'm not sure how to avoid breaking the backward compatibility with variables, Kratos components especially for applications with derived apps.  The registered components in the core is another complication as mentioned by @jcotela

**Comment by RiccardoRossi** [comment]
The idea we are considering in the @KratosMultiphysics/technical-committee is to employ this idea of application local namespaces and to extend it to the registry. 

We will look into this in the future when we define a suitable registration mechanism.
