### ISSUE TITLE
Adding missing override warning

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1826]
Following the discussion in #589
Since we recently added the missing overrides, we could think abt adding the override warnings to the global CMakeLists.

Basically what them DEM guys [are already doing](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/DEM_application/CMakeLists.txt#L109-L115) 

This might lead to many warnings with external libs (e.g. Trilinos gives maaany warnings), so it would be good if one could disable the check for certain apps (is this possible?)

@KratosMultiphysics/technical-committee

**Comment by RiccardoRossi** [comment]
a better solution would be to fix the warnings :-)

**Comment by pooyan-dadvand** [comment]
but we cannot do it for trilinos....

**Comment by maceligueta** [comment]
If you put 
`add_definitions( -w )`
in the CMakeLists.txt file, that inhibits all warnings in that folder.
It is done in several libraries of the repository, like [here](https://github.com/KratosMultiphysics/Kratos/blob/3f764e9f4ed2ca225ed14d6acb2447b7acf4329a/external_libraries/gidpost/CMakeLists.txt#L17).
I guess you can supress specific warnings in the same fashion.
