### ISSUE TITLE
Warning concerning integration of the quadrilateral

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#183]
`In file included from /home/vicente/bin/Kratos/kratos/geometries/quadrilateral_2d_4.h:27:0,
                 from /home/vicente/bin/Kratos/kratos/tests/processes/test_coarsening_process.cpp:25:
/home/vicente/bin/Kratos/kratos/integration/quadrilateral_gauss_legendre_integration_points.h: In static member function ‘static Kratos::QuadrilateralGaussLegendreIntegrationPoints5::IntegrationPointsArrayType& Kratos::QuadrilateralGaussLegendreIntegrationPoints5::IntegrationPoints()’:
/home/vicente/bin/Kratos/kratos/integration/quadrilateral_gauss_legendre_integration_points.h:229:13: warning: this ‘for’ clause does not guard... [-Wmisleading-indentation]
             for(int j = 0; j < 5; ++j)
`

**Comment by pooyan-dadvand** [comment]
@loumalouomega would you please give more info about which compiler and flags which gives this warning?

**Comment by loumalouomega** [comment]
I am using currently the last version of GCC (6.2), with ` -msse3 -std=c++11`

**Comment by roigcarlo** [comment]
If it is of any help, this in general means that there are flow control statements without `{...}`

Like:
```C++
for(auto foo: boo)
    for(auto roo: moo)
        if(foo == roo)
            printf("Hi")
```

vs

```C++
for(auto foo: boo) {
    for(auto roo: moo) {
        if(foo == roo) {
            printf("Hi")
        }
    }
}
```

**Comment by pooyan-dadvand** [comment]
@loumalouomega does braces solve the warning?

**Comment by loumalouomega** [comment]
Sorry, I didn't try it

**Comment by loumalouomega** [comment]
Yes, working
