### ISSUE TITLE
Reusing the same convergence criteria for multiple problems

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1836]
Same as #1835 we were discussing today how the `ConvergenceCriteria` could be used for multiple problems

I had a look around the existing criteria in the previous days and found that there are many criteria out there that do basically the same, only based on different variables. E.g. the convergence criterion used in FluidDynamics separates the convergence the `VELOCITY`and the `PRESSURE` whereas the one in StructuralMechanics does the same but for `DISPLACEMENT` and `ROTATION`.

Furthermore there are quite a few inconsistencies (not small ones)!

My proposed solution for this is to implement the `ConvergenceCriteria` in a general way (both the residual and the "SolutionBased" criteria) such that it can be used in multiple problems. The key to do this is to pass the variable of interest to the criteria and not hardcode it.

My main point for the discussion is how to handle problems with several variables (like for Fluids with `VELOCITY` and `PRESSURE`, I will use this in the following explanation)

- Using **ONE** criteria that can handle **MULTIPLE** variables: We can pass the **list of variables** to be considered "separately". For this we have two options:
    - We would pass BOTH, `VELOCITY` and `PRESSURE` => We check explicitly if the `Dof` Variable is `PRESSURE` or `VELOCITY_X/Y/Z` => the problem here is that if additional Variables are present as dofs they are not considered! I am not sure though how relevant this case is, usually adding more dofs means also modifications in other places. (We could check though if other Dof-Variables are present and throw an error) 

    - We pass the list of Dof Variables -1 => We pass only the `VELOCITY` and the other dofs are considered together. For a better understanding this is done in the [DisplacementAndOtherDoFCriteria](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_strategies/custom_convergencecriterias/displacement_and_other_dof_criteria.h)

- Using **MULTIPLE** criteria that each handle **ONE** variable and combine then using the `And` (or `Or`) criterion. If we modify these two criteria to use `N` instead of `2` criteria we could combine them in whatever way we want. This is imo a cleaner solution but we have the same problem as above that some dofs might not be considered . Furthermore if only one variable is considered criteria we have to loop the nodes multiple times (once per variable)

Btw the criteria can be implemented in a generic way, i.e. working both in serial and MPI using the ModelPart-Communicator

@jcotela I hope I explained everything we talked abt in an understandable way, please feel free to add if I missed sth

@KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
I had an idea thant can be take into term now, now is easier to identify if  a variable is a component, then it can be used to easily "organize" the dofs

**Comment by philbucher** [comment]
What you propose would also work, Since here we use only the dofset I think Kratos::Components can be used in the initialization without much hassle

**Comment by RiccardoRossi** [comment]
It may sound an obviety, but the problem for all of this is not really the "how to do it" but rather the "how to do it efficiently". For the first one i see options. The second one worries me a bit more

**Comment by philbucher** [comment]
Thx for your comments, I will try to come up with a draft then

**Comment by RiccardoRossi** [comment]
closing for now, reopen when we have advances on this
