### ISSUE TITLE
Proposal of adding StrainMeasure_Velocity_Gradient in constitutive_law.h

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#1837]
To add hypo-elastic laws it would be good to characterise the strain measure that these laws support. The velocity gradient ( the spatial velocity gradient ) is the natural strain measure in this case. 
It is clear that the list of strain and stress measures is incomplete and the new measures must be added when needed for the constitutive models. 
If you have any proposal for the names, it will be welcomed. @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
I agree, we can take the opportunity to do some other changes. @marandra has some comments about how to improve the CL base class.

Additionally we can fully deploy the cpp tests for the CL base class methods

**Comment by RiccardoRossi** [comment]
I am also ok with the proposed additon.

I would take the opportunity to depracate old methods (@vryy ...it is happening...last step before removal)

**Comment by josep-m-carbonell** [comment]
That is good, I we would like to listen for ideas and improvements. There is also a naming clash with the Parameters of the constitutive law and the Kratos Parameters. Maybe the Clw parameters can be renamed to avoid future problems or another solution can be applied. We can open a more general issue for that, and leave this only to decide if the addition proposed is ok.

**Comment by philbucher** [comment]
+1 for renaming the ConstLaw Parameters (I think this was anyway discussed somewhere else)

**Comment by josep-m-carbonell** [comment]
It is possible @philbucher, I think @RiccardoRossi  was the one who realised about this and said something.
I have opened an issue to list there the ideas and proposed changes #1838 .
