### ISSUE TITLE
SpingDamper tests fails in FullDebug

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1845]
@RiccardoRossi @loumalouomega @adityaghantasala @qaumann @msandre 

with the recent introduction of the debug check for computing the reactions now the test below fails SOMETIMES, even though it does NOT compute reactions (and therefore the reaction dofs are not added which seems correct to me)

I suspect that this has to do sth with the EigenSolverStrategy wrongly asking for the calculation of reactions.
Since it happens only sometimes it could be related to sth not being initialized

~~~
======================================================================
ERROR: test_undamped_mdof_system_eigen (test_spring_damper_element.SpringDamperElementTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_aux/applications/StructuralMechanicsApplication/tests/test_spring_damper_element.py", line 329, in test_undamped_mdof_system_eigen
    solver.Solve()
RuntimeError: Error: Reaction variable not set for the following : 
Node : 1
Dof : Fix ROTATION_X degree of freedom
    Variable               : ROTATION_X
    Reaction               : NONE
    IsFixed                : True
    Equation Id            : 0

Not possible to calculate reactions.
~~~

**Comment by loumalouomega** [comment]
I had that problem and I solved defining a missing reaction variable

**Comment by philbucher** [comment]
So we have to define the rotation dof even if we don't compute the reactions?

Also this doesn't answer why it fails ocationally

**Comment by loumalouomega** [comment]
You need to define the reaction to all variables that have dofs. If it
fails randomly this is a work for debuggingman, I will check it later.

**Comment by qaumann** [comment]
I will look into the element and define all required variables.

**Comment by adityaghantasala** [comment]
@loumalouomega  mentioned all DOF variables should have reaction variables define. One this is done the problem here should be solved. 
@philbucher  

> So we have to define the rotation dof even if we don't compute the reactions?

Do you mean if you have to define reaction to rotation dof ? If a variable is used as DOF it should have a reaction defined to it.
