### ISSUE TITLE
Schemes for Structural require additional DOFs

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1855]
Following the discussion in #1844 
@KratosMultiphysics/structural-mechanics @KratosMultiphysics/technical-committee 

In StructuralMechanics the dynamic solvers are adding the dofs for `VELOCITY` and `ACCELERATION` even though the elements do not need it (they only use `DISPLACEMENT` & some of them `ROTATION`)

@RiccardoRossi says that the schemes need these dofs in `Predict` if velocities or accelerations are prescribed.
This seems a bit strange to me and also is some overhead I think.

This issue is to keep track of this and discuss if we leave it as is or if another solution can be found

**Comment by loumalouomega** [comment]
Yes, this was the reason, now I remember, haha. Well, the only solution would be to modify the dofs, what is a very technical issue. @KratosMultiphysics/technical-committee any idea?

**Comment by jcotela** [comment]
ok, so I think that the issue here is that the only one that knows if a value is fixed or free is the Dof. You add dofs for velocity and acceleration because there is no other way to store the information of what is an initial condition and what is a boundary value that should be kept constant.

**Comment by philbucher** [comment]
I am fine with leaving it as is but then I would add a brief explanation to the corresponding function such that this question doesn't pop up again
=> and add a test where I prescribe the acc or vel which would fail if these dofs are removed

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/5d80ab14e0beb35acaeda489d34cbb4febb30d1b/kratos/solving_strategies/schemes/residual_based_bossak_displacement_scheme.hpp#L260

**Comment by jcotela** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/5d80ab14e0beb35acaeda489d34cbb4febb30d1b/kratos/includes/node.h#L1181-L1185

**Comment by philbucher** [comment]
Thx for the explanations guys, I will add a test and a comment to the corresponding functions to not accidentally break this (like I would have done)
