### ISSUE TITLE
Remove liboost-serialization

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1859]
To be discussed tomorrow.
Technically it will be possible, but I don't k now the effects. We should discuss how to tackle this. @KratosMultiphysics/technical-committee

**Comment by RiccardoRossi** [comment]
just as a reminder, we need to add this not just in the case of MSVC but also in the case of INTEL (for windows)

**Comment by philbucher** [comment]
So from how I understand you you still have to compile boost if you are in Win?

**Comment by RiccardoRossi** [comment]
no, in principle it is not needed any longer. you do need the headers

**Comment by roigcarlo** [comment]
@RiccardoRossi I think we should define this in the common flags. If I am not mistaken CMake can handle the conversion of `-DFoo` type of flags across compilers when needed

**Comment by RiccardoRossi** [comment]
i think that if you do "AddDefine" it will behave as you are telling
