### ISSUE TITLE
StructuralMechanics: configure issue regarding CMakeLists.txt under Windows

### ISSUE THREAD

**Issue by longchentum** [KratosMultiphysics/Kratos#186]
Hello,

After pulling the actual code (March.17.2017) for the master branch I got an error when I am configuring the StructuralMechanicsApplication under Windows:

![configure_error](https://cloud.githubusercontent.com/assets/25929689/24051339/0d32c19c-0b32-11e7-9de8-29dc82226a38.png)

I noticed that there are some changes in the line 79 recently.

Thanks in advance.

@KratosMultiphysics/technical-committee @KratosMultiphysics/structural-mechanics

**Comment by loumalouomega** [comment]
@roigcarlo We created the #184 , I just checked in Linux, but I have no idea if it affected to Windows
