### ISSUE TITLE
test_redistance.py Is failing and blocks travis.

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#1872]
Seems to be a rounding problem....

**Comment by philbucher** [comment]
I don't use this and have no clue why it fails, sorry

could be related to #1245 @pablobecker

**Comment by roigcarlo** [comment]
Oh, sorry, I just added the people who touched that file. Probably @RiccardoRossi knows about it.

**Comment by RiccardoRossi** [comment]
I cannot reproduce the error :-(

also i tried to run with valgrind on my machine in FullDebug and with python compiled in debug mode.

output i get is:

    valgrind --leak-check=full --track-origins=yes ~/compiled_libraries/PythonDebug/bin/python3.6d test_redistance.py 
    ==10708== Memcheck, a memory error detector
    ==10708== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
    ==10708== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
    ==10708== Command: /home/rrossi/compiled_libraries/PythonDebug/bin/python3.6d test_redistance.py
    ==10708== 
    |  /           |             
    ' /   __| _` | __|  _ \   __|
    . \  |   (   | |   (   |\__ \ 
    _|\_\_|  \__,_|\__|\___/ ____/
            Multi-Physics 6.0.0-ecf6617-FullDebug
    ModelPartIO:   [Reading Nodes    : : 85 nodes read]
    ModelPartIO:   [Reading Elements : : 249 elements read] [Type: Element3D4N]
    ModelPartIO:   [Total Lines Read : 696]
    CurrentTime: 
    CurrentTime = 1
    setup_dofs_time: setup_dofs_time : 0.26674
    setup_system_time: setup_system_time : 0.02103
    system_matrix_resize_time: system_matrix_resize_time : 0.294088
    Construction time: System Construction Time : 0.6029
    ResidualBasedBlockBuilderAndSolver: Build time: 0.410584
    ResidualBasedBlockBuilderAndSolver: System solve time: 0.270621
    CurrentTime: 
    CurrentTime = 1
    Construction time: System Construction Time : 0.000159
    ResidualBasedBlockBuilderAndSolver: Build time: 0.359519
    ResidualBasedBlockBuilderAndSolver: System solve time: 0.2193
    CurrentTime: 
    CurrentTime = 1
    Construction time: System Construction Time : 8e-06
    ResidualBasedBlockBuilderAndSolver: Build time: 0.349795
    ResidualBasedBlockBuilderAndSolver: System solve time: 0.207257
    ResidualBasedBlockBuilderAndSolver: Clear Function called
    .
    ----------------------------------------------------------------------
    Ran 1 test in 6.684s

    OK







So there is nothing strange **during the run**. However at destruction time (that is, after the "ok" there are some "definitely lost" which appears to be somewhere in the logger. I copy it here:

==10708==    by 0x87BA47F: _ZN8pybind1112cpp_function10initializeIZNOS_6detail8initimpl14pickle_factoryIZNS_5enum_IN6Kratos13LoggerMessage8CategoryEEC4IJEEERKNS_6handleEPKcDpRKT_EUlRKS8_E27_ZNSA_IJEEESD_SF_SJ_EUlNS_5tupleEE28_FSN_SL_EFS8_SN_EE7executeINS_6class_IS8_JEEEJEEEvRT_DpRKT0_EUlRNS2_16value_and_holderESN_E_vJS12_SN_EJNS_4nameENS_9is_methodENS_7siblingENS2_24is_new_style_constructorEEEEvOSV_PFT0_DpT1_EDpRKT2_.lto_priv.3001 (pybind11.h:171)
==10708== 
==10708== 120 bytes in 1 blocks are definitely lost in loss record 2,832 of 3,763

**Comment by philbucher** [comment]
I think it fails occasionally so you might have to try several times

**Comment by roigcarlo** [comment]
We should disable this or mark it as an expected failure. It is blocking Pr from being merged....

**Comment by RiccardoRossi** [comment]
ok, mark it as skip...

**Comment by philbucher** [comment]
Closing since I believe this is solved after merging #1245
