### ISSUE TITLE
DEM - incompatible contstructor arguments

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#1877]
Hi @KratosMultiphysics/dem, since I merged the latest master I cant run no more Dem examples on my pc. #1873 didn't fix that.

Following error occurs:
```
  File "/home/klaus/software/Kratos/applications/DEM_application/python_scripts/sphere_strategy.py", line 282, in CreateCPlusPlusStrategy
    self.search_strategy, self.do_search_neighbours)
TypeError: __init__(): incompatible constructor arguments. The following argument types are supported:
    1. KratosDEMApplication.ExplicitSolverStrategy(arg0: KratosDEMApplication.ExplicitSolverSettings, arg1: float, arg2: int, arg3: float, arg4: int, arg5: Kratos::ParticleCreatorDestructor, arg6: Kratos::DEM_FEM_Search, arg7: Kratos::SpatialSearch, arg8: bool)

Invoked with: <KratosDEMApplication.ExplicitSolverSettings object at 0x7f24d447cd88>, 0.002, 1, 1.0, 1, <KratosDEMApplication.ParticleCreatorDestructor object at 0x7f24d4d1e068>, <KratosDEMApplication.DEM_FEM_Search object at 0x7f24d4d16b58>, <KratosDEMApplication.OMP_DEMSearch object at 0x7f24d447cb90>, True
```

maybe @maceligueta  knows sth. about this. Am I missing sth. or is this an error to be fixed?

Cheers,
Klaus

**Comment by maceligueta** [comment]
I can't reproduce the error anymore from a recently pulled master. Did you close the issue intentionally because it was fixed? If not, we should keep it open until it is solved.

**Comment by KlausBSautter** [comment]
@maceligueta  yeah I wrote this issue before I realised that the newest fix was not yet merged to the master. Now it works again. thanks for your help!
