### ISSUE TITLE
Name change of ALEApplication

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#1879]
Since the ALEApplication is currently not only used for FSI anymore, but also for optimization and other cases we would suggest to rename it in MeshMovingApplication.

Please let us know what you think about this.

**Comment by RiccardoRossi** [comment]
(i gave you a +1)

**Comment by jcotela** [comment]
No objections from my side.

**Comment by RiccardoRossi** [comment]
not asked, however @KratosMultiphysics/technical-committee  agrees

**Comment by dbaumgaertner** [comment]
sounds very nice from the point of view of @KratosMultiphysics/optimization

**Comment by RiccardoRossi** [comment]
can this be closed?

**Comment by philbucher** [comment]
just talked to @AndreasWinterstein he said he will do in the next days, therefore closing
