### ISSUE TITLE
warning on clang

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#188]
clang 3.9+ gives million of warnings about uninitialized components.

they disappear if we add the following lines

KratosComponents<Variable<bool> > bool_components();
KratosComponents<Variable<int> >int_components();
KratosComponents<Variable<unsigned int> >uint_components();
KratosComponents<Variable<double> >double_components();
KratosComponents<Variable<array_1d<double, 3> > >array1d_components();
KratosComponents<Variable<Quaternion<double> > >quaternion_components();
KratosComponents<Variable<Vector> >vector_components();
KratosComponents<Variable<Matrix> >matrix_components();
KratosComponents<Variable<std::string> >string_components();
KratosComponents<VariableComponent<VectorComponentAdaptor<array_1d<double, 3> > > >var_component_components();
KratosComponents<Variable<Flags> >var_flags_components();
KratosComponents<Flags>flags_components();

at the end of kratos components.

this is a bit ugly since i don't love the idea of instantiating a few global objects in the global kratos namespace just for silencing a warning.

however the warning is very noisy, so we should decide where to do this, and eventually immediately destroy the objects. @roigcarlo @pooyan-dadvand 
proposals are welcome...

**Comment by RiccardoRossi** [comment]
looks like my fix is wrong. 

commenting // #ifdef KratosCore_EXPORTS

silences the warning... however i am not really clear about the impact of this

**Comment by roigcarlo** [comment]
If the warnings are really a problem we can just ignore them with the appropiare -Wno-XXXXXX. but this would be a temporal solution...

**Comment by RiccardoRossi** [comment]
just to document that taking out the KratosCore_EXPORTS leads to a failure in the tests. so also a solution to be discarded

**Comment by pooyan-dadvand** [comment]
Would you please send the warning message?

**Comment by pooyan-dadvand** [comment]
It arises compiling the core or kratos or apps?

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand i would say it is in the applications, and it is realted to singleton behaviour of the kratos_components

warning is : 

```
/home/rrossi/kratos_git/kratos/includes/kratos_components.h:85:9: note: add an explicit instantiation declaration to suppress this warning if
      'Kratos::KratosComponents<Kratos::Variable<Kratos::Quaternion<double> > >::msComponents' is explicitly instantiated in another translation unit
        msComponents.insert(typename ComponentsContainerType::value_type(Name , &ThisComponent));
        ^
/home/rrossi/kratos_git/kratos/includes/kratos_components.h:85:9: warning: instantiation of variable 'Kratos::KratosComponents<Kratos::Variable<boost::numeric::ublas::vector<double,
      boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > > >::msComponents' required here, but no definition is available [-Wundefined-var-template]
        msComponents.insert(typename ComponentsContainerType::value_type(Name , &ThisComponent));
        ^
/home/rrossi/kratos_git/kratos/includes/kratos_components.h:205:36: note: forward declaration of template entity is here
    static ComponentsContainerType msComponents ;
                                   ^
/home/rrossi/kratos_git/kratos/includes/kratos_components.h:85:9: note: add an explicit instantiation declaration to suppress this warning if
      'Kratos::KratosComponents<Kratos::Variable<boost::numeric::ublas::vector<double, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > > >::msComponents' is explicitly
      instantiated in another translation unit
        msComponents.insert(typename ComponentsContainerType::value_type(Name , &ThisComponent));
        ^
/home/rrossi/kratos_git/kratos/includes/kratos_components.h:85:9: warning: instantiation of variable 'Kratos::KratosComponents<Kratos::Variable<boost::numeric::ublas::matrix<double,
      boost::numeric::ublas::basic_row_major<unsigned long, long>, boost::numeric::ublas::unbounded_array<double, std::allocator<double> > > > >::msComponents' required here, but no definition is
      available [-Wundefined-var-template]
        msComponents.insert(typename ComponentsContainerType::value_type(Name , &ThisComponent));
```

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi  would you please also sepcify if this happens while compiling the Kratos or the app? And if is Kratos it is the KratosCore.so or Kratos.so?

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand @roigcarlo this is slightly off-topic, however why does variables.h include kratos_components.h? 

as i see this is only needed by the function REGISTER, which is only called in the variables.cpp

i would suggest removing the include of kratos_components.h from the variables.h
as well as from Element, Condition, Point, and a few others. 

this way we could on the contrary have KratosComponents to include the headers of such classes, which is actually a much more logical dependence...

**Comment by pooyan-dadvand** [comment]
I agree that this part can be improved a lot. 

I sould check if we can remove the kratos_components.h from variable but I agree with it. (we need it only in cpp). 

For element and conditions  may be we should add a registered_components.cpp and register all of them there.

**Comment by RiccardoRossi** [comment]
I think we should take a look to this.

**Comment by pooyan-dadvand** [comment]
yep but after the release 5.2

**Comment by pooyan-dadvand** [comment]
We could not finished this bugfix for the release 5.3 neither. Postponed to the next release.

**Comment by pooyan-dadvand** [comment]
Let's wait until I finish the AMatrix, so I can start with Registry which address this issue.
