### ISSUE TITLE
const and non-const ProcessInfo&  in Element.h and Condition.h

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#1897]
It is just to remember that there are still inconsistencies in the arguments of the element base class, that was discussed a long time ago, and some cast was applied to solve the conflicts in the methods arguments. 

For security all ProcessInfo parameters passed to elements and conditions must be constant references, but changing them mean to review all kratos elements and conditions,  for all applications and make them consistent. 

Suggestion:
C++ allows functions to be overloaded on the basis of const-ness of parameters only if the const parameter is a reference or a pointer. --> maybe, in a first step, methods that contain a non-const reference ProcessInfo can be overloaded (with a const reference) and marked as deprecated,  the second step would be to replace them progressively in all applications

**Comment by RiccardoRossi** [comment]
Deprecating is not a bad idea,
         however the use of override should help us a lot here. If now override is consistently used everywhere (which should be the case, otherwise we would get many warnings), it simply wouldn't compile if we change it in the base class.

**Comment by loumalouomega** [comment]
For deprecating we need c++14?

**Comment by loumalouomega** [comment]
https://stackoverflow.com/questions/32463839/inheritance-from-deprecated-class

This can be useful

**Comment by RiccardoRossi** [comment]
we have been discussing this in the @KratosMultiphysics/technical-committee.

we are convinced that now that we have the overrides in place the good way is to add the const in the core, and deal with the compiler errors.

Our proposal is thus to mark as deleted the old version. This implies for example defining BOTH the const and non const version, deleting the non const

    virtual void EquationIdVector(EquationIdVectorType& rResult,
                                  const ProcessInfo& rCurrentProcessInfo)
    {
        if (rResult.size() != 0)
            rResult.resize(0);
    }

    virtual void EquationIdVector(EquationIdVectorType& rResult,
                                   ProcessInfo& rCurrentProcessInfo) = delete;

this of course would make all elements not to compile, and is thus a big change. Let's do this, once the AMatrix porting is done.

**Comment by josep-m-carbonell** [comment]
Closed due to inactivity. Reopen if needed

**Comment by maceligueta** [comment]
I am afraid we might forget about this improvement if we close the issue.

**Comment by philbucher** [comment]
this is part of #2993 , which will be merged hopefully not too far from now :)

**Comment by maceligueta** [comment]
Great, closing then.

**Comment by philbucher** [comment]
done in #4938
