### ISSUE TITLE
Warnings removal campaign (missing overrides)

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#1899]
Dear Kratos developers and @KratosMultiphysics/team-maintainers ,
After adding the compilation flag _suggest-override_ the nightly build throws 24k+ warnings.
The procedure to remove them should be application by application (or groups of applications), so separate pull requests will be opened for each application or group.

- [x] Structural and Contact Structural

- [x] SolidMechanics and Constitutive Models

- [x] Fluid Dynamics

- [x] DEM

- [x] Swimming DEM

- [x] ConvectionDiffusion

- [x] ThermoMechanical

- [x] Poromechanics

- [x] ParticleMechanics

- [x] DAM

Please edit these groups at will.

**Comment by loumalouomega** [comment]
I am checking right now and I think both Structural and Contact Structural are clean on the override side

**Comment by loumalouomega** [comment]
Effectively, here you can see like the combined grep for the structural is empty in comparison of the DamApplication
![imagen](https://user-images.githubusercontent.com/19991680/38981833-9baa5e86-43c0-11e8-98b4-231a905ee10d.png)

**Comment by roigcarlo** [comment]
Ok I am marking them as completed thx!

**Comment by philbucher** [comment]
@maceligueta are you sure there are warnings coming from FluidDynamics and DEM? I compiled those apps when I added the warning and added the missing overrides

**Comment by maceligueta** [comment]
There are a few from Swimming DEM, which I fixed yesterday in a branch. Fluid Dynamics can be marked as done if it doesn't have any.

**Comment by jcotela** [comment]
FluidDynamics and DEM are clean, I don't get any matches when doing a grep of the warning list (each name appears 4 times, but it is in the configuration and testing).

I can take care of the ThermoMechanical to start (1140 warnings).

**Comment by jcotela** [comment]
There are a couple from the FSI, but those should be fixed by #1846

**Comment by ipouplana** [comment]
I'll fix the ones from Poromechanics.

**Comment by ipouplana** [comment]
@joaquinirazabal could you look into the missing overrides of Dam Application? I can help

**Comment by joaquinirazabal** [comment]
Ok @ipouplana I will do it and ask you if I need help. Thanks!

**Comment by joaquinirazabal** [comment]
#1913

**Comment by ipouplana** [comment]
@josep-m-carbonell are you adding the overrides in the SolidMechanics' Constitutive laws? If not, I could do it.

**Comment by jcotela** [comment]
Also, is someone taking charge of convection diffusion? I can do that one if needed.

**Comment by josep-m-carbonell** [comment]
It is done I will start a PR.

**Comment by bodhinandach** [comment]
I have updated the ParticleMechanicsApplication. PR submitted with the other code modifications. #1916

**Comment by roigcarlo** [comment]
I think we can close the issue, nightly log is mostly clean

**Comment by maceligueta** [comment]
Great! Thanks everyone!
