### ISSUE TITLE
[StructuralMechanicsApplication] CL tests not passing due to problematic merge

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#1903]
Hi @PhilippeBussetta , in your commit 26601cb the test_constitutive_law was modified with and older block of code. See the [file history](https://github.com/KratosMultiphysics/Kratos/commits/master/applications/StructuralMechanicsApplication/tests/test_constitutive_law.py)

Currently the CL tests are not passing.

CC @loumalouomega

**Comment by loumalouomega** [comment]
I will take a look

**Comment by PhilippeBussetta** [comment]
Hi @marandra 
I don't understand which block, which function?
Did you speak about the geometry?

**Comment by marandra** [comment]
@PhilippeBussetta  yes, in the  `_create_geometry` function, but there may be other changes besides that. I think the last correct version is in commit 9b5858f by @loumalouomega , just before your merge.

**Comment by PhilippeBussetta** [comment]
I think that the geometry have any influence on the computed solution. Thus we can limit the geometry to Triangular in 2D or Tetrahedral in 3D. The strain is computed from F without any influence of the element type. Moreover, I think we could rewrite the tests of J2Plasticity law using the `_generic_constitutive_law_test` to reduce the duplicated code.

**Comment by marandra** [comment]
At the moment the problem is that some modifications were reverted by the commit 26601cb, leaving it broken. For example, I modified the _create_geometry to consider quads and hexas, necessary to test the plasticity CL, and those additions were reverted in that commit on march 28th. Without those geometries the tests should fail.

I think that conceptually you should revert the changes in 26601cb made to that file, and apply your commits 428091c and 4cf50b7 on top of 9b5858f (see the file history)

**Comment by loumalouomega** [comment]
All CL tests work for me, where is the problem?

**Comment by marandra** [comment]
Everything working here now too.
@PhilippeBussetta after our conversation, I checked in detail and the test should have worked anyways. Not really sure why, but I ended up with unsynchronized files on my side. Nice cleanup by the way. Let's chat on Monday about the CLs.
@loumalouomega thanks for checking.
