### ISSUE TITLE
Linking takes significantly longer after porting to pybind

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#1908]
We noticed, that the linking in Linux and hence the compilation now takes significantly longer after porting Kratos to pybind. It would be just interesting to know if this indeed is now the case or just an issue with the settings.

Thanks in advance.

**Comment by RiccardoRossi** [comment]
@dbaumgaertner i think that compilation does not take longer. It is linking. the point is that LTO (Link Time Optimization) is on by default with pybind. I think there is an option that can be passed to the cmake to avoid this.

can u try to add "-flto=thin" to your CXX_FLAGS?

**Comment by roigcarlo** [comment]
As @RiccardoRossi  says, we will take a look at this. You can also try to use the gold linker in the meantime, its considerably faster

**Comment by roigcarlo** [comment]
So I ran a configuration matrix of the link times (for clean builds only) with Clang 5.0.1:

Linking times (seconds)

| Target        | Regular           | ThinLTO  | Gold | Both
| ------------- | -------------:|-----:|-----:|-----:|
| libKratosCore.so      | 4 | 4 | 5 | 5 |
| Kratos.cpython-36m-x86_64-linux-gnu.so | 140 | 39 | 147 | 40 | 
| KratosExternalSolversApplication.cpython-36m-x86_64-linux-gnu.so | 5 | 6 | 5 | 7 |
| libKratosDEMCore.so | 0s | 1s | 1s | 1s |
| KratosDEMApplication.cpython-36m-x86_64-linux-gnu.so | 11 | 12 | 10 | 12 |

Conclusions 
- We have to add ThinLTO
- Gold only improves incremental linking

**Comment by RiccardoRossi** [comment]
I vote for adding THIN_LTO in all of the modules

**Comment by roigcarlo** [comment]
Yep already done the PR :P
