### ISSUE TITLE
[ShapeOptimizationApplication] Primal results on model part after response evaluation

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#1914]
After the evaluation of a response function (with a primal structural analysis), the model part contains information about the deformed state. This can be a problem because the next response function should receive a "clean" model part to evaluate.

Two situations have to be distinguished: 

1) When several response functions are called after each other, there has to be a mechanism (e.g. a clear-function) that makes sure, the subsequent response operates on a clean mdpa if necessary --> responsibility of the user

2) After the internal / external analyzer is called, a logic has to make sure that possible shape modificatinons during the analyses are reset. --> responsibility of the optimizer

TODO: find proper way to reset the model part after it was evaluated by a response.  
- [x] Introduce a logic to address 1.
- [ ] Introduce "clear-functions" in the response classes
- [x] place clear-functions properly in the analyzer
- [ ] Evaluate if there is a global solution using e.g. core features instead of the ModelPartController in the ShapeOptimizationApp

**Comment by philbucher** [comment]
Wouldn't it be easier to create a git-project for the ShapeOptApp?

There you could have a better overview of all the current issus. Plus you would have an overview of the completed ones too

**Comment by armingeiser** [comment]
Good idea!

**Comment by dbaumgaertner** [comment]
@armingeiser The corresponding branch for developments is [this](https://github.com/KratosMultiphysics/Kratos/tree/fix-analyzer-behavior-in-opt).

**Comment by philbucher** [comment]
is this solved?

**Comment by philbucher** [comment]
ping

**Comment by armingeiser** [comment]
In the internal analyzer the results are cleared after each response function evaluation. 
After the external analyzer is done, the same happens.
