### ISSUE TITLE
Builder and Solver -- ConstructMatrixStructure going through scheme

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#192]
The IntializeAndResize  function in residual_based_block_builder_and_solver.h, while building the matrix structure, is asking for the equation ids of the element. 

Instead it should go through the scheme and ask it for the equation ids to be consistent with build calculating local systems from the scheme. 

If this is not the case, it will have unexpected effect on the assembly when the equationIDs are changed by the scheme, since it will try to write on unallocated positions in the compressed matrix.

**Comment by RiccardoRossi** [comment]
@adityaghantasala , i think your remark makes full sense.

just we need to make sure to do this correctly, that is, not to break anything in the process.

I guess that the scheme should have a function 
ElementGetDofList
ConditionGetDofList

which in the base class directly call the one of the element.
in derived classes we could override this functions as needed

would that suit you?
Riccardo

**Comment by adityaghantasala** [comment]
@RiccardoRossi  Yes I think this will be more consistent . Also works well for me. 

In that case the function EquationIdVector should also be from the scheme. in the lines 1030 to 1070  residual_based_block_builder_and_solver.h , this function is used and the resultant ids are used for making the matrix structure. I think this is the function which effects the structure of matrix A. Please correct me if I understood it wrong.

**Comment by RiccardoRossi** [comment]
@adityaghantasala this should be done also in the "elimination" version of the builder and solver, not just in the block version.

could u propose an implementation for this and make a pull request? 
i think this should touch the two residual builder and solvers and the base class of the scheme

i promise a detailed review of your proposal. In any case once the proposal is done, please consider that prior to merging we'll have to discuss this with all the group. I am telling this since the merging may take a little longer than other changes

**Comment by adityaghantasala** [comment]
@RiccardoRossi  I think the change that we want to pass the element through scheme to get the elementIds will have to be propagated through all the builder and solvers. 

This is because, the current function definition (virtual) of ResizeAndInitialize function has no scheme passed to it. So when I change this function, it should be propagated to all the builder and solver. 

Other wise one can store a pointer to the scheme in the base class of builder and solver and use it. Which one do you think is more correct way of doing it.

**Comment by jcotela** [comment]
This is just to say that I think that @adityaghantasala's proposal makes sense, since our current design is somehow inconsistent (we go through the scheme to fill the matrix but not to allocate it). It would be  a pretty wide-reaching change, though.

**Comment by RiccardoRossi** [comment]
yes, propagating the scheme in the calls to ConstructMatrixStructure will be needed.

**Comment by pooyan-dadvand** [comment]
I agree

**Comment by RiccardoRossi** [comment]
closing since i would say that an agreement has been reached. We'll be waiting for a proposal of pull request following this

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi it would be better to leave the issue open as a reminder and use the auto close feature of GitHub by mentioning something like this fix #192 in the pull request
