### ISSUE TITLE
Enabling -Werror in Travis

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1923]
Hi @KratosMultiphysics/technical-committee 
The compilation of Kratos is currently mostly clean of warnings and a lot effort is been done to clean it

we could add the compiler Flag `-Werror` to Travis to turn compiler warnings into errors in order to keep it clean

**Comment by roigcarlo** [comment]
Almost there, but I think we still have to solve a 

`memset used with constant zero length parameter;`

That has been appearing for quite some time now in travis. Not sure what is causing this warning (or if it is even a gcc warning, it does not follow the signature) but we should solve this before.

**Comment by roigcarlo** [comment]
I will keep an eye on it and add it when no warnings appear in Travis
