### ISSUE TITLE
Improvements & suggestions

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#1926]
In the last days I've been thinking about some ideas of improvements that could be done, in my opinion, that would improve the flexibility of the code in general.

 - Could be possible to use different **time steps / Error tolerance / MaxIterations** according to a certain data set provided?

 - In my case if I want to plot some data about the elements/nodes in a file I do it through python but I think that could be useful to have a general feature to plot data in a file.

Thank you,

**Comment by loumalouomega** [comment]
@pooyan-dadvand correct me if I am wrong, but the idea of the logger is to unify the output and be able to not just "print" an output on the terminal, but files too

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-Logger

**Comment by philbucher** [comment]
@AlejandroCornejo for printing stuff from elements you could use the `PointOutputProcess` in the core

It supports elements but I am currently extending it to also work with nodes

**Comment by AlejandroCornejo** [comment]
Thank you @philbucher , I'll take a look.

**Comment by RiccardoRossi** [comment]
@AlejandroCornejo were u reffering to the gid_io?

**Comment by maceligueta** [comment]
@loumalouomega , I think you are right. The Logger can Add additional outputs (file, for example) but apparently you can't switch. Is this right, @pooyan-dadvand @roigcarlo ?
Could we have coexisting Loggers? Like one Logger for console, another one for a file, then choose one or the other depending on the type of information we are printing. Like 
`KRATOS_INFO(ChosenLogger, Label)<<"whatever"<<endl;`
where ChosenLogger can be an integer, a string, ... I don't know.
Another possibility is to switch between outputs: now the Logger prints to console and file1, now the Logger prints to file2, now back to console and file1. Kind of unconfortable.

**Comment by pooyan-dadvand** [comment]
Logger is designed for output messages and may become an efficiency bottleneck if used for saving many data.  For the output in file we had the sensor object long ago which can be ported to C++ for such problems.

Regarding the logger outputs, as @maceligueta mentions you can have different outputs and filter what you show in each of them. For example having a console output (which is the default output) which filters for info and warning messages and some solver_info file which filters messages related to the convergence and iteration numbers of the solver base on the labels of the messages.

**Comment by philbucher** [comment]
+1 for the suggested solver info

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by loumalouomega** [comment]
This is related with https://github.com/KratosMultiphysics/Kratos/issues/2165

**Comment by loumalouomega** [comment]
@AlejandroCornejo  After what we said this morning, should we create any utility to generate output files for generating graphics?

**Comment by AlejandroCornejo** [comment]
I think that could be an interesting feature to plot, especially, gauss points variables because GiD performs an interpolation to the nodes and the values are modified because of that...

In my App I've implemented some methods to print info using the .json to ask the nodes/elements to be printed so we can follow his line or you can suggest a better way.

**Comment by loumalouomega** [comment]
The question is which app use to plot. There are many options

**Comment by loumalouomega** [comment]
I found this frikada:

https://github.com/fbbdev/plot

**Comment by marandra** [comment]
Why do we need to plot the data? Why not just write the output file, and leave the plotting to an external tool or script (e.g. gnuplot, Excel, matplotlib)

**Comment by loumalouomega** [comment]
Sure, we can use csv, which is a standard

**Comment by AlejandroCornejo** [comment]
yeah @marandra, my original idea was to develop a tool for printing the data in a txt o whatever and then manage this info with excel, gnu...

**Comment by loumalouomega** [comment]
I think we still have not solved this

**Comment by pooyan-dadvand** [comment]
If we wan to create a csv file I would go for porting the `Censor` class from python to C++

**Comment by philbucher** [comment]
is this still active?

**Comment by AlejandroCornejo** [comment]
In addition I'd suggest to think about an strategy/scheme that could behave as Static or dynamic according to TIME or any other variable. (imagine strating as static to apply BC asnd the dynamic to perform the rest of the calculation)

**Comment by loumalouomega** [comment]
The scheme is responsible of that in principle

**Comment by AlejandroCornejo** [comment]
The @KratosMultiphysics/implementation-committee thinks that the need for an standarized to generate raw data files in a convenient way is there. So it is important to study how to extend the current Logger to support such basic function. @AlejandroCornejo will study the issue and propose a design.

**Comment by pooyan-dadvand** [comment]
Just thinking load:
1. I think we should go for a new `DataCollector` class with some derived classes for getting data from solvers, mesh, etc.
2. The difference between this one and the 'Logger' would be the fact that for Logger each object pushes the info, and `LoggerOutput` is in charge of writing it (or not). But in this case, `DataCollector` would select the data to be taken that can be used for writing or postprocessing (i.e. changing timestep due to some maximum value)
3. We may have a proper method of DataCollector which takes a `LoggerOutput` and writes its collected data in the format defined by that output.

**Comment by loumalouomega** [comment]
This was basically what I was suggesting for the logger manager :)
