### ISSUE TITLE
Compiler error C2134 in core

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#1929]
I tried to compile the current master branch in Windows (for the first time since the pybind porting) and i get the following error:

```
F:\04_Development\Kratos\kratos\includes/fnv_1a_hash.h(64): error C2134: 'Kratos::FNV1a32Hash::CalculateHash': call does not result in a constant expression [F:\04_Development\Kratos_build_windows\kratos\KratosCore.vcxproj]
  F:\04_Development\Kratos\kratos\includes/fnv_1a_hash.h(64): note: failure was caused by call of undefined function or one not declared 'constexpr'
  F:\04_Development\Kratos\kratos\includes/fnv_1a_hash.h(79): note: see declaration of 'Kratos::FNV1a32Hash::CalculateHash'
F:\04_Development\Kratos\kratos\includes/fnv_1a_hash.h(130): error C2134: 'Kratos::FNV1a64Hash::CalculateHash': call does not result in a constant expression [F:\04_Development\Kratos_build_windows\kratos\KratosCore.vcxproj]
  F:\04_Development\Kratos\kratos\includes/fnv_1a_hash.h(130): note: failure was caused by call of undefined function or one not declared 'constexpr'
  F:\04_Development\Kratos\kratos\includes/fnv_1a_hash.h(145): note: see declaration of 'Kratos::FNV1a64Hash::CalculateHash'
```

I assume that i did something wrong, because on my colleagues computer it works.
Maybe someone has an idea what i did wrong?

Thanks in advance!

**Comment by armingeiser** [comment]
Some more information:
- Visual Studio 14 2015 Win64
- Python 3.4
- (boost_1_59_0) i assume this is not critical anymore

**Comment by RiccardoRossi** [comment]
you need 2015 **update 3** ... unfortunately ...

**Comment by armingeiser** [comment]
@RiccardoRossi thanks!
I still have the old version without update 3 (if i recall correctly because of boost).
In this case i will directly try 2017.

**Comment by roigcarlo** [comment]
Yep 2015 update 3 or 2017, both should work just fine. As far as I know except one boost version (I believe it was 1.62) every combination of boost + Python should work

**Comment by armingeiser** [comment]
@roigcarlo in an old issue #179 you mentioned that it is not recommended to use Anaconda, is this still the case?

**Comment by roigcarlo** [comment]
Haven't tested myself, but now it shouldn't be a problem as long as the PYTHON_EXECUTABLE points to the anaconda python.exe

**Comment by jginternational** [comment]
In my experience of the windows compilation process, I prefer Visual Studio 2017 x64 for Kratos

**Comment by armingeiser** [comment]
Thank you guys, i will try it and let you know if it worked!

**Comment by armingeiser** [comment]
I tried with 
- Visual Studio 2017 x64
- boost 1.66
- python 3.4.
I get the error C1002 as described in the WIKI. The memory consumption builds up to ~13Gb for the build process and then my physical memory (16Gb) is full.
However i did set the x64 toolset as suggested in the WIKI. This is one line of the output that should show that the correct toolset is used: 
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.13.26128\bin\HostX64\x64\link.exe
```

Is 16GB not enough to build Kratos in Windows? 
Any help is appreciated!

**Comment by roigcarlo** [comment]
Hi @armingeiser

16 are more than enough. Actually the problem is not your physical memory, but the memory the compiler is allowed to allocate. Setting the x64 toolset allows, but not forces, the compiler to allocate more than 3G. 

Sadly this keeps appearing every now and then.

It usually helps to make a clean build of kratos & kratosCore, try that and let me know if it works. This is not a consistent solution but the problem is compiler-side, and honestly there is little we can do apart from filling reports in the VS forums...

**Comment by armingeiser** [comment]
First of all thanks for your quick answer (as always)!

Unfortunately thats bad news =/.
I actually already tried a few clean builds (deleting the hole build directory except for the configure script. Also i tried builds from command line and from within Visual Studio.

I was able to do a clean build of Kratos&KratosCore, but again when i build the ALL_BUILD or INSTALL afterwards it fails.
What i don`t get is, that for me it looks like it is allocating far more than 3 GB right before failing:
![image](https://user-images.githubusercontent.com/25903585/39195963-414d5e46-47e1-11e8-80fe-e2c88fe7d904.png)


By the way: I am getting a warning that my boost version is older then the compiler. But i assume it is not related.

**Comment by roigcarlo** [comment]
No problem with the boost version.

I've been googling a little in the meantime, and I've found a couple of things you can try.

1 - Seems that according to some developers visual studio now enables the _Profile Guided Optimization_  `/LTCG:PGOptimize` which may cause this error to appear more frequently, even with the x64 toolset. 
This option is in: 
`Properties -> Linker -> Optimization -> Link Time Code Generation`.
I've tried several ways to generate Kratos with the CMake and it was not active in any of them, but maybe its worth a try to look at it (more info [here](https://social.msdn.microsoft.com/Forums/en-US/d2c4bb60-e558-4dc6-a0ba-47611d45bc86/c1002-compiler-is-out-of-heap-space-in-pass-2?forum=vcgeneral))

2 - We are well aware of which file is causing the problem and in fact we can disable its compilation, but most of kratos solvers will stop working. @RiccardoRossi would it be possible in his case?

**Comment by armingeiser** [comment]
1 - The ```/LTCG:PGOptimize``` is also not active in my case. If i switch it on, i get an error that a a ```Kratso.pgd``` file is not found.

2 - mostly I am using the the AMGCL solver and the ones from EigenSolversApplication. As an intermediate solution i could also completely switch to the EigenSolversApplication.

**Comment by armingeiser** [comment]
I am considering to try the ```MinGW``` compiler. Do you have any experience with that?

**Comment by roigcarlo** [comment]
I did try that once for curiosity but I wasn't able to get it compiler,
truth to be told I didn't put much effort in it. Probably should be possible

Another possibility is to use clang as a backend compiler with visual
studio. That also was unsuccessful last time I tried (about a year ago) due
to a problems with the stl lib implementation that clang was using but
maybe it's worth another try

**Comment by roigcarlo** [comment]
I did try that once for curiosity but I wasn't able to get it compiler,
truth to be told I didn't put much effort in it. Probably should be possible

~~Another possibility is to use clang as a backend compiler with visual
studio. That also was unsuccessful last time I tried (about a year ago) due
to a problems with the stl lib implementation that clang was using but
maybe it's worth another try~~
**Edit**: Does not work.

**Comment by RiccardoRossi** [comment]
@armingeiser some time back i had a similar problem with a old version of the compiler being left in the system and being called from cmake. Could u take a look if that is the case? (my advice would be to try configuring in a completely empty directory and take a very careful look at the cmake messages

...good luck... (please paste the configure output so that we can make some more noise in the form of opinions :-D)

**Comment by armingeiser** [comment]
- my configure.bat:
```
SET CURRENT_DIRCTORY=%cd%
call "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/Tools/vsdevcmd" -arch=x64
cd %CURRENT_DIRCTORY%

cmake -G "Visual Studio 15 2017 Win64" -T host=x64                                  ^
-DCMAKE_BUILD_TYPE=Release                                                          ^
-DCMAKE_CXX_FLAGS=" -D_SCL_SECURE_NO_WARNINGS "                                     ^
-DBOOST_ROOT="F:/05_Software/Windows/boost_1_66_0/"                                 ^
-DPYTHON_LIBRARY="C:/Users/Geiser/AppData/Local/Programs/Python/Python36/libs/python36.lib"  ^
-DPYTHON_EXECUTABLE="C:/Users/Geiser/AppData/Local/Programs/Python/Python36/python.exe"      ^
-DPYTHON_INCLUDE_PATH="C:/Users/Geiser/AppData/Local/Programs/Python/Python36/include"       ^
-DLAPACK_LIBRARIES="F:/05_Software/Windows/external_libs_2/liblapack.lib"            ^
-DBLAS_LIBRARIES="F:/05_Software/Windows/external_libs_2/libblas.lib"                ^
-DSTRUCTURAL_MECHANICS_APPLICATION=ON					                             ^
-DINSTALL_PYTHON_FILES=OFF                                                           ^
-DINSTALL_EMBEDDED_PYTHON=ON                                                         ^
-DKRATOS_INSTALL_PREFIX="F:/05_Software/Windows/KratosInstall/Release/kratos"        ^
-DUSE_COTIRE=ON                                                                      ^
-DBOOST_CONFIG_SUPPRESS_OUTDATED_MESSAGE=ON                                          ^
../

Msbuild.exe INSTALL.vcxproj /t:Build /p:PreferredToolArchitecture=x64 /p:Configuration=Release /p:Platform="x64"
```

- first lines of the CMAKE output:
```
-- The C compiler identification is MSVC 19.12.25835.0
-- The CXX compiler identification is MSVC 19.12.25835.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.12.25827/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
```

- during compilation the right compiler/linker seems to be used:
```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\CL.exe ...
```

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.12.25827\bin\HostX64\x64\link.exe  ...
```

- the error:
```
     Bibliothek "F:/04_Development/Kratos/windows_cmake_build/kratos/Release/Kratos.lib" und Objekt "F:/04_Development/Kratos/windows_cmake_build/kratos/Release/Kratos.exp" werden erstellt.
  Code wird generiert.
f:\04_development\kratos\kratos\python\add_model_part_to_python.cpp : fatal error C1002:  [F:\04_Development\Kratos\windows_cmake_build\kratos\Kratos.vcxproj]
f:\04_development\kratos\kratos\python\add_modeler_to_python.cpp : fatal error C1002:  [F:\04_Development\Kratos\windows_cmake_build\kratos\Kratos.vcxproj]
f:\04_development\kratos\kratos\python\add_kratos_application_to_python.cpp : fatal error C1002: Im 2. Durchlauf ist kein Heapspeicher mehr f³r den Compiler verf³gbar. [F:\04_Development\Kratos\windows_cmake_build\kratos\Kratos.vcxproj]
f:\04_development\kratos\kratos\python\add_serializer_to_python.cpp : fatal error C1002:  [F:\04_Development\Kratos\windows_cmake_build\kratos\Kratos.vcxproj]
LINK : fatal error LNK1257: Fehler bei Codegenerierung. [F:\04_Development\Kratos\windows_cmake_build\kratos\Kratos.vcxproj]
```

**Comment by armingeiser** [comment]
A short list of what i tried in the meantime (always starting from a clean build directory):
- Installed a slightly older VS2017 (15.7.7): same problem with increasing memory usage and finally C1002
- Installed Python36
- Generate Ninja instead of VS project (as done e.g. by @oberbichler): C1002
- clone Kratos again from master
- switch of all applications, trying to compile only the core
- remove almost everything from my PATH so that i make sure no wrong libs are used for whatever reason
- try mingw-w64 build: Compiler error ```definition of static data member 'Kratos::Timer::msGlobalStart' of dllimport'd class``` and many similar ones
- Build a minimal cpp/pybind project: works with both VS and mingw-w64 compiler

I am running out of ideas...

**Comment by roigcarlo** [comment]
Last thing that I can come up with is trying the /m:1 flag. It should cause to use only one core to compile lowering memory requisites but sensibly Increasing compile time.

Also if it is possible you may try to compile on debug, it should not trigger that error as I suspect is caused in the optimization stage of the linker

**Comment by armingeiser** [comment]
Compilation in debug works.

**Comment by armingeiser** [comment]
I was able to compile the release version (until now i only tried cmopiling the core) by changing ```/GL``` to ```/GL-``` in all the files generated by cmake. This disables ```Whole Program Optimization```.
@roigcarlo can you estimate how much this would impact the runtime performance?

EDIT: Also the other applications compile, tests are running.

**Comment by RiccardoRossi** [comment]
can u try

     -DUSE_COTIRE=OFF

**Comment by armingeiser** [comment]
@RiccardoRossi ```-DUSE_COTIRE=OFF``` does also result in C1002 (i i do not replace the ```/GL``` compiler flag.

**Comment by roigcarlo** [comment]
@armingeiser We have not performed any benchmark on the impact of /GL so honestly I have no Idea. I would expect to be minor in the case of Kratos according to its description but I cannot be sure. 

I will try to schedule some benchmarks from the tests and tell you the results

**Comment by roigcarlo** [comment]
@armingeiser We just figure out ( basically @RiccardoRossi did ) that the cmake module from pybind is very... flag intrusive. We are going to take a look to see if some of the changes is making are the cause of this.

**Comment by armingeiser** [comment]
@roigcarlo thanks for keeping me up to date, in the meantime i can work with this intermediate solution i have found.

**Comment by RiccardoRossi** [comment]
i think this is solved. reopen if needed
