### ISSUE TITLE
something wrong or concatenated error 

### ISSUE THREAD

**Issue by vryy** [KratosMultiphysics/Kratos#195]
Hi all

I ran a mesh convergence sudy to check the accuracy of the integration on the quadrilateral 4-node and 9-node isoparametric element. I ran the test for the problem of a cylinder pipe under internal pressure and plane strain condition, by which the analytical solution exists. I obtained optimal convergence for quadrilateral 4-node element in terms of displacement (L2 error) and stress (H1 error). For quadrilateral 9-node element I obtained optimal convergence for H1 error, but not for L2 error. The result can be seen in the attached file.

[convergence_error.pdf](https://github.com/KratosMultiphysics/Kratos/files/859020/convergence_error.pdf)

As can be seen in the graph, the L2 error of Q9 element start to degrade when the error is down to 1e-7. My question is why can't I obtain higher accuracy. I guess that is the concatenated error happen during the integration. What can be done with Kratos to improve this, other than using a higher accurated data type than double? anyone having experience with checking the convergence of finite element mesh before can give some thoughts?

**Comment by loumalouomega** [comment]
@rubenzorrilla and I, we have the other day a problem with the TotalLagrangian Q9 element, solving a dynamic cantilever (self weight) the error increased with the time and the elements inverted after 50 steps on time. We assumed that the problem was related with some error in the geometries, because the solid elements are implemented in a very general way, but we didn't have the time to investigate more the issue. Maybe @josep-m-carbonell has something to add

**Comment by vryy** [comment]
@loumalouomega I used a linear element, with linear elastic material. Therefore, no nonlinearity appears here. Every simulation converges in 1 step.

**Comment by josep-m-carbonell** [comment]
@vryy, Just ask some more details. Which element, (load) conditions and constitutive law are you using ? From which application ?  and what linear solver (and tolerances) ?

**Comment by vryy** [comment]
@josep-m-carbonell i would admit that I'm not using the standard SolidMechanicsApplication. The simulation is performed using structural_application with kinematic_linear element and plane strain material. The applied load is surface load. abs_tol = 1.0e-10, rel_rol=1.0e-6, but the real achieved abs_tol is down to 1.e-14. I think to reproduce this example using SolidMechanicsApplication is not a big deal. My concern is rather more conceptual, that how far Kratos can produce such an accuracy that we need for such an example.
P/S: the linear solver is Pardiso. I don't know what tolerance it uses but it should be machine accuracy.

**Comment by josep-m-carbonell** [comment]
Hello @vryy 
  I think that the precision of a double is enough to obtain the accuracy you want to obtain. Usually the problem of lose of accuracy comes from some type of operations performed during the computation. One that I have detected as problematic is the rest(-) of scalars. If it is used in the calculation of any parameter (in the geometry, for example) we can lose some accuracy. If the operation is repeated several times the error accumulates.
If you share with us the problem details, we can try to run the same tests using the SolidMechanics to see if we have the same results and try to find out if there is any error.

**Comment by vryy** [comment]
@josep-m-carbonell your idea matches with me. Let's run the same example to see if it is the concatenated error or something else. Give me some time to prepare for necessary information.

**Comment by vryy** [comment]
Hi again

Finally I got time to prepare the data for this benchmark, please refer to
http://solidmechanics.org/Text/Chapter4_1/Chapter4_1.php#Sect4_1_9

for the reference geometry and description of this problem

In my computation, I selected the internal pressure as P=0.1e9, inner radii a=100, outer radii b = 200, and the material is plane strain with E=2.1e11 and nu=0.3, t = 1.0. The convergence I obtained is below:

For Q4 mesh:
#mesh_size  n_nodes n_elements  n_dofs  l2_error                h1_error
10x10       121     100         220     0.008808901037897771    0.06984548714201112
20x20       441     400         840     0.002209348664108962    0.03494646500252988
40x20       1681    1600        3280    0.0005528162330920717   0.017476448017946414
80x20       6561    6400        12960   0.00013825087193952915  0.008738634560903485
160x160     25921   25600       51520   3.4570883782151035e-05  0.004369368815259982
320x320     103041  102400      205440  8.647163415475534e-06   0.002184690920346428

For Q9 mesh:
#mesh_size  n_nodes n_elements  n_dofs  l2_error                h1_error
10x10       441     100         840     1.810257570865519e-05   0.0017108229724077256
20x20       1681    400         3280    2.2131875297760683e-06  0.00043368987771489785
40x40       6561    1600        12960   2.7737754288779227e-07  0.00010883430377933785
80x80       25921   6400        51520   3.812111845240987e-08   2.724126788272367e-05
160x160     103041  25600       205440  1.0144447157371059e-08  6.847358856467869e-06
320x320     410881  102400      820480  3.5712589478629954e-09  1.9746920667615886e-06

l2_error = int(|u-u_ana|) / int(|u_ana|)
h1_error = int(|sigma-sigma_ana|) / int(|sigma_ana|)

This is the analytical solution written in python, it's usable if remove the .txt
[analytical_solution.py.txt](https://github.com/KratosMultiphysics/Kratos/files/921098/analytical_solution.py.txt)

The mesh is here:
[data.zip](https://github.com/KratosMultiphysics/Kratos/files/921097/data.zip)
in the case that you want to really match the data.

Please let me know if something is needed

**Comment by josep-m-carbonell** [comment]
Ok @vryy , I will try to run the example, if something more is needed I will ask you.

**Comment by RiccardoRossi** [comment]
@vryy, @josep-m-carbonell is this issue still open? if not please close it

**Comment by josep-m-carbonell** [comment]
Sorry @vryy @RiccardoRossi , I had no time to check the example. I can say that exist some problems with Q8 and Q9 when computing. At least the results in GiD are not shown correctly... So I or we need to look into the problem a little bit more.

**Comment by vryy** [comment]
@RiccardoRossi i think we need more time on this. I anticipate that is important issue, because it can affect the accuracy of the solution
@josep-m-carbonell i always think the concatenated error is the root cause of the problem, given that the quadrature is only up to machine accuracy. During calculation there are no explicit mechanism to suppress that error.
What do you mean by results in GiD not shown correctly? I guess you use GiD 13, meanwhile I used GiD 12.
Moreover, i think this problem can be reproduced with any current examples in Kratos benchmarking, providing that it has an analytical solution to compare.

**Comment by RiccardoRossi** [comment]
hi both,
ok, no problem!

cheers
Riccardo

**Comment by RiccardoRossi** [comment]
Closing since it is inactive since long-time. Please reopen if you consider it necessary

**Comment by philbucher** [comment]
Actually closing

**Comment by vryy** [comment]
This problem is fixed by improving the accuracy of the mesh. Actually closed.
