### ISSUE TITLE
How to define Variables

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1951]
Hi @roigcarlo 
We are currently trying to define the same variable in two apps (afaik this is possible now right?)

Should we use `KRATOS_DEFINE_APPLICATION_VARIABLE` or `KRATOS_DEFINE_VARIABLE`?

Or what is generally the difference, when should we use what?

Thanks in advance

**Comment by roigcarlo** [comment]
Hi, yep that should work.

- `KRATOS_DEFINE_APPLICATION_VARIABLE`: This one needs to be used if your variable is gonna be used by another application that depends on yours or if the variable appears in the interface (any of the `add_xxx_to_python.cpp`).

- `KRATOS_DEFINE_VARIABLE`: If it is only used inside the cpp of the core. If you don't have the distinction between core and application just use this one.

**Comment by philbucher** [comment]
perfect, thx, closing then

@tteschemacher FYI
