### ISSUE TITLE
Compile error using "sh configure.sh"

### ISSUE THREAD

**Issue by geoyanzhan3** [KratosMultiphysics/Kratos#1955]
Hi Kratos Team, 

I am studying volcanology. And your code seems very premising in modeling the volcano deformation involving multiphysical processes.

I am try to install the Kratos on my iMac (High Sierra 10.13.4). And I have followd your instruction which is very helpful.  But I have difficulties in compiling Kratos. I will appreciate it if you can help me solve this problem.

I got error messages:

make[2]: *** No rule to make target `../python3.5m', needed by `embedded_python/runkratos'.  Stop.
make[1]: *** [embedded_python/CMakeFiles/runkratos.dir/all] Error 2
make: *** [all] Error 2

I have also attached the log containing the error messages and the "configure.sh" I used for your convinence. 

Thank you very much, 
Yan
UIUC
[Kratos_complile_error.txt](https://github.com/KratosMultiphysics/Kratos/files/1947930/Kratos_complile_error.txt)

[configure_sh.txt](https://github.com/KratosMultiphysics/Kratos/files/1947933/configure_sh.txt)

**Comment by loumalouomega** [comment]
@ipouplana Is the expert on OSX compilation

**Comment by geoyanzhan3** [comment]
Thank you! @loumalouomega

**Comment by ipouplana** [comment]
Hi @geoyanzhan3 , looking at your configure.sh, I've noticed that you don't have the line of DPYTHON_LIBRARY:

`-DPYTHON_LIBRARY="/Library/Frameworks/Python.framework/Versions/3.5/Python"                  \`

(modify it for the location of your python). Also, the last line (regarding DEXCLUDE_ITSOL) does not have the backslash '\\' that is needed:

`-DEXCLUDE_ITSOL=ON  \`

Other than that, I don't see any more errors...

**Comment by geoyanzhan3** [comment]
Thank you very much @ipouplana 

Here is my directory to python.

-DPYTHON_EXECUTABLE="/Users/yanzhan/anaconda/pkgs/python-3.5.2-0/bin/python"        		\
-DPYTHON_INCLUDE_DIR="/Users/yanzhan/anaconda/pkgs/python-3.5.2-0/include/python3.5m"		\

And I also screenshot the path on my iMac. Did you see any problem in them?

And also, I don't know which path should be my "-DPYTHON_LIBRARY=".

:)Yan

![screen shot 2018-04-25 at 12 59 29 pm](https://user-images.githubusercontent.com/35808906/39263731-a9e253ec-4888-11e8-9d93-5a13e6385f0a.png)
![screen shot 2018-04-25 at 12 59 17 pm](https://user-images.githubusercontent.com/35808906/39263732-a9f22b28-4888-11e8-8cfe-6c9aa17e0654.png)

**Comment by geoyanzhan3** [comment]
Thank you @ipouplana !

I got it! 

![screen shot 2018-04-25 at 1 22 31 pm](https://user-images.githubusercontent.com/35808906/39265008-d393abf2-488b-11e8-9866-332e7a3f9eef.png)

**Comment by ipouplana** [comment]
You’re welcome
