### ISSUE TITLE
Problems with porting to pybind

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#1959]
Good morning,

I've just started following the steps to port to pybind, I've included the` include(pybind11Tools)` and I've modified the `pybind11_add_module(KratosFluidDynamicsApplication MODULE ............. )` but I got an error doing the configure with this line of the CmakeLists:

pybind11_add_module(KratosFemToDemApplication MODULE ${KRATOS_FEM_TO_DEM_APPLICATION_SOURCES})
**target_link_libraries(KratosFemToDemApplication KratosSolidMechanicsApplication KratosCore )**

with this message:

CMake Error at applications/FemToDemApplication/CMakeLists.txt:32 (target_link_libraries):
  Target "KratosSolidMechanicsApplication" of type MODULE_LIBRARY may not be
  linked into another target.  One may link only to STATIC or SHARED
  libraries, or to executables with the ENABLE_EXPORTS property set.

What should I do?

Thank you,
@roigcarlo 
Alejandro

**Comment by jcotela** [comment]
Hi @AlejandroCornejo, I belileve you need to link to the C++ part of the SolidMechanics, not the python moudle:
```
target_link_libraries(KratosFemToDemApplication KratosSolidMechanicsCore KratosCore )
```

**Comment by AlejandroCornejo** [comment]
It worked!, thank you @jcotela , when I finish porting I will close the issue just in case...
