### ISSUE TITLE
On dropping Python 2.7

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#1966]
Support for Python 2.7 was maintained mainly because of clusters and some linux distributions. Some of them have Python 2.7 and boost-python is compiled with Python 2.7.
However, they usually have Python 3 as well. Now that we don’t depend on boost-python, we think support for Python 2.7 can be dropped. In this case, Kratos would stop if the Python version is <3.
Short discussion of the possibility of requiring Python > 3.5, however, finally it is decided to require >=3.
The rest of the Kratos Community can bring their opinions about these decisions.
@philbucher waits for a response from the industry in issue #1905

**Comment by maceligueta** [comment]
FYI @KratosMultiphysics/team-maintainers

**Comment by RiccardoRossi** [comment]
given the feedback that python2.7 is still essential for industry, we @KratosMultiphysics/technical-committee  agree on mantaining support. closing this issue

**Comment by philbucher** [comment]
I am still waiting for their reply thats why I haven't answered yet
