### ISSUE TITLE
MUMPS Parallel sparse direct solver

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1969]
I was looking into the above mentioned solver and how to integrate it in Kratos. I want to play around and see how it performs compared with the direct solvers of Trilinos.

I saw that it was already used in the MultiScaleApp, but I didn't see that this app could do MPI so I am not entirely sure how it was used.

The Trilinos App would be the best place to add this I guess. 
Or ExternalSolvers? But this one only has non-MPI solvers from what I saw

@KratosMultiphysics/technical-committee @MassimoPetracca 

EDIT here is the [link to the library](http://mumps.enseeiht.fr/)

**Comment by RiccardoRossi** [comment]
Hi @philbucher by chance i have been looking into this. Right now there is a "serial" MUMPS version, but we could do the same as for Pardiso and call it from the eigen interface.

for the parallel one i would propose to have an hangouts to discuss it a bit. In any case i'll be very supportive

**Comment by philbucher** [comment]
Hi @RiccardoRossi sounds good.
I would talk to @oberbichler abt adding it through Eigen, but he is not here today

I will look more into the inclusion of the Parallel version this weekend, we could have a hangouts by the end of next week?

**Comment by loumalouomega** [comment]
Besides to this topic, if you agree I will open an issue to update the current implementation of the PastixSolver (the new version is not retro-compatible, so we need to update the solver)

**Comment by philbucher** [comment]
@loumalouomega fine for me

@RiccardoRossi maybe we could also think abt including the MPI version of pastix then

**Comment by loumalouomega** [comment]
Besides, @philbucher I would like to have in a future a discussion with you in order to implement the contact on MPI (I will send you an email then)

**Comment by philbucher** [comment]
@loumalouomega sounds good, I recently started again with developing the mapping very actively => on [this branch](https://github.com/KratosMultiphysics/Kratos/tree/MappingApp/mapping-framework)

I am designing it very general to work with different mapping methods (IGA-DEM, IGA-FEM, FEM-DEM, mapper for optimization, ...)

It would be good to hear your requirements for the contact

Rest we should do by email though to not pollute this thread too much :)

**Comment by philbucher** [comment]
MUMPS support was added in #1991
