### ISSUE TITLE
Many compiler warnings with Intel Compiler on Linux

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#1973]
When compiling with the Intel compiler there are a lot of compiler warnings like the following:
~~~
In file included from /home/hpc/pr94va/ga59vax3/software/Kratos/kratos/includes/variables.h(29),
                 from /home/hpc/pr94va/ga59vax3/software/Kratos/kratos/includes/constitutive_law.h(28),
                 from /home/hpc/pr94va/ga59vax3/software/Kratos/applications/StructuralMechanicsApplication/custom_python/add_custom_constitutive_laws_to_python.cpp(20):
/home/hpc/pr94va/ga59vax3/software/Kratos/kratos/containers/vector_component_adaptor.h(127): warning #858: type qualifier on return type is meaningless
      const int GetComponentIndex() const {
      ^
~~~

Does this also appear with other compilers?
Should we remove those?

**Comment by philbucher** [comment]
The compiler warning mentioned can be solved by adding "-diag-disable 858" to the cxx flags

@KratosMultiphysics/technical-committee would this be acceptable on a global level?

**Comment by philbucher** [comment]
Also the warning 
~~~
icpc: warning #10193: -vec is default; use -x and -ax to configure vectorization
~~~
appears quite some times, this could be disabled with "-diag-disable 10193"

**Comment by jcotela** [comment]
Personally, I'd be OK with changing the code regarding the const, rather than adding extra flags. Maybe it is a pedantic error, but that const is in fact meaningless.

The `-vec` one, I have no idea where it comes from.

**Comment by philbucher** [comment]
I would at least clean the code regarding the meaningless `const`, I agree that  that is a better solution than disabling the warning

Otherwise one almost cannot see anything because there are so many warnings

if @KratosMultiphysics/technical-committee is ok with it then I would do this in a PR
