### ISSUE TITLE
[ExternalSolversApplication] Updating the Pastix integration + Pastix-MPI

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#1974]
Hi, 

As mentioned in #1969 it would be interesting to update the Pastix Solver in Kratos. The new version of Pastix (6 and following, https://gitlab.inria.fr/solverstack/pastix) is not retrocompatible, so it will be interesting to migrate to the new version (maybe keeping the old one as LegacyPstixSolver during a time) 

Regards

**Comment by philbucher** [comment]
@AndreasWinterstein mentioned that there is also an iterative solver available from pastix, maybe we could include too

**Comment by RiccardoRossi** [comment]
just to tell that the current interface does allow using the pastix gmres+ilu

**Comment by philbucher** [comment]
can we close it?
I think in the long run Pastix is no longer needed

**Comment by philbucher** [comment]
closing since the ExternalSolversApp will be deprecated, and in case someone still wants to use it, then `Eigen` would provide an [interface](https://eigen.tuxfamily.org/dox/group__PaStiXSupport__Module.html)

**Comment by loumalouomega** [comment]
> closing since the ExternalSolversApp will be deprecated, and in case someone still wants to use it, then `Eigen` would provide an [interface](https://eigen.tuxfamily.org/dox/group__PaStiXSupport__Module.html)

In any case we should take the opportunity to add the new Pastix into the EIgenApplication

**Comment by philbucher** [comment]
well this can be done at any point if needed

**Comment by loumalouomega** [comment]
> well this can be done at any point if needed

Of course, just commenting

**Comment by RiccardoRossi** [comment]
Well Pastix IS a pretty cool library, so if Eigen has interface we should use it

**Comment by loumalouomega** [comment]
> Well Pastix IS a pretty cool library, so if Eigen has interface we should use it

We must handcraft it

**Comment by RiccardoRossi** [comment]
https://eigen.tuxfamily.org/dox/group__PaStiXSupport__Module.html

**Comment by loumalouomega** [comment]
> https://eigen.tuxfamily.org/dox/group__PaStiXSupport__Module.html

Thanks, I think it is still the old version (they link to the old repository)
