### ISSUE TITLE
Verify sensitivites of eigenfrequency analysis

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#1975]
There seems to be a systematic deviation to results from global finite differencing.

**Comment by MFusseder** [comment]
I just checked the derivation of the sensitivity relation and I saw that the implemented sensitivity is only valid if the eigenvectors are normalized on the modal mass (transposed eigenvector * mass matrix * eigenvector = 1). The solution of the problem could be that the used eigenvectors are not normalized as mentioned, which would lead to a systematic deviation. I talked with @armingeiser about this and he thinks that there is normalization of the eigenvectors performed.

**Comment by MFusseder** [comment]
In the last sentence I wrote a mistake. I wanted to write that there is NO normalization of the eigenvectors performed.

**Comment by dbaumgaertner** [comment]
thanks @MFusseder . That was it. The problem is going to be fixed with #1976
