### ISSUE TITLE
Turbulence Models

### ISSUE THREAD

**Issue by Jotachiz** [KratosMultiphysics/Kratos#1992]
Dear All,
I'm Joce Uvidia, student from the University of Concepcion (Chile). I'm working in a project about "Softwares for CFD simulations" and I chose "Kratos". I have worked on Ansys Fluent, but Kratos is new for me. So, my question is, Which Turbulence Models does Kratos use? 

Sorry for my English. It's not my native languaje.

**Comment by jcotela** [comment]
Dear Joce,
Kratos does not use a turbulence model by default, although there are some you can try if you need them. If you are looking for LES (large eddy simulation) models, the classical Smagorinsky model is available. Regarding RANS (Reynolds-averaged Navier-Stokes), we have an implementation of the Spalart-Almaras model, although it is a bit old and might not be working as intended (we keep it for legacy reasons, but we haven't given it support and maintenance for a while).
Let us know if you are interested in setting up a simulation using either of them and need help.

**Comment by Jotachiz** [comment]
Thanks for your help. 
I must do a simulation to analyze the efficient aerodynamic in a compressible flow at Ma= 0.8, because I'm doing aerodynamic optimization. So what model should you recommend doing for this case?

**Comment by jcotela** [comment]
The problem you propose is definitely on the compressible flow range. Unfortunately the current CFD solvers of Kratos are designed for incompressible flow, and would not be suitable for your case. We do have a compressible flow solver under development, but it does not yet have support for turbulence modelling at this stage.
