### ISSUE TITLE
Problems in Meshing App when Interpolating internal variables

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#1996]
Good morning,

I have downloaded the latest version of the code and I have an issue when using the **internal_variables_interpolation_process**, the problem appears when I have to interpolate the internal variables directly form the element (not from the CL) because it interpolate always 0.0 values.

I have checked from python that these values are not 0 using:
`for elem in self.FEM_Solution.main_model_part.Elements:
			print(elem.GetValue(KratosFemDem.DAMAGE_ELEMENT))
			print(elem.GetValuesOnIntegrationPoints(KratosFemDem.DAMAGE_ELEMENT,self.FEM_Solution.main_model_part.ProcessInfo)[0][0])`

and efectively they are not null... I attach two figures of the remeshing process. As you can see, the remeshing is done ok but the internal variable is not interpolated (whereas the nodal ones are).

Which could be the problem?

Thank  you.

@loumalouomega 

![imagen](https://user-images.githubusercontent.com/26402605/39516372-052d9594-4dfd-11e8-8040-2b07df2ef4cf.png)

![imagen](https://user-images.githubusercontent.com/26402605/39516379-09c1ad98-4dfd-11e8-939e-757954b315ad.png)

**Comment by loumalouomega** [comment]
Does test_internal_interpolation_process.cpp pass for you?

**Comment by loumalouomega** [comment]
@AlejandroCornejo which element are you using?, the element should have the Get/SetIntegrationValue corresponding method implemented

**Comment by AlejandroCornejo** [comment]
I have implemented the GetValuesOnIntegrationPoints but not the Set__ , maybe that's the problem.

Thank you

**Comment by philbucher** [comment]
is this solved?

**Comment by loumalouomega** [comment]
Yes
