### ISSUE TITLE
Add description in the main GitHub

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#20]
![](https://i.imgur.com/446ghZT.png)

Can you add a short description on the header of the GitHUb main menu?

Thank your very much

**Comment by pooyan-dadvand** [comment]
Good idea. I will.

**Comment by loumalouomega** [comment]
Reminder, TODO

**Comment by loumalouomega** [comment]
Done, I will close this again, thanks @pooyan-dadvand
