### ISSUE TITLE
[Core]Still some boost::python defined on core

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2002]
![imagen](https://user-images.githubusercontent.com/19991680/39551398-27f1815e-4e65-11e8-8ac0-a9558da3b1c7.png)

**Comment by roigcarlo** [comment]
Commented code. But I agree, this should disapear.

**Comment by loumalouomega** [comment]
Some code is commented, but other parts are "using" and so on
