### ISSUE TITLE
Cannot pass Variable<int>& to a constructor from python, probably pybind related.

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#2008]
I have a problem with the constructor of a scheme in the trilinos application, which was exported to python but I am unable to call. The constructor itself is here:

https://github.com/KratosMultiphysics/Kratos/blob/83204aa80398927dccff15ad46f071497b748106/applications/trilinos_application/custom_strategies/schemes/trilinos_predictorcorrector_velocity_bossak_scheme_turbulent.h#L114

And a minimal test example (requires TrilinosApplication, but it is not an mpi case) is here 
```py
from KratosMultiphysics import *
#from KratosMultiphysics.mpi import *
from KratosMultiphysics.FluidDynamicsApplication import *
from KratosMultiphysics.TrilinosApplication import *

print(PATCH_INDEX)

working_scheme = TrilinosPredictorCorrectorVelocityBossakSchemeTurbulent(-0.3,0,3)
broken_scheme = TrilinosPredictorCorrectorVelocityBossakSchemeTurbulent(-0.3,0,3,PATCH_INDEX)

print("Done!")
```
which fails with
```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    broken_scheme = TrilinosPredictorCorrectorVelocityBossakSchemeTurbulent(-0.3,0,3,PATCH_INDEX)
RuntimeError: Unable to load a custom holder type from a default-holder instance
```

The most likely cause of the error is the `const Variable<int>&` argument, since the alternative constructor (without the `Variable` argument) works. However, I do not know how to fix this. What I have tried so far to change the constructor to accept `const Variable<int>` or `Variable<int>&`, but without any luck.

Any ideas @roigcarlo @RiccardoRossi?

**Comment by RiccardoRossi** [comment]
Hi Jordi,

i cannot understnad why it doesn't work. Variable<int> interface is defined in add_containers_to_python.cpp and looks similar to all the others ...

you are compiling with gcc right?

**Comment by jcotela** [comment]
Yes, gcc. I also don't understand why. I got the error report from a colleague (so it is not only on my machine).

**Comment by roigcarlo** [comment]
No idea, maybe it is picky about the `0`, try with `0.0`.
I've tested other functions exported that have Variable\<int\>& and they seem to work

**Comment by jcotela** [comment]
Ok, I think I figured out the why: the class exposes to python three constructors:
https://github.com/KratosMultiphysics/Kratos/blob/de9420b4f0b391e93cdae22d07f7df438336a9e2/applications/trilinos_application/custom_python/add_trilinos_schemes_to_python.cpp#L202-L209
Note that the first and the third both take four arguments, and only the last one is different: one takes a `Process::Pointer` and the other the `const Variable<int>&`. If I coment out the first constructor, my code example above works, so it looks like python is trying to call the first constructor in that example...

Does anyone see a clean solution for this? (other than changing/reordering the arguments)

**Comment by roigcarlo** [comment]
According to http://pybind11.readthedocs.io/en/stable/advanced/functions.html#overload-resolution-order pybind11 should take care of overloaded functions...
maybe if the one with 3 arguments is before the conflicting ones?

**Comment by jcotela** [comment]
I suspect that the code is actually behaving as explained in the docs:

> What this means in practice is that pybind11 will prefer any overload that does not require conversion of arguments to an overload that does, but otherwise prefers earlier-defined overloads to later-defined ones.

both overloads would require a conversion (from the python-exported Kratos.IntegerVariable type to Process or to const Variable<int>&), so it just takes the first.

**Comment by jcotela** [comment]
It seems to be a limitation in the way pybind works, I'll try to rearrange the constructors for this class to avoid the argument clash.
