### ISSUE TITLE
Adding new Membrane Element

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#201]
@longchentum I saw you added your membrane element in your branch. Very nice. Please use some reasonable name for it like MembraneElementTUM or something like that. MembraneElement1 is misleading. When merging it into the master branch we will anyway have to discuss if we should remove the old membrane element.

**Comment by longchentum** [comment]
Hi @AndreasWinterstein,

thanks for the suggestion.

>>@longchentum I saw you added your membrane element in your branch. Very nice. 
The test cases for analysis and form finding are still to be done.

>>Please use some reasonable name for it like MembraneElementTUM or something like that. 
We used this element name at our Chair, so I just inherited it and use it temporarily in my development branch. I have also discussed with @msandre about the naming issue, as you said, we will figure out a proper name.

>> MembraneElement1 is misleading. 
In my experience, there are lot of established FEM packages use this kind of naming convention for their elements (beam188 in ANSYS) . So, I personally don't think it is misleading.

>>When merging it into the master branch we will anyway have to discuss if we should remove the old membrane element.
We can definitely discuss about it.

Best,
Long

**Comment by msandre** [comment]
There are some hints in the wiki page style guide. I also see in a lot of element names information about the number of nodes, e.g.,  Membrane4NElement would be a 4 node membrane. Does the @KratosMultiphysics/structural-mechanics have a convention for element naming?

**Comment by loumalouomega** [comment]
The convection will be something like MembraneElement3D4N, we are using the convention defined in the SolidMechanicsApplication developed by @josep-m-carbonell, can you please  confirm this?

**Comment by josep-m-carbonell** [comment]
We try to use this convention when the elements are defined and registered to kratos:  
*MembraneElement3D4N,  where you can add some  extra definition instead of *.  If there is two types of membrane elements of 4 nodes one from Felippa and another one from Simo, they can be named as FelippaMembraneElement3D4N and the other one SimoMembraneElement3D4N. Something to distinguish them.

**Comment by loumalouomega** [comment]
@josep-m-carbonell 
Thanks

**Comment by longchentum** [comment]
Thank you all for the comments, I will use the convention defined in SolidMechanicsApplication by @josep-m-carbonell .
