### ISSUE TITLE
[Core][Geometries]PointLocalCoordinates is not a constant method

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2011]
https://github.com/KratosMultiphysics/Kratos/blob/de9420b4f0b391e93cdae22d07f7df438336a9e2/kratos/geometries/geometry.h#L885

Related with #1890

**Comment by pooyan-dadvand** [comment]
I would put also the overrides

**Comment by loumalouomega** [comment]
Do I create a new method with const?

**Comment by pooyan-dadvand** [comment]
De we have any reason to have a non-const version? I would change it to const

**Comment by loumalouomega** [comment]
No to my knowledge

**Comment by RiccardoRossi** [comment]
+1 for making it const (provided that the overrides are in place, but i think so)

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee  agrees

**Comment by loumalouomega** [comment]
Done
