### ISSUE TITLE
Redistance test is failing again...

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#2015]
The `test_redistance` is failing again and its blocking some jobs. 

Since we have already tried to fix this several times my proposal is to make it an expected failure until someone finds the correct solution. Can someone take care of this?

@KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi and @pablobecker have you changed it?

**Comment by RiccardoRossi** [comment]
i pushed another correction. I really hope it is the last one

**Comment by roigcarlo** [comment]
Looks like its passing now. Hope it is solved this time. Closing
