### ISSUE TITLE
About the elements or conditions in ".mdpa" file

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#2024]
I find that there are some special words in the file,"Begin Elements CrBeamElement3D2N","Begin Condition PointLoad Condition3D1N".As for the CrBeamElement3D2N or PointLoadCondition3D1N,are they the especial word in the Kratos?If I want to set a cube element as 3D8N,what should I use to define?Is there a list of elements or conditions name?

**Comment by fengzekang** [comment]
could you give me the answer? @loumalouomega

**Comment by loumalouomega** [comment]
The elements and conditions are registered, that is the name they have:

https://github.com/KratosMultiphysics/Kratos/blob/c957f9f53207e803da722d9f7f3a4501a1c57d30/applications/StructuralMechanicsApplication/structural_mechanics_application.cpp#L326
