### ISSUE TITLE
[Pybind11] Not possible to define a smart pointer variable 

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2033]
If a smart pointer variable is registered in python (for example Node<3>::Pointer), it compiles, but it returns 

    AttributeError: NAME_VARIABLE

Any special modification is needed in order to make it work?

**Comment by philbucher** [comment]
You sure?
[here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/structural_mechanics_application_variables.h#L125) it is working ...

**Comment by loumalouomega** [comment]
I will close this, but on that moment wasn't working at all
