### ISSUE TITLE
List of outdated applications

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#2035]
Dear @KratosMultiphysics/team-maintainers 

Here is the list of applications that still haven't been ported to pybind11/long forgotten apps and its last relevant commit. I ping the last person to touch something in every app, but it may not be the right person to contact with, If its the case just ignore ( or ping the correct one if you know him )

I'd like this to be a first step to make the so long anticipated split between "core" and "labs" application.
The idea would be to inform here which is the status of the app, if it will be moving forward or can be deleted, if it is used by someone with a older version of Kratos etc....

TO BE DELETED
- FDApplication - Jun 20, 2016 - @roigcarlo
- multibody_application - Never? - @pooyan-dadvand, @RiccardoRossi
- PODApplication - ???? - Does not even have a CMakeFiles, @RiccardoRossi
- gpu_solvers_application - Apr 7, 2014 - @RiccardoRossi 

DEVELOPING
- CompressiblePotentialFlowApplication  - Jul 25, 2017 - @inigolcanalejo
- IGAStructuralMechanicsApplication - Apr 11, 2018 - @philbucher 
- TopologyOptimizationApplication - Oct 10, 2017 - @dbaumgaertner
- ULFApplication - Mar 9, 2018 - @elafnm ( I understand this is an ongoing change )
- freezing_soil_application - May 27, 2015 - @hgiang
- mpi_search_application - Dec 18, 2017 - @roigcarlo
- structural_application - Mar 7, 2018 - @vryy
- incompressible_fluid_application - Dec 14, 2017 - @juliobarna
- nurbs_application - Jun 12, 2017 - @FabienPean

UNDER CONSIDERATION
- LagrangianMPMApplication - Oct 26, 2017 - @rubenzorrilla 
- MultiScaleApplication - ???? - @RiccardoRossi, @AndreasWinterstein 
- OpenCLapplication - Nov 19, 2015 - @pablobecker  
- wind_turbine_application - Feb 9, 2017 - @jcotela 

STILL UNKNOWN: 
- constitutive_laws_application - Mar 25, 2014 - @RiccardoRossi 
- meshless_application - Oct 9, 2017 - @pooyan-dadvand, @RiccardoRossi  

I will go ahead with mine:
FDApplication - Can be deleted
mpi_search_application - Needs to be ported (probanly I will move the contents to a future KratosMPI core, still under discussion)

**Comment by loumalouomega** [comment]
structural_application -> @vryy

**Comment by philbucher** [comment]
IGAApplication -> @tteschemacher 
We are developing this app very actively, but it hasn't been pushed to Master in a while bcs many things are still under development
In the local branch everything is ported to pybind already

**Comment by inigolcanalejo** [comment]
CompressiblePotentialFlowApplication will be moving forward. Please, do not delete.

**Comment by vryy** [comment]
@loumalouomega structural_application needs substantial clean up, especially it is hub of many other local applications at RUB.

**Comment by pooyan-dadvand** [comment]
multi_body application can be safely deleted!

**Comment by vryy** [comment]
@loumalouomega freezing_soil_application will be merged to something called soil_mechanics_application, but it will be in the future. Now just need to add some compatible testings.

**Comment by vryy** [comment]
@loumalouomega help needed to include   [isogeometric_application](https://github.com/vryy/isogeometric_application) to the repository. To avoid potential name conflicts with other applications, it can be renamed bezier_based_iga_application

**Comment by dbaumgaertner** [comment]
@roigcarlo please don't delete the TopologyOptimizationApp. Currently, we are indeed not actively developing it but there is the plan to integrate the corresponding method in the overall optimization activities. If this is not going to happen soon, there is still the possibility to delte it in the next cleaning wave.

**Comment by roigcarlo** [comment]
Updated the list with the last comments. 
Just to clarify, I do not intend to delete anything unless you clearly indicate it is possible

**Comment by loumalouomega** [comment]
@vryy I suggest that instead clean up the structural_application to migrate the relevant things to the StructuralMechanicsApplication, this way we can reduce code duplication and simplify maintenance (right now no one in the @KratosMultiphysics/team-maintainers is not working in the structural_application).

Idem for the soil_mechanics_application, maybe is better to discuss with @RiccardoRossi  in a independent conversation

For the migration isogeometric_application the question is the following?, does it work with the current master?, do you want to keep it as an independent repository (and therefore add it as a module to Kratos). Besides, the nomenclature for applications use to be cammelcase, would be problematic to call the application IsogeometricApplication?

Maybe the best option will be to discuss this together with @RiccardoRossi in a private conversation.

**Comment by jcotela** [comment]
@roigcarlo I will take care of the wind turbine application, even if most probably the action taken will just be to delete it...

**Comment by RiccardoRossi** [comment]
TO BE DELETED  WITHOUT THINKING TWICE:
PODApplication - ???? - Does not even have a CMakeFiles, @RiccardoRossi
gpu_solvers_application - Apr 7, 2014 - @RiccardoRossi

NEED TO LOOK INTO:
OpenCLapplication - Nov 19, 2015 - @pablobecker
Multiscale
LagrangianMPM

**Comment by RiccardoRossi** [comment]
@vryy why don't you move to the StructuralMechanicsApplication? This would allow you to get up to speed with the developements of the rest of the group, without having to go through the burden of mantaining an old application which is not kept in sync with the recent advances... 

Is there any feature that is missing from the new application and is there in the structural_mechanics?
If so, please let us know ...

**Comment by FabienPean** [comment]
Hi, for nurbs_application -> I just did some minor cleaning when looking at the Kratos repository a while ago, I do not develop nor maintain it. It seems not updated for a while, see history of the folder.

**Comment by bodhinandach** [comment]
@RiccardoRossi @roigcarlo Please do not delete the LagrangianMPMApplication as it might be useful for me in the future. I will take a look at it, but not anytime soon.

**Comment by roigcarlo** [comment]
I made a final PR to delete a couple more, So far only meshless and the old constitutive_law applications are left alone in the wild, so I will close this as I got an updated status of everything. Thx all!
