### ISSUE TITLE
Segmentation fault when debugging Kratos with VSCode

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#2037]
Dear all,

I noticed, that always, when a Kratos prameter object is created within a given python script, then the python debugging in VSCode (to be more precise, the setting of break points) causes a segmentation fault. Now the weird part is, that this seg-fault does not appear when the same script is started from the terminal. 

More precisely, consider the following minimal example / python script:

```
from KratosMultiphysics import *

print("test")

default_parameters = Parameters("""
{
    "name"    : "some_string",
    "number" : 1
}""")

print("done")
```

Running this in the terminal works fine. Running this script using the debugger in VSCode (hitting the F5 button) yields a segfault. In fact, this happens always when the debugger breakes within a function that contains a Kratos parameter object. The version of VSCode I am using is 1.23 and the launch setting is the following: 

```        {
            "name": "Python3",
            "type": "python",
            "request": "launch",
            "stopOnEntry": false,
            "pythonPath": "/usr/bin/python3",
            "program": "${file}",
            "cwd": "",
            "env": {}
        }
```
Since I heard this already a few times, I am not sure if this is a matter of the settings of VSCode or something related to the construction of the parameter json object. In any case it's a pity to be not able to use the Debugger, which usually works great with Kratos.  I am posting this, since quite some people are using VSCode with Kratos and might experience the same sooner or later.

So, can anybody who uses VSCode maybe confirm this behavior or even suggest a solution? Any hint is appreciated.

Cheers

**Comment by ipouplana** [comment]
Hi @dbaumgaertner , 

I experienced the same problem some days ago when debugging in python with VSCode. However, I did not investigate enough to find a solution for debugging in Python...

Maybe this is a problem of the latest versions of VSCode, because I remember that I had previously debugged in python and C++ without problems...

**Comment by msandre** [comment]
Can you print a backtrace of the function calls from the point where it crashes?

**Comment by dbaumgaertner** [comment]
How can I do this, since I cannot step into the constructor of the Parameter object where it fails?

**Comment by msandre** [comment]
Then I'm not sure, it seems strange if you cannot step into the constructor. If you have it open sometime I would be interested to see the problem, although I don't know much about using VSCode to debug.

**Comment by maceligueta** [comment]
I managed to run a hybrid debug of the minimal example and the first lines of the call stack are the following:

```
rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::MemberEnd(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > * const this) (/home/maceli/kratos/external_libraries/rapidjson/document.h:891)
Kratos::Parameters::end(Kratos::Parameters * const this) (/home/maceli/kratos/kratos/includes/kratos_parameters.h:434)
Kratos::Python::<lambda(Kratos::Parameters&)>::operator()(Kratos::Parameters &) const(const Kratos::Python::<lambda(Kratos::Parameters&)> * const __closure, Kratos::Parameters & self) (/home/maceli/kratos/kratos/python/add_kratos_parameters_to_python.cpp:129)
pybind11::detail::argument_loader<Kratos::Parameters&>::call_impl<pybind11::iterator, Kratos::Python::AddKratosParametersToPython(pybind11::module&)::<lambda(Kratos::Parameters&)>&, 0ul, pybind11::detail::void_type>(Kratos::Python::<lambda(Kratos::Parameters&)> &, std::index_sequence, pybind11::detail::void_type &&)(pybind11::detail::argument_loader<Kratos::Parameters&> * const this, Kratos::Python::<lambda(Kratos::Parameters&)> & f) (/home/maceli/kratos/external_libraries/pybind11/cast.h:1869)
pybind11::detail::argument_loader<Kratos::Parameters&>::call<pybind11::iterator, pybind11::detail::void_type, Kratos::Python::AddKratosParametersToPython(pybind11::module&)::<lambda(Kratos::Parameters&)>&>(Kratos::Python::<lambda(Kratos::Parameters&)> &)(pybind11::detail::argument_loader<Kratos::Parameters&> * const this, Kratos::Python::<lambda(Kratos::Parameters&)> & f) (/home/maceli/kratos/external_libraries/pybind11/cast.h:1846)
pybind11::cpp_function::<lambda(pybind11::detail::function_call&)>::operator()(pybind11::detail::function_call &) const(const pybind11::cpp_function::<lambda(pybind11::detail::function_call&)> * const __closure, pybind11::detail::function_call & call) (/home/maceli/kratos/external_libraries/pybind11/pybind11.h:154)
pybind11::cpp_function::<lambda(pybind11::detail::function_call&)>::_FUN(pybind11::detail::function_call &)() (/home/maceli/kratos/external_libraries/pybind11/pybind11.h:132)
pybind11::cpp_function::dispatcher(PyObject * self, PyObject * args_in, PyObject * kwargs_in) (/home/maceli/kratos/external_libraries/pybind11/pybind11.h:619)
PyObject_Call(PyObject * func, PyObject * arg, PyObject * kw) (/usr/src/debug/Python-2.7.13/Objects/abstract.c:2547)
```

**Comment by msandre** [comment]
@armingeiser I think you managed to solve this right?

**Comment by armingeiser** [comment]
@msandre I just tried it with the minimal example above and i got the same segfault. However i can debug into the constructor of the parameters object when i attach the gdb debugger to the kratos process.

I get the same stack as @maceligueta

If the parameters object is created from a file, it seems to work. This was also the case for the script that i debugged today.

```python
from KratosMultiphysics import *

print("test")

file_name = "some_file.json"

with open(file_name,"r") as file:
    default_parameters = Parameters(file.read())

print("done")
```

**Comment by dbaumgaertner** [comment]
Strange enough, it also works if the Parameter object only contains one dictionary entry on the first level. Meaning, the minimal example above gives the seg-fault since it has to string entries on the top level. Changing the example to the following works again:

```
from KratosMultiphysics import *

print("test")

default_parameters = Parameters(""" {
    "entry"  : { "number" : 1, "name":  "string"}
}""")

print("done")
```
