### ISSUE TITLE
Splitting of external and internal contributions to RHS

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#2038]
I started to implement the Generalized-alpha scheme in the branch feature/Add_generalized_alpha_method this week. The basic functionalities are there, but it still has a small bug I have to find.
In any case, there is the necessity to split the external and internal contributions to the RHS vector in oder to be able to use the scheme for other types of loads than constant ones. In the discussion with @loumalouomega today he told me that there are some plans/ideas how to do make this split. 

I would like to start a discussion here.....

**Comment by loumalouomega** [comment]
What I spoke with @RiccardoRossi was to use submodelparts in order to differentiate the external/internal contribution. But this doesn't work, at least it didn't work for the arc length. The alternative, quite painful because require to modify the current implementation of the elements/conditions, is to implement the ComputeRHS/LHS by components

**Comment by KlausBSautter** [comment]
Can't you use 
`sheme->Condition_Calculate_RHS_Contribution(
        Condition::Pointer pCondition,
        LocalSystemVectorType& RHS_Contribution,
        Element::EquationIdVectorType& EquationId,
        ProcessInfo& rCurrentProcessInfo)`

to get the external forces and

`scheme->Calculate_RHS_Contribution(
        Element::Pointer pElement,
        LocalSystemVectorType& RHS_Contribution,
        Element::EquationIdVectorType& EquationId,
        ProcessInfo& rCurrentProcessInfo
        )`

for the internal forces?

**Comment by KlausBSautter** [comment]
as we just discussed the element RHS will include selfweight but as it independent on the time it should do the job for you.... pls correct me if Im wrong

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/c957f9f53207e803da722d9f7f3a4501a1c57d30/kratos/includes/element.h#L430 This is the currently implemented

https://github.com/KratosMultiphysics/Kratos/blob/c957f9f53207e803da722d9f7f3a4501a1c57d30/kratos/includes/element.h#L449 This is the one to implement

**Comment by josep-m-carbonell** [comment]
Just to let you know that the calculation by components was dismissed in the SolidApp because it is very time consuming.

**Comment by loumalouomega** [comment]
Really @josep-m-carbonell, it is because of the STL containers (std::vector)?, because the implementation is quite similar

**Comment by RiccardoRossi** [comment]
guys, i would really use the proposal by @KlausBSautter ...

**Comment by loumalouomega** [comment]
There are elements that have internal/external forces. For example the self-weight, we can separate the self-weight in a different condition. Otherwise a simple oscillation under selfweight  with the generalized alpha will return a wrong solution

**Comment by loumalouomega** [comment]
For example the selfweight, we can separate the selfweight in a different condition

**Comment by KlausBSautter** [comment]
true but I think in case of @AndreasWinterstein 's case he only needs the transient external forces separately which would exclude self weight

**Comment by AndreasWinterstein** [comment]
I will try to do it like @KlausBSautter suggested ...

**Comment by philbucher** [comment]
I believe this can be closed, please reopen if necessary
