### ISSUE TITLE
Are colors a descriptive name?

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#2039]
After PR #2009 I wrote some documentation lines, and I found some things to improve.
When I moved the colors utility to the core I renamed it as `sub_model_parts_list_utility`. But *list* is not a good word, should be a *map*... And the name *colors* is already in some implementations.

Is a good idea turning back to `colors_utility`, or should we look for a more descriptive name?

The second thing can be discussed in another issue: should 'the utility' work with a *Model* instead of a *ModelPart*? I don't like the way we are accessing the sub sub model parts

**Comment by roigcarlo** [comment]
Maybe not the best person to answer but I would vote to change i to `sub_model_parts_coloring_utility` or something like that. This sort of algorithms are historically named as coloring problems, so it would totally make sense to change its name.

@RiccardoRossi what do you think?

**Comment by pooyan-dadvand** [comment]
I put this in the todo list to think about the name

**Comment by pooyan-dadvand** [comment]
`AssignUniqueModelPartCollectionTag` has been decided @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
So, it will be AssignUniqueModelPartCollectionTagUtility?

**Comment by loumalouomega** [comment]
Can we close this?

**Comment by roigcarlo** [comment]
Nope, it is still with the old name.

**Comment by miguelmaso** [comment]
I would wait to use Model and do all the changes

**Comment by roigcarlo** [comment]
We finally merged the model so we can go ahead with this :tada:

**Comment by loumalouomega** [comment]
I don't remember what we planned

**Comment by roigcarlo** [comment]
@loumalouomega some comments above:
> AssignUniqueModelPartCollectionTag has been decided @KratosMultiphysics/technical-committee

**Comment by miguelmaso** [comment]
I can do it this afternoon
