### ISSUE TITLE
Release 6.0.0

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#2047]
Dear developers, it is time to start with the release 6 preparation to have the branch next Friday, May 18th. I would encourage all @KratosMultiphysics/team-maintainers to update the applications to add their corresponding issues to the release 6. milestone so we can track the progress and steps toward release. I would like to suggest that all error and bug issues to go in this milestone and have the most priority.  Also it is very important to have the all the tests working for the release.

**Comment by roigcarlo** [comment]
Friendly reminder that I will lock the branch today. Let me know if there is any urgent PR that needs to be merged and it is not included in the 6.0.0 project so nobody ends up with the code outside!

**Comment by roigcarlo** [comment]
Dear @KratosMultiphysics/team-maintainers during this week I will start to make initial compilations of the release branch for you to test it. 

I've taken the list of applications from 5.3.0 to begin with. 
You can found the list here: https://github.com/KratosMultiphysics/Kratos/projects/5

Please take moment to check that list and feel free to add/remove applications if there is something that needs to be changed. If you touch something please leave a message here so I am aware of the changes.

**Comment by RiccardoRossi** [comment]
@antonialarese should the freesurface application (not sure of its name) be merged in?

what about the MPM?

**Comment by roigcarlo** [comment]
I've just published the first betas for win. Linux is on his way.
https://github.com/KratosMultiphysics/Kratos/releases/tag/v6.0-Beta1

Since its the first version using pybind, expect failures and things that should not be there / are missing, so please test it!

**Comment by roigcarlo** [comment]
@pooyan-dadvand I have not detected any problem with the keys in 32 bits, but there is no harm if someone else runs the rests

**Comment by pooyan-dadvand** [comment]
@josep-m-carbonell would you please check the win32 version with your course problems?

**Comment by ipouplana** [comment]
Hi @roigcarlo, I just tried the Beta1 on Windows and I found a little error in one python file of the Poromechanics and Dam Applications. Can I open a branch from the Release branch and open a PR to fix it?

**Comment by josep-m-carbonell** [comment]
#2151 needs to be fixed

**Comment by roigcarlo** [comment]
@ipouplana Sure
@josep-m-carbonell Thx, I am still working on that one

**Comment by roigcarlo** [comment]
Dear all, I just published the new release so you can test it during the week.
You can found it here: https://github.com/KratosMultiphysics/Kratos/releases/tag/v6.0-Beta2

**Comment by josep-m-carbonell** [comment]
@pooyan-dadvand @roigcarlo  I attach the compilation errors that I got in windows. 

For win 32:
[compilation_errors_win32_R6.0.txt](https://github.com/KratosMultiphysics/Kratos/files/2049357/compilation_errors_win32_R6.0.txt)

and similar errors 

For win 64:
[compilation_errors_win64_R6.0.txt](https://github.com/KratosMultiphysics/Kratos/files/2049731/compilation_errors_win64_R6.0.txt)

**Comment by roigcarlo** [comment]
I've just published the RC:
https://github.com/KratosMultiphysics/Kratos/releases/tag/v6.0-Rc

Please if you find any problem tellme ASAP br.

**Comment by roigcarlo** [comment]
All feedback was positive so I have promoted RC to final. Happy release.
https://github.com/KratosMultiphysics/Kratos/releases/tag/v6.0

**Comment by loumalouomega** [comment]
Should we close this?
