### ISSUE TITLE
Windows compilation for Release version fails (error 1083: not enough space)

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#2048]
Apparently, it's a common problem. @roigcarlo confirmed this. I was first informed by @f-zarate .
Debug Version compiles fine.
I think it is important to solve this issue before Release 6.0.

**Comment by roigcarlo** [comment]
Yes, this is a confirmed problem see #1929 as well.
Recently we have found that the camke module for pybind may be adding some possible problematic flags ( namely, /GL), but still investigating

**Comment by RiccardoRossi** [comment]
this is solved.  closing
