### ISSUE TITLE
FluidDynamicsApplication tests

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#2057]
Dear Kratos members,

I need to run a simple example of a flow in rectangular channel using a VMS2D element.
The problem is that generating the example with a new "professional problemtype" is very inconvenient for doing trials (everything is hidden) and I am not even sure it uses VMS element.

On the other hand, the test_examples of FluidDynamicsApplication (for example, cylinder example) dont seem to work when one sets the solver to vms_monolithic_solver.

Is there any old problemtype that can be used to create and run such example using vms_monolithic_solver?

Thanks!

Pavel

**Comment by RiccardoRossi** [comment]
@playpaolo as you say everything is hidden in the solver. what you can do pretty easily is to derive your own solver and to make the changes you like within the Solve function. That should allow you the same freedom as you had in the main

**Comment by playpaolo** [comment]
Thank you @RiccardoRossi! What do you mean aexactly by derviding my own solver? You mean copying the python solver code, giving it a different name and changing one of the functions? Or is there a way of doing it in a cleaner way?

**Comment by loumalouomega** [comment]
Indeed, you can derive one solver from other solver. As well as in C++, in python you can derive on class from a different one. Take a look at the solvers in the StructuralMechanicsApplication:

The base solver: 
https://github.com/KratosMultiphysics/Kratos/blob/e7189a59245ba62f7e36c7d99e0011c1e8edb04b/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L1

The derived one for static analysis:
https://github.com/KratosMultiphysics/Kratos/blob/e7189a59245ba62f7e36c7d99e0011c1e8edb04b/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_static_solver.py#L1

**Comment by playpaolo** [comment]
Thank you @loumalouomega !

**Comment by jcotela** [comment]
I think the question was answered, so I'll close. @playpaolo feel free to reopen if you have more questions.

**Comment by playpaolo** [comment]
will I still be able to view this issue after it is closed?
 

    On Wednesday, May 23, 2018 12:47 PM, jcotela <notifications@github.com> wrote:
 

 I think the question was answered, so I'll close. @playpaolo feel free to reopen if you have more questions.—

**Comment by jcotela** [comment]
Yes, but you'll need to look for it among the closed issues (or use the link in the email you are quoting).
