### ISSUE TITLE
After pull the master and compile an execution error appeared in Ubuntu

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#2058]
The master not contains any change to the solidmechanics app, but generates this conflict. 

|  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-c740868-FullDebug
Importing    KratosExternalSolversApplication 
Initializing KratosExternalSolversApplication... 
Traceback (most recent call last):
  File "MainKratos.py", line 3, in <module>
    import KratosMultiphysics.SolidMechanicsApplication
  File "/home/cpuigbo/Kratos/KratosMultiphysics/SolidMechanicsApplication.py", line 2, in <module>
    from KratosSolidMechanicsApplication import *
ImportError: /home/cpuigbo/Kratos/libs/KratosSolidMechanicsApplication.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN5boost12hash_combineImEEvRmRKT_

**Comment by loumalouomega** [comment]
Do you have any unordered_map?

**Comment by loumalouomega** [comment]
Solved in physical world
