### ISSUE TITLE
[Duplication] line_2d.h duplicates line_2d_2.h

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2070]
The class line of two nodes in 2d is duplicated in line_2d.h  and line_2d_2.h @KratosMultiphysics/team-maintainers 

The following files are using the line2d.h

![imagen](https://user-images.githubusercontent.com/19991680/40011652-b7b3ac08-57a8-11e8-90c0-c71a1e7ee00e.png)

**Comment by jcotela** [comment]
And which one should we use? (conversely, why are there two classes for 2D lines with two nodes?)

**Comment by loumalouomega** [comment]
Almost everyone, except the screenshoot, uses line2d_2.h. Sincerely I will add a deprecated function on the line2d.h And inform to the people responsible, I recognize @miguelmaso and @josep-m-carbonell

**Comment by roigcarlo** [comment]
Closing this since already merged

**Comment by loumalouomega** [comment]
Ok
