### ISSUE TITLE
result_file_configuration -- Stress - Strain -- ShellThin - Membrane - Truss - Beam

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#2075]
I would like to save data -- Stress and Strain computed with these elements -- 2D and 1D -- into Gid or json file.
The I can see the displacement and the VMS with Gid but not the stress tensor.
What I have to do?

**Comment by philbucher** [comment]
I think outputting these quantities is not implemented for the mentioned elements

You can try adding them to the output configuration in prjectparameters, if the calculation is implemented then they will be written

**Comment by PhilippeBussetta** [comment]
@philbucher Thanks.
In which function I have to implement it?

**Comment by philbucher** [comment]
In the `CalculateOnIntegrationPoints` Method afaik
right @loumalouomega ?
see an example [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_elements/cr_beam_element_3D2N.cpp#L1182)

**Comment by loumalouomega** [comment]
Indeed @philbucher

**Comment by PhilippeBussetta** [comment]
To have the outputting of these quantities one have tu use the specific Flags -- e.g. `"SHELL_STRAIN","SHELL_STRAIN_GLOBAL","SHELL_STRESS_MIDDLE_SURFACE","SHELL_STRESS_MIDDLE_SURFACE_GLOBAL"`
It is possible to have these quantities into the element axis?
The `_GLOBAL` quantities feel equal to the others.

It is possible to have information about the quality of the mesh (e.g. the value of the element angles)?

**Comment by philbucher** [comment]
Regarding those quantities be warned, they are still not fully validated

Regarding the mesh quality I think you can see in somewhere in GiD (don't remember where)
