### ISSUE TITLE
[StructuralMechanicsApplication] Shell element Section when properties are empty

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#2077]
I encountered a problem with the shell element sections.

They seem to initialize everything to zero id properties are empty.
I think this should raise an error.

**Comment by armingeiser** [comment]
It happened when the property was not initialized.

**Comment by philbucher** [comment]
@armingeiser could you please remind me abt this tmr and explain what exactly is happening such that we can fix it?

**Comment by armingeiser** [comment]
It seems that the check() function has not been called.
