### ISSUE TITLE
Processes are exported to Python as Pointers (not as references)

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#2102]
A reference works as a unique pointer, so the process can only be owned by one object.
This change was requested by several users and approved at the @KratosMultiphysics/technical-committee .

**Comment by loumalouomega** [comment]
I think this is the general way pybind works. And in case of change it we will need to accommodate many constructors of many classes that use the process in the constructor

**Comment by maceligueta** [comment]
Addressed in PR #2120.

**Comment by roigcarlo** [comment]
Fixed, closing this.
