### ISSUE TITLE
[Core] Discussion  about SVDSolver class

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2111]
I would like to start a discussion for creating a new base class to define in the future SVD solvers. Right now we have a very basic implementation of the Jacobi method  in the svd_utils.h, but for example Eigen has it own SVD solvers.

I assume that the class will derive from the linear_solver.h, so it will inherit all the methods from this, but we will need to add a new solver taking into account that there will be a matrix input and three output matrixes.

**Comment by RiccardoRossi** [comment]
I am favorable about defining a base class for SVDsolver, however i do not think it should be derived from linear solver since it is not the same interface ... i mean it should give back two matrices and a vector

**Comment by loumalouomega** [comment]
There is a solve for eigenvalues, the concept is the same:

https://github.com/KratosMultiphysics/Kratos/blob/5a0e882b0f06fd01694b4d43ea8d143a3a2bf0d5/kratos/linear_solvers/linear_solver.h#L217

**Comment by rubenzorrilla** [comment]
Well, I think it can be used to solve a problem. Therefore it must have a Solve() method. However, it might be used to several alternative purposes. Having this in mind, I agree @RiccardoRossi in the fact that it will have a different interface to the linear solvers one. According to my understanding, the interface and implementation should be somehow similar to the QR one (of course that we can offer the option of using Eigen's SVD as @loumalouomega is pointing.

**Comment by armingeiser** [comment]
Just as a sidenote: @longchentum is using Eigen's SVD as a utility (because of the lacking base solver) in the EigenSolversApplication in one of his branches.

**Comment by loumalouomega** [comment]
Don't worry, we will not broke the interface, there will be a migration
period.

**Comment by armingeiser** [comment]
I am not worried =), Just saying that if there will be such a base solver or whatever decision is made here, we can migrate that existing EigenSolversApplication utility to the new interface.

**Comment by philbucher** [comment]
is this still active?

**Comment by loumalouomega** [comment]
Yep, don't close please

**Comment by rubenzorrilla** [comment]
Pointing to  #8546 and #9823 and `LinearSolversApplication` in case someone ends up here.
