### ISSUE TITLE
[Release] Installation Guides should be added

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2115]
I think it would make sense if the Installation guides are added to the release branches

Otherwise it will be difficult if someone wants to compile an older release in the future

@KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
Good Idea. One of the things we can do is reference the specific hash of the wiki that was relevant during a given release. I will take a look on how to do this.

**Comment by loumalouomega** [comment]
Did we finish this?

**Comment by philbucher** [comment]
not yet, will do it soon, sorry for the delay

**Comment by philbucher** [comment]
solved with the new installation procedure
