### ISSUE TITLE
Many Stale Branches

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2132]
There are many stale branches floating around the repo, I am pinging the ppl who commited last to those to see whether they can be deleted

feature-UP-formulation: @iiaconeta 
feature-templated-spheric-particle: @GuillermoCasas 
feature_error_distance_function: @juliobarna 
feature-edge-swapping @pooyan-dadvand 
sensitivities_potential_flow: @inigolcanalejo 
feature_distance_function @juliobarna 
feature-dem-eroding-river-bed @pablobecker 
feature-DEM-PFEM-coupled @AFranci 
removing_tetgen @RiccardoRossi 
feature_unit_test_sensitivities @inigolcanalejo 
DEM-debug-search-radius-issue @GuillermoCasas 
feature-cps-add-compute-lift @inigolcanalejo 
feature-pfem-NonNewtonian @AFranci 
feature-pfem-NonNewt_new @AFranci 
feature_pfem_NonNewt_old @AFranci 
feature-FSI-bingham-examples @AFranci 
Branch_generalized_influence_function @longchentum 
feature-pfem-dem @AFranci 
fsi-mass-matrix @rubenzorrilla 
feature-eigen-value-solver @rubenzorrilla 
test-distance-correction @pooyan-dadvand 
fix-constitutive-laws-application @miguelmaso 
feature-fldyn-Ausas-embedded-extra-tests @rubenzorrilla 
debug-updating_to_new_DEM_interface @GuillermoCasas 
feature-sw-taylor-hood @miguelmaso 
feature-fluid-RVE-especial-BC @playpaolo 
ulf/glass-blow @playpaolo 
feature-sw-remeshing @miguelmaso

**Comment by RiccardoRossi** [comment]
please do not take out this one:

feature-approximate-nodal-contact @RiccardoRossi

**Comment by KlausBSautter** [comment]
I want to keep StructMech/feature-1d-plasticity

**Comment by juliobarna** [comment]
Please dont erase feature_pfem2_moving_mesh

**Comment by philbucher** [comment]
I will not erase anything (except my own stale stuff :D ), just wanted to ask

**Comment by loumalouomega** [comment]
I will erase feature-superconvergent-patch-remeshing after merge #2063

**Comment by jcotela** [comment]
`rename-element-integration-point-access-methods` is still relevant (it is related to one of the open issues). I'll try to finish it once the release is done.

**Comment by roigcarlo** [comment]
Need those:
feature-correct-kratos-components-clang-warning
fix-variables_list_data_value_container-serialization-error

This one can be deleted (already did it)
appveyor/skip-merge-to-branches

**Comment by qaumann** [comment]
I would also like to keep my `test-projection-methods`

**Comment by lluis-mv** [comment]
Hi, I am responsible of most of the gpfem/* branches. 
In the following weeks I will create a pull request and erase them.
In the meantime I would prefer to keep them.

**Comment by adityaghantasala** [comment]
I will delete the periodic boundary conditions branch.

**Comment by playpaolo** [comment]
Please dont delete it!
--------------------------------------------
On Tue, 5/22/18, Aditya Ghantasala <notifications@github.com> wrote:

 Subject: Re: [KratosMultiphysics/Kratos] Many Stale Branches (#2132)
 To: "KratosMultiphysics/Kratos" <Kratos@noreply.github.com>
 Cc: "Pavel Ryzhakov" <ryzhakov@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Tuesday, May 22, 2018, 6:01 PM
 
 I will delete the
 periodic boundary conditions branch.
 
 —
 You are
 receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.

**Comment by adityaghantasala** [comment]
@playpaolo  are you using this branch and the boundary condition ?

**Comment by playpaolo** [comment]
Yes, I am and its very important for our current project on turbulence modeling.
 

    On Tuesday, May 22, 2018 7:20 PM, Aditya Ghantasala <notifications@github.com> wrote:
 

 @playpaolo are you using this branch and the boundary condition ?—

**Comment by adityaghantasala** [comment]
@playpaolo I see there are two periodic condition branches
May I ask which one are you using ? 

feature-periodic-condition-by-components
or 
feature-periodic-boundary-conditions

**Comment by playpaolo** [comment]
the one i need is the feature-periodic-condition-by-components. thank you! 

    On Wednesday, May 23, 2018 3:14 PM, Aditya Ghantasala <notifications@github.com> wrote:
 

 @playpaolo I see there are two periodic condition branches
Which one are you using ?feature-periodic-condition-by-components
or
feature-periodic-boundary-conditions—

**Comment by armingeiser** [comment]
i removed all my old branches that i don`t need anymore. Thanks for reminding.

**Comment by philbucher** [comment]
@adityaghantasala I think what @playpaolo uses has nothing to do with your branch

**Comment by philbucher** [comment]
ping once more to the developers in the list, there are still many stale branches
