### ISSUE TITLE
Condition checks DomainSize, but it is not implemented correctly in all existing geometries

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#2151]
Some time ago, the condition.h was checking the Area of the geometry. Now it is checking the DomainSize of the geometry, but the DomainSize is not implemented like the Area in some geometries, so now, suddenly, the check fails, is an example the Quadrilateral3D8.

**Comment by maceligueta** [comment]
If we did not realize, it must be because those checks are not called in the tests for all geometries. My recommendation is to add more tests calling that check.

**Comment by roigcarlo** [comment]
I was fixing this but DomainSize seems to be already implemented in Quadrilateral3D8:

```C++
double DomainSize() const override
{
        return fabs( DeterminantOfJacobian( PointType() ) ) * 0.5;
}
```

Not sure if this is correct or not...

**Comment by josep-m-carbonell** [comment]
DeterminantOfJacobian in this geometry raises an error, so it is a trap.

**Comment by loumalouomega** [comment]
lets see

**Comment by loumalouomega** [comment]
I would remove the override of the Determinant of the Jacobian, I implemented in the base geometry the generalized determinant, so, it should work

**Comment by loumalouomega** [comment]
@josep-m-carbonell can you check if #2190 solves your problem?

**Comment by roigcarlo** [comment]
I've changed the implementation of most geometries so they are based on the class definition of "Length, Area and Volume". Is such functions are not correctly defined, this is beyond what I can hotfix for the release. I've also added tests to check that in the case of the `Quadrilateral3D8`.

As soon as I check this is correct I'll make a PR. I can add more tests in the release if you tell me which geometries were failing. Others will have to come after the release as I don't have time to implement everything before the workshop.

Just read @loumalouomega comments right now. If someone else is fixing this pls tell me so  I don't duplicate code...

**Comment by loumalouomega** [comment]
Too late

**Comment by roigcarlo** [comment]
I trust more in your fix. I don't even understand how the `Quadrilateral3D8` works so if it fixes the problem go ahead with it

**Comment by roigcarlo** [comment]
Gonna close this since has been already Merged to both master and release. For the problems of the methodology I would open a different issue.
