### ISSUE TITLE
Policy on using numpy, h5py and other useful Python modules

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#2165]
I am opening this issue to discuss about the possibility of adding full support to the most common scientific Python modules. 
The advantages are quite clear to those who use them. But what about the inconvenients, can they fit in a next Release? Can they be added to Travis?

**Comment by maceligueta** [comment]
Just referencing @KratosMultiphysics/team-maintainers .

**Comment by pooyan-dadvand** [comment]
Do you mean keeping compatibility with them or also let dependency to them?

**Comment by maceligueta** [comment]
I was just thinking of packing those modules with the Releases. Also adding them to the tests of some applications.

**Comment by RiccardoRossi** [comment]
from my point of view this would be nice, however packing those is very difficult if we want to distribute our own python. For example numpy depends on blas and lapack and may not be easy to pack.

in my opinion one possible way forward would be to distribute docker-type packages, which contain "native" python as well as the packages it needs. that could include the gid in the docker package...

**Comment by roigcarlo** [comment]
For the releases I would be very careful on adding things like numpy, as it require additional shared libs that are often compiled by pip.

But its also true that, for pure python modules, using pybind11 has made the things easier so maybe we can consider this. 

We should add this to the project and discuss it next week

**Comment by pooyan-dadvand** [comment]
In @KratosMultiphysics/technical-committee we have not seen how we can get the numpy especially in windows. Another complexity is the GiD retrieve mechanism.

Compiling it with `run_kratos.exe` considered to be impossible to maintain.

**Comment by maceligueta** [comment]
I just talked to @roigcarlo  about this and we realized that _nuitka_ or _cx_freeze_ could help. Both the Linux and the Windows release could be packed with these utilities, just like it is being done with SpreadDEM or Click2Cast... Actually, both have options for embedding all the necessary modules and libraries to make them standalone.

**Comment by loumalouomega** [comment]
Did we solve this issue?

**Comment by RiccardoRossi** [comment]
Nope,this is open I think

**Comment by pooyan-dadvand** [comment]
In committee a the idea of having a freezed python version of "run_kratos" packed with numpy and hdf5 is proposed and seems to be viable. 

To be experimented by @roigcarlo and @maceligueta

**Comment by loumalouomega** [comment]
FYI I found this:

https://github.com/lava/matplotlib-cpp

**Comment by philbucher** [comment]
are there any advances here?
I would also be interested :)

**Comment by roigcarlo** [comment]
Nothing new from my side. Didn't really have time to test this to be honest, I will try to take a look next week

**Comment by maceligueta** [comment]
This issue is commented during each meeting of the Committee, but there was no time to do the corresponding checks for the moment.

**Comment by philbucher** [comment]
for the record, these modules can now be used in the nightly build, so for making tests they are available (not through `runkratos` though)

**Comment by jcotela** [comment]
Just for the record, please be careful with h5py. The hdf5 library has to be compiled differently depending on whether MPI support is needed, and MPI-enabled kratos will not compile against the serial hdf5 library.

**Comment by roigcarlo** [comment]
Dear @KratosMultiphysics/team-maintainers We are making significant progress in adding custom modules to the compiled version of Kratos (runkratos).

In order to continue with this I would like to know which modules would be interesting to add. The current implementation supports:
- numpy
- h5py (@jcotela I take your comment on this)

Currently requested:
- Matplotlib
- Sympy
- Scipy

If you have interest in a particular module please post it here so I can check if the integration is possible.

**Comment by philbucher** [comment]
If this is the time for adding things to the wishlist :D, then I think also sympy and scipy would be useful

Having support for numpy and h5py is already great! Is this available for the upcoming release?

**Comment by roigcarlo** [comment]
@philbucher No problems with sympy, but I have to take a closer look at scipy, as its a bundle of libs itself ( for example it containts sympy) and I am not sure everything can be packed.

**Comment by dbaumgaertner** [comment]
Just to say that this is a great effort. My wishlist would contain numpy, scipy, and matplotlib as already listed above.

**Comment by RiccardoRossi** [comment]
+1 for scipy! (which includes sympy and matplotlib) :-)

**Comment by jrubiogonzalez** [comment]
Please pat attention to the license. For scipy I think it is fine

**Comment by loumalouomega** [comment]
SciPy is BSD. https://en.wikipedia.org/wiki/SciPy

Matplotlib too https://matplotlib.org/users/license.html https://en.wikipedia.org/wiki/Matplotlib

As well as SymPy https://en.wikipedia.org/wiki/SymPy

**Comment by pooyan-dadvand** [comment]
Scipy is a very large package involving many others. I would go first for small ones and then with more experience we may target the Scipy

**Comment by roigcarlo** [comment]
Wating for installation as module. After that we will start with numpy and go one by one adding new modules

**Comment by maceligueta** [comment]
Any news on this idea of including useful Python modules? Maybe the latest changes allow this better than before...

**Comment by loumalouomega** [comment]
We still have the problem of the runkratos, which does not include the dependencies

**Comment by maceligueta** [comment]
We can replace the old runkratos.exe by a new runkratos.bat with this aspect inside:
```
set PYTHONPATH=%PYTHONPATH%;C:\Kratos\bin\Release;C:\Kratos\bin\Release\libs
set LD_LIBRARY_PATH=%LD_LIBRARY_PATH%;C:\Kratos\bin\Release;C:\Kratos\bin\Release\libs
C:\Python37\python.exe %1
```
If it sounds good,  we could automatically generate `runkratos_Release.bat`, or `runkratos_FullDebug.bat`, etc... and it would be subject to Python restrictions, no extra limitations.

We tested it with @AlejandroCornejo  and it worked. It also allows to run the Release and Debug versions simultaneously if both were compiled beforehand.

**Comment by RiccardoRossi** [comment]
this requires you to have preinstalled python ... the think is how to package the python itself (which might be accomplished by nuitka)

**Comment by maceligueta** [comment]
Ok, thanks @RiccardoRossi Do the latest advances ease the process to pack with nuitka?

**Comment by RiccardoRossi** [comment]
as far as i understand, it should be now automatic to package with nuitka.

the point is that we would need to have a run_kratos.py which does something like

~~~py
from numpy import *
from scipy import *
exec(argv[0])
~~~

and hope that the files contained in the argv are also packaged correctly...  something that will need some playing around...

**Comment by loumalouomega** [comment]
Remember that nuitka is only compatible until python 3.7 (not 3.8, which is the last stable version):

https://github.com/Nuitka/Nuitka

**Comment by maceligueta** [comment]
The last news I had about this subject were that we succeded at packing Kratos with PyInstaller. See #6236 . @jginternational @RiccardoRossi 
Can we move forward?
Talking with @RiccardoRossi , it seems we could substitute `runkratos `by a single file and a folder (all packed with PyInstaller) and we would be good to go...
After checking the previous messages, these are the modules that have been appearing:
- scipy (includes matplotlib and sympy)
- numpy
- h5py
@KratosMultiphysics/technical-committee  what do you think of this?

**Comment by loumalouomega** [comment]
For the people using statistics maybe pandas could be useful (just saying)

**Comment by RiccardoRossi** [comment]
just to say that h5py is a little dangerous as MPI and non-MPI versions of HDF5 may go in conflict

**Comment by maceligueta** [comment]
Is the conflict at installation time or at runtime? @RiccardoRossi 
If it is at runtime, we can make separate launchers, as it was in the past.

**Comment by roigcarlo** [comment]
@maceligueta It is at install time. You cannot have both versions at once.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee approves the use of py_install (or any alternative) to create the executable and at this moment the libraries to be included are:
1. numpy
2. matplotlib

The discussion inclusion of scipy is postponed to the future when we have more experience with included one and the impact in maintenance of having scipy inside.

**Comment by roigcarlo** [comment]
From 9.0 onward all python packages can be supported so long as they are installed in your system.

I have open a follow up issue to discuss which packages should be required to run Kratos. Thx all!
