### ISSUE TITLE
Must a distributed load consider large deformations?

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#217]
There is the non-linearity of the change of the surface orientation (changes in the surface normal in pressure loads or changes in local axes in locally applied loads).

However there is also the non-linearity corresponding to the enlargement or decrease of the surface where a distributed load is applied. 

We can consider the total load as a constant value (to avoid the non-linearity) or consider the distributed value as a constant value ( that means the total load will change with the deformation of the surface ) (non-linear case).
 
Which cases must be implemented?
How can be selected from a GUI ?

@KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
In theory the proper thing is to consider the load energy conservative (look at this from the course of Felippa http://www.colorado.edu/engineering/cas/courses.d/NFEM.d/NFEM.Ch06.d/NFEM.Ch06.pdf)

Besides, technically if we consider that a load is a condition, which means that is formulated in terms of residual, to be really non linear and improve the convergence of the problem the RHS should be derived to compute the respective LHS.

**Comment by pooyan-dadvand** [comment]
I'm not an expert on this but for me the load is NOT follower, but pressure is follower.

**Comment by RiccardoRossi** [comment]
In my opinion a "pressure" load changes in direction and in total value when the surface on which it is applied deforms.

that is ... i think that i agree with @pooyan-dadvand

**Comment by josep-m-carbonell** [comment]
@RiccardoRossi  @pooyan-dadvand , for me it is ok, I think we need to add the implementation for accounting the change of length or area in the current pressure conditions. Other loads will be considered as conservative integrated in a total lagrangian manner.
