### ISSUE TITLE
[Core] Registering a variable with custom number of components?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2182]
https://github.com/KratosMultiphysics/Kratos/blob/4098f560ca06ba74977ae199cd59207aa98e7334/kratos/includes/define.h#L126

Can we define a macro to create variable with custom number of components?, @marandra is interested in this feature in order to avoid register 6 different LM variables

**Comment by pooyan-dadvand** [comment]
For a 3D variable we are creating 4 variables. the arrary and its 3 components. For more components, it is possible but with some macro magic. Another option is to define them manually without macro but I understand that you want to avoid it.

**Comment by loumalouomega** [comment]
Maybe we should limit to 4-6 components to be Voigt notation compatible, i can't find a way to do a loop using preprocessor magic

**Comment by pooyan-dadvand** [comment]
you can do it using some recursion with variadic macro, but if it is for 4 to 6 components I would suggest to have manually written macros for each case

**Comment by loumalouomega** [comment]
What do you think @marandra ?, with 6 would be enough or would you like more flexibility?

**Comment by marandra** [comment]
For my application the number of components is related to the voigt components, so 6 would be enough as I am working mainly with small strains. I may be useful to consider 9 too, so we can extended the application to large strains in the future.

**Comment by loumalouomega** [comment]
:+1:

**Comment by loumalouomega** [comment]
Ping

**Comment by pooyan-dadvand** [comment]
I think it waits for the #2257 not me. Isn't it?

**Comment by loumalouomega** [comment]
Yes, it is fixed in #2257
