### ISSUE TITLE
Cpp test failure in master

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#2191]
@roigcarlo  would you please check if you have the same error? It also happens to me on `core/third-step-toward-amatrix` branch. Would you please also check that branch?

![image](https://user-images.githubusercontent.com/8911479/40538789-f4debb28-6012-11e8-901e-e8204360ea96.png)

**Comment by roigcarlo** [comment]
@pooyan-dadvand No problems in master ( in my computer )

TestModelPartSubModelPartsIterator                                       OK.

I will test the branch now

**Comment by roigcarlo** [comment]
Also OK in the branch

**Comment by philbucher** [comment]
Seems to also fail in Win, see #2170 
I think this is done by @loumalouomega and @miguelmaso

**Comment by loumalouomega** [comment]
Yep, I will see

**Comment by loumalouomega** [comment]
In my computer works, do you have any problem @miguelmaso ?

**Comment by roigcarlo** [comment]
I was testing them on Linux. I can confirm @pooyan-dadvand 's error is there in win for 32 and 64. The others in #2170 did not appear to me :S

**Comment by loumalouomega** [comment]
I am on Windows, working on the solution

**Comment by loumalouomega** [comment]
I am unable to compile with VS2015 Update 3, do I need to update to 2017 for pybind? @roigcarlo

**Comment by loumalouomega** [comment]
I am having https://msdn.microsoft.com/query/dev14.query?appId=Dev14IDEF1&l=EN-US&k=k(C2872)&rd=true for the size_t

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/40579537-83d2c650-6129-11e8-8c56-d9c46beebf4e.png)

**Comment by loumalouomega** [comment]
VS 2017 worked, maybe we should remove that one from the wiki

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/40581045-c70f53a0-614e-11e8-917d-c42bf1b6c6d7.png)

The tests work on my machine in release

**Comment by RiccardoRossi** [comment]
it should also work with 2015...

**Comment by pooyan-dadvand** [comment]
I have added the fix #2209. @roigcarlo would you please merge this to the release and see if tests run well on both linux an windows?
