### ISSUE TITLE
constexpr for geometry dimensions? 

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#2197]
Is it possible to declare methods getting dimension from geometry as constexpr?  The purpose is to define a static constexpr member variable for dimension in elements.   If it is possible, what about the efficiency, it would be better? Is it worth?

**Comment by loumalouomega** [comment]
I added to the technical committee and some tags

**Comment by loumalouomega** [comment]
I agree with the idea of constexpr, we can additionally add remaining tests for the geometries and add some missing methods in derived geometries

**Comment by RiccardoRossi** [comment]
GeometryData is constructed by providing the working_space and local_space dimensions, so i **guess** it would be possible as long as we return directly from the geometry_data.

knowing the size at compile time would definitely be worth...unfortunally using static dimensions becomes impossible as soon as we have a virtual function, which obliges us to use dynamic matrices in all of the dynamic interface.

Still i would upvote if it is possible to make the size methods constexpr. @jcotela i think you also looked into this recently right?

**Comment by josep-m-carbonell** [comment]
@pooyan-dadvand,  the only improvement now is to change that methods to const & instead of doing copies. The constexpr must wait because require static member variables. 
(see https://stackoverflow.com/questions/36489369/constexpr-non-static-member-function-with-non-constexpr-constructor-gcc-clang-d)

**Comment by jcotela** [comment]
@RiccardoRossi we discussed this some time ago with @pooyan-dadvand and we agreed that this would be a good idea. However, no concrete steps were taken, as far as I know. I'd be OK with taking a look again.

**Comment by josep-m-carbonell** [comment]
@jcotela, it is worth in terms of efficiency, do you have any number to justify it?

**Comment by jcotela** [comment]
Well, my concern at the time was not efficieny, but rather the fact that, if the geometry "sizes" could be made constexpr we would have the option to template the elements (and some other classes) based on geometry, which would reduce quite a bit of code duplication and a few `if dimension == 2: ... else: ...` type checks.

**Comment by pooyan-dadvand** [comment]
I had missed this issue....

The idea is very good and I have also liked to have it this way but technically I don't see anyway to make it a constexpr.... 

About returning a const& instead of copy we can do that but will be slightly less efficient to use. A reference access overhead will be imposed.

**Comment by philbucher** [comment]
I am not sure if this is solved, adding it to the TODO of @KratosMultiphysics/technical-committee

**Comment by jcotela** [comment]
@philbucher I don't think the situation has changed much from the opinion expressed by @pooyan-dadvand above. The idea would be quite hard to realize given the current design of geometries. I'd close for now, given that there is no clear path to implementing it.
