### ISSUE TITLE
[DEM] Does dem use the MPICommunicator?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2199]
Hi @maceligueta 
I am thinking a bit ahead for the mpi-solvers and would like to know if for DEM you are using the MPICommunicator when you are running in MPI?
If so, then do you use the regular procedure of replacing it with the processes in the Metis- and the TrilinosApp?
Thx for the info

**Comment by maceligueta** [comment]
Hi @philbucher , we use the MPICommunicator indeed. We are not replacing it with the processes in Metis and Trilinos. Actually, we would like to avoid importing Trilinos, as we do not solve any linear system so far. And it is not so clear if we want to use Metis in the long run...  
The only capabilities we are using are simple methods like MaxAll or SumAll. Are this methods going to be removed? Sorry, I was not aware of it.

**Comment by philbucher** [comment]
thx @maceligueta for the information, I will keep this in mind for further developments

btw nothing will be removed, this question was more into the direction of #781
