### ISSUE TITLE
[ConvDiffusion] Creating new solvers. Conflict name

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2202]
I am creating a new solver+analysis stage for the Conv-Diffusion application. 

My question is what name give to the new/old solvers. @RiccardoRossi suggests to put deprecated in front of the name of the old ones and create the new ones with the very same name. 

Another option is to add new in front of the new ones, and let a time for migration, the problem with this is that we require to change the names twice.

Suggestions?

**Comment by roigcarlo** [comment]
@loumalouomega Why is this marked for Release?

**Comment by loumalouomega** [comment]
I assume @pooyan-dadvand and @RiccardoRossi are expecting this to be ready for the release, because will be part of the Kratos workshop

**Comment by jcotela** [comment]
@loumalouomega which solver(s) do you need to redefine?

**Comment by loumalouomega** [comment]
All of them in order to fit the new structure of the new solvers and stages. That's why I am asking which name to use, because I know that many people use it, and maybe is better to give priority to retrocompatibility

**Comment by jcotela** [comment]
I think there is already some redundancy in the existing python solvers. I would suggest focusing in one formulation for the workshop, and adapting any others to the new format in the future.

**Comment by loumalouomega** [comment]
I was thinking in create just one solver for the moment, and later give support for more formulations. But any case I am having problems with the future analysis-solvers integration, I am unable to make the fluid or the structure properly work

**Comment by pooyan-dadvand** [comment]
If it is for workshop, we should have it in release....

**Comment by loumalouomega** [comment]
Yes, I spoke yesterday with @RiccardoRossi, closing
