### ISSUE TITLE
recovering a branch that disappeared

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#2203]
Dear Sirs,

it appears that feature-fluid-RVE-especial-BC branch is no longer available.
How can one recover it and why do some branches get deleted?

Best,
Pavel

**Comment by loumalouomega** [comment]
Do you remember when was the last time you used it?

**Comment by loumalouomega** [comment]
Is this one?
https://github.com/KratosMultiphysics/Kratos/tree/feature-fluid-RVE-especial-BC

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/40606576-17dde338-6266-11e8-9066-5ae366c5e7d1.png)
![imagen](https://user-images.githubusercontent.com/19991680/40606587-230075a0-6266-11e8-9984-907cd6d83c25.png)
Short tuto

**Comment by playpaolo** [comment]
Maybe around 2 months ago.

**Comment by playpaolo** [comment]
yes, it is this one.

**Comment by playpaolo** [comment]
Thank you- How do I open the thing you attached (shorttuto)?

**Comment by loumalouomega** [comment]
It is just two screenshots

**Comment by playpaolo** [comment]
So how can I get to this branch? Actually, same thing happens for me with periodic-conditions-by-components branch. When I try to check it out, I get an error: Cannot find commit to create a ref on"

**Comment by loumalouomega** [comment]
git checkout -b  feature-fluid-RVE-especial-BC origin/feature-fluid-RVE-especial-BC

**Comment by maceligueta** [comment]
Is this solved, @playpaolo ?

**Comment by loumalouomega** [comment]
I will close this
