### ISSUE TITLE
I want to install the program

### ISSUE THREAD

**Issue by ricardomerida** [KratosMultiphysics/Kratos#2207]
I want install kratos but in the file exe for windows does not do nothing, I want to know what do I do.

**Comment by roigcarlo** [comment]
Dear @ricardomerida 

We currently do not have any installable for kratos but you have several alternatives to use or software that may suit your needs:

You can download it as part of GiD as explained [here](https://github.com/KratosMultiphysics/Kratos/wiki/Getting-Kratos-binaries-(via-GiD))
You can download a precompiled release from [here](https://github.com/KratosMultiphysics/Kratos/releases)
You can compile it yourself as detailed  [here](https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install)

**Comment by ricardomerida** [comment]
Thanks for the help.

I will use the first option but I would like to know where I find help to use the program, and when I add kratos I will see that it is not compatible with the version I can do.

**Comment by roigcarlo** [comment]
Dear @ricardomerida 

You can find several examples of kratos usage in the Docoumentation repo: 
- https://github.com/KratosMultiphysics/Examples

If you want to develop your own application you can follow the tutorials in the wiki:
- https://github.com/KratosMultiphysics/Kratos/wiki/Creating-a-base-application
- https://github.com/KratosMultiphysics/Kratos/wiki/Python-Tutorials
- https://github.com/KratosMultiphysics/Kratos/wiki/Kratos-For-Dummies:-Stationary-heat-transfer

You can also find several other tutorials in the wiki for more specific tasks like debugging, coding in parallel, etc...

**Comment by ricardomerida** [comment]
Thanks @roigcarlo for the help. 

Have a nice day,
