### ISSUE TITLE
When running on a cluster, the Logger prints after too much time. Flush?

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#2213]
Is there any equivalent to `flush` that we can use for the Kratos Logger?

**Comment by pooyan-dadvand** [comment]
Not in the default output. So we have to options:
- One can create an output which does flush each time writes a message
- To add a flush method to the `LoggerOutput` and call it manually.

**Comment by maceligueta** [comment]
I would vote for the second one. Otherwise, there's a risk that many people end up using the output of the XX_Application, because it has a flush...

**Comment by pooyan-dadvand** [comment]
Technical Committee: Flush to be added to the LoggerOutput

**Comment by maceligueta** [comment]
Solved in #2395 .
