### ISSUE TITLE
Process.h adding execution

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#2225]
Can we add a these two methods to process.h in order to complete the solution sequence¿?
ExecuteInitializeNonLinearIteration()
ExecuteFinalizeNonLinearIteration()
@KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
I don't have it clear but of course worth discussing

**Comment by maceligueta** [comment]
@josep-m-carbonell, at the @KratosMultiphysics/technical-committee we would like to have an example. It would be great if we can see an example that shows why these methods are necessary. At the @KratosMultiphysics/technical-committee meeting it was commented that this addition would opens the door unwanted uses of the processes. However, if justified by an example, they could be added.

**Comment by josep-m-carbonell** [comment]
Hi @maceligueta, as I said, they would be necessary to use them consistently with other objects. An example would be a general solving scheme that has a process to perform some operations when calling their methods.  When I ask to the scheme to InitializeNonLinearIteration I think it will be good to call the method with the same name. Imagine that at each iteration (after updating the topology) I want to make some search of the boundaries. Using ExecuteFinalizeNonLinearIteration it will be done.

**Comment by josep-m-carbonell** [comment]
Just for curiosity, which unwanted uses have been mentioned in the committee? . In order to avoid them.

**Comment by maceligueta** [comment]
@josep-m-carbonell : a polemical case would be calling these methods from inside the c++ strategy. The processes were initially designed to be called as a pack in strategic places (already set in Python). So the discussion would be around whether the processes should be used in alternative ways or not.

**Comment by josep-m-carbonell** [comment]
@maceligueta As you know in PfemApp we are using them in different ways in python and in c++,  and in the SolidApp it is like this in some cases too. This is not new, it was implemented when processes were created to replace some type of utilities. They are used in alternative ways, having or not having those two proposed methods.

**Comment by RiccardoRossi** [comment]
My **personal** view of this, is that we should distinguish usages and hierarchies.

With this i mean that something used from the input could be an "Operation" and things constructed internally would be a "InnerProcess". The interfaces could be different to reflect this (for example, this hipotetical "Operation" should not have a method Execute at all, while the InnerProcess could well do, as well as the InitializeNonLinearIteration etc methods.

the biggest problem i see with this approach is that it would bomb completely our backward compatibility and affect everyone. (and once again, to make it clear this is just a personal view)

**Comment by josep-m-carbonell** [comment]
I use Execute as well in inner processes for another type of class structure.

I think it is not a problem two have different type of objects. Maybe it could be clear in order to call all their methods. However to have an object with two more methods I do not think is a problem. I also do not think that is going to break anything or jeopardize the backward compatibility.

**Comment by jcotela** [comment]
For me the issue is that the current Process structure works because we make sure that the python script calls the required methods at the correct points of the code. That is, since all calls are made from the same python layer, it is easy to tell if the system is working correctly or not. The proposed methods would need to be called from the strategy layer, which is typically a separate C++ class. As a result, the mechanism becomes much more fragile, since we now need to ensure that two different objects (in any possible combination of main script + strategy) call the right methods at the right point.

From this point of view, I would prefer to have two separate objects, one that works on the python layer (the current processes) and another that works at the strategy level, with the proposed functions and potentially others that are considered necessary. I also agree with @RiccardoRossi that processes that implement all the Execute... methods are different from those that only have `Execute()` and should be separated, but I'd say that is for another issue.

**Comment by josep-m-carbonell** [comment]
Ok I see that you prefer to create more 'process' objects than to have different methods in the process object to be used for different purposes.

**Comment by maceligueta** [comment]
After the meeting with the @KratosMultiphysics/technical-committee we concluded these remarks:
1- We are trying to establish a well marked distintion between the two scopes `Stage `and the `Solver`. There's a lot of consensus on the big differences between them.
2- While the processes are feeded to the Stage and managed by the Stage, accepting the previous point 1 would mean that the methods `ExecuteInitializeNonLinearIteration()` and `ExecuteFinalizeNonLinearIteration()` cannot be implemented in `Process`, as the process would cross beyond the border between `Stage `and `Solver`.
3- We totally understand the need of an alternative featuring these two methods. It could be another object, called 'SolverProcess', 'Operation', or something equivalent, and they would be feeded to the `Solver`.
4- We think that processes should not, in general, use `Execute()`, as it opens the door to be executed anywhere. However, it is maybe too late by now. Those processes should actually be called 'Action' or equivalent, or be methods in a certain `Utility`.

I'm trying to explain all the thoughts exposed during the meeting. Now, if we forgot to consider something, or some of the points look senseless, the issue remains open for discussion.

**Comment by josep-m-carbonell** [comment]
Ok, thank you to add the comment and discussing it in the technical-committee.
