### ISSUE TITLE
MESH_DISPLACEMENT migration from ALE app. to core

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#223]
Doing some clean up and rearrangements in the FSI application, I noticed that the MESH_DISPLACEMENT variable (which afaik is intended to substitute the DISPLACEMENT var. in the ALE application) belongs to the ALE app. Thus, I suggest to move it to the core to make it available in other applications (e.g. FSI application). Besides, it is somehow strange to have the MESH_VELOCITY in the core but the MESH_DISPLACEMENT in the ALE app.

What do you think @AndreasWinterstein @msandre @KratosMultiphysics/technical-committee ?

**Comment by msandre** [comment]
I had a similar issue with the adjoint application. @jcotela also suggested this solution. Long term I think the plan is to eventually migrate the variables to the applications once the inter-application use of variables is improved. For now I would agree with your suggestion. Should we put the ALE variables in a separate ale_variables.h file in the core?

**Comment by AndreasWinterstein** [comment]
I did not put the ALE variables in the Core since I thought that the number of variables in the core should be reduced. I wanted to move the MESH_VELOCITY to the ALEApplication but it is already used in another application. I think we should clarify with Pooyan if we should do this.

**Comment by msandre** [comment]
That's a good reason for putting the application variables in ale_variables.h if we move to core.

**Comment by jcotela** [comment]
👍 for @msandre's suggestion. Since we still have some issues that have to be solved with application variables (in particular when using those from different applications), we are pushing for the application-specefic `..._variables.h` header files in the core. The idea is that, once the infrastructure to solve these issues is in place, the variables in such headers will be moved to the relevant application.

**Comment by pooyan-dadvand** [comment]
👍  for moving it to core.

**Comment by RiccardoRossi** [comment]
+1 too.

maybe it could be added to cfd_variables instead of to variables.h

**Comment by RiccardoRossi** [comment]
@rubenzorrilla was this done? if so please close the issue

**Comment by rubenzorrilla** [comment]
@RiccardoRossi  Not yet.

**Comment by msandre** [comment]
I added the pr #345 for this issue.

**Comment by msandre** [comment]
ale variables are now in core so I'm closing this issue.
