### ISSUE TITLE
[Core]"Merge" functionality

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#2241]
As pointed out by @philbucher and @loumalouomega we have an outstanding problem with the current settings mechanism:

let's imagine that we have a "base_class"

     class base_class:
            self.default_settings = Parameters({
               "A":2,
               "B":3,
               "C":4
            }

we would like now to define a "derived_class" and to override some of the default settings or add new defaults for example so to achieve:

     class base_class:
            self.default_settings = Parameters({
               "A":200, ---> overridden
               "B":3,
               "C":4,
               "D":300 --> added
            }

currently we would need to replicate all the settings or to add/merge them by hand. This is cumbersome and error prone.

I think it would be good to have the parameters to provide such capability using a "DeriveSettings" functionality (not a good name, Merge would be also a candidate...). Long story short the idea would be to be able to write

      class DerivedClass(BaseClass):

               self.default_settings.Merge( 
                      Parameters( """
                      {   
                           "A": 200, --> this one exists in the default_settings so that we shall override it
                           "D": 300 --> this does not exist in the default_settings so that we shall add it 
                      }
                      """)

**Comment by philbucher** [comment]
+1 from my side, since we discussed this in person already

**Comment by pooyan-dadvand** [comment]
An important feature! 👍

**Comment by pooyan-dadvand** [comment]
Is this can be solved with #3889?

**Comment by loumalouomega** [comment]
> Is this can be solved with #3889?

No, but can be done easily (at least easier than before) using that

**Comment by roigcarlo** [comment]
Closing, repoen if necessary.

**Comment by philbucher** [comment]
I forgot to mention, this is kinda implemented in #4736
