### ISSUE TITLE
Testing release of StructuralMechanics

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2245]
This is just for information for @KratosMultiphysics/structural-mechanics :
- I compiled the release branch and discovered #2240 => fixed in #2242 
Then I pulled the latest version of the Interface (I didn't see a release branch) @jginternational 
- The trusses example works
- A 3D Beam Eigenvalue analysis also worked fine
- A 3D Shell Pendulus (Dynamic Analysis) also worked

That would be it with testing from my side, haven't found flaws

**Comment by jginternational** [comment]
master branch of the interface is going to be published in [Kratos release 6.0.0](https://github.com/KratosMultiphysics/Kratos/releases/tag/v6.0-Beta2) . Any pull request for later Kratos versions are being blocked.
