### ISSUE TITLE
Problem in the design of the python_solvers_wrappers

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#2251]
We have some problems which need to be resolved with the current solvers wrapper:

the main thing is that the function "CreateSolver" should accept only the parameters which refer to the solver, not other parameters such for example the "parallel type".

the thing is that when we want to create a composite solver and to construct internally the solvers, we also whish to use the python_solvers_wrapper, however this cannot be done since we need to create multiple solvers for each of which we have a different parameters object but not "root" with the parallel type etc..."

**Comment by philbucher** [comment]
You can check the ale solvers in the meshmoving app, I had the same problem there

Since only the paralleöism is needed I think what I did there was a good solution

**Comment by pooyan-dadvand** [comment]
would you please provide an example? I'm not sure if I understood it well.

**Comment by philbucher** [comment]
@pooyan-dadvand here is the example from Fluids:
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/python_scripts/python_solvers_wrapper_fluid.py#L13-L14
In order to create the solver you need not only the `solver_settings` from the json but also `problem_data` which is not available in a coupled solver any more

[This is what I did as a workaround in the MeshSolvers](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshMovingApplication/python_scripts/ale_navier_stokes_solver_vmsmonolithic.py#L31-L35)

@RiccardoRossi is right though, this is a limitation

What  if e.g. one solver is running MPI while the other one is not...

**Comment by loumalouomega** [comment]
One option to avoid the wrappers could be to register the solvers, but that would imply to enter in the reign of the C++

**Comment by philbucher** [comment]
@loumalouomega I am not sure if this would be a good solution for the problem pointed out by @RiccardoRossi

**Comment by RiccardoRossi** [comment]
honestly the solution here:

https://github.com/KratosMultiphysics/Kratos/blob/Release-6.0/applications/convection_diffusion_application/python_scripts/python_solvers_wrapper_convection_diffusion.py

looks ok to me.

**Comment by RiccardoRossi** [comment]
with ok, i mean "acceptably clean"

**Comment by loumalouomega** [comment]
I made that and it is based directly on the StructuralMechanicsApplication

**Comment by RiccardoRossi** [comment]
I modified it ... open the link

**Comment by loumalouomega** [comment]
OK, but essentially is the same

**Comment by pooyan-dadvand** [comment]
hmmmm, but this not extensible....

just as an idea, does having include keyword in json can work here?

**Comment by philbucher** [comment]
> just as an idea, does having include keyword in json can work here?

@pooyan-dadvand what exactly do you mean?

Another option: We can check if the parallel_type is available in the solver_settings and if not, then take it from problem_data
If it taken from problem_data then we could add it to the solver_settings
This way it would be easier for coupled solvers to get the correct parallel_type

**Comment by rubenzorrilla** [comment]
IMO @philbucher 's approach is the most straightforward one. Besides it keeps retro-compatibility and it shouldn't be a problem to modify the .json writing.

**Comment by pooyan-dadvand** [comment]
> just as an idea, does having include keyword in json can work here?
> @pooyan-dadvand what exactly do you mean?

to have `@include` keyword in json which incorporate another part of the json in your setting section. another extension would be to have `@optional_include` to give a hint to checker that these values are included as optional and don't claim if they are not used/asked.

**Comment by loumalouomega** [comment]
This discussion is duplicated in #2785 we should close one of them

**Comment by philbucher** [comment]
can we close or migrate this discussion?

**Comment by philbucher** [comment]
closing this, please continue the discussion in #2785
