### ISSUE TITLE
gid io wrapper

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#2255]
I think that in 

https://github.com/KratosMultiphysics/Kratos/wiki/Python-Script-Tutorial:-Writing-Output-File

we should also describe the use of the wrapper that we are using in the stage (it wraps the one described in the tutorial and provides some error checking and reading from parameters).

@jcotela is there any possibility you could take a look into this?

**Comment by philbucher** [comment]
I was planning to write a process which is basically a wrapper for the gid_io_process in a format to work with the AnalysisStage

Same I am currently doing for restart and point output

I can hopefully make the PR by the end of the following week

We could then discuss in the PR, if this would be an applicable solution for you

**Comment by jcotela** [comment]
@RiccardoRossi: @pooyan-dadvand asked me to update this last week, and I have just uploaded the new version. I hope this will be enough for the workshop. On the longer term, I agree with @philbucher that the wrapping layer needs to be rethought (but please do not wrap a process within a process :P)

**Comment by RiccardoRossi** [comment]
guys,
   the goal of this issue is just to signal that the doc needs some polishing (ideally before the tutorial of this week). 

just speak together and come up with a proposal for the polishing...

**Comment by jcotela** [comment]
@RiccardoRossi I meant the tutorial... It should be there already, just check if it is what you need. No polishing until after release. Feel free to close if no further changes are needed to the how-to.
