### ISSUE TITLE
[StructuralMechanicsApplication] Should the load variable be elemental data?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2270]
Right now we add the variable to the nodes (historical), see: https://github.com/KratosMultiphysics/Kratos/blob/7f97570d5c6c50b92b07f04dbf17a57a0b8c1819/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L149

Would be more efficient (memory) to use elemental data (Get/SetValue) ?  @KratosMultiphysics/structural-mechanics

**Comment by philbucher** [comment]
I think this is reasonable, I would wait until @KratosMultiphysics/technical-committee and @KratosMultiphysics/structural-mechanics have time to answer next week

**Comment by loumalouomega** [comment]
Do I proceed with that change?

**Comment by philbucher** [comment]
While doing some FSI I realized that this will be quite a big change for many ppl working with FSI
also @rubenzorrilla would need to change code

Instead of mapping from historical to historical (REACTION => POINT_LOAD) we would have to map from historical to non-historical, which requires some implementation from our side

**Comment by loumalouomega** [comment]
Understood, we should do it, not now, but eventually. We are wasting memory in this and additionally this limits the use of loads. The ideal should be to define directly in the load, so you can do custom definitions of conditions.

**Comment by loumalouomega** [comment]
Besides, using my mapper it is just one parameter of configuration

**Comment by loumalouomega** [comment]
Additionally my plan was not to break the current workflow, but to add a check if the value is defined on the condition, and otherwise take it from the node. This is retro-compatible, but of course doesn't solve the problem and requieres even more memory.

**Comment by pooyan-dadvand** [comment]
I'm not sure if the load history is not important for dynamic problems. @RiccardoRossi any comment?

**Comment by loumalouomega** [comment]
Today we spoke about this in the Kratos Meeting on Barcelona and we said to tackle this and reduce the corresponding memory consumption

**Comment by loumalouomega** [comment]
everyone agrees at @KratosMultiphysics/structural-mechanics ?

**Comment by philbucher** [comment]
as I wrote previously, this breaks the FSI of TUM and @rubenzorrilla 
I have implemented the capabilities for this is #3108 but I am not sure how @rubenzorrilla will solve it
From our side I would prefer to wait for #3108 

EDIT: other than that I agree :+1:

**Comment by loumalouomega** [comment]
I have not problem on waiting, but this is important if we want to improve our application. BTW, we can think if instead of using condition data we use gauss points (important if we want to set not constant values as loads)

**Comment by loumalouomega** [comment]
@rubenzorrilla is informed about this, I told him last Friday

**Comment by rubenzorrilla** [comment]
@loumalouomega @philbucher Makes sense to me as well. If either the MappingApplication mapper or the mortar one in the core are able to deal with this historical - non historical mapping, it shouldn't be a problem for the FSIapplication. 

Let me now if you proceed with the changes! Thanks!

**Comment by loumalouomega** [comment]
The current mortar mapper in the core can dealt both Historical and non historical variables

**Comment by RiccardoRossi** [comment]
A good argument **against **this change is that if you have a time integration than you do need the time history of the force to be able to evaluate loads in the middle of the time step.

for the conditions it is done so that it is possible to apply a discontinuous load to a face, however we have the feeling that it would not be a positive change to do this also for the volume

**Comment by loumalouomega** [comment]
@RiccardoRossi that specific case can be solved creating a new variable like PREVIOUS_POINT_LOAD. We are overloading the memory for a specific case that is not supported right now and can be solved creating a new variable

**Comment by pooyan-dadvand** [comment]
But manual handling of previous time step variable is error prone and make communication between solvers more difficult....

**Comment by loumalouomega** [comment]
True, but in any case is a very particular case, that we can even handle via implementing in the condition to check the nodal value in case no condition value is assign. This will keep the retro compatibility and will allow to consider that particular case @RiccardoRossi is mentioning

**Comment by pooyan-dadvand** [comment]
Meanwhile this would improve the memory efficiency mainly in conditions that most of the time (except for shells) are order of magnitude less than elements. Do you have any measurement showing how it improve the total memory usage?

**Comment by loumalouomega** [comment]
I will need an implementation to check it

**Comment by RiccardoRossi** [comment]
closing since no consensus was reached and the issue appears to be stale.
@loumalouomega please feel free to reopen if you want to discuss this further

**Comment by loumalouomega** [comment]
#3447 is still open. @jrubiogonzalez still interested?
