### ISSUE TITLE
Shell composite properties definition

### ISSUE THREAD

**Issue by peterjwilson** [KratosMultiphysics/Kratos#229]
Hi All,

I’m currently looking at shell elements with composite materials made of an arbitrary number of orthotropic layers. At the moment I'm defining the material properties in the .mdpa file with the _matrix_ variable SHELL_ORTHOTROPIC_LAYERS the following way:

> // Arranged as: thickness, orientation_angle, density, E1, E2, Poisson_12, G12, G13, G23
> SHELL_ORTHOTROPIC_LAYERS  [1,9] ((1,0.0,7850,7.5E+6,2E+6,0.25,1.25E+6,0.625E+6,0.625E+6)) 

Although the above works, it’s not very user friendly. If anyone has ideas on a nicer approach, I’d be happy to hear them.

Cheers,
Peter Wilson

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand, was it Gerardo working on this for the PLC interface? to whom should we ask from Quantech?

**Comment by loumalouomega** [comment]
@peterjwilson I am interested in this topic, I still have pending to implement orthotropy in my solid shell (is defined, but nor properly implemented due to lack of standard definition).

**Comment by pooyan-dadvand** [comment]
Yes @RiccardoRossi  it was Gerardo

**Comment by qatzgerard** [comment]
Hi all,

We define the layup at GUI level in PLC using this table,
 
![imagen](https://cloud.githubusercontent.com/assets/11329978/24710232/d82f34a4-1a1c-11e7-9d21-cfaed67533c3.png)
where for each ply it is necessary to define: a) the composite identifier which is a reference to the material model (elastic, damage, elasto-plastic, etc.) assigned to the layer (ply), b) the current ply thickness, and c) the orientations which are defined in terms of Euler angles by using local co-ordinate system.  

In Kratos could be possible to define a composite layup property, i.e, 
// Elastic material model
Begin Properties 1 
    THICKNESS  1.00000E+000 
    DENSITY  7.85000E+003 
    YOUNG_MODULUS  2.06900E+011 
    POISSON_RATIO  2.90000E-001 
.....
End Properties

// Damage material model
Begin Properties 2 
    DENSITY  7.85000E+003 
    YOUNG_MODULUS  2.06900E+011 
    POISSON_RATIO  2.90000E-001 
    DAMAGE_THRESHOLD  0.00000E+000 
    STRENGTH_RATIO  0.00000E+000 
    FRACTURE_ENERGY  0.00000E+000
.... 
End Properties

// Composite layup
Begin Properties 3 
 SHELL_ORTHOTROPIC_LAYERS [1,1…plypropertieslist]  (( **Reference to material model property identifier** , Thickness, Angle (or Euler angles),…))
SHELL_ORTHOTROPIC_LAYERS [2,1…plypropertieslist] (( **Reference to material model property identifier**, Thickness, Angle (or Euler angles),…))
….
  SHELL_ORTHOTROPIC_LAYERS [n,1…plypropertieslist] (( **Reference to material model property identifier** , Thickness, Angle (or Euler angles),…))
End Properties

Or defining directly the values of ABD matrix using a new Kratos material property keyword. This composite property can be assigned directly to the element in the element definition block (Begin Elements … end Elements).

Here are some **Nastran** references about shell or solid composite definition:
Autodesk® Nastran® In-CAD: (http://help.autodesk.com/view/NINCAD/2016/ENU/?guid=GUID-36130B24-E43D-46CA-898B-23DAB86CC398)

**Patran/Nastran**
http://pages.mscsoftware.com/rs/mscsoftware/images/sec1_intro_to_composites_021712.pdf 
http://www.ist.edu.pk/downloads/amss/lecturers/composite-analysis-ppt-vers-97-2003.pdf

@peterjwilson for the Kratos solid-shell implementation have a look to the Nastran definition:
http://pages.mscsoftware.com/rs/mscsoftware/images/Sec2_Solid_Composites_021712.pdf

**FEMAP/Nastran**
https://www.google.es/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwj23_z2wY3TAhVDuBQKHb84DjQQFggcMAA&url=http%3A%2F%2Fwww.predictiveengineering.com%2Fsystem%2Ffiles_force%2Fcomposite_modeling_handbook_for_femap_nx_nastran_and_ls-dyna_2015.pdf%3Fdownload%3D1&usg=AFQjCNFV3Ty2OGiyDvJ9Yd3cPLNu8Cjw5A&cad=rja

**Comment by pooyan-dadvand** [comment]
Thanks Gerardo!!

**Comment by peterjwilson** [comment]
Thanks Gerado, this approach definitely seems more natural. I'll have a crack at implementing it.

**Comment by peterjwilson** [comment]
It seems that entering any non-numeric data in the SHELL_ORTHOTROPIC_LAYERS matrix entries renders it unable to be parsed properly. Is there a convention for referencing other properties?

**Comment by loumalouomega** [comment]
What do you mean?, Matrix is a class derived from boost  matrix and specialized for doubles. If you want to use something different that number you can use:

`typedef boost::numeric::ublas::matrix<std::string> MatrixStrings`

**Comment by peterjwilson** [comment]
Thanks, but if I switch to that I get the following compile errors for the 'load' and 'save' functions:

![image](https://cloud.githubusercontent.com/assets/23666229/24753695/88e2034c-1ad3-11e7-93de-55ef5227d630.png)

If I use it as a pointer I only get the 'load' error. Even when this matrix issue is fixed, do you know if it is possible to reference and fetch other defined properties? Something along the lines of:

`plydensity = (props)[SHELL_ORTHOTROPIC_LAYERS](currentPly, 0)[DENSITY];`

where SHELL_ORTHOTROPIC_LAYERS is defined in Properties 1 and structured as [MaterialRef1, thickness, angle] and the MaterialRef1 is defined in Properties 2 and has DENSITY, THICKNESS, etc...

**Comment by loumalouomega** [comment]
Maybe, instead of using a  matrix the most practical way is to define your own struct or class storing the information you want to store.

**Comment by RiccardoRossi** [comment]
I would definitely go for defining am auxiliary class. The sectiin
developed by Massimo Petracca should actually allow that

Riccardo

**Comment by pooyan-dadvand** [comment]
Meanwhile I don't get why adding non symmetric entries in mdpa cause you problem. It should work out of the box. @peterjwilson would you please explain a bit more what is the exact error you get?

**Comment by peterjwilson** [comment]
No worries @pooyan-dadvand , I tried to input SHELL_ORTHOTROPIC_LAYERS in the mdpa file in the following format, to see how referencing other properties would work (if it does?):

> SHELL_ORTHOTROPIC_LAYERS  [1,3] ((Property2,0.1,90) )

When I tried to parse it later it was useless, printing it to console gave "`[0,0]( )`". The variable itself is defined as a Matrix though, so it makes sense that it acts strange with text (as Vicente suggested).

**Comment by pooyan-dadvand** [comment]
Now I see, you cannot have a matrix with some entities which are not numbers (like `Property2`)
