### ISSUE TITLE
Errors when compile create_xdmf_file.py

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#2290]
There are some errors when I compile the file:
python3 ~/Kratos/applications/HDF5Application/python_scripts/create_xdmf_file.py MainModelPart.h5
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-ac1d4d7
Importing    KratosHDF5Application
Initializing KratosHDF5Application... 
Traceback (most recent call last):
  File "/home/fengzekang/Kratos/applications/HDF5Application/python_scripts/create_xdmf_file.py", line 93, in <module>
    main()
  File "/home/fengzekang/Kratos/applications/HDF5Application/python_scripts/create_xdmf_file.py", line 81, in main
    for nodal_result in GetNodalResults(h5py_file):
  File "/home/fengzekang/Kratos/applications/HDF5Application/python_scripts/create_xdmf_file.py", line 38, in GetNodalResults
    for variable_name in results_group.keys():
AttributeError: 'NoneType' object has no attribute 'keys'
As following is the create_xdmf_file.py and the MainModelPart.h5

[create_xdmf_file.txt](https://github.com/KratosMultiphysics/Kratos/files/2082698/create_xdmf_file.txt)

**Comment by jcotela** [comment]
@fengzekang which python version are you using?

**Comment by msandre** [comment]
You can use the hdf viewer to check, but I believe you are not writing any results to you file.

**Comment by fengzekang** [comment]
I use the python3. @jcotela

**Comment by fengzekang** [comment]
Do you mean that there is no results in my file so that the errors indicate no "keys"?
And also what is the hdf viewer? @msandre

**Comment by msandre** [comment]
Yes. Check out https://www.hdfgroup.org/downloads/

**Comment by jcotela** [comment]
@fengzekang did you manage to solve this problem?

**Comment by msandre** [comment]
Closing, re-open if needed.
