### ISSUE TITLE
[Documentation]Adding to the wiki "Kratos classes accesible via python"

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2293]
During workshop people were asking how to look the list of classes and methods accessible via python. I created an script to generate this "documentation", can be found [here](https://github.com/KratosMultiphysics/Documentation/tree/master/Wiki_files/pydoc)

The documentation generated is the following:
https://github.com/KratosMultiphysics/Kratos/wiki/Kratos-classes-accesible-via-python

Besides, I discover than some linear solvers are not properly derived from the directa nd iterative solvers respectively, look: 

https://github.com/KratosMultiphysics/Kratos/wiki/LinearSolvers

The only question remaining is if we add extra documentation when exporting the methods and classes to pybind:
https://pybind11.readthedocs.io/en/stable/advanced/misc.html#generating-documentation-using-sphinx

**Comment by RiccardoRossi** [comment]
after having a quick look to the first item ... VERY COOL!!

we should think on how often this should be generated....

**Comment by philbucher** [comment]
there are 1465 pages in the wiki now
Is this related?

**Comment by philbucher** [comment]
looks really cool btw!

**Comment by loumalouomega** [comment]
Yes, it is related, 1200 are just the variables and flags

**Comment by loumalouomega** [comment]
I will close this
