### ISSUE TITLE
Error in structural mechanics: model vs part

### ISSUE THREAD

**Issue by e-dub** [KratosMultiphysics/Kratos#2308]
I am trying to make my code work from before the last changes with the last release, where a model should be passed. There is a problem with the creation of the solver:
- python_solvers_wrapper_structural wants to have a model
- structural_mechanics_solver wants to have a part 

I.e. the original code:
`solver = python_solvers_wrapper_structural.CreateSolver(main_model_part, ProjectParameters)`
throws the following error at python_solvers_wrapper_structural
```
Traceback (most recent call last):
  File "MainKratos.py", line 30, in <module>
    solver = python_solvers_wrapper_structural.CreateSolver(main_model_part, ProjectParameters)
  File "/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/python_solvers_wrapper_structural.py", line 9, in CreateSolver
    raise Exception("input is expected to be provided as a Kratos Model object")
Exception: input is expected to be provided as a Kratos Model object
```

A modified code to pass a model
`solver = python_solvers_wrapper_structural.CreateSolver(main_model, ProjectParameters)`
throws the following error at structural_mechanics_solver
```
Traceback (most recent call last):
  File "MainKratos.py", line 30, in <module>
    solver = python_solvers_wrapper_structural.CreateSolver(main_model, ProjectParameters)
  File "/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/python_solvers_wrapper_structural.py", line 74, in CreateSolver
    solver = solver_module.CreateSolver(model, custom_settings["solver_settings"])
  File "/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_eigensolver.py", line 17, in CreateSolver
    return EigenSolver(main_model_part, custom_settings)
  File "/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_eigensolver.py", line 47, in __init__
    super(EigenSolver, self).__init__(main_model_part, structural_settings)
  File "/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py", line 121, in __init__
    raise Exception('Please specify a model_part name!')
Exception: Please specify a model_part name!
```

You can find this problem also with reproduced with the following example as well:
[github.com/KratosMultiphysics/Examples/tree/master/structural_mechanics/validation/beam_eigenvalue_analysis/source](url)

Any ideas would be most appreciated!

**Comment by loumalouomega** [comment]
We need to update the examples to the new interface, but the solver expects a model right now:

https://github.com/KratosMultiphysics/Kratos/blob/b8918320da671e46a53a67469c172231b17014fe/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L47

**Comment by loumalouomega** [comment]
Take a look what is done on the analysis:

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_analysis.py

**Comment by philbucher** [comment]
@e-dub sorry for breaking your code
We have recently been going through some major restructuring.

The main idea is now that the MainKratos is put into a class, the **AnalysisStage**
=> see the [wiki](https://github.com/KratosMultiphysics/Kratos/wiki/Common-Python-Interface-of-Applications-for-Users)

I will update the example in a moment

**Comment by philbucher** [comment]
@e-dub the example is updated => https://github.com/KratosMultiphysics/Examples/tree/master/structural_mechanics/validation/beam_eigenvalue_analysis

It now works again plus it shows how to use the new `AnalysisStage` - Class:
If you want to do user-scripting the idea is that you derive your own object (like I did in the example) and add your custom coding.

This way you will be less affected by changes in the code

I recommend to also take a look at the [BaseClass](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/analysis_stage.py), this one contains more explanation of what should be done where

**Comment by e-dub** [comment]
@philbucher @loumalouomega Thanks guys for the quick responses and the changes to the examples!   That really helps! 
Unfortunately, I still am not sure how to get to the "computing model part" so I can add elements as I did in my original code. 

```
solver = python_solvers_wrapper_structural.CreateSolver(main_model_part, ProjectParameters)
...
...
...
computing_model_part = solver.GetComputingModelPart()
element = computing_model_part.CreateNewElement(...
```
Is this done now via the following?
```
model = KratosMultiphysics.Model()
computing_model_part = model.GetModelPart(...
```

**Comment by loumalouomega** [comment]
The solver has the method to get the computing model part, but it should be implemented. Technically the first approach is correct

**Comment by philbucher** [comment]
you can do both

if you have your custom `AnalysisStage` (deriving from `StructuralMechanicsAnalysis`) then you can get the solver with `self._GetSolver()`
`GetComputingModelPart()` is still a method of the solver, this hasn't changed

You could also get it from the model
=> `self.model["main_model_part_name.computing_model_part_name"]`
where `main_model_part_name` and `computing_model_part_name`are defined in the [solver_settings in json](computing_model_part_name)

**Comment by e-dub** [comment]
@philbucher and @loumalouomega, thanks!

I think I nearly got this bad boy running again. 
```
model = KratosMultiphysics.Model()
simulation = StructuralMechanicsAnalysisWithEigenPostProcessing(model, parameters)
solver = simulation._GetSolver()
computing_model_part = solver.GetComputingModelPart()
```

**Comment by e-dub** [comment]
@philbucher and @loumalouomega, thanks!

I think I nearly got this bad boy running again.  As the first suggestion is closer to the way I was doing it, I am going that route.  This is what my code looks like:
```
model = KratosMultiphysics.Model()
simulation = StructuralMechanicsAnalysisWithEigenPostProcessing(model, parameters)
solver = simulation._GetSolver()
computing_model_part = solver.GetComputingModelPart()
element = computing_model_part.CreateNewElement(........
```
But now I am getting another error:
```
    computing_model_part = solver.GetComputingModelPart()

  File "/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py", line 268, in GetComputingModelPart
    return self.main_model_part.GetSubModelPart(self.settings["computing_model_part_name"].GetString())

RuntimeError: Error: There is no sub model part with name : computing_domain

in kratos/includes/model_part.h:1078:ModelPart::Pointer ModelPart::pGetSubModelPart(const string&)
```
Did something else change that I am neglecting?

**Comment by philbucher** [comment]
If you call it in this order it will not work because the computing model part is created in the `PrepareModelpart` function of the solver, which itself is called in the `Initialize` fct of the AnalysisStage

If you try to get it afterwards it should work

I will push a fix to throw a proper warning

**Comment by e-dub** [comment]
@philbucher danke sehr...aber olm no net! 

Did you mean like this?   
```
model = km.Model()
simulation = StructuralMechanicsAnalysisWithEigenPostProcessing(model, parameters)
simulation.Initialize()
solver = simulation._GetSolver()
computing_model_part = solver.GetComputingModelPart()
```
This part works perfect, but when it the simulation is started with `simulation.Run()`, it is throwing an error that element ID 1 already exists. Is `simulation.Initialize()` creating the model once and then `simulation.Run()` again?

``` 
Traceback (most recent call last):
  File "MainKratosNew.py", line 42, in <module>
    simulation.Run()
  File "/opt/kratos/kratos/python_scripts/analysis_stage.py", line 47, in Run
    self.Initialize()
  File "/opt/kratos/kratos/python_scripts/analysis_stage.py", line 69, in Initialize
    self._GetSolver().ImportModelPart()
  File "/opt/kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py", line 192, in ImportModelPart
    self._ImportModelPart(self.main_model_part, self.settings["model_import_settings"])
  File "/opt/kratos/kratos/python_scripts/python_solver.py", line 145, in _ImportModelPart
    KratosMultiphysics.ModelPartIO(input_filename).ReadModelPart(model_part)
RuntimeError: Error: attempting to add a new element with Id :1, unfortunately a (different) element with the same Id already exists

in kratos/includes/model_part.h:748:void ModelPart::AddElements(TIteratorType, TIteratorType, ModelPart::IndexType) [with TIteratorType = boost::iterators::indirect_iterator<__gnu_cxx::__normal_iterator<shared_ptr<Element>*, vector<shared_ptr<Element>, allocator<shared_ptr<Element> > > >,...>; ModelPart::IndexType = long unsigned int]
   kratos/includes/model_part.h:771:void ModelPart::AddElements(TIteratorType, TIteratorType, ModelPart::IndexType) [with TIteratorType = boost::iterators::indirect_iterator<__gnu_cxx::__normal_iterator<shared_ptr<Element>*, vector<shared_ptr<Element>, allocator<shared_ptr<Element> > > >,...>; ModelPart::IndexType = long unsigned int]
   kratos/sources/model_part_io.cpp:1405:void ModelPartIO::ReadElementsBlock(ModelPart&)
   kratos/sources/model_part_io.cpp:474:virtual void ModelPartIO::ReadModelPart(ModelPart&)

BuilderAndSolver: Clear Function called
```

**Comment by philbucher** [comment]
`Run` executes the entire simulation => have a look [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/analysis_stage.py#L43-L49)
What you need to do is (if you decide not to derive your own object what we would recommend):
~~~python
simulation.Initialize()
# add elements ...
simulation.RunSolutionLoop()
simulation.Finalize()
~~~

edit to use your example:
~~~
model = km.Model()
simulation = StructuralMechanicsAnalysisWithEigenPostProcessing(model, parameters)
simulation.Initialize()
solver = simulation._GetSolver()
computing_model_part = solver.GetComputingModelPart()
simulation.RunSolutionLoop()
simulation.Finalize()
~~~

**Comment by e-dub** [comment]
Läuft!
@philbucher Besten Dank!
