### ISSUE TITLE
Use of unicode characters in source files.

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#231]
Dear @KratosMultiphysics/kratos-core-team

@jcotela and I have notice that recently there have been commits containing code with comments in which unicode characters are used. This include basically letters with dots, accents and other punctuation symbols.

In general I think it is a good practice that we stick to write codes that only use ASCII (not extended) characters since some compilers may be likely to experience problems trying to compile those files, specially if the encoding of the source code is not supported.

As there is no rule out there that states that the abovementioned characters cannot be used I would like to know your opinion.

**Comment by loumalouomega** [comment]
I agree, but usually if we write comments in English it is not necessary to use extended characters. (and if we don't use emoji everything will be fine)

**Comment by roigcarlo** [comment]
Agree, but Author names have proven to be very challenging :smile:

**Comment by loumalouomega** [comment]
Maybe we can use instead our GitHub usernames

**Comment by RiccardoRossi** [comment]
@charlie,

would it be possible to have Github to reject non-unicode texts at the moment of pull request?

**Comment by roigcarlo** [comment]
It can be done but is not strighforward. I have to create a wrapper hosted elsewhere that checks the files etc...

**Comment by pooyan-dadvand** [comment]
I agree with non Unicode restriction and many of us (like me) have our names translated into English 

Meanwhile @RiccardoRossi the Charlie mentioned by you is not @roigcarlo !!!

**Comment by RiccardoRossi** [comment]
yep sorry @roigcarlo

**Comment by loumalouomega** [comment]
I will add this to https://github.com/KratosMultiphysics/Kratos/wiki/Style-Guide

**Comment by roigcarlo** [comment]
Fine, then we can close it.
