### ISSUE TITLE
[Question][Probably duplicated]Python processes depend on python_process or Kratos::Process?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2314]
@KratosMultiphysics/technical-committee 

Should the processes on python derive from Kratos::Process or from python_process?

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/python_process.py

Many python processes derive from KM.Process:

https://github.com/KratosMultiphysics/Kratos/blob/9c05d22f06183081c78afa4c66996c76c13b88f6/kratos/python_scripts/read_materials_process.py#L15

I will vote to remove/deprecate the python_process and eplace everywhere where is used for Kratos::Process

**Comment by philbucher** [comment]
+1 for removing the python process

**Comment by maceligueta** [comment]
I understand your concern, but removing the Python process would close the door to all those developers who try to avoid (for whatever reason) coding in C++, right?

**Comment by loumalouomega** [comment]
Looks like the Process of Kratos is exposed to python all the python processes heritage from Process, which has the same methods as the python_process. It is a duplicated indeed, you can still do all your developments on python

**Comment by maceligueta** [comment]
And the exposed C++ methods can be overwritten from a derived Python class?

**Comment by loumalouomega** [comment]
yes, because it becomes and object, and you can override any object

**Comment by maceligueta** [comment]
Then, +1 for removing the python process
