### ISSUE TITLE
Higher order (Mindlin) beam elements

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/Kratos#2324]
@KratosMultiphysics/structural-mechanics 

Hi,
I am looking for an higher order beam element (3-noded). Currently, StructuralMechanicsApplication gives an error if I use quadratic elements. Does anyone know if this element is already implemented?

**Comment by KlausBSautter** [comment]
There is no 3_node beam element in the structural_mechanics_application yet

**Comment by Vahid-Galavi** [comment]
Is there any plan to develop it?

**Comment by KlausBSautter** [comment]
As far as I know this is not planed. Do you need a geometrically linear or non-linear one?

**Comment by Vahid-Galavi** [comment]
I need a linear one

**Comment by josep-m-carbonell** [comment]
In the SolidMechanicsApplication the geometrically exact beam element in 3D, for linear (2 nodes),  quadratic (3 nodes) and higher order (can be added easily  if needed) is implemented. You can create a case using the GiDInterface for the solid application.

**Comment by KlausBSautter** [comment]
sry for closing and reopening all the time ..... in this case I suggest to use the SolidMechanicsApp

**Comment by Vahid-Galavi** [comment]
Thanks @KlausBSautter and @josep-m-carbonell!

**Comment by loumalouomega** [comment]
I will close this
