### ISSUE TITLE
AttributeError: 'SIGALRM'

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#233]
Hi everyone, I am currently trying to make my unit tests run. Apparently @peterjwilson has the same problem. 
When I run the 'run_tests.py' file I get following error message:

C:\KRATOS_CLONE\Kratos\kratos\python_scripts>"C:\\KRATOS_CLONE\\KratosInstallNew\\runkratos" run_tests.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.0.0-15f8d5c
Traceback (most recent call last):
  File "run_tests.py", line 273, in <module>
    main()
  File "run_tests.py", line 221, in main
    signal.signal(signal.SIGALRM, handler)
AttributeError: 'module' object has no attribute 'SIGALRM'

Any help is appreciated.

Klaus

**Comment by roigcarlo** [comment]
I am auto-assigning this.

@KlausBSautter This is caused because windows does not know what is SIGALRM. I will try to find an alternative that is OS independent asap.

**Comment by KlausBSautter** [comment]
solved with #240
