### ISSUE TITLE
Duplicated Methods in VariableUtils

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2331]
I was looking at how to set non-historical values on entities and [found a method](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/variable_utils.h#L263-L287) for it

There are however imo two duplicated methods that do the same: 
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/variable_utils.h#L227-L261

Is this intended or am I not seeing sth?

@loumalouomega @rubenzorrilla @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
Indeed, I will deprecate it

**Comment by philbucher** [comment]
Ping

**Comment by pooyan-dadvand** [comment]
They are not the same but can be merged into one.

**Comment by loumalouomega** [comment]
Indeed, give me some time
