### ISSUE TITLE
Maybe inconsistent ModelPart.AddProperties

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#2333]
AddProperties is defined in

https://github.com/KratosMultiphysics/Kratos/blob/c8c5e2ee5057650a0d2f641b96a7602e83766fc2/kratos/includes/model_part.h#L589

which inserts a property (`pNewProperty`) with `ThisIndex` in the current mesh. But the property Id could be another which is not `ThisIndex`. In that case, strange things may occur.

Adding a property with the default index `ThisIndex=0` is a possible bug (what happened to me) since an error is thrown if `Property 0` is already defined. Here is an example:

~~~c++
                Properties::Pointer dry_prop(new Properties(*wet_prop));
                dry_prop->SetId(++last_id);
                // mrModelPart.AddProperties(dry_prop); // This will throw an error if Property 0 is defined
                mrModelPart.AddProperties(dry_prop, dry_prop->Id()); // This works fine
~~~

What is the meaning of `ThisIndex`?
- It should be the mesh index
- It is a useless parameter
- ...

**Comment by loumalouomega** [comment]
@miguelmaso The index is not the index of the property, is the index of the mesh. Lon story short, before the model parts to differentiate between parts the mesh was used. Now it is keep to retro-compatibility, particularly because the mesh is the container of the elements, nodes...

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/c8c5e2ee5057650a0d2f641b96a7602e83766fc2/kratos/includes/model_part.h#L619 

See, here the index is used to get the mesh

**Comment by loumalouomega** [comment]
When you print a model part it print the different meshes, by default there is only one, the 0:

![imagen](https://user-images.githubusercontent.com/19991680/41500407-ecc03f54-7190-11e8-886a-2a932361e960.png)

**Comment by miguelmaso** [comment]
The point is the inconsistency between GetProperties and AddProperties. The next line is part of the definition of AddProperties: 

https://github.com/KratosMultiphysics/Kratos/blob/c8c5e2ee5057650a0d2f641b96a7602e83766fc2/kratos/sources/model_part.cpp#L554

**Comment by loumalouomega** [comment]
Oooh, I see, in any case I think that would be nice to rename to MeshIndex and PropertyIndex to avoid confusion

**Comment by RiccardoRossi** [comment]
mmm,

this does look like a mistake.

as i recall a Property, is an indexed object, so if you want to add it you can ask for its Id by doing

     pprop->Id()

then i think that this interface should be changed accordingly, passing a zero as a default for ThisIndex.

**Comment by pooyan-dadvand** [comment]
It seems that it was broken since 2 years ago.... Rare that nobody has noticed
