### ISSUE TITLE
adjoint tests failed

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#234]
tests worked in branch at commit 0f35d7b88525fa692197a14ca88d083ad8823688 but fail after merged with master in 791b964cdcaffa8176fb3161b695b431e4f784cb

**Comment by RiccardoRossi** [comment]
Hi Mike,

could you give a hint of what type of tests are failing? I am asking this
to guess which can be the feature that is causing the failure
<http://www.cimne.com/>

**Comment by msandre** [comment]
Hi Riccardo,

The unit tests all pass. The verification tests, which compare finite differences of drag on a cylinder with the adjoint sensitivity fail. The problem appears to be from changes to the core related to openmp. I ran an experiment by calculating sensitivities from 5 test runs, once with multiple threads and again with a single thread:

test_Cylinder (AdjointFluidApplication/tests/test_vms_sensitivity_2d.py)
Node 1968, SHAPE_SENSITIVITY_X
Finite Difference Step Size = 0.00000001

commit 0f35d7b88525fa692197a14ca88d083ad8823688 (before PR #187 merged)

Adjoint Sensitivity
-8.448944068383674e-05
-8.448944068382459e-05
-8.448944068382980e-05
-8.448944068382806e-05
-8.448944068384368e-05
-8.44894406838 => 11 digits
Adjoint Sensitivity OMP_NUM_THREADS=1
-8.448944068383327e-05
-8.448944068383327e-05
-8.448944068383327e-05
-8.448944068383327e-05
-8.448944068383327e-05
-8.448944068383327 => 15 digits
Finite Difference Sensitivity
-8.449326850158700e-05
-8.449326850158700e-05
-8.449332271169563e-05
-8.449331729068477e-05
-8.449318176541320e-05
-8.4493 => 4 digits
Finite Difference Sensitivity OMP_NUM_THREADS=1
-8.449324139653269e-05
-8.449324139653269e-05
-8.449324139653269e-05
-8.449324139653269e-05
-8.449324139653269e-05
-8.449324139653269 => 15 digits

commit 791b964cdcaffa8176fb3161b695b431e4f784cb (after PR #187 merged)

Adjoint Sensitivity
-8.448942646811092e-05
-8.448942373318405e-05
-8.448942614704656e-05
-8.448942639109960e-05
-8.448942639109266e-05
-8.448942 => 6 digits
Adjoint Sensitivity OMP_NUM_THREADS=1
-8.448942639109613e-05
-8.448942639109613e-05
-8.448942639109613e-05
-8.448942639109613e-05
-8.448942639109613e-05
-8.448942639109613 => 15 digits
Finite Difference Sensitivity
-8.449737762782072e-05
-8.449326850158700e-05
-8.250792627242931e-05
-8.451844909704298e-05
-8.449324681754355e-05
-8. => 0 digits
Finite Difference Sensitivity OMP_NUM_THREADS=1
-8.449320887046752e-05
-8.449320887046752e-05
-8.449320887046752e-05
-8.449320887046752e-05
-8.449320887046752e-05
-8.449320887046752 => 15 digits

It appears that both the cfd and adjoint solvers are consistent over much fewer digits due to openmp related changes in the core solvers. The tests seem to be failing because the finite differences, used to verify sensitivities, are no-longer accurate and there are fewer digits that will agree with reference data.

**Comment by msandre** [comment]
I think I found part of the issue. If I take the commit 791b964cdcaffa8176fb3161b695b431e4f784cb (after PR #187 merged) and check out the residual-based block builder and solver from the working commit with:

git checkout 0f35d7b88525fa692197a14ca88d083ad8823688 kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h

I get:

Finite Difference Sensitivity
-8.449321429147838e-05
-8.449325765956528e-05
-8.449315466035890e-05
-8.449314381833717e-05
-8.449321429147838e-05
-8.4493 => 4 digits

So the 4 digits of consistency are recovered if the changes to the builder and solver are reverted. To see the changes:

git diff 0f35d7b88525fa692197a14ca88d083ad8823688 791b964cdcaffa8176fb3161b695b431e4f784cb kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h

**Comment by RiccardoRossi** [comment]
Hi Mike,
       i am not sure of what is happening here. 
in commit 0f35d7b we fused together the loop on elements and conditions. This was done so to improve the openmp parallel efficiency. The same commit also allows choosing between using openmp locks or atomics in the assembly phase.

The side effect is that the order at which elements and conditions are evaluated may change dynamically depending on the load unbalance. This is typically accepted for parallel computing, even though it may cause a precision change for very ill conditioned problems. Having said this I wouldn't expect an effect as significant as the one your are seeing ... so i suspect we have an implementation problem.

are u using the function "Build", "Assemble" and "AssembleRHS" or something different?

also, may i ask you to see if the situation remains the same if you define

     #define USE_LOCKS_IN_ASSEMBLY

in the residualbased_block_builder_and_solver.h

ciao







in principle the

**Comment by msandre** [comment]
I'm using Build(), Assemble() functions. I tested the #define USE_LOCKS_IN_ASSEMBLY using a more recent commit (b81a606c4b5b0999554e35a7b45c3c4bdb1cb3e2) so I don't have to recompile so much.

Using locks works:

Finite Difference Sensitivity using locks
-8.449326850158700e-05
-8.449312213429372e-05
-8.449324139653269e-05
-8.449322513350010e-05
-8.449330102765218e-05
-8.4493 => 4 digits

There seems to be a bug in the Assemble() when the RHS is assembled there is a missing atomic. After I add it, the problem is fixed:

Finite Difference Sensitivity
-8.449318176541320e-05
-8.449330102765218e-05
-8.449318718642407e-05
-8.449328476461959e-05
-8.449326850158700e-05
-8.4493 => 4 digits

I will try adding a PR this afternoon.

**Comment by msandre** [comment]
PR #237 added.

**Comment by msandre** [comment]
Issue is solved with PR #237.
