### ISSUE TITLE
[Core][Geometries]Triangle2D3 has only one integration point by default

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2367]
@KratosMultiphysics/technical-committee 

https://github.com/KratosMultiphysics/Kratos/blob/c4c4fc35f587a5ccfc0d65d77c8b0a5684c3476f/kratos/geometries/triangle_2d_3.h#L2131

In the other hand the Quadrilateral2D4 uses 4 GP by default:

https://github.com/KratosMultiphysics/Kratos/blob/c4c4fc35f587a5ccfc0d65d77c8b0a5684c3476f/kratos/geometries/quadrilateral_2d_4.h#L1115

**Comment by philbucher** [comment]
I think this is on purpose
Dont the fluid elements rely on this for being fast? @jcotela

**Comment by loumalouomega** [comment]
This can be configured in the element itself, but in my opinion the default should be the minimum necessary to get a good aproximation in the case of a linear function. Three gauss points for the triangle

**Comment by loumalouomega** [comment]
In fact the tetrahedra has the same problem

https://github.com/KratosMultiphysics/Kratos/blob/c4c4fc35f587a5ccfc0d65d77c8b0a5684c3476f/kratos/geometries/tetrahedra_3d_4.h#L1808

**Comment by loumalouomega** [comment]
@jcotela is this on pourpose as @philbucher says?

**Comment by josep-m-carbonell** [comment]
It is correct, they are the minimum, where is the problem?

**Comment by loumalouomega** [comment]
Well, I expected to be the same at least the minimal necessary to integrate a linear function

**Comment by josep-m-carbonell** [comment]
If  the primary variable is approached by a linear field, one integration point is the minimum. In quadrilaters,  we use four to avoid free energy modes.

**Comment by loumalouomega** [comment]
OK, I will close this then

**Comment by jcotela** [comment]
@loumalouomega @philbucher As far as I know, the criteria for the default integration point is "as many as needed to integrate the stiffness matrix for an elastic linear problem/a Poisson equation".

**Comment by jcotela** [comment]
@loumalouomega since you reopened it, can I ask you to clarify what is your goal with the issue?

The current setup matches the stated "rule": for elements with linear shape functions (triangles/tetras) one gauss point is enough to exactly integrate the stiffness matrix or a Laplacian. For bi-linear elements (quads) you need four, otherwise you get zero energy modes as @josep-m-carbonell is saying.

**Comment by loumalouomega** [comment]
I reopened because you commented, and I thought that the discussion wasn't finished. I am happy with the answer, so I will close again, sorry for the misunderstood

**Comment by jcotela** [comment]
@loumalouomega no problem, thanks for clarifying.
