### ISSUE TITLE
[Discussion] Unify normal computation utilities

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2376]
As @jcotela pointed, there are duplicated utilities for normal computation:

The normal computation utils:

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/normal_calculation_utils.h

The body normal computation:

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/body_normal_calculation_utils.h

And in the mortar utilities:

https://github.com/KratosMultiphysics/Kratos/blob/1714b801d7719de135495d46a71cf71bd22a3fde/kratos/utilities/mortar_utilities.h#L418

https://github.com/KratosMultiphysics/Kratos/blob/1714b801d7719de135495d46a71cf71bd22a3fde/kratos/utilities/mortar_utilities.h#L475

These were developed by me and are oriented to compute normals for any condition geometry (not only for triangles)

We can open a discussion to agreed a common interface and create a common utilities for the normal computation, and deprecate the current ones.

____

# **List  of requirements**
- should work with and without MPI
- should work for all (or at least the main geometry types not just tri and tet)
- should be able to compute the `NORMAL` historical or non-historical in order to save memory

**Comment by jcotela** [comment]
@loumalouomega there is at least one more method (also for triangles/tetra only):
https://github.com/KratosMultiphysics/Kratos/blob/1714b801d7719de135495d46a71cf71bd22a3fde/kratos/processes/tetrahedral_mesh_orientation_check.h#L34-L41

**Comment by pooyan-dadvand** [comment]
Is there any trilinos version of these?

**Comment by jcotela** [comment]
No idea about the new ones, but the old ones work in MPI (they assemble the NORMAL variable when required).

**Comment by loumalouomega** [comment]
Well, do you mind I propose a new common utility and I deprecate the rest?

**Comment by philbucher** [comment]
is this solved?

**Comment by loumalouomega** [comment]
Nope, yet

**Comment by philbucher** [comment]
Some comments from my side:
there is also a trilinos/mpi version: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_utilities/mpi_normal_calculation_utilities.h

I think that the new utility should be able to work both with and without mpi otherwise we again have to reimplement stuff multiple times
With the new MPICore this should be doable :+1: 

And ofc it should not be restricted to tets/trias

Plus I like the recent work done by @loumalouomega such that sth can be computed historical/non-historical

**Comment by loumalouomega** [comment]
> Some comments from my side:
> there is also a trilinos/mpi version: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_utilities/mpi_normal_calculation_utilities.h
> 
> I think that the new utility should be able to work both with and without mpi otherwise we again have to reimplement stuff multiple times
> With the new MPICore this should be doable +1
> 
> And ofc it should not be restricted to tets/trias
> 
> Plus I like the recent work done by @loumalouomega such that sth can be computed historical/non-historical

I will, when I have the time, sorry for that

**Comment by jcotela** [comment]
@loumalouomega as a first step, I think it would be good if we can have a list of the requirements/features of the eventual utility. In this way, maybe other people could collaborate on it if you do not have the time for it (which I completely understand).

**Comment by loumalouomega** [comment]
OK, I assume that the methods implemented on normal calculation utilities are the desired ones. What do you think @RiccardoRossi ?

**Comment by philbucher** [comment]
I modified the first comment and started with a list of requirements
Please feel free to add more requirements

**Comment by philbucher** [comment]
Are we still needed in the NormalCalcUtils now that the Geometry can also provide it?

**Comment by RiccardoRossi** [comment]
guus, body and surface normals have a different role...and they may play very differently on corners

**Comment by loumalouomega** [comment]
> Are we still needed in the NormalCalcUtils now that the Geometry can also provide it?

As @RiccardoRossi an average normal is not the same as a punctual normal

**Comment by loumalouomega** [comment]
This has been more or less done
