### ISSUE TITLE
Issue in GiD output when restart is called

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#2378]
@loumalouomega  @jcotela @rubenzorrilla 

There is an issue in the gid_output_process.py when restart is called.

In line 193 the function from line 624 is called:

  File "Kratos/kratos/python_scripts/gid_output_process.py", line 193, in ExecuteInitialize
    self.__restart_list_files(additional_list_files)
  File "Kratos/kratos/python_scripts/gid_output_process.py", line 624, in __restart_list_files
    file_id.append(int(print_id))
ValueError: invalid literal for int() with base 10: 'cuts'

The problem is, this has the premise that the naming is in a certain way, such as (in the code):
                #if f.name = problem_tested_145.post.bin
                file_parts = f.split('_')  # you get ["problem","tested","145.post.bin"]
                num_parts  = len(file_parts)

                end_parts  = file_parts[num_parts-1].split(".") # you get ["145","post","bin"]
                print_id   = end_parts[0] # you get "145"

We do not always have an int "145" before the extension. I was trying a case with body and cut plane output, where I have the naming
for cuts:

- Rect_51_coarse_cuts.post.bin
- Rect_51_coarse_cuts.post.lst

for body output:

- Rect_51_coarse.post.bin
- Rect_51_coarse.post.lst 

The current implementation is not robust enough to handle general cases. Seems to have been tuned for MPI.

**Comment by mpentek** [comment]
@jcotela said that probably this is a larger work or at least it should be done so that restart works well and maybe already permit more flexible output (with probably separate parameters) for cuts, body, node, etc.

@philbucher any thoughts on the restart part and maybe how should it be made more flexible?

For now the main problem is that it does not work when restart is called unless the above functions are commented out.

**Comment by philbucher** [comment]
this is solved (aka it does not throw any more) in #2815
