### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#2411]
I've ordered the tags a bit:

* **Red**: Errors, warnings, problems, api breakers, etc...
* **Yellow**: Life cycle (compilation, debug, release, ...)
* **Blue**: Components (Kratos, Applications, Documentation, External applications, ...)
* **Purple-Pink**: Human Interactions (Discussions, meetings, help requested, ...)
* **"Pistacho" Green**:  Operating systems & Languages (C++, Python, Windows, ...)
* **Green**: Improvements (hotfix, cleanups, enhancements, ...)
* **Light green**: Performance and Benchmarking. Also valgrind.
* **Grey**: Classification like duplicated, wontfix, etc...

I tried to keep as much as possible the tag colors as they were right now but a couple of them had to change color so match they groups. I treid to follow the Green=Good Red=Bad approach.

I think it is important that further tags follow this classification (or any other) as it really helps to identify things quickly.

Any suggestion is more than welcome.

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/42094898-63141c14-7bb1-11e8-8afa-e81ace3b7b62.png)
