### ISSUE TITLE
speeding up linking time in FullDebug

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#2416]
I would propose adding the following in FullDebug. It sensibly increases linkint time by deactivating lto

if(CMAKE_CONFIGURATION_TYPES MATCHES FullDebug)
    set(PYBIND11_LTO_CXX_FLAGS "" CACHE INTERNAL "")
    set(PYBIND11_LTO_LINKER_FLAGS "" CACHE INTERNAL "")
endif(CMAKE_CONFIGURATION_TYPES MATCHES FullDebug)

**Comment by roigcarlo** [comment]
Just to be clear, were we should put this? as part of the kratos main cmake after including pybind11 module or directly editing the pybind one?

**Comment by RiccardoRossi** [comment]
i would put it on the kratos side... eventually we may want to control it independently of FullDebug...(i mean, give the option of using the same also in Release mode, even though pybind developers **advice against doing it**)

**Comment by roigcarlo** [comment]
Implemented, closing
