### ISSUE TITLE
Mixed-mode Debug

### ISSUE THREAD

**Issue by oberbichler** [KratosMultiphysics/Kratos#2426]
I have some problems with mixed-mode debugging using Windows + Visual Studio + pybind + Anaconda.

Kratos always tries to link to the `python*_d.lib` which is not part of the Anaconda installation.

**Workaround:**
Modifing `pyconfig.h` (very hacky)

**Comment by roigcarlo** [comment]
Hi @oberbichler 

You can disable the compilation of runkratos:
-DINSTALL_EMBEDDED_PYTHON=OFF

Or you can tell visual studio to exclude that lib in the runkratos project properties -> linking -> list of excluded files.

Any of this should solve the problem

**Comment by oberbichler** [comment]
👍 thanks!
