### ISSUE TITLE
Compile error in SolidMechanicsApplication

### ISSUE THREAD

**Issue by e-dub** [KratosMultiphysics/Kratos#2427]
Has something changed in the approximately the last week or so in compiling? I am getting the following error when building:

```
In file included from /kratos/applications/SolidMechanicsApplication/custom_conditions/load_conditions/load_condition.cpp:15:0:
/kratos/applications/SolidMechanicsApplication/custom_conditions/load_conditions/load_condition.hpp: In member function ‘virtual bool Kratos::LoadCondition::HasVariableDof(Kratos::BoundaryCondition::VariableVectorType&)’:
/kratos/applications/SolidMechanicsApplication/custom_conditions/load_conditions/load_condition.hpp:148:23: error: ‘ROTATION’ was not declared in this scope
       if(rVariable == ROTATION)
```
Thanks in advance!

**Comment by josep-m-carbonell** [comment]
I don't know exactly what has changed, I have not detected the compilation error, try to add:
#include "includes/variables.h"
in  load_condition.hpp

**Comment by e-dub** [comment]
Thanks @josep-m-carbonell!

As suggested, I added the following line:
#include "includes/variables.h"
to these files
/kratos/applications/SolidMechanicsApplication/custom_conditions/load_conditions/load_condition.hpp
/kratos/applications/SolidMechanicsApplication/custom_conditions/elastic_conditions/elastic_condition.hpp
That fixed 'er!

**Comment by josep-m-carbonell** [comment]
Please, can you make a PR with the changes?
