### ISSUE TITLE
Bug with the POSITIVE_FACE_PRESSURE load

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#2436]
As I was saying in the previous issue regarding this LOAD, now it applies the load without getting the previous error but I've noticed that when you use this kind of load the **Newton-Raphson strategy iterates (4-5 times) even when I use a LinearElasticLaw + SmallDisplElem**, which is impossible in my opinion...

It seems that it is something wrong with the aplication of this load because sometimes it iterates 4-5 times until convergence when everything is elastic.

Thank you in advance,

@RiccardoRossi @loumalouomega

**Comment by loumalouomega** [comment]
Can I go to see you?

**Comment by AlejandroCornejo** [comment]
Sure

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by AlejandroCornejo** [comment]
As we have talked, it is a problem of the load being to big o something related to the loss of the small displ state (just if someone wants to know)
