### ISSUE TITLE
Where can I find all presentations of Kratos workshop 2018?

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/Kratos#2445]
@loumalouomega 

Where can I find all presentations of Kratos workshop 2018? There are only two presentations here:

https://github.com/KratosMultiphysics/Documentation/tree/master/Workshops_files/Kratos_Workshop_2018

**Comment by loumalouomega** [comment]
I uploaded mine and the one of @roigcarlo , @RiccardoRossi @pooyan-dadvand @rubenzorrilla can you upload yours?

**Comment by rubenzorrilla** [comment]
I already uploaded my presentations. I took the chance to rename the rest to include the workshop edition in the filename.

**Comment by maceligueta** [comment]
Referencing @GuillermoCasas  for the DEM presentation.

**Comment by pooyan-dadvand** [comment]
I have uploaded the general structure. Thanks for reminding

**Comment by GuillermoCasas** [comment]
I just uploaded the DEM presentation, although as a pdf, since it was too heavy (670 MB).

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Documentation/tree/master/Workshops_files/Kratos_Workshop_2018 

Can we close this?, we are almost on 100 issues again

**Comment by rubenzorrilla** [comment]
I think we can. @Vahid-Galavi please reopen it again in case it's needed.

**Comment by rubenzorrilla** [comment]
I think we can. @Vahid-Galavi please reopen it again in case it's needed.
