### ISSUE TITLE
Git shows change in symbolic link file

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#2455]
Hi @GuillermoCasas and @salvalatorre 

In my PR #2443 git shows that i changed the file mode of the following file:

`applications/swimming_DEM_application/test_examples/candelier_spiral.gid/chandelier.py`

even though i don't want to change it, because i have nothing to do with the swimming_DEM_application.
It happened to me already a few times, and I am pretty sure, that the change happened while merging master into my branch, because i am sure that i never touched or modified the file directly.

I would like to revert this change, but checking it out using ```git checkout -- file``` does not help.

Do I have some wrong settings in my Git or does anyone know how i can revert these changes?

PS: when looking at this files history, the same already happened to me once, because i appear in the history of this file.

Thanks for any hints and sorry for any inconvenience.

**Comment by ddiezrod** [comment]
Same thing happened to me at least once ...

**Comment by maceligueta** [comment]
I think all symbolic links should be removed. They also caused problems in my computer. I removed some of them, but some are left and still causing problems to @farrufat-cimne , for instance.

**Comment by armingeiser** [comment]
So I will ignore this in my PR and merge it anyway once it is approved.

**Comment by GuillermoCasas** [comment]
Yes, please, ignore it. The design is faulty and the application is in a bit of a hold. We will fix this as soon as possible

**Comment by armingeiser** [comment]
Thanks!
