### ISSUE TITLE
unexpected exception

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#2467]
Good afternoon!

I've been implementing a new constitutive law whose create funtion is as follows:
![imagen](https://user-images.githubusercontent.com/26402605/42466253-a0da1f4e-83ae-11e8-872e-76dbfa8fbf42.png)

As you can see this CL needs two other CL to be constructed, the constructor has the form:

![imagen](https://user-images.githubusercontent.com/26402605/42466313-cecba026-83ae-11e8-92b2-26bf788ea409.png)

The problem appears when I want to acces to this member CL named "mpPlasticityConstitutiveLaw" and "mpViscousConstitutiveLaw" because I get an error saying that these pointers are null...

The clone method of the main CL is:
`    ConstitutiveLaw::Pointer Clone() const override
    {
        return Kratos::make_shared<GenericSmallStrainViscoplasticity3D>(*this);
    }`

specifically, I get the error at the line 64 of the following picture:
![imagen](https://user-images.githubusercontent.com/26402605/42466468-51ada37c-83af-11e8-9d60-205fc70c34c9.png)

Why are these pointers being "reset" ?

Thank you in advance,

Alejandro

**Comment by RiccardoRossi** [comment]
@AlejandroCornejo , is your clone copying correctly the pointers?

**Comment by AlejandroCornejo** [comment]
I think that this is the problem but I do not know how to solve it, do you have any example?
Thank you

**Comment by loumalouomega** [comment]
@AlejandroCornejo for the member variables you don't need to asign in the body of the method, you can do as in https://github.com/KratosMultiphysics/Kratos/blob/c49cd0f3d33865a1976adf497794c411ad7ca252/applications/StructuralMechanicsApplication/custom_processes/solid_shell_thickness_compute_process.h#L75

**Comment by loumalouomega** [comment]
@AlejandroCornejo have you implemented the copy operator?

**Comment by AlejandroCornejo** [comment]
I have the generic one...

**Comment by AlejandroCornejo** [comment]
These are the 2 files..

https://github.com/KratosMultiphysics/Kratos/blob/adding_const_laws_to_structural_mech_app/applications/StructuralMechanicsApplication/custom_constitutive/generic_small_strain_viscoplasticity_3d.cpp

https://github.com/KratosMultiphysics/Kratos/blob/adding_const_laws_to_structural_mech_app/applications/StructuralMechanicsApplication/custom_constitutive/generic_small_strain_viscoplasticity_3d.h

**Comment by loumalouomega** [comment]
Here:

a8fc8cfc13e59cef14f403d991d621172d872624

**Comment by AlejandroCornejo** [comment]
after all these changes I've tried to run the case and we still have the same problem... I will go to see you tomorrow!

Thank you

**Comment by roigcarlo** [comment]
@AlejandroCornejo @loumalouomega Is this already solved?
