### ISSUE TITLE
Read material behaviour

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#2471]
The current read material tools takes a modelpart and applies the created material to all of its elements and conditions. 
IMO we might separate what is read material (which fills properties) and what is assign material to a modelpart. My use case would be when we have a model and I want to change the material property. (i.e changing shells material but not their thickness) Now we should separate them in different modelpart just by their properties and do some magics. Also it is restricting the normal use of properties within a modelpart without any obvious reason.

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand i see your point, however this goes in the line of having the mdpa to contain "only the geometry" and the organization in submodelparts.

Having said this it is not that i dislike your proposal, but simply that i don't like having such a big backward incompatible change. Rather we could (optionally) throw warnings if a mismatch is found between what is assigned in the mdpa and what is assigned in the json.

**Comment by josep-m-carbonell** [comment]
How can you keep backward compatibility considering the proposed change in #2414 (which I personally approve) ?  In my opinion, some improvement are needed.

**Comment by RiccardoRossi** [comment]
that is actually the 100M$ question...

**Comment by frastellini** [comment]
In Stampack, the input data file contains first a list of materials (with its properties: elastic and plastic properties), later a list of sections (with properties such as thickness, layered materials configuration, Failure o Forming limit criterions, etc).
Each element in the mesh uses one section (not a material, directly). Each element may have different section number within the same geometry (FEM mesh).
In case of composite materials, we can define heterogeneous sections (such as layered sections) with different layers of materials. Each section may contain references to one or several material ids (that must be previously defined).

Do you think that some similar approach could be useful for Kratos? Of course that we will need to see which could be the better way to implement such a change without breaking forward compatibility.
Maybe, if we implement the concept of SECTION, we can automatically set and assign a default homogeneous SECTION to those examples not having a section defined.

This approach may also offer some solution for isuee #2414.

I offer myself for further discussions on this matter. For shure, there are many other aspects that need to be taken into consideration before performing such a change inside Kratos...

**Comment by philbucher** [comment]
@frastellini there is sth in the `SECTION` direction already done for the composite shells in StructuralMechanics
The variable `SHELL_ORTHOTROPIC_LAYERS` is defined as a `Matrix`, where each row represents a layer of material
I don't think however that this is the best solution possible

**Comment by loumalouomega** [comment]
I think that with the new Parameters input for CL we have  lot of flexibility to configure the constitutive laws, and all of this can be accommodated relatively easy.

**Comment by frastellini** [comment]
Thank you @philbucher and @loumalouomega for your comments!
The SECTION already done for the composite shells in StructuralMechanics seems to be a good implementation for layers of orthotropic materials, but homogenous (layer per layer).
We would like to model each layer with a composite material (let's say fibre and matrix) by mixing the CL behaviour of its components (classical rule of mixtures, or another more complex non-linear composition model). Probably, the new enhanced flexibility of constitutive laws may help to implement such mixing of material constitutive laws.
Eventhough, @pooyan-dadvand is proposing in this issue the discussion of extra flexibility in the input of material properties.

**Comment by loumalouomega** [comment]
Did we reach any conclusion?

**Comment by loumalouomega** [comment]
Is this discussion still active?

**Comment by philbucher** [comment]
what is the status of this?

**Comment by pooyan-dadvand** [comment]
In todo of technical committee

**Comment by pooyan-dadvand** [comment]
I agree that the application by submodelparts can substitute the other way. So closing.
