### ISSUE TITLE
problem while Creating new application

### ISSUE THREAD

**Issue by Adityamangaonkar** [KratosMultiphysics/Kratos#2475]
Hi @roigcarlo  

I have tried to create new application but it is giving me following error

aditya@aditya-VirtualBox:~/Kratos_masters/kratos/python_scripts/application_generator$ python createApplication.py MyExample
Traceback (most recent call last):
  File "createApplication.py", line 3, in <module>
    from classes.elementCreator import ElementCreator
  File "/home/aditya/Kratos_masters/kratos/python_scripts/application_generator/classes/elementCreator.py", line 1, in <module>
    from classes.classCreator import ClassCreator
  File "/home/aditya/Kratos_masters/kratos/python_scripts/application_generator/classes/classCreator.py", line 80
    print(msg, file=sys.stderr)
                   ^
SyntaxError: invalid syntax
aditya@aditya-VirtualBox:~/Kratos_masters/kratos/python_scripts/application_generator$ 

have I done anything wrong?

Please guide.
Thanks in advance

**Comment by roigcarlo** [comment]
Hi @Adityamangaonkar 

I think you are trying to use python2. The application generator only works with python 3.
If you can't use python 3 try to add this line at the top of all python files in the application generator folder:

```Python
from __future__ import print_function, absolute_import, division
```

It should work but I cannot confirm it 100%

**Comment by Adityamangaonkar** [comment]
I tried this but it doesn't work. I think I am using python3
aditya@aditya-VirtualBox:~$ python3 --version
Python 3.5.2

**Comment by roigcarlo** [comment]
Hi @Adityamangaonkar, 

Then it's very odd. I have been testing that in my machine and when I run using python3 i obtain:
![image](https://user-images.githubusercontent.com/1935791/42573985-dac2c394-851d-11e8-9983-e0fcd8ea647f.png)

But when running with python2:
![image](https://user-images.githubusercontent.com/1935791/42574027-efbcca88-851d-11e8-93c7-41c4933b2f93.png)

Which is precisely the error you are having. According to the first output you post you were using `python` not `python3`. May this be the issue?

Can you double check the python3 thing?

**Comment by roigcarlo** [comment]
@Adityamangaonkar Came and now it is solved, closing
