### ISSUE TITLE
What is the status of the nurbs_application?

### ISSUE THREAD

**Issue by oberbichler** [KratosMultiphysics/Kratos#2481]
Are overlaps with the [`NurbsBrepApplication`](https://github.com/KratosMultiphysics/Kratos/tree/Brep_Application)?

**Comment by tteschemacher** [comment]
I think that's the application from Dimitrios. If not done already it can be deleated. But there are no overlaps to the NurbsBrepApplication.

**Comment by philbucher** [comment]
Can it be deleted then?

**Comment by loumalouomega** [comment]
Check first that there is anything of value...

**Comment by philbucher** [comment]
@oberbichler could you check this?
I had a look but you are more the expert on this

**Comment by oberbichler** [comment]
AFAIK nobody is using this application at the moment.

For me it is not important to delete the application. Anyway I created a branch to show the affected files:

[delete-nurbs-application](https://github.com/KratosMultiphysics/Kratos/tree/iga/delete-nurbs-application)

There are two commits: one for deleting the application itself and one for deleting the geometry objects in the core (btw: I like the idea of treating nurbs geometries like any other geometry).

`nurbs` appears also in [some](https://github.com/KratosMultiphysics/Kratos/blob/b4566c46108e747172858f77f6b95c46cace3fd2/applications/DEM_application/custom_problemtype/DEMpack/scripts/libs/wkcf/wkcfdem.tcl#L185) [tcl](https://github.com/KratosMultiphysics/Kratos/blob/051536a5c3fa9dcef290bc1c4e3a51f3db65a66c/applications/PoromechanicsApplication/custom_problemtype/Poromechanics_Application.gid/FracturePropagation2D.tcl#L358) [files](https://github.com/KratosMultiphysics/Kratos/blob/051536a5c3fa9dcef290bc1c4e3a51f3db65a66c/applications/PoromechanicsApplication/custom_problemtype/Poromechanics_Application.gid/FracturePropagation3D.tcl#L361). I do not know if there is a relation to the `nurbs_application` or the geometries.

**Comment by oberbichler** [comment]
#2640
