### ISSUE TITLE
There is no time derivative variable in convection_diffusion_settings.h

### ISSUE THREAD

**Issue by apuigferrat** [KratosMultiphysics/Kratos#2487]
We would like to add a new variable (mpDtUnknownVar) in order to create a transient scheme. Can I do it myself or do you want to do it?

**Comment by RiccardoRossi** [comment]
it should be the same as the unknown variable... is that not so?

**Comment by ipouplana** [comment]
No, it is not the same variable. We need to use the unknown and its time derivative for both the current and the previous time steps when updating the unknownvar (here Phi) in the GN11 scheme:
Phi_{n+1} = Phi_{n} + (1.0-Theta)* Dt* DtPhi_{n} + Theta* Dt* DtPhi_{n+1}

**Comment by ipouplana** [comment]
We will try using a specific variable without modifying the convection_diffusion_settings.h
