### ISSUE TITLE
[Core]Unnecessary add_dofs_nodal_process.h?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2490]
What this process does is already done in VariableUtils. So I think we can remove, it is not called in any place of Kratos, not even exported to python.

**Comment by loumalouomega** [comment]
Ping

**Comment by RiccardoRossi** [comment]
which files do you refer to exactly?

**Comment by loumalouomega** [comment]
utilities/variable_utils.h and processes/add_dofs_nodal_process.h

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/variable_utils.h

And

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/add_dofs_nodal_process.h

**Comment by RiccardoRossi** [comment]
ok, the implementation in variable utils is also superior to the process, so take out the process (after verifying by a grep that it is not used anywhere...)

**Comment by loumalouomega** [comment]
I already did, is not even exported to python

**Comment by RiccardoRossi** [comment]
did u merge it? i thought you closed this without merging
