### ISSUE TITLE
How to read nodes from mdpa with different Variables in the SolutionStepsNodalData

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#2494]
Is it possible to customize the read process to have different SolutionStepNodalData in different ModelParts?
Can we have nodes with different SolutionStepsNodalData in the same Modelpart?

**Comment by loumalouomega** [comment]
No right now, when reading nodal data it can read from different step values:

https://github.com/KratosMultiphysics/Kratos/blob/4942bb160ddaf51061c796a1388cd3114476a50c/kratos/sources/model_part_io.cpp#L1532

It just does FasGetSolutionStepValue(X, 0), then just reads the last one. We can do a loop in the buffer size, but that requires the approval of @RiccardoRossi and @pooyan-dadvand

**Comment by josep-m-carbonell** [comment]
@loumalouomega  I think I have not explained correctly, the goal is to have a nodeA with [DISPLACEMENT]  as SolutionStepsNodalData, and a nodeB with [TEMPERATURE]. Note that nodeA does not have the TEMPERATURE variable and nodeB does not have the DISPLACEMENT variable. That means that they not share the same SolutionStepNodalData variables.

**Comment by loumalouomega** [comment]
Ups sorry, I thought a different thing.

**Comment by RiccardoRossi** [comment]
@josep-m-carbonell my best hint is to avoid doing that...

you CAN create modelpart1 and modelpart2, add a different variable list to each, read each of them and then add them to a different modelpart by AddNode. 
However I highly suggest to avoid doing that...

**Comment by pooyan-dadvand** [comment]
The possibility exist but maintaining the integrity of the data structure in this case would be very tricky/risky:

1. Doing clone time step in both modelparts will cause inconsistency in solution step data
2. They should have same buffer size
3. Deleting the model_parts in wrong order would cause memory error at exit
4. ....

IMO, for such a cases It would be better to use to different domain and use constrains to make interaction between them...

**Comment by philbucher** [comment]
I think this is solved
Please reopen if otherwise
