### ISSUE TITLE
Is it possible with GiD i/o, to ask a nodal or elemental flag as output ?

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#2495]
Some elements and nodes are marked by flags usually defining the type or a characteristics, a desirable option would be to post-process some of those characteristics. Defining the FLAGS as nodal or elemental results to be printed as output and post-processed by GiD (as a bool value or in a different layer). Do you think is it possible?

**Comment by loumalouomega** [comment]
Yes it is possible, I implemented myself. It is nodal_flag_output

**Comment by josep-m-carbonell** [comment]
Ok I didn't know that, looking at the gid_output_process.py, I can see the field of **nodal_flags_results** :

        "result_file_configuration": {
            "gidpost_flags": {
                "GiDPostMode": "GiD_PostBinary",
                "WriteDeformedMeshFlag": "WriteUndeformed",
                "WriteConditionsFlag": "WriteElementsOnly",
                "MultiFileFlag": "SingleFile"
            },
            "file_label": "time",
            "output_control_type": "step",
            "output_frequency": 1.0,
            "body_output": true,
            "node_output": false,
            "skin_output": false,
            "plane_output": [],
            "nodal_results": [],
            "nodal_nonhistorical_results": [],
            "nodal_flags_results": [],
            "gauss_point_results": [],
            "additional_list_files": []
        },

Right now for me it is enough I will test it Thank You !, but maybe to have it for elements will be interesting.

**Comment by loumalouomega** [comment]
Maybe we need to discuss how to show that results on the element, the most basic approach is to use the GP.
