### ISSUE TITLE
[Core]Should CreateNewNode also return a Node<3>& (reference)?

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#2502]
Taking a look at this code:
```
ModelPart::NodeType::Pointer ModelPart::CreateNewNode(int Id, double x, double y, double z, VariablesList* pNewVariablesList, ModelPart::IndexType ThisIndex)
{
    KRATOS_TRY
    if (IsSubModelPart())
    {
        NodeType::Pointer p_new_node = mpParentModelPart->CreateNewNode(Id, x, y, z, pNewVariablesList, ThisIndex);
        GetMesh(ThisIndex).AddNode(p_new_node);

        return p_new_node;
    }
```
I wondered how many copies of the shared pointer are there. I count the creation (+1), the copy to p_new_node (+1), the copy to the variable who is receiving this (+1) and the destruction of p_new_node (-1). Maybe c++11 is smarter than that and eliminates some of these. However, for faster performance, in parallel, would it make sense to return a reference? That would limit the _atomic pragmas_ (inside the shared pointer counter) to those strictly necessary. I think the current implementation is necessary as well, though, to play with the node when created.

**Comment by RiccardoRossi** [comment]
I think that the clean solution would be a STD move on exit here

Riccardo

**Comment by RiccardoRossi** [comment]
Just to clarify, I am not against returning a reference...however that
would lead to problems similar to the ones with the ptr_iterators we were
discussing last week

**Comment by maceligueta** [comment]
Added to the @KratosMultiphysics/technical-committee project.

**Comment by oberbichler** [comment]
just out of curiosity: how much time can you save with this change?

**Comment by maceligueta** [comment]
Good question, @oberbichler . I don't know, but I can imagine some cases where the difference might be big.
Suppose you want to create 1 million nodes in a modelpart. You are creating the nodes on the fly and you are basically inventing the Ids and you know the coordinates.
Now, imagine that you don't need the pointer to the nodes because you are happy with the creation and that's all you need.
If you work on a parallel algorithm that does this operation really fast, the creation and destruction of shared pointers will destroying the parallelism (every increase and decrease goes through an atomic section). My impression is that an operation that could be embarrassingly parallel ends up being slow due to the use of shared pointers...

**Comment by maceligueta** [comment]
Definitely, I would like to compare the performance of the existing function and the alternative with std::move (as proposed by @RiccardoRossi ) or the return by reference.

**Comment by philbucher** [comment]
Doesn’t creating Nodes in parallel screw up your memory?
Afaik CreateNewNode allocates new memory which shouldn’t happen in omp...

**Comment by maceligueta** [comment]
Right, maybe I should remove the word 'embarrassingly'. Some sentences in CreateNewPoint should be in Critical sections.

**Comment by oberbichler** [comment]
@maceligueta Interesting. I am not so familiar with the performance issues of parallel code.

The `atomic_add` seems to disappear from the assembly after using `std::move`. Let me know if you have some benchmarks.

**Comment by pooyan-dadvand** [comment]
@maceligueta the `std::shared_ptr` provides the move constructor/assignment and actually all of the copies you are counting would be reduced to only +1 creation....

Edit: adding assignment

**Comment by pooyan-dadvand** [comment]
About returning the reference I would like it but we will face the same problem of iterators as @RiccardoRossi mentioned

**Comment by maceligueta** [comment]
I will close this issue for now until I have some test measuring the time losses, maybe they are just small.
