### ISSUE TITLE
Dam and Poromechanics applications have linking problems

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#2505]
Both of these applications are failing on win (linking problems). They were ok before the release 6.0 so it must have happened in the meantime.

Detailed report here: #2448

@KratosMultiphysics/poromechanics 
@KratosMultiphysics/dam

**Comment by ipouplana** [comment]
Ok, thanks.

I’ll take a look at it ASAP (after lunch)

**Comment by roigcarlo** [comment]
Looking it in more depth, seems that the problem with the poromechanic is that some symbols are not exported.

Dam does not even compile. If you want I can take care of the linking ones, but I have no clue about the others

**Comment by roigcarlo** [comment]
I take care of everything

**Comment by ipouplana** [comment]
Dam is linked to Poro, but I  should see the error to notice what the problems could be ...

**Comment by roigcarlo** [comment]
Don't worry, all under control. Problem was a couple of "or" operators
