### ISSUE TITLE
Issue running Trillinos benchmarks

### ISSUE THREAD

**Issue by vineetmoraybfab** [KratosMultiphysics/Kratos#2513]
Hi I am a newbie and I am trying to run the trillinos benchmarks, but getting some error. Please let me know the correct way to run the application.

Here is what I am running:

mpirun -np 2 runkratos trilinos_benchmarks.py
Traceback (most recent call last):
  File "cantilever_amesos.py", line 45, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_amesos.py", line 45, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_amesos.py", line 45, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_amesos.py", line 45, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_aztec.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_aztec.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_aztec.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_aztec.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_ML.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_ML.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Running Trilinos -- Cantilever_Amesos...
Different amount of benchmark data!
cantilever_amesos.py example FAILED
Running Trilinos -- Cantilever_Aztec...
Different amount of benchmark data!
cantilever_aztec.py example FAILED
Running Trilinos -- Cantilever_ML...
Different amount of benchmark data!
cantilever_ML.py example FAILED
resume of all of the examples for the fluid application :
========== Trilinos Aplication ==========
Trilinos -- Cantilever_Amesos: FAILED
Different amount of benchmark data!

Trilinos -- Cantilever_Aztec: FAILED
Different amount of benchmark data!

Trilinos -- Cantilever_ML (including rotations in null space): FAILED
Different amount of benchmark data!

Traceback (most recent call last):
  File "cantilever_ML.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

Traceback (most recent call last):
  File "cantilever_ML.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:171:unsigned long IO::ReadElementsConnectivities(vector<vector<unsigned long, allocator<unsigned long>>, allocator<vector<unsigned long, allocator<unsigned long>>>> &)
   /home/vineetm/scratch/KFinal/Kratos-5.3/applications/metis_application/custom_processes/metis_partitioning_process.h:332:void MetisPartitioningProcess::Execute()

KRATOS TERMINATED CORRECTLY
Running Trilinos -- Cantilever_Amesos...
Different amount of benchmark data!
cantilever_amesos.py example FAILED
Running Trilinos -- Cantilever_Aztec...
Different amount of benchmark data!
cantilever_aztec.py example FAILED
Running Trilinos -- Cantilever_ML...
Traceback (most recent call last):
  File "trilinos_benchmarks.py", line 80, in <module>
    Run()
  File "trilinos_benchmarks.py", line 59, in Run
    success, Msg = benchmarking.MPIParallelRunBenchmark("cantilever_ML.py", "cantilever.txt")
  File "../../../benchmarking/benchmarking.py", line 423, in MPIParallelRunBenchmark
FileNotFoundError: [Errno 2] No such file or directory: 'BenchTemp.txt'
KRATOS TERMINATED WITH ERROR

**Comment by philbucher** [comment]
Hi @BoNeLeS 
I think the benchmarks are outdated in most Applications 
I recommend trying the tests, i.e. try to run tests/test_TrilinosApplication.py with mpi

**Comment by vineetmoraybfab** [comment]
Hi @philbucher ,
Thank you for the way, can you also let me know how would i benchmark the trilinos application using these tests?
This is the way I am running the application:
mpirun -np 2 runkratos test_TrilinosApplication.py

But I am getting such error:
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.3.0-
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.3.0-
     KRATOS   _____     _ _ _                 
             |_   _| __(_) (_)_ __   ___  ___ 
               | || '__| | | | '_ \ / _ \/ __|
               | || |  | | | | | | | (_) \__ \
               |_||_|  |_|_|_|_| |_|\___/|___/ APPLICATION     
Initializing Kratos MetisApplication... 
Initializing Kratos MetisApplication... 
..xxWorld size: 2
..World size: 2
..World size: 2
..World size: 2
..AZ_check_options: WARNING: Preconditioned matrix may not be symmetric.

AZ_check_options: WARNING: Preconditioned matrix may not be symmetric (due to overlap).


===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 102161 RUNNING AT login.pune.cdac.in
=   EXIT CODE: 11
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
   Intel(R) MPI Library troubleshooting guide:
      https://software.intel.com/node/561764
===================================================================================

Please guide me so that I can tweak some parameters and choose the perfect parameters to make the application scale on my cluster.
Thank a lot!!!

**Comment by philbucher** [comment]
@BoNeLeS 
What exactly do you mean by "benchmarking"?

Regarding your warnings: These ones I also get, I think they don't matter in this context

The error you get I don't know, this could have many reasons. What version of Kratos are you using? Is it self-compiled / precompiled?
Also which version of Trilinos are you using?

**Comment by vineetmoraybfab** [comment]
@philbucher 
I am using Trillinos 12.10.1 and Kratos-5.3.
And for the term benchmarking, what I want to do is..
I want to run this application in parallel on multiple nodes, multiple cores and try to get the least running time for some parameters.
I am not a domain expert, I want to test the application scalability on the cluster that we are having.
Thanks

**Comment by philbucher** [comment]
@BoNeLeS 
This configuration seems fine to me. 
I think you are using the Intel-Compiler, me and also some colleagues had problems with it, not sure if it works in your case.
You could run the mpi-tests in FluidDynamicsApplication or StructuralMechanicsApplication (/tests/<Appname>_mpi.py) to test if a case is running / your installation is working

**Comment by vineetmoraybfab** [comment]
@philbucher 
HI, I am not sure whether I am wrong but I am not able to find any _mpi.py in FluidDynamics or StructuralMechanics. But I found one in ALE, and it seems to be working fine.

Heres is it:

mpirun -np 2 runkratos test_ALEApplication_mpi.py 
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.3.0-
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.3.0-
KRATOS    ___   __   ____             
         / _ | / /  / __/             
        / __ |/ /__/ _/               
       /_/ |_/____/___/  application  
Initializing KratosALEApplication...  
KRATOS    ___   __   ____             
         / _ | / /  / __/             
        / __ |/ /__/ _/               
       /_/ |_/____/___/  application  
Initializing KratosALEApplication...  
Initializing KratosExternalSolversApplication... 
Initializing KratosExternalSolversApplication... 
     KRATOS   _____     _ _ _                 
             |_   _| __(_) (_)_ __   ___  ___ 
               | || '__| | | | '_ \ / _ \/ __|
               | || |  | | | | | | | (_) \__ \
               |_||_|  |_|_|_|_| |_|\___/|___/ APPLICATION     
  [Reading Nodes    :   [Reading Nodes    : 230 nodes read]
  [Reading Elements : 402 elements read] [Type: Element2D3N]
230 nodes read]
  [Reading Elements :   [Total Lines Read : 1370]
402 elements read] [Type: Element2D3N]
  [Total Lines Read : 1370]
..  [Reading Nodes    :   [Reading Nodes    : 297 nodes read]
  [Reading Elements : 297 nodes read]
  [Reading Elements : 257 elements read] [Type: Element2D4N]
  [Total Lines Read : 1236]
257 elements read] [Type: Element2D4N]
  [Total Lines Read : 1236]
..  [Reading Nodes    :   [Reading Nodes    : 317 nodes read]
  [Reading Elements : 317 nodes read]
  [Reading Elements : 1157 elements read] [Type: Element3D4N]
  [Total Lines Read : 3116]
1157 elements read] [Type: Element3D4N]
  [Total Lines Read : 3116]
..  [Reading Nodes    :   [Reading Nodes    : 507 nodes read]
  [Reading Elements : 507 nodes read]
  [Reading Elements : 282 elements read] [Type: Element3D8N]
  [Total Lines Read : 1795]
282 elements read] [Type: Element3D8N]
  [Total Lines Read : 1795]
..  [Reading Nodes    :   [Reading Nodes    : 230 nodes read]
  [Reading Elements : 402 elements read] [Type: Element2D3N]
230 nodes read]
  [Reading Elements :   [Total Lines Read : 1370]
402 elements read] [Type: Element2D3N]
  [Total Lines Read : 1370]
..  [Reading Nodes    :   [Reading Nodes    : 297 nodes read]
  [Reading Elements : 297 nodes read]
  [Reading Elements : 257 elements read] [Type: Element2D4N]
257 elements read] [Type: Element2D4N]
  [Total Lines Read : 1236]
  [Total Lines Read : 1236]
..  [Reading Nodes    :   [Reading Nodes    : 317 nodes read]
  [Reading Elements : 317 nodes read]
  [Reading Elements : 1157 elements read] [Type: Element3D4N]
1157 elements read] [Type: Element3D4N]
  [Total Lines Read : 3116]
  [Total Lines Read : 3116]
..  [Reading Nodes    :   [Reading Nodes    : 507 nodes read]
  [Reading Elements : 507 nodes read]
  [Reading Elements : 282 elements read] [Type: Element3D8N]
  [Total Lines Read : 1795]
282 elements read] [Type: Element3D8N]
  [Total Lines Read : 1795]
..
----------------------------------------------------------------------
Ran 8 tests in 2.420s

OK
Importing    KratosALEApplication
Importing    KratosExternalSolversApplication

----------------------------------------------------------------------
Ran 8 tests in 2.413s

OK
Importing    KratosALEApplication
Importing    KratosExternalSolversApplication

**Comment by vineetmoraybfab** [comment]
@philbucher 
Also, let me know, if I can run this ALE application, how can I increase the domain size/problem size, so that i can check linear time and parallel time.

**Comment by philbucher** [comment]
@BoNeLeS 
I think in the version you are using there are no MPI tests in Fluid and Structure.
Abt the ALE tests I am not sure how up to date those were.

Since you want to check the scaling behavior I recommend you just set up regular cases with different sizes

**Comment by vineetmoraybfab** [comment]
@philbucher
Ok, I will surely try that...

Sorry but I am a total newbie in everything..
I read about the .mdpa files but not getting how to go with that.

Can you please let me know in short..
How and what to specify..
Or suggest me a link to study..
Thanks

**Comment by philbucher** [comment]
@BoNeLeS 
if you are not yet familiar with Kratos then I recommend to create some simple non-mpi examples first. When you are comfortable with this then you could go mpi

**Comment by vineetmoraybfab** [comment]
@philbucher
Ok thanks, I will check it out.
Please close this issue, thanks.
