### ISSUE TITLE
'Vector of matrices' type Kratos variable

### ISSUE THREAD

**Issue by peterjwilson** [KratosMultiphysics/Kratos#252]
Hi All,

I’m looking to output the top and bottom surface stresses of each layer in a composite shell element. Does anyone know of a way to define a Kratos variable which is a vector of matrices? I tried the following, which didn't work:

`KRATOS_CREATE_VARIABLE(std::vector<Matrix>, SHELL_ORTHOTROPIC_LAYER_STRESSES)`

Any help would be much appreciated!

**Comment by loumalouomega** [comment]
Try to use a typedef:

`typedef std::vector<Matrix> MatrixArrayType`

and then:

`KRATOS_CREATE_VARIABLE(MatrixArrayType, SHELL_ORTHOTROPIC_LAYER_STRESSES)`

**Comment by RiccardoRossi** [comment]
@MassimoPetracca 

hi massimo, could you comment on how you were doing output for multiple layers?

**Comment by peterjwilson** [comment]
Thanks for the suggestion @loumalouomega, but it still throws the same error:

![image](https://cloud.githubusercontent.com/assets/23666229/24743073/1ba2226a-1aad-11e7-95e3-e1695fa43987.png)

**Comment by loumalouomega** [comment]
Which is that file variable.h?

**Comment by loumalouomega** [comment]
I created a branch and I will commit now. The problem was that the Variable class can not "print" the info (Stream) if the variable is a vector, then the trick is to consider a pointer to that type:

`KRATOS_DEFINE_VARIABLE( MatrixArrayType*, SHELL_ORTHOTROPIC_LAYER_STRESSES )`

**Comment by loumalouomega** [comment]
The thing is that you will need to consider as a pointer all the time, this means example:

~~~c
MatrixArrayType*  pLayerStresses = pElem->GetValue(SHELL_ORTHOTROPIC_LAYER_STRESSES);
for ( unsigned int i_layer = 0; i_layer < pLayerStresses->size(); ++i_layer )
{
     Matrix = (*pLayerStresses)[i_layer];
 }
~~~

**Comment by jcotela** [comment]
Wouldn't it be better to add the print function for this type of variables? Using a (raw!) pointer creates all kinds of trouble with memory management, since you have to allocate and free the memory yourself.

**Comment by loumalouomega** [comment]
That would be nice, this is trick that I have been using with the contact containers (that used to be std::vectors and now are std::unordered_map), @roigcarlo show me this trick and I wasn't aware of the evil side of the raw pointers

**Comment by loumalouomega** [comment]
@pooyan-dadvand maybe can contribute to this issue

**Comment by loumalouomega** [comment]
@jcotela I am going to try using a make_shared, that way it will be a shared pointer

**Comment by roigcarlo** [comment]
If the problem is the print function I agree that is better to just add it. The problem with shared pointers is that you wont be able to register it as a kratos variable ( Honestly I am not very sure about this ).

If I recall correctly, I suggested the raw pointer because there was not a easy way to use unordered sets as kratos variables

**Comment by loumalouomega** [comment]
@roigcarlo I am having problems with the make_shared, both with std::make_shared and boost::make_shared, trying to make it work

**Comment by loumalouomega** [comment]
@roigcarlo It is with boost::shared_ptr not with make_shared

**Comment by loumalouomega** [comment]
Ok, looks that it compiles, I will change this in my ContactStructuralApplication too, thanks @jcotela . By the way @peterjwilson the example will be:

~~~c
auto  pLayerStresses = pElem->GetValue(SHELL_ORTHOTROPIC_LAYER_STRESSES); // NOTE: I use auto to avoid declare the type everytime
for ( unsigned int i_layer = 0; i_layer < pLayerStresses->size(); ++i_layer )
{
     Matrix = (*pLayerStresses)[i_layer];
 }
~~~

**Comment by peterjwilson** [comment]
Thanks heaps for your help @loumalouomega! Apologies from this Kratos rookie, but where should I add the above code?

**Comment by loumalouomega** [comment]
Wherever you want to use the variable, is just an example. Don't worry I am still very rookie compared with most the main Kratos developers

**Comment by pooyan-dadvand** [comment]
I completely disagree with the use of raw pointer there because it can easy lead to memory leak unless you carefully delete what you allocate. And if somebody wants to use it in a node as a historical variable it will cause a mess in clone time step. (it will copy the pointer pointing to the old data)

An easy solution would be to define the ostream operator `<<` for `std::vector<Matrix>` as suggested by @jcotela. 

However in my opinion instead of using a combination of vector and matrix, it would be better to have a class:
```
class ShellMultiLayerStresses{
    std::vector<Matrix> mLayerStresses;
public:
     Matrix const& GetLayerStress(std::size_t LayerIndex);
     void SetLayerStress(std::size_t LayerIndex, Matrix& NewLayerStress);
};
```

**Comment by RiccardoRossi** [comment]
+1 for Pooyan s suggestion

**Comment by loumalouomega** [comment]
Thanks @pooyan-dadvand , I will change the raw pointers I defined in my application to avoid these undesired problems

**Comment by josep-m-carbonell** [comment]
If you know that these matrices will be always of the same size (2x2 or 3x3)  maybe is better to make matrices bounded ?

(if it will be always the size 3x3):

```
class ShellMultiLayerStresses{
private:
    std::vector<bounded_matrix<double,3,3> > mLayerStresses;
public:
     bounded_matrix<double,3,3> const& GetLayerStress(std::size_t LayerIndex) {...};
     void SetLayerStress(std::size_t LayerIndex, bounded_matrix<double,3,3>& NewLayerStress){ ... };
};
```

**Comment by pooyan-dadvand** [comment]
Thanks @josep-m-carbonell, indeed it is an important improvement!

**Comment by loumalouomega** [comment]
@peterjwilson Did we solved this issue?

**Comment by peterjwilson** [comment]
Yep, closing this.
