### ISSUE TITLE
Process Documentation

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#2522]
Process documentation is missing and should be generated.

From the @KratosMultiphysics/technical-committee we have decided that a good option would be a parser  that goes throug all processes and generates the documentation. 

The documentation for the process should contain:
- Name of the process
- Default parameters
- Description of each parameter if possible.

**Comment by loumalouomega** [comment]
Do you mean Doxygen or something more sophisticated?

**Comment by roigcarlo** [comment]
No, something different, we will take care of this.

**Comment by pooyan-dadvand** [comment]
Essentially a python script which parses the code and looks for processes and their default parameters

**Comment by loumalouomega** [comment]
I understand. The parameters can be parsed and the default variables extracted, but this doesn't guarantee that the description will include all possibilities, and if the name of the parameters are not descriptive enough the resulting documentation will not add any value. 

That's why I asked about Doxygen. Thing, that in my opinion me and @roigcarlo should push a little bit.

**Comment by pooyan-dadvand** [comment]
The problem with doxygen is the fact that the comments get outdated very soon. Using the parser to read the real code will always give documentation base on what is compiling. 

I agree that the options are not there and we should find a way to get them also.

**Comment by maceligueta** [comment]
But I think a brief explanation on what each process does is really needed. Otherwise, you do not know which one you should use when you need them...

**Comment by loumalouomega** [comment]
True, in any case I am still supporting the idea of pushing the Doxygen. 

Besides, I would include some utilities too, many utilities behave similar to a process. 

(Additionally we need to take into account we have cpp processes and python processes)

Additionally, even if I am very pro-automatize things, I not very sure we can make completely automatic this. We can detect the parameters, types and default values. But to detect all the options (except in the case of booleans) we need to define manually the options. This imply define a nomenclature in order be able to define this, and for doing that we can use Doxygen directly, my opinion.

**Comment by roigcarlo** [comment]
I think we are mixing discussions here.

We need a tool to generate documentation for processes, and doxygen is not gonna help there. That tool can be expanded with anything we need ( we are coding it after all ).

I will have a beta version today/tomorrow, then we can discuss which features we want to add over something solid which can be tested.

For the rest of the code we can open another discussion, but for processes we need what we need.

**Comment by roigcarlo** [comment]
Speaking of which, I want through all kratos processes and the following list has no default parameters or are set in a non standard way.

For example HDF5 application uses factory model, but I cannot make my parser undestand design patterns for now. 

```
HDF5Application - single_mesh_temporal_output_process.py
HDF5Application - partitioned_single_mesh_temporal_output_process.py
HDF5Application - partitioned_single_mesh_primal_output_process.py
HDF5Application - single_mesh_primal_output_process.py
HDF5Application - partitioned_multiple_mesh_temporal_output_process.py
HDF5Application - multiple_mesh_temporal_output_process.py
DelaunayMeshingApplication - constant_rotation_process.py
PoromechanicsApplication - apply_normal_load_table_process.py
PoromechanicsApplication - apply_vector_constraint_table_process.py
PoromechanicsApplication - periodic_interface_activation_process.py
PoromechanicsApplication - apply_scalar_constraint_table_process.py
DamApplication - impose_face_heat_flux_process.py
DamApplication - apply_load_vector_dam_table_process.py
DamApplication - impose_nodal_reference_temperature_process.py
DamApplication - impose_heat_source_process.py
DamApplication - impose_chemo_mechanical_aging_process.py
DamApplication - impose_water_loads_condition_process.py
DamApplication - apply_constraint_vector_dam_table_process.py
DamApplication - impose_uniform_temperature_process.py
DamApplication - impose_reservoir_temperature_condition_process.py
DamApplication - apply_load_vector_dam_process.py
DamApplication - impose_temperature_by_device_process.py
DamApplication - impose_thermal_parameters_scalar_value_process.py
DamApplication - impose_nodal_young_modulus_process.py
DamApplication - special_condition_process.py
DamApplication - gid_dam_output_process.py
FluidDynamicsApplication - compute_embedded_drag_process.py
FluidDynamicsApplication - compute_body_fitted_drag_process.py
AdjointFluidApplication - print_drag_process.py
SolidMechanicsApplication - assign_vector_to_conditions_process.py
SolidMechanicsApplication - assign_scalar_to_elements_process.py
SolidMechanicsApplication - assign_scalar_to_conditions_process.py
FluidTransportApplication - apply_vector_constraint_table_process.py
FluidTransportApplication - apply_scalar_constraint_table_process.py
ParticleMechanicsApplication - mpm_gid_output_process.py
IGAStructuralMechanicsApplication - iga_apply_load_process.py
IGAStructuralMechanicsApplication - iga_apply_support_process.py
MeshMovingApplication - impose_ale_rectangle_test_motion_process.py
DEM_application - DEM_inlet_process.py
PfemApplication - assign_inlet_process.py
PfemApplication - remesh_fluid_domains_process.py
PfemFluidDynamicsApplication - assign_inlet_process.py
```

I was able to parse the rest of the processes from all applications correctly. As a example, I can extract the following json from any given process that defines the default parameters:

Example:
**ShallowWaterApplication**
```JSON
[
   {
      "visualization_mesh_process.py":{
         "mesh_id":0,
         "model_part_name":"please_specify_model_part_name"
      }
   },
   {
      "apply_slip_process.py":{
         "model_part_name":"PLEASE_CHOOSE_MODEL_PART_NAME",
         "mesh_id":0
      }
   },
   {
      "set_bathymetry_process.py":{
         "mesh_id":0,
         "model_part_name":"please_specify_model_part_name",
         "interval":[
            0.0,
            1e+30
         ],
         "variable_name":"BATYMETRY",
         "constrained":"False",
         "value":"z"
      }
   },
   {
      "set_initial_water_level_process.py":{
         "mesh_id":0,
         "model_part_name":"please_specify_model_part_name",
         "interval":[
            0.0,
            1e+30
         ],
         "variable_name":"HEIGHT",
         "constrained":"False",
         "value":"1.0"
      }
   }
]
```

**Comment by pooyan-dadvand** [comment]
Nice work @roigcarlo! Creating an understandable document (in github page or wiki) from these jsons is what we have discussed.

Also I want to add that the comments of @loumalouomega about the options and @maceligueta about the brief description are completely correct and we should find a way to consider them:
 -  One idea would be to have a `help` section in Json which has description and also `options` (easier but less effective way)
 - Another option would be to add the options systematically to the Parameters and even validate them. (more long term solution)

**Comment by roigcarlo** [comment]
Agree too

In fact some processes already have the `help` attr, mainly the ones in the Solid app. @loumalouomega has done some work about that in his apps today. I personaly think that it's also a good idea.

It can be easily extracted to generate the doc.

**Comment by loumalouomega** [comment]
Related with:

https://github.com/KratosMultiphysics/Kratos/pull/2583

and 

https://github.com/KratosMultiphysics/Kratos/pull/2584

**Comment by philbucher** [comment]
can this be closed?

**Comment by loumalouomega** [comment]
@roigcarlo Is the responsible

**Comment by roigcarlo** [comment]
Not yet

**Comment by loumalouomega** [comment]
@roigcarlo what is missing?

**Comment by roigcarlo** [comment]
A place to upload, the description string for the processes, etc... The parser works, but it assumes that process have some information most of them lack. 
I can upload the script to generate the info...

**Comment by roigcarlo** [comment]
I am closing this as there are more novel PR relating doc
