### ISSUE TITLE
No correct *post.bin file written

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#2529]
I experienced that in all my simulations the *.post.bin file is not written correctly. This means the file is created, but during and in the end of the simulation no data is added to the file. As an example I directly run a problem created from the GID problemtype with the current master branch.

Has anyone made a similar experience?

**Comment by loumalouomega** [comment]
Can you attach the problem in question?

**Comment by philbucher** [comment]
I think I found the problem (variable not added to SolutionStepData), closing this for now
@AndreasWinterstein we can speak tmr
