### ISSUE TITLE
False positive box intersection in Tetrahedra3D4

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#253]
In Tetrahedra the method: 
`HasIntersection(const Point<3, double>& rLowPoint, const Point<3, double>& rHighPoint)`

always returns true.

I'm not sure if it is used.

**Comment by loumalouomega** [comment]
@pooyan-dadvand Did we solved this issue?

**Comment by pooyan-dadvand** [comment]
Not yet....

**Comment by RiccardoRossi** [comment]
Is this solved?

**Comment by pooyan-dadvand** [comment]
Just pushed in pull request #886
