### ISSUE TITLE
DamApplication Examples Please

### ISSUE THREAD

**Issue by UPC-EnricBonet** [KratosMultiphysics/Kratos#2539]
I'm sorry but I was looking for DamApplication examples so I opened README.md but the link is inside of document doesnt work. Can you share with me some examples? Thanks a lot!!!

Dam Examples
The test examples of dam application have been moved to specific repository.

Please click here to be redirected.

**Comment by ipouplana** [comment]
Hi @KratosCSIC , If you want something from the DamApplication team, remember to add @KratosMultiphysics/dam in your messages so that they notice them.

Regarding your request, DamApplication examples were moved to a private repository, but I guess that CIMNE Madrid team can send you one to test the application.

**Comment by UPC-EnricBonet** [comment]
Ok, thanks Ignasi, so How do I contact with CIMNE Madrid team? 
 
https://github.com/orgs/KratosMultiphysics/teams/dam

**Comment by ipouplana** [comment]
I'll try to contact them. If we need to send you something privately we can do it via enriquebonetgil@hotmail.com, right?

**Comment by UPC-EnricBonet** [comment]
Yes, thanks. I'm member of the FLUMEN, I work with Ernest Bladé and Martí Sánchez in the UPC. I  have been involved with CIMNE previously.

**Comment by ipouplana** [comment]
Ok, before I wrote a mail to them, but they are not answering... 
In any case, next week I have a meeting with them so I can ask them again for an example.

**Comment by UPC-EnricBonet** [comment]
Thanks Ignasi.

**Comment by ipouplana** [comment]
I just talked to them and they'll contact you via mail. 
I close this issue.
