### ISSUE TITLE
Improvement required in skin_detection_process

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#2540]
Good morning,

I've been using this process in my Fem2Dem App and I got an error when detecting the skin nodes after some of the elements/nodes have been deleted from the model_part...

The FemDem removes elements and nodes with the TO_ERASE flag and, when some nodes are erased, this error is returned:

skin_detection_process.Execute()
RuntimeError: Error:  node index not found: 1377.

in kratos/includes/mesh.h:266:Mesh<class Node<3,class Dof >,class Properties,class Element,class Condition>::pGetNode        

kratos/processes/skin_detection_process.cpp:293:SkinDetectionProcess<2>::Execute

It's like somehow he is looking after this removed node...

Thank you in advance.

@loumalouomega

**Comment by loumalouomega** [comment]
I don't understand well, PM

**Comment by loumalouomega** [comment]
Can we close this?
