### ISSUE TITLE
[Core][IMPORTANT FOR EVERYONE] New Model branch

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2543]
@KratosMultiphysics/all (I created a team with everyone to make easier to get the attention of everyone)

@RiccardoRossi is currently working on the PR #2417, which involves the change of how the Model works. This is a very important change that will affect everyone, and we need to everyone to be concerned about the change to avoid problems. The idea is to proceed as in the boost->pybind migration. Everyone does  a PR directly to that branch "model_v3" instead of the master, and at the end that branch will be merged with the master.

The new design of the model unfortunately  **is backward incompatible** in that it hides the modelpart. **Modelpart can now ONLY be created through the model interface**.

**Help is definitely needed to convert other applications.**

The changes essentially consists in substitutiting the calls to the modelpart constructor to

       current_model.CreateModelPart(name, buffer_size)

This implies that current_model must be available in order to create the modelpart. If it is not so, the current model can be retrieved from an existing modelpart by doing

     Model& current_model = existing_model_part.GetOwnerModel()

A utility function is created for modelparts that only need to exist locally to a file. Such utility guarantees that upong destruction, the modelpart is automatically removed.

@RiccardoRossi I just copy pasted your last message, which is this utility?

**Comment by RiccardoRossi** [comment]
the utikity is called for now (it is very ok for me to improve the name)

kratos/containers/unique_modelpart_pointer_wrapper.h

however before using it extensiveli i woild like @msandre to take a look
into it

**Comment by pooyan-dadvand** [comment]
Just to add that this won't affect the creation of the SubModelPart and only the API change is in creating a root modelpart

**Comment by pooyan-dadvand** [comment]
Just to add that this won't affect the creation of the SubModelPart and only the API change is in creating a root modelpart

**Comment by loumalouomega** [comment]
As the model_v3 will be merged soon I will close this to reduce the number of issues
