### ISSUE TITLE
How to run ALE application tests

### ISSUE THREAD

**Issue by vineetmoraybfab** [KratosMultiphysics/Kratos#2555]
Hi, I am using Kratos-5.3, Trilinos 12.10.1 and trying to run the ALE's 

"mpi_test_laplacian_mesh_motion_3d.py" (located in Kratos-5.3/applications/ALEapplication/tests/)  
test by increasing the problem size in 

"mpi_rectangle_3D8N_test_parameters.json" (located in Kratos-5.3/applications/ALEapplication/tests/test_laplacian_mesh_motion_3d/)

But it is observed that, when i run using mpi, (e.x. mpirun -hosts h1,h2 runkratos mpi_test_laplacian_mesh_motion_3d.py) it takes more time than that run without mpi.

Please let me know if I can run the test using mpi or not. If yes then how to to that.

**Comment by philbucher** [comment]
In this version the mpi tests in the ale-application as well as the laplacian-mesh-solver itself are broken
So unfortunately you cannot run these tests in mpi

**Comment by vineetmoraybfab** [comment]
@philbucher 
Can you suggest any application where mpi tests are working good ?
Or maybe a recompile for a new Kratos version?

**Comment by philbucher** [comment]
Afaik in 5.3 there were no working mpi tests
In the current version FluidDynamics and StructuralMechanics have mpi tests, but those are designed to only work with 2 processes.

If you want to test scaling I think there is nothing prepared, you should set up your own problem

**Comment by vineetmoraybfab** [comment]
@philbucher
Thanks a lot for your help, I will create new testes and recompile with the latest Kratos version..
You may close this issue. Thanks
