### ISSUE TITLE
Error in distance function

### ISSUE THREAD

**Issue by juliobarna** [KratosMultiphysics/Kratos#257]
@pooyan-dadvand @roigcarlo 
![distance](https://cloud.githubusercontent.com/assets/26117236/24754507/08b7ee3a-1ad7-11e7-814d-b5c02fc87dac.png)

**Comment by pooyan-dadvand** [comment]
@juliobarna would you please explain it a little, (at least saying what should be the correct behaviour)  I have opened the test you have send me by email and it was another problem.

**Comment by juliobarna** [comment]
Hi Pooyan, in this example i have 2 meshes: polymer and air. I have attached an image to have an idea about the problem. In the previus message the result represent a horizontal cut of the air domain. We expect in this result (part in blue colour) distance value for the polymer d<0 while for the air d>0. However distance for the polymer as well as the air is positive. Something is wrong.
By the way, I have sent the example.
Keep in touch 

![1](https://cloud.githubusercontent.com/assets/26117236/24758686/611c5852-1ae3-11e7-8cfb-4e2c13f36ca9.png)

**Comment by pooyan-dadvand** [comment]
And the first figure is a cross section of the bar or the entire model?

**Comment by juliobarna** [comment]
Hi, it is of the air domain(it is not include the polymer). I sent other figure to your email including the 2 meses.
REgards

**Comment by pooyan-dadvand** [comment]
@juliobarna I am working on a new (improved version) of the distance calculation process but it is taking more than I was expecting. So I would make you a hotfix on it.

**Comment by pooyan-dadvand** [comment]
@juliobarna would you please check the branch issue-257 to see if it fixes your problem?

**Comment by juliobarna** [comment]
It is working however I would like to try it in a dynamic problem @pooyan-dadvand

**Comment by pooyan-dadvand** [comment]
Then you should rerun the process in each time step or convect the distance function as your convenient.

**Comment by pooyan-dadvand** [comment]
@juliobarna Can we close this issue?
