### ISSUE TITLE
[StructuralMechanicsApplication] Help with new CL

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2574]
@KratosMultiphysics/structural-mechanics 

The new CL are here, but we need your help. Right now, only for small deformations and only for 3D. We would appreciate if you can help us with the following:

- [ ] Testing the already existing laws and detecting bugs
- [ ] Thinking things to improve them

@AlejandroCornejo and I have started a new branch called structural/feature-advanced-cl. In this branch we will do the future developments related with CL in the StructuralMechanicsApplication. The following developments are pending (everything does not necessarily need to be accomplished in this branch):

- [ ] Adding 2D plane strain laws (plane stress is more complicated, so no included here)
- [ ] Adding viscoplasticity laws, and some sort of mechanism to combine in serial/parallel certain laws
- [ ] Start the development of the large deformation laws
- [ ] Correcting bugs

**Comment by RiccardoRossi** [comment]
@loumalouomega @AlejandroCornejo i think that if you want to go ahead on mixing theory we need to advance on the discussion #2414 
also i would like @frastellini to participate in the discussion since he is our biggest expert on that specific subject

**Comment by loumalouomega** [comment]
Ok

**Comment by frastellini** [comment]
I will be happy to participate in the discussion regarding composites materials handling (#2414 ).
Please, pay a look to my comment to issue #2471 about the possible use of the section concept.

**Comment by loumalouomega** [comment]
I will close this, we did more or less the objectives

**Comment by frastellini** [comment]
Thank you! Good work!
