### ISSUE TITLE
[Travis] DEM tests often take too long

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2575]
I noticed several times in the last weeks that Travis fails bcs the tests are taking too long
~~~
Running tests for DEMApplication
/home/travis/build/KratosMultiphysics/Kratos/applications//DEM_application/tests/test_DEMApplication.py
[Warning]: Application has been found in "DEM_application" directory but it was expected in "DEMApplication". Please check the naming convention.
...
ABORT: Tests for DEMApplication took to long. Process Killed.
~~~

@maceligueta @roigcarlo can you please have a look?

**Comment by maceligueta** [comment]
In my computer, with Kratos in FullDebug mode, the DEM tests take between 13 seconds (1 thread) and 25 seconds (8 threads). 
However, as I stated in a previous issue (#1807 ) I've sometimes noticed sudden increases in the CPU time requirements when running small cases in parallel.

**Comment by philbucher** [comment]
@maceligueta thanks for the info
I will close this issue then and just restart travis if it happens
