### ISSUE TITLE
Compiling errors in SolidMechanincs & KratosMeshingApp [WINDOWS]

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#2578]
Good afetrnoon,

I've been compiling the SolidMechanicsApplication this morning and I got a lot of compilation errors such as:

Error	LNK2001	símbolo externo "public: static class Kratos::Flags const Kratos::SolverLocalFlags::INITIALIZED" (?INITIALIZED@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	

or 

Error	LNK2001	símbolo externo "public: static class Kratos::Flags const Kratos::SolverLocalFlags::INCREMENTAL_SOLUTION" (?INCREMENTAL_SOLUTION@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	

In addition, there are a lot of errors regarding the MeshingApplication in the file "trigen_droplet_refine.h".
"add_meshers_to_pyhton.cpp" and "trigen_cdt.h"...

**Comment by josep-m-carbonell** [comment]
These two flags only, ok, I will take a look, thank you @AlejandroCornejo !

**Comment by maceligueta** [comment]
Maybe we should add these apps to Appveyor. @roigcarlo

**Comment by AlejandroCornejo** [comment]
here I Ieave you the list of flags @josep-m-carbonell: 
INITIALIZED" (?INITIALIZED@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
CONVERGED" (?CONVERGED@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
DOFS_INITIALIZED" (?DOFS_INITIALIZED@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
ELEMENTS_INITIALIZED" (?ELEMENTS_INITIALIZED@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
CONDITIONS_INITIALIZED" (?CONDITIONS_INITIALIZED@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
MOVE_MESH" (?MOVE_MESH@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
UPDATE_VARIABLES" (?UPDATE_VARIABLES@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
REFORM_DOFS" (?REFORM_DOFS@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
INCREMENTAL_SOLUTION" (?INCREMENTAL_SOLUTION@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
COMPUTE_REACTIONS" (?COMPUTE_REACTIONS@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
CONSTANT_SYSTEM_MATRIX" (?CONSTANT_SYSTEM_MATRIX@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
RAYLEIGH_DAMPING" (?RAYLEIGH_DAMPING@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
IMPLEX" (?IMPLEX@SolverLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
INITIALIZED" (?INITIALIZED@CriterionLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
INCREMENTAL" (?INCREMENTAL@CriterionLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
CONVERGED" (?CONVERGED@CriterionLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
AND" (?AND@CriterionLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
OR" (?OR@CriterionLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
UPDATE_RHS" (?UPDATE_RHS@CriterionLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
SUPPLIED_DOF" (?SUPPLIED_DOF@CriterionLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1	
PREDICT_PRIMARY_VARIABLE" (?PREDICT_PRIMARY_VARIABLE@TimeIntegrationLocalFlags@Kratos@@2VFlags@2@B) sin resolver	KratosSolidMechanicsApplication	D:\KratosMasterBranch\cmake_build\applications\SolidMechanicsApplication\add_custom_strategies_to_python.obj	1
