### ISSUE TITLE
[core] ModelPartIO writes file with consumed time always

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#2586]
Can we put a flag in the constructor which controls if the Timer prints or does not print?
I think that in 99% of the cases nobody looks at these files with the consumed time. It can be activated by the interested user.

**Comment by loumalouomega** [comment]
Additionally I think we should take a look is in adding the possibility to just write the mesh. Writing nodal values is very time consuming and sometimes reading gives an error because the variables has not been added

**Comment by loumalouomega** [comment]
Additionally we should define how to add the new constraints to the ModelPartIO

**Comment by philbucher** [comment]
+++++++++1 for this suggestion @maceligueta !!!
I would set the default to false

**Comment by loumalouomega** [comment]
The current flags IO are: 

~~~cpp
    KRATOS_DEFINE_LOCAL_FLAG( READ );
    KRATOS_DEFINE_LOCAL_FLAG( WRITE );
    KRATOS_DEFINE_LOCAL_FLAG( APPEND );
    KRATOS_DEFINE_LOCAL_FLAG( IGNORE_VARIABLES_ERROR );
~~~

We can still define many flags (unil 32 if I' not wrong)

**Comment by pooyan-dadvand** [comment]
My design would be to migrate the timer to logger and add Start stop method to it. So we can have the log message for each section (with levels) and also give the time elapsed in each pass. So there would be no time file if you don't put a timer_output in your logger system.

Meanwhile I agree with optional write of the time file.
