### ISSUE TITLE
GiD i/o prints only elements and conditions with flag ACTIVE true

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#2594]
This is a little bit hidden, but you can not print non active elements/conditions and the corresponding flag to see which are active or not.

**Comment by loumalouomega** [comment]
What do you mean?, usually if a element or condition is not active should not matter the rest

**Comment by josep-m-carbonell** [comment]
Well, ACTIVE is used to label if a condition or element must be considered in the calculation. However, maybe it is an element that you want to visualize in the output, because it is a wall or is a part or the domain that you only have deactivated to avoid conditioning problems (sliver and others), but you want to see them (in order to know if they exist and what have been considered inactive).

**Comment by loumalouomega** [comment]
The consideration of ACTIVE for GP was something that @jcotela added time ago, I don't remember the reason, I remember is was important...

**Comment by jcotela** [comment]
Hi @loumalouomega I'm not sure if this is what you are referring to, but I remember I had some issues with printing data on non-active elements, since non-active elements may be uninitialized (I think the strategy does not process them in the same way as standard elements) and this was giving me some memory errors. However, this should not be an issue when printing flag results. Maybe we can skip the check in the new functions you implemented?

**Comment by josep-m-carbonell** [comment]
Do you think that these NOT_ACTIVE elements can be printed without any GP result (to avoid memory errors, because no initialization is done) ?. Furthermore,  another flag to hide elements in GiD output can be used in order to give a unique meaning to ACTIVE.

**Comment by jcotela** [comment]
@josep-m-carbonell I think you could print the NOT_ACTIVE elements carefully, but I don't remember the code well enough, I'd have to check. Worst case, I would just suggest printing everything and having the elements be aware of the flag (so they return 0 if NOT_ACTIVE), but this would be a disruptive change.

**Comment by loumalouomega** [comment]
I just checked and for the flag the check ACTIVE is not done

https://github.com/KratosMultiphysics/Kratos/blob/23294d189df6a593cf107e7eb2c705c70b30b93e/kratos/includes/gid_gauss_point_container.h#L99

It is done for the integration values

**Comment by jcotela** [comment]
Then I'm not sure what is going on, I guess it is the elements themselves which are missing (so we tell GiD about the results on gauss points but not where these gauss points should be). @josep-m-carbonell do you have a small example we could use to debug this?

**Comment by philbucher** [comment]
Is this still active?

**Comment by josep-m-carbonell** [comment]
Yes

**Comment by josep-m-carbonell** [comment]
Closed due to inactivity. Reopen if needed
