### ISSUE TITLE
[Core][GiDIO] Not useful loop

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2595]
https://github.com/KratosMultiphysics/Kratos/blob/23294d189df6a593cf107e7eb2c705c70b30b93e/kratos/includes/gid_io.h#L1406

@KratosMultiphysics/technical-committee This loop is doing nothing except expending time :(

**Comment by maceligueta** [comment]
And this line is making a copy?
https://github.com/KratosMultiphysics/Kratos/blob/23294d189df6a593cf107e7eb2c705c70b30b93e/kratos/includes/gid_io.h#L1403

**Comment by loumalouomega** [comment]
Looks like

**Comment by pooyan-dadvand** [comment]
I'm not familiar with this code but seems to be a copy paste error. Meanwhile where are the code for writing coordinates?

**Comment by loumalouomega** [comment]
In WriteMesh()

**Comment by philbucher** [comment]
is this solved?

**Comment by loumalouomega** [comment]
I haven't do a thing, so I think so
