### ISSUE TITLE
LockObject using omp_test_lock instead of omp_set_lock

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#2605]
The LockObject class does not have a way to check if the lock has been set. Can we use omp_test_lock and return a bool if the lock is successfully acquired ? 
Currently omp_set_lock is used which does not let the user know if a successful lock is obtained by the thread or not. 

https://github.com/KratosMultiphysics/Kratos/blob/b96b14a04ddd0747e9847ecb9f8a306cfe47cacd/kratos/includes/lock_object.h#L126

**Comment by RiccardoRossi** [comment]
@adityaghantasala the usage is actually simpler:

       lock.Set() //no one can go past this

        ... do work ...

        lock.UnSet()

no need for any if (the if is inside the lock, which i believe is implemented as a spinock)

**Comment by adityaghantasala** [comment]
ah ok .. perfect then !
