### ISSUE TITLE
Release 6.1 backward incompatible changes

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#2616]
This issue is to decide which backward incompatible changes are priority in this release. A tentative list is:

- Model
- AMatrix
- MPI core

Any comment or addition to the list would be discussed here

**Comment by loumalouomega** [comment]
To my knowledge the one that is in a more advanced development state is the Model. Am I right?

**Comment by loumalouomega** [comment]
Additionally, don't forget about #2542

**Comment by philbucher** [comment]
Model quite urgently requires https://github.com/KratosMultiphysics/GiDInterface/issues/419, ping @jginternational

**Comment by pooyan-dadvand** [comment]
Seems there are no additions to this list. So I close it. Please reopen it if is necessary
