### ISSUE TITLE
Is there the cable or the pile setting in the Kratos when do the tunnel excavate?

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#2622]
I found that a team from Rhur University Bochum,they had added the pile in the engineering based on the ekate.In the Kratos,is there the function to simulate the cable or the pile to do the support in the excavate?
Best regards.

**Comment by fengzekang** [comment]
@loumalouomega Do you know this setting?Can we add the cable or the pile in the Kratos?
Best regards

**Comment by loumalouomega** [comment]
This element I think has been developed by @vryy, not sure at all. If that is the case, the formulation is not public yet, and I don't know if there are plans to publish it in the near future.
