### ISSUE TITLE
Cannot import MeshingApplication

### ISSUE THREAD

**Issue by inigolcanalejo** [KratosMultiphysics/Kratos#2646]
I cannot import the meshing application. I get the following output:

Traceback (most recent call last):
  File "MainKratos.py", line 6, in <module>
    from KratosMultiphysics.MeshingApplication import *
  File "/home/inigo/software/kratosMaster03/Kratos/KratosMultiphysics/MeshingApplication.py", line 2, in <module>
    from KratosMeshingApplication import *
ImportError: dynamic module does not define module export function (PyInit_KratosMeshingApplication)

Does someone have the same problem or knows a solution?

**Comment by loumalouomega** [comment]
Try to update and recompile, @jcotela and I have solved today a compilation
error. (if not try to remove old compiled libraries)

Sorry for the inconvenience

**Comment by inigolcanalejo** [comment]
After updating and recompiling, now it works. Thank you Vicente!
