### ISSUE TITLE
Eigenfrequency optimization of shells is not working for problematic settings with model part name

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#2671]
Tested it with the following example for a simple steepest descent case: [05_Constrained_Shell_Opt.zip](https://github.com/KratosMultiphysics/Kratos/files/2282329/05_Constrained_Shell_Opt.zip)

The eigenfrequency for the beam example still works though. Once fixed, we should include also an eigenfrequency test for shells.

**Comment by loumalouomega** [comment]
Do we have tests to detect when this is broken?

**Comment by dbaumgaertner** [comment]
@loumalouomega No net yet but will follow.

Update: The bug appears when the "model_part_name" in the primal settings does not correspond to the "optimization_model_part_name" in the optimization settings. Note that in the latter case, the name stands for both the name of the input file as well as the name of the model part. In contrast to that, the input file name and the model part name are separately specified in the primal settings. --> ShapeOptApp should be adjusted to the Kratos standard of distinguishing two settings.

**Comment by armingeiser** [comment]
In the meantime i have included a check in the response function, that makes sure the settings are correct.
#2677

**Comment by armingeiser** [comment]
New PR for the check #2684

**Comment by philbucher** [comment]
I think this can be closed now?
