### ISSUE TITLE
Is it possible to compile Kratos on Windows without VS?

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/Kratos#2681]
@roigcarlo 

Hi,

I am wondering if there is a simple way to compile Kratos on Windows without VS: for example by means of Mingw and use VS code for editing/debugging the code.

Thanks!

**Comment by oberbichler** [comment]
Hi!
I strongly recommend to use the **compiler** of *Visual Studio*! The easiest way to install the compiler is with Visual Studio. But that does not mean that you must use Visual Studio as your IDE.

I also use *VS Code* and it works very well with the VS compiler (specially for debugging).

**Comment by roigcarlo** [comment]
Yes, as @oberbichler said, as long as you use MSVC you will be fine. I think that recently @pooyan-dadvand has even managed to compile with clang, but I am not aware on how to do it

**Comment by Vahid-Galavi** [comment]
Thanks for your quick replies!
