### ISSUE TITLE
[FSIApplication] Name of the application

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2682]
When running the whole test suite I got the following error:

~~~sh
[Warning]: Application has been found in "convection_diffusion_application" directory but it was expected in "ConvectionDiffusionApplication". Please check the naming convention.
~~~

Should we change the name of the application to follow the convention?

**Comment by loumalouomega** [comment]
Same for the FSIApplication:

~~~sh
[Warning]: Application has been found in "FSIapplication" directory but it was expected in "FSIApplication". Please check the naming convention.
~~~

**Comment by rubenzorrilla** [comment]
We can change it, but for the moment, I can live with that.

**Comment by loumalouomega** [comment]
Ok

**Comment by philbucher** [comment]
Guess the same applies to trilinos and metis

**Comment by loumalouomega** [comment]
Like there are no tests there I haven't checked

**Comment by philbucher** [comment]
Just for the record, I am updating metis and trilinos to the correct names in #3773 and #3772 
This is planned to be merged after the release, maybe it would be a good idea to also update the other apps then

**Comment by loumalouomega** [comment]
FSI is still with the name not udpated, should be FSIApplication

**Comment by rubenzorrilla** [comment]
I'll take care of the FSI as well

**Comment by loumalouomega** [comment]
Okidoki, finally that inner voice in me will stop
