### ISSUE TITLE
Adding HDF5Application to nightly tests

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2687]
The HDF5Application should be added to the nightly tests, first of all to test if the app itself works and second, bcs more other apps start to depend on it (see #2686 ).
The tricky thing (the stuff I don't know :) ) is to add the installation of the hdf-libs, as described in the [Application-README(https://github.com/KratosMultiphysics/Kratos/tree/master/applications/HDF5Application)]
@roigcarlo can you please help with this?

**Comment by roigcarlo** [comment]
Sure, I take care.

I understand you need the `libhdf5-openmpi-dev` variant right?

**Comment by philbucher** [comment]
@msandre please correct me if I am wrong, but I think the `libhdf5-dev` should be installed, this is for non-mpi
the `libhdf5-openmpi-dev` is needed for the mpi-features, but mpi is not tested in the nightly tests so it is not needed

Thanks @roigcarlo !

**Comment by roigcarlo** [comment]
Ok!
