### ISSUE TITLE
Can HDF5 be added to the nightly build / tests?

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#2689]
Hi @roigcarlo, I think you have set up the nightly testing for kratos. I wanted to ask if it is possible to include HDF5. The HDF5Application does not change much, but there is an increasing number of adjoint tests in FluidDynamicsApplication and StructuralMechanicsApplication which depend on it. If HDF5 is not compiled, then these tests are skipped which generally leads to a time delay before failures are detected. I'm asking since there is a recent issue in #2686. If you give me the specs of your test server I could try to help with the installation of hdf5 lib. It may be as simple as using the system's package manager. If you prefer, we can look into setting up a second test server here, but this would probably not be so nicely integrated.

Thanks

**Comment by philbucher** [comment]
I was faster :D
#2687 & #2688

**Comment by msandre** [comment]
ok thanks!
