### ISSUE TITLE
Is the "label" in KRATOS_INFO("label") necessary?

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#2708]
Not only in KRATOS_INFO, in almost all macros. 
In some cases, Iike in KRATOS_ERROR, the "label " message is not needed.
Which is the reason to supply this label in some of the logger messages?,  and the other thing, why the message of the label is modified introducing a ": " after the label message when it is written down?

std::cout<<" This is the message I want as output "<<std::endl;
output:
This is the message I want as output
But If I write it using the macro:
KRATOS_INFO(" ")<<" This is the message I want as output "<<std::endl;
output:
: This is the message I want as output
KRATOS_INFO(" This is the message I want as output ")<<std::endl;
output:
This is the message I want as output: 

Is not easier to use the macros for assign a severity level without using any extra label?
If there is a compelling reason for it, then it would be good to know. 
My opinion is that it is a little bit cumbersome.

**Comment by loumalouomega** [comment]
If the label is not used is like using std::cout

**Comment by loumalouomega** [comment]
The label is intended to be used in a table output properly formated

**Comment by josep-m-carbonell** [comment]
This does not compile:
KRATOS_INFO<<" This is the message I want as output "<<std::endl;

**Comment by loumalouomega** [comment]
KRATOS_INFO("") is the minimum label, but nothing is printed as label

**Comment by loumalouomega** [comment]
Well, and technically is not the same as std::cout, for example if only warning are shown, the KRATOS_INFO("") will be not shown

**Comment by loumalouomega** [comment]
in any case @pooyan-dadvand

**Comment by josep-m-carbonell** [comment]
are you sure that ":" is not printed with KRATOS_INFO("") ?

"The label is intended to be used in a table output properly formatted" ...  is it feasible if the output data can be everything? ...  maybe this format can be optional  and not condition all messages with this label. (only  my opinion)

**Comment by loumalouomega** [comment]
We use KRATOS_INFO("") a lot when for example printing after import:

https://github.com/KratosMultiphysics/Kratos/blob/41f87618ace4211dd58ead5fba297e35b9468f05/kratos/sources/kernel.cpp#L21

**Comment by josep-m-carbonell** [comment]
In my opinion  here "KRATOS_INFO("") << " |  /           |             " << std::endl;"   the ("") is totally innecessary, and I don't know when you would like to have this message in a table type format.

**Comment by loumalouomega** [comment]
In this case there is no table, the label concept was added in order to consider the table in the future

**Comment by josep-m-carbonell** [comment]
Then, the answer to the question formulated in the issue is "no". The cumbersome (my opinion) label field is only there for a hypothetical table output that will be useful (if it is finally done) for some particular part of the code that would like to have this type of output.
Do you think is it possible to have both options, with and without the label?

**Comment by loumalouomega** [comment]
I think it is possible, but the design of the logger is from @pooyan-dadvand

**Comment by loumalouomega** [comment]
I was only explaining the origin of the label, and it was "my fault", because I planned to create this table logger, but I don't find the moment to do it

**Comment by pooyan-dadvand** [comment]
The label is not only for the table output. You can filter your output only to labels you want. For example you can write done the messages with Solver as label in your .solver output file and the ones with SolidMechanic to your generic output. 

In case that the label is an empty string it is completely omitted in the normal logger output but you may change this behavior in your logger output. 

So answering to your question, yes is necessary to give more possibility to create better output. Maybe we can create another set of macros which put some the label automatically like KRATOS_SOLVER_INFO etc.... But I need to have more use cases to see which ones.

**Comment by loumalouomega** [comment]
@pooyan-dadvand I was explaining the origin of the label, not saying it  is used for that, sorry for the confusion

**Comment by josep-m-carbonell** [comment]
@pooyan-dadvand  thank you for the explanation. However, do you think is it possible to create a macro without ("") for the cases where no label is inserted ?:
KRATOS_INFO<<" message"<<std::endl;  
instead of 
KRATOS_INFO("")<<" message "<<std::endl;

**Comment by pooyan-dadvand** [comment]
Unfortunately macros cannot be overridden in C++.... 

And writing without a label is not encourage because disables the filtering mechanism. I would use it just for cases like logo of Kratos or other similar situations where we want to have it written as it is.

**Comment by philbucher** [comment]
I think this is solved
Please reopen if otherwise
