### ISSUE TITLE
ExternalSolversApplication required in linear_solver_factory

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#2714]
@RiccardoRossi @pooyan-dadvand @rubenzorrilla 

I have just seen that now the linear_solver_factory checks if the ExternalSolversApplication is imported and throws an error if it is not. However some of the solvers there (like AMGCL) do not need this application. Besides, I know a certain company which cannot use this application at all... ;)

Could this be removed, or at least, that the application check is only done when it is necessary? 

Thanks!

**Comment by RiccardoRossi** [comment]
@ddiezrod the error should be thrown only if the solver in question requires the application. can u do the corresponding PR?

**Comment by philbucher** [comment]
I recommend using the `new_linear_solver_factory`, which does not always import this
eventually fixed in #651

**Comment by ddiezrod** [comment]
@philbucher but new_linear_solver_factory does not have the check. I think it is better to do it as @RiccardoRossi says and do the CheckRegisteredApplication inside the options that need it.

**Comment by philbucher** [comment]
We were discussing to do add the check inside the options a while ago with @armingeiser and decided to NOT include it for the case of linear solvers.
The main reason was that if one uses a solver that is just located in a different application (e.g. the EigenSolversApplication) then the user has to know details of the implementation that are Kratos-internal

I.e. only for switching a linear solver one would have to import a different application, which seemed quite inconvenient for us which we wanted to avoid esp for industrial partners

Just our opinion though

**Comment by armingeiser** [comment]
Having that CheckRegisteredApplication before the import of the relevant application inside the if conditions for the different solver types would also work in the 'new_linear_solver_factory'.
Does this check give more information than the import error if the application is not available?

Besides that, i don't really understand whats the difference between "new" and "old" solver factory...

**Comment by ddiezrod** [comment]
@armingeiser To be honest, I do not see very much difference between the check and the import error. The check tells you which is the main_file that is missing the import, but I think thats all.

**Comment by ddiezrod** [comment]
Solved in #2717
