### ISSUE TITLE
[StructuralMechanics] Problem with TestTestSPRErrorProcess2

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2715]
On my machine the test fails, even though it works in other machines and in Travis:
~~~
    TestTestSPRErrorProcess2 Failed with message: 
        Error: Check failed because (0.122409 - process_info[ERROR_OVERALL])/0.122409 is greater than 1.0e-5
in /home/philippb/software/Kratos_prod/applications/StructuralMechanicsApplication/tests/cpp_tests/test_spr_error_process.cpp:286:virtual void Testing::TestTestSPRErrorProcess2::TestFunction()
~~~

see #2612 and #2712

**Comment by loumalouomega** [comment]
@philbucher can you print the exact value is giving to you?, maybe is someting like 1.0-4 and we can live with that

**Comment by philbucher** [comment]
test is working in FullDebug xD

@loumalouomega there is a misleading indentation [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/tests/cpp_tests/test_spr_error_process.cpp#L271-L275) and [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/tests/cpp_tests/test_spr_error_process.cpp#L223-L227), maybe that has sth to do with it

**Comment by loumalouomega** [comment]
I remember there was a warning, but I completely forgot

Besides the tests work in release in my machine
