### ISSUE TITLE
Tests are failing with python 3.7.0

### ISSUE THREAD

**Issue by sunethwarna** [KratosMultiphysics/Kratos#2719]
Hi, 
I'm encountering the following error message when I try to run the tests in python 3.7.0

`Running tests for KratosCore
/home/suneth/software/kratos_master/kratos/tests/test_KratosCore.py
Fatal Python error: _Py_InitializeCore: main interpreter already initialized

Current thread 0x00007fcc18c94300 (most recent call first):
Running tests for FluidDynamicsApplication
/home/suneth/software/kratos_master/applications//FluidDynamicsApplication/tests/test_FluidDynamicsApplication.py
Fatal Python error: _Py_InitializeCore: main interpreter already initialized`

I was able to run the tests in Kratos by replacing the "runkratos" command with "python" in the "kratos/python_scripts/run_tests.py". It may be related with [https://bugs.python.org/issue33932](url)

Does anyone have a clean workaround for this? (except downgrading python) :/
Thank you.

**Comment by philbucher** [comment]
@roigcarlo @RiccardoRossi

**Comment by RiccardoRossi** [comment]
Hi Suneth, i think we will need to change the runkratos ... but i am not 100% sure of how this is to be done.

there is a discussion also here : https://bugs.python.org/issue34008

**Comment by roigcarlo** [comment]
+1,  I think we have another issue about this topic but can't find where exactly, we will probably have to change runkratos...

**Comment by loumalouomega** [comment]
@frastellini is using 3.7 i think in Windows

**Comment by loumalouomega** [comment]
I think

**Comment by roigcarlo** [comment]
@loumalouomega Yes, but we set up his computer to use python.exe directly, as @sunethwarna did.

**Comment by Vahid-Galavi** [comment]
I also tried with python 3.7 and I got the same error in Windows.
