### ISSUE TITLE
[External solvers applications] Pastix requires complex compilation 

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2742]
Can we make optional the compilation of the complex version of Pastix?

Just that

**Comment by josep-m-carbonell** [comment]
I was not able to compile last version of pastix (I think it was version 6.0) with the current kratos configuration. Is it possible to do it now. Is there any update in the documentation to do it?

**Comment by loumalouomega** [comment]
No, it is not possible, they changed completely Pastix API, we need to rewrite almost from scratch the Pastix wrapper to Kratos (the solver I mean). There is alegacy compatibilty mode, but I think is more interesting to properly update the solver

**Comment by rubenzorrilla** [comment]
Guys, is this solved? If so it is, can we close this?

**Comment by loumalouomega** [comment]
We haven't modified anything at all, so is not close

**Comment by loumalouomega** [comment]
Closing for inactive, reopening if necessary
