### ISSUE TITLE
[Core] Moving RAYLEIGH_BETA and RAYLEIGH_ALPHA to core?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2750]
Should we move the RAYLEIGH_BETA and RAYLEIGH_ALPHA variables to the core?, these are both used in @KratosMultiphysics/structural-mechanics and @KratosMultiphysics/solid-mechanics, maybe is a good idea to be a common variable to avoid conflicts between applications

**Comment by tteschemacher** [comment]
I would agree to that. They are also needed in other applications as e.g. the IGA-Applications.

**Comment by philbucher** [comment]
I thought with the hash-based variables we should leave them in the Apps?
Otherwise the core will become heavier and heavier

**Comment by loumalouomega** [comment]
Maybe we should clean unused/deprecated variables first

**Comment by loumalouomega** [comment]
And move to apps the variables only used in apps

**Comment by loumalouomega** [comment]
So maybe is a good idea to do it in several stages

**Comment by philbucher** [comment]
can this be closed?

**Comment by loumalouomega** [comment]
Which was the final conclussion?

**Comment by philbucher** [comment]
I would leave it as is
1. Many apps do NOT use it
2. with the hash-based variables we can define it in several apps
3. changing it would break some stuff => not worth it IMO

The above is my opinion, maybe others have different opinions

**Comment by loumalouomega** [comment]
We can close this then
