### ISSUE TITLE
Shell elements from StructuralMechanicsApplication don’t work

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/Kratos#2753]
I am using structural elements of StructuralMechanicsApplication in another application by calling them directly from python scripts. All structural elements, such as beam, truss and cable, work except the shell elements (both thin and thick ones). Is there anything that I have to consider for these types of elements?

Thanks for your help.

**Comment by philbucher** [comment]
Hi, can you post the error message?
Afaik there is nothing special to consider

The [tests](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/tests/test_patch_test_shells.py) are working, try to follow them when setting up your case

**Comment by loumalouomega** [comment]
Can you attach an example?

**Comment by Vahid-Galavi** [comment]
This is an example of the issue.
Thanks in advance!

[09_prescribedDisplacementOnThinShellGeoOnePhase.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2349861/09_prescribedDisplacementOnThinShellGeoOnePhase.gid.zip)

**Comment by loumalouomega** [comment]
Do I need to compile the Geomechanics? (I assume for the example yes). It is the current Geomechanics up to date what you have in your local branch?

**Comment by Vahid-Galavi** [comment]
No, it is not up to date. I will let you know, when I upload it.

**Comment by philbucher** [comment]
There is no GeoMechanicsApp in Master ...

I saw in your MDPA that you are defining Properties 1 for the shell elements and then also define some Material Props in the StructuralMechanics.json, be careful what to use (I recommend assigning empty Properties in the MDPA)

**Comment by Vahid-Galavi** [comment]
I managed to solve the problem for "thick shell" elements by setting "move_mesh_flag" to true in GeoMechanicsApplication.

"Thin shell" elements do not work in both GeoMechanicsApplication and StructuralMechanicsApplication. I have attached an example that I created in StructuralMechanicsApplication:

[05_prescribedDisplacementOnThinShell.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2353103/05_prescribedDisplacementOnThinShell.gid.zip)

**Comment by loumalouomega** [comment]
@Vahid-Galavi there is no GeoMechanicsApplication in master

**Comment by Vahid-Galavi** [comment]
The last example that I attached, is created with StructuralMechanicsApplication. There I am using thin shell elements.

**Comment by loumalouomega** [comment]
Ok, I undertstood that the problem was the combination of both apps

**Comment by loumalouomega** [comment]
The problem works for me

**Comment by Vahid-Galavi** [comment]
Then I need to check why I don’t get good results. The results do not make sense to me. 

Thanks for checking!

**Comment by loumalouomega** [comment]
The last steps are not converging, try to apply the load/displacement slower

**Comment by Vahid-Galavi** [comment]
It is a linear problem. Size of load/displacement should not matter. Anyway, I tried with smaller time steps. It didn't help. The results are still incorrect.

**Comment by loumalouomega** [comment]
OK, let me check in detail

**Comment by loumalouomega** [comment]
You need to set the displacement in function of time, here your example corrected. In any case certainly the shell converges poorer that I expected
[05_prescribedDisplacementOnThinShell.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2356707/05_prescribedDisplacementOnThinShell.gid.zip)

**Comment by Vahid-Galavi** [comment]
Thanks @loumalouomega!

**Comment by philbucher** [comment]
closing since I think this is solved
please reopen in case you have further questions @Vahid-Galavi
