### ISSUE TITLE
Compiling errors caused by Boost

### ISSUE THREAD

**Issue by oleburghardt** [KratosMultiphysics/Kratos#2755]
Dear Kratos developers,

I've had no luck compiling (or executing) Kratos due to the Boost library. However, after I saw that you updated the Linux Build-section in your Wiki, I'm giving it a new try.
I've got two Boost-libraries (locally) compiled following all the advice that you give [here](https://github.com/KratosMultiphysics/Kratos/wiki/Linux-Build), version `1.67` and `1.68`.

Kratos now apparently **does** find them:
`-- Boost version: 1.67.0`
`-- Found the following Boost libraries:`
`--   python`
`Boost Include: /home/oburghardt/Libraries/boost_1_67_0/include`
`Boost Linkdir: /home/oburghardt/Libraries/boost_1_67_0/stage/lib`
`Boostlib used: /home/oburghardt/Libraries/boost_1_67_0/stage/lib/libboost_python36.so.1.67.0
` 

Compilation runs for quite some time, but stops at 
`[ 36%] Building CXX object applications/ConstitutiveModelsApplication/CMakeFiles/KratosConstitutiveModelsApplication.dir/custom_python/python_outfitted_constitutive_law.cpp.o`
 
saying
`/home/oburghardt/Libraries/boost_1_67_0/include/boost/lexical_cast/detail/converter_lexical_streams.hpp:600:32: Fehler: no match for »operator>>« (operand types are »std::basic_istream<wchar_t>« and »std::__cxx11::basic_string<char>«)
`
Is this due to a version mismatch that I'm still not aware of?

Many thanks in advance for any help! Ole

**Comment by roigcarlo** [comment]
Hi @oleburghardt , It seems to be a problem while trying to print a type from boost, but not boost itself.

@josep-m-carbonell My guess is that this include

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/ConstitutiveModelsApplication/custom_python/python_outfitted_constitutive_law.hpp#L18 

is causing the problem. Is it ok If I remove it?

**Comment by josep-m-carbonell** [comment]
Yes it can be removed. With boost python there was the possibility to write a constitutive law in python and call it from c++. For testing and academic purposes because it is slow. When the change to pybind was done I did not translate it because I thought it was not possible to do it with pybind. This possibility of having an outfitted law was lost. If you think it can be done, we can translate the outfitted law to recover its functionality with pybind. Help is needed here. 
Anyway the include can be removed, is useless now. I didn't know it was causing problems.

**Comment by roigcarlo** [comment]
In this case, @oleburghardt can you check you have the last version of Kratos? that file was removed during the migration to pybind11 from the compilation process and it shouldn't be in the CMake at all ( it is commented ).

That said @josep-m-carbonell, it is "technically possible" (with many quotes) to call python functions from pybind11, but probably a lot of rewriting needs to be done. I will try to set it up and we can discuss the results.

**Comment by josep-m-carbonell** [comment]
I think the file is there, but the inclusion of the hpp must not be there.

**Comment by roigcarlo** [comment]
Yes it's there, but it should be commented in the CMake, at least in the master is.

**Comment by oleburghardt** [comment]
Thank you all!

@roigcarlo  In fact I had checked out a develop branch. Switched to master and I did proceed further (I'll check for the differences later.)

I then had a minor error saying
`/home/oburghardt/Libraries/boost_1_67_0/include/boost/python/detail/wrap_python.hpp:50:11: schwerwiegender Fehler: pyconfig.h: No such file or directory`
which could be solved by adding the Python include folder to `CPLUS_INCLUDE_PATH`.

But now it stops at 
`[ 80%] Building CXX object applications/structural_application/CMakeFiles/KratosStructuralApplication.dir/custom_python/add_conditions_to_python.cpp.o`
`/home/oburghardt/Kratos/applications/structural_application/custom_python/add_conditions_to_python.cpp:76:10: schwerwiegender Fehler: python/pointer_vector_set_python_interface.h: No such file or directory`
`#include "python/pointer_vector_set_python_interface.h"`

Actually it might not have been caused by Boost, but as all my trouble seems to arise from there.. Can someone help me out with this one, too?

**Comment by RiccardoRossi** [comment]
Dear Ole,

i have the feeling you are trying to compile some old stuff.

If you don't know specifically that you need the "structural_mechanics" application (old legacy stuff) and the SolidMechanics  you could set the following in your configure file

-DSTRUCTURAL_APPLICATION=OFF                                                     \
-DSOLID_MECHANICS_APPLICATION=OFF                                           \
-DSTRUCTURAL_MECHANICS_APPLICATION=ON                                 \

i am very convinced that with those settings compilation shall go smooth

**Comment by josep-m-carbonell** [comment]
Dear Ole
   As mentioned in a previous responses, checking out the master and setting -DSTRUCTURAL_APPLICATION=OFF in the configure file,  will probably solve the compiling problems. If you want to use any feature of the structural_application you will have to ask to @vryy in order to know how to update and use it. You can keep in the configuration file the lines
-DSOLID_MECHANICS_APPLICATION=ON 
-DCONSTITUTIVE_MODELS_APPLICATION=ON
If you want to use them. They are up to date and work properly. 

Regards

**Comment by oleburghardt** [comment]
@RiccardoRossi @josep-m-carbonell 

> i have the feeling you are trying to compile some old stuff.

That's some piece of very valuable information for me. Don't get me wrong but I didn't expect that there is some code that actually doesn't compile. I expected the error elsewhere.

> -DSTRUCTURAL_APPLICATION=OFF in the configure file, will probably solve the compiling problems.

It did. Thanks to you all!

I can't rate yet what I'll need in the future (got in touch with Kratos via a joint research project) but hopefully the lines that I set to `YES` suffice.
