### ISSUE TITLE
Expected behaviour of PointLocalCoordinates and IsInside checks

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#276]
In reviewing Pull Request #270 we have encountered some issues that need clarification. The setting is the following: Consider a lower-dimension geometry defined in a higher-dimension working space (a line in 2D, a triangle in 3D) and a point that may or may not be contained in the geometry.

1. We call Geometry::PointLocalCoordinates using this point.

  This operation is only well defined if the point belongs to the same line as the line element or to the same plane as the triangle. What should happen when this is not the case?

  @RiccardoRossi and me have been discussing this and we see two different alternatives: Returning the local coordinates of the projection of the point onto that line/plane or returning the local coordinates of the point on the geometry that is closest to the input point. Apparently, the first option would be desirable for mapping and the second for contact problems.

2. We call Geometry::IsInside using the same point.

  The current IsInside implementations rely on PointLocalCoordinates. If we go with the local coordinates of the _projected_ point, IsInside may retrun true for points that do not lie within the geometry, which is very counterintuitive. However, @roigcarlo was telling me that this is needed for the triangle intersection routines.

I'd like to know the opinion of the Kratos community on this (In particular I know that this concerns @loumalouomega @philbucher @RiccardoRossi @pooyan-dadvand and @roigcarlo)

**Comment by loumalouomega** [comment]
The most general case is to consider 'IsInside()' as physically inside (plus a tolerance), and define an operation which includes the projection, this operation should be defined in the base class as @RiccardoRossi  said.

**Comment by roigcarlo** [comment]
I agree with @loumalouomega. I had similar problems building tests for that specific function and I find somehow not very intuitive that `IsInside()` works with the projection. It can be deduced by the input arguments but I would suggest to have to separate functions, or have some kind of `USE_GLOBAL_COORDINATES` vs `USE_LOCAL_COORDINATES` flag.

**Comment by RiccardoRossi** [comment]
Hi,
     i'd like to clarify that i share @jcotela 's position on this:

with this i mean that (in my opinion) the function Geometry::PointLocalCoordinates shall return the local position in the parameter space of the element obtained by projecting. On the basis of the local coordinates one may reconstruct the position of the position "within the element" and compare it to the original position to see if they coincide within a distance.

The point is that the concept of "IsInside" is kinda fuzzy. To me it makes sense that something is inside if it the projected point lays within the parameteric bounds of the element AND the reconstruction of the position coincides with the original position.
An important point is that on the basis of the local coordinates a user can easily implement a refined "Inside" according to his specific needs. 

Now the possibility of adding another function to all geometries (or to the base class) is not really appealing to me. So the question is...do we REALLY need it? can't we do with some user defined function?

aside of this, @roigcarlo i really don't understand what you mean by USE_GLOBAL_COORDINATES or USE_LOCAL_COORDINATES :-(. I think that the only really reliable decision can be done in the parameter space...

**Comment by roigcarlo** [comment]
@RiccardoRossi Probably the names are unfortunate, I was trying to point out this situation:
Given a point let's say `(1/4, 1/4, 10)` and given a triangle3d3 with coords `(0,0,0)`, `(0,1,0)` and `(1,0,0)`

What should be the output of `IsInside()`?

As it is right now, I understand that it should return `True`, as the point projected is inside the triangle. This is what I meant by `LOCAL`.

What I was expecting when I used this function was a `False`, as is not in the same Z as the triangle. Which would be the `GLOBAL` 

Aside from the discussion whether we actually need that or not, the name is sort of confusing to me as it is right now.

**Comment by RiccardoRossi** [comment]
ok,

than at this point wouldn't it be better to have two distinct functions?


<http://www.cimne.com/>

**Comment by roigcarlo** [comment]
Yes

**Comment by pooyan-dadvand** [comment]
In my opinion `IsInside` should return if it is physically (with some tolerance) on the line (as @loumalouomega mentioned) 
I would put the projections in a separate methods (like `OrthogonalProjection` and `NearestPoint`) which also could come handy in intersections and mappings.
About the question if LocalCoordinates should make the projection I am open to other opinions without a clear choice at this moment.

**Comment by philbucher** [comment]
Why not separating the issue with IsInside and the Projection completely?
IsInside checks either, according to @roigcarlo comment,
- local coords or
- global coords
One could discuss whether one does that with two different functions (IsInsideLocal / IsInsideGlobal) or with a flag IsInside(bool LocalCoords)

The existing PointLocalCoordinates can stay as is, then we only need some functions for projection following @pooyan-dadvand suggestion

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand 

the point is that for a generic element the is inside looks something like (in pseudo code)

      bool IsInside( global_position)
      {
            local_coordinates = LocalCoordinates(global_position)

            decide if local coordinates falls within the element

             decide if the reconstructed point using local coordinates is the same as the original one
      }

that is, the LocalCoordinates plays a crucial role in this

**Comment by philbucher** [comment]
Have there been further discussions in BCN about how to proceed with this issue?

**Comment by pooyan-dadvand** [comment]
In my opinion the implementation detail of the `IsInside` should not change the behavior of `LocalCoordinates`. So let see them two complete different methods. 

About the implementation I know that many geometries are implementing the `IsInside` as @RiccardoRossi mentioning, nevertheless there are important cases where some faster checks (like bounding box check) can avoid calculation of the local coordinates for far points.

Finally if we have the other two projection methods (like OrthogonalProjection and NearestPoint) it would be helpful for is inside as @RiccardoRossi mentioned and also in mapping.

**Comment by RiccardoRossi** [comment]
Hi @pooyan-dadvand, ok i think we are converging.

My proposal would be the following:

1. Leave as it is the Function **LocalCoordinates** provides the coordinates in the parent space, this implicitly means doing a projection to the space of the geometry of interest. For example the projection to a line for a line in the 3D space or to a plane for a surface embedded in the 3D space.
2. Introduce a function **IsInsideProjection** (name to be improved) which tells if the projection of the global point onto the local space falls within the parent element 
3. Function **IsInside** redefined as something equivalent to (with a better implementation for the elements in which a higher optimization is possible). Essentially what i am telling it should happen both that the point falls within the Projection AND that the reconstructed point is not far away from the real one. **My only concern here is that this "far away" should be quantified in the real space, while the tolerance for the IsInsideProjection is always defined with respect to the 0-1 span**


           void IsInside(xglobal)
          {
               bool inside_projection = IsInsideProjection(xglobal)
               if(inside_projection == false)
                   return false;
               else
              {
                  xlocal = LocalCoordinates(xglobal)
                  N = ShapeFunctionValue(xglobal)
                  xreconstructed = sum of N[i] * x[i]

                  if(norm(xreconstructed - xglobal) < tol)
                           return true
                  else
                           return false
              }
           }

I should also say that i was initially very concerned on the possible impact of making a change to this, however i did a grep of the function in the entire kratos and the result is not that many usages. Here goes the list (cleaned up, so i hope i did not remove relevant entries).
The bottomline is that there are not that many entries, so backward compatibility should not be a major issue. **Any comment on this?**

applications/PoromechanicsApplication/custom_utilities/fracture_propagation_3D_utilities.hpp:                IsInside = pElementOld->GetGeometry().IsInside(GlobalCoordinates,LocalCoordinates); //Checks whether the global coordinates fall inside the applications/PoromechanicsApplication/custom_utilities/fracture_propagation_3D_utilities.hpp:                    IsInside = pElementOld->GetGeometry().IsInside(GlobalCoordinates,LocalCoordinates,1.0e-5);
applications/PoromechanicsApplication/custom_utilities/fracture_propagation_2D_utilities.hpp:                IsInside = pElementOld->GetGeometry().IsInside(GlobalCoordinates,LocalCoordinates); //Checks whether the global coordinates fall inside the applications/PoromechanicsApplication/custom_utilities/fracture_propagation_2D_utilities.hpp:                    IsInside = pElementOld->GetGeometry().IsInside(GlobalCoordinates,LocalCoordinates,1.0e-5);
applications/structural_application/custom_utilities/variable_transfer_utility.h:                if( (*it)->GetGeometry().IsInside( newNode, rResult ) )
applications/structural_application/custom_utilities/boundary_conditions_and_contact_utilities.h:                if(geom1.IsInside(geom2[i], result))
applications/structural_application/custom_utilities/boundary_conditions_and_contact_utilities.h:                if(geom2.IsInside(geom1[i], result))
applications/structural_application/custom_utilities/boundary_conditions_and_contact_utilities.h:            if(geom_master.IsInside(geom_slave[Nodes[i]], result))
applications/structural_application/custom_utilities/node_snapping_utility.h:            if( it->GetGeometry().IsInside( point, rResult ) )
applications/structural_application/custom_utilities/parallel_variable_transfer_utility.h:                if( (*it)->GetGeometry().IsInside( newNode, rResult ) )
applications/ParticleMechanicsApplication/custom_utilities/quad_binbased_fast_point_locator.h:                bool is_found = geom.IsInside(coords, Result);
applications/ContactMechanicsApplication/custom_processes/parametric_wall_contact_search_process.hpp:		  if( mpParametricWall->IsInside(Point,Time,Radius) ){
applications/MappingApplication/custom_utilities/mapper_utilities.h:        bool is_inside = pGeometry->IsInside(GlobalCoords, rLocalCoords, tol_local_coords);
applications/MappingApplication/custom_utilities/mapper_utilities.h:        bool is_inside = pGeometry->IsInside(GlobalCoords, rLocalCoords, tol_local_coords);
kratos/utilities/pointlocation.h:            if( rGeom.IsInside(ThisPoint,LocalCoordinates) )
kratos/utilities/bounding_box_utilities.h:           if(geom_master.IsInside(geom_slave[i], result)) {InsideNodes.push_back(&geom_slave[i]);}
kratos/tests/geometries/test_triangle_2d_3.cpp:  KRATOS_TEST_CASE_IN_SUITE(Triangle2D3IsInside, KratosCoreGeometriesFastSuite) {
kratos/tests/geometries/test_triangle_2d_3.cpp:    KRATOS_CHECK(geom->IsInside(PointInside, LocalCoords, EPSILON));
kratos/tests/geometries/test_triangle_2d_3.cpp:    KRATOS_CHECK_IS_FALSE(geom->IsInside(PointOutside, LocalCoords, EPSILON));
kratos/tests/geometries/test_triangle_2d_3.cpp:    KRATOS_CHECK(geom->IsInside(PointInVertex, LocalCoords, EPSILON));
kratos/tests/geometries/test_triangle_2d_3.cpp:    KRATOS_CHECK(geom->IsInside(PointInEdge, LocalCoords, EPSILON));
kratos/tests/geometries/test_triangle_3d_3.cpp:  KRATOS_TEST_CASE_IN_SUITE(Triangle3D3IsInside, KratosCoreGeometriesFastSuite) {
kratos/tests/geometries/test_triangle_3d_3.cpp:    KRATOS_CHECK(geom->IsInside(PointInside, LocalCoords, EPSILON));
kratos/tests/geometries/test_triangle_3d_3.cpp:    KRATOS_CHECK_IS_FALSE(geom->IsInside(PointOutside, LocalCoords, EPSILON));
kratos/tests/geometries/test_triangle_3d_3.cpp:    KRATOS_CHECK(geom->IsInside(PointInVertex, LocalCoords, EPSILON));
kratos/tests/geometries/test_triangle_3d_3.cpp:    KRATOS_CHECK(geom->IsInside(PointInEdge, LocalCoords, EPSILON));
kratos/spatial_containers/bounding_volume_tree.h:    bool IsInside(const PointType& r_point, double tolerance) const
kratos/processes/find_intersected_geometrical_objects_process.cpp:		if (rFirstGeometry.IsInside(rSecondGeometry.GetPoint(0), local_point))

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi

1. I agree to keep local coordinates as it is.
2. I don't like the name.... (I did not understood what it does until I discuss it with you). On the other hand I would like to have `ProjectedPoint` and `NearestPoint` method as they can be very useful in spatial searches. Do you think that we can use them in combination with localcoordinates to implement the `IsInside` ?
3. I see your point, however for epsilon in all our implementations (and most of the collision detection algorithms in literature) the epsilon check is arbitrary in reference or local coordinates in order to reduce flop. If it is really important we should rewrite several algorithms (and not only is inside)

**Comment by loumalouomega** [comment]
@pooyan-dadvand I think is better to keep the `IsInside` of the `ProjectedPoint` separated, because in some cases, when the non linear iteration is used to check the shape functions of a point you can get a false positive of projection. You can combine them, in that case there is not "superposition".

**Comment by loumalouomega** [comment]
Did we finally come to a conclusion?

**Comment by pooyan-dadvand** [comment]
At least one: keep the local coordinate as it is! 😄 

Other results of the discussion:

`IsInside` and `HasIntersection` to give pure geometrical result of them. Return true if the point is inside or if the geometry really collides within given tolerance.

'IsInsideProjection' is a helpful method but the name should be changed

@RiccardoRossi requires tolerance to be respected to local coordinates. Nevertheless, now is not like this and sometimes is not easy to modify our collision algorithms to respect such a constrain. This changes my interpretation of tolerance but I can live with it.

Apart from this I need `Distance`, `NearestPoint`, `ProjectionPoint` methods which are for another issue.

**Comment by loumalouomega** [comment]
Maybe I will implement this approach to close this discussion

**Comment by pooyan-dadvand** [comment]
Thanks @loumalouomega 

Don't forget to change the name of the `IsInsideProjection` with something more understandable....

**Comment by loumalouomega** [comment]
Is named, IsInsideWhenProjected

**Comment by pooyan-dadvand** [comment]
ok

**Comment by loumalouomega** [comment]
I think we solved this
