### ISSUE TITLE
[StructuralMechanicsApplication/Adjoint] Use Kratos components in replacement process

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#2761]
As a reminder:

According to @philbucher suggestion it would make sense to create the adjoint elements in the replacement process using kratos components.

This would allow to remove the includes of the adjoint elements in this process, therefor reduce compile time.

**Comment by philbucher** [comment]
Another suggestion:
[The names of the adjoint elements/conditions and their primal counterparts](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_processes/replace_elements_and_conditions_for_adjoint_problem_process.cpp#L200-L207) should be saved in an `std::map`, this way you can get rid of the if, else if, else if ...

**Comment by philbucher** [comment]
ping

**Comment by armingeiser** [comment]
Using Kratos components is not possible with the current implementation of the AdjointElements.
This is because the pointer of the primal element has to be passed in the constructor/or to a hypothetic `Create` function. But there is no overload for this in the base class.

Thats why we have to specifically call the derived class constructor.
