### ISSUE TITLE
README in cmake_build is outdated

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2764]
@KratosMultiphysics/technical-committee 

One option would be to remove it entirely and refer in `configure.sh` to the corresponding entries in the Wiki (which to my knowledge are more up-to-date) and are describing the same

**Comment by RiccardoRossi** [comment]
is it very outdated? i think it is useful for the cases in which you have no internet...

**Comment by loumalouomega** [comment]
I updated no so much time ago, I think is not so old

**Comment by philbucher** [comment]
I'd say it has not been updated for ~1year ago

**Comment by philbucher** [comment]
still has boost as a requirement

Maybe this can be a light version and the Wiki-Version is the proper one?
I just think it is hard to keep two versions up-to-date, there will most likely always be a newer one

**Comment by loumalouomega** [comment]
We can easily update it. Are you volunteer?

**Comment by loumalouomega** [comment]
And boost is a requirement as only header external library

**Comment by philbucher** [comment]
Sure I can do it (eventually) ...
I would still like to wait for some other opinions (e.g.  whether this should be a light version only)
Otherwise it will be again outdated in a year

**Comment by armingeiser** [comment]
My opinion: 
I didn't know that this exists :smile: 

Having two places where you can potentially look at may be confusing. Would it be possible to reference this README somehow from the WIKI, to avoid duplicated "code"? 
So they would definitely always show the same content.

If such a thing is not possible, i would go for some comments in the template `configure.sh` like @philbucher suggests.

My opinion though.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee after thinking abt this some more, why not move the entire description to the readme that is in the cmake_build - folder? I see four advantages:
1. We can easily reference it from the Wiki (hence no more duplicated stuff)
2. It is available offline too
3. It is also versioned, i.e. one can not just change it!
4. It automatically fixes #2115

What do you think?
I would volunteer to port / unify the README

**Comment by roigcarlo** [comment]
We will move it for after release as we are expecting some major changes in the compilation process to come just after 7.0

**Comment by roigcarlo** [comment]
@philbucher I think we can close this as now we have the install.md ( If you agree please close)
