### ISSUE TITLE
@KratosMultiphysics/dam

### ISSUE THREAD

**Issue by UPC-EnricBonet** [KratosMultiphysics/Kratos#2778]
Hello,
I have simulated the "2d_dam_thermo_mechanical.mdpa" and I think that something is not correct probably I do something wrong. When I change the THERMAL_EXPANSION parameter the displacement changes a lot but when I change the YOUNG_MODULUS a lot (2.46E+07 to 2.46E+03) there is not displacement changes in the nodes which it is quite strange furthermore I change Water_Level and the Spe_weight parameter in the project manager and nothing change in nodes?? Please can you help me?? Thanks!!

**Comment by jcotela** [comment]
looks like the same issue was opened twice for some reason, I'm closing this one, please continue the discussion in #2775
