### ISSUE TITLE
[Applications] Solvers wrapper

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2785]
The main reason I cannot reuse the structural analysis for my contact problems is because the solvers wrapper. I spoke with @RiccardoRossi and he proposes to create a "factory" of solvers to avoid this.

@KratosMultiphysics/structural-mechanics

**Comment by philbucher** [comment]
Sounds good to me!

Can you specify your design a bit more?

**Comment by philbucher** [comment]
@loumalouomega can you explain the design you have in mind?

**Comment by loumalouomega** [comment]
The idea is to follow the design of #615. So the solvers are registered and can acceded via KratosComponents, then we could skip the wrapper

**Comment by philbucher** [comment]
Does this work for python-objects?

**Comment by philbucher** [comment]
is this still open?

**Comment by loumalouomega** [comment]
Yep, and I lost the current point of the discussion

**Comment by RiccardoRossi** [comment]
I think the discussion was about having a way to register solvers so that they can be constructed automatically. I think it can work both for python and c++ objects as long as they all derive from the same object.

**Comment by philbucher** [comment]
there was a duplicated discussion happening in #2251 , please also consider this for further discussions

**Comment by msandre** [comment]
Hi Guys, I am looking for exactly what you are discussing in order to reduce code in my unit tests. Having c++ factories for linear solvers and strategies would be very useful in this regard. Currently, it looks like you already have "includes/linear_solver_factory.h" working in the core.

Would it be ok with everyone if we eliminate the templated polymorphic class structure with a non-templated free function like `LinearSolver<SparseSpaceType,LocalSpaceType>::Pointer CreateLinearSolver(Kratos::Parameters settings);` and use c++11's std::function to perform type erasure and store it in the kratos components? It would reduce the headers a lot and put all of the implementation detail in cpp files.

My second question is, would it be ok to extend this to solving strategies?

**Comment by philbucher** [comment]
@msandre does it also work for the trilinos-factory of the linear solvers?
Then I am +1

BTW @loumalouomega is already working on the factories for other classes (strategy and others) in #3185

**Comment by RiccardoRossi** [comment]
Hi Mike,
      i don't fully follow what you wish to do... but if we have room for include that would be very welcome. As @philbucher suggested we will need two different versions, one for trilinos and a second one for ublas.

I am CC-ing @josep-m-carbonell since to my understanding he was also interested in smthg similar

**Comment by msandre** [comment]
I expanded on my suggestion in #3185.

**Comment by GuillermoCasas** [comment]
ping @RiccardoRossi

**Comment by philbucher** [comment]
#6250 is a solution for using custom solvers

not as sophisticated as having a registry, but I am not sure if we want to go all the way in this case. For python we have never done the registry, not sure if it is worth it in this case

**Comment by adityaghantasala** [comment]
> Does this work for python-objects?

Is this question answered ? Does it ?

**Comment by ddiezrod** [comment]
@loumalouomega Is this still active or should we close this for the moment?

**Comment by loumalouomega** [comment]
I think the idea is still interesting

**Comment by ddiezrod** [comment]
In behalf of @KratosMultiphysics/implementation-committee:

We were wondering if it'd be possible to use @pooyan-dadvand 's new factory here to construct the solvers. Apart from this, if we want to use a factory I think we will need to change pretty much all project parameters.
e.g.
"solver_type":  "static" -> "solver_type" : "structural_mechanics_static_solver"

**Comment by ddiezrod** [comment]
After further discussion, we think that the workaround provided by @philbucher is good enough to solve the problem and we do not clearly see what else could be done to improve it. We can consider this as solved from @KratosMultiphysics/implementation-committee side for the moment.

**Comment by loumalouomega** [comment]
@ddiezrod can you please summarise what it is done and what is pending to be done?

**Comment by ddiezrod** [comment]
At least from what we agreed in @KratosMultiphysics/implementation-committee , nothing needs to be done. Current solution explained by @philbucher to use a custom solver is enough in our opinion.

**Comment by loumalouomega** [comment]
So I will close this
