### ISSUE TITLE
[MeshingApplication] MMG process is not working

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2787]
This is an auto reminder:

![imagen](https://user-images.githubusercontent.com/19991680/45002807-0a482900-afdb-11e8-826a-7ba2041f7944.png)

@loumalouomega, please fix this

**Comment by philbucher** [comment]
I think I might have sth to do with the first failure, cannot say why though
I think sth got broken in the check process at some point, sorry

**Comment by loumalouomega** [comment]
On it

**Comment by loumalouomega** [comment]
The first one is because a relative path, solved

**Comment by loumalouomega** [comment]
@roigcarlo Can we include a precompiled version of MMG in the nightly build or it is problematic?, certainly I don't now when the tests stopped working

**Comment by roigcarlo** [comment]
If it can be downloaded from a known place we can add it

**Comment by loumalouomega** [comment]
It is LGPL, I assume i can precompile it and upload it to a repository

**Comment by loumalouomega** [comment]
I reopen to discuss hot to include MMG to the nightly build

**Comment by philbucher** [comment]
@loumalouomega @roigcarlo could we precompile the libraries and put them somewhere where Travis, Amazon, Appveyor etc can download them?
This would be useful also for Metis, Trilinos, ... and we wouldn't need to worry abt the licensing issues

**Comment by roigcarlo** [comment]
Yep that should work

**Comment by loumalouomega** [comment]
Ok I created https://github.com/loumalouomega/MMGPrecompiled
