### ISSUE TITLE
Dem tests taking too long

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#2788]
@KratosMultiphysics/dem Some people (a lot in fact) are telling me that DEM tests are systematically taking to long to finish which is causing roughtly 1/3 of the Pr fail in travis.

By design I have to handle tests taking to long as errors, which is causing this:
```
[Warning]: Application has been found in "DEM_application" directory but it was expected in "DEMApplication". Please check the naming convention.
...
ABORT: Tests for DEMApplication took to long. Process Killed.
```

Is there a way to identify the problematic test and disable it?

**Comment by maceligueta** [comment]
We have a very minimal set of tests that are run by Travis. I'll try to force one thread and see what happens.

**Comment by maceligueta** [comment]
PR #2804 should decrease the amount of time consumed by the tests...
