### ISSUE TITLE
Issues with the reorder modepartIO and the memory partitioner

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#2789]
Dear all. 

As you probably know, I have been working in making the appropriate changes so the `MetisDivideHeterogeneousInputProcess` can perform perform the process without the need of witting intermediate files, which should help to reduce the load on clusters where the disk IO was causing bottlenecks.

Sadly enough during the development @RiccardoRossi and I have found a design problem that we are not sure how to overcome.

Please consider this code ( full version in https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/python_scripts/trilinos_import_model_part_utility.py#L31 )

```Python
if perform_partitioning == True:
    if KratosMPI.mpi.rank == 0:
        model_part_io = ReorderConsecutiveModelPartIO(input_filename)
        partitioner = MetisDivideHeterogeneousInputProcess(model_part_io, ...)
        partitioner.Execute()

    mpi_input_filename = input_filename + "_" + str(mpi.rank)   
    ModelPartIO(mpi_input_filename).ReadModelPart(self.main_model_part)
```
 
As you can see, this piece of code uses two different `ModelPartIO`, one of which tampers with the order of the ID of the model, while the second one performs a normal read. Once we change the code to use the memory partitioner:

```Python
if perform_partitioning == True:
    model_part_io = ReorderConsecutiveModelPartIO(input_filename)
    partitioner = MetisDivideHeterogeneousInputProcessInMemory(model_part_io, ...)
    partitioner.Execute()

    model_part_io.ReadModelPart(self.main_model_part)
```

Notice that all the process is done in the same `ModelPartIO` as it cannot read from any file. The problem is that, as the `ModelPartIO` is an instance of `ReorderConsecutiveModelPartIO`, the read of every partition is also reordered which we suspect is having all partitions have repeated ID's.

We have been discussing several solutions to this problem, but all solutions are somehow problematic, so we would like to discuss about this a bit. So far we have considered the following:

**1 - Move all the read code to C++**
This would allow to use a custom constructor for a ModelPartIO that I can initialize with the data of the first one. In short, instead of files we would use string. 
That would not break the API and it would maintain the polymorphism of the IO classes.
The problem with this solution is that we would be creating a code dependency between trilinos and metis.

**2 - Expose the buffer so it can be used from python**
Same idea as above, but exposing a function so I can retrieve the buffer from python and initialize a new ModelPartIO with it instead of a file name.
The problems with this one is that we are modifying the API of the IO.

**3 - Integrate the reorder functionality into the basic ModelPartIO.**
The idea will consist on completely removing the ReorderconsecutiveModelPartIO class and integrate the functionality in the normal ReadModelPart function via a flag:
```C++
void ReadModelPart(ModelPart & rThisModelPart) override;
```
to
```C++
void ReadModelPart(ModelPart & rThisModelPart, IO::ReadMode ReadMode = IO::ReadMode::Serial) override;
```

Or define a `SetReadMode()`

Personally, I would go for something in the lines of the 3rd, but as I said, we are actively discussing this. 
Please feel free to ping anyone else interested in this.

**Comment by jcotela** [comment]
@roigcarlo a minor additional problem is that the two current ModelPartIO instances operate on different filenames (the second one has the mpi rank appended), which will require some ugly hardcoding.

Personally, I'm thinking that maybe the Metis partitioner should not be a process but an IO, at least for the in-memory version. In this way we could go from giving the file to setting the ModelPart within a single class and avoid the problems related to passing the partitioned buffer to the ReadModelPart call.

**Comment by philbucher** [comment]
Question:
I see the problem you are describing, but isn't the entire thing more a question of modeling?
I mean, I would not do the partitioning on the cluster, because why waste valuable runtime on sth that can be done locally beforehand?

**Comment by roigcarlo** [comment]
@jcotela In fact Divide Process is doing a reading at the beginning, I could probably put another one at the end as well using a normal ModelPartIO.

@philbucher We want to use that mainly to reduce the load on the file system.

What you purpose can be done and in fact it has been the way to go for really big models until now but such models can simply not be loaded in a normal computer even for partitioning purposes. I am thinking in the Barcelona model which we had to generate in a GiD instance running on the cluster due to memory constraints, also consuming CPU time.

Also, as the model grows, it may not be convenient at all to store all the partition permuations for a benchmark. For example, a benchmark of a 500Gb model for 96, 192, 384 cores can easily occupy up to 2Tb of the quota in a cluster.

**Comment by philbucher** [comment]
ok

another though of mine (a bit off-topic I have to admit): Since you are considering a change, it could make sense to think abt reading input from multiple mdpa's before the partitioning
This could be useful in the future.

**Comment by pooyan-dadvand** [comment]
Just to add that I like the idea of @jcotela in creating a partitioning io more than the rest. It make sense

**Comment by philbucher** [comment]
I think this is solved right @roigcarlo ?

**Comment by roigcarlo** [comment]
Yup, I thought it closed automatically. Thx!
