### ISSUE TITLE
[Core][ConstitutiveLaw] TransformStrains is not a virtual method 

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2806]
In line 1010 of constitutive_law.h the method TransformStrains is not declared virtual, but the method TransformStresses it is. Is this right?

 https://github.com/KratosMultiphysics/Kratos/blob/f86de29047f9cd7dc92c0cc95c299a4365948b3a/kratos/includes/constitutive_law.h#L1010

https://github.com/KratosMultiphysics/Kratos/blob/f86de29047f9cd7dc92c0cc95c299a4365948b3a/kratos/includes/constitutive_law.h#L1023

**Comment by loumalouomega** [comment]
@KratosMultiphysics/technical-committee @KratosMultiphysics/structural-mechanics @KratosMultiphysics/solid-mechanics

**Comment by josep-m-carbonell** [comment]
In fact these methods are utilities that would be better to be located in another place (i.e. constitutive_law_utilities) non virtual.

**Comment by loumalouomega** [comment]
I agree with that, besides that would make the CL lighter (which is something everyone will agree)

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee: The less intrusive option would be to add the virtual to the CL 
 base method.

**Comment by loumalouomega** [comment]
Added
