### ISSUE TITLE
DEMApplication/add force on the rigid face

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#2811]
Hello,everyone
I am just doing the simulation of the shear test.I want to add the vertical load on the top surface.
Is there the parameter in the DEM to set the force(static force)?
Best regards

**Comment by maceligueta** [comment]
In principle you should be able to impose a fix value of the variable EXTERNAL_APPLIED_FORCE to the SubModelPart containing the top surface (inside the SubModelPartData section).
Like this:
`EXTERNAL_APPLIED_FORCE [3] (0.0, 0.0, -100.0) `

**Comment by maceligueta** [comment]
referencing @joaquinirazabal and @KratosMultiphysics/dem in general to make them aware of this issue.
(I saw it by chance, it is better if you assign to issue to someone, @fengzekang. You can also reference someone so they receive an email )

**Comment by fengzekang** [comment]
Thanks for your reply, @maceligueta .
I will try to do it to add the external_applied_force.I will tell you the result after I finished the test.
And also I will reference someone to make somebody note the issue.
Thanks again.
Best regards

**Comment by joaquinirazabal** [comment]
Hi,
If you define the model from the interface in the "Type of motion" of the DEM-wall you should use "Free body motion" and you can apply everything there.
If you make your own .mdpa file the submodelpart should be something like:

Begin SubModelPart Sleeper // GUI DEM-FEM-Wall group identifier: Sleeper
  Begin SubModelPartData // GUI DEM-FEM-Wall group identifier: Sleeper
  PROPERTIES_ID 0
  FREE_BODY_MOTION 1
  RIGID_BODY_MASS 372.0
  RIGID_BODY_CENTER_OF_MASS [3] (2.35,0.728,0.3)
  RIGID_BODY_INERTIAS [3] (170.3225,3.5725,171.25)
  EXTERNAL_APPLIED_FORCE [3] (0.0,0.0,-1000.0)
  EXTERNAL_APPLIED_MOMENT [3] (0.0,0.0,0.0)
  VELOCITY_START_TIME 0.0
  VELOCITY_STOP_TIME 10000.0
  IMPOSED_VELOCITY_X_VALUE 0.0
  IMPOSED_VELOCITY_Y_VALUE 0.0
  IMPOSED_ANGULAR_VELOCITY_X_VALUE 0.0
  IMPOSED_ANGULAR_VELOCITY_Y_VALUE 0.0
  IMPOSED_ANGULAR_VELOCITY_Z_VALUE 0.0
  IDENTIFIER Sleeper
  FORCE_INTEGRATION_GROUP 0
  End SubModelPartData
  Begin SubModelPartNodes
  21
  22
  23
  24
  25
  26
  27
  28
  29
  30
  31
  32
  33
  34
  35
  36
  37
  38
  39
  40
  41
  42
  43
  44
  End SubModelPartNodes
End SubModelPart

**Comment by fengzekang** [comment]
@joaquinirazabal 
Thanks for your reply.What I have wrote in my .mdpa file
Begin ModelPartData
// VARIABLE_NAME value
End ModelPartData

Begin Properties 0
WALL_FRICTION 0.4500473211674043
WALL_COHESION 0.0
COMPUTE_WEAR 0
SEVERITY_OF_WEAR 0.001
IMPACT_WEAR_SEVERITY 0.001
BRINELL_HARDNESS 200.0
YOUNG_MODULUS 1e20
POISSON_RATIO 0.25
End Properties

Begin Properties 1
WALL_FRICTION 0.4500473211674043
WALL_COHESION 0.0
COMPUTE_WEAR 0
SEVERITY_OF_WEAR 0.001
IMPACT_WEAR_SEVERITY 0.001
BRINELL_HARDNESS 200.0
YOUNG_MODULUS 1e20
POISSON_RATIO 0.25
End Properties

Begin Nodes // GUI DEM-FEM-Wall group identifier: box
       1              0.0              0.0              0.0
       2              0.0              0.0             0.09
       3              0.0              0.0            0.045
       4              0.0             0.15             0.09 
       5              0.0            0.075             0.09  
       6              0.0             0.15              0.0 
       7              0.0             0.15            0.045 
       8              0.0            0.075              0.0 
      18              0.2              0.0              0.0 
      19              0.1              0.0              0.0 
      21              0.2              0.0            0.045 
      26              0.2             0.15              0.0 
      29              0.2             0.15            0.045 
      37              0.1             0.15              0.0 
      39              0.2            0.075              0.0 
      44              0.2             0.15             0.09 
      45              0.1             0.15             0.09 
      46              0.2              0.0             0.09 
      47              0.2            0.075             0.09 
      48              0.1              0.0             0.09 
End Nodes

Begin Nodes // GUI DEM-FEM-Wall group identifier: top
       9              0.0              0.0             0.12 
      10              0.0             0.15             0.12 
      11              0.0            0.075             0.12 
      12              0.2             0.15             0.12 
      13              0.1             0.15             0.12 
      14              0.2              0.0             0.12 
      15              0.2            0.075             0.12 
      16              0.1              0.0             0.12 
End Nodes

Begin Conditions RigidFace3D3N // GUI DEM-FEM-Wall group identifier: box
1 0 5 3 2
2 0 8 1 3
3 0 5 4 7
4 0 8 7 6
5 0 8 3 5
6 0 8 5 7
7 0 46 21 47
8 0 21 18 39
9 0 29 44 47
10 0 26 29 39
11 0 47 21 39
12 0 29 47 39
13 0 19 3 1
14 0 48 2 3
15 0 48 21 46
16 0 19 18 21
17 0 19 48 3
18 0 48 19 21
19 0 6 7 37
20 0 7 4 45
21 0 44 29 45
22 0 29 26 37
23 0 7 45 37
24 0 29 37 45
25 0 37 8 6
26 0 19 1 8
27 0 37 26 39
28 0 19 39 18
29 0 19 8 37
30 0 19 37 39
End Conditions

Begin Conditions RigidFace3D3N // GUI DEM-FEM-Wall group identifier: top
31 1 10 11 13
32 1 11 9 16
33 1 15 12 13
34 1 14 15 16
35 1 13 11 16
36 1 15 13 16
End Conditions

Begin SubModelPart 1 // DEM-FEM-Wall. Group name: box
  Begin SubModelPartData // DEM-FEM-Wall. Group name: box
  LINEAR_VELOCITY [3] (0.0,0.0,0.0)
  VELOCITY_PERIOD 0.0
  ANGULAR_VELOCITY [3] (0.0,0.0,0.0)
  ROTATION_CENTER [3] (0.0,0.25,0.3)
  ANGULAR_VELOCITY_PERIOD 0.0
  VELOCITY_START_TIME 0.1
  VELOCITY_STOP_TIME 2.5
  ANGULAR_VELOCITY_START_TIME 0.0
  ANGULAR_VELOCITY_STOP_TIME 0.0
  FIXED_MESH_OPTION 0
  RIGID_BODY_MOTION 1
  FREE_BODY_MOTION 0
  RIGID_BODY_MASS 0.0
  RIGID_BODY_CENTER_OF_MASS [3] (0.0,0.0,0.0)
  RIGID_BODY_INERTIAS [3] (0.0,0.0,0.0)
  TABLE_NUMBER 0
  //TABLE_VELOCITY_COMPONENT 0
  IDENTIFIER bucket
  TOP 0
  BOTTOM 0
  FORCE_INTEGRATION_GROUP 0
  End SubModelPartData
  Begin SubModelPartNodes
         1
         2
         3
         4
         5
         6
         7
         8
        18
        19
        21
        26
        29
        37
        39
        44
        45
        46
        47
        48
  End SubModelPartNodes
End SubModelPart

Begin SubModelPart 2 // DEM-FEM-Wall. Group name: top
  Begin SubModelPartData // DEM-FEM-Wall. Group name: top
  PROPERTIES_ID 1
  FREE_BODY_MOTION 1
  RIGID_BODY_MASS 372.0
  RIGID_BODY_CENTER_OF_MASS [3] (0.1,0.075,0.12)
  RIGID_BODY_INERTIAS [3] (170.3225,3.5725,171.25)
  EXTERNAL_APPLIED_FORCE[3](0.0,0.0,-1000.0)
  EXTERNAL_APPLIED_MOMENT [3] (0.0,0.0,0.0)
  VELOCITY_START_TIME 0.0
  VELOCITY_STOP_TIME 10000.0
  IMPOSED_VELOCITY_X_VALUE 0.0
  IMPOSED_VELOCITY_Y_VALUE 0.0
  IMPOSED_ANGULAR_VELOCITY_X_VALUE 0.0
  IMPOSED_ANGULAR_VELOCITY_Y_VALUE 0.0
  IMPOSED_ANGULAR_VELOCITY_Z_VALUE 0.0
  IDENTIFIER Top
  FORCE_INTEGRATION_GROUP 0
  End SubModelPartData
  Begin SubModelPartNodes
  9
  10
  11
  12
  13
  14
  15
  16
  End SubModelPartNodes
End SubModelPart

Begin Table 0 TIME VELOCITY
0.0  0.0
1.0  0.0
End Table

But when I compile the "runkratos KrtosDEM.py",there will be the error showing:
Traceback (most recent call last):
  File "KratosDEM.py", line 7, in <module>
    solution.Run()
  File "/home/dongxueyang/Kratos/applications/DEM_application/python_scripts/main_script.py", line 238, in Run
    self.Initialize()
  File "/home/dongxueyang/Kratos/applications/DEM_application/python_scripts/main_script.py", line 266, in Initialize
    self.ReadModelParts()
  File "/home/dongxueyang/Kratos/applications/DEM_application/python_scripts/main_script.py", line 387, in ReadModelParts
    model_part_io_fem.ReadModelPart(self.rigid_face_model_part)
RuntimeError: Error: EXTERNAL_APPLIED_FORCE[3](0.0,0.0,-1000.0) is not a valid variable!!!
 [Line 159 ]
in kratos/sources/model_part_io.cpp:843:void ModelPartIO::ReadModelPartDataBlock(ModelPart&, bool)
   kratos/sources/model_part_io.cpp:849:void ModelPartIO::ReadModelPartDataBlock(ModelPart&, bool)
   kratos/sources/model_part_io.cpp:766:void ModelPartIO::ReadSubModelPartDataBlock(ModelPart&)
   kratos/sources/model_part_io.cpp:3035:void ModelPartIO::ReadSubModelPartBlock(ModelPart&, ModelPart&)
   kratos/sources/model_part_io.cpp:475:virtual void ModelPartIO::ReadModelPart(ModelPart&)

KRATOS TERMINATED WITH ERROR
There is no variable,should I update my Kratos?

**Comment by joaquinirazabal** [comment]
You wrote EXTERNAL_APPLIED_FORCE3

However, you have to put EXTERNAL_APPLIED_FORCE[3] (0.0,0.0,-1000.0)

I forgot to comment before that if the angular velocity is 0.0, it is not necessary to define the centre of mass and the inertias.

**Comment by fengzekang** [comment]
@joaquinirazabal Thanks,I will try it now.
I will tell you the result after I finish it.
Best regards

**Comment by fengzekang** [comment]
In fact,I forget the space in the EXTERNAL_APPLIED_FORCE [3] (0.0,0.0,-1000.0)
If there is not the space,there will be the error as what I got.

**Comment by fengzekang** [comment]
![screenshot from 2018-09-07 22-36-22](https://user-images.githubusercontent.com/38140045/45225399-0411bf80-b2ef-11e8-9e58-0a6acb72e572.png)
![screenshot from 2018-09-07 22-38-54](https://user-images.githubusercontent.com/38140045/45225618-8f8b5080-b2ef-11e8-8e61-77acc9533c3c.png)
![screenshot from 2018-09-07 22-48-28](https://user-images.githubusercontent.com/38140045/45225911-366fec80-b2f0-11e8-8e3b-dd2a7ad6fd98.png)
Dear @joaquinirazabal ,I have finished the test and then I visualize the result in the paraview.The first picture attached is shown as the step 0.04.The second shows that step 0.12.The top surface still going down.But what I want to do is just to keep the pressure on the top surface as 200kPa,and then there will be a constant pressure on the DEM particals.As shown in the third picture.
Did you have any ideas for this?
Best regards.
fengzekang

**Comment by fengzekang** [comment]
@maceligueta  @joaquinirazabal  @farrufat-cimne 
Everyone,in the test,can I add the increasing force over time,maybe if I add a force at a moment,there will be a mutation at the first.So I think we can add a gradient force.
And also,in the .json file,there are some parameters named "DeltaTimeSafetyFactor","MaxTimeStep","FinalTime","ControlTime"and"NeighbourSearchFrequency",what's the meaning of these parameters.Especially the "ControlTime" and "NeighbourSearchFrequency".
The final question is that when we add the external_applied_force on the rigid face,I note that we can control the time form start to stopl(VELOCITY_START_TIME, VELOCITY_SOP_TIME,)at there,is the stop_time same as the "FinalTime" we set in the .json file?It can not be bigger than the FinalTime,right?
Best regards.

**Comment by maceligueta** [comment]
Hi @fengzekang ,
from python you can impose a force as a function which depends on time (you can code it with ifs or whatever you want).
About those variables in the .json file, I admit that they are not very well chosen, but I will describe them here:

- "DeltaTimeSafetyFactor" -> only used for automatic time step, which is not used at the moment
- "MaxTimeStep" -> the time step used by the DEM (fixed)
- "FinalTime" -> the time at which the computation stops
- "ControlTime" -> number of seconds between screen messages informing about the progress of the computation
- "NeighbourSearchFrequency" -> number of time steps between searches of neighbours (1 means that neighbours are searched at every time step, but that's super expensive).

If you impose a force on a wall, you should not impose the velocity. We haven't tested much the possibility of imposing the velocity in some axes but imposing forces as well in other axes.

**Comment by fengzekang** [comment]
Dear @maceligueta Based on your reply,I have solve the problem.
But today,I want to add some new more parameters to output for the DEM particals and the FEM walls,just like the stress,angular velocity,total force on the particle,but there are not the result after I change the parameters from false to true in the .json file.
Is there any extra parameters in the default json file?I think some parameters should be delated because they are not useful at least for now.
Best regards.

**Comment by fengzekang** [comment]
Another question,I want to use the parallel computing,what should I do in the input files(Because I am doing a big test with more than 120000 elements),is there the guide to show that how to add the Parallel Computing in the test?
Best regards.

**Comment by maceligueta** [comment]
About the results that are not printed despite the activation in the json, they work for GID, not for Paraview yet. I remember that we coded the output for Paraview for you, but we did not put all the features that are present for GiD. However it is not difficult to code this feature, and any help will be very welcome.

**Comment by maceligueta** [comment]
For parallel computing you won't encounter any problem in using shared memory parallelism (OpenMP). You just need to set the value of the environment variable OMP_NUM_THREADS to the number you want. For instance, in linux:
export OMP_NUM_THREADS=12

**Comment by fengzekang** [comment]
Dear @maceligueta I have tested all the parameters.
1.For the DEM,there is not the CONTACT_FORCES results(contact_forces only for the FEM).
2.I find that Total_forces applied for all of the points,what is the real meaning at there?If I want to find the 'Force chain' in the model,which parameters can I use?
3.As for the parallel calculation,you said that I can set 'export OMP_NUM_THREADS=12',where should I add this command?(I find that in the terminal when I run the test,there are two lines showed that'  Parallelism Info: MPI number of nodes:1   Parallelism Info: OMP number of processors:8   '
Best regards.Wish you have a nice day.

**Comment by farrufat-cimne** [comment]
Hi fengzekang,

The option PostContactForces only shows forces on FEM, if you want to check the forces on the particles you should activate the PostTotalForces option.
About the OMP_NUM_THREADS env. variable, you can set it directly in the terminal prior to running the simulation or add 'export OMP_NUM_THREADS = n' in your script. for example:

import time
from glob import glob
export OMP_NUM_THREADS = 6
main_()

By default, the dem_application will use all the available threads in the system. If you want to run with less, the easiest way is to define it directly in the console before launching the case.

regards,

**Comment by fengzekang** [comment]
Dear @farrufat-cimne 
I have got the total_forces for all points,and I visualize the particle forces in the paraview.
As for the scrip file in which I can add the 'export OMP_NUM_THEREADS',I didn't find it.
the file in the Kratos/applications/DEMApplication/python_scrips/main_scrip ?
Best regards

**Comment by farrufat-cimne** [comment]
Hi, 
It will work if you define  OMP_NUM_THREADS in the main_script.py, although I wouldn't recommend modifying the application scripts directly. Maybe a customized launcher would be a cleaner idea.

regards,

**Comment by fengzekang** [comment]
@farrufat-cimne ![screenshot from 2018-09-14 23-13-01](https://user-images.githubusercontent.com/38140045/45559056-0b4b4700-b874-11e8-922d-1d92968d9a8e.png)
As for the total_forces,I put the results in the paraview.It is shown as the image.
I checked the .res file,I find that the value of data are small,part of these shown in the followed: 
Result "TOTAL_FORCES" "Kratos" 0.3999999999999641 Vector OnNodes
Values
1 -1.86968e-05 -1.80129e-05 -7.81385e-06
2 0 0 0
3 0 0 0
4 -0.000107556 3.24207e-05 -9.69657e-05
5 -1.63279e-05 -6.89832e-06 -0.000126589
6 0.00024074 4.91173e-06 -2.35595e-05
7 0.000562665 -7.31615e-05 0.0014282
8 0 0 0
9 -3.44165e-05 1.49835e-05 3.10252e-05
10 0.002087 6.32126e-05 0.000539796
11 0.000166716 -0.000121227 -2.42062e-05
12 -0.00137414 0.000100987 -0.000362779
13 -1.38078e-05 -1.29019e-05 1.24461e-06
14 4.44502e-06 -7.23198e-08 1.04682e-05
15 1.56333e-05 -2.41683e-05 0.000449187
16 0 0 0
17 0.000533612 -0.000172877 0.000770221
18 0 0 0

**Comment by fengzekang** [comment]
Dear @maceligueta @farrufat-cimne @joaquinirazabal 
I have a question for that is there a parameter and then we can get the normal_forces shear_forces for the DEM particle.I find that there is only the total_forces for the DEM particel, I can not get the force chain in the particles. We can add these(contact_force including normal_contact_force,shear_contact_force for the DEM) in these days if there is not the parameters until now.
Best regards

**Comment by maceligueta** [comment]
Hi @fengzekang , if we plot the resultant contact_forces on a sphere for a stable packing, they are 0.0. We are open to any implementation, but I think that the way to draw the force chains is not by just printing the 'contact-forces'. Maybe the sum of the modules of the contact forces with the neighbours? 
I have seen that graphic many times from other codes, but what are they exactly printing? Any publication with the details will be welcome.

**Comment by fengzekang** [comment]
Hi @maceligueta I have found the normal_forces and tangent_forces in the script which is named DEM_DHertz_viscous_Coulomb_CL.cpp.
![2018-09-19 16-04-26](https://user-images.githubusercontent.com/38140045/45739489-b7e74900-bc25-11e8-912e-fc567f2ad432.png)
![2018-09-19 16-09-10](https://user-images.githubusercontent.com/38140045/45739810-5ffd1200-bc26-11e8-98f1-f1515dcffc4d.png)
I want to get normal_forces and tangential_forces of the DEM particles in the .res files.Could you give me some suggestions or any other thoughts?
Best regards.

**Comment by maceligueta** [comment]
Dear @fengzekang , right now you can't export it to .res files (directly). We can change the code a little bit so we can print it. However, the contact force is different for each neighbour. Then, for a dense packing in equilibrium, if you sum up all the contact forces on a sphere, they sum 0.0. So, if you print the contact forces on the spheres, you will see 0.0 everywhere.
I think that you would be interested in the contact_force at the bonds (contacts), instead. If you print the bonds, and then you print the contact force on the bond, you will have the force chains. However, for the simple DEM computed with spheric particles, we are not using the bonds for anything (so far) and therefore we cannot print them. We should find some value to be printed on the sphere that represents something similar to the force chain.

**Comment by fengzekang** [comment]
Dear @maceligueta ,I know that the total_forces on the DEM is 0.0.But in the process of calculation,we calculated the tangential_force and normal_foece of DEM.I think we can export it(But I don't know how to do it until now,maybe I am wrong)
With your suggestion,I will also find another value on the sphere to represent the force chain.
Best regards.

**Comment by philbucher** [comment]
Closing since inactive 
Please reopen if still needed

**Comment by maceligueta** [comment]
This is addressed in PR #3298. We can leave the issue closed anyways.

**Comment by maceligueta** [comment]
Dear @fengzekang , the pull request #3298 added the possibility of drawing the bonds between spheres. I think this new feature could help you at drawing the force chains.

**Comment by fengzekang** [comment]
@maceligueta Wow Thanks so much for your attention. I will check that few days later. In addition，will You add the tetrahedron element in the DEM application. I think it is important to simulate the real rock and others.And also it is different from the cluster of spheres.
Best regards

**Comment by maceligueta** [comment]
The polyhedra are in the list for long term developments, I would not expect it soon in Kratos...
