### ISSUE TITLE
ProcessInfo is not being passed to Initialize of Elements/Conditions

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2817]
@KratosMultiphysics/technical-committee 

Title says all. Is this intentional? I was having some minor issues with this in #2349 

I see that it is a but a pain to change but maybe it would be a good thing to do bcs it is being passed to pretty much all the other functions too

**Comment by maceligueta** [comment]
As far as I remember from conversations with @RiccardoRossi some years back, it was intentional. Anyways, the Technical Committe will discuss this issue and post an official answer here.

**Comment by RiccardoRossi** [comment]
I don't remember the details, i do remember there were some issues. However i am not opposing this change...

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee: To be passed to initialize. @philbucher you may proceed with it

**Comment by philbucher** [comment]
done in #4938
