### ISSUE TITLE
[AMatrix] Update EigenSolversApplication

### ISSUE THREAD

**Issue by oberbichler** [KratosMultiphysics/Kratos#2842]
Just to get an idea about necessary changes:

**Direct solvers:**
They are only using sparse matrices. I guess we shoud keep the ublas types since AMatrix does not support sparse matrices at the moment(?). For the right-hand-side: is it safe to mix ublas with AMatrix or should we also keep the ublas vectors?

**Eigensystem solver:**
Same as for the direct solvers. Internally we are also using dense matrices. At the moment we use the Eigen types. That still makes sense since we are using them together with the `Eigen::GeneralizedSelfAdjointEigenSolver`.

**Comment by armingeiser** [comment]
I think in the EigenSolversApplication no change is necessary, for the reason you mentioned @oberbichler. 
Lets wait for the experts opinions on your questions though.

**Comment by pooyan-dadvand** [comment]
As @oberbichler mentioned AMatrix doesn’t have sparse matrix yet. 

The matrix of ublas cannot be mixed with AMatrix vector in space

**Comment by pooyan-dadvand** [comment]
But does it compiled with AMatrix as it is?

**Comment by oberbichler** [comment]
No. But even the core with all Apps=Off does not compile

**Comment by oberbichler** [comment]
Found the error...

**Comment by oberbichler** [comment]
#2965
