### ISSUE TITLE
[Core][DoF]Removing Pointers to dofs

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#2847]
@pooyan-dadvand this is a reminder to remove Dof::Pointer from node so to reduce memory usage

**Comment by philbucher** [comment]
also reminder to try to remove the `EquationIdVector` after this

**Comment by philbucher** [comment]
can this be closed?

**Comment by pooyan-dadvand** [comment]
Yes, it is done in the Node memory reductions
