### ISSUE TITLE
Pybind11 produces many deprecation warnings when compiling with Python 3.7

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#2867]
As it says on the title. This makes it hard to detect real kratos warnings in compilation output.

Apparently pybind developers have already solved it (https://github.com/pybind/pybind11/issues/1444) so I'd like to ask the @KratosMultiphysics/technical-committee permission to update the pybind version in this repo.

**Comment by RiccardoRossi** [comment]
+1 on my side

**Comment by loumalouomega** [comment]
Remember that we "patched" the pybind, @roigcarlo do you remember what we changed?

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/commit/7960333336aa139ed227bc53fb9bd50f04c859d2 Ok it was this, take care

**Comment by philbucher** [comment]
> 
> 
> [7960333](https://github.com/KratosMultiphysics/Kratos/commit/7960333336aa139ed227bc53fb9bd50f04c859d2) Ok it was this, take care

just for the record, I updated all of Kratos, so this hack should no longer be necessary

**Comment by pooyan-dadvand** [comment]
> just for the record, I updated all of Kratos, so this hack should no longer be necessary

I'm not sure if all the non public ones have made the change.... @KratosMultiphysics/altair?

**Comment by ddiezrod** [comment]
@pooyan-dadvand  We do not have this change, in our core we still have:

`using size_t  = std::size_t;
`

Should we change this?

**Comment by jcotela** [comment]
@ddiezrod I think that the important part is that, in the `add_..._to_python` files of your applications, you use `namespace py = pybind11;` instead of `using namespace pybind11;`. This was the source of the name clash with `std::size_t`.

**Comment by jrubiogonzalez** [comment]
Is this a change we can perform right now with our current Pybind version or it has to be done when pybind is updated?

**Comment by jcotela** [comment]
It can be done right now.

**Comment by philbucher** [comment]
> @ddiezrod I think that the important part is that, in the `add_..._to_python` files of your applications, you use `namespace py = pybind11;` instead of `using namespace pybind11;`. This was the source of the name clash with `std::size_t`.

It actually would be nice if you could do it soon. It is not much work, here is an example what is to be done (~10min/Application)
https://github.com/KratosMultiphysics/Kratos/pull/3270/files?utf8=%E2%9C%93&diff=split&w=1

**Comment by ddiezrod** [comment]
@jcotela @philbucher Ok, we will take care of that. Thanks !
