### ISSUE TITLE
segfault in enrichment utilities

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#287]
the function CalculateEnrichedShapeFuncions on line 482 of enrichment_utilities.h

is segfaulting on line 842 since the method accesses to the second row of GradientValues.
According to the description and to the documentation GradientValues should have only one row.

@pablobecker @juliobarna any hint of why this is done so? is it simply a mistake (possibly mine)?

**Comment by pablobecker** [comment]
I'll take a look

**Comment by pablobecker** [comment]
Hello again,
I checked and this was a modification that I did a couple of years ago (it is consistent, Nenriched has two columns). The second enrichment shape function is a jump ( negative partitions have their gradients and Nenriched multiplied by -1 ). Do you want me to resize the matrices at initialization to make sure they have the right size?

**Comment by RiccardoRossi** [comment]
@pablobecker 
then as a very minimum the doc string of the function should be changed. 
also please check the code because a few lines above it is initialized just one of the rows and not the second

**Comment by RiccardoRossi** [comment]
@pablobecker concerning the resize, my problem is that until now the resizing has been done on the outside. I am not sure if this was the right choice, however if you now change the behaviour you will silently break the code that is using it. For this reason i would suggest something of the type

     #ifdef KRATOS_DEBUG
          ...here check that the sizes are correct
     #endif

**Comment by pablobecker** [comment]
Can't I just re-resize it inside, after you've done it ouside?

**Comment by RiccardoRossi** [comment]
if you resize you lose the inner data (unless you copy it, which is sort of expensive).

**Comment by pablobecker** [comment]
then it would be still ok, after all this is an argument by reference, you expect me to modify it and give you the right values.

**Comment by RiccardoRossi** [comment]
nope it is not for two reasons:

1. if outside i resized it then i may well have assumed it has size 1 on each gauss point (as the documentation was telling). 
2. you silently made the code slower since resizing is being done twice. I would prefer my code to be broken so at least i know i am doing something badly.

actually for the future we should really care not to change "silently" the behaviour of this type of functions...

**Comment by RiccardoRossi** [comment]
@pablobecker can se closed This?

**Comment by pooyan-dadvand** [comment]
ping @pablobecker

**Comment by pablobecker** [comment]
@rubenzorrilla told that the enrichment utils were being reimplemented. Will this be on time for this relase, or do I have to fix this for this version?

**Comment by rubenzorrilla** [comment]
@pablobecker, due to scheduling reasons, we will not include the reimplementation of the splitting & enrichment for this release. So you need to fix the old ones...

**Comment by pablobecker** [comment]
Ok, I'll take care of it, thanks

**Comment by pooyan-dadvand** [comment]
Thanks! :+1:

**Comment by RiccardoRossi** [comment]
the current implementations sidestep this bug. Also there is upcoming replacement by @rubenzorrilla and @pablobecker is out of combat within the release windows. 

I am taking this out from the release process, that is, we'll live with it in the current release. If someone is strongly against just vocalize it

**Comment by RiccardoRossi** [comment]
this will be superseded by the new version of @rubenzorrilla. closing
