### ISSUE TITLE
Compilation of Pastix slow down SuperLU solver

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#288]
Yesterday I compiled for first time the Pastix Solver, which is much faster than the SuperLU, but I realized that the tests of my application (all of them are using SuperLU) are now 20x times slower than without compiling the Pastix. The only thing that I am not doing standard is the compilation of pastix with shared libraries (without them I am not able to compile Kratos). But this is not supposed to affect all the performance of the others solvers.

[pastix_compiled.pdf](https://github.com/KratosMultiphysics/Kratos/files/922112/pastix_compiled.pdf)
[no_patix_compiled.pdf](https://github.com/KratosMultiphysics/Kratos/files/922113/no_patix_compiled.pdf)

**Comment by RiccardoRossi** [comment]
Which Blas are u using?

Endure they are compiled WITHOUT openmp.

**Comment by loumalouomega** [comment]
Do you mean the pastix is compiled without openmp?, how do I check that?

**Comment by RiccardoRossi** [comment]
The performance of directe solvers, and in particualr of SuperLU depend a lot on the blas library you are employing. A lot of high-performance blas libraries are internally parallelized using OpenMP or some other threading mechanism. You should use  a "serial" blas implementation.

**Comment by loumalouomega** [comment]
The thing is that the only thing I am doing is activating the flag of pastix in the configure.sh, am I changing the blas library because I am compiling an additional solver?

**Comment by RiccardoRossi** [comment]
Pastor and Superliga both link in Blas. If you have two different Blas the symbols of one may override the other...

Other than that i honestly don t have a clientes of what could be the issue...

Riccardo

**Comment by RiccardoRossi** [comment]
No, i mean Blas compiled WITHOUT openmp

**Comment by loumalouomega** [comment]
Still not working

**Comment by loumalouomega** [comment]
I solved the problem, I am updating the Wiki, I close this issue.
