### ISSUE TITLE
[core] A process includes pybind (indirectly)

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#2880]
See
https://github.com/KratosMultiphysics/Kratos/blob/c9ef5ca3c53c3f8669858c88445bd9f7a4e8f55b/kratos/processes/assign_scalar_field_to_conditions_process.h#L24
which leads to 
https://github.com/KratosMultiphysics/Kratos/blob/c9ef5ca3c53c3f8669858c88445bd9f7a4e8f55b/kratos/utilities/python_function_callback_utility.h#L16

This is just a reminder of what was discussed in #2576, where @RiccardoRossi said that processes should not include Pybind.

**Comment by loumalouomega** [comment]
If we need to define a python function how are we supposed to do it?

**Comment by RiccardoRossi** [comment]
@maceligueta... you are right, i guess that the callback is the one
exception to the rule...

if you see the callback is in the python directory.

just, let s avoid making other callback functions.

Riccardo

**Comment by maceligueta** [comment]
Closing then.
