### ISSUE TITLE
Error in Kratos Pfem application while compling

### ISSUE THREAD

**Issue by BilalTsinghua** [KratosMultiphysics/Kratos#2895]
@roigcarlo 
[ 49%] Built target KratosSolidMechanicsApplication
make[2]: *** No rule to make target 'applications/PfemApplication/CMakeFiles/external_tetgen.dir/build'.  Stop.
CMakeFiles/Makefile2:815: recipe for target 'applications/PfemApplication/CMakeFiles/external_tetgen.dir/all' failed
make[1]: *** [applications/PfemApplication/CMakeFiles/external_tetgen.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
When i am compling the kratos Pfem application in my computer, it shows the above mention error.

**Comment by josep-m-carbonell** [comment]
To compile the pfem application you must checkout the master branch or the pfem/develop branch. It seems like your kratos version is not up to date. Now the tetgen submodule is located in the DelaunayMeshingApplication. You can check it looking at its external_modules folder. In the compilation options (cmake configure file) you must set:
-DDELAUNAY_MESHING_APPLICATION=ON
-DPFEM_FLUID_DYNAMICS_APPLICATION=ON
For pfem fluids only. If you want the general pfem for fluids and solids: 
-DDELAUNAY_MESHING_APPLICATION=ON
-DCONSTITUTIVE_MODELS_APPLICATION=ON
-DSOLID_MECHANICS_APPLICATION=ON
-DCONTACT_MECHANICS_APPLICATION=ON
-DPFEM_APPLICATION=ON

**Comment by BilalTsinghua** [comment]
Dear @josep-m-carbonell 
Thanks for your reply.I have updated the Kratos with 'git pull' And then I changed the configure.sh followed your suggestion.But there are more errors after I recompile the file.As followed:
-- Found Git: /usr/bin/git (found version "2.7.4") 
additional default options were set for gcc
CMAKE_CXX_FLAGS =  -msse3 -std=c++11 -funroll-loops -Wall -std=c++11 -Wsuggest-override
CMAKE_C_FLAGS =  -msse3 -funroll-loops -Wall
KRATOS_BUILD_TESTING not defined. Setting to ON
-- Found PythonInterp: /usr/bin/python3 (found version "3.5.2") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.5m.so
-- Performing Test HAS_CPP14_FLAG
-- Performing Test HAS_CPP14_FLAG - Success
KRATOS_EXCLUDE_OPENMP
OpenMP included
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Boost version: 1.68.0
Boost Include: /home/bilal/boost_1_68_0
Boost Linkdir: 
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- A library with BLAS API found.
linker flags with blas =
BLA_VENDOR = All
-- A library with BLAS API found.
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
LAPACK = /usr/lib/liblapack.so/usr/lib/libblas/libblas.so.3.6.0
LAPACK modified = /usr/lib/lapack/liblapack.so.3.6.0/usr/lib/libblas/libblas.so.3.6.0
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Preparing local ZLIB compilation.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
AMatrix not found. Please define the AMATRIX_DIR pointing to the AMatrix root directory.
 
CMAKE_BUILD_TYPE ........ Release
 
WARNING: YOUR GIDPOST IS BEING COMPILED  WITHOUT DEBUG (ALL ASSERTS WILL BE AVOIDED)
-- Performing Test HAS_FLTO
-- Performing Test HAS_FLTO - Success
-- LTO enabled
 
 
***** LIST OF KRATOS APPLICATIONS THAT ARE GOING TO BE COMPILED: *****
 
                CONVECTION_DIFFUSION_APPLICATION - ON
                STRUCTURAL_MECHANICS_APPLICATION - ON
                SOLID_MECHANICS_APPLICATION - ON
                CONTACT_MECHANICS_APPLICATION - ON
                CONSTITUTIVE_MODELS_APPLICATION - ON
                FLUID_DYNAMICS_APPLICATION - ON
                FSI_APPLICATION - ON
                MIXED_ELEMENT_APPLICATION - ON
                PFEM_APPLICATION - ON
                PFEM_FLUID_DYNAMICS_APPLICATION - ON
                EXTERNAL_SOLVERS_APPLICATION - ON
                MESHING_APPLICATION - ON
 
**********************************************************************
 
********** LIST OF KRATOS APPLICATIONS THAT ARE SET TO OFF: **********
 
                STRUCTURAL_APPLICATION - OFF
                INCOMPRESSIBLE_FLUID_APPLICATION - OFF
                DEM_APPLICATION - OFF
                SWIMMING_DEM_APPLICATION - OFF
                OPENCL_APPLICATION - OFF
                TRILINOS_APPLICATION - OFF
                METIS_APPLICATION - OFF
                SHAPE_OPTIMIZATION_APPLICATION - OFF
                TOPOLOGY_OPTIMIZATION_APPLICATION - OFF
                MAPPING_APPLICATION - OFF
                HDF5_APPLICATION - OFF
 
**********************************************************************
 
 
**** configuring KratosExternalSolversApplication ****
**** configuring KratosSolidMechanicsApplication ****
**** configuring KratosPfemApplication ****
**** configuring KratosPfemFluidDynamicsApplication ****
**** configuring KratosContactMechanicsApplication ****
**** configuring KratosConstitutiveModelsApplication ****
**** configuring KratosConvectionDiffusionApplication ****
**** configuring KratosMeshingApplication ****
**** configuring KratosStructuralMechanicsApplication ****
**** configuring KratosFluidDynamicsApplication ****
**** configuring KratosFSIApplication ****
**** configuring KratosMixedElementApplication ****
CMake Warning (dev) at applications/MixedElementApplication/CMakeLists.txt:21 (target_link_libraries):
  Policy CMP0023 is not set: Plain and keyword target_link_libraries
  signatures cannot be mixed.  Run "cmake --help-policy CMP0023" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  The keyword signature for target_link_libraries has already been used with
  the target "KratosMixedElementApplication".  All uses of
  target_link_libraries with a target should be either all-keyword or
  all-plain.

  The uses of the keyword signature are here:

   * cmake_modules/pybind11Tools.cmake:107 (target_link_libraries)

This warning is for project developers.  Use -Wno-dev to suppress it.

*****************************************************************************-------------******** /home/bilal/Kratos/external_libraries/triangle
python libraries to be installed are: /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
--------------------------------  standard install dir /home/bilal/Kratos
installed blas = /usr/lib/libblas/libblas.so.3.6.0
installed lapack = /usr/lib/lapack/liblapack.so.3.6.0/usr/lib/libblas/libblas.so.3.6.0
-- Configuring done
CMake Error at applications/PfemApplication/CMakeLists.txt:57 (add_library):
  Cannot find source file:

    /home/bilal/Kratos/applications/PfemApplication/external_modules/tetgen/tetgen.cxx

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: Cannot determine link language for target "external_tetgen".
CMake Error: CMake can not determine linker language for target: external_tetgen
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ALE_APPLICATION
    DELAUNAY_MESHING_APPLICATION
    MKLSOLVER_INCLUDE_DIR
    MKLSOLVER_LIB_DIR
    MKL_SOLVERS_APPLICATION
    PARMETIS_ROOT_DIR
    TRILINOS_ROOT


-- Build files have been written to: /home/bilal/Kratos/cmake_build
[  4%] Built target zlib
[  5%] Built target zlibstatic
make[2]: *** No rule to make target 'applications/PfemApplication/CMakeFiles/external_tetgen.dir/build'.  Stop.
CMakeFiles/Makefile2:812: recipe for target 'applications/PfemApplication/CMakeFiles/external_tetgen.dir/all' failed
make[1]: *** [applications/PfemApplication/CMakeFiles/external_tetgen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 13%] Built target superlu
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
[  2%] Built target zlib
[  2%] Built target minigzip
[  2%] Built target example
[  5%] Built target zlibstatic
[  6%] Built target example64
[  6%] Built target minigzip64
[  7%] Built target gidpost
[ 27%] Built target KratosCore
[ 32%] Built target Kratos
[ 40%] Built target superlu
[ 41%] Built target KratosExternalSolversApplication
[ 53%] Built target KratosSolidMechanicsCore
[ 55%] Built target KratosSolidMechanicsApplication
make[2]: *** No rule to make target 'applications/PfemApplication/CMakeFiles/external_tetgen.dir/build'.  Stop.
CMakeFiles/Makefile2:812: recipe for target 'applications/PfemApplication/CMakeFiles/external_tetgen.dir/all' failed
make[1]: *** [applications/PfemApplication/CMakeFiles/external_tetgen.dir/all] Error 2
Makefile:116: recipe for target 'all' failed
make: *** [all] Error 2
I have attached my configure.sh file.
[congigure.txt](https://github.com/KratosMultiphysics/Kratos/files/2395718/congigure.txt)

**Comment by BilalTsinghua** [comment]
The file attached is configure.sh,but I can't select it at there so I exchange it from .sh to .txt.
The contents as followed:
#!/bin/sh

# this is an example file...please DO NOT MODIFY if you don't want to do it for everyone
#to use it, copy it to another file and run it

# additional compiler flags could be added customizing the corresponding var, for example
# -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 ". Note that the "defaults are already correctly coded"
#so we should ass here only machine specific stuff

#an effort is made to autodetect all of the libraries needed HOWEVER:
#METIS_APPLICATION needs the var PARMETIS_ROOT_DIR to be specified by the user (not needed if the app is set to OFF)
#TRILINOS_APPLICATION needs the var PARMETIS_ROOT_DIR to be specified by the user (not needed if the app is set to OFF)
#MKL_SOLVERS_APPLICATION needs the var MKLSOLVER_INCLUDE_DIR and MKLSOLVER_LIB_DIR to be specified by the user (not needed if the app is set to OFF)
#note that the MKLSOLVER_LIB_DIR should include /lib/em64t. This is needed as intel is changing location of mkl at every update of the compiler!!

#the user should also note that the symbol "\" marks that the command continues on the next line. IT SHOULD ONLY BE FOLLOWED
#BY the "ENTER" and NOT by any space!!

clear

#you may want to decomment this the first time you compile
rm CMakeCache.txt
rm *.cmake
rm -rf CMakeFiles\
#export BOOST_ROOT=/path/to/your/boost
cmake ..	                                          \
-DCMAKE_C_COMPILER=/usr/bin/gcc		                  \
-DCMAKE_CXX_COMPILER=/usr/bin/g++	                     \
-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 -std=c++11 "    \
-DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -msse3 "           \
-DBOOST_ROOT="/home/bilal/boost_1_68_0"             \
-DPYTHON_EXECUTABLE="/usr/bin/python3"                      \
-DCMAKE_BUILD_TYPE=Release  			           \
-DMESHING_APPLICATION=ON 		                      \
-DEXTERNAL_SOLVERS_APPLICATION=ON                                 \
-DSOLID_MECHANICS_APPLICATION=ON   			    \
-DFLUID_DYNAMICS_APPLICATION=ON 	                    \
-DCONVECTION_DIFFUSION_APPLICATION=ON 		          \
-DDEM_APPLICATION=OFF	                                  \
-DSWIMMING_DEM_APPLICATION=OFF                              \
-DINCOMPRESSIBLE_FLUID_APPLICATION=OFF  		                  \
-DSTRUCTURAL_APPLICATION=OFF 		                      \
-DSTRUCTURAL_MECHANICS_APPLICATION=ON 		          \
-DPFEM_APPLICATION=ON                                  \
-DDELAUNAY_MESHING_APPLICATION=ON                        \
-DPFEM_FLUID_DYNAMICS_APPLICATION=ON                    \
-DCONSTITUTIVE_MODELS_APPLICATION=ON                     \
-DCONTACT_MECHANICS_APPLICATION=ON                          \
-DALE_APPLICATION=ON 		                                 \
-DFSI_APPLICATION=ON 		                                \
-DMAPPING_APPLICATION=OFF 		                      \
-DOPENCL_APPLICATION=OFF	                                 \
-DMIXED_ELEMENT_APPLICATION=ON	                                \
-DMKL_SOLVERS_APPLICATION=OFF	                                      \
-DMKLSOLVER_INCLUDE_DIR="/opt/intel/Compiler/11.1/072/mkl/include"	      \
-DMKLSOLVER_LIB_DIR="/opt/intel/Compiler/11.1/072/mkl/lib/em64t"	      \
-DMETIS_APPLICATION=OFF		                                          \
-DPARMETIS_ROOT_DIR="/home/fengzekang/compiled_libraries/ParMetis-3.1.1"      \
-DTRILINOS_APPLICATION=OFF	                                        \
-DTRILINOS_ROOT="/home/fengzekang/compiled_libraries/trilinos-10.2.0"	     \
-DINSTALL_EMBEDDED_PYTHON=ON                                           \
-DSHAPE_OPTIMIZATION_APPLICATION=OFF \
-DTOPOLOGY_OPTIMIZATION_APPLICATION=OFF \
-DHDF5_APPLICATION=OFF \


#decomment this to have it verbose
#make VERBOSE=1 -j4
make  -j2
make install

**Comment by josep-m-carbonell** [comment]
Try to "make clean". It is still taking the CmakeFile of the old Pfem Apliccation. Also look into the configure.sh to detect some  trailing white space. Delaunay Application is not detected as ON.

**Comment by lluis-mv** [comment]
Hey, I think this error is related to tetgen. (tetgen is not donwloaded automatically). 
In a terminal you may donwload these submodules by typing: 
"git submodule init
git submodule update"

**Comment by fengzekang** [comment]
Hello, @josep-m-carbonell ,how to Delaunay Application in the configure.sh file.
I add the -DDELAUNAY_MESHING_APPLICATION=ON  But when I compile the file,there is no information showing that compiling Delaunay Application.
And then I run the example Test_3D_Newtonian_Sloshing,some erorrs showed that
Traceback (most recent call last):
  File "MainKratos.py", line 3, in <module>
    import KratosMultiphysics.DelaunayMeshingApplication
ImportError: No module named 'KratosMultiphysics.DelaunayMeshingApplication'
KRATOS TERMINATED WITH ERROR
So what should I do to add the DelaunayMeshingApplication?
Best regards

**Comment by josep-m-carbonell** [comment]
cmake additions must be in the same line, so look at the configure.sh to have the corresponding \ before adding the Delaunay app and exist no extra space after the \  It must be compiled to be imported by python

**Comment by fengzekang** [comment]
Dear @josep-m-carbonell 
I think I have add the application in the configure.sh file,the configure.sh as followed:
clear

#you may want to decomment this the first time you compile
rm CMakeCache.txt
rm *.cmake
rm -rf CMakeFiles\
#export BOOST_ROOT=/path/to/your/boost
cmake ..	                                          \
-DCMAKE_C_COMPILER=/usr/bin/gcc		                  \
-DCMAKE_CXX_COMPILER=/usr/bin/g++	                     \
-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 -std=c++11 "    \
-DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -msse3 "           \
-DBOOST_ROOT="/home/dongxueyang/Downloads/boost_1_61_0"             \
-DPYTHON_EXECUTABLE="/usr/bin/python3"                      \
-DCMAKE_BUILD_TYPE=Release  			           \
-DMESHING_APPLICATION=ON 		                      \
-DEXTERNAL_SOLVERS_APPLICATION=ON                                 \
-DSOLID_MECHANICS_APPLICATION=ON   			    \
-DFLUID_DYNAMICS_APPLICATION=ON 	                    \
-DCONVECTION_DIFFUSION_APPLICATION=ON 		          \
-DDEM_APPLICATION=ON	                                  \
-DSWIMMING_DEM_APPLICATION=ON                               \
-DINCOMPRESSIBLE_FLUID_APPLICATION=OFF  		                  \
-DSTRUCTURAL_APPLICATION=OFF 		                      \
-DSTRUCTURAL_MECHANICS_APPLICATION=ON 		          \
-DPFEM_APPLICATION=ON                                  \
-DPFEM_FLUID_DYNAMICS_APPLICATION=ON 	                    \
-DDELAUNAY_MESHING_APPLICATION=ON                                    \
-DCONSTITUTIVE_MODELS_APPLICATION=ON                          \
-DALE_APPLICATION=ON 		                                 \
-DFSI_APPLICATION=ON 		                                \
-DMAPPING_APPLICATION=OFF 		                      \
-DOPENCL_APPLICATION=OFF	                                 \
-DMIXED_ELEMENT_APPLICATION=ON	                                \
-DMKL_SOLVERS_APPLICATION=OFF	                                      \
-DMKLSOLVER_INCLUDE_DIR="/opt/intel/Compiler/11.1/072/mkl/include"	      \
-DMKLSOLVER_LIB_DIR="/opt/intel/Compiler/11.1/072/mkl/lib/em64t"	      \
-DMETIS_APPLICATION=OFF		                                          \
-DPARMETIS_ROOT_DIR="/home/fengzekang/compiled_libraries/ParMetis-3.1.1"      \
-DTRILINOS_APPLICATION=OFF	                                        \
-DTRILINOS_ROOT="/home/fengzekang/compiled_libraries/trilinos-10.2.0"	     \
-DINSTALL_EMBEDDED_PYTHON=ON                                           \
-DSHAPE_OPTIMIZATION_APPLICATION=OFF \
-DTOPOLOGY_OPTIMIZATION_APPLICATION=OFF \
-DHDF5_APPLICATION=ON \
#decomment this to have it verbose
#make VERBOSE=1 -j4
make  -j4
make install

But there is not the Delaunay application in the compiling.Should I download any other software or package?
Best regards

**Comment by josep-m-carbonell** [comment]
If you have alredy downloaded the submodule:
git submodule init
git submodule update

Pull (update) changes in master and try to add this two lines to the configure.sh

-DCONTAC_MECHANICS_APPLICATION=ON
-DADD_DEPENDENT_APPLICATIONS=ON

If it doesn't work. Please, attach the text file with the compilation output to see if any error ocurrs during the compilation.

**Comment by fengzekang** [comment]
Dear @josep-m-carbonell 
After I add the commands -DCONTACT_MECHANICS_APPLICATION=ON
-DADD_DEPENDENT_APPLICATIONS=ON ,contact_mechanics_application has been compiled,but cmake didn't find the ADD_DEPENDENT_APPLICATIONS
In the terminal:
CMake Warning:
  Manually-specified variables were not used by the project:

    ADD_DEPENDENT_APPLICATIONS
    ALE_APPLICATION
    MKLSOLVER_INCLUDE_DIR
    MKLSOLVER_LIB_DIR
    MKL_SOLVERS_APPLICATION
    PARMETIS_ROOT_DIR
    TRILINOS_ROOT

It doesn't work.

**Comment by josep-m-carbonell** [comment]
cmake didn't find the ADD_DEPENDENT_APPLICATIONS, because you have not updated  the Kratos branch via git, it is a new feature. You can delete ADD_DEPENDENT_APPLICATIONS if is not working now. Pfem application needs:

-DEXTERNAL_SOLVERS_APPLICATION=ON
-DSOLID_MECHANICS_APPLICATION=ON
-DCONSTITUTIVE_MODELS_APPLICATION=ON
-DCONTACT_MECHANICS_APPLICATION=ON
-DDELAUNAY_MESHING_APPLICATION=ON
-DPFEM_APPLICATION=ON
-DPFEM_FLUID_DYNAMICS_APPLICATION=ON

I think you have all of them in your configure.sh. If it compiles correctly, then, when you import KratosMultiphysics, or when you import KatosMultiphysics.DelaunayMeshingApplication from python, no error must appear.
So please, attach the compilation text and the error you got to have a little bit more of information about what is happening.

**Comment by fengzekang** [comment]
Dear  @josep-m-carbonell 
[compile_configure.sh.txt](https://github.com/KratosMultiphysics/Kratos/files/2428838/compile_configure.sh.txt)
I added all of them in the configure.sh,and the information as followed,we can see that there is also the cmake warnings:
CMake Warning:
  Manually-specified variables were not used by the project:

    ADD_DEPENDENT_APPLICATIONS
    ALE_APPLICATION
    DELAUNAY_MESHING_APPLICATION
    MKLSOLVER_INCLUDE_DIR
    MKLSOLVER_LIB_DIR
    MKL_SOLVERS_APPLICATION
    PARMETIS_ROOT_DIR
    TRILINOS_ROOT
No errors occured.I can't find the reason.
As what you said,I have updated the submodule in the Kratos use"git pull".
Best regards.

**Comment by josep-m-carbonell** [comment]
You are right, it is very strange. Without delaunay application Pfem must not compile.

Take a look on  Kratos/applications/CMakeLists.txt
 it must be like this one: 
[CMakeLists.txt.zip](https://github.com/KratosMultiphysics/Kratos/files/2429020/CMakeLists.txt.zip)

try to:
make clean
sh configure.sh

**Comment by fengzekang** [comment]
I tried to recompile with your suggestion,"make clean",and then "sh configure.sh",But cmake warning also includes:CMake Warning:
  Manually-specified variables were not used by the project:

    ADD_DEPENDENT_APPLICATIONS
    ALE_APPLICATION
    DELAUNAY_MESHING_APPLICATION
    MKLSOLVER_INCLUDE_DIR
    MKLSOLVER_LIB_DIR
    MKL_SOLVERS_APPLICATION
    PARMETIS_ROOT_DIR
    TRILINOS_ROOT
I think I can try it on another computer.
Best regards

**Comment by fengzekang** [comment]
Dear @josep-m-carbonell 
Do you have time to deal with the problem with me?We can use the teamviewer.Do you have time help me check the problem?
Best regards

**Comment by josep-m-carbonell** [comment]
Hi @fengzekang. Yes I have time.  We can do it next week, on Monday. I'm in Barcelona, please send me an email and propose the hour. cpuigbo@cimne.upc.edu.

**Comment by fengzekang** [comment]
Dear @josep-m-carbonell  
Ok,thanks for your help.I will send you my ID of teamviewer.
Best regards

**Comment by BilalTsinghua** [comment]
> Dear @josep-m-carbonell
> I think I have add the application in the configure.sh file,the configure.sh as followed:
> clear
> 
> #you may want to decomment this the first time you compile
> rm CMakeCache.txt
> rm *.cmake
> rm -rf CMakeFiles
> #export BOOST_ROOT=/path/to/your/boost
> cmake ..	
> -DCMAKE_C_COMPILER=/usr/bin/gcc	
> -DCMAKE_CXX_COMPILER=/usr/bin/g++	
> -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 -std=c++11 " 
> -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -msse3 " 
> -DBOOST_ROOT="/home/dongxueyang/Downloads/boost_1_61_0" 
> -DPYTHON_EXECUTABLE="/usr/bin/python3" 
> -DCMAKE_BUILD_TYPE=Release 
> -DMESHING_APPLICATION=ON 
> -DEXTERNAL_SOLVERS_APPLICATION=ON 
> -DSOLID_MECHANICS_APPLICATION=ON 
> -DFLUID_DYNAMICS_APPLICATION=ON 
> -DCONVECTION_DIFFUSION_APPLICATION=ON 
> -DDEM_APPLICATION=ON	
> -DSWIMMING_DEM_APPLICATION=ON 
> -DINCOMPRESSIBLE_FLUID_APPLICATION=OFF 
> -DSTRUCTURAL_APPLICATION=OFF 
> -DSTRUCTURAL_MECHANICS_APPLICATION=ON 
> -DPFEM_APPLICATION=ON 
> -DPFEM_FLUID_DYNAMICS_APPLICATION=ON 
> -DDELAUNAY_MESHING_APPLICATION=ON 
> -DCONSTITUTIVE_MODELS_APPLICATION=ON 
> -DALE_APPLICATION=ON 
> -DFSI_APPLICATION=ON 
> -DMAPPING_APPLICATION=OFF 
> -DOPENCL_APPLICATION=OFF	
> -DMIXED_ELEMENT_APPLICATION=ON	
> -DMKL_SOLVERS_APPLICATION=OFF	
> -DMKLSOLVER_INCLUDE_DIR="/opt/intel/Compiler/11.1/072/mkl/include"	
> -DMKLSOLVER_LIB_DIR="/opt/intel/Compiler/11.1/072/mkl/lib/em64t"	
> -DMETIS_APPLICATION=OFF	
> -DPARMETIS_ROOT_DIR="/home/fengzekang/compiled_libraries/ParMetis-3.1.1" 
> -DTRILINOS_APPLICATION=OFF	
> -DTRILINOS_ROOT="/home/fengzekang/compiled_libraries/trilinos-10.2.0"	
> -DINSTALL_EMBEDDED_PYTHON=ON 
> -DSHAPE_OPTIMIZATION_APPLICATION=OFF 
> -DTOPOLOGY_OPTIMIZATION_APPLICATION=OFF 
> -DHDF5_APPLICATION=ON 
> #decomment this to have it verbose
> #make VERBOSE=1 -j4
> make -j4
> make install
> 
> But there is not the Delaunay application in the compiling.Should I download any other software or package?
> Best regards

**Comment by josep-m-carbonell** [comment]
Hello @BilalTsinghua, could you finally compile the Kratos with Pfem?

**Comment by BilalTsinghua** [comment]
@josep-m-carbonell  yes i already complied it with Pfem
Thanks for your help

**Comment by josep-m-carbonell** [comment]
You are welcome. I recommend you before running examples to update with last changes and compile again.
In Kratos folder:
git pull
In cmake_build folder: 
sh configure.sh  (with sudo if you have compiled the first time with sudo) 

The compilation have to be fast this time.

**Comment by BilalTsinghua** [comment]
@josep-m-carbonell While compling configure.sh, i will face this error
CMakeFiles/KratosPfemApplication.dir/custom_python/add_custom_bounding_to_python.cpp.o: file not recognized: File truncated
collect2: error: ld returned 1 exit status
applications/PfemApplication/CMakeFiles/KratosPfemApplication.dir/build.make:236: recipe for target 'applications/PfemApplication/CMakeFiles/CMakeRelink.dir/KratosPfemApplication.cpython-35m-x86_64-linux-gnu.so' failed
make[2]: *** [applications/PfemApplication/CMakeFiles/CMakeRelink.dir/KratosPfemApplication.cpython-35m-x86_64-linux-gnu.so] Error 1
CMakeFiles/Makefile2:884: recipe for target 'applications/PfemApplication/CMakeFiles/KratosPfemApplication.dir/preinstall' failed
make[1]: *** [applications/PfemApplication/CMakeFiles/KratosPfemApplication.dir/preinstall] Error 2
Makefile:133: recipe for target 'preinstall' failed
make: *** [preinstall] Error 2


AND WHEN I RUN THE EXAMPLES I WILL THIS ERROR
 /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-4990161
Traceback (most recent call last):
  File "MainKratos.py", line 2, in <module>
    import KratosMultiphysics.ExternalSolversApplication
  File "/home/bilal/Kratos/KratosMultiphysics/ExternalSolversApplication.py", line 2, in <module>
    from KratosExternalSolversApplication import *
ImportError: libf77blas.so.3: cannot open shared object file: No such file or directory
KRATOS TERMINATED WITH ERROR

**Comment by josep-m-carbonell** [comment]
Something is wrong in your compilation. Try to clean the compilation and compike again: 
In cmake_build folder

make clean
sh configure.sh

If it fails it means that your Kratos is not downloaded correctly in local directory. Look for information with git status.

**Comment by BilalTsinghua** [comment]
@josep-m-carbonell In cmake_build folder  MAKE CLEAN means remove all the files in folder?

**Comment by josep-m-carbonell** [comment]
It removes compiled object files. If there is a broken file or an old version one you must remove it to force new compilation to generate it again.

**Comment by BilalTsinghua** [comment]
@josep-m-carbonell  
I did it cmake_build folder
make clean
sh configure.sh

now i run the example with the command runkratos Mainkratos.py, it show  the following error:
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-4990161
Importing    KratosExternalSolversApplication 
Initializing KratosExternalSolversApplication... 
Importing    KratosPfemApplication     
            ___  __                     
     KRATOS| _ \/ _|___ _ __            
           |  _/  _/ -_) '  \            
           |_| |_| \___|_|_|_|APPLICATION 
Initializing KratosPfemApplication    ...        
Importing    KratosPfemFluidDynamicsApplication 
            ___  __           ___ _      _    _          
     KRATOS| _ \/ _|___ _ __ | __| |_  _(_)__| |         
           |  _/  _/ -_) '  \| _|| | || | / _` |         
           |_| |_| \___|_|_|_|_| |_|\_,_|_\__,_|DYNAMICS 
Initializing KratosPfemFluidDynamicsApplication...       
Importing    KratosSolidMechanicsApplication 
            ___      _ _    _          
     KRATOS/ __| ___| (_)__| |         
           \__ \/ _ \ | / _` |         
           |___/\___/_|_\__,_|MECHANICS
Initializing KratosSolidMechanicsApplication...  
Wed Oct 17 15:59:21 2018
Traceback (most recent call last):
  File "MainKratos.py", line 9, in <module>
    MainFluidPFEM.Solution().Run()
  File "/home/bilal/Kratos/applications/PfemFluidDynamicsApplication/python_scripts/MainFluidPFEM.py", line 37, in __init__
    parameter_file = open("ProjectParameters.json",'r')
FileNotFoundError: [Errno 2] No such file or directory: 'ProjectParameters.json'
KRATOS TERMINATED WITH ERROR

**Comment by josep-m-carbonell** [comment]
I attach you a case extracted from tests.  Just go to the folder and:

python3 RunMainPfem.py

[dam_break_2D.zip](https://github.com/KratosMultiphysics/Kratos/files/2486709/dam_break_2D.zip)

**Comment by loumalouomega** [comment]
Did we solved this?

**Comment by philbucher** [comment]
Closing since inactive, pls reopen if otherwise
