### ISSUE TITLE
[Structural] Weird behaviour running tests

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#2907]
On a Windows system, executing the Structural Mechanics tests (test_StructuralMechanicsApplication.py), this is the output

```
PS E:\PROYECTOS\Kratos\applications\StructuralMechanicsApplication\tests> E:\KratosDeploy\runkratos.exe test_StructuralMechanicsApplication.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-a5c36b63db
Importing    KratosStructuralMechanicsApplication
     KRATOS   ___|  |                   |                   |
            \___ \  __|  __| |   |  __| __| |   |  __| _` | |
                  | |   |    |   | (    |   |   | |   (   | |
            _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS
Importing    KratosExternalSolversApplication
Initializing KratosExternalSolversApplication...
ExternalSolversApplication: succesfully imported
PS E:\PROYECTOS\Kratos\applications\StructuralMechanicsApplication\tests>
```

Nothing is executed...

The same happends when running any case from the GUI

**Comment by jginternational** [comment]
@loumalouomega

**Comment by jginternational** [comment]
Also happening in other apps that import the ExternalSolversApplication

What can I do @roigcarlo ?

**Comment by jginternational** [comment]
I've detected that the bug is in this file:
`KratosMultiphysics\EigenSolversApplication.py`
line 13:
`application = KratosEigenSolversApplication()`

Called by 
`applications\StructuralMechanicsApplication\python_scripts\structural_mechanics_analysis.py`
line 14
`import KratosMultiphysics.EigenSolversApplication`

When the Eigen solvers application is not compiled, the exception thrown is not an ImportError, it just crashes there

**Comment by oberbichler** [comment]
I think the mistake is the `except ImportError:`

Maybe we should also catch the corresponding error (or just any kind of exception). That would also make sense for the other applications. (e.g. I never compiled the `ExternalSovlersApplication` on Windows)

**Comment by jginternational** [comment]
I've discarded any problem in the externalsolvers. I've tried catching any exception but I'm better at tcl than at python... :(

**Comment by philbucher** [comment]
@jginternational can you try the following and report the output:
[Here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_analysis.py#L13-L17) change `except ImportError:` to `except Exception as e:` and print(e) in the next line?
~~~
try:
    import KratosMultiphysics.EigenSolversApplication
    KratosMultiphysics.Logger.PrintInfo("EigenSolversApplication", "succesfully imported")
except Exception as e:
    print(e)
~~~

**Comment by jginternational** [comment]
Hi @philbucher 

It never reaches the second break point

![image](https://user-images.githubusercontent.com/5918085/46082452-6992f680-c19f-11e8-8944-1e1fa2791aab.png)

**Comment by philbucher** [comment]
hm then I also don't know :/
@roigcarlo do you have an idea?
Or @oberbichler ?

**Comment by jginternational** [comment]
I'm compiling the EigenSolversApplication, so the problem should be fixed, but this is a kind of enigma

**Comment by philbucher** [comment]
ok now I understand
@oberbichler @armingeiser

**Comment by oberbichler** [comment]
Sorry but I can not reproduce the error. If I remove the EigenSolversApplication I just get the "not imported" warning.

**Comment by armingeiser** [comment]
I just tested it too on Windows and as @oberbichler I also get the not imported warning and the test is skipped.

**Comment by roigcarlo** [comment]
Python unittest does black magic with the errors and can be hiding the exception. I would try to run that script without the testing suit to see what happens

**Comment by loumalouomega** [comment]
Did we solved this?

**Comment by roigcarlo** [comment]
No

**Comment by philbucher** [comment]
in the meantime the try-except import of the solvers-apps has been removed

@jginternational could you please try again and report if you still have the problems?

**Comment by jginternational** [comment]
I haven't been able to get the same behaviour, so I think I can close this.
