### ISSUE TITLE
Create a common API for friction law in the core

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#292]
I started to implement frictional contact, and right now I am just using a static friction coefficient. But in reality the friction can be considered like a constitutive law. This is what @josep-m-carbonell is doing in applications/ContactMechanicsApplication/custom_friction/, where there is a base class FrictionLaw() and the other frictional laws derive from this class. 

I want to propose to create a common API for the friction laws in the core, basically I think that FrictionLaw() is perfectly defined and it is just a question of move it to the core. 

Maybe the only thing that I propose as a change is the possibility of define the friction coefficient as a table (this way will be easier to consider any kind of tribologic behaviour).

**Comment by josep-m-carbonell** [comment]
Are you planning to merge the ContactStructuralMechanicsApplication into the ContactMechanicsApplication when the contact you are developing is going to work properly ?

**Comment by loumalouomega** [comment]
We were planning to move the contact to the structural mechanics once it works, but we can discuss that

**Comment by loumalouomega** [comment]
I will close this, we can reopen i in the future
