### ISSUE TITLE
[IMPORTANT][AMatrix] Please implement tests to avoid future problems after migration

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2927]
@KratosMultiphysics/technical-committee @KratosMultiphysics/all 

In the PR #2923 we have seen that some of my utilities/processes are failing with AMatrix. I already solved some of them, but the point is that we know that this was broken thanks to the tests I implemented in the moment I developed that pieces of code.

The problem in this particular case was that AMatrix considers by default no aliased operations, so in case your operation were assumed to be aliased that part of the code will be broken. This is just one example, but some others minors changes have been considered in AMatrix, compared with Ublas.

What I am trying to say is that it is very important to avoid problems like this in the future:

PLEASE implement unitary tests in your code!!

In the wiki you have all the details of how to do this: https://github.com/KratosMultiphysics/Kratos/wiki/How-to-create-unitary-tests, if the wiki is not understandable we can rewrite it, but please don't let this pass. I understand that this is tedious and not precisely fun, but necessary.

Implementing unitary tests it is not important for the Kratos mantainers, but it is important also for you, it is easier to find errors and detect dangerous changes with them. This will help you in you routine of work.

My recommendations is to implement python standalone tests or cpp tests for utilities and processes, and just full tests once all the others parts of the code are already  checked and we want something more realistic coupled.

**Comment by jcotela** [comment]
I have also fixed a few errors due to the amatrix migration, and I can only add I fully agree with what @loumalouomega is saying. Subtle errors are really hard to fix on a real cases, and having simple tests will make your life much easier when you have to debug them.

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/45956507-f6f51000-c012-11e8-9f04-7bcf36e342f9.png)

**Comment by loumalouomega** [comment]
I will close this to reduce the humongous quantity of issues
