### ISSUE TITLE
[Core] A test fails when running with -D_GLIBCXX_DEBUG

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#2928]
TestDynamicBinsCellSizeConstructorCellSize                               OK.

TestDynamicBinsDefaultConstructorBoundigBox                              OK.

TestDynamicBinsDefaultConstructorCellNumber                              OK.

TestDynamicBinsDefaultConstructorCellSize                                OK.

TestDynamicBinsExistPoint                                                OK.

/usr/include/c++/7/debug/safe_iterator.h:374:
Error: attempt to advance a singular iterator 0 steps, which falls outside 
its valid range.

Objects involved in the operation:
    iterator @ 0x0x7ffe77b34f20 {
      type = __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >*, std::__cxx1998::vector<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::allocator<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > > > > >, std::__debug::vector<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::allocator<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > > > > > (mutable iterator);
      state = singular;
    }
Aborted (core dumped)

**Comment by loumalouomega** [comment]
@RiccardoRossi I tried GLIB ON on the master branch with Ublas and it works, just happens with the AMatrix?

**Comment by RiccardoRossi** [comment]
you should add -D_GLIBCXX_DEBUG to the CXX_FLAGS 

on my computer i have

       -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -D_GLIBCXX_DEBUG -msse3 -std=c++11" 					                        \

**Comment by loumalouomega** [comment]
I did in the configure.sh, I am using clang, are you using gcc?

**Comment by RiccardoRossi** [comment]
yes

**Comment by loumalouomega** [comment]
can you check if this happens with clang?

**Comment by loumalouomega** [comment]
Still happening?

**Comment by RiccardoRossi** [comment]
mmm, i'll close. i think it has been resolved
