### ISSUE TITLE
Compiling FEAST in windows

### ISSUE THREAD

**Issue by peterjwilson** [KratosMultiphysics/Kratos#293]
Hi All,

As per issue #279, I'm trying to use the FEAST solver for Eigenvalue problems. Adding the necessary entries to the configure.bat file (https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-the-FEAST-Solver-in-Kratos%3F#compilation-of-the-feast-library) and running it gives the following error regarding the lack of Fortran compiler:

> 
> **** configuring KratosMeshingApplication ****
> **** configuring KratosExternalSolversApplication ****
> -- Looking for a Fortran compiler
> -- Looking for a Fortran compiler - NOTFOUND
> CMake Error: Could not open file for write in copy operation C:/KratosGithub/Kratos/cmake_build/applications/ExternalSolversApplication/C:/KratosGithub/Kratos/applications/ExternalSolversApplication/custom_external_libraries/FEAST/config_mingw.cmake.tmp
> CMake Error: : System Error: Invalid argument
> CMake Error at C:/Program Files/CMake/share/cmake-3.7/Modules/CMakeAddFortranSubdirectory.cmake:89 (configure_file):
>   configure_file Problem configuring file
> Call Stack (most recent call first):
>   C:/Program Files/CMake/share/cmake-3.7/Modules/CMakeAddFortranSubdirectory.cmake:144 (_setup_mingw_config_and_build)
>   applications/ExternalSolversApplication/CMakeLists.txt:56 (cmake_add_fortran_subdirectory)
> 
> 
> **** configuring KratosStructuralApplication ****
> **** configuring KratosStructuralMechanicsApplication ****
> **** configuring KratosConvectionDiffusionApplication ****
> **** configuring KratosFluidDynamicsApplication ****
> **** configuring KratosALEApplication ****
> **** configuring KratosFSIApplication ****
> **** configuring KratosSolidMechanicsApplication ****
> python libraries to be installed are: C:/Python33/libs/python33.lib
> -------------------------------- user defined install dir C:/KratosInstallGithub
> boost python lib used = C:/boost_1_59_0/stage/lib/boost_python-vc140-mt-1_59.lib
> installed blas = C:/external_libraries/libblas.lib
> installed lapack = C:/external_libraries/liblapack.lib
> -- Configuring incomplete, errors occurred!

I tried to install some Fortran items to overcome this, but to no avail. Any help to overcome this would be appreciated!

**Comment by roigcarlo** [comment]
As far as i can tell you the problem seems to be that a Fortran compiler is missing, unfortunately there is no supported Fortran compiler for Kratos in Windows.
@loumalouomega, could it be possible to pre-compile this lib with MinGW ( like blas/lapack ) and ship it along Kratos?

**Comment by loumalouomega** [comment]
@roigcarlo @peterjwilson  Can we close this issue?

**Comment by roigcarlo** [comment]
Well, we still have no solution for this. But I can't guarantee you that this will be ever possible. 
I can change Kratos so it tries to search for the lib instead of compiling it if it helps (as I mentioned like it does with blas/lapack) 

I don't know exactly what is this lib or where is it needed so. Anyone from kratos that uses it and can give me some insight?

**Comment by peterjwilson** [comment]
@loumalouomega I'm happy to close this issue since it's not particularly due to Kratos itself. 

At the very least it can be helpful to those who try to get Fortran running on Windows in the future and wonder why it doesn't. Currently I'm just running the FEAST solver in a linux virtual machine which is fine for development.

@roigcarlo I'm completely out of my depth here, but perhaps the inclusion of the FEAST Eigensolver in the Intel MKL may allow it to be run on Windows (https://software.intel.com/en-us/mkl-developer-reference-c-extended-eigensolver-routines)? Even if this were the case, I imagine there'd be some considerable work in modifying the existing FEAST arrangement...

**Comment by roigcarlo** [comment]
@peterjwilson That could work indeed but I am afraid the problem in windows will remain, as MKL also needs intel compiler to work.

Hopefully I may have news on that soon, I am testing builds with gcc/clang under win via mingw and the new native windows bash, both of them with potential to solve this, but Its a side project of mine and I am not sure it will ever make it to something we officially support. Anyway, I will have FEST added to the tests just in case if it ends up giving good results.
