### ISSUE TITLE
[Core][Constraint] Question: Why the steps of the MasterSlaveConstraint don't requite de ProcessInfo?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2942]
https://github.com/KratosMultiphysics/Kratos/blob/2d582b3b1f57ed4ca78b3b7f27d14fa8e7279477/kratos/includes/master_slave_constraint.h#L281

Compared with the one in the element.h:

https://github.com/KratosMultiphysics/Kratos/blob/2d582b3b1f57ed4ca78b3b7f27d14fa8e7279477/kratos/includes/element.h#L392

For the aim of consistency I will add the ProcessInfo into the MasterSlaveConstraint

**Comment by adityaghantasala** [comment]
@loumalouomega  I can do that. I any way have some changes to to make to the implementation.

**Comment by loumalouomega** [comment]
OK, I will close this in order to reduce the number of issues. I think that the point is to have everyone involved informed
