### ISSUE TITLE
[MeshMoving] explicit-mesh-moving test fails after 2740

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2950]
see #2740 
The test still uses `Element`, I think it should now use `MeshElement`
I tried it but it seems like the `MeshElement` is not registered
@loumalouomega

**Comment by loumalouomega** [comment]
The elements and conditions registered are the same, they keep the same name, the only thing is that the implementation is in a different file

**Comment by loumalouomega** [comment]
At least if you call it via Element3D4N etc...

**Comment by loumalouomega** [comment]
Can I see the part of the code that fails?

**Comment by philbucher** [comment]
Hm then I don't understand
Here is the file:
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshMovingApplication/tests/cpp_tests/test_explicit_mesh_movement_utility.cpp

**Comment by loumalouomega** [comment]
This uses the standard interface 

        auto p_elem = str_model_part.CreateNewElement("Element2D4N", 1, {100,200,300,400}, p_prop);

Should not be a problem

**Comment by loumalouomega** [comment]
What is the fail?

**Comment by philbucher** [comment]
~~~
Ran 1 of 419 test cases in 0.000632835s. 1 failed:
    TestExplicitMeshMovingUtilities2D Failed with message: 
        Error: The component is not registered!MeshElement2D4N


in kratos/includes/kratos_components.h:102:static const TComponentType& KratosComponents<TComponentType>::Get(const string&) [with TComponentType = Element; __cxx11::string = __cxx11::basic_string<char>]
   kratos/sources/model_part.cpp:743:Element::Pointer ModelPart::CreateNewElement(__cxx11::string, ModelPart::IndexType, Geometry<Node<3ul> >::PointsArrayType, Properties::Pointer, ModelPart::IndexType)
~~~

this happened when I tried with the MeshElement

**Comment by philbucher** [comment]
This is the original Error:
~~~
Ran 1 of 419 test cases in 0.000716225s. 1 failed:
    TestExplicitMeshMovingUtilities2D Failed with message: 
        Error: Please implement the First Create method in your derived ElementElement #1


in kratos/includes/element.h:235:virtual Element::Pointer Element::Create(Element::IndexType, const NodesArrayType&, Properties::Pointer) const
   kratos/includes/element.h:237:virtual Element::Pointer Element::Create(Element::IndexType, const NodesArrayType&, Properties::Pointer) const
~~~

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/46145748-68c29900-c261-11e8-8b9d-0d5c84506e11.png)

https://github.com/KratosMultiphysics/Kratos/blob/66bd6cdb5770773d923b6c3f9380a78a9289bdaa/kratos/includes/kratos_application.h#L401

Element2D4N is already a MeshElement

**Comment by loumalouomega** [comment]
The two creates are implemented

**Comment by philbucher** [comment]
Hm then I also don't know

@rubenzorrilla can you check?

**Comment by rubenzorrilla** [comment]
I will try to have a look ASAP. @philbucher thanks for reporting!

**Comment by rubenzorrilla** [comment]
I think I've found the problem. My ExplicitMeshMovingUtility needs a so called virtual mesh. Such virtual mesh is created as a copy of the origin model part by calling the Create method of each one of the origin elements https://github.com/KratosMultiphysics/Kratos/blob/fcc9a62aa26f8721e0bfa6f8f6a064ec65167605/applications/MeshMovingApplication/custom_utilities/explicit_mesh_moving_utilities.cpp#L78
Since this is a test, the origin mesh is conformed by elements of type Element2D3N (in a real application this would be any fluid element). When we explicitly call the Create method in the line above, the KRATOS_ERROR implemented in the PR #2740 is thrown.

To circumvent this we could try to create the test mesh using any of the elements in the MeshMovingApplication. IMO, this is a dirty solution but it seems that from PR #2740 on we won't be able to "Create" basic elements anymore. Do you have any alternative solution?

**Comment by philbucher** [comment]
> ![imagen](https://user-images.githubusercontent.com/19991680/46145748-68c29900-c261-11e8-8b9d-0d5c84506e11.png)
> 
> [Kratos/kratos/includes/kratos_application.h](https://github.com/KratosMultiphysics/Kratos/blob/66bd6cdb5770773d923b6c3f9380a78a9289bdaa/kratos/includes/kratos_application.h#L401)
> 
> Line 401 in [66bd6cd](/KratosMultiphysics/Kratos/commit/66bd6cdb5770773d923b6c3f9380a78a9289bdaa)
>  const MeshElement mElement2D4N; 
> 
> Element2D4N is already a MeshElement

according to this the Element2D3N is a MeshElement
@loumalouomega could you have a more detailed look?

**Comment by loumalouomega** [comment]
I think the problem is the lack of operator = defined, can you check that?
