### ISSUE TITLE
[Core] Missing const methods on PointerVector

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#2973]
The operator[] and operator() are missing for const classes.

Besides it still depends on boost.

https://github.com/KratosMultiphysics/Kratos/blob/ec22c86d5b37ef7edd8d98e5dcc1ce54aaaa1490/kratos/containers/pointer_vector.h#L29

@KratosMultiphysics/technical-committee

**Comment by jcotela** [comment]
Regarding the title, what is the problem with these two:
https://github.com/KratosMultiphysics/Kratos/blob/ec22c86d5b37ef7edd8d98e5dcc1ce54aaaa1490/kratos/containers/pointer_vector.h#L150-L153
https://github.com/KratosMultiphysics/Kratos/blob/ec22c86d5b37ef7edd8d98e5dcc1ce54aaaa1490/kratos/containers/pointer_vector.h#L160-L163

Regarding the boost issue, looks like we will need our own indirect iterators...

**Comment by loumalouomega** [comment]
No problem, it just needs to be added

**Comment by jcotela** [comment]
but those are there already... do you mean to python?

**Comment by loumalouomega** [comment]
Maybe I was confuse, closing

**Comment by loumalouomega** [comment]
Thanks
