### ISSUE TITLE
[AMGCL] many warnings after #2807

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#2989]
@RiccardoRossi @ddemidov after #2807 AMGCL throws a lot of warnings about unknown parameters

This is some tests-output:
~~~
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
.AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
AMGCL WARNING: unknown parameter relax
AMGCL WARNING: unknown parameter coarsening
AMGCL WARNING: unknown parameter npre
AMGCL WARNING: unknown parameter npost
AMGCL WARNING: unknown parameter coarse_enough
.........AMGCL WARNING: unknown parameter M
~~~

I looked around a bit but I couldn't figure out how to fix it

can you please have a look?

**Comment by ddemidov** [comment]
Did you use the new `preconditioner_type` option with amgcl solver? This switches from amg to a single level relaxation for preconditioning. When you do that, the usual amg parameters are no longer applicable, hence the warnings. The warnings themselves are nothing to worry about except the extra verbosity. Your options are:

* Disable the warning by declaring (either in the code or in cmake)
```cpp
#define AMGCL_PARAM_UNKNOWN(name) (void)0
```
* Do not set the amg parameters when using `preconditioner_type` option.

**Comment by jcotela** [comment]
@sunethwarna I think this is applicable to your issues too.

**Comment by msandre** [comment]
I think the amgcl_solver.h needs to be updated. We are getting a lot of "unknown parameter M" warnings. I closed #3148 since this thread came first, but it is still an open issue for us.

**Comment by ddemidov** [comment]
@RiccardoRossi , what do you think about disabling amgcl warnings completely?

**Comment by ddemidov** [comment]
Looks like uncommenting the following line should be enough:

https://github.com/KratosMultiphysics/Kratos/blob/7ba66bd83307a322f9474923ff061c5e405589c7/kratos/linear_solvers/amgcl_solver.h#L312

**Comment by msandre** [comment]
Just tested it, but still getting the warning about "M" being unknown. My settings are:

```
            "solver_type"         : "AMGCL",
            "max_iteration"       : 200,
            "tolerance"           : 1e-9,
            "provide_coordinates" : false,
            "smoother_type"       : "ilu0",
            "krylov_type"         : "gmres",
            "coarsening_type"     : "aggregation",
            "scaling"             : false
```

I think the problem is related to this if-statement:
https://github.com/KratosMultiphysics/Kratos/blob/dd66d8da4fb621575f673eb2177ccc5b20d83275/kratos/linear_solvers/amgcl_solver.h#L298

**Comment by ddemidov** [comment]
gmres-type solvers should expect 'M' as a parameter. Are you sure you are not using `bicgstab_with_gmres_fallback`? It sets 'M' but uses bicgstab solvers which does not have the parameter.

https://github.com/KratosMultiphysics/Kratos/blob/dd66d8da4fb621575f673eb2177ccc5b20d83275/kratos/linear_solvers/amgcl_solver.h#L302-L305

**Comment by RiccardoRossi** [comment]
@philbucher @ddemidov this is on me. I'll take a look asap

**Comment by RiccardoRossi** [comment]
there are two problems:

1 - M is always set even when gmres is not used. The AMGCL correctly warns about this
2 - amg settings are passed even when amg is not used as a preconditioner

@ddemidov i think that the warnings issued by AMGCL are very useful, and i would prefer not to deactivate them. I'll try to correct this on the user side

**Comment by philbucher** [comment]
The trilinos-version still prints some of those, see #3343 

`AMGCL: Unknown parameter class`

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi ....

**Comment by RiccardoRossi** [comment]
I cleaned up the OpenMP version but not the MPI version. 
I will do also the MPI when i can...

however, @msandre are u getting this with the "serial" version? because that is expected to be clean

**Comment by msandre** [comment]
My warnings (in serial) have disappeared. Thanks!

**Comment by philbucher** [comment]
ping @RiccardoRossi
