### ISSUE TITLE
Mass calculation of elements not unified

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#299]
Hi all,

I need to calculate the total mass of a model part. Now, what I am doing so far is looping over all elements and summing up the individual masses computed by either density x volume (solids) or density x thickness x area (shells). This is not a very nice way since I have to ask for the element type so that I can distinguish between shells and solids. 

To be independent of the element type here, I would expect to have a Volume() function providing me the volume for each element associated with a volume (shells and solids). However, as far as I can judge that, the volume is computed only for solids in the scope of the geometry class. For shells, the associated geometry only has an area() function. On the side of the element, however, I cannot ask for the volume or the mass directly.

So my questions are:
1) Is there a nice way to compute the total mass of a model part without considering individual element types?
2) Is there a unified way for each voluminous element (shell / solid) to ask for its mass/volume?

Thanks in advance.

Best regards,
Daniel

**Comment by loumalouomega** [comment]
You can calculate the assembled mass matrix and lump it, you will get the mass corresponding to each DoF

Best regards

**Comment by dbaumgaertner** [comment]
Thanks for that hint! That's what I also thought. But while this is kind of clever, it is not very handy, too. I was just thinking, that it might be better to have such a basic feature (asking for the volume of a voluminous element) more standardized / unified. Or what do you think?

**Comment by RiccardoRossi** [comment]
Hi Daniel,

the "geometry" class, which implements "Volume" can not access to kratos variables, since by design it is at a lower level. furthermore "THICKNESS" is typically contained in the Properties, so geometry definitely has no access to it.

can't you create a helper function like (in pseudo code)

    if(geom.WorkingSpaceDimension() != geom.LocalSpaceDimension()) //case of a shell for example
        return geom.Area()*geom.pGetProperties()->GetValue(THICKNESS)
    else
        return geom.Volume()

**Comment by dbaumgaertner** [comment]
Thanks again. Then I will stick to the implementation I had which follows the idea of Riccardo.
