### ISSUE TITLE
I started the migration of the Wiki, we can work together to Make the Wiki Great Again

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3]
I just migrated the what is Kratos as the main Wiki page, we should start to migrate the good content of the old Wiki to the new one.

PS: We need to think about to host the images in a different place?

**Comment by pooyan-dadvand** [comment]
First of all we should give it a new structure. The old one is not very clear. A nice line would be to have different sections for final users, developers and issue report.

**Comment by loumalouomega** [comment]
I added the install howto, one trick is that you can copy paste the media wiki format (changing the input format). This way the transition will be faster

**Comment by pooyan-dadvand** [comment]
Just some examples of other wikis in GitHub to get idea:

- [Hystrix wiki](https://github.com/Netflix/Hystrix/wiki) nice and detail overview
- [SnowPlow wiki](https://github.com/snowplow/snowplow/wiki) for quick navigation
- [CellularPrivacy wiki](https://github.com/CellularPrivacy/Android-IMSI-Catcher-Detector/wiki) for side bar layout
- [lettuce wiki](https://github.com/mp911de/lettuce/wiki) again navigation and side bar layout

**Comment by loumalouomega** [comment]
Great contribution. One more thing, we need a place to store the images, otherwise we will continue using the images from the old forum, and this is not a good practice.

**Comment by josep-m-carbonell** [comment]
It seems that  \<span class="red">  \</span> ... is not woking in the wiki. I don't know which is the correct command to write text in colour.

**Comment by loumalouomega** [comment]
That depends if you work with MediaWiki format or Markdown, look https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by roigcarlo** [comment]
Style tags are not processed so no format will support color.

There is partial support for some unicode colored glyphs if one wants to draw attention into something.

&#x1F53A; For example

**Comment by josep-m-carbonell** [comment]
I've said that because the things you uploaded to the wiki, show that  \<span class="red"> \</span> things in the commands you must enter in the terminal to configure or compile the libraries for the installation. They must be corrected.

**Comment by loumalouomega** [comment]
True, I just added C/P from the old wiki, part of the work is to ensure that everything is correctly displayed

**Comment by roigcarlo** [comment]
Working on the installation pages...

**Comment by loumalouomega** [comment]
I corrected the one of Linux

**Comment by roigcarlo** [comment]
Thx, I will probably take some more time and move it to MD if you don't mind

**Comment by loumalouomega** [comment]
I started to use MD too, I like it more and is more powerful

**Comment by loumalouomega** [comment]
Hi, maybe is a good idea to close this issue:

Right now in my TODO list I have to translate the following  articles of the Wiki:

- [ ] http://kratos-wiki.cimne.upc.edu/index.php/How_to_use_Doxygen_to_generate_documentation_for_our_code
- [ ] http://kratos-wiki.cimne.upc.edu/index.php/How_to_Add_a_New_Variable
- [ ] http://kratos-wiki.cimne.upc.edu/index.php/Checking_memory_use_with_Valgrind

If anyone have a proposition for more articles tell me
