### ISSUE TITLE
[AMatrix] Preparation: Using SparseSpace for linear-solver tests

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3004]
When compiling with AMatrix currently the linear-solver tests in the core are not working since the [vectors and the matrix are directly constructed](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/test_linear_solvers.py#L23-L29) and not with the space as it is done e.g. in [trilinos](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/tests/test_trilinos_linear_solvers.py#L27-L36)

I wanted to do the same for the tests in the core but unfortunately I cannot get the references from the Matrices/Vectors like it is possible for Trilinos thanks to the implementation of @rubenzorrilla => the [AuxiliaryMatrixWrapper](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_python/trilinos_pointer_wrapper.h#L62) and [AuxiliaryVectorWrapper](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_python/trilinos_pointer_wrapper.h#L176)

=> I suggest to template the wrappers of @rubenzorrilla with the Space and then we can solve the problems of the core linear-solver tests the same way as in Trilinos (possibly even having only one function then to test linear solvers, they are already now very similar.)

@oberbichler this should properly solve this problem, also it should work when porting to AMatrix-SparseSpace

**Comment by RiccardoRossi** [comment]
It should not be needed to use the wrapper mechanism for the ublas...

The big problem is that the amatrx vector and ublas sparse matrix are not
yet compatible, so we still need ublas in the sparse space...(until amatrix
has a sparse matrix implemented)

**Comment by jcotela** [comment]
@philbucher we discussed this at the @KratosMultiphysics/technical-committee, we agree about adding functions to get a new vector in the sparsespace, but we hope that the wrappers will not be necessary. We can look into the implementation together  when we have some time.

**Comment by philbucher** [comment]
reminder to myself: maybe the solution used in #3137 can be used

**Comment by jcotela** [comment]
@philbucher I suspect that one is a different problem... The functions that use those arguments were some time ago changed to use pointers instead of references (or maybe it was the other way around, I don't remember the details), the linked PR is changing the variables to use the correct holder type.

**Comment by jcotela** [comment]
@philbucher what is the state of this? Maybe we can take a look when you have some time.

**Comment by philbucher** [comment]
I don't know, I only gave a suggestion on how the problem could be solved.
We can have a look again, but last time I checked the core was not compiling with amatrix and I think the problem has not been solved (was the row-access issue I think)

**Comment by philbucher** [comment]
closing since long stale and probably no longer relevant
