### ISSUE TITLE
Potential Bug in ConstitutiveLawUtilities

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3020]
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_utilities/constitutive_law_utilities.cpp#L532-L594

`h_i` and `h_j` are unused, seems odd to me

**Comment by loumalouomega** [comment]
@AlejandroCornejo did that

**Comment by AlejandroCornejo** [comment]
yes you are totally right @philbucher ! I've done a PR correcting that.
