### ISSUE TITLE
Style Guide 

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#303]
In addition to the [existing style guide](https://github.com/KratosMultiphysics/Kratos/wiki/Style-Guide) which is mostly about naming, I propose to use a tool  for having a consistent formatting (brackets, spaces, ...)

I propose [astyle](http://astyle.sourceforge.net/). It works on all systems and is easy to use. One can define a file ("kratos.style" in the following) or a set of command line options to be used by everyone. The usage is simple:
`astyle file_to_format.cpp --options=/path/to/style/file/kratos.style`

@KratosMultiphysics/technical-committee what do you think about this?
I think this would unify the apparence a lot and hence make it easier to read other peoples code.

This is how "kratos.style" could look like:
```
# Kratos code style file for astyle
# See http://astyle.sourceforge.net/
# Brace Style 'Allman'
-A1
# Tab Options (4 Spaces)
-s4
# Padding around operators
-p
```

**Comment by jcotela** [comment]
Hi Philipp,
thanks for addressing this. My understanding is that, once we have the git stuff completely figured out, we can automatically format code when merging a pull request. We tried in the past to use the tool you mention, but it was not so convenient to do as an individual user (it massively messes up the commit history of files, and one has to make sure that everyone uses it or it ends up degenerating into a "free" format).

**Comment by philbucher** [comment]
I also thought of this, I think it should be possible to format during a pull request.
Then I guess I will leave it for now, thanks for your answer
