### ISSUE TITLE
Why there are two Table objects in kratos? 

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#3049]
We can find the table.h and the piecewize_linear_table.h defining the same class Table.
The one used by properties and model_part is the one defined in table.h. However the one defined in the piecewize_linear_table.h has an extra useful property that is it knows the variables defined by the table.

Now the piecewize_linear_table.h is not compiled anywhere because it raises a small compilation error when you do that.

**Comment by philbucher** [comment]
I think that the feature in `piecewize_linear_table.h` is already in `table.h` => if you scroll to the second half of the file there I think you can find the same
Can you check that?

**Comment by RiccardoRossi** [comment]
mentioning @pooyan-dadvand who authored.

btw...the name of the file is obviously misspelled, as a minimum we should correct that 😀

**Comment by pooyan-dadvand** [comment]
The piece-wise linear table used to be the one to be used in properties but after giving several difficulties in using with components. Also it gives us problem for vectorial variables having table for magnitude which gave us problems input file and compilation. 

So we decided to use the base class adding the piece-wise interpolation to it. And leaving the other one to be improved in future. This future seems doesn't arrived yet....

The typo should be mine.... sorry...

**Comment by josep-m-carbonell** [comment]
Ok
