### ISSUE TITLE
Why a Create method was added to the ConstitutiveLaw using a back door? 

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#3061]
#2279
For a back door I mean that only some developers were aware of it.
I do not remember that any issue was open to discuss it. 

It is very important to discuss this type of things because it changes the standard, and new developments have been made in the core following this new standard.

I think that all developers must be considered when some of you decide to change things like this.

**Comment by loumalouomega** [comment]
> For a back door I mean that only some developers were aware of it.

This PR was discussed by the @KratosMultiphysics/technical-committee before adding it. The PR was public and was alive during 5 days. 

> It is very important to discuss this type of things because it changes the standard, and new developments have been made in the core following this new standard.

This PR didn't change any behavior at the moment, only added a new one. Very simple and very general, only 19 lines of code.

Besides, I don't remember any discussion about this:

https://github.com/KratosMultiphysics/Kratos/pull/3055

and this:

https://github.com/KratosMultiphysics/Kratos/pull/3054

And this two PR added new methods to core classes as #2279, but they were alive only during 3 hours (both)

**Comment by josep-m-carbonell** [comment]
You can not compare #3055 and #3054 with #2279.  Comments in #2279 says it explicitly:

 * Create function (should be implemented by any derived class)

This is the purpose. And it is very relevant. 
I don't know if the technical committee decided it. As far as I know technical committee is solving github issues since a year ago.

**Comment by loumalouomega** [comment]
The PR is 4 months old, that belongs to that one year period.

**Comment by loumalouomega** [comment]
The method create should be implemented just in case you require parameters on your construction. Otherwise it creates a clone of the target CL (which will be assumed that uses the default constructor)

**Comment by josep-m-carbonell** [comment]
I suppose that you only executed it. The decision of that is a little bit obscure. That's what I'm telling. Although I am not sharing this solution as a good one for creating CLWs, I am not against it.

**Comment by maceligueta** [comment]
IMO, extending the API's for the sake of completeness, when it is clear that a method was missing, should be quite straight forward. 
Changing the behavior of objects or how they must be constructed can be a lot more dangerous, true. However, it is not clear to me that this is one of these dangerous cases. Otherwise, please explain @josep-m-carbonell (thanks).
 For this reason, I added this issue to the TO DO list of the @KratosMultiphysics/technical-committee .

**Comment by loumalouomega** [comment]
The create in the CL was not existing until that time. Until then is was not possible to construct complex CL using the KratosComponents in a general way. This didn't break any existing beahviour and it was not added as back door, because the PR was public during a whole week, and it was very easy to review, just 19 lines, not thousands of files and lines of code

**Comment by josep-m-carbonell** [comment]
In fact , if you want to concatenate three strings to build a new name and then Clone a previous registered law you don't need a Create method. And I would say more, if you need to register previously each law type with all possible combinations, I can not see the advantage of calling it afterwards using three or more json fields. 
The dangerous thing is that this defines a new standard of creation of laws based on the name, now it is used in the core for some read materials utilities, and it means that you need to implement it to your constitutive laws if you want to keep compatibility....at the same time the correct json parameters are not defined, and I guess that suddently new options can be added silently, and so on.

**Comment by loumalouomega** [comment]
No it is not needed. The base CL does a clone with the KratosComponents and the name, is the same as doing a clone (that it was in fact previously used). There are not defaults configured because the idea is to be general and allow the developer chose what is relevant

**Comment by loumalouomega** [comment]
You don't need to define anything if you don't want, but before of that a simple clone was used

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/pull/2442/files See here, this question was already answered to @philbucher

**Comment by loumalouomega** [comment]
I added a comment in https://github.com/KratosMultiphysics/Kratos/pull/2291/commits/02953131a13386744c05155c2a3b965b628522eb in the c++ counterpart

**Comment by pooyan-dadvand** [comment]
I don't see this as a backdoor and in contrary as a very standard and formal way to do.

The `Create` method is a very standard part of the "factory" pattern. Meanwhile I am trying to create a Factory mechanism for all objects in Kratos and this addition to CLs is aligned with that global move. Note that the object creation in Kratos is not very well solved and I personally see the Kratos factory mechanism a positive move.

On the other side we opted to maintain the old way of construction to ensure the backward compatibility for existing CLs which I see it useful. Specially for cases that @josep-m-carbonell is worry about.

**Comment by josep-m-carbonell** [comment]
![mr-bean-plan](https://user-images.githubusercontent.com/23210788/47106909-1c5aef80-d248-11e8-864d-1771a652d19f.jpg)

**Comment by loumalouomega** [comment]
@josep-m-carbonell be careful when using memes, they have an specific context, the one you used is oriented for sexual insinuations 

"The phrase “if you know what I mean” has been colloquially used to point out a sexual double entendre for many years prior to the creation of the Mr. Bean rage face"

https://knowyourmeme.com/memes/if-you-know-what-i-mean

**Comment by josep-m-carbonell** [comment]
Hehehe.... Yes, I love you all guys. I am not an expert in 'memes', this one shows an humorous disbelief face. Insinuating that the message is conciliatory. The writing of the image changes the meaning. However it is possible that for purist with only the image is enough.

**Comment by josep-m-carbonell** [comment]
Let's close it before someone could feel ofended then.
