### ISSUE TITLE
[Core] Modified shape functions for 3d triangles

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#3065]
Hi all,

I have seen that the current modified shape functions work only for 2d triangles. I would like to use them to cut conditions in 3d, would it be reasonable to extend them to 3d triangles? I could do part of the work myself but I would need some help though.   @jcotela  @RiccardoRossi  @rubenzorrilla

**Comment by ddiezrod** [comment]
@rubenzorrilla I was thinking.. Don't you have the same issue with the EmbeddedAusasNavierStokesWallCondition? Its geometry is a 3d triangle but it uses internally the 2d triangle for the splitting...

**Comment by rubenzorrilla** [comment]
Its a bit more complex. What we do in the Ausas condition is to call the modified shape functions of the parent element of each condition. Thus, the shape function values in the faces are computed by using the parent element geometry. Maybe we can circumvent this issue by doing something similar...

**Comment by jcotela** [comment]
@ddiezrod I'd say that, as long as you work with regular conditions (faces of an existing tetrahedron), using the parent element as @rubenzorrilla is suggesting should be a workable solution.

**Comment by ddiezrod** [comment]
@jcotela @rubenzorrilla Ok, I will take a look to your implementation and see if it works for me. Thanks!

**Comment by rubenzorrilla** [comment]
@ddiezrod closing the issue then! Feel free to reopen it if this doesn't circumvent your problem.
