### ISSUE TITLE
LoggerTableOutput - Help

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#3067]
I am trying to use the LoggerTableOutput but i'm not very succesfull...

Does someone know how to use it?

```
 Eigenfrequency[Hz]weightingfactor
#: 1
Eigenfrequency[Hz]: 43.2457
weightingfactor: 0.5
#: 2
Eigenfrequency[Hz]: 83.8473
weightingfactor: 0.5
# Eigenfrequency[Hz]weightingfactor
1
2 # Eigenfrequency[Hz]weightingfactor

1 1
2
2
```

instead of
```
#   Eigenfrequency [Hz]   weightingfactor
1   43.2457               0.5
2   83.8473               0.5
```

**Comment by loumalouomega** [comment]
Look at the test as reference

**Comment by philbucher** [comment]
I also tried using this some time ago but failed, for the same reason
Afair the test-output is also messed up

@loumalouomega are you using this somewhere?

**Comment by armingeiser** [comment]
I tried to do it according the test, but i failed.
In the test the table is printed properly at the end, but also there all intermediate steps for adding a single value lead to a new line e.g. `Eigenfrequency[Hz]: 83.8473` as above.
In the meantime i simply did the output formating myself, as its just a very simple table

**Comment by philbucher** [comment]
Yep I also had this problem, now I remembered

**Comment by loumalouomega** [comment]
Can we close this?
