### ISSUE TITLE
[CORE] Enable calculation of "distance to skin" for user-defined DISTANCE variables

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#3070]
@rubenzorrilla @pooyan-dadvand @RiccardoRossi 

Dear all,

In my application, I am using two independent distance functions (one using the common DISTANCE variable and the other using an specific EXAMPLE_DISTANCE defined in the application). I would need to use the _calculate distance_ processes for both variables, which is currently not possible as the DISTANCE variable is directly defined inside the processes. For instance (in _calculate_signed_distance_to_3d_skin_process.h_ ): 

>     void CalculateNodeDistance(Node<3>& rNode)
>     {
>         double coord[3] = {rNode.X(), rNode.Y(), rNode.Z()};
>         double distance = DistancePositionInSpace(coord);
>         double& node_distance =  rNode.GetSolutionStepValue(DISTANCE);

I am opening this issue to discuss how we could redefine this processes in order to compute the distances for any user-defined variable (not only the default DISTANCE variable). 

Would it be OK to add two properties in these processes objects (e.g mrDistanceVariable and mrElementalDistancesVariable), which could be defined through the constructor as an input, or defaulted to DISTANCE/ELEMENTAL_DISTANCES otherwise?

Thanks,

**Comment by philbucher** [comment]
Another way would be to use the process as is and then copy the computed to other variables
=> this can easily be done with the [VariableUtils](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/variable_utils.cpp#L209-L224)

**Comment by pooyan-dadvand** [comment]
Not a bad idea, I would pass it in the constructor with default to be DISTANCE in `CalculateDistanceToSkinProcess` and ELEMENTAL_DISTANCES in `CalculateDiscontinuousDistanceToSkinProcess`

**Comment by philbucher** [comment]
is this solved?

**Comment by marcnunezc** [comment]
Hi!
Not yet!
Pooyan suggestion is not yet implemented, but I have been using the VariableUtils as you pointed out to do the workaround.

**Comment by philbucher** [comment]
@marcnunezc was this part of your recent implementations?

**Comment by marcnunezc** [comment]
No it's not yet done!

I started to implement it [here](https://github.com/KratosMultiphysics/Kratos/tree/core/user-defined-vars-skin-process) some weeks ago, but it's still pending
