### ISSUE TITLE
TODOs POST Model V3 Merge

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#3073]
This issue is to pin down the things to be adjusted after merging ModelV3 branch

- [x] Decide in @KratosMultiphysics/technical-committee  a consistent way of managing "local modelparts" and uniformize current implementations (most probably implies adding a clear function to avoid deletion and reconstruction)
- [ ] see if implementation of ModelPart serialize could be achieved without overloading load and save methods in serializer
- [x] decide if GetModel or GetOwnerModel
- [x] Implement Serialization for Model
- [x] Adding ModelPart clear
- [x] Delete branch in #2030 ? => decision up to @RiccardoRossi 
- [x] Close #2137 and delete branch ? => decision up to @RiccardoRossi

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee decides to change GetOwnerModel -> GetModel

**Comment by RiccardoRossi** [comment]
we also decided to add a Clear to model_part

**Comment by loumalouomega** [comment]
Personally I would avoid to change GetModel to GetOwnerModel (or vice versa), so many changes in something so extendely used is not good for the developers

**Comment by pooyan-dadvand** [comment]
`GetOwnModel` is a new method from Model_v3 PR and for this reason we wanted to change it before extensive use of it.

**Comment by RiccardoRossi** [comment]
Decision (about local modelparts):

        MyProcess( Model& current_model, local_mp_name="MyLocalModelPart"):
             mrLocalModelPart( current_model.CreateModelPart( local_mp_name ) )
        {
              //if a modelpart named MyLocalModelPart exists we throw an error
        }

        ... all code ...

        ~MyProcess()
        {
              current_model.DeleteModelPart( mrLocalModelPart.Name() );
        }

**Comment by loumalouomega** [comment]
Better to use parameters?

**Comment by RiccardoRossi** [comment]
@loumalouomega  the point here is not how parameters are passed to the process (or class in general). The point of my comment is that if one wants to create a "local" model part should create it in the constructor of the class and destroy it in the destructor. If a modelpart with the same name all ready exists in the model we shall throw an error. To provide flexibility we should thus give the user the possibility of tellign the name to be used for the local modelpart.

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi for the save and load you can make the following tricks.
- In save you should save the pointer to the Model and NOT the reference:
```c++
void ModelPart::save(Serializer& rSerializer) const
{
    rSerializer.save("Name", mName);
    rSerializer.save("Model", &mrModel); // saving the pointer to the model instead of the reference
    KRATOS_SERIALIZE_SAVE_BASE_CLASS(rSerializer, DataValueContainer);
    KRATOS_SERIALIZE_SAVE_BASE_CLASS(rSerializer, Flags );
    ....
```
- load is more tricky as you should reconstruct agian the ModelPart using new:
```c++
void ModelPart::load(Serializer& rSerializer)
{
    Model* temp_model_pointer;
    rSerializer.load("Model", temp_model_pointer); // loading the pointer
    std::string ModelPartName;
    rSerializer.load("Name", ModelPartName);
    ::new(this)ModelPart(ModelPartName, *temp_model_pointer); // reconstructing the modelpart again
    KRATOS_SERIALIZE_LOAD_BASE_CLASS(rSerializer, DataValueContainer);
    KRATOS_SERIALIZE_LOAD_BASE_CLASS(rSerializer, Flags );
...
```
To avoid memory leak problems you may have to use an special constructor which not allocate any members in heap. 

Saying that, I'm personally in favour of storing a pointer to the model (which is also more flexible) rather than applying the above solution.

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand i think there is a fundamental problem with what you propose:

the essential issue is that when you serialize a single modelpart you do not want (at least not always) to serialize the whole model who owns it. Doing that would imply not just serializing that modelpart but also all the other model_parts owned by that model.
Taking this into account it only makes sense to serialize a model_part if it is created correctly within a given model.

Just think at the current scenario

```py
      #let's assume we have a current_model owning a lot of modelparts
     mp = current_model.CreateModelPart("new")
     mp.Save()
     del(current_model)
 
     # create new model
     new_model = Model()
     mp_to_be_loaded = new_model.CreateModelPart("...")  #now mp_to_be_loaded belongs to new_model
     Serializer.load(mp_to_be_loaded)  ##if i saved the current_model, this would recreate the "current_model" so mp_to_be_loaded does not any longer belong to new_model 
     #ALSO this would imply saving all the modelparts in current_model, which is not what i wanted
     model_to_be_loaded 
```

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi, your observation is correct. Nevertheless from serialization point of view you should notify this to the serializer (by adding the Model to the list of the saved pointer) which is also an adhoc workaround.... This would be also the case for serializing only a sub modelpart in which the pointer to the parent one has the same issue. 
Seeing all these complications I agree with your implementation of having special save and load for model parts and try to do all these workarounds there to keep it simple to use for other users...

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee ping @RiccardoRossi
