### ISSUE TITLE
[Core] Model part IO spurious print

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/Kratos#3074]
Good afternoon,
I am writing a Multilevel Monte Carlo code, and I read many times the model part files.
I would like to not have the model part written in the terminal every time I to the operation. How can I achievef it?
Thanks.
Riccardo

**Comment by loumalouomega** [comment]
You can reduce the LoggerLevel

**Comment by loumalouomega** [comment]
~~~py
KratosMultiphysics.Logger.GetDefaultOutput().SetSeverity(KratosMultiphysics.Logger.Severity.WARNING)
~~~

**Comment by loumalouomega** [comment]
Can we close this?
