### ISSUE TITLE
Method naming at Model

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#3094]
This is a minor issue, just to propose an alternative to the naming of the method `GetSubPartsList` located at
https://github.com/KratosMultiphysics/Kratos/blob/b14db031e95a96ddacdc64cc7dc3731b72cf025d/kratos/containers/model.cpp#L202
This function basically strips the hierarchic string containing Submodelparts and their sons like "ModelPart1.SubModelPartA.SubModelPartC.SubModelPartH" into a vector of separated strings.
I would propose the following options:

1. StripSubModelPartLineage
2. StripSubModelPartHierarchy
3. StripSubModelPartLineageIntoList
4. StripSubModelPartHierarchyIntoList
5. ...

This is open to other options (that's why I opened the issue!).

**Comment by RiccardoRossi** [comment]
As i am telling i am ok to change the name of this... i'll just use the name we decide (and i don't have any proposal i consider good)

**Comment by maceligueta** [comment]
If nobody complains, I would change it to any of those above (my favourite is number 4).
Just referencing @KratosMultiphysics/technical-committee , though this issue is very minor.

**Comment by jcotela** [comment]
My only comment is that in Python "strip" implies removing some characters at the beginning/end of a string, while the operation you describe (dividing a string at occurrences of a given character into a list) is called "split". Out of familiarity, I would call the method `SplitSubModelPart....` (I don't have a preference for a particular alternative), but I would not oppose the suggested names either.

**Comment by RiccardoRossi** [comment]
+1 for SplitSubModelPartHierarchyIntoList

@maceligueta will you do it or shall i take care?

**Comment by maceligueta** [comment]
I can do it.

**Comment by pooyan-dadvand** [comment]
I would like more `SplitSubModelPartHierarchy` 

I see the into list as somehow redundant....

**Comment by jcotela** [comment]
Closing as solved by #3118
