### ISSUE TITLE
Develompents for tables and properties for the usage in the ConstitutiveLaw

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#31]
I would like to know how to work with tables in a proper way. My question is related with this and with the assignation of tables to Properties. 

If I have a YOUNG_MODULUS variable that is defined by a Table for different temperatures, how I check if the value is supplied by a table of the properties or by a variable of the properties ? Is there any method implemented for that issue?

@KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
Good question! Actually I have checked and we don't have a `Has` method implemented to check if the table exists. So at this moment you can check if your variable exist in properties and if not look for table. But a better solution would be to check if your table exists which needs my implementation.

**Comment by josep-m-carbonell** [comment]
I think it is important to establish the correct behaviour, if it exists a table with that variable, took the value from the table, if not, took it from the constant value in the properties.  

But the constitutive law have to know if there is a table defining that variable and which value must be supplied to get it. 

I would like to have it as soon as possible, if you don't have so much time to do it, maybe you can give me some direction lines of how to implement it properly and I can try to do it.

**Comment by pooyan-dadvand** [comment]
The default behaviour you mentioning is not possible because the interface of getting from a table needs more arguments than the GetValue. Nevertheless I can ignore that additional argument in case where the table is not exist but then I'm adding an if in the almost the most inner loop we have which is not a good idea from performance point of view. Having the has you can make once the check and select the correct constitutive law.

Meanwhile I see that the has is important for you so I will add it soon. (let me check how long it takes me to make the test and the method)

**Comment by josep-m-carbonell** [comment]
Hello Pooyan, that issue that I am asking for has a direct relationship with the new json input file for the constitutive laws and properties of the materials. I have also asked some questions to @RiccardoRossi , about that in the #58. I think the proper functioning of reading variables and tables and then how to ask for the properties inside of the constitutive law have to be defined in order to move forward in this implementation. I don't know if some other people want to join and discuss this. First the technical issues must be exposed to know what it is possible to do and how to proceed.

@KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
I have checked and it is possible to add the Has method. Nevertheless one should pass both X and Y variables:
`properties.Has(VISCOSITY, TEMPERATURE)`

It won't be possible to ask for if there is a table for VISCOSITY
@KratosMultiphysics/technical-committee : is what expected from your point of view?

**Comment by josep-m-carbonell** [comment]
I think it will work.
Right now the tables are supplied as an input in the .mdpa file. Usually stored as a Table of the ModelPart. How can be given and stored directly to the Properties ?

**Comment by pooyan-dadvand** [comment]
As described in [Input data in old wiki](http://kratos-wiki.cimne.upc.edu/index.php/Input_Data) (Meanwhile we should continue the migration of the wiki...)

If there is an issue with it just let me know.

**Comment by josep-m-carbonell** [comment]
ok, thank you. Tell me when the Has method would be available.
