### ISSUE TITLE
ReplaceElementProcess should deep copy elemental variables

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#310]
@pooyan-dadvand could you point me to an example of how to do it?

**Comment by pooyan-dadvand** [comment]
In principle copying a `DataValueContainer` using either the copy constructor or assignment operator (=) make a full copy of the values.

**Comment by pooyan-dadvand** [comment]
Just to add an example: 
`element1.Data() = element2.Data()` 

should clone all copy constructable data from one element to the other.

**Comment by jcotela** [comment]
@RiccardoRossi Can we close this? I think the issue is solved.

**Comment by RiccardoRossi** [comment]
done!
