### ISSUE TITLE
[ShapeOpt] Inverse mapping with improved integration ist producing discontinuous shapes

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#3103]
Inverse mapping with gauss integration fails to produce continous shapes (other integration method not tested). In contrast to that, mapping seems to work (produces continuous shapes). 

ToDo:

- [ ] Carefully check / test the two improved integration methods and identify problem
- [ ] Adjust corresponding unit test in given mapper_test

**Comment by armingeiser** [comment]
Did you push the related branch already?

**Comment by dbaumgaertner** [comment]
Yes. There you go: feature-generalize-vertex-morphing-mapping

**Comment by philbucher** [comment]
is this solved?

**Comment by philbucher** [comment]
is this still active?

**Comment by rubenzorrilla** [comment]
Closing as it seems to be inactive.
