### ISSUE TITLE
[CORE] Calculate DISTANCE in the whole domain in order to use MMG remeshing process

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#3145]
Dear all,

In the CalculateDistanceToSkinProcess2D, which was recently added to the master branch, the distance is computed in the elements that are intersecting the skin model part. The rest of the nodes are assigned 1e38 and -1e38 depending if they are inside or outside the skin model part.

On the other hand, the MMG remeshing process utilizes both the distance and the distance gradient to compute the new mesh.

As only the nodes near the skin part are assigned an _actual_ distance value, the distance gradient that results from the CalculateDistanceToSkinProcess is not smooth, and the remeshing does not properly work. 
This is highlighted in the figures attached. One figure shows the remeshing performed for an ellipse (whose distance was computed in the whole domain with the ellipse equation), and the other figure shows the remeshing performed for a NACA airfoil computed with the CalculateDistanceToSkinProcess.

![ellipse](https://user-images.githubusercontent.com/32136457/47350155-84c92700-d6b5-11e8-8f78-fa329cdf7a69.png)

![naca](https://user-images.githubusercontent.com/32136457/47350140-7b3fbf00-d6b5-11e8-91b3-dfba80a71859.png)

Therefore I have two questions:

- Is there something I can do to use the MMG process in this case? @loumalouomega 
- Can the DistanceToSkinProcess be modified to compute the distance in the whole domain (for both 2D and 3D)? 

If there's something I can do/modify I am open to suggestions!

Thanks,

**Comment by loumalouomega** [comment]
I have several questions, and I think that would be more productive if I call you directly, can you send me an email with your Skype account details?

**Comment by loumalouomega** [comment]
As we spoke we can define a custom metric computation, but would be fine to extend the distance calculation a little bit from the pure boundary, or the gradient would be "so intense" that the results could be anything

**Comment by marcnunezc** [comment]
Dear all,

As suggested by @rubenzorrilla and @RiccardoRossi, I am using the [VariationalDistanceCalculationProcess](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/variational_distance_calculation_process.h) in order to extrapolate the distance values to the whole domain.

So now my code looks like this:

```
self.InitializeSkinModelPart() #Load skin model part
self.CalculateDistance() #Calculate distance to skin
     
maximum_iterations = 2 #TODO: Make this user-definable
variational_distance_process = KratosMultiphysics.VariationalDistanceCalculationProcess2D(
                 self.main_model_part,
                 self.linear_solver,
                 maximum_iterations)
variational_distance_process.Execute()      #Calculate distance in the whole domain

self.RefineMesh() #Compute MMG remeshing
self.CalculateDistance() #Recalculate distance to skin in the new mesh
```
