### ISSUE TITLE
[AMGCL] warning unknown parameter M in fluid tests

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#3148]
We are getting a lot of print outs 

> AMGCL WARNING: unknown parameter M

when running tests in FluidDynamicsApplication. E.g., `python3 adjoint_fluid_test.py`. The parameter is not in the json file, but it seems to be set in some places in amgcl_solver.h. E.g., `mAMGCLParameters.put("solver.M",  mGMRESSize);`.

Does anyone know a fix for this?

**Comment by loumalouomega** [comment]
In fact happens not just with fluids, but with almost all the calls to AMGCL

**Comment by philbucher** [comment]
This issue is a duplicate of #2989

**Comment by msandre** [comment]
Ok, closing.
