### ISSUE TITLE
Compressible potential flow not compiling.

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#3157]
Dear @KratosMultiphysics/team-maintainers the compressible potential flow application is not updated to Model3 and it is causing the nightly build to fail. 

I don't know who is responsible of the application so I am pinging everyone.

**Comment by loumalouomega** [comment]
@jginternational solved that last night

**Comment by philbucher** [comment]
FYI @inigolcanalejo 
@inigolcanalejo this only makes the App compile, you might still need to update your scripts

**Comment by philbucher** [comment]
closing since solved

**Comment by jginternational** [comment]
Again @inigolcanalejo

**Comment by inigolcanalejo** [comment]
Is it still giving errors? I cannot find them.

**Comment by rubenzorrilla** [comment]
@jginternational it is not compiling in Windows right?

**Comment by roigcarlo** [comment]
I did test it again on win and seems to compile fine for me as well.

**Comment by inigolcanalejo** [comment]
I guess it is fine then

**Comment by jginternational** [comment]
I'll be back to the office on Monday. I'll check it with @roigcarlo then

**Comment by roigcarlo** [comment]
This is solved and outdated.
