### ISSUE TITLE
Pfem2 Application is not running on parallel

### ISSUE THREAD

**Issue by dcagritan** [KratosMultiphysics/Kratos#3159]
I can't run any test case on parallel on the Pfem2 Application. Is this a common problem in Kratos that occured recently?

Kind Regards,
Deniz

**Comment by philbucher** [comment]
is this solved?

**Comment by GuillermoCasas** [comment]
Perhaps @miguelmaso knows something about this

**Comment by dcagritan** [comment]
Yes it is solved.
I'm closing the issue.
Regards
