### ISSUE TITLE
[Core] We should separate the register from variables.cpp

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3209]
This is a reminder for @KratosMultiphysics/technical-committee .

Right now all the register on the Core is done on the file variables.cpp, https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/sources/variables.cpp

This is not a priori expected, and additionally makes the file huge. We should think about eventually separate the content of the file in multiple files

**Comment by pooyan-dadvand** [comment]
Forwarding to @KratosMultiphysics/implementation-committee

**Comment by AlejandroCornejo** [comment]
@loumalouomega I tried to do that a few months ago but I came up with some problems... @roigcarlo may know if we have to take care of something in special maybe?

**Comment by loumalouomega** [comment]
In this case I mean in the core, not in the applications, if you take a look at the variables.cpp you will see that everything is registered there. Not just the variables, which it is supposed to be the objective of a file called variables.cpp

**Comment by AlejandroCornejo** [comment]
aaah okkey @loumalouomega , then it is going to be even more time consuming hehe

**Comment by philbucher** [comment]
> aaah okkey @loumalouomega , then it is going to be even more time consuming hehe

@AlejandroCornejo why would it be slower? Then several compilation units could compile at the same time rather than one having to compile a huge junk of code

Not 100% sure but quite sure :)

**Comment by AlejandroCornejo** [comment]
> 
> 
> > aaah okkey @loumalouomega , then it is going to be even more time consuming hehe
> 
> @AlejandroCornejo why would it be slower? Then several compilation units could compile at the same time rather than one having to compile a huge junk of code
> 
> Not 100% sure but quite sure :)

yes yes you're right ! I was thinking in time spent rewriting everything ^^

**Comment by GuillermoCasas** [comment]
See #3666.
