### ISSUE TITLE
Renumbering utility for post-processing coupled applications

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#3222]
When coupling applications, it is very common that each application uses ids of nodes which are already used by other applications. It can be avoided initally with a good renumbering and pre-process, but eventually, those applications adding and removing nodes would need complicated operations to avoid overlapping with others.
Post-processing in a single file is nice, but there's a big danger of having these Ids repeated.
In PR #3175 we created an utility to **Renumber** the ids in several ModelParts and **Undo** the renumbering after having printed.
In that PR @rubenzorrilla  proposed to add this utility to the core. This issue is a reminder for the @KratosMultiphysics/technical-committee , to discuss if this should be an Utility or a Process, and how to send a list of ModelParts to this object.

**Comment by pooyan-dadvand** [comment]
Forwarding to @KratosMultiphysics/implementation-committee

**Comment by loumalouomega** [comment]
@maceligueta can you create a PR simply moving it into the core?, we can have a better discussion in the PR

**Comment by AlejandroCornejo** [comment]
@KratosMultiphysics/implementation-committee  It would be okay for the core but we have several questions... 
1. Make sure it is geenral: it whould accept a list of MPs
2. If it is only for printing, perhaps it should be made an option of the IO or a specialized IO
We would accept such a design and we think it would be very useful

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agrees with this decision. Thanks for your comments. 

@maceligueta would take note of the suggestions for the future implementation
