### ISSUE TITLE
[MPI/Trilinos] Unable to runt the tests

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3225]
When I try to run the Trilinos tests I get the following error:

~~~
File "/home/vicente/src/Kratos/KratosMultiphysics/TrilinosApplication.py", line 2, in <module>
    from KratosTrilinosApplication import *
ImportError: /home/vicente/src/Kratos/libs/KratosTrilinosApplication.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN9ML_Epetra11SetDefaultsENSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERN7Teuchos13ParameterListEPiPdb
~~~

@roigcarlo suggested that can be due to a problem with the libraries included in Ubuntu. Any idea?

Many thanks

**Comment by jcotela** [comment]
Things to check locally
- Where are your trilinos libs? is that route in your LD_LIBRARY_PATH?
- does `ldd /home/vicente/src/Kratos/libs/KratosTrilinosApplication.cpython-37m-x86_64-linux-gnu.so` tell you that all the linked trilinos libraries are found?

The symbol you cannot find is
```
ML_Epetra::SetDefaults(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Teuchos::ParameterList&, int*, double*, bool)
```
which points to the ML library. Is that library included in your trilinos compilation?

**Comment by loumalouomega** [comment]
Thanks @jcotela , I will try

**Comment by loumalouomega** [comment]
>     * LD_LIBRARY_PATH

![imagen](https://user-images.githubusercontent.com/19991680/47873046-78a93c00-de10-11e8-8dc7-68bd323d3960.png)
 Not working

**Comment by loumalouomega** [comment]
>     * does `ldd /home/vicente/src/Kratos/libs/KratosTrilinosApplication.cpython-37m-x86_64-linux-gnu.so` tell you that all the linked trilinos libraries are found?
![imagen](https://user-images.githubusercontent.com/19991680/47873141-b4440600-de10-11e8-9d16-0194c2bfc551.png)
Looks right to me

**Comment by loumalouomega** [comment]
> ML_Epetra::SetDefaults(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, Teuchos::ParameterList&, int*, double*, bool)
> ```
> 
> which points to the ML library. Is that library included in your trilinos compilation?

![imagen](https://user-images.githubusercontent.com/19991680/47873238-f9683800-de10-11e8-9813-b1ff54003880.png)
 I think so

**Comment by roigcarlo** [comment]
@loumalouomega how is this progressing, any luck?

**Comment by loumalouomega** [comment]
Nope, still the same problem

**Comment by roigcarlo** [comment]
I know is not the ideal solution but could yo try with your own compiled trilinos? Just to make sure its not a problem of the lib

**Comment by loumalouomega** [comment]
I can, but that would take me some extra time

**Comment by philbucher** [comment]
did you try @loumalouomega ?

**Comment by philbucher** [comment]
ping

**Comment by philbucher** [comment]
can we close this?
Afaik this problem did not appear elsewhere

**Comment by philbucher** [comment]
closing since inactive
