### ISSUE TITLE
[ShapeOpt] Seg-fault when not initializing existing elements before GidIO is initialized

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#3234]
The problem is as follows:

Given an optimization model part which contains elements. Gid is specified as output format. If the elements of the optimization model part are not initialized (which may happen e.g. when no internal analyzer is defined), then the function GiDOutputProcess::ExecuteBeforeSolutionLoop will produce a seg-fault when it calls   

`__initialize_results --> gid_io.h line 643 inside the function InitializeResults. -> AddElement in gid_gauss_point_container.h line 72. `

The reason is that for a not initialized element, the function pElemIt->GetIntegrationMethod()  returns a random number causing a failure of 

`pElemIt->GetGeometry().IntegrationPoints(->GetIntegrationMethod() )`

That means as a consequence, all elements must be initialized before the gid output process is initialized. Right now, this is done by the analyzer through InitializeBeforeOptimizationLoop(), which internally calls the physical solver that does the job. However, this creates an unwanted link between the data logger and the analyzer. Also, it determined the call order. I.e. initializing the analyzer after the gid output process will again create a segfault. 

In either case the seg-fault can be avoided by writing only the design surface (whicho only has conditions without gauss points). As soon as the complete optimization model part shall be written, the error happens again.

As currently the call order in each algorithm is such that no seg-fault is produced, there is no immediate action required. But in the future, this unwanted behavior needs to be removed. This leads to two tasks:

- [ ] Better define output of the optimization model part so that a clean model with only the optimization results is written (e.g. no Gauss point results are specifiable)

- [ ] Make sure that there is no such implicit dependency of the data logger from the (internal) analyzer. Maybe initialize possibly given elements with default settings.

**Comment by armingeiser** [comment]
I don't know if we can call it an unwanted link between data logger and analyzer.
The data logger for the whole modelpart needs the initialized model part as a prerequisite. If we wan't to use it, we need to make sure it is initialized before.
The fact that its not the case for the design surface output is just lucky coincidence and i think we should rather make sure that also that is properly initialized in any case.

**Comment by philbucher** [comment]
is this still active?

**Comment by dbaumgaertner** [comment]
Yes in a sense that it is still to be solved. We use it as an issue on our project page.
