### ISSUE TITLE
[GitHub] New utilities for GitHub

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3250]
@KratosMultiphysics/technical-committee the following may interest you:

https://probot.github.io/ A bot to add some additional features to GitHub

https://github.com/github-changelog-generator/github-changelog-generator An utility to generate changelogs

**Comment by pooyan-dadvand** [comment]
Interesting! especially the change log one!!

**Comment by loumalouomega** [comment]
Feel free to close whenever you thing this is not required anymore

**Comment by loumalouomega** [comment]
Closing
