### ISSUE TITLE
Tests failing in StructuralMechanics

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3259]
The following tests are failing in my machine: (master, GCC 7.3, without cotire)

~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.SmallDeformationPlasticityTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 59, in test_execution
    self.test.RunSolutionLoop()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 60, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/analysis_stage.py", line 134, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/philipp/software/Kratos_MasterBranch/kratos/python_scripts/from_json_check_result_process.py", line 208, in ExecuteFinalizeSolutionStep
    self.assertTrue(isclosethis, msg=(str(value[gp]) + " != " + str(value_json) + ", rel_tol = " + str(reltol) + ", abs_tol = " + str(tol) + " : Error checking elem " + str(elem.Id) + " " + variable_name + " results."))
AssertionError: False is not true : nan != 3000002.499994993, rel_tol = 1e-06, abs_tol = 0.001 : Error checking elem 1 UNIAXIAL_STRESS results.
~~~

~~~
Ran 36 of 585 test cases in 0.0112561s. 1 failed:
    TestTestSPRErrorProcess2 Failed with message: 
        Error: Check failed because (0.122409 - process_info[ERROR_OVERALL])/0.122409 is greater than 1.0e-5
in /home/philipp/software/Kratos_MasterBranch/applications/StructuralMechanicsApplication/tests/cpp_tests/test_spr_error_process.cpp:289:virtual void Testing::TestTestSPRErrorProcess2::TestFunction()
~~~

Plus there are a lot of warnings now:
`Backward Euler Plasticity: Maximum number of iterations in plasticity loop reached...` but I guess until we found a global solution those cannot be avoided

**Comment by AlejandroCornejo** [comment]
I'll take a look at that with @loumalouomega !!
thank you

**Comment by loumalouomega** [comment]
@AlejandroCornejo this is related with the changes you id last Friday (when removing the evil reference), and this is a small deformation test...

**Comment by loumalouomega** [comment]
Did you run all the tests before commit?

**Comment by AlejandroCornejo** [comment]
nope but with which solution is it comparing? obviously the previous solution was wrong..

**Comment by AlejandroCornejo** [comment]
If I had broken something badly the cpp test would not be passing as well, aren't they?

**Comment by AlejandroCornejo** [comment]
I'm testing the plasticity law in a minute

**Comment by loumalouomega** [comment]
I confirm, reverting #3242 it does work. Can you check it @AlejandroCornejo the problem is the one you pass me to check the plasticity

**Comment by loumalouomega** [comment]
The cpp tests run on 1 iteration, so in more non-linear cases this can broke

**Comment by loumalouomega** [comment]
> nope but with which solution is it comparing? obviously the previous solution was wrong..

Probably, that's why I am asking you to check.

**Comment by loumalouomega** [comment]
[test_plasticity.zip](https://github.com/KratosMultiphysics/Kratos/files/2551857/test_plasticity.zip)

Even considering viscosity the problem is not working. I attach exactly same problem you sent me.

**Comment by AlejandroCornejo** [comment]
I' attach you the correct version of the test @loumalouomega 
[test_plasticity.zip](https://github.com/KratosMultiphysics/Kratos/files/2552879/test_plasticity.zip)
