### ISSUE TITLE
Error when preparing data for analysis in DEM

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#3260]
@KratosMultiphysics/dem I just merged the current master and find myself unable to run problems in GID with dem C-DEM app now. When I try to run a problem I get following error message

> Error when preparing data for analysis (can't read "imposed_velocity_X": no such variable)

I do not understand the nature of this problem, as I am not imposing any velocity. Was there sth merged which causes this problem?

**Comment by KlausBSautter** [comment]
this , by the way, only happens if I am assigning a surface to a DEM-FEM wall

**Comment by KlausBSautter** [comment]
https://gigamove.rz.rwth-aachen.de/download/id/wdmWRccstpKfSx

**Comment by farrufat-cimne** [comment]
Hi @KlausBSautter, I will take a look at the problem right now. Probably something related with the last update.

Thx

**Comment by joaquinirazabal** [comment]
I am sure it comes from the last update, I am also checking it, thx

**Comment by farrufat-cimne** [comment]
Hi @KlausBSautter, it doesnt really affects the issue (shared tcl), but the example uploaded was generated with the G-Dempack problemtype doesnt it?

**Comment by KlausBSautter** [comment]
no I am pretty sure it was C-DEM

**Comment by KlausBSautter** [comment]
.... sry of course G-DEM. I am mixing those two in my head all the time

**Comment by joaquinirazabal** [comment]
I have just found the problem, it was something that has to be inside an if that it wasn't. I leave the new file Kratos/applications/DEM_application/custom_problemtype/DEMpack/scripts/libs/wkcf/wkcfdem.tcl here and prepare a pull request.

[wkcfdem.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/2548249/wkcfdem.tar.gz)

**Comment by KlausBSautter** [comment]
@joaquinirazabal  thanks! now it works
