### ISSUE TITLE
DEMPack Tutorial Question

### ISSUE THREAD

**Issue by Furui-Lab** [KratosMultiphysics/Kratos#327]
Hi,

We are working on the tutorial probolem No. 1 in DEMPack. We are trying to follow the user guide but we can't find "initial conditions" tub in the model window. Could you please help us what's wrong here? Attached files are the .gid files and the screenshot of teh DEMPack2. Thanks,

Kenji Furui
![tutorial](https://cloud.githubusercontent.com/assets/27983476/25364584/67a1a816-299e-11e7-8921-e13ac271096d.png)
[D_DEMPack2_Tutorial_4.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/953592/D_DEMPack2_Tutorial_4.gid.zip)

**Comment by merceln** [comment]
Dear Kenji Furui

The tutorial you mention correspond to a DEMPack version that is not downloadable yet from our website. We are sorry that the links on the DEMPack tutorials were wrong. You can have the correct manual and tutorial following these links:
http://kratos-wiki.cimne.upc.edu/index.php/D-DEMPack_manual
http://kratos-wiki.cimne.upc.edu/index.php/D-DEMPack_Tutorial_1:_Conveyor_belt 

We will upload in the next days the new release version of DEMPack with its corresponding documentation.

Sorry for the inconvenience

M López

**Comment by philbucher** [comment]
Seems to not be active
Please reopen if I am wrong
