### ISSUE TITLE
Working Space Dimension deprecated in mesh

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#3275]
Seems that `WorkingSpaceDimension()` call is deprecated and should be using the geometry one. Someone can confirm?

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/mesh.h#L254-L269

**Comment by philbucher** [comment]
I deprecated this, therefore confirm => #2997 

Want me to change it?

**Comment by roigcarlo** [comment]
If you can, that would be nice :+1:
