### ISSUE TITLE
Feast constructor inconsistency

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#3277]
Defaults and check for this solver constructor are not matching.

https://github.com/KratosMultiphysics/Kratos/blob/60b6b3a672cc0af703b9cef45bcd040f794ede3c/applications/ExternalSolversApplication/external_includes/feast_solver.h#L98-L105

**Comment by roigcarlo** [comment]
@loumalouomega ping

**Comment by loumalouomega** [comment]
Ups

**Comment by loumalouomega** [comment]
It is not wrong, the check is performed in first place, the second check is to tell you that if you want to consider the standard skyline instead of the complex you should use the other constructor

I haven't implemented that BTW

**Comment by josep-m-carbonell** [comment]
then ->  != "complex_skyline_lu_solver"  instead of    -> != "skyline_lu"

**Comment by loumalouomega** [comment]
Is not the same check, those are two different checks

**Comment by josep-m-carbonell** [comment]
The person who changed it broke the SolidApp tests twice. First changing to complex, and now with the second wrong check. But if everything is correct, then, no problem. Let's close the issue and go ahead with another thing.

**Comment by philbucher** [comment]
is this solved?

**Comment by josep-m-carbonell** [comment]
my issue is solved, the code is wrong

**Comment by RiccardoRossi** [comment]
from what i understand 

https://github.com/KratosMultiphysics/Kratos/blob/60b6b3a672cc0af703b9cef45bcd040f794ede3c/applications/ExternalSolversApplication/external_includes/feast_solver.h#L105

should be changed complex_skyline_.... @msandre is that so?

i don't really understand why that check is needed...

**Comment by msandre** [comment]
Yes, it looks like I changed both to complex_skyline_lu_solver in cb2740db19, but  c8bc4b7f92 also changed the line and the error probably crept in while fixing a merge conflict.

| * cb2740db19 making feast work with new eigen_solver_factory
* | c8bc4b7f92 removing use of Parameters::Pointer
|/  
* 9948b16d01 adding overrides

I think it's to guard against an user selecting the wrong skyline for feast.

**Comment by philbucher** [comment]
@loumalouomega didn't you already fix this?

**Comment by loumalouomega** [comment]
I think so

**Comment by jcotela** [comment]
Looks like it was corrected in the current master (by @loumalouomega)
https://github.com/KratosMultiphysics/Kratos/blob/5404d914a8bd6e343ccbc859c028e298deeee194/applications/ExternalSolversApplication/external_includes/feast_solver.h#L99-L108

**Comment by loumalouomega** [comment]
Looks like :D

**Comment by jcotela** [comment]
Closing then. Reopen if it creeps back in, I guess...
