### ISSUE TITLE
Core MPC test fails if StructuralMechanics is not compiled

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3281]
Title says all, the test should be skipped if the app is not available
~~~
======================================================================
ERROR: test_MPC_Constraints (test_linear_master_slave_constraints.TestLinearMultipointConstraints)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_Master/kratos/tests/test_linear_master_slave_constraints.py", line 276, in test_MPC_Constraints
    self._setup_model_part()
  File "/home/philippb/software/Kratos_Master/kratos/tests/test_linear_master_slave_constraints.py", line 227, in _setup_model_part
    [14, 11, 12, 15], self.mp.GetProperties()[1])
RuntimeError: Error: The component is not registered!SmallDisplacementElement2D4N


in kratos/includes/kratos_components.h:102:static const TComponentType& KratosComponents<TComponentType>::Get(const string&) [with TComponentType = Element; __cxx11::string = __cxx11::basic_string<char>]
   kratos/sources/model_part.cpp:779:Element::Pointer ModelPart::CreateNewElement(__cxx11::string, ModelPart::IndexType, Geometry<Node<3ul> >::PointsArrayType, Properties::Pointer, ModelPart::IndexType)
~~~

**Comment by loumalouomega** [comment]
I am adding a dummy 2D bar element in  #3236, that could help...The problem is that the element is not exported to python

**Comment by RiccardoRossi** [comment]
Interesting...because i SPECIFICALLY ASKED if tests were running correctly without the StructuralMechanicsApplication ;-)

**Comment by pooyan-dadvand** [comment]
@loumalouomega I would go for the distance element that is in the core rather than adding a dummy one.

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand i suggested adding a new one. It is added as part as the test and not registered, so it does not do any harm

**Comment by loumalouomega** [comment]
Ok, but remember that this test is from @adityaghantasala 

BTW, the test_material_input.py requires FluidDynamicsApplication @jcotela

**Comment by jcotela** [comment]
@loumalouomega I know, but that one has the proper checks to be skipped if the user does not compile it. If I remember correctly, it was done deliberately to test importing constitutive laws using the `Module.LawName` syntax.

**Comment by loumalouomega** [comment]
Yes, the problem can be easily solved anyway

**Comment by loumalouomega** [comment]
Done

**Comment by pooyan-dadvand** [comment]
My concern about the dummy one is the fact that it can go easily out of new changes in element and give us false ok in the test. The distance element should always work and it would be good test example....
