### ISSUE TITLE
Error: Zero aggregates found - 2D CFD problem

### ISSUE THREAD

**Issue by 94zz94** [KratosMultiphysics/Kratos#3295]
Hi everyone, I'm using the developer version of KratosMulti-Physics 6.0.0-60b6b3a672.
In the problemtype->kratos->Fluid->2D I run the example simulation of the cylinder and it worked.
Then I replicate the example with no problems, in the end I tried an easy 2D example from TUM's slide (that I know worked in previous versions of kratos) and some errors are printed out;
I compared the MainKratos.py and the ProjectParameter.json files to see if there were some differences but I found nothing relevant (only few caps locks).
That's what the terminal printed out:

Fluid Dynamics Analysis: Analysis -START-  
Setup Dofs Time: 0.00658291
Setup System Time: 0.000630464
System Matrix Resize Time: 0.0270951
System Construction Time: 0.0349163
Fluid Dynamics Analysis: STEP:  1 
Fluid Dynamics Analysis: TIME:  0.01 
ResidualBasedBlockBuilderAndSolver: Build time: 0.0027196
ResidualBasedBlockBuilderAndSolver: System solve time: 0.446164
CONVERGENCE CHECK:
 VELOC.: ratio = -nan; exp.ratio = 0.001 abs = -nan exp.abs = 1e-05
 PRESS.: ratio = nan; exp.ratio = 0.001 abs = nan exp.abs = 1e-05
ResidualBasedBlockBuilderAndSolver: Build time: 0.00271929
Traceback (most recent call last):
  File "MainKratos.py", line 34, in <module>
    simulation.Run()
  File "/home/bod-cwe/Kratos/kratos/python_scripts/analysis_stage.py", line 48, in Run
    self.RunSolutionLoop()
  File "/home/bod-cwe/Kratos/kratos/python_scripts/analysis_stage.py", line 59, in RunSolutionLoop
    self._GetSolver().SolveSolutionStep()
  File "/home/bod-cwe/Kratos/applications/FluidDynamicsApplication/python_scripts/fluid_solver.py", line 111, in SolveSolutionStep
    is_converged = self.solver.SolveSolutionStep()
RuntimeError: Error: Zero aggregates found.

in kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:366:void ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::SystemSolveWithPhysics(ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemMatrixType&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType&, ModelPart&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; TLinearSolver = LinearSolver<UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >, UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >; ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemMatrixType = boost::numeric::ublas::compressed_matrix<...>; ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType = boost::numeric::ublas::vector<double>]
   kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h:410:void ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::BuildAndSolve(typename ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::BaseType::TSchemeType::Pointer, ModelPart&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemMatrixType&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType&, ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType&) [with TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >; TDenseSpace = UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> >; TLinearSolver = LinearSolver<UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >, UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > >; typename ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::BaseType::TSchemeType::Pointer = shared_ptr<Scheme<UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::ublas::vector<double> >, UblasSpace<double, boost::numeric::ublas::matrix<double>, boost::numeric::ublas::vector<double> > > >; ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemMatrixType = boost::numeric::ublas::compressed_matrix<...>; ResidualBasedBlockBuilderAndSolver<TSparseSpace,...>::TSystemVectorType = boost::numeric::ublas::vector<double>]

BuilderAndSolver: Clear Function called
KRATOS TERMINATED WITH ERROR

It seems a problem of convergence or a numeric zero division since it compares VELOC.: ratio = -nan
I tried to modify the setting of the solver but nothing changed.
Could you help me with that?
I leave you in annex the folder created by GID for the mesh
Thank you
Enrico

[2Dproblem.zip](https://github.com/KratosMultiphysics/Kratos/files/2554271/2Dproblem.zip)
@rubenzorrilla

**Comment by RiccardoRossi** [comment]
We fixed some important error in the amgcl solver ... however the fix is not in version 6.0

do you have the possibility of compiling the latest version?

**Comment by 94zz94** [comment]
I think I already have the latest version, since I compiled Kratos 3 days ago...do I have to upgrade ?

**Comment by RiccardoRossi** [comment]
nope...

**Comment by rubenzorrilla** [comment]
@94zz94 after a very brief discussion with @RiccardoRossi , we realised that the slip boundary conditions are not being written in the *.mdpa file. Without such conditions, there is no normal vector, which turns to be a nan.

We will take care of that ASAP. Until we fix it, you can impose symmetry conditions in the flow by substituting the slip boundary condition process in the json file by this:
```
{
      "python_module" : "assign_vector_variable_process",
      "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
      "process_name"  : "AssignVectorVariableProcess",
      "Parameters"    : {
                "model_part_name" : "FluidModelPart.Slip2D",
                "variable_name": "VELOCITY",
                "value": [null,0.0,null],
                "constrained": [false,true,false],
                "interval": [0.0,"End"]
      }
}
```

@jginternational may this be related with the last change we did in the FluidDynamicsApplication writting?

BTW, thanks for reporting!

**Comment by 94zz94** [comment]
Thank you, now it's working fine but I have another issue...
Now the program GID x64 14.1.0d is not able to read the output file, even if imported.
Is there a way to bypass the problem or do I have to wait until the fix is available?

**Comment by rubenzorrilla** [comment]
In my case the output works perfectly... I cannot see the reason why GiD is not opening it. Which kind of error you get?

**Comment by 94zz94** [comment]
I'm sorry..everything ok...I shouldn't renamed the folder
Thank you very much for your kindness

**Comment by rubenzorrilla** [comment]
GUI fixed by @jginternational . @94zz94 I'm closing it. Do not hesitate to open it again if needed.

**Comment by RiccardoRossi** [comment]
@rubenzorrilla this means that @94zz94 needs to download the problemtype from git right?

**Comment by rubenzorrilla** [comment]
@RiccardoRossi yes, he needs to do a `git pull` inside the GiD interface folder.
