### ISSUE TITLE
adding nodes (3D - IS_STRUCTURE)

### ISSUE THREAD

**Issue by elafnm** [KratosMultiphysics/Kratos#3296]
@pooyan-dadvand 

Greetings dear,

We are almost completed the surface_tension codes in 2D, and now, we are moving to the 3D, 

Here I am not able to add nodes on the IS_STRUCTURE (as you can find in the attached two figures, where the nodes are added as the droplets move except for the IS_STRUCURE). 

I tried to work on the TETGEN "pfem refine" but I am not sure yet what I need to do and what routines I need to add. could you please advise, and in case there is a working example that I can follow.

Thanks and best regards,

![final_position](https://user-images.githubusercontent.com/30217273/48092410-d0a5c100-e1c9-11e8-807c-0b792248c7dd.png)
![initial_position](https://user-images.githubusercontent.com/30217273/48092417-d9969280-e1c9-11e8-8cb9-6ad84a5315d5.png)

**Comment by elafnm** [comment]
@pooyan-dadvand 

![is_free_final](https://user-images.githubusercontent.com/30217273/48102928-78cb8200-e1ea-11e8-8baa-5b6cfb2275fc.png)
the same thing for the faces, nods are not added here as well,

I tried to use the pfem-face-refinement tetgen file but not sure how to make it work,

best regards,

**Comment by pooyan-dadvand** [comment]
I am not familiar with tetgen....

@playpaolo and @RiccardoRossi ?

**Comment by playpaolo** [comment]
Ill take care of it.
