### ISSUE TITLE
[PFEM]:could we simulate the dam break with pfem using inflow and outflow

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3312]
Hello,everyone
These days, our group meet a disaster about dam break. And now, we want to use the pfem to simulate the dam break process,especially using the inflow and outflow( because the flow continuous).
So search for help for all of you.
Best regards.

**Comment by fengzekang** [comment]
Dear @josep-m-carbonell 
DO you know the PFEM with inlet?

**Comment by josep-m-carbonell** [comment]
Dear Feng, yes it is possible to use an inlet, there is a process to set it. There is still no test for it in the repository. We will try to make a test to show how it works.

**Comment by fengzekang** [comment]
Dear   @josep-m-carbonell Maria
How long can you make a test example about inlet, these days we meet a heavy disaster about dam break. I think it is useful to use PFEM to simulate the process, but the inflow is a problem how to use it?
And also, if you are online the Skepy, we can talk with that.
Best regards

**Comment by fengzekang** [comment]
![2018-11-10 15-33-44](https://user-images.githubusercontent.com/38140045/48298789-2649d880-e4fe-11e8-96f7-30276f003983.png)
Why I can't find the PFEM application in GID.KRATOS?

**Comment by josep-m-carbonell** [comment]
The one that is downloaded directly from GiD is the release version. You want the development one. https://github.com/KratosMultiphysics/GiDInterface
You can follow the steps defined in the readme.

**Comment by fengzekang** [comment]
Hi,everyone:
In addition, If I silulate the dam break, I can control the inflow velocity(equal to the flow value) using the inlet boundaty. How can I record the amount of water flowing out? Moreover, can we use a flow function as the water level changes（in the .json file, there is only the velocity of inlet, and also it is a constant value)？
Best regards~

**Comment by josep-m-carbonell** [comment]
Is it possible that the inlet is not working propertly ¿? @AFranci , @maceligueta , @jgonzalezusua , @ipouplana ¿?

**Comment by fengzekang** [comment]
Hi, @josep-m-carbonell 
I have changed the .mdpa, imposing a velocity in the boundaries to keep them fixed. 
But there is also the problem: the dam and water pass through the boundary(As shown in figure). Should I change the dt to control this? Is it necessary?
Best regards.
[Dam_break_3D.zip](https://github.com/KratosMultiphysics/Kratos/files/2572024/Dam_break_3D.zip)
![screenshot from 2018-11-12 21-21-42](https://user-images.githubusercontent.com/38140045/48350066-ff87cf80-e6c0-11e8-8850-b9df0effdb6b.png)

**Comment by josep-m-carbonell** [comment]
Hi @fengzekang, I think you must refine your fluid mesh near the solid boundary. "PfemFluid" application is depicting full rigid elements as fluid element, I think the fluid is not trespassing, just some rigid elements are formed in the boundaries. I don't know why this elements are depicted. We must ask @AFranci.

**Comment by ipouplana** [comment]
I think the inlet should work, but I don't know if you can measure the amount of water flowing out... @AFranci ?

**Comment by josep-m-carbonell** [comment]
The left part is actually a inlet boundary...
![inlet-dam](https://user-images.githubusercontent.com/23210788/48377012-e8e77580-e6cc-11e8-80ea-97c551031449.gif)

**Comment by fengzekang** [comment]
Dear @josep-m-carbonell 
Okay,I will change the mesh size of the fluid of water and dam model.
As for the gif, is this the inlet boundary in input files I attached?As same as the inlet boundary which I defined.
Best regards

**Comment by fengzekang** [comment]
![screenshot from 2018-11-13 17-18-57](https://user-images.githubusercontent.com/38140045/48403258-7deb7c80-e768-11e8-9258-b109c36db629.png)
![screenshot from 2018-11-13 17-19-18](https://user-images.githubusercontent.com/38140045/48403269-82b03080-e768-11e8-8859-56966821c002.png)
![screenshot from 2018-11-13 17-19-30](https://user-images.githubusercontent.com/38140045/48403276-8643b780-e768-11e8-8148-ca29fa84fb67.png)
![screenshot from 2018-11-13 17-19-45](https://user-images.githubusercontent.com/38140045/48403284-89d73e80-e768-11e8-8be6-b684befc2508.png)
For this test, the water and dam pass through the boundary totally. If I can control this problem, it will be right to simulate the dam_break with inlet boundary.

**Comment by AFranci** [comment]
Hi everyone,
@josep-m-carbonell, looking to your animation, I think you didn't assign to the inlet boundary a rigid part. If you do like that it should work.
@fengzekang which PFEM interface are you using? In case of using the PfemFluid one, all the rigid boundaries should have a mesh size similar to the one of the fluid (even better if it is the same as the fluid). Moreover, you have to put them in a rigid part and assign to them some velocity boundary conditions. Maybe the troubles come from this...

**Comment by fengzekang** [comment]
Thanks for your reply. @AFranci 
You mean that if I set the size of boundary similar to the size of fluid element, the problem passing through will be solved, right?
I have set the velocity of rigid boundaries as 0.0.
In addtion, is there the limit of the number of element? More elements just cost more memory?
Best regards.

**Comment by fengzekang** [comment]
Dear @ @AFranci 
Could you please help me test this example, as attached.
I have changed the size of mesh. But there is also the problem exist (the dam passing through the boundary).  
If you have the spare time, can you help me do a test.
Best regards.
[Dam_Break3D.zip](https://github.com/KratosMultiphysics/Kratos/files/2579495/Dam_Break3D.zip)

**Comment by fengzekang** [comment]
Hi @josep-m-carbonell ,
Do you have spare time today, can you help me do a test of this example?
[Dam_Break3D.zip](https://github.com/KratosMultiphysics/Kratos/files/2580613/Dam_Break3D.zip)

**Comment by josep-m-carbonell** [comment]
Hi @fengzekang, 
I am busy, however I will try to sent you an example using the Pfem application instead of the PfemFluid before the end of this week.
Right now the solid in the Pfem applications is not remeshed and it does not flow. What do you expect from the solid dam part?

**Comment by fengzekang** [comment]
Dear Maria
Thanks so much for your reply. Wish that it has not affected your work.
For this simulation, we want to reach the dam break, not only the fluid push the dam structure looks like the dam_break_2D. For the solid dam part, we want to use large viscosity coefficient which different from the fluid, so there will be the break of the dam.
In addition, as for the Pfemsolidapplication, is it used to simulated the fluid and solid interaction problem?  Which one of Pfemapplication, Pfemfluidapplication, Pfemsolidapplication is the best method to do the simulation like the dam_break?（Water hits the dam, causing destroy to the dam）
Best regards.

**Comment by josep-m-carbonell** [comment]
If you need to model a non-newtonian material flow for the dam, maybe @AFranci can guide you how to do something to treat the dam as a type of non-newtonian fluid. If it is modelled as solid,I guess that the dam breakage can not be modelled with the current status of the code with any of the applications.

**Comment by fengzekang** [comment]
Thanks very much for your suggestion. Tomorrow I will discuss this with my surpervisor.
And some days later, can I send you an email and make a copy for my surpervisor, where I will introduce both of you for each other? I think it will be better for our Cooperation in the futher.
Best regards

**Comment by fengzekang** [comment]
Dear @AFranci 
Are you online? For the dam break, the dam was defined as solid with a rigid boundary in the Dam_bereak_2D example, which looks like the FSI, the water only pushed the dam structure(no destroy).
But in the practical engineering, the dam will be break gradually. So could we just use the solid or non-newtonian type to define the dam? 
Looking forward to your reply.
Best regards.

**Comment by fengzekang** [comment]
Dear @josep-m-carbonell  and @AFranci 
Until now, I have set a sample test based on the Dam_break_2D, I changed the dam from 'Solid' into 'fluid'(But for the parameters,  I don't know some of them, how can I control the stiffness of the fluid to make the fluid element can 'stand' at the beginning and have high stiffness. (Following figure shows the dam collapse due to the gravity, I know it is fluid, is there any method or parameters can control this?)
![screenshot from 2018-11-17 01-40-40](https://user-images.githubusercontent.com/38140045/48637837-d42b1a80-ea09-11e8-858d-9b7a364a09fa.png)
Now, I can use the inlet boundary and make the interaction between fluid(water) and fluid(dam). 
![screenshot from 2018-11-17 01-43-59](https://user-images.githubusercontent.com/38140045/48637994-4865be00-ea0a-11e8-9bb3-5ee05e2edb6c.png)
As for the dam, can we change the parameters of fluid to control it? If it's wrong to define the dam as fluid, any methods to simulate the break process (just like the figure2) due to the water push?
Best regards.

**Comment by josep-m-carbonell** [comment]
Hello @fengzekang. 
The fracture, erosion or breakage of a solid part can be a product of different phenomena.  Right now, with the current development of the pfem in kratos we can not handle this type of problem. The current implementation is based on the simulation of fluid movement in a basic stage. Problems combining to fluids with different densities or behavior are also something not addressed specifically in the current implementation because, if you consider this, then you must to start to account for the miscible or not miscible fluids. Surface tension between different fluid interfaces, in fact it is a complex problem. 
There is still a long way to do, all contributions are welcome. 
For the problem you are showing, some trick can be done, like setting gravity to zero or very small value to dam elements, adding a submodel part with this nodes and a process that sets the value to them. However this is only a trick that will not solve the problem of the solid dam.

**Comment by josep-m-carbonell** [comment]
By my side, I am not working with the PfemFluid right now, I am developing the Pfem application, which, in the future, will handle problems related with solids and fluids. Initially in a separated way and then I will couple them. Trying to reproduce the fluid dam-break only with the Pfem app, I can send you this example, I have been solving some problems after running the case several times. The working branch is the pfem/develop. It is a new implementation (this year) and there are still a lot of thing to polish. You can try to run it, maybe it can help you in some way.
[big_dam_test_rigid.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2590435/big_dam_test_rigid.gid.zip)

**Comment by fengzekang** [comment]
Hi, @josep-m-carbonell 
Yeah, this problem troubled me for several days. If I use 'solid', the dam will not break. But if I use the 'fluid', they will interact and the dam fluid will be 'break', but at the beginning, the dam will collapse. And also, after the discussion with my tutor, can we use the non-newton fluid to define the dam, because it is high viscosity. 
And then thanks for your suggestion, I make a  try to change the gravity. I will give you a result after I made it.
Finally, Have a good night. I must go to sleep(2:30 am, Beijing)
Best regards~

**Comment by fengzekang** [comment]
Thanks very much for your help~ @josep-m-carbonell

**Comment by AFranci** [comment]
Hi @fengzekang ,
Sorry for the delay of the response but I am very busy in these days...
I am glad to see that you finally could model correctly the water column collapse and its intereaction with the rigid walls. As a general rule, it is better to start with the 2D problem and then move to the 3D one...
On the other hand, the breaking of the dam, as already Dr. Carbonell told you, is not as simple. Up to now, we do not have a FSI model with solids that are undergoing fracture. 
You proposed to model the dam with as a non-Newtonian fluid...I think this can give you just a coarse idea of the problem, but of course all depends on the material of the real dam. However, if you are interested in this strategy and you want to make the dam more resistent, you can try to increase both its viscosity and yield stress (see here the formulation that is implemented https://www.sciencedirect.com/science/article/pii/S0377025718300399). However, two-fluid problems have not been tested yet with the required detail (it will be done in the next future).
Regards and good luck!

**Comment by fengzekang** [comment]
Dear @AFranci 
Thanks very much for your reply. These days I also read some papers which said the FSI problem mostly as same as what you said. The interaction between fluid and solid to reach the fraction of solid is diffculte. As for the two kinds of fluid, I think the interaction between these can just only show the general phenomenon, but it should not solve the fundamental problem of the solid dam.
Thanks for your guid. I will try it. 
In addayion, I find that http://www.cimne.com/pfem/dam.asp ,there is an example looks lile this
![dam_safty](https://user-images.githubusercontent.com/38140045/48659088-f31bc200-ea86-11e8-9234-be7b7add9736.png) Is this the interaction between fluid and soil? Or just the water flowing out through the hole of dam?
Finally, wish you a nice weekend.
Best regards~

**Comment by AFranci** [comment]
As far I know, the example of the web is just a fluid dynamic case. The dam is modeled as a rigid body without a fracture model.

**Comment by philbucher** [comment]
Closing dince inactive
