### ISSUE TITLE
What is the official way to retrieve a certain value from a process in a simulation?

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#3318]
Dear all,

@RiccardoTosi and me are running a MonteCarlo analysis with the potential flow application. For every simulation of the potential flow application that is executed, we want to retrieve the lift coefficient that is computed [in this process](https://github.com/KratosMultiphysics/Kratos/blob/MonteCarloCompressibleFlow/applications/CompressiblePotentialFlowApplication/python_scripts/compute_lift_process.py) and use it outside the simulation.Run() call. 

Right now we are saving the value in a variable container in the RootModelPart and retrieving it like this:

> def execution_task(model_part_file_name, parameter_file_name):
>     with open(parameter_file_name,'r') as parameter_file:
>         parameters = KratosMultiphysics.Parameters(parameter_file.read())
>     local_parameters = parameters # in case there are more parameters file, we rename them
>     model = KratosMultiphysics.Model()
>     local_parameters["solver_settings"]["model_import_settings"]["input_filename"].SetString(model_part_file_name[:-5])
>     sample = GenerateBetaSample()
>     simulation = MonteCarloAnalysis(model,local_parameters,sample)
>     simulation.Run()
>     QoI = EvaluateQuantityOfInterest(simulation)
> return QoI

Inside MonteCarloAnalysis, the potential flow solver is called. EvaluateQuantityOfInterest is defined as:

> 
> def EvaluateQuantityOfInterest(simulation):
>  """here we evaluate the QoI of the problem: the lift coefficient"""
>     Q = simulation._GetSolver().main_model_part.GetValue(KratosMultiphysics.FRICTION_COEFFICIENT)
> return Q

Where the lift coefficient is obtained from the model part (now using FRICTION_COEFFICIENT as placeholder).

Is this the best way to do so? Do you have any suggestions or improvements?

Thanks in advance!

**Comment by RiccardoRossi** [comment]
I think that we can cast the question more in general as:

**"what is the _official_ way of returning some data from an analysis"** ?

**Comment by philbucher** [comment]
This is actually a very good question
- One option is what you do now with setting variables on the ModelPart
- Another way would be to set them in the `ProjectParameters`. This way you could easily keep on processing them. This might be not the best way for a lot of output I guess

**Comment by pooyan-dadvand** [comment]
I would go for setting it in ModelPart and leave the ProjectParameters only for input/default not output....

**Comment by armingeiser** [comment]
In Structural Optimization we are setting our response function values on the process info of the model part. Requires a dedicated variable though. We are using `StructuralMechanicsApplication.RESPONSE_VALUE`.

I wasn't aware that setting it directly on the model_part is also possible.
