### ISSUE TITLE
Avoid zeros in cut geometries

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#3319]
The current implementation of the divide_tetrahedra cannot deal with geometries where one of the nodes has exactly DISTANCE = 0.0.
 In the (not so) deprecated enrichment_utilities_duplicate_dofs.h, distances are modified to do this.

 https://github.com/KratosMultiphysics/Kratos/blob/47d7e615586b56f5b773c0ea2975ab1d02aca840/kratos/utilities/enrichment_utilities_duplicate_dofs.h#L170

I think that the new utility should be able to deal with this as well. However, I am open to discussion whether this should be managed by the element or the solver or ...  someone else.

@jcotela @RiccardoRossi

**Comment by rubenzorrilla** [comment]
The old enrichment_utilities_duplicate_dofs.h silently hides something that should be used-definable: the tolerance for considering a small distance value equal to zero. IMO, the divide_tetrahedra must take care about dividing tetrahedra, not about correcting the distance field. To that purpose we have the distance_modification_process.h/cpp (which of course must be called before any divide).

**Comment by ddiezrod** [comment]
Ok, I did not know this process. I will take a look, but at first sight seems to be quite oriented to embedded formulation...

**Comment by rubenzorrilla** [comment]
It is not oriented to any CFD formulation. Actually, I use it in combination with the two-fluid element. It takes the distance field (either continuous or discontinuous) and corrects it in accordance to a user-definable tolerance. The unique variables involved are DISTANCE, ELEMENTAL_DISTANCE, NODAL_H, PRESSURE and VELOCITY. Hopefully, it can be the job for your application.

**Comment by ddiezrod** [comment]
Ok, thanks! Is it mandatory to use ELEMENTAL_DISTANCE and NODAL_H? We do not use them right now and I'd like to keep it that way.

**Comment by rubenzorrilla** [comment]
ELEMENTAL_DISTANCES is the variable that the discontinuous distance calculation tool uses internally. Are you using an elemental distance or a nodal one? I guess that you use the continuous one, so the distance is saved in DISTANCE variable (which is the one used in this process).

Concerning the NODAL_H, in here we are using the elemental nodal size to set the distance tolerance. However, I have no objections to use (implement) an alternative threshold criterion. It might be interesting to have both of them.

**Comment by ddiezrod** [comment]
Ok, maybe we will think in a different criterion in the future but I guess this is ok for the moment. Thanks @rubenzorrilla !
