### ISSUE TITLE
[Discussion] Parallelism exception treatment

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3323]
In the meeting organized yesterday we spoke about the issues related with the Exception treatment in a general to not just stop the calculation, but design strategies to adapt the calculations.

One of the main issues is related with the fact that OMP doesn't allow the treatment of exceptions. That's why in the discussion the  multi-thread implementations in the STL library was mentioned. This one doesn't have that problem. Besides MS is giving more support to this than to the OMP library.
https://en.cppreference.com/w/cpp/thread

The problem is that changing this in all Kratos code implies a lot of work, but I was thinking that maybe the solution is not changing it everywhere but in the places which this exceptions happen the most. Particularly in the solving strategies (schemes, B&S, NR...).

With this maybe we have a minimum base to tackle the exception treatment on parallel.

@KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
I discovered this blog: https://www.bfilipek.com/2018/11/parallel-alg-perf.html

Where the comparison of OMP with STL parallel is done (C++17 which have better performance apparently). Even so, best case scenario and with the proper implementation the performance is slightly better than OMP and in general is slightly worse:
![imagen](https://user-images.githubusercontent.com/19991680/48338616-67f59300-e666-11e8-9121-addecc898f6e.png)

Some examples here:

https://www.bfilipek.com/2018/06/parstl-tests.html

**Comment by pooyan-dadvand** [comment]
The behavior is very CPU dependent....

It seems that openmp don't like the i7 4720...

**Comment by loumalouomega** [comment]
Looks like in the case of STL thread is less dependent

**Comment by loumalouomega** [comment]
https://www.bfilipek.com/2018/11/pstl.html Good article, for the far future

**Comment by philbucher** [comment]
shall we close this and discuss again when it becomes more relevant?

**Comment by roigcarlo** [comment]
I think so @philbucher

**Comment by RiccardoRossi** [comment]
ok, let's close this ...
