### ISSUE TITLE
Is CheckRegisteredApplication still needed?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3328]
I was in contact with @jcotela and @rubenzorrilla and we were wondering, if the `CheckRegisteredApplications` in the python-scripts is still needed?
To my knowledge this was only necessary before the variables were hash-based, but are there any other reasons?

E.g. for conditionally constructing an (ALE)-Fluid solver, is it ok to import the MeshMovingApp on-the-fly?
=> WITHOUT having to import the MeshMovingApp in the Main-script

In the same context also, is [CheckForPreviousImport](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_interface/__init__.py#L21) still needed?

related with #1246

**Comment by philbucher** [comment]
ping

**Comment by pooyan-dadvand** [comment]
As I remember this was to ensure the correct assignment of variables keys and no longer needed. @RiccardoRossi  do you remember any other issue?

**Comment by jcotela** [comment]
For future reference: no, looks like it is no longer needed (the linked PR tests this).
