### ISSUE TITLE
Initialization of Strategies in Restart

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3348]
I noticed that the way restart is handled is inconsistent, the behavior of `Initialize` in particular:
**In case of a Restart, does the initialization of the SolvingStrategy and its members (scheme, elements, conditions etc) have to be done again?**
I guess not, but currently this is done in most cases (e.g. in FluidDynamics). 
There is a [hack in StructuralMechanics](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L221-L229) to tackle this problem but I don't think this is how it should be done.

If we don't want to reinitialize after a restart, then we could e.g. check [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L419) if the ModelPart comes from a restart

any opinions @pooyan-dadvand @RiccardoRossi ?

BTW the restarts also currently seems to be working (...correctly?), so I guess there is another check somewhere, but in any case I think this should be improved for clarity

**Comment by pooyan-dadvand** [comment]
The cleanest way would be to save and load the solver and strategy but I'm not sure what would be the side effect...
@RiccardoRossi?

**Comment by RiccardoRossi** [comment]
i personally would recreate the solver and the processes

**Comment by philbucher** [comment]
I also think it is better to recreate it

The main question is: what is the intended behavior?
Should `Initialize` of Elements/Conditions be called in a restart or not?

**Comment by pooyan-dadvand** [comment]
We are always recreating them which gives a lot of headache and implementations.... My suggestion also targets the Project and its serialization... 

If we are using the save and load as a data file facility I would also call initialize.

**Comment by jcotela** [comment]
Just for the record, the few FluidDynamics elements that store internal data accept that Initialize may be called after a restart. The way this is done is that the Initialize method can recognize if the element is newly constructed or if load has been called (essentially going by the allocated size of the internal storage). We discussed this possibility with @philbucher and this seems not to be practical for structural elements in general.

**Comment by philbucher** [comment]
@pooyan-dadvand so you suggest to add serialization also to Strategies, schemes, B&S ...?
This seems also rather tedious, I am not sure if this is necessary / a good way to go

@jcotela how did you solve if `Clear` in the Strategy was called? I think in this case the Elems/Conds have to be reinitialized
At least that is how it is implemented in the NR-Strategy

**Comment by jcotela** [comment]
@philbucher that's a good point... I think we are not freeing elemental data on Clear. Shouldn't Cleared elements be reinitialized anyways?

**Comment by pooyan-dadvand** [comment]
I see your point @philbucher, my proposal was a long term one....let's process with initialization.

**Comment by philbucher** [comment]
closing this as I now think it would be wrong to not reinitialize
in any case now `Initialize` gets a `ProcessInfo`, there one can check if it is a restart
