### ISSUE TITLE
Compile errors in pybind within pytypes.h with gcc 7.3.0

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#3355]
Hi together,

I am currently trying to compile the Kratos with its current master branch on a cluster and I am getting several compile errors (see attached file: 
[compile_error.txt](https://github.com/KratosMultiphysics/Kratos/files/2577785/compile_error.txt)). On my own machine and on another cluster it is working perfectly with the same settings. 

Probably someone has seen this problem before.

**Comment by RiccardoRossi** [comment]
maybe a stupid comment but ... can u check if the -std=c++11 option is set?

**Comment by philbucher** [comment]
I compiled this today with GCC 7.3, but I will check again

**Comment by philbucher** [comment]
The compiler error seems to come from pybind itself
A quick google search didn’t give anything 

Btw Riccardo I think the c++11 flag is set by cmake also

**Comment by philbucher** [comment]
@AndreasWinterstein I think you are not linking correctly against python
from your output:
~~~
-- Found PythonInterp: /usr/bin/python (found version "2.6.9") 
-- Found PythonLibs: /home/hpc/pn56ba/ga49gux3/software/python3/Python-3.6.1/libpython3.6m.so
~~~

seems like python2 and python3 are mixed up

**Comment by jcotela** [comment]
Note that the new findPython module we use for pybind uses different cmake variables... The only way I found to specify a non-default python is to set ` -DPYTHON_EXECUTABLE=...`

**Comment by AndreasWinterstein** [comment]
**Solved.** Those two Cmake variables have to be added to the config file with their **full path** (@philbucher using $HOME or ~/ was why it was partially linking to python2).

```
-DPYTHON_LIBRARY="something/software/python3/Python-3.6.1/libpython3.6m.so"                 \
-DPYTHON_INCLUDE_DIR="something/software/python3/Python-3.6.1/include/python3.6m"           \
```
 
@RiccardoRossi: Not a stupid question, but  -std=c++11 was set :-)

@jcotela: This only works perfectly on my own workstation, but not with version of python3 I compiled on the cluster myself.


Thanks to all for their help.
