### ISSUE TITLE
Addition of a PERIODIC Kratos flag.

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#336]
We want to expand and modernize the periodic conditions/periodic builder and solver, and we would like to update it to use Kratos Flags instead of signaling with nodal variables. The only "problem" is that we would need to define a flag value to do so, and we feel this should be discussed with the community.

@KratosMultiphysics/technical-committee can we go ahead and add a new PERIODIC flag to the list of Kratos flags?

**Comment by adityaghantasala** [comment]
Hi @jcotela  Just for my understanding : Regarding periodic builder and solver, once we have the multi-point constraints builder(its still under approval stage) and solver one can use this more general builder and solver also for periodic boundary conditions .. am I correct ?

**Comment by jcotela** [comment]
Hi @adityaghantasala Yes, the longer-term plan is to reimplement periodic boundary conditions as multi-point constraints, since it is much more flexible than what we can do with the existing point-to-point periodic conditions.
This is for something that we want to try with @ipouplana where the existing approach should be sufficient, but we need a way to distinguish between two-noded periodic links (which are stored internally as line conditions) and real line conditions already existing in the model (line loads on a structural problem, basically).

**Comment by pooyan-dadvand** [comment]
I agree. 👍 

@KratosMultiphysics/technical-committee ?

**Comment by maceligueta** [comment]
With the @KratosMultiphysics/dem team, we use 'periodic' as a characteristic of a domain (model part, bins, etc...) but I think we don't use this characteristic for the walls/conditions. Having said this, if a generic desing needs it I am not against using one of the bits for PERIODIC.

**Comment by pooyan-dadvand** [comment]
@maceligueta I see your point. It is a good practice to work with model part when the group with an attribute is not very dynamic and using the flags for fast activate deactivate inside of some algorithm or when you should check an attribute of the node inside the element where you don't have access to ModelPart

**Comment by GuillermoCasas** [comment]
@jcotela I agree with Pooyan here: is it not possible to employ some global variable for this? We are currently working on the periodicity of DEM too, so we might want to stick to a similar convention.

**Comment by jcotela** [comment]
@GuillermoCasas The issue here is that we have the periodic link represented as a line condition. Due to the way the the algorithm works (the builder and solver does "special" things when it finds a periodic link) we need a robust way to determine if a condition represents a periodic link or is some other kind of two-noded condition. I'm open to using other alternatives, but a global setting is not enough for this.

**Comment by GuillermoCasas** [comment]
Oh, I see. Then flags sound right.

**Comment by RiccardoRossi** [comment]
Just to say that I am also in favor of spending a bit for the PERIODIC flag

**Comment by ipouplana** [comment]
Probably tonight or tomorrow I will open a Pull Request for the addition of the PERIODIC flag along with a new process in the PoromechanicsApplication already using it...

**Comment by jcotela** [comment]
I'm closing this since it is done. The PERIODIC flag was added in #373.
