### ISSUE TITLE
Enable --using-mpi flag in the test runner

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#3362]
Related with #3340. 

Just for me to remember to implement it

**Comment by philbucher** [comment]
actually I think it will be called `using-mpi` => https://github.com/KratosMultiphysics/Kratos/pull/3340/commits/0f176ac9468f7ac01f285cc895c962e50bd79582
right @jcotela ?

**Comment by roigcarlo** [comment]
@philbucher ouch thx, I think I compiled valgrind too many times... :P. Already corrected!
