### ISSUE TITLE
MPI mesh moving tests are failing

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#3363]
Currently the mpi mesh moving tests are failing with the following error (full debug output):

```
MeshMovingAnalysis: Using the old way to create the processes, this will be removed! 
MeshMovingAnalysis: Using the old way to create the processes, this will be removed! 
Info: attempting to delete inexisting modelpart : StructuralMeshMovingPart
Info: attempting to delete inexisting modelpart : StructuralMeshMovingPart
::[MeshSolverBase]:: Finished initialization.
E[andreas-ThinkPad-T430s:05749] *** An error occurred in MPI_Allreduce
[andreas-ThinkPad-T430s:05749] *** reported by process [2233073665,1]
[andreas-ThinkPad-T430s:05749] *** on communicator MPI_COMM_WORLD
[andreas-ThinkPad-T430s:05749] *** MPI_ERR_TRUNCATE: message truncated
[andreas-ThinkPad-T430s:05749] *** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
```

@philbucher: Does this result from the changes you made in the trilinos strategies? Should I try to fix it or are you planning to do more changes there?

**Comment by philbucher** [comment]
@AndreasWinterstein I know, I think they are not working for a while already
I will fix them soon, since I anyway will remove more duplicated code.

This can be another reason why it is failing, but those things will be removed entirely!
`Info: attempting to delete inexisting modelpart : StructuralMeshMovingPart`

**Comment by AndreasWinterstein** [comment]
No this is not the problem why they are not working. I already checked this. But for sure it should be corrected.
