### ISSUE TITLE
ALEFluidSolver Interface

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3369]
@AndreasWinterstein @mpentek @adityaghantasala @msandre @rubenzorrilla 

I am currently thinking abt the final interface for the [ALE-Fluid-Solver](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshMovingApplication/python_scripts/ale_fluid_solver.py) in the MeshMovingApp

Current Interface:
~~~json5
"solver_settings" : {
    ... // these are the regular fluid-settings as they come out of GiD
    "ale_settings" : {
        ... // these are the settings for the mesh-motion-solver AND for ALE
    }
}
~~~

maintaining the mixing of MeshMotion and ALE-settings (e.g. computation of Mesh-Velocity) becomes more and more manual and cumbersome, especially if more settings are added, e.g. in #3326 

Since this solver is a very recent development of mine I suggest to change the interface to the following:
~~~json5
"solver_settings" : {
    "solver_type" : "ale_fluid"
    ... // these are the remaining ALE settings
    "fluid_solver_settings" : {
        ... // these are the regular fluid-settings as they come out of GiD
    }
    "mesh_motion_solver_settings" : {
        ... // these are the settings for the mesh-motion-solver
    }
}
~~~
This way I can pass the settings of the fluid / mesh-motion-solver directly to the respective solvers without any validation / manual parameters handling
Also to me the proposed Interface is more clear and self-explaining

What do you think?

**Comment by rubenzorrilla** [comment]
It makes perfect sense to me. Go ahead!

**Comment by msandre** [comment]
Ok for me :+1:

**Comment by AndreasWinterstein** [comment]
Also OK for me.

**Comment by mpentek** [comment]
All good.

**Comment by adityaghantasala** [comment]
Also ok from my side.

**Comment by philbucher** [comment]
done in #3383
