### ISSUE TITLE
Redistance cannot maintain interface distances.

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#3378]
Hi all @RiccardoRossi @pooyan-dadvand @jrubiogonzalez @rubenzorrilla ,

I have checked that there is a problem in both redistances (parallel and variational). In a first step, exact distances are computed for cut elements. This is done by computing the intersection points. In the case of a tetrahedra, for example, that is cut in three points creating a triangle, nodal distances are computed as the distance from the node to the triangle, which in general is not the same as the distance to the plane, distorting the free surface.

I will try to explain it graphically.
For a 2D case, with two elements cut by the blue interface, we try to compute the exact distance to the red node,

![1](https://user-images.githubusercontent.com/25667299/48556469-53263300-e8e4-11e8-8c24-32107c007b34.JPG)

We do a loop in the elements. For element 1, the nodal distance is the red one, for element 2, the nodal distance is the orange one. In the algorithm we keep the smallest one, that is, the orange one, but we can easily see that the correct distance is actually the green one (!!).
![2](https://user-images.githubusercontent.com/25667299/48556658-dc3d6a00-e8e4-11e8-99a7-4b602084147b.JPG)

My proposal is then, to compute the distance from the node to the plane instead of the distance to the geometry. @pooyan-dadvand has told me that is could cause some problems in embedded formulations, so maybe we should have two different processes or some kind of parameter to define this behaviour.

I attach a test where the redistance is not able to maintain a flat surface.
[test_redistance.zip](https://github.com/KratosMultiphysics/Kratos/files/2585543/test_redistance.zip)

**Comment by pooyan-dadvand** [comment]
My idea is to have both methods implemented and give the selection to the user

**Comment by rubenzorrilla** [comment]
I agree. I would also implement a new one.

**Comment by ddiezrod** [comment]
I am in principle ok with that. It could be added as an extra parameter in both processes. However, my doubt is if there is any situation where the current behaviour is preferred. It seemed more like a bug to me..

**Comment by RiccardoRossi** [comment]
guys, the current method should be able to reprrsent exactly the case in which the zero distance is a line. 

coukd u check that it is not so before making any change?

**Comment by ddiezrod** [comment]
@RiccardoRossi I attached a test where you can see redistance changes distances in cut elements.

The problem is maybe where to implement this. We could add a parameter or create a new process. Besides, it should also be decided if all the internal logic of how the interface cuts element should be added in the process itself or somewhere else.

For me, the cleanest option would be to add a Flag in the same process and implement the new logic in the Geometry Utils.

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi the reason that we choose the minimum distance to triangle instead of to its plane is to avoid patological cases with corners in embedded. 
![image](https://user-images.githubusercontent.com/8911479/48830012-e7c0e300-ed73-11e8-8cc3-b18e36e9f475.png)
Note that in these cases the nodal value can not represent the geometry and we try to represent it in the best way. 
In @ddiezrod case the surface can be represented by nodal value and we can treat it differently saying that we want to have the distance to the plane while keeping all the intersections in place.

**Comment by ddiezrod** [comment]
@RiccardoRossi Were you able to take a look to the test I attached?

**Comment by RiccardoRossi** [comment]
@ddiezrod did u check if a linear distance is correctly preserved?

**Comment by ddiezrod** [comment]
@RiccardoRossi That is what I do in the test. I set an exact distance function in a cube using
`node.SetSolutionStepValue(DISTANCE, node.Z - offset)`
and then check if the distance in the nodes of the cut elements is preserved. (And it is not..)

**Comment by RiccardoRossi** [comment]
just to acknowledge that you are right ;-) (and i am wrong :-D)
