### ISSUE TITLE
DEM GID Output

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#3379]
Hi when using the latest master branch I have problems with the GID output. I create a problem in GID and then run 

> KratosDEM.py

and get 

`DEM: *******************  PRINTING RESULTS FOR GID  *************************** 
DEM:                         (150 elements) 
DEM:                         (150 nodes) 
DEM:  
`

but when I try to visualize the results in GID there is no output. No soultion steps and so on.
https://gigamove.rz.rwth-aachen.de/d/id/ePMKUx3xG2wAbD

Maybe I am just doing sth wrong or missed a pr.... I hope you can help me.

**Comment by KlausBSautter** [comment]
when I try to choose a step, GID tells me 

> Please load a MODEL first

**Comment by maceligueta** [comment]
@salvalatorre and @farrufat-cimne , are you experiencing something similar?

**Comment by farrufat-cimne** [comment]
Testing the benchmarks right now. By now I just detected some of them are failing due to a missing parameter in the json reference file :
"MeanRadius": 0.0001,

working on it

**Comment by salvalatorre** [comment]
Klaus,
I can read the GiD results with no problems at all. I see Radius and Velocity.

**Comment by joaquinirazabal** [comment]
Hi @KlausBSautter, I have just run the case you uploaded and everything is ok on my computer...

**Comment by farrufat-cimne** [comment]
Seems there was a minor issue with the benchmarks that had nothing to do with this issue.

Fixed btw ,


The complete list of benchmarks are included at the end of this message as a quick reference.

========== DEM BENCHMARKING RESULTS ==========

=========== DEM DISCONTINUUM TESTS ===========

==== TSUJI PAPER BENCHMARKS. SLIDING REGIME ==

DEM Benchmark 1: OK!........ Test 1 SUCCESSFUL (error: 0.4, time: 25.49s.)
DEM Benchmark 7: OK!........ Test 7 SUCCESSFUL (error: 0.0, time: 10.61s.)
DEM Benchmark 2: OK!........ Test 2 SUCCESSFUL (error: 0.13, time: 75.78s.)
DEM Benchmark 4: OK!........ Test 4 SUCCESSFUL (error: 4.63, time: 93.08s.)
DEM Benchmark 6: OK!........ Test 6 SUCCESSFUL (error: 3.38, time: 94.54s.)

==== THORNTON PAPER TESTS. FULL REGIME. HERTZIAN LAW ====

DEM Benchmark 11: OK!........ Test 11 (e=0.25) SUCCESSFUL
DEM Benchmark 11: OK!........ Test 11 (e=0.50) SUCCESSFUL
DEM Benchmark 11: OK!........ Test 11 (e=0.75) SUCCESSFUL
DEM Benchmark 3: OK!........ Test 3 SUCCESSFUL (error: 0.75, time: 128.47s.)
DEM Benchmark 8: OK!........ Test 8 SUCCESSFUL (error: 4.16, time: 92.32s.)
DEM Benchmark 11: OK!........ Test 11 (e=0.90) SUCCESSFUL
DEM Benchmark 5: OK!........ Test 5 SUCCESSFUL (error: 1.52, time: 133.07s.)

===== THORNTON PAPER TESTS. FULL REGIME. LINEAR LAW =====

DEM Benchmark 10: OK!........ Test 10 (e=0.25) SUCCESSFUL
DEM Benchmark 9: OK!........ Test 9 SUCCESSFUL (error: 0.97, time: 65.32s.)
DEM Benchmark 10: OK!........ Test 10 (e=0.50) SUCCESSFUL


==== WENSRICH PAPER TEST. ROLLING FRICTION ====

DEM Benchmark 12: OK!........ Test 12 SUCCESSFUL
DEM Benchmark 15: OK!........ Test 15 SUCCESSFUL


== BASIC CONTINUUM TESTS ==

DEM Benchmark 20: OK!........ Test 20 SUCCESSFUL
DEM Benchmark 21: OK!........ Test 21 SUCCESSFUL
DEM Benchmark 22: OK!........ Test 22 SUCCESSFUL


======== DE/FE CONTACT BENCHMARKS ==========

DEM Benchmark 13: OK!........ Test 13 SUCCESSFUL
DEM Benchmark 14: OK!........ Test 14 SUCCESSFUL
DEM Benchmark 24: OK!........ Test 24 SUCCESSFUL


===== DISCONTINUUM CLUSTERS TESTS =====

DEM Benchmark 30: OK!........ Test 30 SUCCESSFUL
DEM Benchmark 25: OK!........ Test 25 SUCCESSFUL
DEM Benchmark 31: OK!........ Test 31 SUCCESSFUL
DEM Benchmark 23: OK!........ Test 23 SUCCESSFUL
DEM Benchmark 10: OK!........ Test 10 (e=0.75) SUCCESSFUL
DEM Benchmark 16: OK!........ Test 16 SUCCESSFUL
DEM Benchmark 10: OK!........ Test 10 (e=0.90) SUCCESSFUL
DEM Benchmark 32: OK!........ Test 32 SUCCESSFUL
DEM Benchmark 33: OK!........ Test 33 SUCCESSFUL
DEM Benchmark 17: OK!........ Test 17 SUCCESSFUL

**Comment by KlausBSautter** [comment]
@salvalatorre @joaquinirazabal that is very strange. I just asked one of my colleagues to try it and he has the same problem as I do --> no output in GID.
Here is what I do:

1. run "KratosDEM.py" (this creates post files)
2. open GID
3. open GID project
4. go to postprocessing

now I have only the models and no results, trying to choose a time step it tells me that there is no data available and that I should load a model first.

I am using the current master and thus cannot understand why this is not working anymore for me

**Comment by KlausBSautter** [comment]
also why the same happens for my colleagues here at the chair. Is there a new GID version or sth. we have to use?

**Comment by salvalatorre** [comment]
@KlausBSautter
Which GiD version are you using? I tested the latest available, 14.1.0d, and also an older one, 13.1.4d, both in Linux64.
This is the test1 simulation you are talking about, right?
![rads](https://user-images.githubusercontent.com/25589908/48609331-d77bc300-e983-11e8-932b-49839a513953.jpg)
![vels](https://user-images.githubusercontent.com/25589908/48609359-df3b6780-e983-11e8-98af-556bc803f9fd.jpg)
I'm currently working in a particular brach, but in a minute will shift to the master and run your test case myself...

**Comment by KlausBSautter** [comment]
I am using GID14
I just realized that the ones that are not working do not conatin a ***.post.lst** file . This leads to the fact that GID does not know what to load in.
For me (using the current master) no ***.post.lst** file is written anymore when running new problems.

**Comment by KlausBSautter** [comment]
When I write this file on my own everything is fine. So something prevents this file to be created for me and my colleagues. It's strange that you get it when you run the same problem on the same master branch :confused:

**Comment by farrufat-cimne** [comment]
So the problem is that the project folder do not contain the project.post.lst BUT there is a actually a post_results folder with all the binary files and the 5 *.lst files for 1,2,5,10,50.
If that the case, it means that the method that generates a lst in the main project folder (outer) is failing.

If the .lst is in the folder but GID cannot load it by default when moving to postprocess, ... that would be a different issue

**Comment by KlausBSautter** [comment]
> So the problem is that the project folder do not contain the project.post.lst BUT there is a actually a post_results folder with all the binary files and the 5 *.lst files for 1,2,5,10,50.
If that the case, it means that the method that generates a lst in the main project folder (outer) is failing.

this

**Comment by maceligueta** [comment]
We are trying to find out why we commented out that line in this hotfix:
https://github.com/KratosMultiphysics/Kratos/commit/8739cd9ac134fdc0b102f55831e9fecf5bbde2d0 
Apparently, there was a problem with that.
