### ISSUE TITLE
Skipping CI

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3399]
@KratosMultiphysics/all 

As you might know our continuous integration (CI) is usually quite full due to many PRs

In some cases a developer knows that more changes will be pushed to a certain branch (e.g. PRs that are for discussion)

In such cases it can be handy to skip triggering the CI to reduce the load on Travis and Appveyor, which means that other PRs can be checked faster
=> **obviously you won't be able to merge if this is done, after you made final changes CI still has to pass, there is no way around this**

in order to use this, the first line of your commit-message has to contain the following: `[skip ci]`

e.g. `[skip ci] new draft of sth`

I will close this issue in a couple of days, it is just for your information

**Comment by pooyan-dadvand** [comment]
This is a GitHub feature or need some implementation?

**Comment by philbucher** [comment]
it is a feature of the CI we are using, i.e. Appveyor and Travis can parse this, see the corresponding docs: 
- https://docs.travis-ci.com/user/customizing-the-build/#skipping-a-build
- https://www.appveyor.com/docs/how-to/filtering-commits/#skip-directive-in-commit-message

**=> we don't have to implement /  do anything**

**Comment by pooyan-dadvand** [comment]
Good to know! Thanks!

**Comment by adityaghantasala** [comment]
Nice .. ! Can we put this info somewhere in Wiki ?

**Comment by philbucher** [comment]
I am closing this without putting it to the Wiki for two reasons:
1. @roigcarlo is setting up a new build system, which will make this unnecessary
2. I have the impression that it does not always work, but I don't know why. I use it as the docs say but still it sometimes builds
