### ISSUE TITLE
[IGA] IgaApplication does not compile under Linux

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3403]
A lot of errors I don't know how to fix (with ANurbs Master from today):
[err.txt](https://github.com/KratosMultiphysics/Kratos/files/2592212/err.txt)

=> will be nice to have #3398 

FYI @tteschemacher

**Comment by oberbichler** [comment]
Check the error log: `AMatrix not found. Please define the AMATRIX_DIR pointing to the AMatrix root directory`

...and we need to merge some updates to the master (dev-branches are working). Anyway: there is a pending pull request.

**Comment by philbucher** [comment]
Does the IGAapp only compile with amatrix?

**Comment by oberbichler** [comment]
Sorry... my fault. The master should work without AMatrix. The errors with the `BaseDiscreteElement` you should discuss with @tteschemacher.

For the ANurbs errors: At the moment nobody is using the `IgaApplication` under Linux but ANurbs is working fine with Travis.

The updates to make Kratos work with the current ANurbs are not in the master yet. I still wait for #3297.

Maybe I should make a separate branch with the last version that works with Kratos. So it will still compile while pull-requests are in discussion...

**Comment by philbucher** [comment]
Ok thx for the answer

Could you point me to the dev-branches that are working?

**Comment by oberbichler** [comment]
iga/membrane-element e.g.

**Comment by philbucher** [comment]
Hm same problems :/

The problem with the `BaseDiscreteElement` I could solve but not the ones related to anurbs

are you using a different anurbs branch?

**Comment by philbucher** [comment]
#3297 does also not compile

It would be great if there would be a branch I could compile :D

Could you fix the errors in a branch based on #3297 ?

**Comment by oberbichler** [comment]
I can not fix it because I don't have a bug. It compiles on my two machines and also on the two machines of the master students (all of them are using windows). It also compiles on the travis (gcc 4.8.4). Maybe a gcc-6/linux specific issue.

**Comment by philbucher** [comment]
> The updates to make Kratos work with the current ANurbs are not in the master yet. I still wait for #3297.
> 
> Maybe I should make a separate branch with the last version that works with Kratos. So it will still compile while pull-requests are in discussion...

Thats what I meant. Unfortunately the errors from ANurbs are too severe for me to fix

Maybe we can take a look together when I am back

**Comment by oberbichler** [comment]
👍 
You can also try to run the ANurbs tests. Then it should be clear if it is a compiler problem. (BTW: It also compiles under macOS 10.14 using gcc-8.1 and gcc-6.5)

Probably just a little mistake...

**Comment by AndreasWinterstein** [comment]
Out of curiosity I also tried to compile with the current master branch. I am getting also a lot of errors in linux like @philbucher . I am using gcc 7.3.0 with the latest ANurbs repo.

**Comment by oberbichler** [comment]
Can someone of you check if the branch 'iga/fix-anurbs-linux' compiles under linux?

**Comment by philbucher** [comment]
I merged master into this branch and get the following error:
~~~
In file included from /home/philipp/software/ANurbs/include/ANurbs/Integration:4:0,
                 from /home/philipp/software/Kratos_MasterBranch/applications/IgaApplication/custom_utilities/anurbs.h:54,
                 from /home/philipp/software/Kratos_MasterBranch/applications/IgaApplication/custom_python/add_custom_utilities_to_python.cpp:21:
/home/philipp/software/ANurbs/include/ANurbs/src/PolygonTessellation.h:9:10: fatal error: Mapbox/Earcut.hpp: No such file or directory
 #include <Mapbox/Earcut.hpp>
          ^~~~~~~~~~~~~~~~~~~
~~~

Does not seem to be related to ANurbs

**Comment by AndreasWinterstein** [comment]
Getting the same error.

**Comment by AndreasWinterstein** [comment]
Renaming the "mapbox" folde to "Mapbox" and "earcut.hpp" to "Earcut.hpp" in ANurbs will fix this problem. But it results in another error. @oberbichler is currently trying to fix it.

**Comment by oberbichler** [comment]
I fixed the template bug (array_1d is using size_t for the dimension) and another error that happens when gcc's -pedantic is enabled. The problem with the case sensitivity is fixed inside the ANurbs-Repo (BTW: Case sensitivity is depending on the FS and not on the OS. APFS can be both but is case-insensitive by-default on macOS…).

Please update ANurbs and let me know if it is compiling now.

**Comment by philbucher** [comment]
I cannot find the branch (`iga/fix-anurbs-linux`) any more, did you delete it?

**Comment by oberbichler** [comment]
Yes. The right fix is inside this branch

**Comment by philbucher** [comment]
which branch?

=> `iga/fix-anurbs-linux` is not in the remote repo any more for some reason

**Comment by oberbichler** [comment]
sorry... not the pull request... #3297

**Comment by philbucher** [comment]
now it compiles :+1: thanks
I get the following compiler warning:
~~~
In file included from /home/philippb/software/ANurbs/external_libraries/ClipperLib/clipper.cpp:41:0:
/home/philippb/software/ANurbs/external_libraries/ClipperLib/clipper.hpp:396:25: warning: ‘virtual const char* ClipperLib::clipperException::what() const’ can be marked override [-Wsuggest-override]
     virtual const char* what() const throw() {return m_descr.c_str();}
                         ^
In file included from /home/philippb/software/ANurbs/include/ANurbs/src/TrimmedSurfaceClipping.h:12:0,
                 from /home/philippb/software/ANurbs/include/ANurbs/Integration:3,
                 from /home/philippb/software/Kratos_Master/applications/IgaApplication/custom_utilities/anurbs.h:19,
                 from /home/philippb/software/Kratos_Master/applications/IgaApplication/custom_python/add_custom_utilities_to_python.cpp:21:
/home/philippb/software/ANurbs/external_libraries/ClipperLib/clipper.hpp:396:25: warning: ‘virtual const char* ClipperLib::clipperException::what() const’ can be marked override [-Wsuggest-override]
     virtual const char* what() const throw() {return m_descr.c_str();}
~~~

=> I tried including these dirs as `SYSTEM` (see #2592 ) but id did not work yet, we can take a look next week.

**Comment by philbucher** [comment]
this is the tests-output @tteschemacher :
~~~
.s....s...DEPRECATION: ************************************************************
DEPRECATION: USING OLD DEPRECATED CONSTRUCTOR OF MODELPART
DEPRECATION: THIS WILL BE REMOVED ON NOV 1 2018
DEPRECATION: the call to ModelPart(Model ) 
DEPRECATION: should be substituted by current_model.CreateModelPart(Model) 
DEPRECATION: ************************************************************
.DEPRECATION: ************************************************************
DEPRECATION: USING OLD DEPRECATED CONSTRUCTOR OF MODELPART
DEPRECATION: THIS WILL BE REMOVED ON NOV 1 2018
DEPRECATION: the call to ModelPart(Model ) 
DEPRECATION: should be substituted by current_model.CreateModelPart(Model) 
DEPRECATION: ************************************************************
.DEPRECATION: ************************************************************
DEPRECATION: USING OLD DEPRECATED CONSTRUCTOR OF MODELPART
DEPRECATION: THIS WILL BE REMOVED ON NOV 1 2018
DEPRECATION: the call to ModelPart(Model ) 
DEPRECATION: should be substituted by current_model.CreateModelPart(Model) 
DEPRECATION: ************************************************************
.DEPRECATION: ************************************************************
DEPRECATION: USING OLD DEPRECATED CONSTRUCTOR OF MODELPART
DEPRECATION: THIS WILL BE REMOVED ON NOV 1 2018
DEPRECATION: the call to ModelPart(Model ) 
DEPRECATION: should be substituted by current_model.CreateModelPart(Model) 
DEPRECATION: ************************************************************
.DEPRECATION: ************************************************************
DEPRECATION: USING OLD DEPRECATED CONSTRUCTOR OF MODELPART
DEPRECATION: THIS WILL BE REMOVED ON NOV 1 2018
DEPRECATION: the call to ModelPart(Model ) 
DEPRECATION: should be substituted by current_model.CreateModelPart(Model) 
DEPRECATION: ************************************************************
.DEPRECATION: ************************************************************
DEPRECATION: USING OLD DEPRECATED CONSTRUCTOR OF MODELPART
DEPRECATION: THIS WILL BE REMOVED ON NOV 1 2018
DEPRECATION: the call to ModelPart(Model ) 
DEPRECATION: should be substituted by current_model.CreateModelPart(Model) 
DEPRECATION: ************************************************************
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
FDEPRECATION: ************************************************************
DEPRECATION: USING OLD DEPRECATED CONSTRUCTOR OF MODELPART
DEPRECATION: THIS WILL BE REMOVED ON NOV 1 2018
DEPRECATION: the call to ModelPart(Model ) 
DEPRECATION: should be substituted by current_model.CreateModelPart(Model) 
DEPRECATION: ************************************************************
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
F
======================================================================
FAIL: testCantileverOneQuadraticSpanWithParameterDistortion (shell_kl_discrete_element_tests.ShellKLDiscreteElementTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_Master/applications/IgaApplication/tests/shell_kl_discrete_element_tests.py", line 290, in testCantileverOneQuadraticSpanWithParameterDistortion
    self.assertAlmostEqual(surface.Node(2, 0).Z, -0.141013552223511)
AssertionError: 0.0 != -0.141013552223511 within 7 places

======================================================================
FAIL: testCantileverOneQuadraticSpanWithoutParameterDistortion (shell_kl_discrete_element_tests.ShellKLDiscreteElementTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philippb/software/Kratos_Master/applications/IgaApplication/tests/shell_kl_discrete_element_tests.py", line 226, in testCantileverOneQuadraticSpanWithoutParameterDistortion
    self.assertAlmostEqual(surface.Node(2, 0).Z, -0.141013552223511)
AssertionError: 0.0 != -0.141013552223511 within 7 places

----------------------------------------------------------------------
Ran 17 tests in 0.016s

FAILED (failures=2, skipped=2)
~~~

**Comment by oberbichler** [comment]
my fault... there was a braking change in the api... now it should work also with the tests
