### ISSUE TITLE
Change in MeshMoving App causes failure of mesh motion in optimization

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#3425]
After one of the recent changes in the MeshMovingApp, I get the following error:
```
  File "~/software/kratos/applications/MeshMovingApplication/python_scripts/mesh_solver_base.py ", line 141, in Check
    self.get_mesh_motion_solving_strategy().Check()
RuntimeError: Error: Missing Degree of Freedom for DISPLACEMENT_X in node 71.

```

I am using the structural similarity solver as an isolated analysis, see applications/ShapeOptimizationApplication/python_scripts/mesh_controller_with_solver.py

I thought the app only uses MESH_DISPLACEMENT? @philbucher Since you did these changes, do you have an idea of what changed here to cause this error?

Thanks

**Comment by philbucher** [comment]
solved in #3429 
@dbaumgaertner did you finally get to use git-blame? :D
