### ISSUE TITLE
AMGCL with MPI strange terminal output

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#3439]
When running the MPI version of the AMGCL I am getting the output "AMGCL: Unknown parameter class" several times (refer to file attached [output_amgcl.log](https://github.com/KratosMultiphysics/Kratos/files/2604055/output_amgcl.log)
) in each system solve. The results of the simulation are fine.

Did anyone else get a similar output so far? It is very likely that it is machine dependent, since the output does not seem to come directly from the code.

**Comment by philbucher** [comment]
see #2989

**Comment by AndreasWinterstein** [comment]
Thx. Did not see that one.
