### ISSUE TITLE
Python:: Modules (Applications) and Variables import enhancement

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#344]
```
> import KratosMultiphysics
> import KratosMultiphysics.SolidMechanicsApplication as KratosSolid
> import KratosMultiphysics.StructuralMechanicsApplication as KratosStructural
```

**Is it possible to create a import system to simplify the previous import sequence to** 
```
> import KratosMultiphysics.StructuralMechanicsApplication as KratosStructure
```
Taking into account that in the compilation of the application the previous application and the core is included. 

If this simplification is possible would be very useful to avoid certain problems that occur when you miss to import the mother applications or if you change the import order

i.e: Next can carry out some problems
```
> import KratosMultiphysics
> import KratosMultiphysics.StructuralMechanicsApplication as KratosStructural
> import KratosMultiphysics.SolidMechanicsApplication as KratosSolid

```
That concerns also to the variables exported to python by the different modules

ie. Kratos core defines and exports to python VAR_A,  
    SolidMechanics core defines and exports to python VAR_B,
    StructuralMechanics core defines and exports to python VAR_C,

After importing applications in python in the way exposed previously 
the variables must be called specifying the module
```
KratosMultiphysics.VAR_A
KratosSolid.VAR_B
KratosStructural.VAR_C
```
**How to avoid this without using import \* ?**

 @KratosMultiphysics/technical-committee  @jcotela @roigcarlo @loumalouomega ...

**Comment by loumalouomega** [comment]
I found this the other day https://pymotw.com/3/venv/, maybe can be an interesting alternative, at least for releases user oriented. The other and simpler alternative can be create some kind of macros to call several applications at once with a same name, but anyway let's wait for the @KratosMultiphysics/technical-committee opinion.
