### ISSUE TITLE
Wrong/strange reaction computation with elimination builder and solver

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#3442]
I see some strange reaction calculation when using Elimination builder and solver. 
Below is the case attached. (with elimination builder and solver)
Also for initial impression I am adding two screen shots : first one with block builder and solver , second one with elimination builder and solver

![block_builder_solver_reaction_plot](https://user-images.githubusercontent.com/2531316/48841461-cf5fc100-ed91-11e8-834e-8c3582b31938.jpg)

![elem_builder_solver_reaction_plot](https://user-images.githubusercontent.com/2531316/48841477-d2f34800-ed91-11e8-8f7f-6be8e9f9ab0e.jpg)

[34_test_elem_b_and_s.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2604169/34_test_elem_b_and_s.gid.zip)

**Comment by adityaghantasala** [comment]
one can switch the use of elimination builder and solver by 
`block_builder` in the ProjectParameters.

**Comment by loumalouomega** [comment]
Can you try the one in the branch #3249 ?, I fix some errors on the base elimination there (mainly related with OMP, but some related with other things)

**Comment by adityaghantasala** [comment]
@loumalouomega   I tried .. it also produces same results.

**Comment by loumalouomega** [comment]
I will check later

**Comment by loumalouomega** [comment]
Something surprising is that it is the same magnitude order, so looks like the dofs order is altered

**Comment by loumalouomega** [comment]
Fixes, I confirm that the size of the reactions were wrong and the assignment quite random

**Comment by RiccardoRossi** [comment]
@loumalouomega did u pass valgrind on the latest version? as this sort of errors suggest that you did not

**Comment by loumalouomega** [comment]
Is not a memory error, it is an implementation error, I fix it on the
mentioned PR
