### ISSUE TITLE
[Core] Are really necessary the following processes?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3452]
These processes are only one line of code, in my opinion is over-complicated:

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/node_erase_process.h
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/element_erase_process.h
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/condition_erase_process.h

We could do a greep and replace it for the equivalent line

**Comment by roigcarlo** [comment]
@loumalouomega I suspect this exists for performance reasons.

Looking at the code, I assume the process exists to prevent calling the `RemoveFoo(id)` function (and other flavors) directly from python.

Do we have any performance metric to compare the use a python loop to remove the nodes/elements/... against the use of the process?

**Comment by loumalouomega** [comment]
I don't think that this is the case, the methods are exported to python in the same way

**Comment by roigcarlo** [comment]
It is exported because you may want to delete a single node. What I meant to say is that:

```python
# Very pseudocode
nodes = GenerateNodes(1000000)
for node in nodes:
    if node.ToBeEreased():
        node.Erease()
``` 

will be much slower than

```python
# Very pseudocode
nodes = GenerateNodes(1000000)
enp = EreaseNodesPorcess(nodes)
enp.Execute()
``` 

Or your may not event want to know the implementation details of such process (read details as "i have to use a flag").

Since it's only calling one line as you say maybe the discussion would be if we can move this to the modelpart python interface instead of having a dedicate process to it. In any case I think this operation should exists in python.

**Comment by loumalouomega** [comment]
The method is completely valid, we just need to export it to python. Then replace the call of the processes. Obviously this will take some time and better wait for the release. But compiling three classes for one line of code is a little upsetting

**Comment by GuillermoCasas** [comment]
In my opinion, it does not matter that the process performs a very simple task. Otherwise we end up with some tasks being processes and some others not being so for reasons that will end up looking arbitrary. Perhaps the process can be generalized at some point (i.e., EraseEntities()).

**Comment by RiccardoRossi** [comment]
on my side, i don't see any downside on calling directly the Method Remove* from python.

Still it might be useful to have the processes. For example think of a multistage analysis. You could want to remove some nodes in the second step, which you can do from the interface by calling the processes

**Comment by loumalouomega** [comment]
Ok

**Comment by pablobecker** [comment]
I agree with Riccardo and Guillermo. Processes are useful when staging

**Comment by GuillermoCasas** [comment]
The @KratosMultiphysics/implementation-committee has decided that the best would be to create a template-process (e.g., RemoveEntities) that unifies all the remove processes here. However, we will keep these methods temporarily and add a 'deprecated warning' until they are finally removed. The @KratosMultiphysics/technical-committee has the final word on this, nonetheless.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agrees with the decision of the @KratosMultiphysics/implementation-committee

**Comment by loumalouomega** [comment]
Closing as it is solved
