### ISSUE TITLE
[Core] GiDOutputProcessMPI fails check in AnalysisStage

### ISSUE THREAD

**Issue by swenczowski** [KratosMultiphysics/Kratos#3477]
In the scope of commit #3002 (https://github.com/KratosMultiphysics/Kratos/commit/18146e1b5d781bf8af85fa2549e0379f2f8370af) by @philbucher, a check loop was added in AnalysisStage. Once "gid_output_process_mpi" is added as an output process, the simulation run crashes crashes with a segmentation fault error. An closer investigation allowed to exclude other reasons and to trace the error back to the "recently" added check-loop. A exemplaric *.json configuration file for a crashing case is attached.

[json.txt](https://github.com/KratosMultiphysics/Kratos/files/2612235/json.txt)

In a preceding discussion, @rubenzorrilla mentioned the introduction of an additional barrier() in the base class implementation of the method Check() as a probable solution.

**Comment by philbucher** [comment]
Can you add a call to the base-class constructor?
-> see #3000

**Comment by philbucher** [comment]
That will 99% fix it

**Comment by swenczowski** [comment]
Dear Philipp,
indeed, it seems to solve the problem. 
Thank you very much for your immediate answer.
