### ISSUE TITLE
Warning compiling PasTiX

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#348]
I have the following warning compiling PasTiX:

`f951: Warning: Nonexistent include directory ‘/home/vicente/bin/Kratos/external_libraries/omptl’ [-Wmissing-include-dirs]`

Effectively, there is no folder `omptl` in the `external_libraries` folder. I assume is the OpenMP Tools: http://www.openmp.org/wp-content/uploads/ompt-tr.pdf

**Comment by RiccardoRossi** [comment]
Hi Vicente,

please take out that include line. It should be completely harmless

cheers
Riccardo
<http://www.cimne.com/>

**Comment by loumalouomega** [comment]
Do I create a pull request with the modification?

**Comment by RiccardoRossi** [comment]
Yes...
