### ISSUE TITLE
[Core] Remove flag requirement from MPC

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3482]
This is a reminder for the elimination of the requirement of flag for using MPC with block builder and solver B&S. 

Besides, when the behaviour was changed last time?, right now if a node has a MASTER flag can not have assigned a slave DoF.

**Comment by RiccardoRossi** [comment]
Well ... this is a little worrysome...

we should converge to a solution and consider it frozen, meaning that we will need to be extremelty conservative with further changes.

Having said this, why at all do we need the MASTER and SLAVE flags?
The master-slave relation is already stored in the MPCs, and it is defined dof-by-dof, so it cannot be a nodal value

**Comment by loumalouomega** [comment]
@RiccardoRossi explained better than me

**Comment by adityaghantasala** [comment]
@loumalouomega  @RiccardoRossi  .. I was also trying experimenting on removing the SLAVE flag (MASTER flag as I know is not used). For the BlockBuilderAndSolver I do use it to skip the processing if no node of an element is marked SLAVE. I have a version which do not need this. But I believe (haven't tested) it will be a bit expensive than the current implementation.  I will try to make the comparison plots  with this b&s till the end of the week and post them on the corresponding PR. We can discuss this further there. 

@RiccardoRossi  When you said we should converge on a `solution`  ... A solution for what ?

**Comment by loumalouomega** [comment]
I think that @RiccardoRossi means that the treatment of the constraints should be the same independent of the B&S

**Comment by adityaghantasala** [comment]
@loumalouomega  you mean that either having a global T or doing it element by element ?

**Comment by loumalouomega** [comment]
Yes

**Comment by adityaghantasala** [comment]
ok !

**Comment by philbucher** [comment]
should this go into the release?

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by loumalouomega** [comment]
With the last changes this is not required anymore
