### ISSUE TITLE
Create and return KDTree in a local function

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#351]
Hello all together,

I am looking for a way to outsource the construction of a KDTree in a local function. But since I cannot declare an object of the KDtree without already passing the list of nodes, I don't see a proper way to do this. Can you maybe suggest me something here? Here is what I am thinking of (which obviously is still wrong):

`typedef Tree< KDTreePartition<BucketType> > KDTree; `
`KDTree aConstantlyChangingSearchTree = createANewKDTreeForAllNodesInTheMDPA()`

`KDTree createANewKDTreeForAllNodesInTheMDPA()`
`{`
`      someListOfNodes;`
`      someBucketSize;`
`      return KDTree(someListOfNodes.begin(), someListOfNodes.end(), someBucketSize);`
`}`

Thanks a lot already!

**Comment by pooyan-dadvand** [comment]
Unfortunately the KdTree is designed in this way and needs all points to be passed in construction. So one solution would be to pass the ModelPart to this function. Another solution would be using the BinaryOctree  which designed to be more dynamic.

**Comment by dbaumgaertner** [comment]
A way, that works and is fine for me was using a boost::shared_ptr:

`KDTree::Pointer mpASearchTreeClassMember`

`mpASearchTreeClassMember = createSearchTree()`

`KDTree::Pointer createSearchTree()`
 `{`
`return boost::shared_ptr<KDTree>(new KDTree(mListOfNodes.begin(), mListOfNodes.end(), mBucketSize));`
  `}` 

Is there any reasons not to do it like that?

**Comment by pooyan-dadvand** [comment]
Ah, I thought that you don't have the list of nodes on construction time. 

There is no problem with what you did. (The smart pointer overhead should be very small at level you are working)  

If the owner is only one object you can also use the `std::unique_ptr` which prevents you from copying it to another object.
