### ISSUE TITLE
Json parameters coding Style

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#353]
Regarding to @RiccardoRossi the json parameters should use [Google coding style](https://google.github.io/styleguide/jsoncstyleguide.xml) Nevertheless there are many inconsistency. Especially capital and non_capital properties. I think we should react and put some consistency on it.

**Comment by philbucher** [comment]
I would propose to enhance the Wiki on this page.
The Google style guide is quite large and if it is anyway not consistent then I think it would make sense to add a comprehensive guide for json to the existng one

**Comment by pooyan-dadvand** [comment]
@philbucher I completely agree with you that the google standard is too large with a lot of web app things. It would be great if you can put a resume of it in our [wiki](https://github.com/KratosMultiphysics/Kratos/wiki/Style-Guide)!

**Comment by philbucher** [comment]
@pooyan-dadvand I will do it next week, no problem

**Comment by pooyan-dadvand** [comment]
Thanks @philbucher !

**Comment by philbucher** [comment]
@pooyan-dadvand I updated the style guide. Please let me know if you want changes, then we can close this issue

**Comment by pooyan-dadvand** [comment]
Good job! Saying that I should add that I have not understood the flattened and structured data. Are you sure that the example is correct?

**Comment by philbucher** [comment]
I misunderstood what was described in the styleguide
Now it seems like we do the structured style, which is not recommended by google.

I  just delete this section then since it doesn't apply to us

**Comment by jcotela** [comment]
Hi, a minor question (which I don't think deserves a new issue): the style guide now says that JSON arrays should have plural names, but we might want to use them to define vectors. I have an example right now that has `{ "gravity" : [0.0, -9.81, 0.0] }`, which would be ilegal under the current style guide.

What is the preferred usage here?

**Comment by philbucher** [comment]
I think this is a valid exception
I can change the guide if @pooyan-dadvand agrees

**Comment by pooyan-dadvand** [comment]
👍 for @jcotela observation!

**Comment by jcotela** [comment]
I've gone ahead and changed the guide. I recommended singular names for array variables that represent physical magnitudes (vectors) and plural names for generic lists.
