### ISSUE TITLE
[MPI] Variable used before defined in Trilinos model part import utility

### ISSUE THREAD

**Issue by swenczowski** [KratosMultiphysics/Kratos#3539]
In the scope of commit #3476 , the variable `model_part_import_settings` was introduced. As I understand the code, it is used before it is given a value. For me, this leads to an error also pointing at an undefined variable. Unfortunately, my understanding of the section is too weak to offer a reliable suggestion for a solution.

@philbucher It would be very kind if you could have a look over the inserted paragraph once again, please.

**Comment by philbucher** [comment]
sorry my bad, fixing it
