### ISSUE TITLE
Remove DKRATOS_EXPORT_INTERFACE_2

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#354]
From #345, It looks that this does nothing... 

My grep:

> kratos/sources/dem_variables.cpp:#define DKRATOS_EXPORT_INTERFACE_2 1
> kratos/sources/dem_variables.cpp:#undef DKRATOS_EXPORT_INTERFACE_2
> kratos/sources/variables.cpp:#define DKRATOS_EXPORT_INTERFACE_2 1
> kratos/sources/variables.cpp:#undef DKRATOS_EXPORT_INTERFACE_2
> kratos/sources/c2c_variables.cpp:#define DKRATOS_EXPORT_INTERFACE_2 1
> kratos/sources/c2c_variables.cpp:#undef DKRATOS_EXPORT_INTERFACE_2
> kratos/sources/deprecated_variables.cpp:#define DKRATOS_EXPORT_INTERFACE_2 1
> kratos/sources/deprecated_variables.cpp:#undef DKRATOS_EXPORT_INTERFACE_2
> kratos/sources/cfd_variables.cpp:#define DKRATOS_EXPORT_INTERFACE_2 1
> kratos/sources/cfd_variables.cpp:#undef DKRATOS_EXPORT_INTERFACE_2
> kratos/sources/legacy_structural_app_vars.cpp:#undef DKRATOS_EXPORT_INTERFACE_2
> 

Can it be safely removed?

**Comment by roigcarlo** [comment]
Just created a PR to deal with this. If no one complains in a while I will merge.

**Comment by pooyan-dadvand** [comment]
👍  for removing
