### ISSUE TITLE
Appointment of three new committees

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#3547]
Dear @KratosMultiphysics/all 

The Technical Committee has decided to create 3 new committees to further involve senior developers in the Kratos organization. The objective is to increase the participation of the community while improving and accelerating the decision-making procedures.

There are many issues which affect more than one application (typically issues related to core, common modules or base applications). These committees would evaluate these issues and pull requests in their area and give their suggestions to the Technical Committee for the final approval. It would be great if all developers mention them when appropriate. 

The new committees are:

- **Design Committee**: @KratosMultiphysics/design-committee would review the proposals for new components, changes in code design or API. Their objective is to ensure the quality of the design in terms of flexibility, extensibility and coherence with the rest of Kratos. This committee is formed by 3 members:
  - Micheal Andre: @msandre 
  - Ruben Zorrilla: @rubenzorrilla 
  - Phillipp Bucher: @philbucher 
</br>

- **Implementation Committee**: @KratosMultiphysics/implementation-committee oversees the quality and performance of the new implementations, ensuring backward compatibility if possible or suggest a change of the behavior if they consider so to the Technical Committee. This committee is formed by 5 members:
  - Pablo Becker: @pablobecker 
  - Aditya Ghantasala: @adityaghantasala 
  - Vicente Mataix:  @loumalouomega 
  - Guillermo Casas: @GuillermoCasas 
  - Alejandro Cornejo: @AlejandroCornejo 
</br>

- **Interface Committee**: @KratosMultiphysics/interface-committee is responsible of evaluating the changes in Kratos input/output formats (Json files, mpda, hdf5, h3d, etc...) and suggesting the best solution balancing backward compatibility and flexibility. This committee is formed by 4 members:
  - Antonia Larese: @antonialarese 
  - Jordi Rubio: @jrubiogonzalez 
  - Daniel Baumgaertner: @dbaumgaertner 
  - Javier Garate: @jginternational

**Comment by RiccardoRossi** [comment]
just to say a word of welcome to the new teams!!

**Comment by philbucher** [comment]
the @KratosMultiphysics/design-committee created a project to coordinate issues / PRs
If an action from @KratosMultiphysics/design-committee is required then please add it under **Projects** such that we become aware:
![screenshot from 2018-12-05 09-42-52](https://user-images.githubusercontent.com/25484702/49500993-2f666500-f872-11e8-8140-a7085d9a3037.png)

**Comment by jcotela** [comment]
I am closing this since the new committees have been operative for a while now (good job everyone!). Feel free to reopen if something new pops up.
