### ISSUE TITLE
Parameters changing type

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3557]
I have the following question abt the Parameters (ping also @loumalouomega )
Is the `SetXXX` function allowed to change the type of a setting or is this a bug?
The following code runs:
~~~py
import KratosMultiphysics as KM

settings = KM.Parameters("""{
    "dummy_sub": {
        "some_param": "unknown_name"
    }
}""")

print("BEFORE:\n" + settings.PrettyPrintJsonString())

settings.SetBool(False) # is this ok to change the type ???

print("\nAFTER:\n" + settings.PrettyPrintJsonString())
~~~

This prints:
~~~
BEFORE:
{
    "dummy_sub": {
        "some_param": "unknown_name"
    }
}

AFTER:
false
~~~

On empty settings created with `AddEmptyValue` I guess this is ok but if the setting already exists then I could imagine it to be better to throw if one is trying to change the type

What do you think?

**Comment by loumalouomega** [comment]
If I understood well certain conversions are allowed, and I implemented in that way in the JSON branch

**Comment by philbucher** [comment]
ping @RiccardoRossi

**Comment by philbucher** [comment]
ping @RiccardoRossi

**Comment by RiccardoRossi** [comment]
mmm

@philbucher i do not have this fresh, however i would say that the function Set is allowed to change the type. This allows for example to put some logic and allow different input types...

**Comment by loumalouomega** [comment]
> mmm
> 
> @philbucher i do not have this fresh, however i would say that the function Set is allowed to change the type. This allows for example to put some logic and allow different input types...

@RiccardoRossi both json and current implementation throw an error in case of inconsistency (the only one allowed is mixing integers and doubles ), if I remember properly

**Comment by philbucher** [comment]
> mmm
> 
> @philbucher i do not have this fresh, however i would say that the function Set is allowed to change the type. This allows for example to put some logic and allow different input types...

there seems to be a test for this, so I guess it is intended then
sorry for the noise, closing
