### ISSUE TITLE
Apply a walllaw condition in PFEM2

### ISSUE THREAD

**Issue by rafaelbravopareja** [KratosMultiphysics/Kratos#3565]
Dear Kratos community:

I'm trying to use the custom condition of PFEM2 called autoslipinlet which has the possibility of applying a wall law. When apply this condition the the wall is not created. I think that this condition is not fully implemented. Please confirm my suspects and if there is a easy way to apply that condition. 

Thanks

**Comment by philbucher** [comment]
@KratosMultiphysics/pfem2

**Comment by philbucher** [comment]
is this still active?

**Comment by dcagritan** [comment]
Hello @philbucher, 
I assume it is. I'll take charge of it.

Hello @rafaelbravopareja,
Sorry for the late answer. I'd like to help you with your issue. Could you please explain me what sort of simulation you're trying to solve? 

Regards

**Comment by rafaelbravopareja** [comment]
Dear Deniz:

I’d like to apply a wall law like  this 

http://kratos-wiki.cimne.upc.edu/index.php/CFDm_2.5.Boundary_Conditions <http://kratos-wiki.cimne.upc.edu/index.php/CFDm_2.5.Boundary_Conditions>

Just to not make a very fine mesh in the wall. I’d like to simulate the flow in a channel and compute the shear stress induced by the flow in the wall.


Thanks

BR

**Comment by dcagritan** [comment]
Hello Rafael,

Let me check the condition and see what the problem is.  I'll contact you soon.
Regards,
Deniz

**Comment by philbucher** [comment]
Closing since inactive 
Please reopen otherwise
