### ISSUE TITLE
Nightly build for IgaApplication fails

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#3566]
As you might have recognized the nightly build for the IgaApplication failed. 

`Failed Applications : 1
IgaApplication --> KratosIgaApplication.dir
Compiling Errors    : 3
/home/ubuntu/Kratos/applications/IgaApplication/custom_python/add_custom_utilities_to_python.cpp:266:5: error: no matching function for call to ‘pybind11::class_<ANurbs::SurfaceGeometryBase<Kratos::array_1d<double, 1ul> >, std::shared_ptr<ANurbs::SurfaceGeometryBase<Kratos::array_1d<double, 1ul> > > >::def(const char [7], <unresolved overloaded function type>, pybind11::arg, pybind11::arg)’
/home/ubuntu/Kratos/applications/IgaApplication/custom_python/add_custom_utilities_to_python.cpp:266:5: error: no matching function for call to ‘pybind11::class_<ANurbs::SurfaceGeometryBase<Kratos::array_1d<double, 2ul> >, std::shared_ptr<ANurbs::SurfaceGeometryBase<Kratos::array_1d<double, 2ul> > > >::def(const char [7], <unresolved overloaded function type>, pybind11::arg, pybind11::arg)’
/home/ubuntu/Kratos/applications/IgaApplication/custom_python/add_custom_utilities_to_python.cpp:266:5: error: no matching function for call to ‘pybind11::class_<ANurbs::SurfaceGeometryBase<Kratos::array_1d<double, 3ul> >, std::shared_ptr<ANurbs::SurfaceGeometryBase<Kratos::array_1d<double, 3ul> > > >::def(const char [7], <unresolved overloaded function type>, pybind11::arg, pybind11::arg)’`

I compiled on my own machine, but there it seems to work, correctly. Maybe someone else can check this.

**Comment by philbucher** [comment]
this is strange, it was working 4 days ago in the nightly build
@oberbichler did you merge sth in the meantime?

**Comment by philbucher** [comment]
yep I can confirm, with the latest updates in ANurbs it does not compile

**Comment by oberbichler** [comment]
It is a problem with the pybind interface in kratos. It should be easy to fix.
