### ISSUE TITLE
Appveyor build merged PRs

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3568]
I think appveyor builds when PRs are merged, I am not entirely sure though
this one e.g.: https://ci.appveyor.com/project/KratosMultiphysics/kratos/builds/20729861

**Comment by roigcarlo** [comment]
Hi @philbucher Its uncommon but there are still some merges that need to be compiled. I cant tell you exactly the cause but if you notice an increment on the number of merges being compiled I can take a closer look

**Comment by philbucher** [comment]
I watched it and I think it builds ~3-5 merged PRs per day, depending on how many are merged

Closing now, but we should keep this in mind I think
