### ISSUE TITLE
Installation Guide for MPI

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#357]
In addition to the existing (serial) Kratos I propose to have an additional one of another one for compiling Kratos with MPI-support
Mainly because the versions of the auxiliary software are important and also quite time-consuming to figure out.

I would extend the existing Guide, unless there are other opinions

**Comment by msandre** [comment]
I think this would be good to have.

**Comment by pooyan-dadvand** [comment]
Thanks in advance!

**Comment by philbucher** [comment]
I finally had time do do it, see [here](https://github.com/KratosMultiphysics/Kratos/wiki/Linux-install#compiling-with-mpi). Let me know if I should change sth @pooyan-dadvand  @RiccardoRossi @roigcarlo
