### ISSUE TITLE
[Ttesting][Adjoint] Missing header here (with the license and the author)

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3572]
https://github.com/KratosMultiphysics/Kratos/blob/c5b413682acd83040b72e26ab64eab21139bfac6/kratos/tests/strategies/schemes/test_residual_based_adjoint_bossak_scheme.cpp#L1

Besides, wait until the cpp tests are moved to a common folder

**Comment by MFusseder** [comment]
@msandre is this your test?

**Comment by loumalouomega** [comment]
I haven't created this

**Comment by MFusseder** [comment]
Me either. I only added the model part as parameter of ```CalculateValue```.

**Comment by msandre** [comment]
It was me :laughing: I added the fix in #3581
