### ISSUE TITLE
[Meshing Application] Avoid printing all the informations

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/Kratos#3576]
Good evening,
I am currently using the mmg refinement process in a Multilevel Monte Carlo algorithm, and I would like to avoid the printing of all the informations about the refinement process.
How can I avoid this printing? This happens when I call the execution of ComputeHessianSolMetricProcess2D.
I referred to https://github.com/KratosMultiphysics/Examples/blob/master/mmg_remeshing_examples/validation/hessian2D/source/test_hessian.py to build my refinement process.
Thanks.
Riccardo

**Comment by loumalouomega** [comment]
The level 0 is supposed to give 0 output. Try to update the MMG, the library change the output level recently

**Comment by riccardotosi** [comment]
Apparently in the ComputeHessianSolMetricProcess it is not possible to set the echo level, am I wrong? We should add this?
(My mmg is updated to last week version.)

**Comment by loumalouomega** [comment]
The verbocity is on the heassian or in the MMG process?

**Comment by riccardotosi** [comment]
In the mmg process.
Here:
MmgProcess = MeshingApplication.MmgProcess2D(main_model_part, remesh_param)
MmgProcess.Execute()

**Comment by loumalouomega** [comment]
The MMG process has echo level as parameter

**Comment by riccardotosi** [comment]
Found, I was looking in the wrong file. Thanks!
