### ISSUE TITLE
cpp test failing in full debug and -D_GLIBCXX_DEBUG

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#3597]
i have a test failure at the line

https://github.com/KratosMultiphysics/Kratos/blame/master/kratos/tests/spatial_containers/test_bins_dynamic.cpp#L254

error message is 

'''
TestDynamicBinsExistPoint__LINE__ : 251
__LINE__ : 254
__LINE__ : 257
                                                OK.

/usr/include/c++/7/debug/safe_iterator.h:374:
Error: attempt to advance a singular iterator 0 steps, which falls outside 
its valid range.

Objects involved in the operation:
    iterator @ 0x0x7ffe50e01b40 {
      type = __gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >*, std::__cxx1998::vector<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::allocator<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > > > > >, std::__debug::vector<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::allocator<__gnu_debug::_Safe_iterator<__gnu_cxx::__normal_iterator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >*, std::__cxx1998::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >, std::__debug::vector<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<std::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > > > > > (mutable iterator);
      state = singular;
    }
Aborted (core dumped)
'''

**Comment by RiccardoRossi** [comment]
similar error in
DynamicBinsDefaultConstructorCellSize

**Comment by philbucher** [comment]
I think this is a duplicate of #3254 
ping @roigcarlo

**Comment by RiccardoRossi** [comment]
also in 
DynamicBinsBBConstructorCellNumber

**Comment by RiccardoRossi** [comment]
oh sorry for duplication

**Comment by RiccardoRossi** [comment]
terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: Missing variable NODAL_AREA variable #1845612800


in kratos/processes/compute_nodal_gradient_process.cpp:88:ComputeNodalGradientProcess<TDim, TVarType, THist>::ComputeNodalGradientProcess(ModelPart&, TVarType&, Variable<array_1d<double, 3> >&, Variable<double>&) [with int TDim = 2; TVarType = Variable<double>; HistoricalValues THist = (HistoricalValues)0]
   kratos/processes/compute_nodal_gradient_process.cpp:90:ComputeNodalGradientProcess<TDim, TVarType, THist>::ComputeNodalGradientProcess(ModelPart&, TVarType&, Variable<array_1d<double, 3> >&, Variable<double>&) [with int TDim = 2; TVarType = Variable<double>; HistoricalValues THist = (HistoricalValues)0]

**Comment by philbucher** [comment]
> terminate called after throwing an instance of 'Kratos::Exception'
> what(): Error: Missing variable NODAL_AREA variable #1845612800
> 
> in kratos/processes/compute_nodal_gradient_process.cpp:88:ComputeNodalGradientProcess<TDim, TVarType, THist>::ComputeNodalGradientProcess(ModelPart&, TVarType&, Variable<array_1d<double, 3> >&, Variable&) [with int TDim = 2; TVarType = Variable; HistoricalValues THist = (HistoricalValues)0]
> kratos/processes/compute_nodal_gradient_process.cpp:90:ComputeNodalGradientProcess<TDim, TVarType, THist>::ComputeNodalGradientProcess(ModelPart&, TVarType&, Variable<array_1d<double, 3> >&, Variable&) [with int TDim = 2; TVarType = Variable; HistoricalValues THist = (HistoricalValues)0]

@loumalouomega

**Comment by loumalouomega** [comment]
Sorry, I will fix this, but in FullDebug tests are running fine in my machine and Travis run the tests at the moment

**Comment by RiccardoRossi** [comment]
other tests
 are still failing

**Comment by loumalouomega** [comment]
The same reason?, as I said I did a blind fix, I cannot replicate the error
in my computer (I tried it in a VM with Ubuntu 18.04 and gcc in full debug
and glibcxx debug)

**Comment by RiccardoRossi** [comment]
i did not check yet, but also @roigcarlo  had some failing tests

**Comment by roigcarlo** [comment]
I will let this compiling now and copy here the results.

**Comment by loumalouomega** [comment]
I this solved?

**Comment by philbucher** [comment]
nope, ping @roigcarlo
