### ISSUE TITLE
line output process: No node found

### ISSUE THREAD

**Issue by 94zz94** [KratosMultiphysics/Kratos#3598]
Hi everyone, I have a problem with line_output_process.py in Kratos Multi-Physics 6.0.0-a3395a3d1e.

Sometimes happen that Kratos is not able to locate some points in the domain.
The thing is that those point exists...I created them manually.
I meshed the domain with Gid, using model parameters so it should use the existing nodes for the mesh
Can be that the tetrahedral mesh can't reach those nodes?
Is it a problem of numeric tollerance? 
I tried to look at point_output_process.py and it looks like BruteForcePointLocator can't find them, because the found id is -1.

       .......
        elif entity_type == "element":
            self.sf_values = KratosMultiphysics.Vector()
            found_id = KratosMultiphysics.BruteForcePointLocator(self.model_part).FindElement(point, self.sf_values)
.......

That's the warning message from the terminal:

(for TimeBasedAsciiFileWriterUtility output file line_output_H_114_front.dat 
Point Locator: No Node found for Point: Point(-15, 10, 114) )

So the output file for that point is empty.
In the Projectparameters.json I have written this:
            },{
                "python_module"  : "line_output_processCustom",
                "kratos_module"  : "KratosMultiphysics",
                "process_name"   : "LineOutputProcess",
                "Parameters"            : {
                    "start_point"       : [-15,  -15, 114],
                    "end_point"         : [-15,  15, 114],
                    "sampling_points"   : 7,
                    "model_part_name"   : "Parts_fluid",
                    "output_file_settings": {
                        "file_name" : "line_output_H_114_front"
                    },
                    "output_variables" : ["PRESSURE"]
                }
            },{

Thanks in advance.
@rubenzorrilla

**Comment by philbucher** [comment]
are the points on the boundary of your domain?

**Comment by 94zz94** [comment]
yes indeed they are point of a 3D "parallelepiped" , like an obstacle for the flow of the wind

**Comment by philbucher** [comment]
I don't fully understand what "parallelepiped" is but just to say that the points should not be on the boundary exactly, otherwise the search can fail due to tolerances

**Comment by 94zz94** [comment]
The thing is that the 3d rettangular is a building and I have to see the pressure precisely in those point...
is there a way to overcome this issues? Maybe reducing the tollerance?

**Comment by philbucher** [comment]
in this case I would use the MultiplePointsOutputProcess and specify "node" as entity type. There you can (have to) specify the exact location of nodes

**Comment by jcotela** [comment]
It is usually enough to move your points a very small amount towards the interior of the domain (say `1e-6`), the pressure variation should be negligible in that length.

**Comment by 94zz94** [comment]
Since I have hundreds of points, I prefered to move them...thank you a lot .. It works 👍
