### ISSUE TITLE
[Core][ConstitutiveLaw] Bounded parameters

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3605]
@KratosMultiphysics/technical-committee @KratosMultiphysics/design-committee @KratosMultiphysics/structural-mechanics @KratosMultiphysics/solid-mechanics 

Speaking with @frastellini we realized that there is not an option for bounded arrays/matrices in the Parameters of the constitutive_law.h class. We thought that is possible to add an option (something like BoundedParameters) equal in everything to the current Parameters but using bounded arrays and matrices. Something like:

~~~cpp
    template<std::size_t TVoigtSize>
    struct BoundedParameters
    {
        /// We define the dimension
       static constexpr SizeType Dimension = TVoigtSize == 6 ? 3 : 2;

        KRATOS_CLASS_POINTER_DEFINITION(BoundedParameters);

    private:

      Flags                mOptions;
      double               mDeterminantF;

      array1d<double, TVoigtSize>* mpStrainVector;
      array1d<double, TVoigtSize>* mpStressVector;

      const Vector*        mpShapeFunctionsValues;
      const Matrix*        mpShapeFunctionsDerivatives;

      const BoundedMatrix<double, Dimension, Dimension>*  mpDeformationGradientF;
      BoundedMatrix<double, TVoigtSize, TVoigtSize>*  mpConstitutiveMatrix;

      const ProcessInfo*   mpCurrentProcessInfo;
      const Properties*    mpMaterialProperties;
      const GeometryType* mpElementGeometry;

... Equal to Parameters
~~~

**Comment by RiccardoRossi** [comment]
If you do this you all the elements would be templated. for example you would not be able to have an element that works both in 2D and in 3D. Also your design does not contemplate the case in which you want to have a strain of size 4 (some cases of plane strain as @marandra pointed out)

as discussed with @pooyan-dadvand , one option for having the same behaviour, once we are fully ported to AMatrix, is to allocate everything in stack with a size sufficient for 3D, but see a view of it which behaves with the sizes corresponding to 2D if you want that behaviour.

**Comment by loumalouomega** [comment]
@RiccardoRossi the proposed design still allows you to use the not bounded Parameters, so this doesn't breaks anything. Besides, you don't need necessarily to template the element. You can put a simple if in the element, I assume that an if condition is cheaper than a dynamic vector/matrix.

For the size 4, you can just give TVoigtSize = 4, in any case this is just a proposal.

**Comment by RiccardoRossi** [comment]
@loumalouomega your computation of the dimension would fail. Also, if you do not specify the template size the voigtsize is 6, so you are assuming 3D

**Comment by loumalouomega** [comment]
This is just an example, developer should know what they are doing (in reference to the 3D, which is a clear default option). 

And the computation of the domain size would not fail. The problem will be to adapt the current methods on the CL. This is just a discussion of a potential proposal, nothing else

**Comment by RiccardoRossi** [comment]
the problem is that you cannot default to 3D. Think of the TotalLagrangianElement. That works both for 2d and 3D. how would you accomplish that?

**Comment by ipouplana** [comment]
If this proposal still allows people using the previous struct Parameters, I don't see it as something bad to have more options in the way we can use the CLs...

**Comment by loumalouomega** [comment]
> the problem is that you cannot default to 3D. Think of the TotalLagrangianElement. That works both for 2d and 3D. how would you accomplish that?

It is just a proposal, the default can be easily removed

**Comment by jcotela** [comment]
@loumalouomega how would you pass this new object to the CL? Would this imply duplicating the CL interface so that functions accept either `Parameters` or `BoundedParameters<...>`?

**Comment by loumalouomega** [comment]
> @loumalouomega how would you pass this new object to the CL? Would this imply duplicating the CL interface so that functions accept either `Parameters` or `BoundedParameters<...>`?

That's my concern, an alternative would be to create a base Parameters class, so with polymorphism magic be able to use indistinctly the Bounded or Unbounded

**Comment by jcotela** [comment]
> That's my concern, an alternative would be to create a base Parameters class, so with polymorphism magic be able to use indistinctly the Bounded or Unbounded

Yes, that is the big problem. Simple polymorphism does not work here because you are changing the types of the member objects (`mpDeformationGradientF` for example) between the two implementations. I believe that you would have to template the CL itself depending on the `Parameters` type, and eventually the element itself, as @RiccardoRossi was pointing to.

**Comment by RiccardoRossi** [comment]
I really think that using a stack allocator for the DenseMatrix and DenseVector would be a nice solution for the problem in the long run

[edit:] example of stack allocator https://howardhinnant.github.io/stack_alloc.html

**Comment by loumalouomega** [comment]
> > That's my concern, an alternative would be to create a base Parameters class, so with polymorphism magic be able to use indistinctly the Bounded or Unbounded
> 
> Yes, that is the big problem. Simple polymorphism does not work here because you are changing the types of the member objects (`mpDeformationGradientF` for example) between the two implementations. I believe that you would have to template the CL itself depending on the `Parameters` type, and eventually the element itself, as @RiccardoRossi was pointing to.

Yes, I was afraid of that

**Comment by loumalouomega** [comment]
> I really think that using a stack allocator for the DenseMatrix and DenseVector would be a nice solution for the problem in the long run
> 
> [edit:] example of stack allocator https://howardhinnant.github.io/stack_alloc.html

I see

**Comment by pooyan-dadvand** [comment]
Also there is another issue related to AMatrix. At this moment AMatrix does not support resizing an stack array and this would make the migration more difficult.

**Comment by loumalouomega** [comment]
OK, I think I will close this if everyone agrees and we can reopen in a future if necessary

**Comment by frastellini** [comment]
ok. We can close the issue due to current technical limitations. Thanks anyway for considering the matter...
