### ISSUE TITLE
Staged calculations

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/Kratos#3609]
When I attended Kratos worshop (June 2018), @RiccardoRossi presented an early implementation of a python script to perform "staged calculations" in which several different analyses after each other on a same model can be done. I am wondering if that implementation is finalised and where I can find it.

Thanks,

Vahid

**Comment by RiccardoRossi** [comment]
Dear Vahid,
the AnalysisStage is quite mature now, however i don't think it has been used for multistage analysis yet.

can u describe one simple use case, so that we may propose how to do it?

**Comment by Vahid-Galavi** [comment]
Hi Riccardo,

A use case might be the simulation of a shallow foundation in 2-phase condition as follows:

1. In the first stage, we can apply body force (gravity loading) to initialize effective stresses in the soil. This should be done in drained condition to prevent generation of pore water pressure. Therefore a separate analysis is needed.
2. In the second stage, we will apply a load on the ground surface in 2-phase condition. At this stage we allow for generation of pore water pressure.

This is a simple example, but I just want to learn how to do it. Then I can extend this to other multistage analyses.

Thanks in advance.

**Comment by Vahid-Galavi** [comment]
@RiccardoRossi do we have an implementation of this?

https://github.com/KratosMultiphysics/Kratos/wiki/Common-Python-Interface-of-Applications-for-Users#outlook-kratos-project-multi-stage-simulation

**Comment by ddiezrod** [comment]
@RiccardoRossi Is there anything done about this? I think @KratosMultiphysics/altair team should have an important role here

**Comment by philbucher** [comment]
I think none has tried this yet, but I think it is not that complicated to try
the outline I did here https://github.com/KratosMultiphysics/Kratos/wiki/Common-Python-Interface-of-Applications-for-Users#outlook-kratos-project-multi-stage-simulation should work more or less.

Just create the stages one-by-one and run them one-by-one

**Comment by philbucher** [comment]
I just updated the Wiki, you can have another look
the old description was a bit outdated

@RiccardoRossi I am quite sure this is in line of your vision

**Comment by Vahid-Galavi** [comment]
@philbucher Thanks! I will try it and ask you if I have any question.

**Comment by philbucher** [comment]
can we close this @Vahid-Galavi ?

**Comment by philbucher** [comment]
closing since inactive, please reopen otherwise

**Comment by Vahid-Galavi** [comment]
I close this issue
