### ISSUE TITLE
About the NonewtonFluid in PFEM2

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3627]
Hello @msandre 
Do you work with the PFEM2_Application? For the nonewton Fluid, may I use it with the PFEMFluid_appliction, I want to do a simulation as dam break and use the fluid to simulate the water and use the nonewton Fluid to simulate the dam, finally the water will make the dam break( make it damage).
So is there any suggestion for this? Do a coupling of PFEMFluid and PFEM2 or just change the parameters in PFEMFluid?
Best regards~

**Comment by msandre** [comment]
Hi @fengzekang, I don't work with pfem. Maybe @KratosMultiphysics/pfem2 can answer your question

**Comment by pablobecker** [comment]
please contact @dcagri

**Comment by fengzekang** [comment]
Thanks for your reply @marandra .
Did you do this work with PFEM2 @dcagri ，the nonewton Fluid with PFEM2？
Best regards~

**Comment by pablobecker** [comment]
on the other hand, pfem2 with nonewtonian fluid was only done for an article, it was very experimental. As far as I'm concerned, @dcagri only has experience with newtonian fluid. Maybe it will be better to contact @AFranci since he has used several constitutive models with PFEM and also this app is more updated than pfem2.

**Comment by fengzekang** [comment]
Thank you very much @pablobecker .
Last month, I asked some questions about the PFEMFluid for @AFranci . And we talked about the simulation about dam break (water with Fluid and dam with Rigid), but if we do the dam break, this has not been implemented yet. As my tutor's suggestion, if I can do this using nonewton_fluid to simulate the dam, and then the water will damage the dam until a certain moment.
Thanks again. I will dicuss this problem with AFranci (how to change the parameters). Thanks for all of you.
Best regards.

**Comment by dcagritan** [comment]
Dear @fengzekang,
As @pablobecker mentioned, I only have experience with Newtonian Fluids. However, I'm ready to help you with anything regarding PFEM2. So as far as I understand, you would like to run the dam break case with using a Nonnewtonian Fluid? Could you please give me more details?
Thank you and have a nice day.
Regards,
Deniz

**Comment by fengzekang** [comment]
Thanks for your reply @dcagri 
Yes,I want to do a simulation of dam break case. Last month I used the PFEMFluid to do some test about the Fluid and Rigid and Solid, I can use the Fluid to simulate the water and use the Solid to milulate the dam (with rigid boundary), I think this is same as the FSI problem. But waht I want to do is to make the dam break due to the water level rising up. So I changed the parameters of interaction between Fluid and Fluid (one part stands for the water and another part stands for the dam) including the Yield_shear, viscosity and something else. But I didn't get a good result, maybe I did not really understand the definition of the parameters, or the parameter settings were wrong. Or I can't use Fluid to represent the dam essentially. 
By the way, if you use the skype or other tools(emails or somthing else) usually, I can use that to comumunicate with you.
Best regards.
Feng

**Comment by dcagritan** [comment]
Dear @fengzekang,
I clearly understand your intention, however I'd be glad if you could explain me the part related with the Non-Newtonian Fluids. You want to simulate a special type of fluid?
My email is dcagri@cimne.upc.edu, please feel free to contact me.

Kind Regards,
Deniz

**Comment by fengzekang** [comment]
Dear @dcagri 
Yes, I want to simulate a special type of fluid.  In fact, as for the dam part, I have no idea how to do this (in PFEMFluid_Application there is only the fluid, solid and rigid, but the solid and rigid element can't be break, so I tried to use the different Fluid to simulate the dam, so this part is different from the water). But I just changed the viscosity and the Yield_shear, the results is not right. 
My tutor gave me another suggestion that using the Nonewton_Fluid to simulate the dam part(just like the earth dam), so the dam will be break finally. And then I tried some tests in the PFEM2_Application. In fact, I don't know if it will be right using the nonewton_fluid. If I just change parameters of the Fluid to reach the results, I think it will be well for this work.
Best regards.

**Comment by dcagritan** [comment]
Dear @fengzekang,
My recommendation is let's start with the Newtonian Fluid, and in the meantime I'll try to inform myself regarding Non-Newtonian Fluid. 
Pfem-2 is perfectly suitable for a dambreak case. Could you please provide me a sketch of your testcase, fluid properties and etc.? 
Regards,
Deniz

**Comment by fengzekang** [comment]
Hello,@dcagri
I have sent you an email about this. From an aticle, a sketch to do the erosion of earth dam using the PFEM.
Best regards.

**Comment by dcagritan** [comment]
Hello @fengzekang,
I've received your email. I assume you already have experience with Kratos and Gid, am I right? Do you already have a mesh for this case?
Regards,

**Comment by fengzekang** [comment]
Hi @dcagri 
[Dam_Break_2D.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/2667794/Dam_Break_2D.tar.gz)
I changed the parameters of dam part in the .mdpa. And the results I got of the dam part were ugly.
I think I didn't understand the real meaning of these parameters.
Begin Properties 2
    DENSITY 1500.0
    DYNAMIC_VISCOSITY 10000.0
    BULK_MODULUS 2100000000000.0
    FLOW_INDEX 1
    YIELD_SHEAR 1000000.0
    ADAPTIVE_EXPONENT 1000
    STATIC_FRICTION 100.0
    REGULARIZATION_COEFFICIENT 1000000.0
    DYNAMIC_FRICTION 400.0
    POISSON_RATIO 0.25
End Properties

Best regards.

**Comment by philbucher** [comment]
is this still active?

**Comment by dcagritan** [comment]
Hello @philbucher,

For now it is. I'll update the situation soon.
Regards

**Comment by philbucher** [comment]
closing since inactive

please reopen otherwise
