### ISSUE TITLE
Kratos For Dummies

### ISSUE THREAD

**Issue by PhilippeBussetta** [KratosMultiphysics/Kratos#363]
The tutorial 'Kratos For Dummies' have not been updated since the commit ID 36 (Propagating the pScheme through the functions to reach ConstructMatrixStructure function).
Could you change the line 128 of file ‘strategy_python.py’ in the function ‘InitializeSolutionStep’:
`self.builder_and_solver.ResizeAndInitializeVectors(`**self.scheme**`,self.pA,self.pDx,self.pb,self.model_part.Elements,self.model_part.Conditions,self.model_part.ProcessInfo);
`

**Comment by loumalouomega** [comment]
I am planning to update including how to use the AD tools. I can finish the current article.

**Comment by pooyan-dadvand** [comment]
It is true @PhilippeBussetta that this tutorial is outdated....

Thanks @loumalouomega! It would be an important contribution!

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi is the material updated?

**Comment by loumalouomega** [comment]
Nope, I have this still pending

**Comment by pooyan-dadvand** [comment]
So I would reopen it.

**Comment by RiccardoRossi** [comment]
@loumalouomega  ping!

**Comment by loumalouomega** [comment]
I know...few free time :(

**Comment by pooyan-dadvand** [comment]
Good job everybody! :+1:
