### ISSUE TITLE
Usage of LinearSolvers from apps not working

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3634]
After #615 and #3615 currently there is no instance that imports the apps in which linear solvers are defined.

After a brief discussion with @jcotela we think that they could be imported in python if needed.

**Comment by loumalouomega** [comment]
When are we planning to merge #3635 ?, I am right now modifying by hand the solvers to import the linear solvers, and I don't like this very much

**Comment by philbucher** [comment]
asap I'd say, but it needs at least some attention by the @KratosMultiphysics/technical-committee 

Btw why do you modify the solvers? (and which solvers?)

Just import the ExternalSolvers or EigenSolvers in your MainKratos and you are good
Its annoying, I agree, but this way you don't need to modify stuff in Kratos

**Comment by loumalouomega** [comment]
Ups, I was adding the import in the solver, the other option is easier, haha
