### ISSUE TITLE
Kratos SWOT matrix

### ISSUE THREAD

**Issue by frastellini** [KratosMultiphysics/Kratos#3655]
[KRATOS_SWOT-matrix-template_02.docx](https://github.com/KratosMultiphysics/Kratos/files/2639038/KRATOS_SWOT-matrix-template_02.docx)
I have already received some answers to my first query by email.
Could you please send your contribution? We can discuss the answers of the survey in next Kratos meetings. Thank you all for making a better Kratos!!!
BTW, when is the next Kratos meeting?

_Originally posted by @frastellini in https://github.com/KratosMultiphysics/Kratos/issues/3335#issuecomment-443662485_

**Comment by frastellini** [comment]
ping. More answers are welcome. Thank you very much!

**Comment by GuillermoCasas** [comment]
Yes, sorry, I have had it there pending for some time now, but never remembered to bring it up in our weekly meetings.

**Comment by frastellini** [comment]
No matter. It always happens to us... The urgent things does not leave us time for the important ...

**Comment by philbucher** [comment]
is this still active?

**Comment by frastellini** [comment]
I will send a compiled report with all received answers to the technical committee.
Thanks you all for your kind contributions!
