### ISSUE TITLE
Problems with line search in SolidMechanicsApplication

### ISSUE THREAD

**Issue by jrubiogonzalez** [KratosMultiphysics/Kratos#366]
I have realized that the line search utility inside the Solid Mechanics Application has all the max iterations and convergence settings hardcoded inside. There is no possible configuration. In addition, when running it looks like it is bouncing around the solution when it is close to the result.

**Comment by loumalouomega** [comment]
There is a line search implemented in the core, in `Kratos/kratos/solving_strategies/strategies/line_search_strategy.h`, with that one you can choose your convergence settings and max iterations in the usual way.

**Comment by RiccardoRossi** [comment]
Just to say that we "officially support" the one in the core, so let us know if you have troubles with that

**Comment by pooyan-dadvand** [comment]
And it has relaxation so it may not oscillate around the convergence point.

**Comment by loumalouomega** [comment]
@jrubiogonzalez , do you think that we can close this issue?

**Comment by loumalouomega** [comment]
@jrubiogonzalez I will close this discussion, we can reopen it if needed

**Comment by josep-m-carbonell** [comment]
Hello @jrubiogonzalez 

   Sorry for the late response. You are right,  the one used can experience that behaviour. If you look at the code you will see that there are several implementations from the algorithms written in the solid mechanics books by several authors. The selected one is the one we got better performance. However it still presents some problems. Later on, a different implementation of a line search was coded in the core. Maybe it works better, I would like to test it. Please, can you give some feedback if you test it or if you know a better algorithm? 

About the configuration, as you said, everything is hard-coded. Which parameters would you like to configure?  The json file for the solver and the strategy can be extended for this. It is open to improvements and it has the support of the Solid Mechanics team, which you are invited to join and cooperate. 

K R

**Comment by jcotela** [comment]
Closing since the original issue is solved. @josep-m-carbonell, feel free to reopen (or create a new issue) if there are new developments update on this topic.

**Comment by josep-m-carbonell** [comment]
@jcotela, we don't know if it is solved. No feedback was given. I don't know if the responses were so correct in this case. However if no clarification is requested it means that the interested person is not interested anymore. Therefore I agree with you that it is better to close the issue.
