### ISSUE TITLE
[PFEM]problems in the process of calculation about mesh?

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3667]
![screenshot from 2018-12-16 00-52-03](https://user-images.githubusercontent.com/38140045/50045416-49ebda00-00cd-11e9-84c7-260f5ac38d64.png)
![screenshot from 2018-12-16 00-57-38](https://user-images.githubusercontent.com/38140045/50045448-cda5c680-00cd-11e9-90a5-4957a6721853.png)
Hello, everyone
@dcagri @AFranci @josep-m-carbonell @ipouplana 
After I run the example, the mesh in the process is confused, I don't know why is it?What should I do to escape this problem.
Best regards

**Comment by fengzekang** [comment]
I think I have found the reason why there is the confused mesh, as follows:
![screenshot from 2018-12-16 16-03-26](https://user-images.githubusercontent.com/38140045/50051396-3f245a00-014c-11e9-987b-5b94e82f5987.png)
The pink point is the rigid boundary, if I set the inlet including these points there will be false mesh in the process. But as for this wrong process, I don't know how to deal with it. Should I change another solver?  Maybe I haven't understood the real meaning of the mesh still. Could you give me some suggestions?
Best regards.

**Comment by ipouplana** [comment]
If the rigid boundary is moving, could it be because you assigned a velocity different from zero on it?

**Comment by josep-m-carbonell** [comment]
Which application are you using, PfemApplication or PfemFluidApplication?

**Comment by fengzekang** [comment]
I will change the points of inlet, not the boundary nodes.  @ipouplana 
I used the PFEMFluidApplication. @josep-m-carbonell

**Comment by fengzekang** [comment]
![screenshot from 2018-12-17 00-13-48](https://user-images.githubusercontent.com/38140045/50056043-c1833d00-0191-11e9-801b-1f745112d9bb.png)
![1](https://user-images.githubusercontent.com/38140045/50056045-c47e2d80-0191-11e9-9871-ac51b184c42c.png)
As the above images shown, there is obvious differencr of the nodes. I have pointed that the second one there are two nodes which will be stoped at there causing the confused mesh.
These two pictures were from a same condition(all input files are the same), but I use two different computer(maybe the Kratos version are different, the first one is old and the second is a new one I download the kratos these days). I just set four nodes as the inlet nodes at the rigid boundary (I set the rigid boundary as the velocity_part 0.0,0.0,0.0 and I set the inlet nodes as 1.0,0.0,0.0). We can see that, the first picture didn't have confused mesh(means that there is no rigid boundary nodes move away), on the other hand, the second picture showed the bad results with the confused mesh (means that there are two nodes move away from the rigid boundary and then stopped at a constant point casuing the wrong mesh).
Did we do any improvement of mesh in the PFEMFluid_Application? Or maybe this result comes from my computer itself? I am a little confused.
Best regards.

**Comment by fengzekang** [comment]
Dear friends, What do you think of this? @josep-m-carbonell  @AFranci  @ipouplana

**Comment by AFranci** [comment]
Dear @fengzekang ,  you are right. A recent change that we made, introduced some troubles in the post-process. The computational results are the same (see the nodes positions in your snapshots), it is just a problem of mesh printing in examples involving inlet boundaries. @maceligueta and I, we are trying to fix it as soon as possible...

**Comment by fengzekang** [comment]
Dear @AFranci 
All right. If there is no differences of computational results, I will use the new version to do tests. 
BTW, if there is any work I can do, I am pleasure to do it and make it better.
Thanks again. Best regards
Feng

**Comment by fengzekang** [comment]
Dear @AFranci 
All right. If there is no differences of computational results, I will use the new version to do tests. 
BTW, if there is any work I can do, I am pleasure to do it and make it better.
Thanks again. Best regards
Feng

**Comment by maceligueta** [comment]
@fengzekang , can you pull the master and try if the issue is solved? If so, we can close this issue.

**Comment by AFranci** [comment]
Now it is not necessary to define the inlet boundary as a RIGID body anymore. 
So, define as RIGID only the boundaries with VELOCITY boundary conditions and not those with INLET boundary conditions.
It should work and the mesh quality in the post-process should be preserved.
