### ISSUE TITLE
How to create a exe of an application

### ISSUE THREAD

**Issue by shibashisG** [KratosMultiphysics/Kratos#3668]
Hello,
It would be great if someone can guide me how to create a .exe out of a complied Kratos application

**Comment by RiccardoRossi** [comment]
hello, the easiest option is to use "nuitka" yo transform the python script
in a exe.

http://nuitka.net

it also helps on packaging the solution

**Comment by loumalouomega** [comment]
More in detail

https://stackoverflow.com/questions/49831163/compile-python-3-6-script-to-standalone-exe-with-nuitka-on-windows-10

**Comment by shibashisG** [comment]
Thank you friends, let me try it out. Shall update after that.

**Comment by philbucher** [comment]
is this solved?

**Comment by philbucher** [comment]
closing since inactive

please reopen otherwise
