### ISSUE TITLE
[Core] Process factory Python module import

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#3673]
At the moment, we always do an import of the process Python module to construct the processes inside the process factory (see below)
https://github.com/KratosMultiphysics/Kratos/blob/44dd1dd28a6990ba4b780de1cbaed04d70988700/kratos/python_scripts/process_factory.py#L17
This requires to always have a Python file to construct the process. Even though the Python processes implementation makes sense in several cases, there are other applications in where we end up with these "apply_whatever_c++_process" files to allow the construction of the c++ implemented processes.

On top of that, the GiD interface requires an underlying process to allow the user to assign conditions. Sometimes we want the user to assign entities that will have no BC or initial conditions imposition (e.g. any coupled problem interface) so when we write the ProjectParameters.json we need to set a "do nothing" process. As a temporary solution, I'm using the Python base process, which is expected to be removed since all the processes must derive from the c++ base process.

One solution that comes to my mind is to use the base c++ process as "fake" process. This will allow to finally remove the Python base process, but then we will need to modify the factory to avoid the Python import. This will also allow to some of these "apply_whatever_c++_process" processes.

Summarizing, is it possible to modify the process factory to include such capabilities?

**Comment by loumalouomega** [comment]
@rubenzorrilla I think if we implement a common constructor with Model and Parameters it can be done, specially if we implement a factory, so then will be able to use a C++ process without the need to create the corresponding python process

**Comment by philbucher** [comment]
The @KratosMultiphysics/design-committee has reached a consensus:

- So we agreed that the interface should be the same as in python
- The C-Processes (at least the ones that one would call from the process-factory) should be registered in KratosComponents

**Comment by philbucher** [comment]
@rubenzorrilla did you start with this?

**Comment by RiccardoRossi** [comment]
@maceligueta FYI this is the first step towards allowing registering of processes

**Comment by loumalouomega** [comment]
> 
> 
> @maceligueta FYI this is the first step towards allowing registering of processes

Do you mean this https://github.com/KratosMultiphysics/Kratos/pull/6016 ?

**Comment by rubenzorrilla** [comment]
Now that we have the ability to properly register any stuff (see #10420), including processes, this is no longer a problem.
