### ISSUE TITLE
Concerning the compiler option -ffast-math

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#369]
This issue tries to open a discussion about the benefits and problems of the option -ffast-math.
Problem 1- I recently noted that I can't compile the External Solvers Application with gcc 5.3.1. I tried without the option -ffast-math and no problem, it compiles smoothly!
Problem 2- While debugging my application, I wanted to stop the code as soon as a NaN appeared, so I decided to use 'if(std::isnan(variable)) DoSomething();' just to put a breakpoint there. However, 'isnan' does not work with -ffast-math. When I removed it, I could use 'isnan' with no problems.

I have not tested what is the increase in performance when this option is used, but it's clear that it has some drawbacks. For solving Problem 2, we might use -ffast-math for the release version, but I don't really know how to solve Problem 1. Any ideas? Has anyone tested the performance increase?
Any help from @KratosMultiphysics/technical-committee or anyone else is welcome.

**Comment by maceligueta** [comment]
I forgot to paste the error I am getting when I compile the External Solvers Application. It is actually a linker error:
`/usr/bin/ld: ~/glibc_install/lib/libmvec_nonshared.a(svml_finite_alias.oS): relocation R_X86_64_PC32 against undefined symbol _ZGVbN2v_log@@GLIBC_2.22 can not be used when making a shared object; recompile with -fPIC`

**Comment by RiccardoRossi** [comment]
Hi,
    My proposal would be to remove the fastmath when in debug mode.

That may fix your issue. Regarding the linker error, could you try to remove intrinsically? (Take out the msse)

**Comment by roigcarlo** [comment]
@maceligueta Which error is giving you the ExternalSolver application? Nightly builds run with gcc 5.3.1 and --ffast-math enabled with no problems

Edit: Just saw the error. I would said that this has something to do with something else which happens to conflict with -ffast-math, but the flag along in kratos should be fine, ( from the compiling point of view)

**Comment by pooyan-dadvand** [comment]
Long time ago I had to take out the fast math (to check some round off error problem) and I have not seen a noticeable different. @RiccardoRossi Do you have recent experience on that?

**Comment by RiccardoRossi** [comment]
we did some benchmarks some time back with @ddemidov and the difference was pretty large in the solution.

**Comment by ddemidov** [comment]
I just did a quick test re `-ffast-math`, and it does not look like the option makes any difference. The tests were made on a 16-core Intel(R) Xeon(R) CPU E5-2640 v3 @ 2.60GHz system.

### With `-ffast-math`:
- 3D Poisson on a 150^3 grid (scalar problem):
```
$ OMP_PROC_BIND=TRUE numactl -l ./solver -n 150
coarsening:          smoothed_aggregation
relaxation:          spai0
Number of levels:    4
Operator complexity: 1.57
Grid complexity:     1.12

level     unknowns       nonzeros
---------------------------------
    0      3375000       23490000 (63.87%)
    1       401950       12700268 (34.53%)
    2         8690         586182 ( 1.59%)
    3           99           4139 ( 0.01%)

Iterations: 20
Error:      6.96252e-09

[Profile:          3.804 s] (100.00%)
[ self:            0.011 s] (  0.30%)
[  assembling:     0.212 s] (  5.56%)
[  setup:          1.169 s] ( 30.73%)
[  solve:          2.412 s] ( 63.41%)
```
- Non-scalar problem (I think its Navier-Stokes in 3D), 4x4 blocks as values:
```
$ OMP_PROC_BIND=TRUE numactl -l ./solver -B -A block4/A.bin -f block4/b.bin -P block4/p.json -b4
coarsening:          aggregation
relaxation:          damped_jacobi
Number of levels:    3
Operator complexity: 1.05
Grid complexity:     1.05

level     unknowns       nonzeros
---------------------------------
    0       186736        2620098 (95.63%)
    1         8469         116745 ( 4.26%)
    2          397           2977 ( 0.11%)

Iterations: 67
Error:      8.77855e-07

[Profile:       3.160 s] (100.00%)
[ self:         0.004 s] (  0.12%)
[  reading:     0.330 s] ( 10.43%)
[  setup:       0.289 s] (  9.15%)
[  solve:       2.537 s] ( 80.30%)
```
### Without `-ffast-math`:
- 3D Poisson:
```
OMP_PROC_BIND=TRUE numactl -l ./solver -n 150
coarsening:          smoothed_aggregation
relaxation:          spai0
Number of levels:    4
Operator complexity: 1.57
Grid complexity:     1.12

level     unknowns       nonzeros
---------------------------------
    0      3375000       23490000 (63.87%)
    1       401950       12700268 (34.53%)
    2         8690         586182 ( 1.59%)
    3           99           4139 ( 0.01%)

Iterations: 20
Error:      6.96252e-09

[Profile:          3.789 s] (100.00%)
[ self:            0.012 s] (  0.32%)
[  assembling:     0.227 s] (  5.99%)
[  setup:          1.182 s] ( 31.19%)
[  solve:          2.368 s] ( 62.50%)
```
- Non-scalar problem:
```
$ OMP_PROC_BIND=TRUE numactl -l ./solver -B -A block4/A.bin -f block4/b.bin -P block4/p.json -b4
coarsening:          aggregation
relaxation:          damped_jacobi
Number of levels:    3
Operator complexity: 1.05
Grid complexity:     1.05

level     unknowns       nonzeros
---------------------------------
    0       186736        2620098 (95.63%)
    1         8469         116745 ( 4.26%)
    2          397           2977 ( 0.11%)

Iterations: 67
Error:      8.77855e-07

[Profile:       3.208 s] (100.00%)
[ self:         0.004 s] (  0.11%)
[  reading:     0.379 s] ( 11.83%)
[  setup:       0.302 s] (  9.41%)
[  solve:       2.523 s] ( 78.66%)
```

**Comment by loumalouomega** [comment]
@ddemidov So If I understood correctly the difference in time is not so high 3.804 vs 3.789 in the first case and 3.160 vs 3.208 in the second case.

**Comment by ddemidov** [comment]
I would just compare 'setup' and 'solve' times, so 1.169/2.412 vs 1.182/2.368 and 0.289/2.537 vs 0.302/2.523. I would say the difference is small enough to be a sporadic measurement effect.

I get similar results on my older machine (4 core Intel(R) Core(TM) i7 CPU 920 @ 2.67GHz). The numbers here are 2.444/11.066 vs 2.496/11.520 for Poisson and 0.570/11.862 vs 0.594/12.580 for the non-scalar problem. The build with `-ffast-math` is repeatedly faster here, but the difference is still not very big.

**Comment by pooyan-dadvand** [comment]
Thanks @ddemidov. It seems that finally the difference is about 2-5%. So removing the flag won't bother me so much.

**Comment by RiccardoRossi** [comment]
Is thai to be closed?

**Comment by maceligueta** [comment]
The Problem 1 was solved, I think it was an update of the linux kernel.
I have to check about Problem 2 in #580

**Comment by pooyan-dadvand** [comment]
I would add this to release 5.2

**Comment by RiccardoRossi** [comment]
@jcotela @roigcarlo can we close this taking into account #881 ?

**Comment by rainwoodman** [comment]
Problem 1 was a bug in GLIBC 2.22. If your folks have updated GLIBC it should have disappeared automatically. I wonder if there is any other workaround than disabling fastmath.

**Comment by pooyan-dadvand** [comment]
Thank @rainwoodman for your comment. We will take note of GLIBC 2.22 when compiling in old machine to avoid this problem!
