### ISSUE TITLE
Voight stress vector size should be 4 in plane strain condition

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/Kratos#3690]
Hi,

I performed a simple calculation using StructuralMechanicsApplication. I defined a square in 2D plane strain condition and applied self-weight. I used LinearElasticPlaneStrain2DLaw.

In plane strain condition, we have 4 nonzero Cauchy stresses (i.e. sig_xx, sig_yy, sig_zz and sig_xy). However, the size of stress vector is set to 3 in LinearElasticPlaneStrain2DLaw and sig_zz is ignored.

**Comment by Vahid-Galavi** [comment]
The example is attached.

[04_k0_procedure_StructuralMechanics.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2691054/04_k0_procedure_StructuralMechanics.gid.zip)

**Comment by RiccardoRossi** [comment]
dear vahid, we use 3 stress components bkth for 2d plane strain and 3d
plane stress. zz sttrss shoukd be probably implemented as postprocess (but
i don t think is impleme ted as of now)

**Comment by philbucher** [comment]
this was discussed in #3935 

I also think the postprocess for zz-stress is not implemented yet

**Comment by philbucher** [comment]
closeing since inactive and consensus was reached in #3935
