### ISSUE TITLE
TRAVIS blocking PRs 

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#3692]
Travis is blocking PRs, because it exceeds the time limits. Furthermore it is compiling some applications only. If a PR has not relationship with these applications, why they must be compiled ?, is a waste of time and a useless thing. These are the applications included in the compilation:
                STRUCTURAL_MECHANICS_APPLICATION - ON
                FLUID_DYNAMICS_APPLICATION - ON
                DEM_APPLICATION - ON
                EXTERNAL_SOLVERS_APPLICATION - ON
Why these applications and not others? Which is the followed criterion to set them ON? 
Maybe it will be better to set them OFF to reduce the compilation time and avoid such problems.

**Comment by RiccardoRossi** [comment]
we are working to fond solutions. for now the only option is to restart the travis compilation.

the list of applications to be compiled is selected by the technical committee and is limited exactly by the compilation time offered by the free version of travis.

**Comment by josep-m-carbonell** [comment]
About the list of applications. And related to #3553. Is it a coincidence that those applications are the ones belonging (in terms of who is the responsible mantainer) to the members of the technical committee themselves?

**Comment by roigcarlo** [comment]
Ideally we would like to compile every application in development in Kratos, and the reason to compile applications that are apparently not related to one's PR is precisely to capture errors that may be affecting such applications as a side effect of the changes that were not tested by the developer.

As @RiccardoRossi says, we are currently working on a solution to this which will enable us to compile all applications both in windows and linux, probably even with multiple compilers, and have more control over what we want to do and when we want to do it without having to depend on 3rd party services.

This is technically hard to deploy as we need a system which is able to scale with minimal effort in the future as the tendency is the code to be bigger every time.

As for the list of applications in Travis, I am part of the technical committee and the person who basically built the current system, and I don't have any of the applications I develop or I am interested in being tested. So, again, the list is purely selected based on which applications fit better the time limits. 

Appveyor has more time and more applications are in. I remember you coming to tell me if we could add your applications and telling you that there was no problem, we even helped with the sub-modules problem (see #2952 and #3081)

**Comment by josep-m-carbonell** [comment]
Appveyor is also experiencing problems and blocking PRs. So the same as TRAVIS.
If there is any problem to include in Appveyor some of the applications I am responsible, please tell me. It was a kind of favour?
If you, like the person who is basically in charge of built the current system, can not test the parts that you consider that have main interest for the correct functioning of the code. Something inappropriate is happening.

**Comment by roigcarlo** [comment]
Is not a problem that you have you application in appveyor, as I said we
would like as many applications as possible to be in the integration tests,
but currently not all of them can be compiled because we are at the limit
of what the services we use right now can deliver.

This was not a problem when we initially build it but has proven to have
limitations as the code grew. Precisely for that reason we started to work
in a more scalable system.

We could remove the applications and only compile the core and we have
discussed that possibility already but we believe that the benefits of
having to restart the builds in the case they fail currently outweight the
problems of having incorrect code in the master. Of course you are free to
think differently and expose your opinion.

I thought by your comments that it was important to explain the reasons why
there are currently applications being compiled while others are not and
why the list of applications is different due to the different services
allowing us to use more or less resources, and that there are more people
suffering from the current limitations right know.

**Comment by maceligueta** [comment]
I think we should focus on the permanent solution of this issue, as nobody actually likes the current situation. 
@josep-m-carbonell , you already had your answer: some members of the @KratosMultiphysics/technical-committee are building a complex system which will compile all the applications in a reasonable time, probably in more operating systems than now.
For that, we are planning to install our own dedicated computers. This might be solved in the following weeks. Your application will be compiled, as any other that you need to add. 
If this answer seems satisfactory to you, please close the issue. If you want to request more features/capabilities go ahead.

**Comment by josep-m-carbonell** [comment]
I think that an issue must be closed when it is solved. Right now we only have your kind words telling that the @KratosMultiphysics/technical-committee is going to do a big sacrifice to satisfy my request. I have to thank you for that consideration. However, nothing has been solved right now.

**Comment by maceligueta** [comment]
That's not exact. The Comittee was working on this long before your request. Because everyone knows that the current CI is not sufficient.

**Comment by josep-m-carbonell** [comment]
That's ok, however, my thanks to trying to solve this well-known issue are kept.

**Comment by josep-m-carbonell** [comment]
Solved. Reopen if needed
