### ISSUE TITLE
Announcement: V Kratos Workshop -- 25th to 27th March 2019

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#3707]
## V Kratos Workshop, Technical University of Munich (TUM)

Edit: last updated on 22 Jan. Please check the [workshop webpage](http://www.st.bgu.tum.de/de/software/forschung/kratos-multiphysics/kratos-workshop-2019/) for up-to-date information.

The fifth edition of the Kratos Workshop will take place at the Technical University of Munich from the 25th to the 27th of March 2019.
The Kratos Workshop is the main meeting of users and developers of the Kratos Multiphysics open-source framework. Its goal is to bring together developers, industrial users and researchers to present new features in the code and discuss new and potential applications.

### Objectives:

-   Give an overview on the open-source Multiphysics software project for potential future users and contributors.
-  Provide forum for recent and (potential) future users and developers in research and industry.
-  Improve the common knowledge of developers by presenting the latest features of the Kratos and solutions based on Kratos.
-  Team building.
-  In person discussions and contacts.
-  Take advantage of round tables to discuss important issues and features.
-  Dissemination of Kratos capabilities to local research centers and industries.
-  Support the identification and formation of subject-specific networks and joint developer groups.

### Events:

-  Monday March 25th (Vorhoelzer Forum):
Presentations about Kratos Multiphysics and its use in industrial and research applications.
- Tuesday March 26th (Vorhoelzer Forum):
Continuation of presentations.
Discussion roundtables focusing on code design and development of new features.
- Wednesday March 27th (Seminar room TBA):
Hands-on Kratos Course. Participants are asked to bring their own laptop. The course will assume a basic level of knowledge of the Python language.

### Venue:

TUM Munich, City Campus, Vorhoelzer Forum (25th and 26th) http://www.ar.tum.de/en/vf/startseite/
Seminar room for training on the 27th to be determined.

**Please register at the following [link](https://www.cognitoforms.com/KratosMultiphysics/KratosWorkshop2019Registration)**
Registration is open from 21.01.2019 to 22.02.2019.
Total number of participants will be restricted due to available room capacities.

Suggestions for contributions (talks on requirements of open-source software for various purposes in research and industry, presentations about recent developments, focused topics for round tables and discussion groups, … ) are highly welcome.

The organization of the workshop gratefully acknowledges the financial support of our partners:
![partners](https://user-images.githubusercontent.com/5071546/51616511-8b707000-1f2a-11e9-8a2e-c5136c115a99.png)

**Comment by philbucher** [comment]
The registration is open now:
https://www.cognitoforms.com/KratosMultiphysics/KratosWorkshop2019Registration

**Comment by jcotela** [comment]
Workshop-related information will be centralized at
http://www.st.bgu.tum.de/de/software/forschung/kratos-multiphysics/kratos-workshop-2019/

Please see the updated schedule (essentially, we will have some presentations on the 26th too).

The registration will remain open up to 22.02.2019.
