### ISSUE TITLE
[PFEM] I want to ask for advice and study the couped CFD-PFEM.

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3709]
Hello,
Someone did the couping CFD-PFEM or CFD-PFEM2? As Dr.Larese and her team did with couped CFD-PFEM in the attached paper, what I want to do is similar with the 'Failure analysis of scale models of rockfill dams under seepage conditions' including the process of seepage and dam break.
 
![_20181221143715](https://user-images.githubusercontent.com/38140045/50328621-c730a800-052e-11e9-9086-829b3c0293af.png)
And also as  Gonzalez Gutierrez illustrated in her master thesis, she update the method to coupled CFD-PFEM2 to sovle the rockfill dam break and seepage problem.
![_20181217200635](https://user-images.githubusercontent.com/38140045/50328848-c0566500-052f-11e9-82d3-1d64403bc899.jpg)
I am intersted this and my work in the future will be to solve the dam break. So I want to talk about someone about this method and study.I am glad to do anything that makes us progress together.
Thanks very much.
[TFM_María_González_Gutiérrez.pdf](https://github.com/KratosMultiphysics/Kratos/files/2701797/TFM_Maria_Gonzalez_Gutierrez.pdf)

**Comment by maceligueta** [comment]
Referencing @antonialarese  @josep-m-carbonell @AFranci @ipouplana @GuillermoCasas .

**Comment by philbucher** [comment]
can this be closed?

**Comment by antonialarese** [comment]
Dear @fengzekang First of all my apologies for the late reply. I thought I already have answered you, but it was a different issue. Sorry.
I will be glad to share all the papers and information on both the CFD-Seepage model and the coupling.

[2014Larese_Archives.pdf](https://github.com/KratosMultiphysics/Kratos/files/2840552/2014Larese_Archives.pdf)
[2012RossiLarese_IJNMF.pdf](https://github.com/KratosMultiphysics/Kratos/files/2840555/2012RossiLarese_IJNMF.pdf)


Currently, unfortunately the version of PFEM used for these examples is no longer present. Nevertheless  we are going to couple the CFD seepage model to the new MPM developments (see  https://github.com/KratosMultiphysics/Kratos/blob/master/applications/ParticleMechanicsApplication/README.md ) creating an updated version of the coupling strategy.
Please, see the following papers for further information.
[2017Iaconeta_Materials.pdf](https://github.com/KratosMultiphysics/Kratos/files/2840558/2017Iaconeta_Materials.pdf)
[2018Iaconeta_CompMech.pdf](https://github.com/KratosMultiphysics/Kratos/files/2840559/2018Iaconeta_CompMech.pdf)
[2017_Iaconeta_MPMcongress.pdf](https://github.com/KratosMultiphysics/Kratos/files/2840560/2017_Iaconeta_MPMcongress.pdf)
[2019_Chandra_MPMcongress.pdf](https://github.com/KratosMultiphysics/Kratos/files/2840561/2019_Chandra_MPMcongress.pdf)


Feel free of contacting me at my personal address for any further discussion.

Regards

**Comment by fengzekang** [comment]
Dear @antonialarese  
Thanks for your reply and your help. I will read these papers later.
Best regards.
Feng
