### ISSUE TITLE
[DataValueContainer] Check in Debug related to Allocation

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3712]
I was checking the code with @jcotela and have a question:
[GetValue](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/containers/data_value_container.h#L208-L226) checks (if in OMP) if a certain Variable already exists before allocating it and throws if not

[SetValue](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/containers/data_value_container.h#L258-L269) on the other hand ALSO allocates if a certain variable does not exist but does NOT throw

Now the question is, is it threadsafe or not? I think it is, but I am not entirely sure.
The [VariableUtils](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/variable_utils.h#L341-L357) are using this and I am pretty sure this does allocate in parallel (Afaik this has not created problems yet).
=> E.g. if Variables are allocated for Nodes separately then I think this is threadsafe, but the check would prevent this

@RiccardoRossi you added the corresponding check, can you comment?

**Comment by philbucher** [comment]
probably also interesting for @msandre

**Comment by roigcarlo** [comment]
`SetValue` is not threadsafe, 

`GetValue` is threadsafe as long as the variable has already been set, hence the check in debug mode that throws an error if your are trying to use the `GetValue` function to allocate the variable.

**Comment by philbucher** [comment]
@roigcarlo but both methods internally do the same allocation in case the Variable does not exist, so how can one be thread-safe and the other not? Thats my confusion:

GetValue: `mData.push_back(ValueType(&rThisVariable,new TDataType(rThisVariable.Zero())));`

SetValue: `mData.push_back(ValueType(&rThisVariable,new TDataType(rValue))); //TODO: this shall be insert not push_back`

**Comment by roigcarlo** [comment]
Because `GetValue()` is technically a `GetAndSetValue()`

The get part is safe, the set is not. Examples (pseudocode)

* Parallel set / Parallel  get
```C++
// This is not threadsafe because SetValue is not
#pragma omp parallel for
for(auto &node: ModelPart.GetNodes()) {
    node.SetValue(FOO_VAR, 0)
}

// This part is threadsafe because the variable has already been set
#pragma omp parallel for
for(auto &node: ModelPart.GetNodes()) {
    node.GetValue(FOO_VAR)
}
```

* Parallel get / Parallel  get
```C++
// This is not threadsafe becase it does not act as GetValue but as a SetValue
#pragma omp parallel for
for(auto &node: ModelPart.GetNodes()) {
    node.GetValue(FOO_VAR) = 0
}

// This part is threadsafe becasue the variable has been set by the fallback case of the GetValue
#pragma omp parallel for
for(auto &node: ModelPart.GetNodes()) {
    node.GetValue(FOO_VAR)
}
```

* Serial set / Parallel get
```C++
// This is safe because is not in parallel
for(auto &node: ModelPart.GetNodes()) {
    node.SetValue(FOO_VAR,0)
}

// This part is threadsafe becasue the variable has been set by the fallback case of the GetValue
#pragma omp parallel for
for(auto &node: ModelPart.GetNodes()) {
    node.GetValue(FOO_VAR)
}
```

* Serial get / Parallel get
```C++
// This is also safe because is not in parallel
for(auto &node: ModelPart.GetNodes()) {
    node.GetValue(FOO_VAR) = 0
}

// This part is threadsafe becasue the variable has been set by the fallback case of the GetValue
#pragma omp parallel for
for(auto &node: ModelPart.GetNodes()) {
    node.GetValue(FOO_VAR)
}
```

**Comment by roigcarlo** [comment]
Notice here:

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/containers/data_value_container.h#L216

That, if the variable exists, it does not execute the pushback, which is the non-threadsafe part

**Comment by philbucher** [comment]
ok but then we should also add this check in `SetValue` right?
~~~c
#ifdef KRATOS_DEBUG
        if(OpenMPUtils::IsInParallel() != 0)
            KRATOS_ERROR << "attempting to do a GetValue for: " << rThisVariable << " unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)" << std::endl;
#endif 
~~~

Plus then we have to correct the VariableUtils, i.e. removing the omp [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/variable_utils.h#L350)

**Comment by roigcarlo** [comment]
Not really, the code in the VariableUtils is ok, becase the container is preallocated, and there is no pushback.

The +k ensures that any thread is accessing the same element twice or at the same time, and there is no push_back because it enters the first condition of the SetValue function.

As for marking the pushback part as non-threadsafe 👍 .

We could make something like:

```C++
    template<class TDataType> void SetValue(const Variable<TDataType>& rThisVariable, TDataType const& rValue)
    {
#ifdef KRATOS_DEBUG
        KRATOS_ERROR_IF(rThisVariable.Key() == 0) << "attempting to do a SetValue for: " << rThisVariable << " the variable has key zero" << std::endl;
#endif
        typename ContainerType::iterator i;

        if ((i = std::find_if(mData.begin(), mData.end(), IndexCheck(rThisVariable.Key())))  != mData.end())
            *static_cast<TDataType*>(i->second) = rValue;
        else {
#ifdef KRATOS_DEBUG
            if(OpenMPUtils::IsInParallel() != 0)
                KRATOS_ERROR << "attempting to do a GetValue for: " << rThisVariable << " unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)" << std::endl;
#endif 
            mData.push_back(ValueType(&rThisVariable,new TDataType(rValue))); //TODO: this shall be insert not push_back
        }
    }
```

**Comment by philbucher** [comment]
Ok this makes sense to me, the check you are proposing is also what I had in Mind

Regarding the VariableUtils: I was explaining myself badly, the code in there is fine but not how we use it, i.e. in many cases this is used to initialize, i.e. allocate the values, which makes it non-thread-safe

=> Proposal:
- Modify the existing function by removing the OMP
- Add another function that does the same but in OMP and call it `FastSetNonHistoricalVariable` or `ParallelSetNonHistoricalVariable`

This way we would not break existing code, but slowing it down in the worst case (in cases where OMP is ok bcs the values are already allocated)

**Comment by roigcarlo** [comment]
Ok

I was answering you and I realized that SetValue is actually half-threadsafe as GetValue, so I supose the check is in the Get function only because of the name of the method.

Technically you don't need to do any change in the VariableUtils, in hat loop its threadsafe, sorry for the confusion.

Still, addign the check in the set probably is a good idea.

**Comment by RiccardoRossi** [comment]
Hi Guys.
the current behaviour is deliberate. Neither GetValue nor SetValue are threadsafe, however SetValue can be used (with care) to allocate space for a variable while GetValue can not.

**Comment by philbucher** [comment]
@RiccardoRossi are you saying that we should add the check @roigcarlo is proposing or not?

What is confusing for me is that both methods use the same code for allocating (given the Variable was not allocated before) but one is threadsafe while the other one is not
Just trying to understand :)

If you are sure that the current behavior is the correct and intended one then please feel free to close this issue

**Comment by RiccardoRossi** [comment]
@philbucher let me expan on my previous answer.

let's consider the code

~~~c++
     auto& value = pnode->GetValue(VELOCITY)
     #pragma omp parallel
      value = other_value //BUM! writing conflict
~~~

here we have a racing condition at writing so we need to protect the writing somehow.

~~~c++
     #pragma omp parallel
     const auto& value = pnode->GetValue(VELOCITY) //ok if VELOCITY exists in node
~~~

this code would work if VELOCITY exists, however it would crash if velocity is not allocated. Here we throw an error in the case VELOCITY is not allocated, but otherwise **the code works correctly**. 

The problem is however if we want to allocate a value in parallel. for example imagine you want to do

~~~c++
    #pragma omp parallel for
    for(int i=0; i<rNodes.size(); ++i)
    {
              auto it = rNodes.begin() + i;
              it->GetValue(TEMPERATURE) = 0.0; //would be ok: never working on the same node !!
                                     //BUT it throws!
    }
~~~

the loop above is ok even if TEMPERATURE is not allocated, UNFORTUNATELY an exception is thown since you are accessing a variable that does not exist within a parallel region. 
NOW you do want this to be possible, so the way yo achieve it is to do:

~~~c++
    #pragma omp parallel for
    for(int i=0; i<rNodes.size(); ++i)
    {
              auto it = rNodes.begin() + i;
              it->SetValue(TEMPERATURE, 0.0); //ok! here we do not do the check but at least it is explicit what you do...
    }
~~~

so the SetValue does not throw to allow you to write the code above. In this sense the current behaviour is by design

**Comment by loumalouomega** [comment]
> @philbucher let me expan on my previous answer.
> 
> let's consider the code
> 
> ```c++
>      auto& value = pnode->GetValue(VELOCITY)
>      #pragma omp parallel
>       value = other_value //BUM! writing conflict
> ```
> 
> here we have a racing condition at writing so we need to protect the writing somehow.
> 
> ```c++
>      #pragma omp parallel
>      const auto& value = pnode->GetValue(VELOCITY) //ok if VELOCITY exists in node
> ```
> 
> this code would work if VELOCITY exists, however it would crash if velocity is not allocated. Here we throw an error in the case VELOCITY is not allocated, but otherwise **the code works correctly**.
> 
> The problem is however if we want to allocate a value in parallel. for example imagine you want to do
> 
> ```c++
>     #pragma omp parallel for
>     for(int i=0; i<rNodes.size(); ++i)
>     {
>               auto it = rNodes.begin() + i;
>               it->GetValue(TEMPERATURE) = 0.0; //would be ok: never working on the same node !!
>                                      //BUT it throws!
>     }
> ```
> 
> the loop above is ok even if TEMPERATURE is not allocated, UNFORTUNATELY an exception is thown since you are accessing a variable that does not exist within a parallel region.
> NOW you do want this to be possible, so the way yo achieve it is to do:
> 
> ```c++
>     #pragma omp parallel for
>     for(int i=0; i<rNodes.size(); ++i)
>     {
>               auto it = rNodes.begin() + i;
>               it->SetValue(TEMPERATURE, 0.0); //ok! here we do not do the check but at least it is explicit what you do...
>     }
> ```
> 
> so the SetValue does not throw to allow you to write the code above. In this sense the current behaviour is by design

@philbucher This is what the VariableUtils does

**Comment by philbucher** [comment]
@RiccardoRossi thanks for the detailed explanation, much appreciated!
now it all makes sense, thanks for taking the time

Then we don't need to do anything, closing

@jcotela this is the solution to the discussion we were having the other day
