### ISSUE TITLE
[Pfem] "CheckForPreviousImport" is not needed any more and can be safely removed

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3713]
Hello,  @AFranci 
::[Pfem Fluid Solver]:: Model reading finished.
::[Pfem Fluid Solver]:: DOF's ADDED
SetInletProcess:  inlet_management CONSTRUCTOR DEPRECATION: "CheckForPreviousImport" is not needed any more and can be safely removed
It does nothing any more 
DEPRECATION: "CheckForPreviousImport" is not needed any more and can be safely removed
It does nothing any more 
DEPRECATION: "CheckForPreviousImport" is not needed any more and can be safely removed
It does nothing any more 
::[Meshing_Domain]:: ( Body1  ) -BUILT-
::[Meshing_Domain]:: ( Body2  ) -BUILT-
::[Meshing_Domain]:: ( Body3  ) -BUILT-
::[--Process_Handler--]:: Process List Ready
::[--Domain Utilities-]:: Nodal Search executed 
::[Meshing Domain]:: -START-
::[Fluid Meshing Strategy]:: SET MESHER
DEPRECATION: "CheckForPreviousImport" is not needed any more and can be safely removed
It does nothing any more 
DEPRECATION: "CheckForPreviousImport" is not needed any more and can be safely removed
It does nothing any more 
Construction of the Pre Refining Mesher finished
::[--Meshing Strategy-]:: Ready
::[Meshing Domain]:: -END- 
the mean_nodal_h is   0.31524108880164986
::[Meshing Domain]:: -START-
::[Fluid Meshing Strategy]:: SET MESHER
::[--Meshing Strategy-]:: Ready
::[Meshing Domain]:: -END- 
::[Meshing Domain]:: -START-
::[Fluid Meshing Strategy]:: SET MESHER
::[--Meshing Strategy-]:: Ready
::[Meshing Domain]:: -END- 
InletManagementProcess:  inlet_management CONSTRUCTOR RemoveMeshNodesForFluidsProcess:  remove_mesh_nodes_process_for_fluids DEPRECATION: "CheckForPreviousImport" is not needed any more and can be safely removed
It does nothing any more 

If I got these messages in the terminal after I run the 'runkratos Mainkratos.py' to do a test, what's meaning of this information, especially for the next sentence:
DEPRECATION: "CheckForPreviousImport" is not needed any more and can be safely removed
It does nothing any more 
DEPRECATION: "CheckForPreviousImport" is not needed any more and can be safely removed
It does nothing any more.
Best regards.

**Comment by philbucher** [comment]
hi @fengzekang 
The function `CheckForPreviousImport` is legacy, i.e. it is not needed any more.
In order to not break existing code that still calls this functions we put a deprecation-warning informing the users that they can simply delete <the call to this function

**Comment by fengzekang** [comment]
Thank you @philbucher  And also, there is another message every step as shown:
ATTENTION! NO PROPERTIES HAVE BEEN FOUNDED FOR THIS ELEMENT! X,Y 7,17
ATTENTION! NO PROPERTIES HAVE BEEN FOUNDED FOR THIS ELEMENT! X,Y 7,17
ATTENTION! NO PROPERTIES HAVE BEEN FOUNDED FOR THIS ELEMENT! X,Y 7,17
ATTENTION! NO PROPERTIES HAVE BEEN FOUNDED FOR THIS ELEMENT! X,Y 7,17
ATTENTION! NO PROPERTIES HAVE BEEN FOUNDED FOR THIS ELEMENT! X,Y 7,17
 DANGEROUS ELEMENT!!!!!!!!!!!!!!!!!!!!!
 MeanValueMass=0	 MeanValueMaterial= 19972.9ATTENTION! NO PROPERTIES HAVE BEEN FOUNDED FOR THIS ELEMENT! X,Y 6.50048,17 
Is this meaning that my model has wrong element? right?
Best regards.

**Comment by fengzekang** [comment]
CRITICAL MESH SIZE :  supplied size 0.315241 is bigger than initial mesh size 0.307021 ]

**Comment by AFranci** [comment]
Dear @fengzekang, please update to the new master version. The warning should not appear anymore.

**Comment by fengzekang** [comment]
Dear @AFranci 
Thanks for your help. I will study this application deeply and help you deal with other problems in the future. Thanks again.

**Comment by philbucher** [comment]
@fengzekang general comment:
We are cleaning the Kratos-Core a lot since a few months
This involves also the refactoring of many things which break other things
Since this is really inconvenient for other users/developers we usually ensure backwards-compatibility by only deprecating and not removing old methods.
They still work as expected but give a hint to the developer (the depreciation warnings you had) that they should be updated
For you as a user those warnings don’t really matter

**Comment by fengzekang** [comment]
Thanks for your reply @philbucher  I understand your meaning. And also I hope I can make some development for the Kratos in the future.
Best regards.
