### ISSUE TITLE
Improvements for Adjoint-Elements

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3727]
I found some things that should be improved, using this issue as a reminder:
- In Adjoint-Truss: `CalculateReferenceLength` and `CalculateCurrentLength` are reimplemented, I think those functions could go to a a utility-namespace **EDIT:** solved in #3915
- [Creating new ProcessInfos](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_response_functions/adjoint_elements/adjoint_finite_difference_base_element.cpp#L304) should be avoided => will be possible after #2993

**Comment by armingeiser** [comment]
You mean a static method like
```cpp
static double TrussElement3D2N::CalculateCurrentLength(Geometry&, int Id) //id is needed for potential error message
{ 
...
}

**Comment by philbucher** [comment]
@armingeiser almost
It should be a free function within the [`StructuralMechanicsElementUtilities`](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_utilities/structural_mechanics_element_utilities.h) such that it can be used by all 1D-elements
