### ISSUE TITLE
[StructuralMechanics] MassMatrix-default: lumped or consistent?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3728]
The title says it all, we should agree on how to specify that the lumped-/consistent mass-matrix is used.

Afaik currently in the Beams the lumped is default, while in the Solids the consistent one is default.
In the Shells it is not consistent (haven't had the time yet to clean it)

Also we should agree on a variable (`bool`) that is used for specifying it.
Currently used in Solids: `COMPUTE_LUMPED_MASS_MATRIX`
Currently used in Beams: `USE_CONSISTENT_MASS_MATRIX`

What do you think regarding those two things?
- Consistent vs lumped (could be different for different elements?)
- Name of variable used to specify it? Personally I like sth with `USE_XXX_MASS_MATRIX`

**Comment by philbucher** [comment]
related to #3715

**Comment by loumalouomega** [comment]
Due to the fact that Kratos is by default implicit I would use consistent by default. You want lumped matrix to compute explicit computations. In a implicit computation lumped matrix bring to "noise" (I don't remember the proper name, but the thing is that the quality in the time integration is drop)

**Comment by loumalouomega** [comment]
About the options:

Currently used in Solids: COMPUTE_LUMPED_MASS_MATRIX->Vote this comment with :+1: 
Currently used in Beams: USE_CONSISTENT_MASS_MATRIX->Vote this comment with :heart: 

Edit: I change the :-1: to avoid negative bias

**Comment by RiccardoRossi** [comment]
I am not sure of what we should default to. My reasoning is that Consistent mass matrix is more precise, however it is more expensive to compute and slighty more difficult to solve. 
Also for example in the context of convection diffusion problems the use of lumped mass matrices leads to somewhat smaller overshoots and undershoots. 

For now my vote is for USE_CONSISTENT_MASS_MATRIX ...   but you can make me change opinion

**Comment by AndreasWinterstein** [comment]
I would also suggest to use the consistent one by default except when using the explicit time integration. I currently did some dynamic simulations with shells and especially there the consistent one is better.

**Comment by loumalouomega** [comment]
> I would also suggest to use the consistent one by default except when using the explicit time integration. I currently did some dynamic simulations with shells and especially there the consistent one is better.

Can you vote in my comment?, right now there is tie 1-1

**Comment by AndreasWinterstein** [comment]
Done. I just got a bit confused by the emojis.

**Comment by philbucher** [comment]
> About the options:
> 
> Currently used in Solids: COMPUTE_LUMPED_MASS_MATRIX->Vote this comment with +1
> Currently used in Beams: USE_CONSISTENT_MASS_MATRIX->Vote this comment with heart
> 
> Edit: I change the -1 to avoid negative bias

I just noticed that this vote is just abt the name of the variable not abt the behavior and hence a bit confusing :)

=> I would suggest that whatever becomes the default we use the other name:
I.e. we seem to be more inclined towards using the consistent MM as default, and optinally the lumped one => then I think using `COMPUTE_LUMPED_MASS_MATRIX` would make more sense for the user

Still waiting for the opinion of @KlausBSautter , afterwards I will make an attempt on unifying this
Thx for your comments

**Comment by RiccardoRossi** [comment]
what is the conclusion of this PR? it should be commented in the wiki once a consensus is reached

**Comment by philbucher** [comment]
> what is the conclusion of this PR? it should be commented in the wiki once a consensus is reached

@RiccardoRossi will do, sorry I haven't done it yet
I am anyway planning to write a more elaborate guide for users/devs how the elements work
