### ISSUE TITLE
ShapeFunctionsValues(IntegrationMethod xyz) for class Line3D2 not available

### ISSUE THREAD

**Issue by swenczowski** [KratosMultiphysics/Kratos#3742]
I am very sorry in case I have been missing an obvious solution to the experienced problem so far. The observation is the following:

For an instance of class `Line3D2` (more precisely `Line3D2<IndexedPoint>` ), the shape function values could be retrieved by means of the function `ShapeFunctionsValues( GeometryData::GI_GAUSS_2 )`, where the specification of the quadrature rule is the only argument of the function. An example is given below:

`const Matrix& n_container = p_aux_line->ShapeFunctionsValues( GeometryData::GI_GAUSS_2 );`

The function `ShapeFunctionsValues(IntegrationMethod xyz)` is defined in the class `Geometry`. After the function was overwritten in the derived class `Line3D2 in the scope of #3621 by @loumalouomega, the described function call is no longer possible and the compilation fails. Only after lines 640 - 651 in /kratos/geometries/line_3d_2.h were commented, the old behaviour could be restored.

At the moment I am not sure whether it was intended that `ShapeFunctionsValues(IntegrationMethod xyz)` can no longer be used as described. In this case, I would be very grateful for a hint pointing out an alternative approach to retrieve the shape function values for a given quadrature rule. If the described change was not intended, I think it would be great if the function was further available.

Thank you very much for having a look in advance.

**Comment by loumalouomega** [comment]
Can you provide any example to replicate the error?, I created the PR #3743, in the new test created I can use the function without any additional problem

**Comment by swenczowski** [comment]
Thank you very much for your response. As you show in the PR #3743 (line 324), the function call 

`geom->ShapeFunctionsValues(N_values, coord);` (A)

works. This is also true for my application. What I was trying to do is to use the function call

`const Matrix& n_container = geom->ShapeFunctionsValues( GeometryData::GI_GAUSS_2 );`, (B)

where the function receives the quadrature rule as the only argument. If you want to test this, all you need to do is to replace (A) by (B). This function call (B) used to work for my application but failed after #3621. 

As I understand the class hierarchy, `Line3D2` should inherit this function from class `Geometry`. Or I am a missing an important detail here?

**Comment by philbucher** [comment]
@swenczowski I think the problem is that your `geom` is obtained with `auto` right?
=> the compiler replaces `auto` by `Line3D2N<...>` and not by `Geometry<...>` (don't know the exact reason, just an assumption)
=> the polymorphism fails

Can you try specifying the type explicitly?

**Comment by philbucher** [comment]
https://stackoverflow.com/questions/38320732/whats-the-right-behavior-when-auto-meets-polymorphism-and-virtual-function

**Comment by swenczowski** [comment]
Thank you very much for this hint. Indeed, I was using a smart pointer to an instance of `Line3D2`. A working version finally reads:
~~~c
Kratos::shared_ptr< Geometry<IndexedPoint> > p_aux_line = nullptr;
GenerateAuxLine( rGeom, distance, p_aux_line, aux_velocity1, aux_velocity2 );

const auto& IntegrationPoints = p_aux_line->IntegrationPoints( GeometryData::GI_GAUSS_2 );
const unsigned int num_gauss = IntegrationPoints.size();
Vector gauss_pts_det_jabobian = ZeroVector(num_gauss);
p_aux_line->DeterminantOfJacobian(gauss_pts_det_jabobian, GeometryData::GI_GAUSS_2);
const Matrix n_container = p_aux_line->ShapeFunctionsValues( GeometryData::GI_GAUSS_2 ); //(here 
error)
~~~

Please excuse that I am still stuck at the initial question, however: Why is it advantageous that the function call `ShapeFunctionsValues( GeometryData::GI_GAUSS_2 )` is no longer possible for an object of type `Line3D2` (as it was before)?  

Thank you very much for your effort and help, @loumalouomega and @philbucher. The code under development is now in a working state, again.

**Comment by philbucher** [comment]
good question
@roigcarlo any idea?

**Comment by roigcarlo** [comment]
I believe the problem is that we are combining override and overloading of a derivative class. 

`line2d3.h` and `line2d2.h` both are implementing just a flavour of  `ShapeFunctionsValues`. This one https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/geometries/geometry.h#L1757 to be specific.

As there are two versions of this function in the base class and the derived ones are only implementing one, the other is being hidden from the base.

In order to solve this we should either propagate the implementation of the missing overload to the children, which is not a very good idea, or add 

```c++
using Geometry<TPointType>::ShapeFunctionsValues;
```

To the files where you want the other definition available.

**Comment by philbucher** [comment]
@swenczowski can you please try if it works then?

**Comment by swenczowski** [comment]
My apologies for the delayed reply - I was a bit confused and had to do some reading first. By this occasion, I came across

https://en.cppreference.com/w/cpp/language/using_declaration (in particular the sub-section "In class definition").

If I understood the given example correctly, I would even make sense to include `using Geometry<TPointType>::ShapeFunctionsValues;` in the classes `Line2D2` and `Line3D2`. Thus, all the base class definitions would be further available from the derived `LineXD2`-classes and the functions implemented inside the derived classes would still override where it is required.

Does this make sense? Did I understand correctly what you meant, @roigcarlo?

**Comment by roigcarlo** [comment]
@swenczowski Yes, exactly. 

We should have added it in #3621 while overriding the other one but we missed it. Sorry for that.

**Comment by swenczowski** [comment]
Thank you very much for your quick reply - I tested it already and a suggestion can be found in PR #3753.

Again, thanks to everybody for your effort and the discussion!
