### ISSUE TITLE
Modal Analysis Help

### ISSUE THREAD

**Issue by Rbravo555** [KratosMultiphysics/Kratos#3747]
Good day. 

I am Raul Bravo, working on my master thesis. I kindly request some help or guidance to use the Modal Analysis tool in Kratos. I am using the GiD interface.

Best regards,

Raul Bravo
MSc Computational Mechanics
UPC Barcelona

**Comment by philbucher** [comment]
Hi Raul,
Select kratos => Structural => Model-Information => Eigenvalue
![screenshot from 2019-01-03 09-37-35](https://user-images.githubusercontent.com/25484702/50629043-406ec880-0f3b-11e9-86ce-a2bd1d170c9d.png)

The define your model and the constraints and it should work

Note that you have to manually load the visualization file in the postprocessing => `xxx_EigenResults.post.bin`

**Comment by Rbravo555** [comment]
Thanks a lot for your reply

**Comment by philbucher** [comment]
is this solved @Rbravo555 ?
If so then please close this issue

**Comment by Rbravo555** [comment]
@philbucher Could you please point to the folder in Kratos where modal analysis is coded? Thanks

**Comment by philbucher** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_eigensolver.py

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_strategies/custom_schemes/eigensolver_dynamic_scheme.hpp

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_strategies/custom_strategies/eigensolver_strategy.hpp
