### ISSUE TITLE
[MeshMoving] Local large mesh deformation

### ISSUE THREAD

**Issue by rafaelbravopareja** [KratosMultiphysics/Kratos#3774]
Dear developers:

I'm trying to impose mesh deformations using MeshMoving application. The Laplacian deformation fails it only deforms the elements where deformation is only applied creating a deformation with no geometrical meaning. 
![laplacian](https://user-images.githubusercontent.com/37374816/50769295-cfede180-1283-11e9-8a26-fee05fb93eb5.jpg)
The structural_similarity method works well for global deformations, but for local deformations, some elements become very distorted and their volume become negative 

![structural](https://user-images.githubusercontent.com/37374816/50770207-c4e88080-1286-11e9-8101-d9372c29bf9e.jpg)

Is there any problem with the laplacian method?, What am i doing wrong with the structural similarity? Is there any way to avoid that the volume of the elements become negative?

Thank you in advance

Here are my input files:

[test_laplacian.zip](https://github.com/KratosMultiphysics/Kratos/files/2732838/test_laplacian.zip)
[test_structural.zip](https://github.com/KratosMultiphysics/Kratos/files/2732841/test_structural.zip)

**Comment by philbucher** [comment]
We will take a look
FYI @AndreasWinterstein

**Comment by philbucher** [comment]
By briefly looking at it it seems like you are missing the call to PrepareModelPart
Filling the buffer is done there, I can imagine that this creates problems if not done.

I recommend using the MeshMovingAnalysis (or deriving you own class from it for customization) rather than doing all the steps by hand, this way you are safer

If you want to do it  by hand, then take a look at the call sequence in kratos/python_scripts/analysis_stage.py

**Comment by philbucher** [comment]
The tests are working, you can have a look there how it works with a more up-to-date version

**Comment by rafaelbravopareja** [comment]
Dear Phil:

Thank you for your prompt answer. I have update to the most recent version of Kratos with boost1.67 and things continue the same. 

The message that I obtain with the laplacian is :
ResidualBasedEliminationBuilderAndSolver: ATTENTION! setting the RHS to zero!

I also have run the tests with Laplacian and I obtain the same message.  For the structural_similarity case the volume of the elements become negative.

Please could you provide a hand script? I need to combine several applications.

Thank you very much

**Comment by adityaghantasala** [comment]
As a comment 

> ResidualBasedEliminationBuilderAndSolver: ATTENTION! setting the RHS to zero!

this generally means that the Dirichlet boundary condition displacement is zero. Hope that helps in tracing the issue.

**Comment by AndreasWinterstein** [comment]
Just a comment from my side. The mesh solvers work best, when you are refining at the boundary, since small elements are treated stiffer than lager elements. 

The warning "ATTENTION! setting the RHS to zero!". This should only appear at the first step, since the RHS is calculated from the displacement and this is zero in the first step.

@adityaghantasala is right. This warning means that you are not setting the Dirichlet boundary conditions correctly.

**Comment by philbucher** [comment]
> Dear Phil:
> 
> Thank you for your prompt answer. I have update to the most recent version of Kratos with boost1.67 and things continue the same.
> 
> The message that I obtain with the laplacian is :
> ResidualBasedEliminationBuilderAndSolver: ATTENTION! setting the RHS to zero!
> 
> I also have run the tests with Laplacian and I obtain the same message. For the structural_similarity case the volume of the elements become negative.
> 
> Please could you provide a hand script? I need to combine several applications.
> 
> Thank you very much

@rafaelbravopareja the tests issue this message only bcs in the first step there is no movement applied. I also checked the tests, they run as expected.

As I wrote before, the tests are already a complete setup. On the python-side, you can directly use the `MeshMovinAnalysis` like we do in the tests. This is up-to-date with the global developments ([`AnalysisStage`](https://github.com/KratosMultiphysics/Kratos/wiki/Common-Python-Interface-of-Applications-for-Users)) in Kratos

You should be able to use this with your custom project-parameters, which in the simplest case only contain the solver-settings and the boundary conditions

I strongly suggest you try this and report the results
Alos take into account the comments of @adityaghantasala and @AndreasWinterstein

**Comment by pooyan-dadvand** [comment]
Just to add that for local smoothing process you should set the BOUNDARY flag in all walls to fix the nodes there

**Comment by AndreasWinterstein** [comment]
Is this solved? Can we close this?

**Comment by rafaelbravopareja** [comment]
Dear Andreas:

I have not still tried the suggestion from Pooyan. Let's wait several days.

Thanks

**Comment by philbucher** [comment]
@rafaelbravopareja the suggestion of @pooyan-dadvand refers to a process in the Core
the `BOUNDARY`-Flag is not used in the MeshMovingApp

**Comment by rafaelbravopareja** [comment]
With boundary flag the simulation is working much better. Thank you very much. You can close this issue. 

Regards
