### ISSUE TITLE
FastQuadSpatialContainer problems

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#379]
By #376 creating a new class derived from `Bins_dynamic_objects`, a problem has arisen in  `FastQuadSpatialContainer` because `FastQuadSpatialContainersConfigure` does not define the functions for "radius".

This was hidden before, since the base bins was not derived, the functions that where not called ( the ones with radius argument) were simply not compiled.

The solution is as easy as declare those functions, which will simply call the normal ones. Or maybe it implies separate the new bins into a different class.

@iiaconeta, @GuillermoCasas  is it ok if I make the changes myself? (not sure which solution is the best right now)
I m not sure who is responsible for that particles code.

**Comment by iiaconeta** [comment]
I am the responsible for the ParticleMechanicsApplication.
@roigcarlo I think the best solution is to declare these new functions in `FastQuadSpatialContainer`

**Comment by GuillermoCasas** [comment]
Of course, please go ahead and make these changes! Sorry, I should have seen this coming.

**Comment by roigcarlo** [comment]
:+1:
