### ISSUE TITLE
[Core] Should we add a deprecation warning into read_materials_process

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3791]
https://github.com/KratosMultiphysics/Kratos/blob/cf973ad58e6162c4554334b7800468ab5b0df637/kratos/python_scripts/read_materials_process.py#L10

In order to "force" developers to migrate to the C++ ReadMaterialsUtility class

@KratosMultiphysics/structural-mechanics @bodhinandach

**Comment by philbucher** [comment]
hmmm
I am using an abomination of this for some stuff, but this is only local.

I would say we can deprecate it, before they diverge...

Pls wait for the opinion of others before making a PR

**Comment by loumalouomega** [comment]
Yep, I was suggesting just a warning, like in the python process

**Comment by philbucher** [comment]
Ok thats fine I guess

**Comment by philbucher** [comment]
Is this even still used? Did you grep for usages?

**Comment by loumalouomega** [comment]
Yes it is used on the particle and MPM applications, that's why I mentioned @bodhinandach

**Comment by philbucher** [comment]
Ah ok, I will speak with him next week

**Comment by bodhinandach** [comment]
Sorry @philbucher @loumalouomega I am still away for a conference. Will return next week and get back to this soon.

**Comment by loumalouomega** [comment]
Don't worry

**Comment by philbucher** [comment]
once #3883 is merged I think you can go ahead @loumalouomega

**Comment by loumalouomega** [comment]
Nice

**Comment by philbucher** [comment]
Now you can go ahead @loumalouomega
