### ISSUE TITLE
[StructuralMechanics] multiple time intervals per analysis

### ISSUE THREAD

**Issue by philipkalkbrenner** [KratosMultiphysics/Kratos#3797]
Is there a way to define multiple time intervals with differing time step sizes?
for example:
"start_time_1"    : 0.0,
"end_time_1"     : 1.0,
"time_step_1"    : 0.10,
"start_time_2"    : "end_time_1",
"end_time_2"     : 2.0,
"time_step_2"    : 0.010

**Comment by philbucher** [comment]
What Application are you referring to?

**Comment by philipkalkbrenner** [comment]
StructuralMechanicsApplication

**Comment by philbucher** [comment]
In theory this is possible, we just did not implement it yet.

An easy way to do this would be sth like this (referring to [`AdvanceInTime`](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L242-L248))
Change this to accept your input (defined in `ProjectParameters/solver_settings/time_stepping`) that you showed above, i.e. return the time that depends on your variable time-step

FYI @RiccardoRossi we can discuss how to do this properly in the future

**Comment by philipkalkbrenner** [comment]
Thanks a lot @philbucher, I could easily do it the way you explained it!

**Comment by philbucher** [comment]
closing since solved

Please reopen if necessary
