### ISSUE TITLE
DEMApplicatin:is there the format of Cluster_DEM.mdpa files in any tests?

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3798]
Dear @maceligueta 
I asked you about cluster_dem problem before and I checked the core files in the application. I found that there is a file named cluster_mdpa_creator.py which give us a format of the .mdpa file, looks like:

Begin Nodes
NodeNumber[j]    NodeX[j]   NodeY[j]   NodeZ[j]
End Nodes
Begin Elements Cluster3D
NodeNumber   ClusterType    NodeNumber[j]
End Elements
Begin NodalData CHARACTERISTIC_LENGTH
NodeNumber[j]     0     ChLength[j]
End NodalData
Begin NodalData ORIENTATION
NodeNumber[j]    0 [4] (  qX[j]  ,  qY[j]  ,  qZ[j] , qW[j])
End NodalData

In this file, I don't know the ClusterType  and ChLength and the last one NodeNumber[j]    0 [4] (  qX[j]  ,  qY[j]  ,  qZ[j] , qW[j])
For this, is there a document to introduce this file or just the format of this cluster_dem.mdpa?
Best regards~
Feng

**Comment by maceligueta** [comment]
@joaquinirazabal , you have this fresher than me. Can you answer please?

**Comment by joaquinirazabal** [comment]
Dear @fengzekang 
The way to define the clusters_mdpa is:

Begin ModelPartData
// VARIABLE_NAME value
End ModelPartData

Begin Properties 1
PARTICLE_DENSITY 1.0
YOUNG_MODULUS 1.0e6
POISSON_RATIO 0.2
FRICTION 0.0
PARTICLE_COHESION 0.0
COEFFICIENT_OF_RESTITUTION 0.2
PARTICLE_MATERIAL 1
ROLLING_FRICTION 0.0
ROLLING_FRICTION_WITH_WALLS 0.0
BREAKABLE_CLUSTER 0
CLUSTER_FILE_NAME benchmark_cylinder.clu
DEM_DISCONTINUUM_CONSTITUTIVE_LAW_NAME DEM_D_Hertz_viscous_Coulomb
DEM_CONTINUUM_CONSTITUTIVE_LAW_NAME DEMContinuumConstitutiveLaw
End Properties

Begin Nodes
5 0.0 0.0 0.0
End Nodes

Begin Elements Cluster3D
2 1 5
End Elements

Begin NodalData CHARACTERISTIC_LENGTH
5 0 1.0
End NodalData

Begin NodalData ORIENTATION
5 0 [4] ( 0.0 , 0.0 , 0.0 , 1.0 )
End NodalData

As you can see, in the Properties you have to set the CLUSTER_FILE_NAME, which is the file defining the cluster (you can find some examples in DEMApplication/custom_elements/custom_clusters/).

You can use different types of clusters defining more properties with different CLUSTER_FILE_NAME, and that is the reason for using ClusterType which is the property number of that cluster.

ChLength is the size of the cluster compared to the size of the cluster defined in the file, in this case, benchmark_cylinder.clu

The last part is to define the initial orientation of the cluster. If it is not rotated you have to use: NumberoftheNode 0 [4] ( 0.0 , 0.0 , 0.0 , 1.0 ).

( 0.0 , 0.0 , 0.0 , 1.0 ) is a quaternion, you can rotate the cluster changing it.
