### ISSUE TITLE
[PFEM_Pluid]No results in the output

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#3806]
[Slope_test3D.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/2752101/Slope_test3D.tar.gz)

Dear @AFranci 
These days, I used the PFEM_FluidApplication to do a simulation of the slope 3D. There is no error in the running process in Kratos.  I got the .res and .msh files every steps, but there is empty in the .res files and only get the results of .msh. So I can open the result files in the GID to visualise the slope.
And also when I open the .lst file aiming to see every step and the whole process, but there are warnings showing during opening every step file, as bellow:
Some errors found in the results file:
Found EOF too early 
  in line 1 of file '/home/fengzk/Slope/model_inlet_0.001.post.res'.
Some errors found in the results file:
Found EOF too early 
  in line 1 of file '/home/fengzk/Slope/model_inlet_0.01.post.res'.
Some errors found in the results file:
Found EOF too early 
  in line 1 of file '/home/fengzk/Slope/model_inlet_0.02.post.res'.
..............(as same as every step)

By the way, I clicked the 'View Results' and then in the option 'Control fill' 'Control lines' and other options there is no results looks like x_displacement, y_displacement, acceleration and so on.
The attached files are the input files, and I really set the output including Displacement, velocity and so on in the .json file. I am confused for this problem~~~

What should I do to deal with this problem and get the results of displacement or velocity so on.
Best regards
Feng

**Comment by fengzekang** [comment]
Dear @AFranci 
If I changed the "GiDPostMode"           : "GiD_PostAscii" to PostBinary, the output files in GID will be shown with the data results such as velocity, pressure and displacement. So now I can see the results in GID.
But I think we should deal with the option of 'PostAscii', so that the data results will be shown in the .res file and we can check it corresponding to every node and elements.
Best regards.
Feng

**Comment by AFranci** [comment]
Dear @fengzekang
Yes, you should use the default Binary option to see correctly the results in the post-process. 
However, we (@maceligueta , @ipouplana ) will try to fix the Ascii option in the next future.
Thank you and best regards,
Alessandro
