### ISSUE TITLE
Compute drag process

### ISSUE THREAD

**Issue by 94zz94** [KratosMultiphysics/Kratos#3807]
Hi everyone
I tried to execute compute_custom_drag_process.py by inserting in ProjectParameter this:
            "python_module" : "compute_custom_drag_process",
            "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
            "process_name"  : "ComputeCustomDragProcess",
            "Parameters"    : {
                "model_part_name"        : "FluidModelPart.Drag_structure",
                "write_drag_output_file" : true,
                "print_drag_to_screen"   : false,
                "interval"               : [0.0,"End"]
Then I received from the terminal:

Traceback (most recent call last):
  File "MainKratosCustom.py", line 34, in <module>
    simulation.Run()
  File "/opt/Kratos/kratos/python_scripts/analysis_stage.py", line 47, in Run
    self.Initialize()
  File "/opt/Kratos/kratos/python_scripts/analysis_stage.py", line 80, in Initialize
    self.Check()
  File "/opt/Kratos/kratos/python_scripts/analysis_stage.py", line 163, in Check
    process.Check()
AttributeError: 'ComputeCustomDragProcess' object has no attribute 'Check'
KRATOS TERMINATED WITH ERROR

 Can anyone help me?

In Annex there's the process.
[compute_custom_drag_process.txt](https://github.com/KratosMultiphysics/Kratos/files/2751941/compute_custom_drag_process.txt)

**Comment by philbucher** [comment]
This should be fixed for a while already in Master
Can you update to the latest version?

Btw the python-process is deprecated, you should derive from the c-process
Check out how the regular drag process in FluidDynamics is done
