### ISSUE TITLE
Windows compile problems in Contact Structural Mechanics and Convection Diffussion

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#3837]
On Windows 10

![image](https://user-images.githubusercontent.com/5918085/51202359-dc66df80-18fe-11e9-8861-920c531a1e44.png)

[https://docs.microsoft.com/en-us/cpp/parallel/openmp/2-7-2-6-reduction?view=vs-2017](https://docs.microsoft.com/en-us/cpp/parallel/openmp/2-7-2-6-reduction?view=vs-2017)

**Comment by loumalouomega** [comment]
Well, we deactivatated windows compilations to make faster the appveyor
(not my decision but I agreed).
