### ISSUE TITLE
the problem of using python_solvers_wrapper_structural

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#3843]
Is python_solvers_wrapper_structural deprecated one? 
I am trying to construct the solving file with solver python_solvers_wrapper_structural, but there are some unknowing problems.
**this is the code of inputing model part and creating solver:**
main_model_part = ModelPart(ProjectParameters["problem_data"]["model_part_name"].GetString())#main_model_part.ProcessInfo.SetValue(DOMAIN_SIZE, ProjectParameters["problem_data"]["domain_size"].GetInt())
import python_solvers_wrapper_structural
solver = python_solvers_wrapper_structural.CreateSolver(main_model_part, ProjectParameters)

**the error is following the process of creating solver:**
Exception: input is expected to be provided as a Kratos Model object

**Comment by ZhimingGuo** [comment]
I use the method of Python Script Tutorial to rewrite this part, like:
this_model = KratosMultiphysics.Model()
main_model_part = this_model.CreateModelPart(ProjectParameters["problem_data"]["model_part_name"].GetString())
main_model_part.ProcessInfo.SetValue(DOMAIN_SIZE, ProjectParameters["problem_data"]["domain_size"].GetInt())
main_model_part_io = ModelPartIO(ProjectParameters["problem_data"]["problem_name"].GetString())
main_model_part_io.ReadModelPart(main_model_part)
import python_solvers_wrapper_structural
solver = python_solvers_wrapper_structural.CreateSolver(main_model_part, ProjectParameters)

but the error is still there.

**Comment by philbucher** [comment]
You have to pass „this_model“, not the ModelPart 
That’s exactly the error message you are getting

**Comment by ZhimingGuo** [comment]
**I put "this_model" in solver, like**
solver = python_solvers_wrapper_structural.CreateSolver(this_model, ProjectParameters)
**but have another error, it shows model part name cannot be passed through solvers.**
structural_mechanics_solver.py", line 109, in __init__
    raise Exception('Please specify a model_part name!')
Exception: Please specify a model_part name!

**Comment by philbucher** [comment]
you have to specify a name for the ModelPart in the solver-settings

BTW why do you try to create the case yourself? I would recommend to use the StructuralMechanicsAnalysis, then you can simplify your life a lot

**Comment by ZhimingGuo** [comment]
**I wrote codes with StructuralMechanicsAnalysis,** 
if __name__ == "__main__":
    with open("ProjectParameters.json",'r') as parameter_file:
        parameters = KratosMultiphysics.Parameters(parameter_file.read())
    model = KratosMultiphysics.Model()
    simulation = StructuralMechanicsAnalysis(model,parameters)
    simulation.Run()

**But, there is still have error companioned**
Read materials: Started
Read materials: Ignoring module information for component LinearElasticPlaneStress2DLaw
Read materials: Ignoring module information for component CROSS_AREA
Read materials: Ignoring module information for component TORSIONAL_INERTIA
Read materials: Ignoring module information for component I22
Read materials: Ignoring module information for component I33
Read materials: Finished

  File "/home/zhiming/Kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py", line 420, in _create_linear_solver
    return KratosMultiphysics.LinearSolverFactory().Create(linear_solver_configuration)
**RuntimeError: Error**: Trying to construct a Linear solver with solver_type:
"Super_LU" which does not exist.
The list of available options (for currently loaded applications) is:
Kratos components
    AMGCL
    AMGCLSolver
    AMGCL_NS_Solver
    BICGSTABSolver
    CGSolver
    DeflatedCGSolver
    ScalingSolver
    SkylineLUFactorizationSolver
    TFQMRSolver

**Comment by ZhimingGuo** [comment]
replaced Super_LU with AMGCL, for example, the computation continue to run, but result is not correct.

::[StaticMechanicalSolver]::  Initializing ...: 
::[MechanicalSolver]::  Initializing ...: 
::[MechanicalSolver]::  Constructing a regular (non-complex) linear solver: 
::[MechanicalSolver]::  Finished initialization.: 
::[StaticMechanicalSolver]::  Finished initialization.: 
::[KSM Simulation]:: : Analysis -START-  
::[KSM Simulation]:: : STEP:  1 
::[KSM Simulation]:: : TIME:  0.0005 
**ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!**
::[KSM Simulation]:: : STEP:  2 
::[KSM Simulation]:: : TIME:  0.001 
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
::[KSM Simulation]:: : STEP:  3 
::[KSM Simulation]:: : TIME:  0.0015 
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!
::[KSM Simulation]:: : STEP:  4 
::[KSM Simulation]:: : TIME:  0.002 
ResidualBasedBlockBuilderAndSolver: ATTENTION! setting the RHS to zero!

**Comment by ZhimingGuo** [comment]
sorry, the last one should be caused by neglecting to add external force boundary condition.

**Comment by philbucher** [comment]
If you want to use the SuperLU, then you have to import the `ExternalSolversApplication` in `MainKratos.py`
