### ISSUE TITLE
[StructuralMechanics] Some sensititvity tests are failing

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#3845]
The tests for the sensitivities TestAdjointSensitivityAnalysisNonLinearTrussStructure, TestAdjointSensitivityAnalysisLinearTrussStructure and TestEigenfrequencyResponseFunction are currently failing. Please check them.

**Comment by armingeiser** [comment]
I just tested it with the current master, but i cannot reproduce this error. Lets have a look tomorrow at your computer.

**Comment by armingeiser** [comment]
If i run the tests independently, so not from the "test_StructuralMechanicsApplication.py" or "kratos/python_scripts/run_tests.py" however, they do produce errors related to #3634 because the ExternalSolversApplication is not explicitly imported in those scripts.

**Comment by MFusseder** [comment]
On my machine TestEigenfrequencyResponseFunction is running but the truss tests produce errors even if I include the ExternalSolversApplication. The error message is:
"AttributeError: module 'KratosMultiphysics.kratos_utilities' has no attribute 'IsApplicationAvailable'"

**Comment by armingeiser** [comment]
After some more tests at @AndreasWinterstein computer we found the reason for the failing tests:

He has both, TrilinosApplication and EigenSolversApplication compiled.
If both are imported at the same time, segfaults happen.
This is the case if the `test_StructuralMechanicsApplication.py`  is used to run the tests. If the tests are run individually, they work.

**Comment by AndreasWinterstein** [comment]
I think we can close this. We will have to figure this out, when including MPI tests into the StructuralMechanicsApplication.

**Comment by philbucher** [comment]
closing, description on how to solve it is in #4114
