### ISSUE TITLE
[StructuralMechanics] line load uses POSITIVE_FACE_PRESSURE

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3848]
shouldn't it use `POSITIVE_LINE_PRESSURE` and `NEGATIVE_LINE_PRESSURE` instead of `POSITIVE_FACE_PRESSURE` and `NEGATIVE_FACE_PRESSURE`?
seems inconsistent to me
@KratosMultiphysics/structural-mechanics 

also including @rubenzorrilla and @bodhinandach

**Comment by loumalouomega** [comment]
Does POSITIVE_LINE_PRESSURE and NEGATIVE_LINE_PRESSURE exist?

**Comment by philbucher** [comment]
not yet, but I guess it could make sense to define it

**Comment by loumalouomega** [comment]
I think that the name is correct, otherwise we need to repeat almost the same code for 2D and 3D

**Comment by philbucher** [comment]
what code would need to be repeated? I don't understand.
I would simply change the name of the variable, just to make it more clear

IMO it is confusing that a FACE-pressure is applied to a line => dimension mismatch

**Comment by loumalouomega** [comment]
The think is that the line load and surface load are essentially the same, just changing the geoemetry

**Comment by philbucher** [comment]
Ok then we should also unify/refactor the code, but in a separate step

what do others thing regarding the naming?

**Comment by bodhinandach** [comment]
> The think is that the line load and surface load are essentially the same, just changing the geoemetry

I think I agree with @loumalouomega. I mean in 2D, basically we omit the other dimension, and therefore a line pressure there is actually a surface pressure.

**Comment by RiccardoRossi** [comment]
I also agree with   @loumalouomega ... a line is the face of a  2D structure abd i wouldn't like to have to change all the code and the interface to distinguish 2D fro 3D

**Comment by philbucher** [comment]
Even in 2D the topology is a line ...

Also what units does this have?
Without looking into the code I wouldn't know. I think this can confuse not-so-experienced users

Either way, I am not using this, so I am fine with it :)
Just wanted to point it out
