### ISSUE TITLE
[Trilinos][MPI] Compilation failing 

### ISSUE THREAD

**Issue by swenczowski** [KratosMultiphysics/Kratos#3852]
After recent changes, the master branch does not seem to compile without errors any more. Dear @jcotela, @roigcarlo told me that you were the expert to turn to in this respect. Unfortunately, I do not understand the code well enough to suggest a correction, here. The error was first noticed in the afternoon of Jan16, 2019. The following error message is displayed:

[ 97%] Building CXX object applications/trilinos_application/CMakeFiles/KratosTrilinosApplication.dir/trilinos_application.cpp.o

In file included from /home/simon/Kratos_Main/applications/trilinos_application/trilinos_application.cpp:20:0:
/home/simon/Kratos_Main/applications/trilinos_application/custom_factories/trilinos_linear_solver_factory.h:123:102: error: redefinition of ‘Kratos::KratosComponents<TComponentType>::ComponentsContainerType Kratos::KratosComponents<TComponentType>::msComponents’
 typename KratosComponents<TComponentType>::ComponentsContainerType KratosComponents<TComponentType>::msComponents;
                                                                                                      ^
In file included from /home/simon/Kratos_Main/kratos/includes/kratos_application.h:23:0,
                 from /home/simon/Kratos_Main/applications/trilinos_application/trilinos_application.h:22,
                 from /home/simon/Kratos_Main/applications/trilinos_application/trilinos_application.cpp:19:
/home/simon/Kratos_Main/kratos/includes/kratos_components.h:445:68: note: ‘Kratos::KratosComponents<TComponentType>::ComponentsContainerType Kratos::KratosComponents<TComponentType>::msComponents’ previously declared here
 typename KratosComponents<TComponentType>::ComponentsContainerType KratosComponents<TComponentType>::msComponents;
                                                                    ^
applications/trilinos_application/CMakeFiles/KratosTrilinosApplication.dir/build.make:62: die Regel für Ziel „applications/trilinos_application/CMakeFiles/KratosTrilinosApplication.dir/trilinos_application.cpp.o“ scheiterte (english: the rule to generate ... failed)

It would be very kind, if you could have a look at the respective files, please. Thank you very much in advance.

**Comment by roigcarlo** [comment]
I've tested and it seems to compile without the duplicated definition. I can make a PR but not sure if we can happily delete it.

It wasn't crashing before #3589 because the core definition was warded, but I cannot see why it was needed there, it doesn't seem like anyone is using it...

**Comment by philbucher** [comment]
@jcotela and I added this to make it work initially
If it also works/compiles without then you can happily remove it :)

**Comment by jcotela** [comment]
Looking into the timeline of the changes, I would say that this line was added after I created my branch, so this is a conflict that was not (could not) be detected by git.

**Comment by swenczowski** [comment]
Thank you very much. The compilation now runs without problems. In contrast, the following error still occurs for me (@roigcarlo, as mentioned):

AttributeError: 
module 'KratosMultiphysics' has no attribute 'mpi'

After checking-out an older version of the master, this problem could be solved. Thus, I hope it is not  caused by my local implementations. For me, the error can be reproduced by simply executing (in python3):

`from KratosMultiphysics.mpi import *`

Do you think this could be related or should I open a new issue in this concern?

**Comment by jcotela** [comment]
@swenczowski can you try adding `-DMPI_NEEDED=ON \` to your cmake compilation file (if you do not have it already)

**Comment by philbucher** [comment]
I have the same problem @jcotela , but I don't understand fully what is going on. I briefly checked it, could be some circular import

**Comment by swenczowski** [comment]
@jcotela : No, adding `-DMPI_NEEDED=ON  \` unfortunately does not seem to solve the problem. The error message further reads as follows:

  File "/home/simon/Kratos_Main/kratos/python_scripts/analysis_stage.py", line 36, in __init__
    import KratosMultiphysics.mpi as KratosMPI
  File "/home/simon/Kratos_Main/KratosMultiphysics/mpi/__init__.py", line 17, in <module>
    from .. import legacy_mpi_python_interface
  File "/home/simon/Kratos_Main/KratosMultiphysics/legacy_mpi_python_interface.py", line 4, in <module>
    import KratosMultiphysics.mpi as mpi

**Comment by swenczowski** [comment]
This error was fixed in #3857 by @philbucher.

Gentlemen, thank you all very much for your effort and help.

**Comment by swenczowski** [comment]
I am sorry for re-opening this issue, but the following observation was made:

After checking out the master branch most recently, the following error message was displayed when starting a regular case. From its first impression, the error may somehow be related to the problems described here in #3852. The `-DMPI_NEEDED=ON` option was set for compiling.

Traceback (most recent call last):
  File "MyMainKratos.py", line 60, in <module>
    simulation = FluidDynamicsAnalysisWithFlush(model,parameters)
  File "MyMainKratos.py", line 19, in __init__
    super(FluidDynamicsAnalysisWithFlush,self).__init__(model,project_parameters)
  File "/home/simon/Kratos_Main/applications/FluidDynamicsApplication/python_scripts/fluid_dynamics_analysis.py", line 35, in __init__
    super(FluidDynamicsAnalysis,self).__init__(model,parameters)
  File "/home/simon/Kratos_Main/kratos/python_scripts/analysis_stage.py", line 36, in __init__
    import KratosMultiphysics.mpi as KratosMPI
ImportError: No module named 'KratosMultiphysics.mpi'

The sub directories `KratosMultiphysics` and `libs` were deleted before the compilation to avoid any influences.

**Comment by swenczowski** [comment]
I am sorry for re-opening this issue, but the following observation was made:

After checking out the master branch most recently, the following error message was displayed when starting a regular case. From its first impression, the error may somehow be related to the problems described here in #3852. The -DMPI_NEEDED=ON option was set for compiling.

Traceback (most recent call last):
File "MyMainKratos.py", line 60, in
simulation = FluidDynamicsAnalysisWithFlush(model,parameters)
File "MyMainKratos.py", line 19, in init
super(FluidDynamicsAnalysisWithFlush,self).init(model,project_parameters)
File "/home/simon/Kratos_Main/applications/FluidDynamicsApplication/python_scripts/fluid_dynamics_analysis.py", line 35, in init
super(FluidDynamicsAnalysis,self).init(model,parameters)
File "/home/simon/Kratos_Main/kratos/python_scripts/analysis_stage.py", line 36, in init
import KratosMultiphysics.mpi as KratosMPI
ImportError: No module named 'KratosMultiphysics.mpi'

The sub directories KratosMultiphysics and libs were deleted before the compilation to avoid any influences.

**Comment by philbucher** [comment]
I had the same problems but it worked after @jcotela and I fixed it.

Can you post a screenshot of the contents of your `KratosMultiphysics`-folder?

**Comment by swenczowski** [comment]
I am sorry for the delayed answer - a running simulation (compiled with an older version) prevented an immediate recompilation of Kratos. After recompiling (with `git pull` in advance), however, the initially described problem had vanished. 

My apologies for the alarm and I still cannot explain the source of the error. Neither can I explain why it works now. I assume I made an unnoticed change somewhere which caused the problem.

For the sake of documentation, the content of the folder `KratosMultiphysics` is the following:

![grafik](https://user-images.githubusercontent.com/45034120/51854126-539e6980-232a-11e9-8b8d-e37efc3167ed.png)
