### ISSUE TITLE
Some way to access to the processes outside the python main script

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#386]
Concerning #385, I had the same problem I had in previous implementations of remeshing, where I needed to recompute processes after remeshing to have a solvable model part. Until now I was using some kind of complicated python trick, loosing generality, but in #385 was impossible to use this trick because the remeshing is done directly inside the non-linear loop, implemented via a convergence criteria.  (I don't want to use a strategy, the convergence criteria is more modular and can be used in different strategies)

I have been thinking, and everything I thought I needed to modify the kernel, in order save the processes in python in the process info or something and execute them inside the loop (or wherever and whenever I want).

**Comment by RiccardoRossi** [comment]
Hi Vicente,
    i am not sure of what you need, however you should NOT change the way processes are passed to the Main script. 

if you need you can compose processes one inside the other, however you will not be able to use them from another place. This was a programmatic decision...

**Comment by loumalouomega** [comment]
What I did in the previous `mmg_process.py` is to add the flag `MODIFIED` to the model part, and then in the main script to check before the `Solve()` iof the model part is `MODIFIED`, in that case we recompute the processes, something like:

~~~
if (self.main_model_part.Is(MODIFIED) == True):
    # WE INITIALIZE THE SOLVER
    self.solver.Initialize()
    # WE RECOMPUTE THE PROCESSES AGAIN
    ## Processes initialization
    for process in self.list_of_processes:
        process.ExecuteInitialize()
    ## Processes before the loop
    for process in self.list_of_processes:
        process.ExecuteBeforeSolutionLoop()
    ## Processes of initialize the solution step
    for process in self.list_of_processes:
        process.ExecuteInitializeSolutionStep()
~~~

For more details look to the `Kratos_Execute_Meshing_Test.py` in the test folder of the `MeshingApplication`

**Comment by loumalouomega** [comment]
The problem comes when you want to do this inside the non-linear loop, I am not asking to change the current API, but to extend it or think some way to keep  the current API and do what I am saying.

**Comment by loumalouomega** [comment]
I was thinking in pass the list of processes as a python object in C++ code, https://stackoverflow.com/questions/37577676/using-python-objects-in-c, but this is maybe too advanced.

**Comment by pooyan-dadvand** [comment]
@loumalouomega passing python processes to the c++ code violates the layers relations in Kratos. Python layer is the top most and above all C++ ones. The reason behind this design is to keep the global modularity of the code and keep the scripting part as separate as possible.

**Comment by loumalouomega** [comment]
Yes, I spoke with Riccardo and he said to keep the current implementation and "play" with the number of linear iterations, and we will look for a nicer way in the future
