### ISSUE TITLE
IsotropicDamageSimoJu test failed in cl_test of structural_mechamics_application

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#3866]
the test IsotropicDamageSimoJu can not get constitutive law, even though i make the material document. please check it. 
the constitutive law should be IsotropicDamageSimoJuPlaneStress2DLaw.

**Comment by loumalouomega** [comment]
That test is quite old, and should be removed (and if you see it is not executed in the tests of the application)

**Comment by pooyan-dadvand** [comment]
Is there any test for it?

**Comment by loumalouomega** [comment]
This a law that only exists in the Solid application, the test is
deprecated and it is proposed to be removed in a PR.
