### ISSUE TITLE
(What has been done / What is important to be done) regarding the Constitutive Laws in StructuralMechApp

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#3874]
Dear Structural Mechanics Team (and colleagues)
I think that it is important to recapitulate all the implemented CL and the current state of them. In this way I've created the following table in order to summarize the work done.

![imagen](https://user-images.githubusercontent.com/26402605/51334522-42c73b80-1a80-11e9-9128-e4b50ede5c3c.png)

This issue has, in my opinion, two main objectives:

1. Summarize and decide the TODO tasks regarding the job done

2. Talk about the future implementations (new CL's, modifications of the current structure of the code...)

Thank you all,

**Comment by loumalouomega** [comment]
nice, I still have pending to apply the last corrections in the large deformations laws

**Comment by RiccardoRossi** [comment]
@AlejandroCornejo well done! my feeling is that it would be pretty important to have some implementation of the basic casis of plane stress/strain (once we agreed about #3935 )

also what kind of plastic potential etc ?

as a final comment we should document with some examples of use

**Comment by frastellini** [comment]
Thank you @AlejandroCornejo .
It would be also good to have a table with implemented yield functions, plastic potentials and hardening laws available for plastic (and damage) models.

**Comment by AlejandroCornejo** [comment]
![imagen](https://user-images.githubusercontent.com/26402605/51748417-a8cd4780-20ac-11e9-8438-54a8bfec5ae6.png)

**Comment by philbucher** [comment]
Guys will you make a separate issue abt separating the CLaws into a different shared-library and replacing the template-mechanism by sth more suitable?

**Comment by loumalouomega** [comment]
I tried, but is a little bit more complex I expected, because recursive dependencies between laws and other things

**Comment by AlejandroCornejo** [comment]
> 
> 
> Guys will you make a separate issue abt separating the CLaws into a different shared-library and replacing the template-mechanism by sth more suitable?

I think that we can talk about that here in fact :)

**Comment by philbucher** [comment]
> I tried, but is a little bit more complex I expected, because recursive dependencies between laws and other things

Ok

Still I would say this should be made priority very soon after the release, the linking times have really increased and it affects out developments in StructuralMechanics

**Comment by philbucher** [comment]
ping, any news?

**Comment by philbucher** [comment]
Another question, what is the plan regarding the deprecation-warnings related to the ConstitutiveLaws?

**Comment by loumalouomega** [comment]
First we should update the message. Then check which laws use this methods, then remove from the elements. Then pray

**Comment by philbucher** [comment]
any news here?

**Comment by AlejandroCornejo** [comment]
Okkey! I sincerely forgot about this issue, sorry @philbucher . As far as I've understood, there are two main concerns:

1. Compilation time due to the highly templated CL
1.  Set CL variables in a separated file

The point 1. is the tricky one since it means refactoring everything (quite a work) but it can be done if it's a major improvement
The point 2. it's easy and relatively fast I think.

What are your opinions @loumalouomega @RiccardoRossi @philbucher

**Comment by philbucher** [comment]
about 1. yes ofc this is a large work but I think this will pay of
about 2. as discussed above the idea would be do "decouple" the CLaws more from the elements, i.e. to reduce the dependencies. The intermediate solution would be to have them in a separate shared library and the final goal from how I understood the previous discussions would be to have a separate app for the advanced CLaws and the basic CLaws should be in the Core

@AlejandroCornejo I suggest that once your current PRs are merged we can start by putting the CLaws into a different lib, this wil already mitigate the problems with dependencies and compilation/linking times

**Comment by loumalouomega** [comment]
@philbucher I already tried to separate into a independent library the CL, and I remember the change was not trivial...
