### ISSUE TITLE
[Discussion] Releases codenames

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3881]
Today at the Kratos meeting I suggested to use codenames for the releases, in the same way as Debian for example: https://www.electrictoolbox.com/debian-release-names/

I propose for example using beer names, something that I think people from TUM may agree ;) . Maybe we can do one release with a BCN beer name (there are many small brews in BCN) and one release with a Bavarian beer :D

**Comment by loumalouomega** [comment]
BTW, we can add a Beerware clause to the current BSD-3 license:

https://en.wikipedia.org/wiki/Beerware

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/51338604-8aeb5b80-1a8a-11e9-92f4-a5cbfd88563d.png)

**Comment by philbucher** [comment]
`Kratos version "Augustiner"` :D

or `Kratos version "Erdinger alkoholfrei"` ;) @KlausBSautter (alkoholfrei == alcohol-free)

**Comment by RiccardoRossi** [comment]
+1 for Augustiner

**Comment by riccardotosi** [comment]
Agree with the beer idea :)

**Comment by philbucher** [comment]
Considering that the Kratos Workshop is gonna be in Munich, Augustiner would be a good name :)

**Comment by loumalouomega** [comment]
(There are new emojis in GitHub!!!)

**Comment by marandra** [comment]
Love the idea! Here's my proposal for following version names, based on favorite beers mostly from Catalonia, Bavaria and the US. Cheers.

**Augustiner** | Augustiner Braü | Helles
**Aecht** | Schlenkerla | Rauchbier
**Bitches Brew** | Dogfish Head | Imperial Stout
**Black Tundra** | Laugar | RI Stout
**Carmela** | La Pirata | DIPA
**Catharsis** | Tree House | Porter
**Doppelgänger** | Tree House | IPA
**Downfall** | Garage | NEIPA
**Erdinger** | Erdinger Weissbrau | Dunkel
**Esgarrapats** | Guineu | American IPA
**Fat Tire** | Amber Ale | Amber ale
**Fluoro** | Garage | DIPA
**GoTo** | Stone | IPA
**Heady Topper** | The Alchemist | NEIPA
**Hustle** | Tree House | Porter
**Ichiban** | Kirin | Lager
**Julius** | Tree House | IPA
**Kowtow** | Garage | Brutt IPA
**Lupuluau** | Dogfish Head | IPA
**Lupulus** | La Pirata | IPA
**Midas** | Dogfish Head | Ancient Ale
**Montessori** | Garage | NEIPA
**Namaste** | Dogfish Head | Belgian witbier
**Old Chub** | Oskar Blues | Scottish
**Panoptic** | La Pirata | NEIPA
**Pliny** | Russian River | DIPA
**Quad** | Weyerbacher | IPL
**Ruination** | Stone | DIPA
**Salvator** | Paulaner | Doppelbock
**Sansa** | La Pirata | Amber Ale
**Tap 6** | Schneider Weisse | Weizenbock
**Txiripa** | Guineu | American IPA
**UFO** | Harpoon | Witbier
**Viakrucis** | La Pirata | IPA
**Woozy** | Garage | DNEIPA
**Xocoveza** | Stone | Imperial Stout
**Yeti** | Great Divide | Imperial Stout
**Zombie Dust** | 3 Floyds | Pale Ale

**Comment by loumalouomega** [comment]
Please, I suggest for T Tyris, from Valencia -> https://www.cervezatyris.com/

**Comment by riccardotosi** [comment]
For i I suggest Ichnusa
For p I suggest pedavena, poretti, peroni
For b i suggest moretti (a classic)
For n i suggest nastro azzurro
These are italians

**Comment by loumalouomega** [comment]
I will close this to reduce the number of issues
