### ISSUE TITLE
[MPI] PARTITION_INDEX is a historical double variable

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#3884]
Since we are currently cleaning up MPI-related fetaures of Kratos I think that the following should also be improved:

[`PARTITION_INDEX` is a `double`-Variable](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/variables.h#L143) that is added as a [historical value to the Nodes](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/custom_utilities/parallel_fill_communicator.h#L130)

=> I think it should be an `int` (bcs of MPI) and a non-historical quantity of the Nodes

this is a reminder to change it eventually

**Comment by RiccardoRossi** [comment]
+1 for it being a int.

not 100% sure if we do not want it to be hisotrical (it may help in a repartitioning conetext), however  i don't see this as mandatory

If we go for non historical than i would also consider making it a property of the node rather than a variable (hat would help performancewise)

**Comment by philbucher** [comment]
ok your comment abt repartitioning makes sense, lets keep it in mind

Regarding making it a property of the node, I thought you don't want to make the node-objects any more heavier than it already is?

**Comment by RiccardoRossi** [comment]
the point is that if you store it as GetValue you are actually storing a pointer to the data and the data.
it also has the overhead of a lookup.

storing it as a class member would have minor overhead in this specific case (but we would have to pay it also in the non-mpi case). It would also be faster
In any case i am just tellign that this is an option we might want to consider

**Comment by jcotela** [comment]
I like the idea of storing PARTITION_INDEX in the nodes directly, but any solution not using the "standard" containers has the additional drawback that communicating it across processes would require an additional set of functions for the communicator (SynchonizePartitionIndex, etc.)

**Comment by RiccardoRossi** [comment]
@jcotela you are right, nevertheless it tends to be a constant value. Also that's the kind of thing for which we could take advantage of new global_pointers capabilities

**Comment by philbucher** [comment]
Interesting points
If it should be a nodal-value, then I think the index of the parent-node is known by the ghost-node at the time of partitioning isn't it?
Hence no synchronization would be needed

**Comment by philbucher** [comment]
to add to the discussion that if we do the partitioning in through files (i.e. not in Memory) then we currently the indices are written into the MDPA file [here](https://github.com/KratosMultiphysics/Kratos/blob/06b562de89caa33ad0c3104fa6f2de584ac24990/kratos/sources/model_part_io.cpp#L4263)

AFAIK it is not possible to read non-historical values on nodes from the mdpa

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee 
for now we will only change the datatype from `double` to `int`
We also decided to keep it historical, since it has two pointers less than the non-historical version. Furthermore it might be useful to have the history in remeshing or load balancing
In the future we might think again if maybe we want to move this information to the `Node`
