### ISSUE TITLE
[Discussion] Header file name should be .h or .hpp?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#3897]
I am seeing that everyday there are more *.hpp files, that are in my opinion the proper way to name the files. But for my understanding the right name was *.h. Can we discuss about this?

**Comment by philbucher** [comment]
I thought that header-only could be hpp and header-source could be h/cpp

Seems like there is no common standard, probably we should agree on sth and but it to the style-guide

**Comment by adityaghantasala** [comment]
In a different framework I was following .... Its done like this : 

Any header which has only the function declarations has an extension .h 

Any header which has declarations + definitions has an extension of .hpp 

For me this seems reasonable ....

**Comment by RiccardoRossi** [comment]
we traditionally used .h only.  Do we really need to change this?

**Comment by loumalouomega** [comment]
No, but the lack of consistency is not good marketing for us, we should have standardized practices, in such a way that we don't look like a chaotic project

**Comment by RiccardoRossi** [comment]
One of my favored quotes:

"organize your self ... but not too much!"

i don't know (nor really care) about what is the convention we decide to take, nevertheless i am STRONGLY against the idea of changing this on existing files

**Comment by loumalouomega** [comment]
Well @RiccardoRossi, what I am saying is if we want to appeal as a consistent code we should get rid of these inconsistencies. Probably the clever way to proceed is to change the hpp to h, because the 90% of the headers files are h, and the most important are h (basically Core). The other option is to change one by one the extension of the files.

**Comment by RiccardoRossi** [comment]
as i am telling, i am open for discussion for future files. I am NOT open to changing all the repository

**Comment by roigcarlo** [comment]
For historic reasons the @KratosMultiphysics/technical-committee decided to keep using `*.h` instead of `*.hpp`, as changing all the code will rend the history of most of the core files unavailable.

At the same time we encourage to change the existing `*.hpp` to `*.h`
