### ISSUE TITLE
outdated message in top level CMakeLists.txt file

### ISSUE THREAD

**Issue by qiukailu** [KratosMultiphysics/Kratos#390]
Hi,

This is probably a very very minor issue, but I noticed that in line 45 of the top level CMakeLists.txt file, the message says "additional default options were set for intel compiler". However, it should actually be "for clang compiler". Could someone please update this message to avoid potential confusion? 

Thanks~

~kai

**Comment by loumalouomega** [comment]
I assigned @roigcarlo , sorry if this is not your responsabilty.

**Comment by roigcarlo** [comment]
Np @loumalouomega I take care 👍

**Comment by qiukailu** [comment]
Thanks for the quick fix! 

I am not familiar with the workflow here, should I close this issue myself or someone from the development team will close it? Please advise.

**Comment by loumalouomega** [comment]
Usually the one who started closes the issue and the pull request (with the merge), I can do it for you
