### ISSUE TITLE
[Output] output_frequency

### ISSUE THREAD

**Issue by GuillermoCasas** [KratosMultiphysics/Kratos#3914]
The  time that passes between successive outputs is held in the json variable '**output_frequency**'. I find the name very unfortunate, since it clearly is not used as a frequency (units 1/time) but as a period (units of time). I suspect the difficulty of finding a suitable term guided this final choice. But I still think we could do better.
I do think it is much more intuitive to fix a time interval than a frequency (which would require calculations in most cases) or a number of time steps (one could fix the number of time steps in between prints).
So I propose to discuss possible alternatives (@KratosMultiphysics/implementation-committee ). Here are a few:
- output_period
- output_process_period
- output_time_interval
- time_between_outputs
- time_between_consecutive_outputs
- time_interval_between_consecutive_outputs
- time_interval_between_outputs
Or, my favourite so far:
- output_time_period

**Comment by philbucher** [comment]
related to #3766

**Comment by josep-m-carbonell** [comment]
If the time discretization is given by the variable "**time_step**",  maybe a good name for printing the output is "**output_time_step**"

**Comment by AlejandroCornejo** [comment]
> 
> 
> If the time discretization is given by the variable "**time_step**", maybe a good name for printing the output is "**output_time_step**"

This name I think that it is confusing if your "output_control_type" is "step" for example... Maybe output_period? IDK

**Comment by josep-m-carbonell** [comment]
As confusing as "**time_step**" is. At least is consistent.

**Comment by GuillermoCasas** [comment]
@josep-m-carbonell Yes, I do not know why it did not come to mind. **output_time_step** sounds very good to me and it is consistent in the way you pointed out.

**Comment by GuillermoCasas** [comment]
The @KratosMultiphysics/implementation-committee has come to the following decision concerning this issue:
The name **output_frequency** is definitely not appropriate and it should be changed. There are two possibilities and we could not reach a definitive agreement on which one to follow.

1. Change the name to **output_interval** so that it is neutral to either integers (number of time steps) or doubles (time interval).
2. Create two different variables, so only one of them is used depending on the control parameter (step or time). Their names would be **output_time_interval** and **output_every_n_steps**. This has the advantage of making it clear what the variable means from its name, although it would require a lot more re-coding.

We pass the issue on to the @KratosMultiphysics/technical-committee to decide.

**Comment by philbucher** [comment]
I think I would go for the first option

**Comment by pooyan-dadvand** [comment]
Thanks @KratosMultiphysics/implementation-committee for their clarification. Any opinion from @KratosMultiphysics/interface-committee?

**Comment by dbaumgaertner** [comment]
Speaking for @KratosMultiphysics/interface-committee, I would also vote for the first option above. The reasons is its increased flexibility/usability while reducing overhead implementations through the distinction of two variables which area technically standing for the same thing.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agrees with the decision of the @KratosMultiphysics/implementation-committee and @KratosMultiphysics/interface-committee 

Thanks all!

**Comment by RiccardoRossi** [comment]
this is done, at least concerning the @KratosMultiphysics/technical-committee 

now someone needs to step up to implement it

**Comment by roigcarlo** [comment]
Ping @KratosMultiphysics/implementation-committee Is there anyone doing this?

**Comment by AlejandroCornejo** [comment]
It is assigned to @GuillermoCasas but he has to find time to implement it I think :)
