### ISSUE TITLE
missing images

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#3926]
@adityaghantasala the link

https://github.com/KratosMultiphysics/Kratos/wiki/Applying-periodic-boundary-conditions

has broken images

**Comment by RiccardoRossi** [comment]
also the links to the examples are broken

**Comment by adityaghantasala** [comment]
@RiccardoRossi  sorry ... 
I fixed them now .. !!

**Comment by philbucher** [comment]
images are there now, closing ...
