### ISSUE TITLE
Python import mechanism failing in Python 3.6.1?

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#394]
the mechanism for importing applications seems to be broken in my computer (with Python 3.6.1) but works in @rubenzorrilla's  (Python 3.5.2).

This works correctly in both computers when run from a script:
```
from KratosMultiphysics import *
from KratosFluidDynamicsApplication import *
```
But fails on mine (with the newer python) if I try to run it from an interactive python command prompt. I don't get the `Importing    KratosFluidDynamicsApplication` line, and the application's `python_script` folder does not get added to `sys.path`. I also don't get any kind of error message, which is weird.

Everything works fine on python 3.5.2. I'm not sure if this is something misconfigured on my computer or a bug.

**Comment by ipouplana** [comment]
Just the other day I installed python 3.6.1 under macOS Sierra and, if I remember correctly, I run my tests examples without a problem... Have you tried whether importing modules like this

```
import KratosMultiphysics
import KratosMultiphysics.FluidDynamicsApplication
```

works for you?

**Comment by jcotela** [comment]
It doesn't... It may perfectly be something wrong in my end. Can you confirm that this works from an interactive python shell? (It also works for me if I do it in a script).

**Comment by ipouplana** [comment]
Ok. I cannot confirm it right now, because I don't have the laptop with me... This evening I could try it from the interactive python shell...

**Comment by jcotela** [comment]
Nevermind, the problem was on my end. Closing, thanks for the help.

**Comment by ipouplana** [comment]
You're welcome
