### ISSUE TITLE
Parsing Error and "temporary of non-literal type in constant expressions"

### ISSUE THREAD

**Issue by Glovedsasquatchcodes** [KratosMultiphysics/Kratos#3957]
While trying to configure the example case "MyLaplacianApplication" as instructed on the wiki page of Kratos, I find following errors:
[errors.txt](https://github.com/KratosMultiphysics/Kratos/files/2792911/errors.txt)

Kindly help me understand how should one deal with these.

**Comment by josep-m-carbonell** [comment]
If you look at the error :  a **`>`** is missing

 return Kratos::make_shared<PointSourceCondition`>`(NewId, GetGeometry().Create(ThisNodes), pProperties);

I guess something was wrong during the generation of the application.

**Comment by Glovedsasquatchcodes** [comment]
The error still continues to appear. I am not able to understand what is exactly happening during this function call. Can you also put some insight into that?

**Comment by philbucher** [comment]
I think @roigcarlo recently fixed a bug in the appgenerator, could you pull master and try again?

**Comment by Glovedsasquatchcodes** [comment]
I think with the recent pull, I was successfully able to configure the MyLaplacianApplication. Now proceeding ahead to see if I encounter any further problems in the tutorials.

I have just this another question. On the [page](https://github.com/KratosMultiphysics/Kratos/wiki/Kratos-For-Dummies:-Stationary-heat-transfer), in the section 'Editing the main files of the application and creating elements and conditions' in point 4 it says one needs to compile the kratos. What command should one use to do this? Is it "runkratos MyLaplacianApplication.py" or "python MyLaplacianApplication.py" (in the folder location /applications/MyLaplacianApplication) or something else?

I configured configure.sh and that works. Is that all?

**Comment by jcotela** [comment]
I understand from your log that you are using linux. If it is the case, see the "configure" and "compile" sections on this wiki link: https://github.com/KratosMultiphysics/Kratos/wiki/Linux-Build#configure

Once you have everything set up, re-compilation just requires re-running configure.sh. If you have already done so and the process ends with some message like 
```
Install the project...
[list of installed files in your system]
``` 
then you are done.

**Comment by Glovedsasquatchcodes** [comment]
Perfect. Yeah, I had done it before and the result was as you mentioned. 
Thanks a lot.

**Comment by philbucher** [comment]
closing since I think this is solved.
Please reopen otherwise
