### ISSUE TITLE
BuilderAndSolvers failing when changing the constraints

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#3958]
I have been trying both the block builder and solver and the elimination builder and solver.

I can solve correctly one first time, but if i do something like

1 define constraints
2 solve
3 clear
4 wipe constraints
5 define new constraints
6 solver

i get a failure at the second time in 6. The problem is a bad index in the BuilderAndSolver, which makes me to believe that something is not correctly reinitialized after the clear is called

**Comment by loumalouomega** [comment]
Can you attach the example so I can debug it?

**Comment by adityaghantasala** [comment]
This is strange .. we do exactly the same in Chimera application and it works there ! 

https://github.com/KratosMultiphysics/Kratos/blob/0cf9c2bce32f5fe2e3a57f217a6d5882b962c76b/applications/ChimeraApplication/custom_processes/apply_chimera_process_Monolithic.h#L232

**Comment by loumalouomega** [comment]
> This is strange .. we do exactly the same in Chimera application and it works there !
> 
> [Kratos/applications/ChimeraApplication/custom_processes/apply_chimera_process_Monolithic.h](https://github.com/KratosMultiphysics/Kratos/blob/0cf9c2bce32f5fe2e3a57f217a6d5882b962c76b/applications/ChimeraApplication/custom_processes/apply_chimera_process_Monolithic.h#L232)
> 
> Line 232 in [0cf9c2b](/KratosMultiphysics/Kratos/commit/0cf9c2bce32f5fe2e3a57f217a6d5882b962c76b)
>  mrMainModelPart.RemoveMasterSlaveConstraintFromAllLevels(i);

We found the reason, @RiccardoRossi had not done the PR yet, it is only two lines of code, I can do it myself if you don't mind in approve

**Comment by adityaghantasala** [comment]
So the constraints are not explicitly deleted in step 4 above ??
