### ISSUE TITLE
[GeoProcessing] Proposal of an external application

### ISSUE THREAD

**Issue by swenczowski** [KratosMultiphysics/Kratos#3959]
For the simulation of geophysical flow phenomena, the geometry of the fluid domain has to be derived from geodetic data sets (geodata). A robust and, at the same time, generic processing pipeline provides the first step towards this goal. Following the philosophy of KratosMultiphysics, the pipeline will be  constructed of individual and case-specifically exchangeable modules.

To facilitate the collaboration in the development of such a pipeline, we suggest to establish a repository for an external application named “GeoProcessor”. In this scope, the following modular components shall be summarized.

- Preprocessors (application specific) for geodata files		: “GeoPreprocessor”	
- Parsers for different formats of geodata	: 			“GeoImporter”
- Meshing applications (with specific variants)			: 			“GeoMesher”
- Integration of the built environment : "GeoBuildingIntegrator"
- Preparation of the model for use in KratosMultipyhsics	: 	“GeoModelCreator”

Though KratosMultiphysics was searched for possible alternatives, a number of additional external Python libraries is required. At the current state of the development, the following libraries are used:

- scipy
- numpy
- triangle (*)
- meshpy (*)
- pygal (*)

The last three of these libraries (*) could be replaced by using PyMesh. In the current development state, technical problems in the installation forbid the usage of the PyMesh library. Though the already created code is purely written in Python, more computationally intensive tasks may be implemented in C++.

We hope that we could give a first impression of the suggested external application. Thank you for sharing your opinion on the suggested idea. In case of further questions, we are available at your convenience.

Best regards, Nicola Germano (@NicolaGermano) and Simon Wenczowski (@swenczowski)

![Diagram of Workflow](https://user-images.githubusercontent.com/45034120/51740246-c641e780-2093-11e9-9e8a-edf36531ea1f.png)

**Comment by rubenzorrilla** [comment]
@swenczowski @NicolaGermano first of all I would like to thank you for such a nice explanation. However, I'd like to say that I'm much more in favour of creating a new application than of creating a new repository.

Concerning your design proposal, I guess that each one of the pink boxes will be one family of classes. I also guess that those classes will be called by a Python script that implements step by step the work flow you are proposing (which also makes sense to me).

Concerning the inclusion of scipy and numpy modules, can you list the feature you require from them?

**Comment by swenczowski** [comment]
Thank you very much for your feedback and the suggestion. If no legal aspects (concerning licenses) forbid to declare it an application, this approach would also be perfect from our position.

Exactly, the final workflow will be "assembled" out of the modules in a python script. Also, the rough idea concerning the structure of the classes is correct. At the current development stage, however, we could not yet fix a particular structure - work will continue here.

The following features / functionalities of the modules are used (so far):
- `numpy`: array (hardest to avoid), arange, vstack, sin(), cos(), pi()
- `scipy.spatial`: KDTree (for the terrain smoothing)

**Comment by rubenzorrilla** [comment]
> Thank you very much for your feedback and the suggestion. If no legal aspects (concerning licenses) forbid to declare it an application, this approach would also be perfect from our position.
> 
> Exactly, the final workflow will be "assembled" out of the modules in a python script. Also, the rough idea concerning the structure of the classes is correct. At the current development stage, however, we could not yet fix a particular structure - work will continue here.
> 
> The following features / functionalities of the modules are used (so far):
> 
>     * `numpy`: array (hardest to avoid), arange, vstack, sin(), cos(), pi()

- array: Why don't you use the Kratos Vector instead? 
- sin(), cos(), pi()... : You can use `math` module, which is always available
- concerning arange and vstack, It should be possible to reimplement what you have done (maybe in c++) to avoid them

> 
>     * `scipy.spatial`: KDTree (for the terrain smoothing)

If I'm not wrong, Kratos already have a KDTree, so we can use that one.

**Comment by pooyan-dadvand** [comment]
Very nice explanation! Thanks! I would also support the idea of @rubenzorrilla about having an application rather than the separate repository which simplifies considerably the maintenance   

About the design I have some comments:
* I am not sure if the Integrator should go before meshing rather than after it
* I would suggest to design each part in a modular way considering a generic use of it in other parts of the Kratos (examples: converting XYZ file to surface mesh, stl to surface mesh, remeshing by distance function, etc...)
* triangle is integrated in Kratos. It would be better to reuse it.
* I would suggest to use Kratos vector instead of numpy array when is possible to be more compatible with the rest of the Kratos.
* We have a kdtree in Kratos but no smoothing algorithm is build over it.
* If triangle works for you I would avoid the pyMesh and pygal libraries. They give more headache in maintaining the code and installation procedure.

**Comment by philbucher** [comment]
what is the status of this?

**Comment by rubenzorrilla** [comment]
I think that @NicolaGermano is still working on it. @NicolaGermano can you confirm?

**Comment by NicolaGermano** [comment]
Yes yes. I confirm that I'm working on this

**Comment by loumalouomega** [comment]
@NicolaGermano did your problem of coloring persists?

**Comment by NicolaGermano** [comment]
I opened an issue ([#5237](https://github.com/KratosMultiphysics/Kratos/issues/5237)) about this

**Comment by rubenzorrilla** [comment]
Which is the status of this? @NicolaGermano would be nice to have the application in the master branch although there are still pending tasks.

**Comment by NicolaGermano** [comment]
Something still needs to be completed but I can start to upload the complete things to the master.

**Comment by adityaghantasala** [comment]
@NicolaGermano  is the dependency on pyMesh and pygal now removed ?

**Comment by NicolaGermano** [comment]
Yes, there are no such dependencies

**Comment by rubenzorrilla** [comment]
@uxuech pinging you as this might be of your interest. Closing as it has been inactive for almost one year. Feel free to reopen if required.
