### ISSUE TITLE
POINT_MOMENT variable is defined multiple times in different applications

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#398]
Dear all, 
just detected that variable POINT_MOMENT is duplicated in 
* PfemSolidMechanics
* StructuralMechanics
* SolidMechanics

This is even most dangerous as the StructuralMechanics variants in exported, making it visible to everyone.

Compilation problems appear in windows and this is most certainly causing memory problems.

@KratosMultiphysics/pfem 
@KratosMultiphysics/structural-mechanics 

It should be moved to the core or use different names.

**Comment by loumalouomega** [comment]
We solved this issue with the new structural
