### ISSUE TITLE
problem when compiling kratos in windows 10

### ISSUE THREAD

**Issue by Rhapneo** [KratosMultiphysics/Kratos#3981]
This is the message I get when I run configure.bat

D:\Programas\KratosMultiphysics\cmake_build>cmake -G "Visual Studio 15 2017 Win64"  -DPYTHON_INCLUDE_PATH="C:\Python33\include"  -DPYTHON_LIBRARY="C:\Python33\libs\python33.lib"  -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=" -D_SCL_SECURE_NO_WARNINGS "  -DLAPACK_LIBRARIES="D:\Programas\KratosMultiphysics\external_libraries\liblapack.lib"  -DBLAS_LIBRARIES="D:\Programas\KratosMultiphysics\external_libraries\libblas.lib"  -DBOOST_ROOT:PATH="D:\Programas\KratosMultiphysics\external_libraries\boost_1_55_0"  -DINCOMPRESSIBLE_FLUID_APPLICATION=ON  -DMESHING_APPLICATION=ON  -DEXTERNAL_SOLVERS_APPLICATION=ON  -DPFEM_APPLICATION=ON  -DSTRUCTURAL_APPLICATION=ON  -DCONVECTION_DIFFUSION_APPLICATION=ON  -DFLUID_DYNAMICS_APPLICATION=ON  -DALE_APPLICATION=ON  -DFSI_APPLICATION=ON  -DDEM_APPLICATION=OFF  -DSWIMMING_DEM_APPLICATION=OFF  -DKRATOS_INSTALL_PREFIX:PATH="D:\Programas\KratosMultiphysics"  -DINSTALL_PYTHON_FILES=ON  -DINSTALL_EMBEDDED_PYTHON=ON  -DEXCLUDE_ITSOL=ON  -DSOLID_MECHANICS_APPLICATION=ON  ..
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.16.27026.1
-- The CXX compiler identification is MSVC 19.16.27026.1
-- Check for working C compiler: D:/Programas/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: D:/Programas/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Programas/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: D:/Programas/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Subversion: C:/Program Files (x86)/Subversion/bin/svn.exe (found version "1.8.0")
detected compiler as MSVC14
KRATOS_EXCLUDE_OPENMP
OpenMP included
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
CMake Error at C:/Program Files/CMake/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.55.0

  Boost include path:
  D:/Programas/KratosMultiphysics/external_libraries/boost_1_55_0

  Could not find the following Boost libraries:

          boost_python

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:144 (find_package)

-- Found PythonLibs: C:/Python33/libs/python33.lib (found version "3.3.4")
-- Found BLAS: D:\Programas\KratosMultiphysics\external_libraries\libblas.lib
linker flags with blas =
BLA_VENDOR = All
-- Found BLAS: D:/Programas/KratosMultiphysics/external_libraries/libblas.lib
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- A library with LAPACK API found.
LAPACK = D:\Programas\KratosMultiphysics\external_libraries\liblapack.lib
LAPACK modified = D:/Programas/KratosMultiphysics/external_libraries/liblapack.lib

CMAKE_BUILD_TYPE ........ Release

-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found

INCOMPRESSIBLE_FLUID_APPLICATION ... ON
MESHING_APPLICATION ................ ON
EXTERNAL_SOLVERS_APPLICATION........ ON
PFEM_APPLICATION.................... ON
STRUCTURAL_APPLICATION.............. ON
STRUCTURAL_MECHANICS_APPLICATION....
CONVECTION_DIFFUSION_APPLICATION.... ON
SOLID_MECHANICS_APPLICATION......... ON
PFEM_BASE_APPLICATION...............
PFEM_SOLID_MECHANICS_APPLICATION....
MACHINING_APPLICATION...............
FLUID_DYNAMICS_APPLICATION.......... ON
PFEM_FLUID_DYNAMICS_APPLICATION.....
STRING_DYNAMICS_APPLICATION.........
ALE_APPLICATION..................... ON
FSI_APPLICATION..................... ON
EMPIRE_APPLICATION..................
MIXED_ELEMENT_APPLICATION...........
DEM_APPLICATION..................... OFF
SWIMMING_DEM_APPLICATION............ OFF
CONSTITUTIVE_LAWS_APPLICATION.......
THERMO_MECHANICAL_APPLICATION.......
OPENCL_APPLICATION..................
MKL_SOLVERS_APPLICATION.............
MPI_SEARCH_APPLICATION..............
METIS_APPLICATION...................
TRILINOS_APPLICATION................
TURBULENT_FLOW_APPLICATION..........
BLOOD_FLOW_APPLICATION..............
PURE_DIFFUSION_APPLICATION..........
MESHLESS_APPLICATION................
WIND_TURBINE_APPLICATION ...........
CLICK2CAST_APPLICATION .............
MULTISCALE_APPLICATION .............
PFEM2_APPLICATION...................
FREEZING_SOIL_APPLICATION...........
ADJOINT_FLUID_APPLICATION...........
POROMECHANICS_APPLICATION...........
PARTICLE_MECHANICS_APPLICATION......
FORMING_APPLICATION.................
DAM_APPLICATION.....................
SHAPE_OPTIMIZATION_APPLICATION......
TOPOLOGY_OPTIMIZATION_APPLICATION...
MY_LAPLACIAN_APPLICATION............
LAGRANGIAN_MPM_APPLICATION..........
CONTACT_MECHANICS_APPLICATION.......
CONTACT_STRUCTURAL_MECHANICS_APPLICATION.......
MAPPING_APPLICATION.................
CONSTITUTIVE_MODELS_APPLICATION.....

**** configuring KratosIncompressibleFluidApplication ****
**** configuring KratosMeshingApplication ****
**** configuring KratosExternalSolversApplication ****
**** configuring KratosPFEMApplication ****
**** configuring KratosStructuralApplication ****
**** configuring KratosConvectionDiffusionApplication ****
**** configuring KratosFluidDynamicsApplication ****
**** configuring KratosALEApplication ****
**** configuring KratosFSIApplication ****
**** configuring KratosSolidMechanicsApplication ****
python libraries to be installed are: C:/Python33/libs/python33.lib
-------------------------------- user defined install dir D:/Programas/KratosMultiphysics
boost python lib used = Boost_PYTHON_LIBRARY_RELEASE-NOTFOUND
installed blas = D:/Programas/KratosMultiphysics/external_libraries/libblas.lib
installed lapack = D:/Programas/KratosMultiphysics/external_libraries/liblapack.lib
-- Configuring incomplete, errors occurred!
See also "D:/Programas/KratosMultiphysics/cmake_build/CMakeFiles/CMakeOutput.log".
See also "D:/Programas/KratosMultiphysics/cmake_build/CMakeFiles/CMakeError.log".

**### This is the configure used.**

del CMakeCache.txt
:: this is an example file...please DO NOT MODIFY if you don't want to do it for everyone
:: to use it, copy it to another file and run it

cls

:: you may want to decomment this the first time you compile
del CMakeCache.txt

cmake -G "Visual Studio 15 2017 Win64" ^
 -DPYTHON_INCLUDE_PATH="C:\Python33\include" ^
 -DPYTHON_LIBRARY="C:\Python33\libs\python33.lib" ^
 -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=" -D_SCL_SECURE_NO_WARNINGS " ^
 -DLAPACK_LIBRARIES="D:\Programas\KratosMultiphysics\external_libraries\liblapack.lib" ^
 -DBLAS_LIBRARIES="D:\Programas\KratosMultiphysics\external_libraries\libblas.lib" ^
 -DBOOST_ROOT:PATH="D:\Programas\KratosMultiphysics\external_libraries\boost_1_55_0" ^
 -DINCOMPRESSIBLE_FLUID_APPLICATION=ON ^
 -DMESHING_APPLICATION=ON ^
 -DEXTERNAL_SOLVERS_APPLICATION=ON ^
 -DPFEM_APPLICATION=ON ^
 -DSTRUCTURAL_APPLICATION=ON ^
 -DCONVECTION_DIFFUSION_APPLICATION=ON ^
 -DFLUID_DYNAMICS_APPLICATION=ON ^
 -DALE_APPLICATION=ON ^
 -DFSI_APPLICATION=ON ^
 -DDEM_APPLICATION=OFF ^
 -DSWIMMING_DEM_APPLICATION=OFF ^
 -DKRATOS_INSTALL_PREFIX:PATH="D:\Programas\KratosMultiphysics" ^
 -DINSTALL_PYTHON_FILES=ON ^
 -DINSTALL_EMBEDDED_PYTHON=ON ^
 -DEXCLUDE_ITSOL=ON ^
 -DSOLID_MECHANICS_APPLICATION=ON ^
 ..

BR

**Comment by Rhapneo** [comment]
@loumalouomega @AlejandroCornejo

**Comment by loumalouomega** [comment]
Better @roigcarlo

**Comment by roigcarlo** [comment]
Dear @Rhapneo,

The error you posted means that boost is not found. Please make sure that the variable
```
-DBOOST_ROOT:PATH="D:\Programas\KratosMultiphysics\external_libraries\boost_1_55_0" ^
```
Is pointing to a valid boost folder.

**Comment by Rhapneo** [comment]
Dear @roigcarlo 
Yes. even try different versions of boost. but still giving the same error
![problema](https://user-images.githubusercontent.com/47089146/51868059-11216080-231b-11e9-9699-0fa7bae7b33b.png)
BR

**Comment by roigcarlo** [comment]
Dear @Rhapneo 

Notice that the version in the configuration file is 1.55, but according to the screen you have 1.67, so you must change your configure with this:

```
-DBOOST_ROOT:PATH="D:\Programas\KratosMultiphysics\external_libraries\boost_1_67_0" ^
```

Please let me know if it works.

**Comment by Rhapneo** [comment]
Yes. i try , with versions 1.55, 1.67 and 1.69, anyone work.

**Comment by roigcarlo** [comment]
Mm im not sure to follow, did it work?

You can use any boost version you want, but you must ensure that the BOOST_ROOT path matches the folder.

I've generated a configuration for you that should work for 1.67. You can find it herem just copy paste it:
https://pastebin.com/RiMmb2Fi

**Comment by Rhapneo** [comment]
I'm sorry, I told you, that I tried several versions of boost. V 1.55, V 1.67 V 1.69 and no version worked
Obviously change the configure.bat file for each version

**Comment by roigcarlo** [comment]
Hi @Rhapneo 

Are you using an updated version of kratos? I didn't realized it the first time I look but the problem seems to be specifically of `boost_python`. We drop the support for this almost a year ago.

**Comment by Rhapneo** [comment]
Hi @roigcarlo 

**I downloaded a version of Kratos. The error has changed. Now show this:**

D:\Programas\Kratos-master\cmake_build>cmake -G "Visual Studio 15 2017 Win64"  -DPYTHON_INCLUDE_PATH="C:\Python33\include"  -DPYTHON_LIBRARY="C:\Python33\libs"  -DPYTHON_EXECUTABLE="C:\Python33\python.exe"  -DCMAKE_BUILD_TYPE=Release  -DCMAKE_CXX_FLAGS=" -D_SCL_SECURE_NO_WARNINGS "  -DLAPACK_LIBRARIES="D:\Programas\KratosMultiphysics\external_libraries\liblapack.lib"  -DBLAS_LIBRARIES="D:\Programas\KratosMultiphysics\external_libraries\libblas.lib"  -DBOOST_ROOT:PATH="D:\Programas\KratosMultiphysics\external_libraries\boost_1_67_0"  -DINCOMPRESSIBLE_FLUID_APPLICATION=Off  -DMESHING_APPLICATION=ON  -DEXTERNAL_SOLVERS_APPLICATION=ON  -DPFEM_APPLICATION=ON  -DSTRUCTURAL_APPLICATION=OFF  -DCONVECTION_DIFFUSION_APPLICATION=OFF  -DFLUID_DYNAMICS_APPLICATION=OFF  -DALE_APPLICATION=ON  -DFSI_APPLICATION=ON  -DDEM_APPLICATION=OFF  -DSWIMMING_DEM_APPLICATION=OFF  -DKRATOS_INSTALL_PREFIX:PATH="D:\Programas\KratosMultiphysics"  -DINSTALL_PYTHON_FILES=ON  -DINSTALL_EMBEDDED_PYTHON=ON  -DEXCLUDE_ITSOL=ON  -DSOLID_MECHANICS_APPLICATION=ON  ..
-- Selecting Windows SDK version 10.0.17763.0 to target Windows 10.0.17134.
-- The C compiler identification is MSVC 19.16.27026.1
-- The CXX compiler identification is MSVC 19.16.27026.1
-- Check for working C compiler: D:/Programas/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working C compiler: D:/Programas/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: D:/Programas/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe
-- Check for working CXX compiler: D:/Programas/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/Hostx86/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:8 (cmake_policy):
  The OLD behavior for policy CMP0054 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


-- Could NOT find Git (missing: GIT_EXECUTABLE)
Git was not found on your system. SHA1 number will be set to 0.
Detected compiler as MSVC
KRATOS_BUILD_TESTING not defined. Setting to ON
-- Found PythonInterp: C:/Python33/python.exe (found version "3.3.4")
-- Found PythonLibs: C:/Python33/libs/Python33.lib
KRATOS_EXCLUDE_OPENMP
OpenMP included
-- Found OpenMP_C: -openmp (found version "2.0")
-- Found OpenMP_CXX: -openmp (found version "2.0")
-- Found OpenMP: TRUE (found version "2.0")
-- Boost version: 1.67.0
Boost Include: D:/Programas/KratosMultiphysics/external_libraries/boost_1_67_0
Boost Linkdir:
-- Found BLAS: D:\Programas\KratosMultiphysics\external_libraries\libblas.lib
linker flags with blas =
BLA_VENDOR = All
-- Found BLAS: D:/Programas/KratosMultiphysics/external_libraries/libblas.lib
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- A library with LAPACK API found.
LAPACK = D:\Programas\KratosMultiphysics\external_libraries\liblapack.lib
LAPACK modified = D:/Programas/KratosMultiphysics/external_libraries/liblapack.lib
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Preparing local ZLIB compilation.
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - failed
-- Looking for fseeko
-- Looking for fseeko - not found
-- Looking for unistd.h
-- Looking for unistd.h - not found
**AMatrix not found. Please define the AMATRIX_DIR pointing to the AMatrix root directory.**

CMAKE_BUILD_TYPE ........ Release

WARNING: YOUR GIDPOST IS BEING COMPILED  WITHOUT DEBUG (ALL ASSERTS WILL BE AVOIDED)
-- Performing Test HAS_MSVC_GL_LTCG
-- Performing Test HAS_MSVC_GL_LTCG - Success
-- LTO enabled


***** LIST OF KRATOS APPLICATIONS THAT ARE GOING TO BE COMPILED: *****

                SOLID_MECHANICS_APPLICATION - ON
                FSI_APPLICATION - ON
                PFEM_APPLICATION - ON
                EXTERNAL_SOLVERS_APPLICATION - ON
                MESHING_APPLICATION - ON

**********************************************************************

****** LIST OF KRATOS APPLICATIONS THAT ARE SET TO OFF: **************

                CONVECTION_DIFFUSION_APPLICATION - OFF
                STRUCTURAL_APPLICATION - OFF
                FLUID_DYNAMICS_APPLICATION - OFF
                DEM_APPLICATION - OFF
                SWIMMING_DEM_APPLICATION - OFF

**********************************************************************


**** configuring KratosExternalSolversApplication ****
**** configuring KratosSolidMechanicsApplication ****
CMake Error at applications/SolidMechanicsApplication/CMakeLists.txt:12 (message):
  The ConsitutiveModelsApplication must be compiled before this one.  Set
  CONSTITUTIVE_MODELS_APPLICATION=ON in the configure file.


**** configuring KratosPfemApplication ****
CMake Error at applications/PfemApplication/CMakeLists.txt:16 (message):
  The Delaunay Meshing Application must be compiled before this one.  Set
  DELAUNAY_MESHING_APPLICATION=ON in the configure file.


**** configuring KratosMeshingApplication ****
**** configuring KratosFSIApplication ****
*****************************************************************************-------------******** D:/Programas/Kratos-master/external_libraries/triangle
python libraries to be installed are: C:/Python33/libs/python33.lib
-------------------------------- user defined install dir D:/Programas/KratosMultiphysics
installed blas = D:/Programas/KratosMultiphysics/external_libraries/libblas.lib
installed lapack = D:/Programas/KratosMultiphysics/external_libraries/liblapack.lib
-- Configuring incomplete, errors occurred!
See also "D:/Programas/Kratos-master/cmake_build/CMakeFiles/CMakeOutput.log".
See also "D:/Programas/Kratos-master/cmake_build/CMakeFiles/CMakeError.log".

**Comment by philbucher** [comment]
check the error cmake is giving you:
~~~
CMake Error at applications/SolidMechanicsApplication/CMakeLists.txt:12 (message):
The ConsitutiveModelsApplication must be compiled before this one. Set
CONSTITUTIVE_MODELS_APPLICATION=ON in the configure file.

**** configuring KratosPfemApplication ****
CMake Error at applications/PfemApplication/CMakeLists.txt:16 (message):
The Delaunay Meshing Application must be compiled before this one. Set
DELAUNAY_MESHING_APPLICATION=ON in the configure file.
~~~

the applications you want to compile have some dependencies on other applications => you need to compile all of them

**Comment by Rhapneo** [comment]
I managed to compile (I think without error), I executed the visual studio file. The executable runkratos.exe was created. but when I double click, it does not do anything
![problema](https://user-images.githubusercontent.com/47089146/51945793-a0974400-23ed-11e9-9bb9-8e5371068e9b.png)

**Comment by roigcarlo** [comment]
Hi @Rhapneo, you cannot run directly the runkratos by double-click only as its needs a main script to execute.

If you look at this section: https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install#test-and-usage you can find the basic usage.
