### ISSUE TITLE
[Adjoint] What are the boundary conditions that correspond to the adjoint problem?

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#3997]
(I am not sure if I tagged the correct people, sorry if I am missing part of the team or if I included someone not related to the topic!)

Dear all,

I am currently tying to adapt your adjoint analysis scheme and gradient computation from the StructuralMechanicsApplication to the CompressiblePotentialFlowApplication, in order to obtain the gradient of the lift with respect to the geometry parameters. I am developing it in[ this branch.](https://github.com/KratosMultiphysics/Kratos/tree/CompressiblePotentialFlow/feature-embedded-mesh-implementation/applications/CompressiblePotentialFlowApplication) In the following days/weeks, I would like to discuss with some of you the exact implementation of the utilities, schemes, etc, to check that I am using everything as it is intended. However, this issue is about how to deal with the boundary conditions in the adjoint problem.

As of now, I am imposing the **same** boundary conditions in the adjoint problem as in the primal problem, which are:
![image](https://user-images.githubusercontent.com/32136457/51891507-a82ffc00-239f-11e9-94e5-4fe5592005f4.png)
![image](https://user-images.githubusercontent.com/32136457/51891521-ad8d4680-239f-11e9-8942-e69c024bbaef.png)

In summary, these are: Dirchlet conditon at the inlet, No-Slip condition at the walls, a Neuman condition at the Outlet, and the Wake Boundary conditions, where two constraints for the gradient of the potential are imposed.

As for the dirichlet condition at the inlet, I am imposing a certain value of potential (and adjoint_potential)  and fixing those degrees of freedom for both the primal problem and the adjoint problem.

As for the wake boundary conditions, these are included in the element formulation, meaning that the elements of the wake already have these constraints in their LeftHandSideMatrix. In the adjoint problem these constraints are kept (since we use the LHS/RHS from the primal problem).

- Is this correct? Are the boundary conditions in the adjoint problem the same as in the primal problem? Or a different approach should be considered?

Thanks in advance!

Regards

**Comment by inigolcanalejo** [comment]
As far as I know for the adjoint problem one applies homogeneous Dirichlet.

**Comment by dbaumgaertner** [comment]
I don't know the situation for the above problem and therefore cannot readily comment on whether your approach is correct in this case. Just a general comment.

The first thing you might want to ask yourself is, whether you want to follow a discrete, a continuous or even a hybrid adjoint approach as this has a major impact on the resulting adjoint problem setup. A good source to get a feeling for where the adjoint boundary conditions come from and how they look can be found [here](https://searchworks.stanford.edu/view/10608073). It discusses the case of compressible flows using RANS and the continuous adjoint approach.

From the above I suspect you are heading for such a continuous adjoint approach. In this case Dirichlet, No-Slip and Neumann conditions are equivalently present in the adjoint problem. Obviously with different values, though. The wake boundary conditions, I don't know.  

Hope this helps a bit.

Best regards

**Comment by RiccardoRossi** [comment]
@dbaumgaertner we are using a discrete adjoint approach
