### ISSUE TITLE
Node search with changing node position

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#400]
Hi all,

when I create a search three in the form:

`for (ModelPart::NodesContainerType::iterator node_it = mrModelPart.NodesBegin(); node_it != mrModelPart.NodesEnd(); ++node_it)`
`        {`
`            NodeTypePointer pnode = *(node_it.base());`
`            mListOfNodes.push_back(pnode);`
`        }`

`mpSearchTree = boost::shared_ptr<KDTree>(new KDTree(mListOfNodes.begin(), mListOfNodes.end(), mBucketSize));`

and for some reason, the coordinates of the nodes in the listofNodes change. Will the following spatial searches work on the updated nodes or the old ones?

Thanks already in advance.

Cheers,
Daniel

**Comment by RiccardoRossi** [comment]
Hi Daniel,
      the search tree is formed in the constructor, and it is **not** updated dynamically.

if you change the position you'll have to reform the tree

cheers
Riccardo

**Comment by dbaumgaertner** [comment]
Thanks, Riccardo! Maybe another in this context:

Why is it necessary to specify a maximal number of neighbor nodes, when I perform "mpSearchTree->SearchInRadius(...,maxNeighborNodes)"? Is there no way to avoid such a specification?

cheers,
Daniel

**Comment by RiccardoRossi** [comment]
Hi Daniel,

the point is that you must allocate a vector for the output... and here you are tellign the size of that vector.

i am afraid there is no way around

**Comment by dbaumgaertner** [comment]
Alright. Thanks a lot! I thought there is maybe some automatic resizing but I guess this is not feasible for large cases.
