### ISSUE TITLE
strange behaviour when running with periodicity + jump condition

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#4011]
Hi @adityaghantasala @loumalouomega 

i have been implementing boundary conditions for RVE calculation.

essentially the boundary condition is set to be $uslave = umaster + eps*(xslave-xmaster)$

you can find the implementation in the branch "RVE_periodic".

We have two problems here:
1 - using the Block version, the constraints appear to be applied correctly, HOWEVER the solution is not the correct one. With this i mean that if i start from the solution u=eps_tensor*x it is a solution that fulfills periodicity and equilibrium and is hence the (unique solution). Nevertheless the code moves away from that. This looks like a problem in equilibrium and i think it depends on the implementation
2 - using "non-block" version it directly does not impose the jump condition. @loumalouomega i appreciate that you don't have time to look into this now, however i think it is important to report the bug.

the attached test includes a minimal example (with a lot of debugging output) which can be used to verify what i am saying

[smallest_test.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/2812084/smallest_test.gid.zip)

**Comment by loumalouomega** [comment]
Riccardo I don't understand your condition $uslave = umaster + eps*(xslave-xmaster)$. Umaster means that the dof relation is 1, and eps * (xslave-xmaster) is the constant, which you calculate previously

**Comment by RiccardoRossi** [comment]
what i mean is that the displacement of the slave = displacement of the master + a constant.

the constant is applied by me and it is applied correctly.

**Comment by RiccardoRossi** [comment]
@loumalouomega i confirm that as we saw together it works correctly with the elimination builder and solver

@adityaghantasala unfortunately i do get wrong results with the block implementation

**Comment by adityaghantasala** [comment]
so it is possible to include a constant with elimination builder and solver ?
Does the setup need any modifications to work correctly with elimination builder and solver ?

**Comment by adityaghantasala** [comment]
@RiccardoRossi @loumalouomega  I am trying to run the test posted by Riccardo. But I get errors. I cannot run the case as it requires the RVEPeriodicityUtility . If this has changed, can you please update the test ?

**Comment by adityaghantasala** [comment]
ping !

**Comment by philbucher** [comment]
this is solved isn't it?

**Comment by philbucher** [comment]
closing since I believe this was loved in the meantime
