### ISSUE TITLE
HDF5 failing in windows

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#4012]
Hi @armingeiser one of my student reported that HDF5 tests fail in windows. is that so?

**Comment by armingeiser** [comment]
Yes that is true.
The cpp tests are "hard coded" for a certain file driver mode, that is not available in windows.
@msandre probably knows the details about it, as he implemented the application.

**Comment by RiccardoRossi** [comment]
if this is so, than maybe we should mark them as known failure or something of the sort...

**Comment by armingeiser** [comment]
:+1: , BTW, I think the HDF5 application was not really used in windows until now.

**Comment by msandre** [comment]
I suggest first trying

```
    Parameters file_params(R"(
        {
            "file_name" : "test.h5",
#if (defined(_WIN32) || defined(_WIN64))
            "file_driver":  "windows",
            "file_access_mode" : "truncate"
#else
            "file_driver": "core"
#endif
        })");
```

at the bottom of test_utils.cpp. My problem is I don't have a windows installation.

**Comment by philbucher** [comment]
@RiccardoRossi did you test the suggestion of @msandre ?

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by philbucher** [comment]
closing since inactive
