### ISSUE TITLE
[Core] Sphere

### ISSUE THREAD

**Issue by GuillermoCasas** [KratosMultiphysics/Kratos#4047]
I would like to implement GetVolume() and other similar functions in the sphere geometry [https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/geometries/sphere_3d_1.h](url). The problem is that this geometry has no knowledge of its radius. There are two aspects to be discussed, with several options:

Access-related
1. We could implement GetDiameter() (or GetRadius()) in the base geometry
2. Or else we could re-use an existing function such as Circumradius() (I think this is uglier)

Memory-related
1. We can either store the diameter in the sphere itself
2. We can hard-code the necessity of the sphere's node to have the variable RADIUS (or DIAMETER) added and hope that that quantity represents the size of the sphere.

I would like to discuss this issue, because the users of sphere_3d such as DEMApplication or SwimmingDEMApplication are not able to take advantage of the geometry at all as it is now. Is it really that difficult to move to a more general notion of geoemtry? This question (related to #3737) has been raised in the past to @RiccardoRossi and others. I refer it to the @KratosMultiphysics/implementation-committee.

**Comment by loumalouomega** [comment]
Geometries cannot access right now to values, the values are stored in nodes (the class geometry can be defined by point or nodes, so this is not an option) or in the element/condition. The @KratosMultiphysics/design-committee agreed to move the data value container from the element/condition to the geometry, this is not available for the moment, so not an option.

What I see is that the method Get/SetRadius can be defined in the base geometry, doing nothing in the base geometry, but you can add a member variable in the Sphere mRadius that can be accesed through this methods in the derived class.

**Comment by loumalouomega** [comment]
By the way, the method Volume already exists

**Comment by GuillermoCasas** [comment]
@loumalouomega: about your comments:

 > By the way, the method Volume already exists

 Yes, but there is no implementation for sphere.

> the method Get/SetRadius can be defined in the base 

Yes, but I am accessing the generic geometry through GetGeometry(). It is not desirable to force the geometry to be a sphere since it is not always a sphere what we have.

**Comment by roigcarlo** [comment]
I also like the idea of having the `Radius()`/`Diameter()` functions defined in the base (I would use them myself in the future) as a property like `Volume()`, `Area()`, etc... As for how implement it, can be done as @loumalouomega suggests. Something like:

```C++
/* geometry.h */
virtual double Radius() const {
    KRATOS_ERROR << "Calling base class 'Radius' method instead of derived class one. Please check the definition of derived class. " << *this << std::endl;
    return 0.0;
    // Or even return Circumradius();
}
```

```C++
/* sphere_3d_1.h */
virtual double Radius() const {
    return mRadius
}
```

> Yes, but there is no implementation for sphere.

There are very few (if any) of these methods that are implemented for generic geometries.

**Comment by GuillermoCasas** [comment]
@KratosMultiphysics/implementation-committee, you can follow (and comment) on the corresponding developments I am making on this issue [here](https://github.com/KratosMultiphysics/Kratos/compare/core/adding-getradius-to-base-geometry).

**Comment by loumalouomega** [comment]
For the copy constructors do:

~~~
    Sphere3D1( Sphere3D1 const& rOther )
        : BaseType( rOther ),
		  mpRadius(rOther.mpRadius)
    {
    }
~~~

instead of:

~~~
    Sphere3D1( Sphere3D1 const& rOther )
        : BaseType( rOther )
    {
        mpRadius = rOther.mpRadius;
    }
~~~

**Comment by loumalouomega** [comment]
Replace the std::cout by KRATOS_WARNING("Sphere3D1")

**Comment by loumalouomega** [comment]
That's all

**Comment by pablobecker** [comment]
ping @KratosMultiphysics/technical-committee

**Comment by AlejandroCornejo** [comment]
This issue has become stale. the @KratosMultiphysics/implementation-committee thinks that the course of action should be one of the following two options:

    1. Tag the issue as "Limbo" and remove from the TODO list of @KratosMultiphysics/implementation-committee 
    2. Accept the basic content

**Comment by AlejandroCornejo** [comment]
We are closing this issue since it has become stale for too long
