### ISSUE TITLE
Error when changing deprecated names of 'Preconditioners'

### ISSUE THREAD

**Issue by djvicente** [KratosMultiphysics/Kratos#4048]
Hi @philbucher 
In Issue #3966 I have found an error when using deprecated "preconditioner_type" names. I have realized running one of my cases of the DamApplication.
In line 121, of the file 'python_linear_solver_factory.py', it seems that there is a lack of the command .GetString() at the end of the line.
I have run again my case with the following command and it works well.
> preconditioner_type = config["preconditioner_type"].GetString()

I hope this will help. Regards,
David J. Vicente

**Comment by philbucher** [comment]
thanks for spotting, fixed in #4049

**Comment by djvicente** [comment]
You're welcome
