### ISSUE TITLE
Adjoints become unstable after modifications to block builder and solver

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#407]
A simulation of fluid adjoints set up and computed in February was recently recomputed. The fluid solution appears the same in both cases, but the recomputed adjoints are unstable in time. This problem occurs despite all adjoint tests passing (the adjoint tests only compute a few time steps). The change that triggered this behavior can be seen by running git diff 9a95d2ae06915257bd39aa3319a48ed29aa650d5 a24ee26b9ba649a17cb50ec33d17b79ac6648b7c kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h. It has something to do with the new openmp directives in Build().

**Comment by loumalouomega** [comment]
If you run with one thread the problem disappears?

**Comment by msandre** [comment]
That's an interesting point I forgot to mention. It fails even with a single thread.

**Comment by msandre** [comment]
If I comment out the loop over conditions, the problem disappears. The problem I am solving doesn't depend on conditions though.

**Comment by loumalouomega** [comment]
Huuuum, and then is you restore the old version of B&S it works properly?

**Comment by msandre** [comment]
At commit a24ee26 everything works. Then I checkout the builder and solver from 9a95d2a and it fails.

**Comment by loumalouomega** [comment]
OK

**Comment by loumalouomega** [comment]
The main difference between the two loop is the `nowait` (line 224 vs line 254), I am not an expert, http://bisqwit.iki.fi/story/howto/openmp/#BarrierDirectiveAndTheNowaitClause

**Comment by RiccardoRossi** [comment]
Hi Mike,

what i can think of is that either the "EquationId" or the LeftHandSideMatrix/RightHandSideVector are not resized to zero in the conditions, for whatever reason.

in principle the nowait clause shall have no impact on this

can u print out the assembled matrix and vector to matrix market and compare the two? (echo_level=4 would do that)

**Comment by msandre** [comment]
Thx for the hints. I think what @RiccardoRossi is the problem. The matrices and equation ids are not resized. The old openmp directives used firstprivate separately for each loop so the problem did not occur. I will try adding a fix for this and see if that works.

**Comment by msandre** [comment]
This issue is solved now. Thanks!
