### ISSUE TITLE
Release 7.0.0

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#4087]
# 8 days to freeze the release branch

Dear @KratosMultiphysics/all, 

 The branch for release 7.0.0 will be created on 15th of February. I would encourage all @KratosMultiphysics/team-maintainers to update the applications to add their corresponding issues to the release 7.0 milestone so we can track the progress and steps toward release. We should address as much as possible the errors and bugs in this milestone. Also it is very important to have the all the tests working for the release.

**Comment by roigcarlo** [comment]
Dear @KratosMultiphysics/team-maintainers remember that the freeze will be done tomorrow at 18:00 CET.

If you plan to include something after this time, please let me know.

**Edit**:
Sorry for the confusion, the release is at 6:00 PM CET (18:00). I've edited accordingly

**Comment by roigcarlo** [comment]
Dear @KratosMultiphysics/team-maintainers 
We have a delay with #4045, once its merged we will freeze the release branch.

We apologize for the delay.

**Comment by philbucher** [comment]
@roigcarlo did you freeze the branch?

**Comment by roigcarlo** [comment]
Yup: https://github.com/KratosMultiphysics/Kratos/tree/Release-7.0

**Comment by pooyan-dadvand** [comment]
Thanks @roigcarlo!!

Is there any reason that the name of the branch is not all lower case?

**Comment by roigcarlo** [comment]
No, but all release branches are in capital :S

**Comment by pooyan-dadvand** [comment]
Just to communicate that the support for AMatrix has been dropped in this release due to the #3980.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/team-maintainers would you please proceed with updating the what is new section in the readme.md files of each application?

**Comment by vryy** [comment]
@pooyan-dadvand Is there intention to bring it back on future/near future?

**Comment by pooyan-dadvand** [comment]
Yes, I am working on the solution and it will be one of the first things to be pushed after release

**Comment by jginternational** [comment]
Available to download
https://github.com/KratosMultiphysics/GiDInterface/releases/tag/Release-7.0.0

Soon in GiD Internet Retrieve

**Comment by rubenzorrilla** [comment]
There are some things that will be needed for the 3rd day of the Workshop. So ask before preparing the internet retrieve version.

**Comment by jginternational** [comment]
So we'll have a Release 7.0.1
