### ISSUE TITLE
setting row of matrix

### ISSUE THREAD

**Issue by vryy** [KratosMultiphysics/Kratos#4088]
Hi

It is typical to use noalias to set the row of the matrix if using boost.ublas like:

noalias(row(CurrentDisp, node)) = GetGeometry()[node].GetSolutionStepValue(DISPLACEMENT);

This however doesn't work with amatrix interface. What is the best way to set it?

**Comment by pooyan-dadvand** [comment]
Sorry but I missed this issue. It is related to #3980 and I am implementing a solution for it. For this reason we had to stop the AMatrix port for this release

**Comment by vryy** [comment]
thanks for let me know
