### ISSUE TITLE
wrong use of float instead of double

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#4105]
Hi guys, i just realized that there are initializations in the builder and solver as

0.0f or 1.0f

this is WRONG!! the final f stands for "float" which is a shorter type than double

double a = 0.0f only sets a part of the double!!

**Comment by loumalouomega** [comment]
I always use the double, the part of the code with f is not mine.

**Comment by philbucher** [comment]
I think @roigcarlo told me back in the day to use this ...

**Comment by RiccardoRossi** [comment]
0.0d is a double

0.0f is a float (shorter) 

the problem is that (to my understanding) if you assign a float to a double you only set the first 7-8 digits

**Comment by loumalouomega** [comment]
I use 0.0

https://stackoverflow.com/questions/1384434/c-difference-between-0-and-0-0

**Comment by roigcarlo** [comment]
I may have wrongly suggested that sorry

**Comment by philbucher** [comment]
No worries 
Just to be clear, we should always use 0 for ints and 0.0 for doubles right?

**Comment by RiccardoRossi** [comment]
yes, this is wrongly used in the block builder and solver.

**Comment by adityaghantasala** [comment]
@RiccardoRossi  also not my implementations, but I will correct them in the PR I am preparing if that is ok. 
Secondly, out of curiosity, won't it be implicitly casted to a double or at least compiler takes care of that ?

**Comment by RiccardoRossi** [comment]
effectively it looks like gcc is smart about this. at least initialization from constant looks ok (although i would not count on this behaviour)

~~~cpp
#include <iostream>
#include <iomanip>

int main()
{
  std::cout << std::setprecision(15) << std::fixed;
  double a = 1.0f/3.0f ;
  std::cout <<  "float fraction a = " << a << std::endl;
  a = 1.0/3.0 ;
  std::cout <<  "double fraction a = " << a << std::endl;
  a = 0.0f;
  std::cout <<  "assignement a = " << a << std::endl;
  return 0;
~~~

outputs

~~~
 riccardo  ~/data/scratch  ./test.exe 
float fraction a = 0.333333343267441
double fraction a = 0.333333333333333
assignement a = 0.000000000000000

~~~

to be honest i don't understand why the last is different from the first... never mind...it looks like i can close this thread
