### ISSUE TITLE
[StructuralMechanics] resizing of bounded vectors

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4108]
I found sth strange: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_utilities/constitutive_law_utilities.cpp#L200-L201
You are resizing bounded vectors ... ?
I think it is wrong but I am not sure

This happens several times in this file

**Comment by loumalouomega** [comment]
True, Copy paste I assume, one moment
