### ISSUE TITLE
Commiting requires relinking of Core

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4109]
The commit-hash is included in the Logo of Kratos that is printed
~~~
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 6.0.0-2a6cffb
~~~

This requires relinking of the core each time a commit is done
I.e. each time (at least for me) it takes ~4-5min just because of this, even though I didn't modify the core

Is there a way to change/improve/reduce this?

Thanks in advance

FYI @KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
@philbucher You can avoid that by not calling the cmake command every time, just make/make install  and cmake only when you are adding removing files applications.

Aside from that, we could try to make a separate library only for the versioning which is excluded from the normal compilation process, which in my opinion is a little bit excessive, but should reduce the linking tie of that particular file as it will be very small.

Also, we could ward the generation of the versioning file with a cmake option, like `-DDO_NOT_REFRESH_VERSION` or so.

**Comment by philbucher** [comment]
thanks for your comments @roigcarlo 

suggestion one seems to work, but it requires changing of the configure many times

suggestion two seems a bit overkill :)

Suggestion three seems like a good option for developers, I guess the default should be to to false
I would wait a few days to see others opinions and make a draft PR for this

**Comment by roigcarlo** [comment]
> suggestion one seems to work, but it requires changing of the configure many times

You can just comment the make lines and call it from the terminal. Its wait i do :D 
like

```sh
./configure.sh
make install -j4
```

> Suggestion three seems like a good option for developers, I guess the default should be to to false
I would wait a few days to see others opinions and make a draft PR for this

:+1:

**Comment by roigcarlo** [comment]
As the high linking time its due LTO @maceligueta will test the impact of that flag (both in compilation time and performance). We think that the cmake variable may be problematic. After that we will decide.

**Comment by philbucher** [comment]
I just checked, for me it takes now ~30sec to recompile if I committed sth (python only) due to the changes in the version-number

Guess we can close this, don't see it necessary any more, since now it is only ~10% of the original time :)
