### ISSUE TITLE
CMake 3.13 finds intel BLAS - leads to error in SuperLU 

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#4114]
I am using both the ExternalSolversApplication and the EigenSolversApplication with MKL support already for a while now.

Recently the SuperLU solver does not work anymore, it gives a strange error (related to MKL)
```
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```
So i assume it links to the wrong libraries.

I previously updated to CMake 3.13. It seems that the `find_package` has changed and now the MKL installation is found:
```
installed blas = /intel/mkl_2018/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so/intel/mkl_2018/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_gnu_thread.so/intel/mkl_2018/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_core.so/usr/lib/x86_64-linux-gnu/libomp.so.5
installed lapack = /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1/intel/mkl_2018/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_intel_lp64.so/intel/mkl_2018/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_gnu_thread.so/intel/mkl_2018/compilers_and_libraries_2018.1.163/linux/mkl/lib/intel64_lin/libmkl_core.so/usr/lib/x86_64-linux-gnu/libomp.so.5
```

CMake 3.10 gives this output (SuperLU works):
```
installed blas = /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1
installed lapack = /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1/usr/lib/x86_64-linux-gnu/blas/libblas.so
```

Maybe this is related to #3845

**Comment by armingeiser** [comment]
Also if EigenSolversApplication is not compiled, the error is the same. So it seems only to be a problem between Intel BLAS and SuperLU.

(EigenSolversApplication and the mkl solvers work in any case)

**Comment by armingeiser** [comment]
FYI @AndreasWinterstein

**Comment by roigcarlo** [comment]
@armingeiser I don't know if this may help but you should be able to specify exactly which blas/lapack implementation you want to use. For instance, to keep the old behavior:

```CMake
-DBLAS_LIBRARIES=/usr/lib/x86_64-linux-gnu/blas/libblas.so.3.7.1        \
-DLAPACK_LIBRARIES=/usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.7.1  \
```

**Comment by armingeiser** [comment]
@roigcarlo Thanks, yes that does solve the issue for me, as i am happy to use the default BLAS from Ubuntu
