### ISSUE TITLE
FluidDynamics App not using constraints

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#4121]
The fluid dynamics application is not using constraint builder and solver for applying period boundary conditions. This will break the examples and apply_periodic_comdition.py cannot be used.

**Comment by RiccardoRossi** [comment]
I think this should be fixed by #4149 since it adds that capability to the default Builder And Solver

**Comment by adityaghantasala** [comment]
yes .. then still the python solver should be changed to remove use of a different b & s when periodic bcs are used !

**Comment by philbucher** [comment]
@jcotela told me he will anyway update the python-solvers in the near future
@jcotela guess you can add this to the list of TODOs :)

**Comment by jcotela** [comment]
@philbucher is right, the python solvers will be updated at the beginning of the next release cycle. Mentioning #871 so that I have a reference to this issue there.

**Comment by jcotela** [comment]
(sorry, closed by mistake)

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by rubenzorrilla** [comment]
I think this was solved long ago (see for instance the fluid RVE).
