### ISSUE TITLE
CalculateRightHandSide in Explicit Scheme

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#4123]
Hi as I just described in #4122 the pr #4035 caused problems for me which I just noticed. 
#4035 changed the ExplicitScheme in such a way that it does not call `CalculateLocalSystem` but `CalculateRightHandSide`. Which is a good idea.

But :
For the truss and the cable I wrote `CalculateRightHandSide` so that it calculates the Reaction Forces after the solution is obtained (this is how I understood the purpose of this function). And in `CalculateLocalSystem` I calculated the RHS so that it represents the residual.

Problem: For plasticity e.g. the Reaction Forces should only consider the elastic strains and not the plastic ones. So at the moment `CalculateRightHandSide` does not give me correct residuals for the internal forces in case of plasticity e.g.

**Comment by KlausBSautter** [comment]
I think I would need a function that calculates Reaction in case of non-elasticy?

**Comment by philbucher** [comment]
Hmm I really don’t like making the scheme somewhat depending on which CLaw is being used
There has to be a better way of doing this

Vicente how do you do this for the solids?

**Comment by KlausBSautter** [comment]
@bodhinandach this is the problem. Change the claw to TrussConstitutiveLaw. Plasticity with explicit time int is currently to working for the cables

**Comment by KlausBSautter** [comment]
I see the problem now. Let me think about this ...

**Comment by KlausBSautter** [comment]
yes sry I realized my problem

**Comment by RiccardoRossi** [comment]
@KlausBSautter `CalculateLocalSystem` and `CalculateRightHandSide` shall deliver identical results with regards to the rhs.

the rhs represents the residual ...

**Comment by KlausBSautter** [comment]
@RiccardoRossi yes my fault. I did the respective changes
