### ISSUE TITLE
Retriving the AMGCL macro warning after updating it

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#414]
For some reason we have again the solved macro bug:

```
1>C:\Kratos\external_libraries\amgcl/util.hpp(127): warning C4003: not enough actual parameters for macro 'BOOST_PP_SEQ_DETAIL_IS_NOT_EMPTY'
1>C:\Kratos\external_libraries\amgcl/util.hpp(127): warning C4003: not enough actual parameters for macro 'BOOST_PP_SEQ_DETAIL_EMPTY_SIZE'
```

and the compilation out of heap space error

**Comment by RiccardoRossi** [comment]
are u sure you are up-to-date?

line 127 in util.hpp is empty...

https://github.com/KratosMultiphysics/Kratos/blob/master/external_libraries/amgcl/util.hpp#L127

also please take a look at the version of 
add_amgcl_to_python.cpp.

can you verify you have the lines:
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python/add_amgcl_solver_to_python.cpp#L21

in your local version?

**Comment by pooyan-dadvand** [comment]
May be not....  let me check

**Comment by ddemidov** [comment]
By the way, @RiccardoRossi, you can drop lines [21-22](https://github.com/KratosMultiphysics/Kratos/blob/3e5ca9cf7f6e346c309c84def7dcae39977dcf76/kratos/python/add_amgcl_solver_to_python.cpp#L21-L22), as both `multicolor_gauss_seidel` and `parallel_ilu0` were dropped/merged with other code.

**Comment by pooyan-dadvand** [comment]
Updating again and no problem. It seems that my master was one week older....

Sorry for distracting.
