### ISSUE TITLE
[StructuralMechanics] Error to run structural problems without compiling EigenSolversApplication

### ISSUE THREAD

**Issue by bodhinandach** [KratosMultiphysics/Kratos#4147]
I tried to run a standard structural problem without compiling EigenSolverApplication as I dont need it, but the following errors come up. 
![image](https://user-images.githubusercontent.com/37140224/52704068-0c49e700-2f80-11e9-8f09-0500c4b1d46c.png)

I think it is related to the following function calls in kratos_utilities:
https://github.com/KratosMultiphysics/Kratos/blob/d75418de32ff1c3841a7225061cf670ebdacd925/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py#L417-L421

**Comment by loumalouomega** [comment]
@marandra also noticed this

**Comment by philbucher** [comment]
this is not related to the EigenSolversApplication
in a nutshell: Delete the Folder `KratosMultiphysics` and recompile

Do you want the long explanation as well?

**Comment by philbucher** [comment]
btw you should always delete this folder when you recompile, see #2848

**Comment by bodhinandach** [comment]
@philbucher Alright! Deleting the folder works for me. Thanks
