### ISSUE TITLE
ERROR MESSAGES not printed in the CMD window in Windows

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#4150]
Dear all,
During this time I've noticed that the erro messages (KRATOS_ERROR, KRATOS_ERROR_IF, etc) are not shown when I am calculating with the command window in Windows 10.
If I want to see the error msg I have to run the case with the visual studio with 1 thread which is really annoying.

Why the CMD is not showing the error msgs?

Thank you

**Comment by loumalouomega** [comment]
How many threads are you using?, the messages are only guaranteed to appear in single thread computation

**Comment by AlejandroCornejo** [comment]
With the CMD I suppose that 8 threads... How do you change the num of threads in windows?

**Comment by loumalouomega** [comment]
http://lmgtfy.com/?q=number+of+OMP+thread+in+CMD+windows

-> https://software.intel.com/en-us/mkl-windows-developer-guide-setting-the-number-of-threads-using-an-openmp-environment-variable

**Comment by loumalouomega** [comment]
(The previous comment no offence is intended)

**Comment by AlejandroCornejo** [comment]
Thank you! I'll try this!

**Comment by AlejandroCornejo** [comment]
I've tried to set 1 thread and the error messages are never shown.. :S

**Comment by philbucher** [comment]
> http://lmgtfy.com/?q=number+of+OMP+thread+in+CMD+windows
> 
> -> https://software.intel.com/en-us/mkl-windows-developer-guide-setting-the-number-of-threads-using-an-openmp-environment-variable

+1 for lmgtfy :DDD 
(also no offence is intended ;) )

**Comment by philbucher** [comment]
any news here?

**Comment by roigcarlo** [comment]
No. Honestly I havn't have much time to look in to the issue lately, I will see if I can take a little look next week.

**Comment by philbucher** [comment]
closing as there is no real solution as long as we are using openmp, as ricc explained here: https://github.com/KratosMultiphysics/Kratos/issues/5397#issuecomment-521306639

this should be solved when we move to C++11 based parallelism

**Comment by philbucher** [comment]
should be working with #9335
