### ISSUE TITLE
[PFEMFluid] The types of output files('ascii')

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#4167]
Dear @AFranci 
As for the output types, there is only one kind of type of output files just the .bin. If I changed the 'GidPostMode' as the 'Gid_PostAscii', there will be the .res and .msh files every step but there is no results in the .res files.(This problem I have mentioned before）. Could you please take a moment to look at this question and deal with it?
Best regards. And have a nice day~
Feng

**Comment by fengzekang** [comment]
Dear @AFranci 
And also I have another question, as for the Bingham_Fluid model, there are such properties to define the fluid,
Begin Properties 1
    DENSITY 1550.0
    DYNAMIC_VISCOSITY 1.0
    BULK_MODULUS 2100000000.0
    FLOW_INDEX 1
    YIELD_SHEAR 100.0
    ADAPTIVE_EXPONENT 1000
End Properties
Could you please explain the meaning of these parameters and what do they control? Are there any else properties which can be used to control the non-Newton fluid model?
Best regards~
Feng

**Comment by AFranci** [comment]
Dear @fengzekang 

For the first question, maybe @maceligueta and @ipouplana know something more than me... I just output which have .post.bin extention and they work properly.

Concerning the fluid parameters, they are the classical ones for the non-Newtonian regularized model of Papanastasiou. I suggest you to take a look to the next reference to understand them better
 https://www.sciencedirect.com/science/article/pii/S0377025718300399

Regards,

Alessandro

**Comment by fengzekang** [comment]
Dear @AFranci 
Thanks for your reply. I will follow your paper to try to define the properties in the real model.
Thanks a lot.
Best regards.
Feng

**Comment by ipouplana** [comment]
Hi @fengzekang, it is actually strange that the pfem fluid output results are only written when using the binary format but not when using ascii.

I have looked into the pfem_fluid_gid_output_process.py and it seems quite standard. It derives from the gid_output_process.py of the Kratos Core, and uses the PfemFluidGidIO C++ class, which at the same time derives from the GidIO class (~/Kratos/kratos/includes/gid_io.h). I'm not sure why it does not work...

Right now I have not the time to study this problem in detail, but if you need to solve this issue, I recommend that you debug these files while running a small example to compare the behavior when using 'GidPostMode' as 'GiD_PostBinary' and 'GidPostMode' as 'GiD_PostAscii'.

If you can neither look into the problem, we will try to solve it when we have time. In any case, thank you for noticing this issue ;)
