### ISSUE TITLE
[StructuralMechanics] clang compiler warnings from nightly build

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4175]
~~~
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/adjoint_nodal_displacement_response_function.h:84:10: warning: 'Kratos::AdjointNodalDisplacementResponseFunction::CalculateGradient' hides overloaded virtual function [-Woverloaded-virtual]
/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/custom_response_functions/response_utilities/adjoint_local_stress_response_function.h:81:10: warning: 'Kratos::AdjointLocalStressResponseFunction::CalculateGradient' hides overloaded virtual function [-Woverloaded-virtual]
~~~

**Comment by armingeiser** [comment]
I checked this and it is intended:
* the base class in the core has two overloaded functions `CalculateGradient`
* the first level of inheritance `AdjointStructuralResponse` overrides one of them
* the second level of inheritance `AdjointNodalDisplacementResponseFunction` and `AdjointLocalStressResponseFunction` override the second version of this function.

**Comment by armingeiser** [comment]
I don't know how to resolve such a warning without copying both overloaded functions into the first level of inheritance and essentially duplicating the code of the base class for the one i don't wan't to override.
