### ISSUE TITLE
math operator on Kratos::Point

### ISSUE THREAD

**Issue by vryy** [KratosMultiphysics/Kratos#4189]
Right now when I declare

    #include<geometries/point.h>
    ...
    Point A, B, C;
    A = B - C;

The compiler throw the error

error: no match for ‘operator=’ (operand types are ‘Kratos::Point’ and ‘AMatrix::MatrixMinusExpression<Kratos::Internals::Matrix<double, 3, 1>, Kratos::Internals::Matrix<double, 3, 1> >’)

How is it possible? The point is supposed to be addable/subtractable, right?

**Comment by vryy** [comment]
In addition, A = ZeroVector(3) also doesn't work. What is the best way to set a Point to zero?

**Comment by RiccardoRossi** [comment]
hi Bui,

       the behaviour you are seeing does nit depend on Amagtix but rather
in thr "explicit" keyword that was added to the point constructor.

just do

point.Coordinaates() = ...

**Comment by vryy** [comment]
thanks. I got it.
