### ISSUE TITLE
Addition of cmake_build_debug folder to .gitignore

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#419]
What do you think about adding a debug compilation folder to the gitignore as is done with the cmake_build folder? We can name it as "cmake_build_debug".

**Comment by loumalouomega** [comment]
We already discussed this, for example in my case is called `build_debug`, you can just add the folder to the exclude

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-make-Git-ignore-the-files-resulting-from-a-compilation-without-conflicts-in-.gitignore

**Comment by rubenzorrilla** [comment]
I'm aware of that, but in this case the .gitignore is appearing when doing a git status, isn't it?

**Comment by philbucher** [comment]
For me it doens't show up aka it works

**Comment by rubenzorrilla** [comment]
You were right. Thanks @loumalouomega @philbucher . I think we can close this.
