### ISSUE TITLE
[ConvectionDiffusionApplication] Tests for BFECC are failing

### ISSUE THREAD

**Issue by swenczowski** [KratosMultiphysics/Kratos#4195]
Dear developers,
(my apologies for not knowing who is the expert in this concern)

while looking for a reference for the usage of the BFECC convection process, I happened to come across the file `test_bfecc.py` (applications/convection_diffusion_application/test_examples/bfecc_test/test_bfecc.py). 

During the execution of the test case, the following error message was displayed (please, find below). My first thought was to relate the error to the deprecation warning. However, the same error message kept showing up after moving to the new way of creating a model part.

It would be very kind if you could try and reproduce the error, please. I hope that its occurrence is not related to my local settings. If it is indeed a general problem, it would be very helpful if you could find a solution to restore the functionality of the test case.

ModelPartIO:   [Reading Nodes    : 3449 nodes read]
ModelPartIO:   [Reading Elements : 6496 elements read] [Type: FractionalStep2D]
ModelPartIO:   [Total Lines Read : 9954]
base_model_part = -BasePart- model part
    Buffer Size : 2
    Number of tables : 0
    Number of sub model parts : 0
    Current solution step index : 0

    Mesh 0 :
        Number of Nodes       : 3449
        Number of Properties  : 1
        Number of Elements    : 6496
        Number of Conditions  : 0
        Number of Constraints : 0

Traceback (most recent call last):
  File "test_bfecc.py", line 88, in <module>
    bfecc_utility = BFECCConvection2D(locator)
RuntimeError: Unable to load a custom holder type from a default-holder instance

**Comment by roigcarlo** [comment]
Hi @swenczowski 

Are you running with Python2 by any chance?

**Comment by swenczowski** [comment]
No, I am using `python3` to run the test case? Didn't the error occur for you?

**Comment by roigcarlo** [comment]
No, but recently we've got some similar errors that were caused while compiling with p2.7, anyway, I think I know which is the problem. Let me take a look.

**Comment by roigcarlo** [comment]
Well, found the problem. The locator needs to be exported as a pointer, and right now is exported as a reference. The fix is easy:

_kratos/python/add_utilities_to_python.cpp:556_
```C++
py::class_< BinBasedFastPointLocator < 2 >, BinBasedFastPointLocator < 2 >::Pointer >(m,"BinBasedFastPointLocator2D")
    .def(py::init<ModelPart& >())
    .def("UpdateSearchDatabase", &BinBasedFastPointLocator < 2 > ::UpdateSearchDatabase)
    .def("UpdateSearchDatabaseAssignedSize", &BinBasedFastPointLocator < 2 > ::UpdateSearchDatabaseAssignedSize)
    .def("FindPointOnMesh", &BinBasedFastPointLocator < 2 > ::FindPointOnMeshSimplified)
    ;

py::class_< BinBasedFastPointLocator < 3 >, BinBasedFastPointLocator < 3 >::Pointer >(m,"BinBasedFastPointLocator3D")
    .def(py::init<ModelPart&  >())
    .def("UpdateSearchDatabase", &BinBasedFastPointLocator < 3 > ::UpdateSearchDatabase)
    .def("FindPointOnMesh", &BinBasedFastPointLocator < 3 > ::FindPointOnMeshSimplified)
    .def("UpdateSearchDatabaseAssignedSize", &BinBasedFastPointLocator < 3 > ::UpdateSearchDatabaseAssignedSize)
```

But I don't know who else is using the locator, if there is any place where is expected as reference this will break it. The alternative solution is to change the bfecc process so it uses a reference instead of an object, but that requires some extra code change.

__Edit__:
Corrected the path

**Comment by swenczowski** [comment]
Just to avoid confusion in the further discussion: Are you referring to the file `convection_diffusion_application/custom_python/add_custom_utilities_to_python.cpp` or to `kratos/python/add_utilities_to_python.cpp`? By now, I assume the latter because changes in the first file yield redefinition warnings.

**Comment by roigcarlo** [comment]
@swenczowski Ups you are right, I've copy pasted the wrong path :S

**Comment by philbucher** [comment]
Note that the cases in test_examples are sometimes outdated because they are not part of the testing framework 

That’s why for a while already we try to add them to the regular testing  (if suitable)

**Comment by rubenzorrilla** [comment]
@swenczowski I encourage you to migrate the test from the outated test_examples folder to the "official" suite.

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by rubenzorrilla** [comment]
Now it is. The old tests in the `test_example` folder have been migrated and upgraded to the current test suite. Both the BFECC and BFECC with limiter convection are working.
