### ISSUE TITLE
Tests failing in nightly build

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4223]
in ContactStructuralMechanics:
~~~
Running tests for ContactStructuralMechanicsApplication
/home/ubuntu/Kratos/applications//ContactStructuralMechanicsApplication/tests/test_ContactStructuralMechanicsApplication.py

[Error]: Tests for ContactStructuralMechanicsApplication took to long. Process Killed.
~~~

in DEM:
~~~
Running tests for DEMApplication
....u.
----------------------------------------------------------------------
Ran 6 tests in 16.073s

FAILED (unexpected successes=1)
/home/ubuntu/Kratos/applications//DEMApplication/tests/test_DEMApplication.py
~~~

**Comment by maceligueta** [comment]
Yep, it’s an unexpected succes thanks to the presence of numpy. Can we modify the unittests so they give OK when there’s unexpected success? I will google that.

**Comment by loumalouomega** [comment]
I can move more tests to validations, this didn't happen before

**Comment by loumalouomega** [comment]
Done

**Comment by philbucher** [comment]
@maceligueta isn't the default to give ok when the test is successful?

**Comment by maceligueta** [comment]
@philbucher: yes, in general. But it says ‘Failed’ when there’s one successful test that was marked with ‘expected failure’. I guess that makes you remove the decorator, but in our case this test passes in nightly but fails in Travis (no numpy).

**Comment by philbucher** [comment]
@maceligueta I guess you could add some skiptests depending on whether numpy is available 
Can you point me to this test? I think I know how to fix it

**Comment by loumalouomega** [comment]
Here an example: https://github.com/KratosMultiphysics/Kratos/blob/0380e591ac9707431380499095fd3edd43b7535d/kratos/tests/test_sparse_multiplication.py#L16

**Comment by maceligueta** [comment]
@philbucher  this is the conflictive test:
https://github.com/KratosMultiphysics/Kratos/blob/0380e591ac9707431380499095fd3edd43b7535d/applications/DEMApplication/tests/test_analytics.py#L204
It's funny that in my computer it says OK to all (detecting an unexpected failure), but in @farrufat-cimne 's pc we get the same problem as with the nightly tests... I am using Python 2.7 though, and Linux Opensuse, while he's using Python3 and Ubuntu.

**Comment by philbucher** [comment]
@maceligueta if you say that it works for some configurations then it seems to not be related to numpy right?

Otherwise you could just skip the tests as @loumalouomega showed

**Comment by maceligueta** [comment]
Apparently, they changed the behavior of Unittest between Python2 and Python3: an unexpected success is  now considered a Fail, while it was ignored before. The fact that numpy is available for the nightly but not for Travis is what tiggers this fail. Though it does not happen in my pc where I have Python 2.7.
I do not know what's the best solution. We can skip it for the moment, until numpy is supported everywhere. What are the others doing with their cases which need numpy?

**Comment by philbucher** [comment]
Test is dem is working now, closing
