### ISSUE TITLE
[PFEMFluid]parameters setting

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#4227]
Dear @AFranci 
Can we define the damp coefficient of the elements?(is this controlled by the DYNAMIC_VISCOSITY)
And also, can we define the coefficient of friction between the rigid boundary and the fluid part. I mean that if I simulate the landslide,  the parameter of friction coefficient should be set.
Best regards
Feng

**Comment by AFranci** [comment]
In the current version of the formulation, the interaction between fluid element and rigid wall is modeled only considering no-slip conditions.
DYNAMIC_VISCOSITY is the viscosity of the fluid elements.
