### ISSUE TITLE
Error: While installing Toggling ON -DTOPOLOGY_OPTIMIZATION_APPLICATION causes the following error

### ISSUE THREAD

**Issue by Glovedsasquatchcodes** [KratosMultiphysics/Kratos#4230]
With the following structure of the configure.sh file:
cmake ..                                                                            \
-DCMAKE_C_COMPILER=/usr/bin/gcc                                                     \
-DCMAKE_CXX_COMPILER=/usr/bin/g++                                                   \
-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 -std=c++11 "                           \
-DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -msse3 "                                          \
-DBOOST_ROOT="$/home/meinhard/Software/boost_1_69_0/boost_1_69_0/boost"                                                        \
-DPYTHON_EXECUTABLE="/usr/bin/python3"                                              \
-DCMAKE_BUILD_TYPE=Release                                                          \
-DMESHING_APPLICATION=ON                                                            \
-DEXTERNAL_SOLVERS_APPLICATION=ON                                                   \
-DSTRUCTURAL_MECHANICS_APPLICATION=ON                                               \
-DCONVECTION_DIFFUSION_APPLICATION=ON                                               \
-DSOLID_MECHANICS_APPLICATION=ON                                                    \
-DCONSTITUTIVE_MODELS_APPLICATION=ON                                                \
-DFLUID_DYNAMICS_APPLICATION=ON                                                     \
-DMESH_MOVING_APPLICATION=ON                                                        \
-DFSI_APPLICATION=ON                                                                \
-DDEM_APPLICATION=ON                                                               \
-DSWIMMING_DEM_APPLICATION=ON                                                     \
-DMIXED_ELEMENT_APPLICATION=ON                                                     \
-DSHAPE_OPTIMIZATION_APPLICATION=ON                                                \
-DTOPOLOGY_OPTIMIZATION_APPLICATION=ON                                             \
-DMETIS_APPLICATION=OFF                                                             \
-DPARMETIS_ROOT_DIR="/home/youruser/compiled_libraries/ParMetis-3.1.1"              \
-DTRILINOS_APPLICATION=OFF                                                          \
-DTRILINOS_ROOT="/home/youruser/compiled_libraries/trilinos-10.2.0"                 \
-DINSTALL_EMBEDDED_PYTHON=ON							\

I am getting the following error:

CMake Error at applications/TopologyOptimizationApplication/CMakeLists.txt:25 (target_link_libraries):
  Target "KratosSolidMechanicsApplication" of type MODULE_LIBRARY may not be
  linked into another target.  One may link only to STATIC or SHARED
  libraries, or to executables with the ENABLE_EXPORTS property set.

-- triangle : /home/meinhard/Software/Kratos/external_libraries/triangle
python libraries to be installed are: /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
-- Standard install dir /home/meinhard/Software/Kratos
installed blas = /usr/lib/openblas-base/libblas.so.3
installed lapack = /usr/lib/openblas-base/liblapack.so.3/usr/lib/openblas-base/libblas.so.3
-- Configuring incomplete, errors occurred!
See also "/home/meinhard/Software/Kratos/cmake_build/CMakeFiles/CMakeOutput.log".
Makefile:656: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1

Kindly help!!!!!

**Comment by loumalouomega** [comment]
I am not maintainer of that app, but I think is not even updated to recent changes as the pybind migration. Let's ask to the rest of the @KratosMultiphysics/structural-mechanics crew

**Comment by philbucher** [comment]
Unfortunately the TopOptApp does not compile as of now, it would require some attention from the maintainers (@dbaumgaertner ) to bring it up to date
At the moment from what I know this will not happen in the near future, hence it cannot be used for now

**Comment by Glovedsasquatchcodes** [comment]
Okay, thanks for your response.
