### ISSUE TITLE
SpringDamperElement gives rotational DOFs without stiffness

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#4245]
The spring damper element in str mech app is adding rotational degree of freedoms on its nodes without adding any rotational stiffness ! (this might cause zero rows columns in the matrix)
https://github.com/KratosMultiphysics/Kratos/blob/f038e54c5d1597a01664dc33551abdee09c72c9e/applications/StructuralMechanicsApplication/custom_elements/spring_damper_element_3D2N.cpp#L146

Shouldn't the rotational degree of freedoms be removed if it is not implemented ?
https://github.com/KratosMultiphysics/Kratos/blob/f038e54c5d1597a01664dc33551abdee09c72c9e/applications/StructuralMechanicsApplication/custom_elements/spring_damper_element_3D2N.cpp#L370

**Comment by loumalouomega** [comment]
This is fix in a PR of mine: https://github.com/KratosMultiphysics/Kratos/pull/2512

**Comment by adityaghantasala** [comment]
@loumalouomega  if the PR #2512 is taking more time, you can cherry pick these changes and make a different PR as a fast PR .. this change is independent of the other changes in PR #2512

**Comment by loumalouomega** [comment]
#2512is ready and I applied all the corrections suggested by @philbucher,we are waiting for @RiccardoRossi (ping @RiccardoRossi)

**Comment by RiccardoRossi** [comment]
i will take a look tomorrow

**Comment by loumalouomega** [comment]
This is solved on https://github.com/KratosMultiphysics/Kratos/pull/4781, closing
