### ISSUE TITLE
Fancy convergence criterion output

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#425]
I have created a fancier (and specially, easier to look) output for the convergence criteria. I was tired of needing to look each time when the problem converged, without any easy way to look at the terminal and knowing what was happening.

I used bprinter (https://github.com/dattanchu/bprinter a MIT libary, that I modified to make it even cooler), here a screenshoot:

![imagen](https://cloud.githubusercontent.com/assets/19991680/26357536/df64bfa4-3fcf-11e7-9dec-d520495cef75.png)

As you can see it is easy to see when a step is finished and what is happening in each NL iteration. Besides using colors I can see if it converged easily. I think this could be interested to be implemented in a more general in the core and accessible to everyone. What do you thing @KratosMultiphysics/technical-committee ?

**Comment by RiccardoRossi** [comment]
admittedly very cool.... but...does it work on windows?

**Comment by loumalouomega** [comment]
I don't know, and I am scared of try it there (I know that compiling in windows is complicated). Can anyone using Windows try it? (requires my branch)

![](https://i.imgur.com/wFcoZ43.mp4)

**Comment by pooyan-dadvand** [comment]
@loumalouomega Which branch is?

**Comment by pooyan-dadvand** [comment]
Meanwhile I have noticed that this library uses the boost::karma based on spirit which is usually time consuming to compile. I would try to use it without Karma.

**Comment by loumalouomega** [comment]
Without karma the output is not so fancy, because Karma automatically generates the scientific notation output. I can try it to do using pure c++.

**Comment by loumalouomega** [comment]
The branch is features_mortar_contact_advances

**Comment by loumalouomega** [comment]
@pooyan-dadvand I removed the dependency of the boost::karma, now it is accesory. I just use pure c++

**Comment by loumalouomega** [comment]
@pooyan-dadvand  and @RiccardoRossi I solved the problem in Windows (right now no colours 👎 )

I will try to use this (when I have some time): https://stackoverflow.com/questions/4053837/colorizing-text-in-the-console-with-c

PS: The colours worked with the PowerShell, but I assume that I am suppose to use cmd.exe as the standard

**Comment by loumalouomega** [comment]
@pooyan-dadvand  and @RiccardoRossi I will close this discussion until some more prioritary discussions are closed
