### ISSUE TITLE
Why are many functions in VariableUtils strongly type-dependent rather than templated

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4251]
I saw that many methods in the variable_utils are taking as arguments e.g. a double OR a array-variable, e.g. [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/variable_utils.h#L461-L477)
The code btw the functions is pretty much identical.

Is there a reason we did not template this? I think it would make a lot of sense, then it can also be used more flexible and is extensible in the future. (e.g. right now it is not possible to use some of the functions with component-vars, e.g. `VELOCITY_Y`)

If you agree I would add general methods and deprecate the old ones.

FYI @jcotela maybe you also have an opinion abt this

**Comment by RiccardoRossi** [comment]
i think that one problem was the need of using noalias

**Comment by philbucher** [comment]
I see
with AMatrix this should no longer be needed right?

I never tried, but could one use `noalias` also for scalars? (I know it does not make sense but then once could have only one fct)
If not, then do you think it would have a big performance-impact / could we sacrifice it for now in order to remove code duplication and not to add even more duplicates?

**Comment by loumalouomega** [comment]
We can create the template version and deprecate the current ones

**Comment by RiccardoRossi** [comment]
yes, the noalias is not needed with AMatrix.

as of today however the performance impact IS sensible :-( (but as we get ready to move to AMatrix i am not against your proposal)

**Comment by philbucher** [comment]
Sweet, then I will create a draft and we can discuss it :)

**Comment by loumalouomega** [comment]
Ok

**Comment by rubenzorrilla** [comment]
I'm already taking care of this. In a first stage I'll improve the `VariableUtils` and add some deprecation warnings. In further PRs we can start removing such warnings (I found that this will make the review easier).

**Comment by RiccardoRossi** [comment]
you will have a problem.with the noalias if you try to remove them

**Comment by rubenzorrilla** [comment]
> you will have a problem.with the noalias if you try to remove them

I know, but as we agreed above I'm not using the `noalias` anymore. We can wait for the AMatrix to merge this.

**Comment by philbucher** [comment]
@RiccardoRossi :

https://github.com/KratosMultiphysics/Kratos/issues/4251#issuecomment-466933394

;)

**Comment by philbucher** [comment]
closed by #5470
