### ISSUE TITLE
[Structural] Convergence problem in simple case

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#4272]
Dear @KratosMultiphysics/structural-mechanics ,

While debugging my new embedded solver I realised that the structure was not converging for a simple `POSITIVE_FACE_PRESSURE`distribution. I did extract such pressure load to set a simple structural mechanics problem with the same geometry. Some of you will note that it is the Mok benchmark beam but with a larger Young modulus. 

I'm attaching the files so you can run it. 

Many thanks in advance!
[test_structure.zip](https://github.com/KratosMultiphysics/Kratos/files/2906492/test_structure.zip)

**Comment by RiccardoRossi** [comment]
I believe that the problem is in the way the first residual is initialized:

we should compute the residual r0 BEFORE solving the system of equations, not after having updated the solution.

Having said this, we need to be careful in doing this in a way that is not affected by the MPCs, in the sense that the residual will not be zero there where the MPCs are acting, so master and slave dofs will have to be taken out from this computation.

**Comment by rubenzorrilla** [comment]
Just to clarify things, I was using the `residual_criteria`

**Comment by loumalouomega** [comment]
> I believe that the problem is in the way the first residual is initialized:
> 
> we should compute the residual r0 BEFORE solving the system of equations, not after having updated the solution.
> 
> Having said this, we need to be careful in doing this in a way that is not affected by the MPCs, in the sense that the residual will not be zero there where the MPCs are acting, so master and slave dofs will have to be taken out from this computation.

We should differentiate external and internal forces (that's the key)

**Comment by RiccardoRossi** [comment]
easier to say than to do...

also what would u do for the fluid?

to begin i would at least compute r(x0) correctly.

now we are computing r0 as r(x0+dx) (and btw we are computing twice the norm)

**Comment by loumalouomega** [comment]
@RiccardoRossi I do what you propose in https://github.com/KratosMultiphysics/Kratos/pull/4286

**Comment by RiccardoRossi** [comment]
@loumalouomega about differentiating internal and external forces you are surely right. along the same line we should also differentiate damping and inertia forces for dynamic problems.

my proposal would be to address this by implementing in the structural elements and conditions a 
$Calculate(EXTERNAL_FORCES_VECTOR)$

the BuilderAndSolver could then assemble that. The nasty part of it is that than we would surely need to have an mpi version and a serial version of the convergence criterias to be able to do the assembly differently. Also for dynamic problems the convergence criteria would have to be aware of the scheme (which is not)

**Comment by philbucher** [comment]
> the BuilderAndSolver could then assemble that. The nasty part of it is that than we would surely need to have an mpi version and a serial version of the convergence criterias to be able to do the assembly differently. Also for dynamic problems the convergence criteria would have to be aware of the scheme (which is not)

maybe for this #859 could be used ...

**Comment by RiccardoRossi** [comment]
ok, this is an option, still the only object that would know this is the convergence criteria (the strategy does not know of this behaviour) so we would have to pass the builder and solver and scheeme to the convergence criteria if you want to use that mechanism.

it might also make sense to explore some sort of modified build function to which a lambda function could be assigned

**Comment by vryy** [comment]
What is the resolution for this problem? We also have convergence problem for a simple test case. See attached file.
[test_square_pressure.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/3042501/test_square_pressure.gid.zip)

**Comment by vryy** [comment]
Just to be clear on what happens, we create a square and set symmetry condition on left and bottom side. The pressure is applied on top and the material is linear, small displacement element is used. The move_mesh_flag is disabled. The iteration did not converge in 10 steps. How come this is possible?

**Comment by loumalouomega** [comment]
> Just to be clear on what happens, we create a square and set symmetry condition on left and bottom side. The pressure is applied on top and the material is linear, small displacement element is used. The move_mesh_flag is disabled. The iteration did not converge in 10 steps. How come this is possible?

No idea, strange...

**Comment by vgudzulic** [comment]
Hi all,

here is a benchmark example for StructuralMechanicsApplication of cylinder with applied internal pressure. I have tried to run it with both line load and pressure on the internal edge with linear and quadratic small displacement elements. I have obtained some strange behavior and I hope someone can help me understand it. Namely, for the Q4 element with line_load condition everything goes perfectly. For the same element with pressure condition, I have obtained the same result but after 5 iterations! (the move_mesh_flag is set to false)
![deformed_shape_q4_line_load](https://user-images.githubusercontent.com/21369389/55644682-ed750d80-57d6-11e9-8291-c98d7fdb37a5.png)

For Q9 element with line load condition, I obtained wrong result, but the simulation converged in one iteration as it should. For pressure condition the simulation did not converge after 10 iterations.
![deformed_shape_q9_line_load](https://user-images.githubusercontent.com/21369389/55644762-1eedd900-57d7-11e9-854d-aaa0c0b1f98c.png)

I was thinking that it may be that I have mad a mistake in setting the boundary conditions for the quadratic case, however it seems all fine to me. I would appreciate greatly if someone can check the attached input files and provide some feedback. Is it possible that there is a bug somewhere in the line_load_condition_2d? Are there any other working examples with pressure and line load on small displacement element?

Best regards and thanks in advance! I wish a nice weekend to everyone.
Vladislav

[cylinder_internal_pressure.zip](https://github.com/KratosMultiphysics/Kratos/files/3048956/cylinder_internal_pressure.zip)

**Comment by loumalouomega** [comment]
I assume that the issue is in the line_load_condition. Which assumes that the line is only two nodes (which is wrong). If we add a general integration we will need anyway to update the interface for consistency.

For the pressure is strange, it the load is follower, but the mesh is not moving, should not matter.

**Comment by loumalouomega** [comment]
I will check

**Comment by loumalouomega** [comment]
@vgudzulic Respect the q4, I needed to update the test you send us and I added #4596 in order to be able to apply a load in a analytic direction so the resulting load is exactly the same. The pressure has as you said 5  iterations instead of 1, I am researching that right now.

[q4.zip](https://github.com/KratosMultiphysics/Kratos/files/3050819/q4.zip)

**Comment by vgudzulic** [comment]
@loumalouomega Thanks a lot for looking into it. Let me know if I can help somehow

**Comment by loumalouomega** [comment]
> @loumalouomega Thanks a lot for looking into it. Let me know if I can help somehow

Well, my theory is that the Line2D3 has some bug, I am creating tests right now.

**Comment by loumalouomega** [comment]
> > @loumalouomega Thanks a lot for looking into it. Let me know if I can help somehow
> 
> Well, my theory is that the Line2D3 has some bug, I am creating tests right now.

The length computation was wrong for example

**Comment by loumalouomega** [comment]
> > > @loumalouomega Thanks a lot for looking into it. Let me know if I can help somehow
> > 
> > 
> > Well, my theory is that the Line2D3 has some bug, I am creating tests right now.
> 
> The length computation was wrong for example

 #4601 Fixes the quadratic line, many things wrong or badly copypasted. The PR includes tests and fixes everything wrong (I found)

**Comment by loumalouomega** [comment]
> Hi all,
> 
> here is a benchmark example for StructuralMechanicsApplication of cylinder with applied internal pressure. I have tried to run it with both line load and pressure on the internal edge with linear and quadratic small displacement elements. I have obtained some strange behavior and I hope someone can help me understand it. Namely, for the Q4 element with line_load condition everything goes perfectly. For the same element with pressure condition, I have obtained the same result but after 5 iterations! (the move_mesh_flag is set to false)
> ![deformed_shape_q4_line_load](https://user-images.githubusercontent.com/21369389/55644682-ed750d80-57d6-11e9-8291-c98d7fdb37a5.png)
> 
> For Q9 element with line load condition, I obtained wrong result, but the simulation converged in one iteration as it should. For pressure condition the simulation did not converge after 10 iterations.
> ![deformed_shape_q9_line_load](https://user-images.githubusercontent.com/21369389/55644762-1eedd900-57d7-11e9-854d-aaa0c0b1f98c.png)
> 
> I was thinking that it may be that I have mad a mistake in setting the boundary conditions for the quadratic case, however it seems all fine to me. I would appreciate greatly if someone can check the attached input files and provide some feedback. Is it possible that there is a bug somewhere in the line_load_condition_2d? Are there any other working examples with pressure and line load on small displacement element?
> 
> Best regards and thanks in advance! I wish a nice weekend to everyone.
> Vladislav
> 
> [cylinder_internal_pressure.zip](https://github.com/KratosMultiphysics/Kratos/files/3048956/cylinder_internal_pressure.zip)

Can you try #4601?

**Comment by vgudzulic** [comment]
Hi,

line load using line2D3 is now working. Thanks a lot @loumalouomega !

![deformed_shape_q9_line_load_corrected](https://user-images.githubusercontent.com/21369389/55746398-dd109d00-5a39-11e9-8ca0-8252f2c15303.png)

Pressure still needs 5 iterations though, but gives the same result in both cases.

**Comment by loumalouomega** [comment]
> Hi,
> 
> line load using line2D3 is now working. Thanks a lot @loumalouomega !
> 
> ![deformed_shape_q9_line_load_corrected](https://user-images.githubusercontent.com/21369389/55746398-dd109d00-5a39-11e9-8ca0-8252f2c15303.png)
> 
> Pressure still needs 5 iterations though, but gives the same result in both cases.

In my case it takes 2 iterations, are you considering 1.0e-4 for relative criteria or smaller?

**Comment by vgudzulic** [comment]
@loumalouomega Yes, true, I am using 1.0e-09. If I set relative tolerance to 1.0e-04, it converges in 2 steps as you say. However, in case of small_displacement elements it should converge in one iteration. The only difference is in that in LINE_LOAD we give the direction to the load explicitly, whereas in POSITIVE_FACE_PRESSURE, the line_load condition computes it itself.

By the way, here is the convergence study for global error in stresses (h1) and displacements (l2) for this problem with a small_displacement element and applied line load. It shows perfect convergence now. When the PR is approved, we would like to submit this as an example for the StructuralMechanicsApplication, and possibly as a nightly test.

![convergence_error](https://user-images.githubusercontent.com/21369389/55804300-4d6ffa80-5adc-11e9-95ef-0c16f1cde2bd.jpg)

**Comment by loumalouomega** [comment]
> @loumalouomega Yes, true, I am using 1.0e-09. If I set relative tolerance to 1.0e-04, it converges in 2 steps as you say. However, in case of small_displacement elements it should converge in one iteration. The only difference is in that in LINE_LOAD we give the direction to the load explicitly, whereas in POSITIVE_FACE_PRESSURE, the line_load condition computes it itself.
> 
> By the way, here is the convergence study for global error in stresses (h1) and displacements (l2) for this problem with a small_displacement element and applied line load. It shows perfect convergence now. When the PR is approved, we would like to submit this as an example for the StructuralMechanicsApplication, and possibly as a nightly test.
> 
> ![convergence_error](https://user-images.githubusercontent.com/21369389/55804300-4d6ffa80-5adc-11e9-95ef-0c16f1cde2bd.jpg)

Feel free to approve (wink wink)

**Comment by loumalouomega** [comment]
I reopen, because we still have some problem of convergence (I think)

@vgudzulic feel free to create the test

**Comment by philbucher** [comment]
@vgudzulic why do you disable the move_mesh flag?
@RiccardoRossi @loumalouomega isn't this required for StructuralMechanics?

**Comment by vgudzulic** [comment]
@philbucher Because I don't want the mesh to move (this is a small displacement element so I want everything to be computed in the reference configuration). At the time when I started preparing this example I was not getting correct results so I thought that move_mesh_flag was an issue, so I disabled it. I checked now with the move_mesh_flag=true and there is no side effect when the LINE_LOAD condition is used, because the solution converges in one iteration. However, with pressure, it causes slight change in the final result (it gets worse) but the number of iterations stays the same (2 for relative tolerance 10^-04 and 5 for tolerance 10^-09).


@loumalouomega I will try to prepare some test in the following days

**Comment by loumalouomega** [comment]
We solved this, can we close it?

**Comment by vryy** [comment]
Hi Vlad

Is the line load with PRESSURE working as expected?

**Comment by vgudzulic** [comment]
I believe that the pressure should converge in one step in this case, so far it is not. Line load works perfectly. I promised to make some tests, but, unfortunately, I never got time to look into that. I would keep it open if others agree

**Comment by vgudzulic** [comment]
Hi, 
related to this issue, I have made two tests that verify that the rhs is computed correctly even for curved geometries (one for curved line and one for curved triangle) which I could provide if needed. The value is correct and is not a cause for the fact that for small displacement element the solution doesn't converge in one step (even with move_mesh_flag set to false). The problem is in fact the load stiffness that should be a zero matrix in case of small displacements, as a linearization of rhs (since the normal doesn't change). This is currently not possible due to the fact that the condition is the same for small displacement, TL, and UL and it is always assumed that everything is computed on deformed configuration as already discussed in #5890. 

I tried that as well locally and when I find Jacobian on reference configuration and set the lhs contribution to zeros explicitly, I obtain the correct convergence in one step.

With this conclusion, I think we know the cause of the problem and maybe this issue is not necessary anymore.

Regards
Vladislav

**Comment by rubenzorrilla** [comment]
> Hi,
> related to this issue, I have made two tests that verify that the rhs is computed correctly even for curved geometries (one for curved line and one for curved triangle) which I could provide if needed. The value is correct and is not a cause for the fact that for small displacement element the solution doesn't converge in one step (even with move_mesh_flag set to false). The problem is in fact the load stiffness that should be a zero matrix in case of small displacements, as a linearization of rhs (since the normal doesn't change). This is currently not possible due to the fact that the condition is the same for small displacement, TL, and UL and it is always assumed that everything is computed on deformed configuration as already discussed in #5890.
> 
> I tried that as well locally and when I find Jacobian on reference configuration and set the lhs contribution to zeros explicitly, I obtain the correct convergence in one step.
> 
> With this conclusion, I think we know the cause of the problem and maybe this issue is not necessary anymore.
> 
> Regards
> Vladislav

@RiccardoRossi and me faced this same problem when implementing the mixed u-eps_vol element a few weeks ago.

We agreed that we should (sooner than later) implement a load condition for small displacement elements.

**Comment by RiccardoRossi** [comment]
yes, as described in  #5890 right now we have surely a problem in the case of non negligible deformations. I think it is actually quite important to implement integration on the reference configuration for such cases
