### ISSUE TITLE
[Tests] Test object printing is failing in Windows

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#4279]
The test is failing because apparently the order of submodelparts are not the same in Linux and windows and `-outlet-` is printed before `-inlets-`causing the comparison to fail.

@philbucher would you please take a look at it? I don't know the purpose of the test so I didn't want it to change it by myself

**Comment by philbucher** [comment]
I will fix it tonight

**Comment by pooyan-dadvand** [comment]
Thanks @philbucher
