### ISSUE TITLE
How to output to hdf5 from project parameters

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#4285]
Hello everyone, 
       we are trying to output to hdf5 by prescribing it from the ProjectParameters.

can anyone give a minimal working example? we have been trying to add to the output processes

~~~py
"python_module" : "hdf5_output_process",
                        "kratos_module" : "KratosMultiphysics.HDF5Application",
                        "process_name"  : "",
                        "Parameters"    : {
                            "model_part_name"                    : "FluidModelPart",
                            "create_xdmf_file_level"             : 2,
                            "save_h5_files_in_folder"            : true,
                            "output_control_type"                : "step",
                            "output_frequency"                   : 1,
                            "nodal_solution_step_data_variables" : ["VELOCITY","PRESSURE","MESH_DISPLACEMENT","MESH_VELOCITY"]
                        }
~~~

which we copied from the tests in the empire_app, however this (obviously) does not work since the file
 hdf5_output_process does not exist.

any help would be greatly appreciated

**Comment by philbucher** [comment]
Sorry, what you are referring to was an intermediate solution it obviously didn’t make it to master :)
Here is an example of the xdmf output process. This process writes the h5 files and the xdmf file to visualize it in Paraview
Is this what you need?
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/HDF5Application/tests/test_hdf5_processes.py#L97

**Comment by jcotela** [comment]
In case you need other examples (hdf5 only, I did not test is with the xdmf), these tests should be up to date:
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/tests/adjoint_fluid_test.py
