### ISSUE TITLE
Question on the accuracy of the test server

### ISSUE THREAD

**Issue by vryy** [KratosMultiphysics/Kratos#4311]
Hi

The commit 24c396870ef3ca02b1961a567ce071152d74c0b2 apparently broke the file utilities/math_utils.h because the code below is clearly wrong

    static void Solve(
           MatrixType A,
          VectorType& rX,
          const VectorType& rB
         )
      {
    #ifdef KRATOS_USE_AMATRIX   // This macro definition is for the migration period and to be removed afterward please do not use it
            AMatrix::LUFactorization<MatrixType, DenseVector<std::size_t> > lu_factorization(rA); //////  ERROR HERE
            double determinant = lu_factorization.determinant();
            KRATOS_ERROR_IF(std::abs(determinant) <= ZeroTolerance) << "Matrix is singular: " << rA << std::endl;
            rX = lu_factorization.solve(rB);
    #else
    ...
    #endif

This is exactly the error i have when compiling the updated Kratos. I'm not sure why the test server compiled this commit successfully.

**Comment by jcotela** [comment]
I believe that the test machine does not define `KRATOS_USE_AMATRIX` at the moment... This would explain the discrepancy.

However, I do not think that kratos as a whole is ready for defining this macro yet (only the core and a few applications support amatrix at the moment, and your experience shows that this is not even true for the core right now).

**Comment by vryy** [comment]
If I recalled correctly, it is activated sometimes ago. In any case, if it is not fully supported in the core, then shall not be in the applications.

**Comment by pooyan-dadvand** [comment]
Sorry @vryy for miscommunication. We had to drop the support for AMatrix in release due to the #3980 in which I am working on a solution. I have updated the release note about this.
