### ISSUE TITLE
StructMech Explicit Time Int. "AdvanceInTime"

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#4322]
Hi I need the explicit time integration to also use "AdvanceInTime" or a similar option to use it in a strong coupling algorithm. 
At the moment the strategy calls `SolveSolutionStep`, which then calls `Update` in the scheme. Which always proceeds in time. For a stroung coupling algorithm I would need a possibility to repeat a certain time step several times. 
I'll work on this now, but I thought you might already have good ideas on how to realize this.

Klaus

**Comment by loumalouomega** [comment]
Why closed?

**Comment by KlausBSautter** [comment]
I thought I found the problem .... I did not :D so we might reopen this.

**Comment by KlausBSautter** [comment]
I think we have to rewrite `UpdateTranslationalDegreesOfFreedom` to sth. which uses
`        const array_1d<double, 3>& r_previous_velocity = itCurrentNode->FastGetSolutionStepValue(VELOCITY, 1);

this to update the current entities

**Comment by KlausBSautter** [comment]
+ rewrite mTime....
`mTime.Current = r_current_process_info[TIME];`
`mTime.Delta = r_current_process_info[DELTA_TIME];`
`mTime.Middle   = mTime.Current - 0.50*mTime.Delta;`
`mTime.Previous = mTime.Current - 1.00*mTime.Delta;`
`mTime.PreviousMiddle = mTime.Middle - 1.00*mTime.Delta;`

**Comment by KlausBSautter** [comment]
ok I think I made it work. I'll create a PR
