### ISSUE TITLE
Inconsistent behaviour of the KRATOS_CHECK_NEAR macro

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#4326]
Today I was checking a test with @philipkalkbrenner  and we noticed that the KRATOS_CHECK_NEAR  returns OK when one of the numbers that is compared is NaN! @roigcarlo I suppose that we should add some is_nan check or something?
Regards

**Comment by philbucher** [comment]
maybe related to the recent changes of @jcotela

**Comment by loumalouomega** [comment]
std::isnan doesn't work properly in release according to my experience

**Comment by jcotela** [comment]
My experience matches that of @loumalouomega... I think it is because the isnan detection is something that just does not work when using one of the optimization flags (maybe ffast-math? I do not remember precicely)

**Comment by RiccardoRossi** [comment]
i think you should force ieee754 for isnan to work (but i am not fulky
sure...)

maybe we can force it in superdebug
