### ISSUE TITLE
Implementation committee meeting day

### ISSUE THREAD

**Issue by GuillermoCasas** [KratosMultiphysics/Kratos#4327]
It seems that most of us prefer to meet on Wednesdays instead of Mondays. I do not mind myself, but I do require then to move the starting time to 15:00, since I have a fixed project meeting at 16:00 on Wednesdays. Can you all confirm that this works for you or else propose an alternative?

Thanks to all the @KratosMultiphysics/implementation-committee members.

**Comment by AlejandroCornejo** [comment]
I think that if you have an appointment at 16 it's even better so we cannot spend more time than necessary.
Good for me

**Comment by loumalouomega** [comment]
Fine for me

**Comment by GuillermoCasas** [comment]
No complains so from now on the meeting will be held on Wednesdays, 15:00.
