### ISSUE TITLE
Error in TestRunner

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4328]
Sometimes (I don't know what it depends on) I get the following after the tests ran when using `run_tests.py` from the core:
~~~
Exception in thread Thread-10:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "run_tests.py", line 136, in RunTestSuit
    print(process_stdout.decode('ascii'), file=sys.stdout)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe0 in position 901: ordinal not in range(128)
~~~

@roigcarlo any idea where this comes from?

**Comment by roigcarlo** [comment]
Mm I know what the error is about but can't link it to anything.
Basically it says that is trying to read an invalid ascii character. For example from a malformed string (projectProperties, mdpa's, serializations, etc...)

**Comment by philbucher** [comment]
ok thx, I will check again in more detail once it happens again

I never saw it before #3562 thats why I was asking

**Comment by roigcarlo** [comment]
Hum I will take a look to, maybe there is a problem parsing the process output on fail

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by roigcarlo** [comment]
No

**Comment by philbucher** [comment]
I had this problem in a similar context and found this to be helpful:
https://stackoverflow.com/a/51302441

**Comment by philbucher** [comment]
closing as I think this works now

> I had this problem in a similar context and found this to be helpful:
> https://stackoverflow.com/a/51302441

https://github.com/philbucher/KratosSalomePlugin/pull/79
Here it works fine now for me
