### ISSUE TITLE
[CompressiblePotentialFlowApp] test failing

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4329]
the following test fails on my machine:
~~~
Ran 4 of 547 test cases in 0.000437208s. 1 failed:
    TestCompressiblePotentialFlowElement_CalculateLocalSystemWake Failed with message: 
        Error: Check failed because RHS(0) = -3 is not near to 0.5 = 0.5 within the tolerance 1e-07
in /home/philippb/software/Kratos_prod/applications/CompressiblePotentialFlowApplication/tests/cpp_tests/test_compressible_potential_element.cpp:124:virtual void Testing::TestCompressiblePotentialFlowElement_CalculateLocalSystemWake::TestFunction()
~~~

**Comment by marcnunezc** [comment]
I ran the tests in the master in Release and they are working in my machine.

Are you in FullDebug?

**Comment by philbucher** [comment]
I tried in release

**Comment by inigolcanalejo** [comment]
I just tried in release and they also go through... it would be interesting to know why they are failing in your machine

**Comment by marcnunezc** [comment]
I also tried in FullDebug and the tests work as well.
> I just tried in release and they also go through... it would be interesting to know why they are failing in your machine

Indeed! How can we check this? It would be useful to see which LHS and RHS you are getting in the test after doing CalculateLocalSystem().

**Comment by philbucher** [comment]
@inigolcanalejo maybe we can check together

**Comment by pooyan-dadvand** [comment]
I would check for clear valgrind

**Comment by inigolcanalejo** [comment]
> @inigolcanalejo maybe we can check together

Sure!

**Comment by philbucher** [comment]
I think this is solved, I will reopen if I find more problems
