### ISSUE TITLE
restart functionality with mpi

### ISSUE THREAD

**Issue by vryy** [KratosMultiphysics/Kratos#433]
Dear folks

I would like to ask if someone has experience using the restart/serializer in Kratos with MPI?

In my case, it works well for serial (OpenMP) but gives "MemoryError" when using with MPI. It can be that the Kratos kernel I'm using missing some patches. However, I just want to confirm if that works in the current Kratos version?

Thanks
Bui

**Comment by jcotela** [comment]
I have used it for CFD problems, but it is not complete. The main problem is that there is no serialization support for the MPI communication data structure (coloring, local nodes, ghost nodes,...). What I had to do is to rebuild the communicator data using the ParallelFillCommunicator tool after loading the restart file.

**Comment by vryy** [comment]
Thanks Jordi. That's useful. So you successfully loaded the restart file and then rebuild the communicator data. But I'm not able to load them at first time. Any idea?

**Comment by jcotela** [comment]
So what is failing is the load operation itself? It may be that some of the components you are saving has badly implemented save/load methods. Have you tried using a more verbose serialization option? (SERIALIZER_TRACE_ALL, SERIALIZER_TRACE_ERROR) as an argument to the save() and load() calls? That may give you a better idea of what's wrong. (Note that you have to use the same option for both the save and the load calls to get a compatible file)

**Comment by vryy** [comment]
Hi @jcotela , how to use the SERIALIZER_TRACE_ALL & SERIALIZER_TRACE_ERROR? Seem like it's passed to the constructor of Serializer class. Can we set it at runtime?

**Comment by jcotela** [comment]
Yes, the trace arguments are passed to the constructor of the Serializer class. You can set it at runtime if you construct the serializer object from python. If you are using the serializer object from within some other C++ object, you can either set it at compile time or pass it as an argument to the corresponding Python call.

The Serializer Trace arguments are already exported to python so, from your python code, it is just a matter of passing one of `SERIALIZER_NO_TRACE`, `SERIALIZER_TRACE_ERROR` or `SERIALIZER_TRACE_ALL` to the serializer constructor (or to the function that constructs it)

**Comment by vryy** [comment]
Thanks. I ran with SERIALIZER_TRACE_ERROR. One process throws this message:

RuntimeError: In line 1 the trace tag is not the expected one:
    Tag found : A���L��
    Tag given : ModelPart

Do you know which could be the reason?

**Comment by jcotela** [comment]
This is on Serializer.load(...) right? It is strange because it does not seem to be parsing the file correctly. Can you double-check that you saved the restart file using the same trace type (so also doing the Serializer.save() with a serializer instance constructed with SERIALIZER_TRACE_ERROR)?

**Comment by jcotela** [comment]
Hi Bui, I've been thinking about this some more... Since you said that the code works fine on OpenMP, I'm not so sure it is an implementation error. Just to be sure: you are saving and reading a different restart file for each MPI process, right? (I just append the mpi rank to the base filename)

**Comment by vryy** [comment]
Hi Jordi, you are right. I saved the restart file to model_name_1.0001.rest, model_name_1.0002.rest, ...  The save is flawlessly. For loading each process then reads the corresponding restart file based on rank. As designed, each .rest file containing a model_part for a partition, hence the error above is quite strange.

**Comment by jcotela** [comment]
Hi Bui, it seems to me you are doing everything right, so I'm not sure what else to suggest. Could you send me a small example exhibiting this error so that we can try to debug it? Thanks!

**Comment by vryy** [comment]
Hi Jordi, I will try to reproduce the error in the small example. Currently, the problem occurs with big model.

**Comment by philbucher** [comment]
Is this solved?

**Comment by pooyan-dadvand** [comment]
I will close this due to inactivity. @vryy feel free to reopen it if there are new advances.
