### ISSUE TITLE
Is there anyone who are using Kratos in Civil Engineering?

### ISSUE THREAD

**Issue by xuhenry** [KratosMultiphysics/Kratos#4335]
Hello everyone,
     Is there anyone who are using Kratos in Civil Engineering? Such as the excavation of the tunnel, deep foundation, the interaction between the pile and soil   and so on.
   Thanks a lot!
Best regards,
Henry

**Comment by GuillermoCasas** [comment]
At least I know of @joaquinirazabal, who has worked a lot on the simulation of rail track ballast using DEM.

**Comment by RiccardoRossi** [comment]
just to name a few:
@ipouplana has experience with Biot model
@antonialarese worked on the simulation of pile driving into soil by the MPM method
@Vahid-Galavi is expert in geotechnics

**Comment by xuhenry** [comment]
@GuillermoCasas @RiccardoRossi Many thanks for your reply.
Thanks a lot!

**Comment by philbucher** [comment]
Closing since inactive
