### ISSUE TITLE
[core] Two instances of GidIO giving segmentation fault.

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#4337]
The problem appears when the two instances use different template paramenters for GidIO. Then, they are instances of different classes, so the static variable msLiveInstances becomes useless. When the external library GidPost is finalized, it is done twice, because msLiveInstances goes to zero when the first GidIO is destroyed. The destruction of the second GidIO triggers the second finalization of GidPost and the SegFault shows up.

**Comment by maceligueta** [comment]
The proposal to fix this is to create an independent singleton with msLiveInstances.
Any comment on where this variable should go is welcome @pooyan-dadvand  @jcotela  @roigcarlo .

**Comment by GuillermoCasas** [comment]
We will be discussing this also in the @KratosMultiphysics/implementation-committee

**Comment by pablobecker** [comment]
@KratosMultiphysics/implementation-committee has reached consensus. We agree with @maceligueta  that the singleton solution is the way to go. @maceligueta , will you take care of this, otherwise someone from the @KratosMultiphysics/implementation-committee will implement this.

**Comment by maceligueta** [comment]
@pooyan-dadvand  warned me about the difficulty of coding a good singleton. Will talk to him and proceed. Thanks.

**Comment by philbucher** [comment]
what is the status of this?

**Comment by maceligueta** [comment]
It is still pending. I did not have time to implement the singleton.

**Comment by AlejandroCornejo** [comment]
ping @maceligueta

**Comment by maceligueta** [comment]
@pooyan-dadvand , I just thought that I could implement a base class for `GidIO` called `GidIOBase`, which is **not** a class template, but contains the `msLiveInstances` static member variable. Then, all the instantiations of GidIO (templated ) would use the same `msLiveInstances` variable from `GidIOBase`.

**Comment by pooyan-dadvand** [comment]
This would be a clean solution

**Comment by philbucher** [comment]
@maceligueta this is solved now isn't it?

**Comment by roigcarlo** [comment]
If I am not mistaken, that should be solved by #6212 yes.

**Edit**:  I mean the leftovers that may still have been there, the issue perse was solved in #5653

**Comment by maceligueta** [comment]
I am not 100% sure that everything was fixed, but since I am not getting info about misbehaviour lately, I would close. 
The problem here is that people find workarounds and sometimes the bugs is still there. Let's hope this is not the case and let's close.
Referencing @AlejandroCornejo and @AFranci , who first detected anomalies. Please guys, let us know if the problem was totally fixed or you are bypassing it!
