### ISSUE TITLE
Problem with adjoint "auto"-settings

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#4339]
Assume primal settings, where the  "input_type"  is "use_input_model_part". Given that, creating a response function where the adjoint settings are automatically translated as introduced in #3962 will lead to a failing initialization of the adjoint problem. It seems the adjoint analysis does not to import / read any model part then and remains empty. The response settings I use are:

            "kratos_response_settings":{
                "response_type"     : "adjoint_local_stress",
                "gradient_mode"     : "semi_analytic",
                "step_size"         : 1.0e-8,
                "traced_element_id" : 22147,
                "stress_type"       : "VON_MISES_STRESS",
                "stress_treatment"  : "mean",
                "primal_settings"   : "primal_parameters.json",
                "adjoint_settings"  : "auto",
                "sensitivity_settings" : {
                    "sensitivity_model_part_name"     : "Parts_solid",
                    "nodal_sensitivity_variables"     : ["SHAPE"],
                    "element_sensitivity_variables"   : [],
                    "condition_sensitivity_variables" : [],
                    "build_mode": "static"
                }
            },

**Comment by armingeiser** [comment]
Hm i see the problem. Thats actually not easy to solve, i need to think about it.

**Comment by dbaumgaertner** [comment]
will be solved by #4364

**Comment by philbucher** [comment]
closing since the corresponding PR seems to be merged
please reopen if otherwise
