### ISSUE TITLE
[Wiki] New tutorial: multiple cases execution using PyCOMPSs

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/Kratos#4352]
Dear all,

This issue is just to inform the Kratos users and developers that there is a new tutorial in the TODOs Kratos wiki: [How to run multiple cases using PyCOMPSs](https://github.com/KratosMultiphysics/Kratos/wiki/How-to-run-multiple-cases-using-PyCOMPSs).

This tutorial guides the user to run different cases of a problem, using the PyCOMPSs library developed at the Barcelona Supercomputing Center.

Feel free to report here suggestions or corrections of the tutorial.

Riccardo

**Comment by RiccardoRossi** [comment]
@marandra i think this can be very interesting for you guys

**Comment by RiccardoRossi** [comment]
(btw, @riccardotosi thx for the effort!)

**Comment by philbucher** [comment]
can this be closed?
