### ISSUE TITLE
VisualStudio resets the libs folder in the KratosInstall

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#4356]
Hello!
I've pulled the master branch and I'm getting the following error regarding the **ExternalSolversApplication**:

Traceback (most recent call last):
  File "KratosFemDemCoupledApplication.py", line 4, in <module>
    import CouplingFemDem
  File "D:\KratosInstall\applications\FemToDemApplication\python_scripts\CouplingFemDem.py", line 4, in <module>
    import MainFEM_for_coupling as FEM
  File "D:\KratosInstall\applications\FemToDemApplication\python_scripts\MainFEM_for_coupling.py", line 3, in <module>
    import MainFemDem
  File "D:\KratosInstall\applications\FemToDemApplication\python_scripts\MainFemDem.py", line 10, in <module>
    import KratosMultiphysics.ExternalSolversApplication as KratosSolvers
  File "D:\KratosInstall\KratosMultiphysics\ExternalSolversApplication\__init__.py", line 3, in <module>
    from KratosExternalSolversApplication import *
ImportError: DLL load failed: No se puede encontrar el módulo especificado.
KRATOS TERMINATED WITH ERROR

Anyone knows what's happening?
Thank you!
@philbucher

**Comment by philbucher** [comment]
hm no clue...
For me it works, compiling master all the time
Also I am not too familiar with this app

Do you delete the old libs before recompiling?

If this doesn't work I recommend the following steps ;)
1. https://purplemonkeydishwasher.co.uk/2019/01/30/the-ubuntu-installation-guide/
2. https://github.com/KratosMultiphysics/Kratos/wiki/Linux-Build

**Comment by AlejandroCornejo** [comment]
It seems that recompiling everything works! thank you and sorry fot the inconvenience @philbucher

**Comment by AlejandroCornejo** [comment]
It is weird... The problem is with VisualStudio, when compiling the code it resets the libs folder and I have to copy the .dll everytime I compile Kratos! @roigcarlo Do you know it is performing in this way?
Thank you

**Comment by philbucher** [comment]
this happens after #4314 

Reason is to remove possible "old" libraries e.g. if you no longer compile an application it should no longer be accessible

In windows you have additional libraries in this folder?

**Comment by AlejandroCornejo** [comment]
Yes! After the compilation we need to copy several files... It is explained
in the windows build in the wiki. Maybe we should review this

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/53890823-419a9f80-4029-11e9-95f6-97f540c30806.png)

**Comment by roigcarlo** [comment]
Uh... yep. The changes we made to the libs folder will cause this. I will update the wiki now.

From now on if you don't want to copy the libs every time you will need to add the ming-gw and the folder with blas lapack to the system path.
https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install#post-compilation

Edit: @loumalouomega  I've deleted the imagine because I want to to keep this one technical as many people could eventually have this problem

**Comment by philbucher** [comment]
we could add a "whitelist" when on Windows ...?

**Comment by roigcarlo** [comment]
We could, but people in will will have the problem with the old compiled libs again. 
Or I could force cmake to install the requeired libs in the folder. I can do it without any changes for blas and lapack but I would need a new -DMINGW_DIRECTORY in the configure for the rest

**Comment by AlejandroCornejo** [comment]
thank you for your time! Shall i close the issue?

**Comment by philbucher** [comment]
> configure

I meant you could delete everything except some libblas and lapack (and maybe some others, you can control what is on the whitelist)

**Comment by roigcarlo** [comment]
Leave it open until Friday just in case.

@philbucher I can do it for the recommended versions of the wiki, but if someone uses anything else will have the same problem :S

**Comment by philbucher** [comment]
ok I see
Well then at least it should be documented properly

**Comment by roigcarlo** [comment]
> ok I see
Well then at least it should be documented properly

:+1: Already added in the wiki, but I will make a PR with the implementation of the whitelist solution

**Comment by loumalouomega** [comment]
Is this solved?

**Comment by roigcarlo** [comment]
> Leave it open until Friday just in case.
