### ISSUE TITLE
Possible bugs in MPICommunicator

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#4358]
I ran a static analysis while looking at #1277. It flagged some suspicious lines which might be bugs. I didn't want to comment in #1277 since these lines are not part of the PR.

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/mpi/includes/mpi_communicator.h#L352
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/mpi/includes/mpi_communicator.h#L367
> Casting from double* to integer* is not portable due to different binary data representations on different platforms.

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/mpi/includes/mpi_communicator.h#L196
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/mpi/includes/mpi_communicator.h#L223
> Member variable 'MPICommunicator::mpVariables_list' is not initialized in the constructor

Can you take a look?

**Comment by roigcarlo** [comment]
Thx @msandre I'll take a look asap

**Comment by jcotela** [comment]
@msandre Thanks for the report! @roigcarlo the second reported issue I have already fixed in a WIP branch I have (I fixed the copy constructor, the assignment one I deleted, since I didn't really see a use case for that, the communicator is tightly linked to the modelpart, I believe it does not make sense to assign it around):
https://github.com/KratosMultiphysics/Kratos/compare/mpi/communicator-update

**Comment by roigcarlo** [comment]
Also for the record, I suppose the first one could be solved making a static_cast<unsigned int>. @msandre which static analyzer are you using? Just to test it in my machine before submitting any PR

**Comment by msandre** [comment]
I used cppcheck with some options (see the script https://github.com/msandre/tools/blob/master/kratos/run_cpp_check.sh). I can run it for you if you send me your branch name.

**Comment by roigcarlo** [comment]
Thx @msandre I prefer to set it up myself for future use. But I don't manage to run I will send you the branch
