### ISSUE TITLE
Math Utils are not compiling with AMatrix

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#4361]
@pooyan-dadvand @philbucher @loumalouomega 
I tried today to compile the core using AMatrix and I got an error in math utils, more specifically in the InvertMatrix method. This method uses a template in order to be able to use it with both BoundedMatrix and Matrix. Besides, it uses inside a resize to make sure that sizes of original and inverted matrices are the same. The problem is that AMatrix does not allowed to do a resize of a BoundedMatrix as it is considered an inefficiency.
Maybe cleanest solution would be to throw an error when sizes of input and output matrices do not match. What do you think?

**Comment by loumalouomega** [comment]
Well that is a behavior change and if we do that change many changes should be changed, otherwise tons of tens will not run anymore (abusing of the hyperbolic language)

**Comment by ddiezrod** [comment]
You are completely right, what do you propose then?

**Comment by loumalouomega** [comment]
We can use the AMATRIX macro to print a warning as part of a transition. Then the people responsible should change that. According to my experience developers don't use to do that, so one day we will do it all at once...

**Comment by pooyan-dadvand** [comment]
I agree that the solution above with behaviour change is more complicated to be accomplished

Another solution would be to have two template version of invert matrix one with `BoundedMatrix<TDataType>` without resize, and another one with `Matrix<TDataType>` as argument with resize.

**Comment by loumalouomega** [comment]
Adding a dummy resize method for BoundedMatrix is a no go?

**Comment by RiccardoRossi** [comment]
+1 for the dummy rrsize, throwing an error if actually used with different
sizes
