### ISSUE TITLE
Deriving a class and issue with execution, i.e., ImportError: dynamic module does not define module export function

### ISSUE THREAD

**Issue by Glovedsasquatchcodes** [KratosMultiphysics/Kratos#4370]
I have been trying to execute a very simple example case through derived class obtained from an existing class (application) in the Kratos directory. The example case works perfectly fine when running with the base application. However, with the derived application, it tends to throw an error. Similar error occurs if I try to open a python shell and import the application, namely:

`ImportError: dynamic module does not define module export function (PyInit_Name_of_Derived_Application)`

While I looked up for the error on the internet and Kratos Issues page, most common solution was with regards to `$PYTHONPATH` or `$LD_LIBRARY_PATH`. I have checked all the path configuration steps that is required for KratosMultiphysics to work seamlessly. 

Could someone suggest places or possible error? Kindly also guide me the necessary checkpoints that one must look at when deriving an application from an existing one within the Kratos directory.

**Comment by roigcarlo** [comment]
HI @Glovedsasquatchcodes 

I would need little bit more of info to help you.
- What application are you deriving from 
- Is your new application divided into core / interface or you compiling a single .so?
- What are you linking the application against?

You can find all this info in the `CMakeLists.txt`, so if you want just copy the file here.

**Comment by Glovedsasquatchcodes** [comment]
Hi @roigcarlo ,
I will try my best to answer the question and seek clarifications for the ones I have doubt.

a) and b)
 I am trying to derive from ContactStructuralMechanicsApplication (But looking at your second question I checked the following path `/home/meinhard/Software/Kratos/cmake_build/applications` and compared the folders for StructuralMechanicsApplication and ContactStructuralMechanicsApplication  and realized that the latter has been derived as an interface to the former because *ContactStructuralMechanicsApplication* does not have a corresponding core.so file available for it. Thus my question from this realization would be (and sorry if I sound foolish here): Is it possible to derive an application out of an existing one which is derived only as an interface from another application with a core? If so how is the procedure to specify the directory in the CMakeList.txt file, i.e., in the cmake file how do these lines change or modify:
`define library Kratos which defines the basic python interface
pybind11_add_module(KratosContactStructuralMechanicsApplication MODULE THIN_LTO ${KRATOS_CONTACT_STRUCTURAL_MECHANICS_APPLICATION_SOURCES} ${KRATOS_CONTACT_STRUCTURAL_MECHANICS_TESTING_SOURCES})

target_link_libraries(KratosContactStructuralMechanicsApplication PRIVATE KratosCore KratosStructuralMechanicsCore)
set_target_properties(KratosContactStructuralMechanicsApplication PROPERTIES COMPILE_DEFINITIONS "CONTACT_STRUCTURAL_MECHANICS_APPLICATION=EXPORT,API")
set_target_properties(KratosContactStructuralMechanicsApplication PROPERTIES PREFIX "")`
)

*Also, could you please elaborate a little on how the application structure, i.e., core and interface work. A part of this question is because if I configure the new application with the variables of the derived application, it threw errors. So, why should this be if applications have different .so files?*

c) I do not really understand the question very clearly but as far as my understanding goes I was trying to link the application as an interface to another existent application which is derived as an interface (probably) to a base application.
Something like this: 
StructuralMechanicsApplication (base app. existing as core) 
                                                ^
                                                 |
                                                 |
 ContactStructuralMechanicsApplication   (already existing but derived as interface) 
                                                ^
                                                 |
                                                 |
OptContactStructuralMechanicsApplication (new application being derived as interface)

[CMakeLists.txt](https://github.com/KratosMultiphysics/Kratos/files/2946611/CMakeLists.txt)

**Comment by loumalouomega** [comment]
Yes I never separated Core from application because I never imagine to anyone to derive from ContactStructuralMechanicsApplication

**Comment by loumalouomega** [comment]
One sec

**Comment by loumalouomega** [comment]
Application separated on  #4399
