### ISSUE TITLE
[ShapeOpt] replace shape optimization conditions with default conditions from the core

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#4387]
@armingeiser side question, I though you no longer need the ShapeOptCondition?

_Originally posted by @philbucher in https://github.com/KratosMultiphysics/Kratos/pull/4338_

As the ShapeOptimizationConditions are only used to be able to generate a geometry from the mdpa file, but do not contain any meaningful code, they could be replaced with the default conditions from the core. 

See variables.cpp:
```
      mPointCondition2D1N( 0, GeometryType::Pointer(new Point2D<NodeType >(GeometryType::PointsArrayType(1)))),
      mPointCondition3D1N( 0, GeometryType::Pointer(new Point3D<NodeType >(GeometryType::PointsArrayType(1)))),
      // Line conditions
      mLineCondition2D2N( 0, GeometryType::Pointer(new Line2D2<NodeType >(GeometryType::PointsArrayType(2)))),
      mLineCondition2D3N( 0, GeometryType::Pointer(new Line2D3<NodeType >(GeometryType::PointsArrayType(3)))),
      mLineCondition3D2N( 0, GeometryType::Pointer(new Line3D2<NodeType >(GeometryType::PointsArrayType(2)))),
      mLineCondition3D3N( 0, GeometryType::Pointer(new Line3D3<NodeType >(GeometryType::PointsArrayType(3)))),
      // Surface conditions
      mSurfaceCondition3D3N( 0, GeometryType::Pointer(new Triangle3D3<NodeType >(GeometryType::PointsArrayType(3)))),
      mSurfaceCondition3D6N( 0, GeometryType::Pointer(new Triangle3D6<NodeType >(GeometryType::PointsArrayType(6)))),
      mSurfaceCondition3D4N( 0, GeometryType::Pointer(new Quadrilateral3D4<NodeType >(GeometryType::PointsArrayType(4)))),
      mSurfaceCondition3D8N( 0, GeometryType::Pointer(new Quadrilateral3D8<NodeType >(GeometryType::PointsArrayType(8)))),
      mSurfaceCondition3D9N( 0, GeometryType::Pointer(new Quadrilateral3D9<NodeType >(GeometryType::PointsArrayType(9)))),
```

@dbaumgaertner is there any objection against this?

**Comment by dbaumgaertner** [comment]
First of all yes, they are still needed when you want to do something with normals within the optimization algorithms. However, these conditions are really just placeholders. So any other surface condition does the same job. Thinking about it, it would make actually sense to replace these with the default core conditions! So no objections. One would only need to make the effort and adjust the tests and test examples in the ShapeOptApp.

**Comment by armingeiser** [comment]
:+1: fine, i will create a PR.
