### ISSUE TITLE
_GetScheme to avoid duplicated code

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#4390]
In PR #3714 the `PFEM2NavierStokesMonolithicSolver` that derives from `NavierStokesMonolithicSolver` there is some copied code. An implementation of `_GetScheme` and `_GetBuilderAndSolver` methods in the base class would reduce that necessary code duplication.
I suggest to discuss that on this issue to unblock the PR #3714

**Comment by philbucher** [comment]
I think this is coming in the next wave of refactoring of the fluid-solvers, at least @jcotela told me this

**Comment by miguelmaso** [comment]
thanks. In that case, can we close that issue?

**Comment by philbucher** [comment]
closing, added it to the list
