### ISSUE TITLE
[Core] Behaviour of check_scalar_to_nodes_process

### ISSUE THREAD

**Issue by GuillermoCasas** [KratosMultiphysics/Kratos#4413]
This process is used to compare a nodal quantity to its expected analytical value at the current time. Why is the following line like it is in the definition of ExecuteFinalizeSolutionStep?
` current_time = process_info[KratosMultiphysics.TIME] - process_info[KratosMultiphysics.DELTA_TIME]
`
Note that the process is launched after SolveSolutionStep() is called, so the current time step should be understood as that at the updated state of the simulation.

And indeed, I have found this because I could only make the test I was running work after replacing the line above with
`current_time = process_info[KratosMultiphysics.TIME]`

Can anyone explain why the process is defined as such and could we discuss the possibility of modifying its behaviour as I did? Porbably the @KratosMultiphysics/implementation-committee and the @KratosMultiphysics/design-committee will have something to comment here.

**Comment by loumalouomega** [comment]
I created the process, and I assume that if I did such a way it was due a good reason... (I cannot remember)

**Comment by loumalouomega** [comment]
@GuillermoCasas Can you try to apply your suggested change and run the tests?

**Comment by GuillermoCasas** [comment]
Sure!

**Comment by GuillermoCasas** [comment]
@loumalouomega I have run the KratosCore tests and the ones from the applications I had compiled (ExternalSolvers, FluidDynamics and DEM) and they run. Then I have searched for uses of this process where the time is varied (otherwise it does not matter when you evaluate). I have only found four jsons in StructureMechanicsApplication where the process is used with a time-dependent field and none of the check_vector_components_to_nodes_process.py version. Could you run the StructuralMechanicsApp tests with the modification I suggest?

**Comment by loumalouomega** [comment]
I can, let me a sec

**Comment by loumalouomega** [comment]
~~~
======================================================================
FAIL: test_execution (structural_mechanics_test_factory.RigidSphereFailing)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vicente/src/Kratos/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 55, in test_execution
    self.test.RunSolutionLoop()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 66, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/check_scalar_to_nodes_process.py", line 124, in ExecuteFinalizeSolutionStep
    self.assertAlmostEqual(self.value, value, self.tolerance_rank)
AssertionError: -1.4715000000000003 != -0.4905000000000001 within 8 places

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.RigidSphereFailingExplicit)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vicente/src/Kratos/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 55, in test_execution
    self.test.RunSolutionLoop()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 66, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/check_scalar_to_nodes_process.py", line 124, in ExecuteFinalizeSolutionStep
    self.assertAlmostEqual(self.value, value, self.tolerance_rank)
AssertionError: -0.000981 != 0.0 within 8 places

======================================================================
FAIL: test_execution (structural_mechanics_test_factory.SimpleMeshMovingTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vicente/src/Kratos/applications/StructuralMechanicsApplication/tests/structural_mechanics_test_factory.py", line 55, in test_execution
    self.test.RunSolutionLoop()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 66, in RunSolutionLoop
    self.FinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/analysis_stage.py", line 141, in FinalizeSolutionStep
    process.ExecuteFinalizeSolutionStep()
  File "/home/vicente/src/Kratos/kratos/python_scripts/check_scalar_to_nodes_process.py", line 124, in ExecuteFinalizeSolutionStep
    self.assertAlmostEqual(self.value, value, self.tolerance_rank)
AssertionError: 0.0001 != 5e-05 within 16 places

----------------------------------------------------------------------
Ran 221 tests in 751.796s

FAILED (failures=3, skipped=9)
~~~

**Comment by loumalouomega** [comment]
All of these tests are mine, and probably the reason the time is computed in sucha a way.

**Comment by GuillermoCasas** [comment]
So could you check why this is so? It seems incoherent to compare at the end of the solution step the solution to an old value (the analytic value a time step before).

**Comment by GuillermoCasas** [comment]
It could be a matter of simply redefining your analytic solution...

**Comment by loumalouomega** [comment]
> It could be a matter of simply redefining your analytic solution...

Adding the delta time perhaps?...

**Comment by loumalouomega** [comment]
> So could you check why this is so? It seems incoherent to compare at the end of the solution step the solution to an old value (the analytic value a time step before).

Indeed but the analytic solution is the correct one, maybe the error is on other place...

**Comment by GuillermoCasas** [comment]
It looks like your solution is one time step ahead. The initial value should correspond to t=0, so after the first SolveSolutionStep you should get a value that is already different from the initial solution. If you apply the process as it is you will be comparing the changed solution to the initial solution.

**Comment by GuillermoCasas** [comment]
This issue has been soved in #4492.
