### ISSUE TITLE
Ensure that "Examples" work

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#4421]
@KratosMultiphysics/all please ensure that your "examples" in the corresponding repository work correctly with the release version (branch Release 7.0). This is crucial for things that enter in the release.

Please thick the corresponding box once it is done (and add new boxes/new poeple named to correct what i missed)

- [x] conjugate_heat_transfer @rubenzorrilla
- [x] fluid_dynamics 	@rubenzorrilla @jcotela @msandre 
- [x] fluid_structure_interaction @rubenzorrilla 
- [ ] structural_mechanics @philbucher @KlausBSautter @loumalouomega @AlejandroCornejo 
- [x] contact_structural_mechanics 	@loumalouomega 
- [x] dem 	@maceligueta
- [ ] swimming_dem @GuillermoCasas 
- [x] particle_mechanics @bodhinandach @antonialarese 
- [x] poromechanics @ipouplana 
- [x] pfem2_application @dcagri @pablobecker @miguelmaso

**Comment by antonialarese** [comment]
@RiccardoRossi particle_mechanics example is working fine with the branch release 7.0

- particle_mechanics  @bodhinandach @antonialarese

**Comment by RiccardoRossi** [comment]
thx @antonialarese

**Comment by rubenzorrilla** [comment]
To what concerns the fluid_dynamics, only one example is not working. It should work as soon as discussion #4121 is closed.

**Comment by ipouplana** [comment]
All examples in Poromechanics are working ;)

**Comment by rubenzorrilla** [comment]
> To what concerns the fluid_dynamics, only one example is not working. It should work as soon as discussion #4121 is closed.

@adityaghantasala modified how the periodic BCs are imposed in this particular case to make the failing test work.

**Comment by RiccardoRossi** [comment]
@adityaghantasala why the example was not working? the BlockB&S should be able to do it correctly according to what we spoke before merging

**Comment by adityaghantasala** [comment]
@RiccardoRossi this is solved now ... yes you are correct it should and is working properly. 
it is because of this flag and if condition ... I solved it ... !! 

https://github.com/KratosMultiphysics/Kratos/blob/d274c0596833d653e4b1996ae60dc1d1a921e8c9/applications/FluidDynamicsApplication/python_scripts/navier_stokes_solver_vmsmonolithic.py#L335

**Comment by RiccardoRossi** [comment]
thx @adityaghantasala

**Comment by RiccardoRossi** [comment]
@rubenzorrilla @philbucher @KlausBSautter @loumalouomega @AlejandroCornejo
@loumalouomega
 @maceligueta
 @GuillermoCasas
 @bodhinandach @antonialarese
 @ipouplana
 @dcagri @pablobecker @miguelmaso

ping! (please update the check list above when you are done)

**Comment by RiccardoRossi** [comment]
(sorry i guess i pinged some people that already did the check in the list...be patient :-) )

**Comment by GuillermoCasas** [comment]
@RiccardoRossi: I do not think SwimmingDEMApp goes into the release.

**Comment by GuillermoCasas** [comment]
By the way, I just tried `python3 kratos_run_all_benchmarks.py` in kratos/kratos/test_examples and that does not run: 
> ImportError: No module named 'benchmarking'

Is that meant to be so?

**Comment by philbucher** [comment]
@GuillermoCasas yes, the benchmarking-stuff was removed => #2769

**Comment by philbucher** [comment]
I have not removed `test_examples` from the core yet, thx for the reminder

**Comment by loumalouomega** [comment]
Mines are done

**Comment by RiccardoRossi** [comment]
ping @philbucher @KlausBSautter @loumalouomega @AlejandroCornejo for Structural Mechanics

ping @maceligueta  for DEM

**Comment by maceligueta** [comment]
I just marked DEM. However, swimming DEM examples do not work. Referencing @GuillermoCasas.
