### ISSUE TITLE
[StructuralMechanicsApplication] No boundary conditions in velocity respected

### ISSUE THREAD

**Issue by salvalatorre** [KratosMultiphysics/Kratos#4426]
Hi all,
I'm running a simple case of the compression of half a cube by imposing the Z-velocity at the nodes of the top surface while, at the same time, fixing the displacement in Z of the bottom surface to zero. I attach a figure of the velocity field of the whole mesh and the contents of the corresponding json.
Thanks
![velocity_field](https://user-images.githubusercontent.com/25589908/54268981-b2d3d880-457c-11e9-81d1-4c6116462bbe.png)

{
    "problem_data"     : {
        "problem_name"  : "benchmark03fem",
        "parallel_type" : "OpenMP",
        "echo_level"    : 1,
        "start_time"    : 0.0,
        "end_time"      : 1.0
    },
    "solver_settings"  : {
        "solver_type"                        : "Dynamic",
        "model_part_name"                    : "Structure",
        "domain_size"                        : 3,
        "echo_level"                         : 1,
        "analysis_type"                      : "non_linear",
        "time_integration_method"            : "implicit",
        "scheme_type"                        : "newmark",
        "model_import_settings"              : {
            "input_type"     : "mdpa",
            "input_filename" : "benchmark03fem"
        },
        "material_import_settings"           : {
            "materials_filename" : "StructuralMaterials.json"
        },
        "time_stepping"                      : {
            "time_step" : 0.01
        },
        "linear_solver_settings":             {
            "solver_type":     "amgcl",
            "smoother_type":   "ilu0",
            "krylov_type":     "gmres",
            "coarsening_type": "aggregation",
            "max_iteration":   100,
            "verbosity":       0,
            "tolerance":       1.0e-6,
            "scaling":         false
        },
        "line_search"                        : false,
        "convergence_criterion"              : "and_criterion",
        "displacement_relative_tolerance"    : 0.0001,
        "displacement_absolute_tolerance"    : 1e-9,
        "residual_relative_tolerance"        : 0.0001,
        "residual_absolute_tolerance"        : 1e-9,
        "max_iteration"                      : 10,
        "problem_domain_sub_model_part_list" : ["Parts_topfem"],
        "processes_sub_model_part_list"      : ["VELOCITY_topwall"],
        "rotation_dofs"                      : false
    },
    "processes"        : {
        "constraints_process_list" : [{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Structure.VELOCITY_topwall",
                "variable_name"   : "VELOCITY",
                "constrained"     : [false,false,true],
                "value"           : [0.0,0.0,-0.05],
                "interval"        : [0.0,"End"]
            }
        }],
        "loads_process_list"       : [],
        "list_other_processes"     : []
    },
    "output_processes" : {
        "gid_output" : [{
            "python_module" : "gid_output_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "GiDOutputProcess",
            "help"          : "This process writes postprocessing files for GiD",
            "Parameters"    : {
                "model_part_name"        : "Structure.computing_domain",
                "output_name"            : "benchmark03fem",
                "postprocess_parameters" : {
                    "result_file_configuration" : {
                        "gidpost_flags"       : {
                            "GiDPostMode"           : "GiD_PostBinary",
                            "WriteDeformedMeshFlag" : "WriteDeformed",
                            "WriteConditionsFlag"   : "WriteConditions",
                            "MultiFileFlag"         : "SingleFile"
                        },
                        "file_label"          : "step",
                        "output_control_type" : "step",
                        "output_frequency"    : 1,
                        "body_output"         : true,
                        "node_output"         : false,
                        "skin_output"         : false,
                        "plane_output"        : [],
                        "nodal_results"       : ["DISPLACEMENT","VELOCITY","ACCELERATION"],
                        "gauss_point_results" : ["CAUCHY_STRESS_TENSOR","VON_MISES_STRESS"]
                    },
                    "point_data_configuration"  : []
                }
            }
        }]
    }
}

**Comment by salvalatorre** [comment]
Sorry, in this particular case I didn't fix the displacement in Z at the bottom. I was referring to another similar case I tested. Anyway, the velocity at the top nodes should be respected...

**Comment by loumalouomega** [comment]
Can you attach the whole case please?

**Comment by salvalatorre** [comment]
Here you are:

[benchmark03fem.gid.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/2960852/benchmark03fem.gid.tar.gz)

Thnx

**Comment by maceligueta** [comment]
Referencing @KratosMultiphysics/structural-mechanics

**Comment by loumalouomega** [comment]
This is solved on #4430
