### ISSUE TITLE
[Core] Mortar utils & mapper not compiling in Debug mode with Cotire

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#4433]
The compilation in Debug mode with Clang and Cotire crashes in the `mortar_utilities` and the `simple_mortar_mapper_process` because of the explicit instantiation. It seems to be related with #4412.

**Comment by loumalouomega** [comment]
I don't understand, Travis and Appveyor compile both with Cotire and Debug

**Comment by loumalouomega** [comment]
Is this right @roigcarlo ?

**Comment by rubenzorrilla** [comment]
But not with Clang.

**Comment by loumalouomega** [comment]
It compiles in my machine. Can you post the exact error?

**Comment by loumalouomega** [comment]
I tried again, all fine

**Comment by rubenzorrilla** [comment]
I've deactivated Cotire and it compiles. I need to recompile again using Cotire to post the error... Which version of Clang are you using? Mines is 6.0.0.

**Comment by loumalouomega** [comment]
7.0, moving to 6.0

**Comment by loumalouomega** [comment]
Ok, it fails

**Comment by loumalouomega** [comment]
Fixed on #4433
