### ISSUE TITLE
[Core] GetRegisteredName fails for mSurfaceCondition3D3N

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#4439]
The deprecated Conditions like the `mCondition3D` defined in 
https://github.com/KratosMultiphysics/Kratos/blob/d274c0596833d653e4b1996ae60dc1d1a921e8c9/kratos/includes/kratos_application.h#L378

cause the ` CompareElementsAndConditionsUtility::GetRegisteredName` to return the wrong name for the new conditions like e.g. `mSurfaceCondition3D3N`. This is because both are of the type `MeshCondition` and have a `Triangle3D3` geometry. These are the only two things that are compared.

If the deprecated conditions can not be removed for backwardcompatibility reasons, an intermediate solution could be to create a derived class `DeprecatedMeshCondition` that does fully inherit the `MeshCondition`. Like this they could be distinguished.

**Comment by loumalouomega** [comment]
Maybe we should get rid of the deprecated names instead of having duplicated conditions/elements.

**Comment by armingeiser** [comment]
I that is possible, it would of course make more sense.

**Comment by loumalouomega** [comment]
Yeah, but many people is using still the deprecated names ... I don't think is going to be easy

**Comment by philbucher** [comment]
we could search+replace the old names 
That would be a first step on removing them

**Comment by philbucher** [comment]
Also we could issue a deprecation-warning in the model-part-IO if someone still uses the old names

**Comment by loumalouomega** [comment]
We should merge the PR that separates the variables.cpp first. Otherwise will be a chaos

**Comment by loumalouomega** [comment]
After moving the condition/element register we should re-discuss this. @KratosMultiphysics/technical-committee @KratosMultiphysics/implementation-committee

**Comment by loumalouomega** [comment]
> We should merge the PR that separates the variables.cpp first. Otherwise will be a chaos

This is already done

**Comment by loumalouomega** [comment]
We can use https://github.com/KratosMultiphysics/Kratos/pull/2119

**Comment by loumalouomega** [comment]
@KratosMultiphysics/implementation-committee agrees that the Condition3D must be deprecated and removed, and SurfaceCondition3D3N should be the only one allowed. @jginternational, please remove all references to Condition3D in GiD interface ASAP

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agrees with the decision of the @KratosMultiphysics/implementation-committee  but please wait for the release 7.1 to be frozen. So @KratosMultiphysics/implementation-committee please proceed with it afterward.

**Comment by RiccardoRossi** [comment]
we should proceed with the removal ASAP.
