### ISSUE TITLE
Problems when pulling the master branch

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#4444]
Good afternoon, @SergioJimenezReyes and myself have had problems when pulling the master branch from github... The message that we obtain ehwn performing the git pull from the master is:

error: cannot update the ref 'refs/remotes/origin/release-7.0/core/hotfix-issue-                                                         4409-4419': unable to create directory for '.git/logs/refs/remotes/origin/releas                                                         e-7.0/core/hotfix-issue-4409-4419': No such file or directory                                                                            From https://github.com/KratosMultiphysics/Kratos                                                                                         ! [new branch]              release-7.0/core/hotfix-issue-4409-4419 -> origin/r                                                         elease-7.0/core/hotfix-issue-4409-4419  (unable to update local ref)                                                                     Auto packing the repository in background for optimum performance.                                                                       See "git help gc" for manual housekeeping.
--

We have tried to erase the folder and it doesn't work.
Anyone knows how to solve this?

thank you
@roigcarlo

**Comment by roigcarlo** [comment]
Looking into it

**Comment by roigcarlo** [comment]
@AlejandroCornejo Can you try now?

**Comment by AlejandroCornejo** [comment]
it seems that now it works !
Thank you @roigcarlo

**Comment by ddiezrod** [comment]
It seems that I am having a similar problem here
![image](https://user-images.githubusercontent.com/25667299/54688961-f0a5a380-4b1e-11e9-9dcc-b8288212d588.png)

How did you fix this one?

**Comment by roigcarlo** [comment]
@ddiezrod Last problem was caused by the branch name, this is not the same. It looks like if you had a branch in your local which has diverged from a branch with the same name in the remote.

I cannot solve this without removing the remote which could be still on use by people from DEM. If you are not using that branch, can your try to remove it and try again? Otherwise you can try to:

`git remote prune origin`

This should remove any remote deleted branch from your local, it tends to help.

**Comment by ddiezrod** [comment]
I do not have any branch but the master one in my local repository. Here it is an "interesting" sequence of events..



![image](https://user-images.githubusercontent.com/25667299/54690917-b211e800-4b22-11e9-9b92-629b4e8e09d4.png)

**Comment by ddiezrod** [comment]
I tried  `git gc --prune=now `with the same result ... Strange thing is that I never used that branch

**Comment by roigcarlo** [comment]
Then try to remove it :S I've tested in my local and it seems to work fine.

`git branch -D dem/analysis_stage_parameters`

Also ping @maceligueta to see if they have had similar issues :S

**Comment by maceligueta** [comment]
I had similar issues, but I do not remember in which computer (win or linux). Neither I remember how I skipped the problem.
