### ISSUE TITLE
output vtk date format

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#4448]
Could I output vtk data in structrualmechanicsapplication by defining parameters in Josn file?

**Comment by ZhimingGuo** [comment]
Is there a example of  JOSN  to defining parameters similar with Gidpostmode?

**Comment by rubenzorrilla** [comment]
As far as I know, the current version of the GUI is printing in both .vtk and GiD formats. So if you use it to set up you case (or a fake one to get the .json) you will have an example.

**Comment by ZhimingGuo** [comment]
you mean Kratos.gid 6.0?

**Comment by philbucher** [comment]
no, you need the current developer version
Version 6.0 did not have VTK, neither GiD, nor Kratos

**Comment by ZhimingGuo** [comment]
I think, what i should do  is following this, right?
    Install GiD -> Developer version
    Navigate to GiD's problemtype folder and delete kratos.gid
    Create there a link to our kratos.gid
    Navigate to kratos.gid/exec/
    Create there a symbolic link to the kratos installation folder (where runkratos is located)
        Unix : ln -s ~/Kratos Kratos
        Windows : mklink /J Kratos C:\kratos (Kratos installation folder)

**Comment by ZhimingGuo** [comment]
![Screenshot from 2019-03-15 16-38-48](https://user-images.githubusercontent.com/26964544/54418774-d9db0780-4740-11e9-90b6-526b28823c02.png)

**Comment by ZhimingGuo** [comment]
I used the newest kratos.gid from gidinterface, but did not find vtk in result format. only binary, Ascii, and Ascii zipped.

**Comment by philbucher** [comment]
did you try a case?
It will add it automatically, the options are not yet exposed to the interface

**Comment by ZhimingGuo** [comment]
there is one error when i run test
### line 48: /home/zhiming/GiDx64/14.0.1/problemtypes/kratos.gid/exec/Kratos/runkratos: No such file or directory
I have used "ln -s /home/zhiming/Kratos2019 Kratos", but did not work

**Comment by philbucher** [comment]
you need to make a link to your self-compiled version of Kratos, the dev-version of the interface does not have Kratos

**Comment by ZhimingGuo** [comment]
ok, Thanks!!
