### ISSUE TITLE
MPI Synchronization of dynamic Matrix and Vector type variables?

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#4453]
I am currently writing tests in preparation to update the MPICommunicator for the MPI Core. I have encountered an issue where trying to Assemble a `Variable<Vector>` produces a segfault and I was wondering if anyone has experience with it.

In any case, is Assembly of dynamic vectors and matrices something that is well defined? Should it even be supported? Right now we are not even checking that the vectors have the same sizes on the different ranks before communicating...

@KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
Is it being used anywhere?

**Comment by jcotela** [comment]
@philbucher my suspicion is no, but I opened the issue to confirm...

**Comment by pooyan-dadvand** [comment]
I have not used it by myself

**Comment by RiccardoRossi** [comment]
@jcotela this is just to recall that a possible solution is to use the "generic SendRecv" discussed in #4592

**Comment by jcotela** [comment]
In the end I implemented communication strategies for dynamic Vector and Matrix types in #4745, which should solve this issue. The generic SendRecv will come in a future PR (we will need it anyway to synchronize more complex types).
