### ISSUE TITLE
explicit mpcs slave-master relation

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#4456]
Hi I have the following setup:
![imp](https://user-images.githubusercontent.com/26179700/54433351-ebfe7b00-472b-11e9-8a22-543f85151eed.gif)
the master nodes are on the light blue line and two slave nodes are at the connection between the dark and the light blue line. A force is applied at the right lower node and as you can see in the video above I can realize a sliding on the light blue line by coupling DISP_Y and DISP_Z between master and slave + searching new neighbour nodes in each iteration (not completely correct sliding but I will improve this...). This is using the implicit dynamic scheme.

I now wanted to try the new explicit mpcs and this is the result:
![exi](https://user-images.githubusercontent.com/26179700/54433521-56172000-472c-11e9-8ec0-fd6c4cc22cde.gif)
One can see that the master line does not deform, but the constraints are properly set. 

I think the problem is that in the current implementation of the explicit mpcs the load is not transferred to the master line. My guess would be that we have to couple the residual in `void ExplicitCentralDifferencesScheme::Update` of the slave and the master dof. Because they are in a certain relation, which is not considered at the moment. 

I would be happy about any suggestions.

**Comment by loumalouomega** [comment]
I will take a look on Monday's morning, sorry if I have broke/done
something wrong.

**Comment by loumalouomega** [comment]
Indeed there is a relation, sorry if I haven't seen that.

**Comment by KlausBSautter** [comment]
> I will take a look on Monday's morning, sorry if I have broke/done something wrong.

nothing wrong, I think there is sth. missing. I talked to @adityaghantasala and one way to go would be to check in `Update` if a dof of the current node is a slave dof. If yes we add the weighted residual, nodal mass, etc. to the master node

**Comment by KlausBSautter** [comment]
@loumalouomega I made a first try.
Sth. like edf9d8184ceca17e57ea61ce699373683077575c 
But we can discuss this on monday

**Comment by adityaghantasala** [comment]
@Klaus did this approach work ..  !!

**Comment by KlausBSautter** [comment]
@adityaghantasala It seems to work. I get strange unsymmetric behaviour but this must be a problem with my code. I'll look more into this

**Comment by KlausBSautter** [comment]
![new_exp](https://user-images.githubusercontent.com/26179700/54454511-eb7cd900-4759-11e9-9119-a2ac005caa23.gif)

like that. But I guess this shows that the basic idea will work

**Comment by adityaghantasala** [comment]
Looks like force is transferred property on one side and not the other .. !

**Comment by loumalouomega** [comment]
Just one thing, added to the constraint utilities, so everyone can use it.

**Comment by loumalouomega** [comment]
I just look the code, we can discuss further. But I don't agree on using
flags, mpc should not depend on flags. Have a nice weekend.

**Comment by KlausBSautter** [comment]
Which flag?

**Comment by KlausBSautter** [comment]
IS_SLAVE ?

**Comment by adityaghantasala** [comment]
I think yes ... we have been avoiding to use it ... and soon this flag will not be set even if the node has a slave DOF. 
In stead you could directly search in the MasterSlaveContainer of the modelpart itself.

**Comment by KlausBSautter** [comment]
I deletetd the flag and rewrote the code:  6fcd282

still, this is only a rough idea and I think it would be nice to add this to the mpc_util in the end

**Comment by KlausBSautter** [comment]
another question would be if one has to couple also VEL and ACC now when I coupled only DISP using implicit dynamics

**Comment by KlausBSautter** [comment]
OK @adityaghantasala just told me that also VEL and ACC has to coupled in this case. 
The new approach 6fcd282 works for me. @loumalouomega . So you might check this out.

**Comment by loumalouomega** [comment]
@KlausBSautter in which branch are these developments?

**Comment by KlausBSautter** [comment]
https://github.com/KratosMultiphysics/Kratos/tree/StructMech/advance_explicit_mpcs

**Comment by loumalouomega** [comment]
Fine, can I refactor this?

**Comment by KlausBSautter** [comment]
yes please go ahead. It's just a rough idea how to realize this interaction

**Comment by loumalouomega** [comment]
Thanks, let me a moment

**Comment by loumalouomega** [comment]
Do we have a test for this?

**Comment by KlausBSautter** [comment]
no I have not done any explicit mpcs yet. But the examples I run with implicit mpcs give me now the same result with explicit mpc. E.g. the example I posted in this issue.

**Comment by loumalouomega** [comment]
Can you attach the case?, I cleaned upda and generized and OMP teh code, but the current implementation will work only for MPC with one Dof at a time. A distributed operation with matrix operation must be done in order to correctly computed the explicit MPC. I will do that now

**Comment by philbucher** [comment]
wouldn't a generalized `Apply` function on the constraint make more sense?

=> instead of using the dof-variable use an external variable but do the same operations

**Comment by loumalouomega** [comment]
> wouldn't a generalized `Apply` function on the constraint make more sense?
> 
> => instead of using the dof-variable use an external variable but do the same operations

This is not applicable here because there is no way to know the residual variable used on explicit contributions relatable to the standard dofs.

**Comment by philbucher** [comment]
thats what I mean, this variable (in the explicit case the residual variable) would be an additional argument

I mean, the global problem is that the same operation has to be applied to the constrained variables AND also to other variables (e.g. the residual-variable)

**Comment by loumalouomega** [comment]
> thats what I mean, this variable (in the explicit case the residual variable) would be an additional argument
> 
> I mean, the global problem is that the same operation has to be applied to the constrained variables AND also to other variables (e.g. the residual-variable)

I don't undertstand

**Comment by KlausBSautter** [comment]
> Can you attach the case?

You would need an additional process. Should I commit that? We can later get rid of it again

**Comment by loumalouomega** [comment]
Ok, I will push my changes and you can test it

**Comment by philbucher** [comment]
Guys I am looking at this right now and just to say this is really messy & inefficient, we need a better solution for this ...

**Comment by philbucher** [comment]
we just spoke in person; @KlausBSautter will try if this works properly, then we will try to find a proper & general solution that can go into master

**Comment by loumalouomega** [comment]
> Guys I am looking at this right now and just to say this is really messy & inefficient, we need a better solution for this ...

I am going to push a better solution in a moment

**Comment by philbucher** [comment]
ok :+1:

**Comment by loumalouomega** [comment]
Done, look at it now

**Comment by loumalouomega** [comment]
I just saw that I can optimize it a little bit more. one sec

**Comment by philbucher** [comment]
looks better!
only problem I have is the `pGetNode`, this is a find and a killer in large problems.
So far though I could not think of a better solution though

**Comment by loumalouomega** [comment]
> looks better!
> only problem I have is the `pGetNode`, this is a find and a killer in large problems.
> So far though I could not think of a better solution though

Yes, I have an idea...

**Comment by KlausBSautter** [comment]
@loumalouomega using the current branch, my examples don't converge with implicit mpcs anymore and 

> RuntimeError: Error: Variable is not a component or a double

is thrown with explicit mpcs

**Comment by loumalouomega** [comment]
That't why I asked for a test, I implemented blindly. Sorry

**Comment by loumalouomega** [comment]
I found the error, try now, sorry. I will create a test for it

**Comment by KlausBSautter** [comment]
ok but I wonder why the implicit example does not work anymore. I think the newest changes in the residual crit caused that.... ??

**Comment by loumalouomega** [comment]
> ok but I wonder why the implicit example does not work anymore. I think the newest changes in the residual crit caused that.... ??

Which examples?, are in the repository?

**Comment by loumalouomega** [comment]
> > Can you attach the case?
> 
> You would need an additional process. Should I commit that? We can later get rid of it again

If it is just one file you can send me via private message.

**Comment by KlausBSautter** [comment]
No my local example, the one I posted here at the beginning.
Anyway there is still a problem with the explicit too

>   what():  Error: Dof variable is not defined

when coupling vel, acc etc.

**Comment by KlausBSautter** [comment]
also when I couple only disp this does not work anymore for explicit mpcs. wait I'll send you the example

**Comment by KlausBSautter** [comment]
https://gigamove.rz.rwth-aachen.de/d/id/jqCd8VNkCszUa6

you'll have to add the process which is included

**Comment by loumalouomega** [comment]
Ok, thanks

**Comment by KlausBSautter** [comment]
one very strange thing. if you change the time int to implicit and couple only disp it does not converge anymore in the terminal and stays at the same res all the time. Eventhough the post pro file looks the same as before

**Comment by loumalouomega** [comment]
The changes in this branch are affecting only to explicit things, I assume it is due to recent changes...

**Comment by KlausBSautter** [comment]
yes I found the mistake with the implicit scheme

**Comment by loumalouomega** [comment]
Now it works with explicit

**Comment by loumalouomega** [comment]
Only implicit...

**Comment by loumalouomega** [comment]
The problem of implicit are that VELOCITY and ACCELERATION are reactionless

**Comment by loumalouomega** [comment]
@RiccardoRossi FYI, the block B&S is failing with this case. Check the example posted by @KlausBSautter

**Comment by KlausBSautter** [comment]
@loumalouomega  here this is alright I guess. When you do this example implicit you only couple DISP, as the rest is calculated implicitly from this solution. There was another problem but @philbucher and I just fixed it (see #4478).

When doing the explicit coupling you have to couple also VEL&ACC

**Comment by KlausBSautter** [comment]
I'll try your newest changes now with explicit

**Comment by KlausBSautter** [comment]
@loumalouomega it does not do what it did this morning, before refactoring
Now:
![new_exp](https://user-images.githubusercontent.com/26179700/54541943-27eb4780-499b-11e9-8aa6-d0f69e979a41.gif)
before:
![imp](https://user-images.githubusercontent.com/26179700/54541963-3174af80-499b-11e9-8a8f-3c4ffd77f541.gif)

**Comment by loumalouomega** [comment]
OK,  I will check out

**Comment by loumalouomega** [comment]
> @loumalouomega here this is alright I guess. When you do this example implicit you only couple DISP, as the rest is calculated implicitly from this solution. There was another problem but @philbucher and I just fixed it (see #4478).
> 
> When doing the explicit coupling you have to couple also VEL&ACC

This means that the scheme lacks of update for velocity and acceleration when displacement is known?

**Comment by KlausBSautter** [comment]
which scheme?

**Comment by loumalouomega** [comment]
The explicit one, in the same way we do in the implicit ones.

**Comment by KlausBSautter** [comment]
I think in the implicit one the displacement is the solution which we use to update vel and acc. In explicit the solution is acc which we use to update disp and vel

**Comment by loumalouomega** [comment]
yes, indeed, now we need to think a automatic way to link this instead of specify manually

**Comment by KlausBSautter** [comment]
maybe just couple the respective vel and acc if disp is coupled

**Comment by loumalouomega** [comment]
Yeah, I was thinking something more generic

**Comment by KlausBSautter** [comment]
Maybe I found the problem, not sure .....

why are you transforming the master solution and add this to the slave?

It should be the other way round

**Comment by KlausBSautter** [comment]
yes makes it better but still not completely correct

**Comment by loumalouomega** [comment]
Well the solution of the slave should depend on the master dofs...maybe I did it in an inverse sense...

**Comment by KlausBSautter** [comment]
yes the solution of the slave is preset by the constraints you do this after `Update`
But the solution of the master is dependent on the stiffness and mass which is added by the slaves too, this is what we do before `Update`. So we should add the residual of the slave to the residual of the master. We also have to think about how to add the mass

**Comment by loumalouomega** [comment]
Ok, I understood your implementation wrong, well this has an easy solution

**Comment by loumalouomega** [comment]
Sorry

**Comment by loumalouomega** [comment]
Now it works and gives exactly the same solution

**Comment by KlausBSautter** [comment]
yes, perfect thanks !

**Comment by KlausBSautter** [comment]
For systems with larger masses we might experience problems, if we neglect the mass transfer (which we do right now)

**Comment by loumalouomega** [comment]
> For systems with larger masses we might experience problems, if we neglect the mass transfer (which we do right now)

Maybe we can do that in a future PR. We need o apply Steiner too to transfer inertias

**Comment by KlausBSautter** [comment]
yeah alright. So new PR with this new code ?

**Comment by loumalouomega** [comment]
> yeah alright. So new PR with this new code ?

Feel free
