### ISSUE TITLE
Structrual tests taking way too long

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#4459]
@KratosMultiphysics/structural-mechanics. As you are aware there are a couple of problems while running the structural tests that sometimes are blocking PR from being merged into the release branch. 

The failing one can be disabled, but we still have problems with the tests in general taking too much time.

I've been profiling the small tests in the structural and I have some results. This is obtained in the master, same configuration as travis:

As you can see, tests seem fine, but there are two of them that are taking abnormal amounts of time:

![image](https://user-images.githubusercontent.com/1935791/54443347-b748ee80-4740-11e9-9556-3baacbc5da48.png)

I would say that this two are not ok, notice that the membrane one is taking 1/3 of the total time assigned for ALL the all small group...

* TestPatchTestMembrane.test_membrane_3d4n_dynamic: **18.274** 
* SimpleSmallDeformationPlasticityMCTest.test_execution: **7.749**

Can we temporally disable this? Is there a way to reduce the time?

**Comment by philbucher** [comment]
we can move those tests to the nightly suite

**Comment by roigcarlo** [comment]
:+1:

**Comment by loumalouomega** [comment]
Supporting to move them to Nightly

**Comment by philbucher** [comment]
on it

**Comment by RiccardoRossi** [comment]
guys, the patch_test should take no time, same for the plasticity test. And i would say at least conceptually they belong to the short tests.

@loumalouomega @AlejandroCornejo can u take a look on why they take so long?

**Comment by loumalouomega** [comment]
> guys, the patch_test should take no time, same for the plasticity test. And i would say at least conceptually they belong to the short tests.
> 
> @loumalouomega @AlejandroCornejo can u take a look on why they take so long?

The thing is this is a very long patch test, with many cycles
