### ISSUE TITLE
the issue of section properties(beam,shell and so on) seperating from Material

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#4465]
~~~
{
     "properties" : [{
         "model_part_name" : "Parts_structure",
         "properties_id"   : 1,
         "Material"        : {
            "constitutive_law" : {
                "name" : "KratosMultiphysics.StructuralMechanicsApplication.LinearElasticPlaneStress2DLaw"
            },
            "Variables"        : {
                "DENSITY"       : 7850.0,
                "YOUNG_MODULUS" : 210000000000.0,
                "POISSON_RATIO" : 0.3,                
                "KratosMultiphysics.StructuralMechanicsApplication.CROSS_AREA"  : 0.01,
		"KratosMultiphysics.StructuralMechanicsApplication.TORSIONAL_INERTIA"  : 0.00001,
		"KratosMultiphysics.StructuralMechanicsApplication.I22"  : 0.00001,
		"KratosMultiphysics.StructuralMechanicsApplication.I33"  : 0.00001
            },
            "Tables"           : {}
        }
    }]
}
~~~

**Comment by ZhimingGuo** [comment]
![Screenshot from 2019-03-16 16-18-36](https://user-images.githubusercontent.com/26964544/54472781-723cbf00-4809-11e9-827c-f21fe96ed0a9.png)
Here, the constitutive law is section properties.

**Comment by ZhimingGuo** [comment]
could we find a way to separate section properties from Material  in Properties definition? the format like the following:
 ~~~
 "properties" : [{
        "model_part_name" : "Parts_structure1",
        "properties_id"   : 1,
        "Material"        : {
            "constitutive_law" : {
                "name" : "KratosMultiphysics.StructuralMechanicsApplication.LinearElasticPlaneStress2DLaw"
            },
            "Variables"        : {
                "DENSITY"       : 7850.0,
                "YOUNG_MODULUS" : 210000000000.0,
                "POISSON_RATIO" : 0.3,                
            },
            "Tables"           : {}
        }
        "Section"        : {
            "Variables"        : {
                "KratosMultiphysics.StructuralMechanicsApplication.CROSS_AREA"  : 0.01,
		"KratosMultiphysics.StructuralMechanicsApplication.TORSIONAL_INERTIA"  : 0.00001,
		"KratosMultiphysics.StructuralMechanicsApplication.I22"  : 0.00001,
		"KratosMultiphysics.StructuralMechanicsApplication.I33"  : 0.00001
            },
        }
}]
~~~

**Comment by ZhimingGuo** [comment]
on this way, we can assemble different Material constitutive law and section properties assigning to different parts for model with many parts(including beam, shell, truss, solid). Every combination of Material constitutive law and section properties is assigned its own properties_id.

**Comment by philbucher** [comment]
I dont get what you mean, could you please explain in more detail?
Btw1: you can ofc assign separate materials to separate submodelparts
Btw2: please wrap your code in “~~~“, then it will be nicely formatted

**Comment by philbucher** [comment]
Here is an example how to assign different materials to different submodelparts:
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/materials.json

**Comment by ZhimingGuo** [comment]
I mean if it is possible defining section properties(such as beam element) individually, not including in Material(or constitutive law)

**Comment by ZhimingGuo** [comment]
for example(structural):
~~~
        "properties_id"   : 1,
        "Material"        : {
            "constitutive_law" : {},
            "Variables"        : { },
            "Tables"           : {}
         },
        "Section properties"        : {
             "Variables"        : {
                 "KratosMultiphysics.StructuralMechanicsApplication.CROSS_AREA"  : 0.01,
		 "KratosMultiphysics.StructuralMechanicsApplication.TORSIONAL_INERTIA"  : 0.00001,
		 "KratosMultiphysics.StructuralMechanicsApplication.I22"  : 0.00001,
		 "KratosMultiphysics.StructuralMechanicsApplication.I33"  : 0.00001
            },
        }

~~~

**Comment by philbucher** [comment]
but what is the difference?
You just moved where the variables are defined

Also the element need constitutive laws otherwise they won't work

**Comment by RiccardoRossi** [comment]
@ZhimingGuo the point is that "section" does not exist as a database in Kratos.
Everything is contained in a property, and each element can have a single propery.

There is an open discussion about subproperties #2919  , however i am not sure if it goes as far as you need (nor if it will be accepted in its current form)
