### ISSUE TITLE
[ShapeOpt] Update of mapping in Vertex Morphing

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#4472]
The option "update_mapping_matrix" and the function "Update()" does not apply to matrix-free vertex morphing and consequently behaves inconsistently.  Such an option is actually not possible there, but in the current implementation, it appears to be a valid specification.

As a consequence, e.g. even if one does not call the "Update()" function of the matrix-free mapper, then the search tree is indeed not constructed a second time, but every map will still consider the latest coordinates when the weights are computed. 

- [ ] Hence this option needs to be replaced to a lower level or a mechanism needs to be included to check if the corresponding options are meaningful.

**Comment by philbucher** [comment]
is this still active?

**Comment by rubenzorrilla** [comment]
Closing as it seems to be inactive.
