### ISSUE TITLE
[Particle] MathUtils Invert Matrix

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#4476]
In file Kratos\applications\ParticleMechanicsApplication\custom_constitutive\flow_rules\borja_cam_clay_plastic_flow_rule.cpp

Line MathUtils<double>::InvertMatrix( lhs_matrix, inv_lhs_matrix, det_lhs, -1.0);

I think that @bodhinandach you should remove that -1.0 in order to compile

#4087

**Comment by bodhinandach** [comment]
@jginternational I don't have any problems compiling it in my PC with the latest master. Is it only specific in the release 7.0 version?

**Comment by bodhinandach** [comment]
@jginternational, me and @roigcarlo are merging this branch #4469 to the release this morning.

**Comment by jginternational** [comment]
I'm using the release 7.0 branch on Windows

![image](https://user-images.githubusercontent.com/5918085/54543961-df358d80-499e-11e9-80ae-79784d8a665c.png)

**Comment by bodhinandach** [comment]
Okay, the modification in the MathUtils by @loumalouomega is not there yet. My bad! I will consult with @roigcarlo to revert this.

**Comment by bodhinandach** [comment]
@jginternational thanks for letting me know Javi.
