### ISSUE TITLE
TopologyOptimizationApplication with pybind11

### ISSUE THREAD

**Issue by e-dub** [KratosMultiphysics/Kratos#4484]
I tried to get the TopologyOptimizationApplication running again following 
[https://github.com/KratosMultiphysics/Kratos/wiki/Porting-to-PyBind11---common-steps](https://github.com/KratosMultiphysics/Kratos/wiki/Porting-to-PyBind11---common-steps)

I can build it, but am getting the following error when running a test:
Traceback (most recent call last):
```
  File "run_TopOpt.py", line 14, in <module>
    from KratosMultiphysics.TopologyOptimizationApplication import *
  File "~/opt/kratos/KratosMultiphysics/TopologyOptimizationApplication/__init__.py", line 15, in <module>
    from KratosTopologyOptimizationApplication import *
ImportError: ~/opt/kratos/libs/KratosTopologyOptimizationApplication.cpython-36m-x86_64-linux-gnu.so: 
undefined symbol: _ZN6Kratos12SolidElement16EquationIdVectorERSt6vectorImSaImEERNS_11ProcessInfoE
```
Any hints or ideas on where the problem could be?

**Comment by philbucher** [comment]
maybe the function is not properly implemented in the cpp or has a non-matching functino-signature:
~~~
c++filt _ZN6Kratos12SolidElement16EquationIdVectorERSt6vectorImSaImEERNS_11ProcessInfoE
Kratos::SolidElement::EquationIdVector(std::vector<unsigned long, std::allocator<unsigned long> >&, Kratos::ProcessInfo&)
~~~

also topopt still depends on solidmechanics

**Comment by e-dub** [comment]
Thanks for your quick answer! 

As TopOptApp does not directly reference SolidElement and instead SmallDisplSIMPElement (TopOpt) → SmallDisplElement (SolidMech) → SolidElement (SolidMech), I have been trying to find the error (or inconsistency) in the custom element "small_displacement_simp_element".  Or am I barking up the wrong tree here? 

I have pushed my changes to the following branch: [TopOpt/restarting](https://github.com/KratosMultiphysics/Kratos/tree/TopOpt/restarting)

**Comment by philbucher** [comment]
what is the status of this?

**Comment by e-dub** [comment]
After speaking about this with @dbaumgaertner at the end of March, it makes more sense to move the Topology Optimization Application to run with the Structural Mechanics Application (and away from the Solid Mechanics Application).  I would like to put a master student on this starting next semester. 
Long story short, feel free to close this issue.

**Comment by rubenzorrilla** [comment]
Closing then.
