### ISSUE TITLE
How to make problemType of FluidDynamicsApplication

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#4485]
I remember there is one tutorial on wiki for teaching how to generate ProblemType of Application.
is it still working?

**Comment by RiccardoRossi** [comment]
Hi Zhiming, 
        it is a long time we don't use that. We now have a much more modern problemtype which you can find here:

https://github.com/KratosMultiphysics/GiDInterface

**Comment by ZhimingGuo** [comment]
Can i only pull FluidDynamicsApplication out from the kratos.gid?  I just want Fluid :)

**Comment by rubenzorrilla** [comment]
You can't. There are common features that are also needed. In any case the entire GUI repository is less than 4 mb.

**Comment by ZhimingGuo** [comment]
ok,Thanks!
