### ISSUE TITLE
why the Membrane Element is not included in the GiD interface?

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#4487]
title says it all.

mentioning @playpaolo who noticed it.

**Comment by philbucher** [comment]
it is ... I put it there long ago ...
![Screenshot from 2019-03-19 10-32-47](https://user-images.githubusercontent.com/25484702/54595169-62ec8a00-4a32-11e9-9b2c-baf6c2acbbbe.png)

**Comment by rubenzorrilla** [comment]
Maybe it only appears in developer mode?

**Comment by philbucher** [comment]
indeed...

fixed in https://github.com/KratosMultiphysics/GiDInterface/pull/558

**Comment by philbucher** [comment]
solved ...

**Comment by RiccardoRossi** [comment]
forgot to say thx
