### ISSUE TITLE
How to modify the time-step during the calculation

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#4494]
Dear community,

Due to several cases that I've been running these days I've been thinking about reducing or increasing the time-step during the calculation and I have several doubts about that:

1. Is it possible?
2. Which are the main steps to do that?

Thank you kindly,

**Comment by rubenzorrilla** [comment]
We actually do it in the FluidDynamicsApplication according to the CFL so if your time scheme is implemented such that the delta time is not assumed to be constant, I think it should be perfectly possible.

**Comment by AlejandroCornejo** [comment]
thank you @rubenzorrilla ! In my app I'm using the SolidMechanicsApp @josep-m-carbonell schemes, Are we allowed to do that?

**Comment by philbucher** [comment]
also the schemes in the core are afaik able to handle variable time-steps

the python-solver does `AdvanceInTime` in this function you could change the timestep

**Comment by loumalouomega** [comment]
It is possible with the core schemes, I don't know about SolidMechanics

**Comment by GuillermoCasas** [comment]
Remember that, if possible, it is

**Comment by marandra** [comment]
I am also interested on variable time step during calculation. I understand that core schemes can handle variable time steps; what I would particularly like to know is if there is already a mechanism for specifying different time steps values at different time ranges (like a table or so) in the ProjectParameters, process, or similar.

**Comment by loumalouomega** [comment]
Can we close this, and continue the discussion on #4509? So many issues make it difficult to follow

**Comment by AlejandroCornejo** [comment]
yes!! let's continue there

**Comment by loumalouomega** [comment]
OK
