### ISSUE TITLE
compute_body_fitted_output_process in MPI doesn't print

### ISSUE THREAD

**Issue by fdifrison** [KratosMultiphysics/Kratos#4495]
Kratos version:
Kratos Multi-Physics 7.0.0-807d741

We are doing a fluid dynamic simulation of a tall building and we encountered some issues while running on Cineca Cluster in MPI:
IN particular, "compute_body_fitted_output_process.py" print file is completely empty.
The same issues happened with other processes, like point output process...kratos generates the data file but it doesn't write any result.

Running in local on our desktop instead, everything works fine.

Any clue on what we are missing?

p.s. Don't know if can be of any relevance, but on Cineca cluster, Kratos is compiled with intel, MKL instead BLAS e LAPACK, we are using an old version of Parmetis (3.2).

In attachment the ProjectParameter and the compilation file for Kratos.

Thanks in advance for your help!

[compile.txt](https://github.com/KratosMultiphysics/Kratos/files/2984683/compile.txt)

[ProjectParametersCustom.txt](https://github.com/KratosMultiphysics/Kratos/files/2984688/ProjectParametersCustom.txt)

**Comment by RiccardoRossi** [comment]
@fdifrison are u sure that the writing is not delayed? this happens a lot on our own cluster.

Essentially what i am telling is that the output is written to disk only once a given amount of data is reached.

**Comment by philbucher** [comment]
I also suspect the printing is delayed
you can force the printing by decreasing the buffer size with the following setting (might slow down your simulation depending on the speed of the file system of the cluster!)
~~~json
"python_module" : "compute_body_fitted_drag_process",
"kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
"process_name"  : "ComputeBodyFittedDragProcess",
"Parameters"    : {
    "model_part_name"        : "FluidModelPart.Drag_drag_c",
    "write_drag_output_file" : true,
    "print_drag_to_screen"   : false,
    "interval"               : [0.0,"End"],
    "output_file_settings": {
        "write_buffer_size" : 1
    }
}
~~~

**Comment by fdifrison** [comment]
@RiccardoRossi @philbucher
Thanks for your help.
Actually it is only at step 100 but the strange thing is that compute_custom_drag_process is printing values instead. I will update you if eventually something is written.

**Comment by fdifrison** [comment]
We just tried again with a 2 hours simulation...the same problem ... compute_custom_drag_process wrote properly every step (400), but the others didn't even write the header

**Comment by jcotela** [comment]
Did the simulation end correctly? I would recommend trying a very short test run (printing just a few steps) and letting it finish normally. If the results are there once the simulation ends, everything is normal (for a cluster), if they are not there, then there is something strange going on.

**Comment by fdifrison** [comment]
@jcotela probably you were right!
It seems that if the simulation is ended prematurely, due to time limits imposed by the cluster, Kratos gets angry and writes no output. With a very short simulation, everything seems to be written correctly. We will do some more test and update you shortly.

**Comment by philbucher** [comment]
@fdifrison have you tried my suggestion? With this the output should be written in every step, since you basically disable the buffering

**Comment by fdifrison** [comment]
@philbucher not yet. It is one of the tests on the list. But since it may affect the simulation's speed (and we already tight there) I left it for last ;D

**Comment by philbucher** [comment]
some additional thoughts:
I am not sure if it will affect the time, depends on the cluster. If it has a fast network then you should not notice the difference.

You could also adjust the buffer such that it prints every 10th step or so
Otherwise if the simulation gets killed you might have nothing

**Comment by fdifrison** [comment]
@philbucher Is the "buffer_size" equal to the output frequency? I tried with
    "output_file_settings": {
        "write_buffer_size" : 10
but nothing changed.
