### ISSUE TITLE
minor error in fluid_solver.py of FluidDynamicsApplication

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#4504]
Looks like in line 39, "self" is missing:

            self.main_model_part = model.CreateModelPart(model_part_name)

In order to be unified it should be:

            self.main_model_part = self.model.CreateModelPart(model_part_name)

**Comment by rubenzorrilla** [comment]
Hi  @playpaolo !

I think that it works since `self.model` points to `model` and `model` is still in the scope of the constructor. In any case it is misleading so makes sense to change it.

Thanks for reporting!

**Comment by playpaolo** [comment]
Hi Ruben,yes, it does work, but I think that the same way should be followed throughout the file.
Best,Pavel
 

    On Wednesday, March 20, 2019 3:30 PM, Rubén Zorrilla <notifications@github.com> wrote:
 

 Hi @playpaolo !I think that it works since self.model points to model and model is still in the scope of the constructor. In any case it is misleading so makes sense to change it.Thanks for reporting!—
