### ISSUE TITLE
TrilinosApplication Compilation Error

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#451]
When I try to compile the master branch I get an error when compiling trilinos. The first error is:
`Kratos/applications/trilinos_application/custom_strategies/schemes/trilinos_residualbased_incrementalupdate_variable_property_static_scheme.h:311:47: error: ‘SOLID_FRACTION’ was not declared in this scope
                 ind->FastGetSolutionStepValue(SOLID_FRACTION) = solid_fraction_var;`

This might be related to the disussion in #428

**Comment by jcotela** [comment]
Yes I confirm this is happening. I know what is the issue and will push a hotfix ASAP

**Comment by jcotela** [comment]
Fixing this in PR #452
