### ISSUE TITLE
FluidDynamicsApplication: two-fluid monolithic level set solver problem

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#4511]
Does this error sound familiar to anybody?
Thanks!
terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: Trying to generate the intersection skin in DivideTriangle2D3::GenerateIntersectionsSkin() for a non-split element.

in kratos/utilities/divide_triangle_2d_3.cpp:254:virtual void DivideTriangle2D3::GenerateIntersectionsSkin()

**Comment by rubenzorrilla** [comment]
It is because of the splitting utility. You have a node with 0 (or almost zero) distance. What we normally do to prevent this situation is to use the ModifyDistanceProcess in the fluid dynamics application.

**Comment by playpaolo** [comment]
Thanks Ruben! I'll try it out
Enviado desde Yahoo Mail con Android 
 
  El jue., mar. 21, 2019 a 16:15, Rubén Zorrilla<notifications@github.com> escribió:   
It is because of the splitting utility. You have a node with 0 (or almost zero) distance. What we normally do to prevent this situation is to use the ModifyDistanceProcess in the fluid dynamics application.

**Comment by playpaolo** [comment]
could you pls tell me where to look at an example of using this process @rubenzorilla?
I dont seem to find the process itself in FluidDynamicsApplication/custom_processes

**Comment by rubenzorrilla** [comment]
Hi @playpaolo ! You need to add something like this to your process list:
```
{
    "python_module": "apply_distance_modification_process",
    "kratos_module": "KratosMultiphysics.FluidDynamicsApplication",
    "Parameters": {
        "model_part_name": "FluidModelPart.Parts_Fluid",
        "distance_threshold": 0.001,
        "continuous_distance": true,
        "check_at_each_time_step": true,
        "avoid_almost_empty_elements": true,
        "deactivate_full_negative_elements": true
    }
}
```
Which kind of problem are you trying to solve? Depending on it some of the settings, specially the bool ones might change.

**Comment by rubenzorrilla** [comment]
Since there are no more strange behavior reports, I guess that the suggestion above solved the problem. @playpaolo feel free to reopen the issue if the problem raises again.
