### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by dcagritan** [KratosMultiphysics/Kratos#4512]
Dear all,

Kratos is not compiling. The error that I receive is:

/home/dcagri/Kratos210319/kratos/utilities/sensitivity_builder.cpp:157:46: error: no matching function for call to ‘forward(std::initializer_list<{anonymous}::sensitivity_builder_cpp::CalculateNodalSolutionStepSensitivities(const {anonymous}::sensitivity_builder_cpp::SensitivityVariables<TDataType>&, Kratos::ModelPart&, Kratos::AdjointResponseFunction&, double) [with TDataType = double]::__lambda1>&)’
             std::forward<TCallable>(local_fun)(*(rContainer.begin() + i));

Regards

**Comment by philbucher** [comment]
I just pulled master and for me it works.
Which compiler/OS do you use?
Have you tried a clean build?

**Comment by dcagritan** [comment]
That's really interesting...
I use Ubuntu 14.04 as the OS. My compiler is: gcc 4.8.4

**Comment by philbucher** [comment]
apparently also does not compile with Intel
ping @msandre
