### ISSUE TITLE
CSD problems.

### ISSUE THREAD

**Issue by fengzekang** [KratosMultiphysics/Kratos#4522]
Hello, everyone
Anybody do the work about CSD? What is the real meaning of CSD. I found some examples on video on https://goo.gl/pxrwLy. BTW, is there the CSD_Application in the Kratos until now?
Best regards.

**Comment by fengzekang** [comment]
Do you know the CSD function? @philbucher  @loumalouomega @roigcarlo  @RiccardoRossi 
Best regards.

**Comment by roigcarlo** [comment]
Dear @fengzekan can you give us a little more info?

**Comment by roigcarlo** [comment]
Do you mean the Computational Structural Dynamics?, if it is he case the code is in the structural mechanics application. There are also some examples in the example repo

**Comment by fengzekang** [comment]
Dear  @roigcarlo
I noticed that there is a video http://www.cimnemultimediachannel.com/vnews/2652/brazilian-test. So I am interested to know about what is it.And is there any application to do this. 
I am not sure what is  the meaning of "CSD", which is explained: 
CSD: 2-D & 3-D linear and nonlinear static and dynamic analysis. Various constitutive models (elasticity, plasticity, damage, fracture...). Elements library (beams, trusses, solids, shells, membranes, etc.)   
Is it the Computational Structural Dynamics? I will check the the structural mechanics application and examples.
Best regards.
