### ISSUE TITLE
vtk output for nodal data

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#4527]
I want to output stress to vtk results, such as VON_MISES_STRESS or CAUCHY_STRESS_TENSOR. should i set the variable in parameter element_data_value_variables?  i have tried, but got nothing

**Comment by ZhimingGuo** [comment]
and if i can find a way outputting these variables to nodal data?

**Comment by philbucher** [comment]
Those variables are gauss-point quantities in Kratos.
Unfortunately the vtk-output does not yet support this.

It is quite high though on our TODO-list

**Comment by loumalouomega** [comment]
There is a process in the MeshingApplication to extrapolate values from GP
to nodes. I am not in my computer, but the name of the process is self
explaining (maybe we can move it to the core)

**Comment by adityaghantasala** [comment]
I had a look at that process some time ago .. 

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/python_scripts/integration_values_extrapolation_to_nodes_process.py

completely agree with @loumalouomega  we could move this to the core ... !

**Comment by ZhimingGuo** [comment]
great, looking forward to this!!

**Comment by ZhimingGuo** [comment]
https://github.com/KratosMultiphysics/Kratos/issues/4527
