### ISSUE TITLE
[Core] Unexpected Behaviour of the Residual Convergence criteria

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#4529]
Dear all,
I've been running some cases and I've noticed that the convergence of the problems have been reduced considerably. In fact the behaviour of the problem is totally weird.
My input data for the problem is:
```
            "convergence_criterion":               "Residual_criterion",
            "displacement_relative_tolerance":      1.0E-4,
            "displacement_absolute_tolerance":      1.0E-9,
            "residual_relative_tolerance":          1.0E-4,
            "residual_absolute_tolerance":          1.0E-9,
```
and the streams shows:
```
RESIDUAL CRITERION:  :: [ Obtained ratio = 7.57932e+07; Expected ratio = 0.0001; Absolute norm = 22.9168; Expected norm =  1e-09]
RESIDUAL CRITERION:  :: [ Obtained ratio = 294.336; Expected ratio = 0.0001; Absolute norm = 8.89953e-05; Expected norm =  1e-09]
RESIDUAL CRITERION:  :: [ Obtained ratio = 6.21507; Expected ratio = 0.0001; Absolute norm = 1.87919e-06; Expected norm =  1e-09]
RESIDUAL CRITERION:  :: [ Obtained ratio = 0.126296; Expected ratio = 0.0001; Absolute norm = 3.81868e-08; Expected norm =  1e-09]
RESIDUAL CRITERION:  :: [ Obtained ratio = 0.00255608; Expected ratio = 0.0001; Absolute norm = 7.72856e-10; Expected norm =  1e-09]
RESIDUAL CRITERION: Convergence is achieved
```

In fact it is weird the initial **gigatic** residual (never seen before). The most strange part is that I'm theoretically converging according to the _Absolute norm_ criterion which in my opinion makes no sense.

Thank you in advance,
Alejandro

**Comment by AlejandroCornejo** [comment]
and look the 1st step:
```
 [STEP:: 1  TIME: 0.05 ]
RESIDUAL CRITERION:  :: [ Obtained ratio = 0; Expected ratio = 0.0001; Absolute norm = 4.25625; Expected norm =  1e-09]
RESIDUAL CRITERION: Convergence is achieved
```

**Comment by AlejandroCornejo** [comment]
I must say that my case is **control displacement** so there's no external loading, this is why the 1st step everything is supposed to be 0 (mistake!!)

**Comment by loumalouomega** [comment]
Please can you print the mInitialResidualNorm on residual_criteria.h?

**Comment by AlejandroCornejo** [comment]
> Please can you print the mInitialResidualNorm on residual_criteria.h?
If I put the Watch here:
```
    bool PostCriteria(
        ModelPart& rModelPart,
        DofsArrayType& rDofSet,
        const TSystemMatrixType& A,
        const TSystemVectorType& Dx,
        const TSystemVectorType& b
        ) override
    {
        const SizeType size_b = TSparseSpace::Size(b);
        if (size_b != 0) { //if we are solving for something

            SizeType size_residual;
            CalculateResidualNorm(rModelPart, mCurrentResidualNorm, size_residual, rDofSet, b);

            KRATOS_WATCH(mInitialResidualNorm)
...
```
 ```
[STEP:: 1  TIME: 1.0 ]
mInitialResidualNorm : 0
RESIDUAL CRITERION:  :: [ Obtained ratio = 0; Expected ratio = 0.001; Absolute norm = 8.51251; Expected norm =  1e-09]
RESIDUAL CRITERION: Convergence is achieved
 [STEP:: 2  TIME: 2.0 ]
mInitialResidualNorm : 72628.4
RESIDUAL CRITERION:  :: [ Obtained ratio = 3.00001; Expected ratio = 0.001; Absolute norm = 25.5375; Expected norm =  1e-09]
mInitialResidualNorm : 72628.4
RESIDUAL CRITERION:  :: [ Obtained ratio = 3.99142e-14; Expected ratio = 0.001; Absolute norm = 3.39768e-13; Expected norm =  1e-09]
RESIDUAL CRITERION: Convergence is achieved
 [STEP:: 3  TIME: 3.0 ]
mInitialResidualNorm : 0.0145048
RESIDUAL CRITERION:  :: [ Obtained ratio = 2.5036e+07; Expected ratio = 0.001; Absolute norm = 42.5624; Expected norm =  1e-09]
mInitialResidualNorm : 0.0145048
RESIDUAL CRITERION:  :: [ Obtained ratio = 3.33313e-07; Expected ratio = 0.001; Absolute norm = 5.66648e-13; Expected norm =  1e-09]
RESIDUAL CRITERION: Convergence is achieved
 [STEP:: 4  TIME: 4.0 ]
mInitialResidualNorm : 0.0208496
RESIDUAL CRITERION:  :: [ Obtained ratio = 2.43841e+07; Expected ratio = 0.001; Absolute norm = 59.5873; Expected norm =  1e-09]
mInitialResidualNorm : 0.0208496
RESIDUAL CRITERION:  :: [ Obtained ratio = 3.26226e-07; Expected ratio = 0.001; Absolute norm = 7.97196e-13; Expected norm =  1e-09]
RESIDUAL CRITERION: Convergence is achieved
```

**Comment by loumalouomega** [comment]
But here you are converging!!!

**Comment by AlejandroCornejo** [comment]
yes, here the case is in elastic. When damage is active it's different

**Comment by AlejandroCornejo** [comment]
I didn't say that it's not converging. I think that there's something weird or at least not conventional

**Comment by loumalouomega** [comment]
Can you post when the problem is giving you problems?

**Comment by AlejandroCornejo** [comment]
in my first comment you can see how we achieve convergence by the absolute_norm which is very weird, we should converge always according to the ratio and, if a certain step does not increase the load, then converge with the absolute criterion. (My opinion maybe I'm wrong)

**Comment by loumalouomega** [comment]
OK

**Comment by RiccardoRossi** [comment]
hi @AlejandroCornejo my impression is that what you are seeing is the expected behaviour of a residual criteria.

for the sake of the discussion let's imagine that you define your residual as r(x) = fext - K(x)*x 


what you check is that norm(r(x))/norm(r(x0)) < rel_tol 

at the beginning of a "normal" iteration, x0=xold so you do

     norm(r(x))/norm(r(xold))

now since xold is a "bad guess" then r(xold) may be an arbitrarily large number...the criterion correctly detects convergence when by modifying the criterion you get a reduction below the target threshold.

now,  if you have no displacement r(0) = fext. If you also don't have fext r(0)=0 . anything after that will be divided by zero. so in this specific case the only way to achieve convergence will be by reducing below the absolute convergence threshold.

one possible solution to avoid this would be to do:

~~~cpp
            if(mInitialResidualNorm < std::numeric_limits<TDataType>::epsilon()) {
                mInitialResidualNorm = mCurrentResidualNorm   <----HERE WHAT WE COULD DO
                ratio = 1.0;
            } else {
                ratio = mCurrentResidualNorm/mInitialResidualNorm;
            }
~~~

**Comment by loumalouomega** [comment]
@RiccardoRossi what you are suggesting it is what I suggested last week, @AlejandroCornejo did you tried?
