### ISSUE TITLE
[DEM] DEM and SDEM cleanup

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#4540]
Just following the comments in PR #4526, we should dedicate some time to make those adaptations. This issue is a reminder.

**Comment by maceligueta** [comment]
(referencing @philbucher)

**Comment by maceligueta** [comment]
I would add that all prints should be migrated to the Kratos Logger, so the tests could be silent.

**Comment by GuillermoCasas** [comment]
Addressed in #4574 for SwimmingDEMApplication

**Comment by maceligueta** [comment]
@farrufat-cimne :  as recommended by @philbucher , we should use the full path when importing python scripts. For example:
  ` import DEM_procedures_mpi as DP`
should be 
  `import KratosMultiphysics.DEMApplication.DEM_procedures_mpi as DP`
We should open a PR with a couple of changes in this direction. We can talk about this in person.

**Comment by philbucher** [comment]
Is this solved?

**Comment by maceligueta** [comment]
I don’t remember any PR migrating the prints to Logger...
