### ISSUE TITLE
MPI build instructions updated

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4545]
I updated the build instructions related to MPI:
https://github.com/KratosMultiphysics/Kratos/wiki/Linux-Build#compiling-with-mpi

In case you want to have a look
@jcotela @roigcarlo @maceligueta @RiccardoRossi @rubenzorrilla @pooyan-dadvand

**Comment by philbucher** [comment]
FYI @dagmawibekel

**Comment by vryy** [comment]
I suggest to add the definition of TRILINOS_SOURCE to the configure script or tell user that they have to define that in .bashrc. Otherwise, cmake does not know where to find trilinos.

**Comment by philbucher** [comment]
I wrote that `TRILINOS_ROOT` should be specified. https://github.com/KratosMultiphysics/Kratos/wiki/Linux-Build#compiling-trilinos-yourself
is this not enough?

**Comment by vryy** [comment]
yes, not enough. TRILINOS_SOURCE must also be defined.

**Comment by philbucher** [comment]
@vryy I added a note that it might be necessary to specify `TRILINOS_SOURCE `
Thanks for the hint

**Comment by vryy** [comment]
@philbucher you're welcome

**Comment by philbucher** [comment]
closing, this was just FYI
