### ISSUE TITLE
Error during installation of version 7.0 when building from source in Linux machine

### ISSUE THREAD

**Issue by Glovedsasquatchcodes** [KratosMultiphysics/Kratos#4560]
Dear all,
I have been facing the following issues when trying to build the application from source. This problem particularly appears when we configure contact structural mechanics application by adding the following line in the configure.sh file: 
`-D_CONTACT_STRUCTURAL_MECHANICS_APPLICATION=ON`

![error_installation](https://user-images.githubusercontent.com/38555287/55319300-d780e900-5474-11e9-9288-3427d90d6726.png)

Though in the above screenshot the problem says "virtual memory exhausted", however, the problem seems to persistent on all the 3 linux machines where I tried this (Two with 8 GB RAM and the other with 16 GB RAM and all having sufficient storage). Some how the memory usage shoots to a very value slowing down the systems, some times blocking other processes like synaptic touch or mouse movement, etc. for several minutes. 

Kindly look into this and help me as to how should I proceed with this.

**Comment by loumalouomega** [comment]
Are you using COTIRE?, it may be  a problem related with COTIRE, in any case I don't understand because it is compiled on Appveyor which has less than 8 GB of RAM

**Comment by Glovedsasquatchcodes** [comment]
Dear @loumalouomega ,
I tried passing a message in the COTIRE block of CMakeLists.txt file. The message doesn't get printed on the terminal, so I guess that cotire is not being used. 

Also, this problem was not with the previous version of Kratos.

**Comment by loumalouomega** [comment]
Can you post your configure.sh?, maybe it is an issue of the number of threads used

**Comment by loumalouomega** [comment]
BTW, I am compiling the Contact in my desktop computer which is a 8 years old computer with 16 GB but DDR3

**Comment by Glovedsasquatchcodes** [comment]
Here is the configure file.
~~~
clear

# you may want to decomment this the first time you compile
rm CMakeCache.txt
rm *.cmake
rm -rf CMakeFiles\

cmake ..                                                                            \
-DCMAKE_C_COMPILER=/usr/bin/gcc                                                     \
-DCMAKE_CXX_COMPILER=/usr/bin/g++                                                   \
-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 -std=c++11 "                           \
-DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -msse3 "                                          \
-DBOOST_ROOT="$/home/meinhard/Software/boost_1_69_0/boost_1_69_0/boost"                                                        \
-DPYTHON_EXECUTABLE="/usr/bin/python3"                                              \
-DCMAKE_BUILD_TYPE=Release                                                          \
-DMESHING_APPLICATION=ON                                                            \
-DEXTERNAL_SOLVERS_APPLICATION=ON                                                   \
-DSTRUCTURAL_MECHANICS_APPLICATION=ON                                               \
-DCONVECTION_DIFFUSION_APPLICATION=ON                                               \
-DSOLID_MECHANICS_APPLICATION=ON                                                    \
-DCONTACT_STRUCTURAL_MECHANICS_APPLICATION=ON					    \
-DCONSTITUTIVE_MODELS_APPLICATION=ON                                                \
-DFLUID_DYNAMICS_APPLICATION=ON                                                     \
-DMESH_MOVING_APPLICATION=ON                                                        \
-DFSI_APPLICATION=ON                                                                \
-DDEM_APPLICATION=ON                                                               \
-DSWIMMING_DEM_APPLICATION=ON                                                      \
-DMIXED_ELEMENT_APPLICATION=ON                                                     \
-DSHAPE_OPTIMIZATION_APPLICATION=ON                                                \
-DTOPOLOGY_OPTIMIZATION_APPLICATION=OFF                                             \
-DMETIS_APPLICATION=OFF                                                             \
-DPARMETIS_ROOT_DIR="/home/youruser/compiled_libraries/ParMetis-3.1.1"              \
-DTRILINOS_APPLICATION=OFF                                                          \
-DTRILINOS_ROOT="/home/youruser/compiled_libraries/trilinos-10.2.0"                 \
-DINSTALL_EMBEDDED_PYTHON=ON

# decomment this to have it verbose
# make VERBOSE=1 -j4
make -j4
make install`
~~~

**Comment by loumalouomega** [comment]
Only thing I can suggest is to switch -j4 to -j2, it will become slower, but will require less memory

**Comment by roigcarlo** [comment]
Hi @Glovedsasquatchcodes, is it possible that you are compiling in a 32 bit machine?
Also as @loumalouomega suggest, could you try to compile with -j1?

**Comment by Glovedsasquatchcodes** [comment]
Hi @loumalouomega and @roigcarlo ,
Though there were errors, the installation was complete and project was successfully installed now.

Therefore, closing this issue.
Thanks a lot for your help.
