### ISSUE TITLE
Using initial coordinates in python_function_callback_utility (to impose rotations from the GUI)

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#4562]
We weren't capable of rotating a SubModelPart from the GUI (Structural Mechanics, for example). 
Talking with @RiccardoRossi , we thought it would be possible if x,y,z were considered as X0(), Y0() and Z0() of the nodes. We should give the possibility, at least.

**Comment by philbucher** [comment]
closing since I would say that this is solved by #5387 

please reopen if otherwise
