### ISSUE TITLE
TemplateApplication: Sources not splitted into Core & Python

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4576]
Hi @roigcarlo 
I think it was discussed at some point to do the splitting of app-sources from python for every app right?
Just as a reminder, I think this is not yet done for the [template-application](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/templates/template_application/CMakeLists.txt.in) that is used in the app-generator
I would do it myself but I don't know how :/

mentioning @KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
Some classes are split (elements, conditions, etc..), some are not. I can take a look but it will be low priority :(

**Comment by philbucher** [comment]
cool, thx!
Maybe I also figure it out myself, lets see

**Comment by roigcarlo** [comment]
Actually its very easy. All the generation thing consist on some python scripts that deal with tokenized templates.

the application_generator.py one is the only exception as it also deals with the overall structure tree of the app. Anyway its only dictionaries, replaces and some regex. Also if you look at it, the `_addApplicationToAppList` is not used anymore. There was some dark magic there.
