### ISSUE TITLE
[Core] Packages

### ISSUE THREAD

**Issue by GuillermoCasas** [KratosMultiphysics/Kratos#4578]
I have recently been thinking (and also discussing with @miguelmaso and others) about the way in which enhancements to Kratos are developed. They are usually developed within apps and then, if general and serious enough, they can be moved to the core. Some people also create specific applications to contain such enhancements: ExternalSolversApplication, CoApplication and so on. 

However, I find this a misuse of the concept of Application, which in my opinion should involve the tools necessary to solve a specific family of physical problems.

So I would like to discuss the possibility of adding a new layer in Kratos, very akin to what we see in big open-source projects: the _Packages_.

I doubt this concept is new to you, but I would like to put it on the table again. I think the current way in which enhancements are introduced is not really sustainable, nor conceptually satisfying. Packages should be available only upon specific request and include families of generic tools, independent of the physical problem to be solved.

Any details on how to implement the packages can be discussed later, but I wanted to hear your opinion (@KratosMultiphysics/design-committee  and @KratosMultiphysics/implementation-committee) first.

**Comment by pooyan-dadvand** [comment]
hmmm, interesting! What I have not understood is how it helps our way of development. 

I see the package a good way for distinction of physic based apps from other ones like (trilinos, meshing, metis,  etc apps)

**Comment by AlejandroCornejo** [comment]
I think that it is a good idea and It will avoid many confussions and intersections of contents between Apps. I think that the idea of @GuillermoCasas is to better classify those "objects" that are applications (algorithms to solve some kind of problems) and packages (auxiliar operations like remeshing but they not solve any problem on its own).
Correct me if I'm wrong @GuillermoCasas .

**Comment by RiccardoRossi** [comment]
I am not clear of what is the difference between an "Application" and a "Package".
could u expand?

**Comment by loumalouomega** [comment]
> I am not clear of what is the difference between an "Application" and a "Package".
> could u expand?

Currently it is the same. But what @GuillermoCasas  stands for is differentiate between an application which purpose is define a physical problem (like electromagnetism) or the package that is something that can be common use, but has no problem associated, like mappers or solvers.

**Comment by loumalouomega** [comment]
> I think that it is a good idea and It will avoid many confussions and intersections of contents between Apps. I think that the idea of @GuillermoCasas is to better classify those "objects" that are applications (algorithms to solve some kind of problems) and packages (auxiliar operations like remeshing but they not solve any problem on its own).
> Correct me if I'm wrong @GuillermoCasas .

I think you defined perfectly

**Comment by loumalouomega** [comment]
From my point of view what I don't like is the name of "Package". I like the concept, but I would stand for something more like "Extension". In any case we should look at the competence to see how can we define this.

**Comment by RiccardoRossi** [comment]
But do you see it simply as a different name for "Application" or does it have a technical difference?

**Comment by AlejandroCornejo** [comment]
The difference between them is that the "package" cannot solve a problem on its own. For example the MeshingApp cannot solve a problem because needs a physics behind that is missing so it should be a package.

**Comment by RiccardoRossi** [comment]
let me reformulate my question. If you take the MeshingApplication and you rename it as MeshingPackage/Extension that would be all, or is there another difference?

**Comment by AlejandroCornejo** [comment]
That should be all, I think

**Comment by rubenzorrilla** [comment]
If there is no technical difference and it is just a naming issue, for me it makes no sense to completely break the retrocompatibility. Besides this might introduce silent import errors in those files that have no tests.

**Comment by pooyan-dadvand** [comment]
I understood the idea from the first comment, my question was how this help developers? Let say I don't think that anybody think that MeshingApplication would solve a physics. The question is about what it does.

And @GuillermoCasas metioned 

> Packages should be available only upon specific request and include families of generic tools, independent of the physical problem to be solved.

which is not clear how?

**Comment by AlejandroCornejo** [comment]
> If there is no technical difference and it is just a naming issue, for me it makes no sense to completely break the retrocompatibility. Besides this might introduce silent import errors in those files that have no tests.

I understand that maybe currently could seem pointless this distinction between Apps and Packages but, according to the increasing code growth, maybe we should think about organizing it the most clear as possible in order to anticipate some problems. In this sense I'm not saying that this is needed right now 
 (or ever) but it is indeed an interesting issue to talk about.

**Comment by rubenzorrilla** [comment]
> > If there is no technical difference and it is just a naming issue, for me it makes no sense to completely break the retrocompatibility. Besides this might introduce silent import errors in those files that have no tests.
> 
> I understand that maybe currently could seem pointless this distinction between Apps and Packages but, according to the increasing code growth, maybe we should think about organizing it the most clear as possible in order to anticipate some problems. In this sense I'm not saying that this is needed right now
> (or ever) but it is indeed an interesting issue to talk about.

This reminds me to the old "core" and "sandbox" (or "developing") applications discussion.
