### ISSUE TITLE
Kratos for fire simulation

### ISSUE THREAD

**Issue by fab6** [KratosMultiphysics/Kratos#4582]
Hi,
I am running fire simulation focusing on fire spread and just came across Kratos...

As I am completely new to Kratos, I would like to know if certain methods are already available or if there is any intention to implement any in the near future:

1. Combustion: Which combustion models are available?
2.  Pyrolysis: Is pyrolysis modelling included?
3. Radiation: Is there a FV-DOM method available?
4. I understood that turbulence modelling is possible with LES, is this right?
5. How good is the Parallel Performance? Are there any benchmark for this?
6. What options exist for importing the mesh? 

It would be great, if you can answer a few of my questions!
Thanks in advance!
Fabian

**Comment by loumalouomega** [comment]
Can we close this?

**Comment by fab6** [comment]
Hi, 
I would be happy to receive some comments about my questions.
Best Regards

**Comment by pooyan-dadvand** [comment]
ping @juliobarna and @RiccardoRossi

**Comment by RiccardoRossi** [comment]
Dear @fab6 i am not working in fire simulation but i'll answer as i can inline 

    Combustion: Which combustion models are available?

here we must have a comment by @juliobarna 

    Pyrolysis: Is pyrolysis modelling included?
    Radiation: Is there a FV-DOM method available?
    I understood that turbulence modelling is possible with LES, is this right?

correct. We use a technique known as Variational Multi Scale, which can be understood as a flavour of LES in which the filter is provided by the mesh

    How good is the Parallel Performance? Are there any benchmark for this?

parallel performance should be in principle quite good, in the sense that it should be able to scale in the thousands of mpi processes. Nevertheless our simulations tend to be a little heavier than ÇFV based simulations on a given mesh.

    What options exist for importing the mesh?

you'll need to convert to out own input format (.mdpa)

**Comment by fab6** [comment]
Hi Riccardo,
thank you for the further information!
I will look a bit more into it.
Thanks!
Fabian

**Comment by philbucher** [comment]
closing as inactive, please reopen if you have more questions
