### ISSUE TITLE
Problems building Kratos solution

### ISSUE THREAD

**Issue by SergioJimenezReyes** [KratosMultiphysics/Kratos#4589]
I am installing Kratos with @AlejandroCornejo in a windows computer and I am having problems when launching the configure.bat.

The following message is shown:

D:\SergioJimenezReyes\CIMNE\KRATOS\GitHub\cmake_build>configure.bat

D:\SergioJimenezReyes\CIMNE\KRATOS\GitHub\cmake_build>del CMakeCache.txt
No se pudo encontrar D:\SergioJimenezReyes\CIMNE\KRATOS\GitHub\cmake_build\CMakeCache.txt

D:\SergioJimenezReyes\CIMNE\KRATOS\GitHub\cmake_build>cmake -G "Visual Studio 15 2017 Win64"
        -DCMAKE_BUILD_TYPE=RelWithDebInfo                                                                                                               -DCMAKE_CXX_FLAGS=" -D_SCL_SECURE_NO_WARNINGS "                                                                                                   -DBOOST_ROOT="C:/boost_1_69_0"                                                                                                                    -DPYTHON_EXECUTABLE="C:/Users/sjimenez/AppData/Local/Programs/Python/Python37/python.exe" 
CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.

CMake Error: The source directory "D:/SergioJimenezReyes/CIMNE/KRATOS/GitHub/cmake_build" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

D:\SergioJimenezReyes\CIMNE\KRATOS\GitHub\cmake_build>-DPYTHON_INCLUDE_PATH="C:/Users/sjimenez/AppData/Local/Programs/Python/Python37/include"                                    
"-DPYTHON_INCLUDE_PATH" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

D:\SergioJimenezReyes\CIMNE\KRATOS\GitHub\cmake_build>-DLAPACK_LIBRARIES="D:/SergioJimenezReyes/CIMNE/KRATOS/ExternalLibraries/liblapack.lib"
-DBLAS_LIBRARIES="D:/SergioJimenezReyes/CIMNE/KRATOS/ExternalLibraries/libblas.lib"                                     -DMESHING_APPLICATION=OFF                                                                                                                         -DEXTERNAL_SOLVERS_APPLICATION=ON
                                        -DSTRUCTURAL_MECHANICS_APPLICATION=ON                                                                                                    -DCONVECTION_DIFFUSION_APPLICATION=OFF                                                                                                           -DSOLID_MECHANICS_APPLICATION=OFF                                                                                                                 -DCONSTITUTIVE_MODELS_APPLICATION=ON                                                                                                              -DFLUID_DYNAMICS_APPLICATION=OFF
                                -DMESH_MOVING_APPLICATION=OFF                                                                                                           -DFSI_APPLICATION=OFF                                                                                                                             -DDEM_APPLICATION=OFF                                                                                                                             -DSWIMMING_DEM_APPLICATION=OFF                                                                                                                    -DINSTALL_PYTHON_FILES=ON
                        -DINSTALL_EMBEDDED_PYTHON=ON                                                                                                                    -DEXCLUDE_ITSOL=ON                                                                                                                                -DKRATOS_INSTALL_PREFIX="D:/KratosInstall"                                          ..
"-DLAPACK_LIBRARIES" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

**Comment by roigcarlo** [comment]
Hi @SergioJimenezReyes 

Seems that there is a problem in the Python executable line. Probably a `\` is missing or it has a trailing whitespace

**Comment by SergioJimenezReyes** [comment]
> Hi @SergioJimenezReyes
> 
> Seems that there is a problem in the Python executable line. Probably a `\` is missing or it has a trailing whitespace

Solved, thanks, It seems that it doesn't stand tabulations
