### ISSUE TITLE
[MeshingApp] error in nightly tests

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4590]
~~~
Running tests for MeshingApplication
...
  ## Warning: MMG5_surf: at least 1 negative or null density.
E.
======================================================================
ERROR: test_execution (meshing_application_test_factory.ThreeDShellTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Kratos/applications/MeshingApplication/tests/meshing_application_test_factory.py", line 69, in tearDown
    self.test.Finalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/analysis_stage.py", line 115, in Finalize
    process.ExecuteFinalize()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 88, in ExecuteFinalize
    self.__CompareSolMetricFile()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 322, in __CompareSolMetricFile
    lines_ref, lines_out = self.__GetFileLines()
  File "/home/ubuntu/Kratos/kratos/python_scripts/compare_two_files_check_process.py", line 111, in __GetFileLines
    raise Exception(err_msg)
Exception: The specified reference file name "/home/ubuntu/Kratos/applications/MeshingApplication/tests/mmg_lagrangian_test/test_remesh_shell_result.sol" is not valid!

----------------------------------------------------------------------
Ran 5 tests in 38.059s
~~~

**Comment by loumalouomega** [comment]
I don't know why...
![imagen](https://user-images.githubusercontent.com/19991680/55610267-dc021600-5782-11e9-9c01-77fa9b482a16.png)

What exactly means "Exception: The specified reference file name "/home/ubuntu/Kratos/applications/MeshingApplication/tests/mmg_lagrangian_test/test_remesh_shell_result.sol" is not valid!" ?, the file is not found or it is not equal?

**Comment by philbucher** [comment]
it means that the file does not exist => probably happens bcs MMG crashes

can you run the tests from the core (python_scripts/run_tests.py)?

**Comment by loumalouomega** [comment]
OK, but the adress is supposed to be relative...

**Comment by loumalouomega** [comment]
> it means that the file does not exist => probably happens bcs MMG crashes
> 
> can you run the tests from the core (python_scripts/run_tests.py)?

Not a problem

**Comment by philbucher** [comment]
are you using the same version of MMG

**Comment by loumalouomega** [comment]
> are you using the same version of MMG

Yes, the version I uploaded is the one of my computer...

**Comment by philbucher** [comment]
hm then I also don't know
But it only appeared recently

**Comment by philbucher** [comment]
Ping

**Comment by loumalouomega** [comment]
Still failing?

**Comment by philbucher** [comment]
Unfortunately :/

**Comment by loumalouomega** [comment]
Puff

**Comment by loumalouomega** [comment]
Still happening? I changed many things recently in the MeshingApp

**Comment by philbucher** [comment]
Have you checked the out the nightly build?

**Comment by loumalouomega** [comment]
I marked the email as spam once and now it is automatically deleted and I
cannot find it.

**Comment by philbucher** [comment]
I checked the one from last night, still happening :/
Isn't this sh related to MMG?

**Comment by loumalouomega** [comment]
> I checked the one from last night, still happening :/
> Isn't this sh related to MMG?

yes, but it  is supposed to be fixed

**Comment by roigcarlo** [comment]
Is this still a thing?

**Comment by philbucher** [comment]
there is still an MMG warning but I think we can close this 
~~~
 Running tests for MeshingApplication
.......
  ## Warning: MMG5_surf: at least 1 negative or null density.
..
----------------------------------------------------------------------
Ran 9 tests in 8.711s
~~~
