### ISSUE TITLE
An error occurred when I used kratos

### ISSUE THREAD

**Issue by yanggexuan** [KratosMultiphysics/Kratos#4602]
I'm a student, and when I try to use a 3D example, it goes wrong.   
The code: Some errors found in the results file: Error reading file'C:/Users/yang/Desktop/EX33D.gid/EX33D.post.bin': error reading values for Scalar result 'PRESSURE' of analysis 'Kratos', step '0.2' : <fd:17>: unexpected end of file Only 128820 out of 163391 values read.<fd:17>: unexpected end of file
<fd:17>: unexpected end of file.

**Comment by rubenzorrilla** [comment]
Has your simulation completely and successfully finished? This message appears when your simulation is rather running or crashed. As it explains, the problem is that the output file is not properly ended.

**Comment by jginternational** [comment]
In order to fix this, the application should print it's output the way DEM does, so the user can go to postprocess even if the calculation is not finished with no warnings

**Comment by rubenzorrilla** [comment]
> In order to fix this, the application should print it's output the way DEM does, so the user can go to postprocess even if the calculation is not finished with no warnings

@jginternational thanks for the hint. We should have a look to it.

**Comment by philbucher** [comment]
> In order to fix this, the application should print it's output the way DEM does, so the user can go to postprocess even if the calculation is not finished with no warnings

Can you please describe what you mean @jginternational ?
