### ISSUE TITLE
3D fluid model simulation

### ISSUE THREAD

**Issue by yanggexuan** [KratosMultiphysics/Kratos#4604]
I just find the 2D model of the GID and how to work. But now,I want to know the details of 3D fluid model with Kratos such as how to set the conditions with the model and so on. Do you guys have any models of the 3D? Please cantact with me . Here is my eMail:925071469@qq.com.

**Comment by rubenzorrilla** [comment]
I've just tried to run a few steps of the 3D predefined example in the GiD GUI and works as expected. Yo must be capable of loading it in the same manner you generated the 2D but selecting the 3D option in the application market pop-up window.

**Comment by yanggexuan** [comment]
Thank you so much for your reply.I want to know how long it takes to calculate a 3d model.l spent seven hours trying to calculate a model.Now I want to mix two liquids,I try to use kratos to set conditions，but it cant calculate. @rubenzorrilla

**Comment by rubenzorrilla** [comment]
The computation time completely depends on the machine you are using. If it is taking too long in the machine you are using, it is also possible to run it in a distributed memory platform. In the GUI you need to change the parallel type to MPI (it will prepare the source files to be run in the cluster).

Concerning the two fluids mixing, as far as I know the unique two fluids formulations in Kratos assume that the fluids are immiscible.

**Comment by philbucher** [comment]
closing since inactive
please reopen if needed
