### ISSUE TITLE
Fluid 3D - Cut Plane error

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#4623]
I've detected a Bug in Fluid 3D when a CutPlane is defined.

 ```
 File "MainKratos.py", line 32, in <module>
    simulation.Run()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\kratos\python_scripts\analysis_stage.py", line 47, in Run
    self.Initialize()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\kratos\python_scripts\analysis_stage.py", line 84, in Initialize
    process.ExecuteInitialize()
  File "E:\PROYECTOS\KratosGiD\kratos.gid\exec\kratos\kratos\python_scripts\gid_output_process.py", line 144, in ExecuteInitialize
    self.cut_model_part = ModelPart("CutPart")
TypeError: Kratos.ModelPart: No constructor defined!
```

@soudah 
@KratosMultiphysics/fluid-dynamics 
@KratosMultiphysics/fluid-maintainers 

Attached case

[CutPlane3D.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/3060138/CutPlane3D.gid.zip)

**Comment by rubenzorrilla** [comment]
The model part must be constructed by means of the model.

**Comment by jginternational** [comment]
@rubenzorrilla 

![image](https://user-images.githubusercontent.com/5918085/56282681-07381e00-6110-11e9-987c-fda79f86857c.png)

**Comment by rubenzorrilla** [comment]
The model part constructor was intentionally removed to construct all the model parts through the `Model` container. It seems that the `gid_output_process` is still trying to construct the cut model parts using the old constructor (which is not present anymore). We need to change it to something like `my_model.CreateModelPart("CutModelPartName")`.
