### ISSUE TITLE
explicit dynamic scheme for contact solver

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#4646]
My aim is to simulate contact problem with explicit solver. I changed the parameters of double_arc test to explicit, but core dumped at the very beginning. what should i do to adjust the parameters for explicit one?  
***
terminate called after throwing an instance of 'Kratos::Exception'
terminate called recursively
Aborted (core dumped)
***

**Comment by loumalouomega** [comment]
The explicit contact is in a very alpha state, in fact many important developments are on a branch. I don't recommend to use it for now.

**Comment by ZhimingGuo** [comment]
Can structuralmechanicsapplication be used to make drop test simulation? it should be explicit solver, such as phone drop test.

**Comment by loumalouomega** [comment]
Do you mean define a flat surface to simulate the impact between the phone (solid elements) and the flat surface?. Right now as I said the explicit contact (which you need to simulate impact) is in early state, probably it will not work well. as I said I have a branch with several improvements, but is in early state of development too.

**Comment by ZhimingGuo** [comment]
yes, it is exactly what you described, solid and flat surface. 
so, what can i do for you? i think i can do something for this branch if you'd like.

**Comment by ZhimingGuo** [comment]
Can i use ContactMechanicsApplication to simulate the drop problem? there is rigid material in the application. Actually, the flat surface should be rigid.

**Comment by loumalouomega** [comment]
I don't know about that application and how to use it, it is maintained by
@josep-m-carbonell

**Comment by loumalouomega** [comment]
> yes, it is exactly what you described, solid and flat surface.
> so, what can i do for you? i think i can do something for this branch if you'd like.

I don't feel confident to use the explicit contact yet

**Comment by loumalouomega** [comment]
> I don't know about that application and how to use it, it is maintained by @josep-m-carbonell 

It is implicit I think

**Comment by ZhimingGuo** [comment]
Electronic product drop test is always simulated by explicit integration solver, such as Ls-dyna.

**Comment by loumalouomega** [comment]
Closing for inactive, reopening if necessary
