### ISSUE TITLE
[Core] LineOutputProcess does not find points

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#4652]
The LineOutputProcess does not find any points/elements when using it in MPI. Any ideas?

**Comment by philbucher** [comment]
Again :/
Can you please give us some more info?
What is the output of the process?
And maybe a small case to reproduce?

**Comment by AndreasWinterstein** [comment]
The error is: _Point Locator: No Element found for Point: Point(300, 0, 251.02)_
The example is a simple, empty rectangular channel. Nothing special. You can find it attached.
[Empty_channel_test.zip](https://github.com/KratosMultiphysics/Kratos/files/3076621/Empty_channel_test.zip)

It depends on the partitioning how many elements can be found. The more partitions the less elements are found. For the structural problem it was necessary to explicitly give the submodelpart to the point output process and also explicitly add it to the computing model part.

**Comment by AndreasWinterstein** [comment]
Here a smaller test with no additional interior refinement, which is unfortunately also not working.

[LineOutputTest.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/3076667/LineOutputTest.gid.zip)

For two cores it is at least finding some elements. But when increasing the number of cores the number of elements which cannot be found increases accordingly.

**Comment by philbucher** [comment]
ok thx I will take a look
does it only fail on the cluster or also locally?

**Comment by AndreasWinterstein** [comment]
In this case on both. But as I found out for the structural mechanics part, this is machine dependent.

**Comment by AndreasWinterstein** [comment]
Short update. @mpentek talked to the colleagues in Italy. They recently did use the LineOutputProcess on their cluster, but did not have the problems I saw. They also used intel mpi. Which is quite strange.

**Comment by AndreasWinterstein** [comment]
Fixed by PR #4620.
