### ISSUE TITLE
Accessing Tsai-Wu reserve factor from Python

### ISSUE THREAD

**Issue by emanujoy** [KratosMultiphysics/Kratos#4694]
Hi,
We are building a model in GiD with a "dummy" isotropic material that we are replacing with an orthotropic material in Python the following code:

    with open("ProjectParameters.json", 'r') as parameter_file:
         parameters = km.Parameters(parameter_file.read())model = km.Model()
    simulation = StructuralMechanicsAnalysis(model, parameters)
    simulation.Initialize()solver = simulation._GetSolver()
    cmp = solver.GetComputingModelPart()
    orthotropic_props = GetOrthotropicProperties(Theta)
    cmp.GetProperties()[1].SetValue(sma.SHELL_ORTHOTROPIC_LAYERS,
                                                    orthotropic_props)
    cl = sma.LinearElasticOrthotropic2DLaw()
    cmp.GetProperties()[1].SetValue(km.CONSTITUTIVE_LAW, cl)

After solving with this, we try to access the Tsai-Wu reserve factor via

    cmp.Elements[ii+1].CalculateOnIntegrationPoints(sma.TSAI_WU_RESERVE_FACTOR,
                                                                cmp.ProcessInfo)[0]

This code is though leading to an evil "Kernel died, restarting" error.

what are we missing or doing wrong?

Thank you.

**Comment by e-dub** [comment]
Small, quick but dirty example with problem:
[Shell_component.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/3106364/Shell_component.gid.zip)

**Comment by philbucher** [comment]
Hi Guys,
Several comments:
- I don't see any obvious error
- Could your try to do what you do in [`ModifyInitialProperties`](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/analysis_stage.py#L78)? This is the intended place to do this
- If this doesn't work then can you try in fulldebug and post the error?

NOTE: the orthotropic shells are not tested much, I even would consider them experimental so please check your results carefully. 
At some point I will refactor the stress computation in the shells then this should become more stable

Also: how do you assign the global fiber direction?

**Comment by e-dub** [comment]
Thanks Philip! 

Using `ModifyInitialProperties` exposed the (or an) error (and maybe explains why the code works if there is only one layer, but not for more): `RuntimeError: Error: Specifying THICKNESS conflicts with the definition of  SHELL_ORTHOTROPIC_LAYERS (where the thickness is also specified)`

Can I just kill the old material property set with `mp.RemoveProperties(1)`

As for orthotropic shells being experimental: We are happy to do some testing here. 

The orientation of elemental coordinate system was done in GiD, but Emanuele will have to expound on this. How have you guys built such models?

**Comment by philbucher** [comment]
> Thanks Philip!
> 
> Using `ModifyInitialProperties` exposed the (or an) error (and maybe explains why the code works if there is only one layer, but not for more): `RuntimeError: Error: Specifying THICKNESS conflicts with the definition of SHELL_ORTHOTROPIC_LAYERS (where the thickness is also specified)`

This is just a logic check, done before any computation, don't know if this is responsible for your error. Theoretically I think it could be removed for testing... Could you try if it works then? If so, then we could discuss turning it into a warning.
After all, the orthotropic analysis is far from being consolidated

> Can I just kill the old material property set with `mp.RemoveProperties(1)`

I think so but then you probably have to assign the new props to every element again.

> 
> As for orthotropic shells being experimental: We are happy to do some testing here.
> 
> The orientation of elemental coordinate system was done in GiD, but Emanuele will have to expound on this. How have you guys built such models?

I have no idea what GiD does, I never heard that it was possible to specify the orientation through GiD. TBH I thought I was the only one using the orthotropic stuff. 
Actually I am pretty sure that it does not work through GiD because the functionality to specify the global direction is in one of my many dev-branches :)

**Comment by emanujoy** [comment]
Thanks Philip,
about the coordinate reference system i posted an issue (question) several weeks ago. see: https://github.com/KratosMultiphysics/GiDInterface/issues/563
through the command on GID: "-np- gid_groups_conds::local_axes_window"  i can see the local reference system of each element, and also create a new global system as reference for the local ones. knowing now the local reference system i should only find out which reference is kratos using (x y or unlikely z) for the orthotropic direction.

**Comment by e-dub** [comment]
I commented lines 465 through 479 of [base_shell_element.cpp](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/custom_elements/base_shell_element.cpp) and it appears we are in business!  I (or better said EmanueleJ) still need to check the results.

**Comment by e-dub** [comment]
> Thanks Philip,
> about the coordinate reference system i posted an issue (question) several weeks ago. see: [KratosMultiphysics/GiDInterface#563](https://github.com/KratosMultiphysics/GiDInterface/issues/563)
> through the command on GID: "-np- gid_groups_conds::local_axes_window" i can see the local reference system of each element, and also create a new global system as reference for the local ones. knowing now the local reference system i should only find out which reference is kratos using (x y or unlikely z) for the orthotropic direction.

Please correct me if I am wrong, but I do not think that Kratos "sees" the assignment of the coordinate systems in GiD (see JSON and MDPA files).  Kratos "reassigns" the element coordinate system.

**Comment by e-dub** [comment]
> > Thanks Philip!
> > Using `ModifyInitialProperties` exposed the (or an) error (and maybe explains why the code works if there is only one layer, but not for more): `RuntimeError: Error: Specifying THICKNESS conflicts with the definition of SHELL_ORTHOTROPIC_LAYERS (where the thickness is also specified)`
> 
> This is just a logic check, done before any computation, don't know if this is responsible for your error. Theoretically I think it could be removed for testing... Could you try if it works then? If so, then we could discuss turning it into a warning.
> After all, the orthotropic analysis is far from being consolidated
> 
> > Can I just kill the old material property set with `mp.RemoveProperties(1)`
> 
> I think so but then you probably have to assign the new props to every element again.
> 
> > As for orthotropic shells being experimental: We are happy to do some testing here.
> > The orientation of elemental coordinate system was done in GiD, but Emanuele will have to expound on this. How have you guys built such models?
> 
> I have no idea what GiD does, I never heard that it was possible to specify the orientation through GiD. TBH I thought I was the only one using the orthotropic stuff.
> Actually I am pretty sure that it does not work through GiD because the functionality to specify the global direction is in one of my many dev-branches :)

I am now orienting the element coordinates by looping through the elements immediately before assigning the orthotropic properties.  I would like to confirm MATERIAL_ORIENTATION_ANGLE is the angle between the local XY and global XY coordinate systems about Z.  We good?

**Comment by philbucher** [comment]
@e-dub yes it does not see the GiD-assigned CS. this is not yet implemented for the shells/membranes, only for the beams

Your example (the mdpa) does not contain any information, e.g. the LOCAL_AXIS_2 in the beam case
=> this is required to be assigned a) by the preprocessor or b) by some process/utility in Kratos

**In order to make it usable we have to do the following steps:**
1. Define how the shells/membrane elements should define the usage of a custom local CS. For the Beam this is defined [here](https://github.com/KratosMultiphysics/Kratos/wiki/Local-axes-orientation). I will speak to @AndreasWinterstein abt this since he usually knows those things and post a proposal here.
2. It needs to be implemented. For the shells I can do it, for the membrane we have a student working on this atm
3. GiD needs to write the required information to the mdpa, same as what it does for the beam. 
4. I also have a utility with which the assignment can be done inside Kratos
5. Some adaptions to the orthotropic law will be necessary.
6. I will need someone to help me with the testing of the implementations. @e-dub @emanujoy can you help me here? This would speed up the process a lot!

What do you think? With my proposal we could properly use the orthotropic materials for shells&membranes

**Comment by philbucher** [comment]
> I am now orienting the element coordinates by looping through the elements immediately before assigning the orthotropic properties. I would like to confirm MATERIAL_ORIENTATION_ANGLE is the angle between the local XY and global XY coordinate systems about Z. We good?

@e-dub seems like we wrote at the same time. Yes, this is what currently happens, at least it should be :)
What do you think abt my proposal for integrating this properly?

**Comment by e-dub** [comment]
> > I am now orienting the element coordinates by looping through the elements immediately before assigning the orthotropic properties. I would like to confirm MATERIAL_ORIENTATION_ANGLE is the angle between the local XY and global XY coordinate systems about Z. We good?
> 
> @e-dub seems like we wrote at the same time. Yes, this is what currently happens, at least it should be :)
> What do you think abt my proposal for integrating this properly?

Proposal sounds great!  If I understand you correctly, the goal would be to enable both the use of a "GiD method" to reorient the local coordinate systems or just take any mesh and reorient it within in Kratos? And we will of course assist in testing! Perhaps a unification of the nomenclature is in order: "local axis" also for shells?  

What I am seeing now: The angles are being changed by assigning MATERIAL_ORIENTATION_ANGLE.  This, though, is not being written to the vtk; it is always reporting the angle as 0. I took a test example as "inspiration".  If interested, see attached. 

[shell_component.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/3121564/shell_component.gid.zip)

**Comment by philbucher** [comment]
> Proposal sounds great! If I understand you correctly, the goal would be to enable both the use of a "GiD method" to reorient the local coordinate systems or just take any mesh and reorient it within in Kratos? 

exactly

> And we will of course assist in testing! 

Awesome, thx

>Perhaps a unification of the nomenclature is in order: "local axis" also for shells?

Yes, I will get back to you once we have a proposal

> What I am seeing now: The angles are being changed by assigning MATERIAL_ORIENTATION_ANGLE. This, though, is not being written to the vtk; it is always reporting the angle as 0. I took a test example as "inspiration". If interested, see attached.

hm interesting. It works in GiD?

**Comment by emanujoy** [comment]
>     6. I will need someone to help me with the testing of the implementations. @e-dub @emanujoy can you help me here? This would speed up the process a lot!

> What do you think? With my proposal we could properly use the orthotropic materials for shells&membranes

Yes sure we can test them, and it would be great to find a good result to use the orthotropic materials. 
thank you!

**Comment by philbucher** [comment]
FYI we made progress in this direction in #6044
now we have a process to assign the directions to the elements, hence I am closing this

please reopen if necessary
