### ISSUE TITLE
[Core] Element or Condition based distance calculation

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#4706]
Dear all,

I came across again with the question of which is the most suitable entity type (element or condition) for the skin when computing distance level-set functions. This, turns to be in which is the most suitable entity type for skin model part the `FindIntersectedObjectsProcess` since it is the base for computing the distance as well as another embedded utilities (e.g. FM-ALE, embedded nodal variable, ...).

Right now, it is assumed that the skin is provided as a cloud of **elements** (lines in 2D and triangles in 3D). This makes perfectly sense, since it allows to directly pass the model part as it is when dealing with shell or membrane type structures.

The problem arises when dealing with solid bodies, since we normally save the skin as a cloud of conditions and the `FindIntersectedGeometricalObjectsProcess` expects a cloud of elements. What I normally do to circumvent this problem is to create a new element-based skin model part, which is a copy of the condition based skin but made up with elements. Apart of the memory consumption overhead, I don't really like this solution since it adds complexity to the implementation.

This issue is to get some feedback from the community about what could be done to better handle this situation. So far, what comes to my mind is:

1. We keep things as they are meaning that an element-based skin is always required
2. We create a derived condition based `FindIntersectedGeometricalObjectsProcess` which does the same operations but looping conditions. In the past we have something similar to this and I personally would avoid this option since not only implies the addition of this new class but the consequently derived utilities ones.
3. We modify the `FindIntersectedGeometricalObjectsProcess`to work with both types of entities. I don't know how yet, but maybe a template argument with the container type could do the job. @loumalouomega if I'm not wrong, you've done something similar for other utilities. Am I wrong?

@pooyan-dadvand @RiccardoRossi @marcnunezc  I'm tagging you since you are potential developers and users of these utilities.

**Comment by loumalouomega** [comment]
> We modify the FindIntersectedGeometricalObjectsProcessto work with both types of entities. I don't know how yet, but maybe a template argument with the container type could do the job. @loumalouomega if I'm not wrong, you've done something similar for other utilities. Am I wrong?

@rubenzorrilla  It is done in #4263, I can split the PR, so will be easier to merge

**Comment by loumalouomega** [comment]
@rubenzorrilla I created the PR, I don't like to subdivide to much the PR, because many conflicts appear, but as this is a request I do for you ;)

**Comment by rubenzorrilla** [comment]
Nice feature! Thanks for the implementation. Despite I didn't want to add more complexity to this in the past, right now I was thinking in something similar to this.

However, the question about how we should proceed with the utilities that use the `FindIntersectedGeometricalObjectsProcess` is still open:
- should we export them to Python as `MyUtilityElements` and `MyUtilityConditions` 
- or should their constructor have an argument similar to `use_element_base_skin = True`

**Comment by pooyan-dadvand** [comment]
I see it very useful and I think the second option `use_element_base_skin = True` would be more flexible in use but the first option can be cleaner to implment
