### ISSUE TITLE
vtk output problem for quadratic element

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#4709]
there is vtk output problem when i use structural element 3D10N instead of 3D4N. it is ok for 3D4N

![Screenshot from 2019-04-21 19-51-26](https://user-images.githubusercontent.com/26964544/56556013-4a3f3900-65c9-11e9-8102-6f712bd2d8dd.png)

**Comment by loumalouomega** [comment]
This is easy to solve, one sec.

**Comment by loumalouomega** [comment]
Can you check #4710?

**Comment by ZhimingGuo** [comment]
same error with before, Multi-Physics 7.0.0-4e433cb-Debug.
![Screenshot from 2019-04-23 14-29-20](https://user-images.githubusercontent.com/26964544/56559453-4cf35b80-65d4-11e9-94b4-d16c40b900f0.png)

**Comment by loumalouomega** [comment]
Can you pull and tell me the error is giving to you?, maybe your quadratic is not Kratos_Tetrahedra3D10 but something else.

**Comment by ZhimingGuo** [comment]
git pull information,
***
From https://github.com/KratosMultiphysics/Kratos
   f7fbf09..bd7edfd  core/quadratic-elements-vtk-output -> origin/core/quadratic-elements-vtk-output
Already up-to-date.
***
 the element I used, 
***
Begin Elements SmallDisplacementElement3D10N// GUI group identifier: Parts Auto2
***
the error attached
***
  File "/home/zhiming/Kratos2019/kratos/python_scripts/vtk_output_process.py", line 66, in PrintOutput
    self.vtk_io.PrintOutput()
RuntimeError: Error: Modelpart contains elements or conditions with geometries for which no VTK-output is implemented!

in kratos/input_output/vtk_output.cpp:351:void VtkOutput::WriteCellType(const TContainerType&, ofstream&) const [with TContainerType = PointerVectorSet<Element,...>; ofstream = basic_ofstream<char>]
***

**Comment by loumalouomega** [comment]
strange, it is supposed to tell the element type

**Comment by loumalouomega** [comment]
It works fine in my computer:

![imagen](https://user-images.githubusercontent.com/19991680/56563056-1f45ec80-65ab-11e9-84dd-2bc4e1dfbf25.png)

And it is quadratic:

![imagen](https://user-images.githubusercontent.com/19991680/56563230-692ed280-65ab-11e9-98ea-73cd542134f9.png)

**Comment by loumalouomega** [comment]
Did you recompile?

**Comment by loumalouomega** [comment]
I added a test, it just works

**Comment by ZhimingGuo** [comment]
ok, i am trying to recompile it after making clean.

**Comment by ZhimingGuo** [comment]
same problem. where is the test you made?

**Comment by loumalouomega** [comment]
kratos/tests/test_vtk_output_process.py line 138

**Comment by ZhimingGuo** [comment]
it works, thanks
