### ISSUE TITLE
[Core] mortar mapper tests fail in python 2.7

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#4715]
Hi @loumalouomega , can you take a look?

![image](https://user-images.githubusercontent.com/25667299/56586245-a0b77200-65df-11e9-8ef9-9dbbee9dfa13.png)

**Comment by loumalouomega** [comment]
Looks like a problem related with the json checker, we have changed a lot recently... @philbucher

**Comment by ddiezrod** [comment]
Oh you are right @loumalouomega , sorry I thought it was in your side

**Comment by philbucher** [comment]
Sorry guys will take a look tmr
Seems like I used py3-only formatting
