### ISSUE TITLE
What to do with the Mapping?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4726]
Hi all,
This issue is abt what to do with the mapping in Kratos. We discussed it several times already but I don't think we have reached a consensus yet
Current situation is the following:
- @loumalouomega has an implementation of a mortar-mapper in the core
- There is an old mapper in the FSIapplication
- I am implementing mappers in the MappingApplication, inherently working in serial and MPI
- Also there are some mappers in the ShapeOptimizationApplication, but those are quite specific to VertexMorphing afaik. I think they are self-contained (as long as they don't need MPI, which would require to use the functionalities of the MappingApp I think) FYI @dbaumgaertner @armingeiser 
- others (@andreas-apostolatos @emiroglu-statik @dbaumgaertner ) are using the mappers from Empire through python

Since it is my research, my long term goal is to integrate / reimplement the mappers that we have somehow flying around in the MappingApp such that they are also working in MPI (this includes esp the Mortar and the IGA-Mappers, but also others like the beam-mapper or an RBF-mapper, which do not yet exist in Kratos) This means that the other mappers could be replaced at some point

@pooyan-dadvand told me that he wants to have the MappingApp integrated in the Core at some point, but I also heard the opposite opinion, saying that the mapping CAN be used but does not have to be (Multiphysics also includes SinglePhysics for which mapping is not used) Then having the mappers in an application would make more sense.

I personally don't have a strong opinion, although I lean more towards leaving it in an application. This way the development is easier for me and we don't overload the core with things that not everyone uses. Also the MPI-mapping is depending on trilinos (I use Epetra for the Mapping-matrix in MPI), this would mean that we would have to make the (MPI)-Core dependent on Trilinos, which I know many (e.g. the DEM-guys) would not appreciate (and also makes no sense IMO)

@RiccardoRossi proposed a python-based mapper-factory that can be used from any app, that can also construct mappers from other apps.
@rubenzorrilla and I discussed this yesterday but we thought that it could make more sense to instead move the MortarMapper from the Core to the MappingApp and register it properly in the C-Factory
=> this way everyone that want to use mapping would import the MappingApp (this is anyway the long-term solution) and create the mappers they want

All of the above is up for discussion, I would like to hear your opinions on this before we continue

**Comment by loumalouomega** [comment]
Related with https://github.com/KratosMultiphysics/Kratos/issues/4578

Mappers as @GuillermoCasas would say, are ratter a multipurpose utility than a physical problem by itself.

**Comment by RiccardoRossi** [comment]
I am not against moving this to the meshing_application

**Comment by rubenzorrilla** [comment]
> I am not against moving this to the meshing_application

Do you mean `MappingApplication`?

**Comment by RiccardoRossi** [comment]
yes, sorry

**Comment by pooyan-dadvand** [comment]
I didn't get the rational against moving the serial mapper to the core. It would be great if you explain it more.

I understand that there are apps that never use it but on the other side I think for the rest to be coupled having a core functionality is a must for kratos "multi-physics". Being used by many application is another reason to be in core.

Another important reason would be to have some standard mapping hooks in the applications where we will use a transparent "do nothing mapper" in standard mode but in coupling will be used for mapping. (like the approach we took for MPI synchronize) For this we should have at least some part of the mapping in the core. 


Meanwhile, the dependency to trilinos is an strong argument to exclude it from the core. but MPI core?

**Comment by jcotela** [comment]
@pooyan-dadvand regarding the MPI core, the problem is that we introduce a circular dependency between MPI core and trilinos.

On the one hand, this is only a technical issue and I'm sure that we could find a workaround if this is the route we want to follow. On the other, the MPI core would then be dependent on having trilinos available for compilation, which is something I think we don't want.

**Comment by pooyan-dadvand** [comment]
I see... but at least for serial version I would like to have it in the core....

**Comment by rubenzorrilla** [comment]
@pooyan-dadvand to have all the features needed to do multi-physics available in the core is a fair argument. However, what doesn't make sense at all for me is to have some serial mappers in the MappingApplication and some of them in the core, without taking into account other mappers (some of them deprecated) in other applications. 

Taking into account the current status of the implementations, I think that makes more sense to try to unify things as much as possible in the MappingApplication as a first step. In the medium or long-term, once everything is stable, clean and encapsulated in one place, we can discuss about migrating the serial part to the Kratos core. I think that in this way @philbucher 's mapping development will be easier.

**Comment by pooyan-dadvand** [comment]
I was talking about the long therm. I see a logical step in putting everything in MappingApplication if this make the transition easier.

**Comment by philbucher** [comment]
closing for now, will most probably reopen in the future :)
Thanks for your contributions!
