### ISSUE TITLE
Repository is broken for Windows

### ISSUE THREAD

**Issue by jrubiogonzalez** [KratosMultiphysics/Kratos#4727]
@philbucher @SergioJimenezReyes you have 2 branches with exact same name but for a lower case/ capital. Structural/adding-hcf-cl and structural/adding-hcf-cl. This brakes the repository in windows systems as it is not case sensitive (known issue of Git under windows)

@pooyan-dadvand

**Comment by philbucher** [comment]
Hm I only commented on the PR, the branch(es) belong to @SergioJimenezReyes

**Comment by philbucher** [comment]
FYI @tteschemacher

**Comment by jrubiogonzalez** [comment]
OK

**Comment by SergioJimenezReyes** [comment]
I have deleted the useless branch. Sorry for that. Do I have to do something else?

**Comment by philbucher** [comment]
is this solved @jrubiogonzalez ?

**Comment by jrubiogonzalez** [comment]
I think so, now we have a problem on our side that we are trying to fix. But it looks good to me.

**Comment by rubenzorrilla** [comment]
Closing the issue then.
