### ISSUE TITLE
Intrusive flag in DEM application

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#473]
I just detected that there is a flag added in DEM

```CMAKE
add_definitions( -Wsuggest-override )
```
It breaks windows compilation. Can we remove this @maceligueta ?

**Comment by maceligueta** [comment]
Can we leave it for the gcc compilation?
Is it possible to add this flag just for gcc? Honestly, I think it is a very useful flag.

**Comment by roigcarlo** [comment]
Yep, it can be added only to GCC. The only problem is win, as long as we remove it from there or add it in a way cmake understands that needs to be converted to MSVC format its fine. I can do it tomorrow in 5 min if you want

**Comment by maceligueta** [comment]
I think it would take me more than that. Thanks, Charlie.

**Comment by roigcarlo** [comment]
Nono is not hard at all. Seriusly, we need to add just a couple of lines:

```C++
if(${CMAKE_COMPILER_IS_GNUCXX})
    add_definitions( -Wsuggest-override )
endif
```

Or even better modify locally the `CMAKE_CXX_FLAGS` with thr new flag.

The problem with add_definitions is that CMake does not know that is a flag, it assumes you are trying to add a define (i.e. `-DKRATOS_WHATEVER=ON`), so the `-` does not get converted to `\`
