### ISSUE TITLE
error when importing MetisApplication without mpi

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#4731]
title says it all. I get the error when runnign the tests

core/experiment_with_intrusive_ptr* +7978  ~/.../kratos/python_scripts  python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from KratosMultiphysics import *
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 7.0.0-ffe46e1713-FullDebug
>>> from KratosMultiphysics.MetisApplication import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/riccardo/Kratos/KratosMultiphysics/MetisApplication/__init__.py", line 3, in <module>
    from KratosMetisApplication import *
ImportError: /home/riccardo/Kratos/libs/KratosMetisApplication.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6Kratos19MPIDataCommunicatorC1EP19ompi_communicator_t

**Comment by philbucher** [comment]
you need to import the mpi-core first, otherwise you get the undefined symbols (guess why I know...)
=> `~/.../kratos/python_scripts python3 --using-mpi`
same for the trilinos-app btw

@jcotela seems like we need a better solution soon

**Comment by RiccardoRossi** [comment]
hi, very soon actually :-D

this breaks running the tests when the MetisApplication is imported.

Also it should be possible to import the metis application without mpi...

**Comment by philbucher** [comment]
> hi, very soon actually :-D

agreed :)

> this breaks running the tests when the MetisApplication is imported.

Well yes, but metis kinda does not make sense without MPI. At least at the moment, since it contains raw MPI-calls

> Also it should be possible to import the metis application without mpi...

There is the deprecated setMPIcomm process still there, thats why it is currently required
@jcotela should we remove it ...?

**Comment by pooyan-dadvand** [comment]
Or we should check for the `IsDistributed` in metis process

**Comment by jcotela** [comment]
On this issue (mostly as a note to myself): this is due to the MPI symbols being missing when loading the MPIDataCommunicator (which has, for example, a constructor taking an MPI Comm). This suggests that the MPI core is loaded, but the OpenMPI libraries are not.
