### ISSUE TITLE
Where to place manufactured solutions?

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#4732]
I have implemented a set of manufactured fluid solutions for a specific study. I am wondering which is the best place for the manufactured solutions, a ManufacturedSolutionsApplication or an existing application?
The manufactured solutions does not solve a physical problem like regular applications. They are a research tool, independent of the specific application, implementation or formulation.
It could be related with #4578

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee sees the possibility to add it to example repository or in the application itself but not in a new application.

The decision depends on if this manufactured solutions are large (to go to examples) or small and used in unittesting (to go to tests subfolder)

**Comment by roigcarlo** [comment]
ping @miguelmaso

**Comment by roigcarlo** [comment]
Closing as the decision was taken.
