### ISSUE TITLE
adding the functionality to Create new modelpart with multiple element types

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#474]
this is needed if different geometries are present within a modelpart

**Comment by loumalouomega** [comment]
Right now it is not possible?

**Comment by RiccardoRossi** [comment]
with limitation

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi would you please explain more where is the problem?

**Comment by RiccardoRossi** [comment]
imagine you have a model part whic contains
Element3D3N and Element3D8N

you would like to assign it to another one, with the same connectivity but populated by, say
TotalLagrangian3D3N and TotalLagrangian3D8N
...

right now it is not possible

**Comment by pooyan-dadvand** [comment]
The solution would be to pass a map: Geometry->Element to the modeler and work with that.

**Comment by loumalouomega** [comment]
Maybe would be a good idea to add to the geometries of nodes an Id, and add these geometries to the modelpart, this way the same geometry could be easily reused. Besides this can reduce the size of the mdpa, because we can create processes to assign conditions and elements to existing geometries

**Comment by loumalouomega** [comment]
This way is easier to make work Kratos with the postprocessors, because the post only know the geometries, the rest is just additional implementation

**Comment by roigcarlo** [comment]
What is the status of this?

**Comment by pooyan-dadvand** [comment]
Technical Committee: With sub modelparts this problem can be addressed
