### ISSUE TITLE
[AVOID MERGING MASTER] Several apps broken after intrusive ptr

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#4748]
Already working on it, but the MeshingApplication for example is broken right now

**Comment by RiccardoRossi** [comment]
what did i break? ... i thought i compiled everything...

**Comment by loumalouomega** [comment]
MeshingApplication and HDF5, that one is already fixed. I am unable to fix Meshing, I don't know why...

**Comment by philbucher** [comment]
I am fixing the MappingApp now

=> #4751
