### ISSUE TITLE
Core is registered multiple times

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4776]
Each time and application is imported it calls the baseclass register: e.g. for the [fluid](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/fluid_dynamics_application.cpp#L123)

This re-registers the KratosCore each time an application is imported since this is [done in the baseclass of the applications](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/kratos_application.h#L87-L90)!

Recommended course of action: removing the call to the base-register for the `Register` functions in the applications

**Comment by jcotela** [comment]
Question: do we need to import the core at least once? Meaning, if some python module somewhere imports only the application, I guess that the core is now being registered anyway... I think it is a bit of a corner case, but it would be a behavior change.

**Comment by philbucher** [comment]
due to how python works I think it is not possible to only import an application unless you somehow "hack" the `KratosMultiphysics` folder

even doing e.g. `import KratosMultiphysics.ParticleMechanicsApplication` will first import the core, I just tried

**Comment by pooyan-dadvand** [comment]
This is a legacy code. I think with the current singleton in core we could safely remove this core registration. @philbucher have you tested it without this?

**Comment by philbucher** [comment]
I will test it more extensively now and report back the results

**Comment by RiccardoRossi** [comment]
still active?

**Comment by philbucher** [comment]
yep
