### ISSUE TITLE
[Core] Make unique type definition for shape functions and derivatives

### ISSUE THREAD

**Issue by tteschemacher** [KratosMultiphysics/Kratos#4777]
Hi all,

I would like to suggest that we go for unique type definitions for shape functions and their derivatives. First of all, passing shape functions in a Matrix where dimension one is integration point and dimension two is the respective node is not very efficient. All elements are anyways extracting through the row operation the respective integration points. This is not very efficient. Further, if we talk about higher order derivatives we needn't do everytime typedefs.

I know that this is not a simple change, but, I definitely think we should go for something like that. It would reduce the overhead and the number of functions significantly. For a moment also backwards compatibility can be provided.

I would suggest following structure, which is the same as the gradients are defined now. It would hold for any type not only derivatives. One could store them in a vector and thus, have a not predefined number of derivatives.

```cpp
    /**
    * Derivative type of any order of derivative. Also for shape functions.
    * The matrix is (derivative direction, corresponding)
    */
    typedef Matrix ShapeFunctionsDerivativesType;

    /**
    * Derivative type of any order of derivative. Also for shape functions.
    * DenseVector: each respective integration point is accessed.
    *  Matrix: (derivative direction, corresponding)
    */
    typedef DenseVector<ShapeFunctionsDerivativesType> ShapeFunctionsDerivativesIntegrationPointsType;

    /**
    * Vector of derivatives until any order of derivative, including for shape functions.
    * In the first DenseVector the order of derivative is adressed.
    * Within the second DenseVector each respective integration point is accessed.
    * The matrix is (derivative direction, corresponding)
    */
    typedef DenseVector<ShapeFunctionsDerivativesIntegrationPointsType> ShapeFunctionsDerivativesVectorType;

    /**
    * This container holds all derivatives including shape functions of
    * each integration point.
    * Array: the integration method is accessed.
    *  @see ShapeFunctionsDerivativesVectorType:
    *  DenseVector: the order of derivative is adressed.
    *   @see ShapeFunctionsDerivativesType:
    *   DenseVector: each respective integration point.
    *    Matrix: (derivative direction, corresponding)
    */
    typedef std::array<ShapeFunctionsDerivativesVectorType, NumberOfIntegrationMethods> ShapeFunctionsDerivativesContainerType;
```

@KratosMultiphysics/implementation-committee @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
I would not define as duplicate as it follow different approaches, in any case I understand it can be chaotic and confusing. I need to think about it

**Comment by pooyan-dadvand** [comment]
I am not sure if having so many dynamic vectors of dynamic vectors is more efficient.... In my opinion it should be slower. And allocating it for each geometry would be even slower. Have you test the performance?

Meanwhile, if you can find a way to do the same with BoundedVectors, then it could be a better solution. Although, it will be very painful to change....

**Comment by pooyan-dadvand** [comment]
In @KratosMultiphysics/technical-committee we have discussed about the possibility of creating a tensor class for this purpose to reduce memory allocation. However the use case would be the important factor to choose one.

Let see the use cases for second derivatives

(@tteschemacher proposal)
```c++
auto const& all_second_derivatives = GetShapeFunctionsSecondDerivatives();
for (i_gauss : gauss_points){
     auto const& gauss_second_derivatives = all_second_derivatives[i_gauss];
     for(i_node : geometry_nodes)
          auto const& derivative_matrix = gauss_second_derivatives[i_node];
          double temp = derivative_matrix(k,l);
} 
```

(using DenseVector<Tensor> which to be implemented)
```c++
auto const& all_second_derivatives = GetShapeFunctionsSecondDerivatives();
for (i_gauss : gauss_points){
     auto const& gauss_second_derivatives = all_second_derivatives[i_gauss];
     for(i_node : geometry_nodes)
          double temp = gauss_second_derivatives(i_node, k,l);
} 
```
Any suggestion from the developers, also @tteschemacher and @oberbichler  who invloved more and @KratosMultiphysics/design-committee

**Comment by oberbichler** [comment]
What do the indices `k` and `l` stand for? Where do you get the corresponding weights?

At the moment I am using something like this:

```c++
std::vector<std::pair<Matrix, double>> gauss_points;

for (const auto& [shape_functions, weight] : gauss_points) {
    // Actually I would create a Kratos-IGA element here and pass `shape_function` and `weight` via `Element::SetValue`

    Vector3d tangent = Vector3d::Zero();

    const size_t derivative_index = 1; // e.g. for 1st derivative

    for (size_t i = 0; i < nodes.size(); nodes++) {
        tangent += node[i].actual_location() * shape_functions(derivative_index, i);
    }

    tangent *= weight;
}
```

In general I don't know how many gauss points/derivatives/nodes I have. That's why I am using dynamic containers. Due to the size of the matrices, this should also be more efficient. For example, a cubic shell would have 16x3 matrices.

I don't think that we need a tensor here.

This is of course only a comment from the IGA perspective.

**Comment by RiccardoRossi** [comment]
hi thomas, what you are doing is really not similar to what kratos does.

take a look at

https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-the-Geometry

for a short description of the kratos geometry interface

**Comment by oberbichler** [comment]
I just mean that this is the way the "one GP per element" method was implemented in Kratos. So that shape functions and weight are stored inside the element and not inside the geometry. This doesn't matter as long as you get to this data in the element somehow. The snipped just shows what we are doing with the data.

**Comment by RiccardoRossi** [comment]
I am not 100% sure this is the correct place, but we had a long discussion (without a final agreement) in @KratosMultiphysics/technical-committee and i would like to write here my understanding proposal.

let's say that we have a "ShapeFunctionData" object which wraps the data (name is just a placeholder)

than i understand that we would do

~~~cpp
    ShapeFunctionData& a = GetShapeFunctionData( gauss_point_index, integration_rule ) //note the &, we are not allocaitng a new object
   double Ni = a.ShapeFunctionLocalValues( local_node_index );
   double DNi,k = a.ShapeFunctionFirstDerivatives( local_node_index, k );  diff(N(i), x_k)
   double D2Ni,kl = a.ShapeFunctionSecondDerivatives( local_node_index, k, l );
   double D2Ni,klm = a.ShapeFunctionThirsDerivatives( local_node_index, k, l );
~~~

or alternatively (and probably better) something like

~~~cpp
     double D = a.ShapeFunctionThirsDerivatives( derivative_order, node_index, k , l .... );
~~~

my point here would be to hide the fact that a is internally a matrix by providing a access function which gives back the double we are interested in.

**the important thing to me is the & in the return. no memory allocation should be done when getting the a for a known integration rule.** This is something that is guaranteed right now.

of course togheter with this we would have a different method

~~~cpp
    ShapeFunctionData a = CalculateShapeFunctionData( local_coordinates, max_derivative_order ) //no & here!!
~~~

does this make sense? 
to me what matters is that if we go this way the user will not be aware of how ShapeFunctionData actually stores the shape functions.

One problematic point is that if we go this way normal geometries will have two different ways of getting shape functions and their derivatives.

- the classical way (which will not work for Brep geometries :-( )
- the new way (which will work for all the geometry types).

at the very end this impacts only the old ShapeFunctionLocalDerivatives usages of which we don't have very many. Maybe we could just remove that...

**Comment by tteschemacher** [comment]
Thanks @RiccardoRossi for your comment!

Let me answer this from back.

>  the classical way (which will not work for Brep geometries :-( )

This is not fully true. It actually works for Brep geometries, too. It would not work for high order element formulations (KL-shell, Beams), because those require higher order functions.

>  the new way (which will work for all the geometry types).

The one implementing the element can decide which function to use. Both should be with the same efficiency. Thus, one could make a change all. However, backwards compability would be still given.

One of the discussion points was that the length of **a** should be within a bounded vector for efficiency. Which can be ensured for standard geometries, for special geometries this is of course flexible and also dependent on the use case and thus, is not defined by compile time.

Further, ShapeFunctionData should be still stored in GeometryData for efficiency and accessed through non-virtual functions in the Geometry base class. This gets us to the point why I want to have a vector for the derivative order, because then a generic amount of derivatives can be handled and accessed.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee we agreed about having the new interface as follow:

````c++
 double D = a.ShapeFunctionDerivatives( derivative_order, node_index, k , l .... );
````
please note that **a is a reference** to internal storage of shape functions and derivatives container.

**Comment by AlejandroCornejo** [comment]
@tteschemacher Do you agree with the assignment of this issue?

**Comment by tteschemacher** [comment]
Sure, I'll make a PR as soon as possible.

**Comment by tteschemacher** [comment]
Yes, I totally agree #5424 is adressing this issue, which is ready to go. There might be more interfaces to add, step by step.

**Comment by tteschemacher** [comment]
With #5424 this issue was adressed and it is now available.

Thus, I am closing this issue. Thanks for your comments!
