### ISSUE TITLE
[Structural] BDF2 scheme not working

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#4782]
Dear @KratosMultiphysics/structural-mechanics guys,

I tried to run a simple structural mechanics example with the BDF2 scheme. It throws an error complaining about the previous delta time. Please find attached the case (as you can see is one of the GUI predefined examples but changing the scheme to BDF2).

[test_BDF2.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/3142367/test_BDF2.gid.zip)

**Comment by loumalouomega** [comment]
Fixed on #4786
