### ISSUE TITLE
Contact Mechanics do not compile in Windows

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#4794]
![image](https://user-images.githubusercontent.com/5918085/57221299-f6881300-6ffe-11e9-9c68-bb27ca05e2e7.png)

Maybe missing some KratoAPI @roigcarlo ?

**Comment by loumalouomega** [comment]
ContactMehanics is @josep-m-carbonell , I am ContactStructuralMechanicsApplication

**Comment by jginternational** [comment]
My bad @loumalouomega

**Comment by roigcarlo** [comment]
Looks lime missing KRATOS_API yes
