### ISSUE TITLE
Refactoring Geometry

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#4819]
Some issues with the `Geometry` have come up in at least two separate topics. I'm posting a possible way to refactor the geometry. In case we decide to do it, it can serve as a starting point for discussion.

![geometry](https://user-images.githubusercontent.com/22290001/57316043-35989000-70f5-11e9-8c73-b546e8ee7efe.png)

If there is no interest, I will close the issue after a while.

@KratosMultiphysics/technical-committee @tteschemacher @philbucher

**Comment by RiccardoRossi** [comment]
what about the difference between triangle2d3 and triangle3d3?

**Comment by tteschemacher** [comment]
Just as comment, I would see NurbsSurface under SurfaceGeometry.

**Comment by rubenzorrilla** [comment]
I lack a `LineGeometry` for trusses and beams.

**Comment by msandre** [comment]
> what about the difference between triangle2d3 and triangle3d3?

They remain different. All geometries (e.g., `Triangle3D3`, `Quadrilateral2D4`, etc.) would stay the same, but derive from the specialized interface (e.g., `SurfaceGeometry`) instead of directly from `Geometry`. This way the `Derived` element (e.g., Shell), can call methods directly on the specialized interface.

> Just as comment, I would see NurbsSurface under SurfaceGeometry.

This can be done. The main question here is do we want to have specialized interfaces which we call directly from the derived elements? Or should we stick with one common interface for all geometries?

> I lack a LineGeometry for trusses and beams.

I left it out to keep the diagram small and only give the basic idea. The names and methods of the specialized interfaces can be refined / expanded, but  I would not put a lot of effort on that until we decide on whether to segregate the interfaces or not.

**Comment by loumalouomega** [comment]
I added this to the @KratosMultiphysics/implementation-committee discussion, but in general I agree with this, but I see many conflicts arising from here

**Comment by AlejandroCornejo** [comment]
We, @KratosMultiphysics/implementation-committee , agree with this design. Please @GuillermoCasas and @adityaghantasala check this.

**Comment by pooyan-dadvand** [comment]
I'm not sure if I understood well the design. I see that this would help to unify some implementation in the middle layer knowing the dimension of the object. But as your element has pointer to the geometry your visible interface would be the geometry one and without down casting you cannot see the surface geometry.

Meanwhile, I like the idea.

**Comment by msandre** [comment]
The idea was mainly to segregate the interfaces and leverage the type system a bit more, substituting runtime checks for compile time checks in the lower levels of the assembly loops. For example, assume we have a shell problem that calls `geom.Normal()` a lot in the assembly. Right now, every time the normal gets calculated, the base class does some inspection of the dynamic object type to try to determine if it is a surface-like object. It's obvious however to a shell element that it's geometry must be surface like. So it could check this once on creation, performing a single cast and holding a pointer to the `SurfaceGeometry`. The downside is now we are storing 2 pointers due to the implemenation in GeometricalObject and it is a bit of a half-solution. A full refactoring would remove the base class implementation (cutting the arrow to mpGeometry) and make GeometricalObject pure interface and possibly removing the virtual `Element::Create(Id, pGeometry)`, but I wouldn't go this way since it is a big effort.

I'm not strongly in favor of this design over another one. But I think we should avoid growing this problem with new geometry methods in the base class.

**Comment by RiccardoRossi** [comment]
I am not sure i follow. Are u proposing that the user must "static_cast" to avoid the virtual table?
if this is so, i really don't love the solution

**Comment by RiccardoRossi** [comment]
aside of this, i don't see a Triangle2D3 as a "surface" element, but rather like a 2D volume element

**Comment by pooyan-dadvand** [comment]
As we are refactoring the goemetry to make it compatible with IGA I am open to any suggestion. However still I am not getting the design you are proposing. Do you want to have meeting next week and talk about it?

**Comment by msandre** [comment]
It should be Triangle3D3. Thanks for catching that. I meant dynamic_pointer_cast to get the pointer to derived. To be clear, I'm not in favor of this solution either, but the alternative would be to change the Element and Condition interfaces and remove the implementation from GeometricalObject. I am in favor of having more layered interfaces for geometries and moving ownership to the elements and conditions, but I was mainly concerned with adding a lot of new methods to the Geometry class. It sounds like @tteschemacher can solve the IGA problem by making the pointer vector to nodes a member. In that case I would prefer his solution. The other issues are not as critical so I would suggest to end this discussion for now. We can reopen it later if we want. Thanks for your comments!!
