### ISSUE TITLE
TODOs intrusive pointer

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4820]
I have compiled a list of things (based on Riccardos comments) to do for the Intrusive Pointers introduced by @RiccardoRossi 

The next things to do are:
1. <s>merge #4592 </s>
2. <s>merge #4729 </s>
3. <s>merge #4779 </s>
4. <s>get rid of weakpointers for good </s>
5. <s>move to a leaner implementation of intrusive pointer WHICH DOES NOT ALLOW USING WEAK POINTERS (this should cause minimal changes in the code) </s>

furthermore the following things should be done:

- [x] make the `VariablesList` use intrusive pointers => #4995 
- [ ] make the `MasterSlaveConstraints` use intrusive pointers
- [ ] make the `Properties` use intrusive pointers
- [x] Check the compilation with CLANG 3.8 (used in the nightly build) => #4757 
- [x] Check if the Intel compilation still works after everything is updated (@philbucher)

**Comment by philbucher** [comment]
@RiccardoRossi could you please update the list, you know better than me the current status

**Comment by philbucher** [comment]
Nightly build compiles again :+1:

**Comment by RiccardoRossi** [comment]
I think the list is correct. i am on point 1 right now

**Comment by philbucher** [comment]
Intel compiles and seems to run fine
Checking it off the list
