### ISSUE TITLE
[Core] GeometryData to non static or virtual access to shape functions

### ISSUE THREAD

**Issue by tteschemacher** [KratosMultiphysics/Kratos#4823]
Hi all,

we would like to introduce geometries which hold shape functions for not defined locations inside the respective geometry. Thus, we cannot use a static GeometryData object. In PR #4724 are some example of such geometry objects.

We figured out three options:
First, making the GeometryData non-static. This would require a copying of all dimension variables for each geometry.

The other option is making all access functions in the geometry virtual. Meaning the ShapeFunctions, ShapeFunctionGradients, ... Then we could store the shape functions on the geometry and override the respective accesses. Making those functions virtual would maybe reduce the performance slightly.

Option three: introducing a static GeometrySize class and keeping shape functions and gradients in some GeometryData. For the possible classes this will be static, if not, only this part can be exchanged.

What would you suggest? 
Thanks!

@KratosMultiphysics/technical-committee @KratosMultiphysics/implementation-committee @philbucher @msandre @pooyan-dadvand

**Comment by loumalouomega** [comment]
I added the discussion to the @KratosMultiphysics/implementation-committee

**Comment by pooyan-dadvand** [comment]
@tteschemacher would you please share the result of the benchmarks here?

**Comment by RiccardoRossi** [comment]
also we could compare to the most optimal function we could call which is:

    static inline void CalculateGeometryData(
        const Element::GeometryType& rGeometry,
        BoundedMatrix<double,4,3>& DN_DX,
        array_1d<double,4>& N,
        double& Area)

**Comment by loumalouomega** [comment]
> also we could compare to the most optimal function we could call which is:
> 
> ```
> static inline void CalculateGeometryData(
>     const Element::GeometryType& rGeometry,
>     BoundedMatrix<double,4,3>& DN_DX,
>     array_1d<double,4>& N,
>     double& Area)
> ```

That depends of the geometry, you need to add a template for dimension and number of nodes to define with bounded arrays and matrices

**Comment by tteschemacher** [comment]
I made a speed test comparision between the old geometry, this type, and this type with being virtual.
Test 1: old: 0.797778s non-virtual: 0.805057 virtual: 2.26137s
Test 2: old: 3.12909s non-virtual: 3.18692 virtual: 5.27198s


For completeness this is the example that I used:


            NodeType::Pointer p_node_1 = Kratos::make_intrusive<Node<3>>(1, 0.0, 0.0, 0.0);
            NodeType::Pointer p_node_2 = Kratos::make_intrusive<Node<3>>(2, 1.0, 0.0, 0.0);
            NodeType::Pointer p_node_3 = Kratos::make_intrusive<Node<3>>(3, 1.0, 1.0, 0.0);

            std::vector<NodeType::Pointer> triangle_nodes(3);
            triangle_nodes[0] = p_node_1;
            triangle_nodes[1] = p_node_2;
            triangle_nodes[2] = p_node_3;
            Triangle2D3 <NodeType> triangle(PointerVector<NodeType>{triangle_nodes});

            const std::size_t num_evaluations = 1e8;

            BuiltinTimer timer;

            array_1d<double, 3> N_all;
            for (IndexType i = 0; i<num_evaluations; ++i) {

                // Computing the info
                BoundedMatrix<double, 3, 2> DN_DX;
                array_1d<double, 3> N;
                double area;

                GeometryUtils::CalculateGeometryData(triangle, DN_DX, N, area);

                N_all += N;
            }

            std::cout << std::endl << num_evaluations << " evaluations took " << timer.ElapsedSeconds() << std::endl;

            NodeType::Pointer p_node_5 = Kratos::make_intrusive<Node<3>>(1, 0.0, 0.0, 0.0);
            NodeType::Pointer p_node_6 = Kratos::make_intrusive<Node<3>>(2, 1.0, 0.0, 0.0);
            NodeType::Pointer p_node_7 = Kratos::make_intrusive<Node<3>>(3, 1.0, 1.0, 0.0);
            NodeType::Pointer p_node_8 = Kratos::make_intrusive<Node<3>>(4, 1.0, 1.0, 1.0);

            std::vector<NodeType::Pointer> tetrahedra_nodes(4);
            tetrahedra_nodes[0] = p_node_5;
            tetrahedra_nodes[1] = p_node_6;
            tetrahedra_nodes[2] = p_node_7;
            tetrahedra_nodes[3] = p_node_8;
            Tetrahedra3D4 <NodeType> tetrahedra(PointerVector<NodeType>{tetrahedra_nodes});

            BuiltinTimer timer2;

            array_1d<double, 4> N_all2;
            for (IndexType i = 0; i < num_evaluations; ++i) {

                // Computing the info
                BoundedMatrix<double, 4, 3> DN_DX;
                array_1d<double, 4> N;
                double volume;

                GeometryUtils::CalculateGeometryData(tetrahedra, DN_DX, N, volume);

                N_all2 += N;
            }

            std::cout << std::endl << num_evaluations << " evaluations took " << timer2.ElapsedSeconds() << std::endl;

**Comment by tteschemacher** [comment]
We runned some tests (@philbucher, @pooyan-dadvand + me). The difference between virtual and non-virtual was quite significant.

Checks in Windows:
non-virtual: 37,9518; 38,154; 38,119
virtual: 55,528; 55,3371; 54,8102; 53.6879

Checks in Linux (different machine):
non-virtual: 45
virtual: 60


    auto node_1(Kratos::make_intrusive<NodeType>(1, 0.0, 0.0, 0.0));
    auto node_2(Kratos::make_intrusive<NodeType>(2, 1.0, 0.0, 0.0));
    auto node_3(Kratos::make_intrusive<NodeType>(3, 0.5, 1.0, 0.0));
    auto node_4(Kratos::make_intrusive<NodeType>(4, 0.5, 0.3, 1.0));

    const Geometry<NodeType>::Pointer p_geom(Kratos::make_shared<Tetrahedra3D4<NodeType>>(node_1, node_2, node_3, node_4));

    const std::size_t num_evaluations = 1e10;

    BuiltinTimer timer;

	Matrix N_sum = p_geom->ShapeFunctionsValues();

    for (IndexType i=0; i<num_evaluations; ++i) {
		N_sum += p_geom->ShapeFunctionsValues();
    }

    std::cout << std::endl << num_evaluations << " evaluations took " << timer.ElapsedSeconds() << std::endl;

**Comment by RiccardoRossi** [comment]
yes, i am siggesting just to use it in the tests, to have a performance
reference

**Comment by pooyan-dadvand** [comment]
Just to clarify, the first test was with virtual operator[] for getting points and the second one was with ShapeFunctionsVAlues being virtual

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee agreed on having the mPoints empty in the generic composite geometry

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee sees the division of GeometricalData in two parts (GeometricalData and ShapeFunctionsData) the best option to avoid performance penalty and memory efficiency.

**Comment by tteschemacher** [comment]
Was there made a decission about the typedefs for high order derivatives? See also #4777

**Comment by tteschemacher** [comment]
I think we found now a way to go here. So, I close this issue.
