### ISSUE TITLE
[FluidDynamics][Adjoint] Help needed to compute drag sensitivities in 2D problem.

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#4832]
Hi! Im writing on behalf of the ExaQUte team! (tagging those who are in Kratos: @riccardotosi @RiccardoRossi @andreas-apostolatos and R. AMELA, Q. AYOUL–GUILMARD, S. GANESH, B. KEITH, A. KODAKKAL, M. RICCHIUTO )

We are working on this problem, with an stochastic inlet (work by B. Keith/A. Kodakkal):

![image](https://user-images.githubusercontent.com/32136457/57437077-54a43880-7241-11e9-8cba-e46a8d437810.png)

![benchmark_zero](https://user-images.githubusercontent.com/32136457/57436339-c4b1bf00-723f-11e9-9b5f-8bb81f8da62d.gif)

However, I'm having some troubles when computing the drag sensitivities. First of all I would like to ask:

- As I can see in the FluidApp, the solver that is implemented for the adjoint analysis is the VMS Monolithic. Is the fractional step solver planned to be added? We first defined this problem for the fractional step solver but I can see there is no adjoint solver yet.

When trying to compute the sensitivities for this problem using the VMS, I got errors since the [drag_response_function.h](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/custom_response_functions/drag_response_function.h)  has no implementation on the conditions, so the sensitivity builder throws an error:

```
terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: Calling base class response function method.


in kratos/response_functions/adjoint_response_function.h:245:virtual void AdjointResponseFunction::CalculatePartialSensitivity(Condition&, const Variable<array_1d<double, 3> >&, const Matrix&, Vector&, const ProcessInfo&)
```

I see that the [cylinder_test](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/tests/AdjointVMSSensitivity2DTest/cylinder_test.mdpa) available has no conditions in its mdpa. 
- Should I delete the conditions when solving the adjoint problem? Maybe Im doing something wrong?

Here are the scripts/parameters used to run the example:

[ProblemZero.zip](https://github.com/KratosMultiphysics/Kratos/files/3161014/ProblemZero.zip)

Thank you!!

**Comment by sunethwarna** [comment]
Hi @marcnunezc ,

For the time being, you can remove list of conditions from the mdpa and run the simulation. We can discuss a permenant solution for this once @msandre is back. 

But in this case, as I understand, you are trying to calculate transient drag sensitivities on a turbulent flow. Transient turbulent flows has this major issue of exploding sensitivities due to butterfly effect, therefore currently there is no implementation to calculate sensitivities over a model part in a transient turbulent flow.

As for the fractional step adjoint solver, at the moment, there are no plans to implement fractional step adjoint solver.

**Comment by marcnunezc** [comment]
Hi @sunethwarna / @msandre ,

Thanks for your answer! Sorry for my late response. I have some questions!

I managed to get the drag sensitivities at each time step by deleting the conditions in the adjoint analysis. Our idea is to either use an average of the sensitivities at each time step or to wait for an steady state of the flow. 
- Would you say that this is feasible with the current analysis in the FluidDynApp? 

Now, for the 4-second analysis shown in the first post, I get the following:
![sensitivities](https://user-images.githubusercontent.com/32136457/58238448-948e1400-7d47-11e9-9dba-b44ba94e396e.gif)


I have tried longer analysis of 16 seconds and 32 seconds, waiting for an steady state of the flow. In all cases the sensitivities decay in norm down to a similar value at the final step. 
- Is that the normal behaviour due to the reverse analysis of the adjoint problem?

- Do you have any suggestions to define an optimization problem for the case shown in the first post? 

Thanks!

**Comment by msandre** [comment]
Hi @marcnunezc, the sensitivities for your problem are the values at time t = 0. In the transient case, they are computed by integrating backwards in time. This is why you see small values at the end of simulation and larger and the beginning. The averaged sensitivity at time t will be the value you see divided by (tend - t). For non-chaotic flows, this average should go to a constant for increasing time intervals.

**Comment by marcnunezc** [comment]
Hi @msandre,

Thanks for your response. If I understand it correctly, the sensitivities of my problem to be used in the optimization loop would be only those at t=0 (which are the sensitivities with the highest norm), is that right?

At first I thought that each time step had its own sensitivities, but I now understand that the sensitivities are built up progressively from t=t_end to t=0, is that correct?

If this is the case, why is the sensitivity not averaged in time by default? Does it make sense to just use the non-averaged and high-norm sensitivity from t=0?


Thanks!

**Comment by msandre** [comment]
Yes, you understand it correctly. In the end, the final magnitude of the sensitivities is not usually of interest. This is simply the definition we went with.

**Comment by marcnunezc** [comment]
Closing this and moving the discussion to #5043
