### ISSUE TITLE
[Core] Bound distance values

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#4857]
Now the level-set computation processes yield maximum values of the order of the maximum machine precision. @pooyan-dadvand and me suggest to change it to the maximum size of the bounding box to bound them.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/fluid-dynamics and @KratosMultiphysics/altair

**Comment by rubenzorrilla** [comment]
Closing this since we already merged it.
