### ISSUE TITLE
Issue in tests of the Structural Mechanics application

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#487]
@msandre, @quirin,

i think this is yours

..terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: attempting to do a GetValue for: NODAL_STIFFNESS variable #644 unfortunately the variable is not in the database and the operations is not threadsafe (this function is being called from within a parallel region)

in kratos/containers/data_value_container.h:196:TDataType &DataValueContainer::GetValue(const Variable<TDataType> &) [TDataType = array_1d<double, 3>]
   kratos/applications/StructuralMechanicsApplication/custom_elements/nodal_concentrated_element.cpp:272:virtual void NodalConcentratedElement::CalculateLocalSystem(MatrixType &, VectorType &, ProcessInfo &)
   kratos/solving_strategies/schemes/residual_based_bossak_displacement_scheme.hpp:635:virtual void ResidualBasedBossakDisplacementScheme<UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::Vector >, UblasSpace<double, boost::numeric::Matrix, boost::numeric::Vector > >::CalculateSystemContributions(Element::Pointer, LocalSystemMatrixType &, LocalSystemVectorType &, Element::EquationIdVectorType &, ProcessInfo &) [TSparseSpace = UblasSpace<double, boost::numeric::ublas::compressed_matrix<...>, boost::numeric::Vector >, TDenseSpace = UblasSpace<double, boost::numeric::Matrix, boost::numeric::Vector >]

**Comment by loumalouomega** [comment]
@RiccardoRossi It is solved in the brach, I did a commit
