### ISSUE TITLE
[Fluid Dynamics] 3D simulation runs slow

### ISSUE THREAD

**Issue by chen112p** [KratosMultiphysics/Kratos#4880]
Hello developers,

I am a novice user of Kratos with a goal of comparing its performance with OF or so (imcompressible external bluff body). Everything works by now. I used GiD to create mdpa and json file and make some modification on json accordingly.

I realized that the simulations ran kind of slow, even though I switched from Fractional Step solver to Monolithic. A similar OF case takes a bit 20 min to run 1s of simulation (with 1 inner iteration), but ~35 min in Kratos to run 1s of simulation, both around 1 million cells. I understand that different types of mesh used in each case (Hexahedral in OF vs Tetrahedral in Kratos) might be the cause. I still hope that you can go over my json file to see if there is some thing you would do to cut simulation run time. 

In addition, would anyone mind to provide some kind of instructions on how to run the "new" mpi DataCommunicator thing as opposed to the legacy mpi?

my .json file:

{
    "problem_data"     : {
        "problem_name"  : "CAARC_building",
        "parallel_type" : "MPI",
        "echo_level"    : 3,
        "start_time"    : 0.0,
        "end_time"      : 500
    },
    "output_processes" : {
        "gid_output" : [{
            "python_module" : "gid_output_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "GiDOutputProcess",
            "help"          : "This process writes postprocessing files for GiD",
            "Parameters"    : {
                "model_part_name"        : "FluidModelPart.fluid_computational_model_part",
                "output_name"            : "CAARC_building",
                "postprocess_parameters" : {
                    "result_file_configuration" : {
                        "gidpost_flags"       : {
                            "GiDPostMode"           : "GiD_PostAscii",
                            "WriteDeformedMeshFlag" : "WriteDeformed",
                            "WriteConditionsFlag"   : "WriteConditions",
                            "MultiFileFlag"         : "SingleFile"
                        },
                        "file_label"          : "time",
                        "output_control_type" : "time",
                        "output_frequency"    : 10,
                        "body_output"         : true,
                        "node_output"         : false,
                        "skin_output"         : false,
                        "plane_output"        : [],
                        "nodal_results"       : ["PARTITION_INDEX","VELOCITY","PRESSURE"],
                        "gauss_point_results" : []
                    },
                    "point_data_configuration"  : []
                }
            }
        }],
        "vtk_output" : [{
            "python_module" : "vtk_output_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "VtkOutputProcess",
            "help"          : "This process writes postprocessing files for Paraview",
            "Parameters"    : {
                "model_part_name"                    : "FluidModelPart.fluid_computational_model_part",
                "output_control_type"                : "step",
                "output_frequency"                   : 167,
                "file_format"                        : "ascii",
                "output_precision"                   : 7,
                "output_sub_model_parts"             : true,
                "folder_name"                        : "vtk_output",
                "save_output_files_in_folder"        : true,
                "nodal_solution_step_data_variables" : ["PARTITION_INDEX","VELOCITY","PRESSURE"],
                "nodal_data_value_variables"         : [],
                "element_data_value_variables"       : [],
                "condition_data_value_variables"     : []
            }
        }]
    },
    "solver_settings"  : {
        "model_part_name"             : "FluidModelPart",
        "domain_size"                 : 3,
        "solver_type"                 : "FractionalStep",
        "model_import_settings"       : {
            "input_type"     : "mdpa",
            "input_filename" : "CAARC_building"
        },
        "echo_level"                  : 0,
        "compute_reactions"           : false,
        "dynamic_tau"                 : 1.0,
        "predictor_corrector"         : false,
        "pressure_tolerance"          : 0.001,
        "maximum_pressure_iterations" : 1,
        "velocity_tolerance"          : 0.001,
        "maximum_velocity_iterations" : 1,
        "volume_model_part_name"      : "Parts_Parts_Auto1",
        "skin_parts"                  : ["AutomaticInlet3D_Automatic_inlet_velocity_Auto2","Outlet3D_Outlet_pressure_Auto1","Slip3D","NoSlip3D_No_Slip_Auto2"],
        "no_skin_parts"               : [],
        "time_stepping"               : {
            "automatic_time_step" : false,
            "time_step"           : 0.006
        }
    },
    "processes"        : {
        "initial_conditions_process_list"  : [],
        "boundary_conditions_process_list" : [{
            "python_module" : "apply_inlet_process",
            "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.AutomaticInlet3D_Automatic_inlet_velocity_Auto2",
                "variable_name"   : "VELOCITY",
                "modulus"         : "5*(log(z+0.1) + 2.3)/(log(10+0.1)+2.3)",
                "direction"       : "automatic_inwards_normal",
                "interval"        : [0.0,"End"]
            }
        },{
            "python_module" : "apply_outlet_process",
            "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
            "Parameters"    : {
                "model_part_name"    : "FluidModelPart.Outlet3D_Outlet_pressure_Auto1",
                "variable_name"      : "PRESSURE",
                "constrained"        : true,
                "value"              : 0.0,
                "hydrostatic_outlet" : false,
                "h_top"              : 0.0
            }
        },{
            "python_module" : "apply_noslip_process",
            "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.NoSlip3D_No_Slip_Auto2"
            }
        },{
            "python_module" : "apply_slip_process",
            "kratos_module" : "KratosMultiphysics.FluidDynamicsApplication",
            "process_name"  : "ApplySlipProcess",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.Slip3D"
            }
        }],
        "gravity"                          : [{
            "python_module" : "assign_vector_by_direction_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "AssignVectorByDirectionProcess",
            "Parameters"    : {
                "model_part_name" : "FluidModelPart.Parts_Parts_Auto1",
                "variable_name"   : "BODY_FORCE",
                "modulus"         : 0.0,
                "constrained"     : false,
                "direction"       : [0,-1.0,0.0]
            }
        }],
        "auxiliar_process_list"            : []
    }
}

Thanks a lot!

JTChen

**Comment by RiccardoRossi** [comment]
dear @chen112p can u try to reduce a little the linear solver precision within the linear solver settings?

to do so you can add the following blocks to the json

"pressure_linear_solver_settings":  {
                "solver_type"                    : "amgcl",
                "max_iteration"                  : 200,
                "tolerance"                      : 1e-6, **---------> change to 1e-3**
                "provide_coordinates"            : false,
                "smoother_type"                  : "ilu0",    **---------> you may try changing this to damped_jacobi (but first try with precision reduction alone)**
                "krylov_type"                    : "cg",
                "gmres_krylov_space_dimension"   : 100,
                "use_block_matrices_if_possible" : false,
                "coarsening_type"                : "aggregation",
                "scaling"                        : true,
                "verbosity"                      : 0
            },

you may also try to use a non-amg solution in the velocity step.

this can be achieved as:

"velocity_linear_solver_settings": {
                "solver_type"                    : "amgcl",
                "preconditioner_type"            : **"relaxation",  (default here would be "amg" but it is not optimal for convective problems"**
                "max_iteration"                  : 200,
                "tolerance"                      : 1e-6,
                "provide_coordinates"            : false,
                "smoother_type"                  : "ilu0", **--> here you may also try "damped_jacobi"**
                "krylov_type"                    : "lgmres",  **--> here you may also try "bicgstabl"**
                "gmres_krylov_space_dimension"   : 100,
                "use_block_matrices_if_possible" : false,
                "coarsening_type"                : "aggregation",
                "scaling"                        : true,
                "verbosity"                      : 0
            },

...let us know if you have some luck

**Comment by jcotela** [comment]
Regarding the DataCommunicator warnings, unless you are using some custom python, you should be able to ignore them. They are intended for developers, since we are in the process of updating this part of the code. I'll do a cleaning pass in the following days and let you know once the changes are in master, sorry for the inconvenience.

**Comment by jcotela** [comment]
Also, you may already be doing this, but I am adding it just for completeness, since it is not specified in the inital post:

If you use all the (physical) processors available on your machine as MPI threads, make sure to disable OpenMP parallelism by setting the environment variable OMP_NUM_THREADS=1 (use maximum one thread for OpenMP). Since Kratos uses OpenMP parallelism by default, if this is not set OpenMP may try to spawn multiple threads for each processor on certain loops within the code, which degrades performance.

**Comment by chen112p** [comment]
Thank you Dr.Rossi. I did some test runs and realized that "solver_type" = "amgcl" will let the simulation significantly slower than "multi_level" (~3 to 4 times of time elapsed, or stuck at second time step). Please forgive me that I have not looked into cpp codes, which means I do not what they mean exactly and do not know what caused this issue. 

I am guessing the options available under "multi_level" solver should look like following (taken from Kratos\applications\FluidDynamicsApplication\trilino_navier_stokes_solver_fractionalstep.py). Although I increased the tolerance, there isn't a significant change in run speed (still ~40-50% slower than OF). The other options you pointed such as smoother_type, preconditioner_type, krylov_type are not available in "multi_level" solver.

"pressure_linear_solver_settings": {
                "solver_type"                        : "multi_level",
                "max_iteration"                      : 200,
                "tolerance"                          : 1e-3,     <----------------------increased from 1e-6
                "symmetric"                          : true,
                "scaling"                            : true,
                "reform_preconditioner_at_each_step" : true,
                "verbosity"                          : 0
            }
"velocity_linear_solver_settings": {
                "solver_type"                        : "multi_level",
                "max_iteration"                      : 200,
                "tolerance"                          : 1e-3, <----------------------increased from 1e-3
                "symmetric"                          : false,
                "scaling"                            : true,
                "reform_preconditioner_at_each_step" : true,
                "verbosity"                          : 0
            }

Would you mind to verify that amgcl solver is running well (if it potentially can out perform multi_level)? How well does your CFD simulation perform? Thank you very much for your quick response!

JTChen

**Comment by chen112p** [comment]
Thanks Dr.Cotela. 

I don't think I disabled OpenMP parallelism before. However, with disabling OpenMP I am still not seeing a significant improvement. Probably it is because I did not take all the processors anyhow. Thanks again for the quick response!

JTChen

**Comment by mpentek** [comment]
@chen112p I see that you are running simulations regarding the CAARC building. As I am also doing thew same, feel free to contact me directly. The question related to turbulence modeling and solver setting (also MPI) are probably still best to be posted here, as @RiccardoRossi and @jcotela are experts on the topics. For some further questions feel free to contact me, also directly on mate.pentek@tum.de.

**Comment by RiccardoRossi** [comment]
@chen112p it is a little strange to me to hear that AMGCL is slower, since from our benchmarks it was actually faster than trilino.

could it be that you also run the test with openmp activated? that would make a really large difference when using amgcl (which uses mixed mpi/openmp paralllism) , but probably no difference when running with trilinos (depending on how trilinos was compiled on your system)

**Comment by jcotela** [comment]
Just to mention that I removed deprecated uses of our mpi interface object in pull request #4913. @chen112p if you update your Kratos installation to the current master the warnings related to legacy mpi and the DataCommunicator should be gone.

**Comment by RiccardoRossi** [comment]
closing as inactive
