### ISSUE TITLE
Nightly Build breaks if only one App doesn't compile

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4881]
As the title says
With large changes like the intrusive ptr often it takes some time until all the apps are updated, esp the rarely used ones.

Would it be possible to disable the apps that are not compiling, such that we at least get the output for the other apps?
I.e. the compiler attempts a regular compilation, but if sth goes wrong in some apps then it disables the not compiling ones and reattempts?

Otherwise we sometimes don't get anything from the nightly build

**Comment by roigcarlo** [comment]
Only thing I can came of with is adding the -K flag, but only works at compiler level, I will look for a similar flag for CMake itself, If I found it we can add it.

**Comment by roigcarlo** [comment]
Seems that there is no way to tell CMake to keep compiling other projects if one has failed unless we make the projects individually. The -k flag is already in the script so that would not improve.

We can try to specify the projects manually. is not a solution I like but if it helps we can go ahead.

**Comment by philbucher** [comment]
thanks for taking a look.

Can we get from CMake which applications failed to compile?

**Comment by philbucher** [comment]
seems to me like we can (from tonights build):
~~~
This is the Kratos Nightly report for GCC
=========================================


Failed Applications : 2
ThermoMechanicalApplication --> KratosThermoMechanicalApplication.dir
CompressiblePotentialFlowApplication --> KratosCompressiblePotentialFlowCore.dir
Compiling Errors    : 7
/home/ubuntu/Kratos/applications/ThermoMechanicalApplication/custom_utilities/particle_levelset_utilities.h:903:23: error: â€˜const class Kratos::GlobalPointer<Kratos::Node<3ul> >â€™ has no member named â€˜lockâ€™
/home/ubuntu/Kratos/applications/ThermoMechanicalApplication/custom_utilities/particle_levelset_utilities.h:904:23: error: â€˜const class Kratos::GlobalPointer<Kratos::Node<3ul> >â€™ has no member named â€˜lockâ€™
/home/ubuntu/Kratos/applications/ThermoMechanicalApplication/custom_utilities/particle_levelset_utilities.h:903:23: error: â€˜const class Kratos::GlobalPointer<Kratos::Node<3ul> >â€™ has no member named â€˜lockâ€™
/home/ubuntu/Kratos/applications/ThermoMechanicalApplication/custom_utilities/particle_levelset_utilities.h:904:23: error: â€˜const class Kratos::GlobalPointer<Kratos::Node<3ul> >â€™ has no member named â€˜lockâ€™
/home/ubuntu/Kratos/applications/CompressiblePotentialFlowApplication/custom_conditions/potential_wall_condition.cpp:69:32: error: â€˜Kratos::PotentialWallCondition<TDim, TNumNodes>::ElementWeakPointerType {aka class Kratos::GlobalPointer<Kratos::Element>}â€™ has no member named â€˜lockâ€™
/home/ubuntu/Kratos/applications/CompressiblePotentialFlowApplication/custom_conditions/potential_wall_condition.cpp:259:32: error: â€˜const ElementWeakPointerType {aka const class Kratos::GlobalPointer<Kratos::Element>}â€™ has no member named â€˜lockâ€™
/home/ubuntu/Kratos/applications/CompressiblePotentialFlowApplication/custom_conditions/potential_wall_condition.cpp:261:22: error: â€˜const ElementWeakPointerType {aka const class Kratos::GlobalPointer<Kratos::Element>}â€™ has no member named â€˜lockâ€™
Compiling Warnings  : 165
~~~

cannot we write a small script that disables the failed ones? I imagine this not to be too difficult, what do you think?

**Comment by philbucher** [comment]
ok I just checked `nightly_build.sh` and there you already extract the failed apps, I think I can take it from here, will report back once I have sth

i.e. I am planning to detect failed apps, if there are some I will manually try to disable then in configure.sh and restart the compilation

sorry for the noise.

Please let me know if you have some concerns abt this idea :)

**Comment by roigcarlo** [comment]
If you manage to do it it would be nice 👍

**Comment by philbucher** [comment]
closing this since the nightly build changed now, the apps that are compiled are the same in the new CI
