### ISSUE TITLE
[Compilation] Current master not compiling on Windows

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#4914]
See title. The following error occures:

       "C:\software_development\kratos\cmake_build\INSTALL.vcxproj" (Standardziel) (1) ->
       "C:\software_development\kratos\cmake_build\ALL_BUILD.vcxproj" (Standardziel) (3) ->
       "C:\software_development\kratos\cmake_build\kratos\KratosCore.vcxproj" (Standardziel) (14) ->
       (ClCompile Ziel) ->
         C:\software_development\kratos\kratos\utilities\os_utilities.cpp(19): fatal error C1083: Cannot open include file: 'unistd.h': No such file or directory [C:\software_development\kratos\cmake_build\kratos\KratosCore.vcxproj]

    16 Warnung(en)
    1 Fehler

It seems due to the changes made in #4911. Despite it is a Windows compilation, it tries to include this file. Some things were already discussed here: #4910. From a quick search, it seems for me a problem related to the #ifdef _WIN32 statement. 

@loumalouomega Did you try the compilation on windows? Or can you reproduce this error?

**Comment by philbucher** [comment]
FYI @roigcarlo

**Comment by loumalouomega** [comment]
How did it compile on AppVeyor?, I checked in my own Windows machine BTW

**Comment by loumalouomega** [comment]
Can you replace the WINDOWS_COMPILATION macro for _WIN32?

**Comment by loumalouomega** [comment]
Fixed on #4917, I restored the macro that worked previously

**Comment by roigcarlo** [comment]
Just to say, you can use that macro but you first have to include "define.h", otherwise it dosn't see the correct value.

**Comment by loumalouomega** [comment]
> Just to say, you can use that macro but you first have to include "define.h", otherwise it dosn't see the correct value.

It was included on the header

**Comment by philbucher** [comment]
but you included the header AFTER using the macro 
~~~c
// System includes
#include <stdio.h>  /* defines FILENAME_MAX */
#ifdef KRATOS_COMPILED_IN_WINDOWS
#include <direct.h>
#define GetCurrentDir _getcwd
#else
#include <unistd.h>
#define GetCurrentDir getcwd
#endif

// External includes

// Project includes
#include "utilities/os_utilities.h"
~~~

**Comment by philbucher** [comment]
thanks @roigcarlo this seems to be the source of error :+1:

**Comment by philbucher** [comment]
Good to know that this is not a compiler error (which I would have expected) but a wrong behavior

**Comment by loumalouomega** [comment]
> but you included the header AFTER using the macro
> 
> ```c
> // System includes
> #include <stdio.h>  /* defines FILENAME_MAX */
> #ifdef KRATOS_COMPILED_IN_WINDOWS
> #include <direct.h>
> #define GetCurrentDir _getcwd
> #else
> #include <unistd.h>
> #define GetCurrentDir getcwd
> #endif
> 
> // External includes
> 
> // Project includes
> #include "utilities/os_utilities.h"
> ```

![imagen](https://user-images.githubusercontent.com/19991680/58020571-c9f8ee80-7b08-11e9-86ec-a0886af61ce7.png)

**Comment by philbucher** [comment]
github totally needs this predefined :D
