### ISSUE TITLE
[ExternalSolversApplication] undefined symbol

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#4915]
When running the tests in the StructuralMechanicsApplication with the latest master branch the following error from the ExternalSolversApplication pops up:

_Traceback (most recent call last):
  File "test_StructuralMechanicsApplication.py", line 54, in <module>
    from test_harmonic_analysis import HarmonicAnalysisTests as THarmonicAnalysisTests
  File "/home/mini/software/Kratos/applications/StructuralMechanicsApplication/tests/test_harmonic_analysis.py", line 5, in <module>
    import KratosMultiphysics.ExternalSolversApplication as ExternalSolversApplication
  File "/home/mini/software/Kratos/KratosMultiphysics/ExternalSolversApplication/__init__.py", line 3, in <module>
    from KratosExternalSolversApplication import *
ImportError: /home/mini/software/Kratos/libs/KratosExternalSolversApplication.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cgemv__

Did anyone see something like this before?

**Comment by roigcarlo** [comment]
@AndreasWinterstein Can you tell me against which version/flavour of blas are you linking?

**Comment by AndreasWinterstein** [comment]
I am linking lapack-3.7.0.

**Comment by roigcarlo** [comment]
Mmmm looks to me like a dependency problem with lapack/libblas, maybe there is some outdated libs, can you try to update both lapack and libblas libs and relink?

**Comment by AndreasWinterstein** [comment]
It is the lapack version. When using the one which comes with Ubuntu 18.04 LTS it works. Should we close this issue then?

**Comment by roigcarlo** [comment]
Yup
