### ISSUE TITLE
Solving indefinitions in AddDofs

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#495]
Node has different type of possibilities to add a dof with AddDof methods and pAddDofs methods. The problem exposed here concerns to a the method pAddDof where an existing dof is supplied.
We read of the mdpa (old version) and a variable DISPLACEMENT_X is fixed to node1, this creates the Dof DISPLACEMENT_X in node1 (and a NONE reaction).
Later on we take node2 where the dof DISPLACEMENT_X has been added with the corresponding REACTION_X, and we try to set this Dof to node1. 
The problem is that the REACTION_X is not added to node1 and it remains as NONE.

Help is wanted to fix that behaviour.

**Comment by loumalouomega** [comment]
@RiccardoRossi solved some days ago this issue of the NONE, I don't
remember if he did a PR cherry picking this correction

**Comment by RiccardoRossi** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/feature-porting-elements/kratos/includes/model_part.h

This is the fixed version.

I did not yet commit it to master. Vicente could u do it for me?

**Comment by loumalouomega** [comment]
I can do it, but I am coming back to Paris and will land at 11.30, so I
will do it around 12.30

**Comment by josep-m-carbonell** [comment]
@loumalouomega  @RiccardoRossi, @pooyan-dadvand  told me about this fix, but it concerns to another method. It is another problem. Maybe both fixes can be joined in one pull request.

**Comment by loumalouomega** [comment]
I did the PR #499

**Comment by RiccardoRossi** [comment]
closing since i think that now the two fixed were merged. please reopen if i got it wrong

**Comment by pooyan-dadvand** [comment]
@josep-m-carbonell is this fix has worked for you?

**Comment by josep-m-carbonell** [comment]
Yes, I think so. Thank you very much.
