### ISSUE TITLE
[Fluid Dynamics] EmbeddedDragProcess

### ISSUE THREAD

**Issue by dagmawibekel** [KratosMultiphysics/Kratos#4961]
Hi everyone, 
i was trying to compute the drag and lift forces on an embedded bluff body in a fluid flow. However, the EmbeddedDragProcess results in a segmentation fault in the first iteration if the time interval of the process starts from 0. I am advancing in time using a BDF2 discretization.
The BodyFittedDragProcess using a BDF2 scheme does work independent of the interval chosen. 

With the help of @jcotela, i circumvented the problem by starting the computation of the drag forces starting from the second time step. 
However, i believe that there should be a more robust solution to this problem. 
Best regards!

@rubenzorrilla @KratosMultiphysics/fluid-dynamics

**Comment by rubenzorrilla** [comment]
We should find a way to check that the buffer is filled prior to the drag computation.

**Comment by dagmawibekel** [comment]
Hi, 
I encountered another bug using the embedded drag process. 
I was trying to compute the embedded drag for a system that has approximately 5 million tetrahedral elements. Unfortunately, i keep getting zeros for the drag forces when i use MPI. I checked the same simulation using OpenMP and there i actually get forces unequal to zero. 
Furthermore, i changed the background mesh to have less elements and for less elements it again worked... 

Best regards!

**Comment by rubenzorrilla** [comment]
Hi @dagmawibekel !

This is really weird... Just for me to be sure I understood it well, for MPI is working for a relatively small mesh but no for the 5M elements mesh?

**Comment by dagmawibekel** [comment]
Thanks for the quick reply. 
You understood correctly. 
I am running a simple benchmark example and was refining my background mesh towards my geometry. For smaller examples it is working both using MPI and OpenMP. However, if the simulation has a certain size, the embedded drag process only gives values different from zero for OpenMP. When using MPI i get zeros in each time step.

**Comment by rubenzorrilla** [comment]
Which kind of mesh refining are you using? AFAIK the mmg library doesn't work in MPI (yet).

**Comment by dagmawibekel** [comment]
I am refining my mesh in GID using refinement boxes since i know where the structure is going to be.

**Comment by rubenzorrilla** [comment]
@dagmawibekel would you mind trying after #5171 is merged?

**Comment by dagmawibekel** [comment]
works like a charm @rubenzorrilla

**Comment by rubenzorrilla** [comment]
> works like a charm @rubenzorrilla

"Works" includes the zeros in some MPI cases?

**Comment by philbucher** [comment]
is this still active?

**Comment by rubenzorrilla** [comment]
I don't think so. @dagmawibekel feel free to reopen it if needed.
