### ISSUE TITLE
[Core][ContactStructuralMechanicsApplication] AD symbolic dependency limited to Sympy 1.2

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#4992]
Today I discovered that one function I use on my AD (Automatic Differentiation), which is define dependencies into symbols, is not longer available since Sympy 1.3:

https://github.com/sympy/sympy/wiki/Release-Notes-for-1.3

> Symbols no longer automatically convert to functions when called, e.g., if f = Symbol('f'), f(t) is now a TypeError. To create a function, use f = Function('f') or f = symbols('f', cls=Function).

The problem is that the Functions cannot be used as Symbols (so is not possible to operate with them).

I asked on the forum, for now looks like some users proposed to create an auxiliary dictionary to relate the Symbols and the Function, I hope a better solution can be found.

To solve that temporally you can install the 1.2 version of Sympy:

~~~sh
pip install sympy==1.2 
~~~

or 

~~~sh
python3 -m pip install sympy==1.2
~~~

Until I have a final solution I will add a disclaimer on my AD files to install this version.

**Comment by loumalouomega** [comment]
Related https://github.com/sympy/sympy/issues/16928

**Comment by philbucher** [comment]
can this be closed?

**Comment by loumalouomega** [comment]
It is not solved, but yes
