### ISSUE TITLE
Size of Kratos Repo

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#4996]
@KratosMultiphysics/all 
Hi,
I am observing for a while already the size of the repository. Right now a clean version of Kratos as downloaded from the repo has ~550MB. So already not too small
The `applications` folder has ~525MB, `kratos` ~20MB

I looked around and I saw that there are many files, often leftovers from earlier times are around that occupy space and it seems to me like they are not used.
Esp the `msh` files from GiD are a good candidate

I would therefore ask everyone to check their applications for such files. It would be great if you would take a few minutes to either remove the old code or if it is still up-to-date, please move such large examples to the [Examples-Repo](https://github.com/KratosMultiphysics/Examples)

Thanks for your help!

**Comment by loumalouomega** [comment]
From my side i already emptied all the test_examples

**Comment by pooyan-dadvand** [comment]
Ping to @KratosMultiphysics/team-maintainers

**Comment by maceligueta** [comment]
The @KratosMultiphysics/dem team has an operational GUI in this repository that takes quite a lot of space. We are migrating it to the new GUI in the GiDInterface repo, but precisely the part that takes more space is the hardest to migrate: a Wizard with pre-meshed models. The decision of removing this GUI and migrating to the new one was taken some time ago, so it's a matter of time that it will disappear. If it becomes urgent please let us know and we will find an alternative repo to store the old GUI.

**Comment by philbucher** [comment]
thanks @maceligueta !
It is not urgent, just wanted to make others aware

**Comment by loumalouomega** [comment]
I did my part

![imagen](https://user-images.githubusercontent.com/19991680/58643773-3ee5d880-8300-11e9-817e-d126ebb687b0.png)

**Comment by loumalouomega** [comment]
I am still a "big" problem:

![imagen](https://user-images.githubusercontent.com/19991680/58655606-c17b9180-831a-11e9-858a-4a63b5b02302.png)

There is a way to reduce significantly the size of my AD files (this will reduce the performance a little bit but will reduce the size, compilation time and linking time of the ContactStructuralMechanicsApplication). Consist in avoid the zero terms, which can be easily spotted (I do this for friction, because the active sets are very large combination and otherwise the files would be 100 MB aprox.). With this, sacrificing a little bit of performance and memory allocation i can reduce 45-50  MB aprox the size of my app. Ping @RiccardoRossi

**Comment by pooyan-dadvand** [comment]
@loumalouomega you are accepting AD in your application? :thinking:  At least I hope they are related to simulation! :laughing:

**Comment by loumalouomega** [comment]
AD (Automatic Differentation) == Symbolic Generation. AD is the name commonly use on the literature

**Comment by philbucher** [comment]
the size of the applications-folder has been reduced by ~150MB!
Thanks for everyones help!

last "big" example I found are the `test_examples` in the `pfem_2_application`. Could someone please move them to the examples-repo? I am not sure who is in charge there (maybe @miguelmaso ?)

**Comment by dcagritan** [comment]
I'll deal with it first thing in the morning.
Regards

**Comment by dbaumgaertner** [comment]
The ShapeOptimizationApp is also a guilty candidate with a rather big test examples folder. I will make sure it gets smaller in the next days.

**Comment by philbucher** [comment]
now the size of `applications` is 305MB, meaning that we removed 220MB! Great job everyone!
