### ISSUE TITLE
StructuralMechanicsApplication going live

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#501]
@KratosMultiphysics/structural-mechanics 

hi all, next wednesday in the morning we will push the commit of  #486 .

Even though we did some considerable effort in trying to minimize problems, it will probably generate some waves. Please let me know if we have any crucial reason to stop the push

**Comment by jcotela** [comment]
Note that, in parallel, we are also planning to update the GiD interface to the StructuralApplication, so expect some instability from that side too...

**Comment by loumalouomega** [comment]
Indeed @jcotela

**Comment by loumalouomega** [comment]
I think we can close this
