### ISSUE TITLE
[Core] - Line Search convergence problems

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#5040]
Hi all!

I am facing some problems running a thermal case where there is a high non-linearity due to the phase change. I was using the line search from the core but it required many iterations as its resullt was very close to stagnation point ( delta_x = 0.0 ) .

For this reason, I tried using the secant option that is included in the SolidMechanicsApplication and it works very fine in this case. Is there any reason why this option was not moved to the core as well , or why the other option was preferred? I could do the change myself but I wanted to ask first as I do not have much experience in this.

@RiccardoRossi @jcotela @KratosMultiphysics/altair @philbucher

**Comment by RiccardoRossi** [comment]
how does that work?

aside, u can also check if #4593 solves yoir issues

**Comment by ddiezrod** [comment]
Thanks @RiccardoRossi I will try it now!

If  I understand correctly the code its actually a bisection method, it minimizes Res(x+alphadx)(alpha*dx) in a iterative way. It starts with two limits s0 (alpha = 0.0) and s1 (alpha = 1.0) and iterates using the mid-value checking the sign.

**Comment by RiccardoRossi** [comment]
this is similiar to the proposed impleme tation of the line search...

**Comment by ddiezrod** [comment]
Solution proposed in #4593 works fine too! Then I guess merging that should be enough, thanks @RiccardoRossi !

**Comment by ddiezrod** [comment]
Closing as #4593 solved the issue, thanks @RiccardoRossi
