### ISSUE TITLE
Shape Optimization Test examples 

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#508]
the hook test example is not running -->apply_scalar on_conditions_process not found

**Comment by loumalouomega** [comment]
That process is now in the core, and the current name is: `assign_scalar_to_conditions_process.py`

**Comment by josep-m-carbonell** [comment]
Hello @armingeiser ,  there is a process that replaces it in the SolidMechanicsApp  called 
assign_scalar_to_conditions_process.py, which has a slightly different behaviour.

**Comment by armingeiser** [comment]
thanks @loumalouomega and @josep-m-carbonell  for the valuable hints, @dbaumgaertner or me will have a look at it in the next days!
