### ISSUE TITLE
generic invertmatrix does not give back the det A

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#509]
static void InvertMatrix(
        const MatrixType& InputMatrix,
        MatrixType& InvertedMatrix,
        TDataType& InputMatrixDet
        )

does not give back the determinant of the matrix in the case of arbitrary sized input.
this can be computed obviuosly as the product of the diagonal factors of L

**Comment by loumalouomega** [comment]
well, that can be easily added. One sec

**Comment by loumalouomega** [comment]
Done
