### ISSUE TITLE
use numpy function

### ISSUE THREAD

**Issue by nsegala** [KratosMultiphysics/Kratos#5097]
Hi Kratos team, I am trying to run a script and I need some functions from numpy, for istance I need the function np.zeros and np.shape. I am trying to create an array of the size of mp.Elements in order to use it as a storage into a loop. Any suggestion?
Thanks!

**Comment by loumalouomega** [comment]
I assume that mp is your modelpart, then:

~~~py
size = len(mp.Elements)
~~~

**Comment by nsegala** [comment]
thanks, and the function np.zeros? yes mp are the elements of the fem, I need to create an array of zeros of that size

**Comment by loumalouomega** [comment]
the function of numpy is from numpy, works in the same way independently of your import of Kratos. For this particular case:

~~~py
size = len(mp.Elements)
a_lot_of_zeros = np.zeros(size)
~~~

**Comment by loumalouomega** [comment]
If you want to use that arrays in order to interact with numpy unfortunately we don't support right now that. We are planning ti use the Eigen library for that, not estimated date

**Comment by RiccardoRossi** [comment]
pybind already supports numpy

**Comment by loumalouomega** [comment]
> pybind already supports numpy

Can we interact our sparse and dense matrices/vectors with pybind?

**Comment by loumalouomega** [comment]
May be supported by pybind too, but if we don't do the implementation will be the same "WIP"

**Comment by nsegala** [comment]
Yes in fact np.zeros didn't work. I really don't need a vector of zeros, I need only to create a vector of that size.. Is there a method? Can I use np.zeros if I import pybind?

**Comment by loumalouomega** [comment]
pybind is the library we use to export C++ to python. In order to do as you please you need me to clarify if you want to interact with Kratos or with numpy with that array

**Comment by nsegala** [comment]
I need to interact with Kratos, I created a script for a topology optimization of some elastic material, so I need to get informations from a Gid project such as mp.Elements and do something to optimize the problem untill convergence using a loop.

**Comment by loumalouomega** [comment]
OK, one second. @RiccardoRossi pybind interaction is done via Eigen: https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html

**Comment by nsegala** [comment]
Then I run the script as "python3 kratos_script.py" and postprocess with Gid

**Comment by loumalouomega** [comment]
~~~py
import KratosMultiphysics
space = KratosMultiphysics.UblasSparseSpace()
size = len(mp.Elements)
b = KratosMultiphysics.Vector(size)
space.SetToZeroVector(b)
~~~

b is your zero vector

**Comment by nsegala** [comment]
Thanks, what is the variable n in b = KratosMultiphysics.Vector(n)?

**Comment by loumalouomega** [comment]
Ups, copy paste error, look again

**Comment by nsegala** [comment]
Thanks, it worked!!!
