### ISSUE TITLE
Potential Flow Embedded Test failing in FullDebug

### ISSUE THREAD

**Issue by inigolcanalejo** [KratosMultiphysics/Kratos#5100]
This is issue is related to https://github.com/KratosMultiphysics/Kratos/issues/4834

@marcnunezc the embedded test fails in fulldebug when running in parallel with the following output:

terminate called after throwing an instance of 'Kratos::Exception'
  what():  Error: Attempting to Fix the variable: PRESSURE variable #124150272 within a parallel region. This is not permitted. Create the Dof first by pAddDof

in kratos/includes/node.h:664:void Node<TDimension, TDofType>::Fix(const TVariableType&) [with TVariableType = Variable<double>; long unsigned int TDimension = 3ul; TDofType = Dof]

This happens in line 451 from the distance_modification_process.cpp when trying to fix the PRESSURE which is not a Dof (as mentioned in https://github.com/KratosMultiphysics/Kratos/issues/4834)

@jcotela has just told me that this will be fixed as soon as https://github.com/KratosMultiphysics/Kratos/pull/5066 is merged but I just wanted you to be aware of this (in case you werent).

Funnily the test only fails when ran with more than one thread, which I don't really understand.

**Comment by marcnunezc** [comment]
Hi!

Yes I was aware, sorry for not warning you! I didnt push a fix since it was only happening in FullDebug and I wanted to solve it via #5066 rather than adding more stuff to the potential_solver. You can solve the issue by adding the PRESSURE and VELOCITY dofs in the potential solver. 

After #5066 this will stop happening and we wont need to add extra variables or dofs.

**Comment by inigolcanalejo** [comment]
Perfect! Just wanted to make sure you were aware :+1: 

Since this will be fixed soon Ill close this issue directly.

**Comment by marcnunezc** [comment]
Sorry for the inconvenience!

**Comment by inigolcanalejo** [comment]
No worries! Actually I should have been already aware of this since you opened https://github.com/KratosMultiphysics/Kratos/issues/4834 a long time ago...

**Comment by marcnunezc** [comment]
Hi iñigo, #5066 is already merged!

**Comment by inigolcanalejo** [comment]
Perfect!
