### ISSUE TITLE
How to getet elements area

### ISSUE THREAD

**Issue by nsegala** [KratosMultiphysics/Kratos#5120]
Hi Kratos team, how can I extract from a Gid project the area for each elements in the mesh? I need to get the area elements in order to compute an integral of an elementary function, thanks!

**Comment by loumalouomega** [comment]
For example :

~~~python
area =0.0
for elem in mp.Elements:
    area += elem.GetGeometry().Area() 
~~~

**Comment by loumalouomega** [comment]
@nsegala this solved your issue?

**Comment by nsegala** [comment]
Yes it worked thanks!
Sorry for the delay
