### ISSUE TITLE
Problems regarding the AMGCL solver

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#5132]
Dear @RiccardoRossi an @ddemidov 
I've been using the AMGCL solver lately for large scale calculation tih my application and, up to a certain moment i get the following error msg:
`RuntimeError: Error: Zero aggregates found.`
I've tried to change the "coarsening_type" and the same error occurs... I have to say that in my calculations I remove the elements during the computation (maybe it is important)  and i work with damage models (the stiffness of some elements are reduced) but with direct solvers there's no problem.
Which could be the solution?
Thank you in advance

**Comment by AlejandroCornejo** [comment]
Besides I have this flag activated:
`            "reform_dofs_at_each_step":              true,`

**Comment by loumalouomega** [comment]
> Besides I have this flag activated:
> ` "reform_dofs_at_each_step": true,`

I was going to ask that ;)

**Comment by AlejandroCornejo** [comment]
> > Besides I have this flag activated:
> > ` "reform_dofs_at_each_step": true,`
> 
> I was going to ask that ;)

I know haha I have to say that the solver works when removing elements but at a certain point it crashes

**Comment by loumalouomega** [comment]
Can you show the full configuration of your AMGCL?, there are different types of iterative solvers, by default it is GMRES, you can try with the different ones (if I remember well FGMRES was more robust but more memory consuming)

**Comment by ddemidov** [comment]
I think "Zero aggregates" may only occur when the matrix is diagonal (more precisely, when there are no strong connections found). Could that be the case?

**Comment by AlejandroCornejo** [comment]
> I think "Zero aggregates" may only occur when the matrix is diagonal (more precisely, when there are no strong connections found). Could that be the case?

I'll check! thank you all :)

**Comment by ddemidov** [comment]
> Can you show the full configuration of your AMGCL?, there are different types of iterative solvers, by default it is GMRES, you can try with the different ones (if I remember well FGMRES was more robust but more memory consuming)

The error happens during construction of AMG hierarchy (the setup of the preconditioner), so it should not depend on the iterative solver used.

**Comment by loumalouomega** [comment]
> > Can you show the full configuration of your AMGCL?, there are different types of iterative solvers, by default it is GMRES, you can try with the different ones (if I remember well FGMRES was more robust but more memory consuming)
> 
> The error happens during construction of AMG hierarchy (the setup of the preconditioner), so it should not depend on the iterative solver used.

You know best, I will become a mere spectator.

**Comment by ddemidov** [comment]
I think there was a way to dump the system matrix to a matrix-market file (something like set verbosity level to 4, @RiccardoRossi would know better). The last saved matrix before the crash should be the problematic one (should be in A.mm file). If you attach it here, I will be able to try it out locally.

**Comment by ddemidov** [comment]
And yes, it still would be interesting to see the full amgcl configuration, as @loumalouomega said.

**Comment by RiccardoRossi** [comment]
you can export the matrix at the different steps and iterations but setting the echo_level.of tje strategy to 4
