### ISSUE TITLE
Effective POINT_LOAD changes with number of sub model parts

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#517]
I have a test case of a single beam element with clamped support and a vertical tip load.

I set the nodal solution step variable POINT_LOAD and add the condition PointLoadCondition2D1N to the mdpa. Now I have two submodel parts: Parts_Beam and Boundary. Both sub model parts include the node with the point load and the point load condition. Now the check_and_prepare_model_process_solid.py creates a computing_model_part by adding conditions from the sub model parts in the processes_sub_model_part_list. This adds the same condition twice and now the point load gets assembled twice and the displacements double. If I only include the condition in one sub model part I get the correct result.

**Comment by loumalouomega** [comment]
Well...this can be solved using some flag like `VISITED` or equivalent and telling the BuilderAndSolver to avoid adding twice. Probably there is an easier way

**Comment by RiccardoRossi** [comment]
I believe that creating two identical conditions with the same geometry should not be allowed, however it is difficult to detect such situation.

 I will take a look at that

**Comment by RiccardoRossi** [comment]
Actually, Mike, can I ask you to prepare a minimal test so to reproduce it?

**Comment by msandre** [comment]
Here is the example. The BCs and load are applied in the MainKratos.py.  
[cantilever_demo.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/1089000/cantilever_demo.tar.gz)

Meanwhile I have gotten a bit further with the problem. The check_and_prepare_model_process_solid.py uses the transfer_entities_between_model_parts_process.h to file the computing model part. The Execute() subroutine uses push_back on the node, element and condition containers but doesn't check for uniqueness. The problem appears to be fixed if I insert mrHostModelPart.Conditions().Unique(); after the push_back is finished. I think this would be the correct way to fix it.

There is another issue related to check_and_prepare_model_process_solid.py that concerns me. In Execute, the processes_parts list is used to transfer conditions. So if I add a condition to the model part but don't include the model part in the processes_parts list, then the solver ignores my condition. Is there a reason why we don't include all elements and conditions in the computing model part?

**Comment by loumalouomega** [comment]
@msandre Using the new solvers in `feature-porting-elements` this problem doesn't appear
[cantilever_demo.tar.gz](https://github.com/KratosMultiphysics/Kratos/files/1089220/cantilever_demo.tar.gz)

I got displacement y equal to 1, which is the analytical solution

**Comment by josep-m-carbonell** [comment]
Hello @msandre 
   The check_and_prepare_model_process_solid.py was designed to be called once at the beginning of the analisys. ,At that moment you control exactly where things are located as the GiD interface write things following the same scheme. All conditions must be located in processes_model_parts, if they are not there they will no be included. Domain submodelparts do not include conditions. If you have the same condition defined twice in two processes_model_parts it will be applied 2 times. You can have several conditions on the same geometrical entity, they can represent different loading states and fields. 
     If you need another behaviour a derived class can be added to solve the organization of all your parts. I agree that some control for the uniqueness is needed. Then conditions from the body domain parts could be added too.  Proposals to make this process more general are welcomed. 

Regards
JM.

**Comment by RiccardoRossi** [comment]
@msandre @loumalouomega 

this is just to confirm that the example appears to run correctly in the "porting" branch. The branch will be merged today, so i hope this will be fixed very soon

**Comment by msandre** [comment]
Thanks guys. @josep-m-carbonell I added pr #520 to control uniqueness. My concern about how conditions, elements and nodes are added is because if a user doesn't read down into the code they wouldn't know this. As a user who doesn't know any better, if I add a condition to the model part and then give this to the solver, I would expect it to be included in the assembly. Also, on a complex problem, I probably won't notice that some of my loads were not applied since the results will look close enough to what I expected. I'm not arguing that this needs to be done, but am just explaining how I see it. The issue is resolved from my point of view so I will close it.
