### ISSUE TITLE
Error when running test case in trilinos_application

### ISSUE THREAD

**Issue by asroy** [KratosMultiphysics/Kratos#518]
Hi everyone, I recently started to learn how to use Kratos, and will use it for my CFD development work. My work would need MPI, so I'm learning how to write MPI-enabled application by reading and running the following test case script:

"Kratos/applications/trilinos_application/test_examples/cantilever3d.gid/cantilever3dstatic.py"

But I got the following error message when running this test case, it seems some member functions have not been implemented for class Kratos::GidIO. Did I do something wrong during the run? Any help is appreciated!

Chao

$ mpiexec -np 2 runkratos cantilever3dstatic.py 
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.0.0-
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.0.0-
Initializing KratosStructuralApplication... 
Initializing KratosStructuralApplication... 
     KRATOS   _____     _ _ _                 
             |_   _| __(_) (_)_ __   ___  ___ #
               | || '__| | | | '_ \ / _ \/ __|
               | || |  | | | | | | | (_) \__ \
               |_||_|  |_|_|_|_| |_|\___/|___/ APPLICATION     
Initializing Kratos MetisApplication... 
Initializing Kratos MetisApplication... 
Importing    KratosStructuralApplication
Importing    KratosTrilinosApplication
Importing    KratosMetisApplication
i am  1  of  2
variables for the dynamic structural solution added correctly
number_of_partitions 2
mNumberOfPartitions : 2
Traceback (most recent call last):
  File "cantilever3dstatic.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:159:virtual size_t IO::ReadElementsConnectivities(IO::ConnectivitiesContainerType&)
   /homes/cliu/github/Kratos/applications/metis_application/custom_processes/metis_partitioning_process.h:332:virtual void MetisPartitioningProcess::Execute()

Importing    KratosStructuralApplication
Importing    KratosTrilinosApplication
Importing    KratosMetisApplication
i am  0  of  2
variables for the dynamic structural solution added correctly
number_of_partitions 2
Traceback (most recent call last):
  File "cantilever3dstatic.py", line 44, in <module>
    partitioner.Execute()
RuntimeError: Error: Calling base class member. Please check the definition of derived class

in kratos/includes/io.h:159:virtual size_t IO::ReadElementsConnectivities(IO::ConnectivitiesContainerType&)
   /homes/cliu/github/Kratos/applications/metis_application/custom_processes/metis_partitioning_process.h:332:virtual void MetisPartitioningProcess::Execute()

KRATOS TERMINATED WITH ERROR
KRATOS TERMINATED WITH ERROR

**Comment by jcotela** [comment]
Hi,
I don't think there is anything wrong with your run, the cantilever test is quite old and most likely it is trying to use a deprecated function. I'll look into it, but probably the best course of action is to replace it with a newer example. There is not much in the repository right now, but the examples in the `tests` folder are more up-to-date.

I'm also working on MPI and CFD so, if you have questions I'll be glad to help.

**Comment by asroy** [comment]
@jcotela Thank you for replying! Is there a test case with an input file (preferably a *.mdpa file) that I can run and learn about how to develop MPI-enabled application inside Kratos?

Thanks,
Chao

**Comment by jcotela** [comment]
@asroy I'm pasting here a minimal CFD example so you can start playing around: [trilinos_example.zip](https://github.com/KratosMultiphysics/Kratos/files/1094188/trilinos_example.zip)
run it from console with `mpirun -np 4 python run_example_trilinos.py` (or substitute the appropriate mpi executable/number of processors for your system)

**Comment by asroy** [comment]
@jcotela Thank you so much! This is exactly what I'm looking for. I'm able to run it using 2 MPI processes, and it generated some files (*.post.bin and *.time). I opened Gid, and clicked "Files->open multiple" and selected "trilinos_example_0.post.bin, trilinos_example_1.post.bin" to open, but Gid complained that one of the partioned mesh has 0 node, and after Gid finish the loading, it only show part of solution domain. I'm attaching the results file here. Despite this post-processing issue, the solver itself seems to be working correctly, I'm going to play with this example for a while. Thanks a lot for your help!

[trilinos_example_and_result.zip](https://github.com/KratosMultiphysics/Kratos/files/1095893/trilinos_example_and_result.zip)


![gid_error_message](https://user-images.githubusercontent.com/22615726/27450363-20110b6e-5751-11e7-96f1-71bdd935a34d.png)
![pressure](https://user-images.githubusercontent.com/22615726/27450380-27f6e268-5751-11e7-8e23-29deb22764c6.png)

**Comment by rubenzorrilla** [comment]
Dear @asroy,

In GiD, you have to click "Files -> Merge" and select both *.bin post-process files. "Files -> Open multiple" is used in case you have a post-process file for each time step.

**Comment by asroy** [comment]
Hi @rubenzorrilla, @jcotela 
I tried merge. But I got the same warning. I also got the warning about *.msh, *.bon *.dat *.res  not found. Maybe it's because I didn't write out enough files Gid needs to perform merge. Anyway, I think the solver itself is running correctly on my machine now, so I have something to start learning how to develop in Kratos. Thank you both for the help!
Chao
