### ISSUE TITLE
failing cpp test

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#519]
Hi @pooyan-dadvand 

i guess this is yours. redirect to the correct person in case i am wrong

Ran 123 of 124 test cases in 0.288897s. 1 failed:
    TestModelPartIOSubModelPartsDivision Failed with message: 
        Error: The nodal solution step container deos not have this variable: VELOCITY

in kratos/sources/model_part_io.cpp:1671:void ModelPartIO::ReadNodalDataBlock(ModelPart &)
   kratos/sources/model_part_io.cpp:1711:void ModelPartIO::ReadNodalDataBlock(ModelPart &)
   kratos/sources/model_part_io.cpp:554:virtual void ModelPartIO::ReadModelPart(ModelPart &)

**Comment by pooyan-dadvand** [comment]
I will fix it soon
