### ISSUE TITLE
Trilinos_vms_monolithic_solver.py is broken

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#5191]
- trilinos_strategy_python
- deprecated_trilinos_linear_solver_factory

were deleted in #4537 but there are still in use in the script. Should we delete this one too or replace it by ? (I am trying to fix the imports so I am revising everything)

@philbucher

**Comment by philbucher** [comment]
take a look at #4929 , I think the scripts you are referring to are being removed there

FYI @KratosMultiphysics/fluid-dynamics

**Comment by roigcarlo** [comment]
Thx! Then i will simply not change them
