### ISSUE TITLE
navier_stokes_base_solver.py cannot be derived in python3

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#52]
Since python 3 only allow new-style classes:

```Python
class NavierStokesBaseSolver:

    def __init__(self, main_model_part, custom_settings):

    # etc...
```

Should become:

```Python
class NavierStokesBaseSolver(object):

    def __init__(self, main_model_part, custom_settings):

    # etc...
```

which is also compatible with python > 2.2

I will fix the one in the `navier_stokes_base_solver.py ` but please be aware of this issue since I don't know the content of the rest of the python files.

**Comment by rubenzorrilla** [comment]
My bad. Thanks @roigcarlo !
