### ISSUE TITLE
Moving functions to base Builder and Solver

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#5222]
Following the discussion and comments in #5219 : 

This Issue is to discuss if it makes more efficient (in general) to move some of the functions (declarations) in the current Block and Elimination builder and solvers to base builder and solver.

As I see it following are some of the functions that both Block and Elimination B&S implement : 
(considering the elimination b&s with constraints)
- ConstructMatrixStructure
- ConstructMatrixStructureWithConstraints 
- There are other methods like SetUpDofSetWithConstraints and SetUpDofSet which do the same in both but are named differently ?? ! 
@loumalouomega  any more functions that come to your attention please add here !

**Comment by loumalouomega** [comment]
It is not a matter of efficiency, if it is not in the base class can be acceded only casting the intermediate class, additionally being available as public (like in the case of not constrained methods), will allow to be used from the strategy (like NR). With the corresponding benefits

**Comment by philbucher** [comment]
Are those functions required in the interface?
To me it seems like they are internal
Calling them from outside could mess things up, i.e. we should be careful

**Comment by loumalouomega** [comment]
> Are those functions required in the interface?
> To me it seems like they are internal
> Calling them from outside could mess things up, i.e. we should be careful

May look internal, but they are not. If you want to compute some more advanced non-linear relationships will be important to consider them

**Comment by RiccardoRossi** [comment]
I also think that those functions are internal. furthermore they behave differently for elimination and block versions so i would say they cannot be brought to the base class

**Comment by loumalouomega** [comment]
The functions behave different, but how do you take into account the modification of the structure of the constraints without rebuilding the whole system?

**Comment by philbucher** [comment]
> The functions behave different, but how do you take into account the modification of the structure of the constraints without rebuilding the whole system?

is this even possible? If the structure of the constraints changes then the matrix-structure changes, which I would say requires a rebuild of the entire system

**Comment by loumalouomega** [comment]
> > The functions behave different, but how do you take into account the modification of the structure of the constraints without rebuilding the whole system?
> 
> is this even possible? If the structure of the constraints changes then the matrix-structure changes, which I would say requires a rebuild of the entire system

Not in the case of the block builder and solver for example, the main structure keeps constant. In the elimination it changes, but in that case there is no other option than rebuild everything

**Comment by philbucher** [comment]
What is the status of this?

**Comment by rubenzorrilla** [comment]
Closing as it seems to be inactive.
