### ISSUE TITLE
[Core] How to enable the printing of the analysis stage timings?

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#5227]
Hi,

When running a simulation, is there an option to check the timings spent at each function of the analysis stage (Initialize, InitializeSolutionStep..)? Is it the echo_level? Or using the Logger?

I sometimes get a ".time" file that only contains the Output info:
```

Start   	Stop     	Elapsed 
Writing Output ......................... 6280.47s     	6281.12s     	0.647138s
```

**Comment by loumalouomega** [comment]
Nope, but it can be implemented. I think that the .time file corresponds only with the reading of the mdpa.

**Comment by rubenzorrilla** [comment]
Have you tried with `echo_level` 3. @loumalouomega is right. The .time file is associated to the reading of the .mdpa.

**Comment by loumalouomega** [comment]
Echo level 3 gives much much information, i think @marcnunezc wants something more benchmark oriented

**Comment by philbucher** [comment]
This was intentionally not added because everyone wants to know different timings
It can be easily added in derived analysis_stages though

**Comment by marcnunezc** [comment]
Yep, echo level 3 seems to be quite intrusive and it generates overhead.



> This was intentionally not added because everyone wants to know different timings
> It can be easily added in derived analysis_stages though

Yes for now I just overrode the RunSolutionLoop function:

```
    def RunSolutionLoop(self):
      while self.KeepAdvancingSolutionLoop():
            self.time = self._GetSolver().AdvanceInTime(self.time)
            ini_time = time.time()
            self.InitializeSolutionStep()
            self.initialize_time += time.time() - ini_time
            self._GetSolver().Predict()
            ini_time = time.time()
            is_converged = self._GetSolver().SolveSolutionStep()
            self.solve_time += time.time() - ini_time
            ini_time = time.time()
            self.FinalizeSolutionStep()
            self.finalize_time += time.time() - ini_time
            ini_time = time.time()
            self.OutputSolutionStep()
            self.output_time += time.time() - ini_time
```

**Comment by philbucher** [comment]
@marcnunezc to me looks fine what you do
However having this in the baseclass would make it much more complicated to read IMO

Another option would be to use a profiler, have you considered that?

**Comment by marcnunezc** [comment]
I did not consider using a profiler but I will check it out.

In any case we are aiming to check this timing in our local machines to check scalability of our problem and then also in the clusters, so for now print()'s are good enough.

**Comment by rubenzorrilla** [comment]
Can we close the issue then?

**Comment by marcnunezc** [comment]
Yes, we can close it
