### ISSUE TITLE
GetValuesOnIntegrationPoints mapped to CalculateOnIntegrationPoints

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#523]
GetValuesOnIntegrationPoints in python is mapped directly to CalculateOnIntegrationPoints in C++.
Also note that the function in C++ is called GetValueOnIntegrationPoints (without the 's' in Values), not sure if it is on purpose.

In add_mesh_to_python.cpp:

template< class TObject >
boost::python::list **GetValuesOnIntegrationPointsXXXX**( TObject& dummy,
        const Variable<double>& rVariable, const ProcessInfo& rCurrentProcessInfo )
{
    boost::python::list values_list;
    IntegrationPointsArrayType integration_points = dummy.GetGeometry().IntegrationPoints(
                dummy.GetIntegrationMethod() );
    std::vector<double> values( integration_points.size() );
    dummy.**CalculateOnIntegrationPoints**( rVariable, values, rCurrentProcessInfo );
    for( unsigned int i=0; i<values.size(); i++ )
    {
        boost::python::list integration_point_value;
        integration_point_value.append( values[i] );
        values_list.append( integration_point_value );
    }
    return( values_list );
}

**Comment by jcotela** [comment]
I've also had some issues with this in the past (and I know others too). I would be inclined to change it.

**Comment by pooyan-dadvand** [comment]
I would also like to change it to be more coherent. Nevertheless I cannot estimate the (silent) side effect it may cause to the developers. @KratosMultiphysics/technical-committee any comment?

**Comment by marandra** [comment]
What is the use for GetValueOnIntegrationPoints (in C++)? It appears to have redundant functionality with CalulateOnIntegrationPoints.

**Comment by pooyan-dadvand** [comment]
The historical idea was to turn back what you already stored, but time shows that it is not useful at all.....

**Comment by loumalouomega** [comment]
Indeed, basically it does the same

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee - we believe that the GetValueOnIntegrationPoints should be removed. Only the CalculateOnIntegrationPoints should remove.

the old function will be deprecated

**Comment by jcotela** [comment]
To be discussed again in the next meeting of @KratosMultiphysics/technical-committee. I've looked a bit into the code and the summary of the situation is as follows:

From C++:
```
element.h (and condition.h)
GetValueOnIntegrationPoints (grep finds it 1065 times in master)
SetValueOnIntegrationPoints (339)
CalculateOnIntegrationPoints (662)
```

From Python:
```
defined in add_mesh_to_python.cpp (Notice trailing 's' in Values)
GetValuesOnIntegrationPoints (34) This function actually calls CalculateOnIntegrationPoints!
SetValuesOnIntegrationPoints (20)
CalculateOnIntegrationPoints (6)
```

Finally, note that the GiD I/O function `PrintOnGaussPoints` (used 450 times in master) contains a call to `GetValueOnIntegrationPoints`.

Suggestions:
- Names with Value**s** seem more appropriate: all functions return a list of values (one for each integration points).
- Having Get/Set pairs sound more intutive than Set/Calculate pairs.
- @pooyan-dadvand asks if there really is an use for the `SetValueOnIntegrationPoints` method: it seems to be used to define the constitutive law in some utilities, and some applications (MultiScale at least) use it to define elemental variables.
