### ISSUE TITLE
Consider only conditions and elements in the ComputeTags

### ISSUE THREAD

**Issue by NicolaGermano** [KratosMultiphysics/Kratos#5237]
Hi all,
in the [ComputeTags](https://github.com/KratosMultiphysics/Kratos/blob/57a8b3a99576681958a68f91e18042fa7b1b6189/kratos/utilities/assign_unique_model_part_collection_tag_utility.cpp#L40) I would like to know if it is possible consider only the conditions and the elements (and not the nodes that will have only the tag of the main model part).
In my application I use the MMG process and I have one sub model part for each type of condition/element as specified in the MeshingApplication.
I need these conditions/elements to still be separated after the MMG process.
I have this result if I don't consider the nodes in the ComputeTags.

Is it possible to do this?

Thanks

**Comment by loumalouomega** [comment]
Due to the inner way the submodelpartsare recovered, the nodes are automatically added to the submodelparts. Why is this an issue?, why it is a problem a submodelpart with nodes and elements?. It can be easily deactivated, but I need to understand why

**Comment by NicolaGermano** [comment]
My model part consists of 4 sub model part (1 with only the Elements, 3 with different Conditions).
When I consider the Nodes, combinations are created between the sub model parts and some Conditions are added to the sub model part with only the Elements (after the MMG process).
This happens when I use discretization_type=ISOSURFACE in the MMG process because new conditions are created.

**Comment by miguelmaso** [comment]
Hi Nicola, I'm not sure to be uderstanding it. This issue seems to be how entities are added to sub_model_parts by MMG, rather than computing the tags. Is it right?

**Comment by loumalouomega** [comment]
Certantly @NicolaGermano I need a minimal example. We need to see if the problem is in our side or in the MMG side, so if in the MMG side we will report them, otherwise we will fix it. BUt without a minimal example is not possible to replicate. 

I only need ->Mesh (MDPA), the metric and MMGProcess parameters

**Comment by NicolaGermano** [comment]
Hi, here there are the files ([test_box.zip](https://github.com/KratosMultiphysics/Kratos/files/3398059/test_box.zip)).

Thanks

**Comment by loumalouomega** [comment]
On the way

**Comment by loumalouomega** [comment]
One small thing @NicolaGermano, I needed to register the following variables:

~~~py
main_model_part.AddNodalSolutionStepVariable(KratosMultiphysics.IS_FLUID)
main_model_part.AddNodalSolutionStepVariable(KratosMultiphysics.IS_STRUCTURE)
main_model_part.AddNodalSolutionStepVariable(KratosMultiphysics.IS_FREE_SURFACE)
main_model_part.AddNodalSolutionStepVariable(KratosMultiphysics.IS_BOUNDARY)
main_model_part.AddNodalSolutionStepVariable(KratosMultiphysics.FLAG_VARIABLE)
~~~

It would be much cheaper to use flags, you will save 5 x 1 byte x Buffer size x Number of nodes -> Buffer size 2 and 100K nodes = 1 MB of memory (well is not that much, but also it will be faster)

**Comment by loumalouomega** [comment]
I think it is a problem on the structure of the model parts:

~~~sh
mrThisModelPart : -MainModelPart- model part
    Buffer Size : 1
    Number of tables : 0
    Number of sub model parts : 4
    Current solution step index : 0
    DOMAIN_SIZE : 3
    TIME : 0
    DELTA_TIME : 1

    Mesh 0 :
        Number of Nodes       : 57485
        Number of Properties  : 2
        Number of Elements    : 327288
        Number of Conditions  : 0
        Number of Constraints : 0

    -ElementSubModelPart- model part
        Number of tables : 0
        Number of sub model parts : 0

        Mesh 0 :
            Number of Nodes       : 57485
            Number of Properties  : 0
            Number of Elements    : 327288
            Number of Conditions  : 0
            Number of Constraints : 0
    -bottom- model part
        Number of tables : 0
        Number of sub model parts : 0

        Mesh 0 :
            Number of Nodes       : 4365
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 8576
            Number of Constraints : 0
    -lateral- model part
        Number of tables : 0
        Number of sub model parts : 0

        Mesh 0 :
            Number of Nodes       : 1358
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 2505
            Number of Constraints : 0
    -top- model part
        Number of tables : 0
        Number of sub model parts : 0

        Mesh 0 :
            Number of Nodes       : 296
            Number of Properties  : 0
            Number of Elements    : 0
            Number of Conditions  : 531
            Number of Constraints : 0
~~~

The main has no conditions, this is wrong. The main should have all the element/conditions/nodes

**Comment by loumalouomega** [comment]
OK, I see the problem, this is due to the mRemoveRegions implemented by @swenczowski, I will modify it to make more consistent, but as I don't know exactly what is this supposed to do my contribution will be kind of blind

**Comment by loumalouomega** [comment]
Solution on #5259
