### ISSUE TITLE
Repository for legacy applications

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#5269]
@KratosMultiphysics/all 

@KratosMultiphysics/technical-committee decided to move the legacy applications to a separate repository in KratosMultiphysics project. The conditions to be a legacy is fulfilling one of these conditions:
1. Not compiling for more than 3 months (not imported to pybind, intrusive pointers, etc.)
2. Not running for more than 6 months with current python requirement of core
3. No active maintenance from any known maintainer of the application for more than 1 year.

The procedure would be to announce the legacy status to the project in an issue and after 1 month without changing the situation moving it to the legacy repo.

It is important to mention that developers can update any legacy application in future and request to the technical committee to bring it back to the normal Kratos repository.

**Comment by pooyan-dadvand** [comment]
At this point the list of legacy applications are:
* LagrangianMPMApplication @iiaconeta 
* MixedElementApplication @RiccardoRossi 
* MultiScaleApplication @MassimoPetracca 
* ThermoMechanicalApplication @jrubiogonzalez 
* TopologyOptimizationApplicationn @dbaumgaertner 
* UmatApplication @josep-m-carbonell @lluis-mv 
* constitutive_laws_application @vryy 
* meshless_application @RiccardoRossi 
* mpi_search_application @roigcarlo 


And we are not sure about:
* NvidiaFlexApplication @maceligueta  
* radiation_application @juliobarna

**Comment by loumalouomega** [comment]
Should we move the legacy structural there? (rescuing from any old release)

**Comment by lluis-mv** [comment]
Hey,
The Umat Application (in purpose) is a very small application that works as interface between umat models and Kratos Constitutive models. I am currently working on it, but the developments are in a  branch.

I think that the current version on the master compiles correctly in linux and works fine. I will check next week when I have more time.

**Comment by pooyan-dadvand** [comment]
Thanks @lluis-mv, Please update us with the status of the UmatApplication.

**Comment by pooyan-dadvand** [comment]
> Should we move the legacy structural there? (rescuing from any old release)

What would be the advantage of doing this? We have already cleaned it.

**Comment by loumalouomega** [comment]
Some implementation are still pending to move, but we can still check the old branches.

**Comment by RiccardoRossi** [comment]
i personally don't dislike the idea of having the structural there as legacy. it would be easier to eventually dig for useful code

**Comment by pooyan-dadvand** [comment]
I see, meanwhile I don't have strong objection on it. What I don't like is if someone start developing there...

**Comment by lluis-mv** [comment]
@pooyan-dadvand , the UmatApplication compiles and runs correctly.
I have updated the import mechanism of python and added one test. See #5294

**Comment by pooyan-dadvand** [comment]
Thanks @lluis-mv! We will consider it.

**Comment by dbaumgaertner** [comment]
Just to say that the TopologyOptimizationApplication is indeed a legacy and may be safely moved to the legacy repo - hoping that one day it will be revived with the necessary effort.

**Comment by maceligueta** [comment]
About the NvidiaFlexApplication, it can be considered legacy. When it is necessary to have it back in the general repository we will request that.
