### ISSUE TITLE
Serial debugging Kratos under Windows

### ISSUE THREAD

**Issue by peterjwilson** [KratosMultiphysics/Kratos#5275]
Hi All,

Has anyone managed to debug Kratos under Windows using Visual Studio, but force it to run in serial (not parallel)?

@roigcarlo Carlos, sorry to tag you, but your excellent windows debugging how-to suggests this may be an easy answer for you :)

Any help would be appreciated!

**Comment by roigcarlo** [comment]
HI @peterjwilson ,

It should be as easy as defining `OMP_NUM_THREADS=1` In the envirnment field of the debug options:
![image](https://user-images.githubusercontent.com/1935791/61516765-f2687080-aa05-11e9-8900-7857f05145f7.png)

Please tell me if it works for you

**Comment by roigcarlo** [comment]
Hi @peterjwilson were you able to set the number of threads?
