### ISSUE TITLE
DEM specifying path to problem

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#5301]
@KratosMultiphysics/dem I wrote a test for fem-dem coupling in the latest CoSimulationApp.

I do not succeed properly positioning the test files for the DEM files.
I am on this branch: https://github.com/KratosMultiphysics/Kratos/tree/cosim/fem-dem

the folder structure is `CoSimulation/tests/dem_fem_cable_net`, normally all files should be in this folder and an external script in `CoSimulation/tests` calls the tests.

Now if I write (in `ProjectParametersDEM.json`)
`"problem_name" : "cableNet"`
it cannot find the DEM files as it searches in  `CoSimulation/tests`.

If I write
 `"problem_name" : "dem_fem_cable_net/cableNet"`

it crashes telling me it cannot find 
`dem_fem_cable_net/../dem_fem_cable_net/cableNet.post.lst`

All works fine with the Structural FEM files.

Is there a way to additionally define a path? I checked the DEMApp and saw that you call the tests within the respective folders, which I cannot do in the CoSimApp.

The current branch works but I would like to put all DEM files in the 
'/dem_fem_cable_net` folder.

**Comment by philbucher** [comment]
Basically it boils down to the question how a working directory can be specified for the dem-files

**Comment by maceligueta** [comment]
Hi @KlausBSautter and @philbucher .
What we have done so far is to derive the `DEM_analysis_stage`.py and overwrite the method
```
def GetMainPath(self):
        return os.getcwd()
```
You can return whatever path you want once the method is customized.
Does it help?

**Comment by philbucher** [comment]
thanks @maceligueta for the fast response, we will try tmr

**Comment by KlausBSautter** [comment]
thanks @maceligueta it works now.
