### ISSUE TITLE
[FluidDynamics] Different solution for "vms" and "qsvms" elements

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/Kratos#5356]
Hi,

I have launched one case consisting in a cube using monolithic eulerian fluid (navier_stokes_solver_vmsmonolithic.py) with a velocity inlet of 0.01 m/s and an outlet of zero pressure in the opposite face of the cube. I've set the dynamic tau value to 0.01. I am using the same .mdpa and .json files (for the qsvms, I've defined the Constitutive Law as well). I am using the bicgstab iterative solver. The thing is that I am getting different solutions for both cases, so I was wondering whether I was missing any parameter for the qsvms element that it is not needed for vms. Could you help me to figure out what it's wrong?
I attach you the solution for both cases at the same time step, the upper image is the solution given for qsvms element and the last figure is the solution using the vms one.

By the way, I am working in a brack updated from the master two weeks ago.

![QSVMS Solution](https://user-images.githubusercontent.com/39963156/62457645-8c0c7d80-b77b-11e9-8792-572635883c2f.jpeg)
![VMS Solution](https://user-images.githubusercontent.com/39963156/62457654-8fa00480-b77b-11e9-889d-f1506d0d9d2f.jpeg)

**Comment by rubenzorrilla** [comment]
Both elements implement the same formulation: a Navier-Stokes element with quasi-static ASGS stabilization. However there exist minor differences between them. By heart I can say that the `vms` subintegrates the pressure equation (@jcotela correct me if I'm wrong) and that they use different formulas for the elemental size (h) calculation. This could lead to different results, specially for coarse meshes as the one you are presenting in the images.

By the way, are you solving the 3D cavity flow?

**Comment by jgonzalezusua** [comment]
Ok thanks for the answer. I am not solving 3D cavity.

I will close it.
