### ISSUE TITLE
TestQuadrilateralJacobianTest fails randomly 

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#538]
In my linux machine the TestQuadrilateralJacobianTest fails randomly with following message:
 
```
        Error: Check failed becuase detJ = inf is not near to MathUtils<double>::GeneralizedDet(jacobian) = 0.0422963 within the tolerance 1e-06
in kratos/tests/geometries/test_non_rectangular_jacobian.cpp:108:virtual void Testing::TestQuadrilateralJacobianTest::TestFunction()

```

**Comment by loumalouomega** [comment]
@pooyan-dadvand Randonly means sometimes or always?

**Comment by loumalouomega** [comment]
In this test the points are generated randonly with:GeneratePoint

**Comment by loumalouomega** [comment]
So it is possible that it creates some impossible configurations, particularly because the quadrilateral can be reversed depending of the nodes order. We can just define manually the nodes

**Comment by RiccardoRossi** [comment]
yes, i think that defining manually the points is a wise choice
