### ISSUE TITLE
KRATOS_THROW_ERROR(std::runtime_error, "message") does not show the message on Windows

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/Kratos#5397]
Hi,

KRATOS_THROW_ERROR(std::runtime_error, "message") works properly on Linux but on Windows it stops the calculation without giving any message. 

How can I solve this issue?

**Comment by loumalouomega** [comment]
Has you tried KRATOS_ERROR instead?, it works as a std::cout

**Comment by Vahid-Galavi** [comment]
I can use KRATOS_ERROR in my application but I still miss error messages from Kratos core. For example, it stops while reading input files without giving any error message. I do not have this problem on Linux.

**Comment by loumalouomega** [comment]
How many threads are you using?

Try to use 1

**Comment by Vahid-Galavi** [comment]
I am using 1 thread

**Comment by RiccardoRossi** [comment]
i guess this depends on openmp 😅.  the point is that openmp
is.not.guaranteed to fail graciously implyimg that ot.cam.segfault out of
the exception system.

to test if that is the case try to run with one thread.

unfortunately i have no fix...

**Comment by Vahid-Galavi** [comment]
I am using only one thread.

**Comment by Vahid-Galavi** [comment]
There is already an issue related to this problem:
Duplicate of #4150

**Comment by Vahid-Galavi** [comment]
So, I close this issue.

**Comment by philbucher** [comment]
should be working with #9335
