### ISSUE TITLE
Standard way of importing python-modules

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#5402]
With the "old" way of importing applications being [deprecated](#5255), we now should find a common solution for importing the python scripts
Previously we had to do:
~~~py
import KratosMultiphysics.FluidDynamicsApplication
import vms_solver
~~~
now we have several options:
~~~py
import KratosMultiphysics.FluidDynamicsApplication.vms_solver as vms_solver
from KratosMultiphysics.FluidDynamicsApplication import vms_solver
~~~
#
**However, what is also possible** and where we had several discussions (e.g. [here](https://github.com/KratosMultiphysics/Kratos/pull/5262) and [here](https://github.com/KratosMultiphysics/Kratos/pull/5284)) are **explicit relative imports**:
~~~py
# in vms_sovler.py:
from KratosMultiphysics.FluidDynamicsApplication import fluid_solver # absolute import
# OR:
from . import fluid_solver # explicit relative import
~~~
#
from [PEP8](https://www.python.org/dev/peps/pep-0008/#imports):
"Absolute imports are recommended, as they are usually more readable and tend to be better behaved ..."

"However, explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose"
#
**I tried both ways already and suggest (up for discussion the following):**
- By default I would go for absolute imports, just as PEP8 suggests.
- Since however Kratos has a relatively large/complex file structure I would also **allow** explicit relative imports, if the developer decides to use it, since it does shorten the paths quite a bit (e.g. [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/HDF5Application/python_scripts/core/controllers.py#L9)) 
=> especially when there is a subfolder-structure inside `python_scripts` (which is now possible and already in use, see [CoSimApp](https://github.com/KratosMultiphysics/Kratos/tree/master/applications/CoSimulationApplication/python_scripts) and [HDF5App](https://github.com/KratosMultiphysics/Kratos/tree/master/applications/HDF5Application/python_scripts)) since it can make the paths much shorter
- What I would **not allow** is to use explicit relative imports across directories (e.g. importing from parent directory etc), bcs this becomes really unreadable then [example](https://github.com/KratosMultiphysics/Kratos/pull/5284/commits/a41ec271570ba515613ac26855c2027ae3dbbbe7)

FYI @armingeiser @adityaghantasala

**Comment by armingeiser** [comment]
Thanks for starting this discussion. 

I also think that explicit relative imports are easy to read for imports from within an application (package). 
Personally i am not against navigating back if an import from a parent directory of the **same** package is made. 

However we will implement in #5262 what will be decided here to be Kratos style conform.

**Comment by RiccardoRossi** [comment]
@armingeiser @philbucher i do not want to enter in stylistic questions,
nevertheless what i think is really important to achieve is that our importing mechanism becomes more pythonic, in the sense that it follows the standard python rules.
Right now this is not the case due to the manual edit of the python path we do under the hood.
This will be corrected soon and is the thing we must all beware

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee promotes the absolute import rather than the relative one due to its clarity and considering that we don't have many imports in each file, so the verbosity wouldn't be a problem.

**Comment by philbucher** [comment]
closing since I added it to the style guide: https://github.com/KratosMultiphysics/Kratos/wiki/Style-Guide#imports
