### ISSUE TITLE
Kratos has to be recompiled for ExternalSolversApp

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#5446]
See title
When turning on/off the ExternalSolversApp, then Kratos has to be recompiled

Do you know if there is a good reason for this?

@jcotela @RiccardoRossi @roigcarlo

**Comment by roigcarlo** [comment]
I can recall a couple of reasons.
First is to deal with the name mangling with blas and lapack, which are only included in the external application. When it is eneabled there is a new `-D`  that is passed as argument:

Here for details
https://github.com/KratosMultiphysics/Kratos/blob/master/CMakeLists.txt#L256

Maybe we could just define `-DADD_` by default and just modify it if the condition does not hold so it would not the to be recompiled every time. It should not husrt the rest of the code.

Also I recall someone telling me that there were parts of code in the core warded with some defines that are enabled when compiled with the external app, but I am not sure where this code is, if it even exists.
