### ISSUE TITLE
Using the distance function

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#5505]
Could anyone please provide an example of using the distance function in 2D and 3D?
I have a surface (or polyline in 2D) composed by conditions and would like to find the distance to this embedded skin at the nodes of the background mesh.

Thanks a lot!

**Comment by adityaghantasala** [comment]
You can have look here 
https://github.com/KratosMultiphysics/Kratos/blob/ChimeraApplication-development_2.0/applications/ChimeraApplication/custom_utilities/distance_calcuation_utility.h

**Comment by playpaolo** [comment]
Thank you @adityaghantasala , but as far as I see, this is the function inside ChimeraApplication. I wanted to use the things of the core. Is it possible?

**Comment by adityaghantasala** [comment]
Yes it is .. but this is just calling the utilities and functions from core ..

**Comment by rubenzorrilla** [comment]
Hi @playpaolo ! You can have a look to the `test_calculate_distance_to_skin.py` in the core tests. Should be as simple as `KratosMultiphysics.CalculateDistanceToSkinProcess2D(model_part, skin_model_part).Execute()`.

**Comment by playpaolo** [comment]
Thank you  @adityaghantasala and @rubenzorrilla ! I will try it.

**Comment by rubenzorrilla** [comment]
Closing since it seems to be solved. @playpaolo to reopen it again if you have any further issue with the level set calculation.
