### ISSUE TITLE
ReplaceElementsAndConditions In MPI

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#5509]
So, @pablobecker and I noticed that the process fails while in MPI as it does not care about the elements/conditions in LocalMesh(), or any mpi interface of the modelpart.

Probably would be a good idea to replace the the entitites if the process detects that `isDistributed() == true`

For discussing @KratosMultiphysics/technical-committee & @jcotela

**Comment by RiccardoRossi** [comment]
shouldn t we dkrectly call the ParallelFillComminicator in that case?

**Comment by roigcarlo** [comment]
We will use the parallel fill for now
