### ISSUE TITLE
Debug Kratos under Windows

### ISSUE THREAD

**Issue by longchentum** [KratosMultiphysics/Kratos#551]
Hello Kratos developers,

I am trying debug Kratos (the actual master code) under Windows using Visual Code. I got 2 errors:

1.  when import StructuralMechanicsApplication using
`from KratosMultiphysics.StructuralMechanicsApplication import *`
Kratos crashes and the error message shown in console is 
![debug_kratos_windows](https://user-images.githubusercontent.com/25929689/27586813-1d5558c2-5b42-11e7-90f3-1aa445ae7f89.png)

while importing KratosMultiphysics, SolidMechanicsApplication and ExternalSolverApplication do work.

2. when I commented the line:
`#from KratosMultiphysics.StructuralMechanicsApplication import *`
Kratos stopped at the line
`ProjectParameters = Parameters(parameter_file.read())`

I got Error message on my debug console:

_Tue Jun 27 14:16:18 2017
Importing    KratosSolidMechanicsApplication
Importing    KratosExternalSolversApplication
Traceback (most recent call last):
  File "E:/KratosInstall/test_kratos/Issue/4PunktSegel_noCable_MeshMoving_1iters.gid/MainKratos.py", line 44, in <module>
    ProjectParameters = Parameters(parameter_file.read())
RuntimeError: Error: error found in parsing the json_string, the value of the json string was: 
The document is empty. offset of the error from the beginning of the string = 0
a much more explicative error message can be obtained by analysing the input string with an online analyzer such for example json lint
the value of the string that was attempted to parse is :
in kratos/includes/kratos_parameters.h:122:Parameters::Parameters_

I checked my ProjectParameters.json online, the json is valid. 

I have attached my testcase in the following link:
[Issue_kratos_debug.zip](https://github.com/KratosMultiphysics/Kratos/files/1105212/Issue_kratos_debug.zip)

For the testcase, I can excute Kratos in release modus. For the compiling of Kratos in Debug modus, I followed the the guides in kratos wiki:

https://github.com/KratosMultiphysics/Kratos/wiki/How-to-Compile-Kratos-in-Debug-mode
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-cross-debug-Kratos-under-Windows

I was able to debug the code before (python & C++).  

@pooyan-dadvand @RiccardoRossi @loumalouomega @msandre @AndreasWinterstein 
Thank you very much for your help.
Long

**Comment by jcotela** [comment]
I'm not sure if this is related, but we recently changed things so that the StructuralMechanicsApplicaition is no longer dependent on the SolidMechanicsApplication. Unfortunately, this means there is now some duplicate code between the two. Could you try importing the Structural and not the Solid and see if you have the same problem? (as your error 1)

**Comment by pooyan-dadvand** [comment]
if it is in debug, would you please run it from the Visual studio and see where is crashing?

Is it crashing in release also?

**Comment by loumalouomega** [comment]
Indeed now it is not possible to use Solid and Structural together

**Comment by longchentum** [comment]
Hi,

thanks a lot. I commented the SolidMechanicsApplication and the StructuralMechanicsApplication now can be imported.
But I still have the second issue regarding the _kratos_parameters.h_, line 112 and line 113:
`        mpdoc =  boost::shared_ptr<rapidjson::Document>(new rapidjson::Document() );
        rapidjson::ParseResult ok = mpdoc->Parse<0>(json_string.c_str());`

Best,
Long

**Comment by longchentum** [comment]
Hi @pooyan-dadvand ,

it crashes at the line 112 or line 113 in kratos_parameters_h:
`        mpdoc =  boost::shared_ptr<rapidjson::Document>(new rapidjson::Document() );`
`        rapidjson::ParseResult ok = mpdoc->Parse<0>(json_string.c_str());`

It is fine in release.
I also checked my ProjectParameters.json online, there is no syntax error in json.

Best,
Long

**Comment by pooyan-dadvand** [comment]
It seems that there are some empty entry in your json:

```
RuntimeError: Error: error found in parsing the json_string, the value of the json string was:
The document is empty. offset of the error from the beginning of the string = 0
a much more explicative error message can be obtained by analysing the input string with an online analyzer such for example json lint
the value of the string that was attempted to parse is :
```

@RiccardoRossi a line number indicator in this type of errors would be useful, nevertheless I'm not sure if you have it when making this error.

**Comment by longchentum** [comment]
The problem is the cross-debugging with python and C++ under windows. The problem is solved when I am using VS only to debug C++ code. 

Thanks a lot @RiccardoRossi .
