### ISSUE TITLE
[Core] BDF2 Coefficients if previous delta time is almost zero

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#5515]
Some of our QA examples are failing due to a difference in the way bdf2 coefficients are computed in the case the previous delta time was almost zero. In that case now we compute:
bdf0 = 1.5 / dt
bdf1 = -2 / dt
bdf2 = 0.5 / dt

Previously, if delta time from previous time step was zero we simply used bdf1
bdf0 = 1 / dt
bdf1 = -1/dt
bdf2 = 0

which makes more sense to me as this is telling you pretty much that you do not have a computed step two time steps behind.  Is there any reason why this new option was preferred or can we set it as it used to be?

@KratosMultiphysics/altair @philbucher @rubenzorrilla

**Comment by ddiezrod** [comment]
I mean these lines https://github.com/KratosMultiphysics/Kratos/blob/7e92efa1de5d4162899452939be4f211f8521bfe/kratos/utilities/time_discretization.cpp#L139

**Comment by philbucher** [comment]
hm strange, I thought I used the same as it was before
I will check, but in general I don't have objections, sorry for the inconvenience

**Comment by ddiezrod** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/615e500959c980c11718cb612dbbaf8e5fa64d85/kratos/processes/compute_bdfcoefficients_process.h#L141

here :) , also the if condition is more restrictive now, (I think maybe too much)

**Comment by rubenzorrilla** [comment]
@ddiezrod I think I did not fully understand your point... Do you mean that `Dt` is close to zero, so the BDF coefficients blow up or that the information you have in the oldest position of the buffer is meaningless (very first step of the problem) and you would like to use a BDF1 formula in the very first step?

**Comment by ddiezrod** [comment]
option B: old-old position is meaningless so I think you should use BDF1. This has an impact in results enough to make results change a little but it does not blow up.

**Comment by loumalouomega** [comment]
The core bdf schemes compute the coefficients too. I implemented those, can
you check if there is zero too?

At the moment I checked it, but may be broken too.

**Comment by ddiezrod** [comment]
@loumalouomega https://github.com/KratosMultiphysics/Kratos/blob/7e92efa1de5d4162899452939be4f211f8521bfe/kratos/solving_strategies/schemes/residual_based_bdf_scheme.h#L250

Here it uses the same approach (the new one) , if previous_delta_time is almost zero then it uses constant time step. (previous delta time = delta time). Still, I might me missing something but I think that this does not make much sense.

**Comment by rubenzorrilla** [comment]
More than the scheme, I think this is related with the initial condition of your problem. If you have a good enough initial approximation I think there is no problem in using the scheme as it is. The problem arises when you have to buffer positions full of zeros (which is what we normally do).

**Comment by ddiezrod** [comment]
In our case, temperature is correctly set (this is a thermal problem), so the issue is not so important. I could just update my QA results and that would be it. However, my point is that what we are doing right now (take prev_time_step = time_step) makes less sense that we were doing before (simply use bdf1), so I think it would be better to recover the old behaviour.

**Comment by rubenzorrilla** [comment]
So what you are aiming to do is:
- 1st step: use BDF1 (only buffer position 1 is used)
- 2nd step: start using BDF2 (use buffer position 1 (with data from 1st step) and 0)
If this is the case, I don't think this has to be controlled by the scheme but by the solver...

**Comment by ddiezrod** [comment]
@rubenzorrilla Yes, there are many things I can do from our side to make it work the way we intend. But, if I bring this here its because I think the current behaviour makes no sense as far as I understand it. (Why if a time step is practically zero, should we set it equal to the following time step?) . Of course, you might disagree on this point, but thats the way I see it...

**Comment by rubenzorrilla** [comment]
Now I think I got your point. I thought you were talking about the information in the buffer (if it is meaningful or not), which is to say, how you initialize the problem, which is to say how you fill the buffer to avoid memory errors. This is why I told you that this has to be controlled by the solver and not by the scheme.

You are talking about the computation of the coefficients. What I don't understand right know is how you would avoid memory leaks when you multiply the `bdf2 = 0` coefficient by the third position in the buffer (I assume that you have no previous time step and that's why we are entering in this part of the code).

**Comment by ddiezrod** [comment]
@rubenzorrilla Yes!! Sorry for my bad explanation. You do not get a memory error becauses your buffer size is set to 3, so even if you are in step 1 you can always access two positions before. (Which in this case is probably a zero)

**Comment by pablobecker** [comment]
also, we are intializing correctly the buffer by cloning the timestep a couple of times with timestep close to zero

**Comment by pablobecker** [comment]
a short summary why choose BDF1 or BDF2 in the first step (in both cases delta_t_old=0)

- setting BDF1 implies you tell the solver ONLY the initial conditions (eg V(t=0) , but you have no idea how accelerations were in the previous time step, so it is better to go for a lower order scheme

- setting BDF2  and assuming the old dt was the same  implies you're also setting dV/dt(old) = 0. if you start from a zero velocity scenario, it is ok, but this is not always the case.

IMO it is better to go for BDF1 then, assuming we're always starting from zero derivatives is not a good assumption.

**Comment by rubenzorrilla** [comment]
> also, we are intializing correctly the buffer by cloning the timestep a couple of times with timestep close to zero

Now it is clear. By the way, this is similar but not the same to what we do in the base fluid solver. We use the simulation time step instead of an almost null one.

**Comment by rubenzorrilla** [comment]
> a short summary why choose BDF1 or BDF2 in the first step (in both cases delta_t_old=0)
> 
>     * setting BDF1 implies you tell the solver ONLY the initial conditions (eg V(t=0) , but you have no idea how accelerations were in the previous time step, so it is better to go for a lower order scheme
> 
>     * setting BDF2  and assuming the old dt was the same  implies you're also setting dV/dt(old) = 0. if you start from a zero velocity scenario, it is ok, but this is not always the case.
> 
> 
> IMO it is better to go for BDF1 then, assuming we're always starting from zero derivatives is not a good assumption.

You guys have played around with this kind of robustness issues much more than me. Having said this, I would have no objection on reverting the "almost null time step" coefficients to the old behaviour.

**Comment by ddiezrod** [comment]
Ok, I'll create a MR modifying these coefficients if everyone agrees. @rubenzorrilla @philbucher @loumalouomega
