### ISSUE TITLE
[FluidDynamicsApplication] (Python) Processes - refactoring/improving/exposing existing capabilities

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#5516]
I want to initiate a discussion related to existing capabilities with an outlook to improve or consolidate these preferably with exposure into python in form of a python process.

- Calculating CFL @jcotela (first step in #5499)
- Calculating y+ (for now used in different wall function processes) @msandre @sunethwarna @rubenzorrilla 
- Calculating QValue @msandre (or in general vorticity measures @rubenzorrilla)
- Imposing a fluctuating wind inlet @msandre @AndreasWinterstein 
- Imposing wall function(s) @msandre @sunethwarna @rubenzorrilla 

This is a list of topics I would propose to address. Most of these have a C++ layer implementation and some of us have been using these with our own python process scripts, from which most have not made it into the master, which is a pity.

What would be the wright way to have some functionalities (such as CFL and y+ value calculation) not being part of others (currently estimate dt utility and some wall functions)? It would definitely be desirable to have these working as a postprocessing step, same goes for QValue (or generally vorticity measures).

Can the depending functionalities (such as estimate dt utility and various wall functions) benefit from such a restructuring?

As far as wall functions go, I am not sure how much these are currently depending on certain element formulations, maybe these will prohibit too much generalization and unification.

@inigolcanalejo and @philbucher check out the list and the proposal. I think we could all benefit from these improvements once we agree what would be the best way to go.

@philbucher feel free to leave your thoughts with respect to refactoring and coding bearing in might the current status of the code and where it is heading to.

**Comment by mpentek** [comment]
As a specific sub-topic: creating one assign wall process based upon slip.

After discussiond with @jcotela and @sunethwarna it seems that for body fitted meshes this could be done relatively straight forward. How about embedded meshes @rubenzorrilla, any specific conflicts?

**Comment by mpentek** [comment]
Calculating CFL in #5985 possibly of interest for @akodakkal @AndreasWinterstein @sunethwarna

**Comment by rubenzorrilla** [comment]
> As a specific sub-topic: creating one assign wall process based upon slip.
> 
> After discussiond with @jcotela and @sunethwarna it seems that for body fitted meshes this could be done relatively straight forward. How about embedded meshes @rubenzorrilla, any specific conflicts?

From the embedded perspective, everything should be possible. However, I see that in some cases we will need to specify that the values (or volume integrals) are taken from the real part of the element (e.g. to compute the CFL we need to use the velocity of the wet nodes but no the one from the dry ones). This is not straightforward as we we have two different types of level set (continuous and discontinuous). On top of this, some formulations use a modified FE space, this means that the magnitudes must be computed with this one instead.

With regard to the boundary terms (wall laws), in the embedded case this becomes in a weak BC imposition, so it wouldn't be as straightforward... So far we have a Navier-slip BC, which is a kind of wall law regulated by a so called slip_lenght parameter that can do the job. This is implemented for both volume (continuous level set)  and volumeless (discontinuous level set) bodies.

**Comment by mpentek** [comment]
@rubenzorrilla ok, so my suggestion would be that we proceed with the cfl and wall function processes, such that we can progress with body-fitted simulation - which is the workhorse - and later see what adaptations might be needed for compatibility with embedded as well. Maybe one way to go will be like the compute drag process, with a base classe and respective derived classes, or maybe a smarter way.

**Comment by rubenzorrilla** [comment]
> @rubenzorrilla ok, so my suggestion would be that we proceed with the cfl and wall function processes, such that we can progress with body-fitted simulation - which is the workhorse - and later see what adaptations might be needed for compatibility with embedded as well. Maybe one way to go will be like the compute drag process, with a base classe and respective derived classes, or maybe a smarter way.

Makes perfect sense for me. Actually I like the approach we took for the drag calculation, so it probably makes sense to do the same for the other magnitudes.

**Comment by mpentek** [comment]
One more step achieved in #6119. Nonetheless, I am still not happy with the solution. I would wait to see what maybe similar/other necessities of @sunethwarna and the RANS Application will be before further trying to unify wall conditions. I would be in favor of `apply_wall_condition` with parameters:

```
model_part
wall_function
y_wall
other_flags
```

Now it is misusing IsSlip, which is from a user point of view very confusing. Also leads to weird code dependencies in my opinion. @rubenzorrilla ?

**Comment by mpentek** [comment]
Will need to be continued more focused on certain specific aspects, so closing this old thread.
