### ISSUE TITLE
[CompressivePotentialFlow] Error on Windows compilation

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#5525]
```
1>------ Build started: Project: KratosCompressiblePotentialFlowApplication, Configuration: Release x64 ------
1>Building Custom Rule E:/PROYECTOS/Kratos/applications/CompressiblePotentialFlowApplication/CMakeLists.txt
1>CMake does not need to re-run because E:/PROYECTOS/Kratos/cmake_build/applications/CompressiblePotentialFlowApplication/CMakeFiles/generate.stamp is up-to-date.
1>   Creating library E:/PROYECTOS/Kratos/cmake_build/applications/CompressiblePotentialFlowApplication/Release/KratosCompressiblePotentialFlowApplication.lib and object E:/PROYECTOS/Kratos/cmake_build/applications/CompressiblePotentialFlowApplication/Release/KratosCompressiblePotentialFlowApplication.exp
1>add_custom_utilities_to_python.obj : error LNK2019: unresolved external symbol "void __cdecl Kratos::PotentialFlowUtilities::CheckIfWakeConditionsAreFulfilled<2>(class Kratos::ModelPart const &,double const &,int const &)" (??$CheckIfWakeConditionsAreFulfilled@$01@PotentialFlowUtilities@Kratos@@YAXAEBVModelPart@1@AEBNAEBH@Z) referenced in function "void __cdecl Kratos::Python::AddCustomUtilitiesToPython(class pybind11::module &)" (?AddCustomUtilitiesToPython@Python@Kratos@@YAXAEAVmodule@pybind11@@@Z)
1>add_custom_utilities_to_python.obj : error LNK2019: unresolved external symbol "void __cdecl Kratos::PotentialFlowUtilities::CheckIfWakeConditionsAreFulfilled<3>(class Kratos::ModelPart const &,double const &,int const &)" (??$CheckIfWakeConditionsAreFulfilled@$02@PotentialFlowUtilities@Kratos@@YAXAEBVModelPart@1@AEBNAEBH@Z) referenced in function "void __cdecl Kratos::Python::AddCustomUtilitiesToPython(class pybind11::module &)" (?AddCustomUtilitiesToPython@Python@Kratos@@YAXAEAVmodule@pybind11@@@Z)
1>E:\PROYECTOS\Kratos\cmake_build\applications\CompressiblePotentialFlowApplication\Release\KratosCompressiblePotentialFlowApplication.pyd : fatal error LNK1120: 2 unresolved externals
1>Done building project "KratosCompressiblePotentialFlowApplication.vcxproj" -- FAILED.
```

**Comment by roigcarlo** [comment]
You need to expose the `CheckIfWakeConditionsAreFulfilled` for every template you are using in the add_utilities_to_python file (2 and 3).

**Comment by inigolcanalejo** [comment]
> You need to expose the `CheckIfWakeConditionsAreFulfilled` for every template you are using in the add_utilities_to_python file (2 and 3).

This is actually already done here:
https://github.com/KratosMultiphysics/Kratos/blob/cd4061abafa4ce83ecc40aa0309b2af5caa871bc/applications/CompressiblePotentialFlowApplication/custom_python/add_custom_utilities_to_python.cpp#L30-L33

Or did you mean something else?

I tried this https://github.com/KratosMultiphysics/Kratos/pull/5533/commits/5fb5f3f81a099a01cf9fd61d4b09a51b3ced5a09 but I am not sure it works.

**Comment by roigcarlo** [comment]
Yep, the 5fb5f3f should be enough. I am not sure with the templates but we will see what the CI says ( I don't have win right now to test it).

Just  clarify, the changes in:
The Kratos/applications/CompressiblePotentialFlowApplication/custom_python/add_custom_utilities_to_python.cpp 
Are the ones used to expose the functions to python, the KRATOS_API macro is used to expose the functions between shared libs ( in this case between the core and the python api, which is a separate object):

AppCore.So ->KRATOS_API -> Application.So -> Pybind -> PythonModule.Pyd
