### ISSUE TITLE
TODO: Remove deprecated processes in the core

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#554]
Hi all,

i believe that we should consider as deprecated (and remove asap)
the processes

apply_constant_value_process.py
apply_custom_function_process.py
apply_variable_value_process.py
impose_scalar_value_process.py
impose_vector_value_by_components_process.py
impose_vector_value_by_direction_process.py

the "official" versions (much more feature complete and efficient) are the 
assign_*

processes.

has anyone any concern about this? (migration to the new processes should be very easy)

**Comment by loumalouomega** [comment]
Agree, should I start a PR removing that?, checking of course that are not used in any application

**Comment by jcotela** [comment]
Since you say it is a "simple" change, I'd say we go ahead and start by removing them on a branch. Then we can discuss it/ensure we are not introducing new errors during review in the corresponding PR.

**Comment by ipouplana** [comment]
I am currently using the ApplyConstantScalarValueProcess c++ class... Which is its non-deprecated alternative?
Thanks in advance

**Comment by RiccardoRossi** [comment]
@ipouplana the one to use in that context is:
assign_scalar_variable_process.py 
just pass a constant value and it will follow the optimized code path (just do not specify anything for which the defaults are ok for you)

@jcotela yes, certainly we should start a pull request. My idea however is to first have a deprecation printout from within the deprecated processes, say something like

    WARNING: this processes is deprecated and will be removed on the day ***** - please use ************  instead

@loumalouomega thx for the offer. As i was writing to @jcotela i would go for a removal in stages, first printing a warning. On the practical side, also there are some c++ counterpart of the processes to be removed, so the pull request should be done with some care (and i would wait a bit to do it, see my post to Jordi)

**Comment by jcotela** [comment]
Then I'd just put the deprecation warning right now (Maybe without a date, we are not good at deadlines anyway) and judge how painful the fix will be from the frequency of deprecation messages in our output.

**Comment by RiccardoRossi** [comment]
@jcotela ok, i agree (also on avoiding the date :-) )

@loumalouomega are u still up for making the branch? I'll do it if you prefer

**Comment by loumalouomega** [comment]
The ting of the deprecated remember me that we still have a message for the deprecated "modulus" and stuff. I can do the branch, but I will basically remove the deprecated processes and replace if possible in the applications

**Comment by jcotela** [comment]
@loumalouomega Please wait before removing them for good. The "if possible" part is precisely the problem...

**Comment by loumalouomega** [comment]
Ok, I will wait

**Comment by pooyan-dadvand** [comment]
Maybe we can add the warning in a separate branch and merge it to the master which says please check your code in this branch and remove it from this branch as a test bench.

**Comment by philbucher** [comment]
this was solved in #897
