### ISSUE TITLE
Printing conditions in GiD

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#5544]
Dear all,

 As far as I know, if you use this flag: `"WriteConditionsFlag":   "WriteConditions"` you can print for example the line loads that you have defined. In my opinion could be interesting that each load/condition has different Id/layer so you can set to **on/off each condition** independently. 

Is this possible or should have to be implemented?

Thank you kindly,

Alejandro

**Comment by loumalouomega** [comment]
You should assign a new property

**Comment by AlejandroCornejo** [comment]
How do you do that? :)

**Comment by loumalouomega** [comment]
In the read_materials_utility you can include the submodelparts of the conditions

**Comment by AlejandroCornejo** [comment]
ok! I'll try something like that THX
