### ISSUE TITLE
Hexahedron Node Ordering bad documentation

### ISSUE THREAD

**Issue by JulioGalindo** [KratosMultiphysics/Kratos#5546]
In hexahedra_3d_20.h lines 645 and 646 the nodes 18 and 14 are changed, they might be as follows:

`        faces.push_back( FacePointerType( new FaceType(
                                              this->pGetPoint( 7 ),
                                              this->pGetPoint( 6 ),
                                              this->pGetPoint( 2 ),
                                              this->pGetPoint( 3 ),
                                              this->pGetPoint( 18 ),
                                              this->pGetPoint( 14 ),
                                              this->pGetPoint( 10 ),
                                              this->pGetPoint( 15 ) ) ) );

`
The same problem within hexahedra_3d_27.h, lines 665 and 666, nodes 18 and 14, they might be as follows:
`
        faces.push_back( FacePointerType( new FaceType(
                                              this->pGetPoint( 7 ),
                                              this->pGetPoint( 6 ),
                                              this->pGetPoint( 2 ),
                                              this->pGetPoint( 3 ),
                                              this->pGetPoint( 18 ),
                                              this->pGetPoint( 14 ),
                                              this->pGetPoint( 10 ),
                                              this->pGetPoint( 15 ),
                                              this->pGetPoint( 23 ) ) ) );
`
At the beginning of hexahedra_3d_20.h and hexahedra_3d_27.h as well as in the Wiki documentation the nodes order scheme have a bug. The node ordering is as follows:

![hexahedron_3d_20 h](https://user-images.githubusercontent.com/30028483/64502467-a2d35200-d29c-11e9-8155-1e9fca3e41df.png)
![hexahedron_3d_27 h](https://user-images.githubusercontent.com/30028483/64502468-a2d35200-d29c-11e9-95c7-0c2bdc8c9b2d.png)

.

**Comment by loumalouomega** [comment]
I am human, can you change this please?

**Comment by RiccardoRossi** [comment]
Isn't this tested in the test_geometries? also the patch_tests should cover this :-(

our numeration should be according to
https://www.gidhome.com/documents/referencemanual/PREPROCESSING/Mesh%20Menu/Element%20type

@JulioGalindo do you confirm the error wrt that reference?

**Comment by loumalouomega** [comment]
We are speaking about documentation. It is tested

**Comment by philbucher** [comment]
is this solved?

**Comment by loumalouomega** [comment]
I don't know, I get lost with the node ordering of quadratic stuff

**Comment by loumalouomega** [comment]
Fixed in two PR
