### ISSUE TITLE
 PARTITION_INDEX defined as double?

### ISSUE THREAD

**Issue by asroy** [KratosMultiphysics/Kratos#555]
Hi, this maybe not be an issue. But when I was looking around, I found following code:

./kratos/includes/variables.h:135:    KRATOS_DEFINE_VARIABLE( double, PARTITION_INDEX )

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/variables.h#L135

Shouldn't PARTITION_INDEX be defined as int?

Chao

**Comment by pooyan-dadvand** [comment]
For historical reasons, many years ago (2006) when we wanted to add parallelism to Kratos our input file interepreter could only read double variables.....

someday we should clean it up

**Comment by asroy** [comment]
Hi @pooyan-dadvand, Thank you for the explaining. If I want to compare PARTITION_INDEX with mpi rank (double vs int) in Kratos, could I expect the result to be always correct?
Thanks,
Chao

**Comment by loumalouomega** [comment]
@asroy You can use a static_cast http://en.cppreference.com/w/cpp/language/static_cast

**Comment by maceligueta** [comment]
A static_cast would round 1.99999999999999999 to 1. It is dangerous, in my opinion.

**Comment by RiccardoRossi** [comment]
@asoy (and at all)

i believe that using a double might indeed be dangerous, however so far i didn't experience problems with this, probably because we never really operate with the partition index (i mean, we never sum, multiply, etc)

**Comment by asroy** [comment]
@RiccardoRossi @pooyan-dadvand @loumalouomega @maceligueta 
Thank you for the clarification. I don't see myself would need to operate with the partition index, so it should be OK.
