### ISSUE TITLE
Several typos in the geometries

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#557]
I have found several "length" typos, written as "lenght", in the geometry.h and derived classes.

Do I correct them?, I still have pending PR related with the geometry.h

**Comment by loumalouomega** [comment]
Can we add the label "Typo"?

**Comment by jcotela** [comment]
Are those comments, function names or local variables? (or something else entirely?)

**Comment by loumalouomega** [comment]
In general are comments, but there are some private operations (not common to all the geometries) with typos in some classes

**Comment by jcotela** [comment]
I'd say we fix it, but not in your open PR (I'd prefer not to mix the two improvements). Can you do the changes on a separate branch, without affecting your open PR? If it is possible, I'd say go ahead. Otherwise please wait until there is a decision on the open PR.

**Comment by pooyan-dadvand** [comment]
Added!

**Comment by loumalouomega** [comment]
Thanks @pooyan-dadvand

**Comment by RiccardoRossi** [comment]
as a comment: i think we should make such changes only once we added the overrides. Otherwise we may break the interface

**Comment by loumalouomega** [comment]
I will close this in order to reduce the number of open issues
