### ISSUE TITLE
*.cpp checks are failing for new distance function

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#558]
`TestTetrahedra3IntersectionDistanceProcess` and `TestTetrahedra5IntersectionDistanceProcess` are failing. I believe that we should call calcuate discontinuous distance in them.

**Comment by rubenzorrilla** [comment]
Well, I think that in the `TestTetrahedra5IntersectionDistanceProcess` we should call the `CalculateDistanceToSkinProcess` (the test consists in a two tetrahedron intersection).  

![test_5](https://user-images.githubusercontent.com/19992225/27643493-895467cc-5c21-11e7-8386-e0cc85dfcc28.png)

For the `TestTetrahedra3IntersectionDistanceProcess`, which is a plane-tetrahedron intersection, it might have sense to use the discontinuous one.

![test_3](https://user-images.githubusercontent.com/19992225/27643598-cb761a42-5c21-11e7-9b4a-720ea2683a49.png)

**Comment by pooyan-dadvand** [comment]
👍

**Comment by rubenzorrilla** [comment]
We solve this in #563.
