### ISSUE TITLE
[FluidDynamicsApplication] Does it support LES or DNS of turbulent flow.

### ISSUE THREAD

**Issue by ztdepztdep** [KratosMultiphysics/Kratos#5580]
Does it support LES or DNS of turbulent flow.

**Comment by loumalouomega** [comment]
@KratosMultiphysics/fluid-dynamics @KratosMultiphysics/fluid-maintainers

**Comment by jcotela** [comment]
See the discussion in #4769 for an overview of the available options. Please let me know if you have further questions.

**Comment by jcotela** [comment]
Closing issue as inactive. Feel free to reopen if there are more questions.
