### ISSUE TITLE
[FluidDynamicsApplication] RANS implementation

### ISSUE THREAD

**Issue by Sesae** [KratosMultiphysics/Kratos#5581]
@jcotela I think that you have developed a RANS implementation for Kratos, can you tell me which is current state of the project? @RiccardoRossi

**Comment by jcotela** [comment]
The RANS implementation is mainly the work of @sunethwarna. In terms of the current state, the initial implementation (which will include the k-epsilon model and required classes to use it in combination with the fluid solver) is in the final stages of validation and will be merged to master shortly, hopefully in the coming weeks.

**Comment by sunethwarna** [comment]
The application is being merged in this PR #5689

**Comment by philbucher** [comment]
closing since inactive
please reopen otherwise
