### ISSUE TITLE
[NvidiaFlexApplication] Readme

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/Kratos#5600]
Any reason why the Nvidia application has the DEM readme [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/NvidiaFlexApplication/README.md) Tagging the contributors of the README.md.

**Comment by salvalatorre** [comment]
Thanks, Riccardo, for pointing that out. Obviously it is an error. The application was created by @maceligueta and myself, developers of the DEM Application, so I guess it was only a copy-and-paste slip.
We'll fix that as soon as possible.
Regards!

**Comment by maceligueta** [comment]
Reopening until it's fixed. Assigned to me as well, as a reminder. Thanks @riccardotosi .

**Comment by philbucher** [comment]
can this be closed?
This app was moved to the legacyrepo

**Comment by riccardotosi** [comment]
I leave to @maceligueta and @salvalatorre the answer, since I just spotted the error.

**Comment by maceligueta** [comment]
Yes, it is removed, so closing.
