### ISSUE TITLE
[MeshingApplication] MMG process output is affected by submodelparts in the model

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#5605]
Hi,

Here is an issue that I encountered when using the mmg_process  in the potential flow (but it is not directly related to the potential flow, see minimal test defined next). 

It seems that the remeshing is affected if there are submodelparts defined in the model. For instance, look at this mesh with the following metric tensor field:

![image](https://user-images.githubusercontent.com/32136457/65143350-06841a80-da15-11e9-89f7-88ddf2b1b4f0.png)

The remeghing output (zooming out the image) is the following:

![image](https://user-images.githubusercontent.com/32136457/65143396-23b8e900-da15-11e9-90e6-a735812c2b72.png)

We can see we have refined close to the body, but there is something weird on the right side, close to where we define the "wake" in the  potential flow.

For us the wake is a submodelpart which contains only elements:

```
  -wake_sub_model_part- model part
        Number of tables : 0
        Number of sub model parts : 0

        Mesh 0 :
            Number of Nodes       : 0
            Number of Properties  : 0
            Number of Elements    : 83
            Number of Conditions  : 0
            Number of Constraints : 0
```

If i remove the wake_sub_model_part before remeshing, this issue dissapers:

`main_model_part.RemoveSubModelPart('wake_sub_model_part')`

![image](https://user-images.githubusercontent.com/32136457/65143534-84482600-da15-11e9-8276-acbf4addbeef.png)

While I can always remove these submodelparts, I am not sure if this is the expected behaviour of the remesher.

I prepared a small example, not dependant on the potential flow:

I load a circle:

![image](https://user-images.githubusercontent.com/32136457/65143635-c4a7a400-da15-11e9-9b7a-0bdc6664ed06.png)

And define a sub_model_part containing some elements:

![image](https://user-images.githubusercontent.com/32136457/65143671-ddb05500-da15-11e9-921f-e9362e144d9e.png)

And after remeshing we can see the the final result is affected by the line_model_part that has been defined:

![image](https://user-images.githubusercontent.com/32136457/65143730-fc165080-da15-11e9-840d-646814bc7578.png)

Is this intended?

Here are the files for the minimal example:

[mmg_test.zip](https://github.com/KratosMultiphysics/Kratos/files/3626308/mmg_test.zip)

**Comment by loumalouomega** [comment]
I will check

**Comment by loumalouomega** [comment]
In any case this is something from the library, not from our side

**Comment by loumalouomega** [comment]
[mmg_files.zip](https://github.com/KratosMultiphysics/Kratos/files/3627179/mmg_files.zip)

@marcnunezc I checked and this is an internal thing of MMG, I recommend to take the files that I attach (these are the MMG generated files), and ask directly in the forum. I assume that in order to preserve entities they generate regions before remesh and after that they rebuild the new mesh. Like the original mesh is quite coarse the regions are quite "that". 

I don't know how do you generate your wake elements, but if can be done as a postprocess I recommend to do that. For example when I remesh with contact I remove all the contact conditions, because the remesh process is confused of the amount of information given, I rebuild the contact interface after remesh because I can do it with the initial information which is correctly preserved

**Comment by marcnunezc** [comment]
Ok I will ask in the forum! Just for my understanding, what is the difference in the .sol .msh files if I remove the line_sub_model_part? How can I refer to this when asking in the forum?

> I assume that in order to preserve entities they generate regions before remesh and after that they rebuild the new mesh. Like the original mesh is quite coarse the regions are quite "that".
> 
I think I dont follow you in the last sentence.
> I don't know how do you generate your wake elements, but if can be done as a postprocess I recommend to do that. For example when I remesh with contact I remove all the contact conditions, because the remesh process is confused of the amount of information given, I rebuild the contact interface after remesh because I can do it with the initial information which is correctly preserved

Yes, in fact we reset the wake element when initializing the process, but we don't remove the sub model part once it finishes.

As I said this is not a major problem in our cases but I thought that it may be a problem in other applications.

**Comment by loumalouomega** [comment]
> Ok I will ask in the forum! Just for my understanding, what is the difference in the .sol .msh files if I remove the line_sub_model_part? How can I refer to this when asking in the forum?
> 

.sol is the metric, .mesh is the mesh (you can open it with Medit or GMSH (I recommend this last one))

> > I assume that in order to preserve entities they generate regions before remesh and after that they rebuild the new mesh. Like the original mesh is quite coarse the regions are quite "that".
> 
> I think I dont follow you in the last sentence.
> 

I didn't want to use ugly words in  a public forum

> > I don't know how do you generate your wake elements, but if can be done as a postprocess I recommend to do that. For example when I remesh with contact I remove all the contact conditions, because the remesh process is confused of the amount of information given, I rebuild the contact interface after remesh because I can do it with the initial information which is correctly preserved
> 
> Yes, in fact we reset the wake element when initializing the process, but we don't remove the sub model part once it finishes.

Check the mmg_process_contact.py in the ContactStructuralMechanicsApplication. I do several things there specific for the problem. It is not possible to always use standard procedures as may exist specific behaviors not expected for a standard remeshing procedure

> 
> As I said this is not a major problem in our cases but I thought that it may be a problem in other applications.

I provide common utilities for remeshing, but I cannot predict 100% of potential issues. @AlejandroCornejo has modifications for the FEM-DEM, I have mine for contact

BTW: Ping #4558

**Comment by marcnunezc** [comment]
Ok! You can follow the discussion here:

https://forum.mmgtools.org/t/mmg2d-giving-different-results-for-the-same-metric-depending-on-the-regions-defined-in-the-domain/361

**Comment by marcnunezc** [comment]
Closing this issue after the explanation from the [MMG team](https://forum.mmgtools.org/t/mmg2d-giving-different-results-for-the-same-metric-depending-on-the-regions-defined-in-the-domain/361/2?u=marcnunez).

This is an intended behaviour of MMG, since the remesher tries to preserve the different domains in the mesh.
