### ISSUE TITLE
Selecting solver compilation in TrilinosApplication

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#5612]
Especially when compiling the Kratos on cluster systems one might run into troubles because of trilions. I experienced that there is often a problem with only one of the solvers, which are contained in trilinos. Additionally one might also not need the built in solvers of trilinos but one might only want to use the AMCL from the core (which is anyway faster in most of the cases). Thus, I suggest to give the user the possibility to select if he wants to compile the trilinos solvers in the config script e.g. COMPILE_BUILT_IN_TRILINOS_SOLVERS = TRUE or COMPILE_TRILINOS_ML etc..
Please let me know what you think about this idea. I already briefly discussed this with @philbucher .

**Comment by philbucher** [comment]
This is what #5607 is for :)

**Comment by AndreasWinterstein** [comment]
Sorry. Too many issues..

**Comment by RiccardoRossi** [comment]
hi Andrras,

i dont follow. in my inderstanding, amgcl_mpi should be now compiled by
default and the other solvers (apart for the direct ones) all come in a
single library. so...i don t understand what you propose

Riccardo

**Comment by philbucher** [comment]
Riccardo he basically proposes #5607
