### ISSUE TITLE
[core] Invalid memory access

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#5617]
Invalid memory access reported by Valgrind, somewhere between the model part, node or variable list functions.

As stated by @RiccardoRossi , the cause may be related to the order of destruction of objects in the model part.

I have prepared a minimal working example that reproduces the problem.
[MWE.zip](https://github.com/KratosMultiphysics/Kratos/files/3794156/MWE.zip)

I am also attaching valgrind output with and without errors (obtained commenting out the offending line) (clang and FullDebug)

[valgrind.out.errors.txt](https://github.com/KratosMultiphysics/Kratos/files/3794137/valgrind.out.errors.txt)
[valgrind.out.no_errors.txt](https://github.com/KratosMultiphysics/Kratos/files/3794138/valgrind.out.no_errors.txt)

To compile the MWE, just modify KRATOS_PATH in the Makefile to the Kratos directory, then `make`.
To run, `make run`
To run valgrind, `make valgrind`

Line 13 of main.c (CreateNewNode function) generates the invalid accesses.

EDIT: Invalid memory access, not memory leak

**Comment by marandra** [comment]
I am getting random segmentation faults while running cpp_tests of StructuralMechanicsApplication. I couldn't isolate a specific file, but valgrind seems to point again to node functions, so I suspect the segfauls are related to this issue.

Bumping it to remind @RiccardoRossi .

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee FYI

**Comment by pooyan-dadvand** [comment]
May be related to #5878 ?

**Comment by marandra** [comment]
I don't think so. #5878 is related to a test in python.

I obtain random segfaults with just the following program:
```
#include "includes/kernel.h"
#include "containers/model.h"
void umat ();
void umat ()
{
    Kratos::Kernel kernel;
    kernel.Initialize();
    Kratos::Model current_model;
    Kratos::ModelPart& test_model_part = current_model.CreateModelPart("Main");
    Kratos::Node<3>::Pointer p_node_1 = test_model_part.CreateNewNode(1, 0.0, 0.0, 0.0);
}
int main(int argc, char **argv)
{
  umat();
  return 0;
}
```
with problems inside the CreateNewNode function, according to Valgrind.

**Comment by pooyan-dadvand** [comment]
Really strange..... I think that valgrind is your friend.

**Comment by marandra** [comment]
Debug in progress

```
#include "includes/kernel.h"
#include "containers/model.h"
#include "includes/node.h"

//#include "umat.h"

void umat ();
void umat ()
{
    Kratos::Kernel kernel;
    kernel.Initialize();

    Kratos::Model current_model;
    Kratos::ModelPart& test_model_part = current_model.CreateModelPart("Main");
    //Kratos::Node<3>::Pointer p_node_1 = test_model_part.CreateNewNode(1, 0.0, 0.0, 0.0);
    auto p_new_node = Kratos::make_intrusive< Kratos::Node<3> >( 1, 0.0, 0.0, 0.0, test_model_part.pGetNodalSolutionStepVariablesList());

    // Giving model part's variables list to the node
    //p_new_node->SetSolutionStepVariablesList(test_model_part.pGetNodalSolutionStepVariablesList());

    p_new_node->SetBufferSize(1);

    test_model_part.AddNode(p_new_node);
}

int main(int argc, char **argv)
{
  umat();
  return 0;
}


```

**Comment by pooyan-dadvand** [comment]
@marandra, after checking your code and thanks to the hint of @RiccardoRossi, the memory problem was from the fact that you are not using -fopenmp and -pthread flags in the makefile but your kratos library is compiled with them. Considering that the Node constructor is in the cpp (in kratoscore lib which compiled with these flags) and the destructor is in the header which compiles without these flags, the atomic reference counter was not working well. 

Adding those flags solved the problem.

Meanwhile, I found two constructors of the nodes without the initialization of the reference counter. I will add fix them in a PR.

**Comment by RiccardoRossi** [comment]
closing since this is solved. @marandra please reopen if you consider
