### ISSUE TITLE
About material model in PFEM2 application

### ISSUE THREAD

**Issue by Gaoliu19910601** [KratosMultiphysics/Kratos#5652]
Hi everyone 
  I am a new user to Kratos and I am planning to use to PFEM2 application to study geotechnical problem. However it seems that there is no soil models in the application. I notice that there is a UMAT application in Kratos. Can I use it to embed soil model such as MohrCoulumn model in PFEM2? or is there other way to do it ? It will be of great help for me.

**Comment by philbucher** [comment]
@KratosMultiphysics/pfem2

**Comment by philbucher** [comment]
@miguelmaso

**Comment by dcagritan** [comment]
Dear @Gaoliu19910601,
What do you exactly want to simulate and what are the partial differential equations you'd like to solve?
Please let me know about the details and I'll do my best to help you.
Regards,
Deniz

**Comment by Gaoliu19910601** [comment]
Dear @dcagri 
Thanks so much for your kindness. I want to study the pile penetration into soil. It is a 2D axisymmetric problem and the pile could be regarded a rigid body. I intend to use MohrCoulomb mode to describe the behavior of the soil. Could it be done in PFEM2 and what are the main steps to  do it?

**Comment by dcagritan** [comment]
Dear @Gaoliu19910601,
I'm afraid to tell you that, I believe that PFEM2 is not the best choice of application for the test case you want to conduct. PFEM2 is a good method for single-fluid, or multi-fluid flows. However for solid applications, and especially for your test case, I'd encourage you to employ MPM(Material Point Method). @KratosMultiphysics/mpm 
Please feel free to contact us if you have any other inquiry or doubts.
I wish you a nice day.
Kind Regards,
Deniz

**Comment by Gaoliu19910601** [comment]
Hi @dcagri 
    Thanks so much for your detailed repaly. In fact, I am also trying to study this problem using MPM. However, I encouter  a problem about how to define the designated velocity of a pile (maybe it should be treated as a rigid body or just a body with a prescribed velocity?) but I do not how to apply a prescribed velocity on a body in MPM application. Do you know how to do it?
    Best regards
    Liu Gao

**Comment by PeterJosephWilson** [comment]
Thanks for your interest Liu! :)

I believe this can be done, although I am a little rusty at Kratos myself at the moment. I think @bodhinandach or @tteschemacher could probably help you out.
