### ISSUE TITLE
[Windows] Compilation ERROR in MeshingApplication

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#5656]
Hi!

I've just pulled the master branch and now the code it's not compiling...

One error says:

`Error	C2280	'std::unique_ptr<TDofType,std::default_delete<_Ty>>::unique_ptr(const std::unique_ptr<_Ty,std::default_delete<_Ty>> &)': se está intentando hacer referencia a una función eliminada.	KratosMeshingCore	C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include\xmemory0	881	`

And the other is regarding the add_custom_utilities_to_python in the MeshingApp:

`Error	LNK2019	símbolo externo "__declspec(dllimport) void __cdecl Kratos::MeshingUtilities::RecursiveEnsureModelPartOwnsProperties(class Kratos::ModelPart &,bool)" (__imp_?RecursiveEnsureModelPartOwnsProperties@MeshingUtilities@Kratos@@YAXAEAVModelPart@2@_N@Z) sin resolver al que se hace referencia en la función "void __cdecl Kratos::Python::RecursiveEnsureModelPartOwnsProperties(class Kratos::ModelPart &)" (?RecursiveEnsureModelPartOwnsProperties@Python@Kratos@@YAXAEAVModelPart@2@@Z)	KratosMeshingApplication	D:\KRATOS_MULTIPHYSICS\Kratos\cmake_build\applications\MeshingApplication\add_custom_utilities_to_python.obj	1	`

`Error	LNK2019	símbolo externo "__declspec(dllimport) void __cdecl Kratos::MeshingUtilities::EnsureModelPartOwnsProperties(class Kratos::ModelPart &,bool)" (__imp_?EnsureModelPartOwnsProperties@MeshingUtilities@Kratos@@YAXAEAVModelPart@2@_N@Z) sin resolver al que se hace referencia en la función "void __cdecl Kratos::Python::EnsureModelPartOwnsProperties(class Kratos::ModelPart &)" (?EnsureModelPartOwnsProperties@Python@Kratos@@YAXAEAVModelPart@2@@Z)	KratosMeshingApplication	D:\KRATOS_MULTIPHYSICS\Kratos\cmake_build\applications\MeshingApplication\add_custom_utilities_to_python.obj	1	
`

Anyone knows what's happening??

Thank you in advance,

Alejandro

**Comment by philbucher** [comment]
most probably related to #5550

**Comment by loumalouomega** [comment]
Why the Meshing is not compiled in AppVeyor? even Travis?, MeshingApplication it is supposed to be core app
