### ISSUE TITLE
TestQuadrilateralJacobianTest is failing

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#566]
This test is failing in my linux machine with following message 

```
Error: Check failed becuase detJ = inf is not near to MathUtils<double>::GeneralizedDet(jacobian) = 0.0198539 within the tolerance 1e-06
in kratos/tests/geometries/test_non_rectangular_jacobian.cpp:108:virtual void Testing::TestQuadrilateralJacobianTest::TestFunction()

```

@loumalouomega do you think that it is affected by your change in generailize det?

**Comment by loumalouomega** [comment]
The last change I did the computation  of the determinant for a matrix of any size when calculing the inverse. I thought I solved this issue already

**Comment by loumalouomega** [comment]
Did you updated?

Is this the code of your test?:

~~~
KRATOS_TEST_CASE_IN_SUITE(QuadrilateralJacobianTest, KratosNonRectangularJacobianFastSuite) 
        {
            Node<3>::Pointer PointA = Node<3>::Pointer(new Node<3>(1, 0.1, 0.2, 0.3));
            Node<3>::Pointer PointB = Node<3>::Pointer(new Node<3>(2, 0.4, 0.25, 0.35));
            Node<3>::Pointer PointC = Node<3>::Pointer(new Node<3>(3, 0.4, 0.55, 0.3));
            Node<3>::Pointer PointD = Node<3>::Pointer(new Node<3>(4, 0.15, 0.45, 0.45));
            
            auto geom = Quadrilateral3D4<Node<3>>(PointA,PointB,PointC,PointD);

            IntegrationMethod ThisMethod = geom.GetDefaultIntegrationMethod();
            
            Matrix jacobian ( 3, 2 );
            
            geom.Jacobian( jacobian, 0, ThisMethod);
            
            const double detJ = geom.DeterminantOfJacobian(0, ThisMethod);
            
            KRATOS_CHECK_NEAR(detJ, MathUtils<double>::GeneralizedDet(jacobian), TOLERANCE);
}
~~~

![imagen](https://user-images.githubusercontent.com/19991680/27693628-457874c0-5cea-11e7-8687-6daac2b5ad31.png)

Mine works, I test it 50 times

**Comment by rubenzorrilla** [comment]
IMO 50 times is not enough...

**Comment by pooyan-dadvand** [comment]
@loumalouomega seems that your version `f0e92fd0b` is differnt than current master and mine `a79ba8d`

**Comment by pooyan-dadvand** [comment]
I have tested it twice!! 😆

**Comment by loumalouomega** [comment]
My version is the same than the master

**Comment by jcotela** [comment]
The test passes on my machine (on current master, which is `a79ba8d80`) :/ 
(I have tested it more than two times, but less than 50)

**Comment by loumalouomega** [comment]
Ok, the operation of the determinant is quite simple:

~~~
this->Jacobian( jacobian, pnt, ThisMethod);
            
            const double detJ = std::pow(jacobian(0,1),2)*(std::pow(jacobian(1,0),2)+std::pow(jacobian(2,0),2))+std::pow(jacobian(1,1)*jacobian(2,0)-jacobian(1,0)*jacobian(2,1),2)-2*jacobian(0,0)*jacobian(0,1)*(jacobian(1,0)*jacobian(1,1)+jacobian(2,0)*jacobian(2,1))+std::pow(jacobian(0,0),2)*(std::pow(jacobian(1,1),2)+std::pow(jacobian(2,1),2));
            
            rResult[pnt] = std::sqrt(detJ);
~~~

Can you print your jacobian?

**Comment by pooyan-dadvand** [comment]
is there any random there? in my error it returns inf for detJ

**Comment by loumalouomega** [comment]
Nope,I removed the randomness

**Comment by loumalouomega** [comment]
That's why I ask you to print the jacobian, it is the easiest way

**Comment by pooyan-dadvand** [comment]
The Jacobian:

`[3,2]((0.144717,0.0197169),(0.0302831,0.130283),(0.00386751,0.0538675))`

**Comment by loumalouomega** [comment]
The only thing that I can think could be the origin is that I use std::pow a lot and maybe your compiler is not doing his job

**Comment by pooyan-dadvand** [comment]
Have you tested if the Detj is negative or not?

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/27731674-54fd98f4-5d8e-11e7-821c-ad62215328d8.png)

**Comment by pooyan-dadvand** [comment]
It seems to be a memory error. When I'm enabling the outputs  `Tester.Vervosity.TESTS_OUTPUTS`  the test pases but when I set the verbosity to `Tester.Vervosity.TESTS_LISTS` it fails....

**Comment by loumalouomega** [comment]
Ok

**Comment by pooyan-dadvand** [comment]
would you please test it using the list verbosity?

**Comment by loumalouomega** [comment]
OK

**Comment by pooyan-dadvand** [comment]
I'm testing it (more than two times) and it crashes randomly.

**Comment by loumalouomega** [comment]
@pooyan-dadvand,  is it still crashing?

**Comment by pooyan-dadvand** [comment]
Of course! Have you changed something? In which branch?

**Comment by loumalouomega** [comment]
No, just asking, I don't have any problem, just that

**Comment by pooyan-dadvand** [comment]
Have you run it with valgrind?

**Comment by loumalouomega** [comment]
No, I will try

**Comment by pooyan-dadvand** [comment]
@loumalouomega would you please check this with valgrind?

**Comment by loumalouomega** [comment]
OK

**Comment by loumalouomega** [comment]
~~~c
==11568== Conditional jump or move depends on uninitialised value(s)
==11568==    at 0x58D3101: __ieee754_pow_sse2 (e_pow.c:76)
==11568==    by 0x58B57A3: pow (w_pow_compat.c:27)
==11568==    by 0x958E03D: Kratos::Quadrilateral3D4<Kratos::Node<3ul, Kratos::Dof<double> > >::DeterminantOfJacobian(unsigned long, Kratos::GeometryData::IntegrationMethod) const (quadrilateral_3d_4.h:846)
==11568==    by 0xB0A2968: Kratos::Testing::TestQuadrilateralJacobianTest::TestFunction() (test_non_rectangular_jacobian.cpp:106)
~~~

**Comment by loumalouomega** [comment]
I will try to solve it

**Comment by jcotela** [comment]
@loumalouomega Can you try just replacing the pow calls with regular products? We have seen some weird things with pow (probably due to compiler optimization?) in the past.

**Comment by loumalouomega** [comment]
I am doing that, but it takes to compile....
