### ISSUE TITLE
VTK node ids

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#5660]
The vtk format does not have node or element ids. The numbering happens according to the order of appearance in the vtk file and is not related to the ids in Kratos.

I propose a flag for the vtk output process to include node/element ids as an additional data in the result file - similar to the already existing `write_properties_id`.

naming in the output could e.g. be 
`KRATOS_NODE_ID`
`KRATOS_ELEMENT_ID`

@KratosMultiphysics/interface-committee

**Comment by philbucher** [comment]
You and your IDs ... xD

Ok for me, please go ahead

**Comment by adityaghantasala** [comment]
Fine by me. By the way, it need not be an extra flag, it would be nice if it can be done via existing settings.

**Comment by philbucher** [comment]
FYI @stefangrabke

**Comment by armingeiser** [comment]
> Fine by me. By the way, it need not be an extra flag, it would be nice if it can be done via existing settings.

Doing this with the existing settings i see two options:
* change ` "write_properties_id"`  to ` "write_ids"` and write all ids - of nodes, elements, conditions, properties...
* add a variable to the nodes and use `"nodal_solution_step_data_variables"`

Both are a bit clunky IMO

**Comment by philbucher** [comment]
> change ` "write_properties_id"`  to ` "write_ids"` and write all ids - of nodes, elements, conditions, properties...

+1

**Comment by armingeiser** [comment]
FYI @oberbichler
