### ISSUE TITLE
The kinematic element does not apply the density to calculate self weight

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#567]
@KratosMultiphysics/structural-mechanics It seems that applying self weight in GUI to small displacement element (at least in 2D) does not consider the density of the material

**Comment by jginternational** [comment]
To check it using the GUI, you must be using the last version of the [problemtype ](https://github.com/KratosMultiphysics/GiDInterface) (master branch).

Take this as an example.
[selfStruct.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/1112487/selfStruct.gid.zip)

**Comment by loumalouomega** [comment]
I will solve it ASAP
