### ISSUE TITLE
Prescribed velocity of a body in MPM

### ISSUE THREAD

**Issue by Gaoliu19910601** [KratosMultiphysics/Kratos#5671]
Hi everyone
I want to do a simulation of a pile penetration into soil in MPM by Kratos. My problem is how to define the designated velocity of a pile (maybe it should be treated as a rigid body or just a body with a prescribed velocity?) but I do not how to apply a prescribed velocity on a body which has a MohrCoulomb interaction with soil  in MPM application, Does anyone know and can help me? I will be so grateful.

**Comment by philbucher** [comment]
@KratosMultiphysics/mpm

**Comment by Gaoliu19910601** [comment]
@VeronikaSinger Can you help me？

**Comment by Gaoliu19910601** [comment]
@bodhinandach @antonialarese @peterjwilson @tteschemacher

**Comment by bodhinandach** [comment]
answered in https://github.com/KratosMultiphysics/GiDInterface/issues/649
