### ISSUE TITLE
Compling Kratos in Windows10

### ISSUE THREAD

**Issue by Gaoliu19910601** [KratosMultiphysics/Kratos#5709]
Hi everyone 
   When compling Kratos in Windows10 ， what does the sentence “You may also need to copy the python3X.dll library from your python directory” in Post Compilation prpcess ？where should I copy the python3X.dll library to ？

**Comment by AlejandroCornejo** [comment]
Hi! you should copy that library inside the KratosInstall folder that was created after the correct compilation of kratos :)

**Comment by AlejandroCornejo** [comment]
Inside you should have the `runkratos.exe` by the way

**Comment by Gaoliu19910601** [comment]
Hi @AlejandroCornejo 
   Thank you.
