### ISSUE TITLE
Some questions from a beginner

### ISSUE THREAD

**Issue by dayexingyang** [KratosMultiphysics/Kratos#571]
Dear all,
I'm very interested in the PFEM and according to the introduction of Kratos, Kratos can solve the engineering problems with the PFEM. But I didn't find any tutorials about it. I want to figure out if Kratos can solve the problem with PFEM and support the open code of it.  Besides, are there any more detailed tutorials for installion?  The accessories are too many!

**Comment by pooyan-dadvand** [comment]
I would put this in attention of @KratosMultiphysics/pfem and @KratosMultiphysics/pfem2  teams.

**Comment by maceligueta** [comment]
@dayexingyang , hi!
The migration of the PFEM to Kratos is very recent. Right now we are finishing the first usable version of the PFEM, but (as you just saw) there are no tutorials or manuals to use it. 
Could you manage to download the Kratos Interface? If not, take a look at https://github.com/KratosMultiphysics/GiDInterface. When configured appropriately, it will display a number of GUI's that are available. The PFEM is one of them. You can ask directly to us about it, until manuals and tutorials are written. Sorry about the inconvenience.
What do you mean with "the accessories are too many"?
Do not hesitate to contact the members of the team working on PFEM:
@KratosMultiphysics/pfem 
@AFranci 
@josep-m-carbonell 
@pablobecker 
@maceligueta

**Comment by dayexingyang** [comment]
@maceligueta ,thanks for your reply. And sorry for not having made myself clearly. I just installed Kratos and the code configured completely. Due to my research is focused on the FSI, I want to know if the PFEM in the actual Kratos can simulate the fluid-structure interaction problem.

**Comment by maceligueta** [comment]
The PFEM in Kratos is cannot deal with FSI problems yet, though is one of the prioritary goals of the team.
