### ISSUE TITLE
Error in a MPM case

### ISSUE THREAD

**Issue by Gaoliu19910601** [KratosMultiphysics/Kratos#5729]
Hi every one. I am try to simulate a falling process of a object in MPM, the surounding of the object is fixed and the object is only under gravity. However, the error is 
![Screenshot from 2019-10-05 21-19-21](https://user-images.githubusercontent.com/48948507/66255419-d6c76780-e7b5-11e9-9b61-adc3881bff6e.png)
I submit my .gid file in the attachment
[mpm.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/3693262/mpm.gid.zip)
 and can anyone help me?

**Comment by philbucher** [comment]
@KratosMultiphysics/mpm 
@jginternational

**Comment by VeronikaSinger** [comment]
Hi Geoliu19910601,

the node Id's and the coordinates of the nodes are missing in your 'mpm_Grid.mdpa' file.

**Comment by Gaoliu19910601** [comment]
@VeronikaSinger 
Hi could you send me any examlpe that could be run in GID using MPM？ I can not run any case now，maybe just a simple example could be helpful. I will be so grateful.

**Comment by Gaoliu19910601** [comment]
@bodhinandach

**Comment by VeronikaSinger** [comment]
[FallingBall.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/3696288/FallingBall.gid.zip)

**Comment by Gaoliu19910601** [comment]
Hi @VeronikaSinger 
  Thanks a lot . I will take a good look at the example.
