### ISSUE TITLE
Warning in CoupledFluidThermalSolver

### ISSUE THREAD

**Issue by apuigferrat** [KratosMultiphysics/Kratos#5737]
The CoupledFluidThermalSolver does not return the state of convergence from "SolveSolutionStep". What shall we do?

**Comment by rubenzorrilla** [comment]
I'd return `true` if both the fluid and the thermal solver have converged. I'll prepare a PR with the changes.

**Comment by apuigferrat** [comment]
Okay, thank you. When you open the PR, I will close this issue.
