### ISSUE TITLE
[Trilinos][AMGCL] Check if amg works better with SchurPC than subdomain deflation

### ISSUE THREAD

**Issue by ddemidov** [KratosMultiphysics/Kratos#5756]
Opening this to keep the discussion started in #5734 going.

@RiccardoRossi wrote there:

> regarding the possibility of using full_amg instead of deflation i am also in principle ok if you believe it will work. My doubt comes as I seem to remember that we were using a matrix-free method in the solution of the pressure complement so i am not 100% sure it will work correctly with full amg.

We can still do matrix-free approach with amgcl::mpi::make_solver, but this needs testing to see if it works as well (or hopefully better than subdomain deflation). I'll try to run @sunethwarna's example from #5734 and see what happens.

> BTW @sunethwarna is (i think) solving a stiff problem in terms of two turbulence-related variables. Maybe the CPR preconditioner would work good in that context

I think I can test that as well if I save the system matrix from the test. But I'll need some info about the system to do that. How many dofs per node it has? Which dof is the pressure?

**Comment by sunethwarna** [comment]
Hi @ddemidov ,
This is the geometry of the test problem in #5734. Its a 3D fluid flow problem solved with following properties.

- Each node has 4 dofs. (dof-1 Velocity_x, dof-2 Velocity_y, dof-3 Velocity_z, dof-4 Pressure)
- VMS Monolithic formulation is used
- Transient simulation
- Fixed velocity inlet
- Zero pressure outlet
- No slip walls

![image](https://user-images.githubusercontent.com/7856520/66544745-41bbca00-eb39-11e9-901b-c060bc0944f8.png)
Please let me know if you need more information :)
Thank you :)

**Comment by ddemidov** [comment]
e5a3edb replaces subdomain deflation with amg in `applications/TrilinosApplication/external_includes/amgcl_mpi_schur_complement_solver.h`.

I am attaching logs for @sunethwarna's test problem from #5734 (ran with `mpirun -n 4 python MainKratos.py`).

* [sdd.log](https://github.com/KratosMultiphysics/Kratos/files/3711960/sdd.log)  - before the change
* [amg.log](https://github.com/KratosMultiphysics/Kratos/files/3711959/amg.log)  - after the change

Looks like the amg version makes consistently less iterations than the sdd one. Here is the start of diff between the two logs:

```diff
diff sdd.log amg.log 
51,52c51,52
< Iterations      : 8
< Error           : 8.14279e-10
---
> Iterations      : 5
> Error           : 5.71663e-10
56,57c56,57
< Iterations      : 32
< Error           : 9.21538e-09
---
> Iterations      : 26
> Error           : 7.10296e-09
61,62c61,62
< Iterations      : 48
< Error           : 6.72584e-09
---
> Iterations      : 31
> Error           : 8.49304e-09
66,67c66,67
< Iterations      : 41
< Error           : 7.18648e-09
---
> Iterations      : 32
> Error           : 9.63844e-09
71,72c71,72
< Iterations      : 39
< Error           : 9.48183e-09
---
> Iterations      : 32
> Error           : 9.03673e-09
78,79c78,79
< Iterations      : 39
< Error           : 6.2227e-09
---
> Iterations      : 31
> Error           : 6.17777e-09
83,84c83,84
< Iterations      : 37
< Error           : 5.53618e-09
---
```

**Comment by RiccardoRossi** [comment]
cool!
