### ISSUE TITLE
Centrifugal body force & periodic BCs

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#577]
Hi all,

given a rotationally symmetric part, like a blade from an engine turbine. This part is supposed to be modeled as linear elastic, isotropic solid, analyzed and optimized using Kratos. In this context, is it already possible to apply a centrifugal body force, coming from the rotation of the turbine or some periodic boundary condition, so that the analysis of one blade is sufficient?

Any suggestions, also with respect to a possibly necessary implementation is appreciated.

Best regards,
Daniel

**Comment by jcotela** [comment]
Hi Daniel,
Regarding the body force, the fluid elements (the vms and/or the fractional step) read the `BODY_FORCE` variable. You would need to prepare a function to set the body force to the correct vector at each node and update it at every iteration/time step as needed. You can do this as a process or, as a first test, just set it straight away in Python before calling fluid_solver.Solve(). Note that `BODY_FORCE` is multiplied internally by the density, so it should be understood in terms of force per unit mass.

Regarding periodic conditions, the current approach only allows for matching grids and maintaining the direction of the forces (so you cannot model 1/4 of a circular domain, for example), but @adityaghantasala was working in multi-point constraint conditions which should allow you to realize more complex periodicity conditions.

**Comment by adityaghantasala** [comment]
Hi @dbaumgaertner and @jcotela 

Periodic boundary conditions when the two boundaries are parallel (without constraint on matching mesh) should be ready in a couple of days. But more complex ones are still some time away.

**Comment by dbaumgaertner** [comment]
Thanks both for the answer! That helps already. 

Just to make it clear. I am talking about a pure CSM simulation. No CFD is involved here. But from your explanations, I already got an idea what to do.

**Comment by jcotela** [comment]
Ok, the force thing should be the same for the structural elements, but they use the `VOLUME_ACCELERATION` variable.
