### ISSUE TITLE
Variable component and Variable  same or different ??

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#578]
Hello all

I have a more programming question. 
I want to pass a variable like PRESSURE and a variable component like DISPLACEMENT_X into a function. Is there a way other than overloading the function with 
`Variable<double>&` and `Kratos::VariableComponent<Kratos::VectorComponentAdaptor<Kratos::array_1d<double, 3>>> & ` ??

**Comment by pooyan-dadvand** [comment]
They should be virtual? If they don't need to be virtual having the template method is the easiest as two classes share the interface. 
In case that the methods should be virtual, what I do usually is to have a template method (private) which implements the function and then two overloaded virtual functions (public) with varabile and component arguments.

**Comment by adityaghantasala** [comment]
Hi Pooyan 

Yes they are virtual, I will follow your suggestion with private function and overloading the public virtual method. 

By the way is it not possible to make them derive from a parent class and unify how we pass around variable and variable component ??

**Comment by pooyan-dadvand** [comment]
It depends to the use case, whould you please explain the case more in detail?

**Comment by adityaghantasala** [comment]
Hello Again Pooyan 
Nothing special, I have a process which can work identically with Variable and VariableComponent. 
I see that there can be derivatives of this process in future. For example the apply constraint process for MPC. This can be different for fluid applications, periodic BC and structural application. So I want to make some functions virtual so that derived processes also have these functions. So I asked.

**Comment by pooyan-dadvand** [comment]
If the implementation is in the base class and you won't overload it, then the template in the base class is enough.

if you want to change the implementation in the derived class, then you should pass it as template argument to the base class. (It is combersome and less recomendable)
