### ISSUE TITLE
[Core][Clean Up] Are the following folder necesaries?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#5806]
https://github.com/KratosMultiphysics/Kratos/tree/master/packaging_aux 

https://github.com/KratosMultiphysics/Kratos/tree/master/problemtype_generator

Last update of both folders was 6 years ago

**Comment by philbucher** [comment]
Looks old ...

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi and @roigcarlo for pacakging_aux
@jcotela for problemtype generator

**Comment by roigcarlo** [comment]
TO my understanding `packaging_aux` is no longer used. At least I've never use it while making a package...

**Comment by jcotela** [comment]
I haven't used the problemtype generator in ages but, as far as I know, the last active users were @ipouplana (for his phd research and maybe the dam stuff?) and @antonialarese (for the free surface problemtype). If they no longer need it, I am in favor of removing it. I do not even know if it will still work with GiD 14 :confused:

**Comment by ipouplana** [comment]
I think I never used this ^_^'...

**Comment by jcotela** [comment]
@ipouplana I think you are right... I got confused because the periodic problemtype I sent you once was based on this.
