### ISSUE TITLE
Condition::Check does not throw an error for colapsed (zero area) triangles

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#583]
In PR #582 I found out that Condition::Check only verifies that the element size is not negative, but happily accepts zero size geometries. I understand this was done so that point conditions do not fail the check, however this also means that degenerate geometries (e.g. a triangle with the three points on a line) will pass the test too, which is not very useful.

Can we think of a more comprehensive way of checking for validity in Condition::Check? I can think of different alternatives, but none of them is perfect:
- We leave things as they are: we catch inverted geomteries but not degenerate ones.
- We force a check for area <= 0, but make it clear that derived classes are not forced to also call the base class checks (so that point conditions use a completely different check method, implemented by their developer).
- We check for area <= 0, but exclude point conditions from this check (for example, by also checking geometry type and/or number of points). This does not cover all cases (I can think of using zero-length lines to describe contact-type conditions, for example), but should work in most common situations.

Mentioning @KratosMultiphysics/structural-mechanics, since most point conditions are on the structural side.

**Comment by pooyan-dadvand** [comment]
It seems that the less harmful one is to add a Check method to point conditions which is not calling the base class one. A cleaner option would be to have a IsDegenerated method in geometry which gives the correct answer for given type of geometry. (note that sometimes it is even more efficient to see if is degenerated than the volume.

**Comment by loumalouomega** [comment]
@pooyan-dadvand Indeed I implemented a HeronCheck in my ContactStructuralMechanics application for that pourpose, basically what I check is:

~~~c++
    static inline bool HeronCheck(        
        const PointType PointOrig1,
        const PointType PointOrig2,
        const PointType PointOrig3
        )
    {
        const double a = MathUtils<double>::Norm3(PointOrig1.Coordinates()-PointOrig2.Coordinates());
        const double b = MathUtils<double>::Norm3(PointOrig2.Coordinates()-PointOrig3.Coordinates());
        const double c = MathUtils<double>::Norm3(PointOrig3.Coordinates()-PointOrig1.Coordinates());
      
        const double s = 0.5 * (a + b + c);
        const double A2 = s * (s - a) * (s - b) * (s - c);
        
        return (A2 <= 0.0 ? true : false);  // We consider as bad shaped the ones with no area or negative A2 (semiperimeter smaller than any side)
    }
~~~

**Comment by pooyan-dadvand** [comment]
But the question is not how to check the degenerated tetrahedral elements, the question is how to extend the same test to line conditions where a valid geometry has area = 0.

**Comment by jcotela** [comment]
We were discussing today to add a Check method to geometries, so that, for example, the triangle can throw an error if it has area 0 but the point does not check that. Then, elements/conditions could just call this instead of implementing their own geometrical checks.

**Comment by pooyan-dadvand** [comment]
This would be a good idea. Meanwhile I think that the checks there should be minimal and consider the wide variety of the geometry usage.

**Comment by loumalouomega** [comment]
@jcotela  I agree with you, because in case we implement in the base class something that bothers me if the condition is just one node the area will be zero anyway and will always throw the error

**Comment by pooyan-dadvand** [comment]
I have added this to global plan to be prioritized in committee

**Comment by loumalouomega** [comment]
I think we can close this issue

**Comment by jcotela** [comment]
@loumalouomega we still haven't implemented the Check method for Geometries.

**Comment by loumalouomega** [comment]
Sorry I thought that was solved
