### ISSUE TITLE
Warnings in tests StructuralMechanics

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#5845]
@KratosMultiphysics/structural-mechanics we currently have any warnings in our tests.

Especially the ones of the deprecated access to the Model have to be fixed until end of November. It is very easy to do:
~~~
DEPRECATION_WARNING: The ModelPart "Parts_Parts_Auto1"
is retrieved from the Model by using the flat-map!
This will be removed end of November 2019
Please prepend the Parent-ModelPart-Names like this:
"Structure.Parts_Parts_Auto1"
~~~

@loumalouomega could you please take a look at the warning abt the domain size in the Bossak-Scheme:
~~~
ResidualBasedBossakDisplacementScheme: DOMAIN_SIZE not defined. Please define DOMAIN_SIZE. 3D case will be assumed
~~~

There are many of them but I am quite sure they are coming from few places

**Comment by philbucher** [comment]
I forgot, please also to remove the settings `problem_domain_sub_model_part_list` and `processes_sub_model_part_list`
Without those settings, the entire ModelPart is used in the Simulation, which is going to be the case after the transition period

**Comment by loumalouomega** [comment]
For some reason the verbosity is like Info, instead of warning in addition to the changes needed

**Comment by philbucher** [comment]
closing since solved IMO
thanks for the help
