### ISSUE TITLE
Improve Warning for overriding properties

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#5851]
```ReadMaterialsUtility: WARNING:: The properties ID: 0 in mesh ID: 0 is already defined. This will overwrite the existing values```

This warning should only be printed if there are already properties defined!

**Comment by loumalouomega** [comment]
It is. show me an example that does not work

**Comment by armingeiser** [comment]
OK i need to check again, but next week.

**Comment by armingeiser** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/2a0066e37a64cb391b08029a040f5879f731365d/kratos/utilities/read_materials_utility.cpp#L123

```
"WARNING:: The properties ID: 0 in mesh ID: 0 is already defined. This will overwrite the existing values" 
```
This warning is written, if the property is already existing, even if it has no values assigned yet. E.g. if the property in the mdpa is empty. In that case nothing will be overwritten and this warning is obsolete. 

Only if there are values inside the property, the warning is necessary IMO. This happens here and here:

https://github.com/KratosMultiphysics/Kratos/blob/2a0066e37a64cb391b08029a040f5879f731365d/kratos/utilities/read_materials_utility.cpp#L143

https://github.com/KratosMultiphysics/Kratos/blob/2a0066e37a64cb391b08029a040f5879f731365d/kratos/utilities/read_materials_utility.cpp#L25
