### ISSUE TITLE
[PFEM Fluid] Calculation runs but not printing results

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#5868]
Pfem fluid application in windows.

The calculation output info seem to be correct but no results or mesh is written
Result files are created but empty

![image](https://user-images.githubusercontent.com/5918085/67845645-1efd4f80-fb00-11e9-9944-c3ce0355115c.png)

**Comment by AlejandroCornejo** [comment]
AAAh! I know that... I created an issue some time ago about this. It seems that in Windows, if you have two instances of GiD it does not work properly

**Comment by AlejandroCornejo** [comment]
you can check it by changing the PfemGiD with the standard GiD output and it works fine

**Comment by philbucher** [comment]
@jginternational can you try with #5653?

**Comment by jginternational** [comment]
@AlejandroCornejo What do you mean with "2 instances of GiD" ? GiDPost to write results or GiD the Gui?

**Comment by philbucher** [comment]
@jginternational I think #5653 and #4337 explain the problem and the proposed solution

**Comment by jginternational** [comment]
So @philbucher  I understand that the GiDIO class should be some kind of Singleton. I'll try something with that PR this afternoon

**Comment by maceligueta** [comment]
More related to #3637, I suspect.

**Comment by AlejandroCornejo** [comment]
> 
> More related to #3637, I suspect.
> […](#)
> El 30 oct 2019, a las 12:11, Javi Gárate ***@***.***> escribió: ﻿ So @philbucher I understand that the GiDIO class should be some kind of Singleton. I'll try something with that PR this afternoon — You are receiving this because you were assigned. Reply to this email directly, view it on GitHub, or unsubscribe.

I think that is someting related to what @maceligueta says

**Comment by AlejandroCornejo** [comment]
@jginternational If you modify the file `applications\PfemFluidDynamicsApplication\python_scripts\pfem_fluid_gid_output_process.py` as: `self.body_io = GidIO(` the postprocess works :)

**Comment by jginternational** [comment]
@AlejandroCornejo  I've tested by changing that file into:
```
        if self.body_output or self.node_output:
            self.body_io = GidIO( self.volume_file_name,
                                    self.post_mode,
                                    self.multifile_flag,
                                    self.write_deformed_mesh,
                                    self.write_conditions)

        if self.skin_output or self.num_planes > 0:
            self.cut_io = GidIO(self.cut_file_name,
                                self.post_mode,
                                self.multifile_flag,
                                self.write_deformed_mesh,
                                WriteConditionsFlag.WriteConditionsOnly) # Cuts are conditions, so we always print conditions in the cut ModelPart
```

And it works in Windows

![a](https://user-images.githubusercontent.com/5918085/68417035-e9a6d080-0195-11ea-8d7a-c3a81ac08a89.gif)


So, we need to think about this solution for the release (Since it's the only one working both in windows and linux (Hope on mac also))

**Comment by philbucher** [comment]
@jginternational have you tried with #5653?
If this works then we could push for it to be merged soon in order to be included in the release

**Comment by maceligueta** [comment]
We did an override of GiDIO because it was not sufficient for the interest of PFEM post-process, I don't remember the exact reasons and I don't have time to check them today, but I will do on monday. @AFranci requested the changes, so he should remember as well.

**Comment by maceligueta** [comment]
@AFranci just told me that the flying nodes are not in a separate layer. The PFEM GidIO puts them in a separate layer, so they can be turned off.

**Comment by AFranci** [comment]
Hi all,
First of all, thank all of you for working on this!
Those changes were done to allow the visualization of the PFEM 'flying' nodes. These nodes were put in a different group to differentiate them from the rest of the (inner) nodes. I attach two videos to make it more clear:
GidIO +  with nodes plotted
![WithNodes](https://user-images.githubusercontent.com/25818902/68467916-57471100-0217-11ea-8d79-1523d331690c.gif)
GidIO +  without nodes
![WithoutNodes](https://user-images.githubusercontent.com/25818902/68467924-5b732e80-0217-11ea-9ec6-0f7362e6dd60.gif)
PFEMGidIO + flying nodes
![PFEMgidIO](https://user-images.githubusercontent.com/25818902/68468458-5e225380-0218-11ea-94fd-d9d781d7fa96.gif)
So, it is clear that the PFEMgidIO allows a better post-process, however, being this change not so crucial and while we don't find a solution for the windows problem, I think we should use the core GiDIO for this release version.

**Comment by jginternational** [comment]
@philbucher I've tested the branch you pointed by merging master into that one,  leaving the 'pfem_fluid_gid_output_process.py' script as it was originally and it did not compile for windows. I had to remove the KRATOS_API from the GidIO class
``` c++
class KRATOS_API(KRATOS_CORE) GiDIOBase : public IO {

    protected:
    static int msLiveInstances;
};

template<class TGaussPointContainer = GidGaussPointsContainer, class TMeshContainer = GidMeshContainer>
class GidIO : public GiDIOBase

```

After removing the KratosAPI, it compiled, but the output was still empty:
![image](https://user-images.githubusercontent.com/5918085/68483884-99cf1480-023c-11ea-9b10-757ad183a20b.png)

**Comment by jginternational** [comment]
OK!

![image](https://user-images.githubusercontent.com/5918085/68599736-65a85d80-04a1-11ea-870f-15e9db4340af.png)


With this branch it's now working.
KratosMultiphysics/Kratos#5653

Ready to merge @maceligueta
