### ISSUE TITLE
[MappingApplication] Non historical variables issue

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/Kratos#5885]
Dear all,

I am currently using he MappingApplication to Map one non historical variable to a non historical variable. Following the wiki tutorial, there is no mention regarding historical/non-historical variables, but the projection result I was getting was 0.0 in all the nodes of interest, after the projection. On the other hand, the Mapping is working fine with historical variables.

To solve the issue, I added TO_NON_HISTORICAL and FROM_NON_HISTORICAL flags to both my Map function and to the `add_custom_mapper_to_python.cpp`, but I am not sure this is the correct way of handling non historical variables.

Do you have any comment or suggestion @philbucher ?

I attach a small example, in which if you comment the current Map and use the commented Map, you see that we get 0.0 as values.
[mapping_non_historical.zip](https://github.com/KratosMultiphysics/Kratos/files/3808319/mapping_non_historical.zip)

The proposed solution, that seems working from the small test I did, is just to add these lines to [add_custom_mapping_to_python](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MappingApplication/custom_python/add_custom_mappers_to_python.cpp#L148):
`// Adding the flags that can be used for mapping
    mapper.attr("SWAP_SIGN")           = MapperFlags::SWAP_SIGN;
    mapper.attr("ADD_VALUES")          = MapperFlags::ADD_VALUES;
    mapper.attr("REMESHED")            = MapperFlags::REMESHED;
    mapper.attr("USE_TRANSPOSE")       = MapperFlags::USE_TRANSPOSE;
    mapper.attr("TO_NON_HISTORICAL")   = MapperFlags::TO_NON_HISTORICAL;
    mapper.attr("FROM_NON_HISTORICAL") = MapperFlags::FROM_NON_HISTORICAL;`

**Comment by philbucher** [comment]
Hi @riccardotosi 
You are right, your solution should work for now. If you want you could push it to master.

I haven’t finalized this feature yet because at the time I started it I was not fully clear about the details. 

I will try to finish it soon and add some documentation if you are using it
