### ISSUE TITLE
Implementation committee: thoughts and suggestions after one year

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#5889]
After all these months being involved with the @KratosMultiphysics/implementation-committee work we have reached the following conclusions:

1. Our activity is positive and useful, beacuse it creates a discipline and a habit in looking at the problems and suggestions that arise in Kratos in a systematic way.

1. We think we could be even more productive if we could solve some of the issues without having to pass them on to the @KratosMultiphysics/technical-committee for review every time, since this inevitably creates a huge bottleneck.

1. We have thought of a new way in which to become even more productive in helping the @KratosMultiphysics/technical-committee get more work done faster. It consists in adding the tag Implementation Committee Final Desicion by a member of the @KratosMultiphysics/technical-committee, which would give us the power to close issues and accept PRs of lesser relevance to other committees. 

It would be nice to hear your thoughts and comments.

**Comment by loumalouomega** [comment]
Additionally I cannot attend anymore the meetings after I started my new
job.

**Comment by pooyan-dadvand** [comment]
Thanks for the thoughts and I 100% agree that technical committee approval is a bottleneck that we should remove. 

I could not understand what is the suggestion in point 3. Would you please elaborate a little bit more?

**Comment by GuillermoCasas** [comment]
> 
> 
> Thanks for the thoughts and I 100% agree that technical committee approval is a bottleneck that we should remove.
> 
> I could not understand what is the suggestion in point 3. Would you please elaborate a little bit more?

The third suggestion is the use by the @KratosMultiphysics/technical-committee of a special tag that signals the fact that the decision on a specific matter is relegated to the @KratosMultiphysics/implementation-committee . This means that the matter can be removed from the @KratosMultiphysics/technical-committee 's to-do list by transferring the decision power to the @KratosMultiphysics/implementation-committee for the specific issue that is being tagged.

**Comment by pooyan-dadvand** [comment]
Now I see! To be discussed in @KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee likes the suggestion
Regarding to the proposal, we see 3 levels of issues:
1. The **full implementation decision** ones for simple and small tasks that can be decided and implemented without the technical committee confirmation.
2. The **partial technical decision** ones that can be decided by the implementation committee and approved with only one member of technical committee (sometimes designated one, sometimes any of them)
3. The normal one as before.

Technical committee will give those labels to the incoming issues.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/implementation-committee do you agree with this procedure?

**Comment by loumalouomega** [comment]
I would like to highlight that we should look for a replacement for me

**Comment by GuillermoCasas** [comment]
> @KratosMultiphysics/implementation-committee do you agree with this procedure?

We will discuss it next week, but I personally agree.

**Comment by AlejandroCornejo** [comment]
Hello! I think in the same way as @GuillermoCasas, anyway we will post our discussed opinion. Thank you

**Comment by adityaghantasala** [comment]
On behalf of @KratosMultiphysics/implementation-committee  we agree with the propoal of @KratosMultiphysics/technical-committee . 

We will pay attention to the labels and will act accordingly as suggested.

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee we should proceed with this to accelerate the decisions.
