### ISSUE TITLE
load conditiins are always compited on deformed configuration

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#5890]
this is a problem if you use small deformation elements, since the load depends on the deformed shape

**Comment by loumalouomega** [comment]
I assume we should separate then the loads in small TL and UL.

**Comment by RiccardoRossi** [comment]
i think it would be enough to a a small deformation version, which is
identical except that all integrals are computed on X0 instead X.
TL and UL are identical

**Comment by loumalouomega** [comment]
In theory TL should be integrated in X0?

**Comment by RiccardoRossi** [comment]
no, you are not technically right. In the Total Lagrangian case, the integration is done indeed over the configuration X0 **BUT** the integrand is modified so that the result is identical as if the integration was performed on the deformed configuration. 
In this sense for a given mesh the matrices resulting of the TL and UL formulations (and in particular the ones of the loads) are **exactly** identical. You can verify this on the book of Belytscko for example.

to get convinced "visually" just take a look at the normal to the face employed in the TL configuration. You will quickly verify that it is not the normal in the underformed configuration.

On the contrary for the small strain case the integration is doen exactly as now, BUT, with all the integrals and geometrical quantities computed in the undeformed configuration

**Comment by philbucher** [comment]
Wouldn’t it be sufficient in the small deformation case to NOT move the mesh?

**Comment by RiccardoRossi** [comment]
@philbucher the answer is yes, nevertheless when we wrote the small deformation elements we explicitly considered that the elements should deliver correct results also if MoveMesh=True.
This is accomplished at the element level by always using X0 in all of the calculations

**Comment by RiccardoRossi** [comment]
my point here is that you may well mix large displacement elements and small displacement elements in a same analysis and still expect the analysis to work.

**Comment by philbucher** [comment]
That makes sense to me

**Comment by loumalouomega** [comment]
Yes I know, in fact there is a test that I did to check that the UL and TL
return identical results. My point was about integration.
