### ISSUE TITLE
Problems with VMS at low viscosity

### ISSUE THREAD

**Issue by juliobarna** [KratosMultiphysics/Kratos#5892]
[comentarios.pdf](https://github.com/KratosMultiphysics/Kratos/files/3819777/comentarios.pdf)
@jcotela @rubenzorrilla @playpaolo

**Comment by juliobarna** [comment]
@RiccardoRossi

**Comment by RiccardoRossi** [comment]
Dear Julio,

to be honest i don't understand what we should see here...

How are u including the object into the calculations? is it a dirichlet condition? 
In any case i would NOT fix the pressure in this context.

**Comment by playpaolo** [comment]
Dear Riccardo, 

the thing is that something wrong happens for low viscosity (please do not consider that pressure is fixed, as the problem appears even if its not fixed). 

I tried it in a non-Lagrangian setting (using ALE with no re-meshing and Eulerian) for the same example (dambreak) and saw the same weird velocity distribution at low viscosity (see snapshot).
![Captura de pantalla de 2019-11-08 16-00-50](https://user-images.githubusercontent.com/25840656/68486360-35628400-0241-11ea-8e6c-4825ce7c8f4c.png)

**Comment by RiccardoRossi** [comment]
maybe the nonlinearity is not converging enough. or maybe (if it is no
slip) than that is the only way to impose the divergence constraint.

aren t you getting a vortex in the velocity or smthg of the sort?

**Comment by philbucher** [comment]
closing since inactive, please reopen if you still need it
