### ISSUE TITLE
Kratos intallation isssue in windows,  default build folders not found

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#59]
We are intalling Kratos in windows, and the default location of the build has changed, also the location for the embedded_python  exe file and we can not locate were the new libs and KratosMultiphysics folders are installed.
Please could you give us a solution for a correct install.

Thank you

**Comment by roigcarlo** [comment]
@josep-m-carbonell As far as I know default locations have not been changed at all. 

I corrected some possible sources of error which appeared when migrating the wiki here, mainly html code that is not supported here.

Could you give me some more info about the problem, is it not compiling? is compiling but the files are not being installed? Maybe you could copy the configure somewhere so I can take a look if its possible?

Thx.

**Comment by josep-m-carbonell** [comment]
It is compiling, the embedded python appears in a folder inside of the cmake-build/embedded_python/Release/runkratos.exe, libs folder is missing as well as KratosMultiphysics folder. If we run with this runkratos, python35.dll is missing, if we add it, then KratosMultiphysics is missing.... The configure file is the one is supplied as example in the instructions changing the custom folder directions.

**Comment by josep-m-carbonell** [comment]
I have checked the install, I think that the reason is that the build was done without clicking in the INSTALL of the project.

**Comment by roigcarlo** [comment]
Thanks, based on what you told me, there are two possible causes:
* **INSTALL project is not being triggered**: 
If you compiled using `ALL_BUILD` instead of `INSTALL` files are not copied where they use to be

* **INSTALL project fails**: 
If you are compiling using `INSTALL` it may be failing

**Comment by roigcarlo** [comment]
Ok just read your last reply. So that was the issue.

**Comment by josep-m-carbonell** [comment]
Thank you very much, I change the title of the issue to match with the real problem/mistake
