### ISSUE TITLE
[Question] In the solve methods of the linear solver rA and rb should be constant?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#5900]
https://github.com/KratosMultiphysics/Kratos/blob/fc43b5bb469dc5cf4b2c8b912d9b41af7cfb4171/kratos/linear_solvers/linear_solver.h#L183

For the sake of consistency I think that methods that are supposed to just solve the system (and therefore not modify the input) should accept constant values for rA and rb

**Comment by RiccardoRossi** [comment]
the scaling solver is modifying A as an example

**Comment by philbucher** [comment]
Also I think it could be a problem if we use an ext library that does not correctly use const

**Comment by loumalouomega** [comment]
Clear, I just wondered
