### ISSUE TITLE
CalculateConstitutiveVariables in kinematic_linear elements includes call to constitutive law

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#591]
CalculateConstitutiveVariables in kinematic_linear includes call to constitutive law
    
```
    void KinematicLinear::CalculateConstitutiveVariables(...)
    { /* code */       
        // Actually do the computations in the ConstitutiveLaw    
        **mConstitutiveLawVector[PointNumber]->CalculateMaterialResponsePK2(rValues)**; //here the calculations are actually done 
    }
```

This leads to duplicated work when used in other functions, e.g. CalculateOnIntegrationPoints:
```
/* code */
for ( unsigned int point_number = 0; point_number < integration_points.size(); point_number++ )
{
   CalculateKinematicVariables(this_kinematic_variables, point_number, integration_points);
    CalculateConstitutiveVariables(this_kinematic_variables, this_constitutive_variables, Values, point_number, integration_points, displacements);
    if( rVariable == CAUCHY_STRESS_VECTOR)
    {
       mConstitutiveLawVector[point_number]->CalculateMaterialResponseCauchy(Values);
    }
    else
/* code */
```

**Comment by loumalouomega** [comment]
Agree, but the thing is that the element can use a different stress meassure from the one you are using

**Comment by loumalouomega** [comment]
I am writing the UL element, and I added some additional variables to the constitutive values, one of them is the StressMeasure. We can check if the stress measure corresponds with the one already calculated and avoid this recalculation

**Comment by loumalouomega** [comment]
Or we can just add as an input of the constitutive calculus the stress measure used

**Comment by loumalouomega** [comment]
@marandra Tell me what do you consider more consistent and I will add it

**Comment by loumalouomega** [comment]
Done, I did the second option, I think it is the simplest one

**Comment by loumalouomega** [comment]
I will do today (I hope) a PR for the UL element, this one will include this change

**Comment by marandra** [comment]
That was fast! I agree, adding the stress measure as a parameter may be cleaner.
Thanks @loumalouomega !

**Comment by RiccardoRossi** [comment]
@marandra  please don't forget closing the issue :-)

**Comment by loumalouomega** [comment]
I will close this, the issue was solved
