### ISSUE TITLE
Non-Newtonian Example

### ISSUE THREAD

**Issue by soudah** [KratosMultiphysics/Kratos#5935]
Hi, 
I am using the fluid-dynamics application, and I would like to run a non-newtonian fluid.  Somebody has an example (.json) how to set a non-newtonian fluid?
Thanks,
Edu

**Comment by philbucher** [comment]
@KratosMultiphysics/fluid-dynamics

**Comment by rubenzorrilla** [comment]
Should be as easy as replace the `Newtonian3DLaw` in the FluidMaterials.json by the non-newtonian law you want to use. Note that you also need to run your problem with an element that uses the constitutive law.

**Comment by soudah** [comment]
Hi,

I have created a GID-Branch call "soudah-modifications-on-fluids" (sorry for the name) in order to use non-newtonian fluids.

In this brach, the user can choose different constitutive fluid laws (Bingham and Herschel-Bulkley).  
Also I changed (as Rubén said) the element:  vms --> qswms.

Now, just playing with the parameters!!! :-)

Thanks Philipp and Rubén!!

**Comment by rubenzorrilla** [comment]
Cool! Then I'd close this issue to open a new one in the GID interface repository. Now the open question is if the `qsvms` element replaces the "reference" element `vms` when creating a monolithic problem in the GUI. 

This change would imply that the use of the constitutive law in the fluid elements becomes mandatory. However it opens the possibility of easily setting non-newtonian fluid problems. @jcotela @RiccardoRossi @KratosMultiphysics/fluid-dynamics

**Comment by rubenzorrilla** [comment]
Closing this one to follow the discussion in [https://github.com/KratosMultiphysics/GiDInterface/pull/675](the GiD interface repo).
