### ISSUE TITLE
Kratos by Python code

### ISSUE THREAD

**Issue by Ali-RAFIEE** [KratosMultiphysics/Kratos#5942]
Hi every one,
As a new user of Kratos, I look for a simple example for do a model by using directly python interface without using Gid.
In fact I search an explanatory example in which I can have the input geometry for example via stl format files or similar ways, and I can adjust other parameters including material characteristics, contact conditions and boundary conditions all inside python code. I would like also to have output result files in vtk format with python code.
Already I want to know all these are possible?

Thanks a lot
Ali

**Comment by philbucher** [comment]
#5966
