### ISSUE TITLE
[MappingApplication] Is it possible to map variables of two modelparts with different types of elements?

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#5945]
Hi,

I am opening this issue since I would like to use the MappingApplication to project values from a 2-D triangular mesh, to a 2-D linear mesh (map the values on the nodes of the triangles to the nodes of the lines). 

So far I have been using a custom process, but before opening a PR to merge it I would like to see if I can use what is already there in the MappingApplication. The function I am using is this one (not in the master):
https://github.com/KratosMultiphysics/Kratos/blob/cps/adding-embedded-adjoint/applications/CompressiblePotentialFlowApplication/custom_processes/project_sensitivity_to_skin_process.cpp
This projects the NORMAL_SENSITIVITY values on a triangular mesh to a 2-d linear mesh. This process direclty multiplies these scalar values to the normals of the skin, to finally write the SHAPE_SENSITIVITY on the skin. Here are some pictures to clarify:
![image](https://user-images.githubusercontent.com/32136457/69067587-99483200-0a23-11ea-9c8b-5731743a75d0.png)
These are the scalar values (on a triangular mesh), which are projected to the skin (on a linear mesh, directly computed as vectors using the skin normal).
![image](https://user-images.githubusercontent.com/32136457/69068463-1a53f900-0a25-11ea-9b9e-1b8c3ff5d34c.png)

I have tried using the MappingApplication with `nearest_element_mapper`  and I get the following error:

running:
```
mapping_parameters = KratosMultiphysics.Parameters("""{
	"mapper_type": "nearest_element",
	"interface_submodel_part_origin": "Parts_Parts_Auto1",
	"echo_level" : 4
	}""")
mapper = KratosMultiphysics.MappingApplication.MapperFactory.CreateMapper(model_part,skin_model_part,mapping_parameters)
mapper.Map(KratosMultiphysics.NORMAL_SENSITIVITY,KratosMultiphysics.NORMAL_SENSITIVITY)
```

```
RuntimeError: Error: Remember the normal can be computed just in geometries with a local dimension: 2smaller than the spatial dimension: 2

in kratos/geometries/geometry.h:982:array_1d<double, 3> Geometry<TPointType>::Normal(const CoordinatesArrayType&) const [with TPointType = Node<3>; Geometry<TPointType>::CoordinatesArrayType = array_1d<double, 3>]
```
Which makes me think that maybe the triangle-line combination is not supported?

Using the `nearest_neighbor_mapper ` works, but as you know it does not interpolate the values. 

Is it possible to do this operation in the MappingApplication or should I stick with the custom process?

Thanks!

**Comment by philbucher** [comment]
in principle what you want to do is supported.
The problem is that the nearest-element needs normals to do the projection, but the 2D triangle has not implemented the computation of the normals
Actually I think this should not be difficult, could you add it and see if it works?
Or am I overseeing sth?

**Comment by marcnunezc** [comment]
What normal is it expecting though?

I see it clear in the case of line_2d_2 or triangle_3d_3, but what about the triangle_2d_3? Normal with respect to what?

Same issue happens with tetrahedra_3d_4 right?

**Comment by philbucher** [comment]
it computes the normal in the `Geometry` => normal wrt to its

> Same issue happens with tetrahedra_3d_4 right?

no there the "projection" works different, I don't have to project onto a plane, I can just calculate the SF-Values since I am already in the volume

**Comment by marcnunezc** [comment]
With the changes in #5971 this works!

**Comment by philbucher** [comment]
just saw this now :)
