### ISSUE TITLE
[GiDOutput] Possible bug when writing prism

### ISSUE THREAD

**Issue by vgudzulic** [KratosMultiphysics/Kratos#5947]
Hi,

I believe that there is a bug in function WriteGaussPoints(GiD_FILE MeshFile) in gid_gauss_point_container.h

Namely, I am making some zero-thickness interface elements using prism geometry. When I want to print the normals in GiD, I obtain the following result: 

![wrong_gp_positions](https://user-images.githubusercontent.com/21369389/69081095-98bc9500-0a3d-11ea-8f9b-1cd097673744.png)

As can be seen, the arrows are strangely grouped, and sometimes even outside of elements.

I have identified that the problem lies in the function WriteGaussPoints(GiD_FILE MeshFile) in gid_gauss_point_container.h. Here, the WriteGaussPoints(....) is called when writing output file, and it seems that the coordinates are wrong (at least they are not consistent with what is used for integration)

**Problematic code:**
```

else if ( mGidElementFamily == GiD_Prism  && mSize > 1)
        {
            GiD_fBeginGaussPoint( MeshFile, mGPTitle, GiD_Prism, NULL, 6, 0, 0 );

            GiD_fWriteGaussPoint3D( MeshFile, 1.00 / 3.00 , 2.00 / 3.00, 0.5 * (1.0 - std::sqrt(1.00 / 3.00)));
            GiD_fWriteGaussPoint3D( MeshFile, 2.00 / 3.00 , 1.00 / 3.00, 0.5 * (1.0 - std::sqrt(1.00 / 3.00)));
            GiD_fWriteGaussPoint3D( MeshFile, 2.00 / 3.00 , 2.00 / 3.00, 0.5 * (1.0 - std::sqrt(1.00 / 3.00)));

            GiD_fWriteGaussPoint3D( MeshFile, 1.00 / 3.00 , 2.00 / 3.00, 0.5 * (1.0 + std::sqrt(1.00 / 3.00)));
            GiD_fWriteGaussPoint3D( MeshFile, 2.00 / 3.00 , 1.00 / 3.00, 0.5 * (1.0 + std::sqrt(1.00 / 3.00)));
            GiD_fWriteGaussPoint3D( MeshFile, 2.00 / 3.00 , 2.00 / 3.00, 0.5 * (1.0 + std::sqrt(1.00 / 3.00)));

            GiD_fEndGaussPoint(MeshFile);
        }

```
**To be replaced with:**
```

else if ( mGidElementFamily == GiD_Prism  && mSize > 1)
        {
            GiD_fBeginGaussPoint( MeshFile, mGPTitle, GiD_Prism, NULL, 6, 0, 0 );

            GiD_fWriteGaussPoint3D( MeshFile, 2.00 / 3.00 , 1.00 / 6.00, 0.5 * (1.0 - std::sqrt(1.00 / 3.00)));
            GiD_fWriteGaussPoint3D( MeshFile, 1.00 / 6.00 , 2.00 / 3.00, 0.5 * (1.0 - std::sqrt(1.00 / 3.00)));
            GiD_fWriteGaussPoint3D( MeshFile, 1.00 / 6.00 , 1.00 / 6.00, 0.5 * (1.0 - std::sqrt(1.00 / 3.00)));

            GiD_fWriteGaussPoint3D( MeshFile, 2.00 / 3.00 , 1.00 / 6.00, 0.5 * (1.0 + std::sqrt(1.00 / 3.00)));
            GiD_fWriteGaussPoint3D( MeshFile, 1.00 / 6.00 , 2.00 / 3.00, 0.5 * (1.0 + std::sqrt(1.00 / 3.00)));
            GiD_fWriteGaussPoint3D( MeshFile, 1.00 / 6.00 , 1.00 / 6.00, 0.5 * (1.0 + std::sqrt(1.00 / 3.00)));

            GiD_fEndGaussPoint(MeshFile);
        }

```

The result is now:
![correct_gp_positions](https://user-images.githubusercontent.com/21369389/69081344-08cb1b00-0a3e-11ea-9f3f-02773ad33d7e.png)

I don't know if anyone is using this geometry or if anyone has had the same problem. I would kindly ask the developers to take a look at this issue.

Best Regards
Vladislav

**Comment by philbucher** [comment]
@KratosMultiphysics/interface-committee

**Comment by jginternational** [comment]
@escolano @pasenau

**Comment by jginternational** [comment]
Thanks @vgudzulic for the report.

Could you attach an example where this happens?

**Comment by vgudzulic** [comment]
Hi,

thanks for the response. It is a bit tricky to give an example, because it depends on bunch of code that I have written myself which generates interface elements based on input mesh. However, I can explain what is going on and attach the corresponding GiD output files in ascii format.

Namely, I use the prism_interface_3d_6 geometry for zero-thickness interface elements. I compute the normals and tangents and want to visualize them in GiD. This geometry uses GiD_Prism when writing the output file and apparently it writes its own integration points coordinates into an output file (see attached code in the post above).

I attach the output files of a small example that should illustrate the problem (problematic and corrected). To visualize the problem, deactivate all tetrahedral elements and plot normals of prism elements. 
[possible_bug_in_prism_output.zip](https://github.com/KratosMultiphysics/Kratos/files/3891310/possible_bug_in_prism_output.zip)
