### ISSUE TITLE
KRATOS_LOG: undefined references

### ISSUE THREAD

**Issue by thelfer** [KratosMultiphysics/Kratos#5964]
I tried to use to `KRATOS_LOG` (defined in `kratos/utilities/kratos_log.h`) macro as follows

```c++  
  KRATOS_LOG(KRATOS_SEVERITY_WARNING) << "unimplemented feature, can't compute '"                                         << rThisVariable.Name() << "'\n";
```

This leads to the following linker message:

```
CMakeFiles/KratosMGISCore.dir/custom_constitutive/mgis_constitutive_law.cpp.o : Dans la fonction « Kratos::KratosLog<(Kratos::KRATOS_SEVERITY)1>::GetInstance() » :
mgis_constitutive_law.cpp:(.text._ZN6Kratos9KratosLogILNS_15KRATOS_SEVERITYE1EE11GetInstanceEv[_ZN6Kratos9KratosLogILNS_15KRATOS_SEVERITYE1EE11GetInstanceEv]+0x11) : référence indéfinie vers « Kratos::KratosLog<(Kratos::KRATOS_SEVERITY)1>::mInstanceFlag »
mgis_constitutive_law.cpp:(.text._ZN6Kratos9KratosLogILNS_15KRATOS_SEVERITYE1EE11GetInstanceEv[_ZN6Kratos9KratosLogILNS_15KRATOS_SEVERITYE1EE11GetInstanceEv]+0x1d) : référence indéfinie vers « Kratos::KratosLog<(Kratos::KRATOS_SEVERITY)1>::mpInstance »
mgis_constitutive_law.cpp:(.text._ZN6Kratos9KratosLogILNS_15KRATOS_SEVERITYE1EE11GetInstanceEv[_ZN6Kratos9KratosLogILNS_15KRATOS_SEVERITYE1EE11GetInstanceEv]+0x1a4) : référence indéfinie vers « Kratos::KratosLog<(Kratos::KRATOS_SEVERITY)1>::mpInstance »
collect2: error: ld returned 1 exit status
```

Those symbols does not seem to appear in any library generated by `Kratos`. Is the `KRATOS_LOG` macro deprecated ?

**Comment by philbucher** [comment]
Hi @thelfer 
I am quite sure that this is an implementational detail and not supposed to be used "outside"

=> for this purpose we use [these functions](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/input_output/logger.h#L248-L276)

Usually we use INFO or WARNING

@roigcarlo @pooyan-dadvand please correct me if I am wrong

**Comment by roigcarlo** [comment]
Dear @thelfer as @philbucher says that is not supposed to be used outside the logger.

If you want to print a warrning using the logger should be something like:
```C++
void foo() {
    KRATOS_WARNING("MGIS") << "unimplemented feature, can't compute '" << std::endl;
}
```

Also you can find some other examples of use in https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-Logger

**Comment by thelfer** [comment]
Ok. Thanks for the link.
Thomas
