### ISSUE TITLE
Kratos by python code

### ISSUE THREAD

**Issue by Ali-RAFIEE** [KratosMultiphysics/Kratos#5966]
Hi every one,
As a new user of Kratos, I look for a simple example for do a model by using directly python interface without using Gid.
In fact I search an explanatory example in which I can have the input geometry for example via stl format files or similar ways, and I can adjust other parameters including material characteristics, contact conditions and boundary conditions all inside python code. I would like also to have output result files in vtk format with python code.
Already I want to know all these are possible?

Thanks a lot
Ali

**Comment by AndreasWinterstein** [comment]
You can have a look at the tests in the several applications. There you can see how you can see the direct use from python.

**Comment by Ali-RAFIEE** [comment]
Thank you very much Andreas,
I have seen some of these examples, but I look for a simple one to understand how Kratos works with python code, and also I would like to have output results in vtk format readable by Paraview.

if you can help me find an example like that, I will be very grateful.

thanks a lot.
Ali

**Comment by philbucher** [comment]
have a look at the tests in the StructuralMechanicsApplication, e.g. [this one](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/StructuralMechanicsApplication/tests/test_patch_test_small_displacement_mixed_volumetric_strain.py)
There you can see in very brief how to completely set up an example in python, inkl vtk output. It does not get more comprehensive than that :)

**Comment by Ali-RAFIEE** [comment]
Thanks Philipp
I have this error message when I run this code:
~~~
==========================================
python3 test_patch_test_small_displacement_mixed_volumetric_strain.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 7.0.0-b4d81f1-Release
Compiled with OpenMP and MPI support.
Maximum OpenMP threads: 8.
Running without MPI.
Importing    KratosStructuralMechanicsApplication 
    KRATOS   ___|  |                   |                   |
           \___ \  __|  __| |   |  __| __| |   |  __| _` | |
                 | |   |    |   | (    |   |   | |   (   | |
           _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS
Initializing KratosStructuralMechanicsApplication...
Segmentation fault (core dumped)
========================================
~~~

**Comment by loumalouomega** [comment]
> 
> # Thanks Philipp
> I have this error message when I run this code:
> # python3 test_patch_test_small_displacement_mixed_volumetric_strain.py
> | / |
> ' / **| _` | __| _ \ __| . \ | ( | | ( |\__ \ _|\_\_| \__,_|\__|\___/ ____/ Multi-Physics 7.0.0-b4d81f1-Release Compiled with OpenMP and MPI support. Maximum OpenMP threads: 8. Running without MPI. Importing KratosStructuralMechanicsApplication KRATOS ___| | | | \___ \ __| __| | | __| __| | | __| _` | | | | | | | ( | | | | ( | | _____/ __|_| __,_|_**|__|__,_|_| __,_|_| MECHANICS
> Initializing KratosStructuralMechanicsApplication...
> Segmentation fault (core dumped)

Ping @RiccardoRossi @rubenzorrilla

**Comment by philbucher** [comment]
can you run other tests?

Can you post your configuration (compiler etc)?

**Comment by Ali-RAFIEE** [comment]
Yes I can run other example in the "StructuralMechanicsApplication/tests"
for example:
~~~
===================================
python3 test_patch_test_small_strain.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 7.0.0-b4d81f1-Release
Compiled with OpenMP and MPI support.
Maximum OpenMP threads: 8.
Running without MPI.
Importing    KratosStructuralMechanicsApplication 
    KRATOS   ___|  |                   |                   |
           \___ \  __|  __| |   |  __| __| |   |  __| _` | |
                 | |   |    |   | (    |   |   | |   (   | |
           _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS
Initializing KratosStructuralMechanicsApplication...
......
----------------------------------------------------------------------
Ran 6 tests in 0.087s

OK
==========================================
~~~

**Comment by philbucher** [comment]
nice, then it seems to be a problem of this test (which was only recently added)
Still I think there you can find all the info that you need in order to set up your problems

**Comment by Ali-RAFIEE** [comment]
Thanks again Philipp
but, it was much better if I found an example that works!

**Comment by rubenzorrilla** [comment]
> > # Thanks Philipp
> > I have this error message when I run this code:
> > # python3 test_patch_test_small_displacement_mixed_volumetric_strain.py
> > | / |
> > ' / **| _` | __| _ \ __| . \ | ( | | ( |\__ \ _|\_\_| \__,_|\__|\___/ ____/ Multi-Physics 7.0.0-b4d81f1-Release Compiled with OpenMP and MPI support. Maximum OpenMP threads: 8. Running without MPI. Importing KratosStructuralMechanicsApplication KRATOS ___| | | | \___ \ __| __| | | __| __| | | __| _` | | | | | | | ( | | | | ( | | _____/ __|_| __,_|_**|**|**,_|_| __,_|_| MECHANICS
> > Initializing KratosStructuralMechanicsApplication...
> > Segmentation fault (core dumped)
> 
> Ping @RiccardoRossi @rubenzorrilla

I've just run it and it works for me. @philbucher does this happen to you?

**Comment by philbucher** [comment]
works for me

@rubenzorrilla did you try in fulldebug?

**Comment by rubenzorrilla** [comment]
> works for me
> 
> @rubenzorrilla did you try in fulldebug?

I did implement this tests in fulldebug mode.

**Comment by Ali-RAFIEE** [comment]
I did not try in fulldebug mode.
how can I compile Kratos in fulldebug mode?

**Comment by rubenzorrilla** [comment]
> I did not try in fulldebug mode.
> how can I compile Kratos in fulldebug mode?

https://github.com/KratosMultiphysics/Kratos/wiki/How-to-Compile-Kratos-in-Debug-mode

**Comment by Ali-RAFIEE** [comment]
put this "-DCMAKE_BUILD_TYPE=FullDebug" in configure.sh file, it can do?

**Comment by rubenzorrilla** [comment]
Exactly. You can also switch on the `D_GLIBCXX_DEBUG` flag to have further checks.

**Comment by Ali-RAFIEE** [comment]
I have now this message:
===========================================
python3 test_patch_test_small_displacement_mixed_volumetric_strain.py
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 7.0.0-b4d81f1-FullDebug
Compiled with OpenMP and MPI support.
Maximum OpenMP threads: 8.
Running without MPI.
Importing    KratosStructuralMechanicsApplication 
    KRATOS   ___|  |                   |                   |
           \___ \  __|  __| |   |  __| __| |   |  __| _` | |
                 | |   |    |   | (    |   |   | |   (   | |
           _____/ \__|_|   \__,_|\___|\__|\__,_|_|  \__,_|_| MECHANICS
Initializing KratosStructuralMechanicsApplication...
EE
======================================================================
ERROR: testSmallDisplacementMixedVolumetricStrainElement2DTriangle (__main__.TestPatchTestSmallDisplacementMixedVolumetricStrain)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_patch_test_small_displacement_mixed_volumetric_strain.py", line 155, in testSmallDisplacementMixedVolumetricStrainElement2DTriangle
    model_part.CreateNewElement("SmallDisplacementMixedVolumetricStrainElement2D3N", 1, [1,2,5], model_part.GetProperties()[1])
RuntimeError: Error: The component "SmallDisplacementMixedVolumetricStrainElement2D3N" is not registered!
Maybe you need to import the application where it is defined?
.
.
.
======================================

**Comment by rubenzorrilla** [comment]
I've just checked and the element is registered with this same name. When is the last time you compiled Kratos? (we add this a few weeks ago)

**Comment by Ali-RAFIEE** [comment]
I solved this problem,
but when I choose post_type="vtk" by replacing "gid", I see failed error again.
with gid option this example works, but for vtk there are problems!

thanks a lot Rubén

**Comment by rubenzorrilla** [comment]
> I solved this problem,
> but when I choose post_type="vtk" by replacing "gid", I see failed error again.
> with gid option this example works, but for vtk there are problems!
> 
> thanks a lot Rubén

Do you mean when selecting the test output type? If you want the output to be in vtk format you need a different output process (vtk_output_process.py), which has different settings to the GiD one.

If this is solved, could you please close the issue?
