### ISSUE TITLE
Definition of properties in StructuralMechanicsApplication

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#598]
Hi @KratosMultiphysics/structural-mechanics,

as far as I understand, in the StructuralMechanicsApp, the properties along with the material are defined in a separate json file. This seems to make the properties defined in the mdpa obsolete. However, when I remove the unnecessary properties definition in the mdpa, Kratos complains during the reading process that properties are missing. So, I have to leave them inside, knowing that they do not have an effect. I find this a somewhat confusing and in any case inconsistent behavior. Can anybody confirm this being an issue?

Thanks and best regards,
Daniel

**Comment by RiccardoRossi** [comment]
Hi Daniel,

the point is there is something to be done in the ImportModelPart.

@loumalouomega can u point to where this is done in the StructuralSolver?

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/28013601-dd6cc6f0-6569-11e7-91b8-a631755f3f3a.png)

**Comment by loumalouomega** [comment]
But this is done in the model_part_io

Theoretically the only thing is supposed to be needed to be defined is an empty property

**Comment by RiccardoRossi** [comment]
@loumalouomega ,
no, there is a point in which you read the materials. (most probably in the _execute_after_reading)

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/28015785-d66cf12e-6571-11e7-900c-6859beb66e5a.png)
model_part_io.cpp, the properties are read

**Comment by loumalouomega** [comment]
if the properties are not defined will give an error when reading the elements or conditions

![imagen](https://user-images.githubusercontent.com/19991680/28015827-1a86b62e-6572-11e7-8eb9-e6463cacf44e.png)

**Comment by AndreasWinterstein** [comment]
I think one more problem is, that also the elements might directly get values with the GetProperties function from the *.mdpa files. Thus I think the elements, which do so, should be adapted to the new concept with the materials.json file. 

Do you want to use this concept also for the other applications?
