### ISSUE TITLE
DEMApplication: Some of the benchmark tests in the test_examples getting failed 

### ISSUE THREAD

**Issue by sauravVerma92** [KratosMultiphysics/Kratos#5991]
The Basic continuum tests are getting failed while running the DEM_run_all_benchmarks_analysis.py from the Kratos>applications>DEMApplications>test_examples 
DEM Benchmark 20: KO!........ Test 20 FAILED
DEM Benchmark 21: KO!........ Test 21 FAILED
DEM Benchmark 22: KO!........ Test 22 FAILED
DEM Benchmark 23: KO!........ Test 23 FAILED
DEM Benchmark 24: KO!........ Test 24 FAILED
DEM Benchmark 25: KO!........ Test 25 FAILED

Also, when I run the DEM_run_all_benchmarks_grid.py some of the benchmark tests get failed. 
![Screenshot 2019-11-27 at 7 16 34 PM](https://user-images.githubusercontent.com/58203729/69720525-c7c5bb80-114d-11ea-961b-017463ea5221.png)
![Screenshot 2019-11-27 at 7 16 53 PM](https://user-images.githubusercontent.com/58203729/69720526-c7c5bb80-114d-11ea-99cc-6591db36a212.png)

**Comment by rubenzorrilla** [comment]
@KratosMultiphysics/dem @maceligueta

**Comment by maceligueta** [comment]
Thanks @rubenzorrilla  and @sauravVerma92 , I will check this today.

**Comment by maceligueta** [comment]
Those tests were fixed and approved this morning in PR #6018
Test 40 is still failing, but @farrufat-cimne is taking care of it...
As soon as he finishes I think we will be able to close this issue.

**Comment by philbucher** [comment]
can this be closed?
