### ISSUE TITLE
Kratos release 7.1

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#5992]
Next week we will freeze the branch for the minor release (7.1.0). 

Like any other release please revise the [release project](https://github.com/KratosMultiphysics/Kratos/projects/5) for applications to be included. Please note that the major release 8.0.0 will be announced soon (for the first quarter of the next year) which may include more features than this one.

 @KratosMultiphysics/all

**Comment by jginternational** [comment]
The GiD GUI schedules it's releases with some time offset. 
We'll freeze the release branch the same day but the released zip of the problemtype will be delivered less than a week later, so we can run all the tests with the same exe published in the 'versions' section.

Check which apps will be [deployed in the GUI here](https://github.com/KratosMultiphysics/GiDInterface/issues/661)

**Comment by roigcarlo** [comment]
Dear @KratosMultiphysics/all . I just blocked the current status of the repo as in https://github.com/KratosMultiphysics/Kratos/tree/7.1-Rc

Please if you have commits that need to go into the release add them to the 7.1 Milestone so we can keep track of them and merge it to the branch release. Thx!

**Comment by pooyan-dadvand** [comment]
@roigcarlo, why you didn't create a branch as usual for this release?

**Comment by roigcarlo** [comment]
There is a branch but is not public. Mainly to avoid problems with merging hotfixes, but i can make it visible if you want.

**Comment by pooyan-dadvand** [comment]
Visible and protected?

**Comment by roigcarlo** [comment]
Done

**Comment by pooyan-dadvand** [comment]
Thanks!

**Comment by roigcarlo** [comment]
@AFranci Please note that we cannot add PfemFluid because it still depends on the DelaunayMeshing application, which cannot ship with the release as it depends on tetget.

Would it be possible to fix this? Maybe hidding the options that depends on it from the interface?

**Comment by mpentek** [comment]
Any news on the timeline? When it will potentially be available also as a problemtype for GiD14? @jginternational @roigcarlo seem to have 7.1.3 RC and 7.1. RC ready.

**Comment by roigcarlo** [comment]
Bianries should be ready this afternoon, and GiD soon later.

**Comment by jginternational** [comment]
New GiD problemtype release available here:

https://github.com/KratosMultiphysics/GiDInterface/releases/tag/release-7.1.5

@KratosMultiphysics/all 

Soon in Internet Retrieve!
