### ISSUE TITLE
A proposal for a more flexible handling of material properties in constitutive laws

### ISSUE THREAD

**Issue by thelfer** [KratosMultiphysics/Kratos#6019]
The `MGISApplication` aims at allowing `MFront` constitutive laws to be used in `Kratos`.  Constitutive laws are loaded dynamically in shared libraries generated by `MFront`. As such, the number of material properties and their names required by a constitutive law is no more known at compile time. Thus, relying on `Kratos`' `Variable`s is not an option.

Note that this issue may also be relevant to any applications interfacing external CLs (the `UmatApplication` maybe (?)).

Issue #5950 is an in-depth discussion about why a more flexible handling of material properties and discusses various solutions, none of which were considered satisfactory so far.

The object of this issue is to discuss one new proposal which:

- is backward compatible (i.e. does not lead to any modification of existing CLs)
- allows a complete flexibility,
- allows only a slight and controlable deviation from the standard `Kratos` variaable mechanisms.
- may improve the performances of `MFront` behaviours
- seems quite straightforward to implement.

Again the arguments that back this proposal can be found in Issue #5950.

The proposal can be expressed as follows:

- modify the parsing of the `Variables` section of the input file, so the variables' names are not check.
- create an overloaded version of the `Create` method for CLs which takes the material properties read in the `Variables` section as an argument. The default version of this method would check the variables' names and call the current `Create` methods. This way, backward compatibility in ensured and no change to existing CLs is required.

In the `MGISApplication`, the `MGISConstitutiveLawFactory` will overload this new `Create` function and checks that only the material properties expected by the constitutive law are declared. This allows full flexibility. A mechanism, too long to be described here, is meant to ensure a maximal compatibility with `Kratos`: a variable named `YOUNG_MODULUS`, which is the standard Kratos' naming can be used whenever the behaviour requires the young modulus to be defined.

Concerning performances (efficiency and memory footprint), the `MGIS` library requires the material properties to be stored in a continous array. This proposal allows this array to be build in the `Create` method and be shared among all the clones of the generated CL.

**Comment by loumalouomega** [comment]
The only thing i find problematic is to re-implement the Create in all CL, fortunately not many laws override this method (basically the factories). Because I assume we will need to pass the whole materials Parameters instead of the ones relative to the CL as we do now. 

The second thing is that currently we define the Create considering only some Parameters as input (https://github.com/KratosMultiphysics/Kratos/blob/7a2606aad8cef3c97a51e943d8485129ce29986f/kratos/includes/constitutive_law.h#L517), should we add more input like Properties for example?

**Comment by thelfer** [comment]
@loumalouomega It seems that I did not explain this point properly. Consider that CLs would have two overloaded version of `Create`. The new one will take the Parameters and the material properties as input. It's default implementation would be:

~~~{c++}
virtual Pointer ConstitutiveLaw::Create(Kratos::Parameters NewParameters, const Properties mp) const{
// do checks with mps
return this->Create(NewParameters);
} 
~~~

This means that *one may not have to change a single line* in the existing CLs

**Comment by loumalouomega** [comment]
> @loumalouomega It seems that I did not explain this point properly. Consider that CLs would have two overloaded version of `Create`. The new one will take the Parameters and the material properties as input. It's default implementation would be:
> 
> ```
> virtual Pointer ConstitutiveLaw::Create(Kratos::Parameters NewParameters, const Properties mp) const{
> // do checks with mps
> return this->Create(NewParameters);
> } 
> ```
> 
> This means that _one may not have to change a single line_ in the existing CLs

OK, now I understand

**Comment by roigcarlo** [comment]
we have been discussing this in the @KratosMultiphysics/technical-committee (although not all the members were present due to calendar issues. @pooyan-dadvand please vocalize if you are not in agreement).

we in principle agree about adding to the ConstitutiveLaw base class

~~~c++
virtual Pointer ConstitutiveLaw::Create(Kratos::Parameters NewParameters, 
                    const Properties& rProperties) const
{
// do checks with mps
return this->Create(NewParameters);
} 
~~~

nevertheless our suggestion is to wait one or two days before starting with the PR so to see if anyone (@KratosMultiphysics/structural-mechanics  @KratosMultiphysics/mpm @KratosMultiphysics/dam ) or anyone else has a strong objection about this.

**NOTE:** please note in any case that we do have strong objections about adding extra parameters other than the properties. 

[EDIT:]of course we will need to change the "read_material_utility" to always call the version WITH properties

**Comment by loumalouomega** [comment]
Question, should properties be constant or not?

**Comment by thelfer** [comment]
This is what I understood from @RiccardoRossi   (See  https://github.com/KratosMultiphysics/Kratos/issues/5950#issuecomment-559713626_)

**Comment by philbucher** [comment]
> Question, should properties be constant or not?

`const`

(however related to #3354)

**Comment by RiccardoRossi** [comment]
I would let it const.

It is true that Create is designed for usage at the moment of reading, so without any parallelism, nevertheless i also think that allowing to change things in the Properties is VERY VERY dangerous.

If we want to allow it non-const we need to give strong assurances about Create being called only in serial ... i am not sure we can do that...

In this context if one really wants to do it, than i would use a const_cast to explicitly tell that something nasty is going on.

**Comment by thelfer** [comment]
definitively `const`

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/altair I would suggest you follow this tread and give your feedback on it.

As I expressed myself in #5959 I would go for passing the CL data in its parameters rather than using the Variables. About the variables that are defined already in Properties, I don't have a strong opinion but I would go for having a copy of them in the parameters of CL to be self-contained.  

I understand that for backward compatibility we would need a mechanism to fill the parameters from the properties.

**Comment by pooyan-dadvand** [comment]
Ok, I see this as a solution but not the definitive one. So let's go with it at the moment until we figure out how we can improve it.

**Comment by RiccardoRossi** [comment]
Just to add that one of the outcomes of the discussion of the @KratosMultiphysics/technical-committee is that we should improve the current design of CLs , between other things to allow for a better control of input variables (from tables, nodes, etc...)

the solution here is considered as a short term solution while a new design emerges (which will surely take some time due to the complexity of the issue). 

Having said this i would open a different thread to discuss about this in depth

**Comment by thelfer** [comment]
May we consider that the proposal is accepted ?
I noticed that it is not perfect, but I also see that I has the advantage of not modifying existing CLs, meaning that if we need to pass other information (the modelling hypothesis would be a good example IMHO) we can only modify this new overload of the `Create` method.

@loumalouomega may I ask you for help for the modification of the  `read_material_utility` ?

**Comment by RiccardoRossi** [comment]
@thelfer yes, consider it accepted...but with the kludge that we need a better solution in the future, so this will eventually change when we find something better....

**Comment by thelfer** [comment]
@RiccardoRossi That find for me. As I said, feel free to change this new overload of the `Create` method in the future as it will mostly affect the `MGISApplication` right now.

**Comment by loumalouomega** [comment]
Yes, this change can be done in not time.

**Comment by thelfer** [comment]
Great. Let me know when done so I'll test it :)

**Comment by loumalouomega** [comment]
@thelfer see #6071

**Comment by thelfer** [comment]
@loumalouomega Not yet synchronized with the `mfront/application` branch ?

**Comment by loumalouomega** [comment]
Nope, one sec

**Comment by loumalouomega** [comment]
Now is up-to-date

**Comment by thelfer** [comment]
@loumalouomega Finally had the time to give it a try (sorry for the lack of reactivity) and.... it did not work :)

When trying to add a new material property, the reader still complains.

```sh
RuntimeError: Error: Value type for "NortonCoefficient" not defined
```

My initial proposal was that this check  was to be deported in the `Create` method and remove from the reader. This does not seem to be the case in `constitutive_law.cpp`:

```c++
/**
 * @brief It creates a new constitutive law pointer (version with properties)
 * @param NewParameters The configuration parameters of the new constitutive law
 * @param rProperties The properties of the material
 * @return a Pointer to the new constitutive law
 */
ConstitutiveLaw::Pointer ConstitutiveLaw::Create(
    Kratos::Parameters NewParameters, 
    const Properties& rProperties
    ) const
{
   // here one shall check by default that material properties are registred.
    return this->Create(NewParameters);
}
```

Have I missed something ?

**Comment by loumalouomega** [comment]
Which is the content of the final material.json considered?

**Comment by loumalouomega** [comment]
Dear @thelfer can you clarify the expected behaviour?, maybe i have not properly updated the reader utility accordingly

**Comment by thelfer** [comment]
@loumalouomega This is what I specified:

> * create an overloaded version of the `Create` method for CLs which takes the material properties read in the `Variables` section as an argument. The default version of this method would check the variables' names and call the current `Create` methods. This way, backward compatibility in ensured and no change to existing CLs is required.

To make it clear, one should remove the names' check in the reader and make them part of the default `Create` method.

Thanks for help !

**Comment by thelfer** [comment]
> Which is the content of the final material.json considered?

Here is an example:

```json
{
    "properties" : [{
        "model_part_name" : "Structure.Parts_Solid_Auto1",
        "properties_id"   : 1,
        "Material"        : {
            "constitutive_law" : {
	        "name": "MGISConstitutiveLawFactory",
                "library" : "src/libBehaviour.so",
                "behaviour" : "Elasticity"
            },
            "Variables"        : {
              "NortonCoefficient": 8.2
            },
            "Tables"           : {}
        }
    }]
}
```

**Comment by loumalouomega** [comment]
@thelfer I created #6136. But what I thought we agreed with @RiccardoRossi (maybe I am wrong and I don't remember) is to add the variables related with MGIS in the constitutive law definition

**Comment by thelfer** [comment]
> But what I thought we agreed with @RiccardoRossi (maybe I am wrong and I don't remember) is to add the variables related with MGIS in the constitutive law definition

@loumalouomega Well, maybe things got confused  because we discussed in parallel material properties, internal state variables and external state variables. 

For material properties, tI do believe that the definitive proposal is this one. Having the variables related with MGIS in the constitutive law definition would make a distinction between MFront behaviours and native ones. I wouldn't like that.

**Comment by loumalouomega** [comment]
> 
> 
> > But what I thought we agreed with @RiccardoRossi (maybe I am wrong and I don't remember) is to add the variables related with MGIS in the constitutive law definition
> 
> @loumalouomega Well, maybe things got confused because we discussed in parallel material properties, internal state variables and external state variables.
> 
> For material properties, tI do believe that the definitive proposal is this one. Having the variables related with MGIS in the constitutive law definition would make a distinction between MFront behaviours and native ones. I wouldn't like that.

In that case #6136 will do the trick :)
