### ISSUE TITLE
[For Discussion] Prints in ModelPartIO

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#6048]
Currently in model_part_io.cpp , the output statements use KRATOS_INFO. For example 

https://github.com/KratosMultiphysics/Kratos/blob/5afee738f9cef2bca6ca5e762ba73851a22b16b1/kratos/sources/model_part_io.cpp#L1076

https://github.com/KratosMultiphysics/Kratos/blob/5afee738f9cef2bca6ca5e762ba73851a22b16b1/kratos/sources/model_part_io.cpp#L1387

This means that in an MPI run, only the rank 0 will print the number of nodes , elements (and others) it reads. For example here :
https://github.com/KratosMultiphysics/Kratos/blob/5afee738f9cef2bca6ca5e762ba73851a22b16b1/kratos/sources/model_part_io.cpp#L1426
The other ranks will not output anything. This is misleading IMO. 

It would be better either we print this info on all ranks.
or 
we do a `r_comm.Sum()` for all the number of entries read and print that info on rank 0. 

When decided on how to proceed, I can do the PR.

I ask the opinion of @KratosMultiphysics/technical-committee  and @KratosMultiphysics/implementation-committee

**Comment by philbucher** [comment]
#5863 
Unfortunately not as straight forward, I did an attempt already
Maybe we can speak in person

**Comment by adityaghantasala** [comment]
OK I close this and we can discuss on #5863
