### ISSUE TITLE
KinematicLinearElement

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#606]
Dear @KratosMultiphysics/structural-mechanics team,
Is there any reason to have SmallStrainElement (in GUI) named KinematicLinearElement and not small strain?

**Comment by RiccardoRossi** [comment]
I agree about changing the name

**Comment by loumalouomega** [comment]
Is it just name change in the GUI?

**Comment by pooyan-dadvand** [comment]
For me the GUI name is more understandable than the cpp one.

**Comment by loumalouomega** [comment]
The name used to register is SmallDisplacementElement in order of being retrocompatible

**Comment by RiccardoRossi** [comment]
Hi @loumalouomega Pooyan is suggesting to change the name of the cpp and header to SmallDisplacementElement instead of KinematicLinear.

is it ok for you?

**Comment by loumalouomega** [comment]
Not a problem, go ahead

**Comment by loumalouomega** [comment]
@pooyan-dadvand Done

**Comment by pooyan-dadvand** [comment]
Thanks! 👍

**Comment by loumalouomega** [comment]
Closing
