### ISSUE TITLE
MemoryInfo include windows.h in header

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6062]
While browsing through the code I saw that [MemoryInfo includes `windows.h` in the header!](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/includes/memory_info.h#L34). I recently read up a bit on this and think that this should be moved to a cpp and probably also protected by 
`WIN32_LEAN_AND_MEAN` or `VC_EXTRALEAN`, see https://stackoverflow.com/questions/11040133/what-does-defining-win32-lean-and-mean-exclude-exactly
Reason is that `windows.h` is a very heavy header.

**Comment by roigcarlo** [comment]
@pooyan-dadvand Probably can answer better but `windows.h` is not inclued in Linux, only in win, which is correct.

About the cpp, Honestly I think its small enough to be header only, also its only inclided by a python interface so there is no real impact in compilation time or adding complexity to the code :S

**Comment by philbucher** [comment]
> @pooyan-dadvand Probably can answer better but windows.h is not inclued in Linux, only in win, which is correct.

well would not compile otherwise I guess ;)

> About the cpp, Honestly I think its small enough to be header only, also its only inclided by a python interface so there is no real impact in compilation time or adding complexity to the code :S

hm ok as you say.
Until someone starts including it somewhere else :D

**Comment by pooyan-dadvand** [comment]
I agree that having it in cpp would be cleaner and with less side effects.
