### ISSUE TITLE
removing deprecated members of the base class CL

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#610]
Hi @vryy ,
      i am writing you since i think it would be time to remove the long deprecated functions from the CL.

My proposal would be to create a class "legacy_cl" to be put in your application, and to derive all of the CLs you currently have from such base class. 
the legacy_cl would implement as virtual the functions that are currently deprecated in the base_class (the ones i would like to remove) so that by deriving from it instead of deriving directly from the cl, your classes would still work. 
Would that be acceptable for you?

**Comment by vryy** [comment]
that's OK for me. But i'll name it StructuralConstitutiveLaw to make it sensible. A name legacy_cl does not represent any physics and does not make sense to me.

**Comment by RiccardoRossi** [comment]
hi Bui,
   my point is that this is a "legacy" interface (or deprecated or a similar keyword). The good way for new CLs would be to derive directly from the constitutive_law base class and use the "new" interface

cheers
Riccardo

**Comment by RiccardoRossi** [comment]
@vryy just to make clear, at the very end we call it as you like...mine it is a suggestion, but it doesn't really matter the naming to me

**Comment by vryy** [comment]
@RiccardoRossi , i anticipate what should be done is to embed CalculateMaterialResponse in, i.e. CalculateMaterialResponseCauchy and initialize the respective Parameters. Do you have the same thinking? If that is i will just proceed in that direction.

**Comment by RiccardoRossi** [comment]
hi @vryy, yes i think we are on the same wavelength.

essentially the StructuralConstitutiveLaw should define the function 
CalculteMaterialResponse
which inside should call  the legacy functions, which will be defined as virtual in the same class.

this way any class derived from the StructuralConstitutiveLaw will be compatible with the new interface

btw, i extended the documentation of the "new" interface. You can find it here:
[Constitutive Law Documentation](https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-the-Constitutive-Law-class)

**Comment by vryy** [comment]
seem fine, I'll get it done in couple of days.

**Comment by pooyan-dadvand** [comment]
I just want to mark my **disagreement** with any attempt to make two different version of Constitutive Laws working together. I'm very sorry to say this, but I see it really a "lazy" solution which increments the long therm maintenance cost and reduces the quality of the framework. Finally I don't see why you are resisting so much to not clean the code and actively participate in the new design and improvements....

**Comment by RiccardoRossi** [comment]
@vryy did u make progress on this?

**Comment by RiccardoRossi** [comment]
Hi Bui, the point is that the old form of the cl will cease working once I delete the virtual functions.

 The modification to be done to employ the new format is not very large, so pooyan s point is that you could easily apply it to all the constitutive laws and have a clean solution.

-alternatively (my suggestion) you could derive all of them from a wrapper class that does the format translation. Not the cleanest solution though...

**Comment by vryy** [comment]
@RiccardoRossi In fact, I prefer your method because it reduces possible error with the material integration. However, if we insist on the new interface, the only solution is to re-write everything.

**Comment by pooyan-dadvand** [comment]
Do you think that is a complete rewrite or it would be a restructure of existing codes?

**Comment by RiccardoRossi** [comment]
a newer PR is discussing this: #1838 closing this one as outdated
