### ISSUE TITLE
Extension for StructuralMechanics

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6107]
Hi,
I was just discussing with @KlausBSautter, @longchentum and @zidanmahmoud about the integration of things into StructuralMechanics, that don't fully fit there. In this particular case it is an element that is very specific. We basically were not sure where to put it. First we came up with a separate application, but this would be quite an overkill regarding the maintenance and the also it would be one app for only one element.
The same happened already multiple times, someone implements sth cool, but if we don't have a good place to put it it will eventually be lost.

During the discussion we came up with the following:
Having an application deriving from StructuralMechanics as container for all the "special" things, that are not general enough for StructuralMechanics. E.g. `AdvancedStructuralMechanicsApplication` or `StructuralMechanicsExtensionsApplication`.

This way we could keep the StructuralMechanicsApp very clean and well maintainable, while at the same time having a standard place for advanced things, which makes them easy and straight-forward to use.

We considered the following things to be moved there:
- The things from the CableNetApp
- The new element we were discussing (specific for seismic simulations)
- some specific elements that are currently in StructuralMechanics
- the advanced CLaws until they will be moved to a separate App
- Response-Fcts / Sensitivity Analysis ?

This app can be integrated in the CI, esp with the new actions this should not be a problem

@KratosMultiphysics/technical-committee @KratosMultiphysics/structural-mechanics

**Comment by loumalouomega** [comment]
Huuuuuuuuuuuuum, I need to think about this.

**Comment by philbucher** [comment]
well, lets think abt it and hear what others say

maybe only new things should go there to not again mess with the existing structure of files etc ...

**Comment by RiccardoRossi** [comment]
About moving the CLs i do not really agree. We already decided to eventually have a ConstitutiveLawsApplication and to move them there. I would not do any intermediate movement...

Aside of this, more than having a single ExtensionApp, in which a lot of miscellanea goes in, i think it is better to have different dependent applications. But once again we need to consider this carefully as they would go easily unmantained

**Comment by philbucher** [comment]
> About moving the CLs i do not really agree. We already decided to eventually have a ConstitutiveLawsApplication and to move them there. I would not do any intermediate movement...

ok this makes sense

> Aside of this, more than having a single ExtensionApp, in which a lot of miscellanea goes in, i think it is better to have different dependent applications. But once again we need to consider this carefully as they would go easily unmantained

that is the main point :confused:

**Comment by philbucher** [comment]
closing this for the moment as it is kinda stale now

lets see if we need to reopen in the future
