### ISSUE TITLE
List of applications for the 5.1 release

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#611]
Dear @KratosMultiphysics/kratos-core-team,
Which is the official list of applications that need to be in the release?

**Comment by roigcarlo** [comment]
Im using the ones in here: https://github.com/KratosMultiphysics/Kratos/projects/5

**Comment by pooyan-dadvand** [comment]
👍

**Comment by jginternational** [comment]
This will update this one -> https://github.com/KratosMultiphysics/GiDInterface/projects/5
