### ISSUE TITLE
How to specify file paths for output files?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6120]
right now we have basically 3 ways of specifying the file-name for output-files
- in HDF5App (e.g. [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/HDF5Application/python_scripts/single_mesh_primal_output_process.py)): giving complete control to the user by only specifying `file_name` which includes folder names
- in core, [vtk](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/input_output/vtk_output.cpp#L1064-L1067) and restart process: Separating the file name and the folder name, this makes it possible to write the files to a folder using a flag
- in the [TimeBasedAsciiWriter](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/time_based_ascii_file_writer_utility.py#L18-L19): separately defining file and folder name

each of them have their advantages and disadvantages, I think it would be good to unify, esp since recently several times problems with it arose (e.g. #6118)

I think leaving completely to the user the file_name to also contain folders like done in the HDF app would be the cleanest solution, but then I don't know if it is possible to add a folder with a flag
However if we could specify the folder name inside the file name and create it automatically if it does not yet exist then I think it would be also ok
esp with #6061 this can also be done in C++

**Comment by mpentek** [comment]
What is a bit misleading is perhaps also the labeling. 

- folder_name should only contain folders (relative path?, also pythonic in the sense that creating it happens in the working directory)
- file_name no folder names (some additional checks and warnings (again relative path - also some check if the user specifies folder relative and file absolute...)

I use the folder (and subfolders) for example to have the multiple files from a line output grouped. So I use it somehow as a prefix, as additional information gets added to the automatically created files.

Recent case:
![image](https://user-images.githubusercontent.com/15231695/71109408-6a111600-21c5-11ea-9734-0fcdb83a80fa.png)
![image](https://user-images.githubusercontent.com/15231695/71109430-739a7e00-21c5-11ea-8d2d-5776727f42d9.png)


I have a group _roof_ in GiD, with 3 subgroups, on all of the I want the drag, the file create process misinterprets the slashes, such that I get the following warning:
```
TimeBasedAsciiFileWriteUtility: Relative path "FluidModelPart.Drag_roof" contained wrongly in "file_name": "FluidModelPart.Drag_roof/1_drag.dat"
Use the parameter "folder_name" to specify correctly
```
Mayba a flag for `path_type` with default `relative`?

**Comment by sunethwarna** [comment]
I have a small question regarding the #6061. Is it possible to identify and create folders from a string given ( it should be pretty straight forward regardless of the system ryt? ) If so, would it be possible to have the prefix string for filenames. Does following make sense to address for most of the situations when using prefix?

1. We can pass that string over c++ OSUtils method to do folder creation if folder does not exist. 
2. May be we can also have in the OSutils to get the parent folder from prefix string, and if required then we can clean/create that folder. 

In this way, we don't have to worry about passing relative or absolute paths ryt?

**Comment by adityaghantasala** [comment]
Another question regarding #6061 or may be more in general,

Lets say the file name is given as `/media/user/my_folder/test_vtk_fle.vtk`
with the changes in #6061 or in python is it possible to isolate and get/check if the older `/media/user/my_folder/` exists ?  Or one has to manually extract the string `/media/user/my_folder/` (in python or c++) and check if the folder exists ?

**Comment by adityaghantasala** [comment]
@sunethwarna  regarding your point number 2 this is already what you did in #6082 right ?

**Comment by pablobecker** [comment]
On behalf of the @KratosMultiphysics/implementation-committee 

- We prefer the design that has the name of the file(s) separated from the output location.
- The name of the key holding this path should not end in 'name', but rather 'path' or 'location' etc., since the names are given separately.

**Comment by adityaghantasala** [comment]
@philbucher @mpentek @sunethwarna  any comments ?

**Comment by AlejandroCornejo** [comment]
ping

**Comment by philbucher** [comment]
Still active, this will need some time to update the usages
I am starting to use this in the `RestartUtility` soon since this is the biggest mess atm
