### ISSUE TITLE
Improvements for VariableRedistributionUtility

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6127]
I started using the `VariableRedistributionUtility` in #5993 and it seems to work well.
Here are some suggestions for improvement:
- [x]  Right now is hardcoded to work with Conditions, should be (and can be easily) extended to using elements. After all only uses the geometry. And maybe in the future even directly the geometries
- [x]  The internal "helper" variables are historical, which is quite inconvenient to work with. I didn't see a reason why they cannot be non-historical
- [x]  Same for the "input" variables, they are hardcoded to be historical, I think it would be good if they could be optionally non-historical
- [x]  Currently only lines and triangles are supported, since quads are quite popular in structural problems I think it would make sense to extend it

FYI @shahrokh-shayegan

**Comment by rubenzorrilla** [comment]
The unique reasoning is legacy. Note that this utility used to be part of the very old mapper in the FSI application.

I've no objections to add your enhancements. All of them should be more or less straightforward.

**Comment by rubenzorrilla** [comment]
>     * [ ]   The internal "helper" variables are historical, which is quite inconvenient to work with. I didn't see a reason why they cannot be non-historical

I think that all the auxiliary variables are non-historical (only the input/output ones are forced to be historical as you mention in the next bulletpoint).
