### ISSUE TITLE
[EVERYONE] Please check your stale branches

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#6204]
![image](https://user-images.githubusercontent.com/19991680/72246535-3625e680-35f3-11ea-8abe-d1c5ab101dab.png)

We reached 518 branches, can @KratosMultiphysics/all please check their respective stale branches? 

This is reminder of #1350 #2132 and #3167

[All stale](
https://github.com/KratosMultiphysics/Kratos/branches/stale)
[Yours](
https://github.com/KratosMultiphysics/Kratos/branches/yours)

**Comment by philbucher** [comment]
Maybe we can add an auto delete for branches older than one year

**Comment by KlausBSautter** [comment]
deleted mine. But I do have 1 old one which I need to keep @philbucher

**Comment by philbucher** [comment]
I checked, there are a lot of branches that don't have a single commit to them.
I would say we can safely delete those, what do others think?

**Comment by riccardotosi** [comment]
@philbucher I have old branches that must not be deleted, even with old commits, please check if it is written or not "DO NOT DELETE" if you proceed.

PS. Sorry for closing the issue, I re-opened it.

**Comment by AFranci** [comment]
Please, ask before delete other people's branches.

**Comment by philbucher** [comment]
I won't delete anything, just throwing ideas

as @loumalouomega pointed out we have > 500 branches, and many many are stale. At some point I fear that this will become a performance issue with Git.

Hence I suggest to find a better solution

BTW if there are some branches that must not be deleted, then we could think of protecting those (like the master or the release branches)

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee also highly recommends revising the old branches and eventually think about adding an automatic mechanism to alert the developers for stale branches and delete them if there are no merge from master to it in one month after the notification.

**Comment by loumalouomega** [comment]
> 
> 
> @KratosMultiphysics/technical-committee also highly recommends revising the old branches and eventually think about adding an automatic mechanism to alert the developers for stale branches and delete them if there are no merge from master to it in one month after the notification.

I added an action (recommended by GitHub) for that: https://github.com/KratosMultiphysics/Kratos/pull/6156

I am not an expert in actions, can any expert check how can this work?

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee will eventually implement a mechanism with which ppl will be informed if they have stale branches. Preliminary investigations show that this can work

**Comment by loumalouomega** [comment]
Hello, I just want to remember to @KratosMultiphysics/all that there are still many stale branches: https://github.com/KratosMultiphysics/Kratos/branches/stale and https://github.com/KratosMultiphysics/Kratos/branches/yours . So check it. There are some very old regarding @pooyan-dadvand, @playpaolo , @rubenzorrilla and @RiccardoRossi . We can add a CI action like this one https://github.com/marketplace/actions/stale-branches in order to automatize this. I have already clean up mines.

**Comment by loumalouomega** [comment]
I am starting to think that maybe the easiest way is to create a backup Fork and delete all stale branches older than 2 years... Opinion @KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
We will have to issue another friendly reminder about this. Until then closing.
