### ISSUE TITLE
Add description for File Logger to Wiki

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#6208]
This is a reminder for @armingeiser 

In #5924 #5700 #6124 some new options have been added to the Logger.

The Wiki-section about the Logger should be extended and the compiler flag for the colored logging should be described in the installation guide.

**Comment by philbucher** [comment]
afaik there is already a wiki for the logger

**Comment by armingeiser** [comment]
https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-Logger#writing-log-files
