### ISSUE TITLE
DEMSteucturalCoupling link problems on windows 

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#6221]
The classes `PostProcessUtilities` `SandProductionUtilities` are using Kratos api export, but they should not as are compiled as a part of the interface (I asume this is due to the fact of using the pybind11 lists directly)

You need to remove the KRATOS_API macro or it will not compile in windows

**Comment by roigcarlo** [comment]
You can copy them from here:
https://github.com/KratosMultiphysics/Kratos/commit/20cf0a53302b89c1652840826a5c7edc19904d78

**Comment by ipouplana** [comment]
I just created a branch named "dem/structure-fix-link-windows" and cherry-picked the commit [20cf0a5](https://github.com/KratosMultiphysics/Kratos/commit/20cf0a53302b89c1652840826a5c7edc19904d78)
I will compile it and test that nothing is broken
