### ISSUE TITLE
[Packaging] Attempt at packaging kratos and NUMPY/SCIPY with nuitka

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#6236]
Dear All,

this thread is to report some initial experience with attempting to package kratos with scipy/nunmpy support

to do so i created a file "test.py" (the "runner") as

~~~py
import scipy
import numpy
import sys
print("scipy version = ",scipy.version)
print("runkratos file ", sys.argv[1])
exec(open(sys.argv[1]).read())
~~~

and i packaged it by running

~~~
nuitka3 --standalone --enable-plugin=numpy=scipy --include-package=scipy  --follow-imports test.py
~~~

the first experience is that it is compiling forever... i am leaving it compiling for the night...

**Comment by loumalouomega** [comment]
> the first experience is that it is compiling forever... i am leaving it compiling for the night...

![imagen](https://user-images.githubusercontent.com/19991680/72461624-b6a13e80-37cf-11ea-97eb-7875c68d4ee9.png)

**Comment by RiccardoRossi** [comment]
well, the good news is that it looks like it works.

further steps needed are:
1 - copy the content of kratos_install/libs into test.dist
2 - copy (or link) the KratosMultiphysics folder within the same directory.

with that in principle it is possible to execute

./test.dist/test MainKratos.py

and eventually import scipy or numpy from within that file.

@maceligueta could u try if you can reproduce? (you need to install the latest nuitka)

**Comment by maceligueta** [comment]
Three days compiling and it is still there...

**Comment by RiccardoRossi** [comment]
alternative solution with "pyinstaller" (which can be installed by pip3 install pyinstaller) 
Advantage is that it takes short for compilation

i created a file "runkratos.py"  similar to the one used for nuitka

~~~py

import scipy
import scipy.linalg
import scipy.sparse
import scipy.sparse.linalg
import matplotlib

import numpy
import sys
print("scipy version = ",scipy.version)
print("runkratos file ", sys.argv[1])
exec(open(sys.argv[1]).read())
~~~

and a file "test.py" that a user can change freely (which mocks our MainKratos.py)

~~~py
import KratosMultiphysics

import scipy
import scipy.linalg
import numpy
A = numpy.array([[1,2],[1,0]])
print(scipy.linalg.inv(A))

Asparse = scipy.sparse.csr_matrix(A)

aa = Asparse.tocoo()
print("aa = ",aa)
~~~

the compile command i used is

~~~
python3 ~/scratch/pyinstaller/pyinstaller-pyinstaller-55c8855/pyinstaller.py runkratos.py --add-data ~/kratos_install/KratosMultiphysics:./KratosMultiphysics --add-binary ~/kratos_install/libs/*:. -p .
~~~

i can run it by doing (and change test.py without recompiling)

~~~
./dist/runkratos/runkratos test.py 
~~~

**Comment by RiccardoRossi** [comment]
@jginternational any hope you can try what i proposed just above in windows? should take no time...

**Comment by maceligueta** [comment]
PyInstaller worked for me! The 'compilation' took 10 minutes, but it worked in the end, the cases run. 
I used Python 2.7 in this occasion so Instead of pip I had to use pip2.7. And once pyinstaller was operational, I directly ran the pyinstaller executable (instead of calling python with arguments).

**Comment by RiccardoRossi** [comment]
guess we can close this issue.

**Comment by maceligueta** [comment]
I just wanted to add here that I just packed Kratos for Windows by simply doing two steps

STEP 1:
`python -m PyInstaller runkratos.py`
STEP 2:
Copy the folders `libs `and `KratosMultiphysics `inside `dist/runkratos`

This second step of copying two folders was giving me many problems when adding it to the first sentence, so probably I will make a script which makes the copy after compiling the `runkratos.py`.

**Comment by maceligueta** [comment]
Unfortunately, not all the necessary files are in `libs `and `KratosMultiphysics `, for instance blas and lapack are missing, and probably many other files linked to Visual Studio, etc...
I guess scipy, numpy, etc... will work, but Kratos is still something which we need to pack manually or by means of a script... @RiccardoRossi
