### ISSUE TITLE
Missbehaviour regarding "interval" with loads in StructuralMechanicsApplication

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#6291]
Dear all,

@Rbravo555 is trying to reproduce a simple case (cantilever with a pressure load applied durint a certain time period [0, 3] s) and we have noticed that after the 3.0 s the load remains applied:

![imagen](https://user-images.githubusercontent.com/26402605/73082875-868e2580-3eca-11ea-99f1-c083ad01737a.png)

We have tried to solve this by:

1. Adding Damping -> Not working

1. Non-linear simulation  -> Not working

1. decrease the dt  -> Not working

1. using static simulation  -> Not working

1. using a Total Lagrangian element  -> Not working

So my impression is that the `assign_vector_by_direction_to_condition_process` is not working properly... Anyone knows why?

@Rbravo555 will upload the cases to test.

**Comment by philbucher** [comment]
I am pretty sure that you have to manually set the load to 0 again
The load is set to a value in the interval, but not resetted
You can print the value of the load to check

**Comment by AlejandroCornejo** [comment]
> 
> 
> I am pretty sure that you have to manually set the load to 0 again
> The load is set to a value in the interval, but not resetted
> You can print the value of the load to check

mmm this is what we were thinking, that the condition maintain its previous value. Isn't it more logical to set it as 0 if its beyond the interval? :)

**Comment by Rbravo555** [comment]
Once the pressure is manually set to zero, the behavior is as expected. 

![Screenshot from 2020-01-24 18-22-28](https://user-images.githubusercontent.com/46027276/73089486-9dd31000-3ed6-11ea-9e9a-bde9b8555e1c.png)


The model is here in any case:
 
[PreviousExample.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/4109757/PreviousExample.gid.zip)

**Comment by loumalouomega** [comment]
Huuuum, probably an error from my side (I think I did this). The solution
is easy but I cannot reach my computer until Sunday night (and fix this
from the phone is not trivial)

**Comment by loumalouomega** [comment]
This would affect other types of function loads BTW.

**Comment by philbucher** [comment]
how would you fix this @loumalouomega ?

**Comment by loumalouomega** [comment]
Creating a clear function and calling it when outside of the time interval (basically that)

**Comment by philbucher** [comment]
that makes sense to me, but what does "Clear" do in this case? This is not clear (:laughing:) to me
reset to a value? But what value?

**Comment by loumalouomega** [comment]
Don't worry about that, it is easy to fix

**Comment by RiccardoRossi** [comment]
guys, i think that mantaining the load is the expected behaviour and not a
bug...so please do not change this lighthearted...

if we want to change this we xan, but it needs to be
disccussed,communicated, etc

**Comment by RiccardoRossi** [comment]
the point is that this same fu ction is also used for prescribing inlet. in
that case you would expect to remove the fixity, but to leave the value as
"initial" for the folowing steps

**Comment by loumalouomega** [comment]
Yes, I was thinking about that. That can be solved with flags or auxiliar
variables

**Comment by loumalouomega** [comment]
> 
> the point is that this same fu ction is also used for prescribing inlet. in that case you would expect to remove the fixity, but to leave the value as "initial" for the folowing steps
> […](#)

@RiccardoRossi the process that sets the inlet and the one which sets the loads is different. One is assign_scalar_variable_process and the other one is assign_scalar_variable _to_entitities_process. The first one set on the historical variables and the second one in teh non-historicals. Th process to be modified is the second one

**Comment by philbucher** [comment]
But then the behavior is inconsistent between the two processes

**Comment by loumalouomega** [comment]
> 
> 
> But then the behavior is inconsistent between the two processes

And the nature of the two processes it is too. The historical values are expected to be the result of the problem, therefore the information feedback comes from the resolution of the problem not from an imposed value

**Comment by RiccardoRossi** [comment]
the point is that outside of the interval you simply do not touch any longer the value, so to me it makes sense that it remains to the value you set before and you evolve from there.

if you want to set a new value, for example 0, no problem, but then you need to tell what is the next value

**Comment by loumalouomega** [comment]
> 
> 
> the point is that outside of the interval you simply do not touch any longer the value, so to me it makes sense that it remains to the value you set before and you evolve from there.
> 
> if you want to set a new value, for example 0, no problem, but then you need to tell what is the next value

Therefore current implementation is right, in any case I would add an option to automatically clear after the interval is finished. Otherwise behaviours like this one may occur

**Comment by philbucher** [comment]
Well adding the option not only changes the behavior in sensitive parts of the code but is also redundant and inconsistent 
As Riccardo says, the desired behavior can be achieved already

**Comment by loumalouomega** [comment]
> 
> 
> Well adding the option not only changes the behavior in sensitive parts of the code but is also redundant and inconsistent
> As Riccardo says, the desired behavior can be achieved already

¯\_(ツ)_/¯

**Comment by RiccardoRossi** [comment]
An alternative solution would be to apply the load by table or by a function of time defined with an if

**Comment by loumalouomega** [comment]
> An alternative solution would be to apply the load by table or by a function of time defined with an if

Well, in  #6296 there is a correction assuming that the load must be applied only in the interval. I think the modification makes sense, as is not the same an initial condition than a load. Think first about the expected behavior, but if the load is not cleared, **which is the purpose of the interval in a load?**

**Comment by rubenzorrilla** [comment]
After going through the discussion, I think that @loumalouomega is pointed in the right direction when asking "which is the purpose of the interval in a load?". Unfortunately I think that the answer is completely problem dependent.

For instance, what a would expect in a common mechanical problem is that the load is null outside of the interval. However, this is not the case when solving a geomechanics problem as I would expect the preload to remain if it is not otherwise stated.

Having said this, I'd try to keep the same behaviour in all the processes as @philbucher suggests. Note that the distinction between the historical and non-historical data is rather easy for more or less advanced developers, but this might not the case for a newbie or for someone that is using Kratos directly from the GUI.

**Comment by loumalouomega** [comment]
> After going through the discussion, I think that @loumalouomega is pointed in the right direction when asking "which is the purpose of the interval in a load?". Unfortunately I think that the answer is completely problem dependent.
> 
> For instance, what a would expect in a common mechanical problem is that the load is null outside of the interval. However, this is not the case when solving a geomechanics problem as I would expect the preload to remain if it is not otherwise stated.
> 
> Having said this, I'd try to keep the same behaviour in all the processes as @philbucher suggests. Note that the distinction between the historical and non-historical data is rather easy for more or less advanced developers, but this might not the case for a newbie or for someone that is using Kratos directly from the GUI.

Thanks @rubenzorrilla

**Comment by RiccardoRossi** [comment]
Imagine that you want to have a load that is first growing and then released.

you make two processes, one that grows within and is considered within the same interval, and one that sets the load to zero and is applied in the second interval

**Comment by philbucher** [comment]
closing this as the current behavior is the expected one and the @KratosMultiphysics/technical-committee disagrees changing this as it would no longer be generic (e.g. for fluid would break things)

see also [here](https://github.com/KratosMultiphysics/Kratos/pull/6296#pullrequestreview-432152130)

the correct solution is to specify two process for each interval (the second one is used to set the loads back to zero)
