### ISSUE TITLE
Quadratic quadrilaterals have errors in Kratos

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#632]
After checking an small test example with quadrilaterals with 8 and 9 nodes, the results where depicted in a wrong way in GiD. 

![quad8](https://user-images.githubusercontent.com/23210788/28311202-30e7fa20-6baf-11e7-951b-fd7823e024bd.png)

![quad9](https://user-images.githubusercontent.com/23210788/28311207-3527c43a-6baf-11e7-9266-ed6d8893e52b.png)

I don't know if it is only something related to the post-processing, but maybe there is also some error in the geometry.  Here the example using the GiD interface for the Structural app.

[static_quadratic_quad_test.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/1155410/static_quadratic_quad_test.gid.zip)

**Comment by loumalouomega** [comment]
I will check it, in this kind of cases it is recommended to use the ASCII output for GiD to check that the error is not just in the postprocess

**Comment by josep-m-carbonell** [comment]
Here you have the ASCII file :+1:
[static_quadratic_quad_test_0.post.res.zip]
(https://github.com/KratosMultiphysics/Kratos/files/1155558/static_quadratic_quad_test_0.post.res.zip)

**Comment by loumalouomega** [comment]
The problem is not in the gid output, at least I can't see anything wrong. The number of gauss points is 9 and appears that way in the output. 

The only thing that I detected is that the loads are inserted directly on the nodes of the geometry (the middle node of the side is not having load)

**Comment by loumalouomega** [comment]
I changed the point loads with line loads, still not good results. 
![imagen](https://user-images.githubusercontent.com/19991680/28315050-3355720c-6bbd-11e7-96fb-da22584794ea.png)

The only thing make me be suspicious of the geometry is that the loaded nodes are not deformed in a "solidarity" way

**Comment by RiccardoRossi** [comment]
as a test, without solving anything, apply a displacement field which varies quadratically in space.

for example  
        ux = x^2 
        uy =y^2

the gradient of this varies linearly in space. It should be captured exactly by using higher order elements.

i mean
    eps_x = 2x
    eps_y = 2y
    eps_xy = 0

so that the stress can also be computed exactly. 
Is the result exact in this case?

**Comment by loumalouomega** [comment]
@RiccardoRossi I will do a test following the tests already developed in the structural

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/28327260-2dd42a0a-6be3-11e7-9039-bd6373f53196.png)
Nope, this is what I get with the displacement field you suggested

**Comment by RiccardoRossi** [comment]
@loumalouomega can u add the new test to the tests (mark it as expected failure)

the point is that i am wondering if it is an issue with the order in which the GP results are plotted or if it is a wrong result

for this reason i would need to know xg and yg **for each of the gauss point** to verify if the result on the gauss fits to the expect one -- if this happens the error would not be in the calculation but rather in the output.

On the contrary if this is not the case, then the error will be most probably in the shape function values/derivatives

on the contrary

**Comment by loumalouomega** [comment]
Can anyone tell me where the shape functions and derivatives was taken? I have been checking, and the implementation doesn't correspond with respect to https://ses.library.usyd.edu.au/bitstream/2123/709/8/adt-NU20060210.15574814appendixD.pdf

Additionally there is a commentary in the code:

~~~c++
    /**
     * :TODO: implemented but not yet tested
     */
~~~

**Comment by RiccardoRossi** [comment]
@loumalouomega did u try what i suggested?

in any case apart for what i am suggesting we should
* create a patch test with a quadratic geometry
* implement a check for the quadratic geometry

**Comment by loumalouomega** [comment]
I tried, the result is the one I shown.

I think that the origin of the problem is in the geometry, and I would like to know the reference used to implement it, because that way it would be easier to correct

**Comment by loumalouomega** [comment]
For example the pdf I sent you the orther is different, which means I need to reorder all the shape functions in the reference I found in order be able to implement anything

**Comment by RiccardoRossi** [comment]
so, i don't know what is the reference.

i think that the ordering that was used is like that of GiD (in the GiD user manual)

actually you can check what is the ordering by checking how it is written in the mdpa.

still, try to print out

      xgauss ygauss epsilon

this will tell you have the correct result or not

**Comment by RiccardoRossi** [comment]
just checked on the GiD manual.

the input numeration is:

     4 7 3
     8 9 6
     1 5 2
for the 9 noded element
or

     4 7 3
     8    6
     1 5 2
for the 8 noded element.

i **think**  (not sure though) that this is according to this reference
http://www.colorado.edu/engineering/CAS/courses.d/IFEM.d/IFEM.Ch18.d/IFEM.Ch18.pdf

**Comment by loumalouomega** [comment]
I am checking and correcting the errors i found, I will test and commit if this changes make it work

**Comment by loumalouomega** [comment]
I rewrote the geometry and I am getting the same results, the only thin is that now the code is more readable?, do I PR this?

**Comment by RiccardoRossi** [comment]
regarding the PR, no problem for me. Not urgent neither if the results are not different

having said this, and as i was suggesting before the things to be done would be 

1. Can u post the test you made with the quadratic displacement prescribed at any node?
2. writing the test for the quadratic geometries similar to the ones that are already there?
3. try to implement a simple patch test

**Comment by loumalouomega** [comment]
Solved, the problem was in the `gid_gauss_container.h`. The quadrature was added in the `gid_io.h`, but not in the `gid_gauss_container.h`. I will do the proper PR.

~~~cpp
            else if( mGidElementFamily == GiD_Quadrilateral && mSize == 9 )
            {
                GiD_fBeginGaussPoint( MeshFile, mGPTitle, GiD_Quadrilateral, NULL, 9, 0, 0 );
                GiD_fWriteGaussPoint2D( MeshFile, -std::sqrt(3.00/5.00) , -std::sqrt(3.00/5.00));
                GiD_fWriteGaussPoint2D( MeshFile,  0.00 , -std::sqrt(3.00/5.00) );
                GiD_fWriteGaussPoint2D( MeshFile,  std::sqrt(3.00/5.00) , -std::sqrt(3.00/5.00) );
                GiD_fWriteGaussPoint2D( MeshFile, -std::sqrt(3.00/5.00), 0.00 );
                GiD_fWriteGaussPoint2D( MeshFile,   0.00 , 0.00 );
                GiD_fWriteGaussPoint2D( MeshFile,  std::sqrt(3.00/5.00), 0.00);
                GiD_fWriteGaussPoint2D( MeshFile, -std::sqrt(3.00/5.00), std::sqrt(3.00/5.00) );
                GiD_fWriteGaussPoint2D( MeshFile,  0.00, std::sqrt(3.00/5.00) );
                GiD_fWriteGaussPoint2D( MeshFile,  std::sqrt(3.00/5.00), std::sqrt(3.00/5.00) );
                GiD_fEndGaussPoint(MeshFile);
            }
~~~

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/28364543-27acf6fa-6c85-11e7-98d2-6339256ce8ae.png)

**Comment by loumalouomega** [comment]
Done, please proceed with the PR

**Comment by RiccardoRossi** [comment]
does your "pull test" work correctly now? i am asking since it looks like the deformed shape is not correct (the center node movement does not look convincing)

**Comment by loumalouomega** [comment]
The only figure you need to look is the one with Syy linear

**Comment by loumalouomega** [comment]
This can be closed

**Comment by RiccardoRossi** [comment]
@loumalouomega i don't think you are right. I think we have a problem in the transformation of distributed forces to nodal forces, at least this is what it looks like from the picture you posted

**Comment by loumalouomega** [comment]
@RiccardoRossi I found the error in the line condition, the normal was not working for the quadratic line. Now I use the one from the geometry class.

![imagen](https://user-images.githubusercontent.com/19991680/28377527-5670a5ea-6cad-11e7-9710-9b4f56b0fd4a.png)

**Comment by RiccardoRossi** [comment]
well done.

**Comment by pooyan-dadvand** [comment]
@loumalouomega Whould please make the same bugfix for the release?

**Comment by loumalouomega** [comment]
The only thing is that I am little bit lost, too many cherry-picks to apply. Is it exist any method to pick just files from the master instead of using cherry-picks?

**Comment by pooyan-dadvand** [comment]
The "correct way" of a bug fix is to use the version from release, bug fix it and then also merge it to the master. But not other way around. 
In your situation I'm not sure what is the best solution but as long as you know exactly where to modify (excluding other cleanup changes) you may do it also in the release.

**Comment by josep-m-carbonell** [comment]
@loumalouomega 
Maybe you already know it but sometimes the cleaner way is to do it manually. Look into the changes between branches and copy the modified files individually. Then you can paste them into the branch which you want to have the last changes and commit the changes to that branch.

Meld is a good tool to compare your local branches and detect changed files:
```
sudo apt-get install meld
git config --global diff.tool meld
git branch (to see the local branches checked out in your computer)
git difftool -d master..feature_branch
```

**Comment by loumalouomega** [comment]
@josep-m-carbonell Thanks a lot

**Comment by loumalouomega** [comment]
Do we consider this issue as solved?

**Comment by josep-m-carbonell** [comment]
From my side, yes.

**Comment by josep-m-carbonell** [comment]
@loumalouomega   did you merge the corrections to the Release 5.1 ???

**Comment by loumalouomega** [comment]
#678 It is here

**Comment by josep-m-carbonell** [comment]
Ok
