### ISSUE TITLE
Quality Control Logs

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#634]
I want to add a new category for Quality Control to the logs categories. The idea is to have a log messages with this category which can be filtered but a log output. Also this would be accompanied with a set of macros which can be enabled and disabled in compile time. (so you can have a binary without such a logs) a sample use would be:

```c++
KRATOS_QUALITY_CONTROL_LOGGER << "Velocity in reference node" << reference_node.GetSolutionStepsValue(VELOCITY) << std::endl; 
```

@KratosMultiphysics/team-maintainers any comments about this design?

**Comment by loumalouomega** [comment]
This remembers me to #425

**Comment by pooyan-dadvand** [comment]
They are not the same... Here what is important is to give a different output when we are running with regression tests for quality control (as a complement to our unittest and similar to our old benchmarking examples)

**Comment by loumalouomega** [comment]
OK, then

**Comment by pooyan-dadvand** [comment]
So I will do it in this way.
