### ISSUE TITLE
The Stages of Geometry import

### ISSUE THREAD

**Issue by tteschemacher** [KratosMultiphysics/Kratos#6343]
Hi all,

there was recently a lot of discussion and development in the geometries to allow CAD capabilities within the model_part. I want to summarize in the following some of the important steps which are required to run an IGA analysis. However, those might be the least use cases for the new CAD kernel. It opens to use the CAD kernel additionally as interface, as the exact geometry which can be later be used to be tesselated, meshed, or whatever.

It somehow can be fitted in the existent stages of the analysis_stage. However, at this stage it might be also good to discuss if we want to precise the steps. This is also driven by the new possibilities that we have now, that we can also store the fem geometries inside the kernel.

![StagesOfGeometryImport](https://user-images.githubusercontent.com/25983517/73721883-f759fb00-4770-11ea-999a-b41997aa4684.png)

Please feel free to ask and discuss everything which comes in your minds! Thanks.

**Comment by loumalouomega** [comment]
Do we have any library/implementation planned to mesh the geometries?

**Comment by RiccardoRossi** [comment]
hi Tobi,

good initiative...but i.am.nit 100% sure of what we are discussing right
now 😅

**Comment by tteschemacher** [comment]
> Do we have any library/implementation planned to mesh the geometries?

Basically, the EXAQUTE goes in this direction. I don't know a specific implementation which is planned. But there will definitely come something. I think there are also many things already existent which we can bring in shape here. It will be also required for fast e.g. contact detection (for the initial guess).

> good initiative...but i.am.nit 100% sure of what we are discussing right

Good point ;). So it is a bit a information of what is already here and planned. Some of the features are within open PRs (CadJsonInput #6163, the IGA processes #6277, the output of integration points is coming ). I think we should be clear what we do at what time. In #6279 I pointed out a way how to run IGA. It is possible but it does not really fit in the respective functions. As the here mentioned functions are needed in anyway, the question is if we can find a way to express it clearer. I can put everything in InportModelPart, but this might not be the cleanest.

Maybe we'll put something for ImportNonAnalysisModel (CAD or FEM, if it is needed for mesh purposes only and without dummy elements), PrepareNonAnalysisModel (meshing, find IGA integration points, ...), ImportModelPart (read in mdpa or from mesh and integration points to elements and conditions) then PrepareModelPart (Set initially needed things, assign the properties, e.g. MPM put the elements to the correct background, ...).

This is just a suggestion, it will not open many new features, it just clarifies better what should be done, when...

**Comment by tteschemacher** [comment]
Just to avoid confusion, the names are not yet good. (red: FEM, green: IGA, blue: MPM)

![Presentation1](https://user-images.githubusercontent.com/25983517/73803804-959b9e80-480d-11ea-84e8-c97ae30abc07.png)

**Comment by philbucher** [comment]
I guess what you say makes sense

If e.g. I want to import an STL and mesh it with a Kratos-Mesher (I know it doesn't exist but its likely it will), then how would this look like?
Importing the STL in `ImportGeometryModel` and doing the meshing in `PrepareGeom`?

**Comment by tteschemacher** [comment]
Yes so the stages might be:
- ImportGeometryModel (ModelPart has now geometries and nodes)
- PrepareGeometryModel (Meshing, ... just make stuff analysis suitable)
- ImportModelPart (Putting Elements at the right position)
- PrepareModelPart (Add properties/ ...)

I think sometimes it will be difficult to separate between 2. and 3. because this is usually one step. If this is not possible one could clarify that ImportModelPart is more for new read ins and PrepareGeom for the conversion from the existant model.

**Comment by loumalouomega** [comment]
>     * PrepareGeometryModel (Meshing, ... just make stuff analysis suitable)

Just as curiosity, recently I found this: https://github.com/PyMesh/PyMesh

**Comment by RiccardoRossi** [comment]
I like the 4 stages you propose

**Comment by pooyan-dadvand** [comment]
Very nice overview and I agree that those steps are necessary. Now the question is how we can add it to the existing structure. I see different options:
1. Having a separate stage for preparing the model, geometry, etc.
2. Creating additional methods in stage for those steps and have different Modelers for different scenarios (Meshing, Reloading, cleaning, etc...)
3. Reusing the processes. But I'm afraid that we should extend their interface for it.

**Comment by tteschemacher** [comment]
@pooyan-dadvand thank you for that summary:

I would say 1. and 3. comes along together. As soon as we extend the interfaces of the processes we introduce new stages. Within the processes we should rely on modelers to make it as coherent as possible...

**Comment by philbucher** [comment]
The @KratosMultiphysics/technical-committee had a long discussion abt this yesterday, but it seems like we didn't write down our thoughts.

Our main concern with adding new functions to the `AnalysisStage` is that we cannot know all usecases in the future. E.g. meshing, re-meshing etc. Would we also add new functions for this if it doesn't fit into the current design?

Essentially we thought of moving everything that imports/creates a `ModelPart` to an entirely separate class (we called it Modeler but I think this exists already, anyway name does not matter for now)
I.e. we would have different classes of this for different tasks
I.e. we could have a simple Modeler that only imports a ModelPart from an mdpa-file
Another modeler would be the geometry/CAD related things, with or without the creation of the integration points
Again a different one would be for the Voxel-mesher that @pooyan-dadvand works on atm.

opinions are welcome :)

**Comment by philbucher** [comment]
I just saw #6520 , seems like we are having the same ideas

**Comment by rubenzorrilla** [comment]
> The @KratosMultiphysics/technical-committee had a long discussion abt this yesterday, but it seems like we didn't write down our thoughts.
> 
> Our main concern with adding new functions to the `AnalysisStage` is that we cannot know all usecases in the future. E.g. meshing, re-meshing etc. Would we also add new functions for this if it doesn't fit into the current design?
> 
> Essentially we thought of moving everything that imports/creates a `ModelPart` to an entirely separate class (we called it Modeler but I think this exists already, anyway name does not matter for now)
> I.e. we would have different classes of this for different tasks
> I.e. we could have a simple Modeler that only imports a ModelPart from an mdpa-file
> Another modeler would be the geometry/CAD related things, with or without the creation of the integration points
> Again a different one would be for the Voxel-mesher that @pooyan-dadvand works on atm.
> 
> opinions are welcome :)

I'd like to add the coupled problems into the discussion. Aside of the "modeler type", we need to consider the case in which multiple imports of the same type (e.g. reading a .mdpa) occur.

(just in case I didn't explain myself properly, I'm referring to those cases in which the Python solver do more than one import).

**Comment by oberbichler** [comment]
> Essentially we thought of moving everything that imports/creates a ModelPart to an entirely separate class

Sounds similar to what we have done in the CAD morphing tool. 👍

**Comment by pooyan-dadvand** [comment]
@tteschemacher would you please provide a prototype of the Modeler capable of handling your requirements?

**Comment by tteschemacher** [comment]
In #6529 you can find my thoughts for the modeler interfaces. Those are the ones required for the beginning of the analysis.

**Comment by RiccardoRossi** [comment]
is this still active?

**Comment by RiccardoRossi** [comment]
closing since i think this is already solved. please reopen if i am wrong about this

**Comment by tteschemacher** [comment]
Yes, this is resolved.
