### ISSUE TITLE
MultiPoints Constraints (ContactStructuralMechanicsApplication)

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#6359]
Dear developers,

I wanted to use the multipoint constraint (MPC) modules and followed the corresponding tutorial 
(https://github.com/KratosMultiphysics/Kratos/wiki/%5BKratosAPI%5D-MultiPoint-Constraint-(MPC)-interface). However, it appears that one cannot follow it as it is, since the 
contact_structural_mechanics_analysis.py does not exist anymore. 
What should be done in this case?

Thanks a lot!
Pavel

**Comment by loumalouomega** [comment]
Now it is just simply structural_mechanics_analysis.py, we unified the scripts. I will update later the Wiki

**Comment by playpaolo** [comment]
Thank you @loumalouomega ! But is this structural_mechanics_analysis.py inside StructuralMechanicsApplication or inside ContactStructuralMechanicsApplication?

**Comment by loumalouomega** [comment]
There is only one at StructuralMechanicsApplication now

**Comment by playpaolo** [comment]
Okay, so the entire example in wiki should refer now to StructuralMechanicsApplication, not ContactStructuralMechanicsApplication... 
Thank you @loumalouomega

**Comment by Rbravo555** [comment]
Related the multipoint constraints, I think the file **StructuralMechanicsApplication/tests/test_multipoint_contstraints.py** is outdated, since it calls the **KratosMultiphysics.StructuralMechanicsApplication.ApplyMultipointConstraintsProcess** which does not exist

**Comment by loumalouomega** [comment]
Huuum, probably, when that process was removed?

**Comment by loumalouomega** [comment]
In any case that is not in the ContactStructuralMechanicsApplication

**Comment by Rbravo555** [comment]
My bad, the outdated test is in the StructuralMechanicsApp, not ContactStructuralMechanics. I looked for a similar issue instead of opening a new one. 

I dont know when the ApplyMultipointConstraintsProcess was removed, I was just trying to build a similar test and discovered it is not there anymore...

**Comment by philbucher** [comment]
@adityaghantasala do you know what happened to this?
AFAIK it was moved to the core but I dont remember any more

maybe also @KlausBSautter knows

**Comment by adityaghantasala** [comment]
Yes the linear master slave constraints are moved to core . 

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/test_linear_constraints.py

https://github.com/KratosMultiphysics/Kratos/blob/b9ba3a510c6fedf43678b627b18e42b11230e0d9/kratos/tests/test_KratosCore.py#L131

We can remove the one in the StructuralMechanicsApplication.

**Comment by rubenzorrilla** [comment]
Closing as this is already solved.
