### ISSUE TITLE
Master Compilation uninitialized error

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#6372]
Hi, I am compiling with the following flag:
`-Werror=maybe-uninitialized"`

and get compilation errors when trying to compile the current master.

> s.cpp.o
> In file included from /home/klaus/software/Kratos_Dev/kratos/tests/cpp_tests/spatial_containers/test_geometrical_objects_bins.cpp:21:0:
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h: In member function ‘void Kratos::GeometricalObjectsBins::AddObjectsToCells(TIteratorType, TIteratorType) [with TIteratorType = boost::iterators::indirect_iterator<__gnu_cxx::__normal_iterator<Kratos::intrusive_ptr<Kratos::Element>*, std::vector<Kratos::intrusive_ptr<Kratos::Element>, std::allocator<Kratos::intrusive_ptr<Kratos::Element> > > >, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default, boost::iterators::use_default>]’:
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:330:53: error: ‘max_position[2]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>              for(std::size_t k = min_position[2] ; k < max_position[2] ; k++){
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:331:57: error: ‘max_position[1]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>                  for(std::size_t j = min_position[1] ; j < max_position[1] ; j++){
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:332:61: error: ‘max_position[0]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>                      for(std::size_t i = min_position[0] ; i < max_position[0] ; i++){
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:134:65: error: ‘min_position[2]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>          const std::size_t index = I + J * mNumberOfCells[0] + K * mNumberOfCells[1] * mNumberOfCells[0];
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:327:40: note: ‘min_position[2]’ was declared here
>              array_1d< std::size_t, 3 > min_position;
>                                         ^~~~~~~~~~~~
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:327:40: error: ‘min_position[1]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
> /home/klaus/software/Kratos_Dev/kratos/spatial_containers/geometrical_objects_bins.h:150:70: error: ‘min_position[0]’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
>          result.GetMaxPoint()[0] = mBoundingBox.GetMinPoint()[0] + (I + 1) * mCellSizes[0];

@philbucher asked me to create an issue about that. Could you link the responisble persons?

Klaus

**Comment by philbucher** [comment]
this is @pooyan-dadvand: #6141

**Comment by philbucher** [comment]
no idea why this is not picked up in Travis ...

**Comment by philbucher** [comment]
so it seems to be related to the build-type: in Custom they don't show up, but in Release they do
@roigcarlo any idea what is happening?

**Comment by philbucher** [comment]
maybe has sth to do with optimization flags?

**Comment by roigcarlo** [comment]
Doubt it, but it may happen if its inlining functions or moving code, I will take a look tomorrow

**Comment by pooyan-dadvand** [comment]
Sorry guys!

I am also surprised why we didn't get the error before. Neither the warning in my compilation...
