### ISSUE TITLE
Python version for the linux release

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#638]
In the aim of using standard components, the release version of linux is being compiled with libraries from the official ubuntu 16.04 LTS repositories. (Except for the compiler which has been downgraded to gcc 4.9 to increase compatibility with old libgc's)

Sadly, the boost version from those repositories (1.58) has only python2 support. This can be solved using one of the boost from the developer ppa repos ( 1.59 for example)

Which solution would fit us more?

**Comment by pooyan-dadvand** [comment]
I would go for python3... But I'm not sure if is the best decision.

@KratosMultiphysics/technical-committee ?

**Comment by RiccardoRossi** [comment]
+1 for python3

**Comment by roigcarlo** [comment]
:+1:

**Comment by maceligueta** [comment]
Will this release work on older Ubuntus (<16)? 
Some time ago I packed a linux version of Kratos and many people recommended me to use the oldest possible linux distribution. In such a way that it is compatible with later versions of the OS's.

**Comment by RiccardoRossi** [comment]
Hello,
      a problem here is that we are now assuming c++11, hence we need gcc 4.9+ and corresponding glibc. I don't think we can rely on anything older than 16.04 to work well. (14.04 packs gcc 4.8 which is not fully compatible with c++11).

**Comment by loumalouomega** [comment]
Support to 14.04 finishes in 2019, this means we are supposed to stay in gcc4.8 because of that?

**Comment by pooyan-dadvand** [comment]
There are parts of the code that are not compatible with gcc 4.8 anymore...

**Comment by roigcarlo** [comment]
5.1.0 Rc is ready and still no list of changes / readme...
