### ISSUE TITLE
Embedded CFD solver seems to have troubles capturing sharp edges, suggestions?

### ISSUE THREAD

**Issue by andreas-apostolatos** [KratosMultiphysics/Kratos#6383]
Hello everybody,

we are trying to use the embedded CFD solver to compute the flow around a twisted building which has sharp corners. Although the smooth part of the geometry can be nicely reproduced, the level set function seems to have troubles identifying the sharp corners resulting in a weird oscillatory behaviour.

You can download the aforementioned case under,

https://gigamove.rz.rwth-aachen.de/d/id/6CP2zTDU2re58D

I have also added the .msh file of the skin model part representing the building where you can see that the surface tessellation is quite accurate. 

Do you have any ideas how we can overcome this problem? Any suggestion is more than welcome!

Kind Regards,
Andreas

**Comment by RiccardoRossi** [comment]
sharp corners will always be rounded when you use a level set representation.
you can control the level of error by adjusting the mesh resolution. (for example you could add a higer refineement where the curvature of the distance field is higher)

**Comment by andreas-apostolatos** [comment]
> sharp corners will always be rounded when you use a level set representation.
> you can control the level of error by adjusting the mesh resolution. (for example you could add a higer refineement where the curvature of the distance field is higher)

Hello Riccardo! Thanks for the hint, this is what I also thought. However, in this case the latter results into an oscillating "cutting" of the geometry along the sharp edges which we believe it creates spurious flow solutions which in turns may result into wrong representation of the drag force over which we wish to optimize.

The refinement of the fluid discretization on this other hand, does not seem to fix the problem, it rather creates this spurious "cuts" with smaller amplitudes and higher frequencies along the sharp edges.

We though that maybe mmg could be used by inserting elements along those edges in a body-fitted manner, working as a feature preserving method, which would be the only solution in respresenting the sharp corners exactly.

Thanks once more for the hint!

Greetings,
Andreas

**Comment by rubenzorrilla** [comment]
Hey @andreas-apostolatos !

> 
> The refinement of the fluid discretization on this other hand, does not seem to fix the problem, it rather creates this spurious "cuts" with smaller amplitudes and higher frequencies along the sharp edges.
> 
This might be a small cut instability problem. I'd use a large `distance_threshold` in the json settings of the embedded solver.

> We though that maybe mmg could be used by inserting elements along those edges in a body-fitted manner, working as a feature preserving method, which would be the only solution in respresenting the sharp corners exactly.
> 
Just mentioning that if you insert nodes in the zero isosurface of the level set (which I agree is the unique way to preserve the sharp edges), it makes no sense to use the embedded formulation any more as 0 values of the distance are always ill-conditioned.
We have already tested this same approach to create body-fitted meshes from poorly conditioned input geometries. I think that your use case is pretty similar so  I think it is worth it to try.

**Comment by andreas-apostolatos** [comment]
> Hey @andreas-apostolatos !
> 
> > The refinement of the fluid discretization on this other hand, does not seem to fix the problem, it rather creates this spurious "cuts" with smaller amplitudes and higher frequencies along the sharp edges.
> 
> This might be a small cut instability problem. I'd use a large `distance_threshold` in the json settings of the embedded solver.
> 
> > We though that maybe mmg could be used by inserting elements along those edges in a body-fitted manner, working as a feature preserving method, which would be the only solution in respresenting the sharp corners exactly.
> 
> Just mentioning that if you insert nodes in the zero isosurface of the level set (which I agree is the unique way to preserve the sharp edges), it makes no sense to use the embedded formulation any more as 0 values of the distance are always ill-conditioned.
> We have already tested this same approach to create body-fitted meshes from poorly conditioned input geometries. I think that your use case is pretty similar so I think it is worth it to try.

Hey @rubenzorrilla !

Thanks a lot for taking time and thought to give hints :)

Out colleagues from the math department believe that with such oscillatory behaviour along the sharp edges the sensitivities make no sense because for example the computed drag (whose minimization is our objective) will be dominated by noise in this case.

I will try your hint regarding setting the distance_threshold to a high value, see what comes out of it and let you know.

So far, the embedded solver worked very robustly even if there are elements whose boundaries are aligned with the embedded object, really great job there :) I had a 2D example where the mmg produced elements body-fitted with the embedded object and the simulation ran seamlessly.

This is the next thing to try out, once I get the mmg running with my scripts. However, I am not sure if one can set the mmg solver to produce elements along feaure lines, maybe @marcnunezc has some ideas hopefully here. We don't want to refine blindly around the object but only along the sharp edges.

Gracias!
Andreas

**Comment by rubenzorrilla** [comment]
> > Hey @andreas-apostolatos !
> > > The refinement of the fluid discretization on this other hand, does not seem to fix the problem, it rather creates this spurious "cuts" with smaller amplitudes and higher frequencies along the sharp edges.
> > 
> > 
> > This might be a small cut instability problem. I'd use a large `distance_threshold` in the json settings of the embedded solver.
> > > We though that maybe mmg could be used by inserting elements along those edges in a body-fitted manner, working as a feature preserving method, which would be the only solution in respresenting the sharp corners exactly.
> > 
> > 
> > Just mentioning that if you insert nodes in the zero isosurface of the level set (which I agree is the unique way to preserve the sharp edges), it makes no sense to use the embedded formulation any more as 0 values of the distance are always ill-conditioned.
> > We have already tested this same approach to create body-fitted meshes from poorly conditioned input geometries. I think that your use case is pretty similar so I think it is worth it to try.
> 
> Hey @rubenzorrilla !
> 
> Thanks a lot for taking time and thought to give hints :)
> 
> Out colleagues from the math department believe that with such oscillatory behaviour along the sharp edges the sensitivities make no sense because for example the computed drag (whose minimization is our objective) will be dominated by noise in this case.
> 
> I will try your hint regarding setting the distance_threshold to a high value, see what comes out of it and let you know.
> 
> So far, the embedded solver worked very robustly even if there are elements whose boundaries are aligned with the embedded object, really great job there :) I had a 2D example where the mmg produced elements body-fitted with the embedded object and the simulation ran seamlessly.
> 
> This is the next thing to try out, once I get the mmg running with my scripts. However, I am not sure if one can set the mmg solver to produce elements along feaure lines, maybe @marcnunezc has some ideas hopefully here. We don't want to refine blindly around the object but only along the sharp edges.
> 

I think that the ones that can bring some light with this regard are @swenczowski and @NicolaGermano .

**Comment by swenczowski** [comment]
Hello everybody,

though I am afraid that I will not be able to help much, I can simply share some of my experience that I gained while trying to create city models:

What worked best was an iterative process where the geometry was slowly extended. As you can see in the figure below (left column), the mesh refinement concentrates around the sharp corners in the geometry. Also, the computational effort does not explode.  

![grafik](https://user-images.githubusercontent.com/45034120/74101040-ce04ea80-4b35-11ea-8006-3148ef1389b7.png)

This approach could be transferred to whole city models.

![grafik](https://user-images.githubusercontent.com/45034120/74101100-4d92b980-4b36-11ea-8343-82df65e16656.png)

Unfortunately, this is still far from obtaining perfectly sharp edges. However, with an increasing number of iterations it becomes better and better. Probably @NicolaGermano has already improved this technique. In case it goes into the right direction, we are happy to provide more description.

**Comment by andreas-apostolatos** [comment]
> Hello everybody,
> 
> though I am afraid that I will not be able to help much, I can simply share some of my experience that I gained while trying to create city models:
> 
> What worked best was an iterative process where the geometry was slowly extended. As you can see in the figure below (left column), the mesh refinement concentrates around the sharp corners in the geometry. Also, the computational effort does not explode.
> 
> ![grafik](https://user-images.githubusercontent.com/45034120/74101040-ce04ea80-4b35-11ea-8006-3148ef1389b7.png)
> 
> This approach could be transferred to whole city models.
> 
> ![grafik](https://user-images.githubusercontent.com/45034120/74101100-4d92b980-4b36-11ea-8343-82df65e16656.png)
> 
> Unfortunately, this is still far from obtaining perfectly sharp edges. However, with an increasing number of iterations it becomes better and better. Probably @NicolaGermano has already improved this technique. In case it goes into the right direction, we are happy to provide more description.

Dear @swenczowski ,

thank you very much for your contribution to the discussion. I would be very keen on learning more about how you tackled the problem. Could you please share with me some more information regarding how to obtain a finer mesh around the sharp edges of an embedded geometry?

Thanks once more!

Kind Regards,
Andreas

**Comment by qaumann** [comment]
Dear @andreas-apostolatos,

I am not sure if this is still valid, but I used the `LocalRefineTetrahedraMesh` method in my master's thesis to get a better local representation of the embedded geometry. The edges will not be perfectly sharp though.
![grafik](https://user-images.githubusercontent.com/27352976/74130553-986a0b00-4be2-11ea-81ae-c679c05e4ab3.png)
![grafik](https://user-images.githubusercontent.com/27352976/74130654-d6672f00-4be2-11ea-9c39-1bd3296c11a2.png)
This is the script I used
```python
#prepare refinement
nodal_neighbour_search = FindNodalNeighboursProcess(self.model_part,20,20)
nodal_neighbour_search.Execute()

###perform the refinement
Refine = LocalRefineTetrahedraMesh(self.model_part)
refine_on_reference = False;
interpolate_internal_variables = False;
Refine.LocalRefineMesh(refine_on_reference,interpolate_internal_variables)    

###recompute the neighbours since they changed due to the creation of new nodes
nodal_neighbour_search.ClearNeighbours()
nodal_neighbour_search.Execute()
```

**Comment by andreas-apostolatos** [comment]
> Dear @andreas-apostolatos,
> 
> I am not sure if this is still valid, but I used the `LocalRefineTetrahedraMesh` method in my master's thesis to get a better local representation of the embedded geometry. The edges will not be perfectly sharp though.
> ![grafik](https://user-images.githubusercontent.com/27352976/74130553-986a0b00-4be2-11ea-81ae-c679c05e4ab3.png)
> ![grafik](https://user-images.githubusercontent.com/27352976/74130654-d6672f00-4be2-11ea-9c39-1bd3296c11a2.png)
> This is the script I used
> 
> ```python
> #prepare refinement
> nodal_neighbour_search = FindNodalNeighboursProcess(self.model_part,20,20)
> nodal_neighbour_search.Execute()
> 
> ###perform the refinement
> Refine = LocalRefineTetrahedraMesh(self.model_part)
> refine_on_reference = False;
> interpolate_internal_variables = False;
> Refine.LocalRefineMesh(refine_on_reference,interpolate_internal_variables)    
> 
> ###recompute the neighbours since they changed due to the creation of new nodes
> nodal_neighbour_search.ClearNeighbours()
> nodal_neighbour_search.Execute()
> ```

Dear @qaumann ,

thank you very much for your help! It is understood that the level set function can not exactly reproduce sharp edges. What we want is to only locally refine around the sharp edges so that artifacts are less pronounced.

Can the solution you propose be applied only to sharp edges/corners and if yes could you please share a small example?

Thanks a lot once more!

Greetings,
Andreas

**Comment by RiccardoRossi** [comment]
@andreas-apostolatos 

my advice is the following
1 - compute the gradient of the distance (there is a function to compute it) and normalize it
2 - compute the curvature as the divergence of the unit gradient
3 - choose a target element size depending on the curvature
4 - remesh
5 - recompute distance from surface
6 - go back to 1 and loop until you reach the target accuracy

**Comment by qaumann** [comment]
@andreas-apostolatos 

Sorry I forgot to mention that the script was run iteratively, like Riccardo proposed in his comment above. This is the GiD model I used back then, but unfortunately I cannot find the actual Python script anymore. The snippet above should do the trick nevertheless.

[castle01.zip](https://github.com/KratosMultiphysics/Kratos/files/4180748/castle01.zip)

**Comment by andreas-apostolatos** [comment]
> @andreas-apostolatos
> 
> my advice is the following
> 1 - compute the gradient of the distance (there is a function to compute it) and normalize it
> 2 - compute the curvature as the divergence of the unit gradient
> 3 - choose a target element size depending on the curvature
> 4 - remesh
> 5 - recompute distance from surface
> 6 - go back to 1 and loop until you reach the target accuracy

Thanks a lot for the hints @RiccardoRossi !

**Comment by andreas-apostolatos** [comment]
> @andreas-apostolatos
> 
> Sorry I forgot to mention that the script was run iteratively, like Riccardo proposed in his comment above. This is the GiD model I used back then, but unfortunately I cannot find the actual Python script anymore. The snippet above should do the trick nevertheless.
> 
> [castle01.zip](https://github.com/KratosMultiphysics/Kratos/files/4180748/castle01.zip)

@qaumann thank you very much for the hints. I am going to try implementing the proposed methodolody.

**Comment by marcnunezc** [comment]
Hi Andreas!

Using MMG should definitely help, especially since one has the freedom to select on which manner to refine the whole domain. Taking a look at your model, we can see that the structured domain extends through the whole domain. 


![image](https://user-images.githubusercontent.com/32136457/74146314-21903a80-4c01-11ea-9eea-917b9efcdb4b.png)

While this might be interesting in order to capture all the features happening behind the building, we should be able to get the same level of detail using the MMG library but in a much more efficient manner. 
Also, if we only focus on the description of the geometry  and we take a look at your cut domain, it feels like the element size is still not enough to properly define the edges of your geometry (the height of the elements is aprox 3 units). 
![image](https://user-images.githubusercontent.com/32136457/74146448-5f8d5e80-4c01-11ea-80fa-7338642af294.png)


Next I'll show some results using mmg on this case:
## MMG 
As a first approach, I decided to run mmg with the following sizing parameters:

```
            "minimal_size"                          : 5.0,
            "maximal_size"                         : 1000.0,
            "sizing_parameters": {
                "reference_variable_name"               : "DISTANCE",
                "boundary_layer_max_distance"           : 2000,
                "interpolation"                         : "linear"
```

Note that the bound_layer is huge, covering the whole domain, where I expect to have very big elements far away from the building, and small elements close to the building. I did this to get rid of the small elements far away from the building. This is the mesh that we get:

![image](https://user-images.githubusercontent.com/32136457/74146493-7df35a00-4c01-11ea-8bdc-ba46d5543294.png)

![image](https://user-images.githubusercontent.com/32136457/74146597-b5620680-4c01-11ea-8874-ccfc361dccfa.png)

Now, as @swenczowski has explained, it it interesting to perform several iterations of refinement and lowering the minimal size step by step. Going to the desired minimal size in one go can lead to crashes of the remesher, or create very big "bubbles" of small elements that increase the total cost of the remeshing task. This is greatly affected by the quality of the initial background mesh that it is used. 

In the second refinement I lowered the minimal size by a factor of 10:

```
            "minimal_size"                          : 0.5,
            "maximal_size"                         : 1000.0,
            "sizing_parameters": {
                "reference_variable_name"               : "DISTANCE",
                "boundary_layer_max_distance"           : 2000,
                "interpolation"                         : "linear"
```
And we get:

![image](https://user-images.githubusercontent.com/32136457/74153559-2d83f880-4c11-11ea-8387-ba961788e91b.png)

![image](https://user-images.githubusercontent.com/32136457/74153667-6d4ae000-4c11-11ea-9ed1-3b689d36499f.png)
(I dont know why im getting that line of small elements in front of the building, maybe there was an issue when computing the distance gradient.)
![image](https://user-images.githubusercontent.com/32136457/74153965-f104cc80-4c11-11ea-91c4-c71d262233bd.png)

This is just an example and there might be more efficient ways of combining sizes and bound_layer distances to get a better result faster.

I would try to play with this approach considering the complexity of your geometries, and use @RiccardoRossi  approach or @qaumann approach if this is not enough to represent the sharp edges.


This can also be combined with hessian-based refinement to refine according to the velocity/pressure field of a previous solution of the flow. This is a 2D example of this:

![1e-3error_13knodes](https://user-images.githubusercontent.com/32136457/74155406-d54ef580-4c14-11ea-8a33-23d3728e9343.png)

**Comment by andreas-apostolatos** [comment]
> Hi Andreas!
> 
> Using MMG should definitely help, especially since one has the freedom to select on which manner to refine the whole domain. Taking a look at your model, we can see that the structured domain extends through the whole domain.
> 
> ![image](https://user-images.githubusercontent.com/32136457/74146314-21903a80-4c01-11ea-9eea-917b9efcdb4b.png)
> 
> While this might be interesting in order to capture all the features happening behind the building, we should be able to get the same level of detail using the MMG library but in a much more efficient manner.
> Also, if we only focus on the description of the geometry and we take a look at your cut domain, it feels like the element size is still not enough to properly define the edges of your geometry (the height of the elements is aprox 3 units).
> ![image](https://user-images.githubusercontent.com/32136457/74146448-5f8d5e80-4c01-11ea-80fa-7338642af294.png)
> 
> Next I'll show some results using mmg on this case:
> 
> ## MMG
> As a first approach, I decided to run mmg with the following sizing parameters:
> 
> ```
>             "minimal_size"                          : 5.0,
>             "maximal_size"                         : 1000.0,
>             "sizing_parameters": {
>                 "reference_variable_name"               : "DISTANCE",
>                 "boundary_layer_max_distance"           : 2000,
>                 "interpolation"                         : "linear"
> ```
> 
> Note that the bound_layer is huge, covering the whole domain, where I expect to have very big elements far away from the building, and small elements close to the building. I did this to get rid of the small elements far away from the building. This is the mesh that we get:
> 
> ![image](https://user-images.githubusercontent.com/32136457/74146493-7df35a00-4c01-11ea-8bdc-ba46d5543294.png)
> 
> ![image](https://user-images.githubusercontent.com/32136457/74146597-b5620680-4c01-11ea-8874-ccfc361dccfa.png)
> 
> Now, as @swenczowski has explained, it it interesting to perform several iterations of refinement and lowering the minimal size step by step. Going to the desired minimal size in one go can lead to crashes of the remesher, or create very big "bubbles" of small elements that increase the total cost of the remeshing task. This is greatly affected by the quality of the initial background mesh that it is used.
> 
> In the second refinement I lowered the minimal size by a factor of 10:
> 
> ```
>             "minimal_size"                          : 0.5,
>             "maximal_size"                         : 1000.0,
>             "sizing_parameters": {
>                 "reference_variable_name"               : "DISTANCE",
>                 "boundary_layer_max_distance"           : 2000,
>                 "interpolation"                         : "linear"
> ```
> 
> And we get:
> 
> ![image](https://user-images.githubusercontent.com/32136457/74153559-2d83f880-4c11-11ea-8387-ba961788e91b.png)
> 
> ![image](https://user-images.githubusercontent.com/32136457/74153667-6d4ae000-4c11-11ea-9ed1-3b689d36499f.png)
> (I dont know why im getting that line of small elements in front of the building, maybe there was an issue when computing the distance gradient.)
> ![image](https://user-images.githubusercontent.com/32136457/74153965-f104cc80-4c11-11ea-91c4-c71d262233bd.png)
> 
> This is just an example and there might be more efficient ways of combining sizes and bound_layer distances to get a better result faster.
> 
> I would try to play with this approach considering the complexity of your geometries, and use @RiccardoRossi approach or @qaumann approach if this is not enough to represent the sharp edges.
> 
> This can also be combined with hessian-based refinement to refine according to the velocity/pressure field of a previous solution of the flow. This is a 2D example of this:
> 
> ![1e-3error_13knodes](https://user-images.githubusercontent.com/32136457/74155406-d54ef580-4c14-11ea-8a33-23d3728e9343.png)

Hey @marcnunezc !!

That's really awesome, thanks a lot!

**Comment by NicolaGermano** [comment]
Hi everyone,

below I report the model of a small portion of the city obtained through the iterative process mentioned by @RiccardoRossi.

In this case I performed only 2 refinements.

- Distance field 1:
![01_distance_field_1_top](https://user-images.githubusercontent.com/45101543/74177108-5b7d3300-4c39-11ea-827e-b3c8a35e910d.jpg) 
![02_distance_field_1](https://user-images.githubusercontent.com/45101543/74177242-a5feaf80-4c39-11ea-8683-4756af30f854.jpg)

- Distance field 2:
![03_distance_field_2_top](https://user-images.githubusercontent.com/45101543/74177352-da726b80-4c39-11ea-9608-85ef88774840.jpg)
![04_distance_field_2](https://user-images.githubusercontent.com/45101543/74177358-dc3c2f00-4c39-11ea-8be7-5e1d24a24960.jpg)

- Result:
![05_subtracted_2_top](https://user-images.githubusercontent.com/45101543/74177496-19082600-4c3a-11ea-9733-2b78fc002de9.jpg)
![06_subtracted_2](https://user-images.githubusercontent.com/45101543/74177499-1ad1e980-4c3a-11ea-93d0-da1912fb8916.jpg)


Certainly with one more refinement the result will be better.

Also in my case the smaller elements are close to the buildings and the largest ones are far from the buildings:
![07_section](https://user-images.githubusercontent.com/45101543/74177537-376e2180-4c3a-11ea-9f31-619f3e5ce4eb.jpg)

Greetings,
Nicola

**Comment by rubenzorrilla** [comment]
@uxuech pinging you as this discussion is most probably useful for your research. In any case, I'm closing it as it has been inactive for almost one year.
