### ISSUE TITLE
Failure when using SmallDisplacementSurfaceLoadCondition3D3N

### ISSUE THREAD

**Issue by Rbravo555** [KratosMultiphysics/Kratos#6387]
Good day, 

I am running a structural linear quasi-static case (attached) from the master. I have manually set in the MDPA the conditions to "SmallDisplacementSurfaceLoadCondition3D3N". 

However, not a single step is completed, and instead I get segmentation fault.

Any advices? should I add any more changes to use the SmallDisplacementSurfaceLoadCondition3D3N ? 
[ExampleUsingSmallDisplacementCondition.zip](https://github.com/KratosMultiphysics/Kratos/files/4177145/ExampleUsingSmallDisplacementCondition.zip)

**Comment by loumalouomega** [comment]
@Rbravo555 I am sorry, I did only tests for the condition standalone. You are right, fortunately the problem can be solved in 5 lines of code. You will know more in 15 secods

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/74108790-f6b0d280-4b7d-11ea-98ca-6010e974db74.png)
Uff, almost, I said 15, it was 19
