### ISSUE TITLE
Boost 1.63 problem

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#64]
I've notice that the wiki states that Boost 1.63 is not compatible with Kratos.
Does someone knows why? I'm using this version with no problems.

**Comment by loumalouomega** [comment]
I knew there was a problem with the 1.60, just that

**Comment by pooyan-dadvand** [comment]
It was reported by @jginternational without knowing the exact reason and I added that to wiki to avoid problems until somebody confirm it in windows. Have you used in with Visual Studio?

**Comment by roigcarlo** [comment]
Oh!, didn't remember the Visual Studio bug. Well all clear now thx!
