### ISSUE TITLE
Delete the old PFEM Application?

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#640]
This issue is to check if someone is against deleting the PFEM Application.
The currently used applications on PFEM are:

- PFEM Base Application
- PFEM Solid Mechanics Application
- PFEM Fluid Dynamics Application

We think it's time to remove the old 'PFEM Application' if nobody is using it (in the future, the code would be recoverable by going back to older versions of Kratos).

Please comment!
@KratosMultiphysics/technical-committee @iiaconeta @playpaolo @KratosMultiphysics/pfem

**Comment by iiaconeta** [comment]
For me it is fine.

**Comment by pooyan-dadvand** [comment]
👍

**Comment by pooyan-dadvand** [comment]
I would also change the base pfem to pfem.

**Comment by AFranci** [comment]
Sounds good!

**Comment by josep-m-carbonell** [comment]
:+1:  ok

**Comment by antonialarese** [comment]
Fine for me too

**Comment by RiccardoRossi** [comment]
+1, please go ahead also from my side
