### ISSUE TITLE
Windows debug compilation

### ISSUE THREAD

**Issue by peterjwilson** [KratosMultiphysics/Kratos#6400]
Hi @roigcarlo, although the new compilation changes #6002 are cool and make things much easier I'm unable to get a Debug setup under windows to work. Release works fine. Below is my error message, configure script and python directory showing python_36d.lib (which it cannot open apparently). Any help you could offer would be great!

**Error message (running config bat):**
`LINK : fatal error LNK1104: cannot open file 'python36_d.lib' [C:\Kratos\build\Debug\kratos\run_kratos\runkratos.vcxproj]`

**Config script:**
```
@echo off
rem Please do not modify this script

rem For any question please contact with us in:
rem  - https://github.com/KratosMultiphysics/Kratos

rem Optional parameters:
rem You can find a list will all the compiation options in INSTALL.md or here:
rem  - https://github.com/KratosMultiphysics/Kratos/wiki/Compilation-options

rem Set compiler
set CC=cl.exe
set CXX=cl.exe

rem Set variables
set KRATOS_SOURCE=~0,-1%/..
set KRATOS_BUILD=%KRATOS_SOURCE%/build
set KRATOS_APP_DIR=applications

set LD_LIBRARY_PATH=%KRATOS_BUILD%/bin/%KRATOS_BUILD_TYPE%/libs
set PYTHONPATH=%KRATOS_BUILD%/bin/%KRATOS_BUILD_TYPE%

rem Warning: In windows this option only works if you run through a terminal with admin privileges
rem set KRATOS_INSTALL_PYTHON_USING_LINKS=ON

rem Set basic configuration
if not defined KRATOS_BUILD_TYPE set KRATOS_BUILD_TYPE=Debug
if not defined BOOST_ROOT set BOOST_ROOT=C:\boost_1_67_0
if not defined PYTHON_EXECUTABLE set PYTHON_EXECUTABLE=C:\Python36\python.exe

rem Set applications to compile
set KRATOS_APPLICATIONS=
CALL :add_app %KRATOS_APP_DIR%\ParticleMechanicsApplication;

rem Clean
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\cmake_install.cmake"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeCache.txt"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeFiles"

rem Configure
@echo on
cmake -G"Visual Studio 16 2019" -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%"          ^
-DINCLUDE_FEAST=OFF                                                                                 ^
-DLAPACK_LIBRARIES="C:\external_libraries\liblapack.lib"                                         ^
-DKRATOS_BUILD_TESTING=ON                                                                       ^
-DBLAS_LIBRARIES="C:\external_libraries\libblas.lib"

rem Build
cmake --build "%KRATOS_BUILD%/%KRATOS_BUILD_TYPE%" --target install -- /property:configuration=%KRATOS_BUILD_TYPE% /p:Platform=x64
goto:eof

rem Function to add apps
:add_app
set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%1;
goto:eof

```

**Python directory screenshot:**
![image](https://user-images.githubusercontent.com/23666229/74287025-bf584680-4d74-11ea-940d-cc40ddfeda4e.png)

Ps. THANKS for making it alot easier to compile Kratos - you're the man!

**Comment by roigcarlo** [comment]
Hi @peterjwilson 

I am Afraid that's a problem with Visual studio, who automatically assumes that you want to link against python_d when you compile runkratos. Which is not what you want in most of the cases...

To solve it:
Check if you have the `*.lib` which should be in `C:\Python36\libs`, open the project in visual studio, go to **runkratos -> properties**. This will open a window with a side menu, in that menu navigate to **Linker -> Input**. In the `Additional dependencies` field there should be a list with libs in which the `python36_d.lib` should be. You can now either:

If the path is correct, and you don't have the lib, install it using the python installer.
If the path is not correct, manually change that
If the path is correct, you don't have the lib, and you don't want to install it, just change it by the regular `python36.lib` (you should have that one)

Yet another option is to completely disable runkratos with  `-DINSTALL_RUNKRATOS=OFF` in the config file and use the `python,exe` or `python_d.exe` binaries to run kratos, which should also work.

In none of this works, please tell me and I will try to find another solution.

**Comment by peterjwilson** [comment]
That worked great, thanks @roigcarlo . `Additional dependencies` already had `python36.lib` (which didn't work), I just changed it to `python36_d.lib`.
