### ISSUE TITLE
Python Geometry is not iterable. How to access the nodes from an Element/Condition in Python?

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#6433]
Well, there's a solution: Element has a method called GetNodes() which returns a Pybind list of Nodes, which can be iterated. However, the most experienced coders in Kratos will probably miss the typical C++ way to access the nodes: through Geometry.
Should we export the Geometry as an iterable object, or with the [] operator?
@KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
We added recently (tobias and I), I can't remember if the PR is merged (I
think is #6336). Help @tteschemacher

**Comment by tteschemacher** [comment]
Yes it is #6336 .

You can see in the Python tests how we did it. Does that solve your problem?

**Comment by loumalouomega** [comment]
We may need to cherry pick in order to avoid unnecessary waitings

**Comment by tteschemacher** [comment]
This PR is finished. We just need to merge it....

**Comment by loumalouomega** [comment]
I don't feel qualified to approve it...

**Comment by maceligueta** [comment]
Thanks @loumalouomega  and @tteschemacher , good to know that the work is already done!
