### ISSUE TITLE
Duplication of includes in Structural Mechanics

### ISSUE THREAD

**Issue by lorenzogracia** [KratosMultiphysics/Kratos#644]
Hi @KratosMultiphysics/structural-mechanics,

I was checking sth and I realized that there is a duplication in structural_mechanics_application.cpp:

#include "geometries/quadrilateral_2d_8.h"
#include "geometries/quadrilateral_3d_8.h"

Regards

**Comment by RiccardoRossi** [comment]
Hi @lorenzogracia,
      in principle i would say this is not a duplication. One is a 2D element in the 2D space, the other one is a 2D element _in the 3D space_

**Comment by lorenzogracia** [comment]
Hi @RiccardoRossi,
I am not comparing between them, I mean that each one is duplicated, maybe I am wrong...

**Comment by RiccardoRossi** [comment]
oh now i understood. Can u correct that in a PR?

**Comment by lorenzogracia** [comment]
Of course!

**Comment by loumalouomega** [comment]
I will close this

**Comment by RiccardoRossi** [comment]
Has the pR been done? If not, let s keep this open until it is corrected

**Comment by loumalouomega** [comment]
It appears as merged

**Comment by lorenzogracia** [comment]
it's already merged!!

**Comment by RiccardoRossi** [comment]
ok perfect. sorry for the noise
