### ISSUE TITLE
Name clash with  "Parameters". Duplication with "JSON" and CL

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#645]
Hello everyone,
      i just realized that in Kratos we have two objects named "Parameters" : 

1 - is the "Parameters" class that we use for json input (and lives in the Kratos:: namespace)
2 - ConstitutiveLaw::Parameters, defined in the class "Parameters"

this is at times confusing, particularly for people working in the CLs.

It is fair to be said that the keyword "Parameters" was used first in the constitutive law. The "global" one was added more recently with the name clash going unnoticed for a long while. 
My suggestion however would be to rename the ConstitutiveLaw::Parameters to CLParameters or something of the sort. Note that this is not urgent, however it is something that we should clean up at soem point

**Comment by pooyan-dadvand** [comment]
I would also suggest to change the ConstitutiveLaw::Parameters and keep the global Parameter class to avoid large changes. ConstitutiveLaw::Data?

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee believes that 

**ConstitutiveLaw::Parameters** should be renamed as **ConstitutiveLawData**
