### ISSUE TITLE
CoSim test with MPM fails

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6469]
@KratosMultiphysics/mpm 
The [CoSim test with MPM](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/tests/co_simulation_test_factory.py#L62-L73) fails, I don't know why. 
Maybe related with #5624 or #6401 
there are a lot of warnings:
~~~
[WARNING] Geometry: Computation of local coordinates failed at iteration 0
~~~
hence it might be related with #5624. Actually thinking about it, it can be the case, since if I remember correctly you save quite a lot of stuff in the database, which is no longer separated between your elements but now shared

The MPM-App is not in the CI, this is probably one of the reasons this could happen undetected. I suggest you add it there, see #6412

**Comment by peterjwilson** [comment]
#5624 looks to be the cause. I reverted this in the master and the MPM Python tests run normally again.

**Comment by tteschemacher** [comment]
Unfortunately this affects the entire architecture of the MPM application and will not that easy to be resolved...

**Comment by philbucher** [comment]
Hm
Those changes were discussed for almost 1.5 years :/

**Comment by philbucher** [comment]
@KratosMultiphysics/mpm I recommend adding the App to the CI
I tried but there were some errors

**Comment by philbucher** [comment]
this is fixed in the meantime
