### ISSUE TITLE
Numpy - Kratos-Matrix conversion is deprecated

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6558]
when compiling Kratos (and hence pybind) in debug the newly added conversions (see #6524 and #6542) give the following warning:

`
_frozen_importlib:219: FutureWarning: pybind11-bound class 'Kratos.Matrix' is using an old-style placement-new '__init__' which has been deprecated. See the upgrade guide in pybind11's docs. This message is only visible when compiled in debug mode.
`

@Rbravo555 @qaumann can you please take a look?
Esp for #6496
Thanks

**Comment by qaumann** [comment]
Ok I guess this is what I did. I followed their guide from https://pybind11.readthedocs.io/en/stable/advanced/pycpp/numpy.html#buffer-protocol but apparently they did not yet update their docs. I will fix this.
