### ISSUE TITLE
assertVectorAlmostEqual is very slow

### ISSUE THREAD

**Issue by qaumann** [KratosMultiphysics/Kratos#6601]
Following #6597 I noticed that `KratosUnittest`'s `assertVectorAlmostEqual` is very slow now (for my test 1.6 seconds compared to 0.02 seconds). The slowdown is caused by `msg=GetErrMsg(i)` in line 77 of `KratosUnittest.py`:
```python
            self.assertAlmostEqual(vector1[i], vector2[i], prec, msg=GetErrMsg(i))
```
If the last argument is omitted, the function is as fast as usual.

**Comment by philbucher** [comment]
Hmmm
I will take a look, strange :/

**Comment by qaumann** [comment]
It seems that `GetErrorMsg` is called for each entry that is checked, also if the error is not raised. That's also the case if a formatted string is passed as msg argument, it is evaluated for each value pair. I did a bit of research, but could not find anything about efficiently formatting custom error messages.
