### ISSUE TITLE
Kratos and Python2 support

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6610]
From https://www.python.org/dev/peps/pep-0373/:
~~~
Being the last of the 2.x series, 2.7 received bugfix support until 2020. 
Support officially stopped January 1 2020, and 2.7.18 code freeze occurred on 
January 1 2020, but the final release will occur after that date.

Planned future release dates:

    2.7.18 release candidate early April, 2020
    2.7.18 mid-April, 2020
~~~

Since Python2 officially reached the end of its supported period, we should decide what we want to do with Kratos. Eventually we will drop the support, but it is a question when we will do this.
Furthermore if we drop Python2, then we should decide which version of Python3 will be the minimal supported one (e.g. 3.2, 3.3, ...)

Since this involves everyone I would like to ask here for opinions abt this. 

Personally I would do it soon, because then we can update our code to the newer version without having to worry about (python2) backward compatibility, but this is my opinion

@KratosMultiphysics/all

**Comment by roigcarlo** [comment]
My two cents. 

Drop 2: Now.

Very minimal is 3.5. I will go for for at least 3.7.1 (3.7.0 has a bug with `PyInit()`), but I am not aware of what are the defaults in CentOS/RedHat and other server distros.

**Comment by pooyan-dadvand** [comment]
In @KratosMultiphysics/altair we have moved to Python 3.5. Centos doesn't have it so we install it manually there.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee 
Unless someone has a real blocker, we are thinking to drop the python2 support after the next release

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee Agrees to move to 3.5 after release, but keep the `from future import *` for 2 month after the release.

**Comment by philbucher** [comment]
the release branch was made, this means that we officially no longer support Python2

**Comment by inigolcanalejo** [comment]
Would it be possible to keep the support for python 2 for one more year? I would need it for my project. TAU from DLR still uses python 2...

**Comment by inigolcanalejo** [comment]
Problem solved!

**Comment by RiccardoRossi** [comment]
? what is the solution ?

**Comment by philbucher** [comment]
> ? what is the solution ?

Talking to me :)

**Comment by RiccardoRossi** [comment]
enlightening :-D

but seriously, what changed?

**Comment by philbucher** [comment]
@inigolcanalejo can you explain please?

**Comment by inigolcanalejo** [comment]
Since I only need Kratos with python 2 to compute some basic geometrical information (element normals and areas) and to interpolate them to the nodes using the nodal value interpolation process, Philipp suggested to either use an old version of Kratos with support to python 2 where this is available, or in case I need something more specific, to implement it myself. I agree with him and I think that his suggestion is a good idea. Also, if I am the only one needing python 2 support, it doesn't make sense to block the whole project because of me (specially if a solution is available)
