### ISSUE TITLE
[Mapping] Handling of quad elements in nearest-element mapper

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#6612]
Given a point cloud whose values I want to map onto a quad mesh using the nearest-element technique in the MappingApp. How do you handle warped quad elements, where an orthogonal projection is not as straight-forward as for simple triangles? @philbucher

**Comment by philbucher** [comment]
Hi @dbaumgaertner 
I use the following fct which I implemented in the Core: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/geometrical_projection_utilities.h#L152

Basically it uses the normal in the center of the Quad (or any Geometry) and projects along this one
I have to admit that for the case you are describing this might not always yield the most accurate results, but I have not yet had time to improve this.
I think one needs some iterative algorithm to do this properly

@andreas-apostolatos I think you implemented this better, could you comment please?

**Comment by dbaumgaertner** [comment]
Alright @philbucher, thanks for the answer and the link. So do I understand it correctly? You compute the projected point using the normal at the center of any geometry. For warped geometries, the projected point does obviously not lay on the surface. Consequently, you determine the local coordinates of that projected point by a Newton-Raphson scheme (cf. "PointLocalCoordinatesImplementation" [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/geometries/quadrilateral_3d_4.h#L1575) for quads). Then you use the local coordinates to interpolate the nodal values using the shape functions of the element.

**Comment by philbucher** [comment]
> You compute the projected point using the normal at the center of any geometry.

Yes

> For warped geometries, the projected point does obviously not lay on the surface

Not necessarily, depends on the warpage I'd say. Here IMO to account for the warpage I think I need to implement a NR too, that minimizes the distance btw the surface and the point that is to be projected.
@andreas-apostolatos is this correct?

> Consequently, you determine the local coordinates of that projected point by a Newton-Raphson scheme

yes, this is implemented in the respective geometries

> Then you use the local coordinates to interpolate the nodal values using the shape functions of the element.

yes

**Comment by andreas-apostolatos** [comment]
> > You compute the projected point using the normal at the center of any geometry.
> 
> Yes
> 
> > For warped geometries, the projected point does obviously not lay on the surface
> 
> Not necessarily, depends on the warpage I'd say. Here IMO to account for the warpage I think I need to implement a NR too, that minimizes the distance btw the surface and the point that is to be projected.
> @andreas-apostolatos is this correct?

Yes that's correct.

> > Consequently, you determine the local coordinates of that projected point by a Newton-Raphson scheme
> 
> yes, this is implemented in the respective geometries
> 
> > Then you use the local coordinates to interpolate the nodal values using the shape functions of the element.
> 
> yes

**Comment by dbaumgaertner** [comment]
@andreas-apostolatos @philbucher since all questions are answered, I close this issue. Thanks for the information.
