### ISSUE TITLE
No debug output for tests in MPI

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#6615]
Only the output of the first processor is shown on the screen when running tests in MPI.

this makes impossible to debug them.

the problem appears to come from the lines 

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/testing/tester.cpp#L274

and 

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/testing/tester.cpp#L302

simply commenting those lines enables output to be shown correctly when debugging, however it also implies reporting the "OKs" multiple times when running in MPI.

I think we need to be able to optionally enable outputs, but i am not sure of how that should be achieved

**Comment by RiccardoRossi** [comment]
mentioning @jcotela . Jordi, if you have any hint on this it would be very welcome

**Comment by roigcarlo** [comment]
Probably the best option here is to add an additional level of verbosity for mpi which disables the buffer redirection:

```C++
std::streambuf* original_buffer = nullptr;
if (GetInstance().mVerbosity != Verbosity::TESTS_OUTPUTS_MPI) {
    if (ParallelEnvironment::GetDefaultRank() != 0) {
        original_buffer = std::cout.rdbuf(secondary_stream.rdbuf());
    }
}

if (GetInstance().mVerbosity != Verbosity::TESTS_OUTPUTS && GetInstance().mVerbosity != Verbosity::TESTS_OUTPUTS_MPI ) { // Line 283 also needs change see below.
...

if (GetInstance().mVerbosity != Verbosity::TESTS_OUTPUTS_MPI) {
    if (ParallelEnvironment::GetDefaultRank() != 0) {
        std::cout.rdbuf(original_buffer);
    }
}
```

Adding this is not immediate as we have more levels of verbosity that need to be respected, so one solution would be to duplicate all levels to a have a _MPI twin, or just make an exception with the `TEST_OUTPUT` level, as the rest do not provide any useful information if printed by other than the master process.

**Comment by RiccardoRossi** [comment]
I would eventually call this "MPI_DEBUG_OUTPUTS" or something with "DEBUG" in the name...but i think that what you propose goes in the good direction

**Comment by RiccardoRossi** [comment]
also, we will need to document this in the wiki

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee agrees that when TEST_OUTPUTS is selected all MPI outputs (of all ranks) should be shown.

Code will be modified accordingly soon
