### ISSUE TITLE
[core] Add tests for the quaternions

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#6618]
Just a reminder, because the quaternions are in the core but there are only tests of its python interface, not of their actual computational behaviour.
No rush, but can you take care of this, @joaquinirazabal ?

**Comment by joaquinirazabal** [comment]
Ok, @maceligueta, I will take care of it.

**Comment by joaquinirazabal** [comment]
See  #6769

**Comment by philbucher** [comment]
Closing since solved
Thx
