### ISSUE TITLE
[Core] Moving flags to geometry.h

### ISSUE THREAD

**Issue by sunethwarna** [KratosMultiphysics/Kratos#6624]
Hi,

Is there a specific reason not to move flags as well to the geometry as in #5624. I'm talking about a case, where you have different equation systems to be solved in the same modelpart with same geometries where you only set flags such as SLIP once. Current method requires keeping a pointer to the parent element/condition to access these flags. The change in #5624 was a nice for this kind of problems. It would be great if flags are also moved, so then no need to keep the element/condition pointers as well.

This is not an "Issue", tho I don't know where to ask this :|

@pooyan-dadvand @RiccardoRossi @philbucher

**Comment by rubenzorrilla** [comment]
The main one is that one geometry might be used for several elements / conditions, which eventually may have different value for the same flag.

As a use case, think in a volume coupling problem (e.g. Thermally driven CFD problems).

**Comment by philbucher** [comment]
@rubenzorrilla you could use this exact same argument for the Data ...

In any case, I don’t have a strong opinion...

@sunethwarna maybe you could explain a bit more your problems. Basically what you wrote in the mail you sent me.

**Comment by sunethwarna** [comment]
My use case is in RANSApplication. In there I have the following

1. Main model part -> which holds fluid elements and conditions
2. Duplicated model part 1 -> which holds turbulent kinetic energy transport equation elements and conditions
3. Duplicated model part 2 -> which holds turbulent energy dissipation rate transport equation elements and conditions.

Then I have followings,
1. Slip condition on the wall boundaries to activate wall laws for fluid, turbulent kinetic energy and turbulent energy dissipation rate
2. Incompressible potential flow solver initialization for steady state problems, which needs INLET flag to correctly specify inlet flux based on velocity inlet.

The above mentioned flags are set in the json file, where only one model part is exposed to user (all the others are copies thus having hard to remember long names). Therefore at the moment I am keeping a PARENT_CONDITION_POINTER variable in RANSApplication for all the conditions which points to condition corresponding to its original in fluid model part (which is the original model part, all the duplicates are made out of that). From this "PARENT_CONDITION_POINTER", I access all the required flags for corresponding conditions. This is hackish, I know no better solution at the moment. I had issues relating to data value containers also. U_tau (wall friction velocity) is calculated at the fluid model part conditions, and this same u_tau is required for wall law calculations of the turbulent energy dissipation rate. But this difficulty is removed by #5624.

So long story short, If I am able to have geometry level flags, then I can easily get rid of these "PARENT_CONDITION_POINTER" variable and costs associated with it (assigning and reading, which is significant in the case of MPI large models)

I only mentioned one use case in RANSApplication. Since now we have working k-epsilon, k-omega models as well (which is planned to extend for k-omega-sst), all of them will benefit if we can have geometry level flags.

Do you have better suggestions? I wanted to have a clean solution for flags as well. :)

Did I explain myself clearly?

Again one question from me is, flags like SLIP, INLET, OUTLET, STRUCTURE, can they be used differently in different equation systems? I mean, those are kind of geometryical properties ryt, which is defined by the geometry?. I know there are some non-specific flags as well.

**Comment by rubenzorrilla** [comment]
> @rubenzorrilla you could use this exact same argument for the Data ...
> 

Well, I don't think it is exactly the same... if you are doing volume coupling, I don't think it has so much sense to have to have two different values for `TEMPERATURE`. However on element can be `(ACTIVE, true)` in one solver while it is `(ACTIVE, false)` in the other.

**Comment by loumalouomega** [comment]
IMO we should not add more things to the geometries, we already add many things to the geometry and now are a heavy object with the corresponding additional cost in case we want to do some basic geometry operations. I use point geometries (not node ones), and with the recent changes the creation-deletion time has increased, this is not a problem for implicit simulations, but it will be for explicit. And as @rubenzorrilla said, this is not comparable as the data, where we had a clear example of bottleneck, where the memory consumption was duplicated, in the other hand, even if flags are not assigned, the memory use is already there. IMO if you want to share flags between geometries yo can create a process to synchronize them, this is not difficult and the increase in cost not significant

**Comment by sunethwarna** [comment]
@rubenzorrilla @loumalouomega thanks, I get your points. In that case, would it be possible to modify GenerateModelPart method with ability to assign PARENT_CONDITION/PARENT_ELEMENT variables correspondingly? The problem with assignment it after creation using existing GenerateModelPart is, I have to use "GetElement" method by Id, which is little bit expensive. This can be achieved by adding another constructor to ConnvectivityPreserveModeller with assginemtn flag, so that when generate model part is used it can assign original element/ original conditions there without additional cost. This is again another modification to connectivity_preserve_modeller :|

@loumalouomega, I already have a process for that. But this keeps on increasing the length of json file, where user doesn't need to be exposed to IMO, thats the reason why I created PARENT_CONDITION_POINTER variable where, I take care of this instead of the user.

**Comment by loumalouomega** [comment]
> @rubenzorrilla @loumalouomega thanks, I get your points. In that case, would it be possible to modify GenerateModelPart method with ability to assign PARENT_CONDITION/PARENT_ELEMENT variables correspondingly? The problem with assignment it after creation using existing GenerateModelPart is, I have to use "GetElement" method by Id, which is little bit expensive. This can be achieved by adding another constructor to ConnvectivityPreserveModeller with assginemtn flag, so that when generate model part is used it can assign original element/ original conditions there without additional cost. This is again another modification to connectivity_preserve_modeller :|
> 
> @loumalouomega, I already have a process for that. But this keeps on increasing the length of json file, where user doesn't need to be exposed to IMO, thats the reason why I created PARENT_CONDITION_POINTER variable where, I take care of this instead of the user.

We will solve that when the requirements of the elements/conditions is merged. See #5608

**Comment by philbucher** [comment]
> However on element can be (ACTIVE, true) in one solver while it is (ACTIVE, false) in the other.

this is a very good point and IMO a nogo for moving the Flags to the Geometry

> We will solve that when the requirements of the elements/conditions is merged. See #5608

I am quite convinced this has nothing to do, this is an issue of synchronization

> where we had a clear example of bottleneck, where the memory consumption was duplicated

I think according to the final measurements of @pooyan-dadvand this didn't really make a big difference

**Comment by pooyan-dadvand** [comment]
We have discussed this already in #5624 and concluded that we should have the flags in elements and conditions for the same reasons. 

Meanwhile, we still can add the flags to the geometry and in fact, I am in favor of that. 

I understand that when you have elements and condition you are basically using their flags but in the GeometryModeler flags (to select, mark as external or internal, etc. ) can be very useful. Also, we may use it for shared flags in the same way that we use nodal data.

**Comment by rubenzorrilla** [comment]
> 
> Meanwhile, we still can add the flags to the geometry and in fact, I am in favor of that.
>

:+1: as I don't think it would interfere with the already existent element & conditions ones.

**Comment by GuillermoCasas** [comment]
> > @rubenzorrilla you could use this exact same argument for the Data ...
> 
> Well, I don't think it is exactly the same... if you are doing volume coupling, I don't think it has so much sense to have to have two different values for `TEMPERATURE`. However on element can be `(ACTIVE, true)` in one solver while it is `(ACTIVE, false)` in the other.

You would if you had overlapping media (water spray, where the drops are colder)

**Comment by rubenzorrilla** [comment]
> > > @rubenzorrilla you could use this exact same argument for the Data ...
> > 
> > 
> > Well, I don't think it is exactly the same... if you are doing volume coupling, I don't think it has so much sense to have to have two different values for `TEMPERATURE`. However on element can be `(ACTIVE, true)` in one solver while it is `(ACTIVE, false)` in the other.
> 
> You would if you had overlapping media (water spray, where the drops are colder)

I was thinking in more common stuff (e..g. thermally driven flows). 

In the case you point out, is the spray modelled with the same background mesh? (I thought this is commonly done with particle elements). If so it is, it would possibly make sense to have the database in the element to reuse the same geometry.

In any case I think this is not so much related to the flags discussion (the owning of the data value container was discussed in  #5624).

**Comment by RiccardoRossi** [comment]
@KratosMultiphysics/technical-committee consensus is that
we agree for ADDING flag to geometries in the sense of providing a flag container in there, HOWEVER elements and conditions must retain their own flag. this is needed for example for erasing, selecting, etc.

The bottomline  is that we are NOT in agreement about moving flags from one place to the other, which is something that will have to be discussed **in a case-to-case way ensuring backwards compatibility** as much as possible.
For example, right now "SLIP" is set on conditions and should not be set on the underlying geometry instead. In case we wanted to make such a change we would have to make a PR just about this, and discuss it in there.

**Comment by sunethwarna** [comment]
Having flags in geometry also perfectly fine. Then, there are few other possibilities as well, such as whenever duplicate model part is created we can assign copies of flags to geometries to pass flag info of geometrical flags such as SLIP, INLET, OUTLET to geometries to ensure consistency among all duplicated model parts having same geometry.

**Comment by rubenzorrilla** [comment]
@KratosMultiphysics/technical-committee I think we should revisit this. Though we reached a consensus two years ago it seems that no one missed the feature. Having said this, we might want to briefly re-discuss it again before implementing it.

**Comment by loumalouomega** [comment]
I am still thinking that Geometry is already to big...

**Comment by sunethwarna** [comment]
I am closing this since moving the flags is not possible.
