### ISSUE TITLE
[dem] Update KRATOS_THROW_ERROR to KRATOS_ERROR and KRATOS_ERROR_IF

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#6659]
Something necessary to update to the new Kratos standards.
Triggered by @philbucher 's comments in #6658

**Comment by philbucher** [comment]
I suggest to take a look at what is available and decide depending on your needs:
https://github.com/KratosMultiphysics/Kratos/blob/6c6c37a10415592ca0cf2d47c315c64b25b9a9f6/kratos/includes/exception.h#L161-L175

**Comment by maceligueta** [comment]
@philbucher #7711 should solve this one
