### ISSUE TITLE
Initialization of Constraints

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6702]
Afaik the constraints are nowhere initialized. At least I couldn't find if.
Is this true?

Should this be done in the `Scheme` like Elements and Conditions? I think this would be the most consistent way

**Comment by adityaghantasala** [comment]
So far the existing M-S constraint variants do not implement a Initialize() function. So it has not be an issue. 

I agree that constraints should be initialized. And as @philbucher  says to be consistent scheme is the place to do. 

On a side note : I see that `InititalizeSolutionStep` of the constraints is called twice. Once in builder and scheme and second in the B&S ... we should also remove this.

**Comment by philbucher** [comment]
> On a side note : I see that InititalizeSolutionStep of the constraints is called twice. Once in builder and scheme and second in the B&S ... we should also remove this.

I also noticed (and corrected) this in #5121

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee delegates the followup and approval of this PR to @KratosMultiphysics/implementation-committee

**Comment by philbucher** [comment]
ping @KratosMultiphysics/implementation-committee

**Comment by GuillermoCasas** [comment]
Ok, it makes sense to correct the double call to InitializeSolutionStep as done  in #5121, i.e., the Scheme is the one to call it. I agree with the proposal and this should be done. @adityaghantasala , would you take care of it, since you introduced the MasterSlaveConstraints?

**Comment by adityaghantasala** [comment]
@philbucher should I also remove the double call to `InititalizeSolutionStep` here in the connecting PR ? or should we wait till #5121 goes through ?

**Comment by philbucher** [comment]
> @philbucher should I also remove the double call to `InititalizeSolutionStep` here in the connecting PR ? or should we wait till #5121 goes through ?

@adityaghantasala for me you can do it in the same PR, #5121 might take some more time
