### ISSUE TITLE
Seg fault in CoSimApp tests gdb output

### ISSUE THREAD

**Issue by inigolcanalejo** [KratosMultiphysics/Kratos#6716]
**Gdb output summarized:**

**Program received signal SIGSEGV, Segmentation fault.**
__kmp_acquire_queuing_lock_timed_template<false> (lck=<optimized out>, gtid=<optimized out>) at ../../src/**kmp_lock.cpp:1329**
1329	../../src/kmp_lock.cpp: No such file or directory.
(gdb) bt
#0  __kmp_acquire_queuing_lock_timed_template<false> (lck=<optimized out>, gtid=<optimized out>) at ../../src/kmp_lock.cpp:1329
#1  __kmp_acquire_queuing_lock (lck=0x0, gtid=0) at ../../src/kmp_lock.cpp:1460
#4  0x00007fffd8d42676 in Kratos::Node<3ul, Kratos::Dof<double> >::SetLock (this=0x22a1570) at /home/inigo/software/kratosMerge/Kratos/kratos/includes/node.h:376
#5  0x00007fffd8e7433f in Kratos::Define2DWakeProcess::MarkWakeElements ()
    at /home/inigo/software/kratosMerge/Kratos/applications/CompressiblePotentialFlowApplication/custom_processes/**define_2d_wake_process.cpp:172**

Full Gdb output:

Program received signal SIGSEGV, Segmentation fault.
__kmp_acquire_queuing_lock_timed_template<false> (lck=<optimized out>, gtid=<optimized out>) at ../../src/kmp_lock.cpp:1329
1329	../../src/kmp_lock.cpp: No such file or directory.
(gdb) bt
#0  __kmp_acquire_queuing_lock_timed_template<false> (lck=<optimized out>, gtid=<optimized out>) at ../../src/kmp_lock.cpp:1329
#1  __kmp_acquire_queuing_lock (lck=0x0, gtid=0) at ../../src/kmp_lock.cpp:1460
#2  0x00007fffdc6cbfc8 in __kmp_acquire_queuing_lock_with_checks (lck=0x0, gtid=0) at ../../src/kmp_lock.cpp:1480
#3  0x00007fffdc6b81f9 in __kmpc_set_lock (loc=0x0, gtid=0, user_lock=0x7fffdea43c80) at ../../src/kmp_csupport.c:1756
#4  0x00007fffd8d42676 in Kratos::Node<3ul, Kratos::Dof<double> >::SetLock (this=0x22a1570) at /home/inigo/software/kratosMerge/Kratos/kratos/includes/node.h:376
#5  0x00007fffd8e7433f in Kratos::Define2DWakeProcess::MarkWakeElements ()
    at /home/inigo/software/kratosMerge/Kratos/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp:172
#6  0x00007ffff0e18cbf in GOMP_parallel () from /usr/lib/x86_64-linux-gnu/libgomp.so.1
#7  0x00007fffd8e6f98b in Kratos::Define2DWakeProcess::MarkWakeElements (this=0x1ea0fe0)
    at /home/inigo/software/kratosMerge/Kratos/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp:145
#8  0x00007fffd8e6e712 in Kratos::Define2DWakeProcess::ExecuteInitialize (this=0x1ea0fe0)
    at /home/inigo/software/kratosMerge/Kratos/applications/CompressiblePotentialFlowApplication/custom_processes/define_2d_wake_process.cpp:35
#9  0x00007ffff51a4cdf in pybind11::cpp_function::cpp_function<void, Kratos::Process, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (Kratos::Process::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(Kratos::Process*)#1}::operator()(Kratos::Process*) const ()
    at /home/inigo/software/kratosMerge/Kratos/external_libraries/pybind11/pybind11.h:78
#10 0x00007ffff523b247 in pybind11::detail::argument_loader<Kratos::Process*>::call_impl<void, pybind11::cpp_function::cpp_function<void, Kratos::Process, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (Kratos::Process::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(Kratos::Process*)#1}&, 0ul, pybind11::detail::void_type>(pybind11::cpp_function::cpp_function<void, Kratos::Process, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (Kratos::Process::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(Kratos::Process*)#1}&, pybind11::detail::index_sequence<0ul>, pybind11::detail::void_type&&) (this=0x7fffffffaaf0, f=...) at /home/inigo/software/kratosMerge/Kratos/external_libraries/pybind11/cast.h:1935
#11 0x00007ffff5215262 in pybind11::detail::argument_loader<Kratos::Process*>::call<void, pybind11::detail::void_type, pybind11::cpp_function::cpp_function<void, Kratos::Process, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (Kratos::Process::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(Kratos::Process*)#1}&>(pybind11::cpp_function::cpp_function<void, Kratos::Process, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (Kratos::Process::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(Kratos::Process*)#1}&) && (this=0x7fffffffaaf0, f=...)
    at /home/inigo/software/kratosMerge/Kratos/external_libraries/pybind11/cast.h:1917
#12 0x00007ffff51d3e23 in void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, Kratos::Process, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (Kratos::Process::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(Kratos::Process*)#1}, void, Kratos::Process*, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, Kratos::Process, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (Kratos::Process::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(Kratos::Process*)#1}&&, void (*)(Kratos::Process*), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::operator()(pybind11::detail::function_call) const (__closure=0x0, call=...)
    at /home/inigo/software/kratosMerge/Kratos/external_libraries/pybind11/pybind11.h:159
#13 0x00007ffff51d3efb in void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, Kratos::Process, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (Kratos::Process::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(Kratos::Process*)#1}, void, Kratos::Process*, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, Kratos::Process, , pybind11::name, pybind11::is_method, pybind11::sibling>(void (Kratos::Process::*)(), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(Kratos::Process*)#1}&&, void (*)(Kratos::Process*), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) ()
    at /home/inigo/software/kratosMerge/Kratos/external_libraries/pybind11/pybind11.h:137
#14 0x00007ffff4e74603 in pybind11::cpp_function::dispatcher (self=0x7ffff0bcf840, args_in=0x7fffe83e95f8, kwargs_in=0x0)
    at /home/inigo/software/kratosMerge/Kratos/external_libraries/pybind11/pybind11.h:624

**Comment by philbucher** [comment]
A bit more context would be good

Also this points to the PotentialFlowApp not to CoSim

**Comment by philbucher** [comment]
I was debugging today too some things and noticed that if I compile with MKL enabled then I get random segfaults (same happens in the CI)
This does not happen when I set the number of threads to 1 or when I disable MKL
Note that I was not using any pardiso solver, only the usual SparseLU
The test I am running is unchanged for ~2 years already, it crashes consistently in the FluidApp, but I don't think there is an actual error there, this code is used very often

@armingeiser @oberbichler I am thinking that there is some problem with MKL and OpenMP

**Comment by armingeiser** [comment]
Can you give more info on:
* which test is failing
* does it fail if it runs "standalone" or only if run with a combination of other tests (thats what i understood from the other thread)

EDIT: I mean @philbucher are you talking about the same scenario as #6717 or does it happen in other tests as well?

**Comment by philbucher** [comment]
the test failing was the Mok-Aitken in the CoSimApp. This test has been unchanged for almost two years, this is what bugs me a bit
Also it only fails if another test is run before it (by default its the MPM-FEM-test in the CoSimApp, not sure if this would also happen in other constellations),
I.e. it is very similar to #6716 but not the same tests
Standalone the test works
Also I can run all the tests if MKL is not compiled
