### ISSUE TITLE
[sdem] Add the swimming DEM to the CI

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#6817]
From #6103 I recover this information.
In my opinion, it is very necessary to add the swimming DEM to the CI. Otherwise, it is broken very often.
- Swimming DEM uses Python modules which are non-standard and probably are not available in the CI. Some tests must be skipped in the first attempts to add this to the CI.
- PFEM Fluid uses Triangle/Tetgen. As we can't redistribute a Tetgen, it is not present in the Kratos repo and the CI must download it from somewhere.
- PFEM tests take too long (https://github.com/KratosMultiphysics/Kratos/pull/6103#issuecomment-566073043). They must be shorter.

**Comment by philbucher** [comment]
> PFEM Fluid uses Triangle/Tetgen. As we can't redistribute a Tetgen, it is not present in the Kratos repo and the CI must download it from somewhere.

I think this can be added to the docker

At least in Linux this should be easy, Win I don't know (there we don't use a docker-container (yet))

**Comment by philbucher** [comment]
Are you talking about swimmingDEM or pfemfluid?

**Comment by maceligueta** [comment]
The SwimmingDEM couples de DEM with:
- Fluid application 
- PFEM Fluid application

with different analysis stages.
The tests run examples of both couplings

**Comment by philbucher** [comment]
swimmingdem is added, can this be closed?
