### ISSUE TITLE
Directly passing an elemental non-historical variable to GID

### ISSUE THREAD

**Issue by mrhashemi** [KratosMultiphysics/Kratos#6821]
Dear All,
Is it possible to directly present a nonhistorical variable in the GID post file?
What about directly presenting an **_elemental_** nonhistorical variable? I mean without projecting the variable to a historical nodal value.

**Comment by loumalouomega** [comment]
It is possible with VTK, with GiD we should do a trick and do like a repeated value in the GP

**Comment by mrhashemi** [comment]
> It is possible with VTK, with GiD we should do a trick and do like a repeated value in the GP

Thank you for the comment. Correct me please if I am wrong; you mean it is possible to store and export variables on the Gauss point?

**Comment by loumalouomega** [comment]
Is not store, is to write the value in the GiD file as GP value, but it requires to modify the current implementation. Another alternative is to add a method to you element that when the variable is asked in the GP it just copies the values in the solution vector. Which element are you using?

**Comment by mrhashemi** [comment]
> Is not store, is to write the value in the GiD file as GP value, but it requires to modify the current implementation. Another alternative is to add a method to you element that when the variable is asked in the GP it just copies the values in the solution vector. Which element are you using?

The element is derived from two_fluid_navier_stokes, which is itself derived from the more general fluid_element.

**Comment by loumalouomega** [comment]
OK; I am not going to touch that. But you can just simply add to your derived element something like (or extend in the case you already have the method implemented):

~~~~cpp
void YourDerivedElement::CalculateOnIntegrationPoints(
    const Variable<double>& rVariable,
    std::vector<double>& rOutput,
    const ProcessInfo& rCurrentProcessInfo
    )
{
    const auto& r_geometry = GetGeometry();
    const GeometryType::IntegrationPointsArrayType &integration_points = r_geometry.IntegrationPoints(r_geometry.GetDefaultIntegrationMethod());

    const std::size_t number_of_integration_points = integration_points.size();

    if ( rOutput.size() != number_of_integration_points ) {
        rOutput.resize( number_of_integration_points );
    }

    if (this->Has( rVariable)) {
        cons double value = this->GetValue( rVariable);
        for (std::size_t point_number = 0; point_number < number_of_integration_points; ++point_number) {
            rOutput[point_number] = value;
        }
    }
}
~~~~

**Comment by mrhashemi** [comment]
> OK; I am not going to touch that. But you can just simply add to your derived element something like (or extend in the case you already have the method implemented):
> 
> ```c++
> void YourDerivedElement::CalculateOnIntegrationPoints(
>     const Variable<double>& rVariable,
>     std::vector<double>& rOutput,
>     const ProcessInfo& rCurrentProcessInfo
>     )
> {
>     const auto& r_geometry = GetGeometry();
>     const GeometryType::IntegrationPointsArrayType &integration_points = r_geometry.IntegrationPoints(r_geometry.GetDefaultIntegrationMethod());
> 
>     const std::size_t number_of_integration_points = integration_points.size();
> 
>     if ( rOutput.size() != number_of_integration_points ) {
>         rOutput.resize( number_of_integration_points );
>     }
> 
>     if (this->Has( rVariable)) {
>         cons double value = this->GetValue( rVariable);
>         for (std::size_t point_number = 0; point_number < number_of_integration_points; ++point_number) {
>             rOutput[point_number] = value;
>         }
>     }
> }
> ```

Thank you very much.

**Comment by loumalouomega** [comment]
> > OK; I am not going to touch that. But you can just simply add to your derived element something like (or extend in the case you already have the method implemented):
> > ```c++
> > void YourDerivedElement::CalculateOnIntegrationPoints(
> >     const Variable<double>& rVariable,
> >     std::vector<double>& rOutput,
> >     const ProcessInfo& rCurrentProcessInfo
> >     )
> > {
> >     const auto& r_geometry = GetGeometry();
> >     const GeometryType::IntegrationPointsArrayType &integration_points = r_geometry.IntegrationPoints(r_geometry.GetDefaultIntegrationMethod());
> > 
> >     const std::size_t number_of_integration_points = integration_points.size();
> > 
> >     if ( rOutput.size() != number_of_integration_points ) {
> >         rOutput.resize( number_of_integration_points );
> >     }
> > 
> >     if (this->Has( rVariable)) {
> >         cons double value = this->GetValue( rVariable);
> >         for (std::size_t point_number = 0; point_number < number_of_integration_points; ++point_number) {
> >             rOutput[point_number] = value;
> >         }
> >     }
> > }
> > ```
> 
> Thank you very much.

:D (similar for other types of variables)

**Comment by loumalouomega** [comment]
@mrhashemi if this solved the problem you can close the issue
