### ISSUE TITLE
gcc install Internal Compiler Error

### ISSUE THREAD

**Issue by jc-bm** [KratosMultiphysics/Kratos#6828]
When installing the latest master with applications (git clone, edit standard_configure.sh, run standard_configure.sh, #6002 ) with a 16GB RAM machine and 8 processes it fails with e.g. see attachment. My friend @mhubii has replicated this issue on his computer with a fresh install.

It seems the process requires excessive memory.

In the absence of a proper fix it seems reducing the number of processors allocated to the build can allow it to run without issues (i.e. change the -j option at the end of the file).

[internalcompilererror.txt](https://github.com/KratosMultiphysics/Kratos/files/4540813/internalcompilererror.txt)

**Comment by philbucher** [comment]
It fails in the ContactStructuralMechanics. @loumalouomega

**Comment by loumalouomega** [comment]
How are you compiling?, is not a compilation error, is an error in the compilation. Usually because so many threads are used compiling.

**Comment by loumalouomega** [comment]
CI is compiling the Contact with very limited resources, probably the problem is that the standard script uses as many threads as they are available, try to use -j4

**Comment by roigcarlo** [comment]
Was this solved? can we close?

**Comment by philbucher** [comment]
(When using Cotire) this is mitigated / solved by #7061

Apart from that there is no "solution" for this, this compiling the ContactApp just requires a lot of RAM

as @loumalouomega pointed out one solution is to use fewer cores

**Comment by mhubii** [comment]
using less cores does not solve the issue

**Comment by roigcarlo** [comment]
Closing as this was seemingly caused by excessive template usage / old unity build. 

If it keeps failing please reopen
