### ISSUE TITLE
[ExternalSolversApplication] [CMake] Problem when finding LAPACK

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#6848]
Cmake formats a wrong string for the variable LAPACK_LIBRARIES when configuring ExternalSolversApplication (old or fresh install of Kratos), which leads to failed compilation.

Problem first appears in line 38 in applications/ExternalSolversApplication/CMakeLists.txt:
```
# Linking to the absolute value of the lapack
find_package(LAPACK REQUIRED)
message("LAPACK = " ${LAPACK_LIBRARIES})
```

The output of configuration stage (it has my debug messages):
```
-- Found BLAS: /usr/lib/libopenblas.so
***DEBUG $BLAS_LIBRARIES***: /usr/lib/libopenblas_haswellp-r0.3.9.so
linker flags with blas =
BLA_VENDOR = All
-- Found BLAS: /usr/lib/libopenblas_haswellp-r0.3.9.so  
-- Looking for Fortran cheev
-- Looking for Fortran cheev - found
-- A library with LAPACK API found.
***DEBUG $LAPACK_LIBRARIES***: /usr/lib/libopenblas_haswellp-r0.3.9.so-lm-ldl
LAPACK = /usr/lib/libopenblas_haswellp-r0.3.9.so-lm-ldl
LAPACK modified = /usr/lib/libopenblas_haswellp-r0.3.9.so/home/marcelo/Projects/Kratos/applications/ExternalSolversApplication/-lm/home/marcelo/Projects/Kratos/applications/ExternalSolversApplication/-ldl

```
It detects /usr/lib/libopenblas_haswellp-r0.3.9.so-lm-ldl instead of /usr/lib/libopenblas_haswellp-r0.3.9.so

**Comment by philbucher** [comment]
I recommend using the EigenSolversApp instead
The ExternalSovlersApp is inofficially deprecated

**Comment by marandra** [comment]
I wasn't aware of that. I was loading ExternalSolversApplication for AMGCL, but I see now that my scripts are running normally after removing the import. From my side we can close this issue. Thanks.

**Comment by philbucher** [comment]
amgcl is in the core anyway :)
