### ISSUE TITLE
DEM using time.clock

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6873]
I think this method is being removed in newer versions of python (I was using 3.8)
~~~
======================================================================
ERROR: test_KinematicConstraints_1 (test_kinematic_constraints.TestKinematicConstraints)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/__w/Kratos/Kratos/bin/FullDebug/applications/DEMApplication/tests/test_kinematic_constraints.py", line 113, in test_KinematicConstraints_1
    CreateAndRunStageInOneOpenMPThread(KinematicConstraintsTestSolution, model, parameters_file_name)
  File "/__w/Kratos/Kratos/bin/FullDebug/applications/DEMApplication/tests/test_kinematic_constraints.py", line 24, in CreateAndRunStageInOneOpenMPThread
    my_obj(model, project_parameters).Run()
  File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/analysis_stage.py", line 49, in Run
    self.Initialize()
  File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/DEMApplication/DEM_analysis_stage.py", line 309, in Initialize
    self.report.Prepare(timer, self.DEM_parameters["ControlTime"].GetDouble())
  File "/__w/Kratos/Kratos/bin/FullDebug/KratosMultiphysics/DEMApplication/DEM_procedures.py", line 1215, in Prepare
    self.initial_pr_time = timer.clock()
AttributeError: module 'time' has no attribute 'clock'
~~~

I think you can use `time.time()` instead.
Can you please take a look @KratosMultiphysics/dem

**Comment by maceligueta** [comment]
Unfortunately, time.time() gives a different result from what time.clock() does. `clock()` counts the time of all threads, while `time()` counts the wall time. Actually, we are using `time()` in the same file with a different purpose.
Apparently, there's no equivalent to `clock()` in Python2. I would use `perf_counter()` or maybe `process_time()` in Python3, but we would break the compatibility with Python2.

**Comment by maceligueta** [comment]
How is the status of Python2 support? #6610

**Comment by maceligueta** [comment]
I can remove clock() temporarily until we are fully Python3

**Comment by philbucher** [comment]
Thanks for checking @maceligueta 
Maybe you can do like we do in [KratosUnittest](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/KratosUnittest.py#L31-L33)

**Comment by philbucher** [comment]
you could have a free fct that calls either `clock` or `perf_counter` depending on the python version
what do you think?
this way you would be completely independent of #6610

**Comment by maceligueta** [comment]
I gues there's no clean solution to this... I'll be a bit busy for a couple of days, after that I will implement any of these solutions. Maybe the version selector is the only one fully functional.

**Comment by philbucher** [comment]
Since the release is almost done which was the blocker for dropping the support in #6610 I guess we can first finalize that and then return to the clock issue I suppose

Maybe then you could just replace clock with perfcounter

**Comment by philbucher** [comment]
@maceligueta the python 2 support is now officially dropped
Can you please update your code now?
