### ISSUE TITLE
____

### ISSUE THREAD

**Issue by glovatski** [KratosMultiphysics/Kratos#6882]
Hi
How i can run Kratos software?
do i need install Phyton compiltor or other soft?
 
And can i to do something like this:
http://www.sd.ruhr-uni-bochum.de/Particle_Finite_Element_Simulation_Fresh_Concrete_3DPrinting.html

**Comment by rubenzorrilla** [comment]
> Hi
> How i can run Kratos software?
> do i need install Phyton compiltor or other soft?
> 

In the [wiki page](https://github.com/KratosMultiphysics/Kratos/wiki) you can find how to get Kratos for both Windows and Linux OS. In case you need to build Kratos on your own (it might be possible as you target a quite complex application) you can also find how to do it in [Linux](https://github.com/KratosMultiphysics/Kratos/wiki/Linux-Build) and [Windows](https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install) in the wiki.

> And can i to do something like this:
> http://www.sd.ruhr-uni-bochum.de/Particle_Finite_Element_Simulation_Fresh_Concrete_3DPrinting.html

For this I refer you to the PFEM group, @KratosMultiphysics/pfem, specially to @AFranci who is in charge of the PFEM CFD application.

**Comment by philbucher** [comment]
closing since inactive
