### ISSUE TITLE
Windows libs are not being installed

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#69]
Following #60, DLL should be installed in the libs dir in windows automatically. 

This should be done for the direct dependencies:
* Python
* Boost python
* LibBlas
* Lapack

It also would be nice to have the mingw dependencies. I will propose some solutions in an upcomming PR to tackle this.

**Comment by loumalouomega** [comment]
@roigcarlo So, this was the problem I was suffering last week?

**Comment by roigcarlo** [comment]
Yup

**Comment by roigcarlo** [comment]
@josep-m-carbonell I will close this issue since CMake project for windows as a whole needs a full rework which I will do along with other changes in the overall compile process (#803).

**Comment by josep-m-carbonell** [comment]
Ok
