### ISSUE TITLE
[Fluid][FractionalStepStrategy] Check is inconsistent

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6930]
The `Check` in the FractionalStepStrategy is not consistent with the other strategies in the Core:
- [InitializeStrategy](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/custom_strategies/strategies/fractional_step_strategy.h#L940) calls `this->Check()` twice! Those calls should be removed completely, `Check` is [called from Python](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/python_scripts/fluid_solver.py#L142-L143)
- Maybe `InitializeStrategy` should even be called in the regular `Initialize` of the Strategy?
- The `Check` methods of the Pressure- & Velocity Strategies are never called! I recommend adding a `Check` method to the `SolverSettings` (that calls those missing `Check` methods) that gets called in the `Check` of the `FractionalStepStrategy`
- The [calls for the `Check` of elements and conditions](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/custom_strategies/strategies/fractional_step_strategy.h#L195-L209) should be removed since this is done through the `Scheme` => see #6754

**Comment by rubenzorrilla** [comment]
Thanks for reporting. I'll take care soon.

**Comment by philbucher** [comment]
ping @rubenzorrilla :)
