### ISSUE TITLE
[CoSim] delayed start of solvers depending on condition

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6937]
@KratosMultiphysics/cosimulation 

@KlausBSautter has the following application case (simplified, please correct me if I am wrong @KlausBSautter): Depending on the state of one solver, the other solver starts delayed.
=> for the rock fall protection nets if the dem-particles are close to the structure, then the structural solution starts.

Ofc this can be hardcoded somehow, but I was thinking that this could also be useful for other application cases.

I thought of how to implement this, but I could not come up with a good solution so far.
I think in order to be flexible enough to do this and possibly other things this needs to be implemented in python. I.e. sth similar to the `CouplingOperations`. => has access to all the solvers and can determine whether it is time to start or not.

The coupled-solver would then check if such an object exists for a particular solver and if so ask it if the solution started already

Any thoughts?

**Comment by KlausBSautter** [comment]
vll so?   


 "problem_data" :
    {
        "start_time" : 0.0,
        **"start_time_solvers" : [0.0,1.0,1.1, .....]**
        "end_time" : 1.3,
        **"end_time_solvers" : [1.0,1.1,1.3, .....]**
        "echo_level" : 0,
        "print_colors" : true,
        "parallel_type" : "OpenMP"
    },


then in each solver check 
if time >= my_start_time: 
    myself.time = time
    myself.run()

**Comment by philbucher** [comment]
@KlausBSautter that we can do ofc (which would be a lot simpler to implement) but then you cannot check anything, i.e. you cannot check if the rocks are close to the net

**Comment by KlausBSautter** [comment]
ah I see, maybe we could do this either way. And set specific start_simulation_flag by doing this:

> The coupled-solver would then check if such an object exists for a particular solver and if so ask it if the solution started already

I like this idea. Everyone could overwrite the function to adjust it if necessary
