### ISSUE TITLE
[Windows] Github clone fails because filenames are too long

### ISSUE THREAD

**Issue by tteschemacher** [KratosMultiphysics/Kratos#6946]
Hey,

there are some files added recently which have a super long name. Could you please shorten the names as it can cause troubles in some windows systems. Would be nice. Thank you!

error: unable to create file applications/MultilevelMonteCarloApplication/external_libraries/XMC/xmc/classDefs_solverWrapper/problemDefs_KratosMultiphysics/poisson_2d/problem_settings/parameters_poisson_square_2d_coarse.json: Filename too long
error: unable to create file applications/MultilevelMonteCarloApplication/external_libraries/XMC/xmc/classDefs_solverWrapper/problemDefs_KratosMultiphysics/poisson_2d/problem_settings/parameters_poisson_square_2d_finer.json: Filename too long
error: unable to create file applications/MultilevelMonteCarloApplication/external_libraries/XMC/xmc/classDefs_solverWrapper/problemDefs_KratosMultiphysics/poisson_2d/problem_settings/parameters_poisson_square_2d_level_0.json: Filename too long
error: unable to create file applications/MultilevelMonteCarloApplication/external_libraries/XMC/xmc/classDefs_solverWrapper/problemDefs_KratosMultiphysics/poisson_2d/problem_settings/parameters_poisson_square_2d_level_1.json: Filename too long
error: unable to create file applications/MultilevelMonteCarloApplication/external_libraries/XMC/xmc/classDefs_solverWrapper/problemDefs_KratosMultiphysics/poisson_2d/problem_settings/parameters_poisson_square_2d_level_2.json: Filename too long
error: unable to create file applications/MultilevelMonteCarloApplication/external_libraries/XMC/xmc/classDefs_solverWrapper/problemDefs_KratosMultiphysics/poisson_2d/problem_settings/parameters_poisson_square_2d_level_3.json: Filename too long
error: unable to create file applications/MultilevelMonteCarloApplication/external_libraries/XMC/xmc/classDefs_solverWrapper/problemDefs_KratosMultiphysics/poisson_2d/problem_settings/parameters_poisson_square_2d_level_4.json: Filename too long

**Comment by philbucher** [comment]
@roigcarlo isn't there a global solution for this?

**Comment by riccardotosi** [comment]
The change is done in #6948 @tteschemacher. Thanks for reporting.

**Comment by roigcarlo** [comment]
As for a global solution. I am afraid no, the only solution would be to shorten the paths ourselves.

There is a change one can do in the windows registry to allow longer paths but that's up to the user. If it is usefull I can leave a link explaining how in the wiki or something.

**Comment by tteschemacher** [comment]
I know how to do that, but maybe it would be still useful for some people. But I think we should still try to keep the path lengths within a certain range.

**Comment by loumalouomega** [comment]
> 
> 
> I know how to do that, but maybe it would be still useful for some people. But I think we should still try to keep the path lengths within a certain range.

In my experience, you can create a virtual drive in Windows to shorten paths

**Comment by tteschemacher** [comment]
> > I know how to do that, but maybe it would be still useful for some people. But I think we should still try to keep the path lengths within a certain range.
> 
> In my experience, you can create a virtual drive in Windows to shorten paths

Yes, but we shouldn't make the first step of getting Kratos more complex than it already is ;)

**Comment by riccardotosi** [comment]
Can you git clone now @tteschemacher ?

**Comment by philbucher** [comment]
I think we could add an Action to prevent this in the future

**Comment by philbucher** [comment]
is this solved?

**Comment by roigcarlo** [comment]
No, but I've been searching on the neet and there is little we can do on our side. In this particular case it is a limitation of the Git Client, not even windows.

`git config --system core.longpaths true` should fix it, but it has to be set on the user side.
