### ISSUE TITLE
Structural Mechanics Application: reading external loads from text files

### ISSUE THREAD

**Issue by playpaolo** [KratosMultiphysics/Kratos#6950]
Good morning @RiccardoRossi  and @loumalouomega!  I was wondering if there is any elegant way of prescribing external loading from the input files. 
Basically, I have text file with pressure histories that should be applied as input (external forces) at different locations of the structural model (membrane in my case).

Thanks a lot!
Pavel

**Comment by loumalouomega** [comment]
Can you show an example of input?

**Comment by playpaolo** [comment]
Thank you Vicente (@loumalouomega )!
Here is how it looks like (left column: time. first raw defines the 4 coordinates at which pressure is recorded. and columns underneath are the pressures ):


time | (2.01, 4.25) | (5.01, 4.25) | (2.45, 1.67) | (5.12. 1.72)
-- | -- | -- | -- | --
0,1861 | 29198,3720765 | 7018,84417749 | 7018,90177711 | 29198,3862891
0,3861 | 29198,3890299 | 7006,36974041 | 7006,43109396 | 29198,5425677
0,5861 | 29198,5288172 | 6997,7294434 | 6997,76507546 | 29198,7506439
0,7861 | 29198,4127557 | 6992,61204751 | 6992,61127991 | 29198,585002
0,9861 | 29198,404187 | 6990,2024164 | 6990,15117227 | 29198,4451243
1,1861 | 29198,6610724 | 6989,54556171 | 6989,42301207 | 29198,5214606

**Comment by loumalouomega** [comment]
The coordinates correspond with existing nodes?, or it is a geometrical position and we should interpolate and smooth those values in the FE representation?

**Comment by playpaolo** [comment]
Its geometrical position.

**Comment by playpaolo** [comment]
But lets say that I would want to apply this value for a relatively large area (I mean: one  pressure history will hold be applied to all nodes of the surface of the structural model at a certain range: for example, all nodes of structural surface wth 3<y<4.5 will be getting the pressure of the first column,... All nodes with 4.5<y<6 will get nodes from the second column)...

**Comment by playpaolo** [comment]
I think this figure explains it better than my writing:
![2D-3D](https://user-images.githubusercontent.com/25840656/82891623-56c15e00-9f4e-11ea-941a-2236132c42b8.png)

**Comment by loumalouomega** [comment]
I will start working right now, I cannot assure how long is going to take me

**Comment by playpaolo** [comment]
Thank you very much @loumalouomega !
