### ISSUE TITLE
Merging Release-5.1  into master

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#696]
@KratosMultiphysics/team-maintainers  Now that the release is finished ( unless some problem pops out ) we should start considering to merge Release-5.1 into master, since it was the first time we do a release like that some changes made to Release-5.1 ( mine included!) did not make it to the master.

~~When we do that, please keep in mind that any changes push to Release-5.1, and to future release branches) should be also made to the master, or they won't be included in the code.~~

~~If everyone agrees I will do it myself tomorrow since there is a power cut and the activity will be lower than normal in our office ( to prevent problems ).~~

**Edit:**
After speaking a bit with some people it will be better that you tell me what needs to be included ported to the master and we will exclude everything else, since a big chunk of commits are picks from branches yet to be merged into the master.

**Comment by maceligueta** [comment]
Hi @roigcarlo . We put a fix in Release 5.1 that we do not want in Master. It was there just to avoid the importation of Matplotlib, but we do want this import in Master. It is just one line of code, if you merge we can fix it real fast. However, we never expected that Release 5.1 would be merged to Master. I commented because more people might be in similar situations.

**Comment by roigcarlo** [comment]
Fair point, didn't think on that. Let me make a list of the commits included in one branch and not in the other and we can decide what to move to the master

**Comment by roigcarlo** [comment]
List of commits not in the master:

1be1c4f44 hotfix-explicit-solver
c76823de7 Corrected minor version
da653091f Removed since python automatically adds pythonXX.zip
90da7eaa0 It is better not to delete the path
680972995 Merge pull request #687 from KratosMultiphysics/hotfix-fsi-potential-segfault
4ae72658a Merge branch 'Release-5.1' into hotfix-fsi-potential-segfault
5ff858cda Merge pull request #690 from KratosMultiphysics/dem-avoids-matplotlib-for-release-5.1
c82efaf42 Merge branch 'Release-5.1' into dem-avoids-matplotlib-for-release-5.1
ed7787e3a Merge pull request #688 from KratosMultiphysics/hotfix-fix-testing-files
86d5a051b line 39 commented to dodge Matplotlib
efda108b4 Fixed python import paths
f72b3b053 Bugix: was carelessly accessing a potentially null pointer.
93c2978eb Added missing json and mpda files to the installed files for some applications
cb2e5f4b0 Merge pull request #678 from KratosMultiphysics/feature-adding-last-corrections-and-fix-structural
f6e9d974a Merge branch 'Release-5.1' into feature-adding-last-corrections-and-fix-structural
172a1de6a Merge pull request #680 from KratosMultiphysics/fix-hydrostatic-pressure-mpi-process
f8cf3790e Body force initialization
3d50fc0a9 Merge branch 'Release-5.1' into feature-adding-last-corrections-and-fix-structural
3728b974a Adding just geometries were the Normal methods has been added
1d941b545 Revert "Updating geometries to the last version (necessary for the quadratic loads)"
6c224198c Merge pull request #677 from KratosMultiphysics/fix-fs-trilinos-strategy
9f70fb90d Making the qud8 test work
5f41d4dcd Updating elements in the StructuralMechanicsApplication
9e591ba6a Fix Trilinos Fractional Step strategy
0377bafc4 Updating structural loads
a94c7ecf7 Updating geometries to the last version (necessary for the quadratic loads)
0f37e2640 Adding quad8
23f6c5ff3 Fix _DEBUG casuistic
cf50a2dc7 Merge pull request #673 from KratosMultiphysics/fix-fs-solver
6200caec7 Adding missing EXTERNAL_PRESSURE variable to nodes. This should fix the weird memory error when using the outlet pressure process.
5b6442afd Preventing a non-threadsafe access to Node::GetValue in FS_strategy.h
943236ade Correction in EffectiveViscosity computation. SegFault in C_SMAGORINSKY GetValue when OpenMP parallelism is activated and minor clean up.
9d79391a7 Merged branch fix-fs-solver into fix-fs-solver
7ac33722e Wrong KRATOS_ERROR macros
22afe589f improving info when KRATOS_DEBUG is on
392ad6791 hotfix - removing a wrongly located error in debug mode. Now an attempt to detect variables with Key 0 is done in the functions GetValue and FastGetValue instead of directly in the method Key()
90dcbf3e5 Add windows packaging script
fc5cf148b Merge branch 'Release-5.1' of https://github.com/KratosMultiphysics/Kratos into Release-5.1
72a6069eb Adding packagin script for linux
5aa27c88e Add needed scripts and changes Solid and Pfem
f4a526b62 Fixed error in mpi_python
9fa7112f7 Minor bugs fixed in FSI serial solvers
7b7cfd16d Merge pull request #626 from KratosMultiphysics/feature-improving-defaults-check-inlet-process
ab7c37a1c Merge pull request #637 from KratosMultiphysics/hotfix-FSI-application-tests
076b0f4cb Updating structural mechanics apps main script to its last version
9f6a4621f Addition of a structural Python solvers wrapper
fa77fac1e Merge pull request #628 from KratosMultiphysics/feature-memory-leak-fixed
e68aa44f8 Adding a const for thread safety.
3282dd0da Fixing a race condition if DYNAMIC_TAU is not defined.
0223183fb Adding a few noalias
2203efea3 Correcting matrix sizes.
fba4a11d7 Using const to prevent a race condition in OpenMP.
925b94286 memory leak fixed

**Comment by roigcarlo** [comment]
@maceligueta After speaking with @jcotela I decided it will be better if we just let everyone merge they own changes into master, as it appears that, apart from the ones that do not need to be included there are some that will be included in a near future.

Sorry for the confusion. I will let the issue open just to remind that there are still changes to be merged.

**Comment by jcotela** [comment]
Just for the record, I'd still want to see all changes in the list somehow incorporated in the master. Regarding issues like the one @maceligueta was mentioning, we need to find a permanent solution anyway, otherwise we will encounter the same bugs again in the next release.
I'd propose keeping the issue open untill all the items in @roigcarlo's list have been somehow addressed in master.

**Comment by jcotela** [comment]
Hi, @roigcarlo and I have been cherry-picking the changes we want to keep for master in branch feature-unmerged-release-fixes. Most of the changes in the previous list have been included, except for those of @maceligueta (which won't be added, as requested). @loumalouomega, can you tell us if you want the following changes to be added to the master (or if they are pending in some other open PR):

<del>a94c7ecf7 Updating geometries to the last version (necessary for the quadratic loads)</del>
<del>0377bafc4 Updating structural loads</del>
<del>5f41d4dcd Updating elements in the StructuralMechanicsApplication</del>
<del>9f70fb90d Making the qud8 test work</del>
1d941b545 Revert "Updating geometries to the last version (necessary for the quadratic loads)"
<del>3728b974a Adding just geometries were the Normal methods has been added</del>

**Comment by jcotela** [comment]
Hi @loumalouomega, I've checked the commits in the list and I see that most of the changes are already in the master (the only one I'm not sure about is the one not crossed out in the list above). We'll go ahead and do the PR with the branch as is, if we missed something feel free to create a new PR.

**Comment by jcotela** [comment]
Done in #707

**Comment by loumalouomega** [comment]
Indeed, sorry for my late reply, I did all the commits manually with already patched commits in the master (these were from long time ago and it was very difficult to find the proper commits)
