### ISSUE TITLE
[TrilinosApp] Error in tests

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#6999]
happens with 2 cores:
~~~
======================================================================
FAIL: test_trilinos_levelset_convection (test_trilinos_levelset_convection.TestTrilinosLevelSetConvection)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/philipp/software/Kratos_MasterBranch/applications/TrilinosApplication/tests/test_trilinos_levelset_convection.py", line 110, in test_trilinos_levelset_convection
    self.assertAlmostEqual(max_distance, 0.7904255118014996)
AssertionError: 0.7333041045431626 != 0.7904255118014996 within 7 places
~~~

I think there have been some changes recently but I don't know which

**Comment by philbucher** [comment]
this was working in #6731 (that was the last state when I remember it worked)

**Comment by roigcarlo** [comment]
I will take a look. Its odd. #6731 is from this april and last commit bdac57c6dcd7e5e4b83337abbae52649ae14f607 has the process file identical :S

**Comment by philbucher** [comment]
> I will take a look. Its odd. #6731 is from this april and last commit [bdac57c](https://github.com/KratosMultiphysics/Kratos/commit/bdac57c6dcd7e5e4b83337abbae52649ae14f607) has the process file identical :S

at least I am quite sure :sweat_smile:

**Comment by philbucher** [comment]
but there were quite some changes in the core related to this

**Comment by ddiezrod** [comment]
I will take a look, I'm quite sure is related to the changes in the element size inside the level set element. In that case, I think there is no much we can do but change the test results.

**Comment by rubenzorrilla** [comment]
> I will take a look, I'm quite sure is related to the changes in the element size inside the level set element. In that case, I think there is no much we can do but change the test results.

I agree the problem is most probably related to this.
