### ISSUE TITLE
feature branches should have specific and descriptive name

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#7]
Would you please give a more specific and descriptive name to the pfem_development feature branch? Also he branch names making a new feature should start with feature and the words in branch should be separated by dash "-" not underline "_"

At this moment we don't have a convention documentation about branch naming in wiki and such a generic name would give a wrong message to other developers in naming their branches.

**Comment by josep-m-carbonell** [comment]
ok, I was testing the gitkraken and correcting a bug in the pfembase, I wil use dash and more descriptive names in future branches

**Comment by pooyan-dadvand** [comment]
Thanks! I have also imagine that it was a kind of test! 
👍

**Comment by pooyan-dadvand** [comment]
Also I should add the convection as soon as possible....

**Comment by josep-m-carbonell** [comment]
Ok, that will be the best, if not it is a little bit confusing and branches are a total mess, I agree with you.
