### ISSUE TITLE
[FluidDyn] ImportError trilinos-extension

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7001]
Happens in the CI and also on my local machine
@KratosMultiphysics/fluid-dynamics 

~~~
from KratosFluidDynamicsTrilinosExtension import *
ImportError: /__w/Kratos/Kratos/bin/Custom/libs/KratosFluidDynamicsTrilinosExtension.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZTI14Epetra_MpiComm
~~~

**Comment by sunethwarna** [comment]
Could you try running this line 
`import KratosMultiphysics.FluidDynamicsApplication.TrilinosExtension as KratosCFDTrilinos` ?

In my PC, TrilinosExtension works fine.

**Comment by philbucher** [comment]
> Could you try running this line
> `import KratosMultiphysics.FluidDynamicsApplication.TrilinosExtension as KratosCFDTrilinos` ?
> 
> In my PC, TrilinosExtension works fine.

still fails

**Comment by philbucher** [comment]
it seems like this happens only when using cotire

**Comment by philbucher** [comment]
maybe related to
https://github.com/KratosMultiphysics/Kratos/pull/5769
