### ISSUE TITLE
BlockBuilder builds RHS in BuildLHS

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7022]
https://github.com/KratosMultiphysics/Kratos/blob/0f7b1083807041af6f8c927cd518e5be9dad9987/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L301-L312

to be refactored

the TrilinosBlockBuilder does this correct

FYI @emiroglu

**Comment by loumalouomega** [comment]
See #7028
