### ISSUE TITLE
Missing libgfortran.so.3 in Release 5.1 (Manjaro Linux)

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#704]
Our linux release expects to find a libgfortran.so.3 in the system, but Manjaro linux uses libgfortran.so.4 and execution fails as soon as the external solvers application is imported. I suspect the same will happen in Arch Linux (since manjaro uses the arch repositories).

**Comment by jcotela** [comment]
It also does not like the system openmpi...

**Comment by RiccardoRossi** [comment]
i would say that we should package the libgfortran we need

**Comment by RiccardoRossi** [comment]
@roigcarlo would it be possible at compile time stripping the library name of version number?

**Comment by RiccardoRossi** [comment]
Ok, here it says that they are incompatible....

https://stackoverflow.com/questions/44658867/r-v3-4-0-2-unable-to-find-libgfortran-so-3-on-arch

It suggests to install an old gcc together with the system one.

Regarding mpi I have no suggestions...

**Comment by roigcarlo** [comment]
@RiccardoRossi We are compiling the release with gcc 4.9. It is the minimum version compatible with Kratos.

I think I can manage to strip the lib number if you want, but I have to try.

In windows we have the similar problem with gfortran and we just ship it with the other libs. Should be the same in linux ( we already did that with the release for simphony which had to use an older version of zlib and openssl). But I can't test it unitl tomorrow.

About the mpi, no clues, I can try to replicate what I did in the old release machine, but give me some that as it was no straightforward....

**Comment by RiccardoRossi** [comment]
just to tell that i have been reading, and it looks like that if the first digit changes it is a abi breaking change...so we can not do much. i think that copying libgfortran and libstdcxx, glibc, etc, is an option...but it still will not solve the mpi problem. 
for that we will need the user to install side by side the old mpi, which may not be doable. we need to read how this is managed in rolling releases

**Comment by loumalouomega** [comment]
For the future we can try to use this to avoid problems of compatibility (everything packed in a flatpak style):

https://build.snapcraft.io/

**Comment by roigcarlo** [comment]
Does also handle system dependencies? :open_mouth:

**Comment by loumalouomega** [comment]
It is supposed to create a snap file https://en.wikipedia.org/wiki/Snappy_(package_manager) -> Selfcontained

**Comment by pooyan-dadvand** [comment]
Just a question, making a debian package won't install the dependencies?

**Comment by RiccardoRossi** [comment]
my 2 cents: ... i think that if you package with libgfotrtran.so.3 it will not work with libgfotran.so.4 since the change in the number indicates ABI breakage (according to linux guidelines)

one may make a deb file telling to include old packages, but they may well be unsopported in newer releases.

what we should do is equivalente to Vicente's suggestion, however we can not use snap since we want it installed with the gid...

**Comment by pooyan-dadvand** [comment]
But the idea is not to include the old packages. As you suggest to do something like @loumalouomega suggestion, I would just put the dependency so the packager would install it if is missing (and compatible). For GiD we may pack it with Kratos like the GiD itself.

**Comment by RiccardoRossi** [comment]
To my understanding snap packages all the files, exactly as we are doing...

https://snapcraft.io/docs/snaps/metadata

It is not like a Deb or an rpm. And even in this case you would have to say
"I depend on libgfortran3", please install the old package...

**Comment by loumalouomega** [comment]
Hello, the idea of the self contained package is that it is not required
today install anything else (like in Windows) everything is included in the
package. This duplicate the libraries and files in their system, but for
our case is more practical, look http://flatpak.org/ for example. Snap is
the one supported by Canonical, flatpack is the one that supported by
plasma project, but the idea is the same.

**Comment by pooyan-dadvand** [comment]
I am a little bit confused:

- For standalone installing (without GiD) can we make a deb and make the packager to install all dependencies as asked?

- What is the advantage of the Snap and  Flatpack? You think of them as alternative for deb or zip file?

**Comment by roigcarlo** [comment]
@pooyan-dadvand To my understanding the advantage of snap and flat is that they are universal packages.

- By himself, a deb is a problem for all systems that are not based on Debian: OpenSuse, RedHat, Arch and they flavors to name some.
- A zip file do not manage the dependencies. But it is universal to any linux system

Snap and Flatpack should manage dependencies by creating a bundle and be universal to any linux system at the same time.

That said, we will probably have problems with the openmpi library. But it should be the only one with conflicts...

**Comment by roigcarlo** [comment]
@jcotela I just uploaded the new releases with libgfortran and some other conflicting-prone libraries, can you test if it works (https://github.com/KratosMultiphysics/Kratos/releases/tag/v5.1.1)

I will test it myself in a system running the 4.12 kernel

**Edit**:
I've detected another problem which should be already fixed. Apparently it works in my system (Clean Arch up to date as of 10-08-2017)

**Comment by jcotela** [comment]
Hi @roigcarlo Your new update works in serial, but finishes with the following error
``` 
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
```
The results look OK though, so apparently the error is not a real problem.

The parallel version complains about openmpi again (sorry)
```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Traceback (most recent call last):
  File "MainKratos.py", line 21, in <module>
    from KratosMultiphysics.mpi import *
  File "/home/jcotela/GiDx64/13.1.8d/problemtypes/kratos.gid/exec/Kratos/KratosMultiphysics/mpi.py", line 14, in <module>
    import mpipython
ImportError: libmpi_cxx.so.1: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "MainKratos.py", line 21, in <module>
    from KratosMultiphysics.mpi import *
  File "/home/jcotela/GiDx64/13.1.8d/problemtypes/kratos.gid/exec/Kratos/KratosMultiphysics/mpi.py", line 14, in <module>
    import mpipython
ImportError: libmpi_cxx.so.1: cannot open shared object file: No such file or directory
```
This is my laptop again: Manjaro Linux with 4.9 kernel.

**Comment by roigcarlo** [comment]
@jcotela Thx!, working on the python warning, about the openmpi.. that does not have a quick fix but I'll keep trying.

**Comment by jcotela** [comment]
@roigcarlo In the end, I think we will need to choose which platforms we want to support for the relase anyway. For the record, I would be perfectly fine with supporting whichever flavor of ubuntu is current (or LTS).

Maybe a desirable thing would be to provide a how-to about how to "install" your kratos manually within GiD (if there is not one), so that an arch linux user (for example) can download the GiD interface (without executables), compile the executable from source code and easily link the two.

**Comment by roigcarlo** [comment]
@jcotela Agree in part, I would like to supoport all the systems if possible, but if someone has been able to install let's say Arch or Gentoo to put an example, I assume they have the hability to compile kratos without major problems. That being said, apart from openmpi the release should be multidist. 

I updated the release file so it minizes the PYTHONHOME problem. As a side effect I have found a way to set the pythonpath to kratos inside runkratos, so people do not have to set the variable by themselves, which is good :). 

@jginternational It should be ready to upload, they are packed with the changes in GiDInterface. Can you yake a look?

**Comment by jginternational** [comment]
@roigcarlo Good. We'll upload also DEM.

(Ready for another "To production Friday")

**Comment by RiccardoRossi** [comment]
@jginternational well, we promised it would not be friday ;-)

it is thursday today :-D

**Comment by jginternational** [comment]
Should I assume that [this ](https://github.com/KratosMultiphysics/Kratos/releases/tag/v5.1.1)is the version? @roigcarlo

**Comment by roigcarlo** [comment]
Yes, that's it

**Comment by roigcarlo** [comment]
That was already solved right?

**Comment by loumalouomega** [comment]
I think we started a conversation about using deb, snap, flarck....

**Comment by roigcarlo** [comment]
Ok, closing this...
