### ISSUE TITLE
Create table and add to submodelpart

### ISSUE THREAD

**Issue by ipouplana** [KratosMultiphysics/Kratos#7074]
Is it possible to create a table and add it directly to a submodelpart using the AddTable method?

I have been able to create a table and fill it, but then I cannot add it to a submodelpart because I need a Table::Pointer in the AddTable method... Do you know any way to solve this?

**Comment by loumalouomega** [comment]
I am quite sure you can do it right now

**Comment by loumalouomega** [comment]
I have done a test in #7075, what is missing?

**Comment by ipouplana** [comment]
Thanks a lot Vicente, I will try it as you have done in the test.

**Comment by ipouplana** [comment]
This is solved now. The thing is that I was not initializing the Table::Pointer properly, i.e., as 
`TableType::Pointer p_table = Kratos::make_shared<TableType>();`
and then I was getting a segmentation fault when trying to fill it.
