### ISSUE TITLE
[several apps] Use GetPython3Command() instead of "python3" if which("python3") is not None else "python"	

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#7099]
Replace in all places where it appears...

**Comment by philbucher** [comment]
depends on #7096

**Comment by maceligueta** [comment]
@farrufat-cimne , can you take care of this? You can follow the same change done in  #7096. If you could do it for the whole of Kratos, it would be great. I do not think it appears many times.

**Comment by farrufat-cimne** [comment]
sure
