### ISSUE TITLE
out of date page for windows installation still reachable

### ISSUE THREAD

**Issue by antonialarese** [KratosMultiphysics/Kratos#7115]
Dear all, 

Apparently it is still available on the web the out of date installation page for windows.
https://github.com/KratosMultiphysics/Kratos/wiki/Windows-Install

(it can be esaily found by putting "kratos windows installation" in any web browser).

Thanks!

**Comment by antonialarese** [comment]
...BTW I would say that the new install.md page is missing the final parts (how to compile, post compilation, testing, etc...)

**Comment by philbucher** [comment]
thanks for the feedback @antonialarese

**Comment by roigcarlo** [comment]
Ups I was not aware you could reach unindexed pages.

**Comment by roigcarlo** [comment]
Closing, old page redirects to install.md and I updated the file with some missing parts.

**Comment by antonialarese** [comment]
Thanks!!
