### ISSUE TITLE
whether the cfd solver will suppport finite volume method

### ISSUE THREAD

**Issue by BobCFD** [KratosMultiphysics/Kratos#7129]
1、Whether the cfd solver will suppport finite volume method in the future.
2、It seems  compressible flows solver(CompressiblePotentialFlowApplication)has not been finished.
3、where can we beginers get more complex cases to study.

**Comment by RiccardoRossi** [comment]
mentionining @KratosMultiphysics/fluid-dynamics 

> 1、Whether the cfd solver will suppport finite volume method in the future.
there is no plan in this direction for the moment ... however if someone knowledgeable wants to put effort in that direction things could be done.

> 2、It seems compressible flows solver(CompressiblePotentialFlowApplication)has not been finished.
It is a work in progress, @rubenzorrilla is actively looking into it

> 3、where can we beginers get more complex cases to study.
Do you have access to GiD? that would allow you to create a testcase as you like

**Comment by loumalouomega** [comment]
> 3、where can we beginers get more complex cases to study.


https://github.com/KratosMultiphysics/Examples

**Comment by rubenzorrilla** [comment]
As @RiccardoRossi pointed out there is an explicit compressible full Navier-Stokes solver (written in conservative variables) under development.

**Comment by rubenzorrilla** [comment]
(sorry closed by mistake)

**Comment by rubenzorrilla** [comment]
Closing the issue due to inactivity. @BobCFD feel free to reopen it again if required. Thanks!
