### ISSUE TITLE
Preparing for autumn release

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#714]
@KratosMultiphysics/structural-mechanics , over the next week we 'll issue the first suffix release to iron out some bumps.

I think it is time to think to what is to be included in the autumn release (regarding the structuralmechanics).

In my opinion we should aim at
*support for beam orientation (ping @jginternational)
*exporting eigenvalue solution to the interface. Here we need to solve the problem of Windows support
*exporting some good constitutive law to the gui (@marandra, can you backpirt some of your CLs?)

Other ideas are very welcome.

It would be good if someone steps up as a release manager for the next release of the structural mechanics (to be duly acknowledged in the github). Any candidate?

**Comment by pooyan-dadvand** [comment]
Good idea! I would suggest to make a project for that.

**Comment by marandra** [comment]
Sure. I'll start cleaning up our CLs so they can be included in the next
release.

**Comment by philbucher** [comment]
We added two shell elements, see #716 @jginternational 
`ShellThinElementCorotational3D4N` and `ShellThickElementCorotational3D3N`

**Comment by jginternational** [comment]
Hi @philbucher ,

You can add them to the Structural app in the GUI.
Since the elements are already implemented with different number of nodes, you just need to add the new topology features.

Feel free to add it yourself:
https://github.com/KratosMultiphysics/GiDInterface/blob/master/kratos.gid/apps/Structural/xml/Elements.xml#L361

**Comment by philbucher** [comment]
thanks @jginternational I will add it once the elements are merged
