### ISSUE TITLE
Path Error while Installing Kratos in Window 10 

### ISSUE THREAD

**Issue by ashwakumar** [KratosMultiphysics/Kratos#7145]
I am new to Kratos.
I ran the Configuration batch file  and It completed the compilation without any error. Now When I try to execute the runkratos.exe from Command prompt. I am getting this error message.
I set my Environment variable as mentioned in https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md

My configration.bat file is 

@echo off
rem Please do not modify this script
 
rem For any question please contact with us in:
rem  - https://github.com/KratosMultiphysics/Kratos
 
rem Optional parameters:
rem You can find a list will all the compiation options in INSTALL.md or here:
rem  - https://github.com/KratosMultiphysics/Kratos/wiki/Compilation-options
 
rem Set compiler
set CC=cl.exe
set CXX=cl.exe
 
rem Set variables
set KRATOS_SOURCE=~0,-1%/..
set KRATOS_BUILD=%KRATOS_SOURCE%/build
set KRATOS_APP_DIR=applications
 
rem Warning: In windows this option only works if you run through a terminal with admin privileges
rem set KRATOS_INSTALL_PYTHON_USING_LINKS=ON
 
rem Set basic configuration
if not defined KRATOS_BUILD_TYPE set KRATOS_BUILD_TYPE=Release
if not defined BOOST_ROOT set BOOST_ROOT=E:\Library\boost_1_73_0
if not defined PYTHON_EXECUTABLE set PYTHON_EXECUTABLE=C:\Windows\py.exe
 
rem Set applications to compile
set KRATOS_APPLICATIONS=
CALL :add_app %KRATOS_APP_DIR%\EigenSolversApplication;
CALL :add_app %KRATOS_APP_DIR%\StructuralMechanicsApplication;
CALL :add_app %KRATOS_APP_DIR%\FluidDynamicsApplication;

 
rem Clean
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\cmake_install.cmake"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeCache.txt"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeFiles"
 
rem Configure
@echo on
cmake -G"Visual Studio 16 2019" -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%" -DUSE_EIGEN_MKL=OFF
 
rem Build
cmake --build "%KRATOS_BUILD%/%KRATOS_BUILD_TYPE%" --target install -- /property:configuration=%KRATOS_BUILD_TYPE% /p:Platform=x64
goto:eof
 
rem Function to add apps
:add_app
set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%1;
goto:eof

Need Urgent help

![Env Variable](https://user-images.githubusercontent.com/50194935/85874860-8ffe1f80-b7d3-11ea-9564-c99127430b6f.PNG)
![Error](https://user-images.githubusercontent.com/50194935/85874862-9096b600-b7d3-11ea-80f9-831904a675d1.PNG)

**Comment by roigcarlo** [comment]
Hi @kashwanij 

Missing DLL should be in
`C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\libs`

You can add it to your path or just copy the missing dll there.

Also, if you compiled Kratos in your computer you can just run any script directly with `py` command in the CMD/Powershell without the need to use `runkratos`

For example:
```Python
# test.py
import KratosMultiphysics as KMP
```

then:

`> py.exe test.py`

Please thell me if this works for you.

**Comment by kashwanij** [comment]
This is working.
Thank you so much :-)
