### ISSUE TITLE
about including -DGLIBCXX_DEBUG

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#715]
Hi all, and in particular @maceligueta 

it looks like we can not safely add the GLIBCXX_DEBUG option.

take a look to this thread and the links therein

[LINK](https://github.com/trilinos/Trilinos/issues/1576#issuecomment-320544784)

(i did get a segfault)

**Comment by pooyan-dadvand** [comment]
I see.... So I would only active the stl checks in Visual C in full debug which works for me (obviously without trilinos)
