### ISSUE TITLE
Self weight on shell-model

### ISSUE THREAD

**Issue by veiguf** [KratosMultiphysics/Kratos#7161]
Hi!
In GiD I built a shell-model and I am trying to load it with self weight. There I get the following error with VOLUME_ACCELERATION_X. Attached you can find a small example. Any idea how this can be fixed?
[ShellSelfWeight.zip](https://github.com/KratosMultiphysics/Kratos/files/4856822/ShellSelfWeight.zip)
[Error.txt](https://github.com/KratosMultiphysics/Kratos/files/4856827/Error.txt)

**Comment by philbucher** [comment]
see #6523

you need to add `"constrained" : false` to the process that assigns `VOLUME_ACCELERATION`

@jginternational can you please update this in the interface? Or was this already done (also asking @rubenzorrilla since this affects in multiple places)

**Comment by veiguf** [comment]
Thank you very much!

**Comment by veiguf** [comment]
"loads_process_list"       : [{
            "python_module" : "assign_vector_by_direction_process",
            "kratos_module" : "KratosMultiphysics",
            "check"         : "DirectorVectorNonZero direction",
            "process_name"  : "AssignVectorByDirectionProcess",
            "Parameters"    : {
                "model_part_name" : "Structure.SelfWeight3D_Self_weight_Auto1",
                "variable_name"   : "VOLUME_ACCELERATION",
                "interval"        : [0.0,"End"],
                "modulus"         : "x*100",
                "constrained" : false,
                "direction"       : [1.0,0.0,0.0]
            }
        }],

**Comment by rubenzorrilla** [comment]
I think this was already fixed... @veiguf are your Kratos synchronized with a more or less recent master?

**Comment by veiguf** [comment]
I updated Kratos (pulled and recompiled from origin master) and GiD inteface just now. Then I build a new example and got the same error with VOLUME_ACCELERATION_X. Adding `"constrained" : false`, it works!

**Comment by jginternational** [comment]
Hi @veiguf , can you attach the gid model? (a zip with your case folder and files)

**Comment by jginternational** [comment]
Hi @veiguf , Can you attach your gid model? (A zip containing your case folder and files)

**Comment by rubenzorrilla** [comment]
> I updated Kratos (pulled and recompiled from origin master) and GiD inteface just now. Then I build a new example and got the same error with VOLUME_ACCELERATION_X. Adding `"constrained" : false`, it works!

Then we forgot to fix it... @jginternational once we get the example from @veiguf I'll explain the error to you.

**Comment by veiguf** [comment]
Attached you can find my example.
[ShellSelfWeight.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/4878791/ShellSelfWeight.gid.zip)

**Comment by rubenzorrilla** [comment]
@jginternational which is the status of this?

**Comment by jginternational** [comment]
I think it's fixed in the branch above @rubenzorrilla https://github.com/KratosMultiphysics/GiDInterface/pull/754

**Comment by rubenzorrilla** [comment]
mmm... I think these are different issues. The point in here is that we are adding `VOLUME_ACCELERATION` DOFs. KratosMultiphysics/GiDInterface#754 fixes the membrane element.

**Comment by philbucher** [comment]
is this solved?

**Comment by rubenzorrilla** [comment]
@jginternational I remember discussing this with you. I can't remember however if we finally fixed it. Can you please comment on it? Thanks!

**Comment by jginternational** [comment]
The process associated to the volume acceleration has a parameter called "constrained" set by default to 0.
So I think it's done
