### ISSUE TITLE
Legacy applications

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#7169]
@playpaolo and I are interested in the IncompressibleFluidApplication for a project. I tried to fix that app, but then I realized I don't have permissions to push a branch on KratosLegacyApplications repo.

@philbucher @roigcarlo  can you check the permissions?

**Comment by philbucher** [comment]
the @KratosMultiphysics/technical-committee is aware of this but we didn't get a chance to reach a consensus yet
Sorry for the delay

**Comment by miguelmaso** [comment]
any news?

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee highly encourage developers to work with the Kratos repository itself. However, we realized that making changes in the legacy repository may help in bringing back some features to the current repository.

For this reason, we are opening the PR permission, but please consider it as a way to improve the code there to be ported back to the standard one.
