### ISSUE TITLE
Fluid Dynamics plan for the next Kratos release

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#719]
The purpose of this issue is to open a discussion and set the priorities for the next round of improvement of the Fluid Dynamics application. In particular, I'd like to define the improvements and new features to be included in the next Kratos release (planned for this autumm).

I'll start with my own wishlist of planned features:
- Internal reorganization of the code of the different elements, with the goal of reducing duplication: right now several things have incompatible symbolic and pure C++ implementations.
- Similarly, unification of the python solvers.
- Re-formulation of the dependency with trilinos application: the CFD stuff should depend on trilinos, not the other way around.
- Support for MPC conditions (and potentially, Chimera approaches) once they are included in the Kratos Core.

Everyone is encouraged to suggest new features, but I'd like to at least hear the opinion of @KratosMultiphysics/fluid-dynamics, @adityaghantasala, @msandre.

We have also created a [project](https://github.com/KratosMultiphysics/Kratos/projects/10) to organize new developments.

**Comment by msandre** [comment]
+1 for unification of python solvers.

Long term would also be in favor of doing something to reduce the schemes with slip and periodic extensions to something unified based on MPC conditions, but not sure how feasible that is with the current state.

**Comment by rubenzorrilla** [comment]
I completely agree with @jcotela wishlist. Indeed, I think that the planned features are sorted according to their priority. 

With regard to the python solvers issue, I want to highlight some ideas that we came up in the past just to keep them in mind
- Discuss the Python solvers inheritance structure.
- The restart is not included in the last fluid dynamics solvers. Include it.

Finally, I found that there are still some missing TODOs in the list above
- Validation. In the past some people asked us for running some more validation cases. Even though the elements in the Fluid Dynamics have been already validated, I think that we have to put some effort in setting up some well known benchmark cases as validation test cases in the test folder (of course with some fancy automatized postprocess).
- Discuss and decide which is the "reference" element. With "reference" element I mean the element that appears in the interface.

**Comment by RiccardoRossi** [comment]
i also agree about all what is being said here. my only concern is that the release is due towards the end of october. This will mean feature freeze at the beginning of october. That is...tomorrow. 

We need to be realistic in what can and can not make for the release windows. Next occasion will be in january...

**Comment by adityaghantasala** [comment]
Regarding the MPC conditions and incorporating them completely into the core, I would suggest we do it in the release in January. By that time current master thesis will be consolidated, thus providing a robust implementation and also documentation.

**Comment by jcotela** [comment]
@RiccardoRossi I agree that we might need to reduce our expectations for the immediate release, but I'm also interested in having a longer-term plan. I realize we all have other responsabilities, so whatever we can't fit in October will just have to wait for January.

@adityaghantasala Good point, let's focus on the other issues first, then.

@rubenzorrilla Regarding a reference element, there are two separate problems: Monolithic vs. Fractional Step and the current issue with duplication of implementations. I understand you are concerned with the second, but I hope this will solve itself with the internal conding clean-up (that is, once we have a unified structure, the current old-style elements will be phased out).

Considering the short time frame and the opinions we have gathered up to now, I think the priority for the immediate release should be defining/updating the Python solvers. Adding a set of benchmarking cases is also a relatively low-hanging fruit (or at least we can add a few cases and expand in future releases). The fluid element duplication issue is also a strategic concern for us in Barcelona, and we will keep working on it. We will see how much else we can fit...

**Comment by RiccardoRossi** [comment]
+1 for Jordi's comments.

one question: what is it needed on the GUI side?

**Comment by jginternational** [comment]
From the GUI point of view, Fluid is one of the most complete apps. It has an example for 2D and 3D and some inherited apps.
We can add the restart easily, 'cose it was added to 'common' when I added it to PFEM. It will be fine if we keep the format (in the gui and in the json)
![image](https://user-images.githubusercontent.com/5918085/29140182-df6195ba-7d49-11e7-8fd5-785ab35bc77a.png)

We are currently working both with Monolithic and Fractional step, and just one element. Keep that issue indoors.

**Comment by philbucher** [comment]
Does the FluidDynamicsApplication make use of the materials in json format like Structuralmechanics? (e.g. StructuralMaterials.json)
Last time I used it I think both files, the old format and the new json format were created, but I don't knowe which one was used

**Comment by jginternational** [comment]
@philbucher You are right. Both formats are being written, old format in MDPA and new FluidMaterials.json but I think that the json file is not being used yet.

Maybe we can use only tha json file soon @rubenzorrilla

**Comment by rubenzorrilla** [comment]
@jginternational is right. Both are written but the material properties are still taken from the *.mdpa file. 

The point about using the new json format, is that multiple elements in the FluidDynamicsApplication have the stress computation inside the element, meaning that no constitutive law object is required, meanwhile the "new" (symbolic) ones use the constitutive laws. IMO we first have to solve the elements issue before moving to the new format.

**Comment by jcotela** [comment]
:+1: for @rubenzorrilla. We need to agree on a way to define the "constitutive law" for the different fluid formulations before deciding on the input format.

**Comment by philbucher** [comment]
Hi @KratosMultiphysics/fluid-dynamics 
A student of @adityaghantasala and me will have to use the Spalart-Allmaras TurbModel soon. Do you have plans to include it in the python solvers for the next Release (i.e. until the end of this month)?

**Comment by jcotela** [comment]
@philbucher In short: no. To be honest, I don't trust the current S-A implementation and we have no plans to benchmark it, so I'm afraid it is not production-ready. If you need hints or help setting up the current implementation, I'm happy to help, but I'd advise trying to do some standard test first to build confidence.

**Comment by philbucher** [comment]
@jcotela thx for the information.
I will get back to you if I need your help, thx for that

**Comment by jcotela** [comment]
Closing for now, feel free to add suggestions for future features/improvements in the FluidDynamics project.
