### ISSUE TITLE
[MeshingApplication][MMG] Non-threadsafe operation in MMG process/utilities

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#7209]
Hi,

I have been trying to make use of the feature added in #5337, which returns the __true__ metric tensor after remeshing. 

This works fine if one thread is used:
*metric_tensor_2d (log scale) after remeshing with OMP_NUM_THREADS=1*
![image](https://user-images.githubusercontent.com/32136457/87040636-4e1ca280-c1f1-11ea-86ca-91adc9d4fa35.png)

However, if I run with OMP_NUM_THREADS>1 the metric tensor is written wrongly.

*metric_tensor_2d (log scale) after remeshing with OMP_NUM_THREADS=4*
![image](https://user-images.githubusercontent.com/32136457/87040773-802e0480-c1f1-11ea-90ce-4d4657146458.png)

I tried the same  but removing the #pragma omp decorators both in:

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/custom_processes/mmg_process.cpp

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/custom_utilities/mmg_utilities.cpp

But the same behaviour persists. Any clue on what may be causing the issue?
__EDIT: I must have done something wrong when testing this. Testing it again after @roigcarlo comments, commenting the pragma in these two files prevents the issue from happening, so there is some OMP bug in the code.__

This can be reproduced with the following script:

(try running with OMP=1 and OMP=4 and take a look at the METRIC_SCALAR in the remeshed_gid_output )
[MMG_OMP_TestCase.zip](https://github.com/KratosMultiphysics/Kratos/files/4896901/MMG_OMP_TestCase.zip)

**Comment by loumalouomega** [comment]
I will check once I have the time

**Comment by roigcarlo** [comment]
After some debug:
https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MeshingApplication/custom_processes/mmg_process.cpp#L293

Seems to be the cause of the problem. I imagine that there is a race condition while accessing the mMmgUtilities.GetMetricScalar(r_metric); as probably the call to MMG assumes a sequential access (which is not respected in this case, first node that calls that function get the first results, and the order in not guaranteed if OMP>1

**Comment by roigcarlo** [comment]
Ok it seems that there are other race conditions...

**Comment by marcnunezc** [comment]
> **Edit**
> Sems to be a problem with all loops that call MMG interface functions to set/get nodes elements condition and metrics.

True, I did something wrong when testing disabling the #pragma calls.

I updated the main post, and will try to take a closer look at which lib calls are causing the race condition
