### ISSUE TITLE
Preferred way to cite/acknowledge Kratos in papers?

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#7255]
**Description**
Is there any article to cite, or a text for the acknowledgments (citing grants, institutions, etc.) in the publications?
Any info that must go?

**Additional info**
I don't find this information in the wiki, maybe we can add a "Citing Kratos" article.

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee

**Comment by riccardotosi** [comment]
Hi @marandra , I had the same question and I have been told to cite:

- Dadvand, P., Rossi, R., & Oñate, E. (2010). An object-oriented environment for developing finite element codes for multi-disciplinary applications. Archives of Computational Methods in Engineering, 17(3), 253–297.
- Dadvand, P., Rossi, R., Gil, M., Martorell, X., Cotela, J., Juanpere, E., … Oñate, E. (2013). Migration of a generic multi-physics framework to HPC environments. Computers and Fluids, 80(1), 301–309. https://doi.org/10.1016/j.compfluid.2012.02.004

**Comment by marandra** [comment]
Thanks for the refs @riccardotosi, I'll go with those.

I'll leave the issue open for a little while, in case there are other comments or ideas. I think it'd be good to also add a reference the Kratos github page whenever possible.

**Comment by rubenzorrilla** [comment]
> Thanks for the refs @riccardotosi, I'll go with those.
> 
> I'll leave the issue open for a little while, in case there are other comments or ideas. I think it'd be good to also add a reference the Kratos github page whenever possible.

We can add a "How to cite Kratos" section somewhere. Maybe in the main repo Markdown file?

**Comment by riccardotosi** [comment]
I'd add that you can also cite Kratos latest release:

- Ferrándiz, V. M., Bucher, P., Rossi, R., jcotela, Maria, J., Zorrilla, R., … Tosi, R. (2020). KratosMultiphysics/Kratos: Release 8.0. https://doi.org/10.5281/zenodo.3234644

Please note that in the zenodo web-àge, it is written that 

> Cite all versions? You can cite all versions by using the DOI 10.5281/zenodo.3234644. This DOI represents all versions, and will always resolve to the latest one.

**Comment by philbucher** [comment]
@riccardotosi I like your ideas
Could you please open a PR to initiate a discussion?

I think as @rubenzorrilla suggests having this in the main-readme seem to be a good idea and also consistent with what other libraries do
