### ISSUE TITLE
[Core] After #7138 do we need strategies/explicit_strategy.h?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#7273]
https://github.com/KratosMultiphysics/Kratos/blob/65a31c45ee18626c1092a3b2fdf7fad0e912e649/kratos/solving_strategies/strategies/explicit_strategy.h#L1

This file I assume is no longer required and could be cleared. @KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
Looks old so IMO can go if none is using it

**Comment by rubenzorrilla** [comment]
If it is not used I'd remove it too.
