### ISSUE TITLE
problem with PRESTRESS_11

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#728]
@KratosMultiphysics/structural-mechanics the nightly build tests fail with

File "/home/ubuntu/Kratos/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_solver.py", line 143, in ImportModelPart
    KratosMultiphysics.ModelPartIO(input_filename).ReadModelPart(self.main_model_part)
RuntimeError: Error: PRESTRESS_11 is not a valid variable!!!
 [Line 12 ]

i think this was changed recently, substituting PRESTRESS_** by a vector.
can u confirm/fix the issue?

**Comment by philbucher** [comment]
I think this is related to the recent changes that @longchentum made. Long can you also search for other occurrences o this variable?

**Comment by longchentum** [comment]
Hi, I fixed the issue with this pull request #717.

**Comment by longchentum** [comment]
#717 is merged, please check if the issue is now solved.

**Comment by philbucher** [comment]
For me it works now but lets wait for the result of the nightly tests

**Comment by philbucher** [comment]
nightly tests ran through, closing this
