### ISSUE TITLE
Documentation for Kratos

### ISSUE THREAD

**Issue by gauravbokil8** [KratosMultiphysics/Kratos#7287]
Hi,
I started learning Kratos but could not find a detailed documentation for the classes and methods in the module.
So, I created it myself. I am uploading this crude documentation to help other new users.
Please find attached: **Kratos SphinxDocumentations.zip**
Let me know if it serves well.
Open **index.html** to begin
[Kratos SphinxDocumentation.zip](https://github.com/KratosMultiphysics/Kratos/files/4977600/Kratos.SphinxDocumentation.zip)

**Comment by loumalouomega** [comment]
Thanks @gauravbokil8! 

@KratosMultiphysics/technical-committee I think we should add this to the doc folder and generate automatically in the nightly

**Comment by gauravbokil8** [comment]
Hi @loumalouomega ,
Thanks for the reply. Yes, it would be good to have an official and updated documentation. Most of the examples I've seen are not compliant to the newest build.

**Comment by rubenzorrilla** [comment]
Closing as now we have the [documentation website](https://kratosmultiphysics.github.io/Kratos/). In any case we want to acknowledge again @gauravbokil8 's effort.
