### ISSUE TITLE
Matrix property in StructuralMaterials.json

### ISSUE THREAD

**Issue by peterjwilson** [KratosMultiphysics/Kratos#729]
Hi All,

Was wondering if anyone knows how to define a matrix type material variable in the material file StructuralMaterials.json? This used to be possible when material properties were in the .mdpa file, but I'm not sure if this functionality is available for the StructuralMaterials.json arrangement?

For example, the typical isotropic material variables are written like:

> "Variables"        : {
>                 "THICKNESS"     : 0.1,
>                 "DENSITY"       : 7850.0,
>                 "YOUNG_MODULUS" : 206900000000.0,
>                 "POISSON_RATIO" : 0.29,
>             },

I've unsuccessfully attempted several variations of the following matrix material variable:
> "Variables"        : {
> 				"KratosMultiphysics.StructuralMechanicsApplication.SHELL_ORTHOTROPIC_LAYERS" : [[0.5,0.0,7850,7.5E+6,2E+6,0.25,1.25E+6,0.625E+6,0.625E+6],[0.5,90.0,7850,7.5E+6,2E+6,0.25,1.25E+6,0.625E+6,0.625E+6]]
>             },

Cheers

**Comment by RiccardoRossi** [comment]
mmm,

i think it is currently not implemented. 

the file in which the reading is done is:

[LINK](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/read_materials_process.py#L119)

i think you should add the case of a matrix (and of a vector) around this line

**Comment by RiccardoRossi** [comment]
I also guess that it would be useful to implement the methods

GetMatrix
GetVector
GetArray3

within the Kratos Parameters interpreting an object as a matrix, vector or array...

**Comment by philbucher** [comment]
@RiccardoRossi those methods exist already in the properties:
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python/add_properties_to_python.cpp#L109

So I think its more a question of how the format of the matrix should be

**Comment by philbucher** [comment]
I could for example also not figure out how to initialize a Matrix in python with values, which I think is the same as what is needed here.

**Comment by loumalouomega** [comment]
I did the implementation some time ago

**Comment by loumalouomega** [comment]
https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/read_materials_process.py

Here I added a loop some time ago.

**Comment by philbucher** [comment]
@RiccardoRossi thanks for helping out.
I tried the methods implemented by you, but they fail in the `read_materials_process.py` 
The problem is that in the test created by you the object is of type `Kratos::Parameters`, whereas in the `read_materials_process.py`the type is `dict`, see [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/read_materials_process.py#L44)
Hence it fails because it interprets `[[1,2],[3,4],[5,6]]` as a `list` that does not have the methods you implemented
Shouldn't the object returned by the json-reader be of type `Kratos::Parameters`?

**Comment by RiccardoRossi** [comment]
@jcotela we did some modifications some time ago to the read_material_parameters.py

do you recall where they could be?

**Comment by philbucher** [comment]
I just realized that the file is read by the json module and not by Parameters.
Changing this to read with Parameters results in a segfault when I try to access it. (I can print it, but accessing one of its attributes, e.g. `properties_id` or `Materials` causes the segfault). I don't really understand what is going on.

**Comment by philbucher** [comment]
@loumalouomega  I understood now what you meant, your link pointed to the master and not to your branch.
Either way, it works in this branch, so I approve your pull request #651 
@RiccardoRossi I will implement the missing methods in the next days, thanks for your help
