### ISSUE TITLE
[CoSim] setting the "interface size" in convergence accelerators

### ISSUE THREAD

**Issue by shahrokh-shayegan** [KratosMultiphysics/Kratos#7312]
In the current implementation of the convergence accelerators (in the CoSimulationApplication) the size of the interface (number of dofs on the interface) is known from the interface fields only when UpdateSolution() is called. In some cases UpdateSolution() is not called for a while because the residuals are below the specified tolerance. in my opinion this is a bit of pain for the initialization, especially in the case of Quasi newton methods, and forces one to constantly check whether e.g. the required matrices and vectors are still None or they have been initialized. 
Wouldn't it be better to set the interface size somehow right at the beginning. And the second question is where is it better to do that (e.g. in the Initialize() , ...)?

**Comment by philbucher** [comment]
thx for pointing it out!

I know abt this, the problem it is not done so far is because the meshes might not be read when `Initialize` is called hence the size is not known

I am working on this but it is not ready (as so many things :/ )

**Comment by philbucher** [comment]
Reminder for myself: with #8398 the meshes will be read BEFORE the ConvAcc are even constructed, then this can be easily done.
Also some more cleanup can be done related to the MPI things IIRC

**Comment by philbucher** [comment]
@shahrokh-shayegan with #8398 being merged now you could do what you propose easily :)

**Comment by rubenzorrilla** [comment]
Closing as it seems to be solved in #8398.
