### ISSUE TITLE
Drop ComputingModelPart for Contact Simulations

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7318]
I just had to debug another problem with the ComputingModelPart and remembered that we cannot fully remove it yet from Structural as Contact still uses it

are there any plans of removing it / what is the timeline @loumalouomega ?
also adding @RiccardoRossi and @AlejandroCornejo

**Comment by loumalouomega** [comment]
I thought I already remove it?

**Comment by loumalouomega** [comment]
> I thought I already remove it?

https://github.com/KratosMultiphysics/Kratos/pull/6330

**Comment by philbucher** [comment]
So we can completely remove it?
I thought you still needed it for internal things due to aux ModelParts

**Comment by loumalouomega** [comment]
I need to check that

**Comment by loumalouomega** [comment]
It is OK

**Comment by philbucher** [comment]
Cool then I will make a PR with removing it for good
