### ISSUE TITLE
BinBasedFastPointLocator problems and improvements

### ISSUE THREAD

**Issue by adityaghantasala** [KratosMultiphysics/Kratos#7337]
**Description**
I have two overlapping (in continuous sense)  circles left picture below. When discritized  independently they result in two different set of lines and nodes, right picture below (bad discritization). Now, I am using the `BinBasedFastPointLocator` to locate the blue nodes on the discritization (lines) of black nodes. Since the discritizations are different one cannot expect that blue nodes can lie on the black lines (Line2D2). Some of the nodes will lie a bit above or below the black lines. Lower right case in the picture below. This will result in no location for a  majority of the blue nodes. A similar situation happens in 3D with Triagle3D3 geometry. This is mainly caused by the the `IsInside`   function of the geometries used by the `BinBasedFastPointLocator` . This `IsInside` function in `Line2D2` and `Triangle3D3` does not allow projection of the points on the geometry. See below 

https://github.com/KratosMultiphysics/Kratos/blob/5ae12926c9b4c75d497c88367380841cd5e0bb7d/kratos/geometries/line_2d_2.h#L918

and (in 3D)

https://github.com/KratosMultiphysics/Kratos/blob/5ae12926c9b4c75d497c88367380841cd5e0bb7d/kratos/geometries/triangle_3d_3.h#L901
**Proposal**
Given that I am not the only person who has and will have such a situation, this interface can be extended to include a flag which can specify if a projection is allowed or not. 

FYI : MappingApplication uses a work around to this problem 
https://github.com/KratosMultiphysics/Kratos/blob/5ae12926c9b4c75d497c88367380841cd5e0bb7d/applications/MappingApplication/custom_utilities/projection_utilities.cpp#L65

**Additional info**
![search_github](https://user-images.githubusercontent.com/2531316/89340688-6a044e80-d6a0-11ea-9202-3266ec0c42fd.png)

**Comment by RiccardoRossi** [comment]
@loumaloumega i think this was doscussed at lenght, at least comcerning the
geoemtry api.

could you tell smthg?

about the point locator we will easily arrive to some sort of agreement.

**Comment by loumalouomega** [comment]
There are projection utilities, do not change behaviour in the IsInside or you will break a lot of code. About the projection utilities, ping @philbucher

**Comment by loumalouomega** [comment]
I am on holidays the next ten days, my contributions will be very limited, sorry

**Comment by adityaghantasala** [comment]
ping @RiccardoRossi  @loumalouomega  @KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
OK, after thinking, we can add a flag to avoid projection (we added projection in some point, but I don't remember why)

**Comment by RiccardoRossi** [comment]
i will be able to review starting in the day 24 of august

**Comment by RiccardoRossi** [comment]
to be honest, rereading the discussion, i wonder if we should not have a
different projection utility for this. (i am not sure, just considering
this as possible alteraative)
One option could refactor some code as static functions and just reuse it
in the existing projection or in the specialized one.

specifically for the binbased projection i am pretty convinced we should
not modify it as you suggest, as finding a point which is now to belong to
a given domain is a much more robust operation than finding the closest
point projection, so even if we implement this as a option it should follow
a completely different code path from the current one. (note that if you
just add a tolerance, the result will be order dependent, which is
particularly problematic in parallel)

bests
Riccardo

**Comment by pooyan-dadvand** [comment]
I think the use case of @adityaghantasala is a valid use case. I would also agree that changing the current behavior of FindPointOnMesh would affect many applications. What about having a new `FindNearestPointOnMesh` method for this?

**Comment by rubenzorrilla** [comment]
I'd like to add that some days ago I realized that `FindPointOnMesh` export to Python is not working properly as it relies on a mutable reference to the found element (aside of the fact that it requires creating an empty pointer to the element in Python :scream:).

My idea would be to create an auxiliary method that returns a tuple with the "is_found" bool as well as the pointer to the corresponding element.

**Comment by ddiezrod** [comment]
@adityaghantasala Is this still active or should we close this for the moment?

**Comment by ddiezrod** [comment]
We'll close this for the moment, please reopen if necessary
