### ISSUE TITLE
[PFEM] How can I Start With PFEM and Kratos

### ISSUE THREAD

**Issue by Mariveros** [KratosMultiphysics/Kratos#7340]
Hello,

I'm Marcelo, and I'm doing my research (thesis) about Tailings and run-out distance. So I'm here because I guess that PFEM is a good way to deal with this problem.

Then if you can give me some advice about how to start with PFEM modulus in Kratos, related to modifying Input Data, material properties, and so on.

I reviewed some pdfs (GiD guides, some pages on Wiki here, run the examples and others...) but I think I need to read something more specific to know how to work with Kratos & PFEM.

**A brief resume, I want to Model Tailings, maybe Bingham plastic model for that part of the problem and add some soils or solid material (sands or embankment materials) that had to interact (a dam breach), and measure the run-out distance.**

Thank you, and if you need more information or a better explanation of my request please let me know.

Marcelo R.

**Comment by RiccardoRossi** [comment]
dear Marcelo,

i am cc-ing dr Franci and Dr Celigueta who are the experts in the sector.

however do consider thqt ot os holidays time, so i am not sure of when they
will be able to reply

bests

Riccardo

**Comment by philbucher** [comment]
@AFranci @maceligueta

**Comment by Mariveros** [comment]
thanks for your reply, I'll be waiting and reviewing by myself.

**Comment by AFranci** [comment]
Dear Marcelo,

Apologize me for the late reply but the last week I was on holiday.

Please, send me an email to falessandro@cimne.upc.edu if you are still interested on the topic.

Thank you and kind regards,

Alessandro Franci

**Comment by Mariveros** [comment]
Alessandro,

thank you I'll contact you.

**Comment by rubenzorrilla** [comment]
Closing as it seems to be solved. @Mariveros feel free to reopen it if required.
