### ISSUE TITLE
Area calculation in linear Quadrilaterals seems odd

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7358]
**Description**
When flipping the orientation of a quad in the input (i.e. changing nodes 1 and 3 according to the [node ordering convention](https://github.com/KratosMultiphysics/Kratos/wiki/Mesh-node-ordering#quadrilateral)) the Area becomes negative, even though it should still be positive IMO

**Scope**
- KratosCore

**Expected behavior**
Area should not be affected by flipping the orientation

**Environment**
- Branch: master

**Additional info**
This is especially annoying since the base element checks this for for 2D Elements :/

Is this really a bug or am I missing sth?
@KratosMultiphysics/technical-committee @loumalouomega

**Comment by loumalouomega** [comment]
I don't understand, if you switch the node 1 and 3 you are literally inverting the element. Don't think in an isolated quad, think in a whole mesh, if the nodes 1-3 of a quad are switched, the mesh will be crashed

**Comment by RiccardoRossi** [comment]
+1 for vicente s comment

**Comment by philbucher** [comment]
I think I have to explain a bit more.
I have the following mesh (as simple as it can get). The Node numbers are shown. Lets take a look at the element in the left bottom corner. According to the Kratos convention the connectivity numbering should be _1 - 31 - 33 - 5_. 
By default the orientation is as shown in picture 2, however this results in a numbering _1 - 5 - 33 - 31_
Switching the orientation aka flipping the normals will result in the correct ordering (see pic 3)

My point (and the issue) is that both meshes are valid input, i.e. the mesh is exactly the same in both cases

![image](https://user-images.githubusercontent.com/25484702/90342773-146a6300-e00b-11ea-9bf2-bb77cb088462.png)
![image](https://user-images.githubusercontent.com/25484702/90342775-192f1700-e00b-11ea-9079-859af21f0d15.png)
![image](https://user-images.githubusercontent.com/25484702/90342777-1d5b3480-e00b-11ea-9157-b3b10c2e3534.png)

**Comment by loumalouomega** [comment]
> I think I have to explain a bit more.
> I have the following mesh (as simple as it can get). The Node numbers are shown. Lets take a look at the element in the left bottom corner. According to the Kratos convention the connectivity numbering should be _1 - 31 - 33 - 5_.
> By default the orientation is as shown in picture 2, however this results in a numbering _1 - 5 - 33 - 31_
> Switching the orientation aka flipping the normals will result in the correct ordering (see pic 3)
> 
> My point (and the issue) is that both meshes are valid input, i.e. the mesh is exactly the same in both cases
> 
> ![image](https://user-images.githubusercontent.com/25484702/90342773-146a6300-e00b-11ea-9bf2-bb77cb088462.png) | ![image](https://user-images.githubusercontent.com/25484702/90342775-192f1700-e00b-11ea-9079-859af21f0d15.png) | ![image](https://user-images.githubusercontent.com/25484702/90342777-1d5b3480-e00b-11ea-9157-b3b10c2e3534.png) |

Can you convert this minimal example in a python test we can debug?

**Comment by RiccardoRossi** [comment]
mmm

i have the feeling this is a difference in the local ordering employed by
different programs.

some programs order it as

2 3
0 1

others as

3 2
0 1

what is the convention?

how would u do the flipping in this context?

**Comment by loumalouomega** [comment]
> mmm i have the feeling this is a difference in the local ordering employed by different programs. some programs order it as 2 3 0 1 others as 3 2 0 1 what is the convention? how would u do the flipping in this context?
https://github.com/KratosMultiphysics/Kratos/wiki/Mesh-node-ordering#quadrilateral

**Comment by philbucher** [comment]
The ordering of the nodes is the same:

Kratos | Salome
---|---
![image](https://user-images.githubusercontent.com/25484702/90425177-a0d65d80-e0bf-11ea-9ebd-a15a192541b5.png) | ![image](https://user-images.githubusercontent.com/25484702/90425189-a633a800-e0bf-11ea-8c94-a87dbcca530c.png)

The issue comes when flipping the normal, i.e. from which side one looks at it (front vs back so to say, as depicted in the pics above with the arrows)
If one looks from the from the front then the ordering is correct, looking from the back it is different (still same mesh, just the normal pointing in the opposite direction)

Does this clarify what I mean?

**Comment by loumalouomega** [comment]
> The ordering of the nodes is the same:
> Kratos 	[Salome](http://trac.lecad.si/vaje/chrome/site/doc8.3.0/gui/SMESH/connectivity_page.html)
> ![image](https://user-images.githubusercontent.com/25484702/90425177-a0d65d80-e0bf-11ea-9ebd-a15a192541b5.png) 	![image](https://user-images.githubusercontent.com/25484702/90425189-a633a800-e0bf-11ea-8c94-a87dbcca530c.png)
> 
> The issue comes when flipping the normal, i.e. from which side one looks at it (front vs back so to say, as depicted in the pics above with the arrows)
> If one looks from the from the front then the ordering is correct, looking from the back it is different (still same mesh, just the normal pointing in the opposite direction)
> 
> Does this clarify what I mean?

Can you please provide a mesh example giving issues?

**Comment by philbucher** [comment]
lets speak abt this, I feel like verbal explanations will be more fruitful :)

**Comment by philbucher** [comment]
for the record, I figured together with @sunethwarna that in fluids the `TetrahedralMeshOrientationCheck` is used to make sure things are correct no matter what the preprocessor does :)

**Comment by loumalouomega** [comment]
(but does it work with hexa and quad?)

**Comment by armingeiser** [comment]
My 2 cents: 
Just changing the orientation of the quad (nodes `1,2,3,4` vs `1,4,3,2` as in @philbucher's  example above)  will of course affect in which direction the normal is pointing, but the area should definitely **not** be negative. 

Preprocessors should respect the ordering of nodes in Kratos. The need of making normals coherent is a fix for a deficiency of the input/preprocessor. Also the convention of normals of solid surfaces pointing outwards is fine, but what is outside if we talk about a surface mesh only? In that case the decision of which direction of the surface is the positive normal direction is a user decision IMO and i am not sure how that could be fixed by an automatic process.

**Comment by loumalouomega** [comment]
> My 2 cents:
> Just changing the orientation of the quad (nodes `1,2,3,4` vs `1,4,3,2` as in @philbucher's example above) will of course affect in which direction the normal is pointing, but the area should definitely **not** be negative.
> 
> Preprocessors should respect the ordering of nodes in Kratos. The need of making normals coherent is a fix for a deficiency of the input/preprocessor. Also the convention of normals of solid surfaces pointing outwards is fine, but what is outside if we talk about a surface mesh only? In that case the decision of which direction of the surface is the positive normal direction is a user decision IMO and i am not sure how that could be fixed by an automatic process.

What do you propose?, to change the way the area is computed?, this is the FEM standard. We may enforce the positivity of the area multiplying by a "normal factor" that would be 1 if the normal is the expected and -1 if the opposite, but this should not be like that. If you read the documentation of any FEM it is done ensuring the normal in a certain direction, read for example Code_Aster documentation:

https://www.code-aster.org/V2/doc/v13/en/man_u/u3/u3.01.00.pdf

![imagen](https://user-images.githubusercontent.com/19991680/93879311-c74d7100-fcdb-11ea-955f-221a4ee7d92b.png)

![imagen](https://user-images.githubusercontent.com/19991680/93879346-d7655080-fcdb-11ea-9bc3-77ead72147d1.png)

**Comment by philbucher** [comment]
I still could not communicate what I actually mean and why I think that we are currently not doing it correctly IMO

I will come back to explaining more in detail when I have time

**Comment by armingeiser** [comment]
My understanding is the following:
If a quad (left) undergoes a rigid body rotation, it should not change its area. Of course the normal points in the opposite direction.

![image](https://user-images.githubusercontent.com/25903585/93893603-1bf9e780-fcee-11ea-8882-211c0094643d.png)

Looking at the node numbers we have left `1,2,3,4` and right `1,4,3,2` - which is exactly the example of @Philip above and apparently in Kratos a negative area is calculated for the right case.

**Comment by philbucher** [comment]
thanks @armingeiser this is pretty much what I failed to explain :D

**Comment by loumalouomega** [comment]
If you work in 2D what you posted @armingeiser is an inversion of element. If you want to change that for the 3D I will understand

**Comment by armingeiser** [comment]
Now i see where we are diverging: I was talking about 3D (having shell elements in mind).

@philbucher's in your example you are using Quad2D4N so i guess you guys where talking about 2D :upside_down_face:

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee fully delegates this issue to the @KratosMultiphysics/implementation-committee

**Comment by AlejandroCornejo** [comment]
Dear all, I agree with @loumalouomega in terms that if you change the ordering this has an effect on the normal. But on the normal! I know that Vicente has implemented some checks that ensures the normals to point outwards the body (for contact stuff). My question is, maybe we have to differentiate the area (strinctly positivew value) from the normal (vectorial with sign)?

**Comment by pooyan-dadvand** [comment]
I understand that we are talking about 2D and not 3D. In 2D changing the normal would give a negative area which is a widely used convention. (Not my favorite convention) And an easy way to check if the element is inverted. For the strictly positive area, I used to put the abs after calling the Area method.

**Comment by loumalouomega** [comment]
I would avoid the abs, that hides some potential errors

**Comment by ddiezrod** [comment]
from @KratosMultiphysics/implementation-committee 
We understand that the case is different in 2D and 3D. In 2D, there is only acceptable order to number the nodes. so if this is not correct, we think it's fine that the area is negative, as this could be an indicator that the element is inverted. In the 3D case however, nodes could be ordered in different ways so Area should always be positive. Is this ok for everybody?

**Comment by philbucher** [comment]
closing as no longer relevant for me (using a workaround now) and it would probably be a delicate change
