### ISSUE TITLE
Interfaces of Element, Condition and Scheme updated

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7381]
Dear @KratosMultiphysics/all

After many issues in the past (e.g. with race conditions) the @KratosMultiphysics/technical-committee decided to clean up and improve the interfaces of `Element`, `Condition` and `Scheme`. See #4938, #6643 and #5290.

The changes are done **FULLY BACKWARD COMPATIBLE** (please check the PRs for technical details), hence he updating can be done in multiple steps!!!
The Core and many applications have already been updated!

The main changes are adding `const` to the `ProcessInfo` that is passed to the functions. This is to avoid race conditions.

The following changes were done:
- `Element` & `Condition`:
    - All instances of `ProcessInfo` are being passed as `const`
    - The following functions are `const` functions now:
        - `GetValuesVector`
        - `GetFirstDerivativesVector`
        - `GetSecondDerivativesVector`
        - `Check`
    - `Initialize` gets an instance of `const ProcessInfo&` now
    - `CalculateLocalSystem` with `std::vector` is removed as unused
    - `GetValueOnIntegrationPoints` is deprecated in favor of `CalculateOnIntegrationPoints`. The functions have the same signature, hence search-replace is sufficient

- `Scheme`:
    - All instances of `ProcessInfo` are being passed as `const`
    - Element and Condition are no longer passed as `Pointer` but as reference
    - The function names starting with `Condition_` have the `Condition_` removed i.e. the names for Element and Condition are the same now

The following procedure is suggested for updating the code:
1. Update the c++ tests (if existing) to use the new interfaces, see e.g. #7366
2. Update the interfaces see e.g. #7371
In case some results change it is very likely that a race condition. If you cannot find the issue please let us know

Please check & update your applications. The timeline is (to be confirmed by @KratosMultiphysics/technical-committee):
- activating the deprecation warnings: 2 months from now, end of October
- removing the deprecated functions: 5 months from now, end of January

Please don't hesitate to ask questions if something is unclear!

The following applications have been updated already (if it was necessary)

- CableNetApplication
- ChimeraApplication
- CompressiblePotentialFlowApplication
- ConstitutiveModelsApplication
- ContactStructuralMechanicsApplication
- CoSimulationApplication
- CSharpWrapperApplication
- EigenSolversApplication
- ExaquteSandboxApplication
- ExternalSolversApplication
- FluidDynamicsApplication (partly)
- FreeSurfaceApplication
- FSIApplication
- HDF5Application
- LinearSolversApplication
- MappingApplication
- MeshingApplication
- MeshMovingApplication
- MetisApplication
- MultilevelMonteCarloApplication
- RomApplication
- ShapeOptimizationApplication
- StatisticsApplication
- StructuralMechanicsApplication (mostly)
- TrilinosApplication
- UmatApplication

**Comment by philbucher** [comment]
> Please check & update your applications. The timeline is (to be confirmed by @KratosMultiphysics/technical-committee):
> 
>     * activating the deprecation warnings: 2 months from now, end of October
> 
>     * removing the deprecated functions: 5 months from now, end of January

@KratosMultiphysics/technical-committee confirms this timeline

**Comment by philbucher** [comment]
one month left until the deprecation warnings for the old interfaces will be activated
ping @KratosMultiphysics/mpm @KratosMultiphysics/dem @KratosMultiphysics/fluid-dynamics

**Comment by ddiezrod** [comment]
FYI @KratosMultiphysics/altair

**Comment by ddiezrod** [comment]
@philbucher The substitution of  GetValueOnIntegrationPoints for CalculateOnIntegrationPoints has to be made also in conditions right? Not only in the elements..

**Comment by philbucher** [comment]
@ddiezrod  yes, I forgot to write it, is corrected now

**Comment by philbucher** [comment]
The PR for activating the deprecation warnings is created => #7685 
It will be merged this Friday

**Comment by philbucher** [comment]
ping @KratosMultiphysics/all 

3 weeks left until the old interfaces will be removed

**Comment by philbucher** [comment]
@KratosMultiphysics/all the PR with removing the old interfaces can be found here: #8090 

Please check if your applications compile with this branch.

As stated above, this PR is to be merged end of this month

**Comment by philbucher** [comment]
@KratosMultiphysics/all the old interfaces will be removed in 8 days from now, on Friday 29.
As mentioned above the PR that removes them is #8090 
Please check if your apps are working with this branch

all the apps that are in the CI are already updated
