### ISSUE TITLE
Problem with types of design variables when calculating sensitivities

### ISSUE THREAD

**Issue by MFusseder** [KratosMultiphysics/Kratos#739]
Hey all!

I am currently working on adjoint sensitivity analysis especially for structural problems. 
In the actual concept for computing sensitivities the element base class (and also the condition base class) provides two types of design variables (double and array_1d):

``  virtual void CalculateSensitivityMatrix(const Variable<double>& rDesignVariable, Matrix& rOutput,
const ProcessInfo& rCurrentProcessInfo)``
and
`` virtual void CalculateSensitivityMatrix(const Variable<array_1d<double,3> >& rDesignVariable, Matrix& rOutput,
const ProcessInfo& rCurrentProcessInfo)  ``.

Until now this was sufficient also for my work. But now I detected a problem:

I saw for example in the CrBeamElement in the Structural Mechanics Application changes at the used variables which are problematic for computing sensitivities. So the inertias are now coupled in a Vector variable and are no longer separated in three individual double variables:
`Vector inertia = this->GetProperties()[LOCAL_INERTIA_VECTOR];`
  `const double J = inertia[0];`
 ` const double Iy = inertia[1];`
  `const double Iz = inertia[2];`

Sure this reduces the number of variables but this summing up of variables makes live in sensitivity analysis much harder. This change makes it in the current implementation impossible to use the inertias or e.g. only Iy as design variable(s) in sensitivity analysis. 

But for my work it would be essential to use all (or most) variables in an specific element as design variables. 

To resolve this one solution could be, to look that potential interesting variables for sensitivity analysis are used in the specific elements as double or array_1d variables (e.g. use the inertias again as three individual double variables and not summing them up in a Vector variable).
Sure one could also provide more additional CalculateSensitivityMatrix(...)-functions with other types of variables in the element and condition base classes. But in my eyes double and array_1d are enough if individual variables are not collected. 

What is your opinion to this problem?

Thanks in advance!!

**Comment by armingeiser** [comment]
Just my two cents:

I'm also opting for not combining variables like it is done e.g. for the 

```c++
[LOCAL_INERTIA_VECTOR]
```
doing so would require to have a function like this in the element/condition base class:

```c++
virtual void CalculateSensitivityMatrix(const Variable<Vector>& rDesignVariable, 
                                              const unsigned_int$ rPosition, 
                                              Matrix& rOutput, 
                                              const ProcessInfo& rCurrentProcessInfo)
```
in order to be consistent with the rest of the implementation.
In my opinion the `const unsigned_int$ rPosition` is not very nice.

@AndreasWinterstein, do you know if there is a discussion going on about reducing the number of variables?

**Comment by msandre** [comment]
Hi Martin,

To me it makes sense to have a standard format for how and where different variables are stored. Also I agree with having a variable for each component. But we should see what the @KratosMultiphysics/structural-mechanics team says. Does it work for now if you pass one of the variables IX, IY, IZ to the CalculateSensitivityMatrix()? 

A separate issue I see with the variable is that it is stored in the Properties which is shared among elements. If you try to do finite differencing directly on the variable it will not work in the openmp loops.

**Comment by armingeiser** [comment]
Thanks Mike for your comment, 

@MFusseder  I guess when doing finite differencing inside an element we should make a local copy of the property, or geometry (whatever we are disturbing) inside the CalculateSensitivityMatrix().

**Comment by MFusseder** [comment]
Thank you Mike for your help!

Currently it doesn’t work with Ix, Iy, Iz because I inherit now from the actual CrBeamElement which only knows the inertia vector. But it is possible to pass the variables for them to CalculateSensitivityMatrix(). As a first solution I will add something like that in order to use them again as design variables:
If(rDesignVariable == IZ) --> perform finite differences with inertia[2]

You are right about the Properties. I will try to fix this in the way Armin suggested.

**Comment by loumalouomega** [comment]
I think that you can use the reference and work as usual, example :

~~~
double & inertiax = InertiaVector[0];
~~~

I can not be more specific, I am in the train. Chu Chu Chu (I don't know
how to write the train noise in English)

**Comment by pooyan-dadvand** [comment]
I'm not sure if I understood correctly the problem, do you need to work on just a component like 'INERTIA_Z' instead of the entire variable? Then you would need a set of methods with variable components as input. However I'm not sure if this is a perfect solution.

**Comment by MFusseder** [comment]
To make my problem more clear, I show you first what I am really doing in the CalculateSensitivityMatrix() function:
```c++
void CrBeamElement3D2NForSA::CalculateSensitivityMatrix(const Variable<double>& rDesignVariable, 
	Matrix& rOutput, const ProcessInfo& rCurrentProcessInfo)
{
    // Doing something

     if (this->GetProperties().Has(rDesignVariable) ) 
     {
	// get property vector of element
	Properties::Pointer pElemProp = this->pGetProperties();

        // Doing something

	// disturb the design variable
	const double current_property_value = this->GetProperties()[rDesignVariable];
        pElemProp->SetValue(rDesignVariable, (current_property_value + delta));

        // Performing finite differences

        // undisturb design variable
	pElemProp->SetValue(rDesignVariable, (current_property_value));
      }
}
```
As you see I am directly work with the design variables in order to disturb and undisturb when performing finite differences. Doing so makes it possible to compute the sensitivity matrix in a generic way for all scalar (double) variables.

@pooyan-dadvand the inertia vector is not a 3D variable with components. Instead it is defined as vector variable: 
```c++
KRATOS_DEFINE_VARIABLE(Vector, LOCAL_INERTIA_VECTOR)
```
In order to perform sensitivity analysis for a single entry of the inertia vector an additional function like armin showed it in his first comment would be necessary.

**Comment by loumalouomega** [comment]
I am still thinking that it is possible to work in a similar way using the reference of the components of the vector instead of each variable separately

**Comment by jcotela** [comment]
@loumalouomega if I understand the problem correctly, the issue with a reference is that you need to know what the number in your `double&` means, since you want to do a given operation when you get an inertia or something else entirely if you get a different quantity.

**Comment by MFusseder** [comment]
I'm not sure if I understood you correctly. So you would continue to pass e.g. IY as rDesignVariable to the  CalculateSensitivityMatrix() and prepare there if-clauses like:
```c++
if(rDesignVariable==IT) {double & design_variable = InertiaVector[0];}
if(rDesignVariable==IY) {double & design_variable = InertiaVector[1];}
if(rDesignVariable==IZ) {double & design_variable = InertiaVector[2];}
```
and disturb than design_variable, perform finite differences and undisturb finally design_variable? Sure this can be possible but disturbs a bit the generic approach.

**Comment by loumalouomega** [comment]
Well, may disturb the implementation, but modify the LOCAL_INERTIA_VECTOR will disturb the implementation too.

The code would be:

~~~
double& design_variable = rDesignVariable==IX ? InertiaVector[0] : rDesignVariable==IY ? InertiaVector[1] : InertiaVector[2];
~~~

You can not use anything outside the loop is declared

**Comment by armingeiser** [comment]
I agree that it could be done using an if/else clause to get the `double&` as you suggested @loumalouomega.

But this will only work as long the Variables `IT,IY,IZ` exist, and as far as I see the are not used anywhere. At the moment they exist, but they do not store any information. So we can use them to identify the desired entry of the `LOCAL_INERTIA_VECTOR` but i don't see why there should be two variables for basically the same thing.

What I'm trying to say is, that the `LOCAL_INERTIA_VECTOR`  seems to be treated differently than other variables like e.g. `CROSS_AREA`, ` AREA_EFFECTIVE_Y` or ` AREA_EFFECTIVE_Z`.

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi is there any special reason for defining the `LOCAL_INERTIA`  as vector and not an array_1d with components?

**Comment by RiccardoRossi** [comment]
It can have 6 components in 3d...

Also consider that it can be
I1 I2 I12

SO THE THIRD ONE IS NOT really a component

**Comment by RiccardoRossi** [comment]
One IMPORTANT coment:
An element Can not change the value of its properties!!!

It is shared with other elements, so by doing so you are destroying the parallelism

**Comment by msandre** [comment]
For the parallelism, you could create a new properties in each thread and use the element's GetProperties() to save the shared pointer, SetProperties() to replace with the thread safe properties, do finite differences and then put back the initial properties. 

For the variables, I think the if statement is unavoidable either way. We have to check the variable to know if it is an element property, nodal coordinate, etc.  I personally like the separate variables since the vector index is less clear what it means. Either way, we should pick a standard definition and stick with it (also in the wiki).

**Comment by RiccardoRossi** [comment]
Actually my suggestion is simpler than that. 
I would use and fill a custom structure "data" to be filled from the properties database.

The element should then always read data from that custom structure (fill it and destroy it as needed, do not store it as an el,mental var)

If you need to perturb, you can do,ply perturb the fathered data without affecting the global ones

**Comment by armingeiser** [comment]
First of all, thanks for all the comments!

We are aware of the parallelism and that we need to be careful when perturbing data at element level.
After all this will not only affect us when dealing with properties, but also e.g. with nodal coordinates.

@RiccardoRossi I'm not sure if I got your idea of this custom structure "data" completely, but if we do not store this "data" as an elemental variable, would'nt that require to gather the data from e.g. the property inside each member function again?

Also I think this would require changes in most or nearly all elements?
The way @msandre  suggested, would not require any changes at the element/condition itself.

**Comment by RiccardoRossi** [comment]
@armingeiser @msandre yes, i see your point. 

It is a little hacky but it can be done, as long as on exiting from the sensitivity calculator the elements are assigned back the original property. 

@msandre 's suggestion also fixes the other problem no? i mean, it allows using Inertia as a vector/matrix?

I am telling since i don't thik we can/should avoid having vector properties being passed, also because passing one single vector requires many less database accesses that passing 3 (or 6 in 3D) scalar variables

**Comment by msandre** [comment]
Ok, that's a good point for using the vector type instead of separate scalars. Potentially, you can also use a pointer swap on the element's nodes if you need to do finite differences on those too. That way I think you only need to allocate memory once for each thread, but you would need to copy the data each time. Also you would have to modify the element so we can't have it as a const.

**Comment by RiccardoRossi** [comment]
@msandre actually, you could generate per thread the things you need and swap it when needed.

I mean the following

for elem in elements
    thread_id = ...
    thread_prop_pointer = ...
    elem.SetProperties( thread_prop_pointer )
    ... do what you need
    elem.SetProperties( original_property_pointer )

**Comment by armingeiser** [comment]
I like the idea of allocating the memory per thread.
Only downside in my opinion is, that like this, you need to know if the element you are working with uses finite differences already in the loop that calls the CalculateSensitivityMatrix().
This happens in the response function.

At the moment we are doing the swap of property pointer inside the CalculateSensitivityMatrix(), like this, the response function can use any elements regardless if they calculate the sensitivity matrix analytically or by finite differencing.
But of course this requires to create and destroy the "thread_prop" in each call of the element function.

About the initial problem:
It is possible to use the local inertia vector as it is, at the moment we are using the "IT, IY, IZ" variables to identify which entry we need from the "LOCAL_INERTIA_VECTOR"

Below there are some code snippets to show you how we do it right now.
We use a function similar to "UpdateNodalSensitivities" from the adjoint fluid application and call the elemental CalculateSensitivityMatrix:

```c++
template <typename TDataType>
void UpdateElementSensitivities(Variable<TDataType> const& rSensitivityVariable, Variable<TDataType> const& rOutputVariable)  
{
    for (ModelPart::ElementIterator it = r_model_part.ElementsBegin(); it != r_model_part.ElementsEnd(); ++it)
    {
        if (it->GetValue(UPDATE_SENSITIVITIES) == true)
        {
            it->CalculateSensitivityMatrix(
                rSensitivityVariable, sensitivity_matrix, r_process_info);
            
            // Do the rest of the sensitivity calculation
        }
    }
    r_model_part.GetCommunicator().AssembleCurrentData(rSensitivityVariable);
}
```

```c++
void CrBeamAdjointElement3D2N::CalculateSensitivityMatrix(const Variable<double>& rDesignVariable, Matrix& rOutput, 
										const ProcessInfo& rCurrentProcessInfo)
{
        if (rDesignVariable == IT || rDesignVariable == IY || rDesignVariable == IZ)
        {
             // Do finite differencing basically the same way as below but disturbing the just one entry of the variable vector
        }
        // for all other properties it works in a generic way
	else if ( this->GetProperties().Has(rDesignVariable) ) 
	{
		// Compute RHS before disturbing
		this->CalculateRightHandSide(RHS_undist, testProcessInfo); 

		// Save properties and its pointer
		Properties& r_global_property = this->GetProperties(); 
		Properties::Pointer p_global_properties = this->pGetProperties(); 

		// Create new property and assign it to the element
		Properties::Pointer p_local_property(new Properties(r_global_property));
		this->SetProperties(p_local_property);

		//Disturb and compute finite difference ...

		// Give element original properties back
		this->SetProperties(p_global_properties);
	}
} 
```

**Comment by RiccardoRossi** [comment]
i am closing since this is long inactive. reopen as needed
