### ISSUE TITLE
Tests for gauss point quantities

### ISSUE THREAD

**Issue by peterjwilson** [KratosMultiphysics/Kratos#740]
Hi All,
I'm looking to set up some tests to cover stress recovery functionality in the structural mechanics shell elements. These are calculated on element gauss points. So far it looks like `from_json_check_result_process` only handles nodal quantities. 

Does anyone have experience setting up tests for gauss point quantities?

Cheers

**Comment by jcotela** [comment]
Hi @peterjwilson, is your gauss point quantity calculated 'on the spot' or do you store it? (if so, where?)
In any case, I would recommend writing a minimal example that constructs a small model part (1 to 10 elements?), initializes it to whatever state you want to use for your tests and just calls the corresponding gauss point function on each element. You don't need to use the 'standard' processes if they don't suit you, they are just there for convenience.

**Comment by peterjwilson** [comment]
Thanks @jcotela, the quantities are calculated with the usual `GetValueOnIntegrationPoints` functions. Your test idea sounds interesting, I was wondering if you had an example setup that I could attempt to work from?

**Comment by jcotela** [comment]
It is not exactly what you need, but an example of what I meant is [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/FluidDynamicsApplication/tests/buoyancy_test.py). My suggestion would be to use this script as 'inspiration' and change the `checkResults` function to call `GetValueOnIntegrationPoints` instead.

**Comment by RiccardoRossi** [comment]
Hi,

I think that what Vicente did about recovering gradients is useful for
this. Could h take a look?

**Comment by philbucher** [comment]
I think we can close this for now
