### ISSUE TITLE
Inconsistent behavior of ublas/trilinos spaces

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#741]
@rubenzorrilla has detected that the function ScaleAndAdd(A,rX,B,rY,rZ) behaves differently for `UblasSpace` and `TrilinosSpace`. The Ublas version is doing
```
Assign(rZ, A, rX); //rZ = A*rX
UnaliasedAdd(rZ, B, rY); //rZ += B*rY
```
which can be seen as `rZ = (A * rX) + (B * rY)`

while the trilinos version does
```
rZ.Update(A, rX, B, rY, 1.0);
```
which is equivalent to `rZ = 1.0*rZ + A*rX + B * rY` (or `rZ += (A * rX) + (B * rY)`). This is different to the ublas version unless `rZ` is a zero vector.

We think we can force the trilinos version to behave as the ublas one if we change it to
```
rZ.Update(A, rX, B, rY, 0.0);
```
but this is likely to break something in the trilinos application.

How should we proceed @RiccardoRossi @pooyan-dadvand ?

**Comment by loumalouomega** [comment]
One question, with `rZ.Update(A, rX, B, rY, 0.0)` is not the same as `rZ = 0.0*rZ + A*rX + B * rY` equal to `A*rX + B * rY`?

**Comment by jcotela** [comment]
@loumalouomega yes, and this is what we want (I've edited the original post so it is a bit clearer)

**Comment by loumalouomega** [comment]
Do I remove my now stupid commentary?

**Comment by jcotela** [comment]
As you prefer, I don't mind. We can delete the entire conversation except the OP if you want.

**Comment by loumalouomega** [comment]
Let's be sneaky

**Comment by pooyan-dadvand** [comment]
hmmm no idea....

**Comment by RiccardoRossi** [comment]
mmm, nasty error :-(

where is the function used in ublas? what about trilinos?

**Comment by jcotela** [comment]
These are the files that I could find (with grep)
```
./kratos/linear_solvers/tfqmr_solver.h
./kratos/linear_solvers/cg_solver.h
./kratos/linear_solvers/bicgstab_solver.h
./kratos/linear_solvers/deflated_cg_solver.h
./kratos/linear_solvers/deflated_gmres_solver.h
./kratos/python/add_strategies_to_python.cpp
./kratos/spaces/dense_space.h
./kratos/spaces/mpi_decomposition_space.h
./applications/ULFapplication/custom_strategies/builder_and_solvers/residualbased_elimination_quasiincompresible_builder_and_solver.h
./applications/StructuralMechanicsApplication/custom_strategies/custom_strategies/residual_based_arc_length_strategy.hpp
./applications/FSIapplication/custom_utilities/mvqn_recursive_convergence_accelerator.hpp
./applications/trilinos_application/custom_python/add_trilinos_space_to_python.cpp
./applications/trilinos_application/trilinos_space.h
./applications/structural_application/custom_strategies/strategies/residualbased_arc_length_strategy.h
```
I think most of them should not be a problem (they are non-mpi). Does the arc_length_strategy have an MPI version?

**Comment by loumalouomega** [comment]
@jcotela Nope

**Comment by philbucher** [comment]
The `ClearData` functions are also not consistent. In the Trilinosversion, some are called `SetToZero`

**Comment by pooyan-dadvand** [comment]
I'm not sure but as long as I remember the `ClearData` deallocates the value vector in CSRMatrix while `SetToZero` not.  But not a reason be inconsistent...

**Comment by philbucher** [comment]
From how I see it the `Clear` functions clear and resize the matrix/vector, whereas `ClearData` clears the matrix/vector ([ublas](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/spaces/ublas_space.h#L521)) or writes zeros ([trilinos](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/trilinos_application/trilinos_space.h#L381)) 
In the Trilinos version some of the functions that internally do the same are called `ClearData`, wheras others are called `SetToZero`

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi and @jcotela are you agree with unifying it?

**Comment by jcotela** [comment]
I agree.

**Comment by rubenzorrilla** [comment]
Me too.

**Comment by jcotela** [comment]
Regarding the issue with `ClearData` and `SetToZero`, the code now does this:

`ublas_space.h`:
- `Clear`: clears the matrix data and resizes it to size 0.
- `ClearData`: clears the matrix data (but does not resize it).
- `SetToZero`: does not exist.

`trilinos_space.h`:
- `Clear`: deallocates matrix (swaps with new pointer to empty matrix).
- `ClearData`: puts zeros in the matrix.
- `SetToZero`: puts zeros in the matrix, too.

What should the "unified" version do?

**Comment by pooyan-dadvand** [comment]
I'm really get surprised! When I did the spaces:
- `Clear` was to resize data and graph of matrix to 0. 
- `ClearData` to resize data to zero but maintain the graph of matrix as it is.
- `SetToZero` wasn't there...

**Comment by RiccardoRossi** [comment]
Is this still Active? I am asking since i believe  the issue was fixed

**Comment by jcotela** [comment]
@RiccardoRossi There is a branch fixing the `ScaleAndAdd` inconsistency, but we haven't done the PR yet. We need to decide what to do with the ClearData issue. I think it would make sense to do as @pooyan-dadvand says was originally planned, but I seem to remember discussing with you (years ago) that there was a problem with doing the ClearData in trilinos as in Ublas (it is quite more complicated to achieve that in Trilinos?). Do you have a suggestion about how to proceed?

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand sorry i just deleted your comment by mistake. i was trying to edit to copy the text...

in my undersranding we should have

- **SetToZero** preserves the structure (for a matrix) and sets the entries to zero. _the fact that for a matrix it preserves the graph is very important_
- **Clear** performs an operation equicalent to a resize(0). in trilinos this implies creating a new object and swapping the pointers (hence all the handling must be done through pointers)

if we reach the agreement that SetToZero is a bad name, and should be replaced by ClearData i have no problems (however i personally think that SetToZero is a good name).

**Comment by pooyan-dadvand** [comment]
But `ClearData` is different and also deallocates the value array (but not the graph) of the matrix. So after `ClearData` the matrix become unusable until you allocate again the nonzero array. 

Of course this is somehow fine tuning the memory and out of concern of many nowadays.

**Comment by RiccardoRossi** [comment]
I just checked in the code, 

**ClearData** is _as of today_ essentially not used anywhere. I think it is a legacy method from the time prior to ublas (there was a time looong ago, when boost was young ... )

my suggestion is to remove the ClearData function, and in the very few places in which it is used, replace it by **Clear**

**Comment by pooyan-dadvand** [comment]
:+1: for removing `ClearData`

**Comment by jcotela** [comment]
OK I'll implement this in the branch and do the corresponding PR.
