### ISSUE TITLE
Problem with using auto for array_1d with GCC

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7414]
**Description**
@sunethwarna found that the following code fails when using GCC:

~~~cpp
array_1d<double, 3> rNormal; // also properly initialized ...
const auto result = rNormal / norm_2(rNormal);
~~~

with Clang the type of `result` is correctly determined as `array_1d<double, 3>`
With GCC however the resulting type is `const boost::numeric::ublas::vector_binary_scalar2<Kratos::array_1d<double, 3>, const double, boost::numeric::ublas::scalar_divides<double, double> >` which gives problems later on

**Scope**
- KratosCore

**To Reproduce**
use `auto`, see above

**Expected behavior**
Gcc should produce the same as clang

**Environment**
Tested on multiple machines with different versions of Clang and Gcc. Always works with Clang and always fails with Gcc
E.g.:
- OS: Linux (different ones)
- Branch: master
- Gcc 5.4, Gcc 9.3, Gcc 10

any idea why this is happening?
@KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
Mm no idea to be honest, I will investigate

**Comment by roigcarlo** [comment]
@philbucher @sunethwarna , which version of boost are you using?

**Comment by philbucher** [comment]
I think 1.73

**Comment by sunethwarna** [comment]
I am using 1.72

**Comment by pooyan-dadvand** [comment]
Seems that you are creating an expression of division instead of the result array. So if the expression is used in another place after the original normal array is gone of scope. It will be a memory error and it will mysteriously crashed. 

As a rule of thumb, you should avoid auto for the expressions unless you are sure about the life time of the terms involved in the expression.

**Comment by pooyan-dadvand** [comment]
Also performance is an issue here. Because if you use result 3 times, you are evaluating the division 3 times.

**Comment by pooyan-dadvand** [comment]
So in any case I would suggest to store the values in a array_1d instead of creating auto expression:

```c++
const array_1d<double,3> result = rNormal / norm_2(rNormal);
```

or directly

```c++
rNormal /= norm_2(rNormal);
```

**Comment by philbucher** [comment]
FYI @armingeiser

**Comment by armingeiser** [comment]
Thanks for the explanation! I solved a similar problem like this:
```cpp
auto new_array = rNormal;
new_array /= norm_2(rNormal);
```

Is there any chance such a not recommended use of auto for expressions is detected by the compiler?

**Comment by philbucher** [comment]
> Is there any chance such a not recommended use of auto for expressions is detected by the compiler?

as far as I understood there is not right @roigcarlo ?

**Comment by roigcarlo** [comment]
Not an expert in the topic, but I would say no. I will try to learn more about it to see if I can find anything on this topic.

**Comment by pooyan-dadvand** [comment]
Shall we close this?
