### ISSUE TITLE
create action to inform developers about stale branches

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7433]
As I am writing this we currently have **551 branches in the repository, and it is constantly growing**
MANY of them are stale and haven't been updated in years

the @KratosMultiphysics/technical-committee discussed how to improve this situation and came up with the following solution:

Create a Github Action (same that runs our CI) that checks on a regular basis (e.g. once a week) the stale branches and sends mails to the developers informing them that they have stale branches.

This way devs would know that they have stale branches and can do the following:
- merge master into the branch
- delete the branch
- pull the branch to a fork and delete it in the main repo

**MAYBE** in the future at some point this could also delete the branches after sending several times the reminder, but this has not been decided. (kinda depends if the number of branches further increases)

@KratosMultiphysics/all

**Comment by loumalouomega** [comment]
I would do the following in that action (if possible):

- Email the creator that the branch will be removed in the next 5 days
- Resending the email prior 48h
- Resending the email prior 24h insisting
- Remove the stale branch

This way people will be aware (said so, I will remove my stale branches)

**Comment by loumalouomega** [comment]
> This way people will be aware (said so, I will remove my stale branches)

I removed 10 :D

**Comment by philbucher** [comment]
FYI pulling branches to forks is super simple, simply do the following steps while in the fork:
1. `git checkout upstream/name-of-branch` => this pulls the branch from `KratosMultiphysics/Kratos` (Kratos needs to be set as upstream repo beforehand)
2. `git branch name-of-branch` => this creates the branch locally
3. (optional) push to fork `git push --set-upstream origin name-of-branch`

**Comment by Vahid-Galavi** [comment]
I removed mine

**Comment by RiccardoRossi** [comment]
and how would you tell "please do not touch it"?

**Comment by inigolcanalejo** [comment]
I just deleted about 20. The rest still contain work that I would like to bring to master.

**Comment by loumalouomega** [comment]
I upadted the counter

**Comment by philbucher** [comment]
> I updated the counter

that was not really the idea, I mean now the sentence doesn't make sense any more :smile: :smile: :smile:

**Comment by philbucher** [comment]
> and how would you tell "please do not touch it"?

@RiccardoRossi 

_personal opinion_:
I would not allow this. The main repo is not the backup storage of anyone. Especially after I tried myself with the forks, it is really trivial to use. Furthermore bringing back branches to the main repo in case it becomes necessary again is very easy too.

_professional opinion_:
if we want to allow this I would say those branches should follow a certain naming pattern then they can easily be protected with a branch protection rule (like we do for the release branches)

**Comment by philbucher** [comment]
to add to my comment, if someone really really really wants a branch to stay and not be affected then once can make a trivial change (like adding a whitespace or newline) thus the latest commit would be too new to be detected as stale
or even easier, merge master

in any case, this would show that there is still someone that know (and cares/needs) a certain branch

**Comment by sunethwarna** [comment]
Removed 21 and updated the counter :)

**Comment by philbucher** [comment]
the counter was never supposed to be updated in the firs place as it was supposed to show the situation at that point in time :sweat_smile:

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee thinks that having a weekly email with all your open branches would help the developers to organize themselves. If we see that it is not effective, then we can go for more sever actions.
