### ISSUE TITLE
Non-Linear Analysis Type in StructuralMechanicsApplication

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#746]
Hi guys,
@AndreasWinterstein  and me just noticed that there are 3 different analysis types defined in "structural_mechanics_static_solver.py" + an else statement to create a newton raphson strategy. We would like to change that else statement to  :             
elif self.settings["analysis_type"].GetString() == "Non-Linear":
        mechanical_solver = self._create_newton_raphson_strategy()
and add an error message in a new else statement. Right now the user could type anything and would create a NR-strategy. Is this ok for you?
Klaus

**Comment by RiccardoRossi** [comment]
i think we should throw an error telling, options are :" ...."

**Comment by pooyan-dadvand** [comment]
👍 for throwing error....

**Comment by philbucher** [comment]
I also just had problems, the strategy selection of the static solver is quite different from the dynamic one. I think it would be a good opportunity to unify the behaviors

**Comment by pooyan-dadvand** [comment]
👍 for @philbucher

**Comment by philbucher** [comment]
fixed in #850
