### ISSUE TITLE
How can I get pointer to the constitutive law from a boundary condition?

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/Kratos#7476]
**Description**
I would like to implement viscous boundary conditions (absorbing boundary conditions) for dynamic simulations. Here, I need to get the stiffness of material in the element attached to the boundary condition. I checked the code but I couldn't figure out how I can get access to elements/constitutive laws from a boundary condition.

**Scope**
- KratosCore
- Documentation

**Comment by loumalouomega** [comment]
Huuum, that will require additional work. CL are stored in the GP of the element. We need to detect first the corresponding elements associated to the BC, and then retrieve the corresponding CL (that may be greater than 1 in case of not tri and tetra)

**Comment by rubenzorrilla** [comment]
Hi @Vahid-Galavi !

You can access the parent element of each condition after having computed the neighbours as we do in the `TetrahedralMeshOrientationCheck`. As you can see, that process calculates the condition neighbours such that you can do `p_parent_element = p_my_condition->GetValue(NEIGHBOUR_ELEMENTS)(0)` (the parent element is always saved in the first position of the `NEIGHBOUR_ELEMENTS` vector).

An alternative is what we used to do in the `InitializeSolutionStep` of the `EmbeddedAusasNavierStokesWallCondition`. In there we obtain the parent element from the nodal elemental neighbours, which are computed by executing the `FindGlobalNodalElementalNeighboursProcess`. 

Once you have the pointer to the parent element you can retrieve the constitutive law from one of the Gauss pts. (in here you should consider @loumalouomega 's comment in case the CL involves a plastic/damage behaviour).

Hope this helps.

**Comment by Vahid-Galavi** [comment]
Thanks @loumalouomega and @rubenzorrilla for your prompt answer. I will try the suggestions in my implementation.

**Comment by rubenzorrilla** [comment]
> Thanks @loumalouomega and @rubenzorrilla for your prompt answer. I will try the suggestions in my implementation.

Cool. Let us know if you have any issue.

**Comment by Vahid-Galavi** [comment]
@rubenzorrilla thanks for the suggestion. I found some time to work on this again. In my case, `p_my_condition->GetValue(NEIGHBOUR_ELEMENTS)` is empty for all boundary conditions that I have in my mode. Do I need to call some functions to set neighbor elements before using it?

**Comment by rubenzorrilla** [comment]
Hey  @Vahid-Galavi ! I think you need to call `FindGlobalNodalElementalNeighboursProcess` at the beginning of the simulation.

**Comment by loumalouomega** [comment]
> Hey @Vahid-Galavi ! I think you need to call `FindGlobalNodalElementalNeighboursProcess` at the beginning of the simulation.

Indeed, better approach

**Comment by Vahid-Galavi** [comment]
Hi @rubenzorrilla it seems that this function gives list of elements sharing the same node. So, from each node I can get list of elements. So the syntax is `rGeom[i].GetValue(NEIGHBOUR_ELEMENTS)`. Therefore, I do not get directly pointer to elements of a condition. Is it correct? Is there already such a function?

**Comment by loumalouomega** [comment]
> Hi @rubenzorrilla it seems that this function gives list of elements sharing the same node. So, from each node I can get list of elements. So the syntax is `rGeom[i].GetValue(NEIGHBOUR_ELEMENTS)`. Therefore, I do not get directly pointer to elements of a condition. Is it correct? Is there already such a function?

Sorry, we will need to create a new function in order to make that. The good news is that the code will be very close (and ever simpler) to the SkinDetectionProcess (basically once identified the nodes of the interface look for the conditions with the corresponding ordering and assign the "mother" element).

**Comment by Vahid-Galavi** [comment]
Thanks @loumalouomega! Is it already planed in the technical community to develop such a function or should I do it?

**Comment by loumalouomega** [comment]
> Thanks @loumalouomega! Is it already planed in the technical community to develop such a function or should I do it?

If I had time I could do it myself... (is not that difficult)

**Comment by Vahid-Galavi** [comment]
Thanks @loumalouomega! Then I will go through your code see how you did it.

**Comment by rubenzorrilla** [comment]
OK, now I see. We do this same opetation in the `TetrahedralMeshOrientationCheck`. See [here](https://github.com/KratosMultiphysics/Kratos/blob/4065ca660170b8e66f62bbfd0124e9ee33c0565b/kratos/processes/tetrahedral_mesh_orientation_check.cpp#L143-L150).

**Comment by Vahid-Galavi** [comment]
Thanks @rubenzorrilla and @loumalouomega for your helps. I developed the process and it is under review now in this PR #9412. 
So, I close this issue.
