### ISSUE TITLE
DEM RigidEdge vs. RigidFace

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#7480]
**Description**
Hi, I stumbled upon RigidEdge while working with students in the DEMApp, especially as GID writes RigidEdge3D2N for line wall conditions.

Until now I've been using RigidFace3D2N for line wall conditions. I ran some tests of mine and do not see different results using either of them. Also looking at the code I can't find many differences.

Is there a key point I am missing or is the RigidEdge superfluous?
 
**Scope**
DEM

**Comment by maceligueta** [comment]
Yes @KlausBSautter , the RigidEdge3D2N is useless. We can remove it. I will open a PR for it.
However, the RigidEdge2D2N is still useful. We might think of calling it RigidFace2D2N to make it more uniform, but it would still use the RigidEdge cpp file inside. Actually, the RigidEdge.cpp contains a class called RigidEdge3D, which is wrong, as the RigidEdge is only used in 2D currently. I will incluce all this in a PR.

**Comment by KlausBSautter** [comment]
this can be closed, thanks!
