### ISSUE TITLE
DLL load failed while importing Kratos

### ISSUE THREAD

**Issue by rath3t** [KratosMultiphysics/Kratos#7487]
**Description**
I tried to run the Kratos minimal script.I sucessfully compiled it in Release. Running the script
```python
from KratosMultiphysics import *
```
yields the following error message:

![Error](https://user-images.githubusercontent.com/10537464/93446705-ce3a4500-f8d1-11ea-9506-3e511ee96485.PNG)

My environment variables are 
*LD_LIBRARY_PATH*
![UserLD_LIBRARY_PATH](https://user-images.githubusercontent.com/10537464/93446738-d5615300-f8d1-11ea-88c0-0a862d0fafb1.PNG)
*PATH*
![UserPATH](https://user-images.githubusercontent.com/10537464/93446767-e27e4200-f8d1-11ea-9fbe-cc0d20c7d195.PNG)
*PYTHONPATH*
![UserPYTHONPATH](https://user-images.githubusercontent.com/10537464/93446773-e4480580-f8d1-11ea-9821-b74f75e916c7.PNG)

and finally my configure file
[configure_release.txt](https://github.com/KratosMultiphysics/Kratos/files/5237575/configure_release.txt)

Thanks for your help!

**Comment by roigcarlo** [comment]
Hi @rath3t 

Can you type `python.exe --version` in the terminal and show me the output?

Also can you show me the list of files in:
`C:\Users\Alex\Documents\Kratos_200812\Kratos\bin\Release\libs`

Thx!

**Comment by rath3t** [comment]
Hi @roigcarlo ,
your requested information:
![kratos](https://user-images.githubusercontent.com/10537464/93561458-84f6fd80-f984-11ea-959c-30a989b0d8c3.png)


<img src="https://user-images.githubusercontent.com/10537464/93561108-e9fe2380-f983-11ea-893d-2021749134da.png" alt="drawing" width="200"/>

Thx!

**Comment by roigcarlo** [comment]
Hi @rath3t 

First thing, completely remove the LD_LIBRARY_PATH, that only works for linux.

As for the files and python versions everything seems fine, so the only possible problem that comes to my mind is some problems with the env variables scope. 

I assume you are defining the PATH and PYTHONPATH as user variables (I think in german they appear under `Benutzervariablen für winte` or something like that). You can try this by typing `echo %PATH%` in the terminal and checking the paths you added are there.

If they are not, could yo try to add the paths you already have to the system (systemvariablen) ones? ( they should appear in the bottom list, if not you can create them).

If this was not the problem, could you try to upload the KratosCore.dll somewhere so I can check the dependencies etc...?

**Comment by rath3t** [comment]
Hi @roigcarlo ,
i defined these environment variables also as System env variables and as user variables. If I type `echo %PATH%` i see the added libs folder.
I also appended the KratosCore.dll file.
[KratosCore.dll.txt](https://github.com/KratosMultiphysics/Kratos/files/5253614/KratosCore.dll.txt)

**Comment by roigcarlo** [comment]
Hi, 

According to the file, seems that what's missing is the zlib.dll library.

Could you try adding this flag: `-DFORCE_LOCAL_ZLIB_COMPILATION=ON` and check if the dll is generated?

In win that could happen if you already have a version and its found by cmake, copying it inside the libs folder should have the same effect so you can also try that.

**Comment by rath3t** [comment]
That has done the trick. I copied my `zlib.dll` into `C:\Users\Alex\Documents\Kratos_200812\Kratos\bin\Release\libs` and i got:

![image](https://user-images.githubusercontent.com/10537464/93847825-56409600-fca8-11ea-8bc6-815cac5001db.png)

Thank you!
