### ISSUE TITLE
[Particle] usage of boost.geometry

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7518]
The `MPMSearchElementUtility` uses `boost geometry`
This gives the following warning: `CAUTION: Boost.Geometry in Boost 1.73 deprecates support for C++03 and will require C++14 from Boost 1.75 onwards`
This will be incompatible with Kratos which is C++11 atm

Can this be refactored to be independent of boost?
@tteschemacher @bodhinandach @peterjwilson 
@KratosMultiphysics/mpm

**Comment by philbucher** [comment]
I checked, this was added in #7079

**Comment by peterjwilson** [comment]
@philbucher yep this is my baby 👶 - let's chat about the options we have soon

**Comment by RiccardoRossi** [comment]
@peterjwilson do you really need boost.geometry? 
since a few years we are trying to minimize dependencies on boost, since it is a BIIIIIG dependency. is it completely needed?

**Comment by philbucher** [comment]
I updated to boost 1.75 and ParticleMechanics no longer compiles

I don't have the intention of updating the CI soon, but it might be necessary for the usage of C++ based parallelism I am working on together with @RiccardoRossi atm

I am not sure what the best solution would be
