### ISSUE TITLE
Improving output of MixedGenericCriteria

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7536]
**Description**
The output can be made nicer of the `MixedGenericCriteria`
e.g.
~~~
 DISPLACEMENT : ratio = 1.64144e-07; exp.ratio = 5e-07 abs = 1.34002e-08 exp.abs = 5e-09
 ROTATION : ratio = 1.54434e-05; exp.ratio = 5e-07 abs = 5.03158e-08 exp.abs = 5e-09
~~~

would be easier to read as:
~~~
 DISPLACEMENT : ratio = 1.64144e-07; exp.ratio = 5e-07 abs = 1.34002e-08 exp.abs = 5e-09
 ROTATION :     ratio = 1.54434e-05; exp.ratio = 5e-07 abs = 5.03158e-08 exp.abs = 5e-09
~~~

not urgent, but would be nice to have

**Comment by loumalouomega** [comment]
I am doing in the branch core/mixed-residual-criteria the equivalent residual criteria, note to myself @loumalouomega , do this there too

**Comment by philbucher** [comment]
@ashishdarekar some info for doing this:
The `Variable`s have a `Name` method which gives you a string, from which you can get the `length` for the formatting
you can use this [test](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/tests/cpp_tests/strategies/convergence_criteria/test_mixed_generic_criteria.cpp) to check the output

**Comment by rubenzorrilla** [comment]
```
DISPLACEMENT : ratio = 1.64144e-07; exp.ratio = 5e-07 abs = 1.34002e-08 exp.abs = 5e-09
ROTATION     : ratio = 1.54434e-05; exp.ratio = 5e-07 abs = 5.03158e-08 exp.abs = 5e-09
```
Maybe a bit picky, but I think it would be nicer in this way (note the double dot in `ROTATION`).

**Comment by philbucher** [comment]
@ashishdarekar I agree with @rubenzorrilla, can you please do it as he suggests?
