### ISSUE TITLE
[Core][External library][Discussion] Replace python depence for mathematical expressions

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#7539]
**Description**

Currently, in order to parse the mathematical functions we consider the pybind11 python callback, see: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/utilities/python_function_callback_utility.h

Looking for another project a way to parse a mathematical function without requiring this dependence (and also improving performance, as the performance of the function evaluation is python performance) I found this MIT library: [exprtk](https://www.partow.net/programming/exprtk/index.html)

I would like to discuss if it could be interesting to replace this python callback for  this library.

**Comment by loumalouomega** [comment]
Additionally, the only reason `assign_scalar_field_to_entities_process.cpp` must be added to `KRATOS_PYTHON_SOURCES` instead of `KRATOS_CORE_SOURCES` is the dependence of `Python.h`

https://github.com/KratosMultiphysics/Kratos/blob/4a902bbb8f6090ea83c18c0faa7fc6c5ecd2708e/kratos/CMakeLists.txt#L136

Without this dependence we can group the sources and use a CMake macro and add them automatically instead of modify the `CMakeLists.txt` each time

**Comment by philbucher** [comment]
I wanted to do the same 2 years ago, I was looking at some libraries together with Jordi but we didn't like any of the options for various reasons (don't remember the details)

The main concern was the thread safety that wasn't provided, do you know how the lib you propose does it?

Just to add that I would be in favor of finding a better solution

**Comment by loumalouomega** [comment]
> I wanted to do the same 2 years ago, I was looking at some libraries together with Jordi but we didn't like any of the options for various reasons (don't remember the details)
> 
> The main concern was the thread safety that wasn't provided, do you know how the lib you propose does it?
> 
> Just to add that I would be in favor of finding a better solution

I was doing research this morning, I don't know details. That's why I opened the discussion. 

I want to use it first in my project, understand the library and then I can try to use in here

**Comment by loumalouomega** [comment]
> I wanted to do the same 2 years ago, I was looking at some libraries together with Jordi but we didn't like any of the options for various reasons (don't remember the details)
> 
> The main concern was the thread safety that wasn't provided, do you know how the lib you propose does it?
> 
> Just to add that I would be in favor of finding a better solution

I assume is thread safe, is standard C++, there is no GIL

**Comment by philbucher** [comment]
> I assume is thread safe, is standard C++, there is no GIL

that not, but IIRC some libraries build some "parsing backend" that was shared aka not threadsafe

**Comment by loumalouomega** [comment]
I will ask them

**Comment by ArashPartow** [comment]
Hi @longchentum   - as an example waLBerla uses exprtk:

https://i10git.cs.fau.de/walberla/walberla/-/blob/master/src/core/math/Parser.cpp#L68

**Comment by loumalouomega** [comment]
> Hi @longchentum - as an example waLBerla uses exprtk:
> 
> [i10git.cs.fau.de/walberla/walberla/-/blob/master/src/core/math/Parser.cpp#L68](https://i10git.cs.fau.de/walberla/walberla/-/blob/master/src/core/math/Parser.cpp#L68)
> 
> and if you really want to go through a python layer, there's this:
> 
> [pypi.org/project/cexprtk](https://pypi.org/project/cexprtk/)

I assume you meant me

**Comment by loumalouomega** [comment]
> Hi @longchentum - as an example waLBerla uses exprtk:
> 
> [i10git.cs.fau.de/walberla/walberla/-/blob/master/src/core/math/Parser.cpp#L68](https://i10git.cs.fau.de/walberla/walberla/-/blob/master/src/core/math/Parser.cpp#L68)
> 
> and if you really want to go through a python layer, there's this:
> 
> [pypi.org/project/cexprtk](https://pypi.org/project/cexprtk/)

Thanks!

**Comment by ArashPartow** [comment]
@loumalouomega  apologies - yes i was directed it at you.
