### ISSUE TITLE
Question about monotonicity preserving solver

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#7548]
**Description**
Dear @ddiezrod , I'm interested on monotonicity preserving solvers and I saw the new implementation in #7409 
I would like to understand better how it works, is there any publication about that method?

**Scope**
- Documentation

**Comment by ddiezrod** [comment]
In this solver, I implemented a quite rough approach where basically diffusion is added to make sure there is no positive off-diagonal term that can cause over/undershoots.

We use this for the thermal problem and got quite good results even for low conductivities. I have not tried it yet in other kinds of problems.

There are other more sophisticated implementations that we have not tried yet. Maybe this paper could help you a little.

https://www.mathematik.uni-dortmund.de/~kuzmin/fcttvd.pdf

**Comment by miguelmaso** [comment]
Thanks! I will take a look
