### ISSUE TITLE
Many test failures in nightly build

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7551]
**Description**
Many tests fail in the nightly build

**Scope**
- KratosCore (@sunethwarna )
- DEM & SwimmingDEMApp (@KratosMultiphysics/dem )
- CoSimulation @philbucher 
- Contact but this is known

it happens differently for the different Operating systems, please check

note to myself and @roigcarlo: would probably be a good idea to bring back the mailing of the results

**Comment by sunethwarna** [comment]
On it....

**Comment by roigcarlo** [comment]
About the mails, I can share the code I used with the amazon machine, but to be honest I would prefer not resurrecting that :S, I am not very fan of generating spam.

Or at leas try to condense it in a weekly digest or something

**Comment by pooyan-dadvand** [comment]
I agree with @roigcarlo that mails would be more spam than useful. (most of the people would simply ignore it) 

But we should definitely find another mechanism

**Comment by philbucher** [comment]
solved, nightly build is finally clean!

but still we should find a way to notify devs if sth fails

right now I am thinking of posting a message in PRs that were merged the day before the nightly build broke
But lets see...
