### ISSUE TITLE
Deleting branches by default after merging

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7555]
**Description**
In order to help reducing the number of (unused) branches in the repository (see e.g. #7433) the @KratosMultiphysics/technical-committee is considering deleting branches by default after merging, since in most cases those branches are no longer needed/used.

If someone however wants to keep the branch, they could restore it right away, the button appears right after a branch was deleted
![image](https://user-images.githubusercontent.com/25484702/94907001-c36ddb80-049f-11eb-82ab-bb415eefa999.png)

any opinions @KratosMultiphysics/all ?

**Comment by AlejandroCornejo** [comment]
It's a good thing in my opinion, I always have to remember to remove  the already merged branch.  :+1:

**Comment by riccardotosi** [comment]
Ok to me.

**Comment by loumalouomega** [comment]
I thought this was already by default (at least in my session)

**Comment by philbucher** [comment]
> I thought this was already by default (at least in my session) El vie., 2 oct. 2020 11:47, riccardotosi <notifications@github.com> 

no it is not :)

**Comment by philbucher** [comment]
After having this open for some time, the @KratosMultiphysics/technical-committee decided to go ahead and delete branches by default
Please let us know if you encounter problems

**Comment by pooyan-dadvand** [comment]
I am closing it as it is already applied and works
