### ISSUE TITLE
Conflict with a python file name of the core 

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#758]
In a past pull-request  #44, two files from the SolidMechanicsApplication were copied to the core and modified internally to do different things:

assign_scalar_to_conditions_process.py
assign_vector_to_conditions_process.py

Then the name of one of the files was changed to avoid conflicts but one file remained with the same name. So now there are

assign_scalar_to_conditions_process.py
assign_vector_to_condition_process.py

For consistency the first file must be renamed as 

assign_scalar_to_condition_process.py

This will solve the conflict that exists now, because the file of the SolidMechanicsApplication is hidden by the one in the core.

**Comment by rubenzorrilla** [comment]
Hi  @josep-m-carbonell!!

After a short discussion with @RiccardoRossi, we think that the best way to proceed is to rename the core processes in the way below:

- assign_scalar_to_conditions_process.py to assign_scalar_variable_to_conditions_process.py
- assign_vector_to_condition_process.py to assign_vector_variable_to_conditions_process.py

In this way the name convention is the same as the other core processes and the conflicts with the SolidMechanicsApplication are avoided. Is this ok?

(I will do the changes ASAP)

**Comment by josep-m-carbonell** [comment]
For me it is ok. Thank you!

**Comment by rubenzorrilla** [comment]
Done!! @josep-m-carbonell, would you mind running your tests to be sure that everything is ok? Thank you! (PR #768, branch name: fix-condition-processes-naming)

**Comment by josep-m-carbonell** [comment]
All tests worked, thank you @rubenzorrilla !
