### ISSUE TITLE
[StructuralMechanicsApp] Adding INITIAL_STRESS_VECTOR and INITIAL_STRAIN_VECTOR 

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#7602]
Dear all, 
@maceligueta, @RiccardoRossi and me have been thinking about including the option of applying `INITIAL_STRESS_VECTOR ` and `INITIAL_STRAIN_VECTOR` within the constitutive laws implemented.

The theoretical idea is to be able of perform this:
![imagen](https://user-images.githubusercontent.com/26402605/95980476-86013a80-0e1d-11eb-84fb-3e5cff61d95f.png)

being E_0 the initial strain and S_0 the initial stress. Obviously this has to be implemented in all the CL available inside the SMA.

The main characteristics of the implementation proposed are:

- The  `INITIAL_STRESS_VECTOR ` and `INITIAL_STRAIN_VECTOR` are stored element-wise and assigned and retrieved with the GetValue(-)/SetValue(-) of the element. 

- Since the element Set or GetValue store the vector in the `Geometry`, the CL can have access to it.

- We will create a non-virtual method in the base class called `GetInitialStrain()` and `GetInitialStress()` in order to create a general way of doing it.

Please feel free to give any feedback on this issue.

@KratosMultiphysics/structural-mechanics

**Comment by philbucher** [comment]
sounds good to me

Minor questions:
- cannot the initial... be different for every GP? Asking bcs you say you want to store it element-wise
- The new methods (`GetInitialStrain`, `GetInitialStress`) will be in the `ConstitutiveLaw` baseclass?

@KlausBSautter is this also ok for you? You have more experience with this than me...

**Comment by KlausBSautter** [comment]
This seems ok to me, we will need some restructuring in the truss and membrane elements. But in this way, we will have a unified strategy.

**Comment by loumalouomega** [comment]
I have to recover my initial deformation class, which is more general, but of course I need to find the time

**Comment by loumalouomega** [comment]
> I have to recover my initial deformation class, which is more general, but of course I need to find the time

See https://github.com/KratosMultiphysics/Kratos/tree/core/imp-def

**Comment by KlausBSautter** [comment]
-> cannot the initial... be different for every GP? Asking bcs you say you want to store it element-wise

this is true, we would need that for each GP, in my opinion.

we already use this feature in the following way (we will have to rewrite this), but you can see that it also stores values for each GP:

https://github.com/KratosMultiphysics/Kratos/blob/f9199ae3e1f16265d4bce1d46678c70e23400131/applications/StructuralMechanicsApplication/custom_elements/membrane_element.cpp#L993-L1003

**Comment by loumalouomega** [comment]
> > I have to recover my initial deformation class, which is more general, but of course I need to find the time
> 
> See [`core`/imp-def](https://github.com/KratosMultiphysics/Kratos/tree/core/imp-def?rgh-link-date=2020-10-14T11%3A50%3A50Z)

Here the implementation is more general what you propose @AlejandroCornejo and the idea is to be able to combine them, so being possible to have combined effects of creep and temperature for example

**Comment by maceligueta** [comment]
Just referencing @Vahid-Galavi , because I asked him about this feature in #7573 , to make him aware of this PR.

**Comment by philbucher** [comment]
@loumalouomega looking at your implementation, isn't this two different things?
I.e. there is nothing about initial stresses, only some interfaces for imposed displacements?

**Comment by loumalouomega** [comment]
> @loumalouomega looking at your implementation, isn't this two different things?
> I.e. there is nothing about initial stresses, only some interfaces for imposed displacements?

All the contrary,it is more general, it is possible to impose strains, stresses, and so on. I need time to finish the API

**Comment by loumalouomega** [comment]
> > @loumalouomega looking at your implementation, isn't this two different things?
> > I.e. there is nothing about initial stresses, only some interfaces for imposed displacements?
> 
> All the contrary,it is more general, it is possible to impose strains, stresses, and so on. I need time to finish the API

OK, I see the minimal examples are not there, sorry I need to add them

**Comment by AlejandroCornejo** [comment]
I'm implementing this in here https://github.com/KratosMultiphysics/Kratos/pull/7663 FYI

**Comment by tteschemacher** [comment]
I was recently using something similar as the initial stress/strain, but I was updating it from a different model in every time step. Now the thing is the concept is exactly the same and it doesn't provide any additional overhead, thus, if possible I would suggest to formulate it in a way that it can be updated throughout the time. The name InitialStrain would be a bit confusing as it is more a PreStrain. 

Not sure if I am too late now with my comment, but still having the possibility to update, read or remove the inital stress/strain during simulation would be nice.

**Comment by AlejandroCornejo** [comment]
With the implementation in  #7663 it is possible to modify the value of the imposed strain/stress whenever is necessary. @tteschemacher how do you avoid the overhead?
