### ISSUE TITLE
[Structural] AutomaticRayleighComputationProcess bug

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#7681]
**Description**
Trying to access a non-declared member variable (`self.mass_matrix_diagonal_value`).

**Scope**
- `StructuralMechanicsApplication`

**Expected behavior**
The variable must be set before its use (AFAIK this has something to do with the lumping of the mas matrix so a default behaviour should be also provided if this is not specified in the `ProcessInfo`).

**Comment by rubenzorrilla** [comment]
Going through it I realised that the problem is in the Process defaults validation. If the user does not provide
```
"eigen_system_settings" : {
    "solver_type"       : "eigen_eigensystem"
}
```
the `solver_type` is not recursively added.

**Comment by loumalouomega** [comment]
What do you mean?, can you refer the line of code?

**Comment by rubenzorrilla** [comment]
The line is the 120. Try the process with this settings and it will raise. 
```
{
            "python_module" : "automatic_rayleigh_parameters_computation_process",
            "kratos_module" : "KratosMultiphysics.StructuralMechanicsApplication",
            "process_name"  : "AutomaticRayleighComputationProcess",
            "Parameters"    : {
                "model_part_name" : "Structure"
            }
```

**Comment by loumalouomega** [comment]
See #7687
