### ISSUE TITLE
[Core] Passing ProcessInfo in ModelPart check function

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#7713]
**Description**
Thanks to the warning that we fixed in #7712 @philbucher and I realised that the `Check` function of the `ModelPart` requires passing a `ProcessInfo` container.

Considering that the `ModelPart` owns the `ProcessInfo` this makes not so much sense. Having said so it probably makes sense to remove it. Even though this is an easy change, it would imply breaking the current API (silently for those applications that are not compiled in the CI).

**Comment by philbucher** [comment]
I think that `ModelPart::Check` is not even called in our usual workflow, only the one of the `SolvingStrategy`, which doesn't call the one of the `ModelPart`

=> also we should decide who should do the checking of `Elements` etc (MP, Strategy, Scheme?)

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee delegates completely this issue to the @KratosMultiphysics/implementation-committee

**Comment by rubenzorrilla** [comment]
Ping @KratosMultiphysics/implementation-committee 

Summarizing things to be discussed:

- [ ] Remove `ProcessInfo` argument from `ModelPart` `Check` method.
- [ ] Who checks the `Elements`, `Conditions`, `Constraints`, etc? Through the strategy as we do know or should we start using the `ModelPart` check?

**Comment by rubenzorrilla** [comment]
@KratosMultiphysics/implementation-committee is there any advance in this regard?

**Comment by AlejandroCornejo** [comment]
Hi! On behalf of the @KratosMultiphysics/implementation-committee, We agree with @rubenzorrilla that the `ProcessInfo `has to be removed from the `check `method.

However, who performs the check is more complex. **One option** is to add the ModelPart->Check in the strategy and remove the Elements, conditions check from the Scheme.

Another option (easier one) is to modify the `Scheme `check implementation and call the `ModelPart->check` within the scheme. In this way we do not repeat code.

What is your opinion?

**Comment by ddiezrod** [comment]
After some discussion in the @KratosMultiphysics/implementation-committee we think it might be safer to just go with the second option that @AlejandroCornejo proposed: modify the scheme to call the ModelPart::Check(), modifying the body of this function so it behaves exactly as it does right now in the scheme. If @KratosMultiphysics/technical-committee is with this, we'll proceed in the following days with the changes.

**Comment by rubenzorrilla** [comment]
Should be solved in #9552. Thanks guys!
