### ISSUE TITLE
KRATOS_CHECKS including NaN-values.

### ISSUE THREAD

**Issue by manuelmessmer** [KratosMultiphysics/Kratos#7730]
**Description**
I was just writing a test case and noticed that e.g. `KRATOS_CHECK_NEAR` does not throw an error if the checked value is a NaN-value.
This is simply the case, because an if-statement will always be FALSE, if it contains a NaN-value.
@KratosMultiphysics/technical-committee 

**Scope**
Where in Kratos is this bug happening. 
- Testing

**To Reproduce**
`double a = std::numeric_limits<double>::quiet_NaN()`
`double b = 5;` 
`if( std::abs(a-b) > TOLERANCE) ` -> This will not throw an error, as statement is FALSE for NaN.

**Expected behavior**
`if( !(std::abs(a-b) < TOLERANCE))` This will throw an error, as statement is TRUE for NaN.

**Comment by sunethwarna** [comment]
As per my experience, the `NaN` checking stuff breaks when some of the c++ optimization flags are used. 
https://stackoverflow.com/questions/47703436/isnan-does-not-work-correctly-with-ofast-flags

**Comment by pooyan-dadvand** [comment]
If changing the macro as @manuelmessmer is suggesting works as a workaround, I am completely fine with it. I think that a PR with a unit test would clarify its effectiveness regarding to the optimization and fast math.

**Comment by roigcarlo** [comment]
Just comment that @manuelmessmer altarnative will work since expressions with `NaN` and `-NaN` are always evaluated to false.

**Comment by manuelmessmer** [comment]
okay sounds good! Will put it on my to-do list ;)

**Comment by RiccardoRossi** [comment]
i think suneth is right about this one.

i am afraid this can only work if a specific compiler flag is used to
enforce ieee compliance for floating point operations,

so, what happens if that flag is not set?

**Comment by roigcarlo** [comment]
I understand that @sunethwarna was speaking only about the `std::isnan`, which indeed does not work with `--fast-math`, but as far as I know the fact that `Nan` gets evaluated to `false` in operators has nothing to do with the optimization flags.

You can't tell if its `Nan` or not, but if it is `Nan Op Val` will return `false`.

**Comment by oberbichler** [comment]
Not so important but

`bool almost_equal(double a, double b, double tolerance) { return std::fabs(a - b) <= tolerance); }`

is `false` for checking infinity e.g. `almost_equal(inf, inf, 0) = false`.

Of course a very special case. To handle this I would go for

`bool almost_equal_include_inf(double a, double b, double tolerance) { return (a + tolerance >= b) && (b + tolerance >= a); }`

**Comment by philbucher** [comment]
this can be closed right?
