### ISSUE TITLE
Thread safety issue in test_chunk.cpp

### ISSUE THREAD

**Issue by RezaNajian** [KratosMultiphysics/Kratos#7743]
**Description**
I have been running kratos tests and I noticed that test_chunk is failing from time to time for different num threads. I get this error message:
Error: Error: Check failed because the_vector[i] is equal to nullptr for i = 98 and repeat = 21
   in: kratos/tests/cpp_tests/sources/test_chunk.cpp:137:virtual void Testing::TestChunkParallelAllocateDeallocate::TestFunction()Exception

**Scope**
- cpp tests

**To Reproduce**
I am running run_tests.py and run_cpp_tests.py. Specially it fails when I set OMP_NUM_THREADS=16. 

**Environment**
- OS: Fedora 7.7
- Branch: master
- Python 3.6

**Comment by rezanajianasl** [comment]
@philbucher maybe it is related to PR #7600 ?!

**Comment by philbucher** [comment]
Unlikely, the code in the background is exactly the same
In any case the Chunk is experimental and not used anywhere except the tests
Since the parallelism is being refactored atm we are also looking into rewriting and improving the Chunk so that it can be used in practice 
I will look into it next week so that the tests no longer fail

**Comment by pooyan-dadvand** [comment]
The chunk is still in an experimental state and not in production. @philbucher I think you should have disabled the test using `KRATOS_DISABLED_TEST_CASE_IN_SUITE` macro instead of changing the suite to `EXClUDED`. `TestAllCases` would avoid disabled tests but not this excluded suite.

**Comment by philbucher** [comment]
> @philbucher maybe it is related to PR #7600 ?!

@RezaNajian any idea if this was working before #7600 ?
Maybe I broke sth after all
