### ISSUE TITLE
[StatisticsApplication] Doubt about README

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/Kratos#7747]
**Description**
I am computing **time averages**, discarding an **initial transient time of 2.5 seconds**. I want to compute the time average of **two historical variables** (VELOCITY and PRESSURE, defined in input_settings) and to have **two non-historical variables** as time averaged quantities (defined in output_settings).

I am using the statistics application, and following the README I see that the json should look like
```json
        {
            "kratos_module": "KratosMultiphysics.StatisticsApplication",
            "python_module": "temporal_statistics_process",
            "Parameters": {
                "model_part_name": "FluidModelPart.fluid_computational_model_part",
                "input_variable_settings": [
                    {
                        "method_name": "mean",
                        "norm_type": "none",
                        "container": "nodal_historical_non_historical",
                        "echo_level": 1,
                        "method_settings": {
                            "input_variables": [
                                "VELOCITY",
                                "PRESSURE"
                            ],
                            "output_mean_variables": [
                                "VECTOR_3D_MEAN",
                                "SCALAR_MEAN"
                            ]
                        }
                    }
                ],
                "statistics_start_point_control_variable_name": "TIME",
                "statistics_start_point_control_value": 2.5
            }
        }
```
However, I get the error:
```bash
Parameters being validated are :
{
    "input_variables": [
        "VELOCITY",
        "PRESSURE"
    ],
    "output_mean_variables": [
        "AVERAGED_VELOCITY",
        "AVERAGED_PRESSURE"
    ]
}
Defaults against which the current parameters are validated are :
{
    "input_variables": [],
    "output_variables": []
}

```
 Finally, using this json
```json
        {
            "kratos_module": "KratosMultiphysics.StatisticsApplication",
            "python_module": "temporal_statistics_process",
            "Parameters": {
                "model_part_name": "FluidModelPart.fluid_computational_model_part",
                "input_variable_settings": [
                    {
                        "method_name": "mean",
                        "norm_type": "none",
                        "container": "nodal_historical_non_historical",
                        "echo_level": 1,
                        "method_settings": {
                            "input_variables": [
                                "VELOCITY",
                                "PRESSURE"
                            ],
                            "output_variables": [
                                "VECTOR_3D_MEAN",
                                "SCALAR_MEAN"
                            ]
                        }
                    }
                ],
                "statistics_start_point_control_variable_name": "TIME",
                "statistics_start_point_control_value": 2.5
            }
        }
```
it works fine (without errors).

I think it is just an error of the documentation, but I opened the issue be sure about it. And also to propose to update the README accordingly to the behavior of the process.

**Scope**
Which areas of Kratos are involved
- StatisticsApplication
- Documentation

**Comment by sunethwarna** [comment]
@riccardotosi Yes you are correct. It is a copy paste mistake I made when I was creating the README. The settings in existing README for `mean` is the copied from `variance` method. Sorry for the trouble. Thanks for noticing.

**Comment by sunethwarna** [comment]
Hi @riccardotosi 

> Finally, using this json

        {
            "kratos_module": "KratosMultiphysics.StatisticsApplication",
            "python_module": "temporal_statistics_process",
            "Parameters": {
                "model_part_name": "FluidModelPart.fluid_computational_model_part",
                "input_variable_settings": [
                    {
                        "method_name": "mean",
                        "norm_type": "none",
                        "container": "nodal_historical_non_historical",
                        "echo_level": 1,
                        "method_settings": {
                            "input_variables": [
                                "VELOCITY",
                                "PRESSURE"
                            ],
                            "output_variables": [
                                "VECTOR_3D_MEAN",
                                "SCALAR_MEAN"
                            ]
                        }
                    }
                ],
                "statistics_start_point_control_variable_name": "TIME",
                "statistics_start_point_control_value": 2.5
            }
        }

Are the correct settings for mean :+1: . All the temporal methods except for `variance` has this same structure which is mentioned at 
https://github.com/KratosMultiphysics/Kratos/tree/master/applications/StatisticsApplication#temporal-methods. I know it is not clearly visible when you first look at it in the `README`. I kept this structure because, all the methods only need 1-1 mapping from input to output variables except for `variance`. Would you have a better way to make it more simplified and easy to understand?

**Comment by riccardotosi** [comment]
I found the json I posted [at the beginning](https://github.com/KratosMultiphysics/Kratos/tree/master/applications/StatisticsApplication#temporal-statistics-process-example). Maybe you can clearly state that the json is valid **only for temporal variance process**. Or maybe put also another json, which works with other temporal estimators.
