### ISSUE TITLE
RuntimeError: Trying to set a variable that is not in the model_part

### ISSUE THREAD

**Issue by josep-m-carbonell** [KratosMultiphysics/Kratos#775]
- variable name is POSITIVE_FACE_PRESSURE , defined, created and registered in the core. Added to python, etc.. everything seems to be ok.
- the error appears in the Release version 5.1  and in an updated version of the code from the repository, when running the SolidMechanics and also the StructuralMechanics application. 

Here the complete message: 

### Traceback

 (most recent call last):
  File "MainKratos.py", line 71, in <module>
    list_of_processes += process_factory.KratosProcessFactory(StructureModel).ConstructListOfProcesses(ProjectParameters["loads_process_list"])
  File "/home/josep_maria/Kratos/kratos/python_scripts/process_factory.py", line 16, in ConstructListOfProcesses
    p = python_module.Factory(item, self.Model)
  File "/home/josep_maria/Kratos/kratos/python_scripts/assign_scalar_variable_to_conditions_process.py", line 8, in Factory
    return AssignScalarVariableToConditionsProcess(Model, settings["Parameters"])
  File "/home/josep_maria/Kratos/kratos/python_scripts/assign_scalar_variable_to_conditions_process.py", line 51, in __init__
    self.AssignValueProcess = KratosMultiphysics.AssignScalarVariableToConditionsProcess(self.model_part, params)
RuntimeError: Error: Trying to set a variable that is not in the model_part - variable name is POSITIVE_FACE_PRESSURE 

in kratos/processes/assign_scalar_variable_to_conditions_process.h:90:AssignScalarVariableToConditionsProcess::AssignScalarVariableToConditionsProcess(ModelPart &, Parameters)
   kratos/processes/assign_scalar_variable_to_conditions_process.h:93:AssignScalarVariableToConditionsProcess::AssignScalarVariableToConditionsProcess(ModelPart &, Parameters)

Screenshot from the example, a simple 2d beam fixed in one end and a pressure load in the other end.

![screenshot from 2017-09-15 17-52-20](https://user-images.githubusercontent.com/23210788/30491819-d204d848-9a3e-11e7-9e16-7efa11e863f4.png)

**Comment by josep-m-carbonell** [comment]
by the way @loumalouomega , when I compiled the StructuralMechanics app, the compiler complained about this:

In file included from /home/josep_maria/Kratos/applications/StructuralMechanicsApplication/custom_python/add_custom_strategies_to_python.cpp:32:
/home/josep_maria/Kratos/applications/StructuralMechanicsApplication/custom_strategies/custom_strategies/formfinding_updated_reference_strategy.hpp:219:37: warning: 
      assigning field to itself [-Wself-assign-field]
            mReformDofSetAtEachStep = mReformDofSetAtEachStep;
                                    ^

**Comment by rubenzorrilla** [comment]
@josep-m-carbonell we have just approved the PR #650, which solves this minor bug (thank you!)

**Comment by josep-m-carbonell** [comment]
Ok, good. @rubenzorrilla. I delete the messages related to PR #650 because the issue is related to another problem.

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi is it the process you wrote or the old one?

**Comment by josep-m-carbonell** [comment]
135 of the GiDInterface was the origin of the problem....
