### ISSUE TITLE
Error while compiling new application (following tutorial)

### ISSUE THREAD

**Issue by PhiHo-eng** [KratosMultiphysics/Kratos#7786]
Hi everyone,

I am new to Kratos and I tried the [Tutorial](https://github.com/KratosMultiphysics/Kratos/wiki/Kratos-For-Dummies:-Stationary-heat-transfer) to get an idea how to work with Kratos C++ codes.  I was able to to update the config file for compiling it but I am still getting an error and do not know what I am doing wrong.  The definition of the variables seem to cause the problem:
 
[error.txt](https://github.com/KratosMultiphysics/Kratos/files/5523006/error.txt)

Does anyone know how can I fix this? Did I miss something or is something else on the tutorial perhaps not up-to-date to compile with the newest version?

Thanks in advance!

**Comment by PhiHo-eng** [comment]
Adding `#include "containers/varaibles.h"` to the file `my_laplacian_application_variables.h `solved the problem! Thank you!

**Comment by philbucher** [comment]
@PhiHo-eng I think you should only include `includes/variables.h` in the place where it actually needed, aka most probably the cpp of the Element (that should be where the compiler error comes from)
