### ISSUE TITLE
[Windows] Compilation ERROR

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#7800]
I've just updated the master and i get this error when compiling:

`D:\KRATOS_MULTIPHYSICS\Kratos\kratos\utilities\file_name_data_collector.cpp(107): error C2039: 'isdigit': no es un miembro de 'std' [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\kratos\Kr
atosCore.vcxproj]`

and

`D:\KRATOS_MULTIPHYSICS\Kratos\kratos\utilities\file_name_data_
collector.cpp(458): error C2039: 'isdigit': no es un miembro d e 'std' [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\kratos\Kr atosCore.vcxproj]`

Any ideas?

(no es un miembro de == it's not a member of)

**Comment by AlejandroCornejo** [comment]
my configure:

`rem Please do not modify this script

rem For any question please contact with us in:
rem  - https://github.com/KratosMultiphysics/Kratos

rem Optional parameters:
rem You can find a list will all the compiation options in INSTALL.md or here:
rem  - https://github.com/KratosMultiphysics/Kratos/wiki/Compilation-options

rem Set compiler
@echo off
set CC=cl.exe
set CXX=cl.exe

rem Set variables
set KRATOS_SOURCE=~0,-1%/..
set KRATOS_BUILD=%KRATOS_SOURCE%/build
set KRATOS_APP_DIR=applications
set KRATOS_INSTALL_PYTHON_USING_LINKS=ON

rem Set basic configuration
set KRATOS_BUILD_TYPE=Release
if not defined BOOST_ROOT set BOOST_ROOT=D:\boost_1_69_0
if not defined PYTHON_EXECUTABLE set PYTHON_EXECUTABLE=D:\Python37\python.exe

rem Set applications to compile
set KRATOS_APPLICATIONS=
REM CALL :add_app %KRATOS_APP_DIR%\ExternalSolversApplication;
CALL :add_app %KRATOS_APP_DIR%\StructuralMechanicsApplication;
CALL :add_app %KRATOS_APP_DIR%\FemToDemApplication;
CALL :add_app %KRATOS_APP_DIR%\PfemFluidDynamicsApplication;
CALL :add_app %KRATOS_APP_DIR%\DelaunayMeshingApplication;
CALL :add_app %KRATOS_APP_DIR%\DEMApplication;
CALL :add_app %KRATOS_APP_DIR%\MeshingApplication;
CALL :add_app %KRATOS_APP_DIR%\DemStructuresCouplingApplication;

rem Clean
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\cmake_install.cmake"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeCache.txt"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeFiles"

rem Configure
@echo on
cmake -G"Visual Studio 15 2017 Win64" -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%"  ^
-DINCLUDE_FEAST=OFF                                                      ^
-DLAPACK_LIBRARIES="D:\external_libraries\liblapack.lib"                 ^
-DBLAS_LIBRARIES="D:\external_libraries\libblas.lib"                     ^
-DINCLUDE_MMG=ON                                                         ^
-DMMG_INCLUDE_DIR="D:\mmg_master\buid\include"                           ^
-DMMG2D_INCLUDE_DIR="D:\mmg_master\buid\include\mmg\mmg2d/"              ^
-DMMG3D_INCLUDE_DIR="D:\mmg_master\buid\include\mmg\mmg3d/"              ^
-DMMGS_INCLUDE_DIR="D:\mmg_master\buid\include\mmg\mmgs/"                ^
-DMMG_LIBRARY="D:\mmg_master\buid\lib\Release\mmg.lib"                ^
-DMMG2D_LIBRARY="D:\mmg_master\buid\lib\Release\mmg2d.lib"            ^
-DMMG3D_LIBRARY="D:\mmg_master\buid\lib\Release\mmg3d.lib"            ^
-DMMGS_LIBRARY="D:\mmg_master\buid\lib\Release\mmgs.lib"              ^
-DCMAKE_CXX_FLAGS=" -D_SCL_SECURE_NO_WARNINGS /MP "           ^
-DUSE_COTIRE=OFF         

rem Build
cmake --build "%KRATOS_BUILD%/%KRATOS_BUILD_TYPE%" --target install -- /property:configuration=%KRATOS_BUILD_TYPE% /p:Platform=x64
goto:eof

rem Function to add apps
:add_app
set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%1;
goto:eof
`

**Comment by philbucher** [comment]
@sunethwarna can you please take a look?

**Comment by sunethwarna** [comment]
I will... That is strange since this passed in windows CI...

**Comment by philbucher** [comment]
@AlejandroCornejo can you try including `<cctype>` => https://en.cppreference.com/w/cpp/string/byte/isdigit
