### ISSUE TITLE
problem with ParallelUtilites and constant containers

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#7806]
**Description**
BlockPartition does not work for constant containers

**Scope**
whenever somone tries to iterate in parallel over a constant container

**To Reproduce**

**Expected behavior**
It should be possible to sue a constan container in a parallel loop

**Environment**

**Comment by philbucher** [comment]
hm doesn't this depend on the details of the container?

But I agree that there are occasions where this is required

**Comment by philbucher** [comment]
@RiccardoRossi can you add a small test in `test_parallel_utilities.cpp`? then it would be easier to fix it

**Comment by philbucher** [comment]
specifying the iterator type makes it work, but I consider this a workaround
example:
~~~c++
    BlockPartition<const ModelPart::NodesContainerType, ModelPart::NodesContainerType::const_iterator>(rNodes).for_each([](Node<3>& rNode){
        ...
    });
~~~

note that this doesn't work with the `block_for_each`

I tried to specify the `TIteratorType` of the `BlockPartition` with the following but didn't work (although I didn't spend much time investigating)
~~~c++
class TIteratorType=std::conditional<std::is_const<TContainerType>::value, typename TContainerType::const_iterator,typename TContainerType::iterator>,
~~~

**Comment by RiccardoRossi** [comment]
i think @rubenzorrilla has a fix locally

**Comment by philbucher** [comment]
Hm ok
Can you post it?
I already asked @matekelemen to try to make it work

**Comment by rubenzorrilla** [comment]
> i think @rubenzorrilla has a fix locally

No... @rubenzorrilla thought to have fixed it locally but it doesn't work. :1st_place_medal:

**Comment by rubenzorrilla** [comment]
So far we (@RiccardoRossi and I) tried this
```c++
template <class TContainerType, class TFunctionType>
void block_for_each(const TContainerType &&v, TFunctionType &&func)
{
    BlockPartition<typename std::decay<TContainerType>::type, typename std::decay<TContainerType>::const_iterator>(std::forward<TContainerType>(v.begin(), v.end())).for_each(std::forward<TFunctionType>(func));
}

template <class TReducer, class TContainerType, class TFunctionType>
typename TReducer::value_type block_for_each(const TContainerType &&v, TFunctionType &&func)
{
    return BlockPartition<typename std::decay<TContainerType>::type, typename TContainerType::const_iterator>
        (std::forward<TContainerType>(v.begin(), v.end())).template for_each<TReducer>(std::forward<TFunctionType>(func));
}

template <class TContainerType, class TThreadLocalStorage, class TFunctionType>
void block_for_each(const TContainerType &&v, const TThreadLocalStorage& tls, TFunctionType &&func)
{
    BlockPartition<typename std::decay<TContainerType>::type, typename TContainerType::const_iterator>(std::forward<TContainerType>(v.begin(), v.end())).for_each(tls, std::forward<TFunctionType>(func));
}

template <class TReducer, class TContainerType, class TThreadLocalStorage, class TFunctionType>
typename TReducer::value_type block_for_each(const TContainerType &&v, const TThreadLocalStorage& tls, TFunctionType &&func)
{
    return BlockPartition<typename std::decay<TContainerType>::type, typename TContainerType::const_iterator>
        (std::forward<TContainerType>(v.begin(), v.end())).template for_each<TReducer>(tls, std::forward<TFunctionType>(func));
}
```
but we are having issues with the `&&` operator...

(this required to define a `BlockPartition` constructor with `const` data container).

**Comment by matekelemen** [comment]
Here's what I tried: 21389b4fe1d7fd5df5793f6e20ac342d55e3ae97

I'm still waiting to compile and test it but I'm pretty sure it can be done like this.

The basic idea is that the iterator type is externalized to a partially specialized trait class template, which deduces the constness of the container and defines the iterator type accordingly.

Please excuse the style for now, I'll check the guide once I confirm that it works as intended.

**Comment by RiccardoRossi** [comment]
it shoukd be easier than that

@ddemidov could u take a look at the &&
in our proposal? i would take it out and simply pass a reference, not sure
why we put it there in the first place...

**Comment by matekelemen** [comment]
Well, I tried to avoid code duplication and it seemed the best way to go. Anyway, so far I tested it with a ```block_for_each``` that doesn't use a reducer and it works.

**Comment by ddemidov** [comment]
I think the universal references were there to support arbitrary inputs (temporaries, const and non-const references).
Using just the const references could be problematic if one wants to modify the container elements in the functor. And using non-const references does not allow temporaries.

**Comment by RiccardoRossi** [comment]
here goes a "simple" solution by @ddemidov (thx a lot Denis!!)

https://gist.github.com/ddemidov/499e37801a326bd17a04feac1843ba0b/revisions

aside of this diff we should also change the constructor by container to 

~~~cpp
    template <class TData>
    BlockPartition(TData &&rData, int Nchunks = omp_get_max_threads())
        : BlockPartition(rData.begin(), rData.end(), Nchunks)
    {}
~~~
