### ISSUE TITLE
Declare a team of developers/maintainers for each Application in Kratos

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#7814]
Dear all @KratosMultiphysics/all ,

During the last days I've been thinking that in order to better know **who is in charge of a certain App** (report of bugs, compilation errors, help, etc.) could be interesting of having a list in the wiki with all the Applications in Kratos associated to a certain person.

What do you think?

The format can be something like:

1. PFEMFluidDynamicsApp: A. Franci (email)
2. FemToDemApp: A. Cornejo (acornejo@cimne.upc.edu)
3. StructuralMechanicsApp: R. Rossi, V. Mataix, P. Bucher, A. Cornejo,..., (rrossi@cimne.upc.edu, ...,)
[...]

**Comment by rubenzorrilla** [comment]
I think this can be found in here [https://github.com/orgs/KratosMultiphysics/teams](https://github.com/orgs/KratosMultiphysics/teams). Considering that this can be easily reached from the repository main page and that the wiki will become outdated at some point I will stick to that. Also note that by doing so we somehow encourage people to reach developers through email rather than opening a public issue.

A fair discussion is if we should create a team for each application to clarify who takes care of what as you suggest.

**Comment by AlejandroCornejo** [comment]
> 
> 
> I think this can be found in here https://github.com/orgs/KratosMultiphysics/teams. Considering that this can be easily reached from the repository main page and that the wiki will become outdated at some point I will stick to that. Also note that by doing so we somehow encourage people to reach developers through email rather than opening a public issue.
> 
> A fair discussion is if we should create a team for each application to clarify who takes care of what as you suggest.

I agree to use this existing site. As I can see, a lot of apps are missing so we have to add them right?

**Comment by roigcarlo** [comment]
I think @AlejandroCornejo is right here, some teams do not have apps and some apps have multiple teams behind. Teams are ok, but a formal list of app maintainers would be very useful.

**Comment by AlejandroCornejo** [comment]
> 
> 
> I think @AlejandroCornejo is right here, some teams do not have apps and some apps have multiple teams behind. Teams are ok, but a formal list of app maintainers would be very useful.

That's exactly what I was thinking, THX @roigcarlo

**Comment by dcagri** [comment]
Good morning!
I think this is a very good idea. Moreover, having this list will ensure that everyone on that list will be informed in case there will be a change in the application.

**Comment by dcagri** [comment]
So how do we proceed?

**Comment by armingeiser** [comment]
That means improving the [CODEOWNERS](https://github.com/KratosMultiphysics/Kratos/blob/master/.github/CODEOWNERS) file and adding missing Teams? I also think that a list somewhere in the WIKI will become outdated soon. Maybe we could also just link to this codeowners file?

**Comment by AlejandroCornejo** [comment]
> 
> 
> That means improving the [CODEOWNERS](https://github.com/KratosMultiphysics/Kratos/blob/master/.github/CODEOWNERS) file and adding missing Teams? I also think that a list somewhere in the WIKI will become outdated soon. Maybe we could also just link to this codeowners file?

Yeah, I vote for updating and adding the maintainers of each App in this file and redirect to it in the wiki 👍

**Comment by philbucher** [comment]
Sounds good to me
This should be possible from a technical POV

**Comment by riccardotosi** [comment]
Then, should we [create new teams](https://github.com/orgs/KratosMultiphysics/teams) and add them to [CODEOWNERS](https://github.com/KratosMultiphysics/Kratos/blob/master/.github/CODEOWNERS)?

**Comment by philbucher** [comment]
But why new teams?
I thought individual devs

**Comment by riccardotosi** [comment]
I comment because in #7294, you commented
> Other applications are welcome to be added (with teams, not individual developers).

**Comment by philbucher** [comment]
> I comment because in #7294, you commented
> 
> > Other applications are welcome to be added (with teams, not individual developers).

ah sorry I confused myself once again
please go ahead as you said, aka create the missing teams and add them to the Codeowners

**Comment by philbucher** [comment]
ATTENTION:
Codeowners only works if the team has at least write permissions! 
see here: https://github.community/t/codeowners-works-with-users-but-not-teams/733

I tested it and can confirm that this is the case :)
