### ISSUE TITLE
[FSI] Orphaned (unconnected) nodes during trilinos model import

### ISSUE THREAD

**Issue by SamiBidier** [KratosMultiphysics/Kratos#7828]
I'm stumbling over unconnected nodes (see pull request #432) in my structural model when i'm trying to perform an mpi run.
`RuntimeError: Error: Invalid mesh: number of connected nodes = 7538, number of mesh nodes = 7546.`
I scripted trough the structural.mdpa to check, but couldn't identify nodes that do not belong to elements.

Does anyone have an idea how to identify those nodes or how to repair the model?

Model created with: GiD 15.0.1 (Kratos GiD Release 7.5.1)
MPI Kratos build with Releas 8.0.1

Help or Hints are kindly appreciated! Thx

**Comment by rubenzorrilla** [comment]
Hi @SamiBidier ! I assumed that the problem is solved.

Would you mind to briefly comment which was the issue? (it might be helpful for others in the future). Thanks!

**Comment by SamiBidier** [comment]
Hi @rubenzorrilla 
I found double nodes in the structural file. At first I thought it was an error on my modelling part, as I'm importing a lot of model data from rhino. However, it might also be a bug you could check. I'm computing a system where the solid encloses another part of the solid that has different structural properties and is thus within a separated group in GiD, where the two solid regions share 
 common surfaces, lines and points at their interfaces. It seems that all nodes generated by the GiD output writes those nodes twice within the structural.mdpa. 
Greetings!
