### ISSUE TITLE
[FSI] trilinos_partitioned_fsi_dirichlet_neumann_solver error due to missing dof for mesh_velocity at nodes

### ISSUE THREAD

**Issue by SamiBidier** [KratosMultiphysics/Kratos#7834]
**Description**

Hi,
I'm getting an error that I can't resolve when running a mpi job, due to a seemingly non-existing dof at nodes

` File "/apps/Kratos-8.0.1/bin/Release/KratosMultiphysics/FSIApplication/trilinos_partitioned_fsi_dirichlet_neumann_solver.py", line 86, in _InitializeDirichletNeumannInterface                                                                                                                                                              KratosMultiphysics.VariableUtils().ApplyFixity(KratosMultiphysics.MESH_VELOCITY_X, True, fl_interface_submodelpart.Nodes)                                        RuntimeError: Error: Trying to fix/free dof of variable MESH_VELOCITY_X but this dof does not exist in node #72959!  `

The job was created with GiD15/kratos8.0.1 
Any ideas, maybe @rubenzorrilla again?
Thanks!

**Environment**

OS: CentOS 7
Branch: Releas 8.0.1
Python 3.6.8

**Comment by rubenzorrilla** [comment]
Hey all! After a short meeting with @SamiBidier we are on it!

**Comment by rubenzorrilla** [comment]
@SamiBidier #7850 fixes this.
