### ISSUE TITLE
[KratosCore] Kernel() constructor

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#7874]
**Description**
Owing to the `Kernel()` constructor, more than one kernel can be created #7863.

**Scope**
- KratosCore

**Expected behavior**
Take out the default false from the current constructor and add a default constructor to have the correct behaviour. The implementation should also add the false default value to the static initialization.

**Comment by roigcarlo** [comment]
After looking at it. 

We cannot initialize it directly in the class header, but its already set in the source (https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/sources/kernel.cpp#L156), so just removing  the default parameter from the constructor will suffice.

**Comment by roigcarlo** [comment]
Fixed in #7875 can you review?
