### ISSUE TITLE
[EmbeddedSkinVisualizationProcess] output of visualization_model_part MPI

### ISSUE THREAD

**Issue by frawahl** [KratosMultiphysics/Kratos#7876]
**Description**
When running a simulation with MPI and using an GiD or VTK output process for the skin visualization model part, only Rank 0 is written and therefore only a section of the mesh. 

**Scope**
- Embedded Navier Stokes Discontinuous
- Output of EmbeddedSkinVisualizationProcess

**To Reproduce**
- Use `embedded_symbolic_navier_stokes_discontinuous` as element_type
- Add `ApplyEmbeddedSkinVisualizationProcess` in your ProjectParameters to have a visualization_model_part,( e.g. "visualization_variables": ["VELOCITY","PRESSURE"])
- Add a `GiDOutputProcess` for the visualization model part
- Run a couple of time steps (more than output_interval of GiDOutputProcess)

**Expected behavior**
The whole mesh of the visualization model part should be written by the output process.

**Environment**
- OS: Linux
- Branch: master
- Python 3.6

**Comment by philbucher** [comment]
This only confirms what I wrote in the other issue, the ModelPart seems not to be distributed

**Comment by rubenzorrilla** [comment]
Completely agree. Closing this issue as the underlying problem is the same as that one in #7878.
