### ISSUE TITLE
[Core] PointOutputProcess is not an output process (no IsOutputStep nor PrintOutput)

### ISSUE THREAD

**Issue by frawahl** [KratosMultiphysics/Kratos#7877]
**Description**
An update of the visualization_variables of elements, which are cut, of the visualization_model_part does not seem to happen every time step. E.g. if a PointOutputProcess (or one of the derived classes) creates output every time step for a cut element, the values in the output file of the PointOutputProcess won't change for a certain number of time steps (often until a GiD or VTK Output of the visualization model part happens). The output of works for the standard FluidModelPart.fluid_computational_model_part.

**Scope**
- EmbeddedSkinVisualizationProcess

**To Reproduce**
- Use `embedded_symbolic_navier_stokes_discontinuous` as element_type
- Add `ApplyEmbeddedSkinVisualizationProcess` in your ProjectParameters to have a visualization_model_part,( e.g. "visualization_variables": ["VELOCITY","PRESSURE"])
- Add a `PointOutputProcess` using the visualization_model_part for a point in an element, which is cut (e.g. "output_variables": [ "PRESSURE"])
- Add a `GiDOutputProcess`, which output_interval is bigger than 1 (e.g. "nodal_results"       : ["VELOCITY","PRESSURE"])
- Run a couple of time steps (more that output_interval of your GiDOutputProcess)
example see [visOutput.zip](https://github.com/KratosMultiphysics/Kratos/files/5599021/visOutput.zip) --> first output point of the LineOutputProcess is a cut element, the remaining points not

**Expected behavior**
The files created by a PointOutputProcess writes updated results for every time step, including elements, which are cut.

**Environment**
- OS: Ubuntu 20.04.1
- Branch: master
- Python 3.7.4

**Comment by rubenzorrilla** [comment]
The `EmbeddedSkinVisualizationProcess` updates the variable values within the `ExecuteBeforeOutputStep` method. This means that these are only updated when the `IsOutputStep` of the output process is called. This is intentionally done to avoid the overhead of updating the output values when these are not to be printed.

The poblem in here is that the `PointOutputProcess` does not behave as an output process (even though it is). IMO, the problem in here is the `PointOutputProcess` which behaves as an standard process, not as an output one. Long story short, this process should be placed in the output processes list in the json an then implement the `IsOutputStep`. Then the `AnalysisStage` would call the `ExecuteBeforeOutputStep` of the visualization process to update the values.

Now I bring back the old discussion about having an intermediate `OutputProcess` layer (OFC deriving from the base `Process`) implemented in an `output_process.h`to define the API for output-related processes.

**Comment by rubenzorrilla** [comment]
(@frawahl I changed the issue tittle to better describe the situation. I hope you don't mind.)

**Comment by philbucher** [comment]
In short:
This has historical reasons.
Changing it should be done IMO but it will break every single usage

**Comment by mpentek** [comment]
@frawahl " the values in the output file of the PointOutputProcess won't change for a certain number of time steps"

Apart from the discussion above, might it be that you observe the behavior above in MPI? Now this might be cause how writing out is handles by the [`time_based_ascii_file_writer_utility`](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/time_based_ascii_file_writer_utility.py), specifically the setting `"write_buffer_size"`. For OpenMP it will automatically write out at every time step, for MPI this will happen is you set the value to 1. The problem is that this buffer size is to be related to the data size and not the time step.

See also [how python flushes text to a file](https://stackoverflow.com/questions/3167494/how-often-does-python-flush-to-a-file).

I have a similar issues as I like to see intermediate results and with MPI I am force flushing, which is a temporary solution.

**Comment by frawahl** [comment]
The problem exists in MPI as well, but also in OpenMP.
I think @rubenzorrilla is right with his analysis: The issue is not that no output is written, the issue is that outdated output is written, as `EmbeddedSkinVisualizationProcess` will only update the variable values, if `IsOutputStep` of an (associated?) output process is called.

**Comment by rubenzorrilla** [comment]
> The problem exists in MPI as well, but also in OpenMP.
> I think @rubenzorrilla is right with his analysis: The issue is not that no output is written, the issue is that outdated output is written, as `EmbeddedSkinVisualizationProcess` will only update the variable values, if `IsOutputStep` of an (associated?) output process is called.

Yes, long story short the problem is that the `PointOutputProcess` API doesn't match that one expected for an output process.

**Comment by mpentek** [comment]
I am not sure about the solution, but I am sure that other processes are also probably affected or should be considered, as these are typically piled into the auxiliary process list, although these are clearly output processes (such as drag, HDF output and so on).

**Comment by rubenzorrilla** [comment]
As a rule of thumb, I'd take that any process that outputs to a file needs to implement such `IsOutputStep`-like functionalities. If there is no output to file, but only value postprocessing, then it should be a process.

**Comment by rubenzorrilla** [comment]
After a brief discussion, @KratosMultiphysics/technical-committee agrees that any process outputting information must derive from the `OutputProcess` in order to avoid the inconsistencies reported in here.

**Comment by philbucher** [comment]
in order to easy the transition, I would manually check if output was written, and if not warn the user that the process might not be added to `output_processes`

**Comment by philbucher** [comment]
so now we can easily do the transition thanks to #9529 :tada:
