### ISSUE TITLE
[EmbeddedSkinVisualizationProcess] MPI PointOutputProcess of points in visualization model part called #cores times

### ISSUE THREAD

**Issue by frawahl** [KratosMultiphysics/Kratos#7878]
**Description**
When running an embedded MPI simulation with a point output (or derived classes) of a point in the skin visualization model part, several things happen, that do not happen for a fluid_computational_model_part:

- if 28 cores/ processes are used, there are 27 warnings, that the point was not found
- if the output is supposed to be written to a directory, that does not exist before starting the simulation, there are error messages, because processes try to create that directory, although one process already created it
- the output file will be overwritten 27 times, so that there is an extremely high probability that the last process that writes is a process that could not find the element, so no useful output is created (element id -1 and values 0.0)

**Bypassing the problem**
--> the last problem can be eliminated by a simple change in the PointOutputProcess, so that a process doesn't write a file at all, when it hasn't found a matching element.
--> In case the directory is created in advance and the above change is done in point_output_process.py useful output is written.

**Scope**
- EmbeddedSkinVisualizationProcess
- PointOutputProcess

**To Reproduce**
- embedded simulation with MPI
- a EmbeddedSkinVisualizationProcess to create a visualization model part
- a PointOutputProcess of a point of the visualization model part
see [visOutputMPI.zip](https://github.com/KratosMultiphysics/Kratos/files/5599109/visOutputMPI.zip)

**Expected behavior**
No warnings and no need to prevent point output file of skin visualization model part from being overwritten and no need to create output directory in advance.

**Environment**
- OS: Linux Cluster
- Branch: master
- Python 3.6

**Comment by philbucher** [comment]
Sounds to me like the skin MP is not distributed
@rubenzorrilla can you confirm?

@frawahl can you check (simply call IsDistributed() on the Modelpart)

**Comment by frawahl** [comment]
When I output IsDistributed() from the gid_output_process, I get 28 times, that it is NOT distributed.

**Comment by philbucher** [comment]
then you have your problem :)

BTW in MPI you should use the distributed_gid_output_process

**Comment by frawahl** [comment]
> then you have your problem :)
> 
> BTW in MPI you should use the distributed_gid_output_process

It threw an error when I called the distributed one directly and it's called automatically by GiDOutputProcess if the ModelPart is distributed...
