### ISSUE TITLE
Adding a ConcurrentQueue implementation to kratos

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#7893]
**Description**
Over the last years i have encountered quite often the problem of having to store unordered output which is being produced in parallel (for cases in which the order does not matter).

A possible solution to this problem would be to use a concurrent_queue like this one:

i tried it out, and it looks very performant. 
I would be in favor of including the library in Kratos (it is headeronly, license is BSD or Boost), possibly with a tiny wrapper around it. **Opinions?**

https://github.com/cameron314/concurrentqueue

Here goes the code that i used to verify it suits. I have not checked it out in windows for the moment, however it is c++11 conformant so it should hopefully  work without problems

here goes my testing code

~~~cpp
#include <vector>
#include <iostream>
#include <chrono>
#include "concurrentqueue/concurrentqueue.h"
#include "omp.h"

int main() {
    
    std::cout << " n threads = " << omp_get_max_threads() << std::endl;    

    std::size_t total_items = 100e6;
    std::size_t nitems = total_items/omp_get_max_threads(); //items per thread
    moodycamel::ConcurrentQueue<std::size_t> q;
    
    std::size_t expected_sum=0;

    auto start = std::chrono::system_clock::now();
    #pragma omp parallel
    {
        std::size_t ithread=omp_get_num_threads();

        #pragma omp atomic
        expected_sum += nitems*ithread;

        for(std::size_t i=0; i<nitems; ++i)
            q.enqueue(ithread);
    }
    auto stop = std::chrono::system_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(stop - start).count();
    std::cout << "enqueuing time = " << elapsed << std::endl;
    std::cout << "expected sum = " << expected_sum << std::endl;

    start = std::chrono::system_clock::now();
    std::vector<std::size_t> all;
    all.reserve(q.size_approx());
    bool found = true;
    while(found)
    {
        std::size_t item;
        found = q.try_dequeue(item);
        if(found)
            all.push_back(item);
    }
    stop = std::chrono::system_clock::now();
    elapsed = std::chrono::duration_cast<std::chrono::milliseconds>(stop - start).count();
    std::cout << "push_back time = " << elapsed << std::endl;

    std::size_t sum = 0;
    for(auto item : all)
        sum += item;
    std::cout << "obtained sum = " << sum << std::endl;

    assert(sum == expected_sum);

    return 0;
}
~~~

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee understands the use cases and need for such a tool

Meanwhile, the effectiveness of it should be verified with Intel and MSVC compilers by running the above example in many threads.

About the wrapper, we consider this very simple interface which can be used without a wrapper like standard libraries.

**Comment by RiccardoRossi** [comment]
@sunethwarna you have a usecase for this in the PointerCommunicator

**Comment by sunethwarna** [comment]
@RiccardoRossi Yes I have one use case, I'll create a PR for that use case and refer hear.

**Comment by philbucher** [comment]
Closing as it is merged
