### ISSUE TITLE
Problems compiling in windows

### ISSUE THREAD

**Issue by philipkalkbrenner** [KratosMultiphysics/Kratos#7907]
I am having some errors while compiling Kratos on windows. The error message is below. It is in german. Could somebody help me please? thx

![compile_error](https://user-images.githubusercontent.com/35221607/100763238-2ffc4c80-33f5-11eb-855f-6b6512a43a62.PNG)

**Comment by roigcarlo** [comment]
Dear @philipkalkbrenner, could you post a full log of the error? 

Also, could yo tell me which version of Visual Studio are you using?

**Comment by philipkalkbrenner** [comment]
Hi @roigcarlo,
thanks for your reply, I am using 2017 version
here is the beginning of the log file. (I had to start compiling again to be able to plot it) I hope it is enough for now?
[files_for_issue.zip](https://github.com/KratosMultiphysics/Kratos/files/5623944/files_for_issue.zip)

**Comment by roigcarlo** [comment]
Hi, yep that's enough thx

For the log it appears that you are using a quite old version of the compiler, you will need at least 15.7 2017 to compile Kratos and it appears that you have one of the firsts SP of 2017 (a version from before April 26, 2018).

Would it be posible for you to update your current Visual Studio or install the 2019 version?

**Comment by philipkalkbrenner** [comment]
ok, I will install the 2019 version. Then I will let you know. Thanks!

**Comment by philipkalkbrenner** [comment]
HI @roigcarlo 
same error occurs. any idea? Again the files, I also send you the configure.bat
[files_for_issue.zip](https://github.com/KratosMultiphysics/Kratos/files/5624419/files_for_issue.zip)

**Comment by roigcarlo** [comment]
Ho that's different :), you will have to upgrade Cmake to 3.14 so it can detect the new VS version

**Comment by philipkalkbrenner** [comment]
it seems to work, but I don't know how to add the InstallPrefix direction to the configure.bat, I used to do that in the "old" configure.bat format. Could you please tell me which line to put?

**Comment by roigcarlo** [comment]
Hi @philipkalkbrenner glad it works!

If you want a custom installPrefix you can use the standard cmake `-DCMAKE_INSTALL_PREFIX=[your/path/here]`. If you do not specify anything it will install it in `Kratos/bin/[BuildMode]` automatically

**Comment by philipkalkbrenner** [comment]
Ok. The current (in the master) version of kratos is version 8, right?  so if I add the corresponding PATH and PYTHONPATH, I should see the logo of version 8 right?

**Comment by philipkalkbrenner** [comment]
I just do not know how to jump from one version to the other in case I have 2 different versions installed.

**Comment by roigcarlo** [comment]
> if I add the corresponding PATH and PYTHONPATH, I should see the logo of version 8 right?

Exactly, Imagine that you have 

```
C:\Kratos\bin\Release
C:\Kratos\bin\Debug
C:\OldKratosInstall
```

Pointing the PYTHONPATH and PATH to any of those locations will change the version you are using. Following the example:
```
-- C:\Kratos\bin\Release --
set PYTHONPATH=C:\Kratos\bin\Release
set PATH=%PATH%;C:\Kratos\bin\Release\libs

 --C:\Kratos\bin\Debug --
set PYTHONPATH=C:\Kratos\bin\Debug
set PATH=%PATH%;C:\Kratos\bin\Debug\libs

 --C:\OldKratosInstall --
set PYTHONPATH=C:\OldKratosInstall
set PATH=%PATH%;C:\OldKratosInstall\libs
```

Also, if you want, you can copy paste the files inside this zip: [Launcher.zip](https://github.com/KratosMultiphysics/Kratos/files/5629819/Launcher.zip) in the install folder and run it using the `Kratos` shortcut (it will open a terminal) and calling it through the `kratos script.py` command. It will use the installation located in the folder you copied the files.

**Comment by roigcarlo** [comment]
> I should see the logo of version 8 right?
 
You most likely will see `9.0.Dev\SHA` as we internally use the number for the upcoming version

**Comment by philipkalkbrenner** [comment]
thanks a lot.
now I tried to use the files from the launcher folder and there the follwoing happens:
![grafik](https://user-images.githubusercontent.com/35221607/100889805-db6dd580-34b7-11eb-8d29-1fb72de33ec1.png)

the testing.py file only contains the line : from KratosMultiphysics import *

**Comment by philipkalkbrenner** [comment]
It is working! Thanks a lot!!!
