### ISSUE TITLE
Initialize- & FinalizeSolutionStep of LinearSolver seem not to be called

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#7923]
**Description**
See title

Not sure what the correct solution should be, see also the discussion in #1675

EDIT: as the LinearSolver is a member of `BuilderAndSolver` it should probably be called there
=> If this is cleaned up then we can probably remove `PerformSolutionStep` as `Solve` seems to do the same and is implemented in most solvers
Those are just my initial thoughts as reminders, maybe I missed sth

FYI @armingeiser

**Comment by armingeiser** [comment]
My understanding was that 

Solve:
* InitializeSolutionStep
* PerformSolutionStep
* FinalizeSolutionStep

This is at least how we have used it in https://github.com/KratosMultiphysics/Kratos/blob/ac77e5dfbc4a83ae797fb630b9db25e0f04b73e9/applications/LinearSolversApplication/custom_solvers/eigen_direct_solver.h#L130

Like this one can e.g. do the decomposition once and then solve for multiple RHSs.

**Comment by RiccardoRossi** [comment]
this would be very nice to have ... any volunteer?

**Comment by loumalouomega** [comment]
> this would be very nice to have ... any volunteer?
> 
> i mean... @KratosMultiphysics/technical-committee agrees :-)

what should be done?
