### ISSUE TITLE
Constitutive law

### ISSUE THREAD

**Issue by eliasganthaler** [KratosMultiphysics/Kratos#7962]
Dear all,

I want to simulate the compaction process of metal powder in sinter process. In doing so, I have to implement the constititutive law Drucker-Prager-Cap-Modell (DPC). What is the best way in implementing such a constitutive law?

**Comment by loumalouomega** [comment]
> Dear all,
> 
> I want to simulate the compaction process of metal powder in sinter process. In doing so, I have to implement the constititutive law Drucker-Prager-Cap-Modell (DPC). What is the best way in implementing such a constitutive law?

What do you mean?, do you want to implement it from scratch, or do you want to run a simulation with sucha a model?

**Comment by eliasganthaler** [comment]
Thanks for the quick answer,

I want to run a model, beeing able to simulate the compaction of metal powder using DPC as constitutive law. This process is characterised by its large deformation (~0.5).
Since this model is not yet implemented, I guess I have to implement it from scretch.

Best,
Elias

**Comment by loumalouomega** [comment]
Do you want to consider MPM or traditional FE?

**Comment by eliasganthaler** [comment]
My main goal is not only to simulate the compaction process itself but also to determine cracks/ areas with higher crack likelihood. Do you suggest to go for MPM?
I am worried about the computational cost and would therefore prefer using traditional FEM.

**Comment by AlejandroCornejo** [comment]
Hi @eliasganthaler , So you want to simulate a coupled DEM-FEM simulation in which the FEM exhibits  damage/fracturing?

**Comment by loumalouomega** [comment]
> Hi @eliasganthaler , So you want to simulate a coupled DEM-FEM simulation in which the FEM exhibits damage/fracturing?

I did not though about that, sorry @AlejandroCornejo, I let you guide @eliasganthaler

**Comment by eliasganthaler** [comment]
hi @AlejandroCornejo, yes exactly. 
My goal is to simulate the filling and compaction process.

**Comment by eliasganthaler** [comment]
In doing so I was thinking in a hirachical coupling between DEM and FEM using RVE (representative Volume of Element) in a prefined region of interest.

**Comment by AlejandroCornejo** [comment]
> In doing so I was thinking in a hirachical coupling between DEM and FEM using RVE (representative Volume of Element) in a prefined region of interest.

Hi again! In my thesis i have developed a coupled formulation between the FEM and the DEM (weak or strong coupling) in which the FEM part is able to fracture and experience large changes of topology and large displacements, maybe you'd be interested?

**Comment by eliasganthaler** [comment]
Hi Alejandro,

sounds great! Where can I find your thesis online?

Best,
Elias

**Comment by vryy** [comment]
Elias,

The DP is simple to implement but it will be trickier if the cap is involved. And the shape of the cap depends on the type of application. Do you need to cap on the compression side, or cap on the tension side, or both? A good reference is the Drucker-Prager model with cap in Abaqus:

https://abaqus-docs.mit.edu/2017/English/SIMACAEMATRefMap/simamat-c-capplastic.htm

If you like to experiment if DPWC is the right choice for your application, you can try to run some simple tests in Abaqus first. Then thinking about further implementation will have a better background.

**Comment by eliasganthaler** [comment]
Hi vryy,
thank you for your answer and the link. 

I would need to cap on the compression side. 

Best,
Elias

**Comment by AlejandroCornejo** [comment]
> 
> 
> Hi Alejandro,
> 
> sounds great! Where can I find your thesis online?
> 
> Best,
> Elias

Hi! I'll send it to you as soon as I defend it :D (1 week). Regards

**Comment by eliasganthaler** [comment]
Thank you very much and all the best for your defense.

Best,
Elias

**Comment by rubenzorrilla** [comment]
Closing as it seems to be inactive.
