### ISSUE TITLE
Change logo of the project

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#8]
Just that

**Comment by pooyan-dadvand** [comment]
That's a good idea. I think at least we should refresh its look. I will talk with Laura.

**Comment by loumalouomega** [comment]
Do you mean to create a new logo?

**Comment by loumalouomega** [comment]
I can design it, I am good with that

**Comment by pooyan-dadvand** [comment]
Of course any suggestion is welcomed!! I just wanted to refresh the existing one (changing the style or color) to make it look more modern.

**Comment by loumalouomega** [comment]
I will present some ideas

**Comment by rubenzorrilla** [comment]
@loumalouomega We're looking forward to see your designs!

**Comment by loumalouomega** [comment]
@rubenzorrilla I will start as soon I arrive home

**Comment by loumalouomega** [comment]
![](https://i.imgur.com/8HWyfQV.jpg) 

Just one try with Mathematica, now I am going to try with a Helmet

**Comment by pooyan-dadvand** [comment]
I miss a whatsapp emoji here. The one with two wide open eyes!! :-D

**Comment by roigcarlo** [comment]
:eyes: ( @rubenzorrilla  suggested :hankey: )

**Comment by loumalouomega** [comment]
A new idea:

![](https://i.imgur.com/H60FC64.jpg)

**Comment by maceligueta** [comment]
????

**Comment by loumalouomega** [comment]
It is a tessellation of a spartan helmet, just an idea

**Comment by pooyan-dadvand** [comment]
@loumalouomega I think you may need a line search to converge!! :-D 

I would go for something very iconic and to be used as a very small icon without losing too much details

**Comment by loumalouomega** [comment]
I did a Mathematica code to generate Kratos Logos (old style)

![](https://i.imgur.com/BmQnRl8.png) 

You can generate your own, I generate a [CDF](https://www.wolfram.com/cdf-player/) , this way you don't need to install all Mathematica. The [link](https://dl.dropboxusercontent.com/u/11225823/kratos_logo.cdf)

**Comment by loumalouomega** [comment]
I updated the logo generator with more options

**Comment by loumalouomega** [comment]
Maybe we can close this, except if nobody have a proposition
