### ISSUE TITLE
Jacobian determinant computation in some geometries

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#80]
Dear all,

Implementing an utility for the FSI application I noted the lack a DeterminantOfJacobian() method in these geometries:

- line_2d.h
- line_2d_2.h
- line_2d_3.h
- line_3d_3.h
- triangle_3d_3.h

In these geometries what this DeterminantOfJacobian() method does it to turn an error complaining about the fact that the Jacobian matrix is not squared-shaped. Is there any reason to keep these methods as they are? In my opinion, it could be very useful to extend what is done in the line_3d_2.h geometry since these Jacobian "determinant" values are known

virtual Vector& DeterminantOfJacobian( Vector& rResult, IntegrationMethod ThisMethod ) const
{
    rResult = ZeroVector( 1 );
    rResult[0] = 0.5 * MathUtils<double>::Norm3(( this->GetPoint( 1 ) ) - ( this->GetPoint( 0 ) ) );
    return rResult;
}

If you agree to do that, I would do the implementations.

Regards.

**Comment by loumalouomega** [comment]
The Jacobian is not square, you need to do what I do for contact, which is compute a generalized determinant, in this case sqrt(prod(trans(J),J))

**Comment by loumalouomega** [comment]
https://math.stackexchange.com/questions/854180/determinant-of-a-non-square-matrix

**Comment by loumalouomega** [comment]
We can implement this in #79 , due to the fact we already modified the geometries, this way the push request will be the same

**Comment by rubenzorrilla** [comment]
@loumalouomega for those cases in where the Jacobian is constant and known in the whole element it makes no sense to me to compute the generalized determinant. In my opinion the best approach would be to compute the generalized determinant only in the base class method (for those other elements with "unknown" Jacobian determinant).

**Comment by loumalouomega** [comment]
@rubenzorrilla This is solved in the #109

**Comment by RiccardoRossi** [comment]
sorry but #109 is not an acceptable solution (see review). We are in the process of discussing this issue, and we are not through...

**Comment by MassimoPetracca** [comment]
Dear all,
I found the same issue while working on shell elements. We have non-square jacobian matrices for all structural elements (beams and shells) where the geometry local dimension is not equal to the spatial dimension (i.e. lines (1D geometry) in 2D and 3D space, and surfaces (2D geometry) in 3D space). 
I would suggest the following approach, based on the geometrical meaning of the jacobian in those geometries:

```c++
// pseudo-code
if(jacobian.rows() != jacobian.columns()) {
    if (jacobian.columns() == 1) { 
        // a column vector (2x1 in 2D or 3x1 in 3D)
        detJ = norm(jacobian);
    }
    else if(jacobian.columns() == 2) { 
        // a 3x2 matrix in 3D (2 vectors defining the tangent plane to the surface)
        detJ = norm( cross_prod( jacobian.column(0), jacobian.column(1) ) );
    }
}
else {
    // standard continuum elements 2D or 3D
    detJ = det(jacobian);
}
```

This can be either implemented in the base class, or in the derived classes. I would prefer doing it in the derived classes, so that for each case we can do proper optimizations.

**Comment by rubenzorrilla** [comment]
Done in  #145.
