### ISSUE TITLE
Error compiling Kratos with gcc 10.2.0 version

### ISSUE THREAD

**Issue by uxuech** [KratosMultiphysics/Kratos#8001]
Hi everyone!

I have sincronized Kratos **master branch** today and when I was compiling it I got compilation error. I am using _gcc_ version **10.2.0** in Ubuntu **20.10.**

**Error type**
` g++: fatal error: killed signal terminated program cciplus`

I would appreciate if anyone can check it.
Thank you 
Uxue

**Comment by philbucher** [comment]
Hi @uxuech 
Could you please post the entire log and your configure file?

**Comment by ddemidov** [comment]
Looks like the compiler ran out of memory.

**Comment by roigcarlo** [comment]
Seems to be ok now, closing
