### ISSUE TITLE
Problem Running a Potential Flow Problem from GiD

### ISSUE THREAD

**Issue by inigolcanalejo** [KratosMultiphysics/Kratos#801]
Hi all,

I am encountering the following problem when I try to run a potential flow problem from GiD gid13.1.8d-x64:

Process 'naca0012' has finished with errors: /home/inigo/software/gid13.1.8d-x64/./problemtypes/kratos.gid/exec/Kratos/runkratos: can't open file 'MainKratos.py': [Errno 2] No such file or directory

For some reason GiD does not generate the MainKratos.py. This is what appears in the Info Window:

[InfoWindow](https://syncandshare.lrz.de/dl/fiDNzmvUdpmnXVwApMWTEW97/infoWindow.png?inline)

However, I can run examples using the usual fluid problemType. I have also tried using gid13.1.7d-x64 and I find the same problem.

Did someone ever have this problem and/or knows how to solve it?

Thanks a lot in advance.

P.S.

This are the steps I followed in order to install GiD:
- Install GiD -> Developer version
- Navigate to GiD's problemtype folder and delete kratos.gid
- Create there a link to our kratos.gid
- Navigate to kratos.gid/exec/
- Create there a symbolic link to the kratos installation folder (where runkratos is located)
    Unix : ln -s ~/Kratos Kratos

**Comment by loumalouomega** [comment]
Problems related with the interface to the interface->https://github.com/KratosMultiphysics/GiDInterface

**Comment by loumalouomega** [comment]
Possible problems:

* You need to mesh before lunch the problem

I am out of ideas @jginternational

**Comment by jginternational** [comment]
So @inigolcanalejo , I understand that you are using the current developer version of the problemtype, located where @loumalouomega has said. 

I've seen some "old variables". Let me fix it

**Comment by jginternational** [comment]
@inigolcanalejo Can you try it? (master branch)

**Comment by inigolcanalejo** [comment]
@jginternational  and @loumalouomega thank you very much for your quick answers and your help. I will try it now again and let you know if it works.

**Comment by inigolcanalejo** [comment]
@jginternational and @loumalouomega it works! We are trying to develop a sensitivity analysis for the potential flow and we need GiD to generate new geometries and meshes. Thanks a lot for your support!

**Comment by jginternational** [comment]
Hoorray!

**Comment by loumalouomega** [comment]
@inigolcanalejo If you are interested in remeshing contact me

**Comment by loumalouomega** [comment]
Can we close this?
