### ISSUE TITLE
Midpoint values in shock_capturing_process.h

### ISSUE THREAD

**Issue by pau-mar** [KratosMultiphysics/Kratos#8011]
When computing shock sensors for shock capturing methods, the following variable in line 285 of shock_capturing_process.h

midpoint_tot_ener = 0.5 * midpoint_rho * inner_prod(r_midpoint_v, r_midpoint_v)

happens to be zero when the velocity vector r_midpoint_v is null and there is not a Thermally Coupled Formulation. In such a case the critical temperature used to compute the critical sound velocity is zero and therefore the c_star becomes NaN. Two options are possible:
(1) Avoid having elements with all nodes on the boundary.
(2) Add an extra energy term with the pressure to avoid it being zero. This is a better option since velocity could be zero even if (1) is true.

**Comment by rubenzorrilla** [comment]
Going for (2). Indeed the current version is not completely correct as we are omitting the pressure in the isothermal version of the process. We should also consider the null energy value for the zero initial condition case (which is valid in the incompressible framework).
