### ISSUE TITLE
FluidDynamicsApplication tests failing in CI

### ISSUE THREAD

**Issue by riccardotosi** [KratosMultiphysics/Kratos#8017]
**Description**
In PR #8016, which is a PR completely unrelated with respect to the FluidDynamicsApplication, FluidDynamicsApplication tests failed:
```bash
............../__w/Kratos/Kratos/bin/Custom/applications//FluidDynamicsApplication/tests/test_FluidDynamicsApplication.py
Error: : Tests for FluidDynamicsApplication took too long. Process Killed.
Completed FluidDynamicsApplication tests with exit code 1!
```

I tag @KratosMultiphysics/fluid-maintainers.

**Scope**
Where in Kratos is this bug happening. 
- FluidDynamicsApplication

**To Reproduce**
Should be enough to open a pull request.

**Expected behavior**
CI to pass correctly, since #8016 is unrelated with respect to the FluidDynamicsApplication.

**Environment**
CI environment. The test failed in "CI / ubuntu (Custom, gcc) (pull_request)".

**Comment by marcnunezc** [comment]
Since it is complaining about running out of time, it might have just been an unlucky  run of the tests (like github machines being temporarily slower for some reason?)

**Comment by riccardotosi** [comment]
Yes I believe the same, however I thought it was worth reporting.

**Comment by riccardotosi** [comment]
It happened again in #7973.
![Cattura](https://user-images.githubusercontent.com/43809717/102880039-04481180-444b-11eb-8be3-5286c693c571.PNG)

**Comment by marcnunezc** [comment]
It also happened in #8021 , this time with the DEMApp.

![image](https://user-images.githubusercontent.com/32136457/102888971-0ebdd780-445a-11eb-84fa-0ae4499afc86.png)


@philbucher  do you think this might have to do with the timing changes you did recently?

**Comment by philbucher** [comment]
Did I do timing changes recently?
Don’t think so. Can you point to what you are referring to?
In my experience many test suites are at the time limit for a while already. So if for some reason the machines are a bit slower than usual the tests fail
Btw I think github was updating some stuff recently, might be related. In any case we should keep a close eye

recently I added support for timing in the tests, that way one can discover super easily the slow tests

**Comment by marcnunezc** [comment]
> recently I added support for timing in the tests, that way one can discover super easily the slow tests

Sorry, I was referring to this, in #7818. I see it is not something affecting the CI.

**Comment by rubenzorrilla** [comment]
Just mentioning that I'm on it right now.

**Comment by philbucher** [comment]
> > recently I added support for timing in the tests, that way one can discover super easily the slow tests
> 
> Sorry, I was referring to this, in #7818. I see it is not something affecting the CI.

Ah ok thats what you meant
This is only a minor improvements  with which you can find the slowest tests in a test suite (as I mentioned above)

**Comment by rubenzorrilla** [comment]
The adjoint sensitivity test and the manufactured solution tests are taking around the 50% of the total time in my machine (around 25% and 25%). The manufactured solution test can be moved without any doubt to the validation suite. 

@sunethwarna If you consider that it is impossible to make it faster, IMO we should do so with the sensitivity one.

**Comment by sunethwarna** [comment]
I'll try to make it faster, if not I will move it to validation suite today :)

**Comment by riccardotosi** [comment]
Hi all, in #8075 this issue arose again:

![Screenshot from 2021-01-14 15-10-22](https://user-images.githubusercontent.com/43809717/104601688-d08f8e80-567a-11eb-8abb-6740a6c2d094.png)

**Comment by rubenzorrilla** [comment]
It's strange... The amount and size of the tests hasn't changed during these weeks... Is it recursively happening? (the rest of PR seem to be fine).

**Comment by philbucher** [comment]
I also noticed the same, happens randomly
not as often as before but it still happens

**Comment by riccardotosi** [comment]
It only happened once to me.
