### ISSUE TITLE
Join SLACK of KratosMultiphysics

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#802]
Anyone with @cimne.​upc.​edu or @tum.​de email address can join the KRATOS workspace on Slack.

https://join.slack.com/t/kratosmultiphysics/signup

**Comment by pooyan-dadvand** [comment]
:+1:

**Comment by RiccardoRossi** [comment]
can we close this? instead we could put the link in the wiki

**Comment by loumalouomega** [comment]
Okay
