### ISSUE TITLE
Reducing compile times in travis

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#803]
Following the discussion in #722, 

I have yet to understand how stages work, but in the meantime I have found an alternative that could help reducing the compile times in travis while helping to get errors that usually doesn't show in normal compilation time. 

The idea is to follow a technique called unity build. You can find an example here: https://cheind.wordpress.com/2009/12/10/reducing-compilation-time-unity-builds/

What does this do?
Basically it merges several *.cpp in a unique ub_foo.cpp file. This reduces the stress on the disk while including and traversing the headers. This technique has also the advantage of pointing out possible code issues that usually are hard to detect since each cpp constitutes its own compilation unit, for example functions / variables with the same name in the same namespace (spoiler: some of them arose in kratos while I was testing it)

Of course, it also has drawbacks: As the build is unified it implies higher memory usage and we lose the advantage of iterative builds. (that won't happen in travis most of the time as we use ccache on top). Finally, parallelism in builds is harder to achieve, but also not a big deal with travis as it only has 2 processors. Also, the gain will be hardly diminished if travis hardware makes use of high-end SSD, as UB attacks mostly disk performance.

Some initial numbers showing the compile time with 1 core and a very basic ub setup (Release, -03, usual flags):

|  | KratosCore  | Kratos |
| ------------- | ------------- | ------------- |
| Unified   | 78.58s  | 266.75s  |
| Regular  | 230.39s  | 470.71s  |

Would this fit us? I can make a test-branch if you give me green light and see the results. Its implementation is quite straight forward and both the fast and the regular builds can coexist in peace.

**Comment by philbucher** [comment]
Sounds like a good solution for travis if it is for the purpose of getting the compile times down.

The numbers you showed are from your machine?

**Comment by roigcarlo** [comment]
Yep, numbers are from my machine

**Comment by pooyan-dadvand** [comment]
I agree with using this ONLY in Travis. Nevertheless this leads to the fact that we should group our headers in some module headers.
