### ISSUE TITLE
[Windows] Compilation ERROR

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#8030]
Hi all,

I've updated the master and some errors arised:

test_nurbs_curve.obj : error LNK2001: sÝmbolo externo "public: virtual void __cdecl Kratos::ConstitutiveLaw::CalculateMaterialResponse(class boost::numeric::ublas::vector<double,class boost::numeric::ub
las::unbounded_array<double,class std::allocator<double> > > const &,class boost::numeric::ublas::matrix<double,struct boost::numeric::ublas::basic_row_major<unsigned __int64,__int64>,class boost::numer
ic::ublas::unbounded_array<double,class std::allocator<double> > > const &,class boost::numeric::ublas::vector<double,class boost::numeric::ublas::unbounded_array<double,class std::allocator<double> > >
 &,class boost::numeric::ublas::matrix<double,struct boost::numeric::ublas::basic_row_major<unsigned __int64,__int64>,class boost::numeric::ublas::unbounded_array<double,class std::allocator<double> > >
 &,class Kratos::ProcessInfo const &,class Kratos::Properties const &,class Kratos::Geometry<class Kratos::Node<3,class Kratos::Dof<double> > > const &,class boost::numeric::ublas::vector<double,class b
oost::numeric::ublas::unbounded_array<double,class std::allocator<double> > > const &,bool,int,bool)" (?CalculateMaterialResponse@ConstitutiveLaw@Kratos@@UEAAXAEBV?$vector@NV?$unbounded_array@NV?$alloca
tor@N@std@@@ublas@numeric@boost@@@ublas@numeric@boost@@AEBV?$matrix@NU?$basic_row_major@_K_J@ublas@numeric@boost@@V?$unbounded_array@NV?$allocator@N@std@@@234@@456@AEAV3456@AEAV7456@AEBVProcessInfo@2@AE
BVProperties@2@AEBV?$Geometry@V?$Node@$02V?$Dof@N@Kratos@@@Kratos@@@2@0_NH7@Z) sin resolver [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\kratos\KratosCore.vcxproj]

mapping_variables.obj : error LNK2001: sÝmbolo externo "public: virtual void __cdecl Kratos::ConstitutiveLaw::CalculateMaterialResponse(class boost::numeric::ublas::vector<double,class boost::numeric::u
blas::unbounded_array<double,class std::allocator<double> > > const &,class boost::numeric::ublas::matrix<double,struct boost::numeric::ublas::basic_row_major<unsigned __int64,__int64>,class boost::nume
ric::ublas::unbounded_array<double,class std::allocator<double> > > const &,class boost::numeric::ublas::vector<double,class boost::numeric::ublas::unbounded_array<double,class std::allocator<double> >
> &,class boost::numeric::ublas::matrix<double,struct boost::numeric::ublas::basic_row_major<unsigned __int64,__int64>,class boost::numeric::ublas::unbounded_array<double,class std::allocator<double> >
> &,class Kratos::ProcessInfo const &,class Kratos::Properties const &,class Kratos::Geometry<class Kratos::Node<3,class Kratos::Dof<double> > > const &,class boost::numeric::ublas::vector<double,class
boost::numeric::ublas::unbounded_array<double,class std::allocator<double> > > const &,bool,int,bool)" (?CalculateMaterialResponse@ConstitutiveLaw@Kratos@@UEAAXAEBV?$vector@NV?$unbounded_array@NV?$alloc
ator@N@std@@@ublas@numeric@boost@@@ublas@numeric@boost@@AEBV?$matrix@NU?$basic_row_major@_K_J@ublas@numeric@boost@@V?$unbounded_array@NV?$allocator@N@std@@@234@@456@AEAV3456@AEAV7456@AEBVProcessInfo@2@A
EBVProperties@2@AEBV?$Geometry@V?$Node@$02V?$Dof@N@Kratos@@@Kratos@@@2@0_NH7@Z) sin resolver [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\kratos\KratosCore.vcxproj]

etc... Any ideas? thx

**Comment by RiccardoRossi** [comment]
vicente recemtly.removed something that was deprecated in the cl...maybe
that is the reason

**Comment by philbucher** [comment]
Have you tried a clean compilation?

**Comment by AlejandroCornejo** [comment]
> Have you tried a clean compilation?

Doing it just in case!!

**Comment by AlejandroCornejo** [comment]
> 
> 
> Have you tried a clean compilation?

As most of the cases you were right ;) now it compiles for some weird reason
