### ISSUE TITLE
Kratos for GiD 12

### ISSUE THREAD

**Issue by awa5114** [KratosMultiphysics/Kratos#804]
I only have a license for GiD 12. Is it possible to build Kratos from GiD 12? I was having trouble with this...

**Comment by jginternational** [comment]
If you mean to use the Kratos problemtype for GiD, it is not possible to use it with the 12 version. 

I recommend you to try a free 1 month  GiD 13 license here (you can get up to 3)
https://www.gidhome.com/purchase/passwords/?Licencetype=1&Periodtime=1

**Comment by pooyan-dadvand** [comment]
Just to add that the Kratos binaries comes in GiD are the latest. However you can not generate input file for it from GiD12 anymore......

**Comment by RiccardoRossi** [comment]
I thank thai would be closed
