### ISSUE TITLE
Installation or compilation error Kratos. GNU 10.2.0. Manjaro Linux.

### ISSUE THREAD

**Issue by SADPR** [KratosMultiphysics/Kratos#8043]
**Description**
I compiled Kratos today to check some small changes on a process and now it seems like it didn't compile correctly. This is the first time that happens to me.
------------------------------------------------------------------------------------------------------
 i.e.
from KratosMultiphysics import *
------------------------------------------------------------------------------------------------------
Exception has occurred: ModuleNotFoundError
No module named 'Kratos'
  File "/home/sebastianadpr/Kratos/bin/Release/KratosMultiphysics/__init__.py", line 18, in <module>
    from Kratos import *
------------------------------------------------------------------------------------------------------

I am using:
The C compiler identification is GNU 10.2.0
The CXX compiler identification is GNU 10.2.0

I have seen that other users had problems with GNU 10.2.0. 

------------------------------------------------------------------------------------------------------
My standard_configure.sh:
------------------------------------------------------------------------------------------------------
#!/bin/bash
# Please do not modify this script

# You can use your interpreter of choice (bash, sh, zsh, ...)

# For any question please contact with us in:
#   - https://github.com/KratosMultiphysics/Kratos

# Optional parameters:
# You can find a list will all the compiation options in INSTALL.md or here:
#   - https://github.com/KratosMultiphysics/Kratos/wiki/Compilation-options

# Function to add apps
add_app () {
    export KRATOS_APPLICATIONS="${KRATOS_APPLICATIONS}$1;"
}

# Set compiler
export CC=gcc
export CXX=g++

# Set variables
export KRATOS_SOURCE="${KRATOS_SOURCE:-"$( cd "$(dirname "$0")" ; pwd -P )"/..}"
export KRATOS_BUILD="${KRATOS_SOURCE}/build"
export KRATOS_APP_DIR="${KRATOS_SOURCE}/applications"
# export KRATOS_INSTALL_PYTHON_USING_LINKS=ON

# Set basic configuration
export KRATOS_BUILD_TYPE=${KRATOS_BUILD_TYPE:-"Release"}
export PYTHON_EXECUTABLE=${PYTHON_EXECUTABLE:-"/usr/bin/python3"}

# Set applications to compile
export KRATOS_APPLICATIONS=
add_app ${KRATOS_APP_DIR}/LinearSolversApplication
add_app ${KRATOS_APP_DIR}/StructuralMechanicsApplication

# Clean
clear
rm -rf "${KRATOS_BUILD}/${KRATOS_BUILD_TYPE}/cmake_install.cmake"
rm -rf "${KRATOS_BUILD}/${KRATOS_BUILD_TYPE}/CMakeCache.txt"
rm -rf "${KRATOS_BUILD}/${KRATOS_BUILD_TYPE}/CMakeFiles"

# Configure
cmake -H"${KRATOS_SOURCE}" -B"${KRATOS_BUILD}/${KRATOS_BUILD_TYPE}" -DUSE_MPI=OFF -DUSE_EIGEN_MKL=OFF

# Buid
cmake --build "${KRATOS_BUILD}/${KRATOS_BUILD_TYPE}" --target install -- -j$(nproc)

------------------------------------------------------------------------------------------------------
**Scope**
Where in Kratos is this bug happening. 
E.g.
- Compilation
- KratosCore

**Comment by sunethwarna** [comment]
I am also using Manjaro Linux with gcc 10.2.0, it is working for me.

**Comment by SADPR** [comment]
Thanks a lot @sunethwarnawith you configure file I was able to compile it correctly.
