### ISSUE TITLE
Runtime problems loading ExternalSolversApplication

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#8051]
**Description**
This is a recurrent problem in Windows, which has been experimented by me in the past, but also @salvalatorre a few months back, also @AlejandroCornejo  and many other people, as it can be found if you google "ExternalSolversApplication".
Usually, this gets solved by a phone call to @roigcarlo , who suspects what the problem may be, and recommends actions.
The specific problem I am facing is this:
```
  File "D:\kratos\bin\Release\KratosMultiphysics\ExternalSolversApplication\__init__.py", line 6, in <module>
    from KratosExternalSolversApplication import *
ImportError: DLL load failed: The specified module could not be found
```
As far as I remember, it can be solved adding a bunch of DLL's in the libs folder. But if you switch to another computer or simply delete the libs folder for a clean installation, you lose those DLL's and it is hard to remember where you got them from. 

**Request**
Is there any way we can get a robust compilation of the ExternalSolversApplication without requiring later, manual, action?

**Comment by philbucher** [comment]
I strongly recommend switching to the LinearSolversApplication
the ExternalSolversApp is implicitly deprecated

Is there any specific solver or other reason you are using it?

**Comment by AlejandroCornejo** [comment]
Imagine if it is problematic that I am not compiling it anymore... I'm using the `LinearSolversApplication`

**Comment by maceligueta** [comment]
Well, I just tried to run a case with the Structural Mechanics Application and it was importing the ExternalSolversApplication somehow...

**Comment by AlejandroCornejo** [comment]
> Well, I just tried to run a case with the Structural Mechanics Application and it was importing the ExternalSolversApplication somehow...

With the latests version of the GUI?? if you open the `MainKratos.py` you should remove the import ExternalSolversApplication

**Comment by philbucher** [comment]
> Well, I just tried to run a case with the Structural Mechanics Application and it was importing the ExternalSolversApplication somehow...

I changed this over 2.5 years ago :sweat_smile: https://github.com/KratosMultiphysics/GiDInterface/commit/4413be723795c0b7c9085ad077c9f1758ba4339c#diff-3ce4a8425bb869dfea19e8bd08015708e44e7f08d885ba14f9d09ec8b76b4698

**Comment by maceligueta** [comment]
Ok, I am afraid I had no clue about the implicit deprecation of the ExternalSolversApplication. And I was not even compiling it, actually, but somehow, the code reached this line:
https://github.com/KratosMultiphysics/Kratos/blob/8f752f360d973bf68d18695969055f453494ba17/kratos/python_scripts/python_linear_solver_factory.py#L41
When I saw that the ExternalSolversApplication was 'necessary' I added it to the compilation configure and the previously described problems appeared.
It's good to know that it is being substituted by LinearSolversApplication, but I wonder what made Kratos think I was preferring ExternalSolversApplication when I was not even compiling it. Probably leftovers of an ooold compilation.

**Comment by maceligueta** [comment]
I seems like this is solved by using LinearSolversApplication instead of ExternalSolversApplication. If none of them is compiled I am getting a crash. Maybe the Structural Mechanics App should require the LinearSolversApplication always. Anyways, this is an independent issue. Closing and thanks for the help @philbucher .

**Comment by philbucher** [comment]
> I seems like this is solved by using LinearSolversApplication instead of ExternalSolversApplication. If none of them is compiled I am getting a crash. Maybe the Structural Mechanics App should require the LinearSolversApplication always. Anyways, this is an independent issue. Closing and thanks for the help @philbucher .

Hm that is strange
I thought/hoped this would be bulletproof 😅
@maceligueta can you please share the error message and if possible your configuration?

**Comment by maceligueta** [comment]
Correction:  **it does not crash** (so not SegFault), it just stops. Sorry about the confusion.
If I delete all files starting with LinearSolversApplication*.* (3 files) from the libs folder, and also the ExternalSolversApplication*.* file, I get:
 ```
 File "D:\kratos\bin\Release\KratosMultiphysics\python_linear_solver_factory.py", line 39, in CreateFastestAvailableDirectLinearSolver
    from KratosMultiphysics import LinearSolversApplication
  File "D:\kratos\bin\Release\KratosMultiphysics\LinearSolversApplication\__init__.py", line 12, in <module>
    from KratosLinearSolversApplication import *
ModuleNotFoundError: No module named 'KratosLinearSolversApplication'
```
From GiD, what I first saw was this:
```
::[PythonSolver]:: : Finished reading model part. 
Read materials: Started
Read materials: Finished
::[MechanicalSolver]:: : Constitutive law was successfully imported. 
::[MechanicalSolver]::: ModelPart prepared for Solver. 
::[MechanicalSolver]:: : DOF's ADDED 
::[ImplicitMechanicalSolver]:: : DOF's ADDED 
[WARNING] VtkOutputProcess: 
[1;31m[DEPRECATED INPUT PARAMETERS] [0m'folder_name' is deprecated; use 'output_path' instead. 
[WARNING] VtkOutput: Modelpart "Structure" has both elements and conditions.
Giving precedence to elements and writing only elements!
::[MechanicalSolver]:: : Initializing ... 
::[MechanicalSolver]:: No linear solver was specified, using fastest available solver: 
KRATOS TERMINATED WITH ERROR
```
Which gives no warning messages and you don't know what to do unless you read the error window (code pasted above).

**Comment by philbucher** [comment]
ok thx
I think what is failing in your case is that you still have the python-files of the `LinearSolversApp` but you deleted the libs (hence the import fails)
we use [CheckIfApplicationsAvailable](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/kratos_utilities.py#L58-L62) in [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/python_scripts/python_linear_solver_factory.py#L38), which checks for `ApplicationName.py`, which I guess in your case is still available
can you check please?

**Comment by maceligueta** [comment]
That is correct, in the KratosMultiphysics folder there is a subfolder called `LinearSolversApplication`. If I delete this one (along with the libraries in `libs/`) it runs fine.

**Comment by maceligueta** [comment]
If the LinearSolversApplication is compiling and working well, maybe the StructuralApplication should require the LinearSolversApplication always.

**Comment by philbucher** [comment]
but why?
Lets say I want to use amgcl (which is in the Core) then I don't want/need to compile any other App

**Comment by maceligueta** [comment]
Forget it, I was thinking of a conversation with Riccardo where he said the difference in performance was very big when comparing core vs ExternalSolvers. Several years back. If this has changed, my comment makes no sense.

**Comment by philbucher** [comment]
ok then I guess we can close this :)

BTW another reason for not requiring the LinearSolversApp is bcs it cannot be used in MPI, there we currently use Trilinos Solvers
