### ISSUE TITLE
[core] How to detect if the Python version I am using is the same version used to compile Kratos

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#8061]
**Description**
Maybe this was discussed previously (I am not aware of it), but definitely keeps giving small problems to developers.
Provided a developer has different versions of Python3 (for a number of possible reasons), it can happen that Kratos is compiled against one of the versions but accidentally run with another one. In that case, the Kratos libraries might not be loadable. It happened today to @farrufat-cimne , who has Python 3.6.9 [GCC 8.4.0] on his PC but also Python 3.8.3 [GCC 7.3.0] included in Anaconda. For a  long while we suspected it might be the typical 'environment variables' problem, especially when trying to debug within VSCODE, but it wasn't.
Is there a way to identify this type of mismatch at runtime? Or give a helpful error to the developer, further than 'module could not be loaded'?
If it was a check, it should not use C++ at all, it should be callable from pure Python, like this:
https://github.com/KratosMultiphysics/Kratos/blob/bda2eb16bf21a786e7401a8c8cb7420e31c81fcb/kratos/python_interface/__init__.py#L5
The only idea that comes to my mind is to save a file with a certain signature at compile time, but that does not seem super robust and I think it is something we used to do for the Kratos Version and was discarded eventually.

**Comment by maceligueta** [comment]
I just found an interesting CMake command:
https://cmake.org/cmake/help/latest/command/configure_file.html
The Kratos `__init__.py` file can be configured from a template by CMake at compile time.

**Comment by loumalouomega** [comment]
In my personal experience the python macros of CMake can be troublesome, sometimes does not detect at all. For example I use the following to ensure that python3 is used:

~~~cmake
IF(NOT DEFINED PYTHON_EXECUTABLE)
  INCLUDE(FindPythonInterp)
  IF(NOT PYTHON_EXECUTABLE OR ${PYTHON_VERSION_MAJOR} LESS 3)
      SET(PYTHON_EXECUTABLE "python3")
  ENDIF(NOT PYTHON_EXECUTABLE OR ${PYTHON_VERSION_MAJOR} LESS 3)
ENDIF(NOT DEFINED PYTHON_EXECUTABLE)
~~~

**Comment by loumalouomega** [comment]
You can adapt it using also PYTHON_VERSION_MINOR

**Comment by maceligueta** [comment]
We could have a file called `__init__.py.template` containing the same as `__init__py` has now, but adding this:

```
if sys.version_info.major != ${PYTHON_VERSION_MAJOR} or sys.version_info.minor != ${PYTHON_VERSION_MINOR} or sys.version_info.micro != ${PYTHON_VERSION_MICRO}:
   raise Exception("Kratos is only compatible with the same version of Python it was compiled against")
```

CMake would substitute the values accordingly and the result could be saved as `__init__.py` in the build folder.

**Comment by loumalouomega** [comment]
There is a way to CMake to replace values automatically

**Comment by loumalouomega** [comment]
> There is a way to CMake to replace values automatically

The command CONFIGURE_FILE replaces the defined variables

In the python script the variables must be defines like: test_name = "@test_name@"

**Comment by maceligueta** [comment]
The link to configure_file is a few lines above, Vicente.

**Comment by loumalouomega** [comment]
> The link to configure_file is a few lines above, Vicente.

...

**Comment by roigcarlo** [comment]
But how a templated `__init__.py` will help with this problem? As I understand the problem is that you want the python version to be printed before importing Kratos libs that are dependent?

If that's correct we can extract that from the filenames of python extensions. They should look something like `Kratos.cpython-37m-x86_64-linux-gnu.so` so the info is explicitly there, no need to make an extra template.

Would that work?

**Comment by maceligueta** [comment]
Well, if that is enough, cool, no need to do anything else. I don't know if the micro version is important for this matter, I just see the major and the minor version in the file name you just wrote.
The templated `__init__.py` helps because you can print inside that file any condition you want, based on the information CMake knows at compile time, not only the information available in the file name of the library.
