### ISSUE TITLE
[Core][TODO] StructuredMeshGeneratorProcess does not create conditions

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#8062]
**Description**
@pooyan-dadvand @rubenzorrilla, not sure if you were aware of this. Creating the issue also as a to-do reminder for myself. 

The process only creates new elements. From the python interface it seems it would also create conditions but it does not. There is the option to create a "skin" model part, but it is filled only with the nodes of the boundary, without conditions.

**TODO**
- [x] Add creation of conditions in 2D and 3D

**Comment by loumalouomega** [comment]
You can combine it with the SkinGenerationProcess

**Comment by loumalouomega** [comment]
> You can combine it with the SkinGenerationProcess

It theory it generates the skin with the option ""create_skin_sub_model_part" : true,"

**Comment by loumalouomega** [comment]
I did a fast PR (not even check it, but my aracnosense says it will work) so we can discuss there

**Comment by rubenzorrilla** [comment]
> I did a fast PR (not even check it, but my aracnosense says it will work) so we can discuss there

Aracnosense failed. The entire CI crashes :smile:

**Comment by loumalouomega** [comment]
> > I did a fast PR (not even check it, but my aracnosense says it will work) so we can discuss there
> 
> Aracnosense failed. The entire CI crashes smile

I forget the template argument, maybe I have an ant-sense
