### ISSUE TITLE
Access the stiffness and mass matrices

### ISSUE THREAD

**Issue by veiguf** [KratosMultiphysics/Kratos#8077]
The problem in [https://github.com/KratosMultiphysics/Kratos/issues/1821](https://github.com/KratosMultiphysics/Kratos/issues/1821) has surfaced for us again. We would like to access the mass and stiffness matrices of a structural model and get them in Python.
How can we do that? Any help would be appreciated!

**Comment by rubenzorrilla** [comment]
Hi @veiguf ! Just mentioning that maybe makes sense to reopen #1821 to avoid starting the discussion from scratch again.

**Comment by veiguf** [comment]
Closed and moved to [https://github.com/KratosMultiphysics/Kratos/issues/1821](https://github.com/KratosMultiphysics/Kratos/issues/1821)

**Comment by rubenzorrilla** [comment]
> Closed and moved to #1821

Thanks! :wink:
