### ISSUE TITLE
Sintering simulations with DEM using Kratos

### ISSUE THREAD

**Issue by vovannikov** [KratosMultiphysics/Kratos#8087]
**Description**
I am working on a DEM model for sintering applications. I found classes `DEM_sintering_continuum` and `SinteringSphericContinuumParticle` which seem helpful to start with but there is no any example of their usage. Can you maybe give some hints where additional info regarding this part of Kratos can be found?

**Scope**
- DEM Application

**Comment by rubenzorrilla** [comment]
@KratosMultiphysics/dem

**Comment by maceligueta** [comment]
Hi @vovannikov , we added the sintering element because we wanted to test the potential of the DEM for sintering problems. The implementation you see there is very preliminary and only contains the basics. I myself have a stale branch with several improvements that haven't been merged for a few years. I will take a look at those improvements, and will merge them to master, but the sintering element will still be just a first approximation to the problem...

**Comment by vovannikov** [comment]
@maceligueta, thank you for your quick reply. Merging more stable version would be great. Basics is absolutely fine for me, I want to experiment with a bit different sintering mechanics anyway. After playing around the code with the debugger I got the main concepts of the relevant classes, but I assume I might miss the proper usage of them.

Some code is also confusing (maybe because of draft state). Would you mind if I ask couple of questions?

Why is this check here?
https://github.com/KratosMultiphysics/Kratos/blob/1b59498d2b6e14f3c652d0e5e18123f2721e5c0a/applications/DEMApplication/custom_elements/thermal_spheric_particle.cpp#L41-L42

Why in class `SinteringSphericContinuumParticle` there is method `SetInitialSinteringSphereContacts(const ProcessInfo& r_process_info)` which looks like an override of virtual `SetInitialSphereContacts(const ProcessInfo& r_process_info)` but is named differently and, therefore, never invoked?
https://github.com/KratosMultiphysics/Kratos/blob/1b59498d2b6e14f3c652d0e5e18123f2721e5c0a/applications/DEMApplication/custom_elements/sintering_spheric_continuum_particle.cpp#L167

**Comment by maceligueta** [comment]
Hi @vovannikov .
Thanks for your polite tone when you came accross with the giganitc bug in the thermal particle. That was obvioulsy a hardcoded test, which somehow was merged to master by the team. It should be removed immediately. I will do that.
About the method `SetInitialSinteringSphereContacts`, you are right, it was work in progress and I commented it out in my branch `dem-sintering-fixes` several years ago. Unfortunately, I could not keep working on that.
Concerning this branch I just named, I dedicated some time this afternoon to update it. It compiles now, but I did it in a rush and have not tested it at all. If you want to take a look at it you will see that the method `SetInitialSinteringSphereContacts` is no longer used.

**Comment by maceligueta** [comment]
@vovannikov I removed that piece of code in PR #8105

**Comment by vovannikov** [comment]
@maceligueta Thank you for your quick updates and clarification of my doubts. I will also have a look at branch `dem-sintering-fixes`.

**Comment by vovannikov** [comment]
@maceligueta Are you sure it was OK to delete file `kratos/python/add_dem_variables_to_python.cpp` from `dem-sintering-fixes`? The definition of `AddDEMVariablesToPython()` is then missing.

**Comment by maceligueta** [comment]
No, that must have been a merge mess. The branch was so outdated that I had to do a manual merge, and I only looked at the DEMApplication. This file shouldn't have been removed.

**Comment by vovannikov** [comment]
OK, I thought the same. In the meanwhile, it seems I made it work. But some questions came, if you do not mind, I will place them here though they are related to DEM module in general.

Is it possible to prescribe initial displacement of a particle without specifying its velocity? I want to have particles indented at the very first step but not the indentation to be created by making particles radii such that their sum would exceed the distance between their centers (I found a benchmark test like this).
I did not find any example w

**Comment by maceligueta** [comment]
I don't fully understand the example you want to set. If you want particles initially indented you just need them to be overlapping each other. That can be achieved by using big radii or setting the centers coordinates adequately. The option "`CleanIndentationsOption`" must be set to `false `or the DEMApp will decrease the radii of the particles to avoid explosions.

**Comment by vovannikov** [comment]
Thank you @maceligueta for your hints, after all I managed to implement what I initially planned to try. May I ask another thing. I found only some basic examples with mainly 2 particles in Kratos. Are there any examples with entire compounds of particles? Not necessarily for sintering, of course. I am mainly interested in the following. Does Kratos offer some tools for generation of initial packings of particles?

**Comment by maceligueta** [comment]
Hi @vovannikov , folder `tests `contains small tests. However, folder `test_examples `contains a bit bigger and more complex cases.
Usually, when we want to generate complex geometries and packings, we use GiD. We developed a GUI based on GiD.
Other teams are starting to use Salome (structures, fluids?,...). 
The generation of geometries is a hot topic which most probably will be **briefly** addressed in the [1st Kratos Community Meeting](https://github.com/KratosMultiphysics/Kratos/discussions/8239).

**Comment by rubenzorrilla** [comment]
Closing as it seems to be inactive.
