### ISSUE TITLE
Segmentation Fault in Residual Based Block B&S with MasterSlaveConstraints and multiple OpenMP threads

### ISSUE THREAD

**Issue by emiroglu** [KratosMultiphysics/Kratos#8096]
This problem was initially reported in #8064 [here](https://github.com/KratosMultiphysics/Kratos/issues/8064#issuecomment-760241308).

I have a model with a combination of shell, volume, truss elements and master-slave constraints. 

There are two types of master-slave constraints in the model. One type is defined between the displacement DOFs of an orphan node (slave) and the displacement DOFs of the nodes (master) that belong to elements. The other type is between two nodes that both belong to some elements.

@armingeiser has already reported the location of the `Segmentation Fault` [here](https://github.com/KratosMultiphysics/Kratos/issues/8064#issuecomment-761073903) i.e. `ApplyConstraints` 

You can use [this](https://github.com/KratosMultiphysics/Kratos/files/5835407/1_1_Generic_Tower_MSC_Eigen_Block.zip) case to reproduce the error.

Could @adityaghantasala have an opinion on this?

@KratosMultiphysics/structural-mechanics

**Comment by loumalouomega** [comment]
I certainly don't know for a master-slave procedure how this will affect to the system of equations when getting eigenvalues. Did you try the LM builder and solver for the constraints?

**Comment by loumalouomega** [comment]
> I certainly don't know for a master-slave procedure how this will affect to the system of equations when getting eigenvalues. Did you try the LM builder and solver for the constraints?

FYI: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver_with_lagrange_multiplier.h

**Comment by armingeiser** [comment]
Linking the code location of the segfault for convenience: 

https://github.com/KratosMultiphysics/Kratos/blob/cc86fb69d1108a5517f27d0903aa59fe4c12533a/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L1164-L1172

**Comment by loumalouomega** [comment]
> Linking the code location of the segfault for convenience:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/cc86fb69d1108a5517f27d0903aa59fe4c12533a/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L1164-L1172

That look's like mine

**Comment by loumalouomega** [comment]
> > Linking the code location of the segfault for convenience:
> > https://github.com/KratosMultiphysics/Kratos/blob/cc86fb69d1108a5517f27d0903aa59fe4c12533a/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L1164-L1172
> 
> That look's like mine

If you comment line 1165 does it happen¿?

**Comment by armingeiser** [comment]
> If you comment line 1165 does it happen?

Exactly

**Comment by armingeiser** [comment]
Making line 1169 `omp critical` does also solve it. 
The example posted above does only have 6 `slave_equation_id`s, all of them are unique. So the problem is not that the assignment happens simultaneously for the same `slave_equation_id`.

Could it be that the insertion happens at a place where there is no non-zero element in the sparse matrix before and causes a reallocation? How could this be verified?

**Comment by RiccardoRossi** [comment]
mmm, it looks like slave_id appears twice.
can u verify that? (i think it shouldn t happen)

**Comment by RiccardoRossi** [comment]
i mean, i would check if there are repeated slave_ids in  mSlaveIds

**Comment by emiroglu** [comment]
> Could it be that the insertion happens at a place where there is no non-zero element in the sparse matrix before and causes a reallocation? How could this be verified?

I think @armingeiser is right. The problem might be originally stemming from `ConstructMatrixStructure` function. When the slave node does not belong to any element or condition, its `EquationId` is not inserted in the `indices` of the matrix. Then in `ApplyConstraints` the indices and the data are extended without taking care of the race condition. This should also be the reason why `omp critical` solves the problem.

The case actually works with multiple threads, too, when the following lines are added in the mdpa file:
```
Begin Elements NodalConcentratedDampedElement3D1N
    30000 0 1
End Elements
Begin ElementalData NODAL_MASS
30000 141000.0
End ElementalData
```

**Comment by emiroglu** [comment]
> Could it be that the insertion happens at a place where there is no non-zero element in the sparse matrix before and causes a reallocation? How could this be verified?

I think @armingeiser is right. The problem might be originally stemming from `ConstructMasterSlaveConstraintsStructure` function. Slave nodes `EquationId`s are never inserted in the matrix indices. If it also does not belong to any element or condition, `ConstructMatrixStructure` skips them too. Then in `ApplyConstraints` the indices and the data are extended without taking care of the race condition. This should also be the reason why `omp critical` solves the problem.

The case actually works with multiple threads, too, when the following lines are added in the mdpa file:
```
Begin Elements NodalConcentratedDampedElement3D1N
    30000 0 1
End Elements
Begin ElementalData NODAL_MASS
30000 141000.0
End ElementalData
```

**Comment by emiroglu** [comment]
> Could it be that the insertion happens at a place where there is no non-zero element in the sparse matrix before and causes a reallocation? How could this be verified?

I think @armingeiser is right. The problem might be originally stemming from `ConstructMatrixStructure` function. When the slave node does not belong to any element or condition, its `EquationId` is not inserted in the `indices` of the matrix. Then in `ApplyConstraints` the indices and the data are extended without taking care of the race condition. This should also be the reason why `omp critical` solves the problem.

The case actually works with multiple threads, too, when the following lines are added in the mdpa file:
```
Begin Elements NodalConcentratedDampedElement3D1N
    30000 0 1
End Elements
Begin ElementalData NODAL_MASS
30000 141000.0
End ElementalData
```

**Comment by emiroglu** [comment]
Following addition after [Line 1610](https://github.com/KratosMultiphysics/Kratos/blob/cc86fb69d1108a5517f27d0903aa59fe4c12533a/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L1610) does the job:

```
        if (rModelPart.MasterSlaveConstraints().size() != 0) {
            Element::EquationIdVectorType master_ids(3, 0);
            Element::EquationIdVectorType slave_ids(3, 0);
            
            const int nmasterSlaveConstraints = rModelPart.MasterSlaveConstraints().size();
            const auto const_begin = rModelPart.MasterSlaveConstraints().begin();
            
            #pragma omp parallel for firstprivate(nmasterSlaveConstraints, slave_ids, master_ids)
            for (int iii = 0; iii<nmasterSlaveConstraints; ++iii) {
                auto i_const = const_begin + iii;
                i_const->EquationIdVector(slave_ids, master_ids, CurrentProcessInfo);
                
                for (std::size_t i = 0; i < slave_ids.size(); i++) {
                    lock_array[slave_ids[i]].SetLock();
                    auto& row_indices = indices[slave_ids[i]];
                    row_indices.insert(slave_ids.begin(), slave_ids.end());
                    lock_array[slave_ids[i]].UnSetLock();
                }

                for (std::size_t i = 0; i < master_ids.size(); i++) {
                    lock_array[master_ids[i]].SetLock();
                    auto& row_indices = indices[master_ids[i]];
                    row_indices.insert(master_ids.begin(), master_ids.end());
                    lock_array[master_ids[i]].UnSetLock();
                }
            }
        }
```

**Comment by loumalouomega** [comment]
The errors we found here will apply also to the EliminationBuilderAndSolver

**Comment by RiccardoRossi** [comment]
The point is that you are adding all the columns in the MPC  to the matrix, prior to multiplying it by T and Ttranspose.
As far as i need this should not be needed, since the matrix multiplication will (or should) add this automatically.
I think it should work (and occupy way less memory and time) if you just add the diagonal entry


> Following addition after [Line 1610](https://github.com/KratosMultiphysics/Kratos/blob/cc86fb69d1108a5517f27d0903aa59fe4c12533a/kratos/solving_strategies/builder_and_solvers/residualbased_block_builder_and_solver.h#L1610) does the job:
> 
> ```
>         if (rModelPart.MasterSlaveConstraints().size() != 0) {
>             Element::EquationIdVectorType master_ids(3, 0);
>             Element::EquationIdVectorType slave_ids(3, 0);
>             
>             const int nmasterSlaveConstraints = rModelPart.MasterSlaveConstraints().size();
>             const auto const_begin = rModelPart.MasterSlaveConstraints().begin();
>             
>             #pragma omp parallel for firstprivate(nmasterSlaveConstraints, slave_ids, master_ids)
>             for (int iii = 0; iii<nmasterSlaveConstraints; ++iii) {
>                 auto i_const = const_begin + iii;
>                 i_const->EquationIdVector(slave_ids, master_ids, CurrentProcessInfo);
>                 
>                 for (std::size_t i = 0; i < slave_ids.size(); i++) {
>                     lock_array[slave_ids[i]].SetLock();
>                     auto& row_indices = indices[slave_ids[i]];
>                     row_indices.insert(slave_ids.begin(), slave_ids.end());
>                     lock_array[slave_ids[i]].UnSetLock();
>                 }
> 
>                 for (std::size_t i = 0; i < master_ids.size(); i++) {
>                     lock_array[master_ids[i]].SetLock();
>                     auto& row_indices = indices[master_ids[i]];
>                     row_indices.insert(master_ids.begin(), master_ids.end());
>                     lock_array[master_ids[i]].UnSetLock();
>                 }
>             }
>         }
> ```

**Comment by loumalouomega** [comment]
I am trying to create a very minimal failing test (pure C++) in order to debug and ensure does not break in the future, see #8112

**Comment by emiroglu** [comment]
@RiccardoRossi you are right. Only adding the diagonal entries solved the problem too.

**Comment by RiccardoRossi** [comment]
can u create a PR with the changes?
