### ISSUE TITLE
an idea for c++ testing mechanism

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#81]
@roigcarlo @pooyan-dadvand 

i had an idea about the c++ testing mechanism.

why don't you derive it from the python unit test base class? this way you could interact seamlessly with the python unit testing and it should also be easier to integrate in travis-cl

**Comment by loumalouomega** [comment]
Something like this: https://stackoverflow.com/questions/7652193/is-it-possible-to-use-python-based-unit-test-frameworks-and-runners-to-test-c-c ?

**Comment by RiccardoRossi** [comment]
this we have already... however i was speaking with Pooyan and the goal is to have a test suite which does not depend on python, as this facilitates debugging

i'll close this issue since the reasoning makes complete sense to me
