### ISSUE TITLE
Level-set convection process

### ISSUE THREAD

**Issue by pau-mar** [KratosMultiphysics/Kratos#8101]
**Description**
I would like to know if there is any function available that computes the wet area and volume of the elements inside a given surface, such as in XFEM. The function takes into account the level-set function so that there will be elements cut by the interface with part of their area inside and outside. 

Then, should the Navier Stokes Two-Fluid Solver be used when the level_set_convection_process is called in order to update the position of the interface?

Eventually, is there any Example test available in which this process is used? 

**Scope**
- Documentation

**Comment by rubenzorrilla** [comment]
> **Description**
> I would like to know if there is any function available that computes the wet area and volume of the elements inside a given surface, such as in XFEM. The function takes into account the level-set function so that there will be elements cut by the interface with part of their area inside and outside.
> 

There is neither a process nor a utility for such purpose. However it should be easy to implement it as the modified weights calculation for the intersected elements are already implemented in the `ModifiedShapeFunctions` (we could eventually add a new method to the API to avoid the overhead of calculating the shape functions and gradients).

> Then, should the Navier Stokes Two-Fluid Solver be used when the level_set_convection_process is called in order to update the position of the interface?
> 

I don't think the above query is related to that one. Such process could be used for single-phase problems. If you aim at updating your level set function by using a convection solver, IMO this should be implemented in the embedded solver.

**Comment by pau-mar** [comment]
I have created a process that computes the area corresponding to the interior of the interface (i.e. the area with DISTANCE negative values). It takes into account the area from the cut elements. Maybe it can be useful to somebody working on a similar project.

**Comment by rubenzorrilla** [comment]
I rather create a utility for that as this is intended to be used as an auxiliary tool (most probably inside a process).

**Comment by rubenzorrilla** [comment]
Closed as it is no longer needed.
