### ISSUE TITLE
Repeated definitions of register macros

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#811]
Various definitions related with kratos variables are repeated through the code:

Specifically, identical definitions for:

- `KRATOS_REGISTER_IN_PYTHON_VARIABLE`
- `KRATOS_REGISTER_IN_PYTHON_3D_VARIABLE_WITH_COMPONENTS`

exists in:

- `define.h`
- `add_c2c_variables_to_python.cpp`
- `add_cfd_variables_to_python.cpp`
- `add_containers_to_python.cpp`
- `add_dem_variables_to_python.cpp`
- `add_deprecated_variables_to_python.cpp`
- `add_fsi_variables_to_python.cpp`
- `add_legacy_variables_to_python.cpp`
- `add_mapping_variables_to_python.cpp`
- `add_mat_variables_to_python.cpp`

This may have been the result of result for a problem while registering variables that no longer seems to happen. Maybe just with C2C.

My proposal is to remove the definitions from all files except for `add_c2c_variables_to_python.cpp` and change that one so it uses its own definitions in case is necessary instead of redefining the global ones.

**Comment by jcotela** [comment]
I agree with the proposed solution.

**Comment by jcotela** [comment]
Also, I see no need to having custom macros for most applications (in particular not for the cfd and fsi sources, which are the ones I know best).

**Comment by pooyan-dadvand** [comment]
Seems to me a historical code copy pasted but I'm not sure...
