### ISSUE TITLE
[Core][OpenMP] AtomicAdd template argument deduction issue

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#8125]
**Description**
Take these two functions (or any other feasible use case for the `AtomicAdd`)
```c++
template<>
void VariableRedistributionUtility::ThreadsafeAdd<double>(
    double& rLHS,
    const double& rRHS)
{
    AtomicAdd(rLHS,rRHS);
}

template<>
void VariableRedistributionUtility::ThreadsafeAdd< array_1d<double,3> >(
    array_1d<double,3>& rLHS,
    const array_1d<double,3>& rRHS)
{
    AtomicAdd(rLHS, rRHS);
}
```
This should be possible to be done. However, since the two vector types are the same in the second function (`array_1d<double,3>`), the compiler tries to access the second function in the `AtomicUtilitites`
```c++
template<class TDataType>
inline void AtomicAdd(TDataType& target, const TDataType& value ) {
    #pragma omp atomic
    target += value;
}
```
which of course leads to a compiler error in the addition.

**Scope**
- KratosCore

**To Reproduce**
(see above)

**Expected behavior**
This is obviously solved by specifying the types as
```c++
template<>
void VariableRedistributionUtility::ThreadsafeAdd<double>(
    double& rLHS,
    const double& rRHS)
{
    AtomicAdd<double>(rLHS,rRHS);
}

template<>
void VariableRedistributionUtility::ThreadsafeAdd< array_1d<double,3> >(
    array_1d<double,3>& rLHS,
    const array_1d<double,3>& rRHS)
{
    AtomicAdd<array_1d<double,3>, array_1d<double,3>>(rLHS, rRHS);
}
```
In my opinion, this limits the usability and brings the question if we should try to figure out an alternative implementation of this. Maybe this is the best we can do and we need to live with that.

**Environment**
(any environment)

**Comment by philbucher** [comment]
hm probably there is no way around using a different name :/
Otherwise I am not sure how the compiler can figure it out, both functions have the exact same signature (unless two template args are enforced as you show above)

EDIT: maybe we can use [is_scalar](https://en.cppreference.com/w/cpp/types/is_scalar)? I think this would work here and it wouldn't cause overhead as it is evaluated at compile time from what I see

**Comment by philbucher** [comment]
I thought abt this for some more time and I think it is not possible to have the two functions with the same name and different number of template args
Maybe with some template magic it would be possible...

**Comment by rubenzorrilla** [comment]
> I thought abt this for some more time and I think it is not possible to have the two functions with the same name and different number of template args
> Maybe with some template magic it would be possible...

I'm afraid you're right... @roigcarlo @loumalouomega any idea?

**Comment by loumalouomega** [comment]
> I thought abt this for some more time and I think it is not possible to have the two functions with the same name and different number of template args
> Maybe with some template magic it would be possible...

Variadic templates may be a solution. But I can say from experience that it is a pain to programme

**Comment by roigcarlo** [comment]
If I understand the error the problem is that the compiler can't deduce the type because is `const T` and `T` at the same time?
No need to make it with variadrics, you can declare the const in the implementation as a trait of the type:

```c++
template<class TDataType>
inline void AtomicAdd(TDataType& target, std::ad_const_t<TDataType>& value ) {
    #pragma omp atomic
    target += value;
}
```

**Comment by RiccardoRossi** [comment]
Guys, i am afraid i have a good argument for not templating it at all.

the point is that in order to emulate it with c++ (@philbucher i think you are interested in this discussion) something we are currently pursuing, we will have to use boost's atomic_ref (while waiting for c++20's atomic_ref).
This will work _when the data is well aligned_   We cannot ensure this for all the types (for example for "int" in 32bit mode), so i am afraid we will have to limit the atomic to a few well selected data_types (surely "double" and "std::size_t" but i am not 100% of what more)

**Comment by roigcarlo** [comment]
It can be implemented using:

```C++
#include <vector>
#include <iostream>
#include <type_traits>

// Custom type checks start here.
template <class N>
struct is_kratos_vector { static const int value = 0; };

template <class N>
struct is_kratos_float { static const int value = 0; };

template <class N, class A>
struct is_kratos_vector<std::vector<N, A> > { static const int value = 1; };

template <>
struct is_kratos_float<float> { static const int value = 1; };

template<class TVarType, class TReturnType> using EnalbeIfScalar = typename std::enable_if<
    !is_kratos_vector<TVarType>::value && !is_kratos_float<TVarType>::value, TReturnType>::type;

template<class TVarType, class TReturnType> using EnalbeIfVector = typename std::enable_if<
    is_kratos_vector<TVarType>::value, TReturnType>::type;

template<class TVarType, class TReturnType> using EnalbeIfScalarFloat = typename std::enable_if<
    is_kratos_float<TVarType>::value, TReturnType>::type;
// Custom type checks end here.

// Now we can use it cleanly as:
template<class TDataType>
EnalbeIfScalar<TDataType, void> AtomicAdd(TDataType& a, const TDataType& b) {
    #pragma omp atom
    a += b;
}

template<class TDataType>
EnalbeIfScalarFloat<TDataType, void> AtomicAdd(TDataType& a, const TDataType& b) {
    #pragma omp atom
    a += b + 1;
}

template<class TDataType>
EnalbeIfVector<TDataType, void> AtomicAdd(TDataType& a, const TDataType& b) {
    for(unsigned int i=0; i < a.size(); i++) {
       AtomicAdd(a[i], b[i]);
    }
}

int main() {
    int a = 1;
    int b = 2;

    std::vector<int> va = {1,2,3};
    std::vector<int> vb = {2,4,6};

    float fa = 1;
    float fb = 2;

    AtomicAdd(a,b);     // a = 3
    AtomicAdd(va,vb);   // a[0] = 3
    AtomicAdd(fa,fb);   // a = 4
}
```

This way we can customize types as shown. Also in C++20 we can define a 

```c++
struct is_any : std::integral_constant<bool, (std::is_same<T, Ts>::value || ...)> {};
```

So it does not get that verbose.

**Comment by RiccardoRossi** [comment]
just to continue on my line of not having the template at all, take a look at the "caveats" of atomic_ref in

https://www.boost.org/doc/libs/1_75_0/doc/html/atomic/interface.html
