### ISSUE TITLE
[KratosCore][TODO] Upgrade `VariableRedistributionUtility` tests

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#8136]
**Description**
Currently the `VariableRedistributionUtilities` tests in the `test_variable_redistribution.py` file use the `InterfacePreprocess` utility, which belongs to the `FSIApplication`. This means that the testing of a `KratosCore` feature depends on an application, which is a complete non-sense. 

These tests also require a clean up.

**TODO**
- [x] Remove the `InterfacePreprocess` usage from the `test_variable_redistribution.py`
- [x] Upgrade tests
- [x] Add MPI execution

**Comment by philbucher** [comment]
I would add that the tests are also executed in MPI to make sure the results are consistent btw serial & MPI
