### ISSUE TITLE
[SMA] Not printing simulation time anymore?

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#8149]
**Description**
I've seen that the simulation time is no longer printed... Is there a reason for that in Structural?

Regards 
Alejandro

**Comment by philbucher** [comment]
it should be printed, this comes from the AnalysisStage
And hasn't been changed in a while

Maybe you changed the logging level?

**Comment by AlejandroCornejo** [comment]
> it should be printed, this comes from the AnalysisStage
> And hasn't been changed in a while
> 
> Maybe you changed the logging level?

you mean the echo loevel?

**Comment by philbucher** [comment]
no the verbosity if the logger
the default severity is `INFO`. If you change it to `WARNING` then the levels below will no longer be printed
And the time print is with level `INFO`
https://github.com/KratosMultiphysics/Kratos/blob/bd815e5fd0c17975627dc7b8351e459388bb9477/kratos/python_scripts/analysis_stage.py#L139-L140

**Comment by AlejandroCornejo** [comment]
> no the verbosity if the logger
> the default severity is `INFO`. If you change it to `WARNING` then the levels below will no longer be printed
> And the time print is with level `INFO`
> https://github.com/KratosMultiphysics/Kratos/blob/bd815e5fd0c17975627dc7b8351e459388bb9477/kratos/python_scripts/analysis_stage.py#L139-L140

ookey! I'll try!

**Comment by philbucher** [comment]
this might be the origin:
https://github.com/KratosMultiphysics/Kratos/blob/bd815e5fd0c17975627dc7b8351e459388bb9477/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_analysis.py#L44-L49

however this has been like this for quite a while now

also pinging @loumalouomega in case he knows better

**Comment by loumalouomega** [comment]
> this might be the origin:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/bd815e5fd0c17975627dc7b8351e459388bb9477/applications/StructuralMechanicsApplication/python_scripts/structural_mechanics_analysis.py#L44-L49
> 
> however this has been like this for quite a while now
> 
> also pinging @loumalouomega in case he knows better

It was me, I just like when tests only print dots... (don't judge me)
