### ISSUE TITLE
Census for Kratos Technical Committee elections

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#819]
Dear All,
we have been working in preparing the Census for the Kratos Technical Committee elections. The rules were described in a letter that we sent to the community in July, 

however:
- Requisites to be a **voting member** of the census is **having contributed to the open source version of Kratos during the last year**.
- And **to be eligible** to be responsible of an application with at least two other developers

It is currently quite difficult to evaluate this aspects correctly, since on one side it is less than one year we are on GitHub (hence the statistics are not trustworthy), and it is not easy to quantify other contributions such as documentation, material development and other.
All of this makes the margin of error in preparing the census very large.
This is the first draft of the list we could gather.  _We are convinced there may be errors and omissions_. If you find somebody is missing in the list, please tell us and we'll make the relevant correction

**CENSUS** :

- Aditya Ghantasala
- Alressandro Franci
- Andreas Winterstein
- Antonia Larese
- Armin Geyser
- Carlos Roig
- Daniel Baumgaertner
- Eduardo Soudah
- Fabien Pean
- Ferran Arrufat
- Guillermo Casas
- Hoang Giang Bui
- Ignasi Pouplana
- Ilaria Iaconeta
- Javier Garate
- Joaquin Irazabal
- Jordi Cotela
- Josep Maria Carbonell
- Julio Marti
- Klaus Bernd Sautter
- Lluis Montforte Vila
- Long Chen
- Lorenzo Gracia
- Marcelo Raschi
- Massimo Petracca
- Merce ln
- Micheal Andre
- Miguel Angel Celigueta
- Pablo Becker
- Pavel Ryzhakov
- Philip Bucher
- Pooyan Dadvand
- Quirin Aumann
- Riccardo Rossi
- Roland Wuechner
- Ruben Zorrilla
- Salva Latorre
- Tobias Teschemacher
- Vicente Mataix
- Zaghi Stefano

Out of this list we need to develop a list of candidates, meeting the eligibility conditions mentioned above. **We encourage the eligible people to contact us so that we can fill a public list of candidates.**

Here is the current list of candidates, in order or application. To be honest I am not clear if everyone complies with the requirements, we 'll discuss it next week at the BCN meeting.

**CANDIDATES**
- Michael Andre
- Miguel Angel Celigueta
- Jordi Cotela
- Carlos Roig

**Comment by loumalouomega** [comment]
Do I contact via mail?

**Comment by pooyan-dadvand** [comment]
@loumalouomega as you consider!

**Comment by pooyan-dadvand** [comment]
Meanwhile I would like to encourage all  @KratosMultiphysics/team-maintainers to share this message with other colleagues

**Comment by loumalouomega** [comment]
I candidate

**Comment by jcotela** [comment]
I would like to be considered for the list of candidates.
I have no objections regarding the census.

**Comment by roigcarlo** [comment]
Maybe is a good idea to make a list of possible candidates as well? I am not sure if everyone is aware if they'r eligible or not

**Comment by pooyan-dadvand** [comment]
I think everybody can check his/her eligibility better than me giving the code above.... My opinion...

**Comment by maceligueta** [comment]
Please count me as a candidate, too!

**Comment by msandre** [comment]
Please add me to the list of candidates too.

**Comment by RiccardoRossi** [comment]
Hello everyone, i did not receive other applications nor complaints about the census, so the lists at the beginning of this issue should be now considered as final

**Comment by pooyan-dadvand** [comment]
Dear @KratosMultiphysics developers, The final result of the technical committee election is as follow:
1. Carlos Roig (50%)
2. Jordi Cotela (47.5%)
3. Miguel Angel Celigueta (45%)

The participation can be found in [adoodle](https://www.adoodle.org/index.php?action=showresults&survey=9679ec340b03a676373f9addd6bd9ead&timezone=Europe%2FMadrid)
