### ISSUE TITLE
[StructMech][Eigenvalue] Correct way of getting the number of eigenvalues and shapes wanted

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#8208]
**Description**
I am using the StructuralMechanicsApplication to solve for eigenvalues. As far as I see, the solve is correct, but I am not getting the amount of eigenvalues that I would need. Independent of the settings, I get 5 which I can display and also in the terminal I see only 5 once the solve is done.

Here are 2 small examples:

- [a cantilever modeled with beam elements](https://syncandshare.lrz.de/dl/fiTEqtAe2sgfDhLof4QvoKKP/cantilever_beam_model.gid)
- [a cantilever modeled with solid elements](https://syncandshare.lrz.de/dl/fiA5FomorWmkYSUzaz7gc1tw/cantilever_solid_model.gid)

**Scope**
What is the correct usage for getting the number of eigenvalues intended?

**Comment by e-dub** [comment]
You can change this in the ProjectParameters.json file 
```
        "eigensolver_settings"     : {
            "solver_type"           : "eigen_eigensystem",
            "max_iteration"         : 1000,
            "tolerance"             : 1e-6,
            "number_of_eigenvalues" : 5,
            "echo_level"            : 1
        },
```
or in the Python file 

```
with open("ProjectParameters.json",'r') as parameter_file:
    parameters = km.Parameters(parameter_file.read())
parameters["solver_settings"]["eigensolver_settings"]["number_of_eigenvalues"].SetInt(nEig)
```

**Comment by philbucher** [comment]
we already checked this, no matter what is in the ProjectParams the solver spits out 5

**Comment by e-dub** [comment]
You guys have linear_solver_settings instead of eigensolver_settings in the JSON.  Then it takes the default.  Can that be?

This delivers 10 eigenvalues for your model:

```
        "eigensolver_settings"     : {
            "solver_type"           : "eigen_eigensystem",
            "max_iteration"         : 1000,
            "tolerance"             : 1e-6,
            "number_of_eigenvalues" : 10,
            "echo_level"            : 1
        },
```

**Comment by mpentek** [comment]
Ok, so that actually works, meaning I had to replace
`        "linear_solver_settings"     : {`
with
`        "eigensolver_settings"     : {`

I this the intended behavior? I find it misleading as I anyway specify
`        "solver_type"              : "eigen_value",`
