### ISSUE TITLE
Nurbs2D and 3D has create function with Point<3>

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#821]
It shouldn't be PointType of the geometry?

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/nurbs-breps Are you using the create method?

**Comment by jcotela** [comment]
I can't answer for the current implementation, but the old one (the one of Matthias) used nodes for control points and points for knots (which don't hold data).

**Comment by dbaumgaertner** [comment]
Most probably Tobias is the only guy who can answer this.

**Comment by d-herreroadan** [comment]
Hi Pooyan,


At the moment I am not using Kratos


Regards


Dan

________________________________

**Comment by RiccardoRossi** [comment]
If you comment it out, does the code compile? @tteschemacher comments on this?

**Comment by pooyan-dadvand** [comment]
Actually I have comment it out as it was not used anywhere in the public repo. But I want to be sure if it hurts somewhere else....

**Comment by SaibotTe** [comment]
Nurbs2d and 3d is not written nor used by me. So from my perspective you can comment it out. But I am not sure wether it is used somewhere else, but not by me.

**Comment by tteschemacher** [comment]
Nurbs2d and 3d is not written nor used by me. So from my perspective you can comment it out. But I am not sure wether it is used somewhere else, but not by me.

**Comment by jcotela** [comment]
After looking into it, I believe the Nurbs2d and 3d classes come from the thesis work of Matthias back in 2014. I don't think anyone is using them currently, so we might want to remove them from the repository at some point.

**Comment by pooyan-dadvand** [comment]
Before that I would suggest @KratosMultiphysics/nurbs-breps team to check if they can reuse it in some way...

**Comment by RiccardoRossi** [comment]
Ping

**Comment by RiccardoRossi** [comment]
@vryy maybe you are using it?

**Comment by vryy** [comment]
@RiccardoRossi nope, I didn't. But please keep the Kratos_NURBS in the GeometryData. For some reason, it disappeared.

**Comment by pooyan-dadvand** [comment]
So finally I just leave it as it is.
