### ISSUE TITLE
Nearest element mapper for volume elements

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#822]
Hi @philbucher , @jcotela 

I am opening this issue since it would be increasingly importante por us (due to some projects) to have the capability to map between volumes. Any hope this could be priorized?

Regards
Riccardo

**Comment by philbucher** [comment]
Hi Riccardo,
This is working for a couple of months already.
You can check out the tests in the MappingApplication
I only did small test cases but in principle it is working 
I can do a larger test if you want

**Comment by RiccardoRossi** [comment]
Hi philip,
    Just to be sure, it works VOLUME to VOLUME?

If so perfect!!

Cheers
Riccardo

El 7 oct. 2017 12:14 p. m., "Philipp Bucher" <notifications@github.com>
escribió:

Hi Riccardo,
This is working for a couple of months already.
You can check out the tests in the MappingApplication
I only did small test cases but in principle it is working
I can do a larger test if you want

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/KratosMultiphysics/Kratos/issues/822#issuecomment-334924842>,
or mute the thread

**Comment by philbucher** [comment]
Yes, basically every node in the destination interpolates in the origin, no matter whether the origin is 1D, 2D or 3D
But I can check again in the beginning of next week just to make sure and send you an example

**Comment by RiccardoRossi** [comment]
Thx!

I 'll pass by your office on Monday


Riccardo

**Comment by RiccardoRossi** [comment]
Closing, thx
