### ISSUE TITLE
[Core] PointerVector and PointerVectorSet cbegin and cend iterators.

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#8248]
Should we define the `cbegin` and `cend` iterators in the `PointerVector` and `PointerVectorSet` as the `std::vector` and `std::array` do?

**Comment by philbucher** [comment]
What would be the use?

**Comment by RiccardoRossi** [comment]
you have a non-const vector and you want to get const iterators from it.

it is defined in the standard...

**Comment by RiccardoRossi** [comment]
just pointing here to a discussion about the meaning of &&. A bit mind-blowing (for me) but an interesting read

https://isocpp.org/blog/2012/11/universal-references-in-c11-scott-meyers

**Comment by pooyan-dadvand** [comment]
Ok for me, in fact it would be a copy of `begin() const`

**Comment by rubenzorrilla** [comment]
> Ok for me, in fact it would be a copy of `begin() const`

I think so too.

**Comment by rubenzorrilla** [comment]
I'll take care.
