### ISSUE TITLE
[TwoFluidNavierStokes] Non converging sloshing simulation

### ISSUE THREAD

**Issue by RiedlAndreas** [KratosMultiphysics/Kratos#8259]
**Description**
I'm implementing a 2D rectangular water tank in the TwoFluid Application functioning as a Tuned Liquid Damper. The acceleration of the water tank is coupled with a structural model.

**Problem**
For high dynamic cases, a lot of water sloshing and wave breaking the TwoFluid application does not converge. Can anyone give me any clues, tips or tweaks for my solver settings? @rubenzorrilla @mrhashemi ?
I'm already using the ApplyMassConservationCheckProcess for mass conservation. The boundaries are slip conditions.

**Solver settings**
```
"solver_settings"             		: {
        "model_part_name" 	: "FluidModelPart",
        "domain_size"     	: 2,
        "solver_type"   	: "TwoFluids",
        "model_import_settings"       	: {
            "input_type"     : "mdpa",
            "input_filename" : "mesh_CFD"
        },
        "material_import_settings": {
            "materials_filename": "FluidMaterials.json"
        },
	"maximum_iterations"			: 50,
    	"echo_level"					: 0,
    	"time_order"					: 2,
    	"compute_reactions"				: false,
    	"reform_dofs_at_each_step"		: false,
    	"relative_velocity_tolerance"	: 1e-3,
    	"absolute_velocity_tolerance"	: 1e-5,
    	"relative_pressure_tolerance"	: 1e-3,
    	"absolute_pressure_tolerance"	: 1e-5,
        "volume_model_part_name"     	: "FluidParts_Fluid",
        "skin_parts"                 	: ["Outlet2D_Outlet","Slip2D"],
        "no_skin_parts"              	: [],
        "move_mesh_flag"				: false,
        "time_stepping"  : {
            "automatic_time_step": false,			
            "time_step":    0.001
        },
        "formulation": {
            "dynamic_tau"					: 0.1
        }
        ,
    	"linear_solver_settings": {
            "solver_type" : "amgcl",
            "smoother_type" :"damped_jacobi",
            "krylov_type" : "lgmres",
            "coarsening_type" : "aggregation",
            "max_iteration" : 500,
            "provide_coordinates" : false,
            "gmres_krylov_space_dimension" : 500,
            "verbosity" : 0,
            "tolerance" : 1e-4,
            "scaling" : false,
            "block_size" : 3,
            "use_block_matrices_if_possible" : true,
            "coarse_enough" : 500
    	}
    },
```
![ocbkhiboanbjhnmc](https://user-images.githubusercontent.com/28905563/107387070-c1262880-6af4-11eb-9abe-6f6175f04f68.png)

**Comment by mrhashemi** [comment]
Hi,
Please follow these two steps:
1. Increase the "verbosity" of the linear solver to check if it is converging at each iteration. 
2. Use "ApplyDistanceModificationProcess" with a rather large "distance_threshold" (= 0.01 for example).

**Comment by RiedlAndreas** [comment]
Hi, thanks for your respond.

1. For this case it only achieves a convergence up to time_step 3783. Then it no longer converges. 

```
time=3.783 | step=3783[0m[0m:  
::[KSM Simulation]:: : STEP:  3783 
::[KSM Simulation]:: : TIME:  3.7829999999996944 
Fluid Dynamics Analysis: STEP:  3783 
Fluid Dynamics Analysis: TIME:  3.7829999999996944 
NavierStokesTwoFluidsSolver: Level-set convection is performed. 
ResidualBasedLinearStrategy: System Construction Time5.905e-06
ResidualBasedBlockBuilderAndSolver: Build time: 0.00207408
ResidualBasedBlockBuilderAndSolver: System solve time: 0.0370502
ResidualBasedLinearStrategy: System Construction Time3.161e-06
ResidualBasedBlockBuilderAndSolver: Build time: 0.00218608
ResidualBasedBlockBuilderAndSolver: System solve time: 0.0419863
ResidualBasedLinearStrategy: System Construction Time3.078e-06
ResidualBasedBlockBuilderAndSolver: Build time: 0.00225466
ResidualBasedBlockBuilderAndSolver: System solve time: 0.0400921
NavierStokesTwoFluidsSolver: Redistancing process is finished. 
ResidualBasedNewtonRaphsonStrategy: System Construction Time: 2.761e-06

 ...50 iterartions ...

ResidualBasedBlockBuilderAndSolver: Build time: 0.0151466
ResidualBasedBlockBuilderAndSolver: System solve time: 0.10906
CONVERGENCE CHECK:
 VELOCITY : ratio = 0.00280787; exp.ratio = 0.001 abs = 1.08828e-05 exp.abs = 1e-05
 PRESSURE : ratio = 2.17548e-05; exp.ratio = 0.001 abs = 0.000131194 exp.abs = 1e-05
ResidualBasedNewtonRaphsonStrategy: ATTENTION: max iterations ( 50 ) exceeded!
[WARNING] NavierStokesTwoFluidsSolver: Fluid solver did not converge for step 3783
corresponding to time 3.7829999999996944
```

2. Unfortunately, increasing the distance_threshold does not bring any improvement.

Also choosing a very small time_step does not bring any help. Then it stops converging even earlier. Do I've to adjust another value to calculate with a very small time_step for debugging ?

**Comment by RiccardoRossi** [comment]
can u post a snapshot of velocity and pressure at the step just before it fails?

**Comment by RiedlAndreas** [comment]
![grafik](https://user-images.githubusercontent.com/28905563/107524848-8b497880-6bb6-11eb-938c-27e498316b43.png)
![grafik](https://user-images.githubusercontent.com/28905563/107524914-98fefe00-6bb6-11eb-850d-39ae865ece58.png)
![grafik](https://user-images.githubusercontent.com/28905563/107524956-a3b99300-6bb6-11eb-9f8e-3ce42c6e0f0e.png)

**Comment by RiccardoRossi** [comment]
i think that you have an inlet been created at the top. I mean velocity going towards the inside of the domain in a point where the velocity is not fixed. That is not defined as a BC...and i guess provoques the failure

to check, take a look at the vectors, not just at their norms

**Comment by RiedlAndreas** [comment]
![grafik](https://user-images.githubusercontent.com/28905563/107525609-4d991f80-6bb7-11eb-9fe1-3b1016d8174d.png)

Top boundary is only assigned to pressure = 0 right now

**Comment by RiccardoRossi** [comment]
yes, that's the problem, you have a vortex which enters from the top. The behaviour is undefined since you need to prescribe BCs at the beginning of each streamline.

**Comment by RiedlAndreas** [comment]
Ok. I wonder cause it converges in another simulation with less dynamic movement and smaller velocities. Also with entering velocity from the top condition.

**Comment by RiccardoRossi** [comment]
it MAY converge, or fail...typically it fails when you have a strong vortex crossing the boundary

**Comment by RiedlAndreas** [comment]
All right thank you. I'm gonna try to prevent this scenario

**Comment by RiedlAndreas** [comment]
It seems like that was the problem. Thank you.
