### ISSUE TITLE
TestMathUtilsGenDetMatTest failing in master

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#826]
Hi, it seems that one of the tests in test_math_utils is failing in the current version of master. I get the following message:
```
    TestMathUtilsGenDetMatTest Failed with message:                                                                                                                        
        Error: Check failed becuase det = 1 is not near to 0.0 = 0 within the tolerance 1e-06                                                                              
in kratos/tests/math_utils/test_math_utils.cpp:134:virtual void Testing::TestMathUtilsGenDetMatTest::TestFunction()      
```
Is this normal? @loumalouomega I'm assigning you since you are listed as the author of the test.

**Comment by loumalouomega** [comment]
Oki doki, I checked yesterday, strange...

**Comment by pooyan-dadvand** [comment]
For me was working last Friday before making the branch for point cleanup....

**Comment by jcotela** [comment]
Closing, since it is working now (after #831). Thanks @loumalouomega!
