### ISSUE TITLE
[StructuralMechanicsApplication] Question about beam 

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#8261]
**Description**
This question is presented by @Joekchu, I could not dedicate time to it. I am still thinking in a good answer, but maybe some can contribute already.

> Now I have a container for smart pointers pointing to all the beam elements and another container pointing to the target solid elements. If the beam GP is inside of the solid element, this solid element we define as target solid element.

> That means, if we have 100 beam GPs, we will have 100 target solid elements, each target solid element is wished to be linked to a beam GP which lies inside of it. However, I don’t know how to link them because their sequence in containers is not same. For example, the beginning (the 1st) pointer pointing to the beam element A, but the pointer of target element is not lied at the beginning or 1st place of its container. I need to search over the container to find the correct pointer. It will create a huge overhead. Do you have any suggestions to quickly find the correct target element?

**Scope**
- @KratosMultiphysics/structural-mechanics

**Comment by rubenzorrilla** [comment]
Maybe a custom `unordered_map`?

**Comment by philbucher** [comment]
there are some search structures in Kratos which I think can be used

**Comment by loumalouomega** [comment]
OK, after thinking this is quite a mix what is done in the remeshing processes and the contact search algorithms.

Ok, I will do a simplified C++ code in order to show what can be done:

For this case let's suppose you have already separated the model part of the beams and the solids.

First you need to define a variable for a vector Element::Pointer (see other applications how to be declared), because must be declared in several files:

In `applications/StructuralMechanicsApplication/structural_mechanics_application_variables.h` (or your own application)
~~~c++
.
.
-
KRATOS_DEFINE_APPLICATION_VARIABLE( STRUCTURAL_MECHANICS_APPLICATION, std::vector<Element::Pointer>, TARGET_ELEMENTS ) // Target elements for a certain computation
.
.
.
~~~

In `applications/StructuralMechanicsApplication/structural_mechanics_application_variables.cpp` (or your own application)
~~~c++
KRATOS_CREATE_VARIABLE( std::vector<Element::Pointer>, TARGET_ELEMENTS ) // Target elements for a certain computation
~~~


In `applications/StructuralMechanicsApplication/structural_mechanics_application.cpp` (or your own application)
~~~c++
KRATOS_REGISTER_VARIABLE( TARGET_ELEMENTS ) // Target elements for a certain computation
~~~

Now in a process or utility of your interest (NOTE: If 2D TDim is 2 and if 3D TDim is 3):

~~~c++
.
.
.
#include "utilities/binbased_fast_point_locator.h"
.
.
.
	// First we fill and declare the new database of elements
	// TODO: Add parallel algorithm
	for (auto& r_elem : rModelPart.GetSubModelPart("BeamsSubModelParts")) {
		std::vector<Element::Pointer> aux_vector;
		r_elem.SetValue(TARGET_ELEMENTS, aux_vector);
	}

	// We create the locator
    BinBasedFastPointLocator<TDim> point_locator = BinBasedFastPointLocator<TDim>( rModelPart.GetSubModelPart("SolidsSubModelParts"));
    point_locator.UpdateSearchDatabase();

	// Auxiliar values
	const auto& r_process_info = rModelPart.GetProcessInfo();
    Vector shape_functions;
    Element::Pointer p_element = nullptr;
	std::vector<array_1d<double, 3>> gp_coordinates;

	// TODO: Add parallel algorithm
	for (auto& r_elem : rModelPart.GetSubModelPart("BeamsSubModelParts")) {
		
		// Retrieve GP coordinates
		r_elem.CalculateOnIntegrationPoints(INTEGRATION_COORDINATES, gp_coordinates, r_process_info);
		
		// Iterate over the Gauss points
		for (auto& r_coordinates : gp_coordinates) {
			  const bool is_found = point_locator.FindPointOnMeshSimplified(r_coordinates, shape_functions, p_element, 100, 5.0e-2);
	  
			  // If found append to the database
			  if (is_found) {
				  (r_elem.GetValue(TARGET_ELEMENTS)).push_back(p_element);
				  break; // We want to add the same element just once, so we exit the GP loop
			  }
		}
	}
~~~

**Comment by loumalouomega** [comment]
Basically that @Joekchu, I think is quite detailed
