### ISSUE TITLE
Different "include" requirements in serial and parallel cases

### ISSUE THREAD

**Issue by mrhashemi** [KratosMultiphysics/Kratos#8266]
**Description**
While everything was easily compiled for the serial (USE_MPI=OFF) case, I encountered an strange undefined pointer variable (NEIGHBOUR_NODES) error by setting USE_MPI=ON.
The error is resolved by **_#include "includes/global_pointer_variables.h"_**, however it creates a confusion since there should not be any discrepancy between the serial and parallel cases in this regard.
**Note:** I implemented a function that needs access to NEIGHBOUR_NODES within "levelset_convection_process.h".

**Comment by RiccardoRossi** [comment]
@mrhashemi why do you need the neighbours? i thought you only needed the L2 projections

**Comment by mrhashemi** [comment]
> @mrhashemi why do you need the neighbours? i thought you only needed the L2 projections

The calculation of the limiter is based on the Neighboring nodes. Its formula needs "u_i - u_j".

**Comment by RiccardoRossi** [comment]
ok then

**Comment by rubenzorrilla** [comment]
@mrhashemi is this solved?

**Comment by mrhashemi** [comment]
> @mrhashemi is this solved?

Seems so. It was just for informing that the _#include_ requirements might be different in some cases. 
Anyway, I think I can close it.
