### ISSUE TITLE
[TwoFluids] Access to variables from base class in NavierStokesMPITwoFluidsSolver

### ISSUE THREAD

**Issue by RiedlAndreas** [KratosMultiphysics/Kratos#8313]
**Description**
Setting up a MPI TwoFluids simulation I get an error in NavierStokesTwoFluidsSolver -> InitializeSolutionStep:

`AttributeError: 'NavierStokesMPITwoFluidsSolver' object has no attribute '_reinitialization_type' `

This variable is defined and read in "NavierStokesTwoFluidsSolver.__init__(...)". But as far as I can tell in constructing the NavierStokesMPITwoFluidsSolver the constructor of the parent is not called, but the constructor of the grand-parent (FluidSolver). I think this was initially done to avoid conflicts in attribute settings, but the settings are obligate for continuing with the NavierStokesTwoFluidsSolver.

Same with the variable `_distance_smoothing`

**Comment by RiedlAndreas** [comment]
@rubenzorrilla @jcotela ? As I saw your names in reviewing the NavierStokesMPITwoFluidsSolver ..

**Comment by rubenzorrilla** [comment]
These changes were introduced by @mrhashemi . Thanks for reporting @RiedlAndreas .

**Comment by philbucher** [comment]
@rubenzorrilla it seems like this is another issue stemming from the MPI-fluid solvers not calling the serial version in the init :sweat_smile:

**Comment by rubenzorrilla** [comment]
> @rubenzorrilla it seems like this is another issue stemming from the MPI-fluid solvers not calling the serial version in the init sweat_smile

It is in the top part of the TODO list of the fluid project... I'll take care ASAP.

**Comment by RiedlAndreas** [comment]
The merge #8315 should fix the problem. Thank you
