### ISSUE TITLE
Using the VariableRedistributionUtility

### ISSUE THREAD

**Issue by AndreasWinterstein** [KratosMultiphysics/Kratos#832]
Hi @rubenzorrilla, we would like to use the VariableRedistributionUtility you are also using in the FSI application before and after mapping. We are doing the following in our main script:

import KratosMultiphysics.FSIApplication as FSI

_FSI.VariableRedistributionUtility.DistributePointValues(fluid_model_part, REACTION, VAUX_EQ_TRACTION)
mapper.InverseMap(VAUX_EQ_TRACTION, VECTOR_PROJECTED, flag) 
FSI.VariableRedistributionUtility.ConvertDistributedValuesToPoint(structural_model_part, VECTOR_PROJECTED, POINT_LOAD)

But when doing this we get an error. The gdb output tells us that it jumps into the SetScalarVal function, which seems a bit strange for us._ 

Here is the gdb output:

_#7  0x00007ffff5d33ca5 in void Kratos::VariableUtils::SetScalarVar<Kratos::VariableComponent<Kratos::VectorComponentAdaptor<Kratos::array_1d<double, 3ul> > > >(Kratos::VariableComponent<Kratos::VectorComponentAdaptor<Kratos::array_1d<double, 3ul> > >&, double const&, Kratos::PointerVectorSet<Kratos::Node<3ul, Kratos::Dof<double> >, Kratos::IndexedObject, std::less<unsigned long>, std::equal_to<unsigned long>, boost::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::vector<boost::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > >, std::allocator<boost::shared_ptr<Kratos::Node<3ul, Kratos::Dof<double> > > > > >&) () from /home/mini/software/Kratos/libs/Kratos.so
No symbol table info available._

The question is, can we use your functions also in our own main script outside of the FSI application and why is the SetScalarVar function called?

Thank you in advance for your help.

**Comment by jcotela** [comment]
Hi @AndreasWinterstein, I wrote the current version of the VariableRedistributionUtility. You should be able to use it independently of the currrent FSI scripts (and for vectors), so I'd say you have found a bug. Could you send me some kind of working example, so that I can try debug it?

**Comment by AndreasWinterstein** [comment]
Hi @jcotela, thank you for your help. We could solve the problem ourself. It was due to the GID...
