### ISSUE TITLE
Problems in compilation

### ISSUE THREAD

**Issue by Joekchu** [KratosMultiphysics/Kratos#8333]
**Description**
Dear all,

When I engage to compile the MKL-related application, I got the below errors. I don't know how to fix it, could you please help me? Also, I don't know what means "**AUX6-NOTFOUND;AUX5-NOTFOUND**"

***************************************************************************
****** kratos configured for using the mkl shipped with intel >= 2013 *****
***************************************************************************
************ mkl solver libraries found  /usr/lib/x86_64-linux-gnu/libpthread.so;**AUX6-NOTFOUND;AUX5-NOTFOUND**;/home/joe/intel/oneapi/mkl/2021.1.1/lib/intel64/libmkl_lapack95_ilp64.a;/home/joe/intel/oneapi/mkl/2021.1.1/lib/intel64/libmkl_core.so;/home/joe/intel/oneapi/mkl/2021.1.1/lib/intel64/libmkl_gnu_thread.so;/home/joe/intel/oneapi/mkl/2021.1.1/lib/intel64/libmkl_intel_ilp64.so
mkl include dir /home/joe/intel/oneapi/mkl/2021.1.1/include
mkl libs /usr/lib/x86_64-linux-gnu/libpthread.so;**AUX6-NOTFOUND;AUX5-NOTFOUND**;/home/joe/intel/oneapi/mkl/2021.1.1/lib/intel64/libmkl_lapack95_ilp64.a;/home/joe/intel/oneapi/mkl/2021.1.1/lib/intel64/libmkl_core.so;/home/joe/intel/oneapi/mkl/2021.1.1/lib/intel64/libmkl_gnu_thread.so;/home/joe/intel/oneapi/mkl/2021.1.1/lib/intel64/libmkl_intel_ilp64.so

Thanks a lot!

**Scope**
- Compilation

**Comment by philbucher** [comment]
can you please post your configuration?
OS, compiler, configure file etc

**Comment by Joekchu** [comment]
@philbucher 

Hi, thank you Philipp, I already fix it. The compilation is proceeding on Linux. After I add a symbolic link, it works. Sorry to disturb you so much!
