### ISSUE TITLE
Nightly test execution time

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#834]
Dear @KratosMultiphysics/team-maintainers 

I hate to bring back this but from one day to the next the nightly test time has increased 20 minutes. This means +40 minutes total run time everyday.

We will handle this internally but please try not to add validation tests to the nightly runs, or if it is strictly necessary, keep them as small as possible. The 15 min limit is not there to fill it, it's just a healthy indicator.

**Comment by pooyan-dadvand** [comment]
:+1: for @roigcarlo We should really keep the testing time under control to be able to do much more tests

**Comment by roigcarlo** [comment]
I close this as we already discussed it in the office.
