### ISSUE TITLE
Handeling and Documentation of important Processes

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#836]
Over the past few months me and other ppl at the Chair set up several cases in GiD. Sometimes we had to change sth some time later and often encountered the issue that some Processes had changed names. (e.g. https://github.com/KratosMultiphysics/GiDInterface/issues/156)
We have two wishes / proposals, regarding the processes that are mostly being used for the application of Boundary Conditions: 
1. Could we "freeze" the names of the processes? Constant changes create a lot of confusion
2. I guess the implementation of these processes is rather converged, they have been there for a while now. I think it is time to remove the deprecated ones and also make some documentation, the names are not descriptive (e.g. `AssignVectorByDirectionProcess`, `AssignVectorByDirectionToConditionProcess`, `AssignVectorVariableProcess`, `AssignVectorVariableToConditionProcess`, `ImposeVectorValueByComponentsProcess`, `ImposeVectorValueByDirectionProcess` all sound similar, but it is not clear which one to use for what without looking in detail through the code)

@KratosMultiphysics/kratos-core-team @KratosMultiphysics/structural-mechanics @KratosMultiphysics/fluid-dynamics

**Comment by RiccardoRossi** [comment]
@rubenzorrilla can u finish the cleaning u started?

**Comment by rubenzorrilla** [comment]
@philbucher @RiccardoRossi  I've just start the clean up.

**Comment by pooyan-dadvand** [comment]
Is this for release 5.2? So I would suggest to be added to the [milestone](https://github.com/KratosMultiphysics/Kratos/milestone/4)

**Comment by rubenzorrilla** [comment]
IMO should be in release 5.2. I'm adding it.

**Comment by pooyan-dadvand** [comment]
:+1:

**Comment by RiccardoRossi** [comment]
@philbucher i did some documentation. You can find at the end of the howtos in the wiki, or at this link

https://github.com/KratosMultiphysics/Kratos/wiki/How-to-use-Processes-In-the-application-of-BCs

please fell free to modify the text as you consider

**Comment by RiccardoRossi** [comment]
i think this is quite complete, so i close it. please reopen if you deem it necessary

**Comment by philbucher** [comment]
Great, thanks a lot @RiccardoRossi 
I added the list of which processes replace the deprecated ones
