### ISSUE TITLE
Error compiling example MyLaplacianApplication

### ISSUE THREAD

**Issue by calpe** [KratosMultiphysics/Kratos#8370]
**Description**
I am following steb-by-step Kratos for dummies. 
I have created the application MyLaplacianApplication.
I compile config.sh with the new application. 
I get the following compilation error:

/home/mcalpe/Dev/Kratos/applications/MyLaplacianApplication/custom_conditions/point_source_condition.cpp: In member function ‘virtual void Kratos::PointSourceCondition::EquationIdVector(Kratos::Condition::EquationIdVectorType&, const Kratos::ProcessInfo&) const’:
/home/mcalpe/Dev/Kratos/applications/MyLaplacianApplication/custom_conditions/point_source_condition.cpp:175:42: error: ‘TEMPERATURE’ was not declared in this scope
  175 |     rResult[i] = GetGeometry()[i].GetDof(TEMPERATURE).EquationId();
      |                                          ^~~~~~~~~~~
/home/mcalpe/Dev/Kratos/applications/MyLaplacianApplication/custom_conditions/point_source_condition.cpp: In member function ‘virtual void Kratos::PointSourceCondition::GetDofList(Kratos::Condition::DofsVectorType&, const Kratos::ProcessInfo&) const’:
/home/mcalpe/Dev/Kratos/applications/MyLaplacianApplication/custom_conditions/point_source_condition.cpp:192:53: error: ‘TEMPERATURE’ was not declared in this scope
  192 |     rConditionDofList[i] = GetGeometry()[i].pGetDof(TEMPERATURE);
      |                                                     ^~~~~~~~~~~
make[2]: *** [applications/MyLaplacianApplication/CMakeFiles/KratosMyLaplacianCore.dir/build.make:63: applications/MyLaplacianApplication/CMakeFiles/KratosMyLaplacianCore.dir/custom_conditions/point_source_condition.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:656: applications/MyLaplacianApplication/CMakeFiles/KratosMyLaplacianCore.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Environment**
- OS: Ubuntu 20.04
- Branch: master
- Python 3.8.5

**Comment by philbucher** [comment]
hi @calpe 
You need to include `#include "includes/variables.h"` in those cpp files, then it should work

**Comment by calpe** [comment]
It worked! 
Thank you @philbucher 

Very interesting the Salome plugin with Kratos. I've just read about it!

**Comment by rubenzorrilla** [comment]
> It worked!
> Thank you @philbucher
> 
> Very interesting the Salome plugin with Kratos. I've just read about it!

Just mentioning that tomorrow it will be briefly presented in the Community meeting. Find the Google Meet link in https://github.com/KratosMultiphysics/Kratos/discussions/8239

**Comment by philbucher** [comment]
> > It worked!
> > Thank you @philbucher
> > Very interesting the Salome plugin with Kratos. I've just read about it!
> 
> Just mentioning that tomorrow it will be briefly presented in the Community meeting. Find the Google Meet link in #8239

also I just moved it from my private account to KratosMultiphysics. You can now find it here: https://github.com/KratosMultiphysics/KratosSalomePlugin
