### ISSUE TITLE
[CORE] Proposal: changing the Vector/Matrix handling from Vector to BoundedVector/BoundedMatrix

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#8403]
**Description**
Dear @KratosMultiphysics/all ,

For a few months we have been thinking (@RiccardoRossi ) in modifying the interface of the `ConstitutiveLaw` and deprecating the use of `Vector`and `Matrix` types and using the `BoundedVector `and `BoundedMatrix `types of whicxh tghe size is known at compile time (can be resized afterwards).

In theory it will increase the velocity of the calculation and also a bit the memory consumption but we think that it may be worth.

What do you think?

I suppose that we will create some `typedef's` in the base class to define this.

Regards,

**Comment by maceligueta** [comment]
What do you mean with 'can be resized afterwards'?

**Comment by AlejandroCornejo** [comment]
> What do you mean with 'can be resized afterwards'?

The thing is that a priori yo do not know the Voigt Size for example. You'll have to assume that is 6 and, if your problem is in 2D you can resize the matrix to the correct size

**Comment by maceligueta** [comment]
I was as confused as this guy: https://stackoverflow.com/questions/2068408/ublasbounded-vector-being-resized

**Comment by loumalouomega** [comment]
+1 for this (Besides, I said this some yeas ago)

**Comment by RiccardoRossi** [comment]
well, this is actually useful, ecen though stack_allocated_matrix wpuld
have been better

**Comment by AlejandroCornejo** [comment]
> I was as confused as this guy: https://stackoverflow.com/questions/2068408/ublasbounded-vector-being-resized

That's totally true and understandable, the reality is this: _actually can be resized, it may only not be greater than the size specified as template parameter._ This is what we we'll take advantage of.

**Comment by RiccardoRossi** [comment]
in my opinion we need to provide a list of typedefs in the baseclass and always use those in the CL

for example StrainVectorType, StresVectorType, etc...

**Comment by AlejandroCornejo** [comment]
I suggest to continue the discussion HERE: https://github.com/KratosMultiphysics/Kratos/pull/8700
