### ISSUE TITLE
[CI] Adding not cotired compilation to CI

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#8404]
**Description**
Adding not cotired compilation to CI in order to avoid the problems that appear after a merge and the not cotired compilation fails. This is because there is not cotired CI right now, and the CI does not block the merge

@KratosMultiphysics/technical-committee

**Comment by roigcarlo** [comment]
Agree with @loumalouomega, but we have to carefully thing when. Non cotire compilation can be long. Maybe we should schedule it with the nightlies.

**Comment by philbucher** [comment]
> Maybe we should schedule it with the nightlies.

usually by then it is too late and we have fixed it already :)

**Comment by philbucher** [comment]
I will take care of this once #8384 is merged
