### ISSUE TITLE
Documentation about the RESTART features in Kratos

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#8405]
**Description**
Dear all,

I am currently trying to  use the **restart** in the `PfemFluidDynamicsApplication` and I've managed to print the restart file but, once I try to load it, it crashes without any msg (`Release`and `FullDebug`).

I know that in order to be able to use the restart it is necesary to add the serializer to the elements, conditions and constitutive laws of the problem (already done that hopefully) but I do not know if I am missing something...

**Scope**
- Execution
- PfemFluidDynamicsApplication

**Comment by mpentek** [comment]
FluidDynamicsApp and StructuralMechanicsApp works with restart, both OpenMP and MPI, so it will by something specific to the app.

**Comment by AlejandroCornejo** [comment]
> FluidDynamicsApp and StructuralMechanicsApp works with restart, both OpenMP and MPI, so it will by something specific to the app.

Yes! This is the first thing I tested to be confident with it :). My question is more about the "requirements" or "conditions" that must be fulfilled in order to properly work. THX in any case

**Comment by philbucher** [comment]
I recommend using the ascii format (this can be chosen in the restart utility) when debugging restarts
and afaik the only requirement is to have all the variables in the serializer
