### ISSUE TITLE
add -Wl,--no-as-needed -ldl to build scripts of Linux 

### ISSUE THREAD

**Issue by Vahid-Galavi** [KratosMultiphysics/Kratos#8414]
**Description**
In order to be able to load dynamic link libraries (shared libraries) in an application, we need to add the following compile options to the build scripts:

-Wl,--no-as-needed -ldl

Can we add these options to the template build scripts?

**Comment by roigcarlo** [comment]
Sure, I would add it directly to CMakeLists.txt to be honest, but both should work both ways

**Comment by armingeiser** [comment]
In LinearSolversApp we have added them to CMakeLists.txt as @roigcarlo  suggests: 

https://github.com/KratosMultiphysics/Kratos/blob/62a6224dc27c53f853c49d4e9b76b6be22735180/applications/LinearSolversApplication/CMakeLists.txt#L35

**Comment by philbucher** [comment]
@Vahid-Galavi can you make a corresponding PR?
I think it is easier to decide then

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee approves the idea.

@Vahid-Galavi would you please make a pull request for that?

**Comment by Vahid-Galavi** [comment]
@pooyan-dadvand I have just done a pull request for this issue.
