### ISSUE TITLE
[dem] Check if the intersection function should use geom.size() or geom.WorkingSpaceDimension()

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#8444]
**Description**
This doubt comes from PR #8428. @joaquinirazabal , can you take a look when possible?
Tagging @KlausBSautter 

**TODO**
[ ]  Check if the intersection function should use geom.size() or geom.WorkingSpaceDimension() in GeometryFunctions.h

**Comment by KlausBSautter** [comment]
To clarify:
It used to be `geom.size()` before I changed it to `geom.WorkingSpaceDimension()` a while ago. This was when I started my work and I am sorry but cannot really remember what I thought back then. When I wrote the additional function for a the RigidEdge/Face1N3D I realized that this should be `geom.size()`, I think.

By looking at the code we see that 
if `geom.size() == 1: VertexCheck`
if `geom.size() == 2: Edge&VertexCheck`
if `geom.size() == 3: Face&Edge&VertexCheck`

**Comment by joaquinirazabal** [comment]
Hi @KlausBSautter and @maceligueta. I think you are talking about the file rigid_face_geometrical_object_configure.h

**geom.size()** is correct, **geom.WorkingSpaceDimension()** is wrong. The explanation is exactly what Klaus pointed out:

if geom.size() == 1: VertexCheck
if geom.size() == 2: Edge&VertexCheck
if geom.size() > 2: Face&Edge&VertexCheck

The working dimension does not apply here.

Thank you for finding the error, now it is ok.

**Comment by KlausBSautter** [comment]
then we can close this. Thanks @joaquinirazabal :)
