### ISSUE TITLE
[Structural] Lumped factors in Massmatrix for TL

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#8457]
Hi, I stumbled across the following lines in the base solid element:
https://github.com/KratosMultiphysics/Kratos/blob/53f15798b4dc46d8a0f60c3ca1cbece0be3a1557/applications/FemToDemApplication/custom_elements/base_solid_element.cpp#L1689-L1698

and ran a simple test with a hexahedron and a tetrahedron:
[check_lump.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/6109702/check_lump.gid.zip)

With the lumped mass matrix enabled. Because I wanted to use the `GetGeometry().LumpingFactors( lumping_factors )` for the membrane element too. But when I checked the lumping factors I saw that they were changing for the hexahedron within the dynamic simulation.

e.g. :
lumping_factors : (0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.125)
lumping_factors : (0.121928,0.121928,0.128072,0.128072,0.121928,0.121928,0.128072,0.128072)
lumping_factors : (0.126804,0.126804,0.123196,0.123196,0.126804,0.126804,0.123196,0.123196)

For the tetrahedron and a triangle, the lumping factors are the same anyway all the time (independent of the shape). But for quads and hexahedrons, the lumping factors of course depend on the shape but for a TL element formulation they should stay constant over time. I talked to colleagues (@rolandwuechner) and they agreed with me on that, let me know if this is wrong.

So I calculate the lumping factors w.r.t. the reference configuration for the membrane element and I am wondering if this is a mistake for the total lagrangian element which inherits from the base solid element and apparently re-calculates the lumping factors based on the current configuration.

**Comment by loumalouomega** [comment]
This may be because there are three algorithms for the lumped factors in the geometry. Maybe there is an error in the input.

**Comment by philbucher** [comment]
probably again an issue that we cannot compute stuff on the original configuration

**Comment by loumalouomega** [comment]
> probably again an issue that we cannot compute stuff on the original configuration

That makes even more sense

**Comment by KlausBSautter** [comment]
> This may be because there are three algorithms for the lumped factors in the geometry. Maybe there is an error in the input.

I checked the other options and from 
lumping_factors : (0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.125)

we get
lumping_factors : (0.119421,0.119421,0.130579,0.130579,0.119421,0.119421,0.130579,0.130579)
lumping_factors : (0.116633,0.116633,0.133367,0.133367,0.116633,0.116633,0.133367,0.133367)
lumping_factors : (0.108636,0.108636,0.142112,0.142112,0.108636,0.108636,0.142112,0.142112)
for the 3 different enum possibilities.

So I guess this is wrong right now?

**Comment by loumalouomega** [comment]
> > This may be because there are three algorithms for the lumped factors in the geometry. Maybe there is an error in the input.
> 
> I checked the other options and from
> lumping_factors : (0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.125)
> 
> we get
> lumping_factors : (0.119421,0.119421,0.130579,0.130579,0.119421,0.119421,0.130579,0.130579)
> lumping_factors : (0.116633,0.116633,0.133367,0.133367,0.116633,0.116633,0.133367,0.133367)
> lumping_factors : (0.108636,0.108636,0.142112,0.142112,0.108636,0.108636,0.142112,0.142112)
> for the 3 different enum possibilities at the end of the dynamic simulation.
> 
> So I guess this is wrong right now?

Probably should be computed at the reference configuration. But the methods are correct. It is documented in the code and with the proper tests

**Comment by KlausBSautter** [comment]
> Probably should be computed

Yes, that is what I meant :)

**Comment by RiccardoRossi** [comment]
do think into account that the density distribution would also vary.

considering tjat the mass should remain the same

**Comment by loumalouomega** [comment]
I will post a potential solution soon, but one point @AlejandroCornejo do you still have your solid copy/pasted?, you will need to update to recent changes or unify to depend on the StructuralApp.

**Comment by sunethwarna** [comment]
@KratosMultiphysics/technical-committee is concerned about the issue raised by @RiccardoRossi, hence we would not promote using these lumping factors as their usage is unsafe in some specific cases.
