### ISSUE TITLE
Monolithic FSI in Kratos

### ISSUE THREAD

**Issue by najianaslreza** [KratosMultiphysics/Kratos#846]
Hi guys,

I am new to Kratos and I have couple of questions might be silly to you :-).
We are working on Coupled adjoint based sensitivity analysis for FSI. Long story short, we want to use Kratos for monolithic FSI and monolithic adjoint FSI afterwards. We are mostly interested in internal flows and want to give a shot to monolithic solver.

As far as I got into the code, we have FSIapplication which has partitioned implementation. Now a crucial question for me is that Is there any specific reason that monolithic FSI has not been implemented yet ? 

If one wants to make this solver, I can think of two approaches at the moment:
1. Make a new element which can be served as both fluid and structure ?
2. Use the existing and available elements in different applications, pretty like the current FSIapplication, and construct a full and big jacobian ?
Which one is preferred ?!  Maybe reasons !

Last but not least, do you know any other group or people working on or interested in it? 

Any information is highly appreciated.

Cheers, 

reza

 @adityaghantasala @RiccardoRossi @rubenzorrilla @pooyan-dadvand @msandre

**Comment by msandre** [comment]
Hi Reza, I don't know of anybody doing monolithic fsi right now although I believe it has been done in the past. The way to do it depends on what you want to do. You probably want to use the vms.h element in FluidMechanicsApplication, one of the structural elements in StructuralMechanicsApplication and the ALE element structural similarity. To add coupling conditions you can look at Aditya's multipoint constraints or try writing your own condition. For time discretization I would try looking at the bossak scheme. I think it works for fluid and structure.

**Comment by pooyan-dadvand** [comment]
It has been done in the past by PFEM guys as @msandre mentioned and is possible. But there are many arguments in favor of staggered methods also related to your questions:
1. Making an element to do fluid and structure is too rigid (which structure element?) and not modular
2. It is possible to reuse the elements from fluid and structure to assemble on matrix (skipping the details for now) but for doing that a jacobian free approach  used in FSI application is more appropriated.

**Comment by najianaslreza** [comment]
@msandre 
Thanks Mike. Actually me and Aditya are working together on this. As you pointed, most probably we will follow the same approach used in ChimeraApplication.

**Comment by najianaslreza** [comment]
@pooyan-dadvand 
Hi Pooyan,
Thanks for your comments. I am also in favor of partitioned FSI but we need monolithic to use as a reference for further developments. I think having monolithic solver alongside the partitioned one is not a bad idea. 
You are absolutely right, using current available elements makes more sense and saves the time.

**Comment by pooyan-dadvand** [comment]
I see, meanwhile I think that @RiccardoRossi is the right person to answer this.

**Comment by loumalouomega** [comment]
Can we close this?

**Comment by najianaslreza** [comment]
I think so.
