### ISSUE TITLE
[MPI] Quaternion<double> and communicator

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#8470]
**Description**
We lack the implementation of the MPI communication of `Quaternion<double>` variable data types. This precludes adding synchronizing directives in functions templated with the data type (e.g. `VariableUtils`).

**Comment by philbucher** [comment]
Do you have a usecase?

**Comment by rubenzorrilla** [comment]
No. But we either remove the `Variable<Quaternion<double>>` instantiations in the `VariableUtils` exports to Python or we add the communication.

**Comment by rubenzorrilla** [comment]
Closing as it was solved in #8589.
