### ISSUE TITLE
Windows CI failing

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#8472]
Dear @KratosMultiphysics/all 

You might have experienced failures in the Windows CI since yesterday evening. This is because Github no longer provides boost in their environment (see https://github.com/actions/virtual-environments/issues/2667)

The @KratosMultiphysics/technical-committee is aware of this and working on a solution. 
Unfortunately no PRs can be merged until this is fixed, sorry for the inconvenience

**Comment by loumalouomega** [comment]
At least we depend of boost as header only, it will be relatively easy to solve (but I assume that CI will take a little longer because the time of downloading and decompressing boost)

**Comment by armingeiser** [comment]
> At least we depend on boost as header only

Could we not provide boost headers the same way we do for pybind, eigen, etc?
Or is there a specific reason to not do so?

**Comment by philbucher** [comment]
> 
> 
> At least we depend on boost as header only, it will be relatively easy to solve (but I assume that CI will take a little longer because of the time of downloading and decompressing boost)

thats essentially what we are trying to figure out right now

**Comment by philbucher** [comment]
> 
> 
> > At least we depend on boost as header only
> 
> Could we not provide boost headers the same way we do for pybind, eigen, etc?
> Or is there a specific reason to not do so?

I think the main reason for this is bcs boost is quite big / has many files
Also we cannot only use ublas, there are many cross-references unfortunately

**Comment by philbucher** [comment]
The problem has been fixed

Please merge master in order to fix the Windows Build in the CI
