### ISSUE TITLE
failure in the c++ tests

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#85]
in kratos/sources/model_part_io.cpp:1651:void ModelPartIO::ReadNodalDataBlock(ModelPart&)
   kratos/sources/model_part_io.cpp:1691:void ModelPartIO::ReadNodalDataBlock(ModelPart&)
   kratos/sources/model_part_io.cpp:553:virtual void ModelPartIO::ReadModelPart(ModelPart&)

    TestTetrahedra3D4RegualrityQuiality Failed with message: 
        Error: Method 'RegualrityQuiality' is not yet implemented for Tetrahedra3D4

in kratos/geometries/tetrahedra_3d_4.h:646:double Tetrahedra3D4<TPointType>::RegualrityQuiality() const [with TPointType = Node<3ul>]

    TestTetrahedra3D4VolumeToAverageEdgeLength Failed with message: 
        Error: Check failed becuase geomTriRect->Quality(criteria) = 0.585786 is not near to -1.0 = -1 within the tolerance 1e-06
in kratos/tests/geometries/test_tetrahedra_3d_4.cpp:276:virtual void Testing::TestTetrahedra3D4VolumeToAverageEdgeLength::TestFunction()

    TestTetrahedra3D4VolumeToEdgeLengthQuality Failed with message: 
        Error: Check failed becuase geomTriRect->Quality(criteria) = 0.839947 is not near to -1.0 = -1 within the tolerance 1e-06
in kratos/tests/geometries/test_tetrahedra_3d_4.cpp:261:virtual void Testing::TestTetrahedra3D4VolumeToEdgeLengthQuality::TestFunction()

    TestTetrahedra3D4VolumeToRMSEdgeLength Failed with message: 
        Error: Check failed becuase geomTriRect->Quality(criteria) = 0.839947 is not near to -1.0 = -1 within the tolerance 1e-06
in kratos/tests/geometries/test_tetrahedra_3d_4.cpp:291:virtual void Testing::TestTetrahedra3D4VolumeToRMSEdgeLength::TestFunction()

    TestTetrahedra3D4VolumeToSurfaceAreaQuality Failed with message: 
        Error: Method 'VolumeToSurfaceAreaQuality' is not yet implemented for Tetrahedra3D4

in kratos/geometries/tetrahedra_3d_4.h:660:double Tetrahedra3D4<TPointType>::VolumeToSurfaceAreaQuality() const [with TPointType = Node<3ul>]

**Comment by roigcarlo** [comment]
@RiccardoRossi I am aware they are failing (the geometry ones). I will fixit asap.

**Comment by roigcarlo** [comment]
@RiccardoRossi and @pooyan-dadvand 
Regarding the `TestTetrahedra3D4VolumeToSurfaceAreaQuality`. This test is not implemented because we have no `SurfaceArea()` in the geometry.

I can remember having a discussion whether the `Area()` function should calculate this for 3D geometries or not.

Right now `Area()` is an alias for `Volume()` for 3D geometries and the other way around for 2D geometries.

Should I use `Area()` as `SurfaceArea()` in 3D ( and change its implementation) or should I make another different function?

**Comment by RiccardoRossi** [comment]
Hi Carlos,

than this issue is closed?

**Comment by roigcarlo** [comment]
Well the tests now check that they fail correctly, so I supose that we can close that, but maybe is a good idea to open another issue to so to remember that there are 2 implementations missing, or extend the current PTR that is fixing the problem with the volumeToLenght ratio

I'll do that tomorrow morning.

Anyway, it will be closed automatically when we merge #101
