### ISSUE TITLE
Related to the header file "calculate_octree_signed_distance_to_3d_skin_process.h"

### ISSUE THREAD

**Issue by ashishdarekar** [KratosMultiphysics/Kratos#8508]
**Description**
While Porting OMP stuff to Parallel Utilities (in PR #8507):
I have observed that, this [header file](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/calculate_octree_signed_distance_to_3d_skin_process.h) is not included in the compilation or not used anymore, is it so? Because, I made some mistakes in this file (which I got to know later) not being recognized while compilation (including some syntax errors).

**Scope**
- KratosCore

**Comment by philbucher** [comment]
@KratosMultiphysics/technical-committee is this file used?
It is included nowhere, can we just remove it?

**Comment by rubenzorrilla** [comment]
At first glance, this seems a protoversion of our current signed distance algorithm. I've never used it and I don't think we will introduce it in our current level set methods.

In any case, I'd wait @pooyan-dadvand to give his opinion.

**Comment by pooyan-dadvand** [comment]
In fact, this is a simplified version of the embedded mesh generator of the GiD. We used to work with it when we had moving things and also as a prototype of the GiD one. The complete version is included in the GiD. 

So, I assume that now we can safely remove it.

**Comment by philbucher** [comment]
@ashishdarekar can you please make a PR with removing this file?
Thx
