### ISSUE TITLE
Kratos Precompiled Versions 5.1.0/5.1.1

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#851]
Dear all,

We want to use the 5.1.0/5.1.1 Precompiled (Windows and Linux, 64bit) for teaching at TUM. Unfortunately, the applications which were compiled do not seem to be consistent (for e.g. 5.1.0 Win is different from 5.1.0 Linux).

Could you please help out with a Linux version with the similar packages as 5.1.0 Win 64 (so for us FluidDynamicsApplication, ALEapplication, StructuralMechanicsApplication are important). Linux 5.1.0 is missing ALE. We intend to use it with GiD13.1.8d.

Máté

**Comment by pooyan-dadvand** [comment]
Why you need the 5.1.0? The 5.1.1 which has few bug fixes. @roigcarlo the windows and  linux versions don't use the same source?

**Comment by roigcarlo** [comment]
They use the same code.
The list of applications in each one is differed indeed and its the one in: https://github.com/KratosMultiphysics/Kratos/projects/5, as mentioned in #611. If there is some extra lib in one of the versions sorry but was not officially supported/tested. I will try to make a cleanup next time so this doesn't lead to confusion

**Comment by roigcarlo** [comment]
Also, the version is tagged so you can see the status of the code at the specific moment when the release was made: https://github.com/KratosMultiphysics/Kratos/commit/1be1c4f446564a4839c976fc67ac23889ac31cc2

Since a next Release is scheduled, we should add ALE there, if not I can make a 5.1.2 from the same source but adding the ALE application to it. As you prefer.

**Comment by mpentek** [comment]
@pooyan-dadvand I would happily use any version - as long as both the Windows and Linux one - have ALE as well so that we can run FSI. The donwloads from the GID website did not meet this criteria. 5.1.0 for Win had ALE, 5.1.1 was completely missing it.

@roigcarlo either of your solutions - whether a 5.1.2 or the new release - would work. As said, because we use it for teaching, it would be preferable to have it pre-compiled and same for Windows and Linux. The applications that we intend to use is FluidDynamics, ALE and StructuralMechanics. Others we do not specifically need. Do you have an approximate timeline for the next release?

**Comment by roigcarlo** [comment]
@mpentek Next release will be this November, but I should be able to make a 5.1.2 by Thursday/Friday if it only requires adding the ALE application.

**Comment by mpentek** [comment]
@roigcarlo 5.1.2 for Win and Linux would be great, yes ALE is needed. The applications list from 5.1.0 (for Win) would be enough for us. November is unfortunately too tight of a deadline...

**Comment by roigcarlo** [comment]
No problem then, I will ping you once they are released

**Comment by roigcarlo** [comment]
@mpentek We have just released 5.1.2: [Kratos 5.1.2](https://github.com/KratosMultiphysics/Kratos/releases/tag/v5.1.2)

It contains the precompiled binaries for win(x86), win(x64) and linux(x64)
It should contain as well ALEApplication along with the others that were already in v5.1.1.

Could you check that this version works for you?

**Comment by mpentek** [comment]
hi @roigcarlo thanks for the download link, it is highly appreciated! I just looked through the python scripts, I think everything that we need is there. Will update you as soon as we tested them. 

P.S: is by chance/mistake the win64 written as 5.1.0 or it is really that version? it works for us, just wanted to be sure

**Comment by roigcarlo** [comment]
Ups, copy paste error sorry :P, its the 5.1.2. It should have the correct name now

**Comment by roigcarlo** [comment]
@mpentek Did you have the chance to test everything?

**Comment by mpentek** [comment]
@roigcarlo we are testing the precompiled versions for Windows and Linux currently as a preparation for the course. It seems that under Windows we can run our FSI case, Linux however has on issue with the CSD part. Here is the description of the symptom when running an example of the StructuralMechanics Application (Fluid Dynamics seems to work fine):


_Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.1.0-1be1c4f
Importing    KratosFluidDynamicsApplication
Initializing KratosFluidDynamicsApplication... 
Traceback (most recent call last):
  File "MainKratos.py", line 5, in <module>
    from KratosMultiphysics.ExternalSolversApplication import *
  File "/home/kodakkal/Software/gid13.1.8d-x64/problemtypes/kratos.gid/exec/Kratos/KratosMultiphysics/ExternalSolversApplication.py", line 2, in <module>
    from KratosExternalSolversApplication import *
ImportError: libmvec.so.1: cannot open shared object file: No such file or directory
KRATOS TERMINATED WITH ERROR_

At first, the case seems to run when commenting out the _import ExternalSolversApplication_ line, but encounters it again later.

**Comment by roigcarlo** [comment]
Hi @mpentek, let me look into it.
Could you tell me which version of linux are you using (ubuntu 14, suse, etc..)?

**Comment by roigcarlo** [comment]
@mpentek I've investigated and it seems that it may be a problem with the math lib as the release was compiled with support for OpenMP 4.0, which include vectorial operations. This may cause problem in old systems (Ubuntu 14.04 or earlier).

I've just updated the release package so it includes the missing libmvec.so. Could you check if this solves the issue?

If you proffer you can also install a modern version of gcc ( 5 or higher) in the machine and the problem should disappear.

**Comment by mpentek** [comment]
@roigcarlo thanks, seems to work fine, meaning that the simulations run through and we get results. Wanted to ask you whether the following "symptom" is due to the precompiled version or not: 
=> when we run an FSI (so have one main script to execute the FluidMechanics Application for the fluid and the StructuralMechanics Application for the structure, with ALEApplication for the mesh moving involved as well)
=> in case the StructuralMechanics part output is in Binary, it will throw a "... MESH block", which seems to show that there will be an extra block created in the bin
=> in case we switch to ASCII output for the structure part, all is fine and GiD can display the results

By the way, when are you planning the newer release? We are working on 1-2 script for the mesh moving which are missing from the main repository, probably will commit this week or so.

**Comment by roigcarlo** [comment]
@mpentek Glad it works now. The new release is scheduled for the end of this month but the branch release will be created by the end of the week so try to make a PR with the scripts by then if you want them included in the 5.2.

If it is very important we can try to squish it latter in to the branch release, but if you could make it by the end of the week it would help.

> => when we run an FSI (so have one main script to execute the FluidMechanics Application for the fluid and the StructuralMechanics Application for the structure, with ALEApplication for the mesh moving involved as well)
=> in case the StructuralMechanics part output is in Binary, it will throw a "... MESH block", which seems to show that there will be an extra block created in the bin
=> in case we switch to ASCII output for the structure part, all is fine and GiD can display the results

About this, I am not quite sure to understand the problem, but using a precompiled release should not have any effect with the output.

Can you post the problematic script here? @jcotela Can you take a look?

**Comment by jcotela** [comment]
@roigcarlo  sure, I can look into the output issue. @mpentek can you send me the model? Just email it if it is more convenient for you.

**Comment by mpentek** [comment]
@jcotela this here is our "minimal" FSI example https://syncandshare.lrz.de/dl/fi6SsLq6Y9jypBNEXnoqGeJi/FSI_minimal. It works with Kratos 5.1.2 Precompiled (see the thread). Nonetheless, we can only visualize the StructuralMechanics results as long as in the ProjectParametersCSD.json the output it set from Binary to Ascii.

Please note, that this example and the precompiled we use for teaching purposes, but the problem might persist elsewhere as well.

For the precompiled to work with our example, you will need to add 3 (actually only 2 are directly used for this case, and yes, it is a syntax not compatible with Python 2.7) additional python scripts to the ALEApplication/python_scripts, available here: https://syncandshare.lrz.de/dl/fiBzGzCNcCUCerD4UDS8mrei/ALE_Solver_FractionalStep.

The ALE files would be probably useful for the release, such that ALE works for fractional step and a simple change in the PorjectParametersCFD.json permits the usage of ALEFractionStep. So this might be comitted as well, wanted to check first with you, maybe also Andreas W. and Michael A.

**Comment by mpentek** [comment]
@roigcarlo : one more error popped up for Ubuntu14.04 LTS:

_Current thread 0x00007f56b5ece780 (most recent call first):
Aborted (core dumped)
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ImportError: No module named 'encodings'_

In case I try to run a Linux batch job the above happens with the core being dumped. For non-batch jobs, it will show the error but run. Under Ubuntu 16.04 LTS I did not get this issues. Might be relevant for the next release, for us it is still ok.

**Comment by roigcarlo** [comment]
I will take a look thx

**Comment by pooyan-dadvand** [comment]
@mpentek would you please add the script you mentioned before to the master?

**Comment by mpentek** [comment]
@pooyan-dadvand if you are referring to the pythons scripts for ALE, I am working on it, these are waiting for review as in #995  and a final commit to the master.

**Comment by jcotela** [comment]
Hi @mpentek, regarding your problem with the structure output, it is caused by calling `structure_gid_output.ExecuteBeforeSolutionLoop()` twice in your main script (lines 285 and 511). Commenting either of them should fix it. Maybe it would be a good idea to add internal checks in the gid process to check for this, I'll consider it.

**Comment by mpentek** [comment]
@jcotela great, thanks! A nasty bug from our side...

**Comment by mpentek** [comment]
@roigcarlo with #995 I added the additional python scripts for the ALE and with #1002 the last formatting bug was also removed -> be a nice include for the release, if still possible -> I marked it with the label Release -> is that enough?

**Comment by roigcarlo** [comment]
Yep, its ok, I will create separate PR for the Release and add you in the review
