### ISSUE TITLE
How to replace the ExternalSolversApplication with something else?

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#8513]
**Description**
For particlemechanicsapp, threre is one probleme when running test.

**Error**
  File "C:\Users\gzm\Desktop\KRATOS\Kratos\bin\Release\KratosMultiphysics\ParticleMechanicsApplication\mpm_solver.py", line 353, in _CreateLinearSolver
    return linear_solver_factory.ConstructSolver(linear_solver_configuration)
  File "C:\Users\gzm\Desktop\KRATOS\Kratos\bin\Release\KratosMultiphysics\python_linear_solver_factory.py", line 26, in ConstructSolver
    import_module("KratosMultiphysics." + app_name)
  File "C:\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
**ModuleNotFoundError: No module named 'KratosMultiphysics.ExternalSolversApplication'**

**Comment by philbucher** [comment]
you should use the LinearSolversApplication
@KratosMultiphysics/mpm

**Comment by ZhimingGuo** [comment]
The question is how to modified or replace **ExternalSolversApplication** with **LinearSolversApplication**?  in which python file?

**Comment by ZhimingGuo** [comment]
Iｔｒｉｅｄpython_linear_solver_factory.py

**Comment by ZhimingGuo** [comment]
I tried to delete the ExternalSolversApplication line in python_linear_solver_factory.py, but it did work.

**Comment by philbucher** [comment]
which version of Kratos do you use?

**Comment by philbucher** [comment]
and could you share your ProjectParameters?

**Comment by ZhimingGuo** [comment]
{
    "problem_data"     : {
        "problem_name"  : "granular_flow_2D",
        "parallel_type" : "OpenMP",
        "echo_level"    : 0,
        "start_time"    : 0.0,
        "end_time"      : 2.0
    },
    "solver_settings"  : {
        "solver_type"                        : "Dynamic",
        "model_part_name"                    : "MPM_Material",
        "domain_size"                        : 2,
        "echo_level"                         : 0,
        "analysis_type"                      : "non_linear",
        "time_integration_method"            : "implicit",
        "scheme_type"                        : "newmark",
        "model_import_settings"              : {
            "input_type"     : "mdpa",
            "input_filename" : "granular_flow_2D_Body"
        },
        "material_import_settings"           : {
            "materials_filename" : "ParticleMaterials.json"
        },
        "time_stepping"                      : {
            "time_step" : 5e-5
        },
        "convergence_criterion"              : "residual_criterion",
        "displacement_relative_tolerance"    : 0.0001,
        "displacement_absolute_tolerance"    : 1e-9,
        "residual_relative_tolerance"        : 0.0001,
        "residual_absolute_tolerance"        : 1e-9,
        "max_iteration"                      : 20,
        "problem_domain_sub_model_part_list" : ["Parts_Parts_Auto1","Parts_Parts_Auto2"],
        "processes_sub_model_part_list"      : ["DISPLACEMENT_Displacement_Auto1"],
        "grid_model_import_settings"         : {
            "input_type"     : "mdpa",
            "input_filename" : "granular_flow_2D_Grid"
        },
        "pressure_dofs"                      : false,
        "linear_solver_settings"             : {
            "solver_type" : "ExternalSolversApplication.super_lu",
            "scaling"     : false
        }

    },
    "processes"        : {
        "constraints_process_list" : [{
            "python_module" : "assign_vector_variable_process",
            "kratos_module" : "KratosMultiphysics",
            "Parameters"    : {
                "model_part_name" : "Background_Grid.DISPLACEMENT_Displacement_Auto1",
                "variable_name"   : "DISPLACEMENT",
                "constrained"     : [true,true,true],
                "value"           : [0.0,0.0,0.0],
                "interval"        : [0.0,"End"]
            }
        }],
        "loads_process_list"       : [],
        "list_other_processes"     : [],
        "gravity"                  : [{
            "python_module" : "assign_gravity_to_particle_process",
            "kratos_module" : "KratosMultiphysics.ParticleMechanicsApplication",
            "process_name"  : "AssignGravityToParticleProcess",
            "Parameters"    : {
                "model_part_name" : "MPM_Material",
                "variable_name"   : "MP_VOLUME_ACCELERATION",
                "modulus"         : 9.81,
                "direction"       : [0.0,-1.0,0.0]
            }
        }]
    },
    "output_processes" : {
        "body_output_process" : [{
            "python_module" : "particle_gid_output_process",
            "kratos_module" : "KratosMultiphysics.ParticleMechanicsApplication",
            "process_name"  : "ParticleMPMGiDOutputProcess",
            "help"          : "This process writes postprocessing files for GiD",
            "Parameters"    : {
                "model_part_name"        : "MPM_Material",
                "output_name"            : "granular_flow_2D_Body",
                "postprocess_parameters" : {
                    "result_file_configuration" : {
                        "gidpost_flags"       : {
                            "GiDPostMode"           : "GiD_PostBinary",
                            "WriteDeformedMeshFlag" : "WriteDeformed",
                            "WriteConditionsFlag"   : "WriteConditions",
                            "MultiFileFlag"         : "SingleFile"
                        },
                        "file_label"          : "step",
                        "output_control_type" : "time",
                        "output_frequency"    : 0.01,
                        "body_output"         : true,
                        "node_output"         : false,
                        "skin_output"         : false,
                        "plane_output"        : [],
                        "gauss_point_results" : ["MP_VELOCITY","MP_DISPLACEMENT"]
                    },
                    "point_data_configuration"  : []
                }
            }
        }],
        "grid_output_process" : [{
            "python_module" : "gid_output_process",
            "kratos_module" : "KratosMultiphysics",
            "process_name"  : "GiDOutputProcess",
            "help"          : "This process writes postprocessing files for GiD",
            "Parameters"    : {
                "model_part_name"        : "Background_Grid",
                "output_name"            : "granular_flow_2D_Grid",
                "postprocess_parameters" : {
                    "result_file_configuration" : {
                        "gidpost_flags"       : {
                            "GiDPostMode"           : "GiD_PostBinary",
                            "WriteDeformedMeshFlag" : "WriteDeformed",
                            "WriteConditionsFlag"   : "WriteConditions",
                            "MultiFileFlag"         : "SingleFile"
                        },
                        "file_label"          : "step",
                        "output_control_type" : "time",
                        "output_frequency"    : 0.01,
                        "body_output"         : true,
                        "node_output"         : false,
                        "skin_output"         : false,
                        "plane_output"        : [],
                        "nodal_results"       : ["DISPLACEMENT","REACTION"]
                    },
                    "point_data_configuration"  : []
                }
            }
        }]
    }
}

**Comment by ZhimingGuo** [comment]
Find the place to modified in ProjectParameters, Thanks.

**Comment by philbucher** [comment]
cool 
as you found yourself you specified explicitly to use the ExternalSolversApp
