### ISSUE TITLE
[Mapping] How to do mapping when some ModelParts do not exist on some ranks?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#8515]
I am currently developing the Mapping/CoSim when one solver runs on not all ranks (in MPI). In this case the `ModelParts` of this solver don't exist on the other ranks.
E.g. FSI with 10 MPI Processes, where Fluid uses all 10 but Structure only uses 5 (rank 0-4)
Since I am doing black box coupling I cannot modify the solvers
The input for the `MapperFactory` is two `ModelPart`s. On rank 0-4 this is ok since both the Fluid and the Structure exist on this rank, but ranks 5-9 don't have the Structure `ModelPart`s
I can ofc pass a dummy `ModelPart` but I am not sure if this is the best solution.
Any thoughts / comments would be appreciated :)

@rubenzorrilla @adityaghantasala @pooyan-dadvand @RiccardoRossi @roigcarlo @ddiezrod

**Comment by pooyan-dadvand** [comment]
I am not sure if I understood correctly the entire picture. What I see would be to pass the model to the mapper then you may check if you have a model part or just pass. But I suppose that the question is not this....

**Comment by ddiezrod** [comment]
> I am not sure if I understood correctly the entire picture. What I see would be to pass the model to the mapper then you may check if you have a model part or just pass. But I suppose that the question is not this....

I think the point is that when you are doing everything from one "executable" you always have the information of the model parts. So, even if one processor does not have any element of the structure, it will have the empty model part "structure" and everything will work fine.

This however will not work in CoSim as some processors will know nothing about the structure model part... Honestly, sending a dummy  empty model part is the only option that comes to my mind..

**Comment by philbucher** [comment]
thx for the comments!

> However, this will not work in CoSim as some processors will know nothing about the structure model part... Honestly, sending a dummy empty model part is the only option that comes to my mind..

yes exactly this is the issue. I guess I will stick with a dummy `ModelPart` for now, maybe I find a better solution or someone has a better suggestion

**Comment by philbucher** [comment]
implemented in #9182
