### ISSUE TITLE
[MLMC] Test is failing

### ISSUE THREAD

**Issue by mrhashemi** [KratosMultiphysics/Kratos#8528]
**Description**
test_MultilevelMonteCarloApplication.py is failing.

**Scope**
Small tests

Could you please check if everything is working fine with the current state of the code?
I am working on the level-set convection and do not think it has any interferences with this application.

**Comment by riccardotosi** [comment]
Hi @mrhashemi , I have run #8527 (I cannot compile master branch for the issue solved in the PR) and tests run fine.

Can you post the error?

**Comment by mrhashemi** [comment]
> Hi @mrhashemi , I have run #8527 (I cannot compile master branch for the issue solved in the PR) and tests run fine.
> 
> Can you post the error?

Hi, 
Actually, I do not have the necessary requirements to compile the MultilevelMonteCarloApplication on my machine. It is the error I encounter in [this PR](https://github.com/KratosMultiphysics/Kratos/pull/8519). I just wanted to be sure that the tests and the MLMC application do not rely on the levelset_convection.

**Comment by mrhashemi** [comment]
@riccardotosi do you use "convection_diffusion_settings" in your implementation? This might create some discrepancies.

**Comment by riccardotosi** [comment]
> 
> 
> @riccardotosi do you use "convection_diffusion_settings" in your implementation? This might create some discrepancies.

Yes, some tests actually use the convection diffusion analysis stage, and consequently the `convection_diffusion_settings`

**Comment by riccardotosi** [comment]
Let me know if you need some help in understanding what's going on in the MLMC application!

**Comment by mrhashemi** [comment]
> Let me know if you need some help in understanding what's going on in the MLMC application!

It would be helpful if you can point out where convection diffusion/settings is called in MLMC application.

**Comment by riccardotosi** [comment]
One test uses for example this [analysis stage](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MultilevelMonteCarloApplication/tests/poisson_square_2d_kratos/simulation_definition.py#L26). Settings of this test are defined [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MultilevelMonteCarloApplication/tests/poisson_square_2d_kratos/problem_settings/parameters_poisson_square_2d_coarse.json) and [here](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MultilevelMonteCarloApplication/tests/poisson_square_2d_kratos/problem_settings/parameters_poisson_square_2d_finer.json).

Other tests use the conv-diff application, but in a similar way.

**Comment by riccardotosi** [comment]
~~~bash

Running MultilevelMonteCarloApplication tests
.........../__w/Kratos/Kratos/bin/Custom/applications//MultilevelMonteCarloApplication/tests/test_MultilevelMonteCarloApplication.py
Completed MultilevelMonteCarloApplication tests with exit code 1!
~~~

I do not have any clue about this error. Zero information :/

**Comment by mrhashemi** [comment]
> ```shell
> Running MultilevelMonteCarloApplication tests
> .........../__w/Kratos/Kratos/bin/Custom/applications//MultilevelMonteCarloApplication/tests/test_MultilevelMonteCarloApplication.py
> Completed MultilevelMonteCarloApplication tests with exit code 1!
> ```
> 
> I do not have any clue about this error. Zero information :/

Maybe I should compile MLMC to resolve this issue; for turning ON the MLMC application on my PC, is there any special requirements (downloading external packages)? Is there any guide for it?

**Comment by riccardotosi** [comment]
The [README](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MultilevelMonteCarloApplication/README.md) is the guide. You just need to turn it ON to run the basic test which is failing (if I correctly guessed from my other comments). Otherwise, you need the meshing application and Mmg.

**Comment by mrhashemi** [comment]
@riccardotosi thank you for your comments. New "gradient_variable" is needed to be defined to prevent a segmentation fault.

**Comment by riccardotosi** [comment]
Happy my suggestion helped you!
