### ISSUE TITLE
Computing different derivatives for sensitivity analysis of structural problems

### ISSUE THREAD

**Issue by MFusseder** [KratosMultiphysics/Kratos#853]
Hey all!

I am currently working on sensitivity analysis for structural mechanics problems. Before describing my problem I like the tell you the context in which my trouble occurred.

As you may know the element base class for sensitivity analysis has two new functions:

`    virtual void CalculateSensitivityMatrix( ... )`

These functions are used in our adjoint elements which are derived from elements in the Structural Mechanics Application. The task of this functions is to compute the so called pseudo-load which is the derivative of the RHS w.r.t. the design variables. 
But for some response functions different derivatives are necessary (e.g. derivative of mass matrix, LHS, ...). In order to compute also this derivatives @RiccardoRossi and @pooyan-dadvand suggested on their latest visit here in Munich to use the `Calculate(...)` functions of the element. To communicate with the  `Calculate(...)`  i.e. tell them which element component has to be derived, which design variable shall be used, what is the disturbance measure for finite differences and so on,  they gave us the hint to establish a class (we called it `FiniteDifferencesUtilities`) which contains all the necessary information as member variables. The next step is to create a variable of this class:

`KRATOS_DEFINE_VARIABLE( FiniteDifferencesUtilities::Pointer, FINITE_DIFFERENCE_INFORMATION );`

After the variable is definded, created and registered the plan is to set the variable to the elements within the response functions by:

`SetValue(FINITE_DIFFERENCE_INFORMATION, FD_calculate_gradient)`

This method works in principle very well but due to the current implementation I faced the following problem. The response functions and the adjoint elements are currently located in different applications (the response functions are in the ShapeOptimizationApplication  and the adjoint elements are in the StructuralMechanicsApplication). The `FiniteDifferencesUtilities`-class and also the corresponding variable we placed in ShapeOptimizationApplication. 
When asking now within the adjoint elements for the necessary information with

`FiniteDifferencesUtilities::Pointer FD_calculate_gradient = this->GetValue(FINITE_DIFFERENCE_INFORMATION) `

now the following problem occurs: the class and also the variable are not known in the StructuralMechanicsApplication. Of course one can include the ShapeOptimizationApplication in the CMakeLists of the structure app, but this is definitely not a good solution. For test reasons I did this inclusion of the ShapeOptimizationApplication in the StructuralMechanicsApplication, but still there is the problem of making the VARIABLE defined in the ShapeOptimizationApplication known to the StructuralMechanicsApplication.  I tried it with

`const Variable<FiniteDifferencesUtilities::Pointer> & rFINITE_DIFFERENCE_INFORMATION =
           	  KratosComponents<Variable<FiniteDifferencesUtilities::Pointer> >::Get("FINITE_DIFFERENCE_INFORMATION"); `

but this does not work.

Is there a possibility to resolve this "communication dilemma" in a nice way?

@armingeiser already mentioned  that he would prefer to move the response functions to Structural Mechanics Application. Not only due to the described problem. The main reason for his idea is that the responses  functions describe responses for structural problems and should therefore placed there.
What do you think about this suggestion?

Thanks in advance for your help!

Best wishes Martin

**Comment by pooyan-dadvand** [comment]
Just to say that at this moment (to be updated) having a duplicated variable in two applications will lead to undefined behavior and you should avoid it by adding that variable to core variables.

**Comment by msandre** [comment]
+1 for Pooyan's solution. Besides that I think the problem with the above code is you should ask KratosComponents for a reference, not a smart pointer.

**Comment by MFusseder** [comment]
Thank you for your hints. I will try now both suggestions.

**Comment by AndreasWinterstein** [comment]
@msandre and @MFusseder can we close this issue?

**Comment by armingeiser** [comment]
can be closed.
