### ISSUE TITLE
[Core] SVD utils not working with rectangular matrices

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#8535]
**Description**
I tried the SVD decomposition in the `svd_utils` with a rectangular matrix (m>n) and, as far as I understand, it is not working properly as the product of SVD doesn't give the original matrix. This is not happening with square matrices.

Aside of this, we should throw an error to inform the user that m must be larger than n. Right now it is only documented in the code meaning that the utility just segfaults without any information.

**Comment by rubenzorrilla** [comment]
(not sure if this is a bug at all... I did some fast research and I saw that Jacobi algorithm might require some kind of preconditioning)

**Comment by loumalouomega** [comment]
Any minimal code/branch to test?.

I did this long time ago. It is the Jacobi algorithm. I do not remember...

According to Wikipedia: "Jacobi iteration is one of the time-honored methods to compute the spectral decompositionH=VΛVTof a real symmetric matrix H.". I think that implicitly that discards non-square matrices

**Comment by loumalouomega** [comment]
It is m ore or less the following algorithm: https://github.com/zlliang/jacobi-svd/blob/master/jacobi_svd.m (you can try your matrix with this matlab code)

**Comment by rubenzorrilla** [comment]
> Any minimal code/branch to test?.
> 
> I did this long time ago. It is the Jacobi algorithm. I do not remember...
> 
> According to Wikipedia: "Jacobi iteration is one of the time-honored methods to compute the spectral decompositionH=VΛVTof a real symmetric matrix H.". I think that implicitly that discards non-square matrices

I think that Jacobi can be used with non-squared matrices if some kind of preconditioning is done (not sure at all...)

In any case, this would be no longer valid for relatively large matrices. Hence my plan is to use one of the Eigen implementations as these are now available. Having said so, I wouldn't expect too much time on ours (which I'd keep to do auxiliary things as we did so far). IMO throwing an error saying that m is not equal to n and redirecting to the `LinearSolversApplication` one will be enough.

**Comment by loumalouomega** [comment]
I just checked, and should work with non-square. Let me check the implementation, probably I did something stupid.

**Comment by rubenzorrilla** [comment]
Which is the status of this?

**Comment by loumalouomega** [comment]
For the moment still debuging, I don't find the bug, because a priori the code is right (and the residual is converging). I may be doing something wrong

Also, I have not working on this in two weeks

**Comment by rubenzorrilla** [comment]
@loumalouomega any advance on this?

**Comment by loumalouomega** [comment]
> @loumalouomega any advance on this?

Basically I need to rewrite it, and find the time to it. The algorithm I implemented is not generic enough

**Comment by rubenzorrilla** [comment]
> 
> I think that Jacobi can be used with non-squared matrices if some kind of preconditioning is done (not sure at all...)
> 
> In any case, this would be no longer valid for relatively large matrices. Hence my plan is to use one of the Eigen implementations as these are now available. Having said so, I wouldn't expect too much time on ours (which I'd keep to do auxiliary things as we did so far). IMO throwing an error saying that m is not equal to n and redirecting to the `LinearSolversApplication` one will be enough.

Hence, in the meantime I suggest proceeding as I mentioned in here.

**Comment by loumalouomega** [comment]
OK

**Comment by rubenzorrilla** [comment]
> 
> 
> OK

Will you implement the error thrown or you want me to do it either?

**Comment by loumalouomega** [comment]
One sec

**Comment by loumalouomega** [comment]
> One sec

Done

**Comment by rubenzorrilla** [comment]
"Solved" in #9032.
