### ISSUE TITLE
[FreeSurface] State of development, Use for Tuned Liquid Damper

### ISSUE THREAD

**Issue by RiedlAndreas** [KratosMultiphysics/Kratos#8541]
**Description**
I've seen that recently more work and development has been done on the FreeSurface Application. @joaquinirazabal
I want to know what the actual state of the application is? Is it ready to compile ?

I'm currently working on modeling and simulation of Tuned Liquid Damper in Kratos. Basically it's a rectangluar tank with water, that is accelerated. The sloshing of the water and it's resulting forces on the boundaries are used to dampen structural response. Is it possible to use the FreeSurfaceApplication for this case ? 
Besides this I'm already using the PfemDynamics, TwoFluid and ShallowWater Application to compare.

Follow up of: #1658 #7868

**Comment by mpentek** [comment]
There used to be an example with a marine drilling platform with surface waves around it. Perhaps that might have been created with it.

**Comment by joaquinirazabal** [comment]
Hi @RiedlAndreas. The application is ready to compile. I am not sure about what kind of simulations you want to carry out but I think that it may help you. If you are interested in using it you need to compile the FreeSurfaceApplication together with the FluidDynamicsApplication. For preparing the problem I can send you a wizard to use with GiD, are you interested?

The example @mpentek refers was created with this application, there are other newer (but not much): https://www.youtube.com/watch?v=VAvUT-015mM&list=PLiyl-VE6-1ovten2Hsy5lExV7Orna1l26&index=1

**Comment by mpentek** [comment]
> Hi @RiedlAndreas. The application is ready to compile. I am not sure about what kind of simulations you want to carry out but I think that it may help you. If you are interested in using it you need to compile the FreeSurfaceApplication together with the FluidDynamicsApplication. For preparing the problem I can send you a wizard to use with GiD, are you interested?
> 
> The example @mpentek refers was created with this application, there are other newer (but not much): https://www.youtube.com/watch?v=VAvUT-015mM&list=PLiyl-VE6-1ovten2Hsy5lExV7Orna1l26&index=1

Thanks! @joaquinirazabal glad to hear that the example I remembered goes in this direction. From the physics I see there, it is a good candidate for the application @RiedlAndreas aims for

**Comment by RiedlAndreas** [comment]
> 
> 
> Hi @RiedlAndreas. The application is ready to compile. I am not sure about what kind of simulations you want to carry out but I think that it may help you. If you are interested in using it you need to compile the FreeSurfaceApplication together with the FluidDynamicsApplication. For preparing the problem I can send you a wizard to use with GiD, are you interested?
> 
> The example @mpentek refers was created with this application, there are other newer (but not much): https://www.youtube.com/watch?v=VAvUT-015mM&list=PLiyl-VE6-1ovten2Hsy5lExV7Orna1l26&index=1

Thanks! That sounds great. I'll try to compile it and create a problem. I would be happy if you send me the wizard. a.m.riedl@tum.de

**Comment by RiccardoRossi** [comment]
@rubenzorrilla @uxuech
