### ISSUE TITLE
MMG compilation produces many warnings in Docker Image

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#8562]
See title, this bloats the log a lot and makes it harder to read.

Could you please disable the warnings?

**Comment by loumalouomega** [comment]
The library or the utilities/processes?, we should ping if the library to @lcirrottola and @Algiane 

Can you post the log?

**Comment by philbucher** [comment]
it is in MMG itself

you can find the logs in any Docker CI Image build:https://github.com/KratosMultiphysics/Kratos/actions/workflows/build_docker_images_for_ci.yml

It is too many to post them here

I suggested to disable them as MMG is an external lib for us
