### ISSUE TITLE
Missing Serializer in ConvectionDiffusionApplication?

### ISSUE THREAD

**Issue by pau-mar** [KratosMultiphysics/Kratos#8570]
**Description**
I am trying to generate Restart files for a simulation, but I am having trouble when saving the files. The context of the simulation is one in which there is a bubble of gas moving inside a fluid, therefore the Level-set convection is performed. The BFECC convection is set to false, therefore the ConvectionDiffusionApplication is not imported, but the segmentation fault that occurs when running the simulation and trying to write the restart file shows that the issue comes from the ConvectionDiffusionSettings. I imagine that the problem is that there is a process with no Serialization, but I have not managed to find which.

**Scope**
Serialization of ConvectionDiffusion. The solver that I am using is one of my own, but it incorporates features of the navier_stokes_two_fluids_solver, the most important one being the level-set convection process.
I am attaching some meaningful information of the Kratos debugger when the error occurs. To me the important details are **ConvectionDiffusionSettings** and **DensityVar,** but apart from that I do not see how can I work out this issue.

Kratos::Serializer::write (this=0x6715fd0, rValue=<error reading variable: Cannot access memory at address 0x10>) 
Kratos::Serializer::save<double> (this=0x6715fd0, rTag="DensityVar", pVariable=0x0) 
Kratos::ConvectionDiffusionSettings::save (this=0x1076a30, rSerializer=...) Kratos::Serializer::save<Kratos::ConvectionDiffusionSettings> (this=0x6715fd0, rTag="Data", rObject=...) 
Kratos::Serializer::SavePointer<Kratos::ConvectionDiffusionSettings>

Do you have an idea on how to find the source of the problem?

**Comment by mrhashemi** [comment]
It seems that you have another call of CONVECTION_DIFFUSION_SETTINGS in your solver (besides the one in the levelset_convection_process). It needs to access the **undefined variables**.

**Comment by pau-mar** [comment]
Thank you for the message. How can I know which are the undefined variables and when am I calling CONVECTION_DIFFUSION_SETTINGS? I am not getting which is the issue. Thank you

**Comment by sunethwarna** [comment]
Hi,

May be you can put all the applications being used as imports in
MainKratos.py to solve this. I also have experienced the same in restarting
when more than one application is used or imported via processcess....
Check your log file before the restart and put all application that are
initialized as imports.

--
------ sent via mobile ------
Suneth Warnakulasuriya,
M.Sc. (Hons) Technical University of Munich, Germany.
B.Sc. Eng. (Hons) University of Moratuwa, Sri Lanka.

**Comment by rubenzorrilla** [comment]
Closing as it seems to be inactive.
