### ISSUE TITLE
Automatic format preview

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#858]
Dear @KratosMultiphysics, here: [feature-add-styling-check](https://github.com/KratosMultiphysics/Kratos/tree/feature-add-styling-check) is the branch with the initial proposal for the automatic styling. As agreed:

```
Language: Cpp
BasedOnStyle: Google
ReflowComments: false
IndentWidth: 4
NamespaceIndentation: None
ReflowComments: false
SortIncludes: false
AllowAllParametersOfDeclarationOnNextLine: true
BinPackParameters: true
AlignAfterOpenBracket: DontAlign
```

Which basically takes the Google (ref:  [Google Style C++](https://google.github.io/styleguide/cppguide.html)) and adds the tweaks we discussed and some others to respect as much as our code as possible.

Here is a little tool if you want to play with the options: https://zed0.co.uk/clang-format-configurator/

Of course this is not written in stone and we will not merge until everyone has tested it. Feel free to re-branch this or rebase this branch as you fit in order to make tests.

Also, this can be used with most modern editors:
- **Visual Studio**: https://marketplace.visualstudio.com/items?itemName=xaver.clang-format
- **Visual Code**: In Extensions, examples: https://code.visualstudio.com/docs/languages/cpp
- **Atom**: In Addons: https://atom.io/packages/clang-format
- **Sublime**: https://github.com/rosshemsley/SublimeClangFormat
- **Emacs**: https://github.com/sonatard/clang-format
- **Vim**: https://github.com/rhysd/vim-clang-format (if you use vim as your main editor you probably don't need any tutorial anyway...)
- **QT**: http://doc.qt.io/qtcreator/creator-beautifier.html

Netbeans Users
There is no "official" link that I've found but here it goes a mini-guide: https://stackoverflow.com/questions/38384787/can-clang-formatting-be-used-in-netbeans

Sorry but I don't know anything about Mac specific editors, but if you want support for a particular one tell me and I will investigate.

**Comment by roigcarlo** [comment]
@pooyan-dadvand Commented that short if-else statements / loops were inlined. I disabled this so now codes like

```C++
if(foo) boo();
```

are always translated to

```C++
if(foo) 
    boo();
```

This has however no effect on wether `{` `}` are or not used.

**Comment by pooyan-dadvand** [comment]
I have used:

```
AllowShortLoopsOnASingleLine: false
AllowShortIfStatementsOnASingleLine: false
```

**Comment by roigcarlo** [comment]
Yup that's exactly what I added :+1:

**Comment by roigcarlo** [comment]
I updated to 

```
Language: Cpp
Standard: Cpp11
BasedOnStyle: Google
AlignTrailingComments: true
ReflowComments: false
IndentWidth: 4
ColumnLimit: 2048
NamespaceIndentation: None
SortIncludes: false
AllowAllParametersOfDeclarationOnNextLine: false
BreakConstructorInitializers: BeforeComma
BinPackParameters: true
BinPackArguments: true
AlignAfterOpenBracket: DontAlign
AllowShortIfStatementsOnASingleLine: false
AllowShortLoopsOnASingleLine: false
```

Since the old is giving problems to the application files.
At the sight of the last problem I been extensively resting this everywhere and my conclusion is that it is not ready for our necessities... It lack severals options that we would need. 

Just to put an example, you cannot even set how you want to parse PP directives, they are always indent to 0, (This includes `pragma omp`) and at 12-2017 they are still discussing if they are gonna fix this or not so....

**Comment by pooyan-dadvand** [comment]
So what would be the way to go?

**Comment by RiccardoRossi** [comment]
Making a ping since it would be nice to have this finalized.

**Comment by RiccardoRossi** [comment]
Very hard to make a nice solution. Current choice has trouble with macros. maybe astyle will work better.

closing for now
