### ISSUE TITLE
Flags in ProcessInfo to inform the element abt which analysis is being used

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#859]
Some of our elements, e.g. the recently added shell elements are formulated non-linear. This means that they require a non-linear analysis in order to work properly.
@pooyan-dadvand suggested in #842 to use `Flags` in the `ProcessInfo`, e.g.
```
if (rCurrentProcessInfo.Is(ProcessInfo::SolutionType.NON_LINEAR&ProcessInfo::SolutionType.DYNAMIC)
```
Then the element could check if the correct analysis type is being used in the `Check` functions and throw errors accordingly.
@KratosMultiphysics/kratos-core-team @KratosMultiphysics/structural-mechanics what do you think abt this?

**Comment by pooyan-dadvand** [comment]
We should also think about which Flags would be useful

**Comment by philbucher** [comment]
For the beginning sth like:
- LINEAR
- NON_LINEAR

(set by the strategy)
- STATIC
- DYNAMIC

(set by the scheme)
?

**Comment by philbucher** [comment]
@pooyan-dadvand would you incorporate a `Kratos::Flags` object as membervar into `ProcessInfo`?
And then access it with `GetFlags()` or sth similar to set / querry single flags?

**Comment by RiccardoRossi** [comment]
my 2 cents:
1 - having processinfo to include flags may be a good idea
2 - about adding those flags i am open for discussion
3 - do we really need the element to be aware of that? we made efforts to avoid that so far.

**Comment by RiccardoRossi** [comment]
iterating on this, since we have a very limited number of available flag slots, what if we only define 

NON_LINEAR (this being false would mean linear)
DYNAMIC (false would imply static)
CONSISTENT_MASS_MATRIX (false would imply to use lumped mass matrix)

**Comment by loumalouomega** [comment]
++ to Riccardo

**Comment by philbucher** [comment]
@RiccardoRossi sounds good!
I will make a draft for this.

One question though: If I do a Linear analysis, is your idea to not touch the corresponding flag or to set it to false?
I.e. does the `Is(NON_LINEAR)` function return false in both cases, even if it is not defined? => there are also `IsDefined` functions

**Comment by RiccardoRossi** [comment]
i would say that the solve function should define the flag at the beginnimg
kf the solve.

having said this, others must agree with me before adding the flag to the
list

**Comment by philbucher** [comment]
ok then lets make @KratosMultiphysics/technical-committee aware of this?

**Comment by pooyan-dadvand** [comment]
Actually you can create flags which are oposide to each other: `LINEAR == ! NON_LINEAR` and `ProcessInfo` is already a `Flags` and can store any flags.

**Comment by RiccardoRossi** [comment]
i think that this should not be for the release... my proposal is to (eventually) add it after the release

@philbucher ok for you? if so please remove the Release tag

**Comment by philbucher** [comment]
Sure, that is sth to be discussed after the release.
I think it was not me adding the Release flag, but I will remove it

**Comment by philbucher** [comment]
It wasn't even assigned the release tag

**Comment by RiccardoRossi** [comment]
sorry my bad then...i must have switched to non-release tags without noticing

**Comment by philbucher** [comment]
closing this, not sure if it is still needed ...
