### ISSUE TITLE
gid_mesh_container.h keeps using deprecated variables as IS_INACTIVE

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#86]
The gid_mesh_container.h keeps using the deprecated variable IS_INACTIVE instead of the flag ACTIVE. Should we change this?

**Comment by RiccardoRossi** [comment]
this is definitely legacy code.

my view would be to substitute current code by the following

        bool element_is_active = true;
        if ((it)->IsDefined(ACTIVE))
                element_is_active = (it)->Is(ACTIVE);

        if (element_is_active)
        {...}

this obviously changes the behaviour of existing code, so as a very minimum we should communicate this in the mailing list

opinions?

**Comment by maceligueta** [comment]
I totally agree. It should be a flag. Apart from sending a notification to the mailing list, we can also grep the code and send individualized emails to the owners of the applications using the variable IS_INACTIVE.

**Comment by RiccardoRossi** [comment]
one option would be to remove the IS_INACTIVE from the list of variables.

this was we would produce a hard error instead of a change in behaviour.

I believe this would be a better option, since the fix is trivial but at least one would be warned

**Comment by pooyan-dadvand** [comment]
I agree with both of you
- first create a cleanup-is-inactive branch 
- remove the IS_INACTVE variable 
- email the app developers to check the branch 
- pool request as usual:

**Comment by RiccardoRossi** [comment]
Hi,

  Yes, i already created the branch.

The point is that It is very easy to introduce an error with this, and
complicated to test for the outcome.
I ll try to make a test for the gid_io but the maintainers Will have to
decide if stepping in or removing the Broken code.

Anyway i believe there is a lot of legacy cruft around this...So removing
some stuff is eventually beneficious.
Doing It myself in the Core for the things i am aware of

Riccardo

**Comment by loumalouomega** [comment]
@KratosMultiphysics/technical-committee Additionally maybe is a good idea to start a discussion about the deprecated variables and the possibility of remove them following the same procedure

**Comment by maceligueta** [comment]
There's a mid-term plan to allow the variables to be added from any application (even from multiple applications) in such a way that they are not really repeated in memory. When that feature is coded would be a good time to clean variables, in my opinion. Doing it also now would represent a double work.

**Comment by pooyan-dadvand** [comment]
I agree with @maceligueta !

**Comment by RiccardoRossi** [comment]
I think the point Vicente makes about removing the deprecated variables is still valid...

The IS_* for example should be removed, not just moved to other apps.

Having said this i would say that the discussion exceeds the scope of current issue.

@vicente, could you take a look to my commits to see It they make sense? I did tests for the gid_io, and maybe i could do smthg similar for trilinos, bit i Will be unable to test some of the features i touched...So before consulting with the maintainers It would be good to have a pre-review

**Comment by loumalouomega** [comment]
![](https://media.giphy.com/media/K64cgEYDYWs6c/giphy.gif)

**Comment by loumalouomega** [comment]
@RiccardoRossi The code looks OK, the thing is that I don't know how the MixedElementApplication  works, and I don't know if the utility of removing the nodes inactives can be replaced entirely just with the flag.

**Comment by RiccardoRossi** [comment]
Some revision is now required from the mantainers.

@pablobecker 

could u take a look to the change i did in the pfem2 app

https://github.com/KratosMultiphysics/Kratos/compare/feature-remove-is-inactive

i am writing offline messages to Jordi Rubio and to Hoang Giang Bui to ask for the same since they are not in github

**Comment by RiccardoRossi** [comment]
ping @pablobecker 

ping @vryy 

hi guys, did u take a look at this?

**Comment by RiccardoRossi** [comment]
ping @pablobecker

ping @vryy

**Comment by vryy** [comment]
Hi guys
The IS_INACTIVE variable is heavily used in structural_application to activate/deactivate an element. So removing this variable requires the modification of structural_application first. I believed it is also used in solving_strategies/ residualbased_elimination_builder_and_solver_deactivation. In some of them already there's a mechanism to select the ACTIVE if it's defined. I can safely remove IS_INACTIVE there.

**Comment by RiccardoRossi** [comment]
Hi Bui,

the residualbased_elimination_builder_and_solver_deactivation is to be removed. 

Now (i would say since at least two years) the variable ACTIVE is employed in the block builder and solver providing the same capabilities by default.

can u give an ETA for the change to the legacy structural application?

**Comment by vryy** [comment]
@RiccardoRossi I made a pull request. Can you review this?

**Comment by RiccardoRossi** [comment]
@vryy yes, i accepted. If you click on merge i'll also make a pull request of my changes

**Comment by RiccardoRossi** [comment]
fixed
