### ISSUE TITLE
Compiling and Importing MappingApp in MPI

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#8611]
We have found a problem using MappingApplication in mpi. If MPI is available at the moment of compilation, MappingApp will be built with some mpi dependencies, if you want to use this build later in a non-mpi machine, you will get an error when you try to import the MappingApp. I was discussing this with @pooyan-dadvand and we thought that it would make sense if the mpi part was compiled in a different module (similar to what is done in FluidDynApp with TrillinosExtension), so the same binary can be used for mpi and non-mpi cases. What do you think @philbucher ? @KratosMultiphysics/design-committee

**Comment by philbucher** [comment]
you caught me :D

Long story short, I will create an MPI/trilinos extension soon

**Comment by philbucher** [comment]
just to say that I am on it after discussing with @pooyan-dadvand 
note that this will change the Interface in MPI, the import will be done from a different place

**Comment by philbucher** [comment]
@ddiezrod @pooyan-dadvand I made a first transition PR : #8629 
The faster I can merge the sooner I can continue :)

**Comment by philbucher** [comment]
BTW I remembered now why I hadn't done it earlier :D
It was quite some work xD
