### ISSUE TITLE
[TwoFluids] Utility for calculating the water flow over a surface

### ISSUE THREAD

**Issue by joaquinirazabal** [KratosMultiphysics/Kratos#8619]
Hi, @rubenzorrilla, I have seen that there is a process (MassConservationCheckProcess) that calculates the volume of water and air in a domain. For our (@djvicente) work it would be very interesting to have a utility that calculates the water (and air) flow through a surface (or a line in 2D problems), do you see it feasible?

**Comment by rubenzorrilla** [comment]
Sure! It should be easy with the `ModifiedShapeFunctions`. I'll take care as soon as possible.

**Comment by rubenzorrilla** [comment]
Hi! #8736 goes in this direction. For standard (not free-surface) CFD cases, you can use the `FlowOutputProcess` as it is right now. I'll upgrade it to support level set based formulations as soon as possible.

**Comment by joaquinirazabal** [comment]
Great! We will check the new feature and wait for free-surface cases. Thanks, @rubenzorrilla!
