### ISSUE TITLE
Gauss Lobatto gauss point integration for quadrilateral 4 Nodes and Hexaedra Element 

### ISSUE THREAD

**Issue by Nelmaireni** [KratosMultiphysics/Kratos#8623]
**Description**
What is happening?

Hello team. I need to set the integration rules on the 4 nodes quadrilateral and  8 node hexahedra geometry to Lobatto rules. I have seen that Lobatto integration rules are defined, but no integration method at geometry_data. Please advise.   
Regards,
Nelson

**Scope**
Which areas of Kratos are involved
E.g.
- Compilation
- KratosCore
- FooApplication
- Documentation

**Comment by loumalouomega** [comment]
There is  PR that solves this problem: https://github.com/KratosMultiphysics/Kratos/pull/6745

(any custom integration, otherwise you must add your integration by hand)

**Comment by Nelmaireni** [comment]
If I understand well, any custom integration should be done by the user at the element level?

**Comment by loumalouomega** [comment]
Yes, in any case I fix it for the hexa, unfortunately the quad is already full (limit is 10 integration methods)

**Comment by loumalouomega** [comment]
See #8626

**Comment by Nelmaireni** [comment]
Thanks for the reply.  Do you time for a virtual meeting via team viewer or Microsoft team?.
Please let me know your availability.
Thanks
Regards,
Nelson

**Comment by loumalouomega** [comment]
Not right now
