### ISSUE TITLE
Fluid Characteristic Utilities CFL condition

### ISSUE THREAD

**Issue by pau-mar** [KratosMultiphysics/Kratos#8624]
**Description**
In fluid_characteristic_numbers_utilities.cpp the computation of the CFL number in done taking into account the velocity of the fluid, so that the condition is only on the velocity. Should not the CFL contition take into account the sound velocity as well? That should be more appropiate when dealing with weakly compressible flows.

**Comment by dcagritan** [comment]
Hello @pau-mar,

_> Should not the CFL condition take into account the sound velocity as well?_ 

As far as I know, it is only the case for compressible flows. For incompressible flows, the basic definition of the CFL condition suffices. However, if one is dealing with compressible flows, I'd agree that the current version of the computation of CFL should be modified to take into account the compressible flows.
Regards
