### ISSUE TITLE
[Core] Unused linear transform processes

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#8647]
**Description**
Minor cleanup.

There's a [translation](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/translation_operation.h) and [rotation](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/processes/rotation_operation.h) process in core but a quick grepping shows that neither are used anywhere. Moreover, they are untested and appear to be [poorly written](https://github.com/KratosMultiphysics/Kratos/blob/3199050ebd33262c6eb853e38ca1fb4f1793abfc/kratos/processes/rotation_operation.h#L265).

I'm not sure if there are uses which a grepping wouldn't reveal but if there aren't, I suggest removing them for the sake of cleanliness.

**Comment by philbucher** [comment]
Could you make a Pr please?
