### ISSUE TITLE
[Trilinos] Trilinos solver factory fails when creating linear solvers

### ISSUE THREAD

**Issue by marcnunezc** [KratosMultiphysics/Kratos#8654]
**Description**
If a linear solver is created in MPI, the TrilinosSolversFactory fails creating it. It seems something went wrong in the registering, as no solver is available (see code below) from the list in: 
https://github.com/KratosMultiphysics/Kratos/blob/d5dfb782e14dbf23ed3f6e648b3f3e4c68572aba/applications/TrilinosApplication/python_scripts/trilinos_linear_solver_factory.py#L12-L22

It is maybe related to #3185?

**Scope**
Where in Kratos is this bug happening. 
E.g.
- TrilinosApplication

**To Reproduce**
Run the following code:
```
import KratosMultiphysics
import KratosMultiphysics.TrilinosApplication
print(KratosMultiphysics.TrilinosApplication.TrilinosLinearSolverFactory().Has("cg"))
print(KratosMultiphysics.TrilinosApplication.TrilinosLinearSolverFactory().Has("bicgstab"))
print(KratosMultiphysics.TrilinosApplication.TrilinosLinearSolverFactory().Has("gmres"))
print(KratosMultiphysics.TrilinosApplication.TrilinosLinearSolverFactory().Has("aztec"))
print(KratosMultiphysics.TrilinosApplication.TrilinosLinearSolverFactory().Has("amgcl"))
```

which gives:

```

 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-3e62cf261f-Release
Compiled with OpenMP and MPI support.
Maximum OpenMP threads: 4.
Running without MPI.
Importing    KratosMetisApplication 
    KRATOS  __  __      _   _
           |  \/  | ___| |_(_)___
           | |\/| |/ _ \ __| / __|
           | |  | |  __/ |_| \__ \
           |_|  |_|\___|\__|_|___/
Initializing KratosMetisApplication...
Importing    KratosTrilinosApplication 
    KRATOS  _____     _ _ _
           |_   _| __(_) (_)_ __   ___  ___
             | || '__| | | | '_ \ / _ \/ __|
             | || |  | | | | | | | (_) \__ \
             |_||_|  |_|_|_|_| |_|\___/|___/
Initializing KratosTrilinosApplication...
False
False
False
False
False
```

**Expected behavior**
That the trilinos solver factory correctly creates the solvers, and the above code to give:

```
 |  /           |
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 9.0."Dev"-3e62cf261f-Release
Compiled with OpenMP and MPI support.
Maximum OpenMP threads: 4.
Running without MPI.
Importing    KratosMetisApplication 
    KRATOS  __  __      _   _
           |  \/  | ___| |_(_)___
           | |\/| |/ _ \ __| / __|
           | |  | |  __/ |_| \__ \
           |_|  |_|\___|\__|_|___/
Initializing KratosMetisApplication...
Importing    KratosTrilinosApplication 
    KRATOS  _____     _ _ _
           |_   _| __(_) (_)_ __   ___  ___
             | || '__| | | | '_ \ / _ \/ __|
             | || |  | | | | | | | (_) \__ \
             |_||_|  |_|_|_|_| |_|\___/|___/
Initializing KratosTrilinosApplication...
True
True
True
True
True
```

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Ubuntu 18.04
- Branch: master
- Python 3.6.9
- Compiled with USE_MPI=ON

**Comment by philbucher** [comment]
I have the same issue

how could this pass the ci? :thinking:

**Comment by philbucher** [comment]
I checked, the solvers are detected in the CI
maybe it is an issue with the unity build

also to mention that #3185 doesn't modify the LinearSolverFactory, but there might still be some cross-effects of the registration

**Comment by philbucher** [comment]
yep it is a unity build issue
when compiling with unity build the solvers are found, but not without
@loumalouomega can you please take a look?

**Comment by loumalouomega** [comment]
> yep it is a unity build issue
> when compiling with unity build the solvers are found, but not without
> @loumalouomega can you please take a look?

Huuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuuum, that is strange. The register is not modified.

I can reunify factories, which may fix the issue (it was a TODO anyway)

**Comment by roigcarlo** [comment]
I've been investigating this a bit and so far this is what I can tell.

Solvers do get registered in some container, but I am not sure which one `mrComponents<????>`. Its not clear to me how to get that info from gdb, I am trying...

Once you try to access to them via the `LinearSolverFactory`, it tries to access `mrComponents<FactoryType>`, with the types of `FactoryType` **appear (not 100% sure)** to be correct.

My guess is that the non-unity compilation is using the wrong types when its retrieving the container so the solvers are added in the wrong place, but still unsure which container is getting fetched and why :S

**Comment by roigcarlo** [comment]
Ok, there are two instances of `KratosComponents<LinearSolver<TrilinosSparseSpace, TrilinosLocalSpace>>`

The Trilinos app uses one to register, and the core sees the other to retrieve the components, which is empty.

**Comment by loumalouomega** [comment]
> Ok, there are two instances of `KratosComponents<LinearSolver<TrilinosSparseSpace, TrilinosLocalSpace>>`
> 
> The Trilinos app uses one to register, and the core sees the other to retrieve the components, which is empty.

#3185 did not modify that, so the error was already there and #3185 emerged the bug.

**Comment by philbucher** [comment]
this should work again after #8669 right?

**Comment by roigcarlo** [comment]
Yep, I am closing it.
