### ISSUE TITLE
Compilation error in Windows without unity

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#8663]
When unity is disabled I get the following error:
[error-windows.txt](https://github.com/KratosMultiphysics/Kratos/files/6356559/error-windows.txt)

Not sure where it comes from. I guess it's related to the last changes in strategies or maybe from FluidDynApp. Can someone take a look? @roigcarlo @loumalouomega @rubenzorrilla 

This is my configure file.

[my_configure.txt](https://github.com/KratosMultiphysics/Kratos/files/6356572/my_configure.txt)

**Comment by loumalouomega** [comment]
Another issue from #3185

**Comment by loumalouomega** [comment]
The simpler manner would be to call directly the solver from the factory. It is a warning that is treated as error BTW

**Comment by ddiezrod** [comment]
> The simpler manner would be to call directly the solver from the factory. It is a warning that is treated as error BTW

There are actually two errors, one comes from the warning, but the other is a "real" error, (its at the very end).

**Comment by loumalouomega** [comment]
Huuuuuum

**Comment by ddiezrod** [comment]
> Huuuuuum

Huuuuum indeed : D

**Comment by roigcarlo** [comment]
Apparently there is something very fishy with that PR. I keep investigating.

**Comment by philbucher** [comment]
> Apparently there is something very fishy with that PR. I keep investigating.

🐟

**Comment by roigcarlo** [comment]
@ddiezrod Can you try if it works now?

**Comment by ddiezrod** [comment]
> @ddiezrod Can you try if it works now?

If you mean after the revert, yes, it works.

**Comment by rubenzorrilla** [comment]
Closing as it seems to be solved.
