### ISSUE TITLE
Installing problem on Windows 10

### ISSUE THREAD

**Issue by alecontri** [KratosMultiphysics/Kratos#8667]
Dear all,
I just entered the Kratos world, but I have problems during installation. I followed the "Install.MD" instructions in the Wiki page. The versions are:
- Branch: master
- OS: Windows 10 x64
- Visual Studio 2019 16.9.4
- Cmake 3.20.1
- Python 3.7-64
- Git 2.31.1.windows.1
- Boost: 1_76_0

The text of the configuration file I used is:
[configure.txt](https://github.com/KratosMultiphysics/Kratos/files/6361826/configure.txt)

What the prompt (I used the x64 Native Tools Command Prompt for Visual Studio run as administrator) displays the first time I run configure is this:
[prompt_long.txt](https://github.com/KratosMultiphysics/Kratos/files/6361827/prompt_long.txt)

If I re-run, the shorter version is:
[prompt_short.txt](https://github.com/KratosMultiphysics/Kratos/files/6361829/prompt_short.txt)

No bin folder is present in Kratos. I'm sorry if this has already been solved.
Thank you very much!

**Comment by AlejandroCornejo** [comment]
Hi! If you compile with links try to run the **cmd with admin premisions**

**Comment by roigcarlo** [comment]
Hi @alecontri, we are currently experiencing a problem that prevents Kratos from compiling con windows and running on linux. We are about to deploy a fix for that.

I Kindly as you to wait until later today / tomorrow and try again after updating.

**Comment by alecontri** [comment]
Ok, absolutely no problem, I will wait and retry. Thank you!

**Comment by alecontri** [comment]
Just tried and it all went smooth through the end. Only few warnings which actually I don't know if I should care about:

`LINK : warning LNK4217: il simbolo '?GetBuildType@Kratos@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@
std@@XZ (class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Kratos::GetBui
ldType(void))' definito in 'kratos_version.obj' è stato importato da 'kernel.obj' nella funzione '"public: static class
 std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Kratos::Kernel::BuildType(vo
id)" (?BuildType@Kernel@Kratos@@SA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@XZ)' [C:\Kratos\build
\Release\kratos\KratosCore.vcxproj]
LINK : warning LNK4217: il simbolo '?GetVersionString@Kratos@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D
@2@@std@@XZ (class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Kratos::Ge
tVersionString(void))' definito in 'kratos_version.obj' è stato importato da 'kernel.obj' nella funzione '"public: void
 __cdecl Kratos::Kernel::Initialize(void)" (?Initialize@Kernel@Kratos@@QEAAXXZ)' [C:\Kratos\build\Release\kratos\Kratos
Core.vcxproj]
LINK : warning LNK4286: il simbolo '?GetVersionString@Kratos@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D
@2@@std@@XZ (class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl Kratos::Ge
tVersionString(void))' definito in 'kratos_version.obj' è stato importato da 'logger_output.obj' [C:\Kratos\build\Relea
se\kratos\KratosCore.vcxproj]`

If not, I'm really grateful for your help. Thank you!

**Comment by roigcarlo** [comment]
No, those are normal, if  these are the only ones its fine :+1:
