### ISSUE TITLE
[CMake] Application selection in the CMake GUI

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#8675]
**Description**
Currently (or at least last time I had to set up Kratos from scratch), the list of desired applications must be specified through environment variables. I just found out that CMake variables' names can be defined using other variables' values, which would allow specifying the list of applications to build as options within CMake.

Here's an example:
https://github.com/matekelemen/CMakeExample

This would in turn make configuring Kratos fully from the CMake GUI possible, without relying on shell scripts. I don't know if this is even desired, but I thought it is worth mentioning.

**Comment by roigcarlo** [comment]
Hi @matekelemen 

What you say is correct, we can implement it but will have to be in the top of the current mechanism, as we need to give support for external applications, for example:

```
/user
   /kratos
       /applications
           /structural
           /fluid
   /anotherProject
       /applications
           /fooApplication
```

If you can adapt it to make it work in an scenario we can add it for sure.

**Comment by matekelemen** [comment]
Ah I didn't think about that, though Kratos' *CMakeLists* taking care of external applications is a weird concept in my opinion.

Well it's going to be less pretty than I originally thought but I'll open a draft, just in case.

**Comment by roigcarlo** [comment]
Yep its a little strange but its something we need for the non open-source codes that are based on Kratos
