### ISSUE TITLE
About the implementation of remeshing technology 

### ISSUE THREAD

**Issue by Joekchu** [KratosMultiphysics/Kratos#8686]
Hi everyone,

I am recently using Kratos to do some large deformation simulations in the realm of geotechnics. In our area, there are many different methods that were proposed to solve large deformation problems by mesh regeneration (e.g. Ritss and EALE). I thus was wondering if in Kratos, are there any remeshing technology to help users overcome the large deformation problem?

Million thanks in advance!

Best regards,
Joe

![large-deformation](https://user-images.githubusercontent.com/56572353/116368162-a2554980-a83a-11eb-98e8-7007e438debe.png)

**Comment by loumalouomega** [comment]
Yes, we have several techniques of remeshing, specially with MMG. See:

www.mmgtools.org
https://github.com/KratosMultiphysics/Kratos/tree/master/applications/MeshingApplication

Examples:
https://github.com/KratosMultiphysics/Examples/tree/master/mmg_remeshing_examples

https://github.com/KratosMultiphysics/Examples/tree/master/parmmg_remeshing_examples

**Comment by Joekchu** [comment]
@loumalouomega Hey, Vicente, nice to see you. Thanks for your answer. In fact, I am curious about the PFEM application which was proved to be useful in geotechnical engineering. Also, I will look at MMG. Thank you again for your nice suggestion!
