### ISSUE TITLE
LineLoadCondition

### ISSUE THREAD

**Issue by KlausBSautter** [KratosMultiphysics/Kratos#870]
Hi, I am currently adding work equivalent nodal moments to the LineLoadCondition in StructuralMechanicsApplication and noticed that the current LineLoadCondition2D can also be used in 3D as it gets the dimension from the Geometry. As there is no LineLoadCondition3D in the StructuralMechanicsApplication atm I have two possibilities:
1.) Create a new LineLoadCondition3D
2.) Rename LineLoadCondition2D to LineLoadCondition and work with this.

I would suggest the do 2.) as it is already written in such way that it works for 3D

**Comment by philbucher** [comment]
Thumbs up for reusing existing code

**Comment by loumalouomega** [comment]
:+1: To reuse

**Comment by RiccardoRossi** [comment]
+1 for reusing too
