### ISSUE TITLE
Validation and benchmarking of the FluidDynamicsApplication

### ISSUE THREAD

**Issue by jcotela** [KratosMultiphysics/Kratos#872]
Define a set of validation and benchmarking cases for the Fluid Dynamics Application.

- Test cases: Fast tests (<<10 seconds) to run in the C or Python Fast/Nightly test suites.

- Test examples: Complete cases to showcase the FluidDynamics application. We need to decide if we want to include them in the Kratos binaries (as the current test_examples) or have them be downloadable from somewhere else.

- Benchmarks: Comparable to literature. If they don't have a huge mdpa, they can be added to the Benchmark test queues, if they do, they are only available as downloads from wiki. **All benchmarks should have an associated wiki page**.

**Comment by pooyan-dadvand** [comment]
Very important!

**Comment by adityaghantasala** [comment]
A thought about "Test examples / benchmarks" in general for all the applications : 

Will it be convenient if test examples are  in a separate repository under "KratosMultiphysics"  with application folders having their own test examples / benchmarks inside them ?

We can make a wiki page for this repository and as @jcotela  suggests have a wiki page for each of the benchmarks/Test examples. Once this is done a link to this repo under the wiki page of the main Kratos can be more tidy.  This process will also reduce the size (no need to worry a lot about the size of mdpa files) of the main Kratos repository.

**Comment by pooyan-dadvand** [comment]
Accually not a bad idea. Then one can use this repository with release binaries without having to download the source. 👍 for @adityaghantasala benchmarks repository.

**Comment by adityaghantasala** [comment]
@pooyan-dadvand do you think we should do this for the upcoming release ?

**Comment by pooyan-dadvand** [comment]
At least I would try to do it for the release (end of November). It would be a great added value!

**Comment by RiccardoRossi** [comment]
my 2 cents:

1 - in my opinion small tests  should remain together with the code
2 - I agree that larger tests could be in another repository...

**Comment by pooyan-dadvand** [comment]
Agree. 
- Unit tests in the code
- Benchmarks in Application cases repository.

**Comment by adityaghantasala** [comment]
Perfect.
Can I make such a repository or should the administrators make it ?

**Comment by pooyan-dadvand** [comment]
It should be created by admins. Actually we closed this option after creation of erroneous repositories by some users.

**Comment by pooyan-dadvand** [comment]
I have added the example repository to KratosMulitphysics. I would suggest to add different sub-directories like benchmarks, application_cases etc.

**Comment by maceligueta** [comment]
This will be done in the Examples repo. Closing.
