### ISSUE TITLE
Compilation error [SolidMechanicsApplication]

### ISSUE THREAD

**Issue by Joekchu** [KratosMultiphysics/Kratos#8734]
Hi everyone,

I meet the error when I compile the **SolidMechanicsApplication**. Attached is the message output. Please kindly have a look. My PC system is Ubuntu 18 and the Kratos version is the latest.
[Errors_in_compilation.txt](https://github.com/KratosMultiphysics/Kratos/files/6433279/Errors_in_compilation.txt)

Actually, it is smooth and successful when I try to compile the StructuralMechanicsApplication, LinearSolversApplication, and ConstitutiveModelsApplication. Yet, it doesnt work when I proceed to compile SolidMechanicsApplication. Does anyone share the same experimence? 

Sorry for my noise but your favour will save my whole day! Millions of thanks in advance!

Best regards,
Joe

**Comment by loumalouomega** [comment]
Which is the current status of this @roigcarlo 

Besides, Kratos teams develops mainly StructuralMechanicsApplciation and ConstitutiveLawApplication, ConstitutiveModelsApplication and SolidMechanicsApplication is from a different team, and we do not support it

**Comment by roigcarlo** [comment]
I can only tell you that the errors seems to come mainly from elements that are not using the override mechanism correctly, but that's. @KratosMultiphysics/solid-mechanics should be able to help with the compilation errors.

**Comment by Joekchu** [comment]
@loumalouomega Thank you, Vicente, as always. Indeed, I wish to use the PFEM application but as you may know, SolidMechanicsApplication is the necessary dependency.

@roigcarlo Thanks, I believe you are correct according to the hint.

@KratosMultiphysics/solid-mechanics Could you please help to check these error messages? Thanks a lot!

**Comment by AlejandroCornejo** [comment]
Do not use the `SolidMechanicsApplication`, it is out of maintenance. Instead, if you want to  perform Solid mechanics calculations we recommend you to compile `StructuralMechanicsApplciation `and `ConstitutiveLawApplication` as @loumalouomega suggests

**Comment by AlejandroCornejo** [comment]
Oh we have just posted at the same time hehe Do you want to use the PFEM for fluids  or solids?

**Comment by Joekchu** [comment]
> Oh we have just posted at the same time hehe Do you want to use the PFEM for fluids or solids?

Haha :), I wish to use PFEM for solids (i.e soil-structure interaction)

**Comment by AlejandroCornejo** [comment]
Maybe @AFranci can help you with some insight regarding the PFEM

**Comment by philbucher** [comment]
closing as seems to be solved
please reopen if not
