### ISSUE TITLE
Issue with Drag Results for an High-Rise building CFD model

### ISSUE THREAD

**Issue by TommasoBarbiero** [KratosMultiphysics/Kratos#8762]
**Description**
I'm trying to get Drag results for a 3D high-rise Building, using GID I've divided the structure in surfaces corresponding to the different storeys of the building (immage attached), assigned each of them to a group and ask the drag results for each storey.

I've created another groups of surfaces with the entire structure and ask for the drag.

The results I'm having do not match. The drag of the entire structure can be compared to the one obtained with the Italian codes, The ones for each storey are far lower than expected.
Also, the sum of each "Fx" of the storeys is far lower than the "Fx" of the entire structure, this sounds strange to me. 
Sum of storeys drag: 19885
Median Value of structure Drag: 499816

Could the overlapping of the surfaces of the entire structure with the one of the storeys be a possible problem?

**Scope**. 
Drag Output Values.

**To Reproduce**
Assign a surface to a group and asking GID a drag output.

**Expected behavior**
the sum of values for each storeys to be similar to the one of the entire structure.

**Environment**
- OS: Ubuntu 20.10
- compiled Kratos
- GiD14
- Python 3.8.6

[ProjectParametersLinuxNew.txt](https://github.com/KratosMultiphysics/Kratos/files/6460698/ProjectParametersLinuxNew.txt)
[FluidModelPart.Drag_20-21_drag.txt](https://github.com/KratosMultiphysics/Kratos/files/6460701/FluidModelPart.Drag_20-21_drag.txt)
[FluidModelPart.Drag_struttura_drag.txt](https://github.com/KratosMultiphysics/Kratos/files/6460746/FluidModelPart.Drag_struttura_drag.txt)
![storeys division](https://user-images.githubusercontent.com/82713919/117853212-700b0980-b288-11eb-9768-1d06c9eb7aa5.JPG)
![structure division](https://user-images.githubusercontent.com/82713919/117853216-713c3680-b288-11eb-9ae5-007ca90fff91.JPG)

**Comment by mpentek** [comment]
The FluidDynamicsApplication was used (with an LES-type approach) für various buildings and structures. The force results (even fluctuating values) were in very good agreemen with other reference. So here my notes:

- When comparing to the building code, be careful. Typically codes will deliver higher forces for design.
- When you compare results, provide a more precise desription of what you compare (mean, median, standard deviation, max/min and so on in time, space)

From how I understand you  GiD model and used group you have:
-  struttura-structure, which should have all the surfaces on the structure and the ComputeDragProcess will deliver Fx, Fy, Fz (reaction values in flow-attached axes) -> here you have surfaces spanning the total height
- you have the levels in groups, somehow pairwise -> here you have surfaces spanning the respective heights
 
The error is that you cannot use both
-  so delete the surfaces spanning the whole height and used for the structure
- for the group struttura-structure you can assign all smaller surfaces (that you anyway have for the levels)
- for the groups representing levels keep it as you have

It is anyway interesting that you got restuls, as you need to create some volume representing the flow  fiels which has to snap mesh points on the surface of your building, That is why you cannot have overlapping surfaces there. It is a modeling issue.

**Comment by mpentek** [comment]
Closing as I assume the previous comment provides the solution.
