### ISSUE TITLE
Warnings compiling ExternalSolversApplication

### ISSUE THREAD

**Issue by lorenzogracia** [KratosMultiphysics/Kratos#878]
During the compilation of the application some warnings appears since in the cmake appears the following line;
include_directories( ${CMAKE_CURRENT_SOURCE_DIR}/external_libraries )

I have checked it and that directory does not exist. Any responsible of that application can check it?

Regards

**Comment by loumalouomega** [comment]
I don't have any compilation warning

**Comment by loumalouomega** [comment]
![imagen](https://user-images.githubusercontent.com/19991680/31861084-b4cfbaa4-b726-11e7-9c4e-d13d261d3ae0.png)
![imagen](https://user-images.githubusercontent.com/19991680/31861085-bf2c1632-b726-11e7-8d90-2a2726bbcc65.png)
I have the folder too

**Comment by lorenzogracia** [comment]
Hi @loumalouomega , I have checked it in the master and I think there is a mistake in the cmake of the application. In the cmakeList appears the following;

include_directories( ${CMAKE_SOURCE_DIR}/kratos )
include_directories( ${CMAKE_CURRENT_SOURCE_DIR}/external_libraries )
include_directories( ${CMAKE_CURRENT_SOURCE_DIR}/custom_external_libraries/SuperLU_4.3 )
include_directories( ${CMAKE_CURRENT_SOURCE_DIR}/custom_external_libraries )

external_libraries does not exist and it should be external_includes. Also I don't understand why the specification of SuperLU directory in custom_external_libraries but I suppose that this is for some reason.

Regards

**Comment by RiccardoRossi** [comment]
Can u post the warning?

Riccardo

**Comment by lorenzogracia** [comment]
![warning](https://user-images.githubusercontent.com/25606813/31862418-c309ed62-b73d-11e7-8c9f-5310fab8159d.png)

**Comment by RiccardoRossi** [comment]
ok, can u just delete the li e in which you include that directory and make a PR?

**Comment by lorenzogracia** [comment]
Done in #879
