### ISSUE TITLE
Pressures and forces unit of measurement

### ISSUE THREAD

**Issue by demetrafabris** [KratosMultiphysics/Kratos#8783]
If I have a 2D structure on GiD, in what unit of measurement are the pressures and forces I get? Pa and N or are they per linear meter?

**Comment by rubenzorrilla** [comment]
You get the pressure unit corresponding to the consistent unit system you chose divided by a unit length. In SI, this would be Pa/m.

**Comment by demetrafabris** [comment]
Ok, and for forces I should obtain Newton, right?

**Comment by rubenzorrilla** [comment]
Newton/m as the equations are not integrated over h^3 but h^2.
