### ISSUE TITLE
[CI] Mutually exclusive rules required by Codacy

### ISSUE THREAD

**Issue by marandra** [KratosMultiphysics/Kratos#8816]
I am having problems fixing Codacy issues in CI. Apparently, I hit two mutually exclusive rules regarding formating multiline docstrings in python (rules D212 and D213).

D212 says that multiline comments should start in the second line:
```
'''
Docstring.
```
while D213 says multiline docstring should be on the first line, i.e.
```
'''Docstring.
```
Codacy is checking for both.

![Screenshot from 2021-05-26 12-03-36](https://user-images.githubusercontent.com/6945220/119642202-c21c6500-be1a-11eb-878f-8802ff59f8d2.png)

I found this issue [https://github.com/PyCQA/pydocstyle/issues/242](https://github.com/PyCQA/pydocstyle/issues/242) where it says that only one or none rule should be used. I guess it implies setting something in Codacy project-wise. Do you have experience with this issue @philbucher or @roigcarlo ?

_Originally posted by @marandra in https://github.com/KratosMultiphysics/Kratos/issues/8813#issuecomment-848652832_

**Comment by roigcarlo** [comment]
I've made a PR, can you merge that one into your branch and see if codacy passes? (I've disabled the D212 so the correct one should be the multiline one)

**Comment by roigcarlo** [comment]
@marandra Check if works now. If there are more conflicting flags we should be able to ignore them now.

**Comment by marandra** [comment]
Hi @roigcarlo

The `.pydocstyle` file works fine when I run `pydocstyle` locally, but it is not working with Codacy. It is still checking D212 and D213 rules.

Also, I see Codacy checks for D203 (1 blank line before class docstring), in which case it should ignore D211 (0 blank lines before class docstring)

**Comment by roigcarlo** [comment]
Mmm how odd, codacy should use our config file. I will keep trying
