### ISSUE TITLE
[TwoFluid] error in material import in MPI

### ISSUE THREAD

**Issue by RiedlAndreas** [KratosMultiphysics/Kratos#8829]
**Description**
For the MPI simulation with the navier_stokes_two_fluids_solver I get an error in the material import.

```
RuntimeError: (on rank 7): Error: The material file specified with name "FluidMaterials_x.json_1.json" does not exist!
```

I think it has to do with the deprecated import mechanism of the two_fluid_solver.
https://github.com/KratosMultiphysics/Kratos/blob/56ef9e422e22fcb47bf0bdd8cbae9bc8056e0f1e/applications/FluidDynamicsApplication/python_scripts/navier_stokes_two_fluids_solver.py#L298-L325

Is there already an work around or fast solution for this ?

**Comment by mpentek** [comment]
Is there some viable workaround? Or are the subproperties available in the very near future?

Ideally, we could have our simulations done in a week or so...

**Comment by RiedlAndreas** [comment]
So I've done a temporarily workaround for myself by now. 

But I think this still has to be done.

**Comment by RiccardoRossi** [comment]
just to tell that subproperties should be avilable already...

**Comment by rubenzorrilla** [comment]
I'd add that  the design we agreed long time ago to use a property for the main fluid and a subproperty of that for the air.

**Comment by mpentek** [comment]
At which tests can we have a look at to see how the subproperty should used?

https://github.com/KratosMultiphysics/Kratos/tree/master/applications/FluidDynamicsApplication/tests

**Comment by rubenzorrilla** [comment]
> At which tests can we have a look at to see how the subproperty should used?
> 
> https://github.com/KratosMultiphysics/Kratos/tree/master/applications/FluidDynamicsApplication/tests

It is not implemented yet.

**Comment by mpentek** [comment]
> > At which tests can we have a look at to see how the subproperty should used?
> > https://github.com/KratosMultiphysics/Kratos/tree/master/applications/FluidDynamicsApplication/tests
> 
> It is not implemented yet.

Confused by Riccardo's comment

**Comment by mpentek** [comment]
@RiccardoRossi @rubenzorrilla is there a solution with subproperties available? You had slightly altering comments.
Can we close this  because has a solution or there is still none available yet?

**Comment by rubenzorrilla** [comment]
Subproperties are available from long time ago, we just need to start using them in the two fluids solver/elements.

**Comment by RiedlAndreas** [comment]
As far as I understand, it would be possible to change the material import of the twoFluidSolver to subproperties, but this has not been done yet. Is this correct ?

**Comment by rubenzorrilla** [comment]
> As far as I understand, it would be possible to change the material import of the twoFluidSolver to subproperties, but this has not been done yet. Is this correct ?

Correct. Long time ago we agreed on having the main property for the fluid phase and the air properties as a subproperty of it.

**Comment by mpentek** [comment]
What is the appropriate way to proceed? 

**Solution 1** => For now, actually the more robust solution is to have the properties defined in the MDPA, this is a very old manner, but works with only a small change. Like this no material properties should be specified in through a dedicated JSON-file. this also needs a small "hack" in the python layer, as the properties are now solely imported through `NodalProperties`. This solution also work in MPI.

https://github.com/KratosMultiphysics/Kratos/blob/900b1337b13d682133fd57ab0f4f256611fbd746/applications/FluidDynamicsApplication/python_scripts/navier_stokes_two_fluids_solver.py#L379

```
self._SetNodalProperties()
materials_imported = True
```

Example properties in the MDPA:
```
Begin ModelPartData
//  VARIABLE_NAME value
End ModelPartData

Begin Properties 0
    DENSITY 1.0,
    DYNAMIC_VISCOSITY 1.0
    CONSTITUTIVE_LAW Newtonian2DLaw
End Properties

Begin Properties 1
    DENSITY 1000.0,
    DYNAMIC_VISCOSITY 1.0e-3
    CONSTITUTIVE_LAW Newtonian2DLaw
End Properties

Begin Properties 2
    DENSITY 1.2,
    DYNAMIC_VISCOSITY 1.0e-5
    CONSTITUTIVE_LAW Newtonian2DLaw
End Properties
```
 
**Solution 2** => A way to switch to subproperties would imply changing the JSON file used as well as certain changes in the python layer.

Making sure the subproperties are read in properly and getting rid of the old way:
https://github.com/KratosMultiphysics/Kratos/blob/900b1337b13d682133fd57ab0f4f256611fbd746/applications/FluidDynamicsApplication/python_scripts/navier_stokes_two_fluids_solver.py#L354
```
materials = KratosMultiphysics.Parameters(materials_file.read())

# Add constitutive laws and material properties from json file to model parts.
material_settings = KratosMultiphysics.Parameters("""{"Parameters": {"materials_filename": ""}} """)
material_settings["Parameters"]["materials_filename"].SetString(materials_filename)
KratosMultiphysics.ReadMaterialsUtility(material_settings, self.model)

# A new funciton to set subproperties
self._SetSubProperties() 

# Remove existing code

materials_imported = True
```

```
# Define a new function to set subproperties correctly
def _SetSubProperties(self): 
     prop1 = self.main_model_part.GetProperties()[1]
     subprop11 = prop1.GetSubProperties(11)
     subprop12 = prop1.GetSubProperties(12)

    [...]
```

Any potential conflict of _SetSubProperties() with _SetNodelProperties()? Why would both be needed? Elements seem to be always expected to have nodal properties.
https://github.com/KratosMultiphysics/Kratos/blob/900b1337b13d682133fd57ab0f4f256611fbd746/applications/FluidDynamicsApplication/python_scripts/navier_stokes_two_fluids_solver.py#L122

==>> [Here is](https://syncandshare.lrz.de/getlink/fiBg52qFuLe9h7JbewtWUjWv/TestTwoFluid) an example.

**Comment by philbucher** [comment]
#9615 implements the hotfix for this until the SubProperties are used

**Comment by rubenzorrilla** [comment]
> @rubenzorrilla @uxuech What is the appropriate way to proceed?
> 
> **Solution 1** => For now, actually the more robust solution is to have the properties defined in the MDPA, this is a very old manner, but works with only a small change. Like this no material properties should be specified in through a dedicated JSON-file. this also needs a small "hack" in the python layer, as the properties are now solely imported through `NodalProperties`. This solution also works in MPI.
> 
> https://github.com/KratosMultiphysics/Kratos/blob/900b1337b13d682133fd57ab0f4f256611fbd746/applications/FluidDynamicsApplication/python_scripts/navier_stokes_two_fluids_solver.py#L379
> 
> ```
> self._SetNodalProperties()
> materials_imported = True
> ```
> 
> Example properties in the MDPA:
> 
> ```
> Begin ModelPartData
> //  VARIABLE_NAME value
> End ModelPartData
> 
> Begin Properties 0
>     DENSITY 1.0,
>     DYNAMIC_VISCOSITY 1.0
>     CONSTITUTIVE_LAW Newtonian2DLaw
> End Properties
> 
> Begin Properties 1
>     DENSITY 1000.0,
>     DYNAMIC_VISCOSITY 1.0e-3
>     CONSTITUTIVE_LAW Newtonian2DLaw
> End Properties
> 
> Begin Properties 2
>     DENSITY 1.2,
>     DYNAMIC_VISCOSITY 1.0e-5
>     CONSTITUTIVE_LAW Newtonian2DLaw
> End Properties
> ```
> 
> **Solution 2** => A way to switch to subproperties would imply changing the JSON file used as well as certain changes in the python layer.
> 
> Making sure the subproperties are read in properly and getting rid of the old way:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/900b1337b13d682133fd57ab0f4f256611fbd746/applications/FluidDynamicsApplication/python_scripts/navier_stokes_two_fluids_solver.py#L354
> 
> ```
> materials = KratosMultiphysics.Parameters(materials_file.read())
> 
> # Add constitutive laws and material properties from json file to model parts.
> material_settings = KratosMultiphysics.Parameters("""{"Parameters": {"materials_filename": ""}} """)
> material_settings["Parameters"]["materials_filename"].SetString(materials_filename)
> KratosMultiphysics.ReadMaterialsUtility(material_settings, self.model)
> 
> # A new function to set subproperties
> self._SetSubProperties() 
> 
> # Remove existing code
> 
> materials_imported = True
> ```
> 
> ```
> # Define a new function to set subproperties correctly
> def _SetSubProperties(self): 
>      prop1 = self.main_model_part.GetProperties()[1]
>      subprop11 = prop1.GetSubProperties(11)
>      subprop12 = prop1.GetSubProperties(12)
> 
>     [...]
> ```
> 
> Any potential conflict of _SetSubProperties() with _SetNodalProperties()? Why would both be needed? Elements seem to be always expected to have nodal properties.
> 
> https://github.com/KratosMultiphysics/Kratos/blob/900b1337b13d682133fd57ab0f4f256611fbd746/applications/FluidDynamicsApplication/python_scripts/navier_stokes_two_fluids_solver.py#L122
> 
> ==>> [Here is](https://syncandshare.lrz.de/getlink/fiBg52qFuLe9h7JbewtWUjWv/TestTwoFluid) an example.

Sorry @mpentek I missed your post. The original idea we agreed about was to set the fluid phase properties as we normally do and create one subproperty of it containing the air phase material settings.
