### ISSUE TITLE
Related to the header file "residualbased_elimination_builder_and_solver_slip.h"

### ISSUE THREAD

**Issue by ashishdarekar** [KratosMultiphysics/Kratos#8854]
**Description**
While Porting OMP stuff to Parallel Utilities (in PR #8853):
I have observed that, this [header file ](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/builder_and_solvers/residualbased_elimination_builder_and_solver_slip.h) is not included in the compilation or not used anymore, is it so? 

**Scope**
- Compilation
- KratosCore

**Comment by loumalouomega** [comment]
@KratosMultiphysics/technical-committee

**Comment by philbucher** [comment]
@sunethwarna don't you use this?

**Comment by sunethwarna** [comment]
@philbucher I am not using this. I have not used any of the elimination B&Ss.

**Comment by pooyan-dadvand** [comment]
I think this is an old one from @RiccardoRossi

**Comment by roigcarlo** [comment]
From @KratosMultiphysics/technical-committee we agree that this is probably a leftover and can be safely deleted.
