### ISSUE TITLE
Why serializer doesn't use zlib?

### ISSUE THREAD

**Issue by philbucher** [KratosMultiphysics/Kratos#8855]
I currently have to do some Serialization so I also took a look at the serializer of Kratos.

Why don't we use zlib (which we already have integrated since forever) for compressing the serialized stream? I think this would be really handy for the restart files, which are usually quite large IMO

@KratosMultiphysics/technical-committee 

FYI @mpentek

**Comment by RiccardoRossi** [comment]
in my opinion it should not be directly in the serializer, but rather at
the moment of writing to disk.

my point is that the serializer is also used for "generic" mpi
communications and you definitely don't want the zlib in there...

**Comment by philbucher** [comment]
sure it should be optional

I was talking about the fileserializer anyway :)

**Comment by pooyan-dadvand** [comment]
I think it is a good addition but as @RiccardoRossi said in the buffer level. Nevertheless, for that, we should refactor the serializer to accept a SerializationIO object. (The effort is not big as I have separate methods in buffer level)
