### ISSUE TITLE
[Core, MPI] testDiscontinuousDistanceProcess fails with 8 cores.

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#8859]
testDiscontinuousDistanceProcessCutOnEdge2D and testDiscontinuousDistanceProcessCutThroughNode2D  from test_mpi_processes are failing when running with 8 cores (segmentation fault). It is not shown in ci as we only use 4,3 and 2 cores.

GDB seems to complain about this line.
https://github.com/KratosMultiphysics/Kratos/blob/efb3ea461e6119ca1427a6b3ba98a1711e98fd2b/kratos/processes/find_intersected_geometrical_objects_process.cpp#L284

I guess the problem is that some partitions might be empty so when trying to access NodesBegin you get the segmentation fault. This is what I found so far @uksajja 

Just pinging some people that might be related to this problem. @loumalouomega @marcnunezc @rubenzorrilla

**Comment by uksajja** [comment]
Thank you @ddiezrod

**Comment by ddiezrod** [comment]
> You mean 8 MPI cores, not 8 threads?

yep, thats it.

**Comment by marcnunezc** [comment]
Thanks for reporting! My bad, I should have checked the test with more procs when adding it. Adding a possible fix in #8862
