### ISSUE TITLE
[core] Grouping all tasks of one step in one function (without the 'while')

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#8867]
**Description**
In many occasions, when coupling applications, I found myself copying this whole chunk from the AnalysisStage:

```
self.time = self._GetSolver().AdvanceInTime(self.time)            
self.InitializeSolutionStep()            
self._GetSolver().Predict()            
is_converged = self._GetSolver().SolveSolutionStep()            
self.__CheckIfSolveSolutionStepReturnsAValue(is_converged)            
self.FinalizeSolutionStep()            
self.OutputSolutionStep()
```

from https://github.com/KratosMultiphysics/Kratos/blob/398d72a87daf598402274ddb00f45b5967b377e0/kratos/python_scripts/analysis_stage.py#L57

These are many lines which could be grouped in a function like, say, 'DoAllTasksOfOneStep'. It would save a lot of copy and paste when coupling applications.
@philbucher , how did you guys solve this problem?

Can we edit the AnalysisStage such that it makes: 

```
def RunSolutionLoop(self):
    while self.KeepAdvancingSolutionLoop():
        self.DoAllTasksOfOneStep()
```
?

**Comment by philbucher** [comment]
pinging @RiccardoRossi as he has a stong opinion iirc

The reason this was deliberately not added is the same as the motivation for removing the `Solve` method from strategies & solvers:
It is easy to use wrong!

In a strong coupling ONLY the `SolveSolutionStep` can be called multiple times
In the past it was observed that the `Solve` method (which is essentially the same as your `DoAllTasksOfOneStep`) was called, even inside strong coupling loops. I remember that for FSI it took us quite a while to figure out and correct it

in the CoSimApp I have a list of solvers on which I call the corresponding methods. => this is done in the [baseclass of our coupled solver](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/base_classes/co_simulation_coupled_solver.py)

=> for different ways of coupling we then implement different methods for `SolveSolutionStep`, e.g. only one after the other (weak coupling) or iterative (strong coupling)

can you point me to one of your implementations for improving my understanding of how you do it?

**Comment by maceligueta** [comment]
Basically, I often find myself in this substepping situation:

```
        while self.poromechanics_solution.KeepAdvancingSolutionLoop():
            self.poromechanics_solution.time = self.poromechanics_solution._GetSolver().AdvanceInTime(self.poromechanics_solution.time)
            self.poromechanics_solution.InitializeSolutionStep()
            self.poromechanics_solution._GetSolver().Predict()
            self.poromechanics_solution._GetSolver().SolveSolutionStep()
            self.poromechanics_solution.FinalizeSolutionStep()
            self.poromechanics_solution.OutputSolutionStep()

            self.effective_stresses_communicator.CopyWallCurrentEffectiveStressesToOldEffectiveStresses()
            self.effective_stresses_communicator.CommunicateCurrentRadialEffectiveStressesToDemWalls()

            time_final_DEM_substepping = self.poromechanics_solution.time
            self.Dt_DEM = self.dem_solution.spheres_model_part.ProcessInfo.GetValue(Kratos.DELTA_TIME)

            for self.dem_solution.time_dem in self._YieldDEMTime(self.dem_solution.time, time_final_DEM_substepping, self.Dt_DEM):
                self.dem_solution.time = self.dem_solution._GetSolver().AdvanceInTime(self.dem_solution.time)
                self.dem_solution.InitializeSolutionStep()
                self.dem_solution._GetSolver().Predict()
                self.dem_solution._GetSolver().SolveSolutionStep()
                self.dem_solution.FinalizeSolutionStep()
                self.dem_solution.OutputSolutionStep()
```

**Comment by rubenzorrilla** [comment]
In this I agree @philbucher and @RiccardoRossi. Even though the new function would be useful for one way coupling approaches, misuses of it would be much more prone to happen. On top of that, it would be exactly the same as the `Solve` method which was removed from the Python solver and its being deprecated in the solving strategies.

**Comment by maceligueta** [comment]
Maybe the problem was the word 'Solve'. It is actually quite misleading especially if it's a method of the solver. One might easily expect it to just solve the system.

**Comment by philbucher** [comment]
I see your point
I would have no objections adding such a method as it can be useful for cases like yours 

lets hear what @RiccardoRossi has to say

**Comment by RiccardoRossi** [comment]
I confirm that this waseparated on purpose. The function "Solve" existed and we took it out to make explicit what the steps are, in view of allowing for example the possibility of doing substepping.

this is also important for example when one has plasticity, since the finalization is done in the FinalizeSolutionStep, and one CANNOT call multiple time such function in the case of a coupled solution.

Still, as a quick workaround, one can define on the user side a function "SolveBlock" on the line of 

~~~py
def MyInternalSolveHelper(solution):
    solution.time = solution._GetSolver().AdvanceInTime(self.poromechanics_solution.time)
    solution.InitializeSolutionStep()
    solution._GetSolver().Predict()
    solution._GetSolver().SolveSolutionStep()
    solution.FinalizeSolutionStep()
    solution.OutputSolutionStep()
~~~
