### ISSUE TITLE
Point.h  compilation error Windows

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#887]
I get an error when compiling Kratos with Visual Studio. 

As point.h is not longer a template, typename cannot be used in Visual Studio

C:\Kratos\kratos\geometries/point.h(83): error C2899: typename cannot be used outside a template declaration

@pooyan-dadvand  I guess you can simply delete them right?

**Comment by pooyan-dadvand** [comment]
oops, my fault. let me update the file.

**Comment by ddiezrod** [comment]
@loumalouomega Found the same error in the condition_number_utility (lines 68 to 74)

**Comment by pooyan-dadvand** [comment]
I have just remove them from condition number utility in branch fix-issue-887

**Comment by loumalouomega** [comment]
@pooyan-dadvand So it is done?

**Comment by pooyan-dadvand** [comment]
yep, in PR #888

**Comment by loumalouomega** [comment]
Ok
