### ISSUE TITLE
problems with RVE analysis

### ISSUE THREAD

**Issue by NargesDlm** [KratosMultiphysics/Kratos#8890]
Good afternoon,

I'm using Kratos in Windows (via GUI inside GiD) for RVE analysis.
Its works fine for a geometry aligned with the axes, however, when rotating the geometry by 45º, I get the following error: " ConstructFaceModelParts ("min_x_face has 0 conditions"".

Could you please give me some hints regarding what the problem could be?

Im attaching the snapshots of the "rotated" geometry.
![3D_view](https://user-images.githubusercontent.com/86110052/122558432-5eaedd00-d03e-11eb-85b4-ac6f25a66c3b.png)
![top_view](https://user-images.githubusercontent.com/86110052/122558435-5f477380-d03e-11eb-96b1-15a9a19b64ed.png)

Kind regards,
Narges

**Comment by RiccardoRossi** [comment]
you should have "conjditions" applied to the different faces. Such
conditions are needed to find the matching between the opposite faces

**Comment by rubenzorrilla** [comment]
Closing as I think this is already solved. @NargesDlm feel free to reopen if needed.
