### ISSUE TITLE
[Core] Parallel Level Set Distance Calculation Process

### ISSUE THREAD

**Issue by sunethwarna** [KratosMultiphysics/Kratos#8901]
**Description**
I used `ParallelLevelSetDistanceCalculatorProcess` to calculate distance of internal flow over the cylinder case. Top, bottom and the middle cylinder are walls from which I need to calculate the distances to internal nodes. 

The coordinates of the fluid domain rectangle
lower left = [0, 0]
upper right = [2.2, 0.41]

Cylinder:
Center = [0.2, 0.2]
diameter = 0.1

First mesh (with inner refinement box):
![image](https://user-images.githubusercontent.com/7856520/122765935-47bbf500-d2a1-11eb-959b-63bcc2a30bea.png)

Distance calculation
![image](https://user-images.githubusercontent.com/7856520/122765833-2f4bda80-d2a1-11eb-9141-99424fd584f4.png)

But if I use a different mesh the result looks like the following: (no inner refinement box)
![image](https://user-images.githubusercontent.com/7856520/122766560-fb24e980-d2a1-11eb-9699-863d33366d94.png)

Distance calculation
![image](https://user-images.githubusercontent.com/7856520/122766493-e6e0ec80-d2a1-11eb-9e8a-2aaeb4e86108.png)

As you can see, when I have the inner refinement box, there are large distance gradients, this is reduced when no inner refinement box used. This only happened when I used more than one surfaces as walls for distance calculation (top, bottom and cylinder). If I used only cylinder as the wall, then the distances are correct.

Is this the intended behaviour? Is `DISTANCE` from `ParallelLevelSetDistanceCalculator` supposed to be mesh dependent?

I used `max_levels=1e+5` as well, it does not change the outcome.

Followings are the steps I use to calculate distances using `ParallelLevelSetDistanceCalculationProcess`:
1. Assign all wall nodes with `-1e-12` distance.
2. Assign all neighbourr nodes of wall nodes with correctly calculated wall distances
3. Assign rest of the nodes with `1e+30`
4. Use `ParallelLevelSetDistanceCalculationProcess::CalculateDistances` method
5. Revert all wall negative nodal distances to 0.0

@rubenzorrilla, @RiccardoRossi ?

FYI: @adityaghantasala 

**Scope**
- KratosCore

**Comment by ddiezrod** [comment]
Im afraid this is an "expected" outcome from ParallelLevelSetDistanceCalculatorProcess. It advances layer by layer from all interfaces, so solution from one side might advance quicker if element size is bigger on that area, resulting in that kind of "shocks" between fronts advancing from different interfaces. It could be solved by advancing from the nodes with lowest distances instead of going layer by layer, though it might be not worthy the effort (and probably not efficient at all)

**Comment by sunethwarna** [comment]
@ddiezrod Thanks :)
