### ISSUE TITLE
Segmentation fault in DistanceModificationProcess in MPI

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/Kratos#8921]
**Description**
When using `distance_modification_process` with an empty modelpart, a segmentation fault occurs. The most usual scenario for this to happen is when using MPI and the modelpart is small relative to the whole model.

This is because in [line 126](https://github.com/KratosMultiphysics/Kratos/blob/ff0492769ee978c50c7e9e2e8cfea34fb1689ce5/applications/FluidDynamicsApplication/custom_processes/distance_modification_process.cpp#L126), an iterator to end is dereferenced when the modelpart has no nodes:
```
const auto& r_node = *mrModelPart.NodesBegin();
```

**Scope**
FluidDynamicsApplication

**To Reproduce**
Attempt to use  `Kratos::DistanceModificationProcess::ExecuteInitialize` on either of these:
- An empty modelpart.
- With MPI, a small model that cannot be distributed amongst all partitions, hence some are empty.
- With MPI, a modelpart that takes up a small proportion of the model, so that some some partitions have no nodes from that modelpart.

**Expected behavior**
Since the modelpart has no nodes, nothing should happen.

**Environment**
Should not depend on environment, but here is my particular setup:
- OS: Centos8  (With WSL, running on Windows 10)
- Branch: master
- Python 3.7

**Comment by rubenzorrilla** [comment]
Should be readily fixed by adding an empty partitions check. I'll do it ASAP. Thanks for reporting.
