### ISSUE TITLE
FSI upgrade (including MPI environment) merge

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#893]
With regard to the FSI application, the new features and modifications to be included to the master before the next release packaging are:

- [x] the recent upgrades (large portions of the code have been migrated to C++)
- [x] the new MPI environment
- [x] check that the SetInterfaceProcess is no longer needed

**Comment by pooyan-dadvand** [comment]
:+1: 

So everything is already in master? There are no more action to be taken?

**Comment by rubenzorrilla** [comment]
I have to merge my current branch. The Kratos part is already finished but there are a minor issues with the interface (I'll work on it today). My intention is to merge both things together.

**Comment by pooyan-dadvand** [comment]
Perfect! :+1:

**Comment by rubenzorrilla** [comment]
With the PR #898 the first and second tasks above are completed. I would try to do another PR to get rid of the FSI application SetInterfaceProcess, which I think it is no longer needed.

With regard to the interface, I would keep the double sided surfaces FSI interface for the next release (we already have the capabilities ready in Kratos).

**Comment by RiccardoRossi** [comment]
this is now done no? if so please close
