### ISSUE TITLE
PFEM2Application doesn't compile in Debug Mode.

### ISSUE THREAD

**Issue by dcagritan** [KratosMultiphysics/Kratos#8931]
**Description**
PFEM2Application doesn't compile in Debug Mode. 

**Scope**
-PFEM2Application

**To Reproduce**
I get the following error:

**_CMake Error at applications/PFEM2Application/cmake_install.cmake:390 (file):
  file RPATH_CHANGE could not write new RPATH:

    $ORIGIN/../libs

  to the file:

    /home/dcagritan/Kratos/bin/Debug/libs/KratosPFEM2Application.cpython-38d-x86_64-linux-gnu.so

  No valid ELF RPATH or RUNPATH entry exists in the file; Error reading ELF
  identification.
Call Stack (most recent call first):
  cmake_install.cmake:111 (include)

make: *** [Makefile:86: install] Error 1_**

**Environment**
- OS: Ubuntu 20.04

Dear all,
I'm pretty sure this is something trivial, however unfortunately my knowledge in CMake is limited. Therefore I'd appreciate your help.
Regards!

**Comment by roigcarlo** [comment]
That's looks like if there were a really old installation already in place:

My recommendation would be to delete the whole Kratos folder and try again.

If that is not possible:
1 - Delete the build folder,
2 - Delete the bin folder
3 - Delete the cmake cache ( if present )
4 - `export RPATH=`

And try.

**Comment by dcagri** [comment]
Hello Carlos,
thank you for your answer. I'll try that out and write the results here.
Have a good day!
Regards

**Comment by roigcarlo** [comment]
@dcagritan Closing the issue, please reopen if it keeps failing.
