### ISSUE TITLE
Lid-Driven Cavity Viscoelastic fluid simulation

### ISSUE THREAD

**Issue by alecontri** [KratosMultiphysics/Kratos#8943]
**Description**
Goodmorning to all. Recently, I stumbled across a paper in which a Lid Driven Cavity simulation of an Oldroyd-B viscoelastic fluid was performed. I know that, in Kratos, a Maxwell and a Kelvin viscoelastic model are currently implemented in the ConstitutiveLawsApplication (and thus can be used within the StructuralMechanicsApplication, right?). I was wandering if a similar simulation can thus be achieved (using one of the provided models, not the Oldroyd-B type) with the existing code and, if yes, what are the steps to be followed. My doubts are things like:
- can I use the StructuralMechanicsApplication for the Cavity problem?
- if yes, what's the correct way (processes to utilize ecc.) to set up the problem i.e. imposing eulerian no slip condition at the wall and eulerian imposed velocity on the top?

and so on, more than the overall stability and correctness of the simulation (I read Maxwell model is suitable for small deformations while here we are tackling finite deformations ecc. ecc.).
I would be very grateful if someone could help me and thank you in advance for your help.

**Scope**
- Viscoelastic Models
- ConstitutiveLawsApplication
- StructuralMechanicsApplication

**Comment by RiccardoRossi** [comment]
i am not an expert in this, so my comments may actually be wrong, however
the main issue i see is that the CL models you describe are designed to
work using a lagrangian approach, and i believe they will not work if you
attempt to use an eulerian one.

may take at viscoelastic would be to try using the mpm application.

i am cc-ing Dr Larese who is in charge

**Comment by alecontri** [comment]
Thank you for your prompt answer professor Rossi, that was the focus of my question. Can I impose eulerian Dirichlet and Neumann boundary conditions even in a Lagrangian framework as in the StructuralMechanicsApplication?
Actually I am studying the MPM and its Kratos implementation and I am in contact with professor Larese de Tetto, but I was looking for possible already existing implementations of that kind of problems also for possible comparisons.

**Comment by RiccardoRossi** [comment]
you will have to have a wall that actually moves if you want to do it
lagrangian.

the problem is elasticoty. tje viscous part could be done eulerian easily

**Comment by alecontri** [comment]
Yes, I understand. Thank you for the answer!
