### ISSUE TITLE
[CoSim] Coupling operations in between coupled solver calls is not possible yet

### ISSUE THREAD

**Issue by ceulogiof** [KratosMultiphysics/Kratos#8965]
**Description & Scope**
While coupling an FSI problem (by using the PfemFluidDynamicsApplication and the StructuralMechanicsApplication), I need to perform a coupling operation right after the first coupled solver (in this case the pfem fluid solver) finishes calling its own `SolveSolutionStep()` (for instance, for computing the boundary forces exerted from the fluid onto the structure).
The problem is that the current Gauss Seidel weak and strong coupling scripts only perform coupling operations at:
- `InitializeCouplingIteration()`
- `FinalizeCouplingIteration()`

which is before and after *both* involved solvers are called:

https://github.com/KratosMultiphysics/Kratos/blob/67544f5b16f74fc4669ce0c9bab4504fca33807a/applications/CoSimulationApplication/python_scripts/coupled_solvers/gauss_seidel_weak.py#L8-L18

I am aware that another option is using a Kratos Process. After checking the `process.h` file, the closest function `ExecuteFinalizeSolutionStep()` is only performed *after* both involved solvers have been called, so this is not flexible enough.

The idea is to include a function in the coupling operations called (maybe) `FinalizeSolveSolutionStep()` together with a check to do any operations for the coupling that specifically require to be called right after one solver finishes its computations:

```
                solver.SolveSolutionStep()
                # solving only the coupling operations of the current solver
                for coupling_op in self.coupling_operations_dict.values():
                    if coupling_op.settings["solver"].GetString() == solver_name:
                        coupling_op.FinalizeSolveSolutionStep()
```

This would also require to add a definition of `FinalizeSolveSolutionStep()`  in between here in `co_simulation_coupling_operation.py`:

https://github.com/KratosMultiphysics/Kratos/blob/67544f5b16f74fc4669ce0c9bab4504fca33807a/applications/CoSimulationApplication/python_scripts/base_classes/co_simulation_coupling_operation.py#L33-L34

```
    def FinalizeSolveSolutionStep(self):
        pass
```

https://github.com/KratosMultiphysics/Kratos/blob/67544f5b16f74fc4669ce0c9bab4504fca33807a/applications/CoSimulationApplication/python_scripts/base_classes/co_simulation_coupling_operation.py#L36-L37

**Side Note**
I did try to invert the order of the solvers: Solve first FEM and then the PFEM, such that the `FinalizeCouplingIteration()` is called right after the PFEM solves, but this results in the simulation crashing after some time, whereas with this extra function proposed here, my simulations run as expected.
- Another reason to implement this is if a user wants to couple 3 solvers directly, rather than using nested CoSimulation, so that they can still have a coupling operation in between solver calls.

**Environment**
- OS: Ubuntu 18.04
- Branch: StructMech/couple_pfem
- Python 3.6.9

**Comment by philbucher** [comment]
Short answer:
This is already possible, check how the normals are computed in the mpm-fem coupling 
(Check the tests for the NormalsComputationCouplingOperation)

**Comment by ceulogiof** [comment]
Thank you very much Philipp, I checked and it was very simple to change in my `cosim_parameters.json` script. It works as expected! I will close the issue then.

**Comment by ceulogiof** [comment]
@philbucher I have a new question in this same area: is it possible to perform a coupling operation that is called at `Execute()` (so right in between solver calls) but without any data transfer?

**Comment by philbucher** [comment]
hi,
I don't think that is possible, as the CouplingOperation is not associated with a solver

I think you might need to do this in the `SolverWrapper` (see the `MPM-SolverWrapper` as [reference](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/solver_wrappers/kratos/particle_mechanics_wrapper.py#L26-L59))

**Comment by ceulogiof** [comment]
Thanks again for the hint! This is precisely what I need. I will close again this issue, hehe.
