### ISSUE TITLE
[core] Kratos Parameters copy constructor builds a non-independent object, just a pointer to the same Parameters.

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#8988]
**Description**
For a copy constructor, I would expect the creation of a new object, completely independent from the provided one.
The current implementation
https://github.com/KratosMultiphysics/Kratos/blob/0dbba4eca7d08ffcc251116c1b683ca73ea49d77/kratos/sources/kratos_parameters.cpp#L231
just copies pointers, so we essentially have the same object with a different name. If I wanted that I could create my own pointer or a reference.
I would expect a behavior like the one coded in the `= operator`:
https://github.com/KratosMultiphysics/Kratos/blob/0dbba4eca7d08ffcc251116c1b683ca73ea49d77/kratos/sources/kratos_parameters.cpp#L249
From Python, it is quite hard to get a deepcopy of Kratos Parameters, unless we change the behavior of this constructor. Then it would be very easy.
Can we change this? 
@RiccardoRossi 
@loumalouomega 
@KratosMultiphysics/technical-committee

**Comment by loumalouomega** [comment]
I don't remember why I did that...

**Comment by ddiezrod** [comment]
I think this is the intended functioning and we use it a lot in @KratosMultiphysics/altair side. Our point is to have a unique "solver_settings" and all its options are propagated, validated and autocompleted in all the small pieces of the code. If I understand you correctly this would not work anymore in most cases.

**Comment by maceligueta** [comment]
Yes, I am thinking of cases where the settings would be duplicated, no longer unique. That's exactly what I need at the moment.
If we keep it as it is, I will try to find a way to deepcopy the parameters from Python, or any other solution.
Apart from practical aspects, from a phylosophical point of view I still think that a copy constructor should actually copy the contents, not just point to the same information.

**Comment by maceligueta** [comment]
We could add a method called 
`Parameters& Parameters::DeepCopy(Parameters const& rOther) `

**Comment by loumalouomega** [comment]
Operator = does a deep copy: https://github.com/KratosMultiphysics/Kratos/blob/e8072d8e24ab6f312765185b19d439f01ab7b27b/kratos/sources/kratos_parameters.cpp#L249

**Comment by maceligueta** [comment]
But I can't call it from Python, can I?

**Comment by loumalouomega** [comment]
We only need to expose it

**Comment by loumalouomega** [comment]
I did #8989, but take it as a grain of salt, I'm not in my computer and I did a blind PR from the phone and I don't know if compiles or if it works
