### ISSUE TITLE
About Travis failing

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#899]
@KratosMultiphysics/team-maintainers @KratosMultiphysics/technical-committee As you may have notice builds are having unusual timeouts.

There is (finally) an official confirmation that there is a problem in Travis with docker image (the ones used in kratos).
https://www.traviscistatus.com/incidents/v4jnp6nkgzqx

Expect builds to behave normally again when this is solved.

Also remind you that times are already very tight so even with normal behavior timeouts may appear from time to time. You can tell travis to re-build by clicking on details -> rebuild ( top right corner) if this happen

**Comment by maceligueta** [comment]
@roigcarlo : I can't find this: You can tell travis to re-build by clicking on details -> rebuild ( top right corner) if this happen
Where is it exactly? In GitHub or in Travis?

**Comment by roigcarlo** [comment]
"details" is in github, the rebuild button is in travis

**Comment by maceligueta** [comment]
I see. I had to log in to see the Re-build button. It is not there if you don't log in with the Github credentials.

**Comment by roigcarlo** [comment]
Oh right, sorry forgot to write that :P you need to be logged with your github account, otherwise anyone could restart builds.
