### ISSUE TITLE
Compiling Katos using VS 2017

### ISSUE THREAD

**Issue by oberbichler** [KratosMultiphysics/Kratos#901]
Hi!
Are there any experiences with Visual Studio 2017/Boost 1.65.1?

Greetings
Thomas

**Comment by roigcarlo** [comment]
Hi @oberbichler ,

You should  be able to compile with 2017 and boost 1.65 with no problem.
There have been however some reports of problems with boost 1.65 and python3

If you find any problem detecting or linking boost-python with python3, please add:
```C++
-DBOOST_PYTHON_SUFFIX="3" ^
``` 

To the configure file and it should solve it

**Comment by oberbichler** [comment]
Works like a charm with VS 2017 (15.3.3), Boost 1.65.1 and Python 3.6 (miniconda3).

Thanks!
