### ISSUE TITLE
Debug Kratos in Windows with Visual Studio ignoring breakouts

### ISSUE THREAD

**Issue by alecontri** [KratosMultiphysics/Kratos#9010]
Hello everyone,
I am encountering the exact same problem of #1464 . 
I configured Kratos in FullDebug mode building from command prompt (-DINSTALL_RUNKRATOS=OFF). Then I followed the steps in order to debug the C++ code using only Visual Studio as described in the Wiki "Debugging Kratos using Visual Studio", which are the ones described in the issue above.
I am using the GiD example from the ParticleMechanicsApplication as test case. It runs without errors from prompt and from Visual Studio when I use "Start a new instance" from Kratos>Debug in the solution explorer. Unfortunately the breakouts are completely ignored (I placed a lot randomly all over the updated_lagrangian.cpp file). Moreover, if I try using "Start a new instance" selecting the ParticleMechanicsApplication I get an error saying "Invalid Win32 application".
I attach an image on how I've modified Kratos Property Pages> Debugging> Environment
![Cattura](https://user-images.githubusercontent.com/82971238/127023458-74f2feba-b743-4eed-8b2e-7bcfc65e09c5.JPG)
PYTHONPATH is "C:\Kratos\bin\FullDebug". I tried also writing explicitly the paths needed but nothing changes.
Thank you very much in advance for your help!

**Scope**
- Visual Studio C++ Debug

**Environment**
- OS: Windows 10
- Branch: master
- Python 3.7
- Visual Studio 2019

**Comment by roigcarlo** [comment]
Hi @alecontri 

I will need some more info to help you with this:

1) From the screen you posted, seems that neither `PATH` or `PYTHONPATH` are set correctly. In order to be set inside VS you need to specify the values (like the 3rd `PATH` that appears under `Valore valutato`). If those variables are not set, technically you should not be able to even start a case. If you are able to do so, then it means you have those variables defined in your S.O. env variables. Could you confirm that? If so, could you shown me the values they have?.

2) Additionally, could you send me a screen or post the values you have in the `Kratos` Project (on the tree explorer in one of the sides), **properties -> Debugging**?

3) Also please, could you upload the configure.bat script that you used to generate the current VS solution?

**Comment by alecontri** [comment]
Thank you very much for your answer! So, I can confirm they are set in the O.S env variables. Here it is for PYTHONPATH
![Cattura1](https://user-images.githubusercontent.com/82971238/127134816-c0ffacb9-ccda-4d98-a70d-0efc3282c49a.JPG)
and for PATH
![Cattura2](https://user-images.githubusercontent.com/82971238/127134895-dfbb66c3-a778-4739-942c-c37f66a68cc4.JPG)
Then, this is the Properties->Debug
![Cattura](https://user-images.githubusercontent.com/82971238/127134792-3653059f-04c4-4d13-bd33-146988aec8bb.JPG)
And finally this is the configure file changed in .txt format I used:
[configure_deb.txt](https://github.com/KratosMultiphysics/Kratos/files/6884519/configure_deb.txt)

I now tried and even without PATH and PYTHONPATH in the Properties->Debug->Environment I have the same behaviour as in the beginning.

**Comment by roigcarlo** [comment]
Seems that everythong is fine, so I am not sure which is the problem. 

I assume that the breakpoints that you are setting suddently turn "empty" and a yellow exclamation mark appears next to them. It may be a problem of running the case through the python wrapper as it instructs VS not to look for pdb files.

Try going to **Debug -> Options** in Visual Studio:
![image](https://user-images.githubusercontent.com/1935791/127143978-03dee5b4-d219-4279-86bc-743a0d077bd2.png)

In the "Symbols" section, try to add the Kratos/Build/FullDebug dir (not the bin) and try to run with this.

**Comment by alecontri** [comment]
I did what you said, but nothing changes. The message shown by the breakpoints is "No symbol is loaded for this document".
I don't know if it is needed as information, but I installed only "Python native development tools" in the Visual Studio Installer, while I used Python 3.7 from the official site in order to install Kratos (the only version py.exe is pointing in theory).

**Comment by roigcarlo** [comment]
Yep the error is what I suspected, essentially it cannot find the *.pdb files which are located inside the build folder, but normally it does it automatically. Let me try to reproduce it in my machine to see if I can come up with a solution.

**Comment by ddiezrod** [comment]
If I remember correctly I was never able to use breakpoints in Debug/FullDebug in vscode, only in RelWithDebInfo...

**Comment by roigcarlo** [comment]
It is really odd. I am having no problems loading the debug symbols, either in RelWebDebInfo, Debug or FullDebug, I've tried all of them. Still trying with different versions of python, let's see if this is the problem.

**Comment by alecontri** [comment]
I'm sorry but unfortunately, due to a sudden duty, I won't be able to try solutions, including trying installing the RelWithDebInfo version, for some days. I thank you both for the advice and effort, as soon as I will be back I will try and inform you about the results

**Comment by alecontri** [comment]
Ok, I re-installed Kratos in RelWithDebInfo mode (same configuration file, just switching to "set KRATOS_BUILD_TYPE=RelWithDebInfo" and deleting "-DINSTALL_RUNKRATOS=OFF"). I opened the .sln file with VisualStudio and followed the steps I did before. Now it does not compile but gives me the error "Unable to start program  C:\Kratos\build\RelWithDebInfo\kratos\RelWithDebInfo\Kratos.cp37-win_amd64.pyd" "C:\Kratos\build\RelWithDebInfo\kratos\RelWithDebInfo\Kratos.cp37-win_amd64.pyd is not a valid Win32 application"

**Comment by alecontri** [comment]
At the end, I re-installed everything from scratch (Python 3.9, Kratos in Debug mode and even Visual Studio 16 2019) and it now seems to work
