### ISSUE TITLE
[Nightly][FluidMechanicsApplication] Fluid app currently failing in nightly for Windows

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#9012]
**Description**
https://github.com/KratosMultiphysics/Kratos/runs/3177677808?check_suite_focus=true

The FLuid app fails in Nightly in Windoes

**Scope**
- FluidDynamicsApplication

**To Reproduce**
CI nightly for Winodws

**Expected behavior**
Tests to pass.

**Environment**
- OS: Windows
- Branch: master

**Comment by rubenzorrilla** [comment]
Thanks for reporting. Seems to be something with two array sizes. I'll have a look ASAP.

**Comment by rubenzorrilla** [comment]
Fixed in #9031. Closing as FluidDynamicsApplication is not failing anymore.

**Comment by philbucher** [comment]
now they fail again :/

**Comment by rubenzorrilla** [comment]
Most probably it is related to #9027.

**Comment by rubenzorrilla** [comment]
Genau. I was related to #9027 . As it is reverted we can close the issue again (for the moment...).
