### ISSUE TITLE
[Core] Level set process - inconsistency in the use of phi_old

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#9013]
I was adapting my code to use level_set_convection from core and I have found an inconsitency when using the level set uknown from previous time step.

We can see that in the elements it is used as if it was different from the values in the current time step:
https://github.com/KratosMultiphysics/Kratos/blob/37f9ed8e7508c74726f055e37b95ab4009a602bb/kratos/elements/levelset_convection_element_simplex.h#L148

https://github.com/KratosMultiphysics/Kratos/blob/37f9ed8e7508c74726f055e37b95ab4009a602bb/kratos/elements/levelset_convection_element_simplex_algebraic_stabilization.cpp#L117

however in the level set convection process it is overwritten all the time to use the same value for current and previous time step.
https://github.com/KratosMultiphysics/Kratos/blob/37f9ed8e7508c74726f055e37b95ab4009a602bb/kratos/processes/levelset_convection_process.h#L219

Im not so familiar with the formulation, so I'd like to hear what you think it should be used here.

@RiccardoRossi @rubenzorrilla @mrhashemi

**Comment by ddiezrod** [comment]
FYI @jrubiogonzalez @pablobecker

**Comment by mrhashemi** [comment]
The elements are developed considering the possibility of taking into account 0 <=  \theta <= 1.
On the other hand, the process incorporates substepping:
https://github.com/KratosMultiphysics/Kratos/blob/37f9ed8e7508c74726f055e37b95ab4009a602bb/kratos/processes/levelset_convection_process.h#L194
If we omit this line
https://github.com/KratosMultiphysics/Kratos/blob/37f9ed8e7508c74726f055e37b95ab4009a602bb/kratos/processes/levelset_convection_process.h#L219
the convection (with sub-stepping) won't proceed.

**Comment by ddiezrod** [comment]
what I mean is that these two lines will give you the same result:

```
phi[i] = GetGeometry()[i].FastGetSolutionStepValue(rUnknownVar);
phi_old[i] = GetGeometry()[i].FastGetSolutionStepValue(rUnknownVar,1);
```

So, it looks like either phi_old could be removed and always use phi in the element or something is wrong here. Im not sure if this is an issue or not, but it looks strange to me.

**Comment by mrhashemi** [comment]
> what I mean is that these two lines will give you the same result in the element computation:
> 
> ```
> phi[i] = GetGeometry()[i].FastGetSolutionStepValue(rUnknownVar);
> phi_old[i] = GetGeometry()[i].FastGetSolutionStepValue(rUnknownVar,1);
> ```
> 
> So, it looks like either phi_old could be removed and always use phi in the element or something is wrong here. Im not sure if this is an issue or not, but it looks strange to me.

For these elements (without any non-linearity that requires iterations and incremental update of phi), your point (phi[i]==phi_old[i]) seems correct to me.

**Comment by ddiezrod** [comment]
> > what I mean is that these two lines will give you the same result in the element computation:
> > ```
> > phi[i] = GetGeometry()[i].FastGetSolutionStepValue(rUnknownVar);
> > phi_old[i] = GetGeometry()[i].FastGetSolutionStepValue(rUnknownVar,1);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > So, it looks like either phi_old could be removed and always use phi in the element or something is wrong here. Im not sure if this is an issue or not, but it looks strange to me.
> 
> For these elements (without any non-linearity that requires iterations and incremental update of phi), your point (phi[i]==phi_old[i]) seems correct to me.

Ok, then I think I will remove them to avoid confusion.

**Comment by mrhashemi** [comment]
> > > what I mean is that these two lines will give you the same result in the element computation:
> > > ```
> > > phi[i] = GetGeometry()[i].FastGetSolutionStepValue(rUnknownVar);
> > > phi_old[i] = GetGeometry()[i].FastGetSolutionStepValue(rUnknownVar,1);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > So, it looks like either phi_old could be removed and always use phi in the element or something is wrong here. Im not sure if this is an issue or not, but it looks strange to me.
> > 
> > 
> > For these elements (without any non-linearity that requires iterations and incremental update of phi), your point (phi[i]==phi_old[i]) seems correct to me.
> 
> Ok, then I think I will remove them to avoid confusion.

Actually, it is better to have them in the element. Maybe, the best way is to include an extrapolation in the convection process. Let's keep the code as it is for now (since nothing is wrong and everything works fine). I am afraid by removing these lines, it will become hard to trace it back. Hopefully, I can find some time to run some (time-dependent pure convection) tests to choose the best option.

**Comment by ddiezrod** [comment]
Ok @mrhashemi thanks for the clarification
