### ISSUE TITLE
Dem error in windows

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#902]
This is happening in the current master in windows:

C:\KratosSource\applications\DEM_application\custom_utilities/pre_utilities.h(105): error C2664: 'void Kratos::ModelPart::AddElements(std::vector<Kratos::UblasSpace<TDataType,TMatrixType,TVectorType>::IndexType,std::allocator<T>> &,Kratos::ModelPart::IndexType)': cannot convert argument 1 from 'std::vector<unsigned long,std::allocator<_Ty>>' to 'std::vector<Kratos::UblasSpace<TDataType,TMatrixType,TVectorType>::IndexType,std::allocator<T>> &' [C:\KratosSource\cmake_x64\applications\DEM_application\KratosDEMApplication.vcxproj]

**Comment by maceligueta** [comment]
PR #904 should fix this. Can you try it, @roigcarlo ?
