### ISSUE TITLE
Move structural sensitivity analysis into StructuralMechanicsApplication

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#903]
@MFusseder is working on the structural sensitivity analysis for some time now  in the "feature-eigenfrequency-response-function" branch.
Now we are thinking about moving the related code (some utilities, schemes, elements, and python scripts) into the StructuralMechanicsApplication. 

All the response functions developed in this context are dependent on the StructuralMechanicsApplication and from our point of view it does not make sense to have them in a separate Application.

Before doing so, we would like to know if this is ok for you @KratosMultiphysics/structural-mechanics?

There are a few details we still need to consider, e.g. the dependency of the Sensitivity Analysis on the HDF5 I/O...
I think by adding a compiler flag that can swich the Sensitvity Analysis related part on and off, we could avoid a dependency of the StructuralMechanicaApplication on HDF5.

Thanks for your opinion.

**Comment by RiccardoRossi** [comment]
I quite like the idea, (particularly if the dependence on HDF5 can be switched off) however i would ask for merging this after the current release

**Comment by msandre** [comment]
Hi Armin,

For the time being, you could load the adjoint sensitivity application in python to make use of the HDF5 IO. The HDF5 IO will likely be moved to its own application soon at which point you would not need to load the fluid adjoint anymore.

**Comment by armingeiser** [comment]
Thanks for your comments!
@RiccardoRossi we still have some work to do before actually merging into master.
What we are talking about now will definitely stay in our branch for the next 1-2 months.

**Comment by RiccardoRossi** [comment]
an agreement has been met. closing
