### ISSUE TITLE
How to given initial strain/stress element by element?

### ISSUE THREAD

**Issue by XinLiu100** [KratosMultiphysics/Kratos#9049]
Hi I am new to Kratos and I am trying to use StructuralMechanicsApplication to do elastoplastic simulation. 

I know how to set initial strain by process defined in parameter json file, but my problem is that, I need to give the initial strain field to every element, but I did not find how to do it.

Thank you in advance!

**Comment by rubenzorrilla** [comment]
I think that the @KratosMultiphysics/structural-mechanics and @KratosMultiphysics/constitutive-models would provide a quick answer to this.

**Comment by AlejandroCornejo** [comment]
Hi! You mean @XinLiu100 that you want to apply different initial strain to each element separately?

If so, you can use the same `json `process **AND** adding to the `mdpa ` file the following block detailing the initial strain for each FE:

Begin ElementalData INITIAL_STRAIN_VECTOR
1 [6] (0.01,0.01,0.01,0,0,0)
2 [6] (0.01,0.01,0.01,0,0,0)
3 [6] (0.05,0.01,0.01,0,0,0)
4 [6] (0.06,0.01,0.01,0,0,0)
...
End ElementalData

**Comment by XinLiu100** [comment]
> Hi! You mean @XinLiu100 that you want to apply different initial strain to each element separately?
> 
> If so, you can use the same `json `process **AND** adding to the `mdpa ` file the following block detailing the initial strain for each FE:
> 
> Begin ElementalData INITIAL_STRAIN_VECTOR
> 1 [6] (0.01,0.01,0.01,0,0,0)
> 2 [6] (0.01,0.01,0.01,0,0,0)
> 3 [6] (0.05,0.01,0.01,0,0,0)
> 4 [6] (0.06,0.01,0.01,0,0,0)
> ...
> End ElementalData

Thank you! 
Yes, but can I have this INITIAL_STRAIN_VECTOR assigned in code? In fact, I have multiple steps of simulation, and in each step the initial strain determined by previous step. I wonder is it possible to update it like this `simulation.my_model_part.GetElements()[1].SetValue(KratosMultiphysics.INITIAL_STRAIN_VECTOR,[0.1,0.1,0.1,0,0,0])` ?

**Comment by AlejandroCornejo** [comment]
The `initial_state  `object is located inside the `constitutive_law`. You can set the `INITIAL_STRAIN_VECTOR` with the SetValue but, in order to be storaged you always need to call the `SetInitialStateProcess`, which is the one that creates an initial_state object and sets it inside the CL.
Reading your message, you could at each time step reset the INITIAL_STRAIN_VECTOR with a SetValue and then the set_initial_process would override the information inside the CL

**Comment by XinLiu100** [comment]
> The `initial_state `object is located inside the `constitutive_law`. You can set the `INITIAL_STRAIN_VECTOR` with the SetValue but, in order to be storaged you always need to call the `SetInitialStateProcess`, which is the one that creates an initial_state object and sets it inside the CL.
> Reading your message, you could at each time step reset the INITIAL_STRAIN_VECTOR with a SetValue and then the set_initial_process would override the information inside the CL

Thank you! Very helpful information!
