### ISSUE TITLE
EXEC : CMake error : failed to create symbolic link 'WIN32-VC': operation not permitted

### ISSUE THREAD

**Issue by SakinahBuang** [KratosMultiphysics/Kratos#9054]
Hi, anyone can help me with this error?
EXEC : CMake error : failed to create symbolic link 'WIN32-VC': operation not permitted
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: The command "setlocal
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: "C:\Program Files\CMake\bin\cmake.exe" -DBUILD_TYPE=Release -P cmake_install.cmake
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: if %errorlevel% neq 0 goto :cmEnd
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :cmEnd
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :cmErrorLevel
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: exit /b %1
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :cmDone
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: if %errorlevel% neq 0 goto :VCEnd
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(149,5): error MSB3073: :VCEnd" exited with code -1.
1>Done building project "INSTALL.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 35 up-to-date, 0 skipped ==========

**Comment by Vahid-Galavi** [comment]
Perhaps you need to run it as administrator.

**Comment by roigcarlo** [comment]
As @Vahid-Galavi says, that option requires to run as an administrator in windows.
Or you can turn `set KRATOS_INSTALL_PYTHON_USING_LINKS=OFF` and compile normally.

**Comment by SakinahBuang** [comment]
> As @Vahid-Galavi says, that option requires to run as an administrator in windows.
> Or you can turn `set KRATOS_INSTALL_PYTHON_USING_LINKS=OFF` and compile normally.

Thank youuu! Now that everything clear, new error come in :D

![image](https://user-images.githubusercontent.com/89022991/129733789-94cf1196-142a-4075-b954-2e65535fbda6.png)
**

**Comment by roigcarlo** [comment]
Hi @SakinahBuang that seems to be an issue with the Geant4 project, sadly I cannot help you here as am not aware of the details of that project. 
Maybe you can find some help in their forums: https://geant4-forum.web.cern.ch/
