### ISSUE TITLE
[FluidDynamicsApplication] Quadrilateral and Hexahedra incompatibility

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/Kratos#9056]
**Description**
I have created a 3D model using hexahedra to mesh the fluid but, at the moment to calculate it, I got errors. It seems like the FluidDynamicsApplication is not ready to use hexahedra since it always checks the tetrahedra orientation in `check_and_prepare_model_process_fluid.py`. The function that checks the orientation crashes if we use another type of element.

Similar issue it is found when I use quadrilateral instead of triangles as conditions. The `navier_stokes_solver_vmsmonolithic.py` has a line where `self.condition_name = "MonolithicWallCondition"` is written hard coded. Kratos does not recognize any element called `MonolithicWallCondition3D4N` so the application crashes as well.

**Scope**
- FluidDynamicsApplication

**Environment**
- OS: Ubuntu 18.04
- Branch: master
- Python 3.7

**Comment by rubenzorrilla** [comment]
About the tetrahedral mesh orientation check, you're right. We need to figure out a robust solution. The problem is that the tetrahedral mesh orientation check is now in charge of assigning the neighbors, so is not as easy as removing the call for quads/hexas.

Concerning the condition, you're using the old VMS element. This element only supports tetras and triangles, meaning that there is quad wall condition. You need to switch to the new VMS elements (`qs_vms` and `d_vms`).

**Comment by jgonzalezusua** [comment]
Concerning the conditions, I see what is the problem. I am using a derived class of the new elements and I have a derived solver of the `navier_stokes_solver_vmsmonolithic.py`. I have already included the `self.condition_name variable` so it is fixed.

The remaining issue is the hexahedra incompatibility. I have seen that you are working on it.

**Comment by rubenzorrilla** [comment]
> Concerning the conditions, I see what is the problem. I am using derived classes of the new elements and I have a derived solver of the `navier_stokes_solver_vmsmonolithic.py`. I have already included the `self.condition_name` variable in it so the problem is fixed.
> 
> The remaining issue is the hexahedra incompatibility. I have seen that you are working on it.

If you don't need the neighbors nor the condition normals you can temporarily deactivate it in your local branch. If I'm not wrong it will do the job.

**Comment by jgonzalezusua** [comment]
Ok, thanks.
