### ISSUE TITLE
Python packages

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#9064]
**Description**
For a long time there has been a request for other packages (numpy, matplotlib, among others...) to be able to run alongside with Kratos (see #2165). Now this is possible and the focus of the discussion has to change to decide which packages go where, so I am closing the old discussion and open a new one.

This dependencies for the release will be handled automatically in app/core json's with the changes in #9060.

For example see [this](https://github.com/KratosMultiphysics/Kratos/pull/9060/files#diff-adc2e64e896b153fe9ea361c72ad9eb21d750946fbf0a0cfaee9cae4cc3796a4R6) which has `KratosMultiphysics` as a dependency. Ie: The kratos app package needs the kratos core package.

Note that dependencies can be handled per app, and hence do not need to be global. If someone is compiling locally, he need to ensure those packages are present or the script will not.

Now, the following remains:
- [x] Is the core going to have packages? if so which (numpy, matplotlib?)
- [x] Add those dependencies
- [x] Each App owner should add the list of packages in their corresponding app
- [x] Each App / Core should have the compile instructions updated to indicate the needed python packages.

My idea is having this ready by 9.0.0, so we should agree before October if possible.

**Comment by roigcarlo** [comment]
@KratosMultiphysics/all

**Comment by philbucher** [comment]
> Each App / Core should have the compile instructions updated to indicate the needed python packages.

doesn't python have a standard solution for this?
I think it is called `requrements.txt`

**Comment by roigcarlo** [comment]
> I think it is called requirements.txt

Whatever way you want to do it works for me, I just want to clarify that its something the a developer that wants to compile and run and app will have to do. Again for the release I already take care of this.

**Comment by roigcarlo** [comment]
Since #9230 wheels support. This means that from the release point of view this issue can be closed. I will let this open in case we want to discuss what to do with the packages in the CI, etc...

**Comment by roigcarlo** [comment]
I am moving this issue from the milestone of the release.

While the packages work, most of the TODO in the OP are still relevant, so not closing yet but it makes no sense to be here.

**Comment by AlejandroCornejo** [comment]
I would like to add that, if using Pardiso (at least in Windows), python version above 3.7 does not work. @ddiezrod manage to do it with 3.8 but with some copy-pasting of libraries... I know this is not totally related but It came to my mind.

**Comment by philbucher** [comment]
> I would like to add that, if using Pardiso (at least in Windows), python version above 3.7 does not work. @ddiezrod manage to do it with 3.8 but with some copy-pasting of libraries... I know this is not totally related but It came to my mind.

@oberbichler do you have some thoughts?

**Comment by oberbichler** [comment]
Without conda I have never managed to create a practical working package that includes MKL.

**Comment by ddiezrod** [comment]
> Without conda I have never managed to create a practical working package that includes MKL.

Maybe we should discuss in a different place. I managed to use pardiso with python 3.8 in Windows. Using dependecy walker I saw that LinearSolversApplication seemed to depend on mkl_rt.1.dll. Its strange because this file was already in the PATH. I copied it inside bin folder. Then, in runtime it complained it was missing mkl_intel_thread.1.dll, so I added this one also to the bin folder. After that, it is running smoothly

**Comment by oberbichler** [comment]
👍 
If you have a local installation it should work. I was just thinking about an automatic installation with `pip`. There is a `MKL` package on `pypi` but I never managed to link it properly... would be nice to see if it works.

**Comment by roigcarlo** [comment]
Just to add my two cents.

The way we pack libraries for the wheels will make external libraries which are also present in the pip package invisible. Example:
LinearSolversApplicationd.dll -> mkl_rt.1.dll

If the whl provides mkl support, it will NOT SEE your mkl_rt.1.dll, only the one we add in the whl.
If we do not support it will see a possible lib in your system but won't be able to use it.
Both of this include possible mkl libraries installed through other packages. In general we do not build to be shared-lib compatible with anyone.

This is mostly to prevent clashes with already existing libraries, it is shared across all Kratos wheels and its something done automatically in the packaging process so I am not sure if it can be changed. (It does not mean that you can't use other libraries outside Kratos making use of the same dependencies, just that Kratos will use their own)

If we need mkl in the whl releases (we can enable it as we use gcc for the compilation), please create another issue and we can discuss if its possible to include it in the release (possible = no license issues)

**Comment by roigcarlo** [comment]
We have already packages in place and we are working on releasing with MKL through conda as well. Closing.
