### ISSUE TITLE
Default values for assign_vector_variable_process should be [0.0, 0.0, 0.0]

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#9065]
**Description**
The default value of the `assign_vector_variable_process` should be `[0.0, 0.0, 0.0]` and not a random `[10.0, "3*t", "x+y"]`.
Such an example on how variable values should be given in the docstring in my opinion. 

Or even better: the values field should be mandatory, not sure how this can be done however.  

Happy to hear others opinions.

**Comment by rubenzorrilla** [comment]
Agree. I think we should explicitly ask the user for those values.

**Comment by EduardGomezEscandell** [comment]
Solved! #9415
