### ISSUE TITLE
LOCAL_AXIS management and rotations

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#9067]
**Description**
Dear all,

In order to perform anisotropic calculations efficiently, it is required to orient the elements so they have access to a set of predefined `LOCAL_AXIS`. I can see how this can be done (checking inside the element if `elem->Has(LOCAL_AXIS)`) and then perform the rotation of the strains and posterior stresses (How in finite strains??). This can be done at constitutive level via the `Geometry`...

My idea is to use `Quaternions `in order to storage this info but I have one question. The rotation matrix is exactly the three LOCAL_AXIS vectors in columns right?

Another question is how to rotate the deformation gradient tensor **F**. I think that if A is a rotation matrix from global to local coordinates, the local F (**F**'=**A** **F** inv(**A**))

Working in this  branch: `adding-local-axis-in-elements`

**Comment by philbucher** [comment]
There is also a small wiki: https://github.com/KratosMultiphysics/Kratos/wiki/Local-axes-orientation

@KlausBSautter you have a lot of experience with this, can you comment please?
(and @MFusseder I think you also needed/used this maybe you have sth to add too)

**Comment by AlejandroCornejo** [comment]
> 
> 
> There is also a small wiki: https://github.com/KratosMultiphysics/Kratos/wiki/Local-axes-orientation
> 
> @KlausBSautter you have a lot of experience with this, can you comment please?
> (and @MFusseder I think you also needed/used this maybe you have sth to add too)

Yes! I've checked the wiki. Shortly I'll refer this issue to an actual PR where we can discuss the implementation
