### ISSUE TITLE
[CoSim] Convergence acceleration data transfer

### ISSUE THREAD

**Issue by ceulogiof** [KratosMultiphysics/Kratos#9074]
**Description & Scope**  
While coupling an FSI problem (by using the PfemFluidDynamicsApplication and the StructuralMechanicsApplication) in the CoSimulation Application, I want to perform convergence acceleration on a field (say, displacement or velocity) of the FEM, and then transfer the relaxed values to the PFEM, instead of accelerating the fields separately (the fluid solver should always receive the displacements and velocities from the structural solver). Is this feature already implemented in the CoSimulation? 

I could only find that the acceleration is performed individually on each field of the `interface_data` that was defined for the convergence acceleration. I am referring to the file: https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/convergence_accelerators/convergence_accelerator_wrapper.py

**Environment**
-   OS: Ubuntu 18.04
-   Branch: StructMech/couple_pfem
-   Python 3.6.9

**Comment by ceulogiof** [comment]
> You mean in the next strong coupling iteration step ?

Yes, exactly that. Sorry for not being precise enough. 

> In this case, for what you want to do, the following configuration will work.

I tried your suggested configuration and it worked! My mistake was in thinking that the acceleration had to be specified in the same solver specified in `output_data_list`:
```
{
                "type"      : "aitken",
                "solver"    : "structure",
                "data_name" : "vel"
}
```
Now I realize this tells the CoSimulation to perform the acceleration and then map again to the same field, which is not correct for the simulation I try to run.

I only have a question left: where does the relaxed values exchange from one solver to another take place? I was looking into `co_simulation_convergence_accelerator.py` and `coupling_interface_data.py`, but I am not sure exactly where...

I will greatly appreciate your hint.

**Comment by adityaghantasala** [comment]
> I only have a question left: where does the relaxed values exchange from one solver to another take place? I was looking into co_simulation_convergence_accelerator.py and coupling_interface_data.py, but I am not sure exactly where...

I am glad the configuration worked. Here is where the exchange happens. 

https://github.com/KratosMultiphysics/Kratos/blob/ca5bd29038d56507cc43841d414a50bdae89d6c1/applications/CoSimulationApplication/python_scripts/coupled_solvers/gauss_seidel_strong.py#L83

**Comment by ceulogiof** [comment]
Thank you Aditya! I will close this issue now.
