### ISSUE TITLE
Time limit when running small tests

### ISSUE THREAD

**Issue by salvalatorre** [KratosMultiphysics/Kratos#9087]
Hello all,

In a pull request I just open I got the following message when trying to get the CI for Windows:

Running DEMApplication tests
..........................D:\a\Kratos\Kratos\bin\Custom\applications//DEMApplication/tests/test_DEMApplication.py
Error: : Tests for DEMApplication took too long. Process Killed.
Completed DEMApplication tests with exit code 1!

I don't know why is that the case because in my computer the tests take around 12 seconds and I see that many apps go beyond that limit and have no problems.

Any help? Thanks

**Comment by philbucher** [comment]
In my experience the machines that run the CI are 10-100 times slower than personal computers. 
Windows unfortunately tends to be on the slow side as we cannot use compiler optimization because it blows up the compilation time :/

**Comment by salvalatorre** [comment]
Thanks! I already suspected something in that direction... Anyway, is there any specific time limit value so I know how much I should scale that time down?
Thx!
