### ISSUE TITLE
[CoSim] Coupling operation for printing iteration numbers

### ISSUE THREAD

**Issue by ceulogiof** [KratosMultiphysics/Kratos#9088]
**Description**
For my simulations, I need to print to a file the iteration number in the iterative coupled solvers. I saw that there is already a dummy implementation in [CoSimApp/coupling_operations/print_iteration_number.py](https://github.com/KratosMultiphysics/Kratos/blob/master/applications/CoSimulationApplication/python_scripts/coupling_operations/print_iteration_number.py). I am completing it but I wanted to discuss several ideas of how to pass the iteration number `k` onto the object.
- Should this be exported as a Kratos variable (as in `KM.TIME`)?
- Maybe through the IO?
- Or is there another way to do it?

**Scope**
-CoSimulationApplication

**Comment by adityaghantasala** [comment]
@philbucher  I remember you mentioning  an implementation of this ?

**Comment by philbucher** [comment]
I intended to increase the counter each time `InitializeNonLinearIteration` is called

**Comment by ceulogiof** [comment]
Thanks for the hint, @philbucher ! This ended up working:

https://github.com/KratosMultiphysics/Kratos/blob/1dee579515f269344224229f0fbb30ad40f19d08/applications/CoSimulationApplication/python_scripts/coupling_operations/print_iteration_number.py#L50-L60

I preferred increasing the counter in `FinalizeCouplingIteration` instead of in `InitializeCouplingIteration`, to also store the 0th iteration to also print it to the file, in case there were any coupling that converged right away.

This test is in the branch StructMech/couple__test_reset_pfem here: [coupling_operations/print_iteration_number.py](https://github.com/KratosMultiphysics/Kratos/blob/StructMech/couple_pfem_test_reset_pfem/applications/CoSimulationApplication/python_scripts/coupling_operations/print_iteration_number.py)

**Comment by ceulogiof** [comment]
I will close the issue because you answered my question.
