### ISSUE TITLE
[Poromechanics] Build errors

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#9109]
**Description**
PR #7898 probably caused this.

Files:
- applications/PoromechanicsApplication/custom_strategies/strategies/poromechanics_explicit_strategy.hpp
- applications/PoromechanicsApplication/custom_strategies/strategies/poromechanics_explicit_nonlocal_strategy.hpp

`typedef SolvingStrategy<TSparseSpace, TDenseSpace, TLinearSolver> BaseType;`
should be
`typedef SolvingStrategy<TSparseSpace, TDenseSpace> BaseType;`

In adition, several errors are thrown

**Scope**
- Compilation

**To Reproduce**
Build Poromechanics @KratosMultiphysics/poromechanics 

**Terminal Output**
[aaa.txt](https://github.com/KratosMultiphysics/Kratos/files/7128361/aaa.txt)

**Comment by rubenzorrilla** [comment]
Seems to be caused by #7898.

**Comment by rubenzorrilla** [comment]
> **Description**
> PR #7898 probably caused this.
> 
> Files:
> 
>     * applications/PoromechanicsApplication/custom_strategies/strategies/poromechanics_explicit_strategy.hpp
> 
>     * applications/PoromechanicsApplication/custom_strategies/strategies/poromechanics_explicit_nonlocal_strategy.hpp
> 
> 
> `typedef SolvingStrategy<TSparseSpace, TDenseSpace, TLinearSolver> BaseType;`
> should be
> `typedef SolvingStrategy<TSparseSpace, TDenseSpace> BaseType;`
> 
> In adition, several errors are thrown
> 
> **Scope**
> 
>     * Compilation
> 
> 
> **To Reproduce**
> Build Poromechanics @KratosMultiphysics/poromechanics
> 
> **Terminal Output**
> [aaa.txt](https://github.com/KratosMultiphysics/Kratos/files/7128361/aaa.txt)

Indeed, I think it should be
`typedef ExplicitSolvingStrategy<TSparseSpace, TDenseSpace> BaseType;`

**Comment by ipouplana** [comment]
Thank you @jginternational and @rubenzorrilla , I'll try to fix this in the next days (ASAP).

**Comment by rubenzorrilla** [comment]
> Thank you @jginternational and @rubenzorrilla , I'll try to fix this in the next days (ASAP).

It shouldn't be difficult. Just ping me if you need any hint :wink:
