### ISSUE TITLE
AssignAndValidateDefaults creates an error when the default value is null whereas the parameter is double

### ISSUE THREAD

**Issue by lluis-mv** [KratosMultiphysics/Kratos#911]
Hi,

I have defined the default value of a JSON as null, whereas in some cases this value is a double. However, I get an error in the AssignAndValidateDefaults.
However, if instead of defining this variable as a null it is defined as an array with one component that is null and the other with one array with a double everything goes fine.
I am unsure if I have explained myself correctly, but see the attached python code. The first time it calls the AssignAndValidateDefaults works correctly whereas the second one fails since they have different types.

```
import KratosMultiphysics

default_settings = KratosMultiphysics.Parameters(""" {"component": [null] } """)
custom_settings = KratosMultiphysics.Parameters("""  {"component": [1.0]  } """)

custom_settings.ValidateAndAssignDefaults(default_settings)

if not custom_settings["component"][0].IsNull():
    assign_the_value_to_some_variable = custom_settings["component"][0].GetDouble()
    print( assign_the_value_to_some_variable)


default_settings_2 = KratosMultiphysics.Parameters("""  {"component": null }  """)
custom_settings_2 = KratosMultiphysics.Parameters("""   {"component": 1.0 }  """)

custom_settings_2.ValidateAndAssignDefaults(default_settings_2)

```

I do not know if that's the expected behavior or if I should do this differently,

KR
Lluís

**Comment by RiccardoRossi** [comment]
Hi,
i am not sure if i understand you.
i'll tell you my expectations:

     default_settings = KratosMultiphysics.Parameters(""" {"component": [null] } """)
     custom_settings = KratosMultiphysics.Parameters("""  {"component": [1.0]  } """)
     custom_settings.ValidateAndAssignDefaults(default_settings)

validates OK (single entries are not checked). That is, it checks that the type passed is the same, and the type passed is in both cases an array

on the contrary

       default_settings_2 = KratosMultiphysics.Parameters("""  {"component": null }  """)
       custom_settings_2 = KratosMultiphysics.Parameters("""   {"component": 1.0 }  """)
       custom_settings_2.ValidateAndAssignDefaults(default_settings_2)

i expect this to FAIL since 1.0 is a double and not a null

does this respond you?

**Comment by josep-m-carbonell** [comment]
Hi @RiccardoRossi, thank you for your response. As @lluis-mv exposed, null is not a type, the meaning is that that value (scalar variable)  is not defined. If a scalar variable must not be defined by default one can set it as null. However then it is impossible to set it to a double, or to any other type because the type comparisson is not  possible and can not be checked. It does not allow null to be used as not assigned value.

**Comment by RiccardoRossi** [comment]
@josep-m-carbonell, @lluis-mv this is not how the **current** implementation works. Indeed right now null is a type, as int, double, bool, string, array

which means that _as of today_  if you do 

      default_settings_2 = KratosMultiphysics.Parameters("""  {"component": null }  """)
      custom_settings_2 = KratosMultiphysics.Parameters("""   {"component": 1.0 }  """)
      print("-- default_settings_2[\"component\"].IsNull() --> ", \
                 default_settings_2["component"].IsNull())
      print("-- default_settings_2[\"component\"].IsDouble() --> ",  \ 
                 default_settings_2["component"].IsDouble())

you get the output 

      -- default_settings_2["component"].IsNull() -->  True
      -- default_settings_2["component"].IsDouble() -->  False

Having said this, the introduction of Null is relatively new, and i think it is not yet used a lot. This means that we have some flexibility in discussing other options for its use in validation. 
In particular there is a open discussion (#653) about the topic of defining tokens to make more general the validation process.  I would suggest that we merge this discussion with #653

**Comment by pooyan-dadvand** [comment]
I also suggest to close this one and move the discussion to the #653

**Comment by pooyan-dadvand** [comment]
Meanwhile I like more the keyword default than using null....
