### ISSUE TITLE
Change README banner logo image to work for dark mode

### ISSUE THREAD

**Issue by Kevin-Mattheus-Moerman** [KratosMultiphysics/Kratos#9112]
**Description**
When using GitHub's dark mode, the banner logo on the README page is not very visible: 

![Screenshot from 2021-09-08 14-54-30](https://user-images.githubusercontent.com/8392709/132540447-c60eea7b-f62b-4475-a541-22b8559985ad.png)

I recommend using a "sticker" type white rim e.g. like this, so it works for both white or black backgrounds: 
![kratos](https://user-images.githubusercontent.com/8392709/132540621-3dc0b956-5d38-4cd4-906b-57810e485b6f.png)

**Comment by loumalouomega** [comment]
Should be OK Now

**Comment by loumalouomega** [comment]
(I reuploaded your version)

**Comment by philbucher** [comment]
@loumalouomega in regular mode it looks quite ugly now :)

**Comment by loumalouomega** [comment]
Screenshot?

**Comment by philbucher** [comment]
ah no now it looks fine also in regular mode, probably some of my settings were messed up, sorry for the noise

closing as is solved, thx @Kevin-Mattheus-Moerman !

**Comment by Kevin-Mattheus-Moerman** [comment]
Great. Looks great now. FYI, the same issue exists for other images e.g. the one in this readme: https://github.com/KratosMultiphysics/Documentation
