### ISSUE TITLE
How to Print EIGENVECTOR_MATRIX for vtk/gid?

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#9119]
**Description**
Dear @philbucher (I think that you are the one working specifically on this :) )

I'm trying to run some simulation of EigenValues and I'm interested in printing for GiD (can be vtk) the nodal eigenvectors. How can I do it? I've tried with the `postprocess_eigenvalues_process` but does not allow the variable `EIGENVECTOR_MATRIX`

Thank you very much,

Alejandro

**Comment by AlejandroCornejo** [comment]
I got it! sorry for the noise @philbucher :D

**Comment by philbucher** [comment]
hey,
so the `postprocess_eigenvalues_process` only does the animation of the mode shapes, it doesn't do anything with the `EIGENVECTOR_MATRIX`
I think you can print it too, as it should be a regular `Matrix` format result

how did you manage in the end?

**Comment by AlejandroCornejo** [comment]
It seems that If I want to print the `EIGENVECTOR_MATRIX` is undefined for `nodal_nonhistorical_results`.

**Comment by philbucher** [comment]
hm then it seems like `Matrix` type variables are not supported (in neither gid nor paraview) IIRC

I think @adityaghantasala and I didn't add it as it was not clear which type it was in the vtk format. I.e. it was not clear how the results would be interpreted (e.g. as tensor or sth else which might include interpolation or not)

GiD I think has the same struggle, usually e.g. Stresses are plotted with some interpolation to show e.g. Sxx, Syy, Szz

What exactly do you want to visualize?

maybe @jginternational can also comment?

**Comment by jginternational** [comment]
@pasenau Maybe this is your field

**Comment by AlejandroCornejo** [comment]
I closed it because, as far as I understood from the code, in the 'post_process_eigenvaluse' inside the DoF you are setting the eigenvectors so for me it's enough

**Comment by philbucher** [comment]
> I closed it because, as far as I understood from the code, in the 'post_process_eigenvaluse' inside the DoF you are setting the eigenvectors so for me it's enough

you are right, I used the `EIGENVECTOR_MATRIX` for the animation. Forgot what I wrote some years ago ... (anyway was not my initial idea)

So you want to visualize the modeshapes?

**Comment by AlejandroCornejo** [comment]
It is just a minimal calculation that some people outside Kratos have asked me.. Obtaning the frequencies and the eigenvectors per node should be fine. The animation is fancy though. So I have everything I need I think! thx !

**Comment by philbucher** [comment]
this example might also be interesting for you: https://github.com/KratosMultiphysics/Examples/blob/master/structural_mechanics/validation/beam_eigenvalue_analysis/source/MainKratos.py
