### ISSUE TITLE
How to obtain stress/strain during solving structural problem?

### ISSUE THREAD

**Issue by tempsmith** [KratosMultiphysics/Kratos#9131]
Maybe this is a really naïve question, but how do we get stress or strain between solving steps? I need the stress and strain in intermediate steps. 

I know how to get displacement during solving by `GetSolutionStepValue` and I could interpolate the displacements to get strain, but I guess there is API to obtain strain? 

For stress, I saw the document talking about using constitutive laws, but I don't know how to obtain the constitutive law during solving steps? I tried like this way but it does not work `elem.Calculate(KratosMultiphysics.STRESSES,model.ProcessInfo)`

I am using StructuralMechanicsApplication and ConstitutiveLawsApplication

Any help is appreciated! Thank you!

**Comment by AlejandroCornejo** [comment]
Hi! to retrieve the `CAUCHY_STRESS_VECTOR `or the `GREEN_LAGRANGE_STRAIN_VECTOR `for example you should use:

~~~c++
    void CalculateOnIntegrationPoints(
        const Variable<Vector>& rVariable,
        std::vector<Vector>& rOutput,
        const ProcessInfo& rCurrentProcessInfo
        ) override;
~~~

as elem.CalculateOnIntegrationPoints(----)

**Comment by tempsmith** [comment]
> Hi! to retrieve the `CAUCHY_STRESS_VECTOR `or the `GREEN_LAGRANGE_STRAIN_VECTOR `for example you should use:
> 
> ```c++
>     void CalculateOnIntegrationPoints(
>         const Variable<Vector>& rVariable,
>         std::vector<Vector>& rOutput,
>         const ProcessInfo& rCurrentProcessInfo
>         ) override;
> ```
> 
> as elem.CalculateOnIntegrationPoints(----)

Thank you! I tried this and it works!

**Comment by AlejandroCornejo** [comment]
then we should close the issue :)
Regards
