### ISSUE TITLE
Types of beam models available in Kratos

### ISSUE THREAD

**Issue by BenjaPH** [KratosMultiphysics/Kratos#9135]
**Description**

I am starting to use Kratos with a simple beam model.
The examples I have seen on the Wiki use the element type "CrLinearBeamElement3D2N". But I don't really know which hypotheses are assumed in this formulation.

I would like to know if there is any documentation/explanation about the formulation of each kind of element available in Kratos.

In particular for this beam element, i would like to know if the assumed beam section deformation field is according to the Bernoulli-Euler, Timoshenko–Ehrenfest beam theory or higher order ones. And if it is possible, which parameter allows switching between them.

Thanks in advance,
Benjamín

**Scope**
Which areas of Kratos are involved
- Structural Mechanics Application
- Documentation

**Comment by loumalouomega** [comment]
@KratosMultiphysics/structural-mechanics

**Comment by KlausBSautter** [comment]
hi @BenjaPH it is a Bernoulli beam and there are two variables `AREA_EFFECTIVE_Y` & `AREA_EFFECTIVE_Z` which should allow considering the work done by shear deformation so a transition to Timoshenko. This feature has not been extensively tested!

**Comment by BenjaPH** [comment]
Thanks a lot Klaus.

**Comment by loumalouomega** [comment]
> hi @BenjaPH it is a Bernoulli beam and there are two variables `AREA_EFFECTIVE_Y` & `AREA_EFFECTIVE_Z` which should allow considering the work done by shear deformation so a transition to Timoshenko. This feature has not been extensively tested!

By curiosity, which is the main reference? (Maybe we should add references to the files)

**Comment by BenjaPH** [comment]
> > hi @BenjaPH it is a Bernoulli beam and there are two variables `AREA_EFFECTIVE_Y` & `AREA_EFFECTIVE_Z` which should allow considering the work done by shear deformation so a transition to Timoshenko. This feature has not been extensively tested!
> 
> By curiosity, which is the main reference? (Maybe we should add references to the files)

@KlausBSautter   What Vicente has proposed would be a great idea.
