### ISSUE TITLE
How to export displacement if my (X0, Y0, Z0) is changed

### ISSUE THREAD

**Issue by tempsmith** [KratosMultiphysics/Kratos#9137]
Hi I am using the StructuralMechanicsApplication. 
In my problem I need to update the mesh each step, so I changed (X0, Y0, Z0) each step.
However, I still want to export my displacement as (X - the original X0, Y - the original Y0, Z - the original Z0), so I stored the original (X0, Y0, Z0) and set the displacement in `OutputSolutionStep` with `SetSolutionStepValue` (before `super().OutputSolutionStep()`), but it seemed this is not correct. I am not sure if I did anything wrong? 

Any help is appreciated! Thank you!

**Comment by rubenzorrilla** [comment]
Closing as it seems to be inactive.
