### ISSUE TITLE
Release 5.2: StructuralMechanicsApplication. Tests failing in FullDebug

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#915]
The following tests are failing in FullDebug:
- TTestPatchTestShells
- TShellT3ThickLinearStaticTests
- TShellT3ThickNonLinearStaticTests
- TShellT3ThickLinearDynamicTests
- TShellT3ThickNonLinearDynamicTests
- TShellQ4ThinLinearStaticTests
- TShellQ4ThinNonLinearStaticTests
- TShellQ4ThinLinearDynamicTests
- TShellQ4ThinNonLinearDynamicTests
~~~c
.python3: /home/vicente/bin/boost_1_59_0/boost/smart_ptr/shared_ptr.hpp:687: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = Kratos::ShellCrossSection; typename boost::detail::sp_member_access<T>::type = Kratos::ShellCrossSection*]: Assertion `px != 0' failed.
python3: /home/vicente/bin/boost_1_59_0/boost/smart_ptr/shared_ptr.hpp:687: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = Kratos::ShellCrossSection; typename boost::detail::sp_member_access<T>::type = Kratos::ShellCrossSection*]: Assertion `px != 0' failed.
Abortado (`core' generado)
~~~
- TestLoadingConditions
~~~c
Traceback (most recent call last):
  File "/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/tests/test_loading_conditions.py", line 283, in test_execution
    self._test_LineLoadCondition3D2NRotDof()
  File "/home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/tests/test_loading_conditions.py", line 52, in _test_LineLoadCondition3D2NRotDof
    cond.CalculateLocalSystem(lhs,rhs,mp.ProcessInfo)
RuntimeError: Error: bad index
in /home/vicente/bin/Kratos/applications/StructuralMechanicsApplication/custom_conditions/line_load_condition.cpp:217:virtual void LineLoadCondition::CalculateAll(Condition::MatrixType&, Condition::VectorType&, ProcessInfo&, bool, bool)
~~~

**Comment by RiccardoRossi** [comment]
To reproduce, compile with FullDebug and art the compilation flag -D_GLIBCXX_DEBUG

**Comment by philbucher** [comment]
This should be fixed in the PR abt composites and stress recovery

**Comment by loumalouomega** [comment]
The shells can be modified in the PR, the others is better to modify in a PR ad hoc

**Comment by loumalouomega** [comment]
Additionally the MPC tests fails ramdonly

**Comment by philbucher** [comment]
The shell tests are working in my branch, I am working on the loading conditions
MPC is @adityaghantasala

**Comment by philbucher** [comment]
I tracked the issue with the loading conditions down, it is this line: https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/geometries/geometry.h#L724

**Comment by philbucher** [comment]
If you look into the function that calculates the Jacobian (https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/geometries/line_3d_2.h#L478), you can see right away where the bad index comes from.
The matrix has size 3,1 and the second row (which is not existing) is accessed in the Normal calculation
afaik @loumalouomega you implemented the normals right?

**Comment by philbucher** [comment]
btw shouldn't you check if the norm is 0 before the devision here https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/geometries/geometry.h#L730 ?

**Comment by loumalouomega** [comment]
Yes, definitively. Yes, I implemented the normal

**Comment by loumalouomega** [comment]
We need to think about this, because in the case of a line on 3D the normal should be derived, and necessarily the local axis should take place, which is a problem because a geometry of points will not have any database

**Comment by loumalouomega** [comment]
We can discuss the approach here

**Comment by loumalouomega** [comment]
I was thinking that maybe the best idea in this case is to use the tangent as output for the normal (the person using it should know, that is the biggest problem), otherwise you will have an infinite number of normals

**Comment by philbucher** [comment]
I discussed the issue abt the loading condition test failure with @KlausBSautter and @AndreasWinterstein .
We came to the conclusion that the LineLoadCondition needs major improvements/enhancements to suit our needs.
This will take a bit of time, so we can only do it after the release.
These improvements will also solve the issue with the normals
I hope this is ok for you @loumalouomega and @RiccardoRossi

**Comment by RiccardoRossi** [comment]
well, we need at least to solver the memory problem or to take it out of the release...

**Comment by RiccardoRossi** [comment]
one option would be to go back to the previous behaviour, before the changes of @KlausBSautter

**Comment by KlausBSautter** [comment]
Alright ->  #919

**Comment by pooyan-dadvand** [comment]
And for the normal I suggest to scale the mormal if norm is not zero:

```c++
if(norm > std::numeric_limits<double>::epsilon())
	normal /= norm;
```

**Comment by RiccardoRossi** [comment]
regarding the scaling of the normal i would then name the method as "UnitNormal" as the variable NORMAL is normally employed to identify the Area-proportional normal.

**Comment by RiccardoRossi** [comment]
of course changing the name of the method (if we decide to do so) should not be done for the Release

**Comment by RiccardoRossi** [comment]
@KlausBSautter  @philbucher  I took a look to the problem with the Normal.

thing is that the geometry cannot use variables (it is at a lower level) 

The solution i propose is to define a way to calculate the normal taking into account the LOCAL_AXES_2 within the condition itself. 
btw, to be honest i don't love the way of detecting it it has rotations or not...i think it is a quite weak mechanism (but we can definitely discuss this at a later stage)

**Comment by loumalouomega** [comment]
Solved
