### ISSUE TITLE
License of external library: "triangle"

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#9158]
**Description**
A project partner is evaluating Kratos for commercial use and while checking the licenses of the external libraries in the core, they stumbled upon the license of the "triangle" (`external_libraries/triangle`). The license seems to be self-written by the author and does allow commercial use, but only if the author is contacted first. This might complicate the process of allowing the use of Kratos commercially by the legal department of larger companies.

The library seems not to be used in the core, but by `MeshingApplication`and `DelaunayMeshingApplication`.

Question:
- could the library be moved to the respective applications?
- simply not compiling these applications should solve the issue? Since the binaries would not contain any of the related code?

**Scope**
- License
- MeshingApplication
- DelaunayMeshingApplication

**Comment by philbucher** [comment]
It is used in the Core :)

@KratosMultiphysics/technical-committee

**Comment by armingeiser** [comment]
I just see now as well, its used in `kratos/utilities/delaunator_utilities.cpp` as well...

**Comment by philbucher** [comment]
Yes the dependency was added in #5169

It is not a big dependency and in the worst case could be refactored (I remember the change was controversial anyway) but it would be some work,,,

**Comment by roigcarlo** [comment]
If is only that file, it can be excluded from a regular compilation. In this case is particularly easy as its only used in vicente's own code. @philbucher I think we can just remove both cpp from the compilation and that's it (maybe a ugly #ifdef in the modelers register...)

In my opinion the way to go would be to either create a different compilation object where all this utilities and "extra" components that make use of external libraries exists (which can turned on/off with a compilation option) or either create a different Kratos application for them (call it KratosExtendedCore).

I would go for the first one, tbh.

**Comment by loumalouomega** [comment]
> If is only that file, it can be excluded from a regular compilation. In this case is particularly easy as its only used in vicente's own code. @philbucher I think we can just remove both cpp from the compilation and that's it (maybe a ugly #ifdef in the modelers register...)
> 
> In my opinion the way to go would be to either create a different compilation object where all this utilities and "extra" components that make use of external libraries exists (which can turned on/off with a compilation option) or either create a different Kratos application for them (call it KratosExtendedCore).
> 
> I would go for the first one, tbh.

I just want to say that originally I was using Delaunator, a MIT library, but @KratosMultiphysics/technical-committee recommended to use triangle (you can see the discussion in the PR), because was already in the repo. I have no problem in going back to Delaunator, which is faster for small meshes (and I did this for the mortar segmentation)

**Comment by loumalouomega** [comment]
> > If is only that file, it can be excluded from a regular compilation. In this case is particularly easy as its only used in vicente's own code. @philbucher I think we can just remove both cpp from the compilation and that's it (maybe a ugly #ifdef in the modelers register...)
> > In my opinion the way to go would be to either create a different compilation object where all this utilities and "extra" components that make use of external libraries exists (which can turned on/off with a compilation option) or either create a different Kratos application for them (call it KratosExtendedCore).
> > I would go for the first one, tbh.
> 
> I just want to say that originally I was using Delaunator, a MIT library, but @KratosMultiphysics/technical-committee recommended to use triangle (you can see the discussion in the PR), because was already in the repo. I have no problem in going back to Delaunator, which is faster for small meshes (and I did this for the mortar segmentation)

Do you want me to revert to Delaunator?

**Comment by philbucher** [comment]
I would wait

**Comment by maceligueta** [comment]
I think @RiccardoRossi dedicated time to this and made a summary to the Technical Committee.

**Comment by loumalouomega** [comment]
> having said this i think that the proposal of @roigcarlo of conditionally removing it is more than fair to me. @armingeiser would that solve the issue?

(and therefore I need to replace the library with another one, as I did the first time?)

**Comment by RiccardoRossi** [comment]
no, just thr feature gets inhabilitated...

**Comment by loumalouomega** [comment]
> no, just thr feature gets inhabilitated...

That feature is used in the IGAApp @tteschemacher and in the Contact, why not just replace with a library licence compatible that can get the job done?

**Comment by maceligueta** [comment]
@loumalouomega what do you think about QHull? http://www.qhull.org/html/index.htm

**Comment by loumalouomega** [comment]
> @loumalouomega what do you think about QHull? http://www.qhull.org/html/index.htm I am asking because I even found distributed memory meshers which use QHull inside.

"Qhull does not support constrained Delaunay triangulations, triangulation of non-convex surfaces, mesh generation of non-convex objects, or medium-sized inputs in 9-D and higher. "

But I imagine you are interested in for your "FD DEM method"

**Comment by maceligueta** [comment]
I was actually thinking of PFEM Fluid

**Comment by armingeiser** [comment]
@roigcarlo @loumalouomega thanks for solving this!
