### ISSUE TITLE
[ParticleMechanicsApplication] Accessing number of particles in background element

### ISSUE THREAD

**Issue by alecontri** [KratosMultiphysics/Kratos#9216]
Hi all, 
I was wondering if there was a way to access the number of particles falling inside a certain Background Grid element in the ParticleMechanicsApplication from the "updated_lagrangian.cpp" element. As I understand, every MPM element created has a particle with an associated background geometry in which it falls, but accessing the number of integration points inside the element geometry by construction it always gives 1 if I am not wrong.
I am grateful to anyone who can help me.

**Comment by rubenzorrilla** [comment]
For your first option (which is my preferred option) you don't need to change the base element. You can achieve the same behavior as follows:
1. Create a new variable in the MPM application to specify the number of material points per background element, namely `TOTAL_MATERIAL_POINTS`. This would be the "counter".
2. Then, each time you move the material points points you update this value of this variable, that is to say, initialize it to zero and use a search algorithm (the `BinBasedFastPointLocator` would most probably be the best option for this), to locate each material point. Then you can do `p_found_element->GetValue(TOTAL_MATERIAL_POINTS) += 1`. This is something that needs an `atomic` clause as you pointed up.

Concerning the second option, this is in my opinion no go as makes the MPI parallelization way complex, aside of the fact that you'll need to save and manipulate a dense large vector.

**Comment by rubenzorrilla** [comment]
Closing as it seems to be solved. @alecontri feel free to reopen if needed.
