### ISSUE TITLE
Language Server Hints

### ISSUE THREAD

**Issue by matekelemen** [KratosMultiphysics/Kratos#9229]
Language servers like clangd and intellisense usually expect a ```compile_commands.json``` in the repo's root to define included directories and other information that helps them parse C++ in an IDE. However, I don't see it getting generated anywhere; is this solved somewhere else?

If not, we can simply ask CMake to generate a ```compile_commands.json``` in the build directory and symlink it to the source's root:
```
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
EXECUTE_PROCESS(
    COMMAND ${CMAKE_COMMAND} -E create_symlink
    "${CMAKE_BINARY_DIR}/compile_commands.json"
    "${CMAKE_SOURCE_DIR}/compile_commands.json")
```

In this case, we should also add it to the ```.gitignore``` too of course.
```
/compile_commands.json
```

Any reasons why this shouldn't be done?

**Comment by matekelemen** [comment]
Right, I'm just suggesting we put it into the main ```CMakeLists.txt```. I could just do it in my own configuration script, but then I'd always have to manually ignore the ```compile_commands.json``` when committing. Plus I guess everyone who isn't using a full IDE must already do this, so why not put it in Kratos?

**Comment by roigcarlo** [comment]
If its usable this way :+1:. To be honest I am a clueless about this. Personally I use Intellisense with VScode and a clang linter for Vim and any of those makes use of that file. But again if it helps no problem to add it to the .gitignore or having it in the build folder, any works for me.
