### ISSUE TITLE
Release 9.0

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#9230]
**Description**
Dear @KratosMultiphysics/all 

We are planning to make a Release by the end of November. 
Date of the **Release** will be **26/11/2021**
**Freeze** branch would be ideally a couple of weeks before **12/11/2021**

The list of applications to be released by platform are to be checked here (please comment here if you add/delete apps so I am aware of possible changes):
https://github.com/KratosMultiphysics/Kratos/projects/5

As always we have created a milestone so we can track all the PR that you are interested to have in the release:
https://github.com/KratosMultiphysics/Kratos/milestone/20

Since this is the first release to use wheels instead of the regular zip packages it would be good to have the Freeze ready for the beginning of November to have some buffer to handle unexpected problems, so if you can make it before the 12/11/2021 we would really appreciate it.

**Issue Tracking** (this are on my side, no need to do anything):
- [x] Shallow Water is not compiled
- [x] SwimmingDEM has a missing dll on windows
- [ ] Hdf5 app is failing

**Comment by Vahid-Galavi** [comment]
> https://github.com/KratosMultiphysics/Kratos/projects/5

@roigcarlo I can not see any project here:

https://github.com/KratosMultiphysics/Kratos/projects/5

**Comment by roigcarlo** [comment]
Mm its odd, there should be several columns with lists of applications. 
I've been trying without logging in and seems to be public...

**Comment by roigcarlo** [comment]
9

**Comment by philbucher** [comment]
@roigcarlo did you already create the release branch?

**Comment by roigcarlo** [comment]
No, since there are still plenty of PR pending to be merged...

**Comment by sunethwarna** [comment]
I also would like to add `StatisticsApplication` for windows release as well. It is tested in CI for windows.

**Comment by philbucher** [comment]
@roigcarlo is there sth prepared where we can add stuff to the changelog?

**Comment by roigcarlo** [comment]
I will make a draft for the release later today. you can add it there.

**Comment by roigcarlo** [comment]
@KratosMultiphysics/all Release 9.0 has been created. If you need something to be included in the release, please make a separate PR into that branch.

**Comment by mpentek** [comment]
We would plan to used it for teaching, starting at the middle of December. Do you think I could test it by then, is that at all a feasible timeline?

**Comment by roigcarlo** [comment]
Hi @mpentek. I am planning to upload the binaries during this afternoon, so they should be available today.
I have only been able to test that they work up to certain point ( I don't know the details of the apps etc...) and this is the first release with wheels so I expect that there will be errors. If everyone can provide feedback, specially for win, I assume it shouldn't take more than a week to get rid of the problems.

So, I would say yes, it should be ready by mid December

**Comment by mpentek** [comment]
I can test (FluidDyn, StructMech and FSI) what we use for teaching on Win10 and Ubuntu20. I typically use the in-built examples.

**Comment by roigcarlo** [comment]
Perfect. Binaries should be already published. I think GiD interface will be published later (ping @jginternational ) don't know if you need it.

To install the new ones just extract the wheels somewhere and:

```bash
python -m pip install *.whl
```

Note that now you can use it with anaconda, scipy, or in python integrated in pretty much anything as long as you install the whs using the proper interpreter. (there are binaries for all supported python versions right now except pyton 3.10 win, that one will come on monday).

Also you can finaly use numpy and other python packages in the scripts :)

**Comment by mpentek** [comment]
Great news! @jginternational it would be nice to know if and how this would be bundled. Will it remain via internet retrieve thorugh GiD or there will be a new mechanism?

**Comment by jginternational** [comment]
Yes! But I need to work a little bit on in (check if python is installed in the system, install the proper packages...) 
Out system will change a bit but the users will not notice the changes (almost)

Next week I'll try to create the release

**Comment by mpentek** [comment]
I tested the packages on Win10 with pytho3.9.9 (so the version cp3.9). Here are install notes and an error log attached.

On this OS the long path names has to be enabled for an application, some application have troubles when trying to import.
[win10_cp39_install_notes_error_log.txt]
(https://github.com/KratosMultiphysics/Kratos/files/7649577/win10_cp39_install_notes_error_log.txt)

I tested sample simulation with the FluidMechanics, StructuralMechanics and FSI Apps, all work. I might be able to test the CoSim and Statistics as well.

Will the GiD problemtype be able to use packages installed by the user? Some sort of symbolic linking? Or there will be some other mechanism?

**Comment by roigcarlo** [comment]
Hi @mpentek , thx for the feedback. Looking into it right now.

For GiD, I don't know the details but I think the idea is that the user selects which python interpreter to use (or download one automatically). In this case you should be able to install any module you want. (@jginternational if you can confirm)

About the dev version, you can have both the wheels and dev origins at the same time in the same python version, but I don't recommend it. In any case modules in the PYTHON_PATH should have preference over the ones installed from pip.

**Comment by roigcarlo** [comment]
Hi @mpentek Problems from the `CoSimulatio` and `SwimmingDem` should be fixed (9.0.1 is available)

I am still fixing problems from Particle Mechanics, that seems to be a problem in the app, not in the release, Hopefully will be fixed by Monday

Also, thx to @jginternational you can now install from the internet!:

```
pip install KratosMultiphysics KratosCoSimulationApplication etc...
```

and uninstall (please don't :cry: )

```
pip uninstall KratosMultiphysics KratosCoSimulationApplication etc...
```

It still has some limitations. For win it needs the msvc140 redistributables, and we still cleaning some details, but it should be functional

**Comment by jginternational** [comment]
> Also, thx to @jginternational you can now install from the internet!:
> 
> ```
> pip install KratosMultiphysics KratosCoSimulationApplication etc...
> ```

I'm also working on the gui, so the users get the kratos binaries this way, and developers can choose between this packages or the ones they build from source (configure.sh or .bat)

**Comment by mpentek** [comment]
Ok, so I understand the installation now might go straight away from the internet, without downloading the WHEEL packages locally. @roigcarlo @jginternational  do you think I might be able to  try the new approach from GiD by Tuesday next week? We would intend to "go live" with it for teaching on Thursday afternoon and are still debating whether to use GiD15 with Kratos 8 or aim higher :-D.

**Comment by armingeiser** [comment]
> Also, thx to @jginternational you can now install from the internet!:

very cool, thanks @jginternational! I found a small inconsitency, the wheel version is already 9.0.1, but the title of the package still says 9.0.0. 

<img width="1132" alt="grafik" src="https://user-images.githubusercontent.com/25903585/145460174-aa0df0a3-d574-4e92-b105-7e1c458ec3c1.png">

**Comment by jginternational** [comment]
You can find a beta 9.0.0 of the gid interface here https://github.com/KratosMultiphysics/GiDInterface/releases/tag/Release-9.0.0

I need to test more before adding it as available in the GiD marketplace, but you can use it

**Comment by armingeiser** [comment]
@roigcarlo how often will a new package be created and uploaded?  Is this eventually even automated?

**Comment by roigcarlo** [comment]
For now we will upload them manually as we usually made releases in the past. As everything is in now place you can expect releases more frequently, and not only for major changes (9.0.x and 9.x.x)

Pipy keeps old releases up, so you will be able to target past versions as well if you want. 

We also have nightly and weekly releases on the oven but when they come they will be distributed separately, more on that when are finished
