### ISSUE TITLE
Errors in parallel regions are not correctly captured with visual studio compiler

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#9259]
**Description**
I know this is mainly a known problem. I just wanted to create the issue as I did not find any related to this.

The problem is that the run crashes if we try to throw any error in parallel regions using visual studio, so the user has no clue why their run failed. It seems gcc has something like an auto-wrapper for parallel regions using some kind of try-catch that visual studio lacks. This happens even if you are running with just one thread. I tried also adding KRATOS_TRY - KRATOS_CATCH but the run still crashes without any message.

I discussed with @pooyan-dadvand the possibility of calling the logger before the exception, but this seems more like a dirty trick than a real solution. I wonder if someone has any ideas of how this could be solved or if there is any current work around for it.

Thanks!

**Environment**
- Visual Studio (any version)

@roigcarlo @KratosMultiphysics/technical-committee

**Comment by pooyan-dadvand** [comment]
What about having a for_each_with_exception that handles the exception manually until we switch to C++11?

```c++
template <class TUnaryFunction>
    inline void for_each_with_exception(TUnaryFunction&& f)
    {
        Exception* p_exception = nullptr;
        #pragma omp parallel for
        for (int i=0; i<mNchunks; ++i) {
            try{
                 for (auto it = mBlockPartition[i]; it != mBlockPartition[i+1]; ++it) {
                    f(*it); //note that we pass the value to the function, not the iterator
                }
            }
            catch(Exception& e) {
                 #pragma omp critical
                 {
                         if(p_exception == nullptr) {
                               p_exception = new Exception(e);
                        }
                 }
            }
        }

        KRATOS_ERROR_IF(p_exception) << p_exception->what() << std::endl;
    }

```

**Comment by philbucher** [comment]
I am quite sure that this does not work as omp does not handle exceptions at all afaik

i will try to find some references later

**Comment by philbucher** [comment]
it seems like the solution proposed by @pooyan-dadvand could work, I did some research and came across e.g. [this windows article](https://docs.microsoft.com/en-us/cpp/parallel/concrt/convert-an-openmp-loop-that-uses-exception-handling?view=msvc-170)

Seems like as long as the thread that is causing the exception handles it then we are good
