### ISSUE TITLE
Implementing initial strains/stresses in shell elements

### ISSUE THREAD

**Issue by clazaro** [KratosMultiphysics/Kratos#9273]
In order to simulate thermal expansion/contraction in structures we need to implement initial strains/stresses in shell and beam elements (we see that they are already implemented for solid elements.)
Starting with shell elements, it seems that the implementation should be quite straightforward, because the constitutive behaviour is defined using the `ConstitutiveLaw` class at the level of the integration points of the ply. Therefore a modification of `set_initial_state_process.cpp` for the case of shell elements to point to the ply integration points should suffice to achieve the desired behaviour.
In pseudo-code this should read something like this:
~~~c++
if (r_element.HasCrossSections()){
    loop for the sections in the element
        loop for the plies in the section
            loop for the integration points
                constitutive_law_vector[point_number]->SetInitialState(p_initial_state);

}
else{
    execute-existing-code
}
~~~
We would be glad if we get some support for this implementation, as we are Kratos newbies.
In particular we get stuck at how to point to the sections of the shell element, and how to point to the plies of the section.
For the first case it seems that a public method like
~~~c++
CrossSectionContainerType const& GetCrossSectionsOnIntegrationPoints() const
{
    return *mSections;
}
~~~
should be added to `base_shell_element.hpp` (and possibly to `element.h` as virtual method??)
And something similar for the plies:
~~~c++
PlyCollection const& GetPlyCollection() const
{
    return mStack;
}
~~~
We will be grateful for any help with this enhancement!

**Comment by loumalouomega** [comment]
@clazaro I would need to take a look in detail, but you are right. The one who implemented the InitialState was @AlejandroCornejo . Basically as you say we should provide support for the particular case of the shell. My question is how to do it without penalize the solid computation (as this is done in the gauss point level, it is computed many times, and therefore we can deal with a performance penalty). The implementation detail should be analized...

**Comment by AlejandroCornejo** [comment]
Hi! The `set_initial_state_process` can be extended or you can create your own `set_initial_state_shell_process` if you think it's gonna be more efficient (reduce the number of conditionals, etc). If you propose a new implementation I'll be glad to have a look!
Regarding shells, @philbucher knows better than anyone the implementation :D 

In any case, adding virtual methods to the base element has not been the most desired option in general terms. But let's discuss it :)

**Comment by loumalouomega** [comment]
> Hi! The `set_initial_state_process` can be extended or you can create your own `set_initial_state_shell_process` if you think it's gonna be more efficient (reduce the number of conditionals, etc). If you propose a new implementation I'll be glad to have a look! Regarding shells, @philbucher knows better than anyone the implementation :D
> 
> In any case, adding virtual methods to the base element has not been the most desired option in general terms. But let's discuss it :)

Or evil templates ... ;)

**Comment by loumalouomega** [comment]
> > Hi! The `set_initial_state_process` can be extended or you can create your own `set_initial_state_shell_process` if you think it's gonna be more efficient (reduce the number of conditionals, etc). If you propose a new implementation I'll be glad to have a look! Regarding shells, @philbucher knows better than anyone the implementation :D
> > In any case, adding virtual methods to the base element has not been the most desired option in general terms. But let's discuss it :)
> 
> Or evil templates ... ;)

It is a joke, better with virtual classes

**Comment by philbucher** [comment]
I will check the code and comment asap :)

**Comment by philbucher** [comment]
@clazaro I did a draft in https://github.com/KratosMultiphysics/Kratos/tree/structural/shells-get-claws, this is IMO how it should be done.
Note that the shells can have many CLaws in case they have a layered composite layup

**Comment by clazaro** [comment]
Hi @philbucher, I compiled the `shells-get-claws` branch with no modification and it works fine, at least for a single-layer shell, many thanks! 
A minimal example is attached (could be used as basis for a unit test IMO).
[Shell_initial_strain.zip](https://github.com/KratosMultiphysics/Kratos/files/7470173/Shell_initial_strain.zip)
I will go on trying to set different initial strains in the layers of a multi-layer shell.

**Comment by clazaro** [comment]
Hi! I looked into setting different initial strains at each layer and I think the best way would be to create a new `set_initial_state_shell_process` as suggested by @AlejandroCornejo. If I understood well the code, different CLaws could be set for each layer as you mentioned @philbucher ; this allows the definition of different initial states. However the current implementation in `read_materials_utility.cpp` assigns a single material to each element. In any case, I don't need that feature now. I'd rather work on initial strains in beams, for which I will open another issue.

In the meanwhile, I have prepared the files for a unit test corresponding to the initial state for the shell element (the same for all layers). May I contribute this test? Should I push to the `structural/shells-get-claws` branch? (I guess I have no permission yet.)

**Comment by philbucher** [comment]
@clazaro why do you need the `set_initial_state_shell_process` ? I am confused as to what this one would do

> In the meanwhile, I have prepared the files for a unit test corresponding to the initial state for the shell element (the same for all layers). May I contribute this test? Should I push to the structural/shells-get-claws branch? (I guess I have no permission yet.)

Sure, that would be great. You cab even open a PR, I think the changes make sense to go in
@roigcarlo can you please add @clazaro to the structural team? Thx

**Comment by roigcarlo** [comment]
Done

**Comment by clazaro** [comment]
> why do you need the `set_initial_state_shell_process` ? I am confused as to what this one would do

`set_initial_state_process` is designed to assign a single initial state (strain, stress and/or deformation gradient) to the elements of a model part. However, setting different states in each ply of a shell element would require 
- an array of initial states at each ply as input
- some check to see if the size of the array matches the number of plies in the element section (or equals 1 if the element has only one layer or is not a shell element)
- the needed loops to assign the initial state to the CLs at each gp of each layer

This could be done modifying the 'set_initial_state_process' files for sure, but probably means a performance overhead because of the checks of the size of the arrays. This is why I said that a specific process could be better.

Implementing this could be interesting for example to model the effect of temperature gradients across the shell thickness. We don't need this right now, but if it is meaningful we can contribute.

**Comment by loumalouomega** [comment]
Just to say that IMO the solution from @AlejandroCornejo is the best one.

**Comment by philbucher** [comment]
@clazaro ok since don’t need it atm I suggest we leave it as is and update/add stuff once you have a concrete usecase
