### ISSUE TITLE
about variable registration

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#929]
this is essentially a question for @pooyan-dadvand 

To my understanding when we register a variable in kratos, the function 

     KratosComponents< VariableType >::Add is being called.

currently that code does the following (with a singleton)

     msComponents.insert(typename ComponentsContainerType::value_type(Name , &ThisComponent));

this is then followed by 
 
     void Initialize()
    {
        unsigned int j = 0;
        for(KratosComponents<VariableData>::ComponentsContainerType::iterator i = KratosComponents<VariableData>::GetComponents().begin() ;
                i != KratosComponents<VariableData>::GetComponents().end() ; i++)
            //const_cast<VariableData&>(i->second.get()).SetKey(++j);
            i->second->SetKey(++j);
    }

in the practice this implies that every time a new variable is added the key of all the variables is changed, which explains why the test

https://github.com/KratosMultiphysics/Kratos/blob/experimental-cfd-base-element/kratos/tests/test_importing.py

fails (the variable list is constructed with a set of key, which is then changed when the new variable is added)

My question is:
could we modify the function Add to do something like

    static void Add(std::string const& Name, TComponentType const& ThisComponent)
    {
        auto it = msComponents.find(Name)
        if(it != msComponents.end()) //variable is already registered
        {
            ThisComponent.SetKey( it->Key() ) //we would have to remove the const
        }
        else
        {
             int nregistered = msComponents.size();
             ThisComponent.SetKey( nregistered + 1 );
             msComponents.insert(typename ComponentsContainerType::value_type(Name , &ThisComponent));
        }
    }

**avoding  to call the Initialize function**? (or making it empty)

This way the key of a variable will always remain the same once it is assigned

**Comment by pooyan-dadvand** [comment]
@RiccardoRossi Your observation is absolutely right and your suggestion is also correct! Nevertheless changing the key of variables to hash removes this problem completely and lets better handling of application variables.

**Comment by RiccardoRossi** [comment]
ok. Closing
