### ISSUE TITLE
[CoSim] Compilation problem

### ISSUE THREAD

**Issue by ceulogiof** [KratosMultiphysics/Kratos#9290]
**Description**
I tried to update the branch StructMech/couple_pfem with master, but the following error occurred:
```
CMake Error at applications/CoSimulationApplication/CMakeLists.txt:87 (install):
  install TARGETS given target "co_sim_io" which does not exist in this
  directory.

(...)

-- Configuring incomplete, errors occurred!
See also "/home/dev/Downloads/Software/Kratos/cmake_build_serial_release/CMakeFiles/CMakeOutput.log".
Makefile:644: recipe for target 'cmake_check_build_system' failed
make: *** [cmake_check_build_system] Error 1
```
I attach the log [compilation.log.txt](https://github.com/KratosMultiphysics/Kratos/files/7475847/compilation.log.txt), config [configure.sh.txt](https://github.com/KratosMultiphysics/Kratos/files/7475851/configure.sh.txt) and CMakeOutput files [CMakeOutput.log.txt](https://github.com/KratosMultiphysics/Kratos/files/7475927/CMakeOutput.log.txt).

I also tried cleaning the cache and build files, but I still get the same results. I don't know if I am missing some extra update or configuration because of the CoSimIO recent changes in #9166. I will appreciate any hints.

**Scope**
- Compilation
- CoSimulationApplication

**Environment**
- OS: Ubuntu 18.04
- Branch: StructMech/couple_pfem
- Python 3.6

**Comment by philbucher** [comment]
Hey @ceulogiof 
I compiled your branch and it worked fine for me (btw I (locally) merged master as seems like you hadn't pushed your latest changes.

How did you clean the build files? The error you get seems to come from having leftover files. I would remove everything that is created during compilation and try again.

I compiled on several machines after #9166 and it was never a problem

**Comment by ceulogiof** [comment]
@philbucher You are right, I have some leftovers. I use VSCode, usually clean the cache and erase the cmake_build folder. Maybe am I missing another erasing step? Also, for pushing my changes I usually merge locally first, compile the branch and then make the push to make sure everything is smooth. 
Anyways I am trying now with the remote PC and it seems to be compiling fine for now.
