### ISSUE TITLE
Enhancing residual-based Newton-Raphson strategy

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#9299]
**Description**
I've been trying to implement a more robust "damped" NR strategy in Kratos but I am facing some difficulties, I suppose due to my lack of experience in these strategies.

Imagine that I am solving this:
~~~c++
p_builder_and_solver->BuildAndSolve(p_scheme, r_model_part, rA, rDx, rb);
~~~

And then I update the database in order to be able to compute the updated residual:
~~~c++
UpdateDatabase(rA, rDx, rb, BaseType::MoveMeshFlag());
p_builder_and_solver->BuildRHS(p_scheme, r_model_part, rb);
CalculateResidualNorm(r_model_part, new_residual, r_dof_set, rb);
~~~

And NOW I want to apply only half of the previous rDx to the original state! but If i do the following **i do not return to the previous state**:
~~~c++
TSparseSpace::InplaceMult(rDx, -1.0);  // I try to cancel the whole rDx
UpdateDatabase(rA, rDx, rb, BaseType::MoveMeshFlag());  // should return to the previous case right?
p_builder_and_solver->BuildRHS(p_scheme, r_model_part, rb);
CalculateResidualNorm(r_model_part, new_residual, r_dof_set, rb); // not equal residual!
~~~

What I am missing?

Regards

working in (improve-newton-raphson-strategy)

**Comment by loumalouomega** [comment]
This looks like a line search, have you take a look into that?

**Comment by loumalouomega** [comment]
> This looks like a line search, have you take a look into that?

https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/solving_strategies/strategies/line_search_strategy.h

**Comment by AlejandroCornejo** [comment]
> 
> 
> This looks like a line search, have you take a look into that?

yes!! but I really want to try something very simple... If I learn something on the way better! :)

**Comment by loumalouomega** [comment]
> > This looks like a line search, have you take a look into that?
> 
> yes!! but I really want to try something very simple... If I learn something on the way better! :)

Look at the UpdateDatabase of the line search

**Comment by AlejandroCornejo** [comment]
Solved! only the reset of the rB was missing... `TSparseSpace::SetToZero(rb);` adding this it works
