### ISSUE TITLE
Kratos NOT compiling in Windows

### ISSUE THREAD

**Issue by AlejandroCornejo** [KratosMultiphysics/Kratos#9312]
**Description**
In Windows I am obtaining this compilation errors:

D:\KRATOS_MULTIPHYSICS\Kratos\kratos\modeler\cad_tessellation_modeler.cpp(60): error C2039: 'Kratos_Brep_Surface': no es un miembro de 'Kratos::GeometryData' [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\kratos\KratosCore.vcxproj]
  D:\KRATOS_MULTIPHYSICS\Kratos\kratos\geometries/geometry_data.h(59): note: vea la declaración de 'Kratos::GeometryData'

D:\KRATOS_MULTIPHYSICS\Kratos\kratos\modeler\cad_tessellation_modeler.cpp(60): error C2065: 'Kratos_Brep_Surface': identificador no declarado [D:\KRATOS_MULTIPHYSICS\Kratos\build\Release\kratos\KratosCore.vcxproj]

**Comment by loumalouomega** [comment]
Should work now

**Comment by AlejandroCornejo** [comment]
let's try!
