### ISSUE TITLE
Compilation error related to FemToDemApplication and DelaunayMeshingApplication

### ISSUE THREAD

**Issue by joaquinirazabal** [KratosMultiphysics/Kratos#9316]
**Description**
When trying to compile the FemToDemApplication I am obtaining a compilation error, related with de DelaunayMeshingApplication. Three weeks ago I did not have any problem.

The error is this:

/usr/bin/ld: no se puede encontrar -ltriangle
collect2: error: ld returned 1 exit status
make[2]: *** [applications/DelaunayMeshingApplication/CMakeFiles/KratosDelaunayMeshingCore.dir/build.make:194: applications/DelaunayMeshingApplication/libKratosDelaunayMeshingCore.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1250: applications/DelaunayMeshingApplication/CMakeFiles/KratosDelaunayMeshingCore.dir/all] Error 2

**Scope**
- Compilation

**Environment**
- OS: Ubuntu 20.04
- Branch: master
- Python 3.8

**Comment by joaquinirazabal** [comment]
@AlejandroCornejo

**Comment by loumalouomega** [comment]
This was fix 2 days ago, can you pull the master again?

**Comment by AlejandroCornejo** [comment]
Also now it is required to:
`-DUSE_TRIANGLE_NONFREE_TPL=ON ^`

**Comment by joaquinirazabal** [comment]
Thank you for the quick response, now it is compiling, as @AlejandroCornejo said, now it is necessary to add -DUSE_TRIANGLE_NONFREE_TPL=ON
