### ISSUE TITLE
problems with the beams and local axis

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#932]
@KlausBSautter @philbucher finally i took care of adding the LOCAL_AXIS_* vars.

I need your help in modifying the beam so that it uses correctly (i think it is a trivial modification, however i would prefer you to do it)

until when will you be on holidays?

**Comment by philbucher** [comment]
Hi Riccardo,
I am back on 6.11. 
The beam is Klaus work, it would be best if he does it.
I think he is back on Thursday

**Comment by RiccardoRossi** [comment]
@KlausBSautter i have been looking into the local axis thing. Hopefully by today we ill merge #915 which brings inside the definition of the LOCAL_AXIS_*

i would need you to modify the cr_beam so that it assumes that the axis v2 is given by LOCAL_AXIS_2

@jginternational can u confirm that the interface uses that?

**Comment by pooyan-dadvand** [comment]
This would be problem for release....

**Comment by jginternational** [comment]
@RiccardoRossi 

As we can see [here](https://github.com/KratosMultiphysics/GiDInterface/blob/2fda004376d1e520177f4470565152d586ba8341/kratos.gid/apps/Structural/write/write.tcl#L176) we are using LOCAL_AXIS_2  in the interface

**Comment by RiccardoRossi** [comment]
yes, it is the kratos side failing

**Comment by KlausBSautter** [comment]
@RiccardoRossi  I am back today and started working on it this morning. I keep you updated

**Comment by KlausBSautter** [comment]
@RiccardoRossi  see #948 for the changes in the beam element. And a working example using the LOCAL_AXIS_2 from the *.mdpa
[localAxis2Beam.zip](https://github.com/KratosMultiphysics/Kratos/files/1437170/localAxis2Beam.zip)

**Comment by jginternational** [comment]
@KlausBSautter Check the new write format in KratosMultiphysics/GiDInterface/pull/171
