### ISSUE TITLE
[StructuralMechanics] Bug in formfinding_strategy

### ISSUE THREAD

**Issue by MZecchetto** [KratosMultiphysics/Kratos#9333]
Dear @KratosMultiphysics/structural-mechanics ,
running the example "catenoid_formfinding" in the example repo, validation suite, I got an error.
It looks to me that this line: https://github.com/KratosMultiphysics/Kratos/blob/774096c1037e12e4f58a1a32fef35283d9c077a2/applications/StructuralMechanicsApplication/custom_strategies/custom_strategies/formfinding_strategy.hpp#L165

leads to an error. I removed it in my local and it works fine.
However I cannot push the modification because I am no longer part of the project.

Tagging @KlausBSautter since author of the example.

**To Reproduce**
Run catenoid_formfinding from example repo.

**Environment**
- OS: Ubuntu 18.04
- Branch: master
- Python 3.7

**Comment by philbucher** [comment]
fixed in #9338
