### ISSUE TITLE
Error when compiling the DelaunayMeshingApplication

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#9339]
**Description**
Here the error:

```
/usr/bin/ld: cannot find -ltriangle
collect2: error: ld returned 1 exit status
applications/DelaunayMeshingApplication/CMakeFiles/KratosDelaunayMeshingCore.dir/build.make:281: recipe for target 'applications/DelaunayMeshingApplication/libKratosDelaunayMeshingCore.so' failed
make[2]: *** [applications/DelaunayMeshingApplication/libKratosDelaunayMeshingCore.so] Error 1
CMakeFiles/Makefile2:3413: recipe for target 'applications/DelaunayMeshingApplication/CMakeFiles/KratosDelaunayMeshingCore.dir/all' failed
make[1]: *** [applications/DelaunayMeshingApplication/CMakeFiles/KratosDelaunayMeshingCore.dir/all] Error 2
```

**Scope**
Where in Kratos is this bug happening. 
E.g.
- Kratos DelaunayMeshingApplication
- As a dependency to PfemFluidDynamicsApplication

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Ubuntu 18.04
- Branch: master

**Comment by roigcarlo** [comment]
Hi, it is not an error. (see #9231)

From now own use of tetgen and triangle needs to be explicitly enabled. In this case is enough to add
```
-DUSE_TRIANGLE_NONFREE_TPL=ON
```
in the configure.

**Comment by mpentek** [comment]
> -DUSE_TRIANGLE_NONFREE_TPL=ON

Ok, I understand it is not an error, but it is also less than obvious from a user point of view.

Until now the user wanted the PfemFluidDynamicsApplication, so I get a warning that the dependency DelaunayMeshingApplication is compiled. The message is clear.

With the current usage, I simply get the error I posted initially, which does not point to the reason nor to the solution. Is there a way the user gets prompted to use the compilation setting

**Comment by roigcarlo** [comment]
Yep, I can put a warning if trying to compile an app which requires that lib :+1:

**Comment by loumalouomega** [comment]
> Yep, I can put a warning if trying to compile an app which requires that lib +1

See #9340

**Comment by mpentek** [comment]
Great, thanks! I now also get it, that it is not technical, but also legal. Interfering with science and engineering...
