### ISSUE TITLE
[All][I/O] "analysis_stage" field in "problem_data" section of ProjectParameters.json

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#9341]
**Description**
In order to make the Kratos ROM capabilities more general (and most probably for other purposes) it would be useful to add a new `main_application` field to our `problem_data` section of the `ProjectParameters.json`. This new `main_application` would be intended to specify which is the main application of the current case, that is to say, the application implementing the `AnalysisStage` to be used (e.g. for FSI simulations it would be `"main_application" : "FSIApplication"`, while for CFD problems it would be `"main_application" : "FluidDynamicsApplication"`. )

The idea is to allow properly filtering in the `python_solvers_wrapper_rom.py` as well as to (potentially) unify the ROM analysis stage files.

Note that this change is rather easy from the GUIs perspective. Also note that retrocompatibility is readily ensured since there is no defaults check for the  `problem_data` section.

What do you think?

**Comment by riccardotosi** [comment]
If the purpose is to correctly import the analysis stage, you may be interested in a behavior similar to the one we use in the `MultilevelMonteCarloApplication`, where the analysis stage is always derived from some other analysis stage (e.g. from the fluid dynamics analysis stage).

You simply need to pass a key to your json as
~~~json
analysis_stage: "analysis_stage.ROMAnalysisStage",
~~~
and then import it using the key `analysis_stage`. For example, in the `MultilevelMonteCarloApplication` we do it like this:

https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MultilevelMonteCarloApplication/external_libraries/XMC/xmc/classDefs_solverWrapper/KratosSolverWrapper.py#L82-L86

**Comment by rubenzorrilla** [comment]
> If the purpose is to correctly import the analysis stage, you may be interested in a behavior similar to the one we use in the `MultilevelMonteCarloApplication`, where the analysis stage is always derived from some other analysis stage (e.g. from the fluid dynamics analysis stage).
> 
> You simply need to pass a key to your json as
> 
> ```json
> analysis_stage: "analysis_stage.ROMAnalysisStage",
> ```
> 
> and then import it using the key `analysis_stage`. For example, in the `MultilevelMonteCarloApplication` we do it like this:
> 
> https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MultilevelMonteCarloApplication/external_libraries/XMC/xmc/classDefs_solverWrapper/KratosSolverWrapper.py#L82-L86

Thanks! The mid term idea goes in that direction. However, the aim is precisely to avoid the need of duplicating the same stage for each base one (I think we can achieve that with a mechanism similar to yours, I'll have a look :wink:).

**Comment by philbucher** [comment]
how does this look like if one app uses multiple?

**Comment by ddiezrod** [comment]
Going on the direction @riccardotosi is proposing, I think I'd take this opportunity to do something more global that can be used in a future kratos "main.py" to select which analysis we want to use, having in mind that this mechanism should also be used in multi-stage simulations.

**Comment by rubenzorrilla** [comment]
> how does this look like if one app uses multiple?

This is why my suggestion is to consider as `main_application` the application implementing the stage (which is as far as I understand always unique).

**Comment by rubenzorrilla** [comment]
> Going on the direction @riccardotosi is proposing, I think I'd take this opportunity to do something more global that can be used in a future kratos "main.py" to select which analysis we want to use, having in mind that this mechanism should also be used in multi-stage simulations.

With the design we're working on (see #9258) this would be perfectly compatible since each stage block will have its own `problem_data` section.

**Comment by rubenzorrilla** [comment]
After having discussed this with @pooyan-dadvand we both think that this would be a very useful thing (even to document which stage is used for the run).

However, better than `main_application` the idea would be to use a `analysis_stage` field (e.g. for a CFD problem we would write `"analysis_stage" : "FluidDynamicsApplication.fluid_dynamics_analysis"` while for an FSI one we would do `"analysis_stage" : "FSIApplication.fsi_analysis"`. In this way we document both the application and the stage to be used.

@Rbravo555 @SADPR this will also serve us to solve the ROM stage issue.

**Comment by philbucher** [comment]
How about adding the full name like we do for the processed?
This way also custom anslysis stages outside of Kratos could be used

**Comment by rubenzorrilla** [comment]
> How about adding the full name like we do for the processed? This way also custom anslysis stages outside of Kratos could be used

Do you mean adding `"analysis_stage" : "KratosMultiphysics.FluidDynamicsApplication.fluid_dynamics_stage"`?

**Comment by philbucher** [comment]
Yes exactly!

**Comment by philbucher** [comment]
Then we could even habe a generic MainKratos.py file

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/altair is it compatible with our stages?

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/technical-committee suggests to add this to the root of the stage instead of being in the `problem_data `section.

**Comment by ddiezrod** [comment]
> @KratosMultiphysics/altair is it compatible with our stages?

What do you mean? I understand the mechanism proposed here will import the specified module so it should work fine. With respect to the interface, ours is different. We have two settings: "ams_module" and "analysis_type", so we'll have to change it anyway if we want to adapt it to whatever is done here (because of the "ams")

**Comment by ddiezrod** [comment]
@pooyan-dadvand Just to clarify. We follow the same "app_module.python_module" structure, we do not have any sort of dictionary in the analysis creation.

**Comment by pooyan-dadvand** [comment]
Thanks, That was my concern.

**Comment by rubenzorrilla** [comment]
I think that now that [GiD interface #858](https://github.com/KratosMultiphysics/GiDInterface/pull/858) has been merged we can close this.
