### ISSUE TITLE
Dynamic tau (among others) can only have one value for all calculations.

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#9344]
**Description**
There are some values( I can recall now by heart: dynamic_tau, time_integration_theta and cross_wind_diffusion_factor) that are defined in ProcessInfo. This is problematic as this means that a unique value is used everywhere. For example, we have dynamic_tau in the formulation of the fluid element but also in the level set element.

To deal with this problem, in altair side we are manually setting these values again at every time step so the desired value is used at each place. This works fine, although it is kind of tricky. I think this show somehow the limitations of using process info as a place to store parameters. ~~One possibility could be to store these values directly in the data value container of the model part. This way, we make sure each one has its own value.~~ (edited: this is not possible)

**Scope**
- KratosCore
- FluidDynamicsApplication
- ConvectionDiffusionApplication

@rubenzorrilla @KratosMultiphysics/fluid-dynamics

**Comment by RiccardoRossi** [comment]
the modelpart is not the correct place, since we cannot access it from
within the elements...

a possibility could be in the properties, but that is also kind of tricky.

**Comment by ddiezrod** [comment]
> the modelpart is not the correct place, since we cannot access it from within the elements... a possibility could be in the properties, but that is also kind of tricky.

You are right, of course. I wrote it without thinking too much. From the current options, I think I'd rather modify it every time it is used of that is ok for the rest...

**Comment by rubenzorrilla** [comment]
Honestly, I don't think we have much room for improvements in here... I think we need to live with that and "manually" change it at the solver level.

**Comment by ddiezrod** [comment]
> Honestly, I don't think we have much room for improvements in here... I think we need to live with that and "manually" change it at the solver level.

So you mean you are ok with the solver and the level set process resetting these values every time SolveSolution / Execute is called?

**Comment by rubenzorrilla** [comment]
> > Honestly, I don't think we have much room for improvements in here... I think we need to live with that and "manually" change it at the solver level.
> 
> So you mean you are ok with the solver and the level set process resetting these values every time SolveSolution / Execute is called?

Saying I'm OK is not fair at all, I'd say we live with that...

The point is that the unique container that is global and accessible from elements/conditions is the process info, which is owned by the model part. The unique way that comes to my mind to bypass this is to have more than one model part in order to have more than one process info (which goes against our connectivity preserve modeler idea)...

**Comment by loumalouomega** [comment]
> > > Honestly, I don't think we have much room for improvements in here... I think we need to live with that and "manually" change it at the solver level.
> > 
> > 
> > So you mean you are ok with the solver and the level set process resetting these values every time SolveSolution / Execute is called?
> 
> Saying I'm OK is not fair at all, I'd say we live with that...
> 
> The point is that the unique container that is global and accessible from elements/conditions is the process info, which is owned by the model part. The unique way that comes to my mind to bypass this is to have more than one model part in order to have more than one process info (which goes against our connectivity preserve modeler idea)...

A class specifically defined in order to manage this kind of information can be defined, and stored in the processinfo. This may add a penalty of performance as well...

**Comment by rubenzorrilla** [comment]
> > > > Honestly, I don't think we have much room for improvements in here... I think we need to live with that and "manually" change it at the solver level.
> > > 
> > > 
> > > So you mean you are ok with the solver and the level set process resetting these values every time SolveSolution / Execute is called?
> > 
> > 
> > Saying I'm OK is not fair at all, I'd say we live with that...
> > The point is that the unique container that is global and accessible from elements/conditions is the process info, which is owned by the model part. The unique way that comes to my mind to bypass this is to have more than one model part in order to have more than one process info (which goes against our connectivity preserve modeler idea)...
> 
> A class specifically defined in order to manage this kind of information can be defined, and stored in the processinfo. This may add a penalty of performance as well...

At this point, which would imply changing the access from the elements, I think it would be easier to change the element access by creating `DYNAMIC_TAU_CFD` and `DYNAMIC_TAU_CONVECTION` variables (note that there are not so many concurrencies of this type in Kratos).

**Comment by ddiezrod** [comment]
> At this point, which would imply changing the access from the elements, I think it would be easier to change the element access by creating `DYNAMIC_TAU_CFD` and `DYNAMIC_TAU_CONVECTION` variables (note that there are not so many concurrencies of this type in Kratos).

You will still have a problem if you have two convection processes (e.g. one for level set and one for computing flow length).
