### ISSUE TITLE
FemToDem importing rules

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#9351]
**Description**
FemToDemApplication is asterisk-importing all symbols from dependent applications.

**Scope**
FemToDemApplication

**Expected behavior**
Asterisk imports should never be used, please change from:
```python
from KratosMultiphysics.MeshingApplication import *
from KratosMultiphysics.PfemFluidDynamicsApplication import *
from KratosMultiphysics.DEMApplication import *
from KratosMultiphysics.StructuralMechanicsApplication import *
```

to 

```python
import KratosMultiphysics.MeshingApplication
import KratosMultiphysics.PfemFluidDynamicsApplication
import KratosMultiphysics.DEMApplication
import KratosMultiphysics.StructuralMechanicsApplication
```

I could not do it myself because I don't know the internals of the app and I ignore if you are using any of the symbols imported directly in your app scripts.

If possible I would like this to enter before the release, but if it needs a lot of work is not 100% needed.

**Environment**
Any.

**Comment by AlejandroCornejo** [comment]
working on it.. @joaquinirazabal

**Comment by joaquinirazabal** [comment]
Thanks @AlejandroCornejo :)
