### ISSUE TITLE
Pfem2 Application is not splited

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#9352]
**Description**
Pfem2 Application is still not separated into core/application.
@KratosMultiphysics/pfem2 

**Scope**
Where in Kratos is this bug happening. 
Pfem2 Application

**Expected behavior**
It should be split. 

**Environment**
Any

**Comment by dcagritan** [comment]
Hello @roigcarlo,
I'll deal with that this week. Do we have some sort of deadline? 
Regards

**Comment by roigcarlo** [comment]
No, if it does not have to be in the release there is no deadline

**Comment by dcagritan** [comment]
I see. I'll make it ready for the next release.
Regards
