### ISSUE TITLE
RANSApplication importing rules

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#9354]
**Description**
Importing FluidDynamicsApplication from the RANS main script should not be done conditionally, as it is a linking time dependency of the libKratosRansCore.lib.

Also, * import should be changed for a regular import
@KratosMultiphysics/rans 

**Scope**
RANSApplication

**Expected behavior**
```python
if (CheckIfApplicationsAvailable("FluidDynamicsApplication")):
    from KratosMultiphysics.FluidDynamicsApplication import *
else:
    raise Exception("RANSApplication requires FluidDynamicsApplication.")
```

Should be changed simply to:

```python
import KratosMultiphysics.FluidDynamicsApplication
```

If needed, you can keep the if/else logic, but note that that conditional should never fail, as the compilation of the RansCore will trigger the compilation of FluidDynamics, or fail.

**Environment**
Any

**Comment by sunethwarna** [comment]
Thanks @roigcarlo. This makes sense :)
