### ISSUE TITLE
Level set convection - Zalesak sphere -  problems with new algebraic stabilization element

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#9364]
**Description**
I've created a 3D zalesak sphere test to check how well the different level set options work. For this test, I am doing half a turn with 200 time steps and checking how well the original shape is maintained.

From what I see. the original supg levelset is behaving much bettter than the new agebraic stabilization element.

Left: SUPG, Right: New algebraic stabilization
Original shape:
![image](https://user-images.githubusercontent.com/25667299/142396934-0e64fb22-daeb-44f4-8192-873b61565777.png)
Quarter turn
![image](https://user-images.githubusercontent.com/25667299/142397055-c577e054-51ff-4f07-8d3b-a98bde70f8d6.png)
Half turn
![image](https://user-images.githubusercontent.com/25667299/142397437-670aee7a-cb85-4a7a-8227-9076223b5002.png)

In both cases, the test is run with bfecc. We can clearly see that shape is much better preserved in the SUPG element and that we even have some oscillations/undershoots in the "air" region in the new element.

I have two questions regarding this:
- Is there any time step limitation for the new element? This could explain why its behaving much worse in this case.
- In the original paper where the formulation of the new element is described, there is a "w" parameter that seems to have an important effect on the results. I did not see this parameter in the implemented formulation, was this parameter maybe somehow simplified?

@rubenzorrilla @mrhashemi

**Comment by mrhashemi** [comment]
Please try using a much smaller CFL number (start with 0.1 for example) for the algebraic stabilization. It uses an explicit formulation for higher-order (generally nonlinear) terms and therefore, the time-step should be restricted.

**Comment by ddiezrod** [comment]
> Please try using a much smaller CFL number (start with 0.1 for example) for the algebraic stabilization. It uses an explicit formulation for higher-order (generally nonlinear) terms and therefore, the time-step should be restricted.

OK, I'll try that. Does this mean that in general CFL should be lower than 1? In our problems CFL is usually 10, so if thats the case I guess we just cannot use this formulation.

**Comment by mrhashemi** [comment]
> > Please try using a much smaller CFL number (start with 0.1 for example) for the algebraic stabilization. It uses an explicit formulation for higher-order (generally nonlinear) terms and therefore, the time-step should be restricted.
> 
> OK, I'll try that. Does this mean that in general CFL should be lower than 1? In our problems CFL is usually 10, so if thats the case I guess we just cannot use this formulation.

You can, by using internal substeps. dividing for example each step to 20 or 30 substeps (only for the convection).
Otherwise, you should implement some nonlinear formulation and pay the price (of the computational cost) by doing Newton-Raphson or fixed-point iterations.

**Comment by ddiezrod** [comment]
Ok @mrhashemi , thanks for your answer. I will upload the results using CFL =1 in both cases.

**Comment by mrhashemi** [comment]
> Ok @mrhashemi , thanks for your answer. I will upload the results using CFL =1 in both cases.

- Please first try CFL=0.1 for the case with HO term ("include_anti_diffusivity_terms" : true) and then, increase it (anyway it should be smaller than 1 for this explicit formulation). 

- Use CFL~1 for algebraic stabilization without HO terms ("include_anti_diffusivity_terms" : false).

- For the std. cross-wind stabilized element, using Crank-Nicolson, there is no limitation on CFL.

**Comment by ddiezrod** [comment]
I ran the tests with cfl = 0.95 (using substepping) and the results do not look much better, although instabilities have disappeared.

left (with antidiffusive) right (without)

![image](https://user-images.githubusercontent.com/25667299/144060291-47a1970d-d5b8-43a9-8509-8e0b8737e927.png)

I could not run with cfl = 0.1 (with cfl 1 this is taking already something like 10 h)

**Comment by mrhashemi** [comment]
With the current explicit anti-diffusion terms, it is impossible to use CFL~1. 

Could you please let me know how you calculate h for determining CFL? I assume you let the code do that and if I am not wrong, the code uses an average element size (1/|grad N|). Since the elements are not of equal length at all the edges, setting CFl=0.95 is a little bit tricky.

Let me try it myself and let you know.

**Comment by ddiezrod** [comment]
> With the current explicit anti-diffusion terms, it is impossible to use CFL~1.
> 
> Could you please let me know how you calculate h for determining CFL? I assume you let the code do that and if I am not wrong, the code uses an average element size (1/|grad N|). Since the elements are not of equal length at all the edges, setting CFl=0.95 is a little bit tricky.
> 
> Let me try it myself and let you know.

Yes, Im just letting the code compute its own substeps so CFL = 0.95 is used.

**Comment by mrhashemi** [comment]
@ddiezrod thank you for raising this issue. I did some further tests: despite the promising result of the currently implemented algebraic stabilization with anti-diffusive terms in **2D**, it is still too diffusive in **3D**. The solution is to substitute the average distance gradient with the exact value and make the limiter sharper (increase the power). However, I have not yet completely tested the side effects and cannot implement these modifications.

Just for comparison, these results are obtained without BFECC (CFL is very small):
1- Algebraic stabilization with anti-diffusion terms:
![WithAntiDiff_dt1e-4_noBFECC_theta0-5](https://user-images.githubusercontent.com/56388210/144095711-1dca4e39-d04d-48c4-9d16-0e8cb77c40f6.png)

2- SUPG + CW:
![SUPGCW_dt1e-4_NoBFECC_theta0-5](https://user-images.githubusercontent.com/56388210/144095759-a0eb9c79-c8be-4691-ae19-6c1f9f009292.png)

**Comment by ddiezrod** [comment]
HI @mrhashemi , thanks for your comment. I wouldn't say the mesh is very coarse in my case (about 2.7 M elements) but it still looks very diffusive even using cfl = 0.5. I'm not very familiar with the formulation but I can try to test something if you want. Also, if you are interested. I can send you the test by mail, it seems its too big to upload it here.

**Comment by mrhashemi** [comment]
Hi @ddiezrod
The mesh you use is quite fine :+1:  I think you can reduce the number of elements to ~500K. 
The CFL I used is in the order of 0.1 (counting on h = the shortest edge of the elements). 

If you agree, I can create a draft PR and add a couple of additional setting parameters. Then, it would be easier to run more tests.

**Comment by ddiezrod** [comment]
> Hi @ddiezrod The mesh you use is quite fine 👍 I think you can reduce the number of elements to ~500K. The CFL I used is in the order of 0.1 (counting on h = the shortest edge of the elements).
> 
> If you agree, I can create a draft PR and add a couple of additional setting parameters. Then, it would be easier to run more tests.

That'd be great, thanks!

**Comment by RiccardoRossi** [comment]
news on this? i think it is quite important!

**Comment by mrhashemi** [comment]
> news on this? i think it is quite important!

I'll first make some main settings optional in the convection process (the most important one is the acuteness of the limiter separately for BFECC and for the more accurate algebraically stabilized scheme).
This would not significantly improve the CFL limitation. 
The next step would be to update the gradient (using a first-order scheme, maybe the semi-Lagrangian method).

**Comment by ddiezrod** [comment]
I ran again this test with the latest changes, it looks much better (although I think I also fixed a test in my code that could be important).
Both cases were run with tetha = 0.5, no BFECC and CFL = 0.8. Results with SUPG still look superior to those with algebraic stabilization.
(Left algebraic, right SUPG after a half turn)
![image](https://user-images.githubusercontent.com/25667299/155354057-d83ecd27-3fc5-44c0-b27b-080fbd313cdc.png)

**Comment by mrhashemi** [comment]
> I ran again this test with the latest changes, it looks much better (although I think I also fixed a test in my code that could be important). Both cases were run with tetha = 0.5, no BFECC and CFL = 0.8. Results with SUPG still look superior to those with algebraic stabilization. (Left algebraic, right SUPG after a half turn) ![image](https://user-images.githubusercontent.com/25667299/155354057-d83ecd27-3fc5-44c0-b27b-080fbd313cdc.png)

Is the SUPG result obtained with crosswind stabilization (0.7)? Compared to the first test that you performed with BFECC (posted above), it seems that BFECC worsens the SUPG+CW, which is quite surprising since, in 2D tests, it gives highly diffusive results. Anyway, I do not think there is any further room to improve what you've obtained here for this 3D case. 
What I can suggest is to run and compare the results for the standard 2D Zalesak test (with three shapes).

**Comment by ddiezrod** [comment]
I used CW=0.0. I did a couple of modifications in the test so to compare with bfecc I should run the test ok, I can run them again using bfecc if that info is interesting to you. I could try also the 2D, but we are only interested in 3D resulst at the moment...

**Comment by mrhashemi** [comment]
> I used CW=0.0. I did a couple of modifications in the test so to compare with bfecc I should run the test again, I can run them again using bfecc if that info is interesting to you. I could try also the 2D, but we are only interested in 3D resulst at the moment...

Ok, now, it makes sense. Without CW, the method is not stable. There is a high chance of instabilities with pure SUPG. So, it is better to set it to the default value even though the result for this test seems fine. In case you are focused on 3D cases, maybe I can find a benchmark.

**Comment by ddiezrod** [comment]
I ran again the test using the default value (CW = 0.7) and result is now much better for algebraic stab.
(left algebraic, right supg )

![image](https://user-images.githubusercontent.com/25667299/155491183-9402b970-71f5-48b1-a2c2-2bbe7bc2dc69.png)

I have to say that we normally use cw = 0.0 and I cannot say results are always great, but we do not see instabilities very often., even with high CFLs

**Comment by mrhashemi** [comment]
> I ran again the test using the default value (CW = 0.7) and result is now much better for algebraic stab. (left algebraic, right supg )
> 
> ![image](https://user-images.githubusercontent.com/25667299/155491183-9402b970-71f5-48b1-a2c2-2bbe7bc2dc69.png)
> 
> I have to say that we normally use cw = 0.0 and I cannot say results are always great, but we do not see instabilities very often., even with high CFLs

Maybe I used an incorrect term. With theta=0.5 and pure SUPG you can choose very large CFLs. The problem is with not complying with DMP (it is not monotonic) and the result would be noisy with over/undershoots once a steep gradient occurs.

**Comment by ddiezrod** [comment]
> Maybe I used an incorrect term. With theta=0.5 and pure SUPG you can choose very large CFLs. The problem is with not complying with DMP (it is not monotonic) and the result would be noisy with over/undershoots once a steep gradient occurs.

Got it! Thanks for the all the explanations! Is there any plan for making algebraic stab. work with higher CFLs or you are just interested in low CFLs for the moment?

**Comment by mrhashemi** [comment]
> > Maybe I used an incorrect term. With theta=0.5 and pure SUPG you can choose very large CFLs. The problem is with not complying with DMP (it is not monotonic) and the result would be noisy with over/undershoots once a steep gradient occurs.
> 
> Got it! Thanks for the all the explanations! Is there any plan for making algebraic stab. work with higher CFLs or you are just interested in low CFLs for the moment?

I have not tested the maximum possible CFL. Maybe it works up to CFL~1.5 (or even larger) with theta=0.5. I'd appreciate it if you can test it for this 3D case. There are other approaches (mostly somehow implicit) that might work for large CFLs. At the moment, I have no plan for doing further implementations. The only modification that I will implement (in soon future hopefully) is a modified BFECC algorithm. It is slightly more costly than the current algorithm, but further improves the results.

**Comment by ddiezrod** [comment]
> 

I have tested and at least until CFL = 5 it is working fine. With CFL = 10 you start seeing instabilities. I think we can close this issue for the moment, I think we can consider that algebraic stabilization works fine for low values of CFL, but its not recommended to use in general free surfaces cases due to this limitation. Also, although it might be more unstable in some cases, the supg element with cwd = 0.0 is less diffusive.
