### ISSUE TITLE
about geometry dimension, working space dimesion and local space dimension

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#9369]
**Description**
Recently I had some confusions using the geometry dimensions. As an example, some of the geometries define the following dimensions:

| | Dimension | Working space dimension | Local space dimension |
|----|:---:|:---: |:---:|
| Line3D2              | 3 | 3 | 1 |
| Triangle3D3        | 2 | 3 | 2 |
| Tetrahedra3D4   | 3 | 3 | 3 |
| Line2D2              | 2 | 2 | 1 |
| Triangle2D3        | 2 | 2 | 2 |
| Quadrilateral2D4 | 2 | 2 | 2 |

On the one hand side, there are three dimensions defined. From my point of view, there are only two spaces: the local space and the global/working one. What does mean dimension? On the other hand, how is it possible that the Line3D2 has dimension=3 and the triangle3D3 has dimension=2?

**Comment by loumalouomega** [comment]
This confuses me as well

**Comment by rubenzorrilla** [comment]
I've the feeling that `Dimension` is legacy and what one should trust is `WorkingSpaceDimension` and `LocalSpaceDimension` (what is what we normally do).

**Comment by roigcarlo** [comment]
@KratosMultiphysics/technical-committee We are discussing how to make `Dimension()` consistent. Since this is hardly doable automatically (can't do search and replace), our suggestion is to deprecate `Dimension()` and use `WorkingDimension()` or `LocalDimension()`

**Comment by rubenzorrilla** [comment]
I think that after #10977 the roadmap is completed :tada:
