### ISSUE TITLE
Redefinition of UblasVectorModifier

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#937]
`UblasVectorModifier` is defined in:

vectorial_spaces_python.cpp
add_vector_to_python.cpp

Definitions are equal, and both are being used to compile KratosCore so one has to disappear.

**Comment by roigcarlo** [comment]
Same goes for `UblasSparseVectorModifier`

**Comment by pooyan-dadvand** [comment]
:open_mouth: This will need a cleanup!

**Comment by roigcarlo** [comment]
Just for the record this should be fixed with in #1065, but probably we just need to remove one of the definitions

**Comment by pooyan-dadvand** [comment]
👍

**Comment by roigcarlo** [comment]
Already fixed.
