### ISSUE TITLE
Some quality functions not working properly with non-unitary geometries

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#94]
Creating this issue to track the bug that @pooyan-dadvand found regarding some quality functions (the ones relating magnitudes with different dimensions) not returning normalized results between 0 and 1.

**Comment by loumalouomega** [comment]
What do you mean with quality functions?

**Comment by roigcarlo** [comment]
These are functions to determine whether an element is "good" or not given some criteria.
For example:

```C++
virtual double InradiusToCircumradiusQuality() const {
      constexpr double normFactor = 3.0;

      return normFactor * Inradius() / Circumradius();
    };
```

Which should return values between 0 and 1 (or -1 if the element is inverted) being 0 the worst case and 1 the best. 

I am responsible for these ones @loumalouomega, already working on that. I just created the issue to help it track myself ;)

**Comment by pooyan-dadvand** [comment]
Perfect! I'm just looking forward to have it!
