### ISSUE TITLE
Changing the Normal method behavior

### ISSUE THREAD

**Issue by pooyan-dadvand** [KratosMultiphysics/Kratos#940]
The pull request correcting geometry normal #936 is the first step to change the behavior of Normal method in geometry. In this step the `Normal` changes to `UnitNormal` and defines `AreaNormal` which is not unit length. In a second step the `AreaNormal` will be changed to `Normal`.  This issue is a reminder for the second step.

**Comment by pooyan-dadvand** [comment]
We keep this issue for the next release which is a major release.

**Comment by loumalouomega** [comment]
I will prepare a PR in order to close this issue

**Comment by loumalouomega** [comment]
Done
