### ISSUE TITLE
pyhton.dll cant find

### ISSUE THREAD

**Issue by ciengineerBA** [KratosMultiphysics/Kratos#9421]
**Description**
python dll can' find eror
**Scope**

- Compilation

![image](https://user-images.githubusercontent.com/57172375/144460432-fb4e8f22-0fcf-4fb9-96de-587e1cd4c207.png)

**Comment by roigcarlo** [comment]
Hi @ciengineerBA can you privide some more details about the error.

Did you compile the code yourself, are you trying a release from our webpage or GiD?

**Comment by ciengineerBA** [comment]
Thanks, I edited the environment variables.
