### ISSUE TITLE
How to obtain plastic strain when material properties change?

### ISSUE THREAD

**Issue by XinLiu100** [KratosMultiphysics/Kratos#9432]
I am using the ConstitutiveLawsApplication and StructuralMechanicsApplication in a multistep simulation.

My problem is I need to switch material properties (by setting `elem.Properties`) in different steps, and I need to compute the plastic strain (and elastic strain). I found I can compute the total strain by `elem.CalculateOnIntegrationPoints(KratosMultiphysics.STRAIN,ProcessInfo)`, but when I tried `elem.CalculateOnIntegrationPoints(KratosMultiphysics.ConstitutiveLawsApplication.PLASTIC_STRAIN_VECTOR,ProcessInfo)`, I just got an empty array.

Thank you!

**Comment by loumalouomega** [comment]
Can you try with GREEN_LAGRANGE_STRAIN_VECTOR?

**Comment by XinLiu100** [comment]
> Can you try with GREEN_LAGRANGE_STRAIN_VECTOR?

Yes. I tried `GREEN_LAGRANGE_STRAIN_VECTOR` and it is fine. I guess my problem is I did not setup ProcessInfo correctly. In my problem I need to change some given elements' material properties (including constitutive law from elastic to plastic), I did it by setting `elem.Properties` with another predefined material property, but it seems `CalculateOnIntegrationPoints` still get an elastic element therefore it cannot get the plastic strain. I am not sure if my approach is correct, or I also need to change `ProcessInfo`, or is it possible for Kratos to have a modelpart with different types of material properties assigned on its different elements? Thank you!

**Comment by AlejandroCornejo** [comment]
Hi @XinLiu100 ! In order to get a full vector of `PLASTIC_STRAIN_VECTOR `you should be using a plasticity constitutive law. Are you currently running the case with an elastic or plastic `ConstitutiveLaw`?

**Comment by AlejandroCornejo** [comment]
If you change the material properties without changing the CL it's still an elastic case, which does not know anything about plastic strains.

**Comment by XinLiu100** [comment]
> If you change the material properties without changing the CL it's still an elastic case, which does not know anything about plastic strains.

I guess that is my problem but wonder how do I change CL? Currently what I am doing is like this `elem.Properties = modelpart.GetProperties()[1]` inside `ChangeMaterialProperties`. Thank you!

**Comment by AlejandroCornejo** [comment]
> > If you change the material properties without changing the CL it's still an elastic case, which does not know anything about plastic strains.
> 
> I guess that is my problem but wonder how do I change CL? Currently what I am doing is like this `elem.Properties = modelpart.GetProperties()[1]` inside `ChangeMaterialProperties`. Thank you!

In order to change the `ConstitutiveLaw `(I've never done it) you should do something similar to the `BaseSolidElement::InitializeMaterial()` method for example. 

A simpler way to solve this is: you can start with a plasticity CL (`SmallStrainIsotropicPlasticity3DVonMisesVonMises`) so you'll have the plastic behaviour at any time.

**Comment by XinLiu100** [comment]
> > > If you change the material properties without changing the CL it's still an elastic case, which does not know anything about plastic strains.
> > 
> > 
> > I guess that is my problem but wonder how do I change CL? Currently what I am doing is like this `elem.Properties = modelpart.GetProperties()[1]` inside `ChangeMaterialProperties`. Thank you!
> 
> In order to change the `ConstitutiveLaw `(I've never done it) you should do something similar to the `BaseSolidElement::InitializeMaterial()` method for example.
> 
> A simpler way to solve this is: you can start with a plasticity CL (`SmallStrainIsotropicPlasticity3DVonMisesVonMises`) so you'll have the plastic behaviour at any time.

Thank you! I will try it
