### ISSUE TITLE
How to SetValue of INITIAL_STRAIN_VECTOR inside CL?

### ISSUE THREAD

**Issue by XinLiu100** [KratosMultiphysics/Kratos#9437]
I am implementing this #9049 but found a problem how to use `SetValue` of a CL
my code is like:
```
_tmp_init_strain = [1e-4,0,0,0,0,0]
cl = elem.Properties.GetValue(KratosMultiphysics.CONSTITUTIVE_LAW)
cl.SetValue(KratosMultiphysics.INITIAL_STRAIN_VECTOR,_tmp_init_strain,ProcessInfo)
elem.Properties.SetValue(KratosMultiphysics.CONSTITUTIVE_LAW,cl)
```
But the `cl.SetValue` will go to the virtual function inside [kratos/sources/constitutive_law.cpp](https://github.com/KratosMultiphysics/Kratos/blob/75e572f9d6cc933b541afb704b9c64398e166185/kratos/sources/constitutive_law.cpp) with an error message ("RuntimeError: Error: Called the virtual function for SetValue"). Since I am using SmallStrainIsotropicPlasticityFactory, I guess I need to go "ConstitutiveLawsApplication\custom_constitutive\small_strain_isotropic_plasticity_factory.cpp" and "ConstitutiveLawsApplication\custom_constitutive\small_strain_isotropic_plasticity_factory.h" and define `SetValue` there, but after that  I still got the same error message.

My implementation is like this:

```
void SmallStrainIsotropicPlasticityFactory::SetValue(
    const Variable<Vector>& rThisVariable,
    const Vector& rValue,
    const ProcessInfo& rCurrentProcessInfo
    )
{
    if (rThisVariable == PLASTIC_STRAIN_VECTOR) {
        mPlasticStrain = rValue;
    } 
}
```

Thank you in advance!

**Comment by AlejandroCornejo** [comment]
Hi! In order to apply an initial strain we implemented an straight forward implementation. You can check this PR https://github.com/KratosMultiphysics/Kratos/pull/7663 in order to see how can be used. Basically is adding a block into the ProjectParameters.json. 
You can find more info in the wiki: https://github.com/KratosMultiphysics/Kratos/wiki/%5BKratosStructuralMechanicsAPI%5D-Constitutive-laws-in-Structural-Mechanics-Application

**Comment by AlejandroCornejo** [comment]
If you use the elastic, isotropic plastic or isotropic damage should work, I have not yet added this capability to all the CL's...

**Comment by XinLiu100** [comment]
> If you use the elastic, isotropic plastic or isotropic damage should work, I have not yet added this capability to all the CL's...

Thank

> Hi! In order to apply an initial strain we performed an straight forward implementation. You can check this PR #7663 in order to see how can be used. Basically is adding a block into the ProjectParameters.json. You can find more info in the wiki: https://github.com/KratosMultiphysics/Kratos/wiki/%5BKratosStructuralMechanicsAPI%5D-Constitutive-laws-in-Structural-Mechanics-Application

Thank you! I have checked that PR but my problem is different. I think in that PR you can set initial_strain for different elements by json and they will be kept same thoughout simulation, or set a same initial_strain for every element by set_initial_state_process and you can change them every step, but my problem is I need both, in other words, I need to each element has different initial_strain and being updated each step, therefore I guess I must change the initial_strain inside each FE's CL

**Comment by AlejandroCornejo** [comment]
With the current implementation you can do what you explained. You can set an individual `INITIAL_STRAIN_VECTOR `by doing a `elem.SetValue(INITIAL_STRAIN_VECTOR , VectorOfInitialStrain)` just before calling the s`et_initial_state_process.py`. If you check the code, if the `element.Has(INITIAL_STRAIN_VECTOR )` is true it will set this value and not the imposed default standard one.

**Comment by XinLiu100** [comment]
> With the current implementation you can do what you explained. You can set an individual `INITIAL_STRAIN_VECTOR `by doing a `elem.SetValue(INITIAL_STRAIN_VECTOR , VectorOfInitialStrain)` just before calling the s`et_initial_state_process.py`. If you check the code, if the `element.Has(INITIAL_STRAIN_VECTOR )` is true it will set this value and not the imposed default standard one.

Just want to make sure how do you use `set_initial_state_process.py` here? I used it like this `SetInitialStateProcess(self.model,default_parameters)` and `default_parameters` is basically a blank file with no initial strain defined insidem, but it seems the initial_strain is always set with or without it. Also, it seems I must have put a `set_initial_state_process` block (with zero initial strain defined) inside json file to enable the initial strain defined by `elem.SetValue`. I just feel I did not do it right but I don't know why..

**Comment by AlejandroCornejo** [comment]
The standard way of using this process is by adding the process block inside the `ProjectParameters.json` file. I mention @marandra , he is using intensively this capability.

**Comment by AlejandroCornejo** [comment]
Is this issue solved?

**Comment by XinLiu100** [comment]
> Is this issue solved?

Sorry I forgot to close it. Yes I guess I get it solved. Thank you!
