### ISSUE TITLE
MPCs build time

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#9443]
**Description**
Right now the build time of our B&S doesn't take into account the MPCs application. We should either include this into the build time or stream it to the console separately.

**Comment by loumalouomega** [comment]
Are you sure?, I am sure I added some time ago

**Comment by loumalouomega** [comment]
> Are you sure?, I am sure I added some time ago

I call the timer, but i do not print the elapsed time, solved
