### ISSUE TITLE
[Core][Geometries] Should I move the oriented bounding box class (OBB) to geometries?

### ISSUE THREAD

**Issue by loumalouomega** [KratosMultiphysics/Kratos#9445]
**Description**
@pooyan-dadvand created a bounding box geometry class some months after I created the oriented bounding box class, which is not a geometry class. Should I move the class to geometries to consistency?, maybe a refactor should be done to adapt it to the OBB requirements

Discussion started in #9423

FYI @miguelmaso 

**NOTE:**
https://github.com/KratosMultiphysics/Kratos/commits/master/kratos/includes/oriented_bounding_box.h

I renamed (before it was obb.h) in February 2019.

https://github.com/KratosMultiphysics/Kratos/commits/master/kratos/geometries/bounding_box.h

This is from December 2019.

**Comment by pooyan-dadvand** [comment]
I think driving the boundingbox and OBB from geometry at this moment would reduce its lightweight nature and won't give any benefit. But moving it to the geometries folders would be better.

**Comment by loumalouomega** [comment]
Okay, I will move to geometries, yet not derive from it (makes sense in order to keep it light)
