### ISSUE TITLE
[All] Addition of GetDofsList to Python solvers

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#9462]
**Description**
So far all our Python solvers feature the `AddDofs` function, which is intended to set a collection of variables as DOFs in all the mesh nodes. This collection of variables is hardcoded and can be only known at the solver level, since this is the first layer in which we have access to the full model part (note that we might be mixing elements with different DOFs).

Having said this, I propose adding a method `GetDofList` (and, potentially, a `GetDofWithReactionList`). The idea of this method would be to return a list containing all the variables to be added as DOFs. Then, we'll call this method in the `AddDofs` function prior to the DOFs addition.

The advantages of this would be
1. Right now we normally add the DOFs with the `VariablesUtils.AddDof`. This requires looping all the nodes per each DOF. If we have such list we could create a new method in the `VariablesUtils` to add all the DOFs at once without the need of looping the mesh for each DOF.
2. In the `RomApplication`, this would make possible to automate the selection of the DOFs in a unified ROM solver by calling this new method. Right now we have a derived solver for each physics just because of this.

**Comment by loumalouomega** [comment]
Just two things:

1- 👍🏻 
2- VariablesUtils is not static, is VariablesUtils() (this is just a passive-aggressive way to protest about the not statism of VariablesUtils)

**Comment by philbucher** [comment]
I fully agree with the reasoning, but I don't think this can be easily implemented
=> #5091

What would probably work is to pass a list of strings with the var names to Cpp and then retrieve the corresponding vars before looping, similarly to what is done here:
https://github.com/KratosMultiphysics/Kratos/blob/ccd71b723e097c8760fb848abeb4747a9eeb4441/kratos/processes/from_json_check_result_process.cpp#L228-L238

**Comment by rubenzorrilla** [comment]
> 

Yes. This was my plan. Indeed, this is what we're actually doing in the convection-diffusion solver.

**Comment by loumalouomega** [comment]
> **Description** So far all our Python solvers feature the `AddDofs` function, which is intended to set a collection of variables as DOFs in all the mesh nodes. This collection of variables is hardcoded and can be only known at the solver level, since this is the first layer in which we have access to the full model part (note that we might be mixing elements with different DOFs).
> 
> Having said this, I propose adding a method `GetDofList` (and, potentially, a `GetDofWithReactionList`). The idea of this method would be to return a list containing all the variables to be added as DOFs. Then, we'll call this method in the `AddDofs` function prior to the DOFs addition.
> 
> The advantages of this would be
> 
>     1. Right now we normally add the DOFs with the `VariablesUtils.AddDof`. This requires looping all the nodes per each DOF. If we have such list we could create a new method in the `VariablesUtils` to add all the DOFs at once without the need of looping the mesh for each DOF.
> 
>     2. In the `RomApplication`, this would make possible to automate the selection of the DOFs in a unified ROM solver by calling this new method. Right now we have a derived solver for each physics just because of this.

In addition, we still have to fully implement the GetSpecifications() methods, and use them in the solvers!

**Comment by rubenzorrilla** [comment]
> > **Description** So far all our Python solvers feature the `AddDofs` function, which is intended to set a collection of variables as DOFs in all the mesh nodes. This collection of variables is hardcoded and can be only known at the solver level, since this is the first layer in which we have access to the full model part (note that we might be mixing elements with different DOFs).
> > Having said this, I propose adding a method `GetDofList` (and, potentially, a `GetDofWithReactionList`). The idea of this method would be to return a list containing all the variables to be added as DOFs. Then, we'll call this method in the `AddDofs` function prior to the DOFs addition.
> > The advantages of this would be
> > ```
> > 1. Right now we normally add the DOFs with the `VariablesUtils.AddDof`. This requires looping all the nodes per each DOF. If we have such list we could create a new method in the `VariablesUtils` to add all the DOFs at once without the need of looping the mesh for each DOF.
> > 
> > 2. In the `RomApplication`, this would make possible to automate the selection of the DOFs in a unified ROM solver by calling this new method. Right now we have a derived solver for each physics just because of this.
> > ```
> 
> In addition, we still have to fully implement the GetSpecifications() methods, and use them in the solvers!

This was my first option, the point is that `GetSpecifications` will not work for the elements that use the `CONVECTION_DIFFUSION_SETTINGS` container :disappointed: ...

**Comment by philbucher** [comment]
this is done no?
