### ISSUE TITLE
Compiler and linker error when following one of the Kratos Wiki tutorials

### ISSUE THREAD

**Issue by AlexGreybeard** [KratosMultiphysics/Kratos#9476]
**Description**
I am a new Kratos user and have therefore started with the tutorials on the wiki. However, by following the tutorial Kratos for Dummies (https://github.com/KratosMultiphysics/Kratos/wiki/Kratos-For-Dummies:-Stationary-heat-transfer) I encountered both compiler and linker errors. 
If one follows the tutorial and uses the adapted Python script "laplacian_application_example.py", the following errors occur: 

- First a compiler error that can be fixed by adding " includes/variables.h" at the beginning of the file "custom_conditions/point_source_condition.cpp".
- This is followed by a Python side linker error which can be fixed by replacing the line "KRATOS_DEFINE_VARIABLE( double, POINT_HEAT_SOURCE )" in "my_laplacian_application_variables.h" with the following "KRATOS_DEFINE_APPLICATION_VARIABLE( MY_LAPLACIAN_APPLICATION, double, POINT_HEAT_SOURCE )".

Thanks to the help of Mr. Celigueta, these problems were identified and fixed. It seems that both the above tutorial and the Python script are no longer up to date. The use of the macro "MY_LAPLACIAN_APPLICATION" and therefore, the new command "KRATOS_DEFINE_APPLICATION_VARIABLE" is already considered in the CMakeList file but not by the Python script which creates new applications.

**Scope**
- Compilation
- Linking
- Python
- KratosCore

**Environment**
- OS: Windows 10 Pro
- Branch: master
- Python 3.9

**Comment by rubenzorrilla** [comment]
@AlexGreybeard thanks for reporting. Pinging @roigcarlo as he is the one that really knows how the application generator internally works.

**Comment by roigcarlo** [comment]
Hi @AlexGreybeard thx for reporting, I will fixit asap.

**Comment by SeiDPierre** [comment]
I've just encountered the same issue. The fix works nicely! Thanks

**Comment by rubenzorrilla** [comment]
Closing as it seems to be fixed.
