### ISSUE TITLE
MathUtils::InvertMatrix throws an error if the matrix is not invertible

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#9500]
**Description**
Currently, `MathUtils::InvertMatrix` throws an error if the matrix is not invertible. Since I'm using this function in an iterative procedure, the `KRATOS_ERROR` is stopping the iterations. More or less I'm doing the following:
```c++
Matrix A(6,6); // this is 2D, size is 10 in a 3D case
Matrix invA(6,6);
bool is_invertible = false;
while (!is_invertible) {
    // do something and compute A
    double detA;
    is_invertible = MathUtils<double>::InvertMatrix(A, invA, detA);
    if (!is_invertible){
        // modify the topology
    }
}
```
Fortunately, the system is very simple and usually it is possible to get an invertible A.
For robustness I'm asking to change the error into a warning. Further, It would be useful to return a value indicating if the inverse is successful.

**Comment by ddiezrod** [comment]
I think you can already do now what you want. If you pass a negative value as the fourth argument to InvertMatrix, it will not check the condition number, so no error is thrown. If you want to have a warning. you can call later `MathUtils::CheckConditionNumber` using ThrowError=false which will return false if the condition number is too high (matrix not invertible) and true otherwise.

**Comment by loumalouomega** [comment]
You can change the ZeroTolerance to a large number:

https://github.com/KratosMultiphysics/Kratos/blob/260a6b4193f18a4f201d2f20478cb3facb91f12c/kratos/utilities/math_utils.h#L400

If you don't want to think about a big number, just use the STL maximum: https://en.cppreference.com/w/cpp/types/numeric_limits/max

**Comment by miguelmaso** [comment]
> I think you can already do now what you want. If you pass a negative value as the fourth argument to InvertMatrix, it will not check the condition number, so no error is thrown. If you want to have a warning. you can call later `MathUtils::CheckConditionNumber` using ThrowError=false which will return false if the condition number is too high (matrix not invertible) and true otherwise.

Thanks @ddiezrod !
