### ISSUE TITLE
Add Workflow to create and test wheels based on the current master

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#9508]
**Description**
Currently the wheels are not tested before uploading to PyPi (see #9506). 
I suggest to add a workflow that builds Kratos as wheel instead of the "standard" build, and runs the tests by installing the local Kratos wheels using `pip`. 

Doing this for **one** python version and **one** operating system would already catch most of the potentially occurring errors. Also this should not be too difficult to implement. 

The reason i suggest to build based on latest master instead of using the uploaded packages from PyPi is that otherwise an update of the test cases on the master branch would break the test if the wheels are simply downloaded from PyPi.

At the same time, this would also "test" the whole wheel creation process.

**Comment by roigcarlo** [comment]
Hi @armingeiser, currently the resources that we need to generate the wheels cannot be satisfied with the machines available from github CI. We have a dedicated server which basically mimics the behavior of the CI and creates and uses the wheels for testing before releasing,

I will study if we can integrate it in the github workflows to use that machine in the wheel build, but direct integration through github machines is unlikely to happen for now.
