### ISSUE TITLE
[Wheels] Some App README files are missing for wheel creation

### ISSUE THREAD

**Issue by armingeiser** [KratosMultiphysics/Kratos#9518]
Some Apps do not have a README that is required by the wheels build:

```
"KratosEigenSolversApplication==${KRATOS_VERSION}",
"KratosConstitutiveLawsApplication==${KRATOS_VERSION}",
"KratosDemStructuresCouplingApplication==${KRATOS_VERSION}",
"KratosCSharpWrapperApplication==${KRATOS_VERSION}",
"KratosRANSApplication==${KRATOS_VERSION}",
"KratosCompressiblePotentialFlowApplication==${KRATOS_VERSION}",
"KratosIgaApplication==${KRATOS_VERSION}",
"KratosChimeraApplication==${KRATOS_VERSION}",
"KratosRomApplication==${KRATOS_VERSION}"
```
In #9509 a workarround to skip the requirement of a README was added.

**Comment by roigcarlo** [comment]
Hi @armingeiser. What was the workaround?. The lack of README should not disable the creation of the wheels, just fill it with a empty description. anyway all apps should have a README :)

**Comment by armingeiser** [comment]
https://github.com/KratosMultiphysics/Kratos/pull/9509/files#diff-b109aea96c59956c443054eb261a36d8983930f7830b3f66175992f46c745b11R19-R24

I check if there is a README file, if not i add a standard text instead: `"Readme file not found"` - this could prob. be improved

**Comment by roigcarlo** [comment]
A Ok!
