### ISSUE TITLE
DEM- MPM coupling

### ISSUE THREAD

**Issue by akhilkmat** [KratosMultiphysics/Kratos#9521]
Hi,
I am Akhil Mathews, started my PhD at University of Edinburgh oct 2021, working for an EU project - tusail.eu
Wanted to get in touch with people working on DEM-MPM coupling for granular materials on Kratos; ( my project - https://tusail.eu/projects/esr-11.html ) I was just getting started with the project; If anyone is working on similar field, can you please let me know? Any help would be greatly appreciated.

Kind Regards,
Akhil Mathews

**Comment by philbucher** [comment]
Hi Akhil,
As already discussed via mail, I am CCing my colleagues that work on this or similar topics
@VeronikaSinger @KlausBSautter 
Cheers,
Philipp

**Comment by rubenzorrilla** [comment]
@maceligueta and @salvalatorre  have worked a lot on DEM simulation of granular materials.

**Comment by RiccardoRossi** [comment]
adding Antonia Larese to the cc list

**Comment by philbucher** [comment]
@antonialarese
