### ISSUE TITLE
Discrepancy in the definition of variational redistance coefficients.

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#9534]
**Description**
Long time ago, @pablobecker did some tests with the variational redistance for our Molding solution in Altair. The problem they had is that this redistance was not very robust for them and in some cases it could completely ruin the case. The conclusion of these tests was that it was better to modify some of the coefficients that control the loads in the redistance, making it more robust but at the same time slower, needing more iterations to converge.
These are the differences that were introduced at that moment.
![image](https://user-images.githubusercontent.com/25667299/149331928-e2104397-69f9-4ab7-b947-28efacf8c59a.png)
https://github.com/KratosMultiphysics/Kratos/blob/dd7ee6320f8185188856331fb0ad21ba2d289884/kratos/elements/distance_calculation_element_simplex.h#L262

We've lived with this difference from github core for all this time, but it is a nightmare for maintenance, as many tests have slightly different results. We understand that you might prefer to maintain the current values even if solution is less robust. (At the end its quite hard to justify any value very rigorously)

I discussed this with @pooyan-dadvand and @jrubiogonzalez also and we though that maybe we could introduce this coefficients from element properties or from process info, so everybody can choose the coefficients that better work for them. What do you think @KratosMultiphysics/technical-committee ? @RiccardoRossi @rubenzorrilla @philbucher

**Comment by philbucher** [comment]
Without having any clue abt the physics behind, this seems like a candidate for ProcessInfo (is it always the same within a ModelPart) or Properties (can it be different)

In any case this seems to be a „magic number“ so makes sense to have it variable

In StructuralMechanics we use sth similar for the damping coefficients, can look for it if it is interesting

**Comment by rubenzorrilla** [comment]
Makes sense for me . As suggested by @philbucher this is should be in the `ProcessInfo`. For the moment we can add it to the solver defaults so we don't need to update the tests results. In the future we can change it to more robust values.

**Comment by pooyan-dadvand** [comment]
Usually, it is constant during the calculation for this reason we thought `ProcessInfo` is not the best choice. But it is true that the solver knows this magic number rather than the users.

**Comment by RiccardoRossi** [comment]
well, are we sure that the magic numbers suggested by Pablo aren't better than the ones we use? because i am not :-D

**Comment by pablobecker** [comment]
no, the ones i proposed make the convergence extremely slow, so you'd need lots of iterations to get somehting that resembles a distantance (with gradient=1). This modification reduces the change rate, meant for those complex/horrible meshes in which the variational redistance would crash, therefore limiting the damage to the solution as long as you don't let it iterate to death.

@ddiezrod was working on a new redistance based on a strategy we were using at altair for another problem. Cannot find it now though

**Comment by ddiezrod** [comment]
> well, are we sure that the magic numbers suggested by Pablo aren't better than the ones we use? because i am not :-D

I have my doubts actually. both options can be reasonable, but in altair we need to stay on the "robustness" side. Thats why I think its ok to be able to modify these coefficients.

**Comment by RiccardoRossi** [comment]
ok to me

**Comment by ddiezrod** [comment]
closed in #9535
