### ISSUE TITLE
Inconsistent ModelPart.GetProperties

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#9538]
**Description**

I've observed the following discrepancy in the `ModelPart` interface:
- From the c++ interface, ModelPart.GetProperties(id) returns the property with the corresponding id from the mesh 0 (default value)
- From the python interface, ModelPart.GetProperties(id) returns all the properties from the mesh with the corresponding id.

**Comment by loumalouomega** [comment]
I opened a discussion about this in the past, and I don't remember why we keep it (I think because it would break to much code)

**Comment by miguelmaso** [comment]
## Recap

<table>
    <thead>
        <tr>
            <th></th>
            <th>item</th>
            <th>container</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td rowspan=4>Value</td>
            <td>Node</td>
            <td>Nodes</td>
        </tr>
        <tr>
            <td>Element</td>
            <td>Elements</td>
        </tr>
        <tr>
            <td>Condition</td>
            <td>Conditions</td>
        </tr>
        <tr>
            <td>Properties</td>
            <td>Properties</td>
        </tr>
        <tr>
            <td>Methods</td>
            <td>CreateNew(item) <br/> Has(item) <br/> Get(item) <br/> Add(item) <br/> Remove(item)</td>
            <td>(container) <br/> Set(container)</td>
        </tr>
    </tbody>
</table>

- `Properties` means the item and also the container.
- The Python interface adds `Get(container)`. In general, this is not a problem, but it conflicts in the case of the properties. Consequently, there are multiple definitions of `GetProperties` in Python, returning the container or the item.
- Furthermore, the properties Id may be confused with the mesh Id (legacy).

## My proposal

1. Remove the mesh Id from the python interface. This is a behavior change.
```
- GetProperties(mesh_id) -> Container
+ GetProperties(prop_id) -> Item
```
2. Remove the `GetProperties()` (container), which can be confused with `GetProperties(id)` (item). This is an API breaker.

**Comment by miguelmaso** [comment]
In @KratosMultiphysics/implementation-committee we prefer to remove only the mesh id (option 1)
