### ISSUE TITLE
Adding a method to DataValueContainer for looping

### ISSUE THREAD

**Issue by msandre** [KratosMultiphysics/Kratos#956]
At the moment it seems there is no way to iterate over contents of a data value container. The motivation for such an interface is to save properties when writing the model part (not using serialization). I would like to propose adding a function pGetVariableData() that could be used in the following code,

```
DataValueContainer& r_data = prop.Data();
for (unsigned i=0; i < r_data.size(); ++i)
    const VariableData* p_var = r_data.pGetVariableData(i);
    ...
```

Is this ok or is there a better way for doing this?

Thanks

**Comment by pooyan-dadvand** [comment]
Actually the way you are doing would work but I understand that you don't want to expose so much the internal data array. A better solution would be to add `begin` and `end` methods to the container.

**Comment by msandre** [comment]
thanks, I'll do that instead.
