### ISSUE TITLE
The function "Dimension" of the geometry should be removed

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#9564]
**Description**
my point is that the meaning of Dimension for a geometry is not clear ... one should use instead WorkingSpaceDimension or LocalSpaceDimension

it is used in relatively few places so the option of removing "Dimension" exists

**Comment by marcnunezc** [comment]
Related to #9369

**Comment by rubenzorrilla** [comment]
Indeed, this is redundant to #9369. Closing this one as the current behavior is better documented in there.
