### ISSUE TITLE
Undefined behaviour in test_logger.cpp

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/Kratos#9570]
**Description**
PR #9565 introduces undefined behaviour:
https://github.com/KratosMultiphysics/Kratos/blob/a6e526f42dfdd6d312a5e5f35152be615e93ffc9/kratos/tests/cpp_tests/input_output/test_logger.cpp#L20-L27

As per the C++11 standard:
> 17.6.4.3.2 Global names [global.names]
> 1 Certain sets of names and function signatures are always reserved to the implementation:
> — Each name that contains a double underscore _ _ or begins with an underscore followed by an uppercase letter (2.12) is reserved to the implementation for any use.
> — Each name that begins with an underscore is reserved to the implementation for use as a name in the global namespace.

The relevant part here is that variables cannot start with a leading underscore followed by an uppercase letter, else risking name colisions with the compiler, standard library, etc.

As silly as it seems, I'd avoid such risks and give these variables standard-adhering names.

I personally don't know how the logger works so I prefered not to change it myself.

**Scope**
Where in Kratos is this bug happening. 
- KratosCore

**To Reproduce**
It's undefined behaviour so who knows.

**Expected behavior**
Code should adhere to the standard.

**Environment**
- Branch: master

**Comment by armingeiser** [comment]
Oh sorry seems i was too fast merging #9565...

**Comment by armingeiser** [comment]
@EduardGomezEscandell out of interest: how did you notice? just by chance or is there a compiler warning that i have not seen?

**Comment by EduardGomezEscandell** [comment]
Pure chance, I was interested to see what the logger looked like and I saw these variable names.

I just tried with all compiler warnings I know (`-Wall -Wextra -Wpedantic`) and none reported this issue.

**Comment by armingeiser** [comment]
Good catch than, i was not aware of this- thanks!
