### ISSUE TITLE
Duplicated code in shell elements

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#958]
While playing with some techniques to accelerate compile times I've detected that there is code duplication in these files:

- `shell_thin_element_3D3N.cpp`
- `shell_thick_element_3D3N.cpp`

- `shell_thin_element_3D4N.cpp`
- `shell_thick_element_3D4N.cpp`

Specifically, the functions under the Kratos::Utilities namespaces are defined twice (each in each pair of files).

For example:
```C++
inline void ShapeFunc(double xi, double eta, TVec & N)
{
	N(0) = 0.25 * (1.0 - xi) * (1.0 - eta); // node 1
	N(1) = 0.25 * (1.0 + xi) * (1.0 - eta); // node 2
	N(2) = 0.25 * (1.0 + xi) * (1.0 + eta); // node 3
	N(3) = 0.25 * (1.0 - xi) * (1.0 + eta); // node 4
}
```
Is defined twice.

This doesn't cause any compile error as they belong to two different compile units, but could potentially cause code problems. For instance, if these are used outside the \*.so / \*.dll it will throw an inconsistent DLL linkage, or simply not link due to a "multiple definition of ShapeFunc" error.

My proposal would be to create an utility file so the common code can exist there.

What do you think?

**Comment by roigcarlo** [comment]
Edit: I've changed from bug to enhancement as it is not really a bug if you want to use it locally only.

**Comment by philbucher** [comment]
There is a lot more code duplication in the shells
I have started removing it (by creating a utility class) in a different branch, but it is ok hold until after the release

**Comment by roigcarlo** [comment]
Great! thx @philbucher,

Closing this then
