### ISSUE TITLE
[Constitutive Laws] Use the constitutive laws for non-FEM applications and zero-thickness cracks

### ISSUE THREAD

**Issue by maceligueta** [KratosMultiphysics/Kratos#9607]
**Description**
We are currently exploring the possibility to call the existing constitutive laws from a DEM code. The idea is to provide a strain tensor and get the stress tensor in return. We are aiming to simple damage laws as a first step.
The problem is that, in DEM, we want to detect the damage of a surface (no thickness) separating two particles, however, the constitutive law asks for an element geometry here:
https://github.com/KratosMultiphysics/Kratos/blob/41a0ed173b320d0586c3170b186a13bc3175b73e/applications/ConstitutiveLawsApplication/custom_constitutive/generic_small_strain_isotropic_damage.cpp#L129
we understand that finite elements always have thickness, but it would be awesome if other disciplines could use these constitutive laws as a black box.
Maybe I am not looking at the right file. Any advice? @AlejandroCornejo 
This zero thickness interface between particles seems similar to the joint elements used by @ipouplana . Any help is welcome.
We could also use an artificial thickness, too, but the constitutive law should be able to accept it as an iput.
Thanks

**Comment by RiccardoRossi** [comment]
when you have damage, you have softening and hence you require a characteristic length to do regularization . This is needed to ensure that the amount of energy dissipated is (largely) independent on the mesh size.

In any case this CL is strain based. If you have a zero thickness element you will have a displacement jump which you will need to transform into a strain by dividing by a characteristic length (unless you use a displacement-junmp relation). How do you plan dealing with this?

**Comment by maceligueta** [comment]
If the CL is strain based, great, because I have the strain tensor, obtained with a non-local estimation. However, my plan is to create a crack with no thicknes, with a known surface. I was planning to estimate the damage as the portion of this surface which is no longer contributing.
In any case: I can estimate a characteristic length if that is mandatory, but it seems that the code does not accept a length as an input, currently. The CL asks for a geometry.

**Comment by AlejandroCornejo** [comment]
Yes it asks a geometry to be able to compute a characteristic length. You could create a dummy ad-hoc geometry to circumvent this. We also can generalize the CL so if you set it as a material property it can read it.

**Comment by ipouplana** [comment]
Just so that you know it, the CL that I use for the zero-thickness interface elements is a standard Kratos CL. However, its input is a vector with the relative displacements between the two faces expressed in the local coordinate system of the interface (delta_u_tangential_1,delta_u_tangential_2,delta_u_normal).

**Comment by maceligueta** [comment]
@AlejandroCornejo I was thinking that, if the CL is generalized to accept a carachteristic length, maybe it should read it from the CL Parameters, better than the properties, as this caracteristic length can changes from element to element.

**Comment by loumalouomega** [comment]
> @AlejandroCornejo I was thinking that, if the CL is generalized to accept a carachteristic length, maybe it should read it from the CL Parameters, better than the properties, as this caracteristic length can changes from element to element.

That's a smart take

**Comment by AlejandroCornejo** [comment]
hmm ok! In that case we need to add a `double` and a way to check if has been changed or not (`IsSet()`). We can do it but I'd want to know @RiccardoRossi oppinion regarding the added cost and/or inconveniences.
