### ISSUE TITLE
Kratos currently not compiling under Windows

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#961]
Hi all

We noticed that currently Kratos is not compiling under Windows giving the following error output:

"typename cannot be used outside a template declaration"

The problem may be fixed by replacing "typedef typename" with only "typedef" in the following files:

1) modified_shape_functions.h
2) triangle_2d_3_modified_shape_functions.h
3) divide_geometry.h
4) divide_triangle_2d_3.h

Can somebody confirm this error?

Thanks a lot and best regards
Daniel

**Comment by rubenzorrilla** [comment]
@dbaumgaertner my bad... Thanks and sorry for the inconveniences. I'll do a PR ASAP to fix it.

**Comment by dbaumgaertner** [comment]
@rubenzorrilla Great! Thanks for this very quick reaction.

**Comment by rubenzorrilla** [comment]
Should be fixed with changes in #962.
