### ISSUE TITLE
DEM-PFEM example not working

### ISSUE THREAD

**Issue by akhilkmat** [KratosMultiphysics/Kratos#9617]
Can't get the DEM-PFEM example to work. I have attached an image of the error. ( Quite new to Kratos ). The error happens while doing Kratos-> Write calculation Files-No run. 

Ps: I am looking for a working coupled DEM-Continuum(FEM/MPM/PFEM) example.

Thanks in advance,
Akhil

![error](https://user-images.githubusercontent.com/69186170/152772125-68b4bab2-3a25-4f2d-9177-cd8db93c22ec.png)

**Comment by jgonzalezusua** [comment]
Hi @akhilkmat, I do not know if someone is in charge of DEM-PFEM coupling but, if you are looking for DEM-Cootinuum example, Fluid-DEM couples DEM with FEM and it is working.

**Comment by AlejandroCornejo** [comment]
@AFranci
