### ISSUE TITLE
One more reason for which we need c++17

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#9622]
**Description**
I have been recently working on exposing to python the distributed sparse matrices we have in Kratos.

I wanted to enable the SpMV to be called from the python layer as

y = A@x

where y and x are distributed vectors.
this is not possible as of now since the copy constructor of the distributed vectors is explicit. In debug mode c++11 calls such constructor as copy elision on return is not guaranteed. This makes impossible to implement the @ operator as we may always have a copy on return. C++17 would guarantee that the copy elision happens (even in debug) thus removing this problem

**Comment by rubenzorrilla** [comment]
Aligned to #6611 discussion

**Comment by loumalouomega** [comment]
+ constexpr
+ STL true parallel
+ auto everywhere
+ ...

**Comment by loumalouomega** [comment]
The limit of C++17 was a specific compiler from a specific system?

**Comment by loumalouomega** [comment]
> The limit of C++17 was a specific compiler from a specific system?

Because I can propose a solution...

**Comment by philbucher** [comment]
check #9626

**Comment by RiccardoRossi** [comment]
the problem is that firms using Kratos are forced to distribute code that runs on very old systems (RHEL7) for example, and there it apparently it is not easy to have support for sufficiently new compilers

**Comment by loumalouomega** [comment]
> the problem is that firms using Kratos are forced to distribute code that runs on very old systems (RHEL7) for example, and there it apparently it is not easy to have support for sufficiently new compilers

I have experience using Clang9 in old machines and linking with the STL libraries provided by Clang itself.

**Comment by RiccardoRossi** [comment]
@pooyan-dadvand this is just so that you take a look to this thread
