### ISSUE TITLE
nightly build failing

### ISSUE THREAD

**Issue by RiccardoRossi** [KratosMultiphysics/Kratos#9628]
**Description**
@all nightly build is failing since several days. What is going on? 

**TODO**

**Comment by rubenzorrilla** [comment]
The mass conservation tests are failing. Results are updated in here #9592.

**Comment by marcnunezc** [comment]
Is there much work left to do in #9592? Just saying that we might want to consider setting the failing tests as "Expected failures" while this PR is under development so that the nightly build does not fail.

**Comment by rubenzorrilla** [comment]
> Is there much work left to do in #9592? Just saying that we might want to consider setting the failing tests as "Expected failures" while this PR is under development so that the nightly build does not fail.

Make sense for me. Please go ahead.
