### ISSUE TITLE
[Core][Analysis Stage] FinalizeSolutionStep and OutputSolutionStep order

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#9653]
**Description**
Right now, the order of our run solution loop is the following 
https://github.com/KratosMultiphysics/Kratos/blob/ad314460bf1e24f549e6f1962886db9d6f181d0f/kratos/python_scripts/analysis_stage.py#L57-L68

As you can observe, we first do the `FinalizeSolutionStep` operations to then call the `OutputSolutionStep`, which calls the `ExecuteBeforeOutputStep` and `ExecuteAfterOutputStep`. I wonder if we should modify the current `RunSolutionLoop` to call the `OutputSolutionStep` prior to the `FinalizeSolutionStep`. The rationale is that some output preprocessing/postprocessing operations performed in  `ExecuteBeforeOutputStep` and `ExecuteAfterOutputStep` might depend on the fixity, which we deliberately reset in the `FinalizeSolutionStep` (e.g. the HROM projection to auxiliary meshes).

**Comment by ddiezrod** [comment]
Hmm, I think the current order actually makes more sense. Many of the post-process results are computed in FinalizeSolutionStep, so inverting the order will lead to wrong results in output.

**Comment by rubenzorrilla** [comment]
> Hmm, I think the current order actually makes more sense. Many of the post-process results are computed in FinalizeSolutionStep, so inverting the order will lead to wrong results in output.

The point is that post-process results must be computed in `ExecuteBeforeOutputStep`. This is what this method is intended for on top of the fact that the outputting methods take into account if this is an output step or not (note that some postprocessing operations might be computationally expensive).. Computing them in `FinalizeSolutionStep` is a consequence of the current order.

**Comment by philbucher** [comment]
Not everything that is computed in FinalizeSolutionStep is only for post-processing. Hence switching the fct calls would make it impossible to output those quantities

IMO the order is good as is, i.e. if there is additional stuff that is required ONLY for postprocessing then it should be done here (And require that `IsOutputStep` is true in this step)

Regarding the fixity it seems like quite a specific problem. Which makes me think, why do we even release the fixity? To me this is somewhat inconsistent to not resetting the values => #6296

In any case, changing either thing would be a pretty big change IMO. Consider that this order has been like this for a long time, and I don't think it would be easy to test this properly to avoid silent breaking of code

**Comment by rubenzorrilla** [comment]
> Not everything that is computed in FinalizeSolutionStep is only for post-processing. Hence switching the fct calls would make it impossible to output those quantities

Agree. This would be a limitation. However, no use case come to my mind (aside of debugging OFC).

> 
> IMO the order is good as is, i.e. if there is additional stuff that is required ONLY for postprocessing then it should be done here (And require that `IsOutputStep` is true in this step)
>

Agree, the order is good provided that your postprocessing doesn't rely on the fixity.

> Regarding the fixity it seems like quite a specific problem. Which makes me think, why do we even release the fixity? To me this is somewhat inconsistent to not resetting the values => #6296
> 

Imagine that you're applying a force displacement from time 0 to 1. Then at 1 you want to free the forced displacement so your beam oscillates from time 1 to "End". If you were not releasing the fixity at each time step in the `ExecuteFinalizeSolutionStep` the displacement would remain applied with no oscillation.  

> In any case, changing either thing would be a pretty big change IMO. Consider that this order has been like this for a long time, and I don't think it would be easy to test this properly to avoid silent breaking of code

Agree, it would be painful. But I think is worth discussing it if we overcome current limitations.

**Comment by ddiezrod** [comment]
> > Not everything that is computed in FinalizeSolutionStep is only for post-processing. Hence switching the fct calls would make it impossible to output those quantities
> 
> Agree. This would be a limitation. However, no use case come to my mind (aside of debugging OFC).

I think we have a few of those examples. For example, the temperature gradient it's a post-process result itself but it can be also used in other calculations (we use to compute microporosity and other casting solidification criteria). I think the change is to big for the gain.

**Comment by rubenzorrilla** [comment]
> > > Not everything that is computed in FinalizeSolutionStep is only for post-processing. Hence switching the fct calls would make it impossible to output those quantities
> > 
> > 
> > Agree. This would be a limitation. However, no use case come to my mind (aside of debugging OFC).
> 
> I think we have a few of those cases. For example, the temperature gradient it's a post-process result itself but it can be also used in other calculations (we use to compute microporosity and other casting solidification criteria). I think the change is too big for the gain.

Fair enough, then what is your proposal to overcome current limitation?

**Comment by rubenzorrilla** [comment]
OFC you can do whatever depending on the fixity in the `ExecuteFinalizeSolutionStep` and then call the other processes modifying this. However this requires the user to know which processes are fixing and unfixing, something that is done under the hood and might not be straightforward at all, specially for newbies.

**Comment by ddiezrod** [comment]
I have to say I don't fully understand the problem. Why would a post-process result depend on the fixity? Do you have an example?

**Comment by rubenzorrilla** [comment]
> I have to say I don't fully understand the problem. Why would a post-process result depend on the fixity? Do you have an example?

HROM solution projection onto a visualization mesh. Or any other solution projection from a computational mesh onto a visualization one.

**Comment by rubenzorrilla** [comment]
Anyway, considering that you both @philbucher and @ddiezrod are quite hesitant to modify this with more than fair enough considerations I'll close the issue. In any case it think it has been a positive discussion to (at least) have the issue documented.
