### ISSUE TITLE
Segmentation Fault in Structural Mechanics Application + GiD output process

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/Kratos#9671]
**Description**
This is very much an edge-case.

If you try to use a `BaseSolidElement` or derived class without calling `SetIntegrationMethod`, and later on try to use the `gid_output_process`, a segmentation fault occurs here:

https://github.com/KratosMultiphysics/Kratos/blob/46be0c8b2716663fbd495d95b3c5a71ac1170eaa/kratos/includes/gid_gauss_point_container.h#L70-L72

Particularly in the second condition
```
pElemIt->GetGeometry().IntegrationPoints(pElemIt->GetIntegrationMethod()).size() == mSize
                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                    UNINITIALIZED VALUE
```
This is of course undefined behaviour and more often than not will cause a segmentation fault.

I understand that during normal operation of the application, this `SetIntegrationMethod` is always called at some point, but I was working in ROM where I only use this element because it's the one coming from the MDPA.

**Scope**
- KratosCore: Gid output
- StructuralMechanicsApplication @KratosMultiphysics/structural-mechanics 

**To Reproduce**
Switch to branch `rom/visualize-modes`.
Run unit test at `/applications/RomApplication/tests/test_basis_visualization_analysis.py`
Particularly the second one

**Expected behavior**
Probably set a default value for the integration method. I've never used this application so I'm not sure either.

**Environment**
- OS: Ubuntu 21.10
- Branch: rom/visualize-modes
- Python 3.9.7
Note that this branch doesn't change any of the afected files.

**Comment by philbucher** [comment]
in the solid elements the integration method is initialized in `Initialize`
https://github.com/KratosMultiphysics/Kratos/blob/f55a2c57ac8102038bdb46428cb2d2a95c7b92cc/applications/StructuralMechanicsApplication/custom_elements/base_solid_element.cpp#L32-L76

Hence you need to call `Initialize` first before using the element. I see that this might not be necessary depending on the element, but I think it is a reasonable assumption/requirement for the user to do this before using the element (esp for the usually more complex structural elements). Ofc we could provide some sort of default, but I think it might cause problems as e.g. in this case the IntMethod would be different before and after calling `Initialize`

What do you think?

**Comment by EduardGomezEscandell** [comment]
Hmm I tried going around this by calling Initialize, but then for my particular case (`SmallDisplacementElement2D3N`) I need to specify a constitutive law.

I understand that this is a reasonable demand if you are going to use the element for anything other than plotting like I do, but still I think leaving a publicly accessible member variable uninitialized after the constructor is bad practice.

> Ofc we could provide some sort of default, but I think it might cause problems as e.g. in this case the IntMethod would be different before and after calling Initialize

Currently you are exposed to the same issue, except it will fail silently and/or cause issues latter (like in my case) because it is undefined behaviour.

I'd say the ideal is to have a default integration method, which at least prevents undefined behaviour.

Additionally, if you also want to avoid issues arising from it changing, you can maybe add some warning or error when run in debug mode. Something like:
```C++
IntegrationMethod GetIntegrationMethod() const override
{
    KRATOS_DEBUG_ERROR_IF(mIntegrationMethodNotYetSet, "Accessing integration method before initialize");
// Maybe a warning instead, just in case Initialize is never called?
    return mThisIntegrationMethod;
}

void BaseSolidElement::Initialize(const ProcessInfo& rCurrentProcessInfo) 
{ 
// etc.
    mIntegrationMethodNotYetSet = False;
}
```
Note that this is not what I'm looking for, the issue of accessing before vs. after initialization is a diferent one, I'm only affected by the issue of accessing without ever initializing.

**Comment by philbucher** [comment]
I made a fix in #9680 

I think this is the best fix for the moment. I agree that the element also has a problem, but I prefer for now an exception rather than a silent failure.
Hopefully in the future we can find a better solution.

I understand also your argument with the CTor should leave the element in a usable state, but I also have two strong arguments against it: 
- In Kratos it is standard to have classes with `Initialize`. Hence using a class without calling initialize is somewhat at own risk. This way we can at least use the class in a limited scope (e.g. for writing nodal results). 
- Consider also that without the `Initialize` function we would do all the initializing in the CTor and then you would also have to e.g. specify a CLaw (basically everything that the class needs to be fully functional)

**Comment by EduardGomezEscandell** [comment]
Works for me! :smiley:

**Comment by philbucher** [comment]
> Works for me! smiley

Great!

then #9680 needs approval ;)
