### ISSUE TITLE
Wrong parsing of functions in .json

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/Kratos#9681]
**Description**
This piece of code is in charge of detecting if a function depends on space.

https://github.com/KratosMultiphysics/Kratos/blob/39cc4fcff426d57bb6d19e859dd3c3be05e6837e/kratos/utilities/function_parser_utility.cpp#L39-L46

this fails for something as simple as `exp(t)`, because it contains an `x`.

**Scope**
When a function is passed e.g. for a boundary condition

**To Reproduce**
Check out https://github.com/KratosMultiphysics/Kratos/pull/9679
This branch contains two unit tests showing the problem
```
(1.0)*(50*(cos(t)-2)) -> DependsOnSpace() : false
(1.0)*(50*(exp(t)-2)) -> DependsOnSpace() : true
```

**Expected behavior**
The tests should pass

**Environment**
- OS: Ubuntu Ubuntu 21.10
- Branch: bug-assign-vector-direction-condition
- Python 3.9.7

**Comment by loumalouomega** [comment]
Now I see
