### ISSUE TITLE
Compiler ERROR

### ISSUE THREAD

**Issue by diegotrigos5** [KratosMultiphysics/Kratos#9692]
**Description**
GOOD DAY!!
I'm having trouble compiling KRATOS
I'm using:
- Python 3.9.9
- visual studio 17 2022
- cmake-3.23.0
- boost_1_78_0
- This is the modified configure file:
@echo off
rem Please do not modify this script

rem For any question please contact with us in:
rem  - https://github.com/KratosMultiphysics/Kratos

rem Optional parameters:
rem You can find a list will all the compiation options in INSTALL.md or here:
rem  - https://github.com/KratosMultiphysics/Kratos/wiki/Compilation-options

rem Set compiler
set CC=cl.exe
set CXX=cl.exe

rem Set variables
if not defined KRATOS_SOURCE set KRATOS_SOURCE=%~dp0..
if not defined KRATOS_BUILD set KRATOS_BUILD=%KRATOS_SOURCE%/build

rem Warning: In windows this option only works if you run through a terminal with admin privileges
rem set KRATOS_INSTALL_PYTHON_USING_LINKS=ON

rem Set basic configuration
if not defined KRATOS_BUILD_TYPE set KRATOS_BUILD_TYPE=Release
if not defined BOOST_ROOT set BOOST_ROOT=D:\INSTALADORES\boost_1_78_0
if not defined PYTHON_EXECUTABLE set PYTHON_EXECUTABLE=C:\Windows\py.exe

rem Set applications to compile
set KRATOS_APP_DIR=applications
set KRATOS_APPLICATIONS=
CALL :add_app %KRATOS_APP_DIR%\DelaunayMeshingApplication;
CALL :add_app %KRATOS_APP_DIR%\PfemApplication;

rem Clean
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\cmake_install.cmake"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeCache.txt"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeFiles"

rem Enable this if your build is slow and you have a multi-core machine
rem set KRATOS_PARALLEL_BUILD_FLAG=/MP4

rem Configure
@echo on
cmake -G"Visual Studio 17 2022" -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%"          ^
-DUSE_EIGEN_MKL=OFF        ^
-DCMAKE_CXX_FLAGS=" %KRATOS_PARALLEL_BUILD_FLAG% "

rem Build
cmake --build "%KRATOS_BUILD%/%KRATOS_BUILD_TYPE%" --target install -- /property:configuration=%KRATOS_BUILD_TYPE% /p:Platform=x64
goto:eof

rem Function to add apps
:add_app
set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%1;
goto:eof

[configure.txt](https://github.com/KratosMultiphysics/Kratos/files/8111180/configure.txt)
powershell outputs are:
![image](https://user-images.githubusercontent.com/99924487/155003901-def0b84f-f194-40ef-9dab-ad591e3d0400.png)

I appreciate you can help me

**Scope**
Which areas of Kratos are involved
- Compilation

**Comment by roigcarlo** [comment]
Hi @diegotrigos5 

If you include the Delaunay application you need to enable the triangle library. You can do so by adding `-DUSE_TRIANGLE_NONFREE_TPL=ON`:

```
rem Configure
@echo on
cmake -G"Visual Studio 17 2022" -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%%KRATOS_BUILD_TYPE%" ^
-DUSE_EIGEN_MKL=OFF ^
-DCMAKE_CXX_FLAGS=" %KRATOS_PARALLEL_BUILD_FLAG% " ^
-DUSE_TRIANGLE_NONFREE_TPL=ON
```
 Hope this helps

**Comment by diegotrigos5** [comment]
Thank you very much @roigcarlo the bug was resolved. however, now I have two problems:
1) I find the following example error: Dam_Break_2D in PFEM

![image](https://user-images.githubusercontent.com/99924487/157576707-b10d5d34-afc6-4200-a5c0-0d6ecbf2b30b.png)

2) I found the following error when compiling PFEM2:
![image](https://user-images.githubusercontent.com/99924487/157766722-74175ce1-7f04-4d03-b193-c13d90d81250.png)

Thanks in advance.

**Comment by roigcarlo** [comment]
Hi @diegotrigos5,

1 - 
Seems that you are missing an application needed by this example. 
In this particular case the application needed is `PfemFluidDynamicApplication`, so you have to enable it in the configure script.

The app section should look like this (around line 27):

```bash
rem Set applications to compile
set KRATOS_APP_DIR=applications
set KRATOS_APPLICATIONS=
CALL :add_app %KRATOS_APP_DIR%\DelaunayMeshingApplication;
CALL :add_app %KRATOS_APP_DIR%\PfemApplication;
CALL :add_app %KRATOS_APP_DIR%\PfemFluidDynamicsApplication;
```

I ignore if there are more application needed for that particular example. Ping @KratosMultiphysics/pfem 

2 - 
Seems that the application is not being actively maintained. I will try to solve the issues but you should contact someone from @KratosMultiphysics/pfem2 to get  more details about it.

**Comment by dcagritan** [comment]
I'll check out the issue regarding PFEM2Application today afternoon and will give you a feedback.
Regards,
Deniz

**Comment by roigcarlo** [comment]
@dcagritan I think #9759 should solve the issues, but please take a look as I am no expert in that app

**Comment by dcagritan** [comment]
@roigcarlo Thank you very much! I'll check it out as soon as I'm in the office this afternoon.
Regards

**Comment by diegotrigos5** [comment]
Good day @roigcarlo @dcagritan, when executing the Dam_Break_2D example it already had the PfemFluidDynamicApplication included, perhaps the errors are due to another particular. I will be on the lookout for any sign of a solution to both problems, thank you very much.

**Comment by dcagritan** [comment]
Good morning @diegotrigos5,
does taking PfemFluidDynamicApplication out of the script solve the problem?
Regards

**Comment by AFranci** [comment]
Dear @diegotrigos5 

I have just checked and with the master versions of Kratos and GiD interface the dam break example of the Pfem interface works correctly, at least from the terminal (python3 MainKratos.py).

To run PFEM problems you just need to compile PfemFluidDynamicsApplication and DelaunayMeshingApplication.

If you still have trouble write me at falessandroATcimne.upc.edu

Regards,

Alessandro

**Comment by AFranci** [comment]
![7FB2A1F3-B2B4-4FB3-B4BA-4BA6FA51BBA5](https://user-images.githubusercontent.com/25818902/158199120-d02a62ac-a189-4347-8f36-1da3baa9dd1b.jpeg) and set this in kratos preferences..

**Comment by diegotrigos5** [comment]
thank you very much to all!!! I was able to run the Pfem examples after setting the kratos preferences.
