### ISSUE TITLE
How to reset the stress state of an element

### ISSUE THREAD

**Issue by XinLiu100** [KratosMultiphysics/Kratos#9718]
I am using StructuralMechanicsApplication and some plastic models.

I am implementing some element activation codes and I need to reset the element's stress state between solving steps. I see someone used `ResetConstitutiveLaw `but I am not sure is that the correct way to do so? Or I should just use `elem.SetValue(KratosMultiphysics.STRESSES,[0,0,0,0,0,0]) ` to reset the stresses?

Thank you in advance!

**Comment by loumalouomega** [comment]
@AlejandroCornejo

**Comment by AlejandroCornejo** [comment]
Dear @XinLiu100 , If you are using the stresses at the integration points, you should use `elem.SetValuesOnIntegrationPoints(ZeroVector, CAUCHY_STRESS_VECTOR, ProcessInfo)`. The main issue is to reset the correct stress related variable.

If you are using the stresses via `GetValue` and `SetValue`, the your answer is the correct one.
