### ISSUE TITLE
Multiscale application Constitutive law adapters failing

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#973]
Three constitutive law adapters from the Multiscale application are failing:

* ShellFrom3DConstitutiveLawAdapter
* PlaneStressFrom3DConstitutiveLawAdapter
* PlaneStrainFrom3DConstitutiveLawAdapter

Because they assume `ValidateInput` to be a member of `ConstitutiveLaw` From Kratos, which does not have such method.

The method was deleted here: aea5f2fc9ee2ea432b205cc0781dbfc6aaf6d015

**Comment by josep-m-carbonell** [comment]
It seams that automatic merge failed once again. If MultiScaleApplication is using them ValidateInput has to be restored in constitutive_law. I restore it in pull request #975.

**Comment by roigcarlo** [comment]
Solved in #975
