### ISSUE TITLE
Using self-compiled Kratos in conda environment

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#9773]
**Description**
I want to use / develop Kratos in a conda environment (meaning the precompiled kratos through pip is not an option). So, I compiled the current kratos code and everything works fine. Now I need to setup Kratos for a given conda environment. Unfortunately, I cant get Kratos to work within that environment. It constantly refuses to find the Kratos module. 

I know the usual way of setting the environment variables in a post-compilation step when you don't use environments. But obviously this is different within a conda environment and I am afraid I cant make it work. Simply specifying a PYTHONPATH is not possible in this case afaik. So I already tried adding a link to the bin folder via: `conda develop /PATH/TO/KKRATOS/BINS`. But that did not help.

@roigcarlo Do you have an idea / solution in this case?

Thanks already.

**Scope**
Installation process

**Comment by dbaumgaertner** [comment]
I figured out the problem. In fact, the approach through `conda develop /PATH/TO/KKRATOS/BINS` was correct. But the problem is that Kratos does not copy a zlib.dll to the bin directory. So it fails because the corresponding dll is not found. During compilation of Kratos, however, I do not get an error. It just says:

`-- Found ZLIB: C:/Program Files/Anaconda3/Library/lib/z.lib (found version "1.2.11")`

In the latter directory, there is no corresponding dll, though.  In fact, I do not have one on my computer. Looking at the CMakeLists.txt, my guess is that it finds the above library, prevents a local compilation of zlib, instead tries to copy the dll, but obviously without success. I realized, there is a cmake option `FORCE_LOCAL_ZLIB_COMPILATION`. I will try using that one and see if it helps.

**Comment by philbucher** [comment]
Maybe @oberbichler can help

**Comment by dbaumgaertner** [comment]
Update: With `FORCE_LOCAL_ZLIB_COMPILATION` everything works fine and the zlib.dll is created as expected above.  With that, Kratos can be used and developed in a conda environment.  However, the question remains whether this is a wanted behavior. Wouldn't it be better to check for the dll rather than the z.lib in the Windows compilation process?

**Comment by roigcarlo** [comment]
Check for zlib in windows is very erratic. We added the flag to force the compilation because it was detecting zlib from the most imaginative origins, for example from the video player... In the same way the compiled zlib from Kratos can conflict with other installations, specially if added in the PATH, be careful with this.

As for the conda, it should be possible to directly use Kratos packages. Two options if I am not wrong:

1 - Install pip in conda:
```bash
conda install pip
```
2 - Download the pip packages directly
Since the wheels from pip are just zip files you can manually download them form the pip webpage (https://pypi.org/project/KratosMultiphysics/#files) and then extract them in the conda site-packages as if it were any other conda module.

Site packages should be in a location like `anaconda/lib/python3.x/site-packages`

Also, I suppose eventually we could upload to conda, there should be a similar process as uploading to PyPI

**Comment by roigcarlo** [comment]
> Just one last question: Is there any disadvantage in compiling it locally (performance impacts on Kratos, significantly longer compilation time, ...)?

No, no problem, just be carefull that it may conflict with other progams that use zlib if you add it to the PATH.

**Comment by roigcarlo** [comment]
Also, if it is interestign we can try to make a generator for conda packages

I would say that the only differences respect pip is precesiley that the conda package needs to contain all the libraries, which is something we try to avoid to use as many system libs as we can. But it should be relatively stright forward as long as they are for locase usage.

**Comment by dbaumgaertner** [comment]
An installation directly as conda package rather than a "workaround" through pip within a conda environment is certainly the cleaner solution. For sure it will add to the usability of Kratos as a whole. Its maybe something for Release 9.2?

**Comment by roigcarlo** [comment]
Can't promise the conda one for 9.2 but i will try. I have and rough Idea of what is needed but I need to try first

**Comment by dbaumgaertner** [comment]
Alright. As far as the issue is concerned, the problem is understood and solved by locally compiling zlib.  So I am closing this issue. Thanks for the support!
