### ISSUE TITLE
Regions with negative temperature in a convection-diffusion problem

### ISSUE THREAD

**Issue by AniolSala** [KratosMultiphysics/Kratos#9776]
**Description**
Hi, I have recently started a PhD at CIMNE, and taking the first steps with the ConvectionDiffusionApplication I have seen that, for a circular pipe with a fixed temperature at the inlet, the solution exhibits regions with negative temperature when temperature gradients are large.

![negative_temperature](https://user-images.githubusercontent.com/43894673/158853202-f887df26-6074-43ce-8f3d-5899db1825ef.gif)

The black zones have negative temperature (~-10K). The inlet is kept at T=200K, while the fluid starts at 1K.

**Scope**
- ConvectionDiffusionApplication

**To Reproduce**
[negative_temperature_case.gid.zip](https://github.com/KratosMultiphysics/Kratos/files/8288263/negative_temperature_case.gid.zip)

**Environment**
- OS: Ubuntu 21.10
- Branch: master
- Python 3.9.7

**Comment by AniolSala** [comment]
@RiccardoRossi 
@GuillermoCasas

**Comment by RiccardoRossi** [comment]
dear Aniol, such oscillations are normal and are related to the use of the
galerkin method.
indeed you could experience them already in a pure conduction problem.

in case they are not acceptable for your applications you will need to use
more sophisticated techniques.
i amm cc-ing Dr Hashemi who recently implemented a solution for this
problem.

Mohammad, i don t know your github jser and i am on the mobile, you d
better answer by github

**Comment by ddiezrod** [comment]
Hi @AniolSala , you can use the monotonicity preserving solver. You only need to write in your ProjectParameters.json:
            "linear_solver_settings" : {
                "solver_type" : "monotonicity_preserving",
                "inner_solver_settings" : {
                    "solver_type"         : "cg",
                    "tolerance"           : 1.0e-6,
                    "max_iteration"       : 500,
                    "preconditioner_type" : "diagonal"
              }
            }
where the inner_solver_settings are the current linear solver settings you are using right now. This solver removes all positive off diagonal terms. so you should not see these values anymore. This might be adding a little too much diffusion that it is really needed, but at least in my cases with pure diffusion it worked reallly well.

**Comment by mrhashemi** [comment]
Hi @AniolSala as elaborated by @RiccardoRossi this is a known issue with the non-monotonicity preserving methods. The solution is very well explained by @ddiezrod 
Alternatively, there is an implementation of a monotonicity-preserving pure convection solver (accessible in levelset_convection). Anyway, at the moment, there is no diffusion term in the implementation.

**Comment by AniolSala** [comment]
Thank you @RiccardoRossi , @ddiezrod and @mrhashemi for your responses! I will take a look at the different methods, then!
