### ISSUE TITLE
Nightly build is failing

### ISSUE THREAD

**Issue by miguelmaso** [KratosMultiphysics/Kratos#9784]
**Description**
`RuntimeError: Error: Kratos components missing "AssociativePlasticDamageModel3DVonMisesVonMises"`

seems to be related to #9770 

**Scope**
- NightlyBuild
- ConstitutiveLawsApplication

**Comment by AlejandroCornejo** [comment]
![imagen](https://user-images.githubusercontent.com/26402605/159648693-80f10c98-7744-4fd5-be22-5a9494e6d3f1.png)

**Comment by loumalouomega** [comment]
> ![imagen](https://user-images.githubusercontent.com/26402605/159648693-80f10c98-7744-4fd5-be22-5a9494e6d3f1.png)

Deeply concerned...

**Comment by AlejandroCornejo** [comment]
solved I think

**Comment by ddiezrod** [comment]
I think there is another test failing from ConstitutiveLawsApp 
see https://github.com/KratosMultiphysics/Kratos/runs/5659661998?check_suite_focus=true

**Comment by AlejandroCornejo** [comment]
On it...

**Comment by AlejandroCornejo** [comment]
Should be fine now!
