### ISSUE TITLE
DEM App - Access Violation

### ISSUE THREAD

**Issue by VeronikaSinger** [KratosMultiphysics/Kratos#9791]
Hi all,

I have troubles running examples with the DEM Application as I always get the error that a flag is not defined. 
The debugger reports an error ( Unhandled exception thrown: read access violation.
this was 0x10.) for this line:
       ` [const bool tag_condition = p_particle->IsNot(TO_ERASE)];`
[https://github.com/KratosMultiphysics/Kratos/blob/master/applications/DEMApplication/custom_utilities/create_and_destroy.cpp#:~:text=const%20bool%20tag_condition%20%3D%20p_particle%2D%3EIsNot(TO_ERASE)%3B](url)

This is an example file: [DEM_Files.zip](https://github.com/KratosMultiphysics/Kratos/files/8333979/DEM_Files.zip)
Are there any ideas how to resolve that issue? 

Best regards
Veronika

**Comment by KlausBSautter** [comment]
Thanks, @VeronikaSinger I have the same problem. Maybe this is also interesting for @maceligueta.

**Comment by maceligueta** [comment]
I will take a look today. Thanks for reporting.

**Comment by maceligueta** [comment]
I found the source of error and I am fixing it.
