### ISSUE TITLE
[Fluid] Compressible symbolic generation failing in Centos Nightly CI

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#9795]
**Description**
About the error we found in https://github.com/KratosMultiphysics/Kratos/pull/9787
@EduardGomezEscandell 
I think I found what is happening in the compressible symbolic generation tests in centos. 
If we take a look to the generated symbolic_test_2D4N we see it is different from the one generated in windows:
centos;
![image](https://user-images.githubusercontent.com/25667299/159885290-2415074f-a007-4c8d-a944-4dee1e35d971.png)

windows:
![image](https://user-images.githubusercontent.com/25667299/159885380-6a49a793-d1cb-43c0-8f89-08f98adaa576.png)

I have not checked it but I am almost sure that the problem comes from here:
https://github.com/KratosMultiphysics/Kratos/blob/40d2b1d434c69aab9ee681138cdad3886aa74a5b/applications/FluidDynamicsApplication/python_scripts/symbolic_generation/compressible_navier_stokes/compressible_navier_stokes_symbolic_generator.py#L490

You are using a dictionary for the projections and later you are taking its values and assuming they will be kept in the same order as you added them:
https://github.com/KratosMultiphysics/Kratos/blob/40d2b1d434c69aab9ee681138cdad3886aa74a5b/applications/FluidDynamicsApplication/python_scripts/symbolic_generation/compressible_navier_stokes/compressible_navier_stokes_symbolic_generator.py#L501

but this is not the case! **Dictionaries do not have an order** so you cannot assume elements will be kept in the same order. I guess that for some obscure reasons, windows and ubuntu do no modify the order, but this is not the case in centos.

I leave the correction to you as the code is quite complex, but I guess that you can simply use a list or something similar.

**Scope**
- FluidDynamicsApplication

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: Centos7
- Python 3.5

**Comment by EduardGomezEscandell** [comment]
Good catch, I was ready to add a skip for the test for Python < 3.7 :laughing:.

The linked PR should fix it, let's see if the CI run agrees.
