### ISSUE TITLE
Help! Compiling error on HPC

### ISSUE THREAD

**Issue by fdifrison** [KratosMultiphysics/Kratos#980]
Dear All,

I'm Giovanni Frison, Phd Fellow from the University of Padua (Italy).
I'm trying to compile Kratos on the CINECA HPC (Bologna-Italy). This is the Machine  [http://www.hpc.cineca.it/hardware/marconi](url) (Marconi A1).
I have tried to follow the installation instructions like I did on my laptop but I have to use the pre-compiled packages available on the supercomputer.
I managed to load:
gnu/6.1.0 
boost v1.61
cmake/3.5.2
python/3.5.2
blas/3.6.0--intel--pe-xe-2017--binary
lapack/3.6.1--intel--pe-xe-2017--binary

But there is no compiled module for python3-dev

After some try and thanks to  @RiccardoRossi I got to this compilation stage (see screenshot) and I'am literally stuck. Is it caused by the lack of python3-dev module? 

Any suggestion will be really appreciated!

![screenshot from 2017-11-07 19-20-14](https://user-images.githubusercontent.com/33176611/32510523-2d2527ce-c3f1-11e7-91f9-2d138d216e3e.png)

**Comment by roigcarlo** [comment]
Hi @fdifrison,
The problem seems not to be related with python3-dev, but boost. According to the compiler    `static_vector.hpp` is missing, but this looks odd.
Could you show me the contents of the boost include directory? Specifically what is inside of "boost/container" folder (should be a bunch of `*.hpp` files). Just to be sure that the missing file is there.

**Comment by fdifrison** [comment]
Hi @roigcarlo ,
thank you for your reply. The main problem is that I don't have access to the boost setup folder on the supercomputer (or at least I am not able to, I have to admit I'm not an expert user).
The boost version installed is the 1.61, so it should work accordingly with the setup instructions, but another step that I'm not able to do is the compiling of boost library:
"./b2 stage --with-python --with-serialization cxxflags="-std=c++11" link=shared,static"

I also tried to compile another version of boost by myself but unfortunately it didn't end well.

**Comment by roigcarlo** [comment]
Ok let'stry something. I assume boost is loaded through "module load XXXX" while XXXX is the name of the boost module.

Could you try to run "module show XXXX" being XXXX the name of the boost module.

Also, could you paste here the output of the `sh ./configure` command. Only until it starts to compile, the part that is printed befor the [0%] start appearing at the left.

Both of those procedures should show us where boost includes are.

**Comment by fdifrison** [comment]
OK, this is the first output:

module show boost
-------------------------------------------------------------------
/cineca/prod/opt/modulefiles/base/libraries/boost/1.61.0--intelmpi--2017--binary:

prereq	intelmpi/2017--binary
conflict	boost
setenv	BOOST_HOME	/cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary
setenv	BOOST_LIB	/cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib
setenv	BOOST_INC	/cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/include
setenv	BOOST_INCLUDE	/cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/include
prepend-path	PATH	/cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/bin	:
prepend-path	LIBPATH	/cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib	:
prepend-path	LD_LIBRARY_PATH	/cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib	:
module-whatis	Boost provides free peer-reviewed portable C++ source libraries.

#############################################################################
#  and this is the sh configure.sh output:

configure.sh: line 26: cmake: command not found
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
additional default options were set for gcc
CMAKE_CXX_FLAGS =  -funroll-loops -ffast-math -Wall -std=c++11
CMAKE_C_FLAGS =  -funroll-loops -ffast-math -Wall
KRATOS_EXCLUDE_OPENMP
OpenMP included
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
Using component: python
-- Boost version: 1.53.0
-- Found the following Boost libraries:
--   python
Boost Include: /usr/include
Boost Linkdir: /usr/lib64
Boostlib used: /usr/lib64/libboost_python-mt.so.1.53.0
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.5") 
 
CMAKE_BUILD_TYPE ........ 
 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
WARNING: YOUR GIDPOST IS BEING COMPILED  WITHOUT DEBUG (ALL ASSERTS WILL BE AVOIDED)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
 
INCOMPRESSIBLE_FLUID_APPLICATION ... 
MESHING_APPLICATION ................ 
EXTERNAL_SOLVERS_APPLICATION........ 
PFEM_APPLICATION.................... 
STRUCTURAL_APPLICATION.............. 
STRUCTURAL_MECHANICS_APPLICATION.... 
CONVECTION_DIFFUSION_APPLICATION.... 
SOLID_MECHANICS_APPLICATION......... 
PFEM_BASE_APPLICATION............... 
PFEM_SOLID_MECHANICS_APPLICATION.... 
MACHINING_APPLICATION............... 
FLUID_DYNAMICS_APPLICATION.......... 
PFEM_FLUID_DYNAMICS_APPLICATION..... 
STRING_DYNAMICS_APPLICATION......... 
ALE_APPLICATION..................... 
FSI_APPLICATION..................... 
EMPIRE_APPLICATION.................. 
MIXED_ELEMENT_APPLICATION........... 
DEM_APPLICATION..................... 
SWIMMING_DEM_APPLICATION............ 
CONSTITUTIVE_LAWS_APPLICATION....... 
THERMO_MECHANICAL_APPLICATION....... 
OPENCL_APPLICATION.................. 
MKL_SOLVERS_APPLICATION............. 
MPI_SEARCH_APPLICATION.............. 
METIS_APPLICATION................... 
TRILINOS_APPLICATION................ 
TURBULENT_FLOW_APPLICATION.......... 
BLOOD_FLOW_APPLICATION.............. 
PURE_DIFFUSION_APPLICATION.......... 
MESHLESS_APPLICATION................ 
WIND_TURBINE_APPLICATION ........... 
CLICK2CAST_APPLICATION ............. 
MULTISCALE_APPLICATION ............. 
PFEM2_APPLICATION................... 
FREEZING_SOIL_APPLICATION........... 
ADJOINT_FLUID_APPLICATION........... 
POROMECHANICS_APPLICATION........... 
PARTICLE_MECHANICS_APPLICATION...... 
FORMING_APPLICATION................. 
DAM_APPLICATION..................... 
SHAPE_OPTIMIZATION_APPLICATION...... 
TOPOLOGY_OPTIMIZATION_APPLICATION... 
MY_LAPLACIAN_APPLICATION............ 
LAGRANGIAN_MPM_APPLICATION.......... 
CONTACT_MECHANICS_APPLICATION....... 
CONTACT_STRUCTURAL_MECHANICS_APPLICATION....... 
MAPPING_APPLICATION................. 
CONSTITUTIVE_MODELS_APPLICATION..... 
 
--------------------------------  standard install dir /marconi/home/userexternal/rscotta0/Desktop/kratos
-- Configuring done
-- Generating done
-- Build files have been written to: /marconi/home/userexternal/rscotta0/Desktop/kratos/cmake_build

**Comment by fdifrison** [comment]
## Last Update:
### I have noticed that every time before starting the sh configure.sh I have to reload all the module needed.
Therefore I made another compilation try and this is the last output (only the relevant parts of it):

configure.sh: line 26: cmake: command not found
-- The C compiler identification is GNU 6.1.0
-- The CXX compiler identification is GNU 6.1.0
-- Check for working C compiler: /cineca/prod/opt/compilers/gnu/6.1.0/none/bin/gcc
-- Check for working C compiler: /cineca/prod/opt/compilers/gnu/6.1.0/none/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /cineca/prod/opt/compilers/gnu/6.1.0/none/bin/g++
-- Check for working CXX compiler: /cineca/prod/opt/compilers/gnu/6.1.0/none/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
additional default options were set for gcc
CMAKE_CXX_FLAGS =  -funroll-loops -ffast-math -Wall -std=c++11
CMAKE_C_FLAGS =  -funroll-loops -ffast-math -Wall
KRATOS_EXCLUDE_OPENMP
OpenMP included
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
Using component: python
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   python
Boost Include: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/include
Boost Linkdir: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib
Boostlib used: /marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python.so.1.61.0
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.5") 
 
CMAKE_BUILD_TYPE ........ 
 
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
WARNING: YOUR GIDPOST IS BEING COMPILED  WITHOUT DEBUG (ALL ASSERTS WILL BE AVOIDED)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
.
.
.
.
### [ 46%] Building CXX object kratos/CMakeFiles/KratosCore.dir/sources/reorder_consecutive_model_part_io.cpp.o
/marconi/home/userexternal/rscotta0/Desktop/kratos/kratos/sources/model_part_io.cpp: In member function ‘void Kratos::ModelPartIO::ReadPropertiesBlock(Kratos::ModelPartIO::PropertiesContainerType&)’:
/marconi/home/userexternal/rscotta0/Desktop/kratos/kratos/sources/model_part_io.cpp:1349:13: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
             if(CheckEndBlock("Properties", variable_name))
             ^~
/marconi/home/userexternal/rscotta0/Desktop/kratos/kratos/sources/model_part_io.cpp:1352:3: note: ...this statement, but the latter is misleadingly indented as if it is guarded by the ‘if’
   if(variable_name == "Begin") // here we have some nested block.
   ^~
### [ 46%] Building CXX object kratos/CMakeFiles/KratosCore.dir/sources/io.cpp.o
.
.
.
.
### [100%] Linking CXX shared library Kratos.so
CMakeFiles/Kratos.dir/python/add_model_part_to_python.cpp.o: In function `boost::python::type_info::name() const':
add_model_part_to_python.cpp:(.text._ZNK5boost6python9type_info4nameEv[_ZNK5boost6python9type_info4nameEv]+0x1f): undefined reference to `boost::python::detail::gcc_demangle(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [kratos/Kratos.so] Error 1
make[1]: *** [kratos/CMakeFiles/Kratos.dir/all] Error 2
make: *** [all] Error 2
[ 11%] Built target zlib
[ 22%] Built target zlibstatic
[ 23%] Built target example
[ 25%] Built target minigzip
[ 27%] Built target example64
[ 28%] Built target minigzip64
[ 32%] Built target gidpost
[ 66%] Built target KratosCore
[ 66%] Linking CXX shared library Kratos.so
CMakeFiles/Kratos.dir/python/add_model_part_to_python.cpp.o: In function `boost::python::type_info::name() const':
add_model_part_to_python.cpp:(.text._ZNK5boost6python9type_info4nameEv[_ZNK5boost6python9type_info4nameEv]+0x1f): undefined reference to `boost::python::detail::gcc_demangle(char const*)'
collect2: error: ld returned 1 exit status
make[2]: *** [kratos/Kratos.so] Error 1
make[1]: *** [kratos/CMakeFiles/Kratos.dir/all] Error 2
make: *** [all] Error 2

**Comment by roigcarlo** [comment]
Ok. I was writting you with the response but you alredy did most of the work :D 

There is only one thing that seems to be off. I understand that this has fixed the missing file error, that was caused because kratos was detecting the system boost.

The new error happens when the version of python used in kratos is different from the one used in boost-python. I suspect that since the MACRONI module is python/3.5.2 that is the version you need.

Try to change the configure file so these variables in the configure file:

-DPYTHON_LIBRARY
-DPYTHON_INCLUDE_DIR

so they point to python3 instead of 2. You can get the paths with the `module show python/3.5.2` command

If kratos dosn't detect it copy the output of the show command and I will help you with that.

**Comment by fdifrison** [comment]
This is the module show python/3.5.2

/cineca/prod/opt/modulefiles/base/compilers/python/3.5.2:

conflict	python
setenv	PYTHON_HOME	/cineca/prod/opt/compilers/python/3.5.2/none
prepend-path	PATH	/cineca/prod/opt/compilers/python/3.5.2/none/bin	:
prepend-path	LIBPATH	/cineca/prod/opt/compilers/python/3.5.2/none/lib	:
prepend-path	LD_LIBRARY_PATH	/cineca/prod/opt/compilers/python/3.5.2/none/lib	:
prepend-path	MANPATH	/cineca/prod/opt/compilers/python/3.5.2/none/share/man	:
prepend-path	PYTHONPATH	/cineca/prod/opt/compilers/python/3.5.2/none/lib/python3.5/site-packages/	:
module-whatis	Python programming language
-------------------------------------------------------------------



Did I get it right to add something like this to the configure.sh??

#you may want to decomment this the first time you compile
rm CMakeCache.txt
rm *.cmake
rm -rf CMakeFiles\

cmake ..                                \                                                                                         
### -DPYTHON_LIBRARY="/cineca/prod/opt/modulefiles/base/compilers/python/3.5.2"     \       
### -DPYTHON_INCLUDE_DIR="/cineca/prod/opt/modulefiles/base/compilers/python/3.5.2"         \
-DCMAKE_C_COMPILER=/usr/bin/gcc                                                                                     \
-DCMAKE_INSTALL_RPATH="/marconi/home/userexternal/rscotta0/Desktop/kratos"                              \
-DCMAKE_INSTALL_RPATH_USE_LINK_PATH=TRUE                                        \
-DCMAKE_CXX_COMPILER=/usr/bin/g++                                                                                   \
-DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -msse3 -std=c++11 "

**Comment by roigcarlo** [comment]
Yep, almost there.

Seems that the module paths are too generic for kratos.

-DPYTHON_LIBRARY: That one should point to a directory named "include". Probably will be something like `/cineca/prod/opt/modulefiles/base/compilers/python/3.5.2/none/include` or `/cineca/prod/opt/modulefiles/base/compilers/python/3.5.2/none/include/python3.5`

Can't really tell without having access to the machine. You should be able to locate the directoy by `ls /cineca/prod/opt/modulefiles/base/compilers/python/3.5.2/none/` and looking around for that folder

-DPYTHON_LIBRARY: This one should point to a `.so` file, as with the include, not quite sure where it is as the module is not helping much this time but should be something like 
`/cineca/prod/opt/compilers/python/3.5.2/none/lib/libpython3.5.so`. 

Try to chck if this exists

**Comment by fdifrison** [comment]
Nope, still same error :( ( i tried with both the solution you gave me)

Mmm.. can't really find anything inside this folder... what am I doing wrong?
[rscotta0@r000u06l01 ~]$ cd /cineca/prod/opt/modulefiles/base/compilers/python
[rscotta0@r000u06l01 python]$ ls
2.7.12  3.5.2
[rscotta0@r000u06l01 python]$ cd 3.5.2
-bash: cd: 3.5.2: Not a directory
[rscotta0@r000u06l01 python]$ 



Btw, there are this lines that seems strange to me:

Boost Include: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/include
Boost Linkdir: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib
Boostlib used: /marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python.so.1.61.0
### -- Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.5") 

Doesn't this mean that boost is compiling with another version of python??  I remember that in the "project-config.jam" of boost I had to change the python version (that by default was 2.7).

Can it be part of the problem?

p.s. In good faith, I really have no problem giving you access to the machine (in private)

**Comment by roigcarlo** [comment]
> Boost Include: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/include
> Boost Linkdir: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib
> Boostlib used: /marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python.so.1.61.0
>  Found PythonLibs: /usr/lib64/libpython2.7.so (found version "2.7.5")

Those are fine, is just kratos telling you what versions of the lib is using

> [rscotta0@r000u06l01 python]$ cd 3.5.2
-bash: cd: 3.5.2: Not a directory

This one seems to indicate that the module is somehow not loaded, could you try:

```
module unload python
module load python/3.5.2
```

And check if that folder is not empty anymore?

**Comment by fdifrison** [comment]
Ok, finally the python folder is not empty anymore :+1: 
this is what there's inside:

bin  include  lib  share
[rscotta0@r000u06l01 none]$ cd include
[rscotta0@r000u06l01 include]$ ls
python3.5m
[rscotta0@r000u06l01 include]$ cd python3.5m/
[rscotta0@r000u06l01 python3.5m]$ ls
abstract.h         cellobject.h     dtoa.h                 genobject.h    memoryobject.h     opcode.h       pyctype.h      pymacro.h     pythonrun.h     token.h
accu.h             ceval.h          dynamic_annotations.h  graminit.h     metagrammar.h      osdefs.h       py_curses.h    pymath.h      pythread.h      traceback.h
asdl.h             classobject.h    enumobject.h           grammar.h      methodobject.h     parsetok.h     pydebug.h      pymem.h       pytime.h        tupleobject.h
ast.h              codecs.h         errcode.h              import.h       modsupport.h       patchlevel.h   pyerrors.h     pyport.h      rangeobject.h   typeslots.h
bitset.h           code.h           eval.h                 intrcheck.h    moduleobject.h     pgen.h         pyexpat.h      pystate.h     setobject.h     ucnhash.h
bltinmodule.h      compile.h        fileobject.h           iterobject.h   namespaceobject.h  pgenheaders.h  pyfpe.h        pystrcmp.h    sliceobject.h   unicodeobject.h
boolobject.h       complexobject.h  fileutils.h            listobject.h   node.h             pyarena.h      pygetopt.h     pystrhex.h    structmember.h  warnings.h
bytearrayobject.h  datetime.h       floatobject.h          longintrepr.h  object.h           pyatomic.h     pyhash.h       pystrtod.h    structseq.h     weakrefobject.h
bytes_methods.h    descrobject.h    frameobject.h          longobject.h   objimpl.h          pycapsule.h    pylifecycle.h  Python-ast.h  symtable.h
bytesobject.h      dictobject.h     funcobject.h           marshal.h      odictobject.h      pyconfig.h     pymacconfig.h  Python.h      sysmodule.h
[rscotta0@r000u06l01 python3.5m]$ pwd
/cineca/prod/opt/compilers/python/3.5.2/none/include/python3.5m
[rscotta0@r000u06l01 python3.5m]$ cd ..
[rscotta0@r000u06l01 include]$ cd ..
[rscotta0@r000u06l01 none]$ ls
bin  include  lib  share
[rscotta0@r000u06l01 none]$ cd lib/
[rscotta0@r000u06l01 lib]$ ls
libpython3.5m.so  libpython3.5m.so.1.0  libpython3.so  pkgconfig  python2.7  python3.5

### And this is what I set as variables:
DPYTHON_LIBRARY="/cineca/prod/opt/compilers/python/3.5.2/none/include/python3.5m"
DPYTHON_INCLUDE_DIR="/cineca/prod/opt/compilers/python/3.5.2/none/lib/libpython3.5m.so"

unfortunately... same error until here

**Comment by roigcarlo** [comment]
Ok, lets try one more thing, if this dosn't work I will check it tomorrow at the office.

Maybe python 2.7 is still in the cmake cache. Try to delete all files in the cmake_build folder in kratos expect `configure.sh`

It should give you this output:

> Boost Include: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/include
Boost Linkdir: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib
Boostlib used: /marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python.so.1.61.0
Found PythonLibs: /cineca/prod/opt/compilers/python/3.5.2/none/lib/libpython3.5m.so (found version "3.5.2")

If this keeps failing with the error:

> boost::python::type_info::name() const': add_model_part_to_python.cpp:(.text._ZNK5boost6python9type_info4nameEv[_ZNK5boost6python9type_info4nameEv]+0x1f): undefined reference toboost::python::detail::gcc_demangle(char const*)'

Then we will probably have to contact with the cluster support so they can tell us which version of python we have to use with boost.

**Comment by RiccardoRossi** [comment]
please try to do

ls /marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python*

**Comment by fdifrison** [comment]
I'm back! Sorry for my absence but until now I couldn't get my hands on this.
@RiccardoRossi  this is the output of your request:
[rscotta0@r000u06l01 Desktop]$ ls /marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python*
/marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python.a
/marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python.so
/marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python.so.1.61.0

But right now I have a bigger issue... I'm trying to module load what I need but it doesn't seems to respond:
[rscotta0@r000u06l01 ~]$ module load python/3.5.2
[rscotta0@r000u06l01 ~]$ python --version
Python 2.7.5
[rscotta0@r000u06l01 ~]$ 

and as yesterday I can't access the python/3.5.2 folders
Any idea why??

Thanks again for your time and effort

**Comment by roigcarlo** [comment]
About the python version, probably you have to use `python3` insead of `python`. 
Also boost seems to be linked with python 2? @RiccardoRossi?

Just for the reccord. Here is the list of modules in the cluster http://www.hpc.cineca.it/softwares/All%20software

**Comment by fdifrison** [comment]
ok.. really don't understand why but right now I managed to reload pyhton 3.5.2... maybe it takes some time?? (bah)

other question, which one of these should I link to DPYTHON_INCLUDE_DIR??
(BDW) [rscotta0@r000u06l01 lib]$ ls
libpython3.5m.so  libpython3.5m.so.1.0  libpython3.so  pkgconfig  python2.7  python3.5

**Comment by roigcarlo** [comment]
Include dir must point to something with "include" in its path.

I would say this was ok:

> DPYTHON_LIBRARY="/cineca/prod/opt/compilers/python/3.5.2/none/include/python3.5m"`

If this doesn't work, try

> DPYTHON_LIBRARY="/cineca/prod/opt/compilers/python/2.7/none/include/python2.7"

But the problem you show is likely to be related with `DPYTHON_LIBRARY`. At this poitn  I would tell you to test all `*.so` you find in the python folder.

If it keeps failing we can arrange a remote session to help you (if you are ok withit)

**Comment by fdifrison** [comment]
Nothing... always worst... can't even load correctly gnu seems..
Right know it stop before starting to compile:

rm: cannot remove ‘*.cmake’: No such file or directory
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Git: /usr/bin/git (found version "1.8.3.1") 
additional default options were set for gcc
CMAKE_CXX_FLAGS =  -msse3 -std=c++11 -funroll-loops -Wall -std=c++11
CMAKE_C_FLAGS =  -msse3 -funroll-loops -Wall
KRATOS_BUILD_TESTING not defined. Setting to ON
KRATOS_EXCLUDE_OPENMP
OpenMP included
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
Using component: python
-- Boost version: 1.61.0
-- Found the following Boost libraries:
--   python
Boost Include: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/include
Boost Linkdir: /cineca/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib
Boostlib used: /marconi/prod/opt/libraries/boost/1.61.0/intelmpi--2017--binary/lib/libboost_python.so.1.61.0
-- Found PythonLibs: /cineca/prod/opt/compilers/python/3.5.2/none/include/python3.5m  
-- The Fortran compiler identification is GNU 6.1.0
-- Check for working Fortran compiler: /cineca/prod/opt/compilers/gnu/6.1.0/none/bin/gfortran
-- Check for working Fortran compiler: /cineca/prod/opt/compilers/gnu/6.1.0/none/bin/gfortran  -- works
-- Detecting Fortran compiler ABI info
-- Detecting Fortran compiler ABI info - done
-- Checking whether /cineca/prod/opt/compilers/gnu/6.1.0/none/bin/gfortran supports Fortran 90
-- Checking whether /cineca/prod/opt/compilers/gnu/6.1.0/none/bin/gfortran supports Fortran 90 -- yes
-- Detecting Fortran/C Interface
-- Detecting Fortran/C Interface - Found GLOBAL and MODULE mangling
-- Looking for Fortran sgemm
-- Looking for Fortran sgemm - not found
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
CMake Error at /marconi/prod/opt/tools/cmake/3.5.2/none/share/cmake-3.5/Modules/FindBLAS.cmake:681 (message):
  A required library with BLAS API not found.  Please specify library
  location.
Call Stack (most recent call first):
  CMakeLists.txt:258 (find_package)


-- Configuring incomplete, errors occurred!
See also "/marconi/home/userexternal/rscotta0/Desktop/Kratos/cmake_build/CMakeFiles/CMakeOutput.log".
See also "/marconi/home/userexternal/rscotta0/Desktop/Kratos/cmake_build/CMakeFiles/CMakeError.log".
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target `install'.  Stop.
[rscotta0@r000u07l02 cmake_build]$ 


@roigcarlo I would love a remote session

**Comment by roigcarlo** [comment]
Perfect then, Is it ok to you let's say tomorrow or friday? Any time is good to me, but tomorrow I have an apointment so it can't be before 11:00 CET

**Comment by fdifrison** [comment]
@roigcarlo tomorrow after 11:00 is perfect to me.
Teamviewer is ok or do you prefer something else?

**Comment by roigcarlo** [comment]
Teamviewer is fine 👍

**Comment by roigcarlo** [comment]
Hi, @fdifrison Whenever you want to start please contact me at roigcarlo@gmail.com

**Comment by roigcarlo** [comment]
It compiles now

**Comment by fdifrison** [comment]
@roigcarlo this is all yours!!

[rscotta0@r000u07l02 Desktop]$ runkratos try.py 
 |  /           |             
 ' /   __| _` | __|  _ \   __|
 . \  |   (   | |   (   |\__ \ 
_|\_\_|  \__,_|\__|\___/ ____/
           Multi-Physics 5.1.0-094b288
KRATOS TERMINATED CORRECTLY
[rscotta0@r000u07l02 Desktop]$ 

Thank your very much for your help
