### ISSUE TITLE
Error compiling Kratos in Windows 11

### ISSUE THREAD

**Issue by karencasallas09** [KratosMultiphysics/Kratos#9808]
**Description**
I am working on Windows 11 and I first installed Visual Studio Community 2022 and Python 3.8 and I got the compilation error attached here. Then I uninstalled VS Com. 2022 and Python 3.8, and I installed Visual Studio Community 2019 and Python 3.9, but got the same error:

```
C:\Users\kcasallas\Repo\Kratos\scripts>cmake -G"Visual Studio 16 2019" -H"C:\Users\kcasallas\Repo\Kratos\scripts\.." -B"C:\Users\kcasallas\Repo\Kratos\scripts\../build\FullDebug"          -DUSE_EIGEN_MKL=OFF -DUSE_EIGEN_FEAST=OFF -DFORCE_LOCAL_ZLIB_COMPILATION=ON -DINSTALL_RUNKRATOS=OFF -DCMAKE_CXX_FLAGS=" /MP3 "
-- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
-- The C compiler identification is MSVC 19.29.30141.0
-- The CXX compiler identification is MSVC 19.29.30141.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Deprecation Warning at CMakeLists.txt:2 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- No KRATOS_SOURCE_DIR is defined, using: C:/Users/kcasallas/Repo/Kratos
-- No KRATOS_BINARY_DIR is defined, using: C:/Users/kcasallas/Repo/Kratos/build/FullDebug
-- No KRATOS_BUILD_TESTING is defined. Setting to ON
-- No CMAKE_INSTALL_MESSAGE is defined. Setting to NEVER
CMake Error: failed to create symbolic link 'C:/Users/kcasallas/Repo/Kratos/compile_commands.json': A required privilege is not held by the client.

-- Found Git: C:/Program Files/Git/cmd/git.exe (found version "2.35.1.windows.2")
-- CMAKE_SYSTEM_NAME = Windows
Detected compiler as MSVC
-- Found PythonInterp: "C:\Program Files\Python39\python.exe"
CMake Error at cmake_modules/FindPythonLibsNew.cmake:95 (message):
  Python config failure:

Call Stack (most recent call first):
  cmake_modules/pybind11Tools.cmake:16 (find_package)
  CMakeLists.txt:285 (include)


-- Configuring incomplete, errors occurred!
See also "C:/Users/kcasallas/Repo/Kratos/build/FullDebug/CMakeFiles/CMakeOutput.log".

C:\Users\kcasallas\Repo\Kratos\scripts>rem Build

C:\Users\kcasallas\Repo\Kratos\scripts>cmake --build "C:\Users\kcasallas\Repo\Kratos\scripts\../build/FullDebug" --target install -- /property:configuration=FullDebug /p:Platform=x64
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1009: Project file does not exist.
Switch: install.vcxproj
```

Do you have any idea on how I should proceed?

Thank you very much in advance.

FYI @ipouplana 

**Scope**
- Compilation
- Windows

**Comment by AlejandroCornejo** [comment]
It seems that it has some trouble finding your python... Can you check that you installed a 64bits python? Also that the path of instalation of python inside the `configure.bat` is correct. If those actions do not solve the problem please also try to remove the file C:\Kratos\build\Release\CmakeCache.txt and rerun the configure.

**Comment by karencasallas09** [comment]
I have this Python 3 version:

```
C:\Users\kcasallas>python
Python 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by karencasallas09** [comment]
> Have you tried with clean Windows 11 install?



> It seems that it has some trouble finding your python... Can you check that you installed a 64bits python? Also that the path of instalation of python inside the `configure.bat` is correct. If those actions do not solve the problem please also try to remove the file C:\Kratos\build\Release\CmakeCache.txt and rerun the configure.

I deleted all the build folder and got the same error...

**Comment by karencasallas09** [comment]
> Have you tried with clean Windows 11 install?

Not yet... I would like to avoid that^_^'

**Comment by loumalouomega** [comment]
> > Have you tried with clean Windows 11 install?
> 
> Not yet... I would like to avoid that^_^'

We can try with a VM...

**Comment by roigcarlo** [comment]
Hi, @karencasallas09 

Could you try to add `-DPYTHON_EXECUTABLE="[PATH]" ` in the cmake (the one that starts with cmake -G ....) command with the PATH poiting to your python.exe? It should be the same you alread have in the top of file.

**Comment by karencasallas09** [comment]
> Hi, @karencasallas09
> 
> Could you try to add `-DPYTHON_EXECUTABLE="[PATH]" ` in the cmake (the one that starts with cmake -G ....) command with the PATH poiting to your python.exe? It should be the same you alread have in the top of file.

That solved the issue. Thank you very much!

**Comment by develpGit** [comment]
I'm getting the same issue, tried keeping the -DPYTHON_EXECUTABLE=[path]" but not really working
