### ISSUE TITLE
Nighly builds failing

### ISSUE THREAD

**Issue by roigcarlo** [KratosMultiphysics/Kratos#981]
The nightly build fails since the tetgen submodule for PFEM is not downloaded along with the repo file.

@KratosMultiphysics/technical-committee  I can disable PFEM related apps or modify the build script so it fetches the code from git and dowload the submodule. The latter will take some time to test since kratos was being fetched as a zip file to reduce dowload time...

What is your opinion?

**Comment by maceligueta** [comment]
The PFEM Team could make the application compilable without tetgen, I guess. With a couple of ifdefs maybe. I'll talk with Alessandro and Josep Maria.

**Comment by roigcarlo** [comment]
Well we need tetgen anyway in other apps, this is just a solution for the short run (during the release). After that I will modify the scrip to include tetgen. But since we have moved the kratos one as an external lib and now we also have submodule, I will like to take some time to find a universal solution that looks clean. 

Making the apps compilable without tetgen is even more work...

**Comment by RiccardoRossi** [comment]
@roigcarlo, unless i did some mistake, Tetgen should be only needed for the rest of kratos if one defines 

-DUSE_TETGEN = ON

is that not so?

**Comment by roigcarlo** [comment]
Its under controll now.
