### ISSUE TITLE
[KratosCore] Bug in Prism3D15N geometry

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#9818]
**Description**
The prism3D15N geometry seems to be buggy. [Here (test_Prism3D15N.zip)](https://github.com/KratosMultiphysics/Kratos/files/8399186/test_Prism3D15N.zip) you can find a minimal test case. It is a structural modal analysis with one SmallDisplacementElement3D15N which uses this prism. The single included element follows the Kratos node ordering specified [here](https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/geometries/prism_3d_15.h#L36). However, if one runs the analysis, it throws an error saying that the element base class is called. From the other output, it seems that something is very wrong with the computation of the Jacobian or the shape function (derivatives). 

Now, I checked, if there is a test for this geometry. However, it seems not. In fact, a corresponding test was once committed but then commented out. @loumalouomega from the git history, I noticed that you commented it out saying in the title of the [corresponding commit](https://github.com/KratosMultiphysics/Kratos/commit/bc7faa704785deb36125f50d04d0914824ae0dab) that "Prism3D15 [is](not working yet, the element has some problems to be fixed in the future)".

So my questions is. Did anybody experience this bug before or know a solution for it? It would be great if anyone involved in the geometry implementation could have a look into the element and check if there is something fishy.

Side note: If one changes the prism3D15N to a prism3D6N, the minimal example attached runs again without errors (relevant mdpas are provided). So it just seems to be a bug of the quadratic prism (and not the solver / model setup, etc...).  

**Scope**
- KratosCore

**To Reproduce**
Minimal example attached

**Expected behavior**
The simulation (a modal analysis) should run through and print the eigenvalue of the first mode

**Environment**
- OS: Windows
- Branch: master
- Python 3.9.7

**Comment by loumalouomega** [comment]
The mythical TODO, maybe I wrote that, if git says so. We can check the problem. The easiest way is with a simple patch test, that can be mono-element.

**Comment by loumalouomega** [comment]
> The mythical TODO, maybe I wrote that, if git says so. We can check the problem. The easiest way is with a simple patch test, that can be mono-element.

From the quoted test a priori looks like an ordering issue, I will check if I can
