### ISSUE TITLE
Initial condition process

### ISSUE THREAD

**Issue by mtnzguillermo** [KratosMultiphysics/Kratos#9826]
**Description**

I was searching for a process to apply an initial condition (just assign a value to a variable before the first time step) but I couldn't find any. Does it exist?

When using `FludDynamicsApplication`, I see that the "processes" field in the ProjectParameters has a subcategory called "initial_conditions_processes_list", but I couldn't find any test or example where this list is not empty.

Regarding the `StructuralMechanicsApplication`, when setting up the problem with GiD, an initial condition is translated as an `AssignVectorVariableProcess` where the interval is "[0.0, 0.0]".

Just to make it more straightforward for the user, shouldn't Kratos have a specific process to set initial conditions? Maybe just a child of `AssignScalarVariableProcess`, `AssignVectorVariableProcess` and `AssignVectorByDirectionProcess` where the time interval is forced to be the starting time and the "constrained" option is set to "false"?

**Comment by rubenzorrilla** [comment]
I suggest closing this one and continue the discussion in @ddiezrod 's one as it already has some feedback from the community.

**Comment by mtnzguillermo** [comment]
Sure! Sorry, I did not see the other issue.
