### ISSUE TITLE
Which is the fastest direct solver in mpi?

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#9830]
**Description**
I have started running thermomechanical simulations in mpi using a direct solver. For the moment I was using "amesos", but I have found that it is much slower that pardiso (comparing amesos with 4 cores in mpi against pardiso in 4 threads in smp). I was wondering, before getting into the fight of installing things to test other direct mpi solvers, if anybody in the kratos community has experience with this and if maybe someone knows which direct solver I should try to compile to make mpi runs faster.
@KratosMultiphysics/solid-mechanics @KratosMultiphysics/mpi @philbucher 
Thanks in advance!

**Comment by RiccardoRossi** [comment]
... mumps is known to be good ...

**Comment by philbucher** [comment]
I also heard that

i didnt get it to work though, ended up using amgcl instead which worked very well

in fact I tried pretty much every single direct solver that is available through amesos & amesos2, didn’t get a single one to work (except klu which was 40x slower than amgcl for my case)
I tried like a year ago, when I already had lots of experience with this

also there is a parallel version of Pardiso, maybe worth looking into

**Comment by philbucher** [comment]
Btw on ubuntu the trilinos-all-dev package comes with lots of direct solvers (including mumps)
Maybe that’s interesting for you

I meant above that I didn’t get them to work when trying to compile etc them myself

**Comment by ddiezrod** [comment]
Hi all, thanks for the answers. 
I managed to run a case using super_lu_dist and it is already much faster than klu. The whole test went from 16h with klu to 6h with super_lu using 4 cores in both cases. Still, running the same case with 4 threads (smp) and using pardiso it took only 1 hour.
I will try to compile mumps and see how it runs, I'll post how it went here!

**Comment by loumalouomega** [comment]
The good thing of SUPER_LU_DIST is that it is super robust. It can solve systems that many direct solvers can't

**Comment by philbucher** [comment]
@ddiezrod did you manage to get mumps to work?

Id is the default direct solver in CodeAster, so I am pretty sure that it works well

**Comment by loumalouomega** [comment]
Yes, we make it work. It is a matter of compile Trilinos with it, thanks

**Comment by philbucher** [comment]
I think the community could profit a lot if you would document it ;)

**Comment by loumalouomega** [comment]
> I think the community could profit a lot if you would document it ;)

Actually it is documented with Spack, I feel this is more standard than any other distro

**Comment by loumalouomega** [comment]
> > I think the community could profit a lot if you would document it ;)
> 
> Actually it is documented with Spack, I feel this is more standard than any other distro

https://github.com/KratosMultiphysics/Kratos/tree/master/applications/TrilinosApplication

**Comment by philbucher** [comment]
ok thx
