### ISSUE TITLE
Hyper Elastic Material Law

### ISSUE THREAD

**Issue by UmarSaeedMalik** [KratosMultiphysics/Kratos#9843]
Hello, I am working with Kratos 8.1. For my material i am using "name" : "HyperElastic3DLaw", but i cannot traceback to the law which is actually used. I only input the YOUNGS_MODULUS, DENSITY, POISSON_RATIO, and FRICTION_COEFFICIENT. Can you please guide me?

**Comment by ceulogiof** [comment]
Hey @UmarSaeedMalik, the `HyperElastic3DLaw` is a NeoHookean law in 3D. If you want more options, you might need to set up your simulation using GiD. For instance, other options available are `HyperElasticPlaneStrain2DLaw`,  `KirchhoffSaintVenant3DLaw`, `KirchhoffSaintVenantPlaneStrain2DLaw` and `KirchhoffSaintVenantPlaneStress2DLaw`
Also in the [wiki](https://github.com/KratosMultiphysics/Kratos/wiki/%5BKratosStructuralMechanicsAPI%5D-Constitutive-laws-in-Structural-Mechanics-Application#hyperelasticity) there is some background info.
