### ISSUE TITLE
Small fixes in response function

### ISSUE THREAD

**Issue by dbaumgaertner** [KratosMultiphysics/Kratos#985]
In "consider_discretization":
1) include number of geometry nodes
2) Move function to base class "response_function.h"

**Comment by RiccardoRossi** [comment]
guys, is this still open? if not please close (we need some cleaning up of the issues)

**Comment by armingeiser** [comment]
Yes is still open, i have to fix this soon

**Comment by RiccardoRossi** [comment]
is this done?

**Comment by armingeiser** [comment]
not yet unfortunately

**Comment by philbucher** [comment]
can we close this?
