### ISSUE TITLE
method PointLocalCoordinates of base geometry fails in 2D

### ISSUE THREAD

**Issue by rubenzorrilla** [KratosMultiphysics/Kratos#987]
as can be seen in 
https://github.com/KratosMultiphysics/Kratos/blame/master/kratos/geometries/geometry.h#L880

the method fails for a type mismatch in 2D.

@roigcarlo @iiaconeta, @RiccardoRossi tells that he thinks that you corrected this locally. Can u verify?

**Comment by iiaconeta** [comment]
Hi @rubenzorrilla. Yes it is true. @roigcarlo corrected this error locally.

**Comment by roigcarlo** [comment]
Yep but we did not upload it and I no longer have the fix :S

**Comment by roigcarlo** [comment]
Let me take a look at it later

**Comment by loumalouomega** [comment]
Can we close this?

**Comment by roigcarlo** [comment]
No, still not solved

**Comment by rubenzorrilla** [comment]
@roigcarlo Did we finally fix this?

**Comment by roigcarlo** [comment]
Not yet, probably tomorrow
