### ISSUE TITLE
[Core] Problem when running same time step with smaller dt

### ISSUE THREAD

**Issue by ddiezrod** [KratosMultiphysics/Kratos#9870]
**Description**
We are including what we call "roll back" in our structural solver inside the altair. The idea is simply that if SolveSolutionStep does not converge we reduce the time step in half and try again.
The problem we have is that when we reduce the time step and call InitializeSolutionStep for the next try, it is actually not doing anything as the flag mSolutionStepIsInitialized is true at that moment:

see https://github.com/KratosMultiphysics/Kratos/blob/3acacff20d1d0c815d85310c2dc58d75dab1b463/kratos/solving_strategies/strategies/residualbased_newton_raphson_strategy.h#L797

I am not sure why this flag is there, it seems its being there since the very beginning, but I think it could be removed. The only use I see of this flag is that we avoid calling InitializeSolutionStep twice when we call the Predict later. But in principle, I think we can consider that these functions are completely separated, removing the call to InitializeSolutionStep that is inside the Predict, so the flag is no longer needed.

Maybe there are some dark reasons to keep as it is right now, but in my opinion removing the flag would make it cleaner (and also would solve my problem : D )

@KratosMultiphysics/technical-committee @KratosMultiphysics/implementation-committee

**Comment by ddiezrod** [comment]
Exactly  @miguelmaso ! Thanks a lot for the explanation so everybody can get it more easily ;)

**Comment by loumalouomega** [comment]
This remembers me the old subject of the adaptive Newton Raphson and the adaptive remeshing. 

BTW: https://github.com/KratosMultiphysics/Kratos/pull/4558

**Comment by rubenzorrilla** [comment]
I also think that at this point the flag makes not so much sense. I agree with @ddiezrod observation about assuming that `InitializeSolutionStep` and `Predict` are always called independently.

With regard to the FSI, changes shouldn't affect as the `InitializeSolutionStep` and `Predict` are called once and independently.

**Comment by ddiezrod** [comment]
I created the MR with the proposed changes, CI passed correctly.
