### ISSUE TITLE
Stepped/ Staged Study - Contact Mechanics - Structural Mechanics

### ISSUE THREAD

**Issue by UmarSaeedMalik** [KratosMultiphysics/Kratos#9893]
Hello, 

I am trying to perform a dynamic contact study between two cubic blocks where first I apply an increasing normal force and after a certain time, while keeping the normal force constant, i apply an increasing horizontal displacement. So, there are two steps/stages of the study. A normal force part and then the horizontal displacement part. 

I encounter various problems during the horizontal disp part, so I have to run the simulation again and again to experiment different things. However, my normal force part of the study works fine. Therefore, to save time, i don't want to run that part everytime i run the simulation. I want to save the solution till this first part and then run the simulation from this time step by initializing the saved values.

Has somebody performed such a study where they divide the whole study to two or more steps? 

Please let me know if you have some experience on how to do this.

Kind regards.

**Comment by rubenzorrilla** [comment]
Hi @UmarSaeedMalik!

The restart mechanism can be used for this. The `StructuralMechanicsApplication` supports it, so, as far as I understand, the `ContactStructuralMechanicsApplication` should do so as well. Maybe @loumalouomega can give some more details about. There is a `test_restart.py` in `kratos/tests` explaining how to use the restart save and load.

**Comment by loumalouomega** [comment]
I have never used restart with contact, so maybe it requires some adjustments

**Comment by rubenzorrilla** [comment]
Most probably the @KratosMultiphysics/structural-mechanics team can provide a more precise answer to this, but if there is already a restart test in the application I'd follow that one as reference.

In any case, note @loumalouomega 's comment, maybe there are still some pending things to be done in order to make it work in combination with contact.

**Comment by philbucher** [comment]
> Can you please let me know what is the difference b/w restart_tests.py in applications/StructuralMechanicsApplication/tests/ and test_restart.py in kratos/tests?

the former runs complete structural cases with and without restart and compares the results

the latter tests the basic restart functionalities in Kratos
