### ISSUE TITLE
Compiling Kratos only get 3 Applications

### ISSUE THREAD

**Issue by glanzkaiser** [KratosMultiphysics/Kratos#9924]
**Description**
I compile Kratos v9.1 and I only get 3 applications, while in the src directory there are a lot of applications that are not built or installed

**Scope**
Where in Kratos is this bug happening. 
E.g.
- Build directory
- Installed bin/Release

**Environment**
Please specify your operating system, kratos branch, python version or any other library versions that you consider relevant.
E.g.:
- OS: GFreya OS (I create it with base from Linux From Scratch book a Linux  / GNU, I do not use package manager)
- Branch: v 9.1
- Python 3.9.6

This are my screenshots:
https://ibb.co/6XYc68k
https://ibb.co/0JCQfdn

**Comment by loumalouomega** [comment]
Can you show us the configure script?

**Comment by loumalouomega** [comment]
>     * OS: GFreya OS (I create it with base from Linux From Scratch book a Linux  / GNU, I do not use package manager)

OMG

![imagen](https://user-images.githubusercontent.com/19991680/170215636-9ee39866-8bbf-4d50-9d1e-2f7fa4683268.png)
![imagen](https://user-images.githubusercontent.com/19991680/170215689-8b080cce-9e5b-4168-9149-6f767deb19cf.png)

**Comment by glanzkaiser** [comment]
I also attach my ccmake configuration

maybe the ccmake configuration can give us clue

haha, I know that meme. Linux From Scratch is not that difficult there is Kernotex tutorial that we can follow

https://ibb.co/R0ZYwYW
https://ibb.co/KhM4gjW

**Comment by loumalouomega** [comment]
You need to add more applications, example:

~~~sh
# Set applications to compile
export KRATOS_APPLICATIONS=
add_app ${KRATOS_APP_DIR}/LinearSolversApplication
add_app ${KRATOS_APP_DIR}/StructuralMechanicsApplication
add_app ${KRATOS_APP_DIR}/ConstitutiveLawsApplication
add_app ${KRATOS_APP_DIR}/ContactStructuralMechanicsApplication
add_app ${KRATOS_APP_DIR}/FluidDynamicsApplication
add_app ${KRATOS_APP_DIR}/MeshingApplication
add_app ${KRATOS_APP_DIR}/ParticleMechanicsApplication
add_app ${KRATOS_APP_DIR}/ConvectionDiffusionApplication
add_app ${KRATOS_APP_DIR}/CSharpWrapperApplication
add_app ${KRATOS_APP_DIR}/HDF5Application
add_app ${KRATOS_APP_DIR}/TrilinosApplication
add_app ${KRATOS_APP_DIR}/MetisApplication
add_app ${KRATOS_APP_DIR}/ShapeOptimizationApplication
add_app ${KRATOS_APP_DIR}/CoSimulationApplication
~~~

**Comment by glanzkaiser** [comment]
Hi all,

I wonder why there are only have 3 applications inside /Kratos-9.1/bin/Release/applications (after building the second time) ? 

in the configure.sh in /Kratos-9.1/scripts I have add the applications and install the main modules (METIS, Trilinos, etc)

Thank You.

![Kratos2](https://user-images.githubusercontent.com/72222484/172112380-354f0215-ae4a-429e-8dc4-c293fa900d08.png)


![Kratos1](https://user-images.githubusercontent.com/72222484/172112373-5cf93bcc-0217-434b-bbd5-e5d91f1d9582.png)

**Comment by Vahid-Galavi** [comment]
I have a similar problem and some applications are not installed/compiled.

**Comment by glanzkaiser** [comment]
@Vahid-Galavi 
I can't compile Kratos till 100% until today (June 15th 2022) even after dropping a lot of applications only try to install 5 applications.

This is the centralize discussion of my story and errors on compiling Kratos:
[Kratos-Compiling](https://github.com/KratosMultiphysics/Kratos/issues/9945)
