### ISSUE TITLE
Deprecation warnings in core due to LockObject's move constructor

### ISSUE THREAD

**Issue by EduardGomezEscandell** [KratosMultiphysics/Kratos#9929]
**Description**
There is one last compilation warning in the Kratos Core. It is raised in two diferent places, both because they use the move constructor of LockObject, which is marked deprecated:
https://github.com/KratosMultiphysics/Kratos/blob/629db7132a30f900048e0bc14e4f5b17e33d4456/kratos/includes/lock_object.h#L58-L68

First warning (line 63):

https://github.com/KratosMultiphysics/Kratos/blob/629db7132a30f900048e0bc14e4f5b17e33d4456/kratos/includes/chunk.h#L62-L70

Second warning:

https://github.com/KratosMultiphysics/Kratos/blob/629db7132a30f900048e0bc14e4f5b17e33d4456/kratos/includes/thread_fixed_size_memory_pool.h#L65

This is deep within Kratos and I don't really know what these do, so I'll refrain from touching anything myself.

**Scope**
- Compilation
- KratosCore

**To Reproduce**
Compile from scratch

**Expected behavior**
No warning.

**Environment**
- OS: Ubuntu 22.04 LTS x86_64
- Branch: master
- Compiler: Both gcc and clang

**Comment by philbucher** [comment]
This one is on @pooyan-dadvand to refactor the MemPool

ping @pooyan-dadvand

**Comment by pooyan-dadvand** [comment]
hmmm, I fixed this. The question would be where is the fix. Let me check.

**Comment by pooyan-dadvand** [comment]
Created the PR for the memory pool
