### ISSUE TITLE
Kratos standard-configure.sh Problem with DelaunayMeshingApplications 

### ISSUE THREAD

**Issue by glanzkaiser** [KratosMultiphysics/Kratos#9942]
I run standard-configure.sh at Kratos/scripts

then I got an error (see attachment below), I see the Kratos/external-libraries has triangle folder / library in it.

What was wrong? How to fix this?

Thank You
![Bildschirmfoto_2022-06-06_15-02-01](https://user-images.githubusercontent.com/72222484/172120855-a9209520-4d50-4d09-88d9-560594112b05.png)

**Comment by glanzkaiser** [comment]
I have solved that by adding this at standard-configure.sh :
**-DUSE_TRIANGLE_NONFREE_TPL=ON**

Now there is another error :
(I add TRILINOS_INCLUDE_DIR and TRILINOS_LIBRARY_DIR to my env vars and still not working, I even add 
**-DTRILINOS_ROOT=<path to Trilinos install dir>**

![Bildschirmfoto_2022-06-06_16-28-23](https://user-images.githubusercontent.com/72222484/172134675-c5c381ce-ef26-4f85-a7e5-b55e8cceab3a.png)

**Comment by roigcarlo** [comment]
Hi @glanzkaiser 

Some of the components you are trying to compile have specific compilation flags and dependencies, which should be documented in the app README.md. (I also subscribe to my college words in #9945, we do not recommend to compile Kratos with all applications)

In regards on the specific problems you have shown here:
For the Kernel modules and the MPI ones, you can find the info about the flags and how to enable/disable them in:
- https://github.com/KratosMultiphysics/Kratos/blob/master/INSTALL.md
- https://github.com/KratosMultiphysics/Kratos/blob/master/applications/MetisApplication/README.md
- https://github.com/KratosMultiphysics/Kratos/blob/master/applications/TrilinosApplication/README.md
- 
Particularly, for METIS, the `METIS_INCLUDE_DIR` should point to the location of METIS (version 5 or above) which you can found in http://glaros.dtc.umn.edu/gkhome/metis/metis/overview, or in the package manager of your linux distribution.

Same thing with Trilinos. You will be asked for `TRILINOS_ROOT`, which you can find in https://trilinos.github.io/ or in your distro package manager as well.

If you are familiar with docker environments, you can find an example on an image which have these and other dependencies installed in https://github.com/KratosMultiphysics/Kratos/blob/master/scripts/docker_files/docker_file_ci_ubuntu_20_04/DockerFile.

As a comment, please consider compiling Kratos without using the root user (unless you really need to), as it may cause problems when loading libraries in execution time.

**Comment by glanzkaiser** [comment]
Hi @roigcarlo,

I ask at another forum, and then I have found out on the TRILINOS_INCLUDE_DIR:

**Comment by roigcarlo** [comment]
@glanzkaiser Glad It works! I will close this issue so we can have all problems centralized in #9945
