### ISSUE TITLE
[FluidDynamics] Problem with the Hydrostatic Component when applying outlet pressure

### ISSUE THREAD

**Issue by joaquinirazabal** [KratosMultiphysics/Kratos#9946]
**Description**
I am adapting the FreeSurfaceApplication to use the Kratos and FluidDynamics processes. For us, it would be very interesting to have the possibility of imposing the hydrostatic pressure both in the inlet and in the outlet. When I use the available process in the FluidDynamicsApplication for such purpose, the pressure in the boundaries is the double of the expected one. This is happening with the changes I made in the FreeSurfaceApplication (I think they are right).

Setting to zero the variable min_proj in apply_outlet_process.py works in my case, however, I do not know if it is correct for every situation. I attach a picture of how it is working.

![ImposePress](https://user-images.githubusercontent.com/25591219/172586929-dddb5cc5-3b9c-4b88-9568-f1119a3e858d.png)

**Comment by joaquinirazabal** [comment]
Digging a bit more into the code, I realized that the appropriate change could be:
From: min_proj = min(min_proj, body_force_proj)
To: min_proj = -min(min_proj, -body_force_proj)
As body_force_proj is (most of the time) negative.

**Comment by rubenzorrilla** [comment]
Hi @joaquinirazabal. Thanks for reporting. At first glance I see that the initialization shouldn't be done with 0.0 as we're checking for the min value. An arbitrary large number should be used instead (e.g. `1.0e16`). Can you try if this solves your problem?

I think we cannot assume that body force is always negative...

**Comment by joaquinirazabal** [comment]
Hi @rubenzorrilla, let's see I am understanding this properly. If we are trying to impose the hydrostatic pressure, we should tell to the process the upper point (h_top) where the pressure is zero, as I show in the sketch.

![bitmap](https://user-images.githubusercontent.com/25591219/173013570-c59ad08e-328a-49bc-b13d-ae8423062bea.png)

In this simple case, the parameter min_proj is not needed (in fact, it is increasing the pressure incorrectly). It will be enough to calculate the hydrostatic pressure like this:
hyd_pres = rho*body_force_norm*(self.h_top + body_force_proj)

Thank you for taking a look!

**Comment by joaquinirazabal** [comment]
> Digging a bit more into the code, I realized that the appropriate change could be: From: min_proj = min(min_proj, body_force_proj) To: min_proj = -min(min_proj, -body_force_proj) As body_force_proj is (most of the time) negative.

This is not right, of course.

**Comment by rubenzorrilla** [comment]
> Hi @rubenzorrilla, let's see I am understanding this properly. If we are trying to impose the hydrostatic pressure, we should tell to the process the upper point (h_top) where the pressure is zero, as I show in the sketch.
> 
> ![bitmap](https://user-images.githubusercontent.com/25591219/173014618-54a0ce2f-0784-4b32-bb1a-1660ac1fc475.png)
> 
> In this simple case, the parameter min_proj is not needed (in fact, it is increasing the pressure incorrectly). It will be enough to calculate the hydrostatic pressure like this: hyd_pres = rho * body_force_norm * (self.h_top + body_force_proj)
> 
> Thank you for taking a look!

About your sketch, in this specific case `h_top` would be zero. `h_top` refers to the height above the top point in case a trapezoidal pressure distribution is to be used. I've the feeling that this might be the source of the issues you're experiencing.

With regard to the `min_proj`, we cannot get rid of it. The point is to find the origin value in those cases in which the outlet is not a straight plane (we could admittedly calculate it better as pointed in my previous post).

**Comment by joaquinirazabal** [comment]
This works perfectly, thank you for your help, @rubenzorrilla
