### ISSUE TITLE
[Lapack and Trilinos] Newer versions and compatibility

### ISSUE THREAD

**Issue by mpentek** [KratosMultiphysics/Kratos#9947]
**Description**
On our cluster systems we are using these versions:

- Lapack 3.9.0 (Nov 2019)
- Trilinos 12.14.1 (circa 2019)

**Scope**
What combination of more recent versions would work (compatibility, performance)?

The newest available versions are:
- Lapack 3.10.1 (April 2022)
- Trilinos 13.2.0 (Oct 2021)

**Comment by roigcarlo** [comment]
Personaly no idea about performance.

About compat:
New lapack should give no problems as far as I know.
I am not sure about Trilinos, maybe someone from @KratosMultiphysics/mpi or @marandra has used that version?

**Comment by mpentek** [comment]
I can confirm that the latest configuration works (Lapack 3.10.1 + Trilinos 13.2.0). I tested it on 2 of our supercomputing systems. These run the following operating system: SUSE Linux Enterprise Server 15 SP3.

**Comment by marandra** [comment]
We recently compiled latest Kratos with the following versions of components:

- Trilinos (13.2.0 I think, current master branch in Github)
- METIS and GKlib (current master branch in Github)
- Lapack from MKL 2021.4.0.
- Intel MPI 2021.4.0
- Intel compilers 2021.4.0
- Red Hat Enterprise Linux 8.4.

Compilation of Trilinos, METIS and GKlib is a bit tricky, but in the end it works. Not sure about performance difference with respect to older versions though.

**Comment by philbucher** [comment]
@marandra could you please post your config files for the problematic components for future reference? That might help a lot, esp for Trilinos
Thx!

**Comment by marandra** [comment]
Hi @philbucher 

I created a [wikipage](https://github.com/KratosMultiphysics/Kratos/wiki/Compiling-Kratos-with-MPI-support) with some guidelines on how to compile Kratos with MPI support. I am trying to generalize the instructions, so there may still be some issues, but I will keep on reviewing and updating the info as I fix them.

I am also submitting a PR with a link to the wikipage in the INSTALL.md page.
