### ISSUE TITLE
[core][VTK] numbers <e-40 cause issues in ascii format

### ISSUE THREAD

**Issue by pablobecker** [KratosMultiphysics/Kratos#9969]
**Description**

Scalar variables in kratos are double. This means that the  smallest number is E-307. However, when the vtk files are created , the scalar ( and vectorial) variables are labeled as type float (see https://github.com/KratosMultiphysics/Kratos/blob/master/kratos/input_output/vtk_output.cpp#L937 ) . This means that the smallest number supported is E-38  . When a vectorial var that contains values lower than E-38 is written in ascii format, Paraview is unable to read these numbers outside the float range and throws an error.

I did not directly create a PR to fix this because I assume there were reasons to declare these variables as float ( RAM maybe?). So my proposal would be to cast the numbers to float before printing them. (note that this happens also for scalar vars, but for some reason paraview reads them without issues. Nodal positions are also affected.

**Scope**

Kratos Core , VTK output with ASCII mode in VECTOR variables (e.g. VELOCITY)

**To Reproduce**

In the VELOCITY variable, assign values smaller than 1e-38 and try to read them in Paraview. An error will be returned.

**Expected behavior**

Paraview should open the file correctly, results are good.

**Environment**
- OS: Windows

**Comment by loumalouomega** [comment]
Legacy VTK supports double, I assume we used float to make resulting files lighter. We can add a flag to manually set to double or change current behaviour to double by default

**Comment by pablobecker** [comment]
IMO we can keep it as float, but the cast should be done correctly

**Comment by loumalouomega** [comment]
> IMO we can keep it as float, but the cast should be done correctly

A priori there is a cast:

https://github.com/KratosMultiphysics/Kratos/blob/66c3b2dfa3b7257bd2b74676f9d86375c329d26d/kratos/input_output/vtk_output.cpp#L820

And the solution may be manually filter values to avoid values beyond the bound of the float

**Comment by pablobecker** [comment]
not for vectors in ascii format!
https://github.com/KratosMultiphysics/Kratos/blob/66c3b2dfa3b7257bd2b74676f9d86375c329d26d/kratos/input_output/vtk_output.h#L436
