### ISSUE TITLE
windows compilation errors

### ISSUE THREAD

**Issue by ZhimingGuo** [KratosMultiphysics/Kratos#9971]
**Description**
There were several errors when I compiling kratossolidmechanics under windows system.

**Scope**
- Compilation
- KratosSolidMechanicsCore
- KratosSolidMechanicsApplication
![errors](https://user-images.githubusercontent.com/26964544/174480804-bed59895-401c-48f3-a58c-f47c55eae9be.png)

**Comment by RiccardoRossi** [comment]
can u post details of ypur compiler setup?

**Comment by ZhimingGuo** [comment]
@echo off
rem Please do not modify this script

rem For any question please contact with us in:
rem  - https://github.com/KratosMultiphysics/Kratos

rem Optional parameters:
rem You can find a list will all the compiation options in INSTALL.md or here:
rem  - https://github.com/KratosMultiphysics/Kratos/wiki/Compilation-options

rem Set compiler
set CC=cl.exe
set CXX=cl.exe

rem Set variables
if not defined KRATOS_SOURCE set KRATOS_SOURCE=C:\Programs\Kratos
if not defined KRATOS_BUILD set KRATOS_BUILD=%KRATOS_SOURCE%/build

rem Warning: In windows this option only works if you run through a terminal with admin privileges
rem set KRATOS_INSTALL_PYTHON_USING_LINKS=ON

rem Set basic configuration
if not defined KRATOS_BUILD_TYPE set KRATOS_BUILD_TYPE=Release
if not defined BOOST_ROOT set BOOST_ROOT=C:\boost_1_75_0
if not defined PYTHON_EXECUTABLE set PYTHON_EXECUTABLE=C:\Windows\py.exe

rem Set applications to compile
set KRATOS_APP_DIR=applications
set KRATOS_APPLICATIONS=
CALL :add_app %KRATOS_APP_DIR%\LinearSolversApplication;
CALL :add_app %KRATOS_APP_DIR%\StructuralMechanicsApplication;
CALL :add_app %KRATOS_APP_DIR%\FluidDynamicsApplication;
CALL :add_app %KRATOS_APP_DIR%\MeshMovingApplication;
CALL :add_app %KRATOS_APP_DIR%\FSIApplication;
CALL :add_app %KRATOS_APP_DIR%\SolidMechanicsApplication;

rem Clean
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\cmake_install.cmake"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeCache.txt"
del /F /Q "%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%\CMakeFiles"

rem Enable this if your build is slow and you have a multi-core machine
rem set KRATOS_PARALLEL_BUILD_FLAG=/MP4

rem Configure
@echo on
cmake -G"Visual Studio 15 2017" -A x64 -H"%KRATOS_SOURCE%" -B"%KRATOS_BUILD%\%KRATOS_BUILD_TYPE%"  ^
-DUSE_EIGEN_MKL=OFF        ^
-DCMAKE_CXX_FLAGS=" %KRATOS_PARALLEL_BUILD_FLAG% "

rem Build
cmake --build "%KRATOS_BUILD%/%KRATOS_BUILD_TYPE%" --target install -- /property:configuration=%KRATOS_BUILD_TYPE% /p:Platform=x64
goto:eof

rem Function to add apps
:add_app
set KRATOS_APPLICATIONS=%KRATOS_APPLICATIONS%%1;
goto:eof

**Comment by ZhimingGuo** [comment]
The foregoing is configre file i used to make windows compilation project. Those errors appear in configure process firstly.
Then I use Visual studio 2017 to do compilation with release, the errors still be there.

**Comment by RiccardoRossi** [comment]
charlie any hint? donwe need a special update for vs?

**Comment by roigcarlo** [comment]
Hi @ZhimingGuo,

I will take a look but it seems to be a problem  in the code.

@josep-m-carbonell do you know if there is some pending PR regarding overrides from your side?

**Comment by roigcarlo** [comment]
Hi, I can conform the problems are from the Solid/ConstitutiveModels. For now the only thing I can recommend is to comment this line:

CALL :add_app %KRATOS_APP_DIR%\SolidMechanicsApplication;

Once we have the errors fixed I will ping you so you can re-enable.

**Comment by ZhimingGuo** [comment]
ok, thanks!
