### ISSUE TITLE
Viscous Generalized Maxwell (G.M) Law with HyperElastic (H.E) Law as base class - Structural Mechanics

### ISSUE THREAD

**Issue by UmarSaeedMalik** [KratosMultiphysics/Kratos#9977]
Hello,

I am trying to use Viscous Generalized Maxwell (G.M) law with a user defined (Mooney Rivlin) HyperElastic (H.E) Law instead of the default Linear Isotropic law.

With finite strains (HyperElastic law), when I run it, my simulation doesn't even perform the 1st iteration and crashes, so I am assuming there is a problem in my implementation. 

It is important to mention that I already changed the base class of G.M law from Linear Isotropic to my HyperElastic law in the law itself, in "constitutive_laws_application.h" and "add_custom_constitutive_laws_to_python.cpp", so that should not be a problem.

I suspect that the problem has more to do with the difference in the formulation of finite and small strains and thus stresses in the G.M law file because originally, it is developed for small strains.

Suspecting that there might be a problem with my H.E law, i also tried to use the already existing Neohookean and Kirchhoff laws as a base class for the G.M law but still no luck.

Has anybody tried to use the G.M law with a finite strain law like the Isotropic_Kirchhoff or Isotropic Neohhokean law?

Your help would be much appreciated.

Have a nice day!

Best,
Umar

**Comment by loumalouomega** [comment]
@AlejandroCornejo FYI

**Comment by AlejandroCornejo** [comment]
Hi guys!
Sorry for my delay, I'm on vacation now hehe.

Regarding the maxwell, when I implemented it I was only thinking in small strains. This means that if a hyper elastic cl is used then one must be careful with the use provided strain stuff. 

I think that you should compute from an F, an equivalent strain (green Lagrange) and then perform the generalized maxwell.
