### ISSUE TITLE
RuntimeError: Error: Kratos components missing "HyperElastic3DLaw"

### ISSUE THREAD

**Issue by ggiraldo** [KratosMultiphysics/Kratos#9980]
**Description**
This error is thrown when running Kratos examples which include hyperelastic materials:

`RuntimeError: Error: Kratos components missing "HyperElastic3DLaw"`

**Scope**
Structural Mechanics Application with contacts

**To Reproduce**
Run a simulation using the StructuralMechanicsAnalysis with "HyperElastic3DLaw" constitutive law (examples taken from the contact_structural_mechanics cases here https://github.com/KratosMultiphysics/Examples/tree/master/contact_structural_mechanics)

**Expected behavior**
The case runs successfully and the results presented in the example page are reproduced.

**Environment**

- OS: Windows 11
- Kratos version: Latest from pip
- Python 3.9.13

**Comment by ggiraldo** [comment]
I understood that the pip command would install a pre-compiled version.

Is this version intended to not be complete? In other words, is this not a bug?

**Comment by rubenzorrilla** [comment]
`pip install KratosMultiphysics-all` comes with the main functionalities of Kratos but not all of them. In order to use the NeoHookean model you need to also do `pip install KratosConstitutiveLawsApplication`.

For the next release we will enhance the `all` package. This one will be probably include it. Sorry for the inconveniences.

**Comment by ggiraldo** [comment]
Thanks Ruben for the explanation, please consider to at least mention it in the installation instructions for pip!

The command `pip install KratosConstitutiveLawsApplication` threw an error about the package requiring KratosMultiphysics==9.1.2 while I had v9.1.3.

Explicitly installing KratosMultiphysics-all==9.1.2 and KratosConstitutiveLawsApplication==9.1.2 allowed me to run the case, although I still received an error about Scipy and Numpy versions. 

I guess I should do a virtual environment, please consider to suggest this in the installation instructions!

**Comment by rubenzorrilla** [comment]
> Thanks Ruben for the explanation, please consider to at least mention it in the installation instructions for pip!
> 
> The command `pip install KratosConstitutiveLawsApplication` threw an error about the package requiring KratosMultiphysics==9.1.2 while I had v9.1.3.
> 
> Explicitly installing KratosMultiphysics-all==9.1.2 and KratosConstitutiveLawsApplication==9.1.2 allowed me to run the case, although I still received an error about Scipy and Numpy versions.
> 
> I guess I should do a virtual environment, please consider to suggest this in the installation instructions!

Hi @ggiraldo. Many thanks for the feedback. Indeed, I went into the same issues a few days ago in a student's machine :facepalm: . What we decided is to include (almost) everything into the `all` package despite it gets a bit large.

**Comment by rubenzorrilla** [comment]
@roigcarlo FYI

Closing the issue as it seems to be solved. @ggiraldo feel free to reopen if required.
