### ISSUE TITLE
Composite material

### ISSUE THREAD

**Issue by mnabi** [KratosMultiphysics/Kratos#9986]
**Composite material**

I wonder whether composite material is added to Kratos Stractural Mechanics, and whether it works properly (if exist)?

Thank you in advance

**Scope**
Structural Mechanics
- KratosCore

**Comment by SergioJimenezReyes** [comment]
@mnabi we are studying composite materials through the Rule of Mixtures and the Serial Parallel Rule of Mixtures which are implemented in the ConstitutiveLawsApplication (which is dependent of the Structural Mech Application). We have used it for quite long time and works fine.

**Comment by AlejandroCornejo** [comment]
Can we close this? Is it solved @mnabi ?

**Comment by rubenzorrilla** [comment]
Closing as it seems to be inactive. @mnabi feel free to reopen if required.
