### ISSUE TITLE
CMake Error at CMakeLists.txt:574  (KRATOS)

### ISSUE THREAD

**Issue by LVilla96** [KratosMultiphysics/Kratos#9987]
GOOD DAY!!
I'm having trouble compiling KRATOS
I'm using:

Python 3.8.1
cmake-3.16.3
boost_1_71_0

 powershell outputs are:

WARNING: YOUR GIDPOST IS BEING COMPILED  WITHOUT DEBUG (ALL ASSERTS WILL BE AVOIDED)
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Configuring applications (ENV):
Adding application '/home/engineer-user/Kratos/scripts/../applications/LinearSolversApplication'
**** configuring KratosLinearSolversApplication ****
Adding application '/home/engineer-user/Kratos/scripts/../applications/StructuralMechanicsApplication'
**** configuring KratosStructuralMechanicsApplication ****
Adding application '/home/engineer-user/Kratos/scripts/../applications/FluidDynamicsApplication'
**** configuring KratosFluidDynamicsApplication ****
Adding application '/home/engineer-user/Kratos/scripts/../applications/ExternalSolversApplication'
CMake Error at CMakeLists.txt:574 (add_subdirectory):
  add_subdirectory given source
  "/home/engineer-user/Kratos/scripts/../applications/ExternalSolversApplication"
  which is not an existing directory.

Adding application '/home/engineer-user/Kratos/scripts/../applications/PfemFluidDynamicsApplication'
**** configuring KratosPfemFluidDynamicsApplication ****
-- [Info] Adding dependency DelaunayMeshingApplication
**** configuring KratosDelaunayMeshingApplication ****
-- Tetgen found in /home/engineer-user/Kratos/applications/DelaunayMeshingApplication/external_libraries/tetgen
Adding application '/home/engineer-user/Kratos/scripts/../applications/DEMApplication'
**** configuring KratosDEMApplication ****
Adding application '/home/engineer-user/Kratos/scripts/../applications/ConstitutiveLawsApplication'
**** configuring KratosConstitutiveLawsApplication ****
[Warning] Application '/home/engineer-user/Kratos/scripts/../applications/DelaunayMeshingApplication' was already added

***********************************************************************

        LIST OF APPLICATIONS THAT ARE GOING TO BE COMPILED:

        LinearSolversApplication
        StructuralMechanicsApplication
        FluidDynamicsApplication
        ExternalSolversApplication
        PfemFluidDynamicsApplication
        DEMApplication
        ConstitutiveLawsApplication
        DelaunayMeshingApplication

        APPLICATIONS ADDED TO COMPILATION THROUGH DEPENDENCIES:

***********************************************************************

List of upcoming API-breaking and behavior changes:
Geometry old projection methods deprecation: https://github.com/KratosMultiphysics/Kratos/pull/9024
Geometry old closest point methods deprecation: https://github.com/KratosMultiphysics/Kratos/pull/9243
Model 'CreateModelPart' behavior change (no error thrown if model part exists): https://github.com/KratosMultiphysics/Kratos/pull/9598
Make GetIntegrationMethod method of Condition const: https://github.com/KratosMultiphysics/Kratos/pull/9769
-- triangle : /home/engineer-user/Kratos/external_libraries/triangle
-- tinyexpr : /home/engineer-user/Kratos/external_libraries/tinyexpr/tinyexpr/
python libraries to be installed are: /usr/lib/x86_64-linux-gnu/libpython3.8.so.1.0
-- Configuring incomplete, errors occurred!
See also "/home/engineer-user/Kratos/build/Release/CMakeFiles/CMakeOutput.log".
make: *** No hay ninguna regla para construir el objetivo 'install'.  Alto.

I appreciate you can help me

**Comment by loumalouomega** [comment]
@roigcarlo FYI

**Comment by sunethwarna** [comment]
Could you try removing `ExternalSolversApplication` and putting `LinearSolversApplication` instead?

**Comment by LVilla96** [comment]
> Could you try removing `ExternalSolversApplication` and putting `LinearSolversApplication` instead in the configure.bat file?

Thanks, it´s work

**Comment by sunethwarna** [comment]
Closing since it is solved. Feel free to re-open if there are any other errors @LVilla96.
