### ISSUE TITLE
Caution on branch naming

### ISSUE THREAD

**Issue by jginternational** [KratosMultiphysics/Kratos#9996]
**Description**
2 branches with same name can work on Linux but will crash on Windows.
Windows is case sensitive, so this 2 branches are the same, and causes git to crash on Windows:
- PfemFluid/RefiningBoxes
- PfemFluid/refiningBoxes

**Scope**
- git pull

**Environment**
Windows
![image](https://user-images.githubusercontent.com/5918085/177135482-b1186d9c-2ebf-4fa3-95d4-8ffb6160736d.png)

![image](https://user-images.githubusercontent.com/5918085/177135541-1c607aa3-5e97-401e-bcf6-2c0370919a1e.png)

**Comment by pooyan-dadvand** [comment]
All branch names should be lower case as [style guide](https://github.com/KratosMultiphysics/Kratos/wiki/Style-Guide) says.

**Comment by jginternational** [comment]
I'm removing the branch of @miguelmaso since it has no commits pushed.
You will need to rename the branch @miguelmaso . Call it PfemFluid/refining-boxes

**Comment by miguelmaso** [comment]
> I'm removing the branch of @miguelmaso since it has no commits pushed. You will need to rename the branch @miguelmaso . Call it PfemFluid/refining-boxes

sorry, but I'm not the author of that branch. Someone created it after I merged a PR
