### ISSUE TITLE
Tests of shape functions second derivatives

### ISSUE THREAD

**Issue by jgonzalezusua** [KratosMultiphysics/Kratos#9998]
**Description**
In the formulation I am working, I would like to use the quadratic elements that are in KratosMultiphysics, for example, `quadrilateral_2d_8.h`. I saw that there is a function called `ShapeFunctionsSecondDerivatives` but I have not found any test that checks if it is well implemented. In the case of `ShapeFunctionsValues` or `ShapeFunctionsLocalGradients` functions are tested in `test_quadrilateral_2d_8.cpp`. My question is the following:

- Is there any test which checks that the second derivatives of the shape functions are well implemented? 

**Scope**
Kratos geometry
- Testing

**Comment by pooyan-dadvand** [comment]
These shape functions are implemented long before we start to have unit testing in Kratos. During these years we added tests for the ones we use most but unfortunately these are left without test. It would be great if you could add test for them.

**Comment by jgonzalezusua** [comment]
In #10014 I have proposed a test for the second derivatives.

**Comment by jgonzalezusua** [comment]
Solved in #10014
