### ISSUE TITLE
[DEM] Adding external created contacts to simulation

### ISSUE THREAD

**Issue by flacko89** [KratosMultiphysics/Kratos#9999]
**Description**
I was wondering if there is the possibility to add externally created contacts to a DEM simulation. I'm trying to compare results with another code and therefore I need exactly the same contact network. 

**Scope**
DEMApplication

Thanks for your help.
Christian

**Comment by pooyan-dadvand** [comment]
@KratosMultiphysics/dem

**Comment by maceligueta** [comment]
Hello @flacko89 , currently we have no option to preset the contacts, sorry. We have different ways to set them (with different search tolerances, in terms of type of search and distance extent) but not really any way which allows the direct preset of them.

**Comment by flacko89** [comment]
Ok, thanks. Do you think manipulating the neighbors list is suitable for testing and where might be the best place to do that?

**Comment by ChengshunShang1996** [comment]
Hi @flacko89 . In my opinion, it is not really necessary to manipulate the contact directly if you want to compare results with another code.  By using the same particle positions and the same [SearchTolerance]  (this parameter is used for contact/neighbor searching) in [ProjectParametersDEM.json] file, it is possible to achieve a same contact network.
